0901-   AA          TAX
0902-   AA          TAX
0903-   AA          TAX
0904-   AA          TAX
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   8D AA 20    STA   $20AA
0924-   20 20 20    JSR   $2020
0927-   20 20 20    JSR   $2020
092A-   20 20 20    JSR   $2020
092D-   20 20 20    JSR   $2020
0930-   20 20 20    JSR   $2020
0933-   20 20 20    JSR   $2020
0936-   20 20 20    JSR   $2020
0939-   20 20 20    JSR   $2020
093C-   20 20 20    JSR   $2020
093F-   20 20 AA    JSR   $AA20
0942-   8D AA 20    STA   $20AA
0945-   C1 D0       CMP   ($D0,X)
0947-   CC CC C5    CPY   $C5CC
094A-   C1 D3       CMP   ($D3,X)
094C-   CD 20 C2    CMP   $C220
094F-   D5 C9       CMP   $C9,X
0951-   CC C4 C5    CPY   $C5C4
0954-   D2 20       CMP   ($20)
0956-   D5 D4       CMP   $D4,X
0958-   C9 CC       CMP   #$CC
095A-   C9 D4       CMP   #$D4
095C-   D9 20 20    CMP   $2020,Y
095F-   20 20 20    JSR   $2020
0962-   AA          TAX
0963-   8D AA AD    STA   $ADAA
0966-   20 20 20    JSR   $2020
0969-   20 20 20    JSR   $2020
096C-   20 20 20    JSR   $2020
096F-   20 20 20    JSR   $2020
0972-   20 20 20    JSR   $2020
0975-   20 20 20    JSR   $2020
0978-   20 20 20    JSR   $2020
097B-   20 20 20    JSR   $2020
097E-   20 20 20    JSR   $2020
0981-   20 AD AA    JSR   $AAAD
0984-   8D AA 20    STA   $20AA
0987-   C3          ???
0988-   CF          ???
0989-   D0 C9       BNE   $0954
098B-   C5 D3       CMP   $D3
098D-   20 C4 C5    JSR   $C5C4
0990-   D3          ???
0991-   C9 D2       CMP   #$D2
0993-   C5 C4       CMP   $C4
0995-   20 D3 D5    JSR   $D5D3
0998-   C2          ???
0999-   D2 CF       CMP   ($CF)
099B-   D5 D4       CMP   $D4,X
099D-   C9 CE       CMP   #$CE
099F-   C5 D3       CMP   $D3
09A1-   20 20 20    JSR   $2020
09A4-   AA          TAX
09A5-   8D AA 20    STA   $20AA
09A8-   C6 D2       DEC   $D2
09AA-   CF          ???
09AB-   CD 20 C5    CMP   $C520
09AE-   CE D4 C9    DEC   $C9D4
09B1-   D2 C5       CMP   ($C5)
09B3-   20 CC C9    JSR   $C9CC
09B6-   C2          ???
09B7-   D2 C1       CMP   ($C1)
09B9-   D2 D9       CMP   ($D9)
09BB-   20 CF CE    JSR   $CECF
09BE-   D4          ???
09BF-   CF          ???
09C0-   20 C1 20    JSR   $20C1
09C3-   20 20 AA    JSR   $AA20
09C6-   8D AA 20    STA   $20AA
09C9-   C4 C5       CPY   $C5
09CB-   D3          ???
09CC-   D4          ???
09CD-   C9 CE       CMP   #$CE
09CF-   C1 D4       CMP   ($D4,X)
09D1-   C9 CF       CMP   #$CF
09D3-   CE 20 C4    DEC   $C420
09D6-   C9 D3       CMP   #$D3
09D8-   CB          ???
09D9-   AC 20 D7    LDY   $D720
09DC-   C9 D4       CMP   #$D4
09DE-   C8          INY
09DF-   20 D3 CF    JSR   $CFD3
09E2-   CD C5 20    CMP   $20C5
09E5-   20 AA 8D    JSR   $8DAA
09E8-   AA          TAX
09E9-   20 C3 D5    JSR   $D5C3
09EC-   D3          ???
09ED-   D4          ???
09EE-   CF          ???
09EF-   CD C9 DA    CMP   $DAC9
09F2-   C1 D4       CMP   ($D4,X)
09F4-   C9 CF       CMP   #$CF
09F6-   CE 20 A8    DEC   $A820
09F9-   CC C9 CB    CPY   $CBC9
09FC-   C5 20       CMP   $20
09FE-   D7          ???
09FF-   C8          INY
0A00-   C5 D4       CMP   $D4
0A02-   C8          INY
0A03-   C5 D2       CMP   $D2
0A05-   20 20 AA    JSR   $AA20
0A08-   8D AA 20    STA   $20AA
0A0B-   D4          ???
0A0C-   CF          ???
0A0D-   20 D5 D3    JSR   $D3D5
0A10-   C5 20       CMP   $20
0A12-   CD C9 CE    CMP   $CEC9
0A15-   C9 C6       CMP   #$C6
0A17-   C9 C5       CMP   #$C5
0A19-   C4 20       CPY   $20
0A1B-   D6 C5       DEC   $C5,X
0A1D-   D2 D3       CMP   ($D3)
0A1F-   C9 CF       CMP   #$CF
0A21-   CE D3 A9    DEC   $A9D3
0A24-   AC 20 20    LDY   $2020
0A27-   20 AA 8D    JSR   $8DAA
0A2A-   AA          TAX
0A2B-   20 C1 CE    JSR   $CEC1
0A2E-   C4 20       CPY   $20
0A30-   D4          ???
0A31-   C8          INY
0A32-   C5 CE       CMP   $CE
0A34-   20 C3 D2    JSR   $D2C3
0A37-   C5 C1       CMP   $C1
0A39-   D4          ???
0A3A-   C5 D3       CMP   $D3
0A3C-   20 C1 20    JSR   $20C1
0A3F-   C3          ???
0A40-   D5 D3       CMP   $D3,X
0A42-   D4          ???
0A43-   CF          ???
0A44-   CD 20 20    CMP   $2020
0A47-   20 20 AA    JSR   $AA20
0A4A-   8D AA 20    STA   $20AA
0A4D-   D4          ???
0A4E-   C5 CD       CMP   $CD
0A50-   D0 CC       BNE   $0A1E
0A52-   C1 D4       CMP   ($D4,X)
0A54-   C5 20       CMP   $20
0A56-   C6 C9       DEC   $C9
0A58-   CC C5 20    CPY   $20C5
0A5B-   C6 CF       DEC   $CF
0A5D-   D2 20       CMP   ($20)
0A5F-   D4          ???
0A60-   C8          INY
0A61-   C5 20       CMP   $20
0A63-   CE C5 D7    DEC   $D7C5
0A66-   20 20 20    JSR   $2020
0A69-   20 AA 8D    JSR   $8DAA
0A6C-   AA          TAX
0A6D-   20 D0 D2    JSR   $D2D0
0A70-   CF          ???
0A71-   CA          DEX
0A72-   C5 C3       CMP   $C3
0A74-   D4          ???
0A75-   AE 20 20    LDX   $2020
0A78-   20 20 20    JSR   $2020
0A7B-   20 20 20    JSR   $2020
0A7E-   20 20 20    JSR   $2020
0A81-   20 20 20    JSR   $2020
0A84-   20 20 20    JSR   $2020
0A87-   20 20 20    JSR   $2020
0A8A-   20 AA 8D    JSR   $8DAA
0A8D-   AA          TAX
0A8E-   20 20 20    JSR   $2020
0A91-   20 20 20    JSR   $2020
0A94-   20 20 20    JSR   $2020
0A97-   20 20 20    JSR   $2020
0A9A-   20 20 20    JSR   $2020
0A9D-   20 20 20    JSR   $2020
0AA0-   20 20 20    JSR   $2020
0AA3-   20 20 20    JSR   $2020
0AA6-   20 20 20    JSR   $2020
0AA9-   20 20 20    JSR   $2020
0AAC-   AA          TAX
0AAD-   8D AA AA    STA   $AAAA
0AB0-   AA          TAX
0AB1-   AA          TAX
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   8D AA 8D    STA   $8DAA
0AD1-   AA          TAX
0AD2-   AA          TAX
0AD3-   20 C1 D3    JSR   $D3C1
0AD6-   D3          ???
0AD7-   C5 CD       CMP   $CD
0AD9-   C2          ???
0ADA-   CC C5 D2    CPY   $D2C5
0ADD-   20 C4 C9    JSR   $C9C4
0AE0-   D2 C5       CMP   ($C5)
0AE2-   C3          ???
0AE3-   D4          ???
0AE4-   C9 D6       CMP   #$D6
0AE6-   C5 D3       CMP   $D3
0AE8-   8D AA 8D    STA   $8DAA
0AEB-   A0 C3       LDY   #$C3
0AED-   D9 C3 A0    CMP   $A0C3,Y
0AF0-   C1 D6       CMP   ($D6,X)
0AF2-   C5 8D       CMP   $8D
0AF4-   A0 C5       LDY   #$C5
0AF6-   D8          CLD
0AF7-   D0 A0       BNE   $0A99
0AF9-   CF          ???
0AFA-   C6 C6       DEC   $C6
0AFC-   8D A0 C4    STA   $C4A0
0AFF-   D3          ???
0B00-   CB          ???
0B01-   A0 C2       LDY   #$C2
0B03-   D5 C9       CMP   $C9,X
0B05-   CC C4 C5    CPY   $C5C4
0B08-   D2 8D       CMP   ($8D)
0B0A-   A0 D4       LDY   #$D4
0B0C-   D2 A0       CMP   ($A0)
0B0E-   CF          ???
0B0F-   CE 8D A0    DEC   $A08D
0B12-   CF          ???
0B13-   C2          ???
0B14-   CA          DEX
0B15-   A0 A4       LDY   #$A4
0B17-   C2          ???
0B18-   C6 C5       DEC   $C5
0B1A-   B0 8D       BCS   $0AA9
0B1C-   A0 CF       LDY   #$CF
0B1E-   D2 C7       CMP   ($C7)
0B20-   A0 A4       LDY   #$A4
0B22-   B4 B0       LDY   $B0,X
0B24-   B0 B0       BCS   $0AD6
0B26-   8D AA 8D    STA   $8DAA
0B29-   AA          TAX
0B2A-   AA          TAX
0B2B-   AA          TAX
0B2C-   AA          TAX
0B2D-   AA          TAX
0B2E-   AA          TAX
0B2F-   AA          TAX
0B30-   AA          TAX
0B31-   AA          TAX
0B32-   AA          TAX
0B33-   AA          TAX
0B34-   AA          TAX
0B35-   AA          TAX
0B36-   AA          TAX
0B37-   AA          TAX
0B38-   AA          TAX
0B39-   AA          TAX
0B3A-   AA          TAX
0B3B-   AA          TAX
0B3C-   AA          TAX
0B3D-   AA          TAX
0B3E-   AA          TAX
0B3F-   AA          TAX
0B40-   AA          TAX
0B41-   AA          TAX
0B42-   AA          TAX
0B43-   AA          TAX
0B44-   AA          TAX
0B45-   AA          TAX
0B46-   AA          TAX
0B47-   AA          TAX
0B48-   AA          TAX
0B49-   8D AA 20    STA   $20AA
0B4C-   20 20 20    JSR   $2020
0B4F-   20 20 20    JSR   $2020
0B52-   20 20 20    JSR   $2020
0B55-   20 20 20    JSR   $2020
0B58-   20 20 20    JSR   $2020
0B5B-   20 20 20    JSR   $2020
0B5E-   20 20 20    JSR   $2020
0B61-   20 20 20    JSR   $2020
0B64-   20 20 20    JSR   $2020
0B67-   20 20 AA    JSR   $AA20
0B6A-   8D AA 20    STA   $20AA
0B6D-   C8          INY
0B6E-   C5 C1       CMP   $C1
0B70-   C4 C5       CPY   $C5
0B72-   D2 AC       CMP   ($AC)
0B74-   20 C8 CF    JSR   $CFC8
0B77-   CF          ???
0B78-   CB          ???
0B79-   D3          ???
0B7A-   20 C1 CE    JSR   $CEC1
0B7D-   C4 20       CPY   $20
0B7F-   CD C1 C3    CMP   $C3C1
0B82-   D2 CF       CMP   ($CF)
0B84-   D3          ???
0B85-   20 20 20    JSR   $2020
0B88-   20 20 AA    JSR   $AA20
0B8B-   8D AA 20    STA   $20AA
0B8E-   20 20 20    JSR   $2020
0B91-   20 20 20    JSR   $2020
0B94-   20 20 20    JSR   $2020
0B97-   20 20 20    JSR   $2020
0B9A-   20 20 20    JSR   $2020
0B9D-   20 20 20    JSR   $2020
0BA0-   20 20 20    JSR   $2020
0BA3-   20 20 20    JSR   $2020
0BA6-   20 20 20    JSR   $2020
0BA9-   20 20 AA    JSR   $AA20
0BAC-   8D AA AA    STA   $AAAA
0BAF-   AA          TAX
0BB0-   AA          TAX
0BB1-   AA          TAX
0BB2-   AA          TAX
0BB3-   AA          TAX
0BB4-   AA          TAX
0BB5-   AA          TAX
0BB6-   AA          TAX
0BB7-   AA          TAX
0BB8-   AA          TAX
0BB9-   AA          TAX
0BBA-   AA          TAX
0BBB-   AA          TAX
0BBC-   AA          TAX
0BBD-   AA          TAX
0BBE-   AA          TAX
0BBF-   AA          TAX
0BC0-   AA          TAX
0BC1-   AA          TAX
0BC2-   AA          TAX
0BC3-   AA          TAX
0BC4-   AA          TAX
0BC5-   AA          TAX
0BC6-   AA          TAX
0BC7-   AA          TAX
0BC8-   AA          TAX
0BC9-   AA          TAX
0BCA-   AA          TAX
0BCB-   AA          TAX
0BCC-   AA          TAX
0BCD-   8D AA 8D    STA   $8DAA
0BD0-   A0 CC       LDY   #$CC
0BD2-   D3          ???
0BD3-   D4          ???
0BD4-   A0 CF       LDY   #$CF
0BD6-   C6 C6       DEC   $C6
0BD8-   8D A0 D0    STA   $D0A0
0BDB-   D5 D4       CMP   $D4,X
0BDD-   A0 CD       LDY   #$CD
0BDF-   C9 CE       CMP   #$CE
0BE1-   AE D6 C1    LDX   $C1D6
0BE4-   D2 D3       CMP   ($D3)
0BE6-   AE D2 C5    LDX   $C5D2
0BE9-   D1 D5       CMP   ($D5),Y
0BEB-   C9 D2       CMP   #$D2
0BED-   C5 C4       CMP   $C4
0BEF-   8D A0 D5    STA   $D5A0
0BF2-   D3          ???
0BF3-   C5 A0       CMP   $A0
0BF5-   CD C9 CE    CMP   $CEC9
0BF8-   AE CD C1    LDX   $C1CD
0BFB-   C3          ???
0BFC-   AE D2 C5    LDX   $C5D2
0BFF-   D1 D5       CMP   ($D5),Y
0C01-   C9 D2       CMP   #$D2
0C03-   C5 C4       CMP   $C4
0C05-   8D A0 D0    STA   $D0A0
0C08-   D5 D4       CMP   $D4,X
0C0A-   A0 CD       LDY   #$CD
0C0C-   C9 CE       CMP   #$CE
0C0E-   AE C8 CF    LDX   $CFC8
0C11-   CF          ???
0C12-   CB          ???
0C13-   D3          ???
0C14-   AE D2 C5    LDX   $C5D2
0C17-   D1 D5       CMP   ($D5),Y
0C19-   C9 D2       CMP   #$D2
0C1B-   C5 C4       CMP   $C4
0C1D-   8D A0 D0    STA   $D0A0
0C20-   D5 D4       CMP   $D4,X
0C22-   A0 CD       LDY   #$CD
0C24-   C9 CE       CMP   #$CE
0C26-   AE C8 CF    LDX   $CFC8
0C29-   CF          ???
0C2A-   CB          ???
0C2B-   D3          ???
0C2C-   AE C1 D2    LDX   $D2C1
0C2F-   D2 C1       CMP   ($C1)
0C31-   D9 D3 8D    CMP   $8DD3,Y
0C34-   A0 D0       LDY   #$D0
0C36-   D5 D4       CMP   $D4,X
0C38-   A0 CD       LDY   #$CD
0C3A-   C9 CE       CMP   #$CE
0C3C-   AE C8 CF    LDX   $CFC8
0C3F-   CF          ???
0C40-   CB          ???
0C41-   D3          ???
0C42-   AE C6 C9    LDX   $C9C6
0C45-   CC C5 C9    CPY   $C9C5
0C48-   CF          ???
0C49-   8D A0 D0    STA   $D0A0
0C4C-   D5 D4       CMP   $D4,X
0C4E-   A0 CD       LDY   #$CD
0C50-   C9 CE       CMP   #$CE
0C52-   AE C8 CF    LDX   $CFC8
0C55-   CF          ???
0C56-   CB          ???
0C57-   D3          ???
0C58-   AE D3 D4    LDX   $D4D3
0C5B-   C4 C9       CPY   $C9
0C5D-   CF          ???
0C5E-   8D A0 D0    STA   $D0A0
0C61-   D5 D4       CMP   $D4,X
0C63-   A0 CD       LDY   #$CD
0C65-   C9 CE       CMP   #$CE
0C67-   AE C8 CF    LDX   $CFC8
0C6A-   CF          ???
0C6B-   CB          ???
0C6C-   D3          ???
0C6D-   AE D3 D4    LDX   $D4D3
0C70-   D2 C9       CMP   ($C9)
0C72-   CE C7 D3    DEC   $D3C7
0C75-   8D A0 D5    STA   $D5A0
0C78-   D3          ???
0C79-   C5 A0       CMP   $A0
0C7B-   CD C9 CE    CMP   $CEC9
0C7E-   AE CD C1    LDX   $C1CD
0C81-   C3          ???
0C82-   AE C1 D2    LDX   $D2C1
0C85-   D2 C1       CMP   ($C1)
0C87-   D9 D3 8D    CMP   $8DD3,Y
0C8A-   A0 D5       LDY   #$D5
0C8C-   D3          ???
0C8D-   C5 A0       CMP   $A0
0C8F-   CD C9 CE    CMP   $CEC9
0C92-   AE CD C1    LDX   $C1CD
0C95-   C3          ???
0C96-   AE C3 CF    LDX   $CFC3
0C99-   CE D6 C5    DEC   $C5D6
0C9C-   D2 D4       CMP   ($D4)
0C9E-   8D A0 D5    STA   $D5A0
0CA1-   D3          ???
0CA2-   C5 A0       CMP   $A0
0CA4-   CD C9 CE    CMP   $CEC9
0CA7-   AE CD C1    LDX   $C1CD
0CAA-   C3          ???
0CAB-   AE C6 C9    LDX   $C9C6
0CAE-   CC C5 C9    CPY   $C9C5
0CB1-   CF          ???
0CB2-   8D A0 D5    STA   $D5A0
0CB5-   D3          ???
0CB6-   C5 A0       CMP   $A0
0CB8-   CD C9 CE    CMP   $CEC9
0CBB-   AE CD C1    LDX   $C1CD
0CBE-   C3          ???
0CBF-   AE D3 D4    LDX   $D4D3
0CC2-   C4 C9       CPY   $C9
0CC4-   CF          ???
0CC5-   8D A0 D5    STA   $D5A0
0CC8-   D3          ???
0CC9-   C5 A0       CMP   $A0
0CCB-   CD C9 CE    CMP   $CEC9
0CCE-   AE CD C1    LDX   $C1CD
0CD1-   C3          ???
0CD2-   AE D3 D4    LDX   $D4D3
0CD5-   D2 C9       CMP   ($C9)
0CD7-   CE C7 D3    DEC   $D3C7
0CDA-   8D A0 D5    STA   $D5A0
0CDD-   D3          ???
0CDE-   C5 A0       CMP   $A0
0CE0-   CD C1 C3    CMP   $C3C1
0CE3-   AE CD C5    LDX   $C5CD
0CE6-   CE D5 8D    DEC   $8DD5
0CE9-   A0 D5       LDY   #$D5
0CEB-   D3          ???
0CEC-   C5 A0       CMP   $A0
0CEE-   CD C1 C3    CMP   $C3C1
0CF1-   AE C2 D5    LDX   $D5C2
0CF4-   C9 CC       CMP   #$CC
0CF6-   C4 C5       CPY   $C5
0CF8-   D2 8D       CMP   ($8D)
0CFA-   A0 CC       LDY   #$CC
0CFC-   D3          ???
0CFD-   D4          ???
0CFE-   A0 CF       LDY   #$CF
0D00-   CE 8D AA    DEC   $AA8D
0D03-   8D AA AA    STA   $AAAA
0D06-   AA          TAX
0D07-   AA          TAX
0D08-   AA          TAX
0D09-   AA          TAX
0D0A-   AA          TAX
0D0B-   AA          TAX
0D0C-   AA          TAX
0D0D-   AA          TAX
0D0E-   AA          TAX
0D0F-   AA          TAX
0D10-   AA          TAX
0D11-   AA          TAX
0D12-   AA          TAX
0D13-   AA          TAX
0D14-   AA          TAX
0D15-   AA          TAX
0D16-   AA          TAX
0D17-   AA          TAX
0D18-   AA          TAX
0D19-   AA          TAX
0D1A-   AA          TAX
0D1B-   AA          TAX
0D1C-   AA          TAX
0D1D-   AA          TAX
0D1E-   AA          TAX
0D1F-   AA          TAX
0D20-   AA          TAX
0D21-   AA          TAX
0D22-   AA          TAX
0D23-   AA          TAX
0D24-   8D AA 20    STA   $20AA
0D27-   20 20 20    JSR   $2020
0D2A-   20 20 20    JSR   $2020
0D2D-   20 20 20    JSR   $2020
0D30-   20 20 20    JSR   $2020
0D33-   20 20 20    JSR   $2020
0D36-   20 20 20    JSR   $2020
0D39-   20 20 20    JSR   $2020
0D3C-   20 20 20    JSR   $2020
0D3F-   20 20 20    JSR   $2020
0D42-   20 20 AA    JSR   $AA20
0D45-   8D AA 20    STA   $20AA
0D48-   C3          ???
0D49-   CF          ???
0D4A-   CE D3 D4    DEC   $D4D3
0D4D-   C1 CE       CMP   ($CE,X)
0D4F-   D4          ???
0D50-   20 C4 C5    JSR   $C5C4
0D53-   C3          ???
0D54-   CC C1 D2    CPY   $D2C1
0D57-   C1 D4       CMP   ($D4,X)
0D59-   C9 CF       CMP   #$CF
0D5B-   CE D3 20    DEC   $20D3
0D5E-   20 20 20    JSR   $2020
0D61-   20 20 20    JSR   $2020
0D64-   20 AA 8D    JSR   $8DAA
0D67-   AA          TAX
0D68-   20 20 20    JSR   $2020
0D6B-   20 20 20    JSR   $2020
0D6E-   20 20 20    JSR   $2020
0D71-   20 20 20    JSR   $2020
0D74-   20 20 20    JSR   $2020
0D77-   20 20 20    JSR   $2020
0D7A-   20 20 20    JSR   $2020
0D7D-   20 20 20    JSR   $2020
0D80-   20 20 20    JSR   $2020
0D83-   20 20 20    JSR   $2020
0D86-   AA          TAX
0D87-   8D AA AA    STA   $AAAA
0D8A-   AA          TAX
0D8B-   AA          TAX
0D8C-   AA          TAX
0D8D-   AA          TAX
0D8E-   AA          TAX
0D8F-   AA          TAX
0D90-   AA          TAX
0D91-   AA          TAX
0D92-   AA          TAX
0D93-   AA          TAX
0D94-   AA          TAX
0D95-   AA          TAX
0D96-   AA          TAX
0D97-   AA          TAX
0D98-   AA          TAX
0D99-   AA          TAX
0D9A-   AA          TAX
0D9B-   AA          TAX
0D9C-   AA          TAX
0D9D-   AA          TAX
0D9E-   AA          TAX
0D9F-   AA          TAX
0DA0-   AA          TAX
0DA1-   AA          TAX
0DA2-   AA          TAX
0DA3-   AA          TAX
0DA4-   AA          TAX
0DA5-   AA          TAX
0DA6-   AA          TAX
0DA7-   AA          TAX
0DA8-   8D AA 8D    STA   $8DAA
0DAB-   DF          ???
0DAC-   CF          ???
0DAD-   C2          ???
0DAE-   CA          DEX
0DAF-   A0 C5       LDY   #$C5
0DB1-   D1 D5       CMP   ($D5),Y
0DB3-   A0 A4       LDY   #$A4
0DB5-   C2          ???
0DB6-   C6 C5       DEC   $C5
0DB8-   B0 8D       BCS   $0D47
0DBA-   AA          TAX
0DBB-   8D AA AA    STA   $AAAA
0DBE-   AA          TAX
0DBF-   AA          TAX
0DC0-   AA          TAX
0DC1-   AA          TAX
0DC2-   AA          TAX
0DC3-   AA          TAX
0DC4-   AA          TAX
0DC5-   AA          TAX
0DC6-   AA          TAX
0DC7-   AA          TAX
0DC8-   AA          TAX
0DC9-   AA          TAX
0DCA-   AA          TAX
0DCB-   AA          TAX
0DCC-   AA          TAX
0DCD-   AA          TAX
0DCE-   AA          TAX
0DCF-   AA          TAX
0DD0-   AA          TAX
0DD1-   AA          TAX
0DD2-   AA          TAX
0DD3-   AA          TAX
0DD4-   AA          TAX
0DD5-   AA          TAX
0DD6-   AA          TAX
0DD7-   AA          TAX
0DD8-   AA          TAX
0DD9-   AA          TAX
0DDA-   AA          TAX
0DDB-   AA          TAX
0DDC-   8D AA 20    STA   $20AA
0DDF-   20 20 20    JSR   $2020
0DE2-   20 20 20    JSR   $2020
0DE5-   20 20 20    JSR   $2020
0DE8-   20 20 20    JSR   $2020
0DEB-   20 20 20    JSR   $2020
0DEE-   20 20 20    JSR   $2020
0DF1-   20 20 20    JSR   $2020
0DF4-   20 20 20    JSR   $2020
0DF7-   20 20 20    JSR   $2020
0DFA-   20 20 AA    JSR   $AA20
0DFD-   8D AA 20    STA   $20AA
0E00-   CD C1 C9    CMP   $C9C1
0E03-   CE 20 D0    DEC   $D020
0E06-   D2 CF       CMP   ($CF)
0E08-   C7          ???
0E09-   D2 C1       CMP   ($C1)
0E0B-   CD 20 CC    CMP   $CC20
0E0E-   CF          ???
0E0F-   CF          ???
0E10-   D0 20       BNE   $0E32
0E12-   20 20 20    JSR   $2020
0E15-   20 20 20    JSR   $2020
0E18-   20 20 20    JSR   $2020
0E1B-   20 20 AA    JSR   $AA20
0E1E-   8D AA 20    STA   $20AA
0E21-   20 20 20    JSR   $2020
0E24-   20 20 20    JSR   $2020
0E27-   20 20 20    JSR   $2020
0E2A-   20 20 20    JSR   $2020
0E2D-   20 20 20    JSR   $2020
0E30-   20 20 20    JSR   $2020
0E33-   20 20 20    JSR   $2020
0E36-   20 20 20    JSR   $2020
0E39-   20 20 20    JSR   $2020
0E3C-   20 20 AA    JSR   $AA20
0E3F-   8D AA AA    STA   $AAAA
0E42-   AA          TAX
0E43-   AA          TAX
0E44-   AA          TAX
0E45-   AA          TAX
0E46-   AA          TAX
0E47-   AA          TAX
0E48-   AA          TAX
0E49-   AA          TAX
0E4A-   AA          TAX
0E4B-   AA          TAX
0E4C-   AA          TAX
0E4D-   AA          TAX
0E4E-   AA          TAX
0E4F-   AA          TAX
0E50-   AA          TAX
0E51-   AA          TAX
0E52-   AA          TAX
0E53-   AA          TAX
0E54-   AA          TAX
0E55-   AA          TAX
0E56-   AA          TAX
0E57-   AA          TAX
0E58-   AA          TAX
0E59-   AA          TAX
0E5A-   AA          TAX
0E5B-   AA          TAX
0E5C-   AA          TAX
0E5D-   AA          TAX
0E5E-   AA          TAX
0E5F-   AA          TAX
0E60-   8D AA 8D    STA   $8DAA
0E63-   CD C1 C9    CMP   $C9C1
0E66-   CE 8D A0    DEC   $A08D
0E69-   CA          DEX
0E6A-   D3          ???
0E6B-   D2 A0       CMP   ($A0)
0E6D-   C9 CE       CMP   #$CE
0E6F-   C9 D4       CMP   #$D4
0E71-   8D A0 CA    STA   $CAA0
0E74-   D3          ???
0E75-   D2 A0       CMP   ($A0)
0E77-   D4          ???
0E78-   C9 D4       CMP   #$D4
0E7A-   CC C5 8D    CPY   $8DC5
0E7D-   A0 CA       LDY   #$CA
0E7F-   CD D0 A0    CMP   $A0D0
0E82-   CD DF CF    CMP   $CFDF
0E85-   D0 D4       BNE   $0E5B
0E87-   C9 CF       CMP   #$CF
0E89-   CE D3 8D    DEC   $8DD3
0E8C-   AA          TAX
0E8D-   CA          DEX
0E8E-   D3          ???
0E8F-   D2 20       CMP   ($20)
0E91-   D3          ???
0E92-   C5 CC       CMP   $CC
0E94-   C5 C3       CMP   $C3
0E96-   D4          ???
0E97-   8D AA CA    STA   $CAAA
0E9A-   D3          ???
0E9B-   D2 20       CMP   ($20)
0E9D-   D4          ???
0E9E-   C5 CD       CMP   $CD
0EA0-   D0 CC       BNE   $0E6E
0EA2-   C1 D4       CMP   ($D4,X)
0EA4-   C5 8D       CMP   $8D
0EA6-   AA          TAX
0EA7-   CA          DEX
0EA8-   D3          ???
0EA9-   D2 20       CMP   ($20)
0EAB-   C2          ???
0EAC-   D5 C9       CMP   $C9,X
0EAE-   CC C4 8D    CPY   $8DC4
0EB1-   AA          TAX
0EB2-   8D A0 CA    STA   $CAA0
0EB5-   CD D0 A0    CMP   $A0D0
0EB8-   D2 C5       CMP   ($C5)
0EBA-   C5 CE       CMP   $CE
0EBC-   D4          ???
0EBD-   D2 D9       CMP   ($D9)
0EBF-   8D AA 8D    STA   $8DAA
0EC2-   AA          TAX
0EC3-   AA          TAX
0EC4-   AA          TAX
0EC5-   AA          TAX
0EC6-   AA          TAX
0EC7-   AA          TAX
0EC8-   AA          TAX
0EC9-   AA          TAX
0ECA-   AA          TAX
0ECB-   AA          TAX
0ECC-   AA          TAX
0ECD-   AA          TAX
0ECE-   AA          TAX
0ECF-   AA          TAX
0ED0-   AA          TAX
0ED1-   AA          TAX
0ED2-   AA          TAX
0ED3-   AA          TAX
0ED4-   AA          TAX
0ED5-   AA          TAX
0ED6-   AA          TAX
0ED7-   AA          TAX
0ED8-   AA          TAX
0ED9-   AA          TAX
0EDA-   AA          TAX
0EDB-   AA          TAX
0EDC-   AA          TAX
0EDD-   AA          TAX
0EDE-   AA          TAX
0EDF-   AA          TAX
0EE0-   AA          TAX
0EE1-   AA          TAX
0EE2-   8D AA 20    STA   $20AA
0EE5-   20 20 20    JSR   $2020
0EE8-   20 20 20    JSR   $2020
0EEB-   20 20 20    JSR   $2020
0EEE-   20 20 20    JSR   $2020
0EF1-   20 20 20    JSR   $2020
0EF4-   20 20 20    JSR   $2020
0EF7-   20 20 20    JSR   $2020
0EFA-   20 20 20    JSR   $2020
0EFD-   20 20 20    JSR   $2020
0F00-   20 20 AA    JSR   $AA20
0F03-   8D AA 20    STA   $20AA
0F06-   C9 CE       CMP   #$CE
0F08-   C9 D4       CMP   #$D4
0F0A-   20 D3 D5    JSR   $D5D3
0F0D-   C2          ???
0F0E-   D2 CF       CMP   ($CF)
0F10-   D5 D4       CMP   $D4,X
0F12-   C9 CE       CMP   #$CE
0F14-   C5 20       CMP   $20
0F16-   20 20 20    JSR   $2020
0F19-   20 20 20    JSR   $2020
0F1C-   20 20 20    JSR   $2020
0F1F-   20 20 20    JSR   $2020
0F22-   20 AA 8D    JSR   $8DAA
0F25-   AA          TAX
0F26-   20 20 20    JSR   $2020
0F29-   20 20 20    JSR   $2020
0F2C-   20 20 20    JSR   $2020
0F2F-   20 20 20    JSR   $2020
0F32-   20 20 20    JSR   $2020
0F35-   20 20 20    JSR   $2020
0F38-   20 20 20    JSR   $2020
0F3B-   20 20 20    JSR   $2020
0F3E-   20 20 20    JSR   $2020
0F41-   20 20 20    JSR   $2020
0F44-   AA          TAX
0F45-   8D AA AA    STA   $AAAA
0F48-   AA          TAX
0F49-   AA          TAX
0F4A-   AA          TAX
0F4B-   AA          TAX
0F4C-   AA          TAX
0F4D-   AA          TAX
0F4E-   AA          TAX
0F4F-   AA          TAX
0F50-   AA          TAX
0F51-   AA          TAX
0F52-   AA          TAX
0F53-   AA          TAX
0F54-   AA          TAX
0F55-   AA          TAX
0F56-   AA          TAX
0F57-   AA          TAX
0F58-   AA          TAX
0F59-   AA          TAX
0F5A-   AA          TAX
0F5B-   AA          TAX
0F5C-   AA          TAX
0F5D-   AA          TAX
0F5E-   AA          TAX
0F5F-   AA          TAX
0F60-   AA          TAX
0F61-   AA          TAX
0F62-   AA          TAX
0F63-   AA          TAX
0F64-   AA          TAX
0F65-   AA          TAX
0F66-   8D AA 8D    STA   $8DAA
0F69-   C9 CE       CMP   #$CE
0F6B-   C9 D4       CMP   #$D4
0F6D-   8D AA 8D    STA   $8DAA
0F70-   A0 C1       LDY   #$C1
0F72-   CD CF C4    CMP   $C4CF
0F75-   C5 8D       CMP   $8D
0F77-   A0 CC       LDY   #$CC
0F79-   C4 C1       CPY   $C1
0F7B-   A0 A3       LDY   #$A3
0F7D-   B0 8D       BCS   $0F0C
0F7F-   A0 D3       LDY   #$D3
0F81-   D4          ???
0F82-   C1 A0       CMP   ($A0,X)
0F84-   C3          ???
0F85-   CE D4 8D    DEC   $8DD4
0F88-   A0 C3       LDY   #$C3
0F8A-   CF          ???
0F8B-   CC B4 B0    CPY   $B0B4
0F8E-   8D A0 D2    STA   $D2A0
0F91-   D4          ???
0F92-   D3          ???
0F93-   8D AA 8D    STA   $8DAA
0F96-   AA          TAX
0F97-   AA          TAX
0F98-   AA          TAX
0F99-   AA          TAX
0F9A-   AA          TAX
0F9B-   AA          TAX
0F9C-   AA          TAX
0F9D-   AA          TAX
0F9E-   AA          TAX
0F9F-   AA          TAX
0FA0-   AA          TAX
0FA1-   AA          TAX
0FA2-   AA          TAX
0FA3-   AA          TAX
0FA4-   AA          TAX
0FA5-   AA          TAX
0FA6-   AA          TAX
0FA7-   AA          TAX
0FA8-   AA          TAX
0FA9-   AA          TAX
0FAA-   AA          TAX
0FAB-   AA          TAX
0FAC-   AA          TAX
0FAD-   AA          TAX
0FAE-   AA          TAX
0FAF-   AA          TAX
0FB0-   AA          TAX
0FB1-   AA          TAX
0FB2-   AA          TAX
0FB3-   AA          TAX
0FB4-   AA          TAX
0FB5-   AA          TAX
0FB6-   8D AA 20    STA   $20AA
0FB9-   20 20 20    JSR   $2020
0FBC-   20 20 20    JSR   $2020
0FBF-   20 20 20    JSR   $2020
0FC2-   20 20 20    JSR   $2020
0FC5-   20 20 20    JSR   $2020
0FC8-   20 20 20    JSR   $2020
0FCB-   20 20 20    JSR   $2020
0FCE-   20 20 20    JSR   $2020
0FD1-   20 20 20    JSR   $2020
0FD4-   20 20 AA    JSR   $AA20
0FD7-   8D AA 20    STA   $20AA
0FDA-   D4          ???
0FDB-   C9 D4       CMP   #$D4
0FDD-   CC C5 20    CPY   $20C5
0FE0-   D3          ???
0FE1-   D5 C2       CMP   $C2,X
0FE3-   D2 CF       CMP   ($CF)
0FE5-   D5 D4       CMP   $D4,X
0FE7-   C9 CE       CMP   #$CE
0FE9-   C5 20       CMP   $20
0FEB-   20 20 20    JSR   $2020
0FEE-   20 20 20    JSR   $2020
0FF1-   20 20 20    JSR   $2020
0FF4-   20 20 20    JSR   $2020
0FF7-   AA          TAX
0FF8-   8D AA 20    STA   $20AA
0FFB-   20 20 20    JSR   $2020
0FFE-   20 20 20    JSR   $2020
1001-   20 20 20    JSR   $2020
1004-   20 20 20    JSR   $2020
1007-   20 20 20    JSR   $2020
100A-   20 20 20    JSR   $2020
100D-   20 20 20    JSR   $2020
1010-   20 20 20    JSR   $2020
1013-   20 20 20    JSR   $2020
1016-   20 20 AA    JSR   $AA20
1019-   8D AA AA    STA   $AAAA
101C-   AA          TAX
101D-   AA          TAX
101E-   AA          TAX
101F-   AA          TAX
1020-   AA          TAX
1021-   AA          TAX
1022-   AA          TAX
1023-   AA          TAX
1024-   AA          TAX
1025-   AA          TAX
1026-   AA          TAX
1027-   AA          TAX
1028-   AA          TAX
1029-   AA          TAX
102A-   AA          TAX
102B-   AA          TAX
102C-   AA          TAX
102D-   AA          TAX
102E-   AA          TAX
102F-   AA          TAX
1030-   AA          TAX
1031-   AA          TAX
1032-   AA          TAX
1033-   AA          TAX
1034-   AA          TAX
1035-   AA          TAX
1036-   AA          TAX
1037-   AA          TAX
1038-   AA          TAX
1039-   AA          TAX
103A-   8D AA 8D    STA   $8DAA
103D-   D4          ???
103E-   C9 D4       CMP   #$D4
1040-   CC C5 8D    CPY   $8DC5
1043-   AA          TAX
1044-   8D A0 CA    STA   $CAA0
1047-   D3          ???
1048-   D2 A0       CMP   ($A0)
104A-   C8          INY
104B-   CF          ???
104C-   CD C5 8D    CMP   $8DC5
104F-   A0 D3       LDY   #$D3
1051-   C3          ???
1052-   D0 CF       BNE   $1023
1054-   D3          ???
1055-   A0 A3       LDY   #$A3
1057-   B1 B3       LDA   ($B3),Y
1059-   BB          ???
105A-   A3          ???
105B-   B3          ???
105C-   8D A0 D0    STA   $D0A0
105F-   D2 CE       CMP   ($CE)
1061-   A0 A2       LDY   #$A2
1063-   C1 D0       CMP   ($D0,X)
1065-   D0 CC       BNE   $1033
1067-   C5 DD       CMP   $DD
1069-   DB          ???
106A-   20 C1 D3    JSR   $D3C1
106D-   CD A2 8D    CMP   $8DA2
1070-   A0 D3       LDY   #$D3
1072-   C3          ???
1073-   D0 CF       BNE   $1044
1075-   D3          ???
1076-   A0 A3       LDY   #$A3
1078-   B1 B4       LDA   ($B4),Y
107A-   BB          ???
107B-   A3          ???
107C-   B5 8D       LDA   $8D,X
107E-   A0 D0       LDY   #$D0
1080-   D2 CE       CMP   ($CE)
1082-   A0 A2       LDY   #$A2
1084-   C2          ???
1085-   C1 D2       CMP   ($D2,X)
1087-   C5 C2       CMP   $C2
1089-   CF          ???
108A-   CE C5 D3    DEC   $D3C5
108D-   A2 8D       LDX   #$8D
108F-   A0 D3       LDY   #$D3
1091-   C3          ???
1092-   D0 CF       BNE   $1063
1094-   D3          ???
1095-   A0 A3       LDY   #$A3
1097-   B1 BB       LDA   ($BB),Y
1099-   A3          ???
109A-   B7          ???
109B-   8D A0 D0    STA   $D0A0
109E-   D2 CE       CMP   ($CE)
10A0-   A0 A3       LDY   #$A3
10A2-   D4          ???
10A3-   CE C1 CD    DEC   $CDC1
10A6-   C5 8D       CMP   $8D
10A8-   A0 D3       LDY   #$D3
10AA-   C3          ???
10AB-   D0 CF       BNE   $107C
10AD-   D3          ???
10AE-   A0 A3       LDY   #$A3
10B0-   B1 BB       LDA   ($BB),Y
10B2-   A3          ???
10B3-   B8          CLV
10B4-   8D A0 D0    STA   $D0A0
10B7-   D2 CE       CMP   ($CE)
10B9-   A0 A3       LDY   #$A3
10BB-   D4          ???
10BC-   CE C1 CD    DEC   $CDC1
10BF-   C5 B2       CMP   $B2
10C1-   8D A0 D3    STA   $D3A0
10C4-   C3          ???
10C5-   D0 CF       BNE   $1096
10C7-   D3          ???
10C8-   A0 A3       LDY   #$A3
10CA-   B1 BB       LDA   ($BB),Y
10CC-   A3          ???
10CD-   B9 8D A0    LDA   $A08D,Y
10D0-   D0 D2       BNE   $10A4
10D2-   CE A0 A3    DEC   $A3A0
10D5-   D4          ???
10D6-   CE C1 CD    DEC   $CDC1
10D9-   C5 B3       CMP   $B3
10DB-   8D A0 D3    STA   $D3A0
10DE-   C3          ???
10DF-   D0 CF       BNE   $10B0
10E1-   D3          ???
10E2-   A0 A3       LDY   #$A3
10E4-   B1 BB       LDA   ($BB),Y
10E6-   A3          ???
10E7-   B1 B0       LDA   ($B0),Y
10E9-   8D A0 D0    STA   $D0A0
10EC-   D2 CE       CMP   ($CE)
10EE-   A0 A3       LDY   #$A3
10F0-   D4          ???
10F1-   CE C1 CD    DEC   $CDC1
10F4-   C5 B4       CMP   $B4
10F6-   8D A0 D3    STA   $D3A0
10F9-   C3          ???
10FA-   D0 CF       BNE   $10CB
10FC-   D3          ???
10FD-   A0 A3       LDY   #$A3
10FF-   B1 BB       LDA   ($BB),Y
1101-   A3          ???
1102-   B1 B1       LDA   ($B1),Y
1104-   8D A0 D0    STA   $D0A0
1107-   D2 CE       CMP   ($CE)
1109-   A0 A3       LDY   #$A3
110B-   D4          ???
110C-   CE C1 CD    DEC   $CDC1
110F-   C5 B5       CMP   $B5
1111-   8D A0 D3    STA   $D3A0
1114-   C3          ???
1115-   D0 CF       BNE   $10E6
1117-   D3          ???
1118-   A0 A3       LDY   #$A3
111A-   B9 BB A3    LDA   $A3BB,Y
111D-   B1 B4       LDA   ($B4),Y
111F-   8D A0 D0    STA   $D0A0
1122-   D2 CE       CMP   ($CE)
1124-   A0 A2       LDY   #$A2
1126-   C2          ???
1127-   D9 20 CE    CMP   $CE20,Y
112A-   C1 D4       CMP   ($D4,X)
112C-   C8          INY
112D-   C1 CE       CMP   ($CE,X)
112F-   20 D2 C9    JSR   $C9D2
1132-   C7          ???
1133-   C7          ???
1134-   D3          ???
1135-   AC 20 B2    LDY   $B220
1138-   B0 B1       BCS   $10EB
113A-   B9 A2 AC    LDA   $ACA2,Y
113D-   B8          CLV
113E-   C4 B8       CPY   $B8
1140-   C4 8D       CPY   $8D
1142-   A0 D3       LDY   #$D3
1144-   C3          ???
1145-   D0 CF       BNE   $1116
1147-   D3          ???
1148-   A0 A3       LDY   #$A3
114A-   B5 BB       LDA   $BB,X
114C-   A3          ???
114D-   B1 B7       LDA   ($B7),Y
114F-   8D A0 D0    STA   $D0A0
1152-   D2 CE       CMP   ($CE)
1154-   A0 A2       LDY   #$A2
1156-   A8          TAY
1157-   C4 A9       CPY   $A9
1159-   C5 D3       CMP   $D3
115B-   C3          ???
115C-   D2 C9       CMP   ($C9)
115E-   D0 D4       BNE   $1134
1160-   C9 CF       CMP   #$CF
1162-   CE 20 20    DEC   $2020
1165-   20 20 A8    JSR   $A820
1168-   C9 A9       CMP   #$A9
116A-   CE D3 D4    DEC   $D4D3
116D-   D2 D5       CMP   ($D5)
116F-   C3          ???
1170-   D4          ???
1171-   C9 CF       CMP   #$CF
1173-   CE D3 A2    DEC   $A2D3
1176-   8D A0 D3    STA   $D3A0
1179-   C3          ???
117A-   D0 CF       BNE   $114B
117C-   D3          ???
117D-   A0 A3       LDY   #$A3
117F-   B5 BB       LDA   $BB,X
1181-   A3          ???
1182-   B1 B8       LDA   ($B8),Y
1184-   8D A0 D0    STA   $D0A0
1187-   D2 CE       CMP   ($CE)
1189-   A0 A2       LDY   #$A2
118B-   A8          TAY
118C-   D3          ???
118D-   A9 C5       LDA   #$C5
118F-   D4          ???
1190-   D4          ???
1191-   C9 CE       CMP   #$CE
1193-   C7          ???
1194-   D3          ???
1195-   20 20 20    JSR   $2020
1198-   20 20 20    JSR   $2020
119B-   20 A8 C2    JSR   $C2A8
119E-   A9 D5       LDA   #$D5
11A0-   C9 CC       CMP   #$CC
11A2-   C4 A2       CPY   $A2
11A4-   AC B8 C4    LDY   $C4B8
11A7-   B8          CLV
11A8-   C4 8D       CPY   $8D
11AA-   AA          TAX
11AB-   8D A0 D2    STA   $D2A0
11AE-   D4          ???
11AF-   D3          ???
11B0-   8D AA 8D    STA   $8DAA
11B3-   AA          TAX
11B4-   AA          TAX
11B5-   AA          TAX
11B6-   AA          TAX
11B7-   AA          TAX
11B8-   AA          TAX
11B9-   AA          TAX
11BA-   AA          TAX
11BB-   AA          TAX
11BC-   AA          TAX
11BD-   AA          TAX
11BE-   AA          TAX
11BF-   AA          TAX
11C0-   AA          TAX
11C1-   AA          TAX
11C2-   AA          TAX
11C3-   AA          TAX
11C4-   AA          TAX
11C5-   AA          TAX
11C6-   AA          TAX
11C7-   AA          TAX
11C8-   AA          TAX
11C9-   AA          TAX
11CA-   AA          TAX
11CB-   AA          TAX
11CC-   AA          TAX
11CD-   AA          TAX
11CE-   AA          TAX
11CF-   AA          TAX
11D0-   AA          TAX
11D1-   AA          TAX
11D2-   AA          TAX
11D3-   8D AA 20    STA   $20AA
11D6-   20 20 20    JSR   $2020
11D9-   20 20 20    JSR   $2020
11DC-   20 20 20    JSR   $2020
11DF-   20 20 20    JSR   $2020
11E2-   20 20 20    JSR   $2020
11E5-   20 20 20    JSR   $2020
11E8-   20 20 20    JSR   $2020
11EB-   20 20 20    JSR   $2020
11EE-   20 20 20    JSR   $2020
11F1-   20 20 AA    JSR   $AA20
11F4-   8D AA 20    STA   $20AA
11F7-   CD DF CF    CMP   $CFDF
11FA-   D0 D4       BNE   $11D0
11FC-   C9 CF       CMP   #$CF
11FE-   CE D3 20    DEC   $20D3
1201-   D3          ???
1202-   D5 C2       CMP   $C2,X
1204-   D2 CF       CMP   ($CF)
1206-   D5 D4       CMP   $D4,X
1208-   C9 CE       CMP   #$CE
120A-   C5 20       CMP   $20
120C-   20 20 20    JSR   $2020
120F-   20 20 20    JSR   $2020
1212-   20 20 AA    JSR   $AA20
1215-   8D AA 20    STA   $20AA
1218-   20 20 20    JSR   $2020
121B-   20 20 20    JSR   $2020
121E-   20 20 20    JSR   $2020
1221-   20 20 20    JSR   $2020
1224-   20 20 20    JSR   $2020
1227-   20 20 20    JSR   $2020
122A-   20 20 20    JSR   $2020
122D-   20 20 20    JSR   $2020
1230-   20 20 20    JSR   $2020
1233-   20 20 AA    JSR   $AA20
1236-   8D AA AA    STA   $AAAA
1239-   AA          TAX
123A-   AA          TAX
123B-   AA          TAX
123C-   AA          TAX
123D-   AA          TAX
123E-   AA          TAX
123F-   AA          TAX
1240-   AA          TAX
1241-   AA          TAX
1242-   AA          TAX
1243-   AA          TAX
1244-   AA          TAX
1245-   AA          TAX
1246-   AA          TAX
1247-   AA          TAX
1248-   AA          TAX
1249-   AA          TAX
124A-   AA          TAX
124B-   AA          TAX
124C-   AA          TAX
124D-   AA          TAX
124E-   AA          TAX
124F-   AA          TAX
1250-   AA          TAX
1251-   AA          TAX
1252-   AA          TAX
1253-   AA          TAX
1254-   AA          TAX
1255-   AA          TAX
1256-   AA          TAX
1257-   8D AA 8D    STA   $8DAA
125A-   CD DF CF    CMP   $CFDF
125D-   D0 D4       BNE   $1233
125F-   C9 CF       CMP   #$CF
1261-   CE D3 8D    DEC   $8DD3
1264-   AA          TAX
1265-   8D BA D7    STA   $D7BA
1268-   CC D0 8D    CPY   $8DD0
126B-   A0 D7       LDY   #$D7
126D-   C1 C9       CMP   ($C9,X)
126F-   D4          ???
1270-   8D A0 C3    STA   $C3A0
1273-   CD D0 A0    CMP   $A0D0
1276-   A3          ???
1277-   A4 B4       LDY   $B4
1279-   B4 A0       LDY   $A0,X
127B-   BB          ???
127C-   20 A2 C4    JSR   $C4A2
127F-   A2 8D       LDX   #$8D
1281-   A0 C2       LDY   #$C2
1283-   C5 D1       CMP   $D1
1285-   A0 BA       LDY   #$BA
1287-   C4 C5       CPY   $C5
1289-   D3          ???
128A-   C3          ???
128B-   D2 C9       CMP   ($C9)
128D-   C2          ???
128E-   C5 8D       CMP   $8D
1290-   A0 C3       LDY   #$C3
1292-   CD D0 A0    CMP   $A0D0
1295-   A3          ???
1296-   A4 B4       LDY   $B4
1298-   B9 A0 BB    LDA   $BBA0,Y
129B-   20 A2 C9    JSR   $C9A2
129E-   A2 8D       LDX   #$8D
12A0-   A0 C2       LDY   #$C2
12A2-   C5 D1       CMP   $D1
12A4-   A0 BA       LDY   #$BA
12A6-   C9 CE       CMP   #$CE
12A8-   D3          ???
12A9-   D4          ???
12AA-   D2 D5       CMP   ($D5)
12AC-   C3          ???
12AD-   D4          ???
12AE-   8D A0 C3    STA   $C3A0
12B1-   CD D0 A0    CMP   $A0D0
12B4-   A3          ???
12B5-   A4 B5       LDY   $B5
12B7-   B3          ???
12B8-   A0 BB       LDY   #$BB
12BA-   20 A2 D3    JSR   $D3A2
12BD-   A2 8D       LDX   #$8D
12BF-   A0 C2       LDY   #$C2
12C1-   C5 D1       CMP   $D1
12C3-   A0 BA       LDY   #$BA
12C5-   C7          ???
12C6-   CF          ???
12C7-   D3          ???
12C8-   C5 D4       CMP   $D4
12CA-   D4          ???
12CB-   C9 CE       CMP   #$CE
12CD-   C7          ???
12CE-   D3          ???
12CF-   8D A0 C3    STA   $C3A0
12D2-   CD D0 A0    CMP   $A0D0
12D5-   A3          ???
12D6-   A4 B4       LDY   $B4
12D8-   B2 A0       LDA   ($A0)
12DA-   BB          ???
12DB-   20 A2 C2    JSR   $C2A2
12DE-   A2 8D       LDX   #$8D
12E0-   A0 C2       LDY   #$C2
12E2-   C5 D1       CMP   $D1
12E4-   A0 BA       LDY   #$BA
12E6-   C7          ???
12E7-   CF          ???
12E8-   C2          ???
12E9-   D5 C9       CMP   $C9,X
12EB-   CC C4 8D    CPY   $8DC4
12EE-   A0 C3       LDY   #$C3
12F0-   CD D0 A0    CMP   $A0D0
12F3-   A3          ???
12F4-   A7          ???
12F5-   D1 A7       CMP   ($A7),Y
12F7-   8D A0 C2    STA   $C2A0
12FA-   C5 D1       CMP   $D1
12FC-   A0 BA       LDY   #$BA
12FE-   C7          ???
12FF-   CF          ???
1300-   D1 D5       CMP   ($D5),Y
1302-   C9 D4       CMP   #$D4
1304-   8D A0 CA    STA   $CAA0
1307-   CD D0 A0    CMP   $A0D0
130A-   BA          TSX
130B-   D7          ???
130C-   CC D0 8D    CPY   $8DD0
130F-   BA          TSX
1310-   C7          ???
1311-   CF          ???
1312-   D3          ???
1313-   C5 D4       CMP   $D4
1315-   D4          ???
1316-   C9 CE       CMP   #$CE
1318-   C7          ???
1319-   D3          ???
131A-   8D A0 CA    STA   $CAA0
131D-   CD D0 A0    CMP   $A0D0
1320-   BA          TSX
1321-   D3          ???
1322-   C5 D4       CMP   $D4
1324-   D4          ???
1325-   C9 CE       CMP   #$CE
1327-   C7          ???
1328-   D3          ???
1329-   8D BA C7    STA   $C7BA
132C-   CF          ???
132D-   C2          ???
132E-   D5 C9       CMP   $C9,X
1330-   CC C4 8D    CPY   $8DC4
1333-   A0 CA       LDY   #$CA
1335-   CD D0 A0    CMP   $A0D0
1338-   BA          TSX
1339-   C2          ???
133A-   D5 C9       CMP   $C9,X
133C-   CC C4 8D    CPY   $8DC4
133F-   BA          TSX
1340-   C7          ???
1341-   CF          ???
1342-   D1 D5       CMP   ($D5),Y
1344-   C9 D4       CMP   #$D4
1346-   8D A0 CA    STA   $CAA0
1349-   CD D0 A0    CMP   $A0D0
134C-   BA          TSX
134D-   D1 D5       CMP   ($D5),Y
134F-   C9 D4       CMP   #$D4
1351-   8D BA C4    STA   $C4BA
1354-   C5 D3       CMP   $D3
1356-   C3          ???
1357-   D2 C9       CMP   ($C9)
1359-   C2          ???
135A-   C5 8D       CMP   $8D
135C-   A0 D0       LDY   #$D0
135E-   CC C1 8D    CPY   $8DC1
1361-   A0 D0       LDY   #$D0
1363-   CC C1 8D    CPY   $8DC1
1366-   A0 D0       LDY   #$D0
1368-   D5 D0       CMP   $D0,X
136A-   A0 A3       LDY   #$A3
136C-   B5 BB       LDA   $BB,X
136E-   A3          ???
136F-   B2 BB       LDA   ($BB)
1371-   A3          ???
1372-   B3          ???
1373-   B0 BB       BCS   $1330
1375-   A3          ???
1376-   B2 B0       LDA   ($B0)
1378-   BB          ???
1379-   A2 D4       LDX   #$D4
137B-   AE C4 C5    LDX   $C5C4
137E-   D3          ???
137F-   C3          ???
1380-   A2 BB       LDX   #$BB
1382-   A3          ???
1383-   CD C1 C9    CMP   $C9C1
1386-   CE 8D A0    DEC   $A08D
1389-   CA          DEX
138A-   CD D0 A0    CMP   $A0D0
138D-   CD C1 C9    CMP   $C9C1
1390-   CE 8D BA    DEC   $BA8D
1393-   C9 CE       CMP   #$CE
1395-   D3          ???
1396-   D4          ???
1397-   D2 D5       CMP   ($D5)
1399-   C3          ???
139A-   D4          ???
139B-   8D A0 D0    STA   $D0A0
139E-   CC C1 8D    CPY   $8DC1
13A1-   A0 D0       LDY   #$D0
13A3-   CC C1 8D    CPY   $8DC1
13A6-   A0 D0       LDY   #$D0
13A8-   D5 D0       CMP   $D0,X
13AA-   A0 A3       LDY   #$A3
13AC-   B5 BB       LDA   $BB,X
13AE-   A3          ???
13AF-   B2 BB       LDA   ($BB)
13B1-   A3          ???
13B2-   B3          ???
13B3-   B0 BB       BCS   $1370
13B5-   A3          ???
13B6-   B2 B0       LDA   ($B0)
13B8-   BB          ???
13B9-   A2 D4       LDX   #$D4
13BB-   AE C2 CC    LDX   $CCC2
13BE-   C4 AE       CPY   $AE
13C0-   C9 CE       CMP   #$CE
13C2-   D3          ???
13C3-   D4          ???
13C4-   D2 D5       CMP   ($D5)
13C6-   C3          ???
13C7-   D4          ???
13C8-   A2 BB       LDX   #$BB
13CA-   A3          ???
13CB-   CD C1 C9    CMP   $C9C1
13CE-   CE 8D A0    DEC   $A08D
13D1-   CA          DEX
13D2-   CD D0 A0    CMP   $A0D0
13D5-   CD C1 C9    CMP   $C9C1
13D8-   CE 8D BA    DEC   $BA8D
13DB-   D3          ???
13DC-   C5 D4       CMP   $D4
13DE-   D4          ???
13DF-   C9 CE       CMP   #$CE
13E1-   C7          ???
13E2-   D3          ???
13E3-   8D AA CD    STA   $CDAA
13E6-   C5 CE       CMP   $CE
13E8-   C4 20       CPY   $20
13EA-   A3          ???
13EB-   D3          ???
13EC-   C5 D4       CMP   $D4
13EE-   CD C5 CE    CMP   $CEC5
13F1-   BB          ???
13F2-   A3          ???
13F3-   CD C1 C9    CMP   $C9C1
13F6-   CE 8D A0    DEC   $A08D
13F9-   CD CE D3    CMP   $D3CE
13FC-   CE CD A0    DEC   $A0CD
13FF-   A2 D3       LDX   #$D3
1401-   C5 D4       CMP   $D4
1403-   D4          ???
1404-   C9 CE       CMP   #$CE
1406-   C7          ???
1407-   D3          ???
1408-   20 CD C5    JSR   $C5CD
140B-   CE D5 A2    DEC   $A2D5
140E-   8D A0 CD    STA   $CDA0
1411-   CE D3 CC    DEC   $CCD3
1414-   CE A0 A3    DEC   $A3A0
1417-   A4 B0       LDY   $B0
1419-   B9 8D A0    LDA   $A08D,Y
141C-   CD CE D3    CMP   $D3CE
141F-   CC D7 A0    CPY   $A0D7
1422-   A3          ???
1423-   B2 B0       LDA   ($B0)
1425-   8D A0 CD    STA   $CDA0
1428-   CE D3 CF    DEC   $CFD3
142B-   D7          ???
142C-   A0 A3       LDY   #$A3
142E-   B1 B0       LDA   ($B0),Y
1430-   8D A0 CD    STA   $CDA0
1433-   CE D3 C2    DEC   $C2D3
1436-   CB          ???
1437-   A0 A3       LDY   #$A3
1439-   B2 B7       LDA   ($B7)
143B-   A0 BB       LDY   #$BB
143D-   20 C5 D3    JSR   $D3C5
1440-   C3          ???
1441-   C1 D0       CMP   ($D0,X)
1443-   C5 20       CMP   $20
1445-   CB          ???
1446-   C5 D9       CMP   $D9
1448-   8D A0 CD    STA   $CDA0
144B-   CE D3 C8    DEC   $C8D3
144E-   CB          ???
144F-   A0 A3       LDY   #$A3
1451-   B2 BB       LDA   ($BB)
1453-   A3          ???
1454-   CD C1 C9    CMP   $C9C1
1457-   CE 8D A0    DEC   $A08D
145A-   CD CE C7    CMP   $C7CE
145D-   C8          INY
145E-   CB          ???
145F-   A0 A3       LDY   #$A3
1461-   B2 8D       LDA   ($8D)
1463-   A0 CD       LDY   #$CD
1465-   CE D3 CF    DEC   $CFD3
1468-   D0 A0       BNE   $140A
146A-   A3          ???
146B-   B1 BB       LDA   ($BB),Y
146D-   A2 A3       LDX   #$A3
146F-   DA          PHX
1470-   C5 D2       CMP   $D2
1472-   CF          ???
1473-   A3          ???
1474-   CF          ???
1475-   CE C5 A3    DEC   $A3C5
1478-   D4          ???
1479-   D7          ???
147A-   CF          ???
147B-   A3          ???
147C-   D4          ???
147D-   C8          INY
147E-   D2 C5       CMP   ($C5)
1480-   C5 A2       CMP   $A2
1482-   8D AA CD    STA   $CDAA
1485-   CE D3 C1    DEC   $C1D3
1488-   D6 20       DEC   $20,X
148A-   A2 CD       LDX   #$CD
148C-   C5 CE       CMP   $CE
148E-   D5 AE       CMP   $AE,X
1490-   D4          ???
1491-   C5 D3       CMP   $D3
1493-   D4          ???
1494-   A2 8D       LDX   #$8D
1496-   A0 CA       LDY   #$CA
1498-   D3          ???
1499-   D2 A0       CMP   ($A0)
149B-   C8          INY
149C-   CF          ???
149D-   CD C5 8D    CMP   $8DC5
14A0-   A0 CD       LDY   #$CD
14A2-   CE C4 D3    DEC   $D3C4
14A5-   D0 A0       BNE   $1447
14A7-   A3          ???
14A8-   B0 BB       BCS   $1465
14AA-   A3          ???
14AB-   B0 8D       BCS   $143A
14AD-   A0 D7       LDY   #$D7
14AF-   C1 C9       CMP   ($C9,X)
14B1-   D4          ???
14B2-   8D BA C2    STA   $C2BA
14B5-   D5 C9       CMP   $C9,X
14B7-   CC C4 8D    CPY   $8DC4
14BA-   A0 CA       LDY   #$CA
14BC-   CD D0 A0    CMP   $A0D0
14BF-   CD C1 C9    CMP   $C9C1
14C2-   CE 8D BA    DEC   $BA8D
14C5-   D1 D5       CMP   ($D5),Y
14C7-   C9 D4       CMP   #$D4
14C9-   8D A0 CA    STA   $CAA0
14CC-   CD D0 A0    CMP   $A0D0
14CF-   D2 C5       CMP   ($C5)
14D1-   C5 CE       CMP   $CE
14D3-   D4          ???
14D4-   D2 D9       CMP   ($D9)
14D6-   8D AA 8D    STA   $8DAA
14D9-   AA          TAX
14DA-   AA          TAX
14DB-   AA          TAX
14DC-   AA          TAX
14DD-   AA          TAX
14DE-   AA          TAX
14DF-   AA          TAX
14E0-   AA          TAX
14E1-   AA          TAX
14E2-   AA          TAX
14E3-   AA          TAX
14E4-   AA          TAX
14E5-   AA          TAX
14E6-   AA          TAX
14E7-   AA          TAX
14E8-   AA          TAX
14E9-   AA          TAX
14EA-   AA          TAX
14EB-   AA          TAX
14EC-   AA          TAX
14ED-   AA          TAX
14EE-   AA          TAX
14EF-   AA          TAX
14F0-   AA          TAX
14F1-   AA          TAX
14F2-   AA          TAX
14F3-   AA          TAX
14F4-   AA          TAX
14F5-   AA          TAX
14F6-   AA          TAX
14F7-   AA          TAX
14F8-   AA          TAX
14F9-   8D AA 20    STA   $20AA
14FC-   20 20 20    JSR   $2020
14FF-   20 20 20    JSR   $2020
1502-   20 20 20    JSR   $2020
1505-   20 20 20    JSR   $2020
1508-   20 20 20    JSR   $2020
150B-   20 20 20    JSR   $2020
150E-   20 20 20    JSR   $2020
1511-   20 20 20    JSR   $2020
1514-   20 20 20    JSR   $2020
1517-   20 20 AA    JSR   $AA20
151A-   8D AA 20    STA   $20AA
151D-   D6 C1       DEC   $C1,X
151F-   D2 C9       CMP   ($C9)
1521-   C1 C2       CMP   ($C2,X)
1523-   CC C5 D3    CPY   $D3C5
1526-   20 20 20    JSR   $2020
1529-   20 20 20    JSR   $2020
152C-   20 20 20    JSR   $2020
152F-   20 20 20    JSR   $2020
1532-   20 20 20    JSR   $2020
1535-   20 20 20    JSR   $2020
1538-   20 20 AA    JSR   $AA20
153B-   8D AA 20    STA   $20AA
153E-   20 20 20    JSR   $2020
1541-   20 20 20    JSR   $2020
1544-   20 20 20    JSR   $2020
1547-   20 20 20    JSR   $2020
154A-   20 20 20    JSR   $2020
154D-   20 20 20    JSR   $2020
1550-   20 20 20    JSR   $2020
1553-   20 20 20    JSR   $2020
1556-   20 20 20    JSR   $2020
1559-   20 20 AA    JSR   $AA20
155C-   8D AA AA    STA   $AAAA
155F-   AA          TAX
1560-   AA          TAX
1561-   AA          TAX
1562-   AA          TAX
1563-   AA          TAX
1564-   AA          TAX
1565-   AA          TAX
1566-   AA          TAX
1567-   AA          TAX
1568-   AA          TAX
1569-   AA          TAX
156A-   AA          TAX
156B-   AA          TAX
156C-   AA          TAX
156D-   AA          TAX
156E-   AA          TAX
156F-   AA          TAX
1570-   AA          TAX
1571-   AA          TAX
1572-   AA          TAX
1573-   AA          TAX
1574-   AA          TAX
1575-   AA          TAX
1576-   AA          TAX
1577-   AA          TAX
1578-   AA          TAX
1579-   AA          TAX
157A-   AA          TAX
157B-   AA          TAX
157C-   AA          TAX
157D-   8D AA 8D    STA   $8DAA
1580-   C3          ???
1581-   CE D4 A0    DEC   $A0D4
1584-   C4 D3       CPY   $D3
1586-   A0 B2       LDY   #$B2
1588-   A0 BB       LDY   #$BB
158A-   20 D4 C5    JSR   $C5D4
158D-   CD D0 20    CMP   $20D0
1590-   C3          ???
1591-   CF          ???
1592-   D5 CE       CMP   $CE,X
1594-   D4          ???
1595-   C5 D2       CMP   $D2
1597-   8D D0 CE    STA   $CED0
159A-   C1 CD       CMP   ($CD,X)
159C-   C5 A0       CMP   $A0
159E-   C4 D3       CPY   $D3
15A0-   A0 B3       LDY   #$B3
15A2-   B0 A0       BCS   $1544
15A4-   BB          ???
15A5-   20 D0 D2    JSR   $D2D0
15A8-   CF          ???
15A9-   CA          DEX
15AA-   C5 C3       CMP   $C3
15AC-   D4          ???
15AD-   20 CE C1    JSR   $C1CE
15B0-   CD C5 8D    CMP   $8DC5
15B3-   D0 C1       BNE   $1576
15B5-   C4 C4       CPY   $C4
15B7-   D2 A0       CMP   ($A0)
15B9-   C4 D3       CPY   $D3
15BB-   A0 B2       LDY   #$B2
15BD-   A0 BB       LDY   #$BB
15BF-   20 D0 D2    JSR   $D2D0
15C2-   CF          ???
15C3-   CA          DEX
15C4-   C5 C3       CMP   $C3
15C6-   D4          ???
15C7-   20 CF C2    JSR   $C2CF
15CA-   CA          DEX
15CB-   20 C1 C4    JSR   $C4C1
15CE-   C4 D2       CPY   $D2
15D0-   C5 D3       CMP   $D3
15D2-   D3          ???
15D3-   8D CD C9    STA   $C9CD
15D6-   CE D4 CF    DEC   $CFD4
15D9-   C7          ???
15DA-   A0 C4       LDY   #$C4
15DC-   D3          ???
15DD-   A0 B1       LDY   #$B1
15DF-   A0 BB       LDY   #$BB
15E1-   20 CD C9    JSR   $C9CD
15E4-   CE C9 C6    DEC   $C6C9
15E7-   C9 C5       CMP   #$C5
15E9-   C4 20       CPY   $20
15EB-   D4          ???
15EC-   CF          ???
15ED-   C7          ???
15EE-   C7          ???
15EF-   CC C5 20    CPY   $20C5
15F2-   C6 CC       DEC   $CC
15F4-   C1 C7       CMP   ($C7,X)
15F6-   8D AA 8D    STA   $8DAA
15F9-   AA          TAX
15FA-   AA          TAX
15FB-   20 CC C9    JSR   $C9CC
15FE-   C2          ???
15FF-   D2 C1       CMP   ($C1)
1601-   D2 D9       CMP   ($D9)
1603-   20 C6 CC    JSR   $CCC6
1606-   C1 C7       CMP   ($C7,X)
1608-   D3          ???
1609-   8D AA 8D    STA   $8DAA
160C-   AA          TAX
160D-   AA          TAX
160E-   20 B1 20    JSR   $20B1
1611-   BD 20 C1    LDA   $C120,X
1614-   CC CC 20    CPY   $20CC
1617-   A8          TAY
1618-   C9 CE       CMP   #$CE
161A-   D6 C5       DEC   $C5,X
161C-   D2 D4       CMP   ($D4)
161E-   C5 C4       CMP   $C4
1620-   20 D3 D0    JSR   $D0D3
1623-   C1 C3       CMP   ($C3,X)
1625-   C5 A9       CMP   $A9
1627-   8D AA AA    STA   $AAAA
162A-   20 B2 20    JSR   $20B2
162D-   BD 20 D0    LDA   $D020,X
1630-   C1 D2       CMP   ($D2,X)
1632-   D4          ???
1633-   C9 C1       CMP   #$C1
1635-   CC 20 A8    CPY   $A820
1638-   AA          TAX
1639-   A9 8D       LDA   #$8D
163B-   AA          TAX
163C-   AA          TAX
163D-   20 B3 20    JSR   $20B3
1640-   BD 20 CE    LDA   $CE20,X
1643-   CF          ???
1644-   CE C5 20    DEC   $20C5
1647-   A8          TAY
1648-   C2          ???
1649-   CC C1 CE    CPY   $CEC1
164C-   CB          ???
164D-   20 D3 D0    JSR   $D0D3
1650-   C1 C3       CMP   ($C3,X)
1652-   C5 A9       CMP   $A9
1654-   8D AA 8D    STA   $8DAA
1657-   D3          ???
1658-   D4          ???
1659-   C4 C9       CPY   $C9
165B-   CF          ???
165C-   C6 A0       DEC   $A0
165E-   C4 D3       CPY   $D3
1660-   A0 B2       LDY   #$B2
1662-   A0 BB       LDY   #$BB
1664-   20 D3 D4    JSR   $D4D3
1667-   C4 C9       CPY   $C9
1669-   CF          ???
166A-   20 C6 CC    JSR   $CCC6
166D-   C1 C7       CMP   ($C7,X)
166F-   8D C3 CF    STA   $CFC3
1672-   CD CD CF    CMP   $CFCD
1675-   CE C6 A0    DEC   $A0C6
1678-   C4 D3       CPY   $D3
167A-   A0 B1       LDY   #$B1
167C-   A0 BB       LDY   #$BB
167E-   20 C3 CF    JSR   $CFC3
1681-   CD CD CF    CMP   $CFCD
1684-   CE 20 C6    DEC   $C620
1687-   CC C1 C7    CPY   $C7C1
168A-   8D C1 D2    STA   $D2C1
168D-   D2 C1       CMP   ($C1)
168F-   D9 D3 C6    CMP   $C6D3,Y
1692-   A0 C4       LDY   #$C4
1694-   D3          ???
1695-   A0 B1       LDY   #$B1
1697-   A0 BB       LDY   #$BB
1699-   20 C1 D2    JSR   $D2C1
169C-   D2 C1       CMP   ($C1)
169E-   D9 D3 20    CMP   $20D3,Y
16A1-   C6 CC       DEC   $CC
16A3-   C1 C7       CMP   ($C7,X)
16A5-   8D CD C1    STA   $C1CD
16A8-   D4          ???
16A9-   C8          INY
16AA-   C6 A0       DEC   $A0
16AC-   C4 D3       CPY   $D3
16AE-   A0 B1       LDY   #$B1
16B0-   A0 BB       LDY   #$BB
16B2-   20 CD C1    JSR   $C1CD
16B5-   D4          ???
16B6-   C8          INY
16B7-   20 C6 CC    JSR   $CCC6
16BA-   C1 C7       CMP   ($C7,X)
16BC-   8D D3 D4    STA   $D4D3
16BF-   D2 C9       CMP   ($C9)
16C1-   CE C7 D3    DEC   $D3C7
16C4-   C6 A0       DEC   $A0
16C6-   C4 D3       CPY   $D3
16C8-   A0 B1       LDY   #$B1
16CA-   A0 BB       LDY   #$BB
16CC-   20 D3 D4    JSR   $D4D3
16CF-   D2 C9       CMP   ($C9)
16D1-   CE C7 D3    DEC   $D3C7
16D4-   20 C6 CC    JSR   $CCC6
16D7-   C1 C7       CMP   ($C7,X)
16D9-   8D C6 C9    STA   $C9C6
16DC-   CC C5 C9    CPY   $C9C5
16DF-   CF          ???
16E0-   C6 A0       DEC   $A0
16E2-   C4 D3       CPY   $D3
16E4-   A0 B1       LDY   #$B1
16E6-   A0 BB       LDY   #$BB
16E8-   20 C6 C9    JSR   $C9C6
16EB-   CC C5 C9    CPY   $C9C5
16EE-   CF          ???
16EF-   20 C6 CC    JSR   $CCC6
16F2-   C1 C7       CMP   ($C7,X)
16F4-   8D C3 CF    STA   $CFC3
16F7-   CE D6 C5    DEC   $C5D6
16FA-   D2 D4       CMP   ($D4)
16FC-   C6 A0       DEC   $A0
16FE-   C4 D3       CPY   $D3
1700-   A0 B1       LDY   #$B1
1702-   A0 BB       LDY   #$BB
1704-   20 C3 CF    JSR   $CFC3
1707-   CE D6 C5    DEC   $C5D6
170A-   D2 D3       CMP   ($D3)
170C-   C9 CF       CMP   #$CF
170E-   CE 20 C6    DEC   $C620
1711-   CC C1 C7    CPY   $C7C1
1714-   8D AA 8D    STA   $8DAA
1717-   D4          ???
1718-   CE C1 CD    DEC   $CDC1
171B-   C5 A0       CMP   $A0
171D-   C1 D3       CMP   ($D3,X)
171F-   C3          ???
1720-   A0 A2       LDY   #$A2
1722-   C9 AD       CMP   #$AD
1724-   AD DC 20    LDA   $20DC
1727-   20 C9 20    JSR   $20C9
172A-   20 20 C9    JSR   $C920
172D-   20 C9 20    JSR   $20C9
1730-   C9 20       CMP   #$20
1732-   20 20 20    JSR   $2020
1735-   20 C9 AD    JSR   $ADC9
1738-   AD DC 20    LDA   $20DC
173B-   20 C9 AD    JSR   $ADC9
173E-   AD AD AD    LDA   $ADAD
1741-   20 C9 AD    JSR   $ADC9
1744-   AD DC A2    LDA   $A2DC
1747-   AC B0 B0    LDY   $B0B0
174A-   8D D4 CE    STA   $CED4
174D-   C1 CD       CMP   ($CD,X)
174F-   C5 B2       CMP   $B2
1751-   A0 C1       LDY   #$C1
1753-   D3          ???
1754-   C3          ???
1755-   A0 A2       LDY   #$A2
1757-   C9 20       CMP   #$20
1759-   20 20 A9    JSR   $A920
175C-   20 C9 20    JSR   $20C9
175F-   20 20 C9    JSR   $C920
1762-   20 C9 20    JSR   $20C9
1765-   C9 20       CMP   #$20
1767-   20 20 20    JSR   $2020
176A-   20 C9 20    JSR   $20C9
176D-   20 20 C9    JSR   $C920
1770-   20 C9 20    JSR   $20C9
1773-   20 20 20    JSR   $2020
1776-   20 C9 20    JSR   $20C9
1779-   20 20 A9    JSR   $A920
177C-   A2 AC       LDX   #$AC
177E-   B0 B0       BCS   $1730
1780-   8D D4 CE    STA   $CED4
1783-   C1 CD       CMP   ($CD,X)
1785-   C5 B3       CMP   $B3
1787-   A0 C1       LDY   #$C1
1789-   D3          ???
178A-   C3          ???
178B-   A0 A2       LDY   #$A2
178D-   C9 AD       CMP   #$AD
178F-   AD BC 20    LDA   $20BC
1792-   20 C9 20    JSR   $20C9
1795-   20 20 C9    JSR   $C920
1798-   20 C9 20    JSR   $20C9
179B-   C9 20       CMP   #$20
179D-   20 20 20    JSR   $2020
17A0-   20 C9 20    JSR   $20C9
17A3-   20 20 C9    JSR   $C920
17A6-   20 C9 AD    JSR   $ADC9
17A9-   AD 20 20    LDA   $2020
17AC-   20 C9 AD    JSR   $ADC9
17AF-   AD AF A2    LDA   $A2AF
17B2-   AC B0 B0    LDY   $B0B0
17B5-   8D D4 CE    STA   $CED4
17B8-   C1 CD       CMP   ($CD,X)
17BA-   C5 B4       CMP   $B4
17BC-   A0 C1       LDY   #$C1
17BE-   D3          ???
17BF-   C3          ???
17C0-   A0 A2       LDY   #$A2
17C2-   C9 20       CMP   #$20
17C4-   20 20 A9    JSR   $A920
17C7-   20 C9 20    JSR   $20C9
17CA-   20 20 C9    JSR   $C920
17CD-   20 C9 20    JSR   $20C9
17D0-   C9 20       CMP   #$20
17D2-   20 20 20    JSR   $2020
17D5-   20 C9 20    JSR   $20C9
17D8-   20 20 C9    JSR   $C920
17DB-   20 C9 20    JSR   $20C9
17DE-   20 20 20    JSR   $2020
17E1-   20 C9 20    JSR   $20C9
17E4-   20 DC A2    JSR   $A2DC
17E7-   AC B0 B0    LDY   $B0B0
17EA-   8D D4 CE    STA   $CED4
17ED-   C1 CD       CMP   ($CD,X)
17EF-   C5 B5       CMP   $B5
17F1-   A0 C1       LDY   #$C1
17F3-   D3          ???
17F4-   C3          ???
17F5-   A0 A2       LDY   #$A2
17F7-   C9 AD       CMP   #$AD
17F9-   AD AF 20    LDA   $20AF
17FC-   20 20 AD    JSR   $AD20
17FF-   AD AD 20    LDA   $20AD
1802-   20 C9 20    JSR   $20C9
1805-   C9 AD       CMP   #$AD
1807-   AD AD AD    LDA   $ADAD
180A-   20 C9 AD    JSR   $ADC9
180D-   AD AF 20    LDA   $20AF
1810-   20 C9 AD    JSR   $ADC9
1813-   AD AD AD    LDA   $ADAD
1816-   20 C9 20    JSR   $20C9
1819-   20 20 DC    JSR   $DC20
181C-   A2 AC       LDX   #$AC
181E-   B0 B0       BCS   $17D0
1820-   8D AA 8D    STA   $8DAA
1823-   AA          TAX
1824-   AA          TAX
1825-   AA          TAX
1826-   AA          TAX
1827-   AA          TAX
1828-   AA          TAX
1829-   AA          TAX
182A-   AA          TAX
182B-   AA          TAX
182C-   AA          TAX
182D-   AA          TAX
182E-   AA          TAX
182F-   AA          TAX
1830-   AA          TAX
1831-   AA          TAX
1832-   AA          TAX
1833-   AA          TAX
1834-   AA          TAX
1835-   AA          TAX
1836-   AA          TAX
1837-   AA          TAX
1838-   AA          TAX
1839-   AA          TAX
183A-   AA          TAX
183B-   AA          TAX
183C-   AA          TAX
183D-   AA          TAX
183E-   AA          TAX
183F-   AA          TAX
1840-   AA          TAX
1841-   AA          TAX
1842-   AA          TAX
1843-   8D AA 20    STA   $20AA
1846-   20 20 20    JSR   $2020
1849-   20 20 20    JSR   $2020
184C-   20 20 20    JSR   $2020
184F-   20 20 20    JSR   $2020
1852-   20 20 20    JSR   $2020
1855-   20 20 20    JSR   $2020
1858-   20 20 20    JSR   $2020
185B-   20 20 20    JSR   $2020
185E-   20 20 20    JSR   $2020
1861-   20 20 AA    JSR   $AA20
1864-   8D AA 20    STA   $20AA
1867-   C2          ???
1868-   D5 C9       CMP   $C9,X
186A-   CC C4 C5    CPY   $C5C4
186D-   D2 20       CMP   ($20)
186F-   D3          ???
1870-   D0 C5       BNE   $1837
1872-   C3          ???
1873-   C9 C6       CMP   #$C6
1875-   C9 C3       CMP   #$C3
1877-   20 D3 D5    JSR   $D5D3
187A-   C2          ???
187B-   D2 CF       CMP   ($CF)
187D-   D5 D4       CMP   $D4,X
187F-   C9 CE       CMP   #$CE
1881-   C5 D3       CMP   $D3
1883-   20 AA 8D    JSR   $8DAA
1886-   AA          TAX
1887-   20 20 20    JSR   $2020
188A-   20 20 20    JSR   $2020
188D-   20 20 20    JSR   $2020
1890-   20 20 20    JSR   $2020
1893-   20 20 20    JSR   $2020
1896-   20 20 20    JSR   $2020
1899-   20 20 20    JSR   $2020
189C-   20 20 20    JSR   $2020
189F-   20 20 20    JSR   $2020
18A2-   20 20 20    JSR   $2020
18A5-   AA          TAX
18A6-   8D AA AA    STA   $AAAA
18A9-   AA          TAX
18AA-   AA          TAX
18AB-   AA          TAX
18AC-   AA          TAX
18AD-   AA          TAX
18AE-   AA          TAX
18AF-   AA          TAX
18B0-   AA          TAX
18B1-   AA          TAX
18B2-   AA          TAX
18B3-   AA          TAX
18B4-   AA          TAX
18B5-   AA          TAX
18B6-   AA          TAX
18B7-   AA          TAX
18B8-   AA          TAX
18B9-   AA          TAX
18BA-   AA          TAX
18BB-   AA          TAX
18BC-   AA          TAX
18BD-   AA          TAX
18BE-   AA          TAX
18BF-   AA          TAX
18C0-   AA          TAX
18C1-   AA          TAX
18C2-   AA          TAX
18C3-   AA          TAX
18C4-   AA          TAX
18C5-   AA          TAX
18C6-   AA          TAX
18C7-   8D AA 8D    STA   $8DAA
18CA-   A0 D0       LDY   #$D0
18CC-   D5 D4       CMP   $D4,X
18CE-   A0 CC       LDY   #$CC
18D0-   C9 C2       CMP   #$C2
18D2-   AE CD C5    LDX   $C5CD
18D5-   CE D5 8D    DEC   $8DD5
18D8-   A0 D0       LDY   #$D0
18DA-   D5 D4       CMP   $D4,X
18DC-   A0 D3       LDY   #$D3
18DE-   D5 C2       CMP   $C2,X
18E0-   AE C6 D0    LDX   $D0C6
18E3-   CF          ???
18E4-   D0 8D       BNE   $1873
18E6-   AA          TAX
18E7-   8D AA AA    STA   $AAAA
18EA-   AA          TAX
18EB-   AA          TAX
18EC-   AA          TAX
18ED-   AA          TAX
18EE-   AA          TAX
18EF-   AA          TAX
18F0-   AA          TAX
18F1-   AA          TAX
18F2-   AA          TAX
18F3-   AA          TAX
18F4-   AA          TAX
18F5-   AA          TAX
18F6-   AA          TAX
18F7-   AA          TAX
18F8-   AA          TAX
18F9-   AA          TAX
18FA-   AA          TAX
18FB-   AA          TAX
18FC-   AA          TAX
18FD-   AA          TAX
18FE-   AA          TAX
18FF-   AA          TAX
1900-   AA          TAX
1901-   AA          TAX
1902-   AA          TAX
1903-   AA          TAX
1904-   AA          TAX
1905-   AA          TAX
1906-   AA          TAX
1907-   AA          TAX
1908-   8D AA 20    STA   $20AA
190B-   20 20 20    JSR   $2020
190E-   20 20 20    JSR   $2020
1911-   20 20 20    JSR   $2020
1914-   20 20 20    JSR   $2020
1917-   20 20 20    JSR   $2020
191A-   20 20 20    JSR   $2020
191D-   20 20 20    JSR   $2020
1920-   20 20 20    JSR   $2020
1923-   20 20 20    JSR   $2020
1926-   20 20 AA    JSR   $AA20
1929-   8D AA 20    STA   $20AA
192C-   20 CC CF    JSR   $CFCC
192F-   D7          ???
1930-   AD CC C5    LDA   $C5CC
1933-   D6 C5       DEC   $C5,X
1935-   CC 20 D2    CPY   $D220
1938-   CF          ???
1939-   D5 D4       CMP   $D4,X
193B-   C9 CE       CMP   #$CE
193D-   C5 D3       CMP   $D3
193F-   20 20 20    JSR   $2020
1942-   20 20 20    JSR   $2020
1945-   20 20 20    JSR   $2020
1948-   20 AA 8D    JSR   $8DAA
194B-   AA          TAX
194C-   20 20 20    JSR   $2020
194F-   20 20 20    JSR   $2020
1952-   20 20 20    JSR   $2020
1955-   20 20 20    JSR   $2020
1958-   20 20 20    JSR   $2020
195B-   20 20 20    JSR   $2020
195E-   20 20 20    JSR   $2020
1961-   20 20 20    JSR   $2020
1964-   20 20 20    JSR   $2020
1967-   20 20 20    JSR   $2020
196A-   AA          TAX
196B-   8D AA AA    STA   $AAAA
196E-   AA          TAX
196F-   AA          TAX
1970-   AA          TAX
1971-   AA          TAX
1972-   AA          TAX
1973-   AA          TAX
1974-   AA          TAX
1975-   AA          TAX
1976-   AA          TAX
1977-   AA          TAX
1978-   AA          TAX
1979-   AA          TAX
197A-   AA          TAX
197B-   AA          TAX
197C-   AA          TAX
197D-   AA          TAX
197E-   AA          TAX
197F-   AA          TAX
1980-   AA          TAX
1981-   AA          TAX
1982-   AA          TAX
1983-   AA          TAX
1984-   AA          TAX
1985-   AA          TAX
1986-   AA          TAX
1987-   AA          TAX
1988-   AA          TAX
1989-   AA          TAX
198A-   AA          TAX
198B-   AA          TAX
198C-   8D AA 8D    STA   $8DAA
198F-   A0 CC       LDY   #$CC
1991-   D3          ???
1992-   D4          ???
1993-   A0 CF       LDY   #$CF
1995-   C6 C6       DEC   $C6
1997-   8D AA 8D    STA   $8DAA
199A-   A0 D0       LDY   #$D0
199C-   D5 D4       CMP   $D4,X
199E-   A0 CD       LDY   #$CD
19A0-   C9 CE       CMP   #$CE
19A2-   AE CC C9    LDX   $C9CC
19A5-   C2          ???
19A6-   AE D2 C5    LDX   $C5D2
19A9-   D1 D5       CMP   ($D5),Y
19AB-   C9 D2       CMP   #$D2
19AD-   C5 C4       CMP   $C4
19AF-   8D AA 8D    STA   $8DAA
19B2-   AA          TAX
19B3-   AA          TAX
19B4-   20 C9 CE    JSR   $CEC9
19B7-   C4 C9       CPY   $C9
19B9-   D6 C9       DEC   $C9,X
19BB-   C4 D5       CPY   $D5
19BD-   C1 CC       CMP   ($CC,X)
19BF-   20 D3 D5    JSR   $D5D3
19C2-   C2          ???
19C3-   D2 CF       CMP   ($CF)
19C5-   D5 D4       CMP   $D4,X
19C7-   C9 CE       CMP   #$CE
19C9-   C5 D3       CMP   $D3
19CB-   8D AA 8D    STA   $8DAA
19CE-   AA          TAX
19CF-   AA          TAX
19D0-   20 C1 D2    JSR   $D2C1
19D3-   D2 C1       CMP   ($C1)
19D5-   D9 D3 8D    CMP   $8DD3,Y
19D8-   AA          TAX
19D9-   8D A0 D0    STA   $D0A0
19DC-   D5 D4       CMP   $D4,X
19DE-   A0 CD       LDY   #$CD
19E0-   C9 CE       CMP   #$CE
19E2-   AE D3 D5    LDX   $D5D3
19E5-   C2          ???
19E6-   AE C1 C4    LDX   $C4C1
19E9-   C9 CD       CMP   #$CD
19EB-   B8          CLV
19EC-   B1 8D       LDA   ($8D),Y
19EE-   AA          TAX
19EF-   D0 D5       BNE   $19C6
19F1-   D4          ???
19F2-   20 CD C9    JSR   $C9CD
19F5-   CE AE D3    DEC   $D3AE
19F8-   D5 C2       CMP   $C2,X
19FA-   AE C1 C4    LDX   $C4C1
19FD-   C9 CD       CMP   #$CD
19FF-   B8          CLV
1A00-   B2 8D       LDA   ($8D)
1A02-   A0 D0       LDY   #$D0
1A04-   D5 D4       CMP   $D4,X
1A06-   A0 CD       LDY   #$CD
1A08-   C9 CE       CMP   #$CE
1A0A-   AE D3 D5    LDX   $D5D3
1A0D-   C2          ???
1A0E-   AE C1 C7    LDX   $C7C1
1A11-   C5 D4       CMP   $D4
1A13-   B8          CLV
1A14-   B1 8D       LDA   ($8D),Y
1A16-   AA          TAX
1A17-   D0 D5       BNE   $19EE
1A19-   D4          ???
1A1A-   20 CD C9    JSR   $C9CD
1A1D-   CE AE D3    DEC   $D3AE
1A20-   D5 C2       CMP   $C2,X
1A22-   AE C1 C7    LDX   $C7C1
1A25-   C5 D4       CMP   $D4
1A27-   B8          CLV
1A28-   B2 8D       LDA   ($8D)
1A2A-   A0 D0       LDY   #$D0
1A2C-   D5 D4       CMP   $D4,X
1A2E-   A0 CD       LDY   #$CD
1A30-   C9 CE       CMP   #$CE
1A32-   AE D3 D5    LDX   $D5D3
1A35-   C2          ???
1A36-   AE C1 D0    LDX   $D0C1
1A39-   D5 D4       CMP   $D4,X
1A3B-   B8          CLV
1A3C-   B1 8D       LDA   ($8D),Y
1A3E-   AA          TAX
1A3F-   D0 D5       BNE   $1A16
1A41-   D4          ???
1A42-   20 CD C9    JSR   $C9CD
1A45-   CE AE D3    DEC   $D3AE
1A48-   D5 C2       CMP   $C2,X
1A4A-   AE C1 D0    LDX   $D0C1
1A4D-   D5 D4       CMP   $D4,X
1A4F-   B8          CLV
1A50-   B2 8D       LDA   ($8D)
1A52-   AA          TAX
1A53-   8D AA AA    STA   $AAAA
1A56-   20 D3 D4    JSR   $D4D3
1A59-   C4 C9       CPY   $C9
1A5B-   CF          ???
1A5C-   8D AA 8D    STA   $8DAA
1A5F-   AA          TAX
1A60-   D0 D5       BNE   $1A37
1A62-   D4          ???
1A63-   20 CD C9    JSR   $C9CD
1A66-   CE AE D3    DEC   $D3AE
1A69-   D5 C2       CMP   $C2,X
1A6B-   AE C3 D5    LDX   $D5C3
1A6E-   D2 D3       CMP   ($D3)
1A70-   CF          ???
1A71-   D2 D5       CMP   ($D5)
1A73-   C4 C2       CPY   $C2
1A75-   C6 8D       DEC   $8D
1A77-   A0 D0       LDY   #$D0
1A79-   D5 D4       CMP   $D4,X
1A7B-   A0 CD       LDY   #$CD
1A7D-   C9 CE       CMP   #$CE
1A7F-   AE D3 D5    LDX   $D5D3
1A82-   C2          ???
1A83-   AE C4 D0    LDX   $D0C4
1A86-   D2 C9       CMP   ($C9)
1A88-   CE D4 8D    DEC   $8DD4
1A8B-   A0 D0       LDY   #$D0
1A8D-   D5 D4       CMP   $D4,X
1A8F-   A0 CD       LDY   #$CD
1A91-   C9 CE       CMP   #$CE
1A93-   AE D3 D5    LDX   $D5D3
1A96-   C2          ???
1A97-   AE D3 C9    LDX   $C9D3
1A9A-   CE D0 D5    DEC   $D5D0
1A9D-   D4          ???
1A9E-   8D A0 D0    STA   $D0A0
1AA1-   D5 D4       CMP   $D4,X
1AA3-   A0 CD       LDY   #$CD
1AA5-   C9 CE       CMP   #$CE
1AA7-   AE D3 D5    LDX   $D5D3
1AAA-   C2          ???
1AAB-   AE D4 C6    LDX   $C6D4
1AAE-   C9 CC       CMP   #$CC
1AB0-   CC C1 8D    CPY   $8DC1
1AB3-   A0 D0       LDY   #$D0
1AB5-   D5 D4       CMP   $D4,X
1AB7-   A0 CD       LDY   #$CD
1AB9-   C9 CE       CMP   #$CE
1ABB-   AE D3 D5    LDX   $D5D3
1ABE-   C2          ???
1ABF-   AE D4 C8    LDX   $C8D4
1AC2-   CC C9 CE    CPY   $CEC9
1AC5-   C5 8D       CMP   $8D
1AC7-   A0 D0       LDY   #$D0
1AC9-   D5 D4       CMP   $D4,X
1ACB-   A0 CD       LDY   #$CD
1ACD-   C9 CE       CMP   #$CE
1ACF-   AE D3 D5    LDX   $D5D3
1AD2-   C2          ???
1AD3-   AE D4 D6    LDX   $D6D4
1AD6-   CC C9 CE    CPY   $CEC9
1AD9-   C5 8D       CMP   $8D
1ADB-   A0 D0       LDY   #$D0
1ADD-   D5 D4       CMP   $D4,X
1ADF-   A0 CD       LDY   #$CD
1AE1-   C9 CE       CMP   #$CE
1AE3-   AE D3 D5    LDX   $D5D3
1AE6-   C2          ???
1AE7-   AE D4 D8    LDX   $D8D4
1AEA-   D4          ???
1AEB-   D0 D5       BNE   $1AC2
1AED-   D4          ???
1AEE-   8D A0 D0    STA   $D0A0
1AF1-   D5 D4       CMP   $D4,X
1AF3-   A0 CD       LDY   #$CD
1AF5-   C9 CE       CMP   #$CE
1AF7-   AE D3 D5    LDX   $D5D3
1AFA-   C2          ???
1AFB-   AE D8 D0    LDX   $D0D8
1AFE-   D2 C9       CMP   ($C9)
1B00-   CE D4 8D    DEC   $8DD4
1B03-   AA          TAX
1B04-   8D AA AA    STA   $AAAA
1B07-   20 C6 C9    JSR   $C9C6
1B0A-   CC C5 C9    CPY   $C9C5
1B0D-   CF          ???
1B0E-   8D AA 8D    STA   $8DAA
1B11-   A0 D0       LDY   #$D0
1B13-   D5 D4       CMP   $D4,X
1B15-   A0 CD       LDY   #$CD
1B17-   C9 CE       CMP   #$CE
1B19-   AE D3 D5    LDX   $D5D3
1B1C-   C2          ???
1B1D-   AE C6 D0    LDX   $D0C6
1B20-   D3          ???
1B21-   D4          ???
1B22-   D2 8D       CMP   ($8D)
1B24-   A0 D0       LDY   #$D0
1B26-   D5 D4       CMP   $D4,X
1B28-   A0 CD       LDY   #$CD
1B2A-   C9 CE       CMP   #$CE
1B2C-   AE D3 D5    LDX   $D5D3
1B2F-   C2          ???
1B30-   AE C6 D0    LDX   $D0C6
1B33-   D2 C9       CMP   ($C9)
1B35-   CE D4 8D    DEC   $8DD4
1B38-   A0 D0       LDY   #$D0
1B3A-   D5 D4       CMP   $D4,X
1B3C-   A0 CD       LDY   #$CD
1B3E-   C9 CE       CMP   #$CE
1B40-   AE D3 D5    LDX   $D5D3
1B43-   C2          ???
1B44-   AE C6 C9    LDX   $C9C6
1B47-   CE D0 D5    DEC   $D5D0
1B4A-   D4          ???
1B4B-   8D A0 D0    STA   $D0A0
1B4E-   D5 D4       CMP   $D4,X
1B50-   A0 CD       LDY   #$CD
1B52-   C9 CE       CMP   #$CE
1B54-   AE D3 D5    LDX   $D5D3
1B57-   C2          ???
1B58-   AE C4 CF    LDX   $CFC4
1B5B-   D3          ???
1B5C-   C3          ???
1B5D-   CD C4 8D    CMP   $8DC4
1B60-   A0 D0       LDY   #$D0
1B62-   D5 D4       CMP   $D4,X
1B64-   A0 CD       LDY   #$CD
1B66-   C9 CE       CMP   #$CE
1B68-   AE D3 D5    LDX   $D5D3
1B6B-   C2          ???
1B6C-   AE C2 C9    LDX   $C9C2
1B6F-   CE D3 C1    DEC   $C1D3
1B72-   D6 C5       DEC   $C5,X
1B74-   8D A0 D0    STA   $D0A0
1B77-   D5 D4       CMP   $D4,X
1B79-   A0 CD       LDY   #$CD
1B7B-   C9 CE       CMP   #$CE
1B7D-   AE D3 D5    LDX   $D5D3
1B80-   C2          ???
1B81-   AE C2 C9    LDX   $C9C2
1B84-   CE CC CF    DEC   $CFCC
1B87-   C1 C4       CMP   ($C4,X)
1B89-   8D AA 8D    STA   $8DAA
1B8C-   AA          TAX
1B8D-   AA          TAX
1B8E-   20 C3 CF    JSR   $CFC3
1B91-   CE D6 C5    DEC   $C5D6
1B94-   D2 D3       CMP   ($D3)
1B96-   C9 CF       CMP   #$CF
1B98-   CE 8D AA    DEC   $AA8D
1B9B-   8D A0 D0    STA   $D0A0
1B9E-   D5 D4       CMP   $D4,X
1BA0-   A0 CD       LDY   #$CD
1BA2-   C9 CE       CMP   #$CE
1BA4-   AE D3 D5    LDX   $D5D3
1BA7-   C2          ???
1BA8-   AE C8 C5    LDX   $C5C8
1BAB-   D8          CLD
1BAC-   B2 C8       LDA   ($C8)
1BAE-   C5 D8       CMP   $D8
1BB0-   C1 D3       CMP   ($D3,X)
1BB2-   C3          ???
1BB3-   8D AA 8D    STA   $8DAA
1BB6-   AA          TAX
1BB7-   AA          TAX
1BB8-   20 D3 D4    JSR   $D4D3
1BBB-   D2 C9       CMP   ($C9)
1BBD-   CE C7 D3    DEC   $D3C7
1BC0-   8D AA 8D    STA   $8DAA
1BC3-   A0 D0       LDY   #$D0
1BC5-   D5 D4       CMP   $D4,X
1BC7-   A0 CD       LDY   #$CD
1BC9-   C9 CE       CMP   #$CE
1BCB-   AE D3 D5    LDX   $D5D3
1BCE-   C2          ???
1BCF-   AE D3 D4    LDX   $D4D3
1BD2-   D2 C3       CMP   ($C3)
1BD4-   C1 D4       CMP   ($D4,X)
1BD6-   8D A0 D0    STA   $D0A0
1BD9-   D5 D4       CMP   $D4,X
1BDB-   A0 CD       LDY   #$CD
1BDD-   C9 CE       CMP   #$CE
1BDF-   AE D3 D5    LDX   $D5D3
1BE2-   C2          ???
1BE3-   AE D3 D4    LDX   $D4D3
1BE6-   D2 C3       CMP   ($C3)
1BE8-   CF          ???
1BE9-   CD D0 8D    CMP   $8DD0
1BEC-   A0 D0       LDY   #$D0
1BEE-   D5 D4       CMP   $D4,X
1BF0-   A0 CD       LDY   #$CD
1BF2-   C9 CE       CMP   #$CE
1BF4-   AE D3 D5    LDX   $D5D3
1BF7-   C2          ???
1BF8-   AE D3 D5    LDX   $D5D3
1BFB-   C2          ???
1BFC-   C3          ???
1BFD-   CF          ???
1BFE-   D0 D9       BNE   $1BD9
1C00-   8D A0 D0    STA   $D0A0
1C03-   D5 D4       CMP   $D4,X
1C05-   A0 CD       LDY   #$CD
1C07-   C9 CE       CMP   #$CE
1C09-   AE D3 D5    LDX   $D5D3
1C0C-   C2          ???
1C0D-   AE D3 D5    LDX   $D5D3
1C10-   C2          ???
1C11-   C4 C5       CPY   $C5
1C13-   CC 8D A0    CPY   $A08D
1C16-   D0 D5       BNE   $1BED
1C18-   D4          ???
1C19-   A0 CD       LDY   #$CD
1C1B-   C9 CE       CMP   #$CE
1C1D-   AE D3 D5    LDX   $D5D3
1C20-   C2          ???
1C21-   AE D3 D5    LDX   $D5D3
1C24-   C2          ???
1C25-   C9 CE       CMP   #$CE
1C27-   D3          ???
1C28-   8D A0 D0    STA   $D0A0
1C2B-   D5 D4       CMP   $D4,X
1C2D-   A0 CD       LDY   #$CD
1C2F-   C9 CE       CMP   #$CE
1C31-   AE D3 D5    LDX   $D5D3
1C34-   C2          ???
1C35-   AE D3 D5    LDX   $D5D3
1C38-   C2          ???
1C39-   D0 CF       BNE   $1C0A
1C3B-   D3          ???
1C3C-   8D A0 CC    STA   $CCA0
1C3F-   D3          ???
1C40-   D4          ???
1C41-   A0 CF       LDY   #$CF
1C43-   CE 8D A0    DEC   $A08D
1C46-   D0 D5       BNE   $1C1D
1C48-   D4          ???
1C49-   A0 CD       LDY   #$CD
1C4B-   C9 CE       CMP   #$CE
1C4D-   AE D3 D5    LDX   $D5D3
1C50-   C2          ???
1C51-   AE D0 D2    LDX   $D2D0
1C54-   CE D3 D4    DEC   $D4D3
1C57-   D2 8D       CMP   ($8D)
1C59-   AA          TAX
1C5A-   8D 00 00    STA   $0000
