0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C3    LDY   $C320,X
0950-   CF          ???
0951-   CD CD CF    CMP   $CFCD
0954-   CE 20 C4    DEC   $C420
0957-   C5 CD       CMP   $CD
0959-   CF          ???
095A-   20 A9 AD    JSR   $ADA9
095D-   20 20 20    JSR   $2020
0960-   20 20 20    JSR   $2020
0963-   20 AA 8D    JSR   $8DAA
0966-   AA          TAX
0967-   20 20 20    JSR   $2020
096A-   20 20 20    JSR   $2020
096D-   20 20 20    JSR   $2020
0970-   20 20 20    JSR   $2020
0973-   20 20 20    JSR   $2020
0976-   20 20 20    JSR   $2020
0979-   20 20 20    JSR   $2020
097C-   20 20 20    JSR   $2020
097F-   20 20 20    JSR   $2020
0982-   20 20 20    JSR   $2020
0985-   AA          TAX
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B0       BCS   $094C
099C-   AE B0 B1    LDX   $B1B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B0    JSR   $B020
09D4-   B3          ???
09D5-   AF          ???
09D6-   B0 B4       BCS   $098C
09D8-   AF          ???
09D9-   B1 B9       LDA   ($B9),Y
09DB-   B8          CLV
09DC-   B0 20       BCS   $09FE
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 C4    STA   $C4A0
0B02-   D3          ???
0B03-   CB          ???
0B04-   A0 C3       LDY   #$C3
0B06-   CF          ???
0B07-   CD CD CF    CMP   $CFCD
0B0A-   CE AE C4    DEC   $C4AE
0B0D-   C5 CD       CMP   $CD
0B0F-   CF          ???
0B10-   8D AA 8D    STA   $8DAA
0B13-   AA          TAX
0B14-   E0 E0       CPX   #$E0
0B16-   E0 E0       CPX   #$E0
0B18-   E0 E0       CPX   #$E0
0B1A-   E0 E0       CPX   #$E0
0B1C-   E0 E0       CPX   #$E0
0B1E-   E0 E0       CPX   #$E0
0B20-   E0 E0       CPX   #$E0
0B22-   E0 E0       CPX   #$E0
0B24-   E0 E0       CPX   #$E0
0B26-   E0 E0       CPX   #$E0
0B28-   E0 E0       CPX   #$E0
0B2A-   E0 E0       CPX   #$E0
0B2C-   E0 E0       CPX   #$E0
0B2E-   E0 E0       CPX   #$E0
0B30-   E0 E0       CPX   #$E0
0B32-   AA          TAX
0B33-   8D AA 20    STA   $20AA
0B36-   20 D4 CF    JSR   $CFD4
0B39-   D0 20       BNE   $0B5B
0B3B-   C9 CE       CMP   #$CE
0B3D-   C3          ???
0B3E-   CC D5 C4    CPY   $C4D5
0B41-   C5 D3       CMP   $D3
0B43-   20 A8 D0    JSR   $D0A8
0B46-   D5 D4       CMP   $D4,X
0B48-   D3          ???
0B49-   AC 20 CD    LDY   $CD20
0B4C-   C1 C3       CMP   ($C3,X)
0B4E-   D2 CF       CMP   ($CF)
0B50-   D3          ???
0B51-   A9 20       LDA   #$20
0B53-   AA          TAX
0B54-   8D AA AC    STA   $ACAA
0B57-   AC AC AC    LDY   $ACAC
0B5A-   AC AC AC    LDY   $ACAC
0B5D-   AC AC AC    LDY   $ACAC
0B60-   AC AC AC    LDY   $ACAC
0B63-   AC AC AC    LDY   $ACAC
0B66-   AC AC AC    LDY   $ACAC
0B69-   AC AC AC    LDY   $ACAC
0B6C-   AC AC AC    LDY   $ACAC
0B6F-   AC AC AC    LDY   $ACAC
0B72-   AC AC AA    LDY   $AAAC
0B75-   8D AA 8D    STA   $8DAA
0B78-   A0 D0       LDY   #$D0
0B7A-   D5 D4       CMP   $D4,X
0B7C-   A0 C4       LDY   #$C4
0B7E-   C5 C3       CMP   $C3
0B80-   D3          ???
0B81-   8D A0 D5    STA   $D5A0
0B84-   D3          ???
0B85-   C5 A0       CMP   $A0
0B87-   C3          ???
0B88-   CF          ???
0B89-   CD CD CF    CMP   $CFCD
0B8C-   CE AE CD    DEC   $CDAE
0B8F-   C1 C3       CMP   ($C3,X)
0B91-   8D AA 8D    STA   $8DAA
0B94-   A0 D0       LDY   #$D0
0B96-   D5 D4       CMP   $D4,X
0B98-   20 A0 C3    JSR   $C3A0
0B9B-   CF          ???
0B9C-   CD CD CF    CMP   $CFCD
0B9F-   CE AE C8    DEC   $C8AE
0BA2-   CF          ???
0BA3-   CF          ???
0BA4-   CB          ???
0BA5-   D3          ???
0BA6-   8D AA 8D    STA   $8DAA
0BA9-   A0 CF       LDY   #$CF
0BAB-   D2 C7       CMP   ($C7)
0BAD-   A0 A4       LDY   #$A4
0BAF-   B6 B0       LDX   $B0,Y
0BB1-   B0 B0       BCS   $0B63
0BB3-   8D AA 8D    STA   $8DAA
0BB6-   AA          TAX
0BB7-   E0 E0       CPX   #$E0
0BB9-   E0 E0       CPX   #$E0
0BBB-   E0 E0       CPX   #$E0
0BBD-   E0 E0       CPX   #$E0
0BBF-   E0 E0       CPX   #$E0
0BC1-   E0 E0       CPX   #$E0
0BC3-   E0 E0       CPX   #$E0
0BC5-   E0 E0       CPX   #$E0
0BC7-   E0 E0       CPX   #$E0
0BC9-   E0 E0       CPX   #$E0
0BCB-   E0 E0       CPX   #$E0
0BCD-   E0 E0       CPX   #$E0
0BCF-   E0 E0       CPX   #$E0
0BD1-   E0 E0       CPX   #$E0
0BD3-   E0 E0       CPX   #$E0
0BD5-   AA          TAX
0BD6-   8D AA 20    STA   $20AA
0BD9-   20 20 20    JSR   $2020
0BDC-   20 20 D0    JSR   $D020
0BDF-   D2 CF       CMP   ($CF)
0BE1-   C7          ???
0BE2-   D2 C1       CMP   ($C1)
0BE4-   CD 20 CD    CMP   $CD20
0BE7-   C1 C9       CMP   ($C9,X)
0BE9-   CE 20 C2    DEC   $C220
0BEC-   CF          ???
0BED-   C4 D9       CPY   $D9
0BEF-   20 20 20    JSR   $2020
0BF2-   20 20 20    JSR   $2020
0BF5-   20 AA 8D    JSR   $8DAA
0BF8-   AA          TAX
0BF9-   AC AC AC    LDY   $ACAC
0BFC-   AC AC AC    LDY   $ACAC
0BFF-   AC AC AC    LDY   $ACAC
0C02-   AC AC AC    LDY   $ACAC
0C05-   AC AC AC    LDY   $ACAC
0C08-   AC AC AC    LDY   $ACAC
0C0B-   AC AC AC    LDY   $ACAC
0C0E-   AC AC AC    LDY   $ACAC
0C11-   AC AC AC    LDY   $ACAC
0C14-   AC AC AC    LDY   $ACAC
0C17-   AA          TAX
0C18-   8D AA 8D    STA   $8DAA
0C1B-   AA          TAX
0C1C-   8D AA 8D    STA   $8DAA
0C1F-   AA          TAX
0C20-   AA          TAX
0C21-   20 C2 C9    JSR   $C9C2
0C24-   C7          ???
0C25-   20 CC D5    JSR   $D5CC
0C28-   CD D0 D3    CMP   $D3D0
0C2B-   20 AD AD    JSR   $ADAD
0C2E-   20 C8 C9    JSR   $C9C8
0C31-   C7          ???
0C32-   C8          INY
0C33-   20 CC C5    JSR   $C5CC
0C36-   D6 C5       DEC   $C5,X
0C38-   CC 20 C3    CPY   $C320
0C3B-   CF          ???
0C3C-   C4 C5       CPY   $C5
0C3E-   8D AA 8D    STA   $8DAA
0C41-   AA          TAX
0C42-   8D AA AA    STA   $AAAA
0C45-   20 CD C5    JSR   $C5CD
0C48-   CD C6 C9    CMP   $C9C6
0C4B-   CC CC 20    CPY   $20CC
0C4E-   C4 CF       CPY   $CF
0C50-   C5 D3       CMP   $D3
0C52-   20 C1 C2    JSR   $C2C1
0C55-   CF          ???
0C56-   D5 D4       CMP   $D4,X
0C58-   20 D7 C8    JSR   $C8D7
0C5B-   C1 D4       CMP   ($D4,X)
0C5D-   20 C9 D4    JSR   $D4C9
0C60-   D3          ???
0C61-   20 CE C1    JSR   $C1CE
0C64-   CD C5 8D    CMP   $8DC5
0C67-   AA          TAX
0C68-   AA          TAX
0C69-   20 C9 CD    JSR   $CDC9
0C6C-   D0 CC       BNE   $0C3A
0C6E-   C9 C5       CMP   #$C5
0C70-   D3          ???
0C71-   BA          TSX
0C72-   20 C9 D4    JSR   $D4C9
0C75-   20 C6 C9    JSR   $C9C6
0C78-   CC CC D3    CPY   $D3CC
0C7B-   20 C1 20    JSR   $20C1
0C7E-   C2          ???
0C7F-   CC CF C3    CPY   $C3CF
0C82-   CB          ???
0C83-   20 CF C6    JSR   $C6CF
0C86-   20 CD C5    JSR   $C5CD
0C89-   CD CF D2    CMP   $D2CF
0C8C-   D9 8D AA    CMP   $AA8D,Y
0C8F-   AA          TAX
0C90-   20 D7 C9    JSR   $C9D7
0C93-   D4          ???
0C94-   C8          INY
0C95-   20 C1 20    JSR   $20C1
0C98-   D0 C1       BNE   $0C5B
0C9A-   D2 D4       CMP   ($D4)
0C9C-   C9 C3       CMP   #$C3
0C9E-   D5 CC       CMP   $CC,X
0CA0-   C1 D2       CMP   ($D2,X)
0CA2-   20 C3 C8    JSR   $C8C3
0CA5-   C1 D2       CMP   ($D2,X)
0CA7-   C1 C3       CMP   ($C3,X)
0CA9-   D4          ???
0CAA-   C5 D2       CMP   $D2
0CAC-   AE 20 D4    LDX   $D420
0CAF-   CF          ???
0CB0-   20 D3 C5    JSR   $C5D3
0CB3-   C5 8D       CMP   $8D
0CB5-   AA          TAX
0CB6-   AA          TAX
0CB7-   20 D4 C8    JSR   $C8D4
0CBA-   C9 D3       CMP   #$D3
0CBC-   20 C9 CE    JSR   $CEC9
0CBF-   20 C1 C3    JSR   $C3C1
0CC2-   D4          ???
0CC3-   C9 CF       CMP   #$CF
0CC5-   CE AC 20    DEC   $20AC
0CC8-   C8          INY
0CC9-   C5 C1       CMP   $C1
0CCB-   C4 20       CPY   $20
0CCD-   CF          ???
0CCE-   D6 C5       DEC   $C5,X
0CD0-   D2 20       CMP   ($20)
0CD2-   D4          ???
0CD3-   CF          ???
0CD4-   20 D4 C8    JSR   $C8D4
0CD7-   C5 8D       CMP   $8D
0CD9-   AA          TAX
0CDA-   AA          TAX
0CDB-   20 CD CF    JSR   $CFCD
0CDE-   CE C9 D4    DEC   $D4C9
0CE1-   CF          ???
0CE2-   D2 20       CMP   ($20)
0CE4-   C2          ???
0CE5-   C5 C6       CMP   $C6
0CE7-   CF          ???
0CE8-   D2 C5       CMP   ($C5)
0CEA-   20 C1 CE    JSR   $CEC1
0CED-   C4 20       CPY   $20
0CEF-   C1 C6       CMP   ($C6,X)
0CF1-   D4          ???
0CF2-   C5 D2       CMP   $D2
0CF4-   20 D4 C8    JSR   $C8D4
0CF7-   C9 D3       CMP   #$D3
0CF9-   20 D2 D5    JSR   $D5D2
0CFC-   CE D3 8D    DEC   $8DD3
0CFF-   AA          TAX
0D00-   AA          TAX
0D01-   20 C1 CE    JSR   $CEC1
0D04-   C4 20       CPY   $20
0D06-   D4          ???
0D07-   D9 D0 C5    CMP   $C5D0,Y
0D0A-   20 B3 B0    JSR   $B0B3
0D0D-   B0 CC       BCS   $0CDB
0D0F-   AE 8D AA    LDX   $AA8D
0D12-   8D AA AA    STA   $AAAA
0D15-   20 D4 C8    JSR   $C8D4
0D18-   C5 20       CMP   $20
0D1A-   D3          ???
0D1B-   C1 CD       CMP   ($CD,X)
0D1D-   C5 20       CMP   $20
0D1F-   C1 D3       CMP   ($D3,X)
0D21-   20 C2 C5    JSR   $C5C2
0D24-   CC CF D7    CPY   $D7CF
0D27-   20 C3 C1    JSR   $C1C3
0D2A-   CE 20 C2    DEC   $C220
0D2D-   C5 20       CMP   $20
0D2F-   C1 C3       CMP   ($C3,X)
0D31-   C3          ???
0D32-   CF          ???
0D33-   CD D0 CC    CMP   $CCD0
0D36-   C9 D3       CMP   #$D3
0D38-   C8          INY
0D39-   C5 C4       CMP   $C4
0D3B-   8D AA AA    STA   $AAAA
0D3E-   20 D7 C9    JSR   $C9D7
0D41-   D4          ???
0D42-   C8          INY
0D43-   20 D4 C8    JSR   $C8D4
0D46-   C5 20       CMP   $20
0D48-   C6 CF       DEC   $CF
0D4A-   CC CC CF    CPY   $CFCC
0D4D-   D7          ???
0D4E-   C9 CE       CMP   #$CE
0D50-   C7          ???
0D51-   20 CD C1    JSR   $C1CD
0D54-   C3          ???
0D55-   D2 CF       CMP   ($CF)
0D57-   BA          TSX
0D58-   8D AA 8D    STA   $8DAA
0D5B-   AA          TAX
0D5C-   AA          TAX
0D5D-   20 20 20    JSR   $2020
0D60-   20 20 20    JSR   $2020
0D63-   20 DF CD    JSR   $CDDF
0D66-   C6 C9       DEC   $C9
0D68-   CC 20 A4    CPY   $A420
0D6B-   B3          ???
0D6C-   B0 B0       BCS   $0D1E
0D6E-   BB          ???
0D6F-   A3          ???
0D70-   B1 B0       LDA   ($B0),Y
0D72-   BB          ???
0D73-   A3          ???
0D74-   B0 8D       BCS   $0D03
0D76-   AA          TAX
0D77-   8D A0 CC    STA   $CCA0
0D7A-   C4 C1       CPY   $C1
0D7C-   A0 A3       LDY   #$A3
0D7E-   BE A4 B3    LDX   $B3A4,Y
0D81-   B0 B0       BCS   $0D33
0D83-   A0 BB       LDY   #$BB
0D85-   20 C1 D2    JSR   $D2C1
0D88-   C5 C1       CMP   $C1
0D8A-   20 D4 CF    JSR   $CFD4
0D8D-   20 C6 C9    JSR   $C9C6
0D90-   CC CC BB    CPY   $BBCC
0D93-   20 C8 C9    JSR   $C9C8
0D96-   C7          ???
0D97-   C8          INY
0D98-   8D A0 D0    STA   $D0A0
0D9B-   C8          INY
0D9C-   C1 8D       CMP   ($8D,X)
0D9E-   A0 CC       LDY   #$CC
0DA0-   C4 C1       CPY   $C1
0DA2-   A0 A3       LDY   #$A3
0DA4-   BC A4 B3    LDY   $B3A4,X
0DA7-   B0 B0       BCS   $0D59
0DA9-   A0 BB       LDY   #$BB
0DAB-   20 CC CF    JSR   $CFCC
0DAE-   D7          ???
0DAF-   8D A0 D0    STA   $D0A0
0DB2-   C8          INY
0DB3-   C1 8D       CMP   ($8D,X)
0DB5-   A0 CC       LDY   #$CC
0DB7-   C4 C1       CPY   $C1
0DB9-   A0 A3       LDY   #$A3
0DBB-   BE B1 B0    LDX   $B0B1,Y
0DBE-   8D A0 D0    STA   $D0A0
0DC1-   C8          INY
0DC2-   C1 8D       CMP   ($8D,X)
0DC4-   A0 CC       LDY   #$CC
0DC6-   C4 C1       CPY   $C1
0DC8-   A0 A3       LDY   #$A3
0DCA-   BC B1 B0    LDY   $B0B1,X
0DCD-   8D A0 D0    STA   $D0A0
0DD0-   C8          INY
0DD1-   C1 8D       CMP   ($8D,X)
0DD3-   A0 CC       LDY   #$CC
0DD5-   C4 C1       CPY   $C1
0DD7-   A0 A3       LDY   #$A3
0DD9-   B0 A0       BCS   $0D7B
0DDB-   BB          ???
0DDC-   20 C6 C9    JSR   $C9C6
0DDF-   CC CC 20    CPY   $20CC
0DE2-   C3          ???
0DE3-   C8          INY
0DE4-   C1 D2       CMP   ($D2,X)
0DE6-   C1 C3       CMP   ($C3,X)
0DE8-   D4          ???
0DE9-   C5 D2       CMP   $D2
0DEB-   8D A0 D0    STA   $D0A0
0DEE-   C8          INY
0DEF-   C1 8D       CMP   ($8D,X)
0DF1-   A0 CA       LDY   #$CA
0DF3-   D3          ???
0DF4-   D2 A0       CMP   ($A0)
0DF6-   CD C5 CD    CMP   $CDC5
0DF9-   C6 C9       DEC   $C9
0DFB-   CC CC 8D    CPY   $8DCC
0DFE-   AA          TAX
0DFF-   8D AA AA    STA   $AAAA
0E02-   20 CD C5    JSR   $C5CD
0E05-   CD CD CF    CMP   $CFCD
0E08-   D6 C5       DEC   $C5,X
0E0A-   20 C1 CC    JSR   $CCC1
0E0D-   D3          ???
0E0E-   CF          ???
0E0F-   20 C4 CF    JSR   $CFC4
0E12-   C5 D3       CMP   $D3
0E14-   20 D7 C8    JSR   $C8D7
0E17-   C1 D4       CMP   ($D4,X)
0E19-   20 C9 D4    JSR   $D4C9
0E1C-   20 D3 C1    JSR   $C1D3
0E1F-   D9 D3 BA    CMP   $BAD3,Y
0E22-   20 C9 D4    JSR   $D4C9
0E25-   20 CD CF    JSR   $CFCD
0E28-   D6 C5       DEC   $C5,X
0E2A-   D3          ???
0E2B-   8D AA AA    STA   $AAAA
0E2E-   20 C1 20    JSR   $20C1
0E31-   C2          ???
0E32-   CC CF C3    CPY   $C3CF
0E35-   CB          ???
0E36-   20 CF C6    JSR   $C6CF
0E39-   20 CD C5    JSR   $C5CD
0E3C-   CD CF D2    CMP   $D2CF
0E3F-   D9 20 C6    CMP   $C620,Y
0E42-   D2 CF       CMP   ($CF)
0E44-   CD 20 C1    CMP   $C120
0E47-   20 D3 CF    JSR   $CFD3
0E4A-   D5 D2       CMP   $D2,X
0E4C-   C3          ???
0E4D-   C5 20       CMP   $20
0E4F-   CC CF C3    CPY   $C3CF
0E52-   C1 D4       CMP   ($D4,X)
0E54-   C9 CF       CMP   #$CF
0E56-   CE 8D AA    DEC   $AA8D
0E59-   AA          TAX
0E5A-   20 D4 CF    JSR   $CFD4
0E5D-   20 C1 20    JSR   $20C1
0E60-   C4 C5       CPY   $C5
0E62-   D3          ???
0E63-   D4          ???
0E64-   C9 CE       CMP   #$CE
0E66-   C1 D4       CMP   ($D4,X)
0E68-   C9 CF       CMP   #$CF
0E6A-   CE 20 CC    DEC   $CC20
0E6D-   CF          ???
0E6E-   C3          ???
0E6F-   C1 D4       CMP   ($D4,X)
0E71-   C9 CF       CMP   #$CF
0E73-   CE AE 20    DEC   $20AE
0E76-   D7          ???
0E77-   C5 A7       CMP   $A7
0E79-   CC CC 20    CPY   $20CC
0E7C-   CE CF D7    DEC   $D7CF
0E7F-   20 CD CF    JSR   $CFCD
0E82-   D6 C5       DEC   $C5,X
0E84-   8D AA AA    STA   $AAAA
0E87-   20 D4 C8    JSR   $C8D4
0E8A-   CF          ???
0E8B-   D3          ???
0E8C-   C5 20       CMP   $20
0E8E-   DA          PHX
0E8F-   C5 D2       CMP   $D2
0E91-   CF          ???
0E92-   C5 D3       CMP   $D3
0E94-   20 D0 CC    JSR   $CCD0
0E97-   C1 C3       CMP   ($C3,X)
0E99-   C5 C4       CMP   $C4
0E9B-   20 C2 D9    JSR   $D9C2
0E9E-   20 CD C5    JSR   $C5CD
0EA1-   CD C6 C9    CMP   $C9C6
0EA4-   CC CC 20    CPY   $20CC
0EA7-   D4          ???
0EA8-   CF          ???
0EA9-   20 C1 CE    JSR   $CEC1
0EAC-   CF          ???
0EAD-   D4          ???
0EAE-   C8          INY
0EAF-   C5 D2       CMP   $D2
0EB1-   8D AA AA    STA   $AAAA
0EB4-   20 CC CF    JSR   $CFCC
0EB7-   C3          ???
0EB8-   C1 D4       CMP   ($D4,X)
0EBA-   C9 CF       CMP   #$CF
0EBC-   CE AE 20    DEC   $20AE
0EBF-   C1 C7       CMP   ($C7,X)
0EC1-   C1 C9       CMP   ($C9,X)
0EC3-   CE AC 20    DEC   $20AC
0EC6-   D9 CF D5    CMP   $D5CF,Y
0EC9-   A7          ???
0ECA-   CC CC 20    CPY   $20CC
0ECD-   CF          ???
0ECE-   CE CC D9    DEC   $D9CC
0ED1-   20 D3 C5    JSR   $C5D3
0ED4-   C5 20       CMP   $20
0ED6-   D4          ???
0ED7-   C8          INY
0ED8-   C9 D3       CMP   #$D3
0EDA-   8D AA AA    STA   $AAAA
0EDD-   20 C3 C8    JSR   $C8C3
0EE0-   C1 CE       CMP   ($CE,X)
0EE2-   C7          ???
0EE3-   C5 20       CMP   $20
0EE5-   D6 C9       DEC   $C9,X
0EE7-   C1 20       CMP   ($20,X)
0EE9-   D4          ???
0EEA-   C8          INY
0EEB-   C5 20       CMP   $20
0EED-   CD CF CE    CMP   $CECF
0EF0-   C9 D4       CMP   #$D4
0EF2-   CF          ???
0EF3-   D2 20       CMP   ($20)
0EF5-   A8          TAY
0EF6-   C3          ???
0EF7-   C1 CC       CMP   ($CC,X)
0EF9-   CC AD B1    CPY   $B1AD
0EFC-   B5 B1       LDA   $B1,X
0EFE-   A9 AE       LDA   #$AE
0F00-   8D AA 8D    STA   $8DAA
0F03-   AA          TAX
0F04-   8D AA AA    STA   $AAAA
0F07-   20 D4 C8    JSR   $C8D4
0F0A-   C9 D3       CMP   #$D3
0F0C-   20 C3 C1    JSR   $C1C3
0F0F-   CE 20 C1    DEC   $C120
0F12-   CC D3 CF    CPY   $CFD3
0F15-   20 C2 C5    JSR   $C5C2
0F18-   20 C4 CF    JSR   $CFC4
0F1B-   CE C5 20    DEC   $20C5
0F1E-   D7          ???
0F1F-   C9 D4       CMP   #$D4
0F21-   C8          INY
0F22-   20 D4 C8    JSR   $C8D4
0F25-   C5 20       CMP   $20
0F27-   CD C1 C3    CMP   $C3C1
0F2A-   D2 CF       CMP   ($CF)
0F2C-   BA          TSX
0F2D-   8D AA 8D    STA   $8DAA
0F30-   AA          TAX
0F31-   AA          TAX
0F32-   20 20 20    JSR   $2020
0F35-   20 20 20    JSR   $2020
0F38-   20 DF CD    JSR   $CDDF
0F3B-   CD CF D6    CMP   $D6CF
0F3E-   20 A4 B3    JSR   $B3A4
0F41-   B0 B0       BCS   $0EF3
0F43-   BB          ???
0F44-   A4 B3       LDY   $B3
0F46-   B2 B0       LDA   ($B0)
0F48-   BB          ???
0F49-   A3          ???
0F4A-   B1 B0       LDA   ($B0),Y
0F4C-   8D AA 8D    STA   $8DAA
0F4F-   A0 CC       LDY   #$CC
0F51-   C4 C1       CPY   $C1
0F53-   A0 A3       LDY   #$A3
0F55-   BE A4 B3    LDX   $B3A4,Y
0F58-   B0 B0       BCS   $0F0A
0F5A-   A0 BB       LDY   #$BB
0F5C-   20 D3 D2    JSR   $D2D3
0F5F-   C3          ???
0F60-   20 C8 C9    JSR   $C9C8
0F63-   C7          ???
0F64-   C8          INY
0F65-   8D A0 D0    STA   $D0A0
0F68-   C8          INY
0F69-   C1 8D       CMP   ($8D,X)
0F6B-   A0 CC       LDY   #$CC
0F6D-   C4 C1       CPY   $C1
0F6F-   A0 A3       LDY   #$A3
0F71-   BC A4 B3    LDY   $B3A4,X
0F74-   B0 B0       BCS   $0F26
0F76-   A0 BB       LDY   #$BB
0F78-   20 D3 D2    JSR   $D2D3
0F7B-   C3          ???
0F7C-   20 CC CF    JSR   $CFCC
0F7F-   D7          ???
0F80-   8D A0 D0    STA   $D0A0
0F83-   C8          INY
0F84-   C1 8D       CMP   ($8D,X)
0F86-   A0 CC       LDY   #$CC
0F88-   C4 C1       CPY   $C1
0F8A-   A0 A3       LDY   #$A3
0F8C-   BE A4 B3    LDX   $B3A4,Y
0F8F-   B2 B0       LDA   ($B0)
0F91-   A0 BB       LDY   #$BB
0F93-   20 C4 C5    JSR   $C5C4
0F96-   D3          ???
0F97-   D4          ???
0F98-   20 C8 C9    JSR   $C9C8
0F9B-   C7          ???
0F9C-   C8          INY
0F9D-   8D A0 D0    STA   $D0A0
0FA0-   C8          INY
0FA1-   C1 8D       CMP   ($8D,X)
0FA3-   A0 CC       LDY   #$CC
0FA5-   C4 C1       CPY   $C1
0FA7-   A0 A3       LDY   #$A3
0FA9-   BC A4 B3    LDY   $B3A4,X
0FAC-   B2 B0       LDA   ($B0)
0FAE-   A0 BB       LDY   #$BB
0FB0-   20 C4 C5    JSR   $C5C4
0FB3-   D3          ???
0FB4-   D4          ???
0FB5-   20 CC CF    JSR   $CFCC
0FB8-   D7          ???
0FB9-   8D A0 D0    STA   $D0A0
0FBC-   C8          INY
0FBD-   C1 8D       CMP   ($8D,X)
0FBF-   A0 CC       LDY   #$CC
0FC1-   C4 C1       CPY   $C1
0FC3-   A0 A3       LDY   #$A3
0FC5-   BE B1 B0    LDX   $B0B1,Y
0FC8-   A0 BB       LDY   #$BB
0FCA-   20 A3 20    JSR   $20A3
0FCD-   CF          ???
0FCE-   C6 20       DEC   $20
0FD0-   C2          ???
0FD1-   D9 D4 C5    CMP   $C5D4,Y
0FD4-   D3          ???
0FD5-   20 D4 CF    JSR   $CFD4
0FD8-   20 CD CF    JSR   $CFCD
0FDB-   D6 C5       DEC   $C5,X
0FDD-   8D A0 D0    STA   $D0A0
0FE0-   C8          INY
0FE1-   C1 8D       CMP   ($8D,X)
0FE3-   A0 CC       LDY   #$CC
0FE5-   C4 C1       CPY   $C1
0FE7-   A0 A3       LDY   #$A3
0FE9-   BC B1 B0    LDY   $B0B1,X
0FEC-   A0 BB       LDY   #$BB
0FEE-   20 CC CF    JSR   $CFCC
0FF1-   D7          ???
0FF2-   20 C2 D9    JSR   $D9C2
0FF5-   D4          ???
0FF6-   C5 8D       CMP   $8D
0FF8-   A0 D0       LDY   #$D0
0FFA-   C8          INY
0FFB-   C1 8D       CMP   ($8D,X)
0FFD-   A0 CA       LDY   #$CA
0FFF-   D3          ???
1000-   D2 A0       CMP   ($A0)
1002-   CD C5 CD    CMP   $CDC5
1005-   CD CF D6    CMP   $D6CF
1008-   C5 8D       CMP   $8D
100A-   AA          TAX
100B-   8D AA AA    STA   $AAAA
100E-   20 C4 C5    JSR   $C5C4
1011-   CC C1 D9    CPY   $D9C1
1014-   CD D3 20    CMP   $20D3
1017-   D2 D5       CMP   ($D5)
1019-   CE D3 20    DEC   $20D3
101C-   D4          ???
101D-   C8          INY
101E-   D2 CF       CMP   ($CF)
1020-   D5 C7       CMP   $C7,X
1022-   C8          INY
1023-   20 C3 D9    JSR   $D9C3
1026-   C3          ???
1027-   CC C5 D3    CPY   $D3C5
102A-   20 CF C6    JSR   $C6CF
102D-   20 D4 C8    JSR   $C8D4
1030-   C5 8D       CMP   $8D
1032-   AA          TAX
1033-   AA          TAX
1034-   20 B6 B5    JSR   $B5B6
1037-   B0 B2       BCS   $0FEB
1039-   20 D5 CE    JSR   $CED5
103C-   D4          ???
103D-   C9 CC       CMP   #$CC
103F-   20 C1 20    JSR   $20C1
1042-   C3          ???
1043-   C5 D2       CMP   $D2
1045-   D4          ???
1046-   C1 C9       CMP   ($C9,X)
1048-   CE 20 C1    DEC   $C120
104B-   CD CF D5    CMP   $D5CF
104E-   CE D4 20    DEC   $20D4
1051-   CF          ???
1052-   C6 20       DEC   $20
1054-   D4          ???
1055-   C9 CD       CMP   #$CD
1057-   C5 8D       CMP   $8D
1059-   AA          TAX
105A-   AA          TAX
105B-   20 C8 C1    JSR   $C1C8
105E-   D3          ???
105F-   20 D0 C1    JSR   $C1D0
1062-   D3          ???
1063-   D3          ???
1064-   C5 C4       CMP   $C4
1066-   AE 8D AA    LDX   $AA8D
1069-   8D AA AA    STA   $AAAA
106C-   20 C9 CE    JSR   $CEC9
106F-   20 CD C1    JSR   $C1CD
1072-   C3          ???
1073-   D2 CF       CMP   ($CF)
1075-   20 C6 CF    JSR   $CFC6
1078-   D2 CD       CMP   ($CD)
107A-   BA          TSX
107B-   8D AA 8D    STA   $8DAA
107E-   AA          TAX
107F-   AA          TAX
1080-   20 20 20    JSR   $2020
1083-   20 20 20    JSR   $2020
1086-   20 DF C4    JSR   $C4DF
1089-   CC C1 D9    CPY   $D9C1
108C-   20 A3 B2    JSR   $B2A3
108F-   B5 B0       LDA   $B0,X
1091-   8D AA AA    STA   $AAAA
1094-   20 20 20    JSR   $2020
1097-   20 20 20    JSR   $2020
109A-   20 DF C4    JSR   $C4DF
109D-   CC C1 D9    CPY   $D9C1
10A0-   20 A3 B2    JSR   $B2A3
10A3-   B5 B0       LDA   $B0,X
10A5-   8D AA AA    STA   $AAAA
10A8-   20 20 20    JSR   $2020
10AB-   20 20 20    JSR   $2020
10AE-   20 DF C4    JSR   $C4DF
10B1-   CC C1 D9    CPY   $D9C1
10B4-   20 A3 B2    JSR   $B2A3
10B7-   B5 B0       LDA   $B0,X
10B9-   8D AA AA    STA   $AAAA
10BC-   20 20 20    JSR   $2020
10BF-   20 20 20    JSR   $2020
10C2-   20 DF C4    JSR   $C4DF
10C5-   CC C1 D9    CPY   $D9C1
10C8-   20 A3 B2    JSR   $B2A3
10CB-   B5 B0       LDA   $B0,X
10CD-   8D AA 8D    STA   $8DAA
10D0-   A0 CC       LDY   #$CC
10D2-   C4 D9       CPY   $D9
10D4-   A0 A3       LDY   #$A3
10D6-   B2 B5       LDA   ($B5)
10D8-   B0 A0       BCS   $107A
10DA-   BB          ???
10DB-   20 D4 C9    JSR   $C9D4
10DE-   CD C5 20    CMP   $20C5
10E1-   C9 CE       CMP   #$CE
10E3-   20 CD C9    JSR   $C9CD
10E6-   CC CC C9    CPY   $C9CC
10E9-   D3          ???
10EA-   C5 C3       CMP   $C3
10EC-   CF          ???
10ED-   CE C4 D3    DEC   $D3C4
10F0-   8D BB 20    STA   $20BB
10F3-   C9 D3       CMP   #$D3
10F5-   20 D0 C1    JSR   $C1D0
10F8-   D3          ???
10F9-   D3          ???
10FA-   C5 C4       CMP   $C4
10FC-   20 D6 C9    JSR   $C9D6
10FF-   C1 20       CMP   ($20,X)
1101-   D9 8D BB    CMP   $BB8D,Y
1104-   20 B2 B5    JSR   $B5B2
1107-   B0 20       BCS   $1129
1109-   BD 20 B1    LDA   $B120,X
110C-   AF          ???
110D-   B4 20       LDY   $20,X
110F-   D3          ???
1110-   C5 C3       CMP   $C3
1112-   CF          ???
1113-   CE C4 8D    DEC   $8DC4
1116-   A0 CA       LDY   #$CA
1118-   D3          ???
1119-   D2 A0       CMP   ($A0)
111B-   C4 C5       CPY   $C5
111D-   CC C1 D9    CPY   $D9C1
1120-   CD D3 8D    CMP   $8DD3
1123-   A0 CC       LDY   #$CC
1125-   C4 D9       CPY   $D9
1127-   A0 A3       LDY   #$A3
1129-   B2 B5       LDA   ($B5)
112B-   B0 8D       BCS   $10BA
112D-   A0 CA       LDY   #$CA
112F-   D3          ???
1130-   D2 A0       CMP   ($A0)
1132-   C4 C5       CPY   $C5
1134-   CC C1 D9    CPY   $D9C1
1137-   CD D3 8D    CMP   $8DD3
113A-   A0 CC       LDY   #$CC
113C-   C4 D9       CPY   $D9
113E-   A0 A3       LDY   #$A3
1140-   B2 B5       LDA   ($B5)
1142-   B0 8D       BCS   $10D1
1144-   A0 CA       LDY   #$CA
1146-   D3          ???
1147-   D2 A0       CMP   ($A0)
1149-   C4 C5       CPY   $C5
114B-   CC C1 D9    CPY   $D9C1
114E-   CD D3 8D    CMP   $8DD3
1151-   A0 CC       LDY   #$CC
1153-   C4 D9       CPY   $D9
1155-   A0 A3       LDY   #$A3
1157-   B2 B5       LDA   ($B5)
1159-   B0 8D       BCS   $10E8
115B-   A0 CA       LDY   #$CA
115D-   D3          ???
115E-   D2 A0       CMP   ($A0)
1160-   C4 C5       CPY   $C5
1162-   CC C1 D9    CPY   $D9C1
1165-   CD D3 A0    CMP   $A0D3
1168-   BB          ???
1169-   20 BD 20    JSR   $20BD
116C-   B1 20       LDA   ($20),Y
116E-   D3          ???
116F-   C5 C3       CMP   $C3
1171-   CF          ???
1172-   CE C4 20    DEC   $20C4
1175-   C4 C5       CPY   $C5
1177-   CC C1 D9    CPY   $D9C1
117A-   8D AA 8D    STA   $8DAA
117D-   AA          TAX
117E-   AA          TAX
117F-   20 DA D3    JSR   $D3DA
1182-   C1 D6       CMP   ($D6,X)
1184-   C5 20       CMP   $20
1186-   C2          ???
1187-   C1 C3       CMP   ($C3,X)
1189-   CB          ???
118A-   D3          ???
118B-   20 D5 D0    JSR   $D0D5
118E-   20 D4 C8    JSR   $C8D4
1191-   C5 20       CMP   $20
1193-   A2 C6       LDX   #$C6
1195-   D2 C5       CMP   ($C5)
1197-   C5 A2       CMP   $A2
1199-   20 C1 D2    JSR   $D2C1
119C-   C5 C1       CMP   $C1
119E-   D3          ???
119F-   20 CF C6    JSR   $C6CF
11A2-   8D AA AA    STA   $AAAA
11A5-   20 D4 C8    JSR   $C8D4
11A8-   C5 20       CMP   $20
11AA-   DA          PHX
11AB-   C5 D2       CMP   $D2
11AD-   CF          ???
11AE-   20 D0 C1    JSR   $C1D0
11B1-   C7          ???
11B2-   C5 20       CMP   $20
11B4-   D4          ???
11B5-   CF          ???
11B6-   20 C1 CE    JSR   $CEC1
11B9-   20 C1 CC    JSR   $CCC1
11BC-   D4          ???
11BD-   C5 D2       CMP   $D2
11BF-   CE C1 D4    DEC   $D4C1
11C2-   C5 20       CMP   $20
11C4-   CD C5 CD    CMP   $CDC5
11C7-   CF          ???
11C8-   D2 D9       CMP   ($D9)
11CA-   8D AA AA    STA   $AAAA
11CD-   20 CC CF    JSR   $CFCC
11D0-   C3          ???
11D1-   C1 D4       CMP   ($D4,X)
11D3-   C9 CF       CMP   #$CF
11D5-   CE AE 20    DEC   $20AE
11D8-   D4          ???
11D9-   C8          INY
11DA-   C9 D3       CMP   #$D3
11DC-   20 C9 D3    JSR   $D3C9
11DF-   20 CD CF    JSR   $CFCD
11E2-   D3          ???
11E3-   D4          ???
11E4-   CC D9 20    CPY   $20D9
11E7-   D5 D3       CMP   $D3,X
11E9-   C5 C6       CMP   $C6
11EB-   D5 CC       CMP   $CC,X
11ED-   20 D7 C8    JSR   $C8D7
11F0-   C5 CE       CMP   $CE
11F2-   8D AA AA    STA   $AAAA
11F5-   20 D9 CF    JSR   $CFD9
11F8-   D5 20       CMP   $20,X
11FA-   CB          ???
11FB-   CE CF D7    DEC   $D7CF
11FE-   20 C1 20    JSR   $20C1
1201-   D2 CF       CMP   ($CF)
1203-   D5 D4       CMP   $D4,X
1205-   C9 CE       CMP   #$CE
1207-   C5 20       CMP   $20
1209-   D5 D3       CMP   $D3,X
120B-   C5 D3       CMP   $D3
120D-   20 D4 C8    JSR   $C8D4
1210-   C5 20       CMP   $20
1212-   DA          PHX
1213-   C5 D2       CMP   $D2
1215-   CF          ???
1216-   20 D0 C1    JSR   $C1D0
1219-   C7          ???
121A-   C5 AC       CMP   $AC
121C-   8D AA AA    STA   $AAAA
121F-   20 C2 D5    JSR   $D5C2
1222-   D4          ???
1223-   20 D9 CF    JSR   $CFD9
1226-   D5 20       CMP   $20,X
1228-   D7          ???
1229-   C1 CE       CMP   ($CE,X)
122B-   D4          ???
122C-   20 D4 CF    JSR   $CFD4
122F-   20 CB C5    JSR   $C5CB
1232-   C5 D0       CMP   $D0
1234-   20 D4 C8    JSR   $C8D4
1237-   C5 20       CMP   $20
1239-   D6 C1       DEC   $C1,X
123B-   CC D5 C5    CPY   $C5D5
123E-   D3          ???
123F-   20 C3 D5    JSR   $D5C3
1242-   D2 D2       CMP   ($D2)
1244-   C5 CE       CMP   $CE
1246-   D4          ???
1247-   CC D9 8D    CPY   $8DD9
124A-   AA          TAX
124B-   AA          TAX
124C-   20 D3 D4    JSR   $D4D3
124F-   CF          ???
1250-   D2 C5       CMP   ($C5)
1252-   C4 20       CPY   $20
1254-   D4          ???
1255-   C8          INY
1256-   C5 D2       CMP   $D2
1258-   C5 20       CMP   $20
125A-   C1 C6       CMP   ($C6,X)
125C-   D4          ???
125D-   C5 D2       CMP   $D2
125F-   20 C3 C1    JSR   $C1C3
1262-   CC CC C9    CPY   $C9CC
1265-   CE C7 20    DEC   $20C7
1268-   D4          ???
1269-   C8          INY
126A-   C5 20       CMP   $20
126C-   D2 CF       CMP   ($CF)
126E-   D5 D4       CMP   $D4,X
1270-   C9 CE       CMP   #$CE
1272-   C5 AE       CMP   $AE
1274-   8D AA 8D    STA   $8DAA
1277-   AA          TAX
1278-   AA          TAX
1279-   20 C9 CE    JSR   $CEC9
127C-   20 CD C1    JSR   $C1CD
127F-   C3          ???
1280-   D2 CF       CMP   ($CF)
1282-   20 C6 CF    JSR   $CFC6
1285-   D2 CD       CMP   ($CD)
1287-   BA          TSX
1288-   8D AA 8D    STA   $8DAA
128B-   AA          TAX
128C-   AA          TAX
128D-   20 20 20    JSR   $2020
1290-   20 20 20    JSR   $2020
1293-   20 DF DA    JSR   $DADF
1296-   D3          ???
1297-   D6 20       DEC   $20,X
1299-   20 A4 B6    JSR   $B6A4
129C-   C4 B0       CPY   $B0
129E-   B0 8D       BCS   $122D
12A0-   AA          TAX
12A1-   8D A0 CC    STA   $CCA0
12A4-   C4 C1       CPY   $C1
12A6-   A0 A3       LDY   #$A3
12A8-   B0 B1       BCS   $125B
12AA-   8D A0 D3    STA   $D3A0
12AD-   D4          ???
12AE-   C1 A0       CMP   ($A0,X)
12B0-   A4 B0       LDY   $B0
12B2-   B6 8D       LDX   $8D,Y
12B4-   A0 CC       LDY   #$CC
12B6-   C4 C1       CPY   $C1
12B8-   A0 A3       LDY   #$A3
12BA-   B0 B2       BCS   $126E
12BC-   8D A0 D3    STA   $D3A0
12BF-   D4          ???
12C0-   C1 A0       CMP   ($A0,X)
12C2-   A4 B0       LDY   $B0
12C4-   B7          ???
12C5-   8D A0 CC    STA   $CCA0
12C8-   C4 C1       CPY   $C1
12CA-   A0 A3       LDY   #$A3
12CC-   B0 B3       BCS   $1281
12CE-   8D A0 D3    STA   $D3A0
12D1-   D4          ???
12D2-   C1 A0       CMP   ($A0,X)
12D4-   A4 B0       LDY   $B0
12D6-   B8          CLV
12D7-   8D A0 CC    STA   $CCA0
12DA-   C4 C1       CPY   $C1
12DC-   A0 A3       LDY   #$A3
12DE-   B0 B4       BCS   $1294
12E0-   8D A0 D3    STA   $D3A0
12E3-   D4          ???
12E4-   C1 A0       CMP   ($A0,X)
12E6-   A4 B0       LDY   $B0
12E8-   B9 8D A0    LDA   $A08D,Y
12EB-   CC C4 C1    CPY   $C1C4
12EE-   A0 A3       LDY   #$A3
12F0-   BE A4 B6    LDX   $B6A4,Y
12F3-   C4 B0       CPY   $B0
12F5-   B0 8D       BCS   $1284
12F7-   A0 D0       LDY   #$D0
12F9-   C8          INY
12FA-   C1 8D       CMP   ($8D,X)
12FC-   A0 CC       LDY   #$CC
12FE-   C4 C1       CPY   $C1
1300-   A0 A3       LDY   #$A3
1302-   BC A4 B6    LDY   $B6A4,X
1305-   C4 B0       CPY   $B0
1307-   B0 A0       BCS   $12A9
1309-   BB          ???
130A-   20 CC CF    JSR   $CFCC
130D-   D7          ???
130E-   20 C4 C5    JSR   $C5C4
1311-   D3          ???
1312-   D4          ???
1313-   8D A0 D0    STA   $D0A0
1316-   C8          INY
1317-   C1 8D       CMP   ($8D,X)
1319-   A0 CA       LDY   #$CA
131B-   D3          ???
131C-   D2 A0       CMP   ($A0)
131E-   DA          PHX
131F-   D3          ???
1320-   C1 D6       CMP   ($D6,X)
1322-   C5 8D       CMP   $8D
1324-   AA          TAX
1325-   8D AA AA    STA   $AAAA
1328-   20 D9 CF    JSR   $CFD9
132B-   D5 20       CMP   $20,X
132D-   C3          ???
132E-   C1 CE       CMP   ($CE,X)
1330-   20 D2 C5    JSR   $C5D2
1333-   D3          ???
1334-   D4          ???
1335-   CF          ???
1336-   D2 C5       CMP   ($C5)
1338-   20 D4 C8    JSR   $C8D4
133B-   C5 20       CMP   $20
133D-   DA          PHX
133E-   C5 D2       CMP   $D2
1340-   CF          ???
1341-   20 D0 C1    JSR   $C1D0
1344-   C7          ???
1345-   C5 20       CMP   $20
1347-   D4          ???
1348-   CF          ???
1349-   20 C9 D4    JSR   $D4C9
134C-   D3          ???
134D-   8D AA AA    STA   $AAAA
1350-   20 D0 D2    JSR   $D2D0
1353-   C9 CF       CMP   #$CF
1355-   D2 20       CMP   ($20)
1357-   D3          ???
1358-   D4          ???
1359-   C1 D4       CMP   ($D4,X)
135B-   C5 20       CMP   $20
135D-   C2          ???
135E-   D9 20 D4    CMP   $D420,Y
1361-   C8          INY
1362-   C5 CE       CMP   $CE
1364-   20 C3 C1    JSR   $C1C3
1367-   CC CC C9    CPY   $C9CC
136A-   CE C7 20    DEC   $20C7
136D-   DA          PHX
136E-   CC CF C1    CPY   $C1CF
1371-   C4 AE       CPY   $AE
1373-   8D AA 8D    STA   $8DAA
1376-   AA          TAX
1377-   AA          TAX
1378-   20 CD C1    JSR   $C1CD
137B-   C3          ???
137C-   D2 CF       CMP   ($CF)
137E-   BA          TSX
137F-   8D AA 8D    STA   $8DAA
1382-   AA          TAX
1383-   AA          TAX
1384-   20 20 20    JSR   $2020
1387-   20 20 20    JSR   $2020
138A-   20 DF DA    JSR   $DADF
138D-   CC C4 20    CPY   $20C4
1390-   20 A4 B6    JSR   $B6A4
1393-   C4 B0       CPY   $B0
1395-   B0 8D       BCS   $1324
1397-   AA          TAX
1398-   8D A0 CC    STA   $CCA0
139B-   C4 C1       CPY   $C1
139D-   A0 A3       LDY   #$A3
139F-   BE A4 B6    LDX   $B6A4,Y
13A2-   C4 B0       CPY   $B0
13A4-   B0 A0       BCS   $1346
13A6-   BB          ???
13A7-   20 C8 C9    JSR   $C9C8
13AA-   C7          ???
13AB-   C8          INY
13AC-   BB          ???
13AD-   20 D3 CF    JSR   $CFD3
13B0-   D5 D2       CMP   $D2,X
13B2-   C3          ???
13B3-   C5 8D       CMP   $8D
13B5-   A0 D0       LDY   #$D0
13B7-   C8          INY
13B8-   C1 8D       CMP   ($8D,X)
13BA-   A0 CC       LDY   #$CC
13BC-   C4 C1       CPY   $C1
13BE-   A0 A3       LDY   #$A3
13C0-   BC A4 B6    LDY   $B6A4,X
13C3-   C4 B0       CPY   $B0
13C5-   B0 A0       BCS   $1367
13C7-   BB          ???
13C8-   20 CC CF    JSR   $CFCC
13CB-   D7          ???
13CC-   8D A0 D0    STA   $D0A0
13CF-   C8          INY
13D0-   C1 8D       CMP   ($8D,X)
13D2-   A0 CA       LDY   #$CA
13D4-   D3          ???
13D5-   D2 20       CMP   ($20)
13D7-   DA          PHX
13D8-   CC CF C1    CPY   $C1CF
13DB-   C4 8D       CPY   $8D
13DD-   AA          TAX
13DE-   8D AA 8D    STA   $8DAA
13E1-   AA          TAX
13E2-   AA          TAX
13E3-   20 CC C9    JSR   $C9CC
13E6-   D4          ???
13E7-   D4          ???
13E8-   CC C5 20    CPY   $20C5
13EB-   CC D5 CD    CPY   $CDD5
13EE-   D0 D3       BNE   $13C3
13F0-   20 AD AD    JSR   $ADAD
13F3-   20 CD C9    JSR   $C9CD
13F6-   C4 AF       CPY   $AF
13F8-   CC CF D7    CPY   $D7CF
13FB-   20 CC C5    JSR   $C5CC
13FE-   D6 C5       DEC   $C5,X
1400-   CC 8D AA    CPY   $AA8D
1403-   8D AA 8D    STA   $8DAA
1406-   A0 CA       LDY   #$CA
1408-   CD D0 A0    CMP   $A0D0
140B-   D2 C5       CMP   ($C5)
140D-   C5 CE       CMP   $CE
140F-   D4          ???
1410-   D2 D9       CMP   ($D9)
1412-   8D AA 8D    STA   $8DAA
1415-   AA          TAX
1416-   E0 E0       CPX   #$E0
1418-   E0 E0       CPX   #$E0
141A-   E0 E0       CPX   #$E0
141C-   E0 E0       CPX   #$E0
141E-   E0 E0       CPX   #$E0
1420-   E0 E0       CPX   #$E0
1422-   E0 E0       CPX   #$E0
1424-   E0 E0       CPX   #$E0
1426-   E0 E0       CPX   #$E0
1428-   E0 E0       CPX   #$E0
142A-   E0 E0       CPX   #$E0
142C-   E0 E0       CPX   #$E0
142E-   E0 E0       CPX   #$E0
1430-   E0 E0       CPX   #$E0
1432-   E0 E0       CPX   #$E0
1434-   AA          TAX
1435-   8D AA 20    STA   $20AA
1438-   20 20 20    JSR   $2020
143B-   20 20 20    JSR   $2020
143E-   20 C2 CF    JSR   $CFC2
1441-   D4          ???
1442-   D4          ???
1443-   CF          ???
1444-   CD 20 C9    CMP   $C920
1447-   CE C3 CC    DEC   $CCC3
144A-   D5 C4       CMP   $C4,X
144C-   C5 D3       CMP   $D3
144E-   20 20 20    JSR   $2020
1451-   20 20 20    JSR   $2020
1454-   20 AA 8D    JSR   $8DAA
1457-   AA          TAX
1458-   AC AC AC    LDY   $ACAC
145B-   AC AC AC    LDY   $ACAC
145E-   AC AC AC    LDY   $ACAC
1461-   AC AC AC    LDY   $ACAC
1464-   AC AC AC    LDY   $ACAC
1467-   AC AC AC    LDY   $ACAC
146A-   AC AC AC    LDY   $ACAC
146D-   AC AC AC    LDY   $ACAC
1470-   AC AC AC    LDY   $ACAC
1473-   AC AC AC    LDY   $ACAC
1476-   AA          TAX
1477-   8D AA 8D    STA   $8DAA
147A-   AA          TAX
147B-   8D AA AA    STA   $AAAA
147E-   20 C2 CF    JSR   $CFC2
1481-   D4          ???
1482-   D4          ???
1483-   CF          ???
1484-   CD 20 C9    CMP   $C920
1487-   CE C3 CC    DEC   $CCC3
148A-   D5 C4       CMP   $C4,X
148C-   C5 D3       CMP   $D3
148E-   8D AA 8D    STA   $8DAA
1491-   A0 D0       LDY   #$D0
1493-   D5 D4       CMP   $D4,X
1495-   A0 C3       LDY   #$C3
1497-   CF          ???
1498-   CD CD CF    CMP   $CFCD
149B-   CE AE CC    DEC   $CCAE
149E-   C9 C2       CMP   #$C2
14A0-   8D AA 8D    STA   $8DAA
14A3-   AA          TAX
14A4-   8D 00 00    STA   $0000
