0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 D3    LDY   $D320,X
0950-   D4          ???
0951-   C4 C9       CPY   $C9
0953-   CF          ???
0954-   20 C4 C5    JSR   $C5C4
0957-   CD CF 20    CMP   $20CF
095A-   BE AD 20    LDX   $20AD,Y
095D-   20 20 20    JSR   $2020
0960-   20 20 20    JSR   $2020
0963-   20 AA 8D    JSR   $8DAA
0966-   AA          TAX
0967-   20 20 20    JSR   $2020
096A-   20 20 20    JSR   $2020
096D-   20 20 20    JSR   $2020
0970-   20 20 20    JSR   $2020
0973-   20 20 20    JSR   $2020
0976-   20 20 20    JSR   $2020
0979-   20 20 20    JSR   $2020
097C-   20 20 20    JSR   $2020
097F-   20 20 20    JSR   $2020
0982-   20 20 20    JSR   $2020
0985-   AA          TAX
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B1    JSR   $B120
09D4-   B3          ???
09D5-   AD CA C1    LDA   $C1CA
09D8-   CE AD B2    DEC   $B2AD
09DB-   B0 B1       BCS   $098E
09DD-   B9 20 20    LDA   $2020,Y
09E0-   20 20 20    JSR   $2020
09E3-   20 20 20    JSR   $2020
09E6-   20 20 AA    JSR   $AA20
09E9-   8D AA 20    STA   $20AA
09EC-   20 20 20    JSR   $2020
09EF-   20 20 20    JSR   $2020
09F2-   20 20 20    JSR   $2020
09F5-   20 20 20    JSR   $2020
09F8-   20 20 20    JSR   $2020
09FB-   20 20 20    JSR   $2020
09FE-   20 20 20    JSR   $2020
0A01-   20 20 20    JSR   $2020
0A04-   20 20 20    JSR   $2020
0A07-   20 20 AA    JSR   $AA20
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   C6 C6       DEC   $C6
0AFE-   8D A0 D4    STA   $D4A0
0B01-   D2 A0       CMP   ($A0)
0B03-   CF          ???
0B04-   CE 8D A0    DEC   $A08D
0B07-   C4 D3       CPY   $D3
0B09-   CB          ???
0B0A-   A0 D3       LDY   #$D3
0B0C-   D4          ???
0B0D-   C4 C9       CPY   $C9
0B0F-   CF          ???
0B10-   AE C4 C5    LDX   $C5C4
0B13-   CD CF 8D    CMP   $8DCF
0B16-   A0 CF       LDY   #$CF
0B18-   C2          ???
0B19-   CA          DEX
0B1A-   A0 A4       LDY   #$A4
0B1C-   C2          ???
0B1D-   C6 C5       DEC   $C5
0B1F-   B0 8D       BCS   $0AAE
0B21-   A0 CF       LDY   #$CF
0B23-   D2 C7       CMP   ($C7)
0B25-   A0 A4       LDY   #$A4
0B27-   B6 B0       LDX   $B0,Y
0B29-   B0 B0       BCS   $0ADB
0B2B-   8D AA 8D    STA   $8DAA
0B2E-   AA          TAX
0B2F-   E0 E0       CPX   #$E0
0B31-   E0 E0       CPX   #$E0
0B33-   E0 E0       CPX   #$E0
0B35-   E0 E0       CPX   #$E0
0B37-   E0 E0       CPX   #$E0
0B39-   E0 E0       CPX   #$E0
0B3B-   E0 E0       CPX   #$E0
0B3D-   E0 E0       CPX   #$E0
0B3F-   E0 E0       CPX   #$E0
0B41-   E0 E0       CPX   #$E0
0B43-   E0 E0       CPX   #$E0
0B45-   E0 E0       CPX   #$E0
0B47-   E0 E0       CPX   #$E0
0B49-   E0 E0       CPX   #$E0
0B4B-   E0 E0       CPX   #$E0
0B4D-   AA          TAX
0B4E-   8D AA 20    STA   $20AA
0B51-   20 D4 CF    JSR   $CFD4
0B54-   D0 20       BNE   $0B76
0B56-   C9 CE       CMP   #$CE
0B58-   C3          ???
0B59-   CC D5 C4    CPY   $C4D5
0B5C-   C5 D3       CMP   $D3
0B5E-   20 A8 C8    JSR   $C8A8
0B61-   CF          ???
0B62-   CF          ???
0B63-   CB          ???
0B64-   D3          ???
0B65-   AC CD C1    LDY   $C1CD
0B68-   C3          ???
0B69-   D2 CF       CMP   ($CF)
0B6B-   D3          ???
0B6C-   A9 20       LDA   #$20
0B6E-   AA          TAX
0B6F-   8D AA AC    STA   $ACAA
0B72-   AC AC AC    LDY   $ACAC
0B75-   AC AC AC    LDY   $ACAC
0B78-   AC AC AC    LDY   $ACAC
0B7B-   AC AC AC    LDY   $ACAC
0B7E-   AC AC AC    LDY   $ACAC
0B81-   AC AC AC    LDY   $ACAC
0B84-   AC AC AC    LDY   $ACAC
0B87-   AC AC AC    LDY   $ACAC
0B8A-   AC AC AC    LDY   $ACAC
0B8D-   AC AC AA    LDY   $AAAC
0B90-   8D AA 8D    STA   $8DAA
0B93-   A0 D0       LDY   #$D0
0B95-   D5 D4       CMP   $D4,X
0B97-   A0 CD       LDY   #$CD
0B99-   C9 CE       CMP   #$CE
0B9B-   AE D6 C1    LDX   $C1D6
0B9E-   D2 D3       CMP   ($D3)
0BA0-   AE D2 C5    LDX   $C5D2
0BA3-   D1 D5       CMP   ($D5),Y
0BA5-   C9 D2       CMP   #$D2
0BA7-   C5 C4       CMP   $C4
0BA9-   8D A0 D0    STA   $D0A0
0BAC-   D5 D4       CMP   $D4,X
0BAE-   20 A0 CD    JSR   $CDA0
0BB1-   C9 CE       CMP   #$CE
0BB3-   AE C8 CF    LDX   $CFC8
0BB6-   CF          ???
0BB7-   CB          ???
0BB8-   D3          ???
0BB9-   AE D2 C5    LDX   $C5D2
0BBC-   D1 D5       CMP   ($D5),Y
0BBE-   C9 D2       CMP   #$D2
0BC0-   C5 C4       CMP   $C4
0BC2-   8D A0 D5    STA   $D5A0
0BC5-   D3          ???
0BC6-   C5 A0       CMP   $A0
0BC8-   CD C9 CE    CMP   $CEC9
0BCB-   AE CD C1    LDX   $C1CD
0BCE-   C3          ???
0BCF-   AE D2 C5    LDX   $C5D2
0BD2-   D1 D5       CMP   ($D5),Y
0BD4-   C9 D2       CMP   #$D2
0BD6-   C5 C4       CMP   $C4
0BD8-   8D A0 D5    STA   $D5A0
0BDB-   D3          ???
0BDC-   C5 A0       CMP   $A0
0BDE-   CD C9 CE    CMP   $CEC9
0BE1-   AE CD C1    LDX   $C1CD
0BE4-   C3          ???
0BE5-   AE D3 D4    LDX   $D4D3
0BE8-   C4 C9       CPY   $C9
0BEA-   CF          ???
0BEB-   8D A0 D0    STA   $D0A0
0BEE-   D5 D4       CMP   $D4,X
0BF0-   A0 CD       LDY   #$CD
0BF2-   C9 CE       CMP   #$CE
0BF4-   AE C8 CF    LDX   $CFC8
0BF7-   CF          ???
0BF8-   CB          ???
0BF9-   D3          ???
0BFA-   AE D3 D4    LDX   $D4D3
0BFD-   C4 C9       CPY   $C9
0BFF-   CF          ???
0C00-   8D AA 8D    STA   $8DAA
0C03-   AA          TAX
0C04-   E0 E0       CPX   #$E0
0C06-   E0 E0       CPX   #$E0
0C08-   E0 E0       CPX   #$E0
0C0A-   E0 E0       CPX   #$E0
0C0C-   E0 E0       CPX   #$E0
0C0E-   E0 E0       CPX   #$E0
0C10-   E0 E0       CPX   #$E0
0C12-   E0 E0       CPX   #$E0
0C14-   E0 E0       CPX   #$E0
0C16-   E0 E0       CPX   #$E0
0C18-   E0 E0       CPX   #$E0
0C1A-   E0 E0       CPX   #$E0
0C1C-   E0 E0       CPX   #$E0
0C1E-   E0 E0       CPX   #$E0
0C20-   E0 E0       CPX   #$E0
0C22-   AA          TAX
0C23-   8D AA 20    STA   $20AA
0C26-   20 20 20    JSR   $2020
0C29-   20 20 D0    JSR   $D020
0C2C-   D2 CF       CMP   ($CF)
0C2E-   C7          ???
0C2F-   D2 C1       CMP   ($C1)
0C31-   CD 20 CD    CMP   $CD20
0C34-   C1 C9       CMP   ($C9,X)
0C36-   CE 20 C2    DEC   $C220
0C39-   CF          ???
0C3A-   C4 D9       CPY   $D9
0C3C-   20 20 20    JSR   $2020
0C3F-   20 20 20    JSR   $2020
0C42-   20 AA 8D    JSR   $8DAA
0C45-   AA          TAX
0C46-   AC AC AC    LDY   $ACAC
0C49-   AC AC AC    LDY   $ACAC
0C4C-   AC AC AC    LDY   $ACAC
0C4F-   AC AC AC    LDY   $ACAC
0C52-   AC AC AC    LDY   $ACAC
0C55-   AC AC AC    LDY   $ACAC
0C58-   AC AC AC    LDY   $ACAC
0C5B-   AC AC AC    LDY   $ACAC
0C5E-   AC AC AC    LDY   $ACAC
0C61-   AC AC AC    LDY   $ACAC
0C64-   AA          TAX
0C65-   8D AA 8D    STA   $8DAA
0C68-   A0 CA       LDY   #$CA
0C6A-   D3          ???
0C6B-   D2 A0       CMP   ($A0)
0C6D-   C8          INY
0C6E-   CF          ???
0C6F-   CD C5 A0    CMP   $A0C5
0C72-   BB          ???
0C73-   20 C3 CC    JSR   $CCC3
0C76-   C5 C1       CMP   $C1
0C78-   D2 20       CMP   ($20)
0C7A-   D3          ???
0C7B-   C3          ???
0C7C-   D2 C5       CMP   ($C5)
0C7E-   C5 CE       CMP   $CE
0C80-   8D AA 8D    STA   $8DAA
0C83-   AA          TAX
0C84-   AA          TAX
0C85-   20 D3 C9    JSR   $C9D3
0C88-   CE C3 C5    DEC   $C5C3
0C8B-   20 D4 C8    JSR   $C8D4
0C8E-   C5 20       CMP   $20
0C90-   D3          ???
0C91-   D4          ???
0C92-   C4 C9       CPY   $C9
0C94-   CF          ???
0C95-   20 CC C9    JSR   $C9CC
0C98-   C2          ???
0C99-   D2 C1       CMP   ($C1)
0C9B-   D2 D9       CMP   ($D9)
0C9D-   20 C8 C1    JSR   $C1C8
0CA0-   D3          ???
0CA1-   20 CD C1    JSR   $C1CD
0CA4-   C3          ???
0CA5-   D2 CF       CMP   ($CF)
0CA7-   D3          ???
0CA8-   20 C9 CE    JSR   $CEC9
0CAB-   8D AA AA    STA   $AAAA
0CAE-   20 C1 C4    JSR   $C4C1
0CB1-   C4 C9       CPY   $C9
0CB3-   D4          ???
0CB4-   C9 CF       CMP   #$CF
0CB6-   CE 20 D4    DEC   $D420
0CB9-   CF          ???
0CBA-   20 D2 CF    JSR   $CFD2
0CBD-   D5 D4       CMP   $D4,X
0CBF-   C9 CE       CMP   #$CE
0CC1-   C5 D3       CMP   $D3
0CC3-   20 D4 C8    JSR   $C8D4
0CC6-   C1 D4       CMP   ($D4,X)
0CC8-   20 C6 D5    JSR   $D5C6
0CCB-   CE C3 D4    DEC   $D4C3
0CCE-   C9 CF       CMP   #$CF
0CD0-   CE 20 CF    DEC   $CF20
0CD3-   CE 8D AA    DEC   $AA8D
0CD6-   AA          TAX
0CD7-   20 D4 C8    JSR   $C8D4
0CDA-   C5 C9       CMP   $C9
0CDC-   D2 20       CMP   ($20)
0CDE-   CF          ???
0CDF-   D7          ???
0CE0-   CE AC 20    DEC   $20AC
0CE3-   D4          ???
0CE4-   C8          INY
0CE5-   C9 D3       CMP   #$D3
0CE7-   20 C4 C5    JSR   $C5C4
0CEA-   CD CF 20    CMP   $20CF
0CED-   D7          ???
0CEE-   C9 CC       CMP   #$CC
0CF0-   CC 20 D0    CPY   $D020
0CF3-   D2 C9       CMP   ($C9)
0CF5-   CD C1 D2    CMP   $D2C1
0CF8-   C9 CC       CMP   #$CC
0CFA-   D9 20 D5    CMP   $D520,Y
0CFD-   D3          ???
0CFE-   C5 8D       CMP   $8D
0D00-   AA          TAX
0D01-   AA          TAX
0D02-   20 CD C1    JSR   $C1CD
0D05-   C3          ???
0D06-   D2 CF       CMP   ($CF)
0D08-   D3          ???
0D09-   20 D4 CF    JSR   $CFD4
0D0C-   20 C9 CC    JSR   $CCC9
0D0F-   CC D5 D3    CPY   $D3D5
0D12-   D4          ???
0D13-   D2 C1       CMP   ($C1)
0D15-   D4          ???
0D16-   C5 20       CMP   $20
0D18-   D4          ???
0D19-   C8          INY
0D1A-   C5 C9       CMP   $C9
0D1C-   D2 20       CMP   ($20)
0D1E-   C6 D5       DEC   $D5
0D20-   CE C3 D4    DEC   $D4C3
0D23-   C9 CF       CMP   #$CF
0D25-   CE D3 AE    DEC   $AED3
0D28-   8D AA 8D    STA   $8DAA
0D2B-   AA          TAX
0D2C-   AA          TAX
0D2D-   20 D0 D2    JSR   $D2D0
0D30-   CE 20 D3    DEC   $D320
0D33-   C9 CD       CMP   #$CD
0D35-   D0 CC       BNE   $0D03
0D37-   D9 20 D0    CMP   $D020,Y
0D3A-   D2 C9       CMP   ($C9)
0D3C-   CE D4 D3    DEC   $D3D4
0D3F-   20 C1 20    JSR   $20C1
0D42-   D3          ???
0D43-   D4          ???
0D44-   D2 C9       CMP   ($C9)
0D46-   CE C7 20    DEC   $20C7
0D49-   CF          ???
0D4A-   C6 20       DEC   $20
0D4C-   D4          ???
0D4D-   C5 D8       CMP   $D8
0D4F-   D4          ???
0D50-   20 D4 CF    JSR   $CFD4
0D53-   20 D4 C8    JSR   $C8D4
0D56-   C5 8D       CMP   $8D
0D58-   AA          TAX
0D59-   AA          TAX
0D5A-   20 D3 C3    JSR   $C3D3
0D5D-   D2 C5       CMP   ($C5)
0D5F-   C5 CE       CMP   $CE
0D61-   20 C1 D4    JSR   $D4C1
0D64-   20 D4 C8    JSR   $C8D4
0D67-   C5 20       CMP   $20
0D69-   C3          ???
0D6A-   D5 D2       CMP   $D2,X
0D6C-   D2 C5       CMP   ($C5)
0D6E-   CE D4 20    DEC   $20D4
0D71-   C3          ???
0D72-   D5 D2       CMP   $D2,X
0D74-   D3          ???
0D75-   CF          ???
0D76-   D2 20       CMP   ($20)
0D78-   D0 CF       BNE   $0D49
0D7A-   D3          ???
0D7B-   C9 D4       CMP   #$D4
0D7D-   C9 CF       CMP   #$CF
0D7F-   CE AC 20    DEC   $20AC
0D82-   CF          ???
0D83-   D2 8D       CMP   ($8D)
0D85-   AA          TAX
0D86-   AA          TAX
0D87-   20 D0 D2    JSR   $D2D0
0D8A-   C9 CE       CMP   #$CE
0D8C-   D4          ???
0D8D-   D3          ???
0D8E-   20 D4 C8    JSR   $C8D4
0D91-   C5 20       CMP   $20
0D93-   C4 C1       CPY   $C1
0D95-   D4          ???
0D96-   C1 20       CMP   ($20,X)
0D98-   C1 D4       CMP   ($D4,X)
0D9A-   20 C1 20    JSR   $20C1
0D9D-   D0 C1       BNE   $0D60
0D9F-   D2 D4       CMP   ($D4)
0DA1-   C9 C3       CMP   #$C3
0DA3-   D5 CC       CMP   $CC,X
0DA5-   C1 D2       CMP   ($D2,X)
0DA7-   20 CD C5    JSR   $C5CD
0DAA-   CD CF D2    CMP   $D2CF
0DAD-   D9 20 C1    CMP   $C120,Y
0DB0-   C4 C4       CPY   $C4
0DB2-   D2 C5       CMP   ($C5)
0DB4-   D3          ???
0DB5-   D3          ???
0DB6-   AE 8D AA    LDX   $AA8D
0DB9-   AA          TAX
0DBA-   20 C9 D4    JSR   $D4C9
0DBD-   20 C1 C3    JSR   $C3C1
0DC0-   C3          ???
0DC1-   CF          ???
0DC2-   CD D0 CC    CMP   $CCD0
0DC5-   C9 D3       CMP   #$D3
0DC7-   C8          INY
0DC8-   C5 D3       CMP   $D3
0DCA-   20 D4 C8    JSR   $C8D4
0DCD-   C9 D3       CMP   #$D3
0DCF-   20 C2 D9    JSR   $D9C2
0DD2-   20 C4 C5    JSR   $C5C4
0DD5-   D4          ???
0DD6-   C5 D2       CMP   $D2
0DD8-   CD C9 CE    CMP   $CEC9
0DDB-   C9 CE       CMP   #$CE
0DDD-   C7          ???
0DDE-   20 C9 C6    JSR   $C6C9
0DE1-   20 D4 C8    JSR   $C8D4
0DE4-   C5 8D       CMP   $8D
0DE6-   AA          TAX
0DE7-   AA          TAX
0DE8-   20 D0 C1    JSR   $C1D0
0DEB-   D2 C1       CMP   ($C1)
0DED-   CD C5 D4    CMP   $D4C5
0DF0-   C5 D2       CMP   $D2
0DF2-   20 C9 D3    JSR   $D3C9
0DF5-   20 C1 20    JSR   $20C1
0DF8-   D3          ???
0DF9-   D4          ???
0DFA-   D2 C9       CMP   ($C9)
0DFC-   CE C7 20    DEC   $20C7
0DFF-   CF          ???
0E00-   D2 20       CMP   ($20)
0E02-   C1 CE       CMP   ($CE,X)
0E04-   20 C1 C4    JSR   $C4C1
0E07-   C4 D2       CPY   $D2
0E09-   C5 D3       CMP   $D3
0E0B-   D3          ???
0E0C-   AC 20 D4    LDY   $D420
0E0F-   C8          INY
0E10-   C5 CE       CMP   $CE
0E12-   20 C3 C1    JSR   $C1C3
0E15-   CC CC C9    CPY   $C9CC
0E18-   CE C7 8D    DEC   $8DC7
0E1B-   AA          TAX
0E1C-   AA          TAX
0E1D-   20 C5 C9    JSR   $C9C5
0E20-   D4          ???
0E21-   C8          INY
0E22-   C5 D2       CMP   $D2
0E24-   20 D8 D0    JSR   $D0D8
0E27-   D2 C9       CMP   ($C9)
0E29-   CE D4 20    DEC   $20D4
0E2C-   CF          ???
0E2D-   D2 20       CMP   ($20)
0E2F-   C4 D0       CPY   $D0
0E31-   D2 C9       CMP   ($C9)
0E33-   CE D4 AE    DEC   $AED4
0E36-   8D AA 8D    STA   $8DAA
0E39-   AA          TAX
0E3A-   AA          TAX
0E3B-   20 D4 C8    JSR   $C8D4
0E3E-   C5 20       CMP   $20
0E40-   D2 CF       CMP   ($CF)
0E42-   D5 D4       CMP   $D4,X
0E44-   C9 CE       CMP   #$CE
0E46-   C5 20       CMP   $20
0E48-   D1 D5       CMP   ($D5),Y
0E4A-   C9 D4       CMP   #$D4
0E4C-   D3          ???
0E4D-   20 D0 D2    JSR   $D2D0
0E50-   C9 CE       CMP   #$CE
0E52-   D4          ???
0E53-   C9 CE       CMP   #$CE
0E55-   C7          ???
0E56-   20 CF CE    JSR   $CECF
0E59-   C3          ???
0E5A-   C5 20       CMP   $20
0E5C-   D4          ???
0E5D-   C8          INY
0E5E-   C5 20       CMP   $20
0E60-   D6 C1       DEC   $C1,X
0E62-   CC D5 C5    CPY   $C5D5
0E65-   8D AA AA    STA   $AAAA
0E68-   20 CF C6    JSR   $C6CF
0E6B-   20 B0 B0    JSR   $B0B0
0E6E-   20 C9 D3    JSR   $D3C9
0E71-   20 C5 CE    JSR   $CEC5
0E74-   C3          ???
0E75-   CF          ???
0E76-   D5 CE       CMP   $CE,X
0E78-   D4          ???
0E79-   C5 D2       CMP   $D2
0E7B-   C5 C4       CMP   $C4
0E7D-   AC 20 C9    LDY   $C920
0E80-   CE 20 D4    DEC   $D420
0E83-   C8          INY
0E84-   C5 20       CMP   $20
0E86-   C3          ???
0E87-   C1 D3       CMP   ($D3,X)
0E89-   C5 20       CMP   $20
0E8B-   CF          ???
0E8C-   C6 20       DEC   $20
0E8E-   D0 D2       BNE   $0E62
0E90-   C9 CE       CMP   #$CE
0E92-   D4          ???
0E93-   C9 CE       CMP   #$CE
0E95-   C7          ???
0E96-   8D AA AA    STA   $AAAA
0E99-   20 C6 D2    JSR   $D2C6
0E9C-   CF          ???
0E9D-   CD 20 CD    CMP   $CD20
0EA0-   C5 CD       CMP   $CD
0EA2-   CF          ???
0EA3-   D2 D9       CMP   ($D9)
0EA5-   AE 20 CE    LDX   $CE20
0EA8-   CF          ???
0EA9-   D4          ???
0EAA-   C5 20       CMP   $20
0EAC-   D4          ???
0EAD-   C8          INY
0EAE-   C1 D4       CMP   ($D4,X)
0EB0-   20 C5 C9    JSR   $C9C5
0EB3-   D4          ???
0EB4-   C8          INY
0EB5-   C5 D2       CMP   $D2
0EB7-   20 C1 20    JSR   $20C1
0EBA-   CC C9 D4    CPY   $D4C9
0EBD-   C5 D2       CMP   $D2
0EBF-   C1 CC       CMP   ($CC,X)
0EC1-   20 CF D2    JSR   $D2CF
0EC4-   20 C1 CE    JSR   $CEC1
0EC7-   20 C1 C4    JSR   $C4C1
0ECA-   C4 D2       CPY   $D2
0ECC-   C5 D3       CMP   $D3
0ECE-   D3          ???
0ECF-   8D AA AA    STA   $AAAA
0ED2-   20 C9 D3    JSR   $D3C9
0ED5-   20 C1 C3    JSR   $C3C1
0ED8-   C3          ???
0ED9-   C5 D0       CMP   $D0
0EDB-   D4          ???
0EDC-   C5 C4       CMP   $C4
0EDE-   AC 20 C9    LDY   $C920
0EE1-   C6 20       DEC   $20
0EE3-   CE CF D4    DEC   $D4CF
0EE6-   20 C1 20    JSR   $20C1
0EE9-   D3          ???
0EEA-   D4          ???
0EEB-   D2 C9       CMP   ($C9)
0EED-   CE C7 BB    DEC   $BBC7
0EF0-   20 C2 CF    JSR   $CFC2
0EF3-   D4          ???
0EF4-   C8          INY
0EF5-   20 C1 D2    JSR   $D2C1
0EF8-   C5 20       CMP   $20
0EFA-   D4          ???
0EFB-   D2 C5       CMP   ($C5)
0EFD-   C1 D4       CMP   ($D4,X)
0EFF-   C5 C4       CMP   $C4
0F01-   20 C1 D3    JSR   $D3C1
0F04-   8D AA AA    STA   $AAAA
0F07-   20 C1 C4    JSR   $C4C1
0F0A-   C4 D2       CPY   $D2
0F0C-   C5 D3       CMP   $D3
0F0E-   D3          ???
0F0F-   C5 D3       CMP   $D3
0F11-   AC 20 C2    LDY   $C220
0F14-   D5 D4       CMP   $D4,X
0F16-   20 C9 CE    JSR   $CEC9
0F19-   20 D4 C8    JSR   $C8D4
0F1C-   C5 20       CMP   $20
0F1E-   CC C1 D4    CPY   $D4C1
0F21-   D4          ???
0F22-   C5 D2       CMP   $D2
0F24-   20 CE CF    JSR   $CFCE
0F27-   CE AD CC    DEC   $CCAD
0F2A-   C9 D4       CMP   #$D4
0F2C-   C5 D2       CMP   $D2
0F2E-   C1 CC       CMP   ($CC,X)
0F30-   20 C3 C1    JSR   $C1C3
0F33-   D3          ???
0F34-   C5 AC       CMP   $AC
0F36-   20 D4 C8    JSR   $C8D4
0F39-   C5 8D       CMP   $8D
0F3B-   AA          TAX
0F3C-   AA          TAX
0F3D-   20 C1 C4    JSR   $C4C1
0F40-   C4 D2       CPY   $D2
0F42-   C5 D3       CMP   $D3
0F44-   D3          ???
0F45-   20 C9 D3    JSR   $D3C9
0F48-   20 D0 D5    JSR   $D5D0
0F4B-   CC CC C5    CPY   $C5CC
0F4E-   C4 20       CPY   $20
0F50-   C6 D2       DEC   $D2
0F52-   CF          ???
0F53-   CD 20 D4    CMP   $D420
0F56-   C8          INY
0F57-   C5 20       CMP   $20
0F59-   C7          ???
0F5A-   C9 D6       CMP   #$D6
0F5C-   C5 CE       CMP   $CE
0F5E-   20 C1 C4    JSR   $C4C1
0F61-   C4 D2       CPY   $D2
0F63-   C5 D3       CMP   $D3
0F65-   D3          ???
0F66-   AC 20 CC    LDY   $CC20
0F69-   C9 CB       CMP   #$CB
0F6B-   C5 20       CMP   $20
0F6D-   C1 CE       CMP   ($CE,X)
0F6F-   8D AA AA    STA   $AAAA
0F72-   20 C9 CE    JSR   $CEC9
0F75-   C4 C9       CPY   $C9
0F77-   D2 C5       CMP   ($C5)
0F79-   C3          ???
0F7A-   D4          ???
0F7B-   20 D2 C5    JSR   $C5D2
0F7E-   C6 C5       DEC   $C5
0F80-   D2 C5       CMP   ($C5)
0F82-   CE C3 C5    DEC   $C5C3
0F85-   AE 8D AA    LDX   $AA8D
0F88-   8D AA AA    STA   $AAAA
0F8B-   20 CD C1    JSR   $C1CD
0F8E-   C3          ???
0F8F-   D2 CF       CMP   ($CF)
0F91-   BA          TSX
0F92-   20 D0 D2    JSR   $D2D0
0F95-   CE 20 A2    DEC   $A220
0F98-   D3          ???
0F99-   D4          ???
0F9A-   D2 C9       CMP   ($C9)
0F9C-   CE C7 A2    DEC   $A2C7
0F9F-   20 BC CF    JSR   $CFBC
0FA2-   D2 BE       CMP   ($BE)
0FA4-   20 D0 D2    JSR   $D2D0
0FA7-   CE 20 C9    DEC   $C920
0FAA-   CE C4 C9    DEC   $C9C4
0FAD-   D2 C5       CMP   ($C5)
0FAF-   C3          ???
0FB0-   D4          ???
0FB1-   DF          ???
0FB2-   C1 C4       CMP   ($C4,X)
0FB4-   C4 D2       CPY   $D2
0FB6-   C5 D3       CMP   $D3
0FB8-   D3          ???
0FB9-   8D AA AA    STA   $AAAA
0FBC-   20 20 20    JSR   $2020
0FBF-   20 20 20    JSR   $2020
0FC2-   20 20 BC    JSR   $BC20
0FC5-   CF          ???
0FC6-   D2 BE       CMP   ($BE)
0FC8-   20 D0 D2    JSR   $D2D0
0FCB-   CE 20 A3    DEC   $A320
0FCE-   D3          ???
0FCF-   D4          ???
0FD0-   D2 C9       CMP   ($C9)
0FD2-   CE C7 DF    DEC   $DFC7
0FD5-   C1 C4       CMP   ($C4,X)
0FD7-   C4 D2       CPY   $D2
0FD9-   C5 D3       CMP   $D3
0FDB-   D3          ???
0FDC-   8D AA 8D    STA   $8DAA
0FDF-   A0 D0       LDY   #$D0
0FE1-   D2 CE       CMP   ($CE)
0FE3-   A0 A2       LDY   #$A2
0FE5-   D4          ???
0FE6-   C8          INY
0FE7-   C5 20       CMP   $20
0FE9-   D0 D2       BNE   $0FBD
0FEB-   CE 20 CD    DEC   $CD20
0FEE-   C1 C3       CMP   ($C3,X)
0FF0-   D2 CF       CMP   ($CF)
0FF2-   20 D3 C9    JSR   $C9D3
0FF5-   CD D0 CC    CMP   $CCD0
0FF8-   D9 20 A2    CMP   $A220,Y
0FFB-   AC B8 C4    LDY   $C4B8
0FFE-   8D A0 D0    STA   $D0A0
1001-   D2 CE       CMP   ($CE)
1003-   A0 A2       LDY   #$A2
1005-   C4 C9       CPY   $C9
1007-   D3          ???
1008-   D0 CC       BNE   $0FD6
100A-   C1 D9       CMP   ($D9,X)
100C-   D3          ???
100D-   20 C1 20    JSR   $20C1
1010-   CC C9 D4    CPY   $D4C9
1013-   C5 D2       CMP   $D2
1015-   C1 CC       CMP   ($CC,X)
1017-   20 D3 D4    JSR   $D4D3
101A-   D2 C9       CMP   ($C9)
101C-   CE C7 20    DEC   $20C7
101F-   A2 AC       LDX   #$AC
1021-   B8          CLV
1022-   C4 8D       CPY   $8D
1024-   A0 D0       LDY   #$D0
1026-   D2 CE       CMP   ($CE)
1028-   A0 A2       LDY   #$A2
102A-   CF          ???
102B-   D2 20       CMP   ($20)
102D-   C4 C1       CPY   $C1
102F-   D4          ???
1030-   C1 20       CMP   ($20,X)
1032-   CC CF C3    CPY   $C3CF
1035-   C1 D4       CMP   ($D4,X)
1037-   C5 C4       CMP   $C4
1039-   20 C1 D4    JSR   $D4C1
103C-   20 C1 20    JSR   $20C1
103F-   D3          ???
1040-   D0 C5       BNE   $1007
1042-   C3          ???
1043-   C9 C6       CMP   #$C6
1045-   C9 C3       CMP   #$C3
1047-   20 A2 AC    JSR   $ACA2
104A-   B8          CLV
104B-   C4 8D       CPY   $8D
104D-   A0 D0       LDY   #$D0
104F-   D2 CE       CMP   ($CE)
1051-   A0 A2       LDY   #$A2
1053-   C1 C4       CMP   ($C4,X)
1055-   C4 D2       CPY   $D2
1057-   C5 D3       CMP   $D3
1059-   D3          ???
105A-   20 A8 D4    JSR   $D4A8
105D-   C8          INY
105E-   C5 20       CMP   $20
1060-   CC C1 D4    CPY   $D4C1
1063-   D4          ???
1064-   C5 D2       CMP   $D2
1066-   20 D7 C9    JSR   $C9D7
1069-   CC CC 20    CPY   $20CC
106C-   C2          ???
106D-   C5 20       CMP   $20
106F-   D3          ???
1070-   C8          INY
1071-   CF          ???
1072-   D7          ???
1073-   CE A2 AC    DEC   $ACA2
1076-   B8          CLV
1077-   C4 8D       CPY   $8D
1079-   A0 D0       LDY   #$D0
107B-   D2 CE       CMP   ($CE)
107D-   A0 A2       LDY   #$A2
107F-   C1 C6       CMP   ($C6,X)
1081-   D4          ???
1082-   C5 D2       CMP   $D2
1084-   20 D4 C8    JSR   $C8D4
1087-   C5 20       CMP   $20
1089-   C9 CE       CMP   #$CE
108B-   D0 20       BNE   $10AD
108D-   CD C1 C3    CMP   $C3C1
1090-   D2 CF       CMP   ($CF)
1092-   AE A2 AC    LDX   $ACA2
1095-   B8          CLV
1096-   C4 B8       CPY   $B8
1098-   C4 8D       CPY   $8D
109A-   A0 D0       LDY   #$D0
109C-   D2 CE       CMP   ($CE)
109E-   A0 A2       LDY   #$A2
10A0-   CE CF D4    DEC   $D4CF
10A3-   C5 20       CMP   $20
10A5-   D4          ???
10A6-   C8          INY
10A7-   C1 D4       CMP   ($D4,X)
10A9-   20 C1 20    JSR   $20C1
10AC-   CE C5 D7    DEC   $D7C5
10AF-   20 CC C9    JSR   $C9CC
10B2-   CE C5 20    DEC   $20C5
10B5-   C3          ???
10B6-   C1 CE       CMP   ($CE,X)
10B8-   20 C2 C5    JSR   $C5C2
10BB-   20 D3 C5    JSR   $C5D3
10BE-   CE D4 20    DEC   $20D4
10C1-   A2 AC       LDX   #$AC
10C3-   B8          CLV
10C4-   C4 8D       CPY   $8D
10C6-   A0 D0       LDY   #$D0
10C8-   D2 CE       CMP   ($CE)
10CA-   A0 A2       LDY   #$A2
10CC-   C2          ???
10CD-   D9 20 C1    CMP   $C120,Y
10D0-   C4 C4       CPY   $C4
10D2-   C9 CE       CMP   #$CE
10D4-   C7          ???
10D5-   20 AC B8    JSR   $B8AC
10D8-   C4 20       CPY   $20
10DA-   C1 C6       CMP   ($C6,X)
10DC-   D4          ???
10DD-   C5 D2       CMP   $D2
10DF-   20 D4 C8    JSR   $C8D4
10E2-   C5 20       CMP   $20
10E4-   C5 CE       CMP   $CE
10E6-   C4 C9       CPY   $C9
10E8-   CE C7 20    DEC   $20C7
10EB-   A2 AC       LDX   #$AC
10ED-   B8          CLV
10EE-   C4 8D       CPY   $8D
10F0-   A0 D0       LDY   #$D0
10F2-   D2 CE       CMP   ($CE)
10F4-   A0 A2       LDY   #$A2
10F6-   D3          ???
10F7-   D4          ???
10F8-   D2 C9       CMP   ($C9)
10FA-   CE C7 20    DEC   $20C7
10FD-   C4 C5       CPY   $C5
10FF-   CC C9 CD    CPY   $CDC9
1102-   C9 D4       CMP   #$D4
1104-   C5 D2       CMP   $D2
1106-   AE A2 AC    LDX   $ACA2
1109-   B8          CLV
110A-   C4 B8       CPY   $B8
110C-   C4 8D       CPY   $8D
110E-   A0 D7       LDY   #$D7
1110-   C1 C9       CMP   ($C9,X)
1112-   D4          ???
1113-   8D AA 8D    STA   $8DAA
1116-   AA          TAX
1117-   AA          TAX
1118-   20 CD C1    JSR   $C1CD
111B-   C3          ???
111C-   D2 CF       CMP   ($CF)
111E-   BA          TSX
111F-   20 C9 CE    JSR   $CEC9
1122-   D0 AC       BNE   $10D0
1124-   20 CE CF    JSR   $CFCE
1127-   20 D0 C1    JSR   $C1D0
112A-   D2 C1       CMP   ($C1)
112C-   CD C5 D4    CMP   $D4C5
112F-   C5 D2       CMP   $D2
1131-   D3          ???
1132-   8D AA 8D    STA   $8DAA
1135-   A0 CA       LDY   #$CA
1137-   D3          ???
1138-   D2 A0       CMP   ($A0)
113A-   C8          INY
113B-   CF          ???
113C-   CD C5 8D    CMP   $8DC5
113F-   A0 D0       LDY   #$D0
1141-   D2 CE       CMP   ($CE)
1143-   A0 A2       LDY   #$A2
1145-   D4          ???
1146-   C8          INY
1147-   C5 20       CMP   $20
1149-   C9 CE       CMP   #$CE
114B-   D0 20       BNE   $116D
114D-   CD C1 C3    CMP   $C3C1
1150-   D2 CF       CMP   ($CF)
1152-   20 C1 C3    JSR   $C3C1
1155-   C3          ???
1156-   C5 D0       CMP   $D0
1158-   D4          ???
1159-   D3          ???
115A-   20 D5 D0    JSR   $D0D5
115D-   20 D4 CF    JSR   $CFD4
1160-   A2 AC       LDX   #$AC
1162-   B8          CLV
1163-   C4 8D       CPY   $8D
1165-   A0 D0       LDY   #$D0
1167-   D2 CE       CMP   ($CE)
1169-   A0 A2       LDY   #$A2
116B-   B2 B5       LDA   ($B5)
116D-   B5 20       LDA   $20,X
116F-   C3          ???
1170-   C8          INY
1171-   C1 D2       CMP   ($D2,X)
1173-   C1 C3       CMP   ($C3,X)
1175-   D4          ???
1176-   C5 D2       CMP   $D2
1178-   D3          ???
1179-   20 C1 CE    JSR   $CEC1
117C-   C4 20       CPY   $20
117E-   D3          ???
117F-   D4          ???
1180-   CF          ???
1181-   D2 C5       CMP   ($C5)
1183-   D3          ???
1184-   20 D4 C8    JSR   $C8D4
1187-   C5 CD       CMP   $CD
1189-   A2 AC       LDX   #$AC
118B-   B8          CLV
118C-   C4 8D       CPY   $8D
118E-   A0 D0       LDY   #$D0
1190-   D2 CE       CMP   ($CE)
1192-   A0 A2       LDY   #$A2
1194-   C9 CE       CMP   #$CE
1196-   20 DB D2    JSR   $D2DB
1199-   C5 D4       CMP   $D4
119B-   D5 D2       CMP   $D2,X
119D-   CE DD AE    DEC   $AEDD
11A0-   20 D4 C8    JSR   $C8D4
11A3-   C9 D3       CMP   #$D3
11A5-   20 C3 C1    JSR   $C1C3
11A8-   CE 20 C2    DEC   $C220
11AB-   C5 20       CMP   $20
11AD-   C5 C1       CMP   $C1
11AF-   D3          ???
11B0-   C9 CC       CMP   #$CC
11B2-   D9 A2 AC    CMP   $ACA2,Y
11B5-   B8          CLV
11B6-   C4 8D       CPY   $8D
11B8-   A0 D0       LDY   #$D0
11BA-   D2 CE       CMP   ($CE)
11BC-   A0 A2       LDY   #$A2
11BE-   D0 D2       BNE   $1192
11C0-   C9 CE       CMP   #$CE
11C2-   D4          ???
11C3-   C5 C4       CMP   $C4
11C5-   20 C9 CD    JSR   $CDC9
11C8-   CD C5 C4    CMP   $C4C5
11CB-   C9 C1       CMP   #$C1
11CD-   D4          ???
11CE-   C5 CC       CMP   $CC
11D0-   D9 20 D7    CMP   $D720,Y
11D3-   C9 D4       CMP   #$D4
11D5-   C8          INY
11D6-   20 D0 D2    JSR   $D2D0
11D9-   CE 20 C2    DEC   $C220
11DC-   D9 A2 AC    CMP   $ACA2,Y
11DF-   B8          CLV
11E0-   C4 8D       CPY   $8D
11E2-   A0 D0       LDY   #$D0
11E4-   D2 CE       CMP   ($CE)
11E6-   A0 A2       LDY   #$A2
11E8-   D5 D3       CMP   $D3,X
11EA-   C9 CE       CMP   #$CE
11EC-   C7          ???
11ED-   20 D4 C8    JSR   $C8D4
11F0-   C5 20       CMP   $20
11F2-   C1 C4       CMP   ($C4,X)
11F4-   C4 D2       CPY   $D2
11F6-   C5 D3       CMP   $D3
11F8-   D3          ???
11F9-   20 CD CF    JSR   $CFCD
11FC-   C4 C5       CPY   $C5
11FE-   AE A2 AC    LDX   $ACA2
1201-   B8          CLV
1202-   C4 B8       CPY   $B8
1204-   C4 8D       CPY   $8D
1206-   A0 D0       LDY   #$D0
1208-   D2 CE       CMP   ($CE)
120A-   A0 A2       LDY   #$A2
120C-   C5 CE       CMP   $CE
120E-   D4          ???
120F-   C5 D2       CMP   $D2
1211-   20 D3 CF    JSR   $CFD3
1214-   CD C5 D4    CMP   $D4C5
1217-   C8          INY
1218-   C9 CE       CMP   #$CE
121A-   C7          ???
121B-   BA          TSX
121C-   20 A2 8D    JSR   $8DA2
121F-   A0 C9       LDY   #$C9
1221-   CE D0 8D    DEC   $8DD0
1224-   A0 D0       LDY   #$D0
1226-   D2 CE       CMP   ($CE)
1228-   A0 A2       LDY   #$A2
122A-   20 A2 AC    JSR   $ACA2
122D-   B8          CLV
122E-   C4 B8       CPY   $B8
1230-   C4 8D       CPY   $8D
1232-   A0 D0       LDY   #$D0
1234-   D2 CE       CMP   ($CE)
1236-   A0 A2       LDY   #$A2
1238-   D9 CF D5    CMP   $D5CF,Y
123B-   20 D7 D2    JSR   $D2D7
123E-   CF          ???
123F-   D4          ???
1240-   C5 BA       CMP   $BA
1242-   20 A2 AC    JSR   $ACA2
1245-   B8          CLV
1246-   C4 B8       CPY   $B8
1248-   C4 8D       CPY   $8D
124A-   A0 D0       LDY   #$D0
124C-   D2 CE       CMP   ($CE)
124E-   A0 A3       LDY   #$A3
1250-   D2 C5       CMP   ($C5)
1252-   D4          ???
1253-   D5 D2       CMP   $D2,X
1255-   CE 8D A0    DEC   $A08D
1258-   D0 D2       BNE   $122C
125A-   CE A0 A2    DEC   $A2A0
125D-   20 A2 AC    JSR   $ACA2
1260-   B8          CLV
1261-   C4 B8       CPY   $B8
1263-   C4 8D       CPY   $8D
1265-   A0 D7       LDY   #$D7
1267-   C1 C9       CMP   ($C9,X)
1269-   D4          ???
126A-   8D AA 8D    STA   $8DAA
126D-   AA          TAX
126E-   AA          TAX
126F-   20 CD C1    JSR   $C1CD
1272-   C3          ???
1273-   D2 CF       CMP   ($CF)
1275-   BA          TSX
1276-   20 C7 CB    JSR   $CBC7
1279-   C5 D9       CMP   $D9
127B-   AC 20 CE    LDY   $CE20
127E-   CF          ???
127F-   20 D0 C1    JSR   $C1D0
1282-   D2 C1       CMP   ($C1)
1284-   CD C5 D4    CMP   $D4C5
1287-   C5 D2       CMP   $D2
1289-   D3          ???
128A-   8D AA 8D    STA   $8DAA
128D-   A0 D0       LDY   #$D0
128F-   D2 CE       CMP   ($CE)
1291-   A0 A2       LDY   #$A2
1293-   D4          ???
1294-   C8          INY
1295-   C5 20       CMP   $20
1297-   C7          ???
1298-   CB          ???
1299-   C5 D9       CMP   $D9
129B-   20 CD C1    JSR   $C1CD
129E-   C3          ???
129F-   D2 CF       CMP   ($CF)
12A1-   20 D3 C9    JSR   $C9D3
12A4-   CD D0 CC    CMP   $CCD0
12A7-   D9 20 C7    CMP   $C720,Y
12AA-   C5 D4       CMP   $D4
12AC-   D3          ???
12AD-   A2 AC       LDX   #$AC
12AF-   B8          CLV
12B0-   C4 8D       CPY   $8D
12B2-   A0 D0       LDY   #$D0
12B4-   D2 CE       CMP   ($CE)
12B6-   A0 A2       LDY   #$A2
12B8-   C1 20       CMP   ($20,X)
12BA-   D3          ???
12BB-   C9 CE       CMP   #$CE
12BD-   C7          ???
12BE-   CC C5 20    CPY   $20C5
12C1-   CB          ???
12C2-   C5 D9       CMP   $D9
12C4-   D0 D2       BNE   $1298
12C6-   C5 D3       CMP   $D3
12C8-   D3          ???
12C9-   AC 20 D3    LDY   $D320
12CC-   D4          ???
12CD-   CF          ???
12CE-   D2 C5       CMP   ($C5)
12D0-   C4 20       CPY   $20
12D2-   C9 CE       CMP   #$CE
12D4-   20 AE C1    JSR   $C1AE
12D7-   A2 AC       LDX   #$AC
12D9-   B8          CLV
12DA-   C4 B8       CPY   $B8
12DC-   C4 8D       CPY   $8D
12DE-   A0 C7       LDY   #$C7
12E0-   CB          ???
12E1-   C5 D9       CMP   $D9
12E3-   8D AA 8D    STA   $8DAA
12E6-   AA          TAX
12E7-   AA          TAX
12E8-   20 CD C1    JSR   $C1CD
12EB-   C3          ???
12EC-   D2 CF       CMP   ($CF)
12EE-   BA          TSX
12EF-   20 D3 C3    JSR   $C3D3
12F2-   D0 CF       BNE   $12C3
12F4-   D3          ???
12F5-   20 D8 DF    JSR   $DFD8
12F8-   D0 CF       BNE   $12C9
12FA-   D3          ???
12FB-   C9 D4       CMP   #$D4
12FD-   C9 CF       CMP   #$CF
12FF-   CE BB D9    DEC   $D9BB
1302-   DF          ???
1303-   D0 CF       BNE   $12D4
1305-   D3          ???
1306-   C9 D4       CMP   #$D4
1308-   C9 CF       CMP   #$CF
130A-   CE 8D AA    DEC   $AA8D
130D-   AA          TAX
130E-   20 CD C1    JSR   $C1CD
1311-   C3          ???
1312-   D2 CF       CMP   ($CF)
1314-   BA          TSX
1315-   20 D3 C5    JSR   $C5D3
1318-   D4          ???
1319-   C3          ???
131A-   D8          CLD
131B-   20 D8 DF    JSR   $DFD8
131E-   D0 CF       BNE   $12EF
1320-   D3          ???
1321-   C9 D4       CMP   #$D4
1323-   C9 CF       CMP   #$CF
1325-   CE 8D AA    DEC   $AA8D
1328-   AA          TAX
1329-   20 CD C1    JSR   $C1CD
132C-   C3          ???
132D-   D2 CF       CMP   ($CF)
132F-   BA          TSX
1330-   20 D3 C5    JSR   $C5D3
1333-   D4          ???
1334-   C3          ???
1335-   D9 20 D9    CMP   $D920,Y
1338-   DF          ???
1339-   D0 CF       BNE   $130A
133B-   D3          ???
133C-   C9 D4       CMP   #$D4
133E-   C9 CF       CMP   #$CF
1340-   CE 8D AA    DEC   $AA8D
1343-   8D A0 CA    STA   $CAA0
1346-   D3          ???
1347-   D2 A0       CMP   ($A0)
1349-   C8          INY
134A-   CF          ???
134B-   CD C5 8D    CMP   $8DC5
134E-   A0 D3       LDY   #$D3
1350-   C3          ???
1351-   D0 CF       BNE   $1322
1353-   D3          ???
1354-   A0 A3       LDY   #$A3
1356-   B1 B0       LDA   ($B0),Y
1358-   BB          ???
1359-   A3          ???
135A-   B1 B5       LDA   ($B5),Y
135C-   8D A0 D0    STA   $D0A0
135F-   D2 CE       CMP   ($CE)
1361-   A0 A2       LDY   #$A2
1363-   D3          ???
1364-   C3          ???
1365-   D0 CF       BNE   $1336
1367-   D3          ???
1368-   20 D0 CF    JSR   $CFD0
136B-   D3          ???
136C-   C9 D4       CMP   #$D4
136E-   C9 CF       CMP   #$CF
1370-   CE D3 20    DEC   $20D3
1373-   D4          ???
1374-   C8          INY
1375-   C5 20       CMP   $20
1377-   C3          ???
1378-   D5 D2       CMP   $D2,X
137A-   D3          ???
137B-   CF          ???
137C-   D2 A2       CMP   ($A2)
137E-   8D A0 D0    STA   $D0A0
1381-   D2 CE       CMP   ($CE)
1383-   A0 A2       LDY   #$A2
1385-   20 C1 D4    JSR   $D4C1
1388-   20 D4 C8    JSR   $C8D4
138B-   C5 20       CMP   $20
138D-   C7          ???
138E-   C9 D6       CMP   #$D6
1390-   C5 CE       CMP   $CE
1392-   20 D8 AC    JSR   $ACD8
1395-   D9 AE A2    CMP   $A2AE,Y
1398-   8D A0 D7    STA   $D7A0
139B-   C1 C9       CMP   ($C9,X)
139D-   D4          ???
139E-   8D A0 D3    STA   $D3A0
13A1-   C5 D4       CMP   $D4
13A3-   C3          ???
13A4-   D9 A0 A3    CMP   $A3A0,Y
13A7-   B2 B0       LDA   ($B0)
13A9-   8D A0 D3    STA   $D3A0
13AC-   C5 D4       CMP   $D4
13AE-   C3          ???
13AF-   D8          CLD
13B0-   A0 A3       LDY   #$A3
13B2-   B1 8D       LDA   ($8D),Y
13B4-   A0 D0       LDY   #$D0
13B6-   D2 CE       CMP   ($CE)
13B8-   A0 A2       LDY   #$A2
13BA-   D3          ???
13BB-   C5 D4       CMP   $D4
13BD-   C3          ???
13BE-   D8          CLD
13BF-   20 D3 C5    JSR   $C5D3
13C2-   D4          ???
13C3-   D3          ???
13C4-   20 D8 20    JSR   $20D8
13C7-   D0 CF       BNE   $1398
13C9-   D3          ???
13CA-   C9 D4       CMP   #$D4
13CC-   C9 CF       CMP   #$CF
13CE-   CE 20 A2    DEC   $A220
13D1-   8D A0 D3    STA   $D3A0
13D4-   C5 D4       CMP   $D4
13D6-   C3          ???
13D7-   D9 A0 A3    CMP   $A3A0,Y
13DA-   B2 B2       LDA   ($B2)
13DC-   8D A0 D0    STA   $D0A0
13DF-   D2 CE       CMP   ($CE)
13E1-   A0 A2       LDY   #$A2
13E3-   D3          ???
13E4-   C5 D4       CMP   $D4
13E6-   C3          ???
13E7-   D9 20 D3    CMP   $D320,Y
13EA-   C5 D4       CMP   $D4
13EC-   D3          ???
13ED-   20 D4 C8    JSR   $C8D4
13F0-   C5 20       CMP   $20
13F2-   D9 A2 8D    CMP   $8DA2,Y
13F5-   A0 D7       LDY   #$D7
13F7-   C1 C9       CMP   ($C9,X)
13F9-   D4          ???
13FA-   8D AA 8D    STA   $8DAA
13FD-   AA          TAX
13FE-   AA          TAX
13FF-   20 CD C1    JSR   $C1CD
1402-   C3          ???
1403-   D2 CF       CMP   ($CF)
1405-   BA          TSX
1406-   20 C3 D5    JSR   $D5C3
1409-   D2 C6       CMP   ($C6)
140B-   20 CE D5    JSR   $D5CE
140E-   CD C2 C5    CMP   $C5C2
1411-   D2 DF       CMP   ($DF)
1413-   CF          ???
1414-   C6 DF       DEC   $DF
1416-   D3          ???
1417-   D0 C1       BNE   $13DA
1419-   C3          ???
141A-   C5 D3       CMP   $D3
141C-   8D AA AA    STA   $AAAA
141F-   20 20 20    JSR   $2020
1422-   20 20 20    JSR   $2020
1425-   20 20 C3    JSR   $C320
1428-   D5 D2       CMP   $D2,X
142A-   C2          ???
142B-   20 CE D5    JSR   $D5CE
142E-   CD C2 C5    CMP   $C5C2
1431-   D2 DF       CMP   ($DF)
1433-   CF          ???
1434-   C6 DF       DEC   $DF
1436-   D3          ???
1437-   D0 C1       BNE   $13FA
1439-   C3          ???
143A-   C5 D3       CMP   $D3
143C-   8D AA AA    STA   $AAAA
143F-   20 20 20    JSR   $2020
1442-   20 20 20    JSR   $2020
1445-   20 20 C3    JSR   $C320
1448-   D5 D2       CMP   $D2,X
144A-   D5 20       CMP   $20,X
144C-   CE D5 CD    DEC   $CDD5
144F-   C2          ???
1450-   C5 D2       CMP   $D2
1452-   DF          ???
1453-   CF          ???
1454-   C6 DF       DEC   $DF
1456-   D3          ???
1457-   D0 C1       BNE   $141A
1459-   C3          ???
145A-   C5 D3       CMP   $D3
145C-   8D AA AA    STA   $AAAA
145F-   20 20 20    JSR   $2020
1462-   20 20 20    JSR   $2020
1465-   20 20 C3    JSR   $C320
1468-   D5 D2       CMP   $D2,X
146A-   C4 20       CPY   $20
146C-   CE D5 CD    DEC   $CDD5
146F-   C2          ???
1470-   C5 D2       CMP   $D2
1472-   DF          ???
1473-   CF          ???
1474-   C6 DF       DEC   $DF
1476-   D3          ???
1477-   D0 C1       BNE   $143A
1479-   C3          ???
147A-   C5 D3       CMP   $D3
147C-   8D AA 8D    STA   $8DAA
147F-   A0 CA       LDY   #$CA
1481-   D3          ???
1482-   D2 A0       CMP   ($A0)
1484-   C8          INY
1485-   CF          ???
1486-   CD C5 8D    CMP   $8DC5
1489-   A0 D0       LDY   #$D0
148B-   D2 CE       CMP   ($CE)
148D-   A0 A2       LDY   #$A2
148F-   D4          ???
1490-   C8          INY
1491-   C5 20       CMP   $20
1493-   C3          ???
1494-   D5 D2       CMP   $D2,X
1496-   D3          ???
1497-   CF          ???
1498-   D2 20       CMP   ($20)
149A-   C3          ???
149B-   C1 CE       CMP   ($CE,X)
149D-   20 C1 CC    JSR   $CCC1
14A0-   D3          ???
14A1-   CF          ???
14A2-   20 C2 C5    JSR   $C5C2
14A5-   20 CD CF    JSR   $CFCD
14A8-   D6 C5       DEC   $C5,X
14AA-   C4 A2       CPY   $A2
14AC-   8D A0 D7    STA   $D7A0
14AF-   C1 C9       CMP   ($C9,X)
14B1-   D4          ???
14B2-   8D A0 C3    STA   $C3A0
14B5-   D5 D2       CMP   $D2,X
14B7-   C6 A0       DEC   $A0
14B9-   A3          ???
14BA-   B1 B0       LDA   ($B0),Y
14BC-   8D A0 D0    STA   $D0A0
14BF-   D2 CE       CMP   ($CE)
14C1-   A0 A2       LDY   #$A2
14C3-   D2 C5       CMP   ($C5)
14C5-   CC C1 D4    CPY   $D4C1
14C8-   C9 D6       CMP   #$D6
14CA-   C5 20       CMP   $20
14CC-   D4          ???
14CD-   CF          ???
14CE-   20 D4 C8    JSR   $C8D4
14D1-   C5 20       CMP   $20
14D3-   C3          ???
14D4-   D5 D2       CMP   $D2,X
14D6-   D2 C5       CMP   ($C5)
14D8-   CE D4 A2    DEC   $A2D4
14DB-   8D A0 D7    STA   $D7A0
14DE-   C1 C9       CMP   ($C9,X)
14E0-   D4          ???
14E1-   8D A0 C3    STA   $C3A0
14E4-   D5 D2       CMP   $D2,X
14E6-   C4 A0       CPY   $A0
14E8-   A3          ???
14E9-   B0 B3       BCS   $149E
14EB-   8D A0 D0    STA   $D0A0
14EE-   D2 CE       CMP   ($CE)
14F0-   A0 A2       LDY   #$A2
14F2-   D0 CF       BNE   $14C3
14F4-   D3          ???
14F5-   C9 D4       CMP   #$D4
14F7-   C9 CF       CMP   #$CF
14F9-   CE 20 D7    DEC   $D720
14FC-   C9 D4       CMP   #$D4
14FE-   C8          INY
14FF-   20 D4 C8    JSR   $C8D4
1502-   C5 20       CMP   $20
1504-   C3          ???
1505-   D5 D2       CMP   $D2,X
1507-   C6 AC       DEC   $AC
1509-   C3          ???
150A-   D5 D2       CMP   $D2,X
150C-   C4 AC       CPY   $AC
150E-   A2 8D       LDX   #$8D
1510-   A0 D7       LDY   #$D7
1512-   C1 C9       CMP   ($C9,X)
1514-   D4          ???
1515-   8D A0 C3    STA   $C3A0
1518-   D5 D2       CMP   $D2,X
151A-   C4 A0       CPY   $A0
151C-   A3          ???
151D-   B8          CLV
151E-   8D A0 D3    STA   $D3A0
1521-   C5 D4       CMP   $D4
1523-   C3          ???
1524-   D8          CLD
1525-   A0 A3       LDY   #$A3
1527-   B1 B2       LDA   ($B2),Y
1529-   8D A0 C3    STA   $C3A0
152C-   D5 D2       CMP   $D2,X
152E-   C2          ???
152F-   A0 A3       LDY   #$A3
1531-   B1 B0       LDA   ($B0),Y
1533-   8D A0 D0    STA   $D0A0
1536-   D2 CE       CMP   ($CE)
1538-   A0 A2       LDY   #$A2
153A-   C3          ???
153B-   D5 D2       CMP   $D2,X
153D-   C2          ???
153E-   20 C1 CE    JSR   $CEC1
1541-   C4 A2       CPY   $A2
1543-   8D A0 C3    STA   $C3A0
1546-   D5 D2       CMP   $D2,X
1548-   D5 A0       CMP   $A0,X
154A-   A3          ???
154B-   B0 B5       BCS   $1502
154D-   8D A0 D0    STA   $D0A0
1550-   D2 CE       CMP   ($CE)
1552-   A0 A2       LDY   #$A2
1554-   C3          ???
1555-   D5 D2       CMP   $D2,X
1557-   D5 20       CMP   $20,X
1559-   A8          TAY
155A-   C6 CF       DEC   $CF
155C-   D2 D7       CMP   ($D7)
155E-   C1 D2       CMP   ($D2,X)
1560-   C4 AC       CPY   $AC
1562-   20 C4 CF    JSR   $CFC4
1565-   D7          ???
1566-   CE AC 20    DEC   $20AC
1569-   C2          ???
156A-   C1 C3       CMP   ($C3,X)
156C-   CB          ???
156D-   AC 20 D5    LDY   $D520
1570-   D0 A9       BNE   $151B
1572-   A2 8D       LDX   #$8D
1574-   A0 D7       LDY   #$D7
1576-   C1 C9       CMP   ($C9,X)
1578-   D4          ???
1579-   8D AA 8D    STA   $8DAA
157C-   AA          TAX
157D-   AA          TAX
157E-   20 CD C1    JSR   $C1CD
1581-   C3          ???
1582-   D2 CF       CMP   ($CF)
1584-   BA          TSX
1585-   20 D2 C3    JSR   $C3D2
1588-   D0 CF       BNE   $1559
158A-   D3          ???
158B-   20 D8 DF    JSR   $DFD8
158E-   D0 CF       BNE   $155F
1590-   D3          ???
1591-   C9 D4       CMP   #$D4
1593-   C9 CF       CMP   #$CF
1595-   CE BB D9    DEC   $D9BB
1598-   DF          ???
1599-   D0 CF       BNE   $156A
159B-   D3          ???
159C-   C9 D4       CMP   #$D4
159E-   C9 CF       CMP   #$CF
15A0-   CE 8D AA    DEC   $AA8D
15A3-   8D A0 CA    STA   $CAA0
15A6-   D3          ???
15A7-   D2 A0       CMP   ($A0)
15A9-   C8          INY
15AA-   CF          ???
15AB-   CD C5 8D    CMP   $8DC5
15AE-   A0 D0       LDY   #$D0
15B0-   D2 CE       CMP   ($CE)
15B2-   A0 A2       LDY   #$A2
15B4-   C1 C1       CMP   ($C1,X)
15B6-   C1 C1       CMP   ($C1,X)
15B8-   C1 C1       CMP   ($C1,X)
15BA-   C1 C1       CMP   ($C1,X)
15BC-   C1 C1       CMP   ($C1,X)
15BE-   A2 8D       LDX   #$8D
15C0-   A0 D3       LDY   #$D3
15C2-   C3          ???
15C3-   D0 CF       BNE   $1594
15C5-   D3          ???
15C6-   A0 A3       LDY   #$A3
15C8-   B0 B5       BCS   $157F
15CA-   BB          ???
15CB-   A3          ???
15CC-   B0 B5       BCS   $1583
15CE-   8D A0 D0    STA   $D0A0
15D1-   D2 CE       CMP   ($CE)
15D3-   A0 A2       LDY   #$A2
15D5-   C1 C1       CMP   ($C1,X)
15D7-   C2          ???
15D8-   C2          ???
15D9-   C3          ???
15DA-   C3          ???
15DB-   A2 AC       LDX   #$AC
15DD-   B8          CLV
15DE-   C4 B8       CPY   $B8
15E0-   C4 B8       CPY   $B8
15E2-   C4 8D       CPY   $8D
15E4-   A0 D2       LDY   #$D2
15E6-   C3          ???
15E7-   D0 CF       BNE   $15B8
15E9-   D3          ???
15EA-   A0 A3       LDY   #$A3
15EC-   B0 B5       BCS   $15A3
15EE-   BB          ???
15EF-   A3          ???
15F0-   B0 B5       BCS   $15A7
15F2-   8D A0 D3    STA   $D3A0
15F5-   D4          ???
15F6-   C1 A0       CMP   ($A0,X)
15F8-   A4 B3       LDY   $B3
15FA-   B0 B0       BCS   $15AC
15FC-   8D A0 D0    STA   $D0A0
15FF-   D2 CE       CMP   ($CE)
1601-   A0 A2       LDY   #$A2
1603-   20 A2 AC    JSR   $ACA2
1606-   B8          CLV
1607-   C4 8D       CPY   $8D
1609-   A0 D0       LDY   #$D0
160B-   D2 CE       CMP   ($CE)
160D-   A0 A2       LDY   #$A2
160F-   D4          ???
1610-   C8          INY
1611-   C5 20       CMP   $20
1613-   D2 C3       CMP   ($C3)
1615-   D0 CF       BNE   $15E6
1617-   D3          ???
1618-   20 CD C1    JSR   $C1CD
161B-   C3          ???
161C-   D2 CF       CMP   ($CF)
161E-   20 D2 C5    JSR   $C5D2
1621-   D4          ???
1622-   D5 D2       CMP   $D2,X
1624-   CE D3 20    DEC   $20D3
1627-   D4          ???
1628-   C8          INY
1629-   C5 A2       CMP   $A2
162B-   AC B8 C4    LDY   $C4B8
162E-   8D A0 D0    STA   $D0A0
1631-   D2 CE       CMP   ($CE)
1633-   A0 A2       LDY   #$A2
1635-   C3          ???
1636-   C8          INY
1637-   C1 D2       CMP   ($D2,X)
1639-   C1 C3       CMP   ($C3,X)
163B-   D4          ???
163C-   C5 D2       CMP   $D2
163E-   20 C1 D4    JSR   $D4C1
1641-   20 D4 C8    JSR   $C8D4
1644-   C5 20       CMP   $20
1646-   C7          ???
1647-   C9 D6       CMP   #$D6
1649-   C5 CE       CMP   $CE
164B-   20 D8 AC    JSR   $ACD8
164E-   D9 A2 AC    CMP   $ACA2,Y
1651-   B8          CLV
1652-   C4 8D       CPY   $8D
1654-   A0 D0       LDY   #$D0
1656-   D2 CE       CMP   ($CE)
1658-   A0 A2       LDY   #$A2
165A-   CC CF C3    CPY   $C3CF
165D-   C1 D4       CMP   ($D4,X)
165F-   C9 CF       CMP   #$CF
1661-   CE AE 20    DEC   $20AE
1664-   D4          ???
1665-   C8          INY
1666-   C5 20       CMP   $20
1668-   C3          ???
1669-   C8          INY
166A-   C1 D2       CMP   ($D2,X)
166C-   20 C1 20    JSR   $20C1
166F-   B5 AC       LDA   $AC,X
1671-   B5 A2       LDA   $A2,X
1673-   AC B8 C4    LDY   $C4B8
1676-   8D A0 D0    STA   $D0A0
1679-   D2 CE       CMP   ($CE)
167B-   A0 A2       LDY   #$A2
167D-   C9 D3       CMP   #$D3
167F-   BA          TSX
1680-   20 A2 8D    JSR   $8DA2
1683-   A0 CC       LDY   #$CC
1685-   C4 C1       CPY   $C1
1687-   A0 A4       LDY   #$A4
1689-   B3          ???
168A-   B0 B0       BCS   $163C
168C-   8D A0 CA    STA   $CAA0
168F-   D3          ???
1690-   D2 A0       CMP   ($A0)
1692-   C3          ???
1693-   CF          ???
1694-   D5 D4       CMP   $D4,X
1696-   B1 8D       LDA   ($8D),Y
1698-   A0 D0       LDY   #$D0
169A-   D2 CE       CMP   ($CE)
169C-   A0 A2       LDY   #$A2
169E-   20 A2 AC    JSR   $ACA2
16A1-   B8          CLV
16A2-   C4 B8       CPY   $B8
16A4-   C4 8D       CPY   $8D
16A6-   A0 D7       LDY   #$D7
16A8-   C1 C9       CMP   ($C9,X)
16AA-   D4          ???
16AB-   8D AA 8D    STA   $8DAA
16AE-   AA          TAX
16AF-   AA          TAX
16B0-   20 CD C1    JSR   $C1CD
16B3-   C3          ???
16B4-   D2 CF       CMP   ($CF)
16B6-   BA          TSX
16B7-   20 D0 C4    JSR   $C4D0
16BA-   CC 20 D0    CPY   $D020
16BD-   C1 C4       CMP   ($C4,X)
16BF-   C4 CC       CPY   $CC
16C1-   C5 DF       CMP   $DF
16C3-   CE D5 CD    DEC   $CDD5
16C6-   C2          ???
16C7-   C5 D2       CMP   $D2
16C9-   8D AA 8D    STA   $8DAA
16CC-   A0 CA       LDY   #$CA
16CE-   D3          ???
16CF-   D2 A0       CMP   ($A0)
16D1-   C8          INY
16D2-   CF          ???
16D3-   CD C5 8D    CMP   $8DC5
16D6-   A0 D0       LDY   #$D0
16D8-   D2 CE       CMP   ($CE)
16DA-   A0 A2       LDY   #$A2
16DC-   D4          ???
16DD-   C8          INY
16DE-   C5 20       CMP   $20
16E0-   D0 C4       BNE   $16A6
16E2-   CC 20 CD    CPY   $CD20
16E5-   C1 C3       CMP   ($C3,X)
16E7-   D2 CF       CMP   ($CF)
16E9-   20 D2 C5    JSR   $C5D2
16EC-   C1 C4       CMP   ($C4,X)
16EE-   D3          ???
16EF-   20 D4 C8    JSR   $C8D4
16F2-   C5 A2       CMP   $A2
16F4-   AC B8 C4    LDY   $C4B8
16F7-   8D A0 D0    STA   $D0A0
16FA-   D2 CE       CMP   ($CE)
16FC-   A0 A2       LDY   #$A2
16FE-   C3          ???
16FF-   D5 D2       CMP   $D2,X
1701-   D2 C5       CMP   ($C5)
1703-   CE D4 20    DEC   $20D4
1706-   D3          ???
1707-   D4          ???
1708-   C1 D4       CMP   ($D4,X)
170A-   C5 20       CMP   $20
170C-   CF          ???
170D-   C6 20       DEC   $20
170F-   D4          ???
1710-   C8          INY
1711-   C5 20       CMP   $20
1713-   D0 C1       BNE   $16D6
1715-   C4 C4       CPY   $C4
1717-   CC C5 A2    CPY   $A2C5
171A-   AC B8 C4    LDY   $C4B8
171D-   8D A0 D0    STA   $D0A0
1720-   D2 CE       CMP   ($CE)
1722-   A0 A2       LDY   #$A2
1724-   C1 CE       CMP   ($CE,X)
1726-   C4 20       CPY   $20
1728-   D2 C5       CMP   ($C5)
172A-   D4          ???
172B-   D5 D2       CMP   $D2,X
172D-   CE D3 20    DEC   $20D3
1730-   D4          ???
1731-   C8          INY
1732-   C1 D4       CMP   ($D4,X)
1734-   20 D3 D4    JSR   $D4D3
1737-   C1 D4       CMP   ($D4,X)
1739-   C5 A2       CMP   $A2
173B-   AC B8 C4    LDY   $C4B8
173E-   8D A0 D0    STA   $D0A0
1741-   D2 CE       CMP   ($CE)
1743-   A0 A2       LDY   #$A2
1745-   C9 CE       CMP   #$CE
1747-   20 AE D9    JSR   $D9AE
174A-   AE A2 AC    LDX   $ACA2
174D-   B8          CLV
174E-   C4 B8       CPY   $B8
1750-   C4 8D       CPY   $8D
1752-   A0 D0       LDY   #$D0
1754-   D2 CE       CMP   ($CE)
1756-   A0 A2       LDY   #$A2
1758-   CD CF D6    CMP   $D6CF
175B-   C5 20       CMP   $20
175D-   D4          ???
175E-   C8          INY
175F-   C5 20       CMP   $20
1761-   D0 C1       BNE   $1724
1763-   C4 C4       CPY   $C4
1765-   CC C5 20    CPY   $20C5
1768-   C1 20       CMP   ($20,X)
176A-   C2          ???
176B-   C9 D4       CMP   #$D4
176D-   20 D4 CF    JSR   $CFD4
1770-   20 D3 C5    JSR   $C5D3
1773-   C5 A2       CMP   $A2
1775-   AC B8 C4    LDY   $C4B8
1778-   8D A0 D0    STA   $D0A0
177B-   D2 CE       CMP   ($CE)
177D-   A0 A2       LDY   #$A2
177F-   D4          ???
1780-   C8          INY
1781-   C5 20       CMP   $20
1783-   D6 C1       DEC   $C1,X
1785-   CC D5 C5    CPY   $C5D5
1788-   20 CF C6    JSR   $C6CF
178B-   20 D9 20    JSR   $20D9
178E-   C3          ???
178F-   C8          INY
1790-   C1 CE       CMP   ($CE,X)
1792-   C7          ???
1793-   C5 AE       CMP   $AE
1795-   A2 AC       LDX   #$AC
1797-   B8          CLV
1798-   C4 B8       CPY   $B8
179A-   C4 8D       CPY   $8D
179C-   A0 D0       LDY   #$D0
179E-   D2 CE       CMP   ($CE)
17A0-   A0 A2       LDY   #$A2
17A2-   A8          TAY
17A3-   D0 D2       BNE   $1777
17A5-   C5 D3       CMP   $D3
17A7-   D3          ???
17A8-   20 C1 20    JSR   $20C1
17AB-   CB          ???
17AC-   C5 D9       CMP   $D9
17AE-   20 C6 C9    JSR   $C9C6
17B1-   D2 D3       CMP   ($D3)
17B3-   D4          ???
17B4-   AC 20 D4    LDY   $D420
17B7-   CF          ???
17B8-   20 D3 D4    JSR   $D4D3
17BB-   C1 D2       CMP   ($D2,X)
17BD-   D4          ???
17BE-   A9 A2       LDA   #$A2
17C0-   8D A0 D7    STA   $D7A0
17C3-   C1 C9       CMP   ($C9,X)
17C5-   D4          ???
17C6-   8D A0 CC    STA   $CCA0
17C9-   C4 C1       CPY   $C1
17CB-   A0 A3       LDY   #$A3
17CD-   B0 8D       BCS   $175C
17CF-   A0 D3       LDY   #$D3
17D1-   D4          ???
17D2-   C1 A0       CMP   ($A0,X)
17D4-   A4 B3       LDY   $B3
17D6-   B0 B0       BCS   $1788
17D8-   8D A0 CC    STA   $CCA0
17DB-   C4 C1       CPY   $C1
17DD-   A0 A3       LDY   #$A3
17DF-   B0 8D       BCS   $176E
17E1-   A0 D3       LDY   #$D3
17E3-   D4          ???
17E4-   C1 A0       CMP   ($A0,X)
17E6-   A4 B3       LDY   $B3
17E8-   B1 B0       LDA   ($B0),Y
17EA-   8D A0 CA    STA   $CAA0
17ED-   D3          ???
17EE-   D2 A0       CMP   ($A0)
17F0-   C8          INY
17F1-   CF          ???
17F2-   CD C5 8D    CMP   $8DC5
17F5-   D0 CC       BNE   $17C3
17F7-   D0 8D       BNE   $1786
17F9-   A0 D0       LDY   #$D0
17FB-   C4 CC       CPY   $CC
17FD-   A0 A3       LDY   #$A3
17FF-   B0 8D       BCS   $178E
1801-   A0 D4       LDY   #$D4
1803-   D9 C1 8D    CMP   $8DC1,Y
1806-   A0 CA       LDY   #$CA
1808-   D3          ???
1809-   D2 A0       CMP   ($A0)
180B-   C3          ???
180C-   CF          ???
180D-   D5 D4       CMP   $D4,X
180F-   B1 8D       LDA   ($8D),Y
1811-   A0 C9       LDY   #$C9
1813-   CE C3 A0    DEC   $A0C3
1816-   A4 B3       LDY   $B3
1818-   B0 B0       BCS   $17CA
181A-   8D A0 CC    STA   $CCA0
181D-   C4 C1       CPY   $C1
181F-   A0 A4       LDY   #$A4
1821-   B3          ???
1822-   B0 B0       BCS   $17D4
1824-   8D A0 C3    STA   $C3A0
1827-   CD D0 A0    CMP   $A0D0
182A-   A3          ???
182B-   B2 B5       LDA   ($B5)
182D-   B5 8D       LDA   $8D,X
182F-   A0 C2       LDY   #$C2
1831-   CE C5 A0    DEC   $A0C5
1834-   D0 CC       BNE   $1802
1836-   D0 8D       BNE   $17C5
1838-   A0 C9       LDY   #$C9
183A-   CE C3 A0    DEC   $A0C3
183D-   A4 B3       LDY   $B3
183F-   B1 B0       LDA   ($B0),Y
1841-   8D A0 CC    STA   $CCA0
1844-   C4 C1       CPY   $C1
1846-   A0 A4       LDY   #$A4
1848-   B3          ???
1849-   B1 B0       LDA   ($B0),Y
184B-   8D A0 C3    STA   $C3A0
184E-   CD D0 A0    CMP   $A0D0
1851-   A3          ???
1852-   B4 8D       LDY   $8D,X
1854-   A0 C2       LDY   #$C2
1856-   C5 D1       CMP   $D1
1858-   A0 D8       LDY   #$D8
185A-   D0 CC       BNE   $1828
185C-   D0 8D       BNE   $17EB
185E-   A0 C2       LDY   #$C2
1860-   CE C5 A0    DEC   $A0C5
1863-   D0 CC       BNE   $1831
1865-   D0 8D       BNE   $17F4
1867-   D8          CLD
1868-   D0 CC       BNE   $1836
186A-   D0 8D       BNE   $17F9
186C-   AA          TAX
186D-   8D AA AA    STA   $AAAA
1870-   20 CD C1    JSR   $C1CD
1873-   C3          ???
1874-   D2 CF       CMP   ($CF)
1876-   BA          TSX
1877-   20 D0 C2    JSR   $C2D0
187A-   D8          CLD
187B-   20 D0 C1    JSR   $C1D0
187E-   C4 C4       CPY   $C4
1880-   CC C5 DF    CPY   $DFC5
1883-   C2          ???
1884-   D5 D4       CMP   $D4,X
1886-   D4          ???
1887-   CF          ???
1888-   CE DF CE    DEC   $CEDF
188B-   D5 CD       CMP   $CD,X
188D-   C2          ???
188E-   C5 D2       CMP   $D2
1890-   8D AA 8D    STA   $8DAA
1893-   A0 CA       LDY   #$CA
1895-   D3          ???
1896-   D2 A0       CMP   ($A0)
1898-   C8          INY
1899-   CF          ???
189A-   CD C5 8D    CMP   $8DC5
189D-   A0 D0       LDY   #$D0
189F-   D2 CE       CMP   ($CE)
18A1-   A0 A2       LDY   #$A2
18A3-   D4          ???
18A4-   C8          INY
18A5-   C5 20       CMP   $20
18A7-   D0 C2       BNE   $186B
18A9-   D8          CLD
18AA-   20 CD C1    JSR   $C1CD
18AD-   C3          ???
18AE-   D2 CF       CMP   ($CF)
18B0-   20 D2 C5    JSR   $C5D2
18B3-   D4          ???
18B4-   D5 D2       CMP   $D2,X
18B6-   CE D3 20    DEC   $20D3
18B9-   B1 20       LDA   ($20),Y
18BB-   C9 CE       CMP   #$CE
18BD-   D4          ???
18BE-   CF          ???
18BF-   A2 AC       LDX   #$AC
18C1-   B8          CLV
18C2-   C4 8D       CPY   $8D
18C4-   A0 D0       LDY   #$D0
18C6-   D2 CE       CMP   ($CE)
18C8-   A0 A2       LDY   #$A2
18CA-   D4          ???
18CB-   C8          INY
18CC-   C5 20       CMP   $20
18CE-   C1 C3       CMP   ($C3,X)
18D0-   C3          ???
18D1-   D5 CD       CMP   $CD,X
18D3-   D5 CC       CMP   $CC,X
18D5-   C1 D4       CMP   ($D4,X)
18D7-   CF          ???
18D8-   D2 20       CMP   ($20)
18DA-   C9 C6       CMP   #$C6
18DC-   20 D4 C8    JSR   $C8D4
18DF-   C5 20       CMP   $20
18E1-   D0 D2       BNE   $18B5
18E3-   CF          ???
18E4-   CD D0 D4    CMP   $D4D0
18E7-   C5 C4       CMP   $C4
18E9-   A2 AC       LDX   #$AC
18EB-   B8          CLV
18EC-   C4 8D       CPY   $8D
18EE-   A0 D0       LDY   #$D0
18F0-   D2 CE       CMP   ($CE)
18F2-   A0 A2       LDY   #$A2
18F4-   D0 C1       BNE   $18B7
18F6-   C4 C4       CPY   $C4
18F8-   CC C5 20    CPY   $20C5
18FB-   C2          ???
18FC-   D5 D4       CMP   $D4,X
18FE-   D4          ???
18FF-   CF          ???
1900-   CE 20 C9    DEC   $C920
1903-   D3          ???
1904-   20 D0 D2    JSR   $D2D0
1907-   C5 D3       CMP   $D3
1909-   D3          ???
190A-   C5 C4       CMP   $C4
190C-   AE 20 D4    LDX   $D420
190F-   C8          INY
1910-   C9 D3       CMP   #$D3
1912-   A2 AC       LDX   #$AC
1914-   B8          CLV
1915-   C4 8D       CPY   $8D
1917-   A0 D0       LDY   #$D0
1919-   D2 CE       CMP   ($CE)
191B-   A0 A2       LDY   #$A2
191D-   C9 D3       CMP   #$D3
191F-   20 D5 D3    JSR   $D3D5
1922-   D5 C1       CMP   $C1,X
1924-   CC CC D9    CPY   $D9CC
1927-   20 D0 C2    JSR   $C2D0
192A-   B0 20       BCS   $194C
192C-   CF          ???
192D-   D2 20       CMP   ($20)
192F-   D0 C2       BNE   $18F3
1931-   B1 AE       LDA   ($AE),Y
1933-   20 D4 C8    JSR   $C8D4
1936-   C5 A2       CMP   $A2
1938-   AC B8 C4    LDY   $C4B8
193B-   8D A0 D0    STA   $D0A0
193E-   D2 CE       CMP   ($CE)
1940-   A0 A2       LDY   #$A2
1942-   C1 D0       CMP   ($D0,X)
1944-   D0 CC       BNE   $1912
1946-   C5 20       CMP   $20
1948-   CB          ???
1949-   C5 D9       CMP   $D9
194B-   D3          ???
194C-   20 C1 D2    JSR   $D2C1
194F-   C5 20       CMP   $20
1951-   C1 CC       CMP   ($CC,X)
1953-   D3          ???
1954-   CF          ???
1955-   20 CD C1    JSR   $C1CD
1958-   D0 D0       BNE   $192A
195A-   C5 C4       CMP   $C4
195C-   20 C8 C5    JSR   $C5C8
195F-   D2 C5       CMP   ($C5)
1961-   AE A2 AC    LDX   $ACA2
1964-   B8          CLV
1965-   C4 8D       CPY   $8D
1967-   A0 D0       LDY   #$D0
1969-   D2 CE       CMP   ($CE)
196B-   A0 A2       LDY   #$A2
196D-   D0 D2       BNE   $1941
196F-   C5 D3       CMP   $D3
1971-   D3          ???
1972-   20 D0 C1    JSR   $C1D0
1975-   C4 C4       CPY   $C4
1977-   CC C5 20    CPY   $20C5
197A-   C2          ???
197B-   D5 D4       CMP   $D4,X
197D-   D4          ???
197E-   CF          ???
197F-   CE 20 DA    DEC   $DA20
1982-   C5 D2       CMP   $D2
1984-   CF          ???
1985-   20 CF D2    JSR   $D2CF
1988-   20 CF D0    JSR   $D0CF
198B-   C5 CE       CMP   $CE
198D-   A2 AC       LDX   #$AC
198F-   B8          CLV
1990-   C4 8D       CPY   $8D
1992-   A0 D0       LDY   #$D0
1994-   D2 CE       CMP   ($CE)
1996-   A0 A2       LDY   #$A2
1998-   C1 D0       CMP   ($D0,X)
199A-   D0 CC       BNE   $1968
199C-   C5 20       CMP   $20
199E-   D4          ???
199F-   CF          ???
19A0-   20 C3 CF    JSR   $CFC3
19A3-   CE D4 C9    DEC   $C9D4
19A6-   CE D5 C5    DEC   $C5D5
19A9-   AE A2 8D    LDX   $8DA2
19AC-   A0 CC       LDY   #$CC
19AE-   C4 C1       CPY   $C1
19B0-   A0 A3       LDY   #$A3
19B2-   B0 8D       BCS   $1941
19B4-   D0 C2       BNE   $1978
19B6-   CC D0 8D    CPY   $8DD0
19B9-   A0 D0       LDY   #$D0
19BB-   C2          ???
19BC-   D8          CLD
19BD-   A0 A3       LDY   #$A3
19BF-   D0 C2       BNE   $1983
19C1-   B0 8D       BCS   $1950
19C3-   A0 C3       LDY   #$C3
19C5-   CD D0 A0    CMP   $A0D0
19C8-   A3          ???
19C9-   B1 8D       LDA   ($8D),Y
19CB-   A0 C2       LDY   #$C2
19CD-   CE C5 A0    DEC   $A0C5
19D0-   D0 C2       BNE   $1994
19D2-   CC D0 8D    CPY   $8DD0
19D5-   AA          TAX
19D6-   8D AA AA    STA   $AAAA
19D9-   20 CD C1    JSR   $C1CD
19DC-   C3          ???
19DD-   D2 CF       CMP   ($CF)
19DF-   BA          TSX
19E0-   20 D4 D6    JSR   $D6D4
19E3-   CC C9 CE    CPY   $CEC9
19E6-   20 D9 DF    JSR   $DFD9
19E9-   D3          ???
19EA-   D4          ???
19EB-   C1 D2       CMP   ($D2,X)
19ED-   D4          ???
19EE-   BB          ???
19EF-   D9 DF C5    CMP   $C5DF,Y
19F2-   CE C4 BB    DEC   $BBC4
19F5-   D8          CLD
19F6-   DF          ???
19F7-   D0 CF       BNE   $19C8
19F9-   D3          ???
19FA-   C9 D4       CMP   #$D4
19FC-   C9 CF       CMP   #$CF
19FE-   CE BB C6    DEC   $C6BB
1A01-   C9 CC       CMP   #$CC
1A03-   CC DF C3    CPY   $C3DF
1A06-   C8          INY
1A07-   C1 D2       CMP   ($D2,X)
1A09-   8D AA AA    STA   $AAAA
1A0C-   20 20 20    JSR   $2020
1A0F-   20 20 20    JSR   $2020
1A12-   20 20 D4    JSR   $D420
1A15-   C8          INY
1A16-   CC C9 CE    CPY   $CEC9
1A19-   20 D8 DF    JSR   $DFD8
1A1C-   D3          ???
1A1D-   D4          ???
1A1E-   C1 D2       CMP   ($D2,X)
1A20-   D4          ???
1A21-   BB          ???
1A22-   D8          CLD
1A23-   DF          ???
1A24-   C5 CE       CMP   $CE
1A26-   C4 BB       CPY   $BB
1A28-   D9 DF D0    CMP   $D0DF,Y
1A2B-   CF          ???
1A2C-   D3          ???
1A2D-   C9 D4       CMP   #$D4
1A2F-   C9 CF       CMP   #$CF
1A31-   CE BB C6    DEC   $C6BB
1A34-   C9 CC       CMP   #$CC
1A36-   CC DF C3    CPY   $C3DF
1A39-   C8          INY
1A3A-   C1 D2       CMP   ($D2,X)
1A3C-   8D AA 8D    STA   $8DAA
1A3F-   AA          TAX
1A40-   AA          TAX
1A41-   20 20 20    JSR   $2020
1A44-   20 20 20    JSR   $2020
1A47-   20 20 D4    JSR   $D420
1A4A-   C6 C9       DEC   $C9
1A4C-   CC CC 20    CPY   $20CC
1A4F-   D8          CLD
1A50-   DF          ???
1A51-   D3          ???
1A52-   D4          ???
1A53-   C1 D2       CMP   ($D2,X)
1A55-   D4          ???
1A56-   BB          ???
1A57-   D8          CLD
1A58-   DF          ???
1A59-   C5 CE       CMP   $CE
1A5B-   C4 BB       CPY   $BB
1A5D-   D9 DF D3    CMP   $D3DF,Y
1A60-   D4          ???
1A61-   C1 D2       CMP   ($D2,X)
1A63-   D4          ???
1A64-   BB          ???
1A65-   D9 DF C5    CMP   $C5DF,Y
1A68-   CE C4 CC    DEC   $CCC4
1A6B-   C6 C9       DEC   $C9
1A6D-   CC CC DF    CPY   $DFCC
1A70-   C3          ???
1A71-   C8          INY
1A72-   C1 D2       CMP   ($D2,X)
1A74-   8D AA 8D    STA   $8DAA
1A77-   A0 CA       LDY   #$CA
1A79-   D3          ???
1A7A-   D2 A0       CMP   ($A0)
1A7C-   C8          INY
1A7D-   CF          ???
1A7E-   CD C5 8D    CMP   $8DC5
1A81-   A0 D0       LDY   #$D0
1A83-   D2 CE       CMP   ($CE)
1A85-   A0 A2       LDY   #$A2
1A87-   D4          ???
1A88-   D6 CC       DEC   $CC,X
1A8A-   C9 CE       CMP   #$CE
1A8C-   20 C3 D2    JSR   $D2C3
1A8F-   C5 C1       CMP   $C1
1A91-   D4          ???
1A92-   C5 D3       CMP   $D3
1A94-   20 C1 20    JSR   $20C1
1A97-   D6 C5       DEC   $C5,X
1A99-   D2 D4       CMP   ($D4)
1A9B-   C9 C3       CMP   #$C3
1A9D-   C1 CC       CMP   ($CC,X)
1A9F-   20 CC C9    JSR   $C9CC
1AA2-   CE C5 A2    DEC   $A2C5
1AA5-   AC B8 C4    LDY   $C4B8
1AA8-   8D A0 D0    STA   $D0A0
1AAB-   D2 CE       CMP   ($CE)
1AAD-   A0 A2       LDY   #$A2
1AAF-   CF          ???
1AB0-   C6 20       DEC   $20
1AB2-   D4          ???
1AB3-   C5 D8       CMP   $D8
1AB5-   D4          ???
1AB6-   AC 20 D7    LDY   $D720
1AB9-   C8          INY
1ABA-   C9 CC       CMP   #$CC
1ABC-   C5 20       CMP   $20
1ABE-   D4          ???
1ABF-   C8          INY
1AC0-   CC C9 CE    CPY   $CEC9
1AC3-   20 C3 D2    JSR   $D2C3
1AC6-   C5 C1       CMP   $C1
1AC8-   D4          ???
1AC9-   C5 D3       CMP   $D3
1ACB-   A2 AC       LDX   #$AC
1ACD-   B8          CLV
1ACE-   C4 8D       CPY   $8D
1AD0-   A0 D0       LDY   #$D0
1AD2-   D2 CE       CMP   ($CE)
1AD4-   A0 A2       LDY   #$A2
1AD6-   C1 20       CMP   ($20,X)
1AD8-   C8          INY
1AD9-   CF          ???
1ADA-   D2 C9       CMP   ($C9)
1ADC-   DA          PHX
1ADD-   CF          ???
1ADE-   CE D4 C1    DEC   $C1D4
1AE1-   CC 20 CC    CPY   $CC20
1AE4-   C9 CE       CMP   #$CE
1AE6-   C5 20       CMP   $20
1AE8-   CF          ???
1AE9-   C6 20       DEC   $20
1AEB-   D4          ???
1AEC-   C5 D8       CMP   $D8
1AEE-   D4          ???
1AEF-   AE 20 D9    LDX   $D920
1AF2-   CF          ???
1AF3-   D5 A2       CMP   $A2,X
1AF5-   AC B8 C4    LDY   $C4B8
1AF8-   8D A0 D0    STA   $D0A0
1AFB-   D2 CE       CMP   ($CE)
1AFD-   A0 A2       LDY   #$A2
1AFF-   D3          ???
1B00-   D0 C5       BNE   $1AC7
1B02-   C3          ???
1B03-   C9 C6       CMP   #$C6
1B05-   D9 20 D4    CMP   $D420,Y
1B08-   C8          INY
1B09-   C5 20       CMP   $20
1B0B-   C3          ???
1B0C-   CF          ???
1B0D-   CF          ???
1B0E-   D2 C4       CMP   ($C4)
1B10-   D3          ???
1B11-   20 AF 20    JSR   $20AF
1B14-   C6 C9       DEC   $C9
1B16-   CC CC 20    CPY   $20CC
1B19-   C3          ???
1B1A-   C8          INY
1B1B-   C1 D2       CMP   ($D2,X)
1B1D-   AE A2 AC    LDX   $ACA2
1B20-   B8          CLV
1B21-   C4 B8       CPY   $B8
1B23-   C4 8D       CPY   $8D
1B25-   A0 D4       LDY   #$D4
1B27-   D6 CC       DEC   $CC,X
1B29-   C9 CE       CMP   #$CE
1B2B-   A0 A3       LDY   #$A3
1B2D-   B0 B8       BCS   $1AE7
1B2F-   BB          ???
1B30-   A3          ???
1B31-   B1 B8       LDA   ($B8),Y
1B33-   BB          ???
1B34-   A3          ???
1B35-   B1 B0       LDA   ($B0),Y
1B37-   BB          ???
1B38-   A3          ???
1B39-   A4 C1       LDY   $C1
1B3B-   C1 8D       CMP   ($8D,X)
1B3D-   A0 D7       LDY   #$D7
1B3F-   C1 C9       CMP   ($C9,X)
1B41-   D4          ???
1B42-   8D A0 D4    STA   $D4A0
1B45-   C8          INY
1B46-   CC C9 CE    CPY   $CEC9
1B49-   A0 A3       LDY   #$A3
1B4B-   B1 B0       LDA   ($B0),Y
1B4D-   BB          ???
1B4E-   A3          ???
1B4F-   B3          ???
1B50-   B0 BB       BCS   $1B0D
1B52-   A3          ???
1B53-   B0 B8       BCS   $1B0D
1B55-   BB          ???
1B56-   A3          ???
1B57-   A4 C1       LDY   $C1
1B59-   C1 8D       CMP   ($8D,X)
1B5B-   A0 D7       LDY   #$D7
1B5D-   C1 C9       CMP   ($C9,X)
1B5F-   D4          ???
1B60-   8D A0 D4    STA   $D4A0
1B63-   D6 CC       DEC   $CC,X
1B65-   C9 CE       CMP   #$CE
1B67-   A0 A3       LDY   #$A3
1B69-   B8          CLV
1B6A-   BB          ???
1B6B-   A3          ???
1B6C-   B1 B8       LDA   ($B8),Y
1B6E-   BB          ???
1B6F-   A3          ???
1B70-   B3          ???
1B71-   B0 BB       BCS   $1B2E
1B73-   A3          ???
1B74-   A4 C1       LDY   $C1
1B76-   C1 8D       CMP   ($8D,X)
1B78-   A0 D4       LDY   #$D4
1B7A-   C8          INY
1B7B-   CC C9 CE    CPY   $CEC9
1B7E-   A0 A3       LDY   #$A3
1B80-   B1 B0       LDA   ($B0),Y
1B82-   BB          ???
1B83-   A3          ???
1B84-   B3          ???
1B85-   B1 BB       LDA   ($BB),Y
1B87-   A3          ???
1B88-   B1 B7       LDA   ($B7),Y
1B8A-   BB          ???
1B8B-   A3          ???
1B8C-   A4 C1       LDY   $C1
1B8E-   C1 8D       CMP   ($8D,X)
1B90-   A0 D7       LDY   #$D7
1B92-   C1 C9       CMP   ($C9,X)
1B94-   D4          ???
1B95-   8D A0 D4    STA   $D4A0
1B98-   C8          INY
1B99-   CC C9 CE    CPY   $CEC9
1B9C-   A0 A3       LDY   #$A3
1B9E-   B0 BB       BCS   $1B5B
1BA0-   A3          ???
1BA1-   B3          ???
1BA2-   B9 BB A3    LDA   $A3BB,Y
1BA5-   B0 BB       BCS   $1B62
1BA7-   A3          ???
1BA8-   A4 C1       LDY   $C1
1BAA-   C1 8D       CMP   ($8D,X)
1BAC-   A0 D4       LDY   #$D4
1BAE-   D6 CC       DEC   $CC,X
1BB0-   C9 CE       CMP   #$CE
1BB2-   A0 A3       LDY   #$A3
1BB4-   B0 BB       BCS   $1B71
1BB6-   A3          ???
1BB7-   B2 B3       LDA   ($B3)
1BB9-   BB          ???
1BBA-   A3          ???
1BBB-   B0 BB       BCS   $1B78
1BBD-   A3          ???
1BBE-   A4 C1       LDY   $C1
1BC0-   C1 8D       CMP   ($8D,X)
1BC2-   A0 D4       LDY   #$D4
1BC4-   C8          INY
1BC5-   CC C9 CE    CPY   $CEC9
1BC8-   A0 A3       LDY   #$A3
1BCA-   B0 BB       BCS   $1B87
1BCC-   A3          ???
1BCD-   B3          ???
1BCE-   B9 BB A3    LDA   $A3BB,Y
1BD1-   B2 B3       LDA   ($B3)
1BD3-   BB          ???
1BD4-   A3          ???
1BD5-   A4 C1       LDY   $C1
1BD7-   C1 8D       CMP   ($8D,X)
1BD9-   A0 D4       LDY   #$D4
1BDB-   D6 CC       DEC   $CC,X
1BDD-   C9 CE       CMP   #$CE
1BDF-   A0 A3       LDY   #$A3
1BE1-   B0 B0       BCS   $1B93
1BE3-   BB          ???
1BE4-   A3          ???
1BE5-   B2 B3       LDA   ($B3)
1BE7-   BB          ???
1BE8-   A3          ???
1BE9-   B3          ???
1BEA-   B9 BB A3    LDA   $A3BB,Y
1BED-   A4 C1       LDY   $C1
1BEF-   C1 8D       CMP   ($8D,X)
1BF1-   A0 D7       LDY   #$D7
1BF3-   C1 C9       CMP   ($C9,X)
1BF5-   D4          ???
1BF6-   8D A0 D4    STA   $D4A0
1BF9-   C6 C9       DEC   $C9
1BFB-   CC CC A0    CPY   $A0CC
1BFE-   A3          ???
1BFF-   B0 BB       BCS   $1BBC
1C01-   A3          ???
1C02-   B0 BB       BCS   $1BBF
1C04-   A3          ???
1C05-   B3          ???
1C06-   B9 BB A3    LDA   $A3BB,Y
1C09-   B2 B3       LDA   ($B3)
1C0B-   BB          ???
1C0C-   A3          ???
1C0D-   A4 C1       LDY   $C1
1C0F-   C1 8D       CMP   ($8D,X)
1C11-   A0 D7       LDY   #$D7
1C13-   C1 C9       CMP   ($C9,X)
1C15-   D4          ???
1C16-   8D 20 A0    STA   $A020
1C19-   D4          ???
1C1A-   C6 C9       DEC   $C9
1C1C-   CC CC 20    CPY   $20CC
1C1F-   A3          ???
1C20-   B1 B0       LDA   ($B0),Y
1C22-   BB          ???
1C23-   A3          ???
1C24-   B5 BB       LDA   $BB,X
1C26-   A3          ???
1C27-   B3          ???
1C28-   B0 BB       BCS   $1BE5
1C2A-   A3          ???
1C2B-   B1 B7       LDA   ($B7),Y
1C2D-   BB          ???
1C2E-   A3          ???
1C2F-   A4 C1       LDY   $C1
1C31-   B0 8D       BCS   $1BC0
1C33-   A0 D7       LDY   #$D7
1C35-   C1 C9       CMP   ($C9,X)
1C37-   D4          ???
1C38-   8D A0 D3    STA   $D3A0
1C3B-   C3          ???
1C3C-   D0 CF       BNE   $1C0D
1C3E-   D3          ???
1C3F-   A0 A3       LDY   #$A3
1C41-   B1 B2       LDA   ($B2),Y
1C43-   BB          ???
1C44-   A3          ???
1C45-   B7          ???
1C46-   8D A0 D0    STA   $D0A0
1C49-   D2 CE       CMP   ($CE)
1C4B-   A0 A2       LDY   #$A2
1C4D-   C1 CE       CMP   ($CE,X)
1C4F-   C4 20       CPY   $20
1C51-   D4          ???
1C52-   C6 C9       DEC   $C9
1C54-   CC CC 20    CPY   $20CC
1C57-   C6 C9       DEC   $C9
1C59-   CC CC D3    CPY   $D3CC
1C5C-   20 C1 A2    JSR   $A2C1
1C5F-   AC B8 C4    LDY   $C4B8
1C62-   8D A0 D3    STA   $D3A0
1C65-   C3          ???
1C66-   D0 CF       BNE   $1C37
1C68-   D3          ???
1C69-   A0 A3       LDY   #$A3
1C6B-   B1 B2       LDA   ($B2),Y
1C6D-   BB          ???
1C6E-   A3          ???
1C6F-   B9 8D A0    LDA   $A08D,Y
1C72-   D0 D2       BNE   $1C46
1C74-   CE A0 A2    DEC   $A2A0
1C77-   C7          ???
1C78-   C9 D6       CMP   #$D6
1C7A-   C5 CE       CMP   $CE
1C7C-   20 C1 D2    JSR   $D2C1
1C7F-   C5 C1       CMP   $C1
1C81-   20 D7 C9    JSR   $C9D7
1C84-   D4          ???
1C85-   C8          INY
1C86-   A2 8D       LDX   #$8D
1C88-   A0 D3       LDY   #$D3
1C8A-   C3          ???
1C8B-   D0 CF       BNE   $1C5C
1C8D-   D3          ???
1C8E-   A0 A3       LDY   #$A3
1C90-   B1 B2       LDA   ($B2),Y
1C92-   BB          ???
1C93-   A3          ???
1C94-   B1 B1       LDA   ($B1),Y
1C96-   8D A0 D0    STA   $D0A0
1C99-   D2 CE       CMP   ($CE)
1C9B-   A0 A2       LDY   #$A2
1C9D-   C1 20       CMP   ($20,X)
1C9F-   C6 C9       DEC   $C9
1CA1-   CC CC 20    CPY   $20CC
1CA4-   C3          ???
1CA5-   C8          INY
1CA6-   C1 D2       CMP   ($D2,X)
1CA8-   A2 8D       LDX   #$8D
1CAA-   A0 D7       LDY   #$D7
1CAC-   C1 C9       CMP   ($C9,X)
1CAE-   D4          ???
1CAF-   8D A0 CA    STA   $CAA0
1CB2-   D3          ???
1CB3-   D2 A0       CMP   ($A0)
1CB5-   C8          INY
1CB6-   CF          ???
1CB7-   CD C5 8D    CMP   $8DC5
1CBA-   A0 D0       LDY   #$D0
1CBC-   D2 CE       CMP   ($CE)
1CBE-   A0 A2       LDY   #$A2
1CC0-   CC C1 D3    CPY   $D3C1
1CC3-   D4          ???
1CC4-   CC D9 AC    CPY   $ACD9
1CC7-   20 D4 C8    JSR   $C8D4
1CCA-   C5 20       CMP   $20
1CCC-   D4          ???
1CCD-   D0 D5       BNE   $1CA4
1CCF-   D4          ???
1CD0-   20 CD C1    JSR   $C1CD
1CD3-   C3          ???
1CD4-   D2 CF       CMP   ($CF)
1CD6-   20 D3 C9    JSR   $C9D3
1CD9-   CD D0 CC    CMP   $CCD0
1CDC-   D9 A2 AC    CMP   $ACA2,Y
1CDF-   B8          CLV
1CE0-   C4 8D       CPY   $8D
1CE2-   A0 D0       LDY   #$D0
1CE4-   D2 CE       CMP   ($CE)
1CE6-   A0 A2       LDY   #$A2
1CE8-   D0 CC       BNE   $1CB6
1CEA-   CF          ???
1CEB-   D4          ???
1CEC-   D3          ???
1CED-   20 C1 20    JSR   $20C1
1CF0-   C7          ???
1CF1-   C9 D6       CMP   #$D6
1CF3-   C5 CE       CMP   $CE
1CF5-   20 C3 C8    JSR   $C8C3
1CF8-   C1 D2       CMP   ($D2,X)
1CFA-   C1 C3       CMP   ($C3,X)
1CFC-   D4          ???
1CFD-   C5 D2       CMP   $D2
1CFF-   20 D4 CF    JSR   $CFD4
1D02-   20 D4 C8    JSR   $C8D4
1D05-   C5 A2       CMP   $A2
1D07-   AC B8 C4    LDY   $C4B8
1D0A-   8D A0 D0    STA   $D0A0
1D0D-   D2 CE       CMP   ($CE)
1D0F-   A0 A2       LDY   #$A2
1D11-   D3          ???
1D12-   C3          ???
1D13-   D2 C5       CMP   ($C5)
1D15-   C5 CE       CMP   $CE
1D17-   20 D6 C9    JSR   $C9D6
1D1A-   C1 20       CMP   ($20,X)
1D1C-   C4 C9       CPY   $C9
1D1E-   D2 C5       CMP   ($C5)
1D20-   C3          ???
1D21-   D4          ???
1D22-   20 CD C5    JSR   $C5CD
1D25-   CD CF D2    CMP   $D2CF
1D28-   D9 20 C1    CMP   $C120,Y
1D2B-   C3          ???
1D2C-   C3          ???
1D2D-   C5 D3       CMP   $D3
1D2F-   D3          ???
1D30-   AE A2 8D    LDX   $8DA2
1D33-   A0 D0       LDY   #$D0
1D35-   D2 CE       CMP   ($CE)
1D37-   A0 A2       LDY   #$A2
1D39-   20 A2 AC    JSR   $ACA2
1D3C-   B8          CLV
1D3D-   C4 B8       CPY   $B8
1D3F-   C4 8D       CPY   $8D
1D41-   A0 D7       LDY   #$D7
1D43-   C1 C9       CMP   ($C9,X)
1D45-   D4          ???
1D46-   8D A0 D4    STA   $D4A0
1D49-   D0 D5       BNE   $1D20
1D4B-   D4          ???
1D4C-   A0 A3       LDY   #$A3
1D4E-   B1 B0       LDA   ($B0),Y
1D50-   BB          ???
1D51-   A3          ???
1D52-   B1 B0       LDA   ($B0),Y
1D54-   BB          ???
1D55-   A3          ???
1D56-   A4 C1       LDY   $C1
1D58-   C1 8D       CMP   ($8D,X)
1D5A-   A0 D4       LDY   #$D4
1D5C-   D0 D5       BNE   $1D33
1D5E-   D4          ???
1D5F-   A0 A3       LDY   #$A3
1D61-   B1 B1       LDA   ($B1),Y
1D63-   BB          ???
1D64-   A3          ???
1D65-   B1 B1       LDA   ($B1),Y
1D67-   BB          ???
1D68-   A3          ???
1D69-   A4 C1       LDY   $C1
1D6B-   C1 8D       CMP   ($8D,X)
1D6D-   A0 D4       LDY   #$D4
1D6F-   D0 D5       BNE   $1D46
1D71-   D4          ???
1D72-   A0 A3       LDY   #$A3
1D74-   B1 B2       LDA   ($B2),Y
1D76-   BB          ???
1D77-   A3          ???
1D78-   B1 B2       LDA   ($B2),Y
1D7A-   BB          ???
1D7B-   A3          ???
1D7C-   A4 C1       LDY   $C1
1D7E-   C1 8D       CMP   ($8D,X)
1D80-   A0 D4       LDY   #$D4
1D82-   D0 D5       BNE   $1D59
1D84-   D4          ???
1D85-   A0 A3       LDY   #$A3
1D87-   B1 B3       LDA   ($B3),Y
1D89-   BB          ???
1D8A-   A3          ???
1D8B-   B1 B3       LDA   ($B3),Y
1D8D-   BB          ???
1D8E-   A3          ???
1D8F-   A4 C1       LDY   $C1
1D91-   C1 8D       CMP   ($8D,X)
1D93-   A0 D4       LDY   #$D4
1D95-   D0 D5       BNE   $1D6C
1D97-   D4          ???
1D98-   A0 A3       LDY   #$A3
1D9A-   B1 B4       LDA   ($B4),Y
1D9C-   BB          ???
1D9D-   A3          ???
1D9E-   B1 B4       LDA   ($B4),Y
1DA0-   BB          ???
1DA1-   A3          ???
1DA2-   A4 C1       LDY   $C1
1DA4-   C1 8D       CMP   ($8D,X)
1DA6-   A0 DF       LDY   #$DF
1DA8-   D7          ???
1DA9-   C1 C9       CMP   ($C9,X)
1DAB-   D4          ???
1DAC-   8D A0 CA    STA   $CAA0
1DAF-   D3          ???
1DB0-   D2 A0       CMP   ($A0)
1DB2-   C8          INY
1DB3-   CF          ???
1DB4-   CD C5 8D    CMP   $8DC5
1DB7-   A0 D0       LDY   #$D0
1DB9-   D2 CE       CMP   ($CE)
1DBB-   A0 A2       LDY   #$A2
1DBD-   C6 C9       DEC   $C9
1DBF-   CE AE A2    DEC   $A2AE
1DC2-   AC B8 C4    LDY   $C4B8
1DC5-   B8          CLV
1DC6-   C4 B8       CPY   $B8
1DC8-   C4 8D       CPY   $8D
1DCA-   20 A0 D4    JSR   $D4A0
1DCD-   D0 D5       BNE   $1DA4
1DCF-   D4          ???
1DD0-   A0 A3       LDY   #$A3
1DD2-   B3          ???
1DD3-   B9 BB A3    LDA   $A3BB,Y
1DD6-   B2 B3       LDA   ($B3)
1DD8-   BB          ???
1DD9-   A3          ???
1DDA-   A4 C1       LDY   $C1
1DDC-   C1 8D       CMP   ($8D,X)
1DDE-   AA          TAX
1DDF-   8D A0 CA    STA   $CAA0
1DE2-   CD D0 A0    CMP   $A0D0
1DE5-   D2 C5       CMP   ($C5)
1DE7-   C5 CE       CMP   $CE
1DE9-   D4          ???
1DEA-   D2 D9       CMP   ($D9)
1DEC-   8D AA 8D    STA   $8DAA
1DEF-   AA          TAX
1DF0-   E0 E0       CPX   #$E0
1DF2-   E0 E0       CPX   #$E0
1DF4-   E0 E0       CPX   #$E0
1DF6-   E0 E0       CPX   #$E0
1DF8-   E0 E0       CPX   #$E0
1DFA-   E0 E0       CPX   #$E0
1DFC-   E0 E0       CPX   #$E0
1DFE-   E0 E0       CPX   #$E0
1E00-   E0 E0       CPX   #$E0
1E02-   E0 E0       CPX   #$E0
1E04-   E0 E0       CPX   #$E0
1E06-   E0 E0       CPX   #$E0
1E08-   E0 E0       CPX   #$E0
1E0A-   E0 E0       CPX   #$E0
1E0C-   E0 E0       CPX   #$E0
1E0E-   AA          TAX
1E0F-   8D AA 20    STA   $20AA
1E12-   20 20 20    JSR   $2020
1E15-   20 20 20    JSR   $2020
1E18-   20 C2 CF    JSR   $CFC2
1E1B-   D4          ???
1E1C-   D4          ???
1E1D-   CF          ???
1E1E-   CD 20 C9    CMP   $C920
1E21-   CE C3 CC    DEC   $CCC3
1E24-   D5 C4       CMP   $C4,X
1E26-   C5 D3       CMP   $D3
1E28-   20 20 20    JSR   $2020
1E2B-   20 20 20    JSR   $2020
1E2E-   20 AA 8D    JSR   $8DAA
1E31-   AA          TAX
1E32-   AC AC AC    LDY   $ACAC
1E35-   AC AC AC    LDY   $ACAC
1E38-   AC AC AC    LDY   $ACAC
1E3B-   AC AC AC    LDY   $ACAC
1E3E-   AC AC AC    LDY   $ACAC
1E41-   AC AC AC    LDY   $ACAC
1E44-   AC AC AC    LDY   $ACAC
1E47-   AC AC AC    LDY   $ACAC
1E4A-   AC AC AC    LDY   $ACAC
1E4D-   AC AC AC    LDY   $ACAC
1E50-   AA          TAX
1E51-   8D AA 8D    STA   $8DAA
1E54-   A0 D0       LDY   #$D0
1E56-   D5 D4       CMP   $D4,X
1E58-   A0 CD       LDY   #$CD
1E5A-   C9 CE       CMP   #$CE
1E5C-   AE CC C9    LDX   $C9CC
1E5F-   C2          ???
1E60-   AE D2 C5    LDX   $C5D2
1E63-   D1 D5       CMP   ($D5),Y
1E65-   C9 D2       CMP   #$D2
1E67-   C5 C4       CMP   $C4
1E69-   8D AA 8D    STA   $8DAA
1E6C-   AA          TAX
1E6D-   AA          TAX
1E6E-   20 C9 CE    JSR   $CEC9
1E71-   C4 C9       CPY   $C9
1E73-   D6 C9       DEC   $C9,X
1E75-   C4 D5       CPY   $D5
1E77-   C1 CC       CMP   ($CC,X)
1E79-   20 D3 D5    JSR   $D5D3
1E7C-   C2          ???
1E7D-   D2 CF       CMP   ($CF)
1E7F-   D5 D4       CMP   $D4,X
1E81-   C9 CE       CMP   #$CE
1E83-   C5 20       CMP   $20
1E85-   C9 CE       CMP   #$CE
1E87-   C3          ???
1E88-   CC D5 C4    CPY   $C4D5
1E8B-   C5 D3       CMP   $D3
1E8D-   8D AA 8D    STA   $8DAA
1E90-   AA          TAX
1E91-   20 20 D3    JSR   $D320
1E94-   D4          ???
1E95-   C4 C9       CPY   $C9
1E97-   CF          ???
1E98-   20 D3 D5    JSR   $D5D3
1E9B-   C2          ???
1E9C-   D2 CF       CMP   ($CF)
1E9E-   D5 D4       CMP   $D4,X
1EA0-   C9 CE       CMP   #$CE
1EA2-   C5 D3       CMP   $D3
1EA4-   8D AA 8D    STA   $8DAA
1EA7-   A0 D0       LDY   #$D0
1EA9-   D5 D4       CMP   $D4,X
1EAB-   A0 CD       LDY   #$CD
1EAD-   C9 CE       CMP   #$CE
1EAF-   AE D3 D5    LDX   $D5D3
1EB2-   C2          ???
1EB3-   AE D8 D0    LDX   $D0D8
1EB6-   D2 C9       CMP   ($C9)
1EB8-   CE D4 8D    DEC   $8DD4
1EBB-   A0 D0       LDY   #$D0
1EBD-   D5 D4       CMP   $D4,X
1EBF-   A0 CD       LDY   #$CD
1EC1-   C9 CE       CMP   #$CE
1EC3-   AE D3 D5    LDX   $D5D3
1EC6-   C2          ???
1EC7-   AE C4 D0    LDX   $D0C4
1ECA-   D2 C9       CMP   ($C9)
1ECC-   CE D4 8D    DEC   $8DD4
1ECF-   A0 D0       LDY   #$D0
1ED1-   D5 D4       CMP   $D4,X
1ED3-   A0 CD       LDY   #$CD
1ED5-   C9 CE       CMP   #$CE
1ED7-   AE D3 D5    LDX   $D5D3
1EDA-   C2          ???
1EDB-   AE D4 C8    LDX   $C8D4
1EDE-   CC C9 CE    CPY   $CEC9
1EE1-   C5 8D       CMP   $8D
1EE3-   A0 D0       LDY   #$D0
1EE5-   D5 D4       CMP   $D4,X
1EE7-   A0 CD       LDY   #$CD
1EE9-   C9 CE       CMP   #$CE
1EEB-   AE D3 D5    LDX   $D5D3
1EEE-   C2          ???
1EEF-   AE D4 D6    LDX   $D6D4
1EF2-   CC C9 CE    CPY   $CEC9
1EF5-   C5 8D       CMP   $8D
1EF7-   A0 D0       LDY   #$D0
1EF9-   D5 D4       CMP   $D4,X
1EFB-   A0 CD       LDY   #$CD
1EFD-   C9 CE       CMP   #$CE
1EFF-   AE D3 D5    LDX   $D5D3
1F02-   C2          ???
1F03-   AE C3 D5    LDX   $D5C3
1F06-   D2 D3       CMP   ($D3)
1F08-   CF          ???
1F09-   D2 D5       CMP   ($D5)
1F0B-   C4 C2       CPY   $C2
1F0D-   C6 8D       DEC   $8D
1F0F-   A0 D0       LDY   #$D0
1F11-   D5 D4       CMP   $D4,X
1F13-   A0 CD       LDY   #$CD
1F15-   C9 CE       CMP   #$CE
1F17-   AE D3 D5    LDX   $D5D3
1F1A-   C2          ???
1F1B-   AE D4 C6    LDX   $C6D4
1F1E-   C9 CC       CMP   #$CC
1F20-   CC C1 8D    CPY   $8DC1
1F23-   A0 D0       LDY   #$D0
1F25-   D5 D4       CMP   $D4,X
1F27-   A0 CD       LDY   #$CD
1F29-   C9 CE       CMP   #$CE
1F2B-   AE D3 D5    LDX   $D5D3
1F2E-   C2          ???
1F2F-   AE D3 C9    LDX   $C9D3
1F32-   CE D0 D5    DEC   $D5D0
1F35-   D4          ???
1F36-   8D A0 D0    STA   $D0A0
1F39-   D5 D4       CMP   $D4,X
1F3B-   A0 CD       LDY   #$CD
1F3D-   C9 CE       CMP   #$CE
1F3F-   AE D3 D5    LDX   $D5D3
1F42-   C2          ???
1F43-   AE C7 D0    LDX   $D0C7
1F46-   C2          ???
1F47-   D8          CLD
1F48-   8D A0 D0    STA   $D0A0
1F4B-   D5 D4       CMP   $D4,X
1F4D-   A0 CD       LDY   #$CD
1F4F-   C9 CE       CMP   #$CE
1F51-   AE D3 D5    LDX   $D5D3
1F54-   C2          ???
1F55-   AE D4 D8    LDX   $D8D4
1F58-   D4          ???
1F59-   D0 D5       BNE   $1F30
1F5B-   D4          ???
1F5C-   8D AA 8D    STA   $8DAA
