0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 D3    LDY   $D320,X
0950-   D4          ???
0951-   C4 C9       CPY   $C9
0953-   CF          ???
0954-   20 C4 C5    JSR   $C5C4
0957-   CD CF 20    CMP   $20CF
095A-   BE AD 20    LDX   $20AD,Y
095D-   20 20 20    JSR   $2020
0960-   20 20 20    JSR   $2020
0963-   20 AA 8D    JSR   $8DAA
0966-   AA          TAX
0967-   20 20 20    JSR   $2020
096A-   20 20 20    JSR   $2020
096D-   20 20 20    JSR   $2020
0970-   20 20 20    JSR   $2020
0973-   20 20 20    JSR   $2020
0976-   20 20 20    JSR   $2020
0979-   20 20 20    JSR   $2020
097C-   20 20 20    JSR   $2020
097F-   20 20 20    JSR   $2020
0982-   20 20 20    JSR   $2020
0985-   AA          TAX
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B1    JSR   $B120
09D4-   B3          ???
09D5-   AD CA C1    LDA   $C1CA
09D8-   CE AD B2    DEC   $B2AD
09DB-   B0 B1       BCS   $098E
09DD-   B9 20 20    LDA   $2020,Y
09E0-   20 20 20    JSR   $2020
09E3-   20 20 20    JSR   $2020
09E6-   20 20 AA    JSR   $AA20
09E9-   8D AA 20    STA   $20AA
09EC-   20 20 20    JSR   $2020
09EF-   20 20 20    JSR   $2020
09F2-   20 20 20    JSR   $2020
09F5-   20 20 20    JSR   $2020
09F8-   20 20 20    JSR   $2020
09FB-   20 20 20    JSR   $2020
09FE-   20 20 20    JSR   $2020
0A01-   20 20 20    JSR   $2020
0A04-   20 20 20    JSR   $2020
0A07-   20 20 AA    JSR   $AA20
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   C6 C6       DEC   $C6
0AFE-   8D A0 D4    STA   $D4A0
0B01-   D2 A0       CMP   ($A0)
0B03-   CF          ???
0B04-   CE 8D A0    DEC   $A08D
0B07-   C4 D3       CPY   $D3
0B09-   CB          ???
0B0A-   A0 D3       LDY   #$D3
0B0C-   D4          ???
0B0D-   C4 C9       CPY   $C9
0B0F-   CF          ???
0B10-   AE C4 C5    LDX   $C5C4
0B13-   CD CF 8D    CMP   $8DCF
0B16-   A0 CF       LDY   #$CF
0B18-   C2          ???
0B19-   CA          DEX
0B1A-   A0 A4       LDY   #$A4
0B1C-   C2          ???
0B1D-   C6 C5       DEC   $C5
0B1F-   B0 8D       BCS   $0AAE
0B21-   A0 CF       LDY   #$CF
0B23-   D2 C7       CMP   ($C7)
0B25-   A0 A4       LDY   #$A4
0B27-   B6 B0       LDX   $B0,Y
0B29-   B0 B0       BCS   $0ADB
0B2B-   8D AA 8D    STA   $8DAA
0B2E-   AA          TAX
0B2F-   E0 E0       CPX   #$E0
0B31-   E0 E0       CPX   #$E0
0B33-   E0 E0       CPX   #$E0
0B35-   E0 E0       CPX   #$E0
0B37-   E0 E0       CPX   #$E0
0B39-   E0 E0       CPX   #$E0
0B3B-   E0 E0       CPX   #$E0
0B3D-   E0 E0       CPX   #$E0
0B3F-   E0 E0       CPX   #$E0
0B41-   E0 E0       CPX   #$E0
0B43-   E0 E0       CPX   #$E0
0B45-   E0 E0       CPX   #$E0
0B47-   E0 E0       CPX   #$E0
0B49-   E0 E0       CPX   #$E0
0B4B-   E0 E0       CPX   #$E0
0B4D-   AA          TAX
0B4E-   8D AA 20    STA   $20AA
0B51-   20 D4 CF    JSR   $CFD4
0B54-   D0 20       BNE   $0B76
0B56-   C9 CE       CMP   #$CE
0B58-   C3          ???
0B59-   CC D5 C4    CPY   $C4D5
0B5C-   C5 D3       CMP   $D3
0B5E-   20 A8 C8    JSR   $C8A8
0B61-   CF          ???
0B62-   CF          ???
0B63-   CB          ???
0B64-   D3          ???
0B65-   AC CD C1    LDY   $C1CD
0B68-   C3          ???
0B69-   D2 CF       CMP   ($CF)
0B6B-   D3          ???
0B6C-   A9 20       LDA   #$20
0B6E-   AA          TAX
0B6F-   8D AA AC    STA   $ACAA
0B72-   AC AC AC    LDY   $ACAC
0B75-   AC AC AC    LDY   $ACAC
0B78-   AC AC AC    LDY   $ACAC
0B7B-   AC AC AC    LDY   $ACAC
0B7E-   AC AC AC    LDY   $ACAC
0B81-   AC AC AC    LDY   $ACAC
0B84-   AC AC AC    LDY   $ACAC
0B87-   AC AC AC    LDY   $ACAC
0B8A-   AC AC AC    LDY   $ACAC
0B8D-   AC AC AA    LDY   $AAAC
0B90-   8D AA 8D    STA   $8DAA
0B93-   A0 D0       LDY   #$D0
0B95-   D5 D4       CMP   $D4,X
0B97-   A0 D2       LDY   #$D2
0B99-   C5 D1       CMP   $D1
0B9B-   D5 C9       CMP   $C9,X
0B9D-   D2 C5       CMP   ($C5)
0B9F-   C4 AE       CPY   $AE
0BA1-   D6 C1       DEC   $C1,X
0BA3-   D2 D3       CMP   ($D3)
0BA5-   8D A0 D0    STA   $D0A0
0BA8-   D5 D4       CMP   $D4,X
0BAA-   20 A0 D2    JSR   $D2A0
0BAD-   C5 D1       CMP   $D1
0BAF-   D5 C9       CMP   $C9,X
0BB1-   D2 C5       CMP   ($C5)
0BB3-   C4 AE       CPY   $AE
0BB5-   C8          INY
0BB6-   CF          ???
0BB7-   CF          ???
0BB8-   CB          ???
0BB9-   D3          ???
0BBA-   AE CD C9    LDX   $C9CD
0BBD-   CE 8D A0    DEC   $A08D
0BC0-   D5 D3       CMP   $D3,X
0BC2-   C5 A0       CMP   $A0
0BC4-   D2 C5       CMP   ($C5)
0BC6-   D1 D5       CMP   ($D5),Y
0BC8-   C9 D2       CMP   #$D2
0BCA-   C5 C4       CMP   $C4
0BCC-   AE CD C1    LDX   $C1CD
0BCF-   C3          ???
0BD0-   AE CD C9    LDX   $C9CD
0BD3-   CE 8D A0    DEC   $A08D
0BD6-   D5 D3       CMP   $D3,X
0BD8-   C5 A0       CMP   $A0
0BDA-   D3          ???
0BDB-   D4          ???
0BDC-   C4 C9       CPY   $C9
0BDE-   CF          ???
0BDF-   AE CD C1    LDX   $C1CD
0BE2-   C3          ???
0BE3-   AE CD C9    LDX   $C9CD
0BE6-   CE 8D A0    DEC   $A08D
0BE9-   D0 D5       BNE   $0BC0
0BEB-   D4          ???
0BEC-   A0 D3       LDY   #$D3
0BEE-   D4          ???
0BEF-   C4 C9       CPY   $C9
0BF1-   CF          ???
0BF2-   AE C8 CF    LDX   $CFC8
0BF5-   CF          ???
0BF6-   CB          ???
0BF7-   D3          ???
0BF8-   AE CD C9    LDX   $C9CD
0BFB-   CE 8D AA    DEC   $AA8D
0BFE-   8D AA E0    STA   $E0AA
0C01-   E0 E0       CPX   #$E0
0C03-   E0 E0       CPX   #$E0
0C05-   E0 E0       CPX   #$E0
0C07-   E0 E0       CPX   #$E0
0C09-   E0 E0       CPX   #$E0
0C0B-   E0 E0       CPX   #$E0
0C0D-   E0 E0       CPX   #$E0
0C0F-   E0 E0       CPX   #$E0
0C11-   E0 E0       CPX   #$E0
0C13-   E0 E0       CPX   #$E0
0C15-   E0 E0       CPX   #$E0
0C17-   E0 E0       CPX   #$E0
0C19-   E0 E0       CPX   #$E0
0C1B-   E0 E0       CPX   #$E0
0C1D-   E0 AA       CPX   #$AA
0C1F-   8D AA 20    STA   $20AA
0C22-   20 20 20    JSR   $2020
0C25-   20 20 D0    JSR   $D020
0C28-   D2 CF       CMP   ($CF)
0C2A-   C7          ???
0C2B-   D2 C1       CMP   ($C1)
0C2D-   CD 20 CD    CMP   $CD20
0C30-   C1 C9       CMP   ($C9,X)
0C32-   CE 20 C2    DEC   $C220
0C35-   CF          ???
0C36-   C4 D9       CPY   $D9
0C38-   20 20 20    JSR   $2020
0C3B-   20 20 20    JSR   $2020
0C3E-   20 AA 8D    JSR   $8DAA
0C41-   AA          TAX
0C42-   AC AC AC    LDY   $ACAC
0C45-   AC AC AC    LDY   $ACAC
0C48-   AC AC AC    LDY   $ACAC
0C4B-   AC AC AC    LDY   $ACAC
0C4E-   AC AC AC    LDY   $ACAC
0C51-   AC AC AC    LDY   $ACAC
0C54-   AC AC AC    LDY   $ACAC
0C57-   AC AC AC    LDY   $ACAC
0C5A-   AC AC AC    LDY   $ACAC
0C5D-   AC AC AC    LDY   $ACAC
0C60-   AA          TAX
0C61-   8D AA 8D    STA   $8DAA
0C64-   A0 CA       LDY   #$CA
0C66-   D3          ???
0C67-   D2 A0       CMP   ($A0)
0C69-   C8          INY
0C6A-   CF          ???
0C6B-   CD C5 A0    CMP   $A0C5
0C6E-   BB          ???
0C6F-   20 C3 CC    JSR   $CCC3
0C72-   C5 C1       CMP   $C1
0C74-   D2 20       CMP   ($20)
0C76-   D3          ???
0C77-   C3          ???
0C78-   D2 C5       CMP   ($C5)
0C7A-   C5 CE       CMP   $CE
0C7C-   8D AA 8D    STA   $8DAA
0C7F-   AA          TAX
0C80-   AA          TAX
0C81-   20 D3 C9    JSR   $C9D3
0C84-   CE C3 C5    DEC   $C5C3
0C87-   20 D4 C8    JSR   $C8D4
0C8A-   C5 20       CMP   $20
0C8C-   D3          ???
0C8D-   D4          ???
0C8E-   C4 C9       CPY   $C9
0C90-   CF          ???
0C91-   20 CC C9    JSR   $C9CC
0C94-   C2          ???
0C95-   D2 C1       CMP   ($C1)
0C97-   D2 D9       CMP   ($D9)
0C99-   20 C8 C1    JSR   $C1C8
0C9C-   D3          ???
0C9D-   20 CD C1    JSR   $C1CD
0CA0-   C3          ???
0CA1-   D2 CF       CMP   ($CF)
0CA3-   D3          ???
0CA4-   20 C9 CE    JSR   $CEC9
0CA7-   8D AA AA    STA   $AAAA
0CAA-   20 C1 C4    JSR   $C4C1
0CAD-   C4 C9       CPY   $C9
0CAF-   D4          ???
0CB0-   C9 CF       CMP   #$CF
0CB2-   CE 20 D4    DEC   $D420
0CB5-   CF          ???
0CB6-   20 D2 CF    JSR   $CFD2
0CB9-   D5 D4       CMP   $D4,X
0CBB-   C9 CE       CMP   #$CE
0CBD-   C5 D3       CMP   $D3
0CBF-   20 D4 C8    JSR   $C8D4
0CC2-   C1 D4       CMP   ($D4,X)
0CC4-   20 C6 D5    JSR   $D5C6
0CC7-   CE C3 D4    DEC   $D4C3
0CCA-   C9 CF       CMP   #$CF
0CCC-   CE 20 CF    DEC   $CF20
0CCF-   CE 8D AA    DEC   $AA8D
0CD2-   AA          TAX
0CD3-   20 D4 C8    JSR   $C8D4
0CD6-   C5 C9       CMP   $C9
0CD8-   D2 20       CMP   ($20)
0CDA-   CF          ???
0CDB-   D7          ???
0CDC-   CE AC 20    DEC   $20AC
0CDF-   D4          ???
0CE0-   C8          INY
0CE1-   C9 D3       CMP   #$D3
0CE3-   20 C4 C5    JSR   $C5C4
0CE6-   CD CF 20    CMP   $20CF
0CE9-   D7          ???
0CEA-   C9 CC       CMP   #$CC
0CEC-   CC 20 D0    CPY   $D020
0CEF-   D2 C9       CMP   ($C9)
0CF1-   CD C1 D2    CMP   $D2C1
0CF4-   C9 CC       CMP   #$CC
0CF6-   D9 20 D5    CMP   $D520,Y
0CF9-   D3          ???
0CFA-   C5 8D       CMP   $8D
0CFC-   AA          TAX
0CFD-   AA          TAX
0CFE-   20 CD C1    JSR   $C1CD
0D01-   C3          ???
0D02-   D2 CF       CMP   ($CF)
0D04-   D3          ???
0D05-   20 D4 CF    JSR   $CFD4
0D08-   20 C9 CC    JSR   $CCC9
0D0B-   CC D5 D3    CPY   $D3D5
0D0E-   D4          ???
0D0F-   D2 C1       CMP   ($C1)
0D11-   D4          ???
0D12-   C5 20       CMP   $20
0D14-   D4          ???
0D15-   C8          INY
0D16-   C5 C9       CMP   $C9
0D18-   D2 20       CMP   ($20)
0D1A-   C6 D5       DEC   $D5
0D1C-   CE C3 D4    DEC   $D4C3
0D1F-   C9 CF       CMP   #$CF
0D21-   CE D3 AE    DEC   $AED3
0D24-   8D AA 8D    STA   $8DAA
0D27-   AA          TAX
0D28-   AA          TAX
0D29-   20 D0 D2    JSR   $D2D0
0D2C-   CE 20 D3    DEC   $D320
0D2F-   C9 CD       CMP   #$CD
0D31-   D0 CC       BNE   $0CFF
0D33-   D9 20 D0    CMP   $D020,Y
0D36-   D2 C9       CMP   ($C9)
0D38-   CE D4 D3    DEC   $D3D4
0D3B-   20 C1 20    JSR   $20C1
0D3E-   D3          ???
0D3F-   D4          ???
0D40-   D2 C9       CMP   ($C9)
0D42-   CE C7 20    DEC   $20C7
0D45-   CF          ???
0D46-   C6 20       DEC   $20
0D48-   D4          ???
0D49-   C5 D8       CMP   $D8
0D4B-   D4          ???
0D4C-   20 D4 CF    JSR   $CFD4
0D4F-   20 D4 C8    JSR   $C8D4
0D52-   C5 8D       CMP   $8D
0D54-   AA          TAX
0D55-   AA          TAX
0D56-   20 D3 C3    JSR   $C3D3
0D59-   D2 C5       CMP   ($C5)
0D5B-   C5 CE       CMP   $CE
0D5D-   20 C1 D4    JSR   $D4C1
0D60-   20 D4 C8    JSR   $C8D4
0D63-   C5 20       CMP   $20
0D65-   C3          ???
0D66-   D5 D2       CMP   $D2,X
0D68-   D2 C5       CMP   ($C5)
0D6A-   CE D4 20    DEC   $20D4
0D6D-   C3          ???
0D6E-   D5 D2       CMP   $D2,X
0D70-   D3          ???
0D71-   CF          ???
0D72-   D2 20       CMP   ($20)
0D74-   D0 CF       BNE   $0D45
0D76-   D3          ???
0D77-   C9 D4       CMP   #$D4
0D79-   C9 CF       CMP   #$CF
0D7B-   CE AC 20    DEC   $20AC
0D7E-   CF          ???
0D7F-   D2 8D       CMP   ($8D)
0D81-   AA          TAX
0D82-   AA          TAX
0D83-   20 D0 D2    JSR   $D2D0
0D86-   C9 CE       CMP   #$CE
0D88-   D4          ???
0D89-   D3          ???
0D8A-   20 D4 C8    JSR   $C8D4
0D8D-   C5 20       CMP   $20
0D8F-   C4 C1       CPY   $C1
0D91-   D4          ???
0D92-   C1 20       CMP   ($20,X)
0D94-   C1 D4       CMP   ($D4,X)
0D96-   20 C1 20    JSR   $20C1
0D99-   D0 C1       BNE   $0D5C
0D9B-   D2 D4       CMP   ($D4)
0D9D-   C9 C3       CMP   #$C3
0D9F-   D5 CC       CMP   $CC,X
0DA1-   C1 D2       CMP   ($D2,X)
0DA3-   20 CD C5    JSR   $C5CD
0DA6-   CD CF D2    CMP   $D2CF
0DA9-   D9 20 C1    CMP   $C120,Y
0DAC-   C4 C4       CPY   $C4
0DAE-   D2 C5       CMP   ($C5)
0DB0-   D3          ???
0DB1-   D3          ???
0DB2-   AE 8D AA    LDX   $AA8D
0DB5-   AA          TAX
0DB6-   20 C9 D4    JSR   $D4C9
0DB9-   20 C1 C3    JSR   $C3C1
0DBC-   C3          ???
0DBD-   CF          ???
0DBE-   CD D0 CC    CMP   $CCD0
0DC1-   C9 D3       CMP   #$D3
0DC3-   C8          INY
0DC4-   C5 D3       CMP   $D3
0DC6-   20 D4 C8    JSR   $C8D4
0DC9-   C9 D3       CMP   #$D3
0DCB-   20 C2 D9    JSR   $D9C2
0DCE-   20 C4 C5    JSR   $C5C4
0DD1-   D4          ???
0DD2-   C5 D2       CMP   $D2
0DD4-   CD C9 CE    CMP   $CEC9
0DD7-   C9 CE       CMP   #$CE
0DD9-   C7          ???
0DDA-   20 C9 C6    JSR   $C6C9
0DDD-   20 D4 C8    JSR   $C8D4
0DE0-   C5 8D       CMP   $8D
0DE2-   AA          TAX
0DE3-   AA          TAX
0DE4-   20 D0 C1    JSR   $C1D0
0DE7-   D2 C1       CMP   ($C1)
0DE9-   CD C5 D4    CMP   $D4C5
0DEC-   C5 D2       CMP   $D2
0DEE-   20 C9 D3    JSR   $D3C9
0DF1-   20 C1 20    JSR   $20C1
0DF4-   D3          ???
0DF5-   D4          ???
0DF6-   D2 C9       CMP   ($C9)
0DF8-   CE C7 20    DEC   $20C7
0DFB-   CF          ???
0DFC-   D2 20       CMP   ($20)
0DFE-   C1 CE       CMP   ($CE,X)
0E00-   20 C1 C4    JSR   $C4C1
0E03-   C4 D2       CPY   $D2
0E05-   C5 D3       CMP   $D3
0E07-   D3          ???
0E08-   AC 20 D4    LDY   $D420
0E0B-   C8          INY
0E0C-   C5 CE       CMP   $CE
0E0E-   20 C3 C1    JSR   $C1C3
0E11-   CC CC C9    CPY   $C9CC
0E14-   CE C7 8D    DEC   $8DC7
0E17-   AA          TAX
0E18-   AA          TAX
0E19-   20 C5 C9    JSR   $C9C5
0E1C-   D4          ???
0E1D-   C8          INY
0E1E-   C5 D2       CMP   $D2
0E20-   20 D8 D0    JSR   $D0D8
0E23-   D2 C9       CMP   ($C9)
0E25-   CE D4 20    DEC   $20D4
0E28-   CF          ???
0E29-   D2 20       CMP   ($20)
0E2B-   C4 D0       CPY   $D0
0E2D-   D2 C9       CMP   ($C9)
0E2F-   CE D4 AE    DEC   $AED4
0E32-   8D AA 8D    STA   $8DAA
0E35-   AA          TAX
0E36-   AA          TAX
0E37-   20 D4 C8    JSR   $C8D4
0E3A-   C5 20       CMP   $20
0E3C-   D2 CF       CMP   ($CF)
0E3E-   D5 D4       CMP   $D4,X
0E40-   C9 CE       CMP   #$CE
0E42-   C5 20       CMP   $20
0E44-   D1 D5       CMP   ($D5),Y
0E46-   C9 D4       CMP   #$D4
0E48-   D3          ???
0E49-   20 D0 D2    JSR   $D2D0
0E4C-   C9 CE       CMP   #$CE
0E4E-   D4          ???
0E4F-   C9 CE       CMP   #$CE
0E51-   C7          ???
0E52-   20 CF CE    JSR   $CECF
0E55-   C3          ???
0E56-   C5 20       CMP   $20
0E58-   D4          ???
0E59-   C8          INY
0E5A-   C5 20       CMP   $20
0E5C-   D6 C1       DEC   $C1,X
0E5E-   CC D5 C5    CPY   $C5D5
0E61-   8D AA AA    STA   $AAAA
0E64-   20 CF C6    JSR   $C6CF
0E67-   20 B0 B0    JSR   $B0B0
0E6A-   20 C9 D3    JSR   $D3C9
0E6D-   20 C5 CE    JSR   $CEC5
0E70-   C3          ???
0E71-   CF          ???
0E72-   D5 CE       CMP   $CE,X
0E74-   D4          ???
0E75-   C5 D2       CMP   $D2
0E77-   C5 C4       CMP   $C4
0E79-   AC 20 C9    LDY   $C920
0E7C-   CE 20 D4    DEC   $D420
0E7F-   C8          INY
0E80-   C5 20       CMP   $20
0E82-   C3          ???
0E83-   C1 D3       CMP   ($D3,X)
0E85-   C5 20       CMP   $20
0E87-   CF          ???
0E88-   C6 20       DEC   $20
0E8A-   D0 D2       BNE   $0E5E
0E8C-   C9 CE       CMP   #$CE
0E8E-   D4          ???
0E8F-   C9 CE       CMP   #$CE
0E91-   C7          ???
0E92-   8D AA AA    STA   $AAAA
0E95-   20 D0 D2    JSR   $D2D0
0E98-   CF          ???
0E99-   CD 20 CD    CMP   $CD20
0E9C-   C5 CD       CMP   $CD
0E9E-   CF          ???
0E9F-   D2 D9       CMP   ($D9)
0EA1-   AE 8D AA    LDX   $AA8D
0EA4-   8D AA AA    STA   $AAAA
0EA7-   20 CD C1    JSR   $C1CD
0EAA-   C3          ???
0EAB-   D2 CF       CMP   ($CF)
0EAD-   BA          TSX
0EAE-   20 D0 D2    JSR   $D2D0
0EB1-   CE 20 A2    DEC   $A220
0EB4-   D3          ???
0EB5-   D4          ???
0EB6-   D2 C9       CMP   ($C9)
0EB8-   CE C7 A2    DEC   $A2C7
0EBB-   20 BC CF    JSR   $CFBC
0EBE-   D2 BE       CMP   ($BE)
0EC0-   20 D0 D2    JSR   $D2D0
0EC3-   CE 20 D3    DEC   $D320
0EC6-   D4          ???
0EC7-   D2 C9       CMP   ($C9)
0EC9-   CE C7 DF    DEC   $DFC7
0ECC-   C1 C4       CMP   ($C4,X)
0ECE-   C4 D2       CPY   $D2
0ED0-   C5 D3       CMP   $D3
0ED2-   D3          ???
0ED3-   8D AA 8D    STA   $8DAA
0ED6-   A0 D0       LDY   #$D0
0ED8-   D2 CE       CMP   ($CE)
0EDA-   A0 A2       LDY   #$A2
0EDC-   D4          ???
0EDD-   C8          INY
0EDE-   C5 20       CMP   $20
0EE0-   D0 D2       BNE   $0EB4
0EE2-   CE 20 CD    DEC   $CD20
0EE5-   C1 C3       CMP   ($C3,X)
0EE7-   D2 CF       CMP   ($CF)
0EE9-   20 D3 C9    JSR   $C9D3
0EEC-   CD D0 CC    CMP   $CCD0
0EEF-   D9 20 A2    CMP   $A220,Y
0EF2-   AC B8 C4    LDY   $C4B8
0EF5-   8D A0 D0    STA   $D0A0
0EF8-   D2 CE       CMP   ($CE)
0EFA-   A0 A2       LDY   #$A2
0EFC-   C4 C9       CPY   $C9
0EFE-   D3          ???
0EFF-   D0 CC       BNE   $0ECD
0F01-   C1 D9       CMP   ($D9,X)
0F03-   D3          ???
0F04-   20 C1 20    JSR   $20C1
0F07-   CC C9 D4    CPY   $D4C9
0F0A-   C5 D2       CMP   $D2
0F0C-   C1 CC       CMP   ($CC,X)
0F0E-   20 D3 D4    JSR   $D4D3
0F11-   D2 C9       CMP   ($C9)
0F13-   CE C7 20    DEC   $20C7
0F16-   A2 AC       LDX   #$AC
0F18-   B8          CLV
0F19-   C4 8D       CPY   $8D
0F1B-   A0 D0       LDY   #$D0
0F1D-   D2 CE       CMP   ($CE)
0F1F-   A0 A2       LDY   #$A2
0F21-   CF          ???
0F22-   D2 20       CMP   ($20)
0F24-   C4 C1       CPY   $C1
0F26-   D4          ???
0F27-   C1 20       CMP   ($20,X)
0F29-   CC CF C3    CPY   $C3CF
0F2C-   C1 D4       CMP   ($D4,X)
0F2E-   C5 C4       CMP   $C4
0F30-   20 C1 D4    JSR   $D4C1
0F33-   20 C1 20    JSR   $20C1
0F36-   D3          ???
0F37-   D0 C5       BNE   $0EFE
0F39-   C3          ???
0F3A-   C9 C6       CMP   #$C6
0F3C-   C9 C3       CMP   #$C3
0F3E-   20 A2 AC    JSR   $ACA2
0F41-   B8          CLV
0F42-   C4 8D       CPY   $8D
0F44-   A0 D0       LDY   #$D0
0F46-   D2 CE       CMP   ($CE)
0F48-   A0 A2       LDY   #$A2
0F4A-   C1 C4       CMP   ($C4,X)
0F4C-   C4 D2       CPY   $D2
0F4E-   C5 D3       CMP   $D3
0F50-   D3          ???
0F51-   20 A8 D4    JSR   $D4A8
0F54-   C8          INY
0F55-   C5 20       CMP   $20
0F57-   CC C1 D4    CPY   $D4C1
0F5A-   D4          ???
0F5B-   C5 D2       CMP   $D2
0F5D-   20 D7 C9    JSR   $C9D7
0F60-   CC CC 20    CPY   $20CC
0F63-   C2          ???
0F64-   C5 20       CMP   $20
0F66-   D3          ???
0F67-   C8          INY
0F68-   CF          ???
0F69-   D7          ???
0F6A-   CE A2 AC    DEC   $ACA2
0F6D-   B8          CLV
0F6E-   C4 8D       CPY   $8D
0F70-   A0 D0       LDY   #$D0
0F72-   D2 CE       CMP   ($CE)
0F74-   A0 A2       LDY   #$A2
0F76-   C1 C6       CMP   ($C6,X)
0F78-   D4          ???
0F79-   C5 D2       CMP   $D2
0F7B-   20 D4 C8    JSR   $C8D4
0F7E-   C5 20       CMP   $20
0F80-   C9 CE       CMP   #$CE
0F82-   D0 20       BNE   $0FA4
0F84-   CD C1 C3    CMP   $C3C1
0F87-   D2 CF       CMP   ($CF)
0F89-   AE A2 AC    LDX   $ACA2
0F8C-   B8          CLV
0F8D-   C4 B8       CPY   $B8
0F8F-   C4 8D       CPY   $8D
0F91-   A0 D0       LDY   #$D0
0F93-   D2 CE       CMP   ($CE)
0F95-   A0 A2       LDY   #$A2
0F97-   CE CF D4    DEC   $D4CF
0F9A-   C5 20       CMP   $20
0F9C-   D4          ???
0F9D-   C8          INY
0F9E-   C1 D4       CMP   ($D4,X)
0FA0-   20 C1 20    JSR   $20C1
0FA3-   CE C5 D7    DEC   $D7C5
0FA6-   20 CC C9    JSR   $C9CC
0FA9-   CE C5 20    DEC   $20C5
0FAC-   C3          ???
0FAD-   C1 CE       CMP   ($CE,X)
0FAF-   20 C2 C5    JSR   $C5C2
0FB2-   20 D3 C5    JSR   $C5D3
0FB5-   CE D4 20    DEC   $20D4
0FB8-   A2 AC       LDX   #$AC
0FBA-   B8          CLV
0FBB-   C4 8D       CPY   $8D
0FBD-   A0 D0       LDY   #$D0
0FBF-   D2 CE       CMP   ($CE)
0FC1-   A0 A2       LDY   #$A2
0FC3-   C2          ???
0FC4-   D9 20 C1    CMP   $C120,Y
0FC7-   C4 C4       CPY   $C4
0FC9-   C9 CE       CMP   #$CE
0FCB-   C7          ???
0FCC-   20 AC B8    JSR   $B8AC
0FCF-   C4 20       CPY   $20
0FD1-   C1 C6       CMP   ($C6,X)
0FD3-   D4          ???
0FD4-   C5 D2       CMP   $D2
0FD6-   20 D4 C8    JSR   $C8D4
0FD9-   C5 20       CMP   $20
0FDB-   C5 CE       CMP   $CE
0FDD-   C4 C9       CPY   $C9
0FDF-   CE C7 20    DEC   $20C7
0FE2-   A2 AC       LDX   #$AC
0FE4-   B8          CLV
0FE5-   C4 8D       CPY   $8D
0FE7-   A0 D0       LDY   #$D0
0FE9-   D2 CE       CMP   ($CE)
0FEB-   A0 A2       LDY   #$A2
0FED-   D3          ???
0FEE-   D4          ???
0FEF-   D2 C9       CMP   ($C9)
0FF1-   CE C7 20    DEC   $20C7
0FF4-   C4 C5       CPY   $C5
0FF6-   CC C9 CD    CPY   $CDC9
0FF9-   C9 D4       CMP   #$D4
0FFB-   C5 D2       CMP   $D2
0FFD-   AE A2 AC    LDX   $ACA2
1000-   B8          CLV
1001-   C4 B8       CPY   $B8
1003-   C4 8D       CPY   $8D
1005-   A0 DF       LDY   #$DF
1007-   D7          ???
1008-   C1 C9       CMP   ($C9,X)
100A-   D4          ???
100B-   8D AA 8D    STA   $8DAA
100E-   AA          TAX
100F-   AA          TAX
1010-   20 CD C1    JSR   $C1CD
1013-   C3          ???
1014-   D2 CF       CMP   ($CF)
1016-   BA          TSX
1017-   20 D0 C3    JSR   $C3D0
101A-   D2 AC       CMP   ($AC)
101C-   20 CE CF    JSR   $CFCE
101F-   20 D0 C1    JSR   $C1D0
1022-   D2 C1       CMP   ($C1)
1024-   CD C5 D4    CMP   $D4C5
1027-   C5 D2       CMP   $D2
1029-   D3          ???
102A-   8D AA 8D    STA   $8DAA
102D-   A0 D0       LDY   #$D0
102F-   D2 CE       CMP   ($CE)
1031-   A0 A2       LDY   #$A2
1033-   D9 CF D5    CMP   $D5CF,Y
1036-   20 C3 C1    JSR   $C1C3
1039-   CE 20 C1    DEC   $C120
103C-   CC D3 CF    CPY   $CFD3
103F-   20 C7 C5    JSR   $C5C7
1042-   D4          ???
1043-   20 C1 20    JSR   $20C1
1046-   CE C5 D7    DEC   $D7C5
1049-   CC C9 CE    CPY   $CEC9
104C-   C5 A2       CMP   $A2
104E-   AC B8 C4    LDY   $C4B8
1051-   8D A0 D0    STA   $D0A0
1054-   D2 CE       CMP   ($CE)
1056-   A0 A2       LDY   #$A2
1058-   C2          ???
1059-   D9 20 D5    CMP   $D520,Y
105C-   D3          ???
105D-   C9 CE       CMP   #$CE
105F-   C7          ???
1060-   20 D4 C8    JSR   $C8D4
1063-   C5 20       CMP   $20
1065-   D0 C3       BNE   $102A
1067-   D2 A2       CMP   ($A2)
1069-   8D A0 D0    STA   $D0A0
106C-   C3          ???
106D-   D2 8D       CMP   ($8D)
106F-   A0 D0       LDY   #$D0
1071-   C3          ???
1072-   D2 8D       CMP   ($8D)
1074-   A0 D0       LDY   #$D0
1076-   C3          ???
1077-   D2 8D       CMP   ($8D)
1079-   A0 D0       LDY   #$D0
107B-   D2 CE       CMP   ($CE)
107D-   A0 A2       LDY   #$A2
107F-   D2 CF       CMP   ($CF)
1081-   D5 D4       CMP   $D4,X
1083-   C9 CE       CMP   #$CE
1085-   C5 AE       CMP   $AE
1087-   A2 8D       LDX   #$8D
1089-   A0 D0       LDY   #$D0
108B-   C3          ???
108C-   D2 8D       CMP   ($8D)
108E-   A0 D0       LDY   #$D0
1090-   C3          ???
1091-   D2 8D       CMP   ($8D)
1093-   A0 D0       LDY   #$D0
1095-   C3          ???
1096-   D2 8D       CMP   ($8D)
1098-   A0 DF       LDY   #$DF
109A-   D7          ???
109B-   C1 C9       CMP   ($C9,X)
109D-   D4          ???
109E-   8D AA 8D    STA   $8DAA
10A1-   AA          TAX
10A2-   AA          TAX
10A3-   20 CD C1    JSR   $C1CD
10A6-   C3          ???
10A7-   D2 CF       CMP   ($CF)
10A9-   BA          TSX
10AA-   20 C9 CE    JSR   $CEC9
10AD-   D0 AC       BNE   $105B
10AF-   20 CE CF    JSR   $CFCE
10B2-   20 D0 C1    JSR   $C1D0
10B5-   D2 C1       CMP   ($C1)
10B7-   CD C5 D4    CMP   $D4C5
10BA-   C5 D2       CMP   $D2
10BC-   D3          ???
10BD-   8D AA 8D    STA   $8DAA
10C0-   A0 CA       LDY   #$CA
10C2-   D3          ???
10C3-   D2 A0       CMP   ($A0)
10C5-   C8          INY
10C6-   CF          ???
10C7-   CD C5 8D    CMP   $8DC5
10CA-   A0 D0       LDY   #$D0
10CC-   D2 CE       CMP   ($CE)
10CE-   A0 A2       LDY   #$A2
10D0-   D4          ???
10D1-   C8          INY
10D2-   C5 20       CMP   $20
10D4-   C9 CE       CMP   #$CE
10D6-   D0 20       BNE   $10F8
10D8-   CD C1 C3    CMP   $C3C1
10DB-   D2 CF       CMP   ($CF)
10DD-   20 C1 C3    JSR   $C3C1
10E0-   C3          ???
10E1-   C5 D0       CMP   $D0
10E3-   D4          ???
10E4-   D3          ???
10E5-   20 D5 D0    JSR   $D0D5
10E8-   20 D4 CF    JSR   $CFD4
10EB-   A2 AC       LDX   #$AC
10ED-   B8          CLV
10EE-   C4 8D       CPY   $8D
10F0-   A0 D0       LDY   #$D0
10F2-   D2 CE       CMP   ($CE)
10F4-   A0 A2       LDY   #$A2
10F6-   B2 B5       LDA   ($B5)
10F8-   B5 20       LDA   $20,X
10FA-   C3          ???
10FB-   C8          INY
10FC-   C1 D2       CMP   ($D2,X)
10FE-   C1 C3       CMP   ($C3,X)
1100-   D4          ???
1101-   C5 D2       CMP   $D2
1103-   D3          ???
1104-   20 C1 CE    JSR   $CEC1
1107-   C4 20       CPY   $20
1109-   D3          ???
110A-   D4          ???
110B-   CF          ???
110C-   D2 C5       CMP   ($C5)
110E-   D3          ???
110F-   20 D4 C8    JSR   $C8D4
1112-   C5 CD       CMP   $CD
1114-   A2 AC       LDX   #$AC
1116-   B8          CLV
1117-   C4 8D       CPY   $8D
1119-   A0 D0       LDY   #$D0
111B-   D2 CE       CMP   ($CE)
111D-   A0 A2       LDY   #$A2
111F-   C9 CE       CMP   #$CE
1121-   20 DB D2    JSR   $D2DB
1124-   C5 D4       CMP   $D4
1126-   D5 D2       CMP   $D2,X
1128-   CE DD AE    DEC   $AEDD
112B-   20 D4 C8    JSR   $C8D4
112E-   C9 D3       CMP   #$D3
1130-   20 C3 C1    JSR   $C1C3
1133-   CE 20 C2    DEC   $C220
1136-   C5 20       CMP   $20
1138-   C5 C1       CMP   $C1
113A-   D3          ???
113B-   C9 CC       CMP   #$CC
113D-   D9 A2 AC    CMP   $ACA2,Y
1140-   B8          CLV
1141-   C4 8D       CPY   $8D
1143-   A0 D0       LDY   #$D0
1145-   D2 CE       CMP   ($CE)
1147-   A0 A2       LDY   #$A2
1149-   D0 D2       BNE   $111D
114B-   C9 CE       CMP   #$CE
114D-   D4          ???
114E-   C5 C4       CMP   $C4
1150-   20 C9 CD    JSR   $CDC9
1153-   CD C5 C4    CMP   $C4C5
1156-   C9 C1       CMP   #$C1
1158-   D4          ???
1159-   C5 CC       CMP   $CC
115B-   D9 20 D7    CMP   $D720,Y
115E-   C9 D4       CMP   #$D4
1160-   C8          INY
1161-   20 D0 D2    JSR   $D2D0
1164-   CE 20 C2    DEC   $C220
1167-   D9 A2 AC    CMP   $ACA2,Y
116A-   B8          CLV
116B-   C4 8D       CPY   $8D
116D-   A0 D0       LDY   #$D0
116F-   D2 CE       CMP   ($CE)
1171-   A0 A2       LDY   #$A2
1173-   D5 D3       CMP   $D3,X
1175-   C9 CE       CMP   #$CE
1177-   C7          ???
1178-   20 D4 C8    JSR   $C8D4
117B-   C5 20       CMP   $20
117D-   C1 C4       CMP   ($C4,X)
117F-   C4 D2       CPY   $D2
1181-   C5 D3       CMP   $D3
1183-   D3          ???
1184-   20 CD CF    JSR   $CFCD
1187-   C4 C5       CPY   $C5
1189-   AE A2 AC    LDX   $ACA2
118C-   B8          CLV
118D-   C4 B8       CPY   $B8
118F-   C4 8D       CPY   $8D
1191-   A0 D0       LDY   #$D0
1193-   D2 CE       CMP   ($CE)
1195-   A0 A2       LDY   #$A2
1197-   C5 CE       CMP   $CE
1199-   D4          ???
119A-   C5 D2       CMP   $D2
119C-   20 D3 CF    JSR   $CFD3
119F-   CD C5 D4    CMP   $D4C5
11A2-   C8          INY
11A3-   C9 CE       CMP   #$CE
11A5-   C7          ???
11A6-   BA          TSX
11A7-   20 A2 8D    JSR   $8DA2
11AA-   A0 C9       LDY   #$C9
11AC-   CE D0 8D    DEC   $8DD0
11AF-   A0 D0       LDY   #$D0
11B1-   C3          ???
11B2-   D2 8D       CMP   ($8D)
11B4-   A0 D0       LDY   #$D0
11B6-   C3          ???
11B7-   D2 8D       CMP   ($8D)
11B9-   A0 D0       LDY   #$D0
11BB-   D2 CE       CMP   ($CE)
11BD-   A0 A2       LDY   #$A2
11BF-   D9 CF D5    CMP   $D5CF,Y
11C2-   20 D7 D2    JSR   $D2D7
11C5-   CF          ???
11C6-   D4          ???
11C7-   C5 BA       CMP   $BA
11C9-   20 A2 AC    JSR   $ACA2
11CC-   B8          CLV
11CD-   C4 B8       CPY   $B8
11CF-   C4 8D       CPY   $8D
11D1-   A0 D0       LDY   #$D0
11D3-   D2 CE       CMP   ($CE)
11D5-   A0 D2       LDY   #$D2
11D7-   C5 D4       CMP   $D4
11D9-   D5 D2       CMP   $D2,X
11DB-   CE 8D A0    DEC   $A08D
11DE-   D0 C3       BNE   $11A3
11E0-   D2 8D       CMP   ($8D)
11E2-   A0 D0       LDY   #$D0
11E4-   C3          ???
11E5-   D2 8D       CMP   ($8D)
11E7-   A0 DF       LDY   #$DF
11E9-   D7          ???
11EA-   C1 C9       CMP   ($C9,X)
11EC-   D4          ???
11ED-   8D AA 8D    STA   $8DAA
11F0-   AA          TAX
11F1-   AA          TAX
11F2-   20 CD C1    JSR   $C1CD
11F5-   C3          ???
11F6-   D2 CF       CMP   ($CF)
11F8-   BA          TSX
11F9-   20 C7 CB    JSR   $CBC7
11FC-   C5 D9       CMP   $D9
11FE-   AC 20 CE    LDY   $CE20
1201-   CF          ???
1202-   20 D0 C1    JSR   $C1D0
1205-   D2 C1       CMP   ($C1)
1207-   CD C5 D4    CMP   $D4C5
120A-   C5 D2       CMP   $D2
120C-   D3          ???
120D-   8D AA 8D    STA   $8DAA
1210-   A0 D0       LDY   #$D0
1212-   D2 CE       CMP   ($CE)
1214-   A0 A2       LDY   #$A2
1216-   D4          ???
1217-   C8          INY
1218-   C5 20       CMP   $20
121A-   C7          ???
121B-   CB          ???
121C-   C5 D9       CMP   $D9
121E-   20 CD C1    JSR   $C1CD
1221-   C3          ???
1222-   D2 CF       CMP   ($CF)
1224-   20 D3 C9    JSR   $C9D3
1227-   CD D0 CC    CMP   $CCD0
122A-   D9 20 C7    CMP   $C720,Y
122D-   C5 D4       CMP   $D4
122F-   D3          ???
1230-   A2 AC       LDX   #$AC
1232-   B8          CLV
1233-   C4 8D       CPY   $8D
1235-   A0 D0       LDY   #$D0
1237-   D2 CE       CMP   ($CE)
1239-   A0 A2       LDY   #$A2
123B-   C1 20       CMP   ($20,X)
123D-   D3          ???
123E-   C9 CE       CMP   #$CE
1240-   C7          ???
1241-   CC C5 20    CPY   $20C5
1244-   CB          ???
1245-   C5 D9       CMP   $D9
1247-   D0 D2       BNE   $121B
1249-   C5 D3       CMP   $D3
124B-   D3          ???
124C-   AC 20 D3    LDY   $D320
124F-   D4          ???
1250-   CF          ???
1251-   D2 C5       CMP   ($C5)
1253-   C4 20       CPY   $20
1255-   C9 CE       CMP   #$CE
1257-   20 AE C1    JSR   $C1AE
125A-   A2 AC       LDX   #$AC
125C-   B8          CLV
125D-   C4 B8       CPY   $B8
125F-   C4 8D       CPY   $8D
1261-   A0 C7       LDY   #$C7
1263-   CB          ???
1264-   C5 D9       CMP   $D9
1266-   8D AA 8D    STA   $8DAA
1269-   AA          TAX
126A-   AA          TAX
126B-   20 CD C1    JSR   $C1CD
126E-   C3          ???
126F-   D2 CF       CMP   ($CF)
1271-   BA          TSX
1272-   20 D3 C3    JSR   $C3D3
1275-   D0 CF       BNE   $1246
1277-   D3          ???
1278-   20 D8 DF    JSR   $DFD8
127B-   D0 CF       BNE   $124C
127D-   D3          ???
127E-   C9 D4       CMP   #$D4
1280-   C9 CF       CMP   #$CF
1282-   CE BB D9    DEC   $D9BB
1285-   DF          ???
1286-   D0 CF       BNE   $1257
1288-   D3          ???
1289-   C9 D4       CMP   #$D4
128B-   C9 CF       CMP   #$CF
128D-   CE 8D AA    DEC   $AA8D
1290-   AA          TAX
1291-   20 CD C1    JSR   $C1CD
1294-   C3          ???
1295-   D2 CF       CMP   ($CF)
1297-   BA          TSX
1298-   20 D3 C5    JSR   $C5D3
129B-   D4          ???
129C-   C3          ???
129D-   D8          CLD
129E-   20 D8 DF    JSR   $DFD8
12A1-   D0 CF       BNE   $1272
12A3-   D3          ???
12A4-   C9 D4       CMP   #$D4
12A6-   C9 CF       CMP   #$CF
12A8-   CE 8D AA    DEC   $AA8D
12AB-   AA          TAX
12AC-   20 CD C1    JSR   $C1CD
12AF-   C3          ???
12B0-   D2 CF       CMP   ($CF)
12B2-   BA          TSX
12B3-   20 D3 C5    JSR   $C5D3
12B6-   D4          ???
12B7-   C3          ???
12B8-   D9 20 D9    CMP   $D920,Y
12BB-   DF          ???
12BC-   D0 CF       BNE   $128D
12BE-   D3          ???
12BF-   C9 D4       CMP   #$D4
12C1-   C9 CF       CMP   #$CF
12C3-   CE 8D AA    DEC   $AA8D
12C6-   8D A0 CA    STA   $CAA0
12C9-   D3          ???
12CA-   D2 A0       CMP   ($A0)
12CC-   C8          INY
12CD-   CF          ???
12CE-   CD C5 8D    CMP   $8DC5
12D1-   A0 D3       LDY   #$D3
12D3-   C3          ???
12D4-   D0 CF       BNE   $12A5
12D6-   D3          ???
12D7-   A0 A3       LDY   #$A3
12D9-   B1 B0       LDA   ($B0),Y
12DB-   BB          ???
12DC-   A3          ???
12DD-   B1 B5       LDA   ($B5),Y
12DF-   8D A0 D0    STA   $D0A0
12E2-   D2 CE       CMP   ($CE)
12E4-   A0 A2       LDY   #$A2
12E6-   D3          ???
12E7-   C3          ???
12E8-   D0 CF       BNE   $12B9
12EA-   D3          ???
12EB-   20 D0 CF    JSR   $CFD0
12EE-   D3          ???
12EF-   C9 D4       CMP   #$D4
12F1-   C9 CF       CMP   #$CF
12F3-   CE D3 20    DEC   $20D3
12F6-   D4          ???
12F7-   C8          INY
12F8-   C5 20       CMP   $20
12FA-   C3          ???
12FB-   D5 D2       CMP   $D2,X
12FD-   D3          ???
12FE-   CF          ???
12FF-   D2 A2       CMP   ($A2)
1301-   8D A0 D0    STA   $D0A0
1304-   D2 CE       CMP   ($CE)
1306-   A0 A2       LDY   #$A2
1308-   20 C1 D4    JSR   $D4C1
130B-   20 D4 C8    JSR   $C8D4
130E-   C5 20       CMP   $20
1310-   C7          ???
1311-   C9 D6       CMP   #$D6
1313-   C5 CE       CMP   $CE
1315-   20 D8 AC    JSR   $ACD8
1318-   D9 AE A2    CMP   $A2AE,Y
131B-   8D A0 DF    STA   $DFA0
131E-   D7          ???
131F-   C1 C9       CMP   ($C9,X)
1321-   D4          ???
1322-   8D A0 D3    STA   $D3A0
1325-   C5 D4       CMP   $D4
1327-   C3          ???
1328-   D9 A0 A3    CMP   $A3A0,Y
132B-   B2 B0       LDA   ($B0)
132D-   8D A0 D3    STA   $D3A0
1330-   C5 D4       CMP   $D4
1332-   C3          ???
1333-   D8          CLD
1334-   A0 A3       LDY   #$A3
1336-   B1 8D       LDA   ($8D),Y
1338-   A0 D0       LDY   #$D0
133A-   D2 CE       CMP   ($CE)
133C-   A0 A2       LDY   #$A2
133E-   D3          ???
133F-   C5 D4       CMP   $D4
1341-   C3          ???
1342-   D8          CLD
1343-   20 D3 C5    JSR   $C5D3
1346-   D4          ???
1347-   D3          ???
1348-   20 D8 20    JSR   $20D8
134B-   D0 CF       BNE   $131C
134D-   D3          ???
134E-   C9 D4       CMP   #$D4
1350-   C9 CF       CMP   #$CF
1352-   CE 20 A2    DEC   $A220
1355-   8D A0 D3    STA   $D3A0
1358-   C5 D4       CMP   $D4
135A-   C3          ???
135B-   D9 A0 A3    CMP   $A3A0,Y
135E-   B2 B2       LDA   ($B2)
1360-   8D A0 D0    STA   $D0A0
1363-   D2 CE       CMP   ($CE)
1365-   A0 A2       LDY   #$A2
1367-   D3          ???
1368-   C5 D4       CMP   $D4
136A-   C3          ???
136B-   D9 20 D3    CMP   $D320,Y
136E-   C5 D4       CMP   $D4
1370-   D3          ???
1371-   20 D4 C8    JSR   $C8D4
1374-   C5 20       CMP   $20
1376-   D9 A2 8D    CMP   $8DA2,Y
1379-   A0 DF       LDY   #$DF
137B-   D7          ???
137C-   C1 C9       CMP   ($C9,X)
137E-   D4          ???
137F-   8D AA 8D    STA   $8DAA
1382-   AA          TAX
1383-   AA          TAX
1384-   20 CD C1    JSR   $C1CD
1387-   C3          ???
1388-   D2 CF       CMP   ($CF)
138A-   BA          TSX
138B-   20 C3 D5    JSR   $D5C3
138E-   D2 C6       CMP   ($C6)
1390-   20 CE D5    JSR   $D5CE
1393-   CD C2 C5    CMP   $C5C2
1396-   D2 DF       CMP   ($DF)
1398-   CF          ???
1399-   C6 DF       DEC   $DF
139B-   D3          ???
139C-   D0 C1       BNE   $135F
139E-   C3          ???
139F-   C5 D3       CMP   $D3
13A1-   8D AA AA    STA   $AAAA
13A4-   20 20 20    JSR   $2020
13A7-   20 20 20    JSR   $2020
13AA-   20 20 C3    JSR   $C320
13AD-   D5 D2       CMP   $D2,X
13AF-   C2          ???
13B0-   20 CE D5    JSR   $D5CE
13B3-   CD C2 C5    CMP   $C5C2
13B6-   D2 DF       CMP   ($DF)
13B8-   CF          ???
13B9-   C6 DF       DEC   $DF
13BB-   D3          ???
13BC-   D0 C1       BNE   $137F
13BE-   C3          ???
13BF-   C5 D3       CMP   $D3
13C1-   8D AA AA    STA   $AAAA
13C4-   20 20 20    JSR   $2020
13C7-   20 20 20    JSR   $2020
13CA-   20 20 C3    JSR   $C320
13CD-   D5 D2       CMP   $D2,X
13CF-   D5 20       CMP   $20,X
13D1-   CE D5 CD    DEC   $CDD5
13D4-   C2          ???
13D5-   C5 D2       CMP   $D2
13D7-   DF          ???
13D8-   CF          ???
13D9-   C6 DF       DEC   $DF
13DB-   D3          ???
13DC-   D0 C1       BNE   $139F
13DE-   C3          ???
13DF-   C5 D3       CMP   $D3
13E1-   8D AA AA    STA   $AAAA
13E4-   20 20 20    JSR   $2020
13E7-   20 20 20    JSR   $2020
13EA-   20 20 C3    JSR   $C320
13ED-   D5 D2       CMP   $D2,X
13EF-   C4 20       CPY   $20
13F1-   CE D5 CD    DEC   $CDD5
13F4-   C2          ???
13F5-   C5 D2       CMP   $D2
13F7-   DF          ???
13F8-   CF          ???
13F9-   C6 DF       DEC   $DF
13FB-   D3          ???
13FC-   D0 C1       BNE   $13BF
13FE-   C3          ???
13FF-   C5 D3       CMP   $D3
1401-   8D AA 8D    STA   $8DAA
1404-   A0 CA       LDY   #$CA
1406-   D3          ???
1407-   D2 A0       CMP   ($A0)
1409-   C8          INY
140A-   CF          ???
140B-   CD C5 8D    CMP   $8DC5
140E-   A0 D0       LDY   #$D0
1410-   D2 CE       CMP   ($CE)
1412-   A0 A2       LDY   #$A2
1414-   D4          ???
1415-   C8          INY
1416-   C5 20       CMP   $20
1418-   C3          ???
1419-   D5 D2       CMP   $D2,X
141B-   D3          ???
141C-   CF          ???
141D-   D2 20       CMP   ($20)
141F-   C3          ???
1420-   C1 CE       CMP   ($CE,X)
1422-   20 C1 CC    JSR   $CCC1
1425-   D3          ???
1426-   CF          ???
1427-   20 C2 C5    JSR   $C5C2
142A-   20 CD CF    JSR   $CFCD
142D-   D6 C5       DEC   $C5,X
142F-   C4 A2       CPY   $A2
1431-   8D A0 DF    STA   $DFA0
1434-   D7          ???
1435-   C1 C9       CMP   ($C9,X)
1437-   D4          ???
1438-   8D A0 C3    STA   $C3A0
143B-   D5 D2       CMP   $D2,X
143D-   C6 A0       DEC   $A0
143F-   A3          ???
1440-   B1 B0       LDA   ($B0),Y
1442-   8D A0 D0    STA   $D0A0
1445-   D2 CE       CMP   ($CE)
1447-   A0 A2       LDY   #$A2
1449-   D2 C5       CMP   ($C5)
144B-   CC C1 D4    CPY   $D4C1
144E-   C9 D6       CMP   #$D6
1450-   C5 20       CMP   $20
1452-   D4          ???
1453-   CF          ???
1454-   20 D4 C8    JSR   $C8D4
1457-   C5 20       CMP   $20
1459-   C3          ???
145A-   D5 D2       CMP   $D2,X
145C-   D2 C5       CMP   ($C5)
145E-   CE D4 A2    DEC   $A2D4
1461-   8D A0 DF    STA   $DFA0
1464-   D7          ???
1465-   C1 C9       CMP   ($C9,X)
1467-   D4          ???
1468-   8D A0 C3    STA   $C3A0
146B-   D5 D2       CMP   $D2,X
146D-   C4 A0       CPY   $A0
146F-   A3          ???
1470-   B0 B3       BCS   $1425
1472-   8D A0 D0    STA   $D0A0
1475-   D2 CE       CMP   ($CE)
1477-   A0 A2       LDY   #$A2
1479-   D0 CF       BNE   $144A
147B-   D3          ???
147C-   C9 D4       CMP   #$D4
147E-   C9 CF       CMP   #$CF
1480-   CE 20 D7    DEC   $D720
1483-   C9 D4       CMP   #$D4
1485-   C8          INY
1486-   20 D4 C8    JSR   $C8D4
1489-   C5 20       CMP   $20
148B-   C3          ???
148C-   D5 D2       CMP   $D2,X
148E-   C6 AC       DEC   $AC
1490-   C3          ???
1491-   D5 D2       CMP   $D2,X
1493-   C4 AC       CPY   $AC
1495-   A2 8D       LDX   #$8D
1497-   A0 DF       LDY   #$DF
1499-   D7          ???
149A-   C1 C9       CMP   ($C9,X)
149C-   D4          ???
149D-   8D A0 C3    STA   $C3A0
14A0-   D5 D2       CMP   $D2,X
14A2-   C4 A0       CPY   $A0
14A4-   A3          ???
14A5-   B8          CLV
14A6-   8D A0 D3    STA   $D3A0
14A9-   C5 D4       CMP   $D4
14AB-   C3          ???
14AC-   D8          CLD
14AD-   A0 A3       LDY   #$A3
14AF-   B1 B2       LDA   ($B2),Y
14B1-   8D A0 C3    STA   $C3A0
14B4-   D5 D2       CMP   $D2,X
14B6-   C2          ???
14B7-   A0 A3       LDY   #$A3
14B9-   B1 B0       LDA   ($B0),Y
14BB-   8D A0 D0    STA   $D0A0
14BE-   D2 CE       CMP   ($CE)
14C0-   A0 A2       LDY   #$A2
14C2-   C3          ???
14C3-   D5 D2       CMP   $D2,X
14C5-   C2          ???
14C6-   20 C1 CE    JSR   $CEC1
14C9-   C4 A2       CPY   $A2
14CB-   8D A0 C3    STA   $C3A0
14CE-   D5 D2       CMP   $D2,X
14D0-   D5 A0       CMP   $A0,X
14D2-   A3          ???
14D3-   B0 B5       BCS   $148A
14D5-   8D A0 D0    STA   $D0A0
14D8-   D2 CE       CMP   ($CE)
14DA-   A0 A2       LDY   #$A2
14DC-   C3          ???
14DD-   D5 D2       CMP   $D2,X
14DF-   D5 20       CMP   $20,X
14E1-   A8          TAY
14E2-   C6 CF       DEC   $CF
14E4-   D2 D7       CMP   ($D7)
14E6-   C1 D2       CMP   ($D2,X)
14E8-   C4 AC       CPY   $AC
14EA-   20 C4 CF    JSR   $CFC4
14ED-   D7          ???
14EE-   CE AC 20    DEC   $20AC
14F1-   C2          ???
14F2-   C1 C3       CMP   ($C3,X)
14F4-   CB          ???
14F5-   AC 20 D5    LDY   $D520
14F8-   D0 A9       BNE   $14A3
14FA-   A2 8D       LDX   #$8D
14FC-   A0 DF       LDY   #$DF
14FE-   D7          ???
14FF-   C1 C9       CMP   ($C9,X)
1501-   D4          ???
1502-   8D AA 8D    STA   $8DAA
1505-   AA          TAX
1506-   AA          TAX
1507-   20 CD C1    JSR   $C1CD
150A-   C3          ???
150B-   D2 CF       CMP   ($CF)
150D-   BA          TSX
150E-   20 D2 C3    JSR   $C3D2
1511-   D0 CF       BNE   $14E2
1513-   D3          ???
1514-   20 D8 DF    JSR   $DFD8
1517-   D0 CF       BNE   $14E8
1519-   D3          ???
151A-   C9 D4       CMP   #$D4
151C-   C9 CF       CMP   #$CF
151E-   CE BB D9    DEC   $D9BB
1521-   DF          ???
1522-   D0 CF       BNE   $14F3
1524-   D3          ???
1525-   C9 D4       CMP   #$D4
1527-   C9 CF       CMP   #$CF
1529-   CE 8D AA    DEC   $AA8D
152C-   8D A0 CA    STA   $CAA0
152F-   D3          ???
1530-   D2 A0       CMP   ($A0)
1532-   C8          INY
1533-   CF          ???
1534-   CD C5 8D    CMP   $8DC5
1537-   A0 D0       LDY   #$D0
1539-   D2 CE       CMP   ($CE)
153B-   A0 A2       LDY   #$A2
153D-   C1 C1       CMP   ($C1,X)
153F-   C1 C1       CMP   ($C1,X)
1541-   C1 C1       CMP   ($C1,X)
1543-   C1 C1       CMP   ($C1,X)
1545-   C1 C1       CMP   ($C1,X)
1547-   A2 8D       LDX   #$8D
1549-   A0 D3       LDY   #$D3
154B-   C3          ???
154C-   D0 CF       BNE   $151D
154E-   D3          ???
154F-   A0 A3       LDY   #$A3
1551-   B0 B5       BCS   $1508
1553-   BB          ???
1554-   A3          ???
1555-   B0 B5       BCS   $150C
1557-   8D A0 D0    STA   $D0A0
155A-   D2 CE       CMP   ($CE)
155C-   A0 A2       LDY   #$A2
155E-   C1 C1       CMP   ($C1,X)
1560-   C2          ???
1561-   C2          ???
1562-   C3          ???
1563-   C3          ???
1564-   A2 AC       LDX   #$AC
1566-   B8          CLV
1567-   C4 B8       CPY   $B8
1569-   C4 B8       CPY   $B8
156B-   C4 8D       CPY   $8D
156D-   A0 D2       LDY   #$D2
156F-   C3          ???
1570-   D0 CF       BNE   $1541
1572-   D3          ???
1573-   A0 A3       LDY   #$A3
1575-   B0 B5       BCS   $152C
1577-   BB          ???
1578-   A3          ???
1579-   B0 B5       BCS   $1530
157B-   8D A0 D3    STA   $D3A0
157E-   D4          ???
157F-   C1 A0       CMP   ($A0,X)
1581-   A4 B3       LDY   $B3
1583-   B0 B0       BCS   $1535
1585-   8D A0 D0    STA   $D0A0
1588-   C3          ???
1589-   D2 8D       CMP   ($8D)
158B-   A0 D0       LDY   #$D0
158D-   D2 CE       CMP   ($CE)
158F-   A0 A2       LDY   #$A2
1591-   D4          ???
1592-   C8          INY
1593-   C5 20       CMP   $20
1595-   D2 C3       CMP   ($C3)
1597-   D0 CF       BNE   $1568
1599-   D3          ???
159A-   20 CD C1    JSR   $C1CD
159D-   C3          ???
159E-   D2 CF       CMP   ($CF)
15A0-   20 D2 C5    JSR   $C5D2
15A3-   D4          ???
15A4-   D5 D2       CMP   $D2,X
15A6-   CE D3 20    DEC   $20D3
15A9-   D4          ???
15AA-   C8          INY
15AB-   C5 A2       CMP   $A2
15AD-   AC B8 C4    LDY   $C4B8
15B0-   8D A0 D0    STA   $D0A0
15B3-   D2 CE       CMP   ($CE)
15B5-   A0 A2       LDY   #$A2
15B7-   C3          ???
15B8-   C8          INY
15B9-   C1 D2       CMP   ($D2,X)
15BB-   C1 C3       CMP   ($C3,X)
15BD-   D4          ???
15BE-   C5 D2       CMP   $D2
15C0-   20 C1 D4    JSR   $D4C1
15C3-   20 D4 C8    JSR   $C8D4
15C6-   C5 20       CMP   $20
15C8-   C7          ???
15C9-   C9 D6       CMP   #$D6
15CB-   C5 CE       CMP   $CE
15CD-   20 D8 AC    JSR   $ACD8
15D0-   D9 A2 AC    CMP   $ACA2,Y
15D3-   B8          CLV
15D4-   C4 8D       CPY   $8D
15D6-   A0 D0       LDY   #$D0
15D8-   D2 CE       CMP   ($CE)
15DA-   A0 A2       LDY   #$A2
15DC-   CC CF C3    CPY   $C3CF
15DF-   C1 D4       CMP   ($D4,X)
15E1-   C9 CF       CMP   #$CF
15E3-   CE AE 20    DEC   $20AE
15E6-   D4          ???
15E7-   C8          INY
15E8-   C5 20       CMP   $20
15EA-   C3          ???
15EB-   C8          INY
15EC-   C1 D2       CMP   ($D2,X)
15EE-   20 C1 20    JSR   $20C1
15F1-   B5 AC       LDA   $AC,X
15F3-   B5 A2       LDA   $A2,X
15F5-   AC B8 C4    LDY   $C4B8
15F8-   8D A0 D0    STA   $D0A0
15FB-   D2 CE       CMP   ($CE)
15FD-   A0 A2       LDY   #$A2
15FF-   C9 D3       CMP   #$D3
1601-   BA          TSX
1602-   20 A2 8D    JSR   $8DA2
1605-   A0 CC       LDY   #$CC
1607-   C4 C1       CPY   $C1
1609-   A0 A4       LDY   #$A4
160B-   B3          ???
160C-   B0 B0       BCS   $15BE
160E-   8D A0 CA    STA   $CAA0
1611-   D3          ???
1612-   D2 A0       CMP   ($A0)
1614-   C3          ???
1615-   CF          ???
1616-   D5 D4       CMP   $D4,X
1618-   B1 8D       LDA   ($8D),Y
161A-   A0 D0       LDY   #$D0
161C-   C3          ???
161D-   D2 8D       CMP   ($8D)
161F-   A0 D0       LDY   #$D0
1621-   C3          ???
1622-   D2 8D       CMP   ($8D)
1624-   A0 DF       LDY   #$DF
1626-   D7          ???
1627-   C1 C9       CMP   ($C9,X)
1629-   D4          ???
162A-   8D AA 8D    STA   $8DAA
162D-   AA          TAX
162E-   AA          TAX
162F-   20 CD C1    JSR   $C1CD
1632-   C3          ???
1633-   D2 CF       CMP   ($CF)
1635-   BA          TSX
1636-   20 D0 C4    JSR   $C4D0
1639-   CC 20 D0    CPY   $D020
163C-   C1 C4       CMP   ($C4,X)
163E-   C4 CC       CPY   $CC
1640-   C5 DF       CMP   $DF
1642-   CE D5 CD    DEC   $CDD5
1645-   C2          ???
1646-   C5 D2       CMP   $D2
1648-   8D AA 8D    STA   $8DAA
164B-   A0 CA       LDY   #$CA
164D-   D3          ???
164E-   D2 A0       CMP   ($A0)
1650-   C8          INY
1651-   CF          ???
1652-   CD C5 8D    CMP   $8DC5
1655-   A0 D0       LDY   #$D0
1657-   D2 CE       CMP   ($CE)
1659-   A0 A2       LDY   #$A2
165B-   D4          ???
165C-   C8          INY
165D-   C5 20       CMP   $20
165F-   D0 C4       BNE   $1625
1661-   CC 20 CD    CPY   $CD20
1664-   C1 C3       CMP   ($C3,X)
1666-   D2 CF       CMP   ($CF)
1668-   20 D2 C5    JSR   $C5D2
166B-   C1 C4       CMP   ($C4,X)
166D-   D3          ???
166E-   20 D4 C8    JSR   $C8D4
1671-   C5 A2       CMP   $A2
1673-   AC B8 C4    LDY   $C4B8
1676-   8D A0 D0    STA   $D0A0
1679-   D2 CE       CMP   ($CE)
167B-   A0 A2       LDY   #$A2
167D-   C3          ???
167E-   D5 D2       CMP   $D2,X
1680-   D2 C5       CMP   ($C5)
1682-   CE D4 20    DEC   $20D4
1685-   D3          ???
1686-   D4          ???
1687-   C1 D4       CMP   ($D4,X)
1689-   C5 20       CMP   $20
168B-   CF          ???
168C-   C6 20       DEC   $20
168E-   D4          ???
168F-   C8          INY
1690-   C5 20       CMP   $20
1692-   D0 C1       BNE   $1655
1694-   C4 C4       CPY   $C4
1696-   CC C5 A2    CPY   $A2C5
1699-   AC B8 C4    LDY   $C4B8
169C-   8D A0 D0    STA   $D0A0
169F-   D2 CE       CMP   ($CE)
16A1-   A0 A2       LDY   #$A2
16A3-   C1 CE       CMP   ($CE,X)
16A5-   C4 20       CPY   $20
16A7-   D2 C5       CMP   ($C5)
16A9-   D4          ???
16AA-   D5 D2       CMP   $D2,X
16AC-   CE D3 20    DEC   $20D3
16AF-   D4          ???
16B0-   C8          INY
16B1-   C1 D4       CMP   ($D4,X)
16B3-   20 D3 D4    JSR   $D4D3
16B6-   C1 D4       CMP   ($D4,X)
16B8-   C5 A2       CMP   $A2
16BA-   AC B8 C4    LDY   $C4B8
16BD-   8D A0 D0    STA   $D0A0
16C0-   D2 CE       CMP   ($CE)
16C2-   A0 A2       LDY   #$A2
16C4-   C9 CE       CMP   #$CE
16C6-   20 AE D9    JSR   $D9AE
16C9-   AE A2 AC    LDX   $ACA2
16CC-   B8          CLV
16CD-   C4 B8       CPY   $B8
16CF-   C4 8D       CPY   $8D
16D1-   A0 D0       LDY   #$D0
16D3-   D2 CE       CMP   ($CE)
16D5-   A0 A2       LDY   #$A2
16D7-   CD CF D6    CMP   $D6CF
16DA-   C5 20       CMP   $20
16DC-   D4          ???
16DD-   C8          INY
16DE-   C5 20       CMP   $20
16E0-   D0 C1       BNE   $16A3
16E2-   C4 C4       CPY   $C4
16E4-   CC C5 20    CPY   $20C5
16E7-   C1 20       CMP   ($20,X)
16E9-   C2          ???
16EA-   C9 D4       CMP   #$D4
16EC-   20 D4 CF    JSR   $CFD4
16EF-   20 D3 C5    JSR   $C5D3
16F2-   C5 A2       CMP   $A2
16F4-   AC B8 C4    LDY   $C4B8
16F7-   8D A0 D0    STA   $D0A0
16FA-   D2 CE       CMP   ($CE)
16FC-   A0 A2       LDY   #$A2
16FE-   D4          ???
16FF-   C8          INY
1700-   C5 20       CMP   $20
1702-   D6 C1       DEC   $C1,X
1704-   CC D5 C5    CPY   $C5D5
1707-   20 CF C6    JSR   $C6CF
170A-   20 D9 20    JSR   $20D9
170D-   C3          ???
170E-   C8          INY
170F-   C1 CE       CMP   ($CE,X)
1711-   C7          ???
1712-   C5 AE       CMP   $AE
1714-   A2 AC       LDX   #$AC
1716-   B8          CLV
1717-   C4 B8       CPY   $B8
1719-   C4 8D       CPY   $8D
171B-   A0 D0       LDY   #$D0
171D-   D2 CE       CMP   ($CE)
171F-   A0 A2       LDY   #$A2
1721-   A8          TAY
1722-   D0 D2       BNE   $16F6
1724-   C5 D3       CMP   $D3
1726-   D3          ???
1727-   20 C1 20    JSR   $20C1
172A-   CB          ???
172B-   C5 D9       CMP   $D9
172D-   20 C6 C9    JSR   $C9C6
1730-   D2 D3       CMP   ($D3)
1732-   D4          ???
1733-   AC 20 D4    LDY   $D420
1736-   CF          ???
1737-   20 D3 D4    JSR   $D4D3
173A-   C1 D2       CMP   ($D2,X)
173C-   D4          ???
173D-   A9 A2       LDA   #$A2
173F-   8D A0 DF    STA   $DFA0
1742-   D7          ???
1743-   C1 C9       CMP   ($C9,X)
1745-   D4          ???
1746-   8D A0 CC    STA   $CCA0
1749-   C4 C1       CPY   $C1
174B-   A0 A3       LDY   #$A3
174D-   B0 8D       BCS   $16DC
174F-   A0 D3       LDY   #$D3
1751-   D4          ???
1752-   C1 A0       CMP   ($A0,X)
1754-   A4 B3       LDY   $B3
1756-   B0 B0       BCS   $1708
1758-   8D A0 CC    STA   $CCA0
175B-   C4 C1       CPY   $C1
175D-   A0 A3       LDY   #$A3
175F-   B0 8D       BCS   $16EE
1761-   A0 D3       LDY   #$D3
1763-   D4          ???
1764-   C1 A0       CMP   ($A0,X)
1766-   A4 B3       LDY   $B3
1768-   B1 B0       LDA   ($B0),Y
176A-   8D A0 CA    STA   $CAA0
176D-   D3          ???
176E-   D2 A0       CMP   ($A0)
1770-   C8          INY
1771-   CF          ???
1772-   CD C5 8D    CMP   $8DC5
1775-   D0 CC       BNE   $1743
1777-   D0 8D       BNE   $1706
1779-   A0 D0       LDY   #$D0
177B-   C4 CC       CPY   $CC
177D-   A0 B0       LDY   #$B0
177F-   8D A0 D4    STA   $D4A0
1782-   D9 C1 8D    CMP   $8DC1,Y
1785-   A0 CA       LDY   #$CA
1787-   D3          ???
1788-   D2 A0       CMP   ($A0)
178A-   C3          ???
178B-   CF          ???
178C-   D5 D4       CMP   $D4,X
178E-   B1 8D       LDA   ($8D),Y
1790-   A0 C9       LDY   #$C9
1792-   CE C3 A0    DEC   $A0C3
1795-   A4 B3       LDY   $B3
1797-   B0 B0       BCS   $1749
1799-   8D A0 CC    STA   $CCA0
179C-   C4 C1       CPY   $C1
179E-   A0 A4       LDY   #$A4
17A0-   B3          ???
17A1-   B0 B0       BCS   $1753
17A3-   8D A0 C3    STA   $C3A0
17A6-   CD D0 A0    CMP   $A0D0
17A9-   A3          ???
17AA-   B2 B5       LDA   ($B5)
17AC-   B5 8D       LDA   $8D,X
17AE-   A0 C2       LDY   #$C2
17B0-   CE C5 A0    DEC   $A0C5
17B3-   D0 CC       BNE   $1781
17B5-   D0 8D       BNE   $1744
17B7-   A0 C9       LDY   #$C9
17B9-   CE C3 A0    DEC   $A0C3
17BC-   A4 B3       LDY   $B3
17BE-   B1 B0       LDA   ($B0),Y
17C0-   8D A0 CC    STA   $CCA0
17C3-   C4 C1       CPY   $C1
17C5-   A0 A4       LDY   #$A4
17C7-   B3          ???
17C8-   B1 B0       LDA   ($B0),Y
17CA-   8D A0 C3    STA   $C3A0
17CD-   CD D0 A0    CMP   $A0D0
17D0-   A3          ???
17D1-   B4 8D       LDY   $8D,X
17D3-   A0 C2       LDY   #$C2
17D5-   C5 D1       CMP   $D1
17D7-   A0 D8       LDY   #$D8
17D9-   D0 CC       BNE   $17A7
17DB-   D0 8D       BNE   $176A
17DD-   A0 C2       LDY   #$C2
17DF-   CE C5 A0    DEC   $A0C5
17E2-   D0 CC       BNE   $17B0
17E4-   D0 8D       BNE   $1773
17E6-   D8          CLD
17E7-   D0 CC       BNE   $17B5
17E9-   D0 8D       BNE   $1778
17EB-   AA          TAX
17EC-   8D AA AA    STA   $AAAA
17EF-   20 CD C1    JSR   $C1CD
17F2-   C3          ???
17F3-   D2 CF       CMP   ($CF)
17F5-   BA          TSX
17F6-   20 D0 C2    JSR   $C2D0
17F9-   D8          CLD
17FA-   20 D0 C1    JSR   $C1D0
17FD-   C4 C4       CPY   $C4
17FF-   CC C5 DF    CPY   $DFC5
1802-   C2          ???
1803-   D5 D4       CMP   $D4,X
1805-   D4          ???
1806-   CF          ???
1807-   CE DF CE    DEC   $CEDF
180A-   D5 CD       CMP   $CD,X
180C-   C2          ???
180D-   C5 D2       CMP   $D2
180F-   8D AA 8D    STA   $8DAA
1812-   A0 CA       LDY   #$CA
1814-   D3          ???
1815-   D2 A0       CMP   ($A0)
1817-   C8          INY
1818-   CF          ???
1819-   CD C5 8D    CMP   $8DC5
181C-   A0 D0       LDY   #$D0
181E-   D2 CE       CMP   ($CE)
1820-   A0 A2       LDY   #$A2
1822-   D4          ???
1823-   C8          INY
1824-   C5 20       CMP   $20
1826-   D0 C2       BNE   $17EA
1828-   D8          CLD
1829-   20 CD C1    JSR   $C1CD
182C-   C3          ???
182D-   D2 CF       CMP   ($CF)
182F-   20 D2 C5    JSR   $C5D2
1832-   D4          ???
1833-   D5 D2       CMP   $D2,X
1835-   CE D3 20    DEC   $20D3
1838-   B1 20       LDA   ($20),Y
183A-   C9 CE       CMP   #$CE
183C-   D4          ???
183D-   CF          ???
183E-   A2 AC       LDX   #$AC
1840-   B8          CLV
1841-   C4 8D       CPY   $8D
1843-   A0 D0       LDY   #$D0
1845-   D2 CE       CMP   ($CE)
1847-   A0 A2       LDY   #$A2
1849-   D4          ???
184A-   C8          INY
184B-   C5 20       CMP   $20
184D-   C1 C3       CMP   ($C3,X)
184F-   C3          ???
1850-   D5 CD       CMP   $CD,X
1852-   D5 CC       CMP   $CC,X
1854-   C1 D4       CMP   ($D4,X)
1856-   CF          ???
1857-   D2 20       CMP   ($20)
1859-   C9 C6       CMP   #$C6
185B-   20 D4 C8    JSR   $C8D4
185E-   C5 20       CMP   $20
1860-   D0 D2       BNE   $1834
1862-   CF          ???
1863-   CD D0 D4    CMP   $D4D0
1866-   C5 C4       CMP   $C4
1868-   A2 AC       LDX   #$AC
186A-   B8          CLV
186B-   C4 8D       CPY   $8D
186D-   A0 D0       LDY   #$D0
186F-   D2 CE       CMP   ($CE)
1871-   A0 A2       LDY   #$A2
1873-   D0 C1       BNE   $1836
1875-   C4 C4       CPY   $C4
1877-   CC C5 20    CPY   $20C5
187A-   C2          ???
187B-   D5 D4       CMP   $D4,X
187D-   D4          ???
187E-   CF          ???
187F-   CE 20 C9    DEC   $C920
1882-   D3          ???
1883-   20 D0 D2    JSR   $D2D0
1886-   C5 D3       CMP   $D3
1888-   D3          ???
1889-   C5 C4       CMP   $C4
188B-   AE 20 D4    LDX   $D420
188E-   C8          INY
188F-   C9 D3       CMP   #$D3
1891-   A2 AC       LDX   #$AC
1893-   B8          CLV
1894-   C4 8D       CPY   $8D
1896-   A0 D0       LDY   #$D0
1898-   D2 CE       CMP   ($CE)
189A-   A0 A2       LDY   #$A2
189C-   C9 D3       CMP   #$D3
189E-   20 D5 D3    JSR   $D3D5
18A1-   D5 C1       CMP   $C1,X
18A3-   CC CC D9    CPY   $D9CC
18A6-   20 D0 C2    JSR   $C2D0
18A9-   B0 20       BCS   $18CB
18AB-   CF          ???
18AC-   D2 20       CMP   ($20)
18AE-   D0 C2       BNE   $1872
18B0-   B1 AE       LDA   ($AE),Y
18B2-   20 D4 C8    JSR   $C8D4
18B5-   C5 A2       CMP   $A2
18B7-   AC B8 C4    LDY   $C4B8
18BA-   8D A0 D0    STA   $D0A0
18BD-   D2 CE       CMP   ($CE)
18BF-   A0 A2       LDY   #$A2
18C1-   C1 D0       CMP   ($D0,X)
18C3-   D0 CC       BNE   $1891
18C5-   C5 20       CMP   $20
18C7-   CB          ???
18C8-   C5 D9       CMP   $D9
18CA-   D3          ???
18CB-   20 C1 D2    JSR   $D2C1
18CE-   C5 20       CMP   $20
18D0-   C1 CC       CMP   ($CC,X)
18D2-   D3          ???
18D3-   CF          ???
18D4-   20 CD C1    JSR   $C1CD
18D7-   D0 D0       BNE   $18A9
18D9-   C5 C4       CMP   $C4
18DB-   20 C8 C5    JSR   $C5C8
18DE-   D2 C5       CMP   ($C5)
18E0-   AE A2 AC    LDX   $ACA2
18E3-   B8          CLV
18E4-   C4 8D       CPY   $8D
18E6-   A0 D0       LDY   #$D0
18E8-   D2 CE       CMP   ($CE)
18EA-   A0 A2       LDY   #$A2
18EC-   D0 D2       BNE   $18C0
18EE-   C5 D3       CMP   $D3
18F0-   D3          ???
18F1-   20 D0 C1    JSR   $C1D0
18F4-   C4 C4       CPY   $C4
18F6-   CC C5 20    CPY   $20C5
18F9-   C2          ???
18FA-   D5 D4       CMP   $D4,X
18FC-   D4          ???
18FD-   CF          ???
18FE-   CE 20 DA    DEC   $DA20
1901-   C5 D2       CMP   $D2
1903-   CF          ???
1904-   20 CF D2    JSR   $D2CF
1907-   20 CF D0    JSR   $D0CF
190A-   C5 CE       CMP   $CE
190C-   A2 AC       LDX   #$AC
190E-   B8          CLV
190F-   C4 8D       CPY   $8D
1911-   A0 D0       LDY   #$D0
1913-   D2 CE       CMP   ($CE)
1915-   A0 A2       LDY   #$A2
1917-   C1 D0       CMP   ($D0,X)
1919-   D0 CC       BNE   $18E7
191B-   C5 20       CMP   $20
191D-   D4          ???
191E-   CF          ???
191F-   20 C3 CF    JSR   $CFC3
1922-   CE D4 C9    DEC   $C9D4
1925-   CE D5 C5    DEC   $C5D5
1928-   AE A2 8D    LDX   $8DA2
192B-   A0 CC       LDY   #$CC
192D-   C4 C1       CPY   $C1
192F-   A0 A3       LDY   #$A3
1931-   B0 8D       BCS   $18C0
1933-   D0 C2       BNE   $18F7
1935-   CC D0 8D    CPY   $8DD0
1938-   A0 D0       LDY   #$D0
193A-   C2          ???
193B-   D8          CLD
193C-   A0 D0       LDY   #$D0
193E-   C2          ???
193F-   B0 8D       BCS   $18CE
1941-   A0 C3       LDY   #$C3
1943-   CD D0 A0    CMP   $A0D0
1946-   A3          ???
1947-   B1 8D       LDA   ($8D),Y
1949-   A0 C2       LDY   #$C2
194B-   CE C5 A0    DEC   $A0C5
194E-   D0 C2       BNE   $1912
1950-   CC D0 8D    CPY   $8DD0
1953-   AA          TAX
1954-   8D AA AA    STA   $AAAA
1957-   20 CD C1    JSR   $C1CD
195A-   C3          ???
195B-   D2 CF       CMP   ($CF)
195D-   BA          TSX
195E-   20 D4 D6    JSR   $D6D4
1961-   CC C9 CE    CPY   $CEC9
1964-   20 D9 DF    JSR   $DFD9
1967-   D3          ???
1968-   D4          ???
1969-   C1 D2       CMP   ($D2,X)
196B-   D4          ???
196C-   BB          ???
196D-   D9 DF C5    CMP   $C5DF,Y
1970-   CE C4 BB    DEC   $BBC4
1973-   D8          CLD
1974-   DF          ???
1975-   D0 CF       BNE   $1946
1977-   D3          ???
1978-   C9 D4       CMP   #$D4
197A-   C9 CF       CMP   #$CF
197C-   CE BB C6    DEC   $C6BB
197F-   C9 CC       CMP   #$CC
1981-   CC DF C3    CPY   $C3DF
1984-   C8          INY
1985-   C1 D2       CMP   ($D2,X)
1987-   8D AA AA    STA   $AAAA
198A-   20 20 20    JSR   $2020
198D-   20 20 20    JSR   $2020
1990-   20 20 D4    JSR   $D420
1993-   C8          INY
1994-   CC C9 CE    CPY   $CEC9
1997-   20 D8 DF    JSR   $DFD8
199A-   D3          ???
199B-   D4          ???
199C-   C1 D2       CMP   ($D2,X)
199E-   D4          ???
199F-   BB          ???
19A0-   D8          CLD
19A1-   DF          ???
19A2-   C5 CE       CMP   $CE
19A4-   C4 BB       CPY   $BB
19A6-   D9 DF D0    CMP   $D0DF,Y
19A9-   CF          ???
19AA-   D3          ???
19AB-   C9 D4       CMP   #$D4
19AD-   C9 CF       CMP   #$CF
19AF-   CE BB C6    DEC   $C6BB
19B2-   C9 CC       CMP   #$CC
19B4-   CC DF C3    CPY   $C3DF
19B7-   C8          INY
19B8-   C1 D2       CMP   ($D2,X)
19BA-   8D AA 8D    STA   $8DAA
19BD-   AA          TAX
19BE-   AA          TAX
19BF-   20 20 20    JSR   $2020
19C2-   20 20 20    JSR   $2020
19C5-   20 20 D4    JSR   $D420
19C8-   C6 C9       DEC   $C9
19CA-   CC CC 20    CPY   $20CC
19CD-   D8          CLD
19CE-   DF          ???
19CF-   D3          ???
19D0-   D4          ???
19D1-   C1 D2       CMP   ($D2,X)
19D3-   D4          ???
19D4-   BB          ???
19D5-   D8          CLD
19D6-   DF          ???
19D7-   C5 CE       CMP   $CE
19D9-   C4 BB       CPY   $BB
19DB-   D9 DF D3    CMP   $D3DF,Y
19DE-   D4          ???
19DF-   C1 D2       CMP   ($D2,X)
19E1-   D4          ???
19E2-   BB          ???
19E3-   D9 DF C5    CMP   $C5DF,Y
19E6-   CE C4 CC    DEC   $CCC4
19E9-   C6 C9       DEC   $C9
19EB-   CC CC DF    CPY   $DFCC
19EE-   C3          ???
19EF-   C8          INY
19F0-   C1 D2       CMP   ($D2,X)
19F2-   8D AA 8D    STA   $8DAA
19F5-   A0 CA       LDY   #$CA
19F7-   D3          ???
19F8-   D2 A0       CMP   ($A0)
19FA-   C8          INY
19FB-   CF          ???
19FC-   CD C5 8D    CMP   $8DC5
19FF-   A0 D0       LDY   #$D0
1A01-   D2 CE       CMP   ($CE)
1A03-   A0 A2       LDY   #$A2
1A05-   D4          ???
1A06-   D6 CC       DEC   $CC,X
1A08-   C9 CE       CMP   #$CE
1A0A-   20 C3 D2    JSR   $D2C3
1A0D-   C5 C1       CMP   $C1
1A0F-   D4          ???
1A10-   C5 D3       CMP   $D3
1A12-   20 C1 20    JSR   $20C1
1A15-   D6 C5       DEC   $C5,X
1A17-   D2 D4       CMP   ($D4)
1A19-   C9 C3       CMP   #$C3
1A1B-   C1 CC       CMP   ($CC,X)
1A1D-   20 CC C9    JSR   $C9CC
1A20-   CE C5 A2    DEC   $A2C5
1A23-   AC B8 C4    LDY   $C4B8
1A26-   8D A0 D0    STA   $D0A0
1A29-   D2 CE       CMP   ($CE)
1A2B-   A0 A2       LDY   #$A2
1A2D-   CF          ???
1A2E-   C6 20       DEC   $20
1A30-   D4          ???
1A31-   C5 D8       CMP   $D8
1A33-   D4          ???
1A34-   AC 20 D7    LDY   $D720
1A37-   C8          INY
1A38-   C9 CC       CMP   #$CC
1A3A-   C5 20       CMP   $20
1A3C-   D4          ???
1A3D-   C8          INY
1A3E-   CC C9 CE    CPY   $CEC9
1A41-   20 C3 D2    JSR   $D2C3
1A44-   C5 C1       CMP   $C1
1A46-   D4          ???
1A47-   C5 D3       CMP   $D3
1A49-   A2 AC       LDX   #$AC
1A4B-   B8          CLV
1A4C-   C4 8D       CPY   $8D
1A4E-   A0 D0       LDY   #$D0
1A50-   D2 CE       CMP   ($CE)
1A52-   A0 A2       LDY   #$A2
1A54-   C1 20       CMP   ($20,X)
1A56-   C8          INY
1A57-   CF          ???
1A58-   D2 C9       CMP   ($C9)
1A5A-   DA          PHX
1A5B-   CF          ???
1A5C-   CE D4 C1    DEC   $C1D4
1A5F-   CC 20 CC    CPY   $CC20
1A62-   C9 CE       CMP   #$CE
1A64-   C5 20       CMP   $20
1A66-   CF          ???
1A67-   C6 20       DEC   $20
1A69-   D4          ???
1A6A-   C5 D8       CMP   $D8
1A6C-   D4          ???
1A6D-   AE 20 D9    LDX   $D920
1A70-   CF          ???
1A71-   D5 A2       CMP   $A2,X
1A73-   AC B8 C4    LDY   $C4B8
1A76-   8D A0 D0    STA   $D0A0
1A79-   D2 CE       CMP   ($CE)
1A7B-   A0 A2       LDY   #$A2
1A7D-   D3          ???
1A7E-   D0 C5       BNE   $1A45
1A80-   C3          ???
1A81-   C9 C6       CMP   #$C6
1A83-   D9 20 D4    CMP   $D420,Y
1A86-   C8          INY
1A87-   C5 20       CMP   $20
1A89-   C3          ???
1A8A-   CF          ???
1A8B-   CF          ???
1A8C-   D2 C4       CMP   ($C4)
1A8E-   D3          ???
1A8F-   20 AF 20    JSR   $20AF
1A92-   C6 C9       DEC   $C9
1A94-   CC CC 20    CPY   $20CC
1A97-   C3          ???
1A98-   C8          INY
1A99-   C1 D2       CMP   ($D2,X)
1A9B-   AE A2 AC    LDX   $ACA2
1A9E-   B8          CLV
1A9F-   C4 B8       CPY   $B8
1AA1-   C4 8D       CPY   $8D
1AA3-   A0 D4       LDY   #$D4
1AA5-   D6 CC       DEC   $CC,X
1AA7-   C9 CE       CMP   #$CE
1AA9-   A0 A3       LDY   #$A3
1AAB-   B0 B8       BCS   $1A65
1AAD-   BB          ???
1AAE-   A3          ???
1AAF-   B1 B8       LDA   ($B8),Y
1AB1-   BB          ???
1AB2-   A3          ???
1AB3-   B1 B0       LDA   ($B0),Y
1AB5-   BB          ???
1AB6-   A3          ???
1AB7-   A4 C1       LDY   $C1
1AB9-   C1 8D       CMP   ($8D,X)
1ABB-   A0 DF       LDY   #$DF
1ABD-   D7          ???
1ABE-   C1 C9       CMP   ($C9,X)
1AC0-   D4          ???
1AC1-   8D A0 D4    STA   $D4A0
1AC4-   C8          INY
1AC5-   CC C9 CE    CPY   $CEC9
1AC8-   A0 A3       LDY   #$A3
1ACA-   B1 B0       LDA   ($B0),Y
1ACC-   BB          ???
1ACD-   A3          ???
1ACE-   B3          ???
1ACF-   B0 BB       BCS   $1A8C
1AD1-   A3          ???
1AD2-   B0 B8       BCS   $1A8C
1AD4-   BB          ???
1AD5-   A3          ???
1AD6-   A4 C1       LDY   $C1
1AD8-   C1 8D       CMP   ($8D,X)
1ADA-   A0 DF       LDY   #$DF
1ADC-   D7          ???
1ADD-   C1 C9       CMP   ($C9,X)
1ADF-   D4          ???
1AE0-   8D A0 D4    STA   $D4A0
1AE3-   D6 CC       DEC   $CC,X
1AE5-   C9 CE       CMP   #$CE
1AE7-   A0 A3       LDY   #$A3
1AE9-   B8          CLV
1AEA-   BB          ???
1AEB-   A3          ???
1AEC-   B1 B8       LDA   ($B8),Y
1AEE-   BB          ???
1AEF-   A3          ???
1AF0-   B3          ???
1AF1-   B0 BB       BCS   $1AAE
1AF3-   A3          ???
1AF4-   A4 C1       LDY   $C1
1AF6-   C1 8D       CMP   ($8D,X)
1AF8-   A0 D4       LDY   #$D4
1AFA-   C8          INY
1AFB-   CC C9 CE    CPY   $CEC9
1AFE-   A0 A3       LDY   #$A3
1B00-   B1 B0       LDA   ($B0),Y
1B02-   BB          ???
1B03-   A3          ???
1B04-   B3          ???
1B05-   B1 BB       LDA   ($BB),Y
1B07-   A3          ???
1B08-   B1 B7       LDA   ($B7),Y
1B0A-   BB          ???
1B0B-   A3          ???
1B0C-   A4 C1       LDY   $C1
1B0E-   C1 8D       CMP   ($8D,X)
1B10-   A0 DF       LDY   #$DF
1B12-   D7          ???
1B13-   C1 C9       CMP   ($C9,X)
1B15-   D4          ???
1B16-   8D A0 D4    STA   $D4A0
1B19-   C8          INY
1B1A-   CC C9 CE    CPY   $CEC9
1B1D-   A0 A3       LDY   #$A3
1B1F-   B0 BB       BCS   $1ADC
1B21-   A3          ???
1B22-   B3          ???
1B23-   B9 BB A3    LDA   $A3BB,Y
1B26-   B0 BB       BCS   $1AE3
1B28-   A3          ???
1B29-   A4 C1       LDY   $C1
1B2B-   C1 8D       CMP   ($8D,X)
1B2D-   A0 D4       LDY   #$D4
1B2F-   D6 CC       DEC   $CC,X
1B31-   C9 CE       CMP   #$CE
1B33-   A0 A3       LDY   #$A3
1B35-   B0 BB       BCS   $1AF2
1B37-   A3          ???
1B38-   B2 B3       LDA   ($B3)
1B3A-   BB          ???
1B3B-   A3          ???
1B3C-   B0 BB       BCS   $1AF9
1B3E-   A3          ???
1B3F-   A4 C1       LDY   $C1
1B41-   C1 8D       CMP   ($8D,X)
1B43-   A0 D4       LDY   #$D4
1B45-   C8          INY
1B46-   CC C9 CE    CPY   $CEC9
1B49-   A0 A3       LDY   #$A3
1B4B-   B0 BB       BCS   $1B08
1B4D-   A3          ???
1B4E-   B3          ???
1B4F-   B9 BB A3    LDA   $A3BB,Y
1B52-   B2 B3       LDA   ($B3)
1B54-   BB          ???
1B55-   A3          ???
1B56-   A4 C1       LDY   $C1
1B58-   C1 8D       CMP   ($8D,X)
1B5A-   A0 D4       LDY   #$D4
1B5C-   D6 CC       DEC   $CC,X
1B5E-   C9 CE       CMP   #$CE
1B60-   A0 A3       LDY   #$A3
1B62-   B0 B0       BCS   $1B14
1B64-   BB          ???
1B65-   A3          ???
1B66-   B2 B3       LDA   ($B3)
1B68-   BB          ???
1B69-   A3          ???
1B6A-   B3          ???
1B6B-   B9 BB A3    LDA   $A3BB,Y
1B6E-   A4 C1       LDY   $C1
1B70-   C1 8D       CMP   ($8D,X)
1B72-   A0 DF       LDY   #$DF
1B74-   D7          ???
1B75-   C1 C9       CMP   ($C9,X)
1B77-   D4          ???
1B78-   8D A0 D4    STA   $D4A0
1B7B-   C6 C9       DEC   $C9
1B7D-   CC CC A0    CPY   $A0CC
1B80-   A3          ???
1B81-   B0 BB       BCS   $1B3E
1B83-   A3          ???
1B84-   B0 BB       BCS   $1B41
1B86-   A3          ???
1B87-   B3          ???
1B88-   B9 BB A3    LDA   $A3BB,Y
1B8B-   B2 B3       LDA   ($B3)
1B8D-   BB          ???
1B8E-   A3          ???
1B8F-   A4 C1       LDY   $C1
1B91-   C1 8D       CMP   ($8D,X)
1B93-   A0 DF       LDY   #$DF
1B95-   D7          ???
1B96-   C1 C9       CMP   ($C9,X)
1B98-   D4          ???
1B99-   8D 20 A0    STA   $A020
1B9C-   D4          ???
1B9D-   C6 C9       DEC   $C9
1B9F-   CC CC 20    CPY   $20CC
1BA2-   A3          ???
1BA3-   B1 B0       LDA   ($B0),Y
1BA5-   BB          ???
1BA6-   A3          ???
1BA7-   B5 BB       LDA   $BB,X
1BA9-   A3          ???
1BAA-   B3          ???
1BAB-   B0 BB       BCS   $1B68
1BAD-   A3          ???
1BAE-   B1 B7       LDA   ($B7),Y
1BB0-   BB          ???
1BB1-   A3          ???
1BB2-   A4 C1       LDY   $C1
1BB4-   B0 8D       BCS   $1B43
1BB6-   A0 DF       LDY   #$DF
1BB8-   D7          ???
1BB9-   C1 C9       CMP   ($C9,X)
1BBB-   D4          ???
1BBC-   8D A0 D3    STA   $D3A0
1BBF-   C3          ???
1BC0-   D0 CF       BNE   $1B91
1BC2-   D3          ???
1BC3-   A0 A3       LDY   #$A3
1BC5-   B1 B2       LDA   ($B2),Y
1BC7-   BB          ???
1BC8-   A3          ???
1BC9-   B7          ???
1BCA-   8D A0 D0    STA   $D0A0
1BCD-   D2 CE       CMP   ($CE)
1BCF-   A0 A2       LDY   #$A2
1BD1-   C1 CE       CMP   ($CE,X)
1BD3-   C4 20       CPY   $20
1BD5-   D4          ???
1BD6-   C6 C9       DEC   $C9
1BD8-   CC CC 20    CPY   $20CC
1BDB-   C6 C9       DEC   $C9
1BDD-   CC CC D3    CPY   $D3CC
1BE0-   20 C1 A2    JSR   $A2C1
1BE3-   AC B8 C4    LDY   $C4B8
1BE6-   8D A0 D3    STA   $D3A0
1BE9-   C3          ???
1BEA-   D0 CF       BNE   $1BBB
1BEC-   D3          ???
1BED-   A0 A3       LDY   #$A3
1BEF-   B1 B2       LDA   ($B2),Y
1BF1-   BB          ???
1BF2-   A3          ???
1BF3-   B9 8D A0    LDA   $A08D,Y
1BF6-   D0 D2       BNE   $1BCA
1BF8-   CE A0 A2    DEC   $A2A0
1BFB-   C7          ???
1BFC-   C9 D6       CMP   #$D6
1BFE-   C5 CE       CMP   $CE
1C00-   20 C1 D2    JSR   $D2C1
1C03-   C5 C1       CMP   $C1
1C05-   20 D7 C9    JSR   $C9D7
1C08-   D4          ???
1C09-   C8          INY
1C0A-   A2 8D       LDX   #$8D
1C0C-   A0 D3       LDY   #$D3
1C0E-   C3          ???
1C0F-   D0 CF       BNE   $1BE0
1C11-   D3          ???
1C12-   A0 A3       LDY   #$A3
1C14-   B1 B2       LDA   ($B2),Y
1C16-   BB          ???
1C17-   A3          ???
1C18-   B1 B1       LDA   ($B1),Y
1C1A-   8D A0 D0    STA   $D0A0
1C1D-   D2 CE       CMP   ($CE)
1C1F-   A0 A2       LDY   #$A2
1C21-   C1 20       CMP   ($20,X)
1C23-   C6 C9       DEC   $C9
1C25-   CC CC 20    CPY   $20CC
1C28-   C3          ???
1C29-   C8          INY
1C2A-   C1 D2       CMP   ($D2,X)
1C2C-   A2 8D       LDX   #$8D
1C2E-   A0 DF       LDY   #$DF
1C30-   D7          ???
1C31-   C1 C9       CMP   ($C9,X)
1C33-   D4          ???
1C34-   8D A0 CA    STA   $CAA0
1C37-   D3          ???
1C38-   D2 A0       CMP   ($A0)
1C3A-   C8          INY
1C3B-   CF          ???
1C3C-   CD C5 8D    CMP   $8DC5
1C3F-   A0 D0       LDY   #$D0
1C41-   D2 CE       CMP   ($CE)
1C43-   A0 A2       LDY   #$A2
1C45-   CC C1 D3    CPY   $D3C1
1C48-   D4          ???
1C49-   CC D9 AC    CPY   $ACD9
1C4C-   20 D4 C8    JSR   $C8D4
1C4F-   C5 20       CMP   $20
1C51-   D4          ???
1C52-   D0 D5       BNE   $1C29
1C54-   D4          ???
1C55-   20 CD C1    JSR   $C1CD
1C58-   C3          ???
1C59-   D2 CF       CMP   ($CF)
1C5B-   20 D3 C9    JSR   $C9D3
1C5E-   CD D0 CC    CMP   $CCD0
1C61-   D9 A2 AC    CMP   $ACA2,Y
1C64-   B8          CLV
1C65-   C4 8D       CPY   $8D
1C67-   A0 D0       LDY   #$D0
1C69-   D2 CE       CMP   ($CE)
1C6B-   A0 A2       LDY   #$A2
1C6D-   D0 CC       BNE   $1C3B
1C6F-   CF          ???
1C70-   D4          ???
1C71-   D3          ???
1C72-   20 C1 20    JSR   $20C1
1C75-   C7          ???
1C76-   C9 D6       CMP   #$D6
1C78-   C5 CE       CMP   $CE
1C7A-   20 C3 C8    JSR   $C8C3
1C7D-   C1 D2       CMP   ($D2,X)
1C7F-   C1 C3       CMP   ($C3,X)
1C81-   D4          ???
1C82-   C5 D2       CMP   $D2
1C84-   20 D4 CF    JSR   $CFD4
1C87-   20 D4 C8    JSR   $C8D4
1C8A-   C5 A2       CMP   $A2
1C8C-   AC B8 C4    LDY   $C4B8
1C8F-   8D A0 D0    STA   $D0A0
1C92-   D2 CE       CMP   ($CE)
1C94-   A0 A2       LDY   #$A2
1C96-   D3          ???
1C97-   C3          ???
1C98-   D2 C5       CMP   ($C5)
1C9A-   C5 CE       CMP   $CE
1C9C-   20 D6 C9    JSR   $C9D6
1C9F-   C1 20       CMP   ($20,X)
1CA1-   C4 C9       CPY   $C9
1CA3-   D2 C5       CMP   ($C5)
1CA5-   C3          ???
1CA6-   D4          ???
1CA7-   20 CD C5    JSR   $C5CD
1CAA-   CD CF D2    CMP   $D2CF
1CAD-   D9 20 C1    CMP   $C120,Y
1CB0-   C3          ???
1CB1-   C3          ???
1CB2-   C5 D3       CMP   $D3
1CB4-   D3          ???
1CB5-   AE A2 8D    LDX   $8DA2
1CB8-   A0 D0       LDY   #$D0
1CBA-   D2 CE       CMP   ($CE)
1CBC-   A0 A2       LDY   #$A2
1CBE-   20 A2 AC    JSR   $ACA2
1CC1-   B8          CLV
1CC2-   C4 B8       CPY   $B8
1CC4-   C4 8D       CPY   $8D
1CC6-   A0 DF       LDY   #$DF
1CC8-   D7          ???
1CC9-   C1 C9       CMP   ($C9,X)
1CCB-   D4          ???
1CCC-   8D A0 D4    STA   $D4A0
1CCF-   D0 D5       BNE   $1CA6
1CD1-   D4          ???
1CD2-   A0 A3       LDY   #$A3
1CD4-   B1 B0       LDA   ($B0),Y
1CD6-   BB          ???
1CD7-   A3          ???
1CD8-   B1 B0       LDA   ($B0),Y
1CDA-   BB          ???
1CDB-   A3          ???
1CDC-   A4 C1       LDY   $C1
1CDE-   C1 8D       CMP   ($8D,X)
1CE0-   A0 D4       LDY   #$D4
1CE2-   D0 D5       BNE   $1CB9
1CE4-   D4          ???
1CE5-   A0 A3       LDY   #$A3
1CE7-   B1 B1       LDA   ($B1),Y
1CE9-   BB          ???
1CEA-   A3          ???
1CEB-   B1 B1       LDA   ($B1),Y
1CED-   BB          ???
1CEE-   A3          ???
1CEF-   A4 C1       LDY   $C1
1CF1-   C1 8D       CMP   ($8D,X)
1CF3-   A0 D4       LDY   #$D4
1CF5-   D0 D5       BNE   $1CCC
1CF7-   D4          ???
1CF8-   A0 A3       LDY   #$A3
1CFA-   B1 B2       LDA   ($B2),Y
1CFC-   BB          ???
1CFD-   A3          ???
1CFE-   B1 B2       LDA   ($B2),Y
1D00-   BB          ???
1D01-   A3          ???
1D02-   A4 C1       LDY   $C1
1D04-   C1 8D       CMP   ($8D,X)
1D06-   A0 D4       LDY   #$D4
1D08-   D0 D5       BNE   $1CDF
1D0A-   D4          ???
1D0B-   A0 A3       LDY   #$A3
1D0D-   B1 B3       LDA   ($B3),Y
1D0F-   BB          ???
1D10-   A3          ???
1D11-   B1 B3       LDA   ($B3),Y
1D13-   BB          ???
1D14-   A3          ???
1D15-   A4 C1       LDY   $C1
1D17-   C1 8D       CMP   ($8D,X)
1D19-   A0 D4       LDY   #$D4
1D1B-   D0 D5       BNE   $1CF2
1D1D-   D4          ???
1D1E-   A0 A3       LDY   #$A3
1D20-   B1 B4       LDA   ($B4),Y
1D22-   BB          ???
1D23-   A3          ???
1D24-   B1 B4       LDA   ($B4),Y
1D26-   BB          ???
1D27-   A3          ???
1D28-   A4 C1       LDY   $C1
1D2A-   C1 8D       CMP   ($8D,X)
1D2C-   A0 DF       LDY   #$DF
1D2E-   D7          ???
1D2F-   C1 C9       CMP   ($C9,X)
1D31-   D4          ???
1D32-   8D A0 CA    STA   $CAA0
1D35-   D3          ???
1D36-   D2 A0       CMP   ($A0)
1D38-   C8          INY
1D39-   CF          ???
1D3A-   CD C5 8D    CMP   $8DC5
1D3D-   A0 D0       LDY   #$D0
1D3F-   D2 CE       CMP   ($CE)
1D41-   A0 A2       LDY   #$A2
1D43-   C6 C9       DEC   $C9
1D45-   CE AE A2    DEC   $A2AE
1D48-   AC B8 C4    LDY   $C4B8
1D4B-   B8          CLV
1D4C-   C4 B8       CPY   $B8
1D4E-   C4 8D       CPY   $8D
1D50-   20 A0 D4    JSR   $D4A0
1D53-   D0 D5       BNE   $1D2A
1D55-   D4          ???
1D56-   A0 A3       LDY   #$A3
1D58-   B3          ???
1D59-   B9 BB A3    LDA   $A3BB,Y
1D5C-   B2 B3       LDA   ($B3)
1D5E-   BB          ???
1D5F-   A3          ???
1D60-   A4 C1       LDY   $C1
1D62-   C1 8D       CMP   ($8D,X)
1D64-   AA          TAX
1D65-   8D A0 CA    STA   $CAA0
1D68-   CD D0 A0    CMP   $A0D0
1D6B-   D2 C5       CMP   ($C5)
1D6D-   C5 CE       CMP   $CE
1D6F-   D4          ???
1D70-   D2 D9       CMP   ($D9)
1D72-   8D AA 8D    STA   $8DAA
1D75-   AA          TAX
1D76-   E0 E0       CPX   #$E0
1D78-   E0 E0       CPX   #$E0
1D7A-   E0 E0       CPX   #$E0
1D7C-   E0 E0       CPX   #$E0
1D7E-   E0 E0       CPX   #$E0
1D80-   E0 E0       CPX   #$E0
1D82-   E0 E0       CPX   #$E0
1D84-   E0 E0       CPX   #$E0
1D86-   E0 E0       CPX   #$E0
1D88-   E0 E0       CPX   #$E0
1D8A-   E0 E0       CPX   #$E0
1D8C-   E0 E0       CPX   #$E0
1D8E-   E0 E0       CPX   #$E0
1D90-   E0 E0       CPX   #$E0
1D92-   E0 E0       CPX   #$E0
1D94-   AA          TAX
1D95-   8D AA 20    STA   $20AA
1D98-   20 20 20    JSR   $2020
1D9B-   20 20 20    JSR   $2020
1D9E-   20 C2 CF    JSR   $CFC2
1DA1-   D4          ???
1DA2-   D4          ???
1DA3-   CF          ???
1DA4-   CD 20 C9    CMP   $C920
1DA7-   CE C3 CC    DEC   $CCC3
1DAA-   D5 C4       CMP   $C4,X
1DAC-   C5 D3       CMP   $D3
1DAE-   20 20 20    JSR   $2020
1DB1-   20 20 20    JSR   $2020
1DB4-   20 AA 8D    JSR   $8DAA
1DB7-   AA          TAX
1DB8-   AC AC AC    LDY   $ACAC
1DBB-   AC AC AC    LDY   $ACAC
1DBE-   AC AC AC    LDY   $ACAC
1DC1-   AC AC AC    LDY   $ACAC
1DC4-   AC AC AC    LDY   $ACAC
1DC7-   AC AC AC    LDY   $ACAC
1DCA-   AC AC AC    LDY   $ACAC
1DCD-   AC AC AC    LDY   $ACAC
1DD0-   AC AC AC    LDY   $ACAC
1DD3-   AC AC AC    LDY   $ACAC
1DD6-   AA          TAX
1DD7-   8D AA 8D    STA   $8DAA
1DDA-   A0 D0       LDY   #$D0
1DDC-   D5 D4       CMP   $D4,X
1DDE-   A0 D2       LDY   #$D2
1DE0-   C5 D1       CMP   $D1
1DE2-   D5 C9       CMP   $C9,X
1DE4-   D2 C5       CMP   ($C5)
1DE6-   C4 AE       CPY   $AE
1DE8-   CC C9 C2    CPY   $C2C9
1DEB-   AE CD C9    LDX   $C9CD
1DEE-   CE 8D AA    DEC   $AA8D
1DF1-   8D AA AA    STA   $AAAA
1DF4-   20 C9 CE    JSR   $CEC9
1DF7-   C4 C9       CPY   $C9
1DF9-   D6 C9       DEC   $C9,X
1DFB-   C4 D5       CPY   $D5
1DFD-   C1 CC       CMP   ($CC,X)
1DFF-   20 D3 D5    JSR   $D5D3
1E02-   C2          ???
1E03-   D2 CF       CMP   ($CF)
1E05-   D5 D4       CMP   $D4,X
1E07-   C9 CE       CMP   #$CE
1E09-   C5 20       CMP   $20
1E0B-   C9 CE       CMP   #$CE
1E0D-   C3          ???
1E0E-   CC D5 C4    CPY   $C4D5
1E11-   C5 D3       CMP   $D3
1E13-   8D AA 8D    STA   $8DAA
1E16-   AA          TAX
1E17-   20 20 D3    JSR   $D320
1E1A-   D4          ???
1E1B-   C4 C9       CPY   $C9
1E1D-   CF          ???
1E1E-   20 D3 D5    JSR   $D5D3
1E21-   C2          ???
1E22-   D2 CF       CMP   ($CF)
1E24-   D5 D4       CMP   $D4,X
1E26-   C9 CE       CMP   #$CE
1E28-   C5 D3       CMP   $D3
1E2A-   8D AA 8D    STA   $8DAA
1E2D-   A0 D0       LDY   #$D0
1E2F-   D5 D4       CMP   $D4,X
1E31-   A0 D8       LDY   #$D8
1E33-   D0 D2       BNE   $1E07
1E35-   C9 CE       CMP   #$CE
1E37-   D4          ???
1E38-   AE D3 D5    LDX   $D5D3
1E3B-   C2          ???
1E3C-   AE CD C9    LDX   $C9CD
1E3F-   CE 8D A0    DEC   $A08D
1E42-   D0 D5       BNE   $1E19
1E44-   D4          ???
1E45-   A0 C4       LDY   #$C4
1E47-   D0 D2       BNE   $1E1B
1E49-   C9 CE       CMP   #$CE
1E4B-   D4          ???
1E4C-   AE D3 D5    LDX   $D5D3
1E4F-   C2          ???
1E50-   AE CD C9    LDX   $C9CD
1E53-   CE 8D A0    DEC   $A08D
1E56-   D0 D5       BNE   $1E2D
1E58-   D4          ???
1E59-   A0 D4       LDY   #$D4
1E5B-   C8          INY
1E5C-   CC C9 CE    CPY   $CEC9
1E5F-   C5 AE       CMP   $AE
1E61-   D3          ???
1E62-   D5 C2       CMP   $C2,X
1E64-   AE CD C9    LDX   $C9CD
1E67-   CE 8D A0    DEC   $A08D
1E6A-   D0 D5       BNE   $1E41
1E6C-   D4          ???
1E6D-   A0 D4       LDY   #$D4
1E6F-   D6 CC       DEC   $CC,X
1E71-   C9 CE       CMP   #$CE
1E73-   C5 AE       CMP   $AE
1E75-   D3          ???
1E76-   D5 C2       CMP   $C2,X
1E78-   AE CD C9    LDX   $C9CD
1E7B-   CE 8D A0    DEC   $A08D
1E7E-   D0 D5       BNE   $1E55
1E80-   D4          ???
1E81-   A0 C3       LDY   #$C3
1E83-   D5 D2       CMP   $D2,X
1E85-   D3          ???
1E86-   CF          ???
1E87-   D2 D5       CMP   ($D5)
1E89-   C4 C2       CPY   $C2
1E8B-   C6 AE       DEC   $AE
1E8D-   D3          ???
1E8E-   D5 C2       CMP   $C2,X
1E90-   AE CD C9    LDX   $C9CD
1E93-   CE 8D A0    DEC   $A08D
1E96-   D0 D5       BNE   $1E6D
1E98-   D4          ???
1E99-   A0 D4       LDY   #$D4
1E9B-   C6 C9       DEC   $C9
1E9D-   CC CC C1    CPY   $C1CC
1EA0-   AE D3 D5    LDX   $D5D3
1EA3-   C2          ???
1EA4-   AE CD C9    LDX   $C9CD
1EA7-   CE 8D A0    DEC   $A08D
1EAA-   D0 D5       BNE   $1E81
1EAC-   D4          ???
1EAD-   A0 D3       LDY   #$D3
1EAF-   C9 CE       CMP   #$CE
1EB1-   D0 D5       BNE   $1E88
1EB3-   D4          ???
1EB4-   AE D3 D5    LDX   $D5D3
1EB7-   C2          ???
1EB8-   AE CD C9    LDX   $C9CD
1EBB-   CE 8D A0    DEC   $A08D
1EBE-   D0 D5       BNE   $1E95
1EC0-   D4          ???
1EC1-   A0 C7       LDY   #$C7
1EC3-   D0 C2       BNE   $1E87
1EC5-   D8          CLD
1EC6-   AE D3 D5    LDX   $D5D3
1EC9-   C2          ???
1ECA-   AE CD C9    LDX   $C9CD
1ECD-   CE 8D A0    DEC   $A08D
1ED0-   D0 D5       BNE   $1EA7
1ED2-   D4          ???
1ED3-   A0 D4       LDY   #$D4
1ED5-   D8          CLD
1ED6-   D4          ???
1ED7-   D0 D5       BNE   $1EAE
1ED9-   D4          ???
1EDA-   AE D3 D5    LDX   $D5D3
1EDD-   C2          ???
1EDE-   AE CD C9    LDX   $C9CD
1EE1-   CE 8D AA    DEC   $AA8D
1EE4-   8D 00 00    STA   $0000
