0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 CD    LDY   $CD20,X
0950-   C1 D4       CMP   ($D4,X)
0952-   C8          INY
0953-   20 20 C4    JSR   $C420
0956-   C5 CD       CMP   $CD
0958-   CF          ???
0959-   20 BE AD    JSR   $ADBE
095C-   20 20 20    JSR   $2020
095F-   20 20 20    JSR   $2020
0962-   20 20 AA    JSR   $AA20
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B2    JSR   $B220
09D4-   B0 AD       BCS   $0983
09D6-   CA          DEX
09D7-   C1 CE       CMP   ($CE,X)
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B8       LDA   ($B8),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 D4    STA   $D4A0
0B02-   D2 A0       CMP   ($A0)
0B04-   CF          ???
0B05-   CE 8D A0    DEC   $A08D
0B08-   C4 D3       CPY   $D3
0B0A-   CB          ???
0B0B-   A0 CD       LDY   #$CD
0B0D-   C1 D4       CMP   ($D4,X)
0B0F-   C8          INY
0B10-   AE C4 C5    LDX   $C5C4
0B13-   CD CF 8D    CMP   $8DCF
0B16-   A0 CF       LDY   #$CF
0B18-   C2          ???
0B19-   CA          DEX
0B1A-   A0 A4       LDY   #$A4
0B1C-   C2          ???
0B1D-   C6 C5       DEC   $C5
0B1F-   B0 8D       BCS   $0AAE
0B21-   A0 CF       LDY   #$CF
0B23-   D2 C7       CMP   ($C7)
0B25-   A0 A4       LDY   #$A4
0B27-   B6 B0       LDX   $B0,Y
0B29-   B0 B0       BCS   $0ADB
0B2B-   8D AA 8D    STA   $8DAA
0B2E-   AA          TAX
0B2F-   E0 E0       CPX   #$E0
0B31-   E0 E0       CPX   #$E0
0B33-   E0 E0       CPX   #$E0
0B35-   E0 E0       CPX   #$E0
0B37-   E0 E0       CPX   #$E0
0B39-   E0 E0       CPX   #$E0
0B3B-   E0 E0       CPX   #$E0
0B3D-   E0 E0       CPX   #$E0
0B3F-   E0 E0       CPX   #$E0
0B41-   E0 E0       CPX   #$E0
0B43-   E0 E0       CPX   #$E0
0B45-   E0 E0       CPX   #$E0
0B47-   E0 E0       CPX   #$E0
0B49-   E0 E0       CPX   #$E0
0B4B-   E0 E0       CPX   #$E0
0B4D-   AA          TAX
0B4E-   8D AA 20    STA   $20AA
0B51-   20 D4 CF    JSR   $CFD4
0B54-   D0 20       BNE   $0B76
0B56-   C9 CE       CMP   #$CE
0B58-   C3          ???
0B59-   CC D5 C4    CPY   $C4D5
0B5C-   C5 D3       CMP   $D3
0B5E-   20 A8 C8    JSR   $C8A8
0B61-   CF          ???
0B62-   CF          ???
0B63-   CB          ???
0B64-   D3          ???
0B65-   AC CD C1    LDY   $C1CD
0B68-   C3          ???
0B69-   D2 CF       CMP   ($CF)
0B6B-   D3          ???
0B6C-   A9 20       LDA   #$20
0B6E-   AA          TAX
0B6F-   8D AA AC    STA   $ACAA
0B72-   AC AC AC    LDY   $ACAC
0B75-   AC AC AC    LDY   $ACAC
0B78-   AC AC AC    LDY   $ACAC
0B7B-   AC AC AC    LDY   $ACAC
0B7E-   AC AC AC    LDY   $ACAC
0B81-   AC AC AC    LDY   $ACAC
0B84-   AC AC AC    LDY   $ACAC
0B87-   AC AC AC    LDY   $ACAC
0B8A-   AC AC AC    LDY   $ACAC
0B8D-   AC AC AA    LDY   $AAAC
0B90-   8D AA 8D    STA   $8DAA
0B93-   A0 D0       LDY   #$D0
0B95-   D5 D4       CMP   $D4,X
0B97-   A0 CD       LDY   #$CD
0B99-   C9 CE       CMP   #$CE
0B9B-   AE D6 C1    LDX   $C1D6
0B9E-   D2 D3       CMP   ($D3)
0BA0-   AE D2 C5    LDX   $C5D2
0BA3-   D1 D5       CMP   ($D5),Y
0BA5-   C9 D2       CMP   #$D2
0BA7-   C5 C4       CMP   $C4
0BA9-   8D A0 D0    STA   $D0A0
0BAC-   D5 D4       CMP   $D4,X
0BAE-   A0 CD       LDY   #$CD
0BB0-   C9 CE       CMP   #$CE
0BB2-   AE C8 CF    LDX   $CFC8
0BB5-   CF          ???
0BB6-   CB          ???
0BB7-   D3          ???
0BB8-   AE D2 C5    LDX   $C5D2
0BBB-   D1 D5       CMP   ($D5),Y
0BBD-   C9 D2       CMP   #$D2
0BBF-   C5 C4       CMP   $C4
0BC1-   8D A0 D5    STA   $D5A0
0BC4-   D3          ???
0BC5-   C5 A0       CMP   $A0
0BC7-   CD C9 CE    CMP   $CEC9
0BCA-   AE CD C1    LDX   $C1CD
0BCD-   C3          ???
0BCE-   AE D2 C5    LDX   $C5D2
0BD1-   D1 D5       CMP   ($D5),Y
0BD3-   C9 D2       CMP   #$D2
0BD5-   C5 C4       CMP   $C4
0BD7-   8D A0 D0    STA   $D0A0
0BDA-   D5 D4       CMP   $D4,X
0BDC-   A0 CD       LDY   #$CD
0BDE-   C9 CE       CMP   #$CE
0BE0-   AE C8 CF    LDX   $CFC8
0BE3-   CF          ???
0BE4-   CB          ???
0BE5-   D3          ???
0BE6-   AE CD C1    LDX   $C1CD
0BE9-   D4          ???
0BEA-   C8          INY
0BEB-   8D A0 D5    STA   $D5A0
0BEE-   D3          ???
0BEF-   C5 A0       CMP   $A0
0BF1-   CD C9 CE    CMP   $CEC9
0BF4-   AE CD C1    LDX   $C1CD
0BF7-   C3          ???
0BF8-   AE CD C1    LDX   $C1CD
0BFB-   D4          ???
0BFC-   C8          INY
0BFD-   8D AA 8D    STA   $8DAA
0C00-   AA          TAX
0C01-   E0 E0       CPX   #$E0
0C03-   E0 E0       CPX   #$E0
0C05-   E0 E0       CPX   #$E0
0C07-   E0 E0       CPX   #$E0
0C09-   E0 E0       CPX   #$E0
0C0B-   E0 E0       CPX   #$E0
0C0D-   E0 E0       CPX   #$E0
0C0F-   E0 E0       CPX   #$E0
0C11-   E0 E0       CPX   #$E0
0C13-   E0 E0       CPX   #$E0
0C15-   E0 E0       CPX   #$E0
0C17-   E0 E0       CPX   #$E0
0C19-   E0 E0       CPX   #$E0
0C1B-   E0 E0       CPX   #$E0
0C1D-   E0 E0       CPX   #$E0
0C1F-   AA          TAX
0C20-   8D AA 20    STA   $20AA
0C23-   20 20 20    JSR   $2020
0C26-   20 20 D0    JSR   $D020
0C29-   D2 CF       CMP   ($CF)
0C2B-   C7          ???
0C2C-   D2 C1       CMP   ($C1)
0C2E-   CD 20 CD    CMP   $CD20
0C31-   C1 C9       CMP   ($C9,X)
0C33-   CE 20 C2    DEC   $C220
0C36-   CF          ???
0C37-   C4 D9       CPY   $D9
0C39-   20 20 20    JSR   $2020
0C3C-   20 20 20    JSR   $2020
0C3F-   20 AA 8D    JSR   $8DAA
0C42-   AA          TAX
0C43-   AC AC AC    LDY   $ACAC
0C46-   AC AC AC    LDY   $ACAC
0C49-   AC AC AC    LDY   $ACAC
0C4C-   AC AC AC    LDY   $ACAC
0C4F-   AC AC AC    LDY   $ACAC
0C52-   AC AC AC    LDY   $ACAC
0C55-   AC AC AC    LDY   $ACAC
0C58-   AC AC AC    LDY   $ACAC
0C5B-   AC AC AC    LDY   $ACAC
0C5E-   AC AC AC    LDY   $ACAC
0C61-   AA          TAX
0C62-   8D AA 8D    STA   $8DAA
0C65-   A0 CA       LDY   #$CA
0C67-   D3          ???
0C68-   D2 A0       CMP   ($A0)
0C6A-   A4 C6       LDY   $C6
0C6C-   C3          ???
0C6D-   B5 B8       LDA   $B8,X
0C6F-   A0 BB       LDY   #$BB
0C71-   20 C8 CF    JSR   $CFC8
0C74-   CD C5 8D    CMP   $8DC5
0C77-   A0 DF       LDY   #$DF
0C79-   D0 D2       BNE   $0C4D
0C7B-   CE D4 A0    DEC   $A0D4
0C7E-   A2 C9       LDX   #$C9
0C80-   CE D4 C5    DEC   $C5D4
0C83-   C7          ???
0C84-   C5 D2       CMP   $D2
0C86-   20 CD C1    JSR   $C1CD
0C89-   D4          ???
0C8A-   C8          INY
0C8B-   20 CC C9    JSR   $C9CC
0C8E-   C2          ???
0C8F-   D2 C1       CMP   ($C1)
0C91-   D2 C9       CMP   ($C9)
0C93-   C5 D3       CMP   $D3
0C95-   20 C1 CE    JSR   $CEC1
0C98-   C4 A2       CPY   $A2
0C9A-   AC B8 C4    LDY   $C4B8
0C9D-   8D A0 DF    STA   $DFA0
0CA0-   D0 D2       BNE   $0C74
0CA2-   CE D4 A0    DEC   $A0D4
0CA5-   A2 CD       LDX   #$CD
0CA7-   C1 C3       CMP   ($C3,X)
0CA9-   D2 CF       CMP   ($CF)
0CAB-   D3          ???
0CAC-   AE 20 20    LDX   $2020
0CAF-   20 20 20    JSR   $2020
0CB2-   20 20 20    JSR   $2020
0CB5-   20 20 20    JSR   $2020
0CB8-   20 20 20    JSR   $2020
0CBB-   20 20 A2    JSR   $A220
0CBE-   AC B8 C4    LDY   $C4B8
0CC1-   8D A0 DF    STA   $DFA0
0CC4-   D0 D2       BNE   $0C98
0CC6-   CE D4 A0    DEC   $A0D4
0CC9-   A2 AD       LDX   #$AD
0CCB-   AD AD AD    LDA   $ADAD
0CCE-   AD AD AD    LDA   $ADAD
0CD1-   AD AD AD    LDA   $ADAD
0CD4-   AD AD AD    LDA   $ADAD
0CD7-   AD AD AD    LDA   $ADAD
0CDA-   AD AD AD    LDA   $ADAD
0CDD-   AD AD AD    LDA   $ADAD
0CE0-   AD AD AD    LDA   $ADAD
0CE3-   A2 AC       LDX   #$AC
0CE5-   B8          CLV
0CE6-   C4 B8       CPY   $B8
0CE8-   C4 8D       CPY   $8D
0CEA-   A0 DF       LDY   #$DF
0CEC-   D0 D2       BNE   $0CC0
0CEE-   CE D4 A0    DEC   $A0D4
0CF1-   A2 D4       LDX   #$D4
0CF3-   C8          INY
0CF4-   C5 20       CMP   $20
0CF6-   D2 C1       CMP   ($C1)
0CF8-   CE C4 B8    DEC   $B8C4
0CFB-   20 D2 CF    JSR   $CFD2
0CFE-   D5 D4       CMP   $D4,X
0D00-   C9 CE       CMP   #$CE
0D02-   C5 20       CMP   $20
0D04-   D2 C5       CMP   ($C5)
0D06-   D4          ???
0D07-   D5 D2       CMP   $D2,X
0D09-   CE D3 A2    DEC   $A2D3
0D0C-   AC B8 C4    LDY   $C4B8
0D0F-   8D A0 DF    STA   $DFA0
0D12-   D0 D2       BNE   $0CE6
0D14-   CE D4 A0    DEC   $A0D4
0D17-   A2 C1       LDX   #$C1
0D19-   20 D0 D3    JSR   $D3D0
0D1C-   C5 D5       CMP   $D5
0D1E-   C4 CF       CPY   $CF
0D20-   AD D2 C1    LDA   $C1D2
0D23-   CE C4 CF    DEC   $CFC4
0D26-   CD 20 D6    CMP   $D620
0D29-   C1 CC       CMP   ($CC,X)
0D2B-   D5 C5       CMP   $C5,X
0D2D-   20 C2 C5    JSR   $C5C2
0D30-   D4          ???
0D31-   D7          ???
0D32-   C5 C5       CMP   $C5
0D34-   CE A2 AC    DEC   $ACA2
0D37-   B8          CLV
0D38-   C4 8D       CPY   $8D
0D3A-   A0 DF       LDY   #$DF
0D3C-   D0 D2       BNE   $0D10
0D3E-   CE D4 A0    DEC   $A0D4
0D41-   A2 B1       LDX   #$B1
0D43-   20 C1 CE    JSR   $CEC1
0D46-   C4 20       CPY   $20
0D48-   B2 B5       LDA   ($B5)
0D4A-   B5 AE       LDA   $AE,X
0D4C-   A2 AC       LDX   #$AC
0D4E-   B8          CLV
0D4F-   C4 B8       CPY   $B8
0D51-   C4 8D       CPY   $8D
0D53-   A0 CA       LDY   #$CA
0D55-   D3          ???
0D56-   D2 A0       CMP   ($A0)
0D58-   D2 C1       CMP   ($C1)
0D5A-   CE C4 B8    DEC   $B8C4
0D5D-   8D A0 D3    STA   $D3A0
0D60-   D4          ???
0D61-   C1 A0       CMP   ($A0,X)
0D63-   A4 B3       LDY   $B3
0D65-   B0 B0       BCS   $0D17
0D67-   8D A0 CA    STA   $CAA0
0D6A-   D3          ???
0D6B-   D2 A0       CMP   ($A0)
0D6D-   D2 C1       CMP   ($C1)
0D6F-   CE C4 B8    DEC   $B8C4
0D72-   8D A0 D3    STA   $D3A0
0D75-   D4          ???
0D76-   C1 A0       CMP   ($A0,X)
0D78-   A4 B3       LDY   $B3
0D7A-   B0 B1       BCS   $0D2D
0D7C-   8D A0 CA    STA   $CAA0
0D7F-   D3          ???
0D80-   D2 A0       CMP   ($A0)
0D82-   D2 C1       CMP   ($C1)
0D84-   CE C4 B8    DEC   $B8C4
0D87-   8D A0 D3    STA   $D3A0
0D8A-   D4          ???
0D8B-   C1 A0       CMP   ($A0,X)
0D8D-   A4 B3       LDY   $B3
0D8F-   B0 B2       BCS   $0D43
0D91-   8D A0 CA    STA   $CAA0
0D94-   D3          ???
0D95-   D2 A0       CMP   ($A0)
0D97-   D2 C1       CMP   ($C1)
0D99-   CE C4 B8    DEC   $B8C4
0D9C-   8D A0 D3    STA   $D3A0
0D9F-   D4          ???
0DA0-   C1 A0       CMP   ($A0,X)
0DA2-   A4 B3       LDY   $B3
0DA4-   B0 B3       BCS   $0D59
0DA6-   8D A0 CA    STA   $CAA0
0DA9-   D3          ???
0DAA-   D2 A0       CMP   ($A0)
0DAC-   D2 C1       CMP   ($C1)
0DAE-   CE C4 B8    DEC   $B8C4
0DB1-   8D A0 D3    STA   $D3A0
0DB4-   D4          ???
0DB5-   C1 A0       CMP   ($A0,X)
0DB7-   A4 B3       LDY   $B3
0DB9-   B0 B4       BCS   $0D6F
0DBB-   8D A0 C4    STA   $C4A0
0DBE-   D5 CD       CMP   $CD,X
0DC0-   D0 A0       BNE   $0D62
0DC2-   A3          ???
0DC3-   A4 B3       LDY   $B3
0DC5-   B0 B0       BCS   $0D77
0DC7-   BB          ???
0DC8-   A3          ???
0DC9-   B5 8D       LDA   $8D,X
0DCB-   A0 DF       LDY   #$DF
0DCD-   D7          ???
0DCE-   C1 C9       CMP   ($C9,X)
0DD0-   D4          ???
0DD1-   8D AA 8D    STA   $8DAA
0DD4-   A0 DF       LDY   #$DF
0DD6-   D0 D2       BNE   $0DAA
0DD8-   CE D4 A0    DEC   $A0D4
0DDB-   A2 20       LDX   #$20
0DDD-   A2 AC       LDX   #$AC
0DDF-   B8          CLV
0DE0-   C4 B8       CPY   $B8
0DE2-   C4 8D       CPY   $8D
0DE4-   A0 DF       LDY   #$DF
0DE6-   D0 D2       BNE   $0DBA
0DE8-   CE D4 A0    DEC   $A0D4
0DEB-   A2 D7       LDX   #$D7
0DED-   C8          INY
0DEE-   C9 CC       CMP   #$CC
0DF0-   C5 20       CMP   $20
0DF2-   D4          ???
0DF3-   C8          INY
0DF4-   C5 20       CMP   $20
0DF6-   D2 CE       CMP   ($CE)
0DF8-   C4 C2       CPY   $C2
0DFA-   20 CD C1    JSR   $C1CD
0DFD-   C3          ???
0DFE-   D2 CF       CMP   ($CF)
0E00-   20 D2 C5    JSR   $C5D2
0E03-   D4          ???
0E04-   D5 D2       CMP   $D2,X
0E06-   CE D3 A2    DEC   $A2D3
0E09-   AC B8 C4    LDY   $C4B8
0E0C-   8D A0 DF    STA   $DFA0
0E0F-   D0 D2       BNE   $0DE3
0E11-   CE D4 A0    DEC   $A0D4
0E14-   A2 C1       LDX   #$C1
0E16-   20 C2 D9    JSR   $D9C2
0E19-   D4          ???
0E1A-   C5 20       CMP   $20
0E1C-   D6 C1       DEC   $C1,X
0E1E-   CC D5 C5    CPY   $C5D5
0E21-   20 C2 C5    JSR   $C5C2
0E24-   D4          ???
0E25-   D7          ???
0E26-   C5 C5       CMP   $C5
0E28-   CE 20 C1    DEC   $C120
0E2B-   20 C7 C9    JSR   $C9C7
0E2E-   D6 C5       DEC   $C5,X
0E30-   CE A2 AC    DEC   $ACA2
0E33-   B8          CLV
0E34-   C4 8D       CPY   $8D
0E36-   A0 DF       LDY   #$DF
0E38-   D0 D2       BNE   $0E0C
0E3A-   CE D4 A0    DEC   $A0D4
0E3D-   A2 CC       LDX   #$CC
0E3F-   CF          ???
0E40-   D7          ???
0E41-   20 C1 CE    JSR   $CEC1
0E44-   C4 20       CPY   $20
0E46-   C8          INY
0E47-   C9 C7       CMP   #$C7
0E49-   C8          INY
0E4A-   20 D6 C1    JSR   $C1D6
0E4D-   CC D5 C5    CPY   $C5D5
0E50-   AE A2 AC    LDX   $ACA2
0E53-   B8          CLV
0E54-   C4 B8       CPY   $B8
0E56-   C4 8D       CPY   $8D
0E58-   A0 D2       LDY   #$D2
0E5A-   CE C4 C2    DEC   $C2C4
0E5D-   A0 A3       LDY   #$A3
0E5F-   A4 C1       LDY   $C1
0E61-   B0 BB       BCS   $0E1E
0E63-   A3          ???
0E64-   A4 C1       LDY   $C1
0E66-   C6 8D       DEC   $8D
0E68-   A0 D3       LDY   #$D3
0E6A-   D4          ???
0E6B-   C1 A0       CMP   ($A0,X)
0E6D-   A4 B3       LDY   $B3
0E6F-   B0 B0       BCS   $0E21
0E71-   8D A0 D2    STA   $D2A0
0E74-   CE C4 C2    DEC   $C2C4
0E77-   A0 A3       LDY   #$A3
0E79-   A4 C1       LDY   $C1
0E7B-   B0 BB       BCS   $0E38
0E7D-   A3          ???
0E7E-   A4 C1       LDY   $C1
0E80-   C6 8D       DEC   $8D
0E82-   A0 D3       LDY   #$D3
0E84-   D4          ???
0E85-   C1 A0       CMP   ($A0,X)
0E87-   A4 B3       LDY   $B3
0E89-   B0 B1       BCS   $0E3C
0E8B-   8D A0 D2    STA   $D2A0
0E8E-   CE C4 C2    DEC   $C2C4
0E91-   A0 A3       LDY   #$A3
0E93-   A4 C1       LDY   $C1
0E95-   B0 BB       BCS   $0E52
0E97-   A3          ???
0E98-   A4 C1       LDY   $C1
0E9A-   C6 8D       DEC   $8D
0E9C-   A0 D3       LDY   #$D3
0E9E-   D4          ???
0E9F-   C1 A0       CMP   ($A0,X)
0EA1-   A4 B3       LDY   $B3
0EA3-   B0 B2       BCS   $0E57
0EA5-   8D A0 D2    STA   $D2A0
0EA8-   CE C4 C2    DEC   $C2C4
0EAB-   A0 A3       LDY   #$A3
0EAD-   A4 C1       LDY   $C1
0EAF-   B0 BB       BCS   $0E6C
0EB1-   A3          ???
0EB2-   A4 C1       LDY   $C1
0EB4-   C6 8D       DEC   $8D
0EB6-   A0 D3       LDY   #$D3
0EB8-   D4          ???
0EB9-   C1 A0       CMP   ($A0,X)
0EBB-   A4 B3       LDY   $B3
0EBD-   B0 B3       BCS   $0E72
0EBF-   8D A0 D2    STA   $D2A0
0EC2-   CE C4 C2    DEC   $C2C4
0EC5-   A0 A3       LDY   #$A3
0EC7-   A4 C1       LDY   $C1
0EC9-   B0 BB       BCS   $0E86
0ECB-   A3          ???
0ECC-   A4 C1       LDY   $C1
0ECE-   C6 8D       DEC   $8D
0ED0-   A0 D3       LDY   #$D3
0ED2-   D4          ???
0ED3-   C1 A0       CMP   ($A0,X)
0ED5-   A4 B3       LDY   $B3
0ED7-   B0 B4       BCS   $0E8D
0ED9-   8D A0 C4    STA   $C4A0
0EDC-   D5 CD       CMP   $CD,X
0EDE-   D0 A0       BNE   $0E80
0EE0-   A3          ???
0EE1-   A4 B3       LDY   $B3
0EE3-   B0 B0       BCS   $0E95
0EE5-   BB          ???
0EE6-   A3          ???
0EE7-   B5 8D       LDA   $8D,X
0EE9-   A0 DF       LDY   #$DF
0EEB-   D7          ???
0EEC-   C1 C9       CMP   ($C9,X)
0EEE-   D4          ???
0EEF-   8D AA 8D    STA   $8DAA
0EF2-   A0 DF       LDY   #$DF
0EF4-   D0 D2       BNE   $0EC8
0EF6-   CE D4 A0    DEC   $A0D4
0EF9-   A2 20       LDX   #$20
0EFB-   A2 AC       LDX   #$AC
0EFD-   B8          CLV
0EFE-   C4 B8       CPY   $B8
0F00-   C4 8D       CPY   $8D
0F02-   A0 DF       LDY   #$DF
0F04-   D0 D2       BNE   $0ED8
0F06-   CE D4 A0    DEC   $A0D4
0F09-   A2 D4       LDX   #$D4
0F0B-   C8          INY
0F0C-   C5 20       CMP   $20
0F0E-   CD D5 CC    CMP   $CCD5
0F11-   B8          CLV
0F12-   20 CD C1    JSR   $C1CD
0F15-   C3          ???
0F16-   D2 CF       CMP   ($CF)
0F18-   20 CD D5    JSR   $D5CD
0F1B-   CC D4 C9    CPY   $C9D4
0F1E-   D0 CC       BNE   $0EEC
0F20-   C9 C5       CMP   #$C5
0F22-   D3          ???
0F23-   A2 AC       LDX   #$AC
0F25-   B8          CLV
0F26-   C4 8D       CPY   $8D
0F28-   A0 DF       LDY   #$DF
0F2A-   D0 D2       BNE   $0EFE
0F2C-   CE D4 A0    DEC   $A0D4
0F2F-   A2 D4       LDX   #$D4
0F31-   D7          ???
0F32-   CF          ???
0F33-   20 D5 CE    JSR   $CED5
0F36-   D3          ???
0F37-   C9 C7       CMP   #$C7
0F39-   CE C5 C4    DEC   $C4C5
0F3C-   20 C2 D9    JSR   $D9C2
0F3F-   D4          ???
0F40-   C5 D3       CMP   $D3
0F42-   20 C1 CE    JSR   $CEC1
0F45-   C4 20       CPY   $20
0F47-   D2 C5       CMP   ($C5)
0F49-   D4          ???
0F4A-   D5 D2       CMP   $D2,X
0F4C-   CE D3 A2    DEC   $A2D3
0F4F-   AC B8 C4    LDY   $C4B8
0F52-   8D A0 DF    STA   $DFA0
0F55-   D0 D2       BNE   $0F29
0F57-   CE D4 A0    DEC   $A0D4
0F5A-   A2 C1       LDX   #$C1
0F5C-   20 B1 B6    JSR   $B6B1
0F5F-   AD C2 C9    LDA   $C9C2
0F62-   D4          ???
0F63-   20 D2 C5    JSR   $C5D2
0F66-   D3          ???
0F67-   D5 CC       CMP   $CC,X
0F69-   D4          ???
0F6A-   20 A8 D7    JSR   $D7A8
0F6D-   CF          ???
0F6E-   D2 C4       CMP   ($C4)
0F70-   A9 AE       LDA   #$AE
0F72-   A2 AC       LDX   #$AC
0F74-   B8          CLV
0F75-   C4 8D       CPY   $8D
0F77-   A0 DF       LDY   #$DF
0F79-   D0 D2       BNE   $0F4D
0F7B-   CE D4 A0    DEC   $A0D4
0F7E-   A2 CE       LDX   #$CE
0F80-   CF          ???
0F81-   D4          ???
0F82-   C5 20       CMP   $20
0F84-   D4          ???
0F85-   C8          INY
0F86-   C1 D4       CMP   ($D4,X)
0F88-   20 D4 C8    JSR   $C8D4
0F8B-   C9 D3       CMP   #$D3
0F8D-   20 D2 C5    JSR   $C5D2
0F90-   D3          ???
0F91-   D5 CC       CMP   $CC,X
0F93-   D4          ???
0F94-   20 C9 D3    JSR   $D3C9
0F97-   20 D3 D4    JSR   $D4D3
0F9A-   CF          ???
0F9B-   D2 C5       CMP   ($C5)
0F9D-   C4 A2       CPY   $A2
0F9F-   AC B8 C4    LDY   $C4B8
0FA2-   8D A0 DF    STA   $DFA0
0FA5-   D0 D2       BNE   $0F79
0FA7-   CE D4 A0    DEC   $A0D4
0FAA-   A2 D7       LDX   #$D7
0FAC-   C9 D4       CMP   #$D4
0FAE-   C8          INY
0FAF-   20 D4 C8    JSR   $C8D4
0FB2-   C5 20       CMP   $20
0FB4-   CC CF D7    CPY   $D7CF
0FB7-   20 C2 D9    JSR   $D9C2
0FBA-   D4          ???
0FBB-   C5 20       CMP   $20
0FBD-   C6 C9       DEC   $C9
0FBF-   D2 D3       CMP   ($D3)
0FC1-   D4          ???
0FC2-   AC 20 D4    LDY   $D420
0FC5-   C8          INY
0FC6-   C5 CE       CMP   $CE
0FC8-   20 D4 C8    JSR   $C8D4
0FCB-   C5 A2       CMP   $A2
0FCD-   AC B8 C4    LDY   $C4B8
0FD0-   8D A0 DF    STA   $DFA0
0FD3-   D0 D2       BNE   $0FA7
0FD5-   CE D4 A0    DEC   $A0D4
0FD8-   A2 C8       LDX   #$C8
0FDA-   C9 C7       CMP   #$C7
0FDC-   C8          INY
0FDD-   20 C2 D9    JSR   $D9C2
0FE0-   D4          ???
0FE1-   C5 AC       CMP   $AC
0FE3-   20 C1 D3    JSR   $D3C1
0FE6-   20 D0 C5    JSR   $C5D0
0FE9-   D2 20       CMP   ($20)
0FEB-   B6 B5       LDX   $B5,Y
0FED-   B0 B2       BCS   $0FA1
0FEF-   20 C3 CF    JSR   $CFC3
0FF2-   CE D6 C5    DEC   $C5D6
0FF5-   CE D4 C9    DEC   $C9D4
0FF8-   CF          ???
0FF9-   CE AE A2    DEC   $A2AE
0FFC-   AC B8 C4    LDY   $C4B8
0FFF-   B8          CLV
1000-   C4 8D       CPY   $8D
1002-   A0 DF       LDY   #$DF
1004-   D0 D2       BNE   $0FD8
1006-   CE D4 A0    DEC   $A0D4
1009-   A2 BA       LDX   #$BA
100B-   BA          TSX
100C-   20 CD D5    JSR   $D5CD
100F-   CC B8 20    CPY   $20B8
1012-   A3          ???
1013-   B1 B0       LDA   ($B0),Y
1015-   BB          ???
1016-   A3          ???
1017-   B1 B0       LDA   ($B0),Y
1019-   20 D2 C5    JSR   $C5D2
101C-   D4          ???
101D-   D5 D2       CMP   $D2,X
101F-   CE D3 20    DEC   $20D3
1022-   A8          TAY
1023-   CC AC C8    CPY   $C8AC
1026-   A9 BA       LDA   #$BA
1028-   A2 AC       LDX   #$AC
102A-   B8          CLV
102B-   C4 8D       CPY   $8D
102D-   A0 CC       LDY   #$CC
102F-   C4 C1       CPY   $C1
1031-   A0 A3       LDY   #$A3
1033-   B1 B0       LDA   ($B0),Y
1035-   8D A0 D3    STA   $D3A0
1038-   D4          ???
1039-   C1 A0       CMP   ($A0,X)
103B-   A4 B3       LDY   $B3
103D-   B0 B0       BCS   $0FEF
103F-   8D A0 CD    STA   $CDA0
1042-   D5 CC       CMP   $CC,X
1044-   B8          CLV
1045-   A0 A3       LDY   #$A3
1047-   B1 B0       LDA   ($B0),Y
1049-   BB          ???
104A-   A4 B3       LDY   $B3
104C-   B0 B0       BCS   $0FFE
104E-   8D A0 C4    STA   $C4A0
1051-   D5 CD       CMP   $CD,X
1053-   D0 A0       BNE   $0FF5
1055-   A3          ???
1056-   D2 C5       CMP   ($C5)
1058-   D4          ???
1059-   D5 D2       CMP   $D2,X
105B-   CE BB A3    DEC   $A3BB
105E-   B2 8D       LDA   ($8D)
1060-   A0 DF       LDY   #$DF
1062-   D7          ???
1063-   C1 C9       CMP   ($C9,X)
1065-   D4          ???
1066-   8D A0 DF    STA   $DFA0
1069-   D0 D2       BNE   $103D
106B-   CE D4 A0    DEC   $A0D4
106E-   A2 20       LDX   #$20
1070-   A2 AC       LDX   #$AC
1072-   B8          CLV
1073-   C4 B8       CPY   $B8
1075-   C4 8D       CPY   $8D
1077-   A0 DF       LDY   #$DF
1079-   D0 D2       BNE   $104D
107B-   CE D4 A0    DEC   $A0D4
107E-   A2 BA       LDX   #$BA
1080-   BA          TSX
1081-   20 CD D5    JSR   $D5CD
1084-   CC B8 20    CPY   $20B8
1087-   A3          ???
1088-   B1 B0       LDA   ($B0),Y
108A-   B0 BB       BCS   $1047
108C-   A3          ???
108D-   B1 B0       LDA   ($B0),Y
108F-   B0 20       BCS   $10B1
1091-   D2 C5       CMP   ($C5)
1093-   D4          ???
1094-   D5 D2       CMP   $D2,X
1096-   CE D3 20    DEC   $20D3
1099-   A8          TAY
109A-   CC AC C8    CPY   $C8AC
109D-   A9 BA       LDA   #$BA
109F-   A2 AC       LDX   #$AC
10A1-   B8          CLV
10A2-   C4 8D       CPY   $8D
10A4-   A0 CD       LDY   #$CD
10A6-   D5 CC       CMP   $CC,X
10A8-   B8          CLV
10A9-   A0 A3       LDY   #$A3
10AB-   B1 B0       LDA   ($B0),Y
10AD-   B0 BB       BCS   $106A
10AF-   A3          ???
10B0-   B1 B0       LDA   ($B0),Y
10B2-   B0 8D       BCS   $1041
10B4-   A0 C4       LDY   #$C4
10B6-   D5 CD       CMP   $CD,X
10B8-   D0 A0       BNE   $105A
10BA-   D2 C5       CMP   ($C5)
10BC-   D4          ???
10BD-   D5 D2       CMP   $D2,X
10BF-   CE BB A3    DEC   $A3BB
10C2-   B2 8D       LDA   ($8D)
10C4-   A0 DF       LDY   #$DF
10C6-   D0 D2       BNE   $109A
10C8-   CE D4 A0    DEC   $A0D4
10CB-   A2 20       LDX   #$20
10CD-   A2 AC       LDX   #$AC
10CF-   B8          CLV
10D0-   C4 B8       CPY   $B8
10D2-   C4 8D       CPY   $8D
10D4-   A0 DF       LDY   #$DF
10D6-   D7          ???
10D7-   C1 C9       CMP   ($C9,X)
10D9-   D4          ???
10DA-   8D AA 8D    STA   $8DAA
10DD-   A0 DF       LDY   #$DF
10DF-   D0 D2       BNE   $10B3
10E1-   CE D4 A0    DEC   $A0D4
10E4-   A2 D4       LDX   #$D4
10E6-   C8          INY
10E7-   C5 20       CMP   $20
10E9-   C4 C9       CPY   $C9
10EB-   D6 B8       DEC   $B8,X
10ED-   20 CD C1    JSR   $C1CD
10F0-   C3          ???
10F1-   D2 CF       CMP   ($CF)
10F3-   20 C4 C9    JSR   $C9C4
10F6-   D6 C9       DEC   $C9,X
10F8-   C4 C5       CPY   $C5
10FA-   D3          ???
10FB-   20 C1 20    JSR   $20C1
10FE-   A2 AC       LDX   #$AC
1100-   B8          CLV
1101-   C4 8D       CPY   $8D
1103-   A0 DF       LDY   #$DF
1105-   D0 D2       BNE   $10D9
1107-   CE D4 A0    DEC   $A0D4
110A-   A2 C4       LDX   #$C4
110C-   C9 D6       CMP   #$D6
110E-   C9 C4       CMP   #$C4
1110-   C5 CE       CMP   $CE
1112-   C4 20       CPY   $20
1114-   C2          ???
1115-   D9 20 C1    CMP   $C120,Y
1118-   20 C4 C9    JSR   $C9C4
111B-   D6 C9       DEC   $C9,X
111D-   D3          ???
111E-   CF          ???
111F-   D2 AC       CMP   ($AC)
1121-   A2 B8       LDX   #$B8
1123-   C4 8D       CPY   $8D
1125-   A0 DF       LDY   #$DF
1127-   D0 D2       BNE   $10FB
1129-   CE D4 A0    DEC   $A0D4
112C-   A2 D2       LDX   #$D2
112E-   C5 D4       CMP   $D4
1130-   D5 D2       CMP   $D2,X
1132-   CE C9 CE    DEC   $CEC9
1135-   C7          ???
1136-   20 D4 C8    JSR   $C8D4
1139-   C5 20       CMP   $20
113B-   D1 D5       CMP   ($D5),Y
113D-   CF          ???
113E-   D4          ???
113F-   C9 C5       CMP   #$C5
1141-   CE D4 AE    DEC   $AED4
1144-   A2 AC       LDX   #$AC
1146-   B8          CLV
1147-   C4 8D       CPY   $8D
1149-   A0 DF       LDY   #$DF
114B-   D0 D2       BNE   $111F
114D-   CE D4 A0    DEC   $A0D4
1150-   A2 C1       LDX   #$C1
1152-   CC CC 20    CPY   $20CC
1155-   D6 C1       DEC   $C1,X
1157-   CC D5 C5    CPY   $C5D5
115A-   D3          ???
115B-   20 C1 D2    JSR   $D2C1
115E-   C5 20       CMP   $20
1160-   D5 CE       CMP   $CE,X
1162-   D3          ???
1163-   C9 C7       CMP   #$C7
1165-   CE C5 C4    DEC   $C4C5
1168-   AE A2 AC    LDX   $ACA2
116B-   B8          CLV
116C-   C4 B8       CPY   $B8
116E-   C4 8D       CPY   $8D
1170-   A0 C4       LDY   #$C4
1172-   C9 D6       CMP   #$D6
1174-   B8          CLV
1175-   A0 A3       LDY   #$A3
1177-   B1 B0       LDA   ($B0),Y
1179-   B0 BB       BCS   $1136
117B-   A3          ???
117C-   B1 B0       LDA   ($B0),Y
117E-   8D A0 DF    STA   $DFA0
1181-   D0 D2       BNE   $1155
1183-   CE D4 A0    DEC   $A0D4
1186-   A2 BA       LDX   #$BA
1188-   BA          TSX
1189-   20 C4 C9    JSR   $C9C4
118C-   D6 B8       DEC   $B8,X
118E-   20 A3 B1    JSR   $B1A3
1191-   B0 B0       BCS   $1143
1193-   BB          ???
1194-   A3          ???
1195-   B1 B0       LDA   ($B0),Y
1197-   20 D2 C5    JSR   $C5D2
119A-   D4          ???
119B-   D5 D2       CMP   $D2,X
119D-   CE D3 BA    DEC   $BAD3
11A0-   A2 AC       LDX   #$AC
11A2-   B8          CLV
11A3-   C4 B8       CPY   $B8
11A5-   C4 8D       CPY   $8D
11A7-   A0 C4       LDY   #$C4
11A9-   D5 CD       CMP   $CD,X
11AB-   D0 A0       BNE   $114D
11AD-   A3          ???
11AE-   D2 C5       CMP   ($C5)
11B0-   D4          ???
11B1-   D5 D2       CMP   $D2,X
11B3-   CE BB A3    DEC   $A3BB
11B6-   B1 8D       LDA   ($8D),Y
11B8-   A0 DF       LDY   #$DF
11BA-   D7          ???
11BB-   C1 C9       CMP   ($C9,X)
11BD-   D4          ???
11BE-   8D A0 DF    STA   $DFA0
11C1-   D0 D2       BNE   $1195
11C3-   CE D4 A0    DEC   $A0D4
11C6-   A2 BA       LDX   #$BA
11C8-   BA          TSX
11C9-   C4 C9       CPY   $C9
11CB-   D6 B8       DEC   $B8,X
11CD-   20 A3 B2    JSR   $B2A3
11D0-   B0 B0       BCS   $1182
11D2-   BB          ???
11D3-   A3          ???
11D4-   B3          ???
11D5-   B3          ???
11D6-   20 D2 C5    JSR   $C5D2
11D9-   D4          ???
11DA-   D5 D2       CMP   $D2,X
11DC-   CE D3 A2    DEC   $A2D3
11DF-   AC B8 C4    LDY   $C4B8
11E2-   B8          CLV
11E3-   C4 8D       CPY   $8D
11E5-   A0 C4       LDY   #$C4
11E7-   C9 D6       CMP   #$D6
11E9-   B8          CLV
11EA-   A0 A3       LDY   #$A3
11EC-   B2 B0       LDA   ($B0)
11EE-   B0 BB       BCS   $11AB
11F0-   A3          ???
11F1-   B3          ???
11F2-   B3          ???
11F3-   8D A0 D3    STA   $D3A0
11F6-   D4          ???
11F7-   D9 A0 A4    CMP   $A4A0,Y
11FA-   B3          ???
11FB-   B0 B0       BCS   $11AD
11FD-   A0 BB       LDY   #$BB
11FF-   20 D2 C5    JSR   $C5D2
1202-   CD C1 C9    CMP   $C9C1
1205-   CE C4 C5    DEC   $C5C4
1208-   D2 20       CMP   ($20)
120A-   C9 CE       CMP   #$CE
120C-   20 AE D9    JSR   $D9AE
120F-   8D A0 C4    STA   $C4A0
1212-   D5 CD       CMP   $CD,X
1214-   D0 A0       BNE   $11B6
1216-   A3          ???
1217-   D2 C5       CMP   ($C5)
1219-   D4          ???
121A-   D5 D2       CMP   $D2,X
121C-   CE BB A3    DEC   $A3BB
121F-   B1 8D       LDA   ($8D),Y
1221-   A0 DF       LDY   #$DF
1223-   D0 D2       BNE   $11F7
1225-   CE D4 A0    DEC   $A0D4
1228-   A2 20       LDX   #$20
122A-   A2 AC       LDX   #$AC
122C-   B8          CLV
122D-   C4 B8       CPY   $B8
122F-   C4 8D       CPY   $8D
1231-   A0 DF       LDY   #$DF
1233-   D0 D2       BNE   $1207
1235-   CE D4 A0    DEC   $A0D4
1238-   A2 D7       LDX   #$D7
123A-   C9 D4       CMP   #$D4
123C-   C8          INY
123D-   20 C1 20    JSR   $20C1
1240-   D2 C5       CMP   ($C5)
1242-   CD C1 C9    CMP   $C9C1
1245-   CE C4 C5    DEC   $C5C4
1248-   D2 20       CMP   ($20)
124A-   CF          ???
124B-   C6 BA       DEC   $BA
124D-   20 A2 AC    JSR   $ACA2
1250-   B8          CLV
1251-   C4 8D       CPY   $8D
1253-   A0 C4       LDY   #$C4
1255-   D5 CD       CMP   $CD,X
1257-   D0 A0       BNE   $11F9
1259-   A3          ???
125A-   A4 B3       LDY   $B3
125C-   B0 B0       BCS   $120E
125E-   BB          ???
125F-   A3          ???
1260-   B1 8D       LDA   ($8D),Y
1262-   A0 DF       LDY   #$DF
1264-   D0 D2       BNE   $1238
1266-   CE D4 A0    DEC   $A0D4
1269-   A2 20       LDX   #$20
126B-   A2 AC       LDX   #$AC
126D-   B8          CLV
126E-   C4 B8       CPY   $B8
1270-   C4 8D       CPY   $8D
1272-   A0 DF       LDY   #$DF
1274-   D7          ???
1275-   C1 C9       CMP   ($C9,X)
1277-   D4          ???
1278-   8D AA 8D    STA   $8DAA
127B-   AA          TAX
127C-   AA          TAX
127D-   20 D4 C8    JSR   $C8D4
1280-   C5 20       CMP   $20
1282-   C6 CF       DEC   $CF
1284-   CC CC CF    CPY   $CFCC
1287-   D7          ???
1288-   C9 CE       CMP   #$CE
128A-   C7          ???
128B-   20 C9 D3    JSR   $D3C9
128E-   20 C4 CF    JSR   $CFC4
1291-   CE C5 20    DEC   $20C5
1294-   CA          DEX
1295-   D5 D3       CMP   $D3,X
1297-   D4          ???
1298-   20 D4 CF    JSR   $CFD4
129B-   20 D3 C8    JSR   $C8D3
129E-   CF          ???
129F-   D7          ???
12A0-   20 D4 C8    JSR   $C8D4
12A3-   C1 D4       CMP   ($D4,X)
12A5-   8D AA AA    STA   $AAAA
12A8-   20 D4 C8    JSR   $C8D4
12AB-   C5 D3       CMP   $D3
12AD-   C5 20       CMP   $20
12AF-   CD C1 C3    CMP   $C3C1
12B2-   D2 CF       CMP   ($CF)
12B4-   D3          ???
12B5-   20 C1 C3    JSR   $C3C1
12B8-   C3          ???
12B9-   C5 D0       CMP   $D0
12BB-   D4          ???
12BC-   20 CC C9    JSR   $C9CC
12BF-   D4          ???
12C0-   C5 D2       CMP   $D2
12C2-   C1 CC       CMP   ($CC,X)
12C4-   20 D6 C1    JSR   $C1D6
12C7-   CC D5 C5    CPY   $C5D5
12CA-   D3          ???
12CB-   20 C1 D3    JSR   $D3C1
12CE-   20 D7 C5    JSR   $C5D7
12D1-   CC CC 8D    CPY   $8DCC
12D4-   AA          TAX
12D5-   AA          TAX
12D6-   20 C1 D3    JSR   $D3C1
12D9-   20 D0 CF    JSR   $CFD0
12DC-   C9 CE       CMP   #$CE
12DE-   D4          ???
12DF-   C5 D2       CMP   $D2
12E1-   D3          ???
12E2-   8D AA 8D    STA   $8DAA
12E5-   A0 CC       LDY   #$CC
12E7-   C4 C1       CPY   $C1
12E9-   A0 A3       LDY   #$A3
12EB-   A4 C4       LDY   $C4
12ED-   B0 A0       BCS   $128F
12EF-   BB          ???
12F0-   20 CC CF    JSR   $CFCC
12F3-   C1 C4       CMP   ($C4,X)
12F5-   20 A3 B2    JSR   $B2A3
12F8-   B0 B0       BCS   $12AA
12FA-   B0 20       BCS   $131C
12FC-   C9 CE       CMP   #$CE
12FE-   D4          ???
12FF-   CF          ???
1300-   20 A4 B3    JSR   $B3A4
1303-   B0 B0       BCS   $12B5
1305-   8D A0 D3    STA   $D3A0
1308-   D4          ???
1309-   C1 A0       CMP   ($A0,X)
130B-   A4 B3       LDY   $B3
130D-   B0 B0       BCS   $12BF
130F-   8D A0 CC    STA   $CCA0
1312-   C4 C1       CPY   $C1
1314-   A0 A3       LDY   #$A3
1316-   A4 B0       LDY   $B0
1318-   B7          ???
1319-   8D A0 D3    STA   $D3A0
131C-   D4          ???
131D-   C1 A0       CMP   ($A0,X)
131F-   A4 B3       LDY   $B3
1321-   B0 B1       BCS   $12D4
1323-   8D A0 CC    STA   $CCA0
1326-   C4 C1       CPY   $C1
1328-   A0 A3       LDY   #$A3
132A-   A4 C2       LDY   $C2
132C-   B8          CLV
132D-   8D A0 D3    STA   $D3A0
1330-   D4          ???
1331-   C1 A0       CMP   ($A0,X)
1333-   A4 B3       LDY   $B3
1335-   B0 B2       BCS   $12E9
1337-   8D A0 CC    STA   $CCA0
133A-   C4 C1       CPY   $C1
133C-   A0 A3       LDY   #$A3
133E-   A4 B0       LDY   $B0
1340-   C2          ???
1341-   8D A0 D3    STA   $D3A0
1344-   D4          ???
1345-   C1 A0       CMP   ($A0,X)
1347-   A4 B3       LDY   $B3
1349-   B0 B3       BCS   $12FE
134B-   8D A0 C1    STA   $C1A0
134E-   C4 C4       CPY   $C4
1350-   B1 B6       LDA   ($B6),Y
1352-   A0 A4       LDY   #$A4
1354-   B3          ???
1355-   B0 B0       BCS   $1307
1357-   BB          ???
1358-   A3          ???
1359-   B3          ???
135A-   B0 B0       BCS   $130C
135C-   B0 8D       BCS   $12EB
135E-   A0 DF       LDY   #$DF
1360-   D0 D2       BNE   $1334
1362-   CE D4 A0    DEC   $A0D4
1365-   A2 20       LDX   #$20
1367-   A2 AC       LDX   #$AC
1369-   B8          CLV
136A-   C4 B8       CPY   $B8
136C-   C4 8D       CPY   $8D
136E-   A0 DF       LDY   #$DF
1370-   D0 D2       BNE   $1344
1372-   CE D4 A0    DEC   $A0D4
1375-   A2 D4       LDX   #$D4
1377-   C8          INY
1378-   C5 20       CMP   $20
137A-   C1 C4       CMP   ($C4,X)
137C-   C4 B1       CPY   $B1
137E-   B6 20       LDX   $20,Y
1380-   CD C1 C3    CMP   $C3C1
1383-   D2 CF       CMP   ($CF)
1385-   20 C1 C4    JSR   $C4C1
1388-   C4 D3       CPY   $D3
138A-   20 D4 D7    JSR   $D7D4
138D-   CF          ???
138E-   A2 AC       LDX   #$AC
1390-   B8          CLV
1391-   C4 8D       CPY   $8D
1393-   A0 DF       LDY   #$DF
1395-   D0 D2       BNE   $1369
1397-   CE D4 A0    DEC   $A0D4
139A-   A2 B1       LDX   #$B1
139C-   B6 AD       LDX   $AD,Y
139E-   C2          ???
139F-   C9 D4       CMP   #$D4
13A1-   20 D6 C1    JSR   $C1D6
13A4-   CC D5 C5    CPY   $C5D5
13A7-   D3          ???
13A8-   AC 20 D3    LDY   $D320
13AB-   C9 C7       CMP   #$C7
13AD-   CE C5 C4    DEC   $C4C5
13B0-   20 CF D2    JSR   $D2CF
13B3-   20 D5 CE    JSR   $CED5
13B6-   D3          ???
13B7-   C9 C7       CMP   #$C7
13B9-   CE C5 C4    DEC   $C4C5
13BC-   AE A2 AC    LDX   $ACA2
13BF-   B8          CLV
13C0-   C4 B8       CPY   $B8
13C2-   C4 8D       CPY   $8D
13C4-   A0 DF       LDY   #$DF
13C6-   D0 D2       BNE   $139A
13C8-   CE D4 A0    DEC   $A0D4
13CB-   A2 C1       LDX   #$C1
13CD-   C4 C4       CPY   $C4
13CF-   B1 B6       LDA   ($B6),Y
13D1-   20 A3 B3    JSR   $B3A3
13D4-   B0 B0       BCS   $1386
13D6-   B0 BB       BCS   $1393
13D8-   A3          ???
13D9-   B2 B0       LDA   ($B0)
13DB-   B0 B0       BCS   $138D
13DD-   20 D2 C5    JSR   $C5D2
13E0-   D4          ???
13E1-   D5 D2       CMP   $D2,X
13E3-   CE D3 BA    DEC   $BAD3
13E6-   20 A2 AC    JSR   $ACA2
13E9-   B8          CLV
13EA-   C4 B8       CPY   $B8
13EC-   C4 8D       CPY   $8D
13EE-   A0 C4       LDY   #$C4
13F0-   D5 CD       CMP   $CD,X
13F2-   D0 A0       BNE   $1394
13F4-   A3          ???
13F5-   D2 C5       CMP   ($C5)
13F7-   D4          ???
13F8-   D5 D2       CMP   $D2,X
13FA-   CE BB D2    DEC   $D2BB
13FD-   C5 D4       CMP   $D4
13FF-   CC C5 CE    CPY   $CEC5
1402-   8D A0 DF    STA   $DFA0
1405-   D0 D2       BNE   $13D9
1407-   CE D4 A0    DEC   $A0D4
140A-   A2 20       LDX   #$20
140C-   A2 AC       LDX   #$AC
140E-   B8          CLV
140F-   C4 B8       CPY   $B8
1411-   C4 8D       CPY   $8D
1413-   A0 DF       LDY   #$DF
1415-   D7          ???
1416-   C1 C9       CMP   ($C9,X)
1418-   D4          ???
1419-   8D AA 8D    STA   $8DAA
141C-   A0 DF       LDY   #$DF
141E-   D0 D2       BNE   $13F2
1420-   CE D4 A0    DEC   $A0D4
1423-   A2 20       LDX   #$20
1425-   A2 AC       LDX   #$AC
1427-   B8          CLV
1428-   C4 B8       CPY   $B8
142A-   C4 8D       CPY   $8D
142C-   A0 DF       LDY   #$DF
142E-   D0 D2       BNE   $1402
1430-   CE D4 A0    DEC   $A0D4
1433-   A2 D4       LDX   #$D4
1435-   C8          INY
1436-   C5 20       CMP   $20
1438-   D3          ???
1439-   D5 C2       CMP   $C2,X
143B-   B1 B6       LDA   ($B6),Y
143D-   20 CD C1    JSR   $C1CD
1440-   C3          ???
1441-   D2 CF       CMP   ($CF)
1443-   20 D3 D5    JSR   $D5D3
1446-   C2          ???
1447-   D4          ???
1448-   D2 C1       CMP   ($C1)
144A-   C3          ???
144B-   D4          ???
144C-   D3          ???
144D-   20 CF CE    JSR   $CECF
1450-   C5 A2       CMP   $A2
1452-   AC B8 C4    LDY   $C4B8
1455-   8D A0 DF    STA   $DFA0
1458-   D0 D2       BNE   $142C
145A-   CE D4 A0    DEC   $A0D4
145D-   A2 B1       LDX   #$B1
145F-   B6 AD       LDX   $AD,Y
1461-   C2          ???
1462-   C9 D4       CMP   #$D4
1464-   20 CE D5    JSR   $D5CE
1467-   CD C2 C5    CMP   $C5C2
146A-   D2 20       CMP   ($20)
146C-   C6 D2       DEC   $D2
146E-   CF          ???
146F-   CD 20 C1    CMP   $C120
1472-   CE CF D4    DEC   $D4CF
1475-   C8          INY
1476-   C5 D2       CMP   $D2
1478-   AE A2 AC    LDX   $ACA2
147B-   B8          CLV
147C-   C4 B8       CPY   $B8
147E-   C4 8D       CPY   $8D
1480-   A0 DF       LDY   #$DF
1482-   D0 D2       BNE   $1456
1484-   CE D4 A0    DEC   $A0D4
1487-   A2 C3       LDX   #$C3
1489-   C1 CC       CMP   ($CC,X)
148B-   C3          ???
148C-   D5 CC       CMP   $CC,X
148E-   C1 D4       CMP   ($D4,X)
1490-   C5 C4       CMP   $C4
1492-   20 CC C5    JSR   $C5CC
1495-   C6 D4       DEC   $D4
1497-   20 D4 CF    JSR   $CFD4
149A-   20 D2 C9    JSR   $C9D2
149D-   C7          ???
149E-   C8          INY
149F-   D4          ???
14A0-   AC 20 CC    LDY   $CC20
14A3-   AD D2 AE    LDA   $AED2
14A6-   A2 AC       LDX   #$AC
14A8-   B8          CLV
14A9-   C4 8D       CPY   $8D
14AB-   A0 DF       LDY   #$DF
14AD-   D0 D2       BNE   $1481
14AF-   CE D4 A0    DEC   $A0D4
14B2-   A2 D3       LDX   #$D3
14B4-   C9 C7       CMP   #$C7
14B6-   CE C5 C4    DEC   $C4C5
14B9-   20 CF D2    JSR   $D2CF
14BC-   20 D5 CE    JSR   $CED5
14BF-   D3          ???
14C0-   C9 C7       CMP   #$C7
14C2-   CE C5 C4    DEC   $C4C5
14C5-   AE A2 AC    LDX   $ACA2
14C8-   B8          CLV
14C9-   C4 B8       CPY   $B8
14CB-   C4 8D       CPY   $8D
14CD-   A0 DF       LDY   #$DF
14CF-   D0 D2       BNE   $14A3
14D1-   CE D4 A0    DEC   $A0D4
14D4-   A2 D3       LDX   #$D3
14D6-   D5 C2       CMP   $C2,X
14D8-   B1 B6       LDA   ($B6),Y
14DA-   20 A3 B5    JSR   $B5A3
14DD-   B0 B0       BCS   $148F
14DF-   B0 BB       BCS   $149C
14E1-   A3          ???
14E2-   B3          ???
14E3-   B0 B0       BCS   $1495
14E5-   B0 20       BCS   $1507
14E7-   D2 C5       CMP   ($C5)
14E9-   D4          ???
14EA-   D5 D2       CMP   $D2,X
14EC-   CE D3 BA    DEC   $BAD3
14EF-   20 A2 AC    JSR   $ACA2
14F2-   B8          CLV
14F3-   C4 B8       CPY   $B8
14F5-   C4 8D       CPY   $8D
14F7-   A0 D3       LDY   #$D3
14F9-   D5 C2       CMP   $C2,X
14FB-   B1 B6       LDA   ($B6),Y
14FD-   A0 A3       LDY   #$A3
14FF-   B5 B0       LDA   $B0,X
1501-   B0 B0       BCS   $14B3
1503-   BB          ???
1504-   A3          ???
1505-   B3          ???
1506-   B0 B0       BCS   $14B8
1508-   B0 A0       BCS   $14AA
150A-   BB          ???
150B-   20 B5 B0    JSR   $B0B5
150E-   B0 B0       BCS   $14C0
1510-   20 AD 20    JSR   $20AD
1513-   B3          ???
1514-   B0 B0       BCS   $14C6
1516-   B0 8D       BCS   $14A5
1518-   A0 C4       LDY   #$C4
151A-   D5 CD       CMP   $CD,X
151C-   D0 A0       BNE   $14BE
151E-   A3          ???
151F-   D2 C5       CMP   ($C5)
1521-   D4          ???
1522-   D5 D2       CMP   $D2,X
1524-   CE BB D2    DEC   $D2BB
1527-   C5 D4       CMP   $D4
1529-   CC C5 CE    CPY   $CEC5
152C-   8D A0 DF    STA   $DFA0
152F-   D0 D2       BNE   $1503
1531-   CE D4 A0    DEC   $A0D4
1534-   A2 20       LDX   #$20
1536-   A2 AC       LDX   #$AC
1538-   B8          CLV
1539-   C4 B8       CPY   $B8
153B-   C4 8D       CPY   $8D
153D-   A0 DF       LDY   #$DF
153F-   D7          ???
1540-   C1 C9       CMP   ($C9,X)
1542-   D4          ???
1543-   8D AA 8D    STA   $8DAA
1546-   A0 DF       LDY   #$DF
1548-   D0 D2       BNE   $151C
154A-   CE D4 A0    DEC   $A0D4
154D-   A2 D4       LDX   #$D4
154F-   C8          INY
1550-   C5 20       CMP   $20
1552-   CD D5 CC    CMP   $CCD5
1555-   B1 B6       LDA   ($B6),Y
1557-   20 CD C1    JSR   $C1CD
155A-   C3          ???
155B-   D2 CF       CMP   ($CF)
155D-   20 CD D5    JSR   $D5CD
1560-   CC D4 C9    CPY   $C9D4
1563-   D0 CC       BNE   $1531
1565-   C9 C5       CMP   #$C5
1567-   D3          ???
1568-   20 D4 D7    JSR   $D7D4
156B-   CF          ???
156C-   A2 AC       LDX   #$AC
156E-   B8          CLV
156F-   C4 8D       CPY   $8D
1571-   A0 DF       LDY   #$DF
1573-   D0 D2       BNE   $1547
1575-   CE D4 A0    DEC   $A0D4
1578-   A2 B1       LDX   #$B1
157A-   B6 AD       LDX   $AD,Y
157C-   C2          ???
157D-   C9 D4       CMP   #$D4
157F-   20 CE D5    JSR   $D5CE
1582-   CD C2 C5    CMP   $C5C2
1585-   D2 D3       CMP   ($D3)
1587-   AC 20 D3    LDY   $D320
158A-   C9 C7       CMP   #$C7
158C-   CE C5 C4    DEC   $C4C5
158F-   20 CF D2    JSR   $D2CF
1592-   20 CE CF    JSR   $CFCE
1595-   D4          ???
1596-   AE A2 AC    LDX   $ACA2
1599-   B8          CLV
159A-   C4 B8       CPY   $B8
159C-   C4 8D       CPY   $8D
159E-   A0 DF       LDY   #$DF
15A0-   D0 D2       BNE   $1574
15A2-   CE D4 A0    DEC   $A0D4
15A5-   A2 CD       LDX   #$CD
15A7-   D5 CC       CMP   $CC,X
15A9-   B1 B6       LDA   ($B6),Y
15AB-   20 A3 B5    JSR   $B5A3
15AE-   B0 B0       BCS   $1560
15B0-   BB          ???
15B1-   A3          ???
15B2-   B5 B0       LDA   $B0,X
15B4-   B0 20       BCS   $15D6
15B6-   D2 C5       CMP   ($C5)
15B8-   D4          ???
15B9-   D5 D2       CMP   $D2,X
15BB-   CE D3 BA    DEC   $BAD3
15BE-   20 A2 AC    JSR   $ACA2
15C1-   B8          CLV
15C2-   C4 B8       CPY   $B8
15C4-   C4 8D       CPY   $8D
15C6-   A0 CD       LDY   #$CD
15C8-   D5 CC       CMP   $CC,X
15CA-   B1 B6       LDA   ($B6),Y
15CC-   A0 A3       LDY   #$A3
15CE-   B5 B0       LDA   $B0,X
15D0-   B0 BB       BCS   $158D
15D2-   A3          ???
15D3-   B5 B0       LDA   $B0,X
15D5-   B0 8D       BCS   $1564
15D7-   A0 C4       LDY   #$C4
15D9-   D5 CD       CMP   $CD,X
15DB-   D0 A0       BNE   $157D
15DD-   A3          ???
15DE-   D2 C5       CMP   ($C5)
15E0-   D4          ???
15E1-   D5 D2       CMP   $D2,X
15E3-   CE BB D2    DEC   $D2BB
15E6-   C5 D4       CMP   $D4
15E8-   CC C5 CE    CPY   $CEC5
15EB-   8D A0 DF    STA   $DFA0
15EE-   D0 D2       BNE   $15C2
15F0-   CE D4 A0    DEC   $A0D4
15F3-   A2 20       LDX   #$20
15F5-   A2 AC       LDX   #$AC
15F7-   B8          CLV
15F8-   C4 B8       CPY   $B8
15FA-   C4 8D       CPY   $8D
15FC-   A0 DF       LDY   #$DF
15FE-   D7          ???
15FF-   C1 C9       CMP   ($C9,X)
1601-   D4          ???
1602-   8D AA 8D    STA   $8DAA
1605-   A0 DF       LDY   #$DF
1607-   D0 D2       BNE   $15DB
1609-   CE D4 A0    DEC   $A0D4
160C-   A2 C1       LDX   #$C1
160E-   CE C4 20    DEC   $20C4
1611-   D4          ???
1612-   C8          INY
1613-   C5 20       CMP   $20
1615-   C4 C9       CPY   $C9
1617-   D6 B1       DEC   $B1,X
1619-   B6 20       LDX   $20,Y
161B-   CD C1 C3    CMP   $C3C1
161E-   D2 CF       CMP   ($CF)
1620-   20 C4 C9    JSR   $C9C4
1623-   D6 C9       DEC   $C9,X
1625-   C4 C5       CPY   $C5
1627-   D3          ???
1628-   20 D4 C8    JSR   $C8D4
162B-   C5 A2       CMP   $A2
162D-   AC B8 C4    LDY   $C4B8
1630-   8D A0 DF    STA   $DFA0
1633-   D0 D2       BNE   $1607
1635-   CE D4 A0    DEC   $A0D4
1638-   A2 C6       LDX   #$C6
163A-   C9 D2       CMP   #$D2
163C-   D3          ???
163D-   D4          ???
163E-   20 D0 C1    JSR   $C1D0
1641-   D2 C1       CMP   ($C1)
1643-   CD C5 D4    CMP   $D4C5
1646-   C5 D2       CMP   $D2
1648-   20 C2 D9    JSR   $D9C2
164B-   20 D4 C8    JSR   $C8D4
164E-   C5 20       CMP   $20
1650-   D3          ???
1651-   C5 C3       CMP   $C3
1653-   CF          ???
1654-   CE C4 AE    DEC   $AEC4
1657-   A2 AC       LDX   #$AC
1659-   B8          CLV
165A-   C4 B8       CPY   $B8
165C-   C4 8D       CPY   $8D
165E-   A0 DF       LDY   #$DF
1660-   D0 D2       BNE   $1634
1662-   CE D4 A0    DEC   $A0D4
1665-   A2 C9       LDX   #$C9
1667-   C6 20       DEC   $20
1669-   D4          ???
166A-   C8          INY
166B-   C5 20       CMP   $20
166D-   D4          ???
166E-   C8          INY
166F-   C9 D2       CMP   #$D2
1671-   C4 20       CPY   $20
1673-   D0 C1       BNE   $1636
1675-   D2 C1       CMP   ($C1)
1677-   CD C5 D4    CMP   $D4C5
167A-   C5 D2       CMP   $D2
167C-   20 C9 D3    JSR   $D3C9
167F-   A2 AC       LDX   #$AC
1681-   B8          CLV
1682-   C4 8D       CPY   $8D
1684-   A0 DF       LDY   #$DF
1686-   D0 D2       BNE   $165A
1688-   CE D4 A0    DEC   $A0D4
168B-   A2 C1       LDX   #$C1
168D-   CE 20 D3    DEC   $D320
1690-   AC 20 D4    LDY   $D420
1693-   C8          INY
1694-   C5 CE       CMP   $CE
1696-   20 D4 C8    JSR   $C8D4
1699-   C5 20       CMP   $20
169B-   C4 C9       CPY   $C9
169D-   D6 C9       DEC   $C9,X
169F-   D3          ???
16A0-   C9 CF       CMP   #$CF
16A2-   CE 20 C9    DEC   $C920
16A5-   D3          ???
16A6-   20 D3 C9    JSR   $C9D3
16A9-   C7          ???
16AA-   CE C5 C4    DEC   $C4C5
16AD-   BB          ???
16AE-   A2 AC       LDX   #$AC
16B0-   B8          CLV
16B1-   C4 8D       CPY   $8D
16B3-   A0 DF       LDY   #$DF
16B5-   D0 D2       BNE   $1689
16B7-   CE D4 A0    DEC   $A0D4
16BA-   A2 CF       LDX   #$CF
16BC-   D4          ???
16BD-   C8          INY
16BE-   C5 D2       CMP   $D2
16C0-   D7          ???
16C1-   C9 D3       CMP   #$D3
16C3-   C5 AC       CMP   $AC
16C5-   20 C9 D4    JSR   $D4C9
16C8-   20 C9 D3    JSR   $D3C9
16CB-   20 D5 CE    JSR   $CED5
16CE-   D3          ???
16CF-   C9 C7       CMP   #$C7
16D1-   CE C5 C4    DEC   $C4C5
16D4-   AE A2 AC    LDX   $ACA2
16D7-   B8          CLV
16D8-   C4 B8       CPY   $B8
16DA-   C4 8D       CPY   $8D
16DC-   A0 DF       LDY   #$DF
16DE-   D0 D2       BNE   $16B2
16E0-   CE D4 A0    DEC   $A0D4
16E3-   A2 C4       LDX   #$C4
16E5-   C9 D6       CMP   #$D6
16E7-   B1 B6       LDA   ($B6),Y
16E9-   20 A3 B2    JSR   $B2A3
16EC-   B5 B0       LDA   $B0,X
16EE-   B0 B0       BCS   $16A0
16F0-   BB          ???
16F1-   A3          ???
16F2-   B5 B0       LDA   $B0,X
16F4-   B0 BB       BCS   $16B1
16F6-   D5 20       CMP   $20,X
16F8-   D2 C5       CMP   ($C5)
16FA-   D4          ???
16FB-   D5 D2       CMP   $D2,X
16FD-   CE D3 BA    DEC   $BAD3
1700-   A2 AC       LDX   #$AC
1702-   B8          CLV
1703-   C4 B8       CPY   $B8
1705-   C4 8D       CPY   $8D
1707-   A0 C4       LDY   #$C4
1709-   C9 D6       CMP   #$D6
170B-   B1 B6       LDA   ($B6),Y
170D-   A0 A3       LDY   #$A3
170F-   B2 B5       LDA   ($B5)
1711-   B0 B0       BCS   $16C3
1713-   B0 BB       BCS   $16D0
1715-   A3          ???
1716-   B5 B0       LDA   $B0,X
1718-   B0 BB       BCS   $16D5
171A-   D5 8D       CMP   $8D,X
171C-   A0 C4       LDY   #$C4
171E-   D5 CD       CMP   $CD,X
1720-   D0 A0       BNE   $16C2
1722-   A3          ???
1723-   D2 C5       CMP   ($C5)
1725-   D4          ???
1726-   D5 D2       CMP   $D2,X
1728-   CE BB D2    DEC   $D2BB
172B-   C5 D4       CMP   $D4
172D-   CC C5 CE    CPY   $CEC5
1730-   8D A0 DF    STA   $DFA0
1733-   D0 D2       BNE   $1707
1735-   CE D4 A0    DEC   $A0D4
1738-   A2 20       LDX   #$20
173A-   A2 AC       LDX   #$AC
173C-   B8          CLV
173D-   C4 B8       CPY   $B8
173F-   C4 8D       CPY   $8D
1741-   A0 DF       LDY   #$DF
1743-   D7          ???
1744-   C1 C9       CMP   ($C9,X)
1746-   D4          ???
1747-   8D AA 8D    STA   $8DAA
174A-   A0 DF       LDY   #$DF
174C-   D0 D2       BNE   $1720
174E-   CE D4 A0    DEC   $A0D4
1751-   A2 D4       LDX   #$D4
1753-   C8          INY
1754-   C5 20       CMP   $20
1756-   D2 C5       CMP   ($C5)
1758-   CD B1 B6    CMP   $B6B1
175B-   20 CD C1    JSR   $C1CD
175E-   C3          ???
175F-   D2 CF       CMP   ($CF)
1761-   20 CC C9    JSR   $C9CC
1764-   CB          ???
1765-   C5 D7       CMP   $D7
1767-   C9 D3       CMP   #$D3
1769-   C5 20       CMP   $20
176B-   C3          ???
176C-   C1 CC       CMP   ($CC,X)
176E-   C3          ???
176F-   D5 CC       CMP   $CC,X
1771-   C1 D4       CMP   ($D4,X)
1773-   C5 D3       CMP   $D3
1775-   A2 AC       LDX   #$AC
1777-   B8          CLV
1778-   C4 8D       CPY   $8D
177A-   A0 DF       LDY   #$DF
177C-   D0 D2       BNE   $1750
177E-   CE D4 A0    DEC   $A0D4
1781-   A2 D4       LDX   #$D4
1783-   C8          INY
1784-   C5 20       CMP   $20
1786-   D2 C5       CMP   ($C5)
1788-   CD C1 C9    CMP   $C9C1
178B-   CE C4 C5    DEC   $C5C4
178E-   D2 20       CMP   ($20)
1790-   CF          ???
1791-   C6 20       DEC   $20
1793-   C1 20       CMP   ($20,X)
1795-   B1 B6       LDA   ($B6),Y
1797-   AD C2 C9    LDA   $C9C2
179A-   D4          ???
179B-   20 C4 C9    JSR   $C9C4
179E-   D6 C9       DEC   $C9,X
17A0-   D3          ???
17A1-   C9 CF       CMP   #$CF
17A3-   CE AE A2    DEC   $A2AE
17A6-   AC B8 C4    LDY   $C4B8
17A9-   8D A0 DF    STA   $DFA0
17AC-   D0 D2       BNE   $1780
17AE-   CE D4 A0    DEC   $A0D4
17B1-   A2 C9       LDX   #$C9
17B3-   D4          ???
17B4-   20 C1 CC    JSR   $CCC1
17B7-   D3          ???
17B8-   CF          ???
17B9-   20 D5 D3    JSR   $D3D5
17BC-   C5 D3       CMP   $D3
17BE-   20 D4 C8    JSR   $C8D4
17C1-   C5 20       CMP   $20
17C3-   D4          ???
17C4-   C8          INY
17C5-   C9 D2       CMP   #$D2
17C7-   C4 20       CPY   $20
17C9-   D0 C1       BNE   $178C
17CB-   D2 C1       CMP   ($C1)
17CD-   CD C5 D4    CMP   $D4C5
17D0-   C5 D2       CMP   $D2
17D2-   20 D4 CF    JSR   $CFD4
17D5-   A2 AC       LDX   #$AC
17D7-   B8          CLV
17D8-   C4 8D       CPY   $8D
17DA-   A0 DF       LDY   #$DF
17DC-   D0 D2       BNE   $17B0
17DE-   CE D4 A0    DEC   $A0D4
17E1-   A2 D3       LDX   #$D3
17E3-   C9 C7       CMP   #$C7
17E5-   CE C9 C6    DEC   $C6C9
17E8-   D9 20 D7    CMP   $D720,Y
17EB-   C8          INY
17EC-   C5 D4       CMP   $D4
17EE-   C8          INY
17EF-   C5 D2       CMP   $D2
17F1-   20 C9 D4    JSR   $D4C9
17F4-   20 C9 D3    JSR   $D3C9
17F7-   20 D3 C9    JSR   $C9D3
17FA-   C7          ???
17FB-   CE C5 C4    DEC   $C4C5
17FE-   20 A8 D3    JSR   $D3A8
1801-   A9 AE       LDA   #$AE
1803-   A2 AC       LDX   #$AC
1805-   B8          CLV
1806-   C4 B8       CPY   $B8
1808-   C4 8D       CPY   $8D
180A-   A0 DF       LDY   #$DF
180C-   D0 D2       BNE   $17E0
180E-   CE D4 A0    DEC   $A0D4
1811-   A2 D2       LDX   #$D2
1813-   C5 CD       CMP   $CD
1815-   B1 B6       LDA   ($B6),Y
1817-   20 A3 B5    JSR   $B5A3
181A-   B0 B0       BCS   $17CC
181C-   B0 BB       BCS   $17D9
181E-   A3          ???
181F-   B3          ???
1820-   B3          ???
1821-   B3          ???
1822-   BB          ???
1823-   D5 20       CMP   $20,X
1825-   D2 C5       CMP   ($C5)
1827-   D4          ???
1828-   D5 D2       CMP   $D2,X
182A-   CE D3 BA    DEC   $BAD3
182D-   A2 AC       LDX   #$AC
182F-   B8          CLV
1830-   C4 B8       CPY   $B8
1832-   C4 8D       CPY   $8D
1834-   A0 D2       LDY   #$D2
1836-   C5 CD       CMP   $CD
1838-   B1 B6       LDA   ($B6),Y
183A-   A0 A3       LDY   #$A3
183C-   B5 B0       LDA   $B0,X
183E-   B0 B0       BCS   $17F0
1840-   BB          ???
1841-   A3          ???
1842-   B3          ???
1843-   B3          ???
1844-   B3          ???
1845-   BB          ???
1846-   D5 8D       CMP   $8D,X
1848-   A0 C4       LDY   #$C4
184A-   D5 CD       CMP   $CD,X
184C-   D0 A0       BNE   $17EE
184E-   A3          ???
184F-   D2 C5       CMP   ($C5)
1851-   D4          ???
1852-   D5 D2       CMP   $D2,X
1854-   CE BB D2    DEC   $D2BB
1857-   C5 D4       CMP   $D4
1859-   CC C5 CE    CPY   $CEC5
185C-   8D A0 DF    STA   $DFA0
185F-   D0 D2       BNE   $1833
1861-   CE D4 A0    DEC   $A0D4
1864-   A2 20       LDX   #$20
1866-   A2 AC       LDX   #$AC
1868-   B8          CLV
1869-   C4 B8       CPY   $B8
186B-   C4 8D       CPY   $8D
186D-   A0 DF       LDY   #$DF
186F-   D7          ???
1870-   C1 C9       CMP   ($C9,X)
1872-   D4          ???
1873-   8D AA 8D    STA   $8DAA
1876-   A0 DF       LDY   #$DF
1878-   D0 D2       BNE   $184C
187A-   CE D4 A0    DEC   $A0D4
187D-   A2 C3       LDX   #$C3
187F-   CD D0 B1    CMP   $B1D0
1882-   B6 20       LDX   $20,Y
1884-   C3          ???
1885-   CF          ???
1886-   CD D0 C1    CMP   $C1D0
1889-   D2 C5       CMP   ($C5)
188B-   D3          ???
188C-   20 D4 D7    JSR   $D7D4
188F-   CF          ???
1890-   20 B1 B6    JSR   $B6B1
1893-   AD C2 C9    LDA   $C9C2
1896-   D4          ???
1897-   20 D6 C1    JSR   $C1D6
189A-   CC D5 C5    CPY   $C5D5
189D-   D3          ???
189E-   A2 AC       LDX   #$AC
18A0-   B8          CLV
18A1-   C4 8D       CPY   $8D
18A3-   A0 DF       LDY   #$DF
18A5-   D0 D2       BNE   $1879
18A7-   CE D4 A0    DEC   $A0D4
18AA-   A2 D3       LDX   #$D3
18AC-   C5 D4       CMP   $D4
18AE-   D4          ???
18AF-   C9 CE       CMP   #$CE
18B1-   C7          ???
18B2-   20 C6 CC    JSR   $CCC6
18B5-   C1 C7       CMP   ($C7,X)
18B7-   D3          ???
18B8-   20 C1 D3    JSR   $D3C1
18BB-   20 D7 CF    JSR   $CFD7
18BE-   D5 CC       CMP   $CC,X
18C0-   C4 20       CPY   $20
18C2-   D4          ???
18C3-   C8          INY
18C4-   C5 20       CMP   $20
18C6-   C3          ???
18C7-   CD D0 20    CMP   $20D0
18CA-   A2 AC       LDX   #$AC
18CC-   B8          CLV
18CD-   C4 8D       CPY   $8D
18CF-   A0 DF       LDY   #$DF
18D1-   D0 D2       BNE   $18A5
18D3-   CE D4 A0    DEC   $A0D4
18D6-   A2 C3       LDX   #$C3
18D8-   CF          ???
18D9-   CD CD C1    CMP   $C1CD
18DC-   CE C4 20    DEC   $20C4
18DF-   C9 CE       CMP   #$CE
18E1-   20 B6 B5    JSR   $B5B6
18E4-   B0 B2       BCS   $1898
18E6-   20 C1 D3    JSR   $D3C1
18E9-   D3          ???
18EA-   C5 CD       CMP   $CD
18EC-   C2          ???
18ED-   CC D9 AE    CPY   $AED9
18F0-   20 D7 C5    JSR   $C5D7
18F3-   20 D7 CF    JSR   $CFD7
18F6-   CE A7 D4    DEC   $D4A7
18F9-   A2 AC       LDX   #$AC
18FB-   B8          CLV
18FC-   C4 8D       CPY   $8D
18FE-   A0 DF       LDY   #$DF
1900-   D0 D2       BNE   $18D4
1902-   CE D4 A0    DEC   $A0D4
1905-   A2 C2       LDX   #$C2
1907-   C5 20       CMP   $20
1909-   C9 CC       CMP   #$CC
190B-   CC D5 D3    CPY   $D3D5
190E-   D4          ???
190F-   D2 C1       CMP   ($C1)
1911-   D4          ???
1912-   C9 CE       CMP   #$CE
1914-   C7          ???
1915-   20 D4 C8    JSR   $C8D4
1918-   C9 D3       CMP   #$D3
191A-   20 C6 CF    JSR   $CFC6
191D-   D2 20       CMP   ($20)
191F-   CE CF D7    DEC   $D7CF
1922-   20 A2 AC    JSR   $ACA2
1925-   B8          CLV
1926-   C4 8D       CPY   $8D
1928-   A0 DF       LDY   #$DF
192A-   D0 D2       BNE   $18FE
192C-   CE D4 A0    DEC   $A0D4
192F-   A2 C2       LDX   #$C2
1931-   C5 C3       CMP   $C3
1933-   C1 D5       CMP   ($D5,X)
1935-   D3          ???
1936-   C5 20       CMP   $20
1938-   C9 20       CMP   #$20
193A-   C8          INY
193B-   C1 D4       CMP   ($D4,X)
193D-   C5 20       CMP   $20
193F-   D9 CF D5    CMP   $D5CF,Y
1942-   AE A2 AC    LDX   $ACA2
1945-   B8          CLV
1946-   C4 B8       CPY   $B8
1948-   C4 8D       CPY   $8D
194A-   A0 DF       LDY   #$DF
194C-   D7          ???
194D-   C1 C9       CMP   ($C9,X)
194F-   D4          ???
1950-   8D AA 8D    STA   $8DAA
1953-   A0 DF       LDY   #$DF
1955-   D0 D2       BNE   $1929
1957-   CE D4 A0    DEC   $A0D4
195A-   A2 20       LDX   #$20
195C-   A2 AC       LDX   #$AC
195E-   B8          CLV
195F-   C4 B8       CPY   $B8
1961-   C4 8D       CPY   $8D
1963-   A0 DF       LDY   #$DF
1965-   D0 D2       BNE   $1939
1967-   CE D4 A0    DEC   $A0D4
196A-   A2 C1       LDX   #$C1
196C-   CE C4 20    DEC   $20C4
196F-   C6 C9       DEC   $C9
1971-   CE C1 CC    DEC   $CCC1
1974-   CC D9 AC    CPY   $ACD9
1977-   20 D4 C8    JSR   $C8D4
197A-   C5 20       CMP   $20
197C-   D2 CE       CMP   ($CE)
197E-   C4 B1       CPY   $B1
1980-   B6 20       LDX   $20,Y
1982-   CD C1 C3    CMP   $C3C1
1985-   D2 CF       CMP   ($CF)
1987-   A2 AC       LDX   #$AC
1989-   B8          CLV
198A-   C4 8D       CPY   $8D
198C-   A0 DF       LDY   #$DF
198E-   D0 D2       BNE   $1962
1990-   CE D4 A0    DEC   $A0D4
1993-   A2 D2       LDX   #$D2
1995-   C5 D4       CMP   $D4
1997-   D5 D2       CMP   $D2,X
1999-   CE D3 20    DEC   $20D3
199C-   C1 20       CMP   ($20,X)
199E-   D2 C1       CMP   ($C1)
19A0-   CE C4 CF    DEC   $CFC4
19A3-   CD 20 B1    CMP   $B120
19A6-   B6 AD       LDX   $AD,Y
19A8-   C2          ???
19A9-   C9 D4       CMP   #$D4
19AB-   20 D6 C1    JSR   $C1D6
19AE-   CC D5 C5    CPY   $C5D5
19B1-   AC 20 C6    LDY   $C620
19B4-   D2 CF       CMP   ($CF)
19B6-   CD A2 AC    CMP   $ACA2
19B9-   B8          CLV
19BA-   C4 8D       CPY   $8D
19BC-   A0 DF       LDY   #$DF
19BE-   D0 D2       BNE   $1992
19C0-   CE D4 A0    DEC   $A0D4
19C3-   A2 B0       LDX   #$B0
19C5-   20 D4 CF    JSR   $CFD4
19C8-   20 B6 B5    JSR   $B5B6
19CB-   B4 B5       LDY   $B5,X
19CD-   B5 AE       LDA   $AE,X
19CF-   A2 AC       LDX   #$AC
19D1-   B8          CLV
19D2-   C4 B8       CPY   $B8
19D4-   C4 8D       CPY   $8D
19D6-   A0 CC       LDY   #$CC
19D8-   D5 D0       CMP   $D0,X
19DA-   A0 B5       LDY   #$B5
19DC-   8D A0 DF    STA   $DFA0
19DF-   D0 D2       BNE   $19B3
19E1-   CE D4 A0    DEC   $A0D4
19E4-   A2 D2       LDX   #$D2
19E6-   CE C4 B1    DEC   $B1C4
19E9-   B6 20       LDX   $20,Y
19EB-   D2 C5       CMP   ($C5)
19ED-   D4          ???
19EE-   D5 D2       CMP   $D2,X
19F0-   CE D3 BA    DEC   $BAD3
19F3-   A2 AC       LDX   #$AC
19F5-   B8          CLV
19F6-   C4 B8       CPY   $B8
19F8-   C4 8D       CPY   $8D
19FA-   A0 D2       LDY   #$D2
19FC-   CE C4 B1    DEC   $B1C4
19FF-   B6 8D       LDX   $8D,Y
1A01-   A0 C4       LDY   #$C4
1A03-   D5 CD       CMP   $CD,X
1A05-   D0 A0       BNE   $19A7
1A07-   A3          ???
1A08-   D2 C5       CMP   ($C5)
1A0A-   D4          ???
1A0B-   D5 D2       CMP   $D2,X
1A0D-   CE BB D2    DEC   $D2BB
1A10-   C5 D4       CMP   $D4
1A12-   CC C5 CE    CPY   $CEC5
1A15-   8D A0 DF    STA   $DFA0
1A18-   D0 D2       BNE   $19EC
1A1A-   CE D4 A0    DEC   $A0D4
1A1D-   A2 20       LDX   #$20
1A1F-   A2 AC       LDX   #$AC
1A21-   B8          CLV
1A22-   C4 B8       CPY   $B8
1A24-   C4 8D       CPY   $8D
1A26-   A0 DF       LDY   #$DF
1A28-   D7          ???
1A29-   C1 C9       CMP   ($C9,X)
1A2B-   D4          ???
1A2C-   8D A0 AD    STA   $ADA0
1A2F-   AD DE 8D    LDA   $8DDE
1A32-   AA          TAX
1A33-   8D AA AA    STA   $AAAA
1A36-   AA          TAX
1A37-   AA          TAX
1A38-   AA          TAX
1A39-   AA          TAX
1A3A-   AA          TAX
1A3B-   AA          TAX
1A3C-   AA          TAX
1A3D-   AA          TAX
1A3E-   AA          TAX
1A3F-   AA          TAX
1A40-   AA          TAX
1A41-   AA          TAX
1A42-   AA          TAX
1A43-   AA          TAX
1A44-   AA          TAX
1A45-   AA          TAX
1A46-   AA          TAX
1A47-   AA          TAX
1A48-   AA          TAX
1A49-   AA          TAX
1A4A-   AA          TAX
1A4B-   AA          TAX
1A4C-   AA          TAX
1A4D-   AA          TAX
1A4E-   AA          TAX
1A4F-   AA          TAX
1A50-   AA          TAX
1A51-   AA          TAX
1A52-   AA          TAX
1A53-   AA          TAX
1A54-   8D AA 8D    STA   $8DAA
1A57-   AA          TAX
1A58-   20 D4 C8    JSR   $C8D4
1A5B-   C5 20       CMP   $20
1A5D-   C6 CF       DEC   $CF
1A5F-   CC CC CF    CPY   $CFCC
1A62-   D7          ???
1A63-   C9 CE       CMP   #$CE
1A65-   C7          ???
1A66-   20 C9 D3    JSR   $D3C9
1A69-   20 C3 D5    JSR   $D5C3
1A6C-   D2 D2       CMP   ($D2)
1A6E-   C5 CE       CMP   $CE
1A70-   D4          ???
1A71-   CC D9 20    CPY   $20D9
1A74-   D5 CE       CMP   $CE,X
1A76-   C4 C5       CPY   $C5
1A78-   D2 8D       CMP   ($8D)
1A7A-   AA          TAX
1A7B-   20 C3 CF    JSR   $CFC3
1A7E-   CE D3 D4    DEC   $D4D3
1A81-   D2 D5       CMP   ($D5)
1A83-   C3          ???
1A84-   D4          ???
1A85-   C9 CF       CMP   #$CF
1A87-   CE AC 20    DEC   $20AC
1A8A-   C1 CE       CMP   ($CE,X)
1A8C-   C4 20       CPY   $20
1A8E-   C4 CF       CPY   $CF
1A90-   C5 D3       CMP   $D3
1A92-   20 CE CF    JSR   $CFCE
1A95-   D4          ???
1A96-   20 D9 C5    JSR   $C5D9
1A99-   D4          ???
1A9A-   8D AA 20    STA   $20AA
1A9D-   D7          ???
1A9E-   CF          ???
1A9F-   D2 CB       CMP   ($CB)
1AA1-   20 C1 D3    JSR   $D3C1
1AA4-   20 D0 CC    JSR   $CCD0
1AA7-   C1 CE       CMP   ($CE,X)
1AA9-   CE C5 C4    DEC   $C4C5
1AAC-   AE 20 C6    LDX   $C620
1AAF-   CC CF C1    CPY   $C1CF
1AB2-   D4          ???
1AB3-   C9 CE       CMP   #$CE
1AB5-   C7          ???
1AB6-   20 D0 CF    JSR   $CFD0
1AB9-   C9 CE       CMP   #$CE
1ABB-   D4          ???
1ABC-   8D AA 20    STA   $20AA
1ABF-   D2 CF       CMP   ($CF)
1AC1-   D5 D4       CMP   $D4,X
1AC3-   C9 CE       CMP   #$CE
1AC5-   C5 D3       CMP   $D3
1AC7-   20 D7 C9    JSR   $C9D7
1ACA-   CC CC 20    CPY   $20CC
1ACD-   C2          ???
1ACE-   C5 20       CMP   $20
1AD0-   C1 C4       CMP   ($C4,X)
1AD2-   C4 C5       CPY   $C5
1AD4-   C4 20       CPY   $20
1AD6-   C9 CE       CMP   #$CE
1AD8-   20 D4 C8    JSR   $C8D4
1ADB-   C5 20       CMP   $20
1ADD-   CE C5 D8    DEC   $D8C5
1AE0-   D4          ???
1AE1-   8D AA 20    STA   $20AA
1AE4-   CD C1 CA    CMP   $CAC1
1AE7-   CF          ???
1AE8-   D2 20       CMP   ($20)
1AEA-   D6 C5       DEC   $C5,X
1AEC-   D2 D3       CMP   ($D3)
1AEE-   C9 CF       CMP   #$CF
1AF0-   CE 20 D2    DEC   $D220
1AF3-   C5 CC       CMP   $CC
1AF5-   C5 C1       CMP   $C1
1AF7-   D3          ???
1AF8-   C5 AE       CMP   $AE
1AFA-   8D AA 8D    STA   $8DAA
1AFD-   AA          TAX
1AFE-   AA          TAX
1AFF-   AA          TAX
1B00-   AA          TAX
1B01-   AA          TAX
1B02-   AA          TAX
1B03-   AA          TAX
1B04-   AA          TAX
1B05-   AA          TAX
1B06-   AA          TAX
1B07-   AA          TAX
1B08-   AA          TAX
1B09-   AA          TAX
1B0A-   AA          TAX
1B0B-   AA          TAX
1B0C-   AA          TAX
1B0D-   AA          TAX
1B0E-   AA          TAX
1B0F-   AA          TAX
1B10-   AA          TAX
1B11-   AA          TAX
1B12-   AA          TAX
1B13-   AA          TAX
1B14-   AA          TAX
1B15-   AA          TAX
1B16-   AA          TAX
1B17-   AA          TAX
1B18-   AA          TAX
1B19-   AA          TAX
1B1A-   AA          TAX
1B1B-   AA          TAX
1B1C-   AA          TAX
1B1D-   8D AA 8D    STA   $8DAA
1B20-   A0 DF       LDY   #$DF
1B22-   D0 D2       BNE   $1AF6
1B24-   CE D4 A0    DEC   $A0D4
1B27-   A2 20       LDX   #$20
1B29-   A2 AC       LDX   #$AC
1B2B-   B8          CLV
1B2C-   C4 B8       CPY   $B8
1B2E-   C4 B8       CPY   $B8
1B30-   C4 B8       CPY   $B8
1B32-   C4 B8       CPY   $B8
1B34-   C4 B8       CPY   $B8
1B36-   C4 B8       CPY   $B8
1B38-   C4 B8       CPY   $B8
1B3A-   C4 8D       CPY   $8D
1B3C-   A0 DF       LDY   #$DF
1B3E-   D0 D2       BNE   $1B12
1B40-   CE D4 A0    DEC   $A0D4
1B43-   A2 C6       LDX   #$C6
1B45-   CC CF C1    CPY   $C1CF
1B48-   D4          ???
1B49-   C9 CE       CMP   #$CE
1B4B-   C7          ???
1B4C-   AD D0 CF    LDA   $CFD0
1B4F-   C9 CE       CMP   #$CE
1B51-   D4          ???
1B52-   20 C3 C1    JSR   $C1C3
1B55-   CC C3 D5    CPY   $D5C3
1B58-   CC C1 D4    CPY   $D4C1
1B5B-   C9 CF       CMP   #$CF
1B5D-   CE A2 AC    DEC   $ACA2
1B60-   B8          CLV
1B61-   C4 8D       CPY   $8D
1B63-   A0 DF       LDY   #$DF
1B65-   D0 D2       BNE   $1B39
1B67-   CE D4 A0    DEC   $A0D4
1B6A-   A2 AD       LDX   #$AD
1B6C-   AD AD AD    LDA   $ADAD
1B6F-   AD AD AD    LDA   $ADAD
1B72-   AD AD AD    LDA   $ADAD
1B75-   AD AD AD    LDA   $ADAD
1B78-   AD AD AD    LDA   $ADAD
1B7B-   AD AD AD    LDA   $ADAD
1B7E-   AD AD AD    LDA   $ADAD
1B81-   AD AD AD    LDA   $ADAD
1B84-   AD A2 AC    LDA   $ACA2
1B87-   B8          CLV
1B88-   C4 B8       CPY   $B8
1B8A-   C4 8D       CPY   $8D
1B8C-   A0 DF       LDY   #$DF
1B8E-   D0 D2       BNE   $1B62
1B90-   CE D4 A0    DEC   $A0D4
1B93-   A2 D4       LDX   #$D4
1B95-   C8          INY
1B96-   C9 D3       CMP   #$D3
1B98-   20 CC C9    JSR   $C9CC
1B9B-   C2          ???
1B9C-   D2 C1       CMP   ($C1)
1B9E-   D2 D9       CMP   ($D9)
1BA0-   20 D5 D3    JSR   $D3D5
1BA3-   C5 D3       CMP   $D3
1BA5-   20 D4 C8    JSR   $C8D4
1BA8-   C5 20       CMP   $20
1BAA-   C1 D0       CMP   ($D0,X)
1BAC-   D0 CC       BNE   $1B7A
1BAE-   C5 D3       CMP   $D3
1BB0-   CF          ???
1BB1-   C6 D4       DEC   $D4
1BB3-   A2 AC       LDX   #$AC
1BB5-   B8          CLV
1BB6-   C4 8D       CPY   $8D
1BB8-   A0 DF       LDY   #$DF
1BBA-   D0 D2       BNE   $1B8E
1BBC-   CE D4 A0    DEC   $A0D4
1BBF-   A2 D2       LDX   #$D2
1BC1-   CF          ???
1BC2-   D5 D4       CMP   $D4,X
1BC4-   C9 CE       CMP   #$CE
1BC6-   C5 D3       CMP   $D3
1BC8-   20 C6 CF    JSR   $CFC6
1BCB-   D2 20       CMP   ($20)
1BCD-   C6 CC       DEC   $CC
1BCF-   CF          ???
1BD0-   C1 D4       CMP   ($D4,X)
1BD2-   C9 CE       CMP   #$CE
1BD4-   C7          ???
1BD5-   AD D0 CF    LDA   $CFD0
1BD8-   C9 CE       CMP   #$CE
1BDA-   D4          ???
1BDB-   A2 AC       LDX   #$AC
1BDD-   B8          CLV
1BDE-   C4 8D       CPY   $8D
1BE0-   A0 DF       LDY   #$DF
1BE2-   D0 D2       BNE   $1BB6
1BE4-   CE D4 A0    DEC   $A0D4
1BE7-   A2 C1       LDX   #$C1
1BE9-   D2 C9       CMP   ($C9)
1BEB-   D4          ???
1BEC-   C8          INY
1BED-   CD C5 D4    CMP   $D4C5
1BF0-   C9 C3       CMP   #$C3
1BF2-   AC 20 D7    LDY   $D720
1BF5-   D2 C9       CMP   ($C9)
1BF7-   D4          ???
1BF8-   D4          ???
1BF9-   C5 CE       CMP   $CE
1BFB-   20 CF D2    JSR   $D2CF
1BFE-   C9 C7       CMP   #$C7
1C00-   C9 CE       CMP   #$CE
1C02-   C1 CC       CMP   ($CC,X)
1C04-   CC D9 A2    CPY   $A2D9
1C07-   AC B8 C4    LDY   $C4B8
1C0A-   8D A0 DF    STA   $DFA0
1C0D-   D0 D2       BNE   $1BE1
1C0F-   CE D4 A0    DEC   $A0D4
1C12-   A2 C2       LDX   #$C2
1C14-   D9 20 D3    CMP   $D320,Y
1C17-   D4          ???
1C18-   C5 D6       CMP   $D6
1C1A-   C5 20       CMP   $20
1C1C-   D7          ???
1C1D-   CF          ???
1C1E-   DA          PHX
1C1F-   CE C9 C1    DEC   $C1C9
1C22-   CB          ???
1C23-   AE 20 D4    LDX   $D420
1C26-   C8          INY
1C27-   C5 D3       CMP   $D3
1C29-   C5 20       CMP   $20
1C2B-   C1 D2       CMP   ($D2,X)
1C2D-   C5 A2       CMP   $A2
1C2F-   AC B8 C4    LDY   $C4B8
1C32-   8D A0 DF    STA   $DFA0
1C35-   D0 D2       BNE   $1C09
1C37-   CE D4 A0    DEC   $A0D4
1C3A-   A2 D0       LDX   #$D0
1C3C-   D2 C5       CMP   ($C5)
1C3E-   D3          ???
1C3F-   C5 CE       CMP   $CE
1C41-   D4          ???
1C42-   20 C9 CE    JSR   $CEC9
1C45-   20 C5 D6    JSR   $D6C5
1C48-   C5 D2       CMP   $D2
1C4A-   D9 20 C1    CMP   $C120,Y
1C4D-   D0 D0       BNE   $1C1F
1C4F-   CC C5 20    CPY   $20C5
1C52-   C9 C9       CMP   #$C9
1C54-   20 CD CF    JSR   $CFCD
1C57-   C4 C5       CPY   $C5
1C59-   CC A2 AC    CPY   $ACA2
1C5C-   B8          CLV
1C5D-   C4 8D       CPY   $8D
1C5F-   A0 DF       LDY   #$DF
1C61-   D0 D2       BNE   $1C35
1C63-   CE D4 A0    DEC   $A0D4
1C66-   A2 C6       LDX   #$C6
1C68-   D2 CF       CMP   ($CF)
1C6A-   CD 20 D4    CMP   $D420
1C6D-   C8          INY
1C6E-   C5 20       CMP   $20
1C70-   C1 D0       CMP   ($D0,X)
1C72-   D0 CC       BNE   $1C40
1C74-   C5 20       CMP   $20
1C76-   DD DB AB    CMP   $ABDB,X
1C79-   20 C1 CE    JSR   $CEC1
1C7C-   C4 20       CPY   $20
1C7E-   C6 CF       DEC   $CF
1C80-   D2 D7       CMP   ($D7)
1C82-   C1 D2       CMP   ($D2,X)
1C84-   C4 AE       CPY   $AE
1C86-   A2 AC       LDX   #$AC
1C88-   B8          CLV
1C89-   C4 8D       CPY   $8D
1C8B-   A0 DF       LDY   #$DF
1C8D-   D0 D2       BNE   $1C61
1C8F-   CE D4 A0    DEC   $A0D4
1C92-   A2 20       LDX   #$20
1C94-   A2 AC       LDX   #$AC
1C96-   B8          CLV
1C97-   C4 B8       CPY   $B8
1C99-   C4 8D       CPY   $8D
1C9B-   A0 DF       LDY   #$DF
1C9D-   D7          ???
1C9E-   C1 C9       CMP   ($C9,X)
1CA0-   D4          ???
1CA1-   8D A0 DF    STA   $DFA0
1CA4-   D0 D2       BNE   $1C78
1CA6-   CE D4 A0    DEC   $A0D4
1CA9-   A2 C6       LDX   #$C6
1CAB-   CC CF C1    CPY   $C1CF
1CAE-   D4          ???
1CAF-   C9 CE       CMP   #$CE
1CB1-   C7          ???
1CB2-   AD D0 CF    LDA   $CFD0
1CB5-   C9 CE       CMP   #$CE
1CB7-   D4          ???
1CB8-   20 D6 C1    JSR   $C1D6
1CBB-   CC D5 C5    CPY   $C5D5
1CBE-   D3          ???
1CBF-   20 C1 D2    JSR   $D2C1
1CC2-   C5 20       CMP   $20
1CC4-   D3          ???
1CC5-   D4          ???
1CC6-   CF          ???
1CC7-   D2 C5       CMP   ($C5)
1CC9-   C4 A2       CPY   $A2
1CCB-   AC B8 C4    LDY   $C4B8
1CCE-   8D A0 DF    STA   $DFA0
1CD1-   D0 D2       BNE   $1CA5
1CD3-   CE D4 A0    DEC   $A0D4
1CD6-   A2 D5       LDX   #$D5
1CD8-   D3          ???
1CD9-   C9 CE       CMP   #$CE
1CDB-   C7          ???
1CDC-   20 D3 C3    JSR   $C3D3
1CDF-   C9 C5       CMP   #$C5
1CE1-   CE D4 C9    DEC   $C9D4
1CE4-   C6 C9       DEC   $C9
1CE6-   C3          ???
1CE7-   20 CE CF    JSR   $CFCE
1CEA-   D4          ???
1CEB-   C1 D4       CMP   ($D4,X)
1CED-   C9 CF       CMP   #$CF
1CEF-   CE AC 20    DEC   $20AC
1CF2-   D7          ???
1CF3-   C8          INY
1CF4-   C5 D2       CMP   $D2
1CF6-   C5 A2       CMP   $A2
1CF8-   AC B8 C4    LDY   $C4B8
1CFB-   8D A0 DF    STA   $DFA0
1CFE-   D0 D2       BNE   $1CD2
1D00-   CE D4 A0    DEC   $A0D4
1D03-   A2 D4       LDX   #$D4
1D05-   C8          INY
1D06-   C5 20       CMP   $20
1D08-   C6 C9       DEC   $C9
1D0A-   D2 D3       CMP   ($D3)
1D0C-   D4          ???
1D0D-   20 C2 D9    JSR   $D9C2
1D10-   D4          ???
1D11-   C5 20       CMP   $20
1D13-   C9 D3       CMP   #$D3
1D15-   20 D4 C8    JSR   $C8D4
1D18-   C5 20       CMP   $20
1D1A-   C5 D8       CMP   $D8
1D1C-   D0 CF       BNE   $1CED
1D1E-   CE C5 CE    DEC   $CEC5
1D21-   D4          ???
1D22-   AC A2 AC    LDY   $ACA2
1D25-   B8          CLV
1D26-   C4 8D       CPY   $8D
1D28-   A0 DF       LDY   #$DF
1D2A-   D0 D2       BNE   $1CFE
1D2C-   CE D4 A0    DEC   $A0D4
1D2F-   A2 D4       LDX   #$D4
1D31-   C8          INY
1D32-   C5 20       CMP   $20
1D34-   D3          ???
1D35-   C5 C3       CMP   $C3
1D37-   CF          ???
1D38-   CE C4 20    DEC   $20C4
1D3B-   D4          ???
1D3C-   C8          INY
1D3D-   D2 CF       CMP   ($CF)
1D3F-   D5 C7       CMP   $C7,X
1D41-   C8          INY
1D42-   20 C6 C9    JSR   $C9C6
1D45-   C6 D4       DEC   $D4
1D47-   C8          INY
1D48-   20 C2 D9    JSR   $D9C2
1D4B-   D4          ???
1D4C-   C5 D3       CMP   $D3
1D4E-   A2 AC       LDX   #$AC
1D50-   B8          CLV
1D51-   C4 8D       CPY   $8D
1D53-   A0 DF       LDY   #$DF
1D55-   D0 D2       BNE   $1D29
1D57-   CE D4 A0    DEC   $A0D4
1D5A-   A2 C1       LDX   #$C1
1D5C-   D2 C5       CMP   ($C5)
1D5E-   20 D4 C8    JSR   $C8D4
1D61-   C5 20       CMP   $20
1D63-   CD C1 CE    CMP   $CEC1
1D66-   D4          ???
1D67-   C9 D3       CMP   #$D3
1D69-   D3          ???
1D6A-   C1 AC       CMP   ($AC,X)
1D6C-   20 C1 CE    JSR   $CEC1
1D6F-   C4 20       CPY   $20
1D71-   D4          ???
1D72-   C8          INY
1D73-   C5 20       CMP   $20
1D75-   D3          ???
1D76-   C9 D8       CMP   #$D8
1D78-   D4          ???
1D79-   C8          INY
1D7A-   A2 AC       LDX   #$AC
1D7C-   B8          CLV
1D7D-   C4 8D       CPY   $8D
1D7F-   A0 DF       LDY   #$DF
1D81-   D0 D2       BNE   $1D55
1D83-   CE D4 A0    DEC   $A0D4
1D86-   A2 C2       LDX   #$C2
1D88-   D9 D4 C5    CMP   $C5D4,Y
1D8B-   20 D4 C8    JSR   $C8D4
1D8E-   C5 20       CMP   $20
1D90-   D3          ???
1D91-   C9 C7       CMP   #$C7
1D93-   CE AE A2    DEC   $A2AE
1D96-   AC B8 C4    LDY   $C4B8
1D99-   B8          CLV
1D9A-   C4 8D       CPY   $8D
1D9C-   A0 DF       LDY   #$DF
1D9E-   D7          ???
1D9F-   C1 C9       CMP   ($C9,X)
1DA1-   D4          ???
1DA2-   8D A0 DF    STA   $DFA0
1DA5-   D0 D2       BNE   $1D79
1DA7-   CE D4 A0    DEC   $A0D4
1DAA-   A2 C5       LDX   #$C5
1DAC-   D8          CLD
1DAD-   D0 20       BNE   $1DCF
1DAF-   20 20 CD    JSR   $CD20
1DB2-   C1 CE       CMP   ($CE,X)
1DB4-   D4          ???
1DB5-   C9 D3       CMP   #$D3
1DB7-   D3          ???
1DB8-   C1 20       CMP   ($20,X)
1DBA-   20 20 20    JSR   $2020
1DBD-   20 D3 C9    JSR   $C9D3
1DC0-   C7          ???
1DC1-   CE A2 AC    DEC   $ACA2
1DC4-   B8          CLV
1DC5-   C4 8D       CPY   $8D
1DC7-   A0 DF       LDY   #$DF
1DC9-   D0 D2       BNE   $1D9D
1DCB-   CE D4 A0    DEC   $A0D4
1DCE-   A2 B0       LDX   #$B0
1DD0-   B0 20       BCS   $1DF2
1DD2-   20 20 20    JSR   $2020
1DD5-   B0 B1       BCS   $1D88
1DD7-   20 B0 B2    JSR   $B2B0
1DDA-   20 B0 B3    JSR   $B3B0
1DDD-   20 B0 B4    JSR   $B4B0
1DE0-   20 20 B0    JSR   $B020
1DE3-   B5 A2       LDA   $A2,X
1DE5-   AC B8 C4    LDY   $C4B8
1DE8-   B8          CLV
1DE9-   C4 B8       CPY   $B8
1DEB-   C4 8D       CPY   $8D
1DED-   A0 CC       LDY   #$CC
1DEF-   C4 C1       CPY   $C1
1DF1-   A0 A3       LDY   #$A3
1DF3-   A4 B8       LDY   $B8
1DF5-   B4 A0       LDY   $A0,X
1DF7-   BB          ???
1DF8-   20 BD 20    JSR   $20BD
1DFB-   A4 B8       LDY   $B8
1DFD-   B0 20       BCS   $1E1F
1DFF-   AB          ???
1E00-   20 C5 D8    JSR   $D8C5
1E03-   D0 CF       BNE   $1DD4
1E05-   CE C5 CE    DEC   $CEC5
1E08-   D4          ???
1E09-   BB          ???
1E0A-   20 AD B1    JSR   $B1AD
1E0D-   20 BD 20    JSR   $20BD
1E10-   A4 B7       LDY   $B7
1E12-   B9 8D A0    LDA   $A08D,Y
1E15-   D3          ???
1E16-   D4          ???
1E17-   C1 A0       CMP   ($A0,X)
1E19-   A4 B3       LDY   $B3
1E1B-   B0 B0       BCS   $1DCD
1E1D-   8D A0 CC    STA   $CCA0
1E20-   C4 C1       CPY   $C1
1E22-   A0 A3       LDY   #$A3
1E24-   A4 C1       LDY   $C1
1E26-   B0 A0       BCS   $1DC8
1E28-   BB          ???
1E29-   20 CD C1    JSR   $C1CD
1E2C-   CE D4 C9    DEC   $C9D4
1E2F-   D3          ???
1E30-   D3          ???
1E31-   C1 8D       CMP   ($8D,X)
1E33-   A0 D3       LDY   #$D3
1E35-   D4          ???
1E36-   C1 A0       CMP   ($A0,X)
1E38-   A4 B3       LDY   $B3
1E3A-   B0 B1       BCS   $1DED
1E3C-   A0 BB       LDY   #$BB
1E3E-   20 D3 D4    JSR   $D4D3
1E41-   CF          ???
1E42-   D2 C5       CMP   ($C5)
1E44-   C4 20       CPY   $20
1E46-   CD CF D3    CMP   $D3CF
1E49-   D4          ???
1E4A-   20 D3 C9    JSR   $C9D3
1E4D-   C7          ???
1E4E-   CE C9 C6    DEC   $C6C9
1E51-   C9 C3       CMP   #$C3
1E53-   C1 CE       CMP   ($CE,X)
1E55-   D4          ???
1E56-   8D A0 CC    STA   $CCA0
1E59-   C4 C1       CPY   $C1
1E5B-   A0 A3       LDY   #$A3
1E5D-   B0 B0       BCS   $1E0F
1E5F-   8D A0 D3    STA   $D3A0
1E62-   D4          ???
1E63-   C1 A0       CMP   ($A0,X)
1E65-   A4 B3       LDY   $B3
1E67-   B0 B2       BCS   $1E1B
1E69-   8D A0 D3    STA   $D3A0
1E6C-   D4          ???
1E6D-   C1 A0       CMP   ($A0,X)
1E6F-   A4 B3       LDY   $B3
1E71-   B0 B3       BCS   $1E26
1E73-   A0 BB       LDY   #$BB
1E75-   20 CC C5    JSR   $C5CC
1E78-   C6 D4       DEC   $D4
1E7A-   20 D4 CF    JSR   $CFD4
1E7D-   20 D2 C9    JSR   $C9D2
1E80-   C7          ???
1E81-   C8          INY
1E82-   D4          ???
1E83-   AE 8D A0    LDX   $A08D
1E86-   D3          ???
1E87-   D4          ???
1E88-   C1 A0       CMP   ($A0,X)
1E8A-   A4 B3       LDY   $B3
1E8C-   B0 B4       BCS   $1E42
1E8E-   8D A0 CC    STA   $CCA0
1E91-   C4 C1       CPY   $C1
1E93-   A0 A3       LDY   #$A3
1E95-   A4 C6       LDY   $C6
1E97-   C6 8D       DEC   $8D
1E99-   A0 D3       LDY   #$D3
1E9B-   D4          ???
1E9C-   C1 A0       CMP   ($A0,X)
1E9E-   A4 B3       LDY   $B3
1EA0-   B0 B5       BCS   $1E57
1EA2-   A0 BB       LDY   #$BB
1EA4-   20 C6 C6    JSR   $C6C6
1EA7-   BD 20 CE    LDA   $CE20,X
1EAA-   C5 C7       CMP   $C7
1EAC-   C1 D4       CMP   ($D4,X)
1EAE-   C9 D6       CMP   #$D6
1EB0-   C5 AC       CMP   $AC
1EB2-   20 B0 20    JSR   $20B0
1EB5-   BD 20 D0    LDA   $D020,X
1EB8-   CF          ???
1EB9-   D3          ???
1EBA-   C9 D4       CMP   #$D4
1EBC-   C9 D6       CMP   #$D6
1EBE-   C5 8D       CMP   $8D
1EC0-   A0 C4       LDY   #$C4
1EC2-   D5 CD       CMP   $CD,X
1EC4-   D0 A0       BNE   $1E66
1EC6-   A3          ???
1EC7-   A4 B3       LDY   $B3
1EC9-   B0 B0       BCS   $1E7B
1ECB-   BB          ???
1ECC-   A3          ???
1ECD-   B6 8D       LDX   $8D,Y
1ECF-   AA          TAX
1ED0-   8D AA AA    STA   $AAAA
1ED3-   20 B2 B5    JSR   $B5B2
1ED6-   C5 B1       CMP   $B1
1ED8-   B0 DE       BCS   $1EB8
1EDA-   AD B1 20    LDA   $20B1
1EDD-   BD 20 B2    LDA   $B220,X
1EE0-   AE B5 8D    LDX   $8DB5
1EE3-   AA          TAX
1EE4-   8D A0 DF    STA   $DFA0
1EE7-   D7          ???
1EE8-   C1 C9       CMP   ($C9,X)
1EEA-   D4          ???
1EEB-   8D A0 DF    STA   $DFA0
1EEE-   D0 D2       BNE   $1EC2
1EF0-   CE D4 A0    DEC   $A0D4
1EF3-   A2 D3       LDX   #$D3
1EF5-   CF          ???
1EF6-   AC 20 CC    LDY   $CC20
1EF9-   C5 D4       CMP   $D4
1EFB-   A7          ???
1EFC-   D3          ???
1EFD-   20 D0 D5    JSR   $D5D0
1F00-   D4          ???
1F01-   20 B2 AE    JSR   $AEB2
1F04-   B5 20       LDA   $20,X
1F06-   C9 CE       CMP   #$CE
1F08-   20 A4 B3    JSR   $B3A4
1F0B-   B0 B0       BCS   $1EBD
1F0D-   20 C1 CE    JSR   $CEC1
1F10-   C4 A2       CPY   $A2
1F12-   AC B8 C4    LDY   $C4B8
1F15-   8D A0 DF    STA   $DFA0
1F18-   D0 D2       BNE   $1EEC
1F1A-   CE D4 A0    DEC   $A0D4
1F1D-   A2 B1       LDX   #$B1
1F1F-   B0 20       BCS   $1F41
1F21-   C9 CE       CMP   #$CE
1F23-   20 A4 B3    JSR   $B3A4
1F26-   B1 B0       LDA   ($B0),Y
1F28-   AC 20 D4    LDY   $D420
1F2B-   C8          INY
1F2C-   C5 CE       CMP   $CE
1F2E-   20 C1 C4    JSR   $C4C1
1F31-   C4 20       CPY   $20
1F33-   D4          ???
1F34-   C8          INY
1F35-   C5 CD       CMP   $CD
1F37-   AE A2 AC    LDX   $ACA2
1F3A-   B8          CLV
1F3B-   C4 B8       CPY   $B8
1F3D-   C4 8D       CPY   $8D
1F3F-   A0 DF       LDY   #$DF
1F41-   D0 D2       BNE   $1F15
1F43-   CE D4 A0    DEC   $A0D4
1F46-   A2 B2       LDX   #$B2
1F48-   AE B5 20    LDX   $20B5
1F4B-   BD 20 B2    LDA   $B220,X
1F4E-   B5 C5       LDA   $C5,X
1F50-   AD B1 20    LDA   $20B1
1F53-   D3          ???
1F54-   C3          ???
1F55-   C9 C5       CMP   #$C5
1F57-   CE D4 C9    DEC   $C9D4
1F5A-   C6 C9       DEC   $C9
1F5C-   C3          ???
1F5D-   20 CE CF    JSR   $CFCE
1F60-   D4          ???
1F61-   C1 D4       CMP   ($D4,X)
1F63-   C9 CF       CMP   #$CF
1F65-   CE A2 AC    DEC   $ACA2
1F68-   B8          CLV
1F69-   C4 B8       CPY   $B8
1F6B-   C4 8D       CPY   $8D
1F6D-   A0 DF       LDY   #$DF
1F6F-   D0 D2       BNE   $1F43
1F71-   CE D4 A0    DEC   $A0D4
1F74-   A2 20       LDX   #$20
1F76-   20 20 20    JSR   $2020
1F79-   BD 20 B0    LDA   $B020,X
1F7C-   B1 20       LDA   ($20),Y
1F7E-   B3          ???
1F7F-   B7          ???
1F80-   20 B0 B0    JSR   $B0B0
1F83-   20 B0 B0    JSR   $B0B0
1F86-   20 B0 B0    JSR   $B0B0
1F89-   20 C6 C6    JSR   $C6C6
1F8C-   A2 AC       LDX   #$AC
1F8E-   B8          CLV
1F8F-   C4 B8       CPY   $B8
1F91-   C4 8D       CPY   $8D
1F93-   A0 DF       LDY   #$DF
1F95-   D0 D2       BNE   $1F69
1F97-   CE D4 A0    DEC   $A0D4
1F9A-   A2 B1       LDX   #$B1
1F9C-   B0 20       BCS   $1FBE
1F9E-   BD 20 B1    LDA   $B120,X
1FA1-   C5 AB       CMP   $AB
1FA3-   B1 A2       LDA   ($A2),Y
1FA5-   AC B8 C4    LDY   $C4B8
1FA8-   8D A0 DF    STA   $DFA0
1FAB-   D0 D2       BNE   $1F7F
1FAD-   CE D4 A0    DEC   $A0D4
1FB0-   A2 20       LDX   #$20
1FB2-   20 20 BD    JSR   $BD20
1FB5-   20 B0 B1    JSR   $B1B0
1FB8-   20 B0 B1    JSR   $B1B0
1FBB-   20 B0 B0    JSR   $B0B0
1FBE-   20 B0 B0    JSR   $B0B0
1FC1-   20 B0 B0    JSR   $B0B0
1FC4-   20 B0 B0    JSR   $B0B0
1FC7-   A2 AC       LDX   #$AC
1FC9-   B8          CLV
1FCA-   C4 B8       CPY   $B8
1FCC-   C4 8D       CPY   $8D
1FCE-   A0 DF       LDY   #$DF
1FD0-   D0 D2       BNE   $1FA4
1FD2-   CE D4 A0    DEC   $A0D4
1FD5-   A2 20       LDX   #$20
1FD7-   A2 AC       LDX   #$AC
1FD9-   B8          CLV
1FDA-   C4 B8       CPY   $B8
1FDC-   C4 B8       CPY   $B8
1FDE-   C4 8D       CPY   $8D
1FE0-   A0 CC       LDY   #$CC
1FE2-   C4 C1       CPY   $C1
1FE4-   A0 A3       LDY   #$A3
1FE6-   A4 B8       LDY   $B8
1FE8-   B4 8D       LDY   $8D,X
1FEA-   A0 CC       LDY   #$CC
1FEC-   C4 C1       CPY   $C1
1FEE-   A0 A3       LDY   #$A3
1FF0-   A4 C1       LDY   $C1
1FF2-   B0 8D       BCS   $1F81
1FF4-   A0 D3       LDY   #$D3
1FF6-   D4          ???
1FF7-   C1 A0       CMP   ($A0,X)
1FF9-   A4 B3       LDY   $B3
1FFB-   B1 B0       LDA   ($B0),Y
1FFD-   8D A0 D3    STA   $D3A0
2000-   D4          ???
2001-   C1 A0       CMP   ($A0,X)
2003-   A4 B3       LDY   $B3
2005-   B1 B1       LDA   ($B1),Y
2007-   8D A0 CC    STA   $CCA0
200A-   C4 C1       CPY   $C1
200C-   A0 A3       LDY   #$A3
200E-   B0 8D       BCS   $1F9D
2010-   A0 D3       LDY   #$D3
2012-   D4          ???
2013-   C1 A0       CMP   ($A0,X)
2015-   A4 B3       LDY   $B3
2017-   B1 B2       LDA   ($B2),Y
2019-   8D A0 D3    STA   $D3A0
201C-   D4          ???
201D-   C1 A0       CMP   ($A0,X)
201F-   A4 B3       LDY   $B3
2021-   B1 B3       LDA   ($B3),Y
2023-   8D A0 D3    STA   $D3A0
2026-   D4          ???
2027-   C1 A0       CMP   ($A0,X)
2029-   A4 B3       LDY   $B3
202B-   B1 B4       LDA   ($B4),Y
202D-   8D A0 D3    STA   $D3A0
2030-   D4          ???
2031-   C1 A0       CMP   ($A0,X)
2033-   A4 B3       LDY   $B3
2035-   B1 B5       LDA   ($B5),Y
2037-   8D A0 DF    STA   $DFA0
203A-   D7          ???
203B-   C1 C9       CMP   ($C9,X)
203D-   D4          ???
203E-   8D A0 DF    STA   $DFA0
2041-   D0 D2       BNE   $2015
2043-   CE D4 A0    DEC   $A0D4
2046-   A2 20       LDX   #$20
2048-   A2 AC       LDX   #$AC
204A-   B8          CLV
204B-   C4 B8       CPY   $B8
204D-   C4 8D       CPY   $8D
204F-   A0 DF       LDY   #$DF
2051-   D0 D2       BNE   $2025
2053-   CE D4 A0    DEC   $A0D4
2056-   A2 CE       LDX   #$CE
2058-   CF          ???
2059-   D7          ???
205A-   20 CC C5    JSR   $C5CC
205D-   D4          ???
205E-   A7          ???
205F-   D3          ???
2060-   20 C1 C4    JSR   $C4C1
2063-   C4 20       CPY   $20
2065-   D4          ???
2066-   C8          INY
2067-   C5 CD       CMP   $CD
2069-   20 D7 C9    JSR   $C9D7
206C-   D4          ???
206D-   C8          INY
206E-   20 D4 C8    JSR   $C8D4
2071-   C5 A2       CMP   $A2
2073-   AC B8 C4    LDY   $C4B8
2076-   8D A0 DF    STA   $DFA0
2079-   D0 D2       BNE   $204D
207B-   CE D4 A0    DEC   $A0D4
207E-   A2 C6       LDX   #$C6
2080-   D0 C1       BNE   $2043
2082-   C4 C4       CPY   $C4
2084-   20 CD C1    JSR   $C1CD
2087-   C3          ???
2088-   D2 CF       CMP   ($CF)
208A-   20 D4 CF    JSR   $CFD4
208D-   20 D3 C5    JSR   $C5D3
2090-   C5 20       CMP   $20
2092-   D4          ???
2093-   C8          INY
2094-   C5 20       CMP   $20
2096-   D2 C5       CMP   ($C5)
2098-   D3          ???
2099-   D5 CC       CMP   $CC,X
209B-   D4          ???
209C-   AE A2 AC    LDX   $ACA2
209F-   B8          CLV
20A0-   C4 B8       CPY   $B8
20A2-   C4 8D       CPY   $8D
20A4-   A0 DF       LDY   #$DF
20A6-   D0 D2       BNE   $207A
20A8-   CE D4 A0    DEC   $A0D4
20AB-   A2 C6       LDX   #$C6
20AD-   D0 C1       BNE   $2070
20AF-   C4 C4       CPY   $C4
20B1-   20 A4 B3    JSR   $B3A4
20B4-   B0 B0       BCS   $2066
20B6-   BB          ???
20B7-   A4 B3       LDY   $B3
20B9-   B1 B0       LDA   ($B0),Y
20BB-   20 D2 C5    JSR   $C5D2
20BE-   D4          ???
20BF-   D5 D2       CMP   $D2,X
20C1-   CE D3 BA    DEC   $BAD3
20C4-   A2 AC       LDX   #$AC
20C6-   B8          CLV
20C7-   C4 B8       CPY   $B8
20C9-   C4 8D       CPY   $8D
20CB-   A0 C6       LDY   #$C6
20CD-   D0 C1       BNE   $2090
20CF-   C4 C4       CPY   $C4
20D1-   A0 A4       LDY   #$A4
20D3-   B3          ???
20D4-   B0 B0       BCS   $2086
20D6-   BB          ???
20D7-   A4 B3       LDY   $B3
20D9-   B1 B0       LDA   ($B0),Y
20DB-   8D A0 C4    STA   $C4A0
20DE-   D5 CD       CMP   $CD,X
20E0-   D0 A0       BNE   $2082
20E2-   A3          ???
20E3-   D2 C5       CMP   ($C5)
20E5-   D4          ???
20E6-   D5 D2       CMP   $D2,X
20E8-   CE BB D2    DEC   $D2BB
20EB-   C5 D4       CMP   $D4
20ED-   CC C5 CE    CPY   $CEC5
20F0-   8D AA 8D    STA   $8DAA
20F3-   AA          TAX
20F4-   AA          TAX
20F5-   AA          TAX
20F6-   AA          TAX
20F7-   AA          TAX
20F8-   AA          TAX
20F9-   AA          TAX
20FA-   AA          TAX
20FB-   AA          TAX
20FC-   AA          TAX
20FD-   AA          TAX
20FE-   AA          TAX
20FF-   AA          TAX
2100-   AA          TAX
2101-   AA          TAX
2102-   AA          TAX
2103-   AA          TAX
2104-   AA          TAX
2105-   AA          TAX
2106-   AA          TAX
2107-   AA          TAX
2108-   AA          TAX
2109-   AA          TAX
210A-   AA          TAX
210B-   AA          TAX
210C-   AA          TAX
210D-   AA          TAX
210E-   AA          TAX
210F-   AA          TAX
2110-   AA          TAX
2111-   AA          TAX
2112-   AA          TAX
2113-   8D AA 8D    STA   $8DAA
2116-   AA          TAX
2117-   20 C5 CE    JSR   $CEC5
211A-   C4 20       CPY   $20
211C-   CF          ???
211D-   C6 20       DEC   $20
211F-   C3          ???
2120-   CF          ???
2121-   CE D3 D4    DEC   $D4D3
2124-   D2 D5       CMP   ($D5)
2126-   C3          ???
2127-   D4          ???
2128-   C9 CF       CMP   #$CF
212A-   CE 8D AA    DEC   $AA8D
212D-   8D AA AA    STA   $AAAA
2130-   AA          TAX
2131-   AA          TAX
2132-   AA          TAX
2133-   AA          TAX
2134-   AA          TAX
2135-   AA          TAX
2136-   AA          TAX
2137-   AA          TAX
2138-   AA          TAX
2139-   AA          TAX
213A-   AA          TAX
213B-   AA          TAX
213C-   AA          TAX
213D-   AA          TAX
213E-   AA          TAX
213F-   AA          TAX
2140-   AA          TAX
2141-   AA          TAX
2142-   AA          TAX
2143-   AA          TAX
2144-   AA          TAX
2145-   AA          TAX
2146-   AA          TAX
2147-   AA          TAX
2148-   AA          TAX
2149-   AA          TAX
214A-   AA          TAX
214B-   AA          TAX
214C-   AA          TAX
214D-   AA          TAX
214E-   8D AA 8D    STA   $8DAA
2151-   A0 CA       LDY   #$CA
2153-   CD D0 A0    CMP   $A0D0
2156-   D2 C5       CMP   ($C5)
2158-   C5 CE       CMP   $CE
215A-   D4          ???
215B-   D2 D9       CMP   ($D9)
215D-   8D AA 8D    STA   $8DAA
2160-   AA          TAX
2161-   E0 E0       CPX   #$E0
2163-   E0 E0       CPX   #$E0
2165-   E0 E0       CPX   #$E0
2167-   E0 E0       CPX   #$E0
2169-   E0 E0       CPX   #$E0
216B-   E0 E0       CPX   #$E0
216D-   E0 E0       CPX   #$E0
216F-   E0 E0       CPX   #$E0
2171-   E0 E0       CPX   #$E0
2173-   E0 E0       CPX   #$E0
2175-   E0 E0       CPX   #$E0
2177-   E0 E0       CPX   #$E0
2179-   E0 E0       CPX   #$E0
217B-   E0 E0       CPX   #$E0
217D-   E0 E0       CPX   #$E0
217F-   AA          TAX
2180-   8D AA 20    STA   $20AA
2183-   20 20 20    JSR   $2020
2186-   20 20 20    JSR   $2020
2189-   20 C2 CF    JSR   $CFC2
218C-   D4          ???
218D-   D4          ???
218E-   CF          ???
218F-   CD 20 C9    CMP   $C920
2192-   CE C3 CC    DEC   $CCC3
2195-   D5 C4       CMP   $C4,X
2197-   C5 D3       CMP   $D3
2199-   20 20 20    JSR   $2020
219C-   20 20 20    JSR   $2020
219F-   20 AA 8D    JSR   $8DAA
21A2-   AA          TAX
21A3-   AC AC AC    LDY   $ACAC
21A6-   AC AC AC    LDY   $ACAC
21A9-   AC AC AC    LDY   $ACAC
21AC-   AC AC AC    LDY   $ACAC
21AF-   AC AC AC    LDY   $ACAC
21B2-   AC AC AC    LDY   $ACAC
21B5-   AC AC AC    LDY   $ACAC
21B8-   AC AC AC    LDY   $ACAC
21BB-   AC AC AC    LDY   $ACAC
21BE-   AC AC AC    LDY   $ACAC
21C1-   AA          TAX
21C2-   8D AA 8D    STA   $8DAA
21C5-   AA          TAX
21C6-   AA          TAX
21C7-   20 C2 CF    JSR   $CFC2
21CA-   D4          ???
21CB-   D4          ???
21CC-   CF          ???
21CD-   CD 20 C9    CMP   $C920
21D0-   CE C3 CC    DEC   $CCC3
21D3-   D5 C4       CMP   $C4,X
21D5-   C5 D3       CMP   $D3
21D7-   8D AA 8D    STA   $8DAA
21DA-   A0 D0       LDY   #$D0
21DC-   D5 D4       CMP   $D4,X
21DE-   A0 CD       LDY   #$CD
21E0-   C9 CE       CMP   #$CE
21E2-   AE CC C9    LDX   $C9CC
21E5-   C2          ???
21E6-   AE D2 C5    LDX   $C5D2
21E9-   D1 D5       CMP   ($D5),Y
21EB-   C9 D2       CMP   #$D2
21ED-   C5 C4       CMP   $C4
21EF-   8D AA 8D    STA   $8DAA
21F2-   AA          TAX
21F3-   AA          TAX
21F4-   20 C9 CE    JSR   $CEC9
21F7-   C4 C9       CPY   $C9
21F9-   D6 C9       DEC   $C9,X
21FB-   C4 D5       CPY   $D5
21FD-   C1 CC       CMP   ($CC,X)
21FF-   20 D3 D5    JSR   $D5D3
2202-   C2          ???
2203-   D2 CF       CMP   ($CF)
2205-   D5 D4       CMP   $D4,X
2207-   C9 CE       CMP   #$CE
2209-   C5 20       CMP   $20
220B-   C9 CE       CMP   #$CE
220D-   C3          ???
220E-   CC D5 C4    CPY   $C4D5
2211-   C5 D3       CMP   $D3
2213-   8D AA 8D    STA   $8DAA
2216-   AA          TAX
2217-   AA          TAX
2218-   20 B8 AD    JSR   $ADB8
221B-   C2          ???
221C-   C9 D4       CMP   #$D4
221E-   20 CD C1    JSR   $C1CD
2221-   D4          ???
2222-   C8          INY
2223-   20 D3 D5    JSR   $D5D3
2226-   C2          ???
2227-   D2 CF       CMP   ($CF)
2229-   D5 D4       CMP   $D4,X
222B-   C9 CE       CMP   #$CE
222D-   C5 D3       CMP   $D3
222F-   8D AA 8D    STA   $8DAA
2232-   A0 D0       LDY   #$D0
2234-   D5 D4       CMP   $D4,X
2236-   A0 CD       LDY   #$CD
2238-   C9 CE       CMP   #$CE
223A-   AE D3 D5    LDX   $D5D3
223D-   C2          ???
223E-   AE CD D5    LDX   $D5CD
2241-   CC D4 B8    CPY   $B8D4
2244-   8D A0 D0    STA   $D0A0
2247-   D5 D4       CMP   $D4,X
2249-   A0 CD       LDY   #$CD
224B-   C9 CE       CMP   #$CE
224D-   AE D3 D5    LDX   $D5D3
2250-   C2          ???
2251-   AE C4 C9    LDX   $C9C4
2254-   D6 C4       DEC   $C4,X
2256-   B8          CLV
2257-   8D A0 D0    STA   $D0A0
225A-   D5 D4       CMP   $D4,X
225C-   A0 CD       LDY   #$CD
225E-   C9 CE       CMP   #$CE
2260-   AE D3 D5    LDX   $D5D3
2263-   C2          ???
2264-   AE D2 C1    LDX   $C1D2
2267-   CE C4 B8    DEC   $B8C4
226A-   8D A0 D0    STA   $D0A0
226D-   D5 D4       CMP   $D4,X
226F-   A0 CD       LDY   #$CD
2271-   C9 CE       CMP   #$CE
2273-   AE D3 D5    LDX   $D5D3
2276-   C2          ???
2277-   AE D2 C1    LDX   $C1D2
227A-   CE C4 C2    DEC   $C2C4
227D-   8D AA 8D    STA   $8DAA
2280-   AA          TAX
2281-   AA          TAX
2282-   20 B1 B6    JSR   $B6B1
2285-   AD C2 C9    LDA   $C9C2
2288-   D4          ???
2289-   20 CD C1    JSR   $C1CD
228C-   D4          ???
228D-   C8          INY
228E-   20 D3 D5    JSR   $D5D3
2291-   C2          ???
2292-   D2 CF       CMP   ($CF)
2294-   D5 D4       CMP   $D4,X
2296-   C9 CE       CMP   #$CE
2298-   C5 D3       CMP   $D3
229A-   8D AA 8D    STA   $8DAA
229D-   A0 D0       LDY   #$D0
229F-   D5 D4       CMP   $D4,X
22A1-   A0 CD       LDY   #$CD
22A3-   C9 CE       CMP   #$CE
22A5-   AE D3 D5    LDX   $D5D3
22A8-   C2          ???
22A9-   AE C1 C4    LDX   $C4C1
22AC-   C4 C9       CPY   $C9
22AE-   D4          ???
22AF-   B1 B6       LDA   ($B6),Y
22B1-   8D A0 D0    STA   $D0A0
22B4-   D5 D4       CMP   $D4,X
22B6-   A0 CD       LDY   #$CD
22B8-   C9 CE       CMP   #$CE
22BA-   AE D3 D5    LDX   $D5D3
22BD-   C2          ???
22BE-   AE D3 D5    LDX   $D5D3
22C1-   C2          ???
22C2-   D4          ???
22C3-   B1 B6       LDA   ($B6),Y
22C5-   8D A0 D0    STA   $D0A0
22C8-   D5 D4       CMP   $D4,X
22CA-   A0 CD       LDY   #$CD
22CC-   C9 CE       CMP   #$CE
22CE-   AE D3 D5    LDX   $D5D3
22D1-   C2          ???
22D2-   AE C3 CF    LDX   $CFC3
22D5-   CD D0 B1    CMP   $B1D0
22D8-   B6 8D       LDX   $8D,Y
22DA-   A0 D0       LDY   #$D0
22DC-   D5 D4       CMP   $D4,X
22DE-   A0 CD       LDY   #$CD
22E0-   C9 CE       CMP   #$CE
22E2-   AE D3 D5    LDX   $D5D3
22E5-   C2          ???
22E6-   AE CD D5    LDX   $D5CD
22E9-   CC D4 B1    CPY   $B1D4
22EC-   B6 8D       LDX   $8D,Y
22EE-   A0 D0       LDY   #$D0
22F0-   D5 D4       CMP   $D4,X
22F2-   A0 CD       LDY   #$CD
22F4-   C9 CE       CMP   #$CE
22F6-   AE D3 D5    LDX   $D5D3
22F9-   C2          ???
22FA-   AE C4 C9    LDX   $C9C4
22FD-   D6 C4       DEC   $C4,X
22FF-   B1 B6       LDA   ($B6),Y
2301-   8D A0 D0    STA   $D0A0
2304-   D5 D4       CMP   $D4,X
2306-   A0 CD       LDY   #$CD
2308-   C9 CE       CMP   #$CE
230A-   AE D3 D5    LDX   $D5D3
230D-   C2          ???
230E-   AE D2 C1    LDX   $C1D2
2311-   CE C4 B1    DEC   $B1C4
2314-   B6 8D       LDX   $8D,Y
2316-   AA          TAX
2317-   8D 00 00    STA   $0000
