0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 CD    LDY   $CD20,X
0950-   C1 D4       CMP   ($D4,X)
0952-   C8          INY
0953-   20 20 C4    JSR   $C420
0956-   C5 CD       CMP   $CD
0958-   CF          ???
0959-   20 BE AD    JSR   $ADBE
095C-   20 20 20    JSR   $2020
095F-   20 20 20    JSR   $2020
0962-   20 20 AA    JSR   $AA20
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B2    JSR   $B220
09D4-   B0 AD       BCS   $0983
09D6-   CA          DEX
09D7-   C1 CE       CMP   ($CE,X)
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B8       LDA   ($B8),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 D4    STA   $D4A0
0B02-   D2 A0       CMP   ($A0)
0B04-   CF          ???
0B05-   CE 8D A0    DEC   $A08D
0B08-   C4 D3       CPY   $D3
0B0A-   CB          ???
0B0B-   A0 CD       LDY   #$CD
0B0D-   C1 D4       CMP   ($D4,X)
0B0F-   C8          INY
0B10-   AE C4 C5    LDX   $C5C4
0B13-   CD CF 8D    CMP   $8DCF
0B16-   A0 CF       LDY   #$CF
0B18-   C2          ???
0B19-   CA          DEX
0B1A-   A0 A4       LDY   #$A4
0B1C-   C2          ???
0B1D-   C6 C5       DEC   $C5
0B1F-   B0 8D       BCS   $0AAE
0B21-   A0 CF       LDY   #$CF
0B23-   D2 C7       CMP   ($C7)
0B25-   A0 A4       LDY   #$A4
0B27-   B6 B0       LDX   $B0,Y
0B29-   B0 B0       BCS   $0ADB
0B2B-   8D AA 8D    STA   $8DAA
0B2E-   AA          TAX
0B2F-   E0 E0       CPX   #$E0
0B31-   E0 E0       CPX   #$E0
0B33-   E0 E0       CPX   #$E0
0B35-   E0 E0       CPX   #$E0
0B37-   E0 E0       CPX   #$E0
0B39-   E0 E0       CPX   #$E0
0B3B-   E0 E0       CPX   #$E0
0B3D-   E0 E0       CPX   #$E0
0B3F-   E0 E0       CPX   #$E0
0B41-   E0 E0       CPX   #$E0
0B43-   E0 E0       CPX   #$E0
0B45-   E0 E0       CPX   #$E0
0B47-   E0 E0       CPX   #$E0
0B49-   E0 E0       CPX   #$E0
0B4B-   E0 E0       CPX   #$E0
0B4D-   AA          TAX
0B4E-   8D AA 20    STA   $20AA
0B51-   20 D4 CF    JSR   $CFD4
0B54-   D0 20       BNE   $0B76
0B56-   C9 CE       CMP   #$CE
0B58-   C3          ???
0B59-   CC D5 C4    CPY   $C4D5
0B5C-   C5 D3       CMP   $D3
0B5E-   20 A8 C8    JSR   $C8A8
0B61-   CF          ???
0B62-   CF          ???
0B63-   CB          ???
0B64-   D3          ???
0B65-   AC CD C1    LDY   $C1CD
0B68-   C3          ???
0B69-   D2 CF       CMP   ($CF)
0B6B-   D3          ???
0B6C-   A9 20       LDA   #$20
0B6E-   AA          TAX
0B6F-   8D AA AC    STA   $ACAA
0B72-   AC AC AC    LDY   $ACAC
0B75-   AC AC AC    LDY   $ACAC
0B78-   AC AC AC    LDY   $ACAC
0B7B-   AC AC AC    LDY   $ACAC
0B7E-   AC AC AC    LDY   $ACAC
0B81-   AC AC AC    LDY   $ACAC
0B84-   AC AC AC    LDY   $ACAC
0B87-   AC AC AC    LDY   $ACAC
0B8A-   AC AC AC    LDY   $ACAC
0B8D-   AC AC AA    LDY   $AAAC
0B90-   8D AA 8D    STA   $8DAA
0B93-   A0 D0       LDY   #$D0
0B95-   D5 D4       CMP   $D4,X
0B97-   A0 D2       LDY   #$D2
0B99-   C5 D1       CMP   $D1
0B9B-   D5 C9       CMP   $C9,X
0B9D-   D2 C5       CMP   ($C5)
0B9F-   C4 AE       CPY   $AE
0BA1-   D6 C1       DEC   $C1,X
0BA3-   D2 D3       CMP   ($D3)
0BA5-   8D A0 D0    STA   $D0A0
0BA8-   D5 D4       CMP   $D4,X
0BAA-   A0 D2       LDY   #$D2
0BAC-   C5 D1       CMP   $D1
0BAE-   D5 C9       CMP   $C9,X
0BB0-   D2 C5       CMP   ($C5)
0BB2-   C4 AE       CPY   $AE
0BB4-   C8          INY
0BB5-   CF          ???
0BB6-   CF          ???
0BB7-   CB          ???
0BB8-   D3          ???
0BB9-   AE CD C9    LDX   $C9CD
0BBC-   CE 8D A0    DEC   $A08D
0BBF-   D5 D3       CMP   $D3,X
0BC1-   C5 A0       CMP   $A0
0BC3-   D2 C5       CMP   ($C5)
0BC5-   D1 D5       CMP   ($D5),Y
0BC7-   C9 D2       CMP   #$D2
0BC9-   C5 C4       CMP   $C4
0BCB-   AE CD C1    LDX   $C1CD
0BCE-   C3          ???
0BCF-   AE CD C9    LDX   $C9CD
0BD2-   CE 8D A0    DEC   $A08D
0BD5-   D0 D5       BNE   $0BAC
0BD7-   D4          ???
0BD8-   A0 CD       LDY   #$CD
0BDA-   C1 D4       CMP   ($D4,X)
0BDC-   C8          INY
0BDD-   AE C8 CF    LDX   $CFC8
0BE0-   CF          ???
0BE1-   CB          ???
0BE2-   D3          ???
0BE3-   8D A0 D5    STA   $D5A0
0BE6-   D3          ???
0BE7-   C5 A0       CMP   $A0
0BE9-   CD C1 D4    CMP   $D4C1
0BEC-   C8          INY
0BED-   AE CD C1    LDX   $C1CD
0BF0-   C3          ???
0BF1-   AE CD C9    LDX   $C9CD
0BF4-   CE 8D AA    DEC   $AA8D
0BF7-   8D AA E0    STA   $E0AA
0BFA-   E0 E0       CPX   #$E0
0BFC-   E0 E0       CPX   #$E0
0BFE-   E0 E0       CPX   #$E0
0C00-   E0 E0       CPX   #$E0
0C02-   E0 E0       CPX   #$E0
0C04-   E0 E0       CPX   #$E0
0C06-   E0 E0       CPX   #$E0
0C08-   E0 E0       CPX   #$E0
0C0A-   E0 E0       CPX   #$E0
0C0C-   E0 E0       CPX   #$E0
0C0E-   E0 E0       CPX   #$E0
0C10-   E0 E0       CPX   #$E0
0C12-   E0 E0       CPX   #$E0
0C14-   E0 E0       CPX   #$E0
0C16-   E0 AA       CPX   #$AA
0C18-   8D AA 20    STA   $20AA
0C1B-   20 20 20    JSR   $2020
0C1E-   20 20 D0    JSR   $D020
0C21-   D2 CF       CMP   ($CF)
0C23-   C7          ???
0C24-   D2 C1       CMP   ($C1)
0C26-   CD 20 CD    CMP   $CD20
0C29-   C1 C9       CMP   ($C9,X)
0C2B-   CE 20 C2    DEC   $C220
0C2E-   CF          ???
0C2F-   C4 D9       CPY   $D9
0C31-   20 20 20    JSR   $2020
0C34-   20 20 20    JSR   $2020
0C37-   20 AA 8D    JSR   $8DAA
0C3A-   AA          TAX
0C3B-   AC AC AC    LDY   $ACAC
0C3E-   AC AC AC    LDY   $ACAC
0C41-   AC AC AC    LDY   $ACAC
0C44-   AC AC AC    LDY   $ACAC
0C47-   AC AC AC    LDY   $ACAC
0C4A-   AC AC AC    LDY   $ACAC
0C4D-   AC AC AC    LDY   $ACAC
0C50-   AC AC AC    LDY   $ACAC
0C53-   AC AC AC    LDY   $ACAC
0C56-   AC AC AC    LDY   $ACAC
0C59-   AA          TAX
0C5A-   8D AA 8D    STA   $8DAA
0C5D-   A0 CA       LDY   #$CA
0C5F-   D3          ???
0C60-   D2 A0       CMP   ($A0)
0C62-   A4 C6       LDY   $C6
0C64-   C3          ???
0C65-   B5 B8       LDA   $B8,X
0C67-   A0 BB       LDY   #$BB
0C69-   20 C8 CF    JSR   $CFC8
0C6C-   CD C5 8D    CMP   $8DC5
0C6F-   A0 DF       LDY   #$DF
0C71-   D0 D2       BNE   $0C45
0C73-   CE D4 A0    DEC   $A0D4
0C76-   A2 C9       LDX   #$C9
0C78-   CE D4 C5    DEC   $C5D4
0C7B-   C7          ???
0C7C-   C5 D2       CMP   $D2
0C7E-   20 CD C1    JSR   $C1CD
0C81-   D4          ???
0C82-   C8          INY
0C83-   20 CC C9    JSR   $C9CC
0C86-   C2          ???
0C87-   D2 C1       CMP   ($C1)
0C89-   D2 C9       CMP   ($C9)
0C8B-   C5 D3       CMP   $D3
0C8D-   20 C1 CE    JSR   $CEC1
0C90-   C4 A2       CPY   $A2
0C92-   AC B8 C4    LDY   $C4B8
0C95-   8D A0 DF    STA   $DFA0
0C98-   D0 D2       BNE   $0C6C
0C9A-   CE D4 A0    DEC   $A0D4
0C9D-   A2 CD       LDX   #$CD
0C9F-   C1 C3       CMP   ($C3,X)
0CA1-   D2 CF       CMP   ($CF)
0CA3-   D3          ???
0CA4-   AE 20 20    LDX   $2020
0CA7-   20 20 20    JSR   $2020
0CAA-   20 20 20    JSR   $2020
0CAD-   20 20 20    JSR   $2020
0CB0-   20 20 20    JSR   $2020
0CB3-   20 20 A2    JSR   $A220
0CB6-   AC B8 C4    LDY   $C4B8
0CB9-   8D A0 DF    STA   $DFA0
0CBC-   D0 D2       BNE   $0C90
0CBE-   CE D4 A0    DEC   $A0D4
0CC1-   A2 AD       LDX   #$AD
0CC3-   AD AD AD    LDA   $ADAD
0CC6-   AD AD AD    LDA   $ADAD
0CC9-   AD AD AD    LDA   $ADAD
0CCC-   AD AD AD    LDA   $ADAD
0CCF-   AD AD AD    LDA   $ADAD
0CD2-   AD AD AD    LDA   $ADAD
0CD5-   AD AD AD    LDA   $ADAD
0CD8-   AD AD AD    LDA   $ADAD
0CDB-   A2 AC       LDX   #$AC
0CDD-   B8          CLV
0CDE-   C4 B8       CPY   $B8
0CE0-   C4 8D       CPY   $8D
0CE2-   A0 DF       LDY   #$DF
0CE4-   D0 D2       BNE   $0CB8
0CE6-   CE D4 A0    DEC   $A0D4
0CE9-   A2 D4       LDX   #$D4
0CEB-   C8          INY
0CEC-   C5 20       CMP   $20
0CEE-   D2 C1       CMP   ($C1)
0CF0-   CE C4 B8    DEC   $B8C4
0CF3-   20 D2 CF    JSR   $CFD2
0CF6-   D5 D4       CMP   $D4,X
0CF8-   C9 CE       CMP   #$CE
0CFA-   C5 20       CMP   $20
0CFC-   D2 C5       CMP   ($C5)
0CFE-   D4          ???
0CFF-   D5 D2       CMP   $D2,X
0D01-   CE D3 A2    DEC   $A2D3
0D04-   AC B8 C4    LDY   $C4B8
0D07-   8D A0 DF    STA   $DFA0
0D0A-   D0 D2       BNE   $0CDE
0D0C-   CE D4 A0    DEC   $A0D4
0D0F-   A2 C1       LDX   #$C1
0D11-   20 D0 D3    JSR   $D3D0
0D14-   C5 D5       CMP   $D5
0D16-   C4 CF       CPY   $CF
0D18-   AD D2 C1    LDA   $C1D2
0D1B-   CE C4 CF    DEC   $CFC4
0D1E-   CD 20 D6    CMP   $D620
0D21-   C1 CC       CMP   ($CC,X)
0D23-   D5 C5       CMP   $C5,X
0D25-   20 C2 C5    JSR   $C5C2
0D28-   D4          ???
0D29-   D7          ???
0D2A-   C5 C5       CMP   $C5
0D2C-   CE A2 AC    DEC   $ACA2
0D2F-   B8          CLV
0D30-   C4 8D       CPY   $8D
0D32-   A0 DF       LDY   #$DF
0D34-   D0 D2       BNE   $0D08
0D36-   CE D4 A0    DEC   $A0D4
0D39-   A2 B1       LDX   #$B1
0D3B-   20 C1 CE    JSR   $CEC1
0D3E-   C4 20       CPY   $20
0D40-   B2 B5       LDA   ($B5)
0D42-   B5 AE       LDA   $AE,X
0D44-   A2 AC       LDX   #$AC
0D46-   B8          CLV
0D47-   C4 B8       CPY   $B8
0D49-   C4 8D       CPY   $8D
0D4B-   A0 CA       LDY   #$CA
0D4D-   D3          ???
0D4E-   D2 A0       CMP   ($A0)
0D50-   D2 C1       CMP   ($C1)
0D52-   CE C4 B8    DEC   $B8C4
0D55-   8D A0 D3    STA   $D3A0
0D58-   D4          ???
0D59-   C1 A0       CMP   ($A0,X)
0D5B-   A4 B3       LDY   $B3
0D5D-   B0 B0       BCS   $0D0F
0D5F-   8D A0 CA    STA   $CAA0
0D62-   D3          ???
0D63-   D2 A0       CMP   ($A0)
0D65-   D2 C1       CMP   ($C1)
0D67-   CE C4 B8    DEC   $B8C4
0D6A-   8D A0 D3    STA   $D3A0
0D6D-   D4          ???
0D6E-   C1 A0       CMP   ($A0,X)
0D70-   A4 B3       LDY   $B3
0D72-   B0 B1       BCS   $0D25
0D74-   8D A0 CA    STA   $CAA0
0D77-   D3          ???
0D78-   D2 A0       CMP   ($A0)
0D7A-   D2 C1       CMP   ($C1)
0D7C-   CE C4 B8    DEC   $B8C4
0D7F-   8D A0 D3    STA   $D3A0
0D82-   D4          ???
0D83-   C1 A0       CMP   ($A0,X)
0D85-   A4 B3       LDY   $B3
0D87-   B0 B2       BCS   $0D3B
0D89-   8D A0 CA    STA   $CAA0
0D8C-   D3          ???
0D8D-   D2 A0       CMP   ($A0)
0D8F-   D2 C1       CMP   ($C1)
0D91-   CE C4 B8    DEC   $B8C4
0D94-   8D A0 D3    STA   $D3A0
0D97-   D4          ???
0D98-   C1 A0       CMP   ($A0,X)
0D9A-   A4 B3       LDY   $B3
0D9C-   B0 B3       BCS   $0D51
0D9E-   8D A0 CA    STA   $CAA0
0DA1-   D3          ???
0DA2-   D2 A0       CMP   ($A0)
0DA4-   D2 C1       CMP   ($C1)
0DA6-   CE C4 B8    DEC   $B8C4
0DA9-   8D A0 D3    STA   $D3A0
0DAC-   D4          ???
0DAD-   C1 A0       CMP   ($A0,X)
0DAF-   A4 B3       LDY   $B3
0DB1-   B0 B4       BCS   $0D67
0DB3-   8D A0 DF    STA   $DFA0
0DB6-   C4 D5       CPY   $D5
0DB8-   CD D0 A0    CMP   $A0D0
0DBB-   A4 B3       LDY   $B3
0DBD-   B0 B0       BCS   $0D6F
0DBF-   BB          ???
0DC0-   A3          ???
0DC1-   B5 8D       LDA   $8D,X
0DC3-   A0 DF       LDY   #$DF
0DC5-   D7          ???
0DC6-   C1 C9       CMP   ($C9,X)
0DC8-   D4          ???
0DC9-   8D AA 8D    STA   $8DAA
0DCC-   A0 DF       LDY   #$DF
0DCE-   D0 D2       BNE   $0DA2
0DD0-   CE D4 A0    DEC   $A0D4
0DD3-   A2 20       LDX   #$20
0DD5-   A2 AC       LDX   #$AC
0DD7-   B8          CLV
0DD8-   C4 B8       CPY   $B8
0DDA-   C4 8D       CPY   $8D
0DDC-   A0 DF       LDY   #$DF
0DDE-   D0 D2       BNE   $0DB2
0DE0-   CE D4 A0    DEC   $A0D4
0DE3-   A2 D7       LDX   #$D7
0DE5-   C8          INY
0DE6-   C9 CC       CMP   #$CC
0DE8-   C5 20       CMP   $20
0DEA-   D4          ???
0DEB-   C8          INY
0DEC-   C5 20       CMP   $20
0DEE-   D2 CE       CMP   ($CE)
0DF0-   C4 C2       CPY   $C2
0DF2-   20 CD C1    JSR   $C1CD
0DF5-   C3          ???
0DF6-   D2 CF       CMP   ($CF)
0DF8-   20 D2 C5    JSR   $C5D2
0DFB-   D4          ???
0DFC-   D5 D2       CMP   $D2,X
0DFE-   CE D3 A2    DEC   $A2D3
0E01-   AC B8 C4    LDY   $C4B8
0E04-   8D A0 DF    STA   $DFA0
0E07-   D0 D2       BNE   $0DDB
0E09-   CE D4 A0    DEC   $A0D4
0E0C-   A2 C1       LDX   #$C1
0E0E-   20 C2 D9    JSR   $D9C2
0E11-   D4          ???
0E12-   C5 20       CMP   $20
0E14-   D6 C1       DEC   $C1,X
0E16-   CC D5 C5    CPY   $C5D5
0E19-   20 C2 C5    JSR   $C5C2
0E1C-   D4          ???
0E1D-   D7          ???
0E1E-   C5 C5       CMP   $C5
0E20-   CE 20 C1    DEC   $C120
0E23-   20 C7 C9    JSR   $C9C7
0E26-   D6 C5       DEC   $C5,X
0E28-   CE A2 AC    DEC   $ACA2
0E2B-   B8          CLV
0E2C-   C4 8D       CPY   $8D
0E2E-   A0 DF       LDY   #$DF
0E30-   D0 D2       BNE   $0E04
0E32-   CE D4 A0    DEC   $A0D4
0E35-   A2 CC       LDX   #$CC
0E37-   CF          ???
0E38-   D7          ???
0E39-   20 C1 CE    JSR   $CEC1
0E3C-   C4 20       CPY   $20
0E3E-   C8          INY
0E3F-   C9 C7       CMP   #$C7
0E41-   C8          INY
0E42-   20 D6 C1    JSR   $C1D6
0E45-   CC D5 C5    CPY   $C5D5
0E48-   AE A2 AC    LDX   $ACA2
0E4B-   B8          CLV
0E4C-   C4 B8       CPY   $B8
0E4E-   C4 8D       CPY   $8D
0E50-   A0 D2       LDY   #$D2
0E52-   CE C4 C2    DEC   $C2C4
0E55-   A0 A3       LDY   #$A3
0E57-   A4 C1       LDY   $C1
0E59-   B0 BB       BCS   $0E16
0E5B-   A3          ???
0E5C-   A4 C1       LDY   $C1
0E5E-   C6 8D       DEC   $8D
0E60-   A0 D3       LDY   #$D3
0E62-   D4          ???
0E63-   C1 A0       CMP   ($A0,X)
0E65-   A4 B3       LDY   $B3
0E67-   B0 B0       BCS   $0E19
0E69-   8D A0 D2    STA   $D2A0
0E6C-   CE C4 C2    DEC   $C2C4
0E6F-   A0 A3       LDY   #$A3
0E71-   A4 C1       LDY   $C1
0E73-   B0 BB       BCS   $0E30
0E75-   A3          ???
0E76-   A4 C1       LDY   $C1
0E78-   C6 8D       DEC   $8D
0E7A-   A0 D3       LDY   #$D3
0E7C-   D4          ???
0E7D-   C1 A0       CMP   ($A0,X)
0E7F-   A4 B3       LDY   $B3
0E81-   B0 B1       BCS   $0E34
0E83-   8D A0 D2    STA   $D2A0
0E86-   CE C4 C2    DEC   $C2C4
0E89-   A0 A3       LDY   #$A3
0E8B-   A4 C1       LDY   $C1
0E8D-   B0 BB       BCS   $0E4A
0E8F-   A3          ???
0E90-   A4 C1       LDY   $C1
0E92-   C6 8D       DEC   $8D
0E94-   A0 D3       LDY   #$D3
0E96-   D4          ???
0E97-   C1 A0       CMP   ($A0,X)
0E99-   A4 B3       LDY   $B3
0E9B-   B0 B2       BCS   $0E4F
0E9D-   8D A0 D2    STA   $D2A0
0EA0-   CE C4 C2    DEC   $C2C4
0EA3-   A0 A3       LDY   #$A3
0EA5-   A4 C1       LDY   $C1
0EA7-   B0 BB       BCS   $0E64
0EA9-   A3          ???
0EAA-   A4 C1       LDY   $C1
0EAC-   C6 8D       DEC   $8D
0EAE-   A0 D3       LDY   #$D3
0EB0-   D4          ???
0EB1-   C1 A0       CMP   ($A0,X)
0EB3-   A4 B3       LDY   $B3
0EB5-   B0 B3       BCS   $0E6A
0EB7-   8D A0 D2    STA   $D2A0
0EBA-   CE C4 C2    DEC   $C2C4
0EBD-   A0 A3       LDY   #$A3
0EBF-   A4 C1       LDY   $C1
0EC1-   B0 BB       BCS   $0E7E
0EC3-   A3          ???
0EC4-   A4 C1       LDY   $C1
0EC6-   C6 8D       DEC   $8D
0EC8-   A0 D3       LDY   #$D3
0ECA-   D4          ???
0ECB-   C1 A0       CMP   ($A0,X)
0ECD-   A4 B3       LDY   $B3
0ECF-   B0 B4       BCS   $0E85
0ED1-   8D A0 DF    STA   $DFA0
0ED4-   C4 D5       CPY   $D5
0ED6-   CD D0 A0    CMP   $A0D0
0ED9-   A4 B3       LDY   $B3
0EDB-   B0 B0       BCS   $0E8D
0EDD-   BB          ???
0EDE-   A3          ???
0EDF-   B5 8D       LDA   $8D,X
0EE1-   A0 DF       LDY   #$DF
0EE3-   D7          ???
0EE4-   C1 C9       CMP   ($C9,X)
0EE6-   D4          ???
0EE7-   8D AA 8D    STA   $8DAA
0EEA-   A0 DF       LDY   #$DF
0EEC-   D0 D2       BNE   $0EC0
0EEE-   CE D4 A0    DEC   $A0D4
0EF1-   A2 20       LDX   #$20
0EF3-   A2 AC       LDX   #$AC
0EF5-   B8          CLV
0EF6-   C4 B8       CPY   $B8
0EF8-   C4 8D       CPY   $8D
0EFA-   A0 DF       LDY   #$DF
0EFC-   D0 D2       BNE   $0ED0
0EFE-   CE D4 A0    DEC   $A0D4
0F01-   A2 D4       LDX   #$D4
0F03-   C8          INY
0F04-   C5 20       CMP   $20
0F06-   CD D5 CC    CMP   $CCD5
0F09-   B8          CLV
0F0A-   20 CD C1    JSR   $C1CD
0F0D-   C3          ???
0F0E-   D2 CF       CMP   ($CF)
0F10-   20 CD D5    JSR   $D5CD
0F13-   CC D4 C9    CPY   $C9D4
0F16-   D0 CC       BNE   $0EE4
0F18-   C9 C5       CMP   #$C5
0F1A-   D3          ???
0F1B-   A2 AC       LDX   #$AC
0F1D-   B8          CLV
0F1E-   C4 8D       CPY   $8D
0F20-   A0 DF       LDY   #$DF
0F22-   D0 D2       BNE   $0EF6
0F24-   CE D4 A0    DEC   $A0D4
0F27-   A2 D4       LDX   #$D4
0F29-   D7          ???
0F2A-   CF          ???
0F2B-   20 D5 CE    JSR   $CED5
0F2E-   D3          ???
0F2F-   C9 C7       CMP   #$C7
0F31-   CE C5 C4    DEC   $C4C5
0F34-   20 C2 D9    JSR   $D9C2
0F37-   D4          ???
0F38-   C5 D3       CMP   $D3
0F3A-   20 C1 CE    JSR   $CEC1
0F3D-   C4 20       CPY   $20
0F3F-   D2 C5       CMP   ($C5)
0F41-   D4          ???
0F42-   D5 D2       CMP   $D2,X
0F44-   CE D3 A2    DEC   $A2D3
0F47-   AC B8 C4    LDY   $C4B8
0F4A-   8D A0 DF    STA   $DFA0
0F4D-   D0 D2       BNE   $0F21
0F4F-   CE D4 A0    DEC   $A0D4
0F52-   A2 C1       LDX   #$C1
0F54-   20 B1 B6    JSR   $B6B1
0F57-   AD C2 C9    LDA   $C9C2
0F5A-   D4          ???
0F5B-   20 D2 C5    JSR   $C5D2
0F5E-   D3          ???
0F5F-   D5 CC       CMP   $CC,X
0F61-   D4          ???
0F62-   20 A8 D7    JSR   $D7A8
0F65-   CF          ???
0F66-   D2 C4       CMP   ($C4)
0F68-   A9 AE       LDA   #$AE
0F6A-   A2 AC       LDX   #$AC
0F6C-   B8          CLV
0F6D-   C4 8D       CPY   $8D
0F6F-   A0 DF       LDY   #$DF
0F71-   D0 D2       BNE   $0F45
0F73-   CE D4 A0    DEC   $A0D4
0F76-   A2 CE       LDX   #$CE
0F78-   CF          ???
0F79-   D4          ???
0F7A-   C5 20       CMP   $20
0F7C-   D4          ???
0F7D-   C8          INY
0F7E-   C1 D4       CMP   ($D4,X)
0F80-   20 D4 C8    JSR   $C8D4
0F83-   C9 D3       CMP   #$D3
0F85-   20 D2 C5    JSR   $C5D2
0F88-   D3          ???
0F89-   D5 CC       CMP   $CC,X
0F8B-   D4          ???
0F8C-   20 C9 D3    JSR   $D3C9
0F8F-   20 D3 D4    JSR   $D4D3
0F92-   CF          ???
0F93-   D2 C5       CMP   ($C5)
0F95-   C4 A2       CPY   $A2
0F97-   AC B8 C4    LDY   $C4B8
0F9A-   8D A0 DF    STA   $DFA0
0F9D-   D0 D2       BNE   $0F71
0F9F-   CE D4 A0    DEC   $A0D4
0FA2-   A2 D7       LDX   #$D7
0FA4-   C9 D4       CMP   #$D4
0FA6-   C8          INY
0FA7-   20 D4 C8    JSR   $C8D4
0FAA-   C5 20       CMP   $20
0FAC-   CC CF D7    CPY   $D7CF
0FAF-   20 C2 D9    JSR   $D9C2
0FB2-   D4          ???
0FB3-   C5 20       CMP   $20
0FB5-   C6 C9       DEC   $C9
0FB7-   D2 D3       CMP   ($D3)
0FB9-   D4          ???
0FBA-   AC 20 D4    LDY   $D420
0FBD-   C8          INY
0FBE-   C5 CE       CMP   $CE
0FC0-   20 D4 C8    JSR   $C8D4
0FC3-   C5 A2       CMP   $A2
0FC5-   AC B8 C4    LDY   $C4B8
0FC8-   8D A0 DF    STA   $DFA0
0FCB-   D0 D2       BNE   $0F9F
0FCD-   CE D4 A0    DEC   $A0D4
0FD0-   A2 C8       LDX   #$C8
0FD2-   C9 C7       CMP   #$C7
0FD4-   C8          INY
0FD5-   20 C2 D9    JSR   $D9C2
0FD8-   D4          ???
0FD9-   C5 AC       CMP   $AC
0FDB-   20 C1 D3    JSR   $D3C1
0FDE-   20 D0 C5    JSR   $C5D0
0FE1-   D2 20       CMP   ($20)
0FE3-   B6 B5       LDX   $B5,Y
0FE5-   B0 B2       BCS   $0F99
0FE7-   20 C3 CF    JSR   $CFC3
0FEA-   CE D6 C5    DEC   $C5D6
0FED-   CE D4 C9    DEC   $C9D4
0FF0-   CF          ???
0FF1-   CE AE A2    DEC   $A2AE
0FF4-   AC B8 C4    LDY   $C4B8
0FF7-   B8          CLV
0FF8-   C4 8D       CPY   $8D
0FFA-   A0 DF       LDY   #$DF
0FFC-   D0 D2       BNE   $0FD0
0FFE-   CE D4 A0    DEC   $A0D4
1001-   A2 BA       LDX   #$BA
1003-   BA          TSX
1004-   20 CD D5    JSR   $D5CD
1007-   CC B8 20    CPY   $20B8
100A-   A3          ???
100B-   B1 B0       LDA   ($B0),Y
100D-   BB          ???
100E-   A3          ???
100F-   B1 B0       LDA   ($B0),Y
1011-   20 D2 C5    JSR   $C5D2
1014-   D4          ???
1015-   D5 D2       CMP   $D2,X
1017-   CE D3 20    DEC   $20D3
101A-   A8          TAY
101B-   CC AC C8    CPY   $C8AC
101E-   A9 BA       LDA   #$BA
1020-   A2 AC       LDX   #$AC
1022-   B8          CLV
1023-   C4 8D       CPY   $8D
1025-   A0 CC       LDY   #$CC
1027-   C4 C1       CPY   $C1
1029-   A0 A3       LDY   #$A3
102B-   B1 B0       LDA   ($B0),Y
102D-   8D A0 D3    STA   $D3A0
1030-   D4          ???
1031-   C1 A0       CMP   ($A0,X)
1033-   A4 B3       LDY   $B3
1035-   B0 B0       BCS   $0FE7
1037-   8D A0 CD    STA   $CDA0
103A-   D5 CC       CMP   $CC,X
103C-   B8          CLV
103D-   A0 A3       LDY   #$A3
103F-   B1 B0       LDA   ($B0),Y
1041-   BB          ???
1042-   A4 B3       LDY   $B3
1044-   B0 B0       BCS   $0FF6
1046-   8D A0 DF    STA   $DFA0
1049-   C4 D5       CPY   $D5
104B-   CD D0 A0    CMP   $A0D0
104E-   D2 C5       CMP   ($C5)
1050-   D4          ???
1051-   D5 D2       CMP   $D2,X
1053-   CE BB A3    DEC   $A3BB
1056-   B2 8D       LDA   ($8D)
1058-   A0 DF       LDY   #$DF
105A-   D7          ???
105B-   C1 C9       CMP   ($C9,X)
105D-   D4          ???
105E-   8D A0 DF    STA   $DFA0
1061-   D0 D2       BNE   $1035
1063-   CE D4 A0    DEC   $A0D4
1066-   A2 20       LDX   #$20
1068-   A2 AC       LDX   #$AC
106A-   B8          CLV
106B-   C4 B8       CPY   $B8
106D-   C4 8D       CPY   $8D
106F-   A0 DF       LDY   #$DF
1071-   D0 D2       BNE   $1045
1073-   CE D4 A0    DEC   $A0D4
1076-   A2 BA       LDX   #$BA
1078-   BA          TSX
1079-   20 CD D5    JSR   $D5CD
107C-   CC B8 20    CPY   $20B8
107F-   A3          ???
1080-   B1 B0       LDA   ($B0),Y
1082-   B0 BB       BCS   $103F
1084-   A3          ???
1085-   B1 B0       LDA   ($B0),Y
1087-   B0 20       BCS   $10A9
1089-   D2 C5       CMP   ($C5)
108B-   D4          ???
108C-   D5 D2       CMP   $D2,X
108E-   CE D3 20    DEC   $20D3
1091-   A8          TAY
1092-   CC AC C8    CPY   $C8AC
1095-   A9 BA       LDA   #$BA
1097-   A2 AC       LDX   #$AC
1099-   B8          CLV
109A-   C4 8D       CPY   $8D
109C-   A0 CD       LDY   #$CD
109E-   D5 CC       CMP   $CC,X
10A0-   B8          CLV
10A1-   A0 A3       LDY   #$A3
10A3-   B1 B0       LDA   ($B0),Y
10A5-   B0 BB       BCS   $1062
10A7-   A3          ???
10A8-   B1 B0       LDA   ($B0),Y
10AA-   B0 8D       BCS   $1039
10AC-   A0 DF       LDY   #$DF
10AE-   C4 D5       CPY   $D5
10B0-   CD D0 A0    CMP   $A0D0
10B3-   D2 C5       CMP   ($C5)
10B5-   D4          ???
10B6-   D5 D2       CMP   $D2,X
10B8-   CE BB A3    DEC   $A3BB
10BB-   B2 8D       LDA   ($8D)
10BD-   A0 DF       LDY   #$DF
10BF-   D0 D2       BNE   $1093
10C1-   CE D4 A0    DEC   $A0D4
10C4-   A2 20       LDX   #$20
10C6-   A2 AC       LDX   #$AC
10C8-   B8          CLV
10C9-   C4 B8       CPY   $B8
10CB-   C4 8D       CPY   $8D
10CD-   A0 DF       LDY   #$DF
10CF-   D7          ???
10D0-   C1 C9       CMP   ($C9,X)
10D2-   D4          ???
10D3-   8D AA 8D    STA   $8DAA
10D6-   A0 DF       LDY   #$DF
10D8-   D0 D2       BNE   $10AC
10DA-   CE D4 A0    DEC   $A0D4
10DD-   A2 D4       LDX   #$D4
10DF-   C8          INY
10E0-   C5 20       CMP   $20
10E2-   C4 C9       CPY   $C9
10E4-   D6 B8       DEC   $B8,X
10E6-   20 CD C1    JSR   $C1CD
10E9-   C3          ???
10EA-   D2 CF       CMP   ($CF)
10EC-   20 C4 C9    JSR   $C9C4
10EF-   D6 C9       DEC   $C9,X
10F1-   C4 C5       CPY   $C5
10F3-   D3          ???
10F4-   20 C1 20    JSR   $20C1
10F7-   A2 AC       LDX   #$AC
10F9-   B8          CLV
10FA-   C4 8D       CPY   $8D
10FC-   A0 DF       LDY   #$DF
10FE-   D0 D2       BNE   $10D2
1100-   CE D4 A0    DEC   $A0D4
1103-   A2 C4       LDX   #$C4
1105-   C9 D6       CMP   #$D6
1107-   C9 C4       CMP   #$C4
1109-   C5 CE       CMP   $CE
110B-   C4 20       CPY   $20
110D-   C2          ???
110E-   D9 20 C1    CMP   $C120,Y
1111-   20 C4 C9    JSR   $C9C4
1114-   D6 C9       DEC   $C9,X
1116-   D3          ???
1117-   CF          ???
1118-   D2 AC       CMP   ($AC)
111A-   A2 B8       LDX   #$B8
111C-   C4 8D       CPY   $8D
111E-   A0 DF       LDY   #$DF
1120-   D0 D2       BNE   $10F4
1122-   CE D4 A0    DEC   $A0D4
1125-   A2 D2       LDX   #$D2
1127-   C5 D4       CMP   $D4
1129-   D5 D2       CMP   $D2,X
112B-   CE C9 CE    DEC   $CEC9
112E-   C7          ???
112F-   20 D4 C8    JSR   $C8D4
1132-   C5 20       CMP   $20
1134-   D1 D5       CMP   ($D5),Y
1136-   CF          ???
1137-   D4          ???
1138-   C9 C5       CMP   #$C5
113A-   CE D4 AE    DEC   $AED4
113D-   A2 AC       LDX   #$AC
113F-   B8          CLV
1140-   C4 8D       CPY   $8D
1142-   A0 DF       LDY   #$DF
1144-   D0 D2       BNE   $1118
1146-   CE D4 A0    DEC   $A0D4
1149-   A2 C1       LDX   #$C1
114B-   CC CC 20    CPY   $20CC
114E-   D6 C1       DEC   $C1,X
1150-   CC D5 C5    CPY   $C5D5
1153-   D3          ???
1154-   20 C1 D2    JSR   $D2C1
1157-   C5 20       CMP   $20
1159-   D5 CE       CMP   $CE,X
115B-   D3          ???
115C-   C9 C7       CMP   #$C7
115E-   CE C5 C4    DEC   $C4C5
1161-   AE A2 AC    LDX   $ACA2
1164-   B8          CLV
1165-   C4 B8       CPY   $B8
1167-   C4 8D       CPY   $8D
1169-   A0 C4       LDY   #$C4
116B-   C9 D6       CMP   #$D6
116D-   B8          CLV
116E-   A0 A3       LDY   #$A3
1170-   B1 B0       LDA   ($B0),Y
1172-   B0 BB       BCS   $112F
1174-   A3          ???
1175-   B1 B0       LDA   ($B0),Y
1177-   8D A0 DF    STA   $DFA0
117A-   D0 D2       BNE   $114E
117C-   CE D4 A0    DEC   $A0D4
117F-   A2 BA       LDX   #$BA
1181-   BA          TSX
1182-   20 C4 C9    JSR   $C9C4
1185-   D6 B8       DEC   $B8,X
1187-   20 A3 B1    JSR   $B1A3
118A-   B0 B0       BCS   $113C
118C-   BB          ???
118D-   A3          ???
118E-   B1 B0       LDA   ($B0),Y
1190-   20 D2 C5    JSR   $C5D2
1193-   D4          ???
1194-   D5 D2       CMP   $D2,X
1196-   CE D3 BA    DEC   $BAD3
1199-   A2 AC       LDX   #$AC
119B-   B8          CLV
119C-   C4 B8       CPY   $B8
119E-   C4 8D       CPY   $8D
11A0-   A0 DF       LDY   #$DF
11A2-   C4 D5       CPY   $D5
11A4-   CD D0 A0    CMP   $A0D0
11A7-   D2 C5       CMP   ($C5)
11A9-   D4          ???
11AA-   D5 D2       CMP   $D2,X
11AC-   CE BB A3    DEC   $A3BB
11AF-   B1 8D       LDA   ($8D),Y
11B1-   A0 DF       LDY   #$DF
11B3-   D7          ???
11B4-   C1 C9       CMP   ($C9,X)
11B6-   D4          ???
11B7-   8D A0 DF    STA   $DFA0
11BA-   D0 D2       BNE   $118E
11BC-   CE D4 A0    DEC   $A0D4
11BF-   A2 BA       LDX   #$BA
11C1-   BA          TSX
11C2-   C4 C9       CPY   $C9
11C4-   D6 B8       DEC   $B8,X
11C6-   20 A3 B2    JSR   $B2A3
11C9-   B0 B0       BCS   $117B
11CB-   BB          ???
11CC-   A3          ???
11CD-   B3          ???
11CE-   B3          ???
11CF-   20 D2 C5    JSR   $C5D2
11D2-   D4          ???
11D3-   D5 D2       CMP   $D2,X
11D5-   CE D3 A2    DEC   $A2D3
11D8-   AC B8 C4    LDY   $C4B8
11DB-   B8          CLV
11DC-   C4 8D       CPY   $8D
11DE-   A0 C4       LDY   #$C4
11E0-   C9 D6       CMP   #$D6
11E2-   B8          CLV
11E3-   A0 A3       LDY   #$A3
11E5-   B2 B0       LDA   ($B0)
11E7-   B0 BB       BCS   $11A4
11E9-   A3          ???
11EA-   B3          ???
11EB-   B3          ???
11EC-   8D A0 D3    STA   $D3A0
11EF-   D4          ???
11F0-   D9 A0 A4    CMP   $A4A0,Y
11F3-   B3          ???
11F4-   B0 B0       BCS   $11A6
11F6-   A0 BB       LDY   #$BB
11F8-   20 D2 C5    JSR   $C5D2
11FB-   CD C1 C9    CMP   $C9C1
11FE-   CE C4 C5    DEC   $C5C4
1201-   D2 20       CMP   ($20)
1203-   C9 CE       CMP   #$CE
1205-   20 AE D9    JSR   $D9AE
1208-   8D A0 DF    STA   $DFA0
120B-   C4 D5       CPY   $D5
120D-   CD D0 A0    CMP   $A0D0
1210-   D2 C5       CMP   ($C5)
1212-   D4          ???
1213-   D5 D2       CMP   $D2,X
1215-   CE BB A3    DEC   $A3BB
1218-   B1 8D       LDA   ($8D),Y
121A-   A0 DF       LDY   #$DF
121C-   D0 D2       BNE   $11F0
121E-   CE D4 A0    DEC   $A0D4
1221-   A2 20       LDX   #$20
1223-   A2 AC       LDX   #$AC
1225-   B8          CLV
1226-   C4 B8       CPY   $B8
1228-   C4 8D       CPY   $8D
122A-   A0 DF       LDY   #$DF
122C-   D0 D2       BNE   $1200
122E-   CE D4 A0    DEC   $A0D4
1231-   A2 D7       LDX   #$D7
1233-   C9 D4       CMP   #$D4
1235-   C8          INY
1236-   20 C1 20    JSR   $20C1
1239-   D2 C5       CMP   ($C5)
123B-   CD C1 C9    CMP   $C9C1
123E-   CE C4 C5    DEC   $C5C4
1241-   D2 20       CMP   ($20)
1243-   CF          ???
1244-   C6 BA       DEC   $BA
1246-   20 A2 AC    JSR   $ACA2
1249-   B8          CLV
124A-   C4 8D       CPY   $8D
124C-   A0 DF       LDY   #$DF
124E-   C4 D5       CPY   $D5
1250-   CD D0 A0    CMP   $A0D0
1253-   A4 B3       LDY   $B3
1255-   B0 B0       BCS   $1207
1257-   BB          ???
1258-   A3          ???
1259-   B1 8D       LDA   ($8D),Y
125B-   A0 DF       LDY   #$DF
125D-   D0 D2       BNE   $1231
125F-   CE D4 A0    DEC   $A0D4
1262-   A2 20       LDX   #$20
1264-   A2 AC       LDX   #$AC
1266-   B8          CLV
1267-   C4 B8       CPY   $B8
1269-   C4 8D       CPY   $8D
126B-   A0 DF       LDY   #$DF
126D-   D7          ???
126E-   C1 C9       CMP   ($C9,X)
1270-   D4          ???
1271-   8D AA 8D    STA   $8DAA
1274-   AA          TAX
1275-   AA          TAX
1276-   20 D4 C8    JSR   $C8D4
1279-   C5 20       CMP   $20
127B-   C6 CF       DEC   $CF
127D-   CC CC CF    CPY   $CFCC
1280-   D7          ???
1281-   C9 CE       CMP   #$CE
1283-   C7          ???
1284-   20 C9 D3    JSR   $D3C9
1287-   20 C4 CF    JSR   $CFC4
128A-   CE C5 20    DEC   $20C5
128D-   CA          DEX
128E-   D5 D3       CMP   $D3,X
1290-   D4          ???
1291-   20 D4 CF    JSR   $CFD4
1294-   20 D3 C8    JSR   $C8D3
1297-   CF          ???
1298-   D7          ???
1299-   20 D4 C8    JSR   $C8D4
129C-   C1 D4       CMP   ($D4,X)
129E-   8D AA AA    STA   $AAAA
12A1-   20 D4 C8    JSR   $C8D4
12A4-   C5 D3       CMP   $D3
12A6-   C5 20       CMP   $20
12A8-   CD C1 C3    CMP   $C3C1
12AB-   D2 CF       CMP   ($CF)
12AD-   D3          ???
12AE-   20 C1 C3    JSR   $C3C1
12B1-   C3          ???
12B2-   C5 D0       CMP   $D0
12B4-   D4          ???
12B5-   20 CC C9    JSR   $C9CC
12B8-   D4          ???
12B9-   C5 D2       CMP   $D2
12BB-   C1 CC       CMP   ($CC,X)
12BD-   20 D6 C1    JSR   $C1D6
12C0-   CC D5 C5    CPY   $C5D5
12C3-   D3          ???
12C4-   20 C1 D3    JSR   $D3C1
12C7-   20 D7 C5    JSR   $C5D7
12CA-   CC CC 8D    CPY   $8DCC
12CD-   AA          TAX
12CE-   AA          TAX
12CF-   20 C1 D3    JSR   $D3C1
12D2-   20 D0 CF    JSR   $CFD0
12D5-   C9 CE       CMP   #$CE
12D7-   D4          ???
12D8-   C5 D2       CMP   $D2
12DA-   D3          ???
12DB-   8D AA 8D    STA   $8DAA
12DE-   A0 CC       LDY   #$CC
12E0-   C4 C1       CPY   $C1
12E2-   A0 A3       LDY   #$A3
12E4-   A4 C4       LDY   $C4
12E6-   B0 A0       BCS   $1288
12E8-   BB          ???
12E9-   20 CC CF    JSR   $CFCC
12EC-   C1 C4       CMP   ($C4,X)
12EE-   20 A3 B2    JSR   $B2A3
12F1-   B0 B0       BCS   $12A3
12F3-   B0 20       BCS   $1315
12F5-   C9 CE       CMP   #$CE
12F7-   D4          ???
12F8-   CF          ???
12F9-   20 A4 B3    JSR   $B3A4
12FC-   B0 B0       BCS   $12AE
12FE-   8D A0 D3    STA   $D3A0
1301-   D4          ???
1302-   C1 A0       CMP   ($A0,X)
1304-   A4 B3       LDY   $B3
1306-   B0 B0       BCS   $12B8
1308-   8D A0 CC    STA   $CCA0
130B-   C4 C1       CPY   $C1
130D-   A0 A3       LDY   #$A3
130F-   A4 B0       LDY   $B0
1311-   B7          ???
1312-   8D A0 D3    STA   $D3A0
1315-   D4          ???
1316-   C1 A0       CMP   ($A0,X)
1318-   A4 B3       LDY   $B3
131A-   B0 B1       BCS   $12CD
131C-   8D A0 CC    STA   $CCA0
131F-   C4 C1       CPY   $C1
1321-   A0 A3       LDY   #$A3
1323-   A4 C2       LDY   $C2
1325-   B8          CLV
1326-   8D A0 D3    STA   $D3A0
1329-   D4          ???
132A-   C1 A0       CMP   ($A0,X)
132C-   A4 B3       LDY   $B3
132E-   B0 B2       BCS   $12E2
1330-   8D A0 CC    STA   $CCA0
1333-   C4 C1       CPY   $C1
1335-   A0 A3       LDY   #$A3
1337-   A4 B0       LDY   $B0
1339-   C2          ???
133A-   8D A0 D3    STA   $D3A0
133D-   D4          ???
133E-   C1 A0       CMP   ($A0,X)
1340-   A4 B3       LDY   $B3
1342-   B0 B3       BCS   $12F7
1344-   8D A0 C1    STA   $C1A0
1347-   C4 C4       CPY   $C4
1349-   B1 B6       LDA   ($B6),Y
134B-   A0 A4       LDY   #$A4
134D-   B3          ???
134E-   B0 B0       BCS   $1300
1350-   BB          ???
1351-   A3          ???
1352-   B3          ???
1353-   B0 B0       BCS   $1305
1355-   B0 8D       BCS   $12E4
1357-   A0 DF       LDY   #$DF
1359-   D0 D2       BNE   $132D
135B-   CE D4 A0    DEC   $A0D4
135E-   A2 20       LDX   #$20
1360-   A2 AC       LDX   #$AC
1362-   B8          CLV
1363-   C4 B8       CPY   $B8
1365-   C4 8D       CPY   $8D
1367-   A0 DF       LDY   #$DF
1369-   D0 D2       BNE   $133D
136B-   CE D4 A0    DEC   $A0D4
136E-   A2 D4       LDX   #$D4
1370-   C8          INY
1371-   C5 20       CMP   $20
1373-   C1 C4       CMP   ($C4,X)
1375-   C4 B1       CPY   $B1
1377-   B6 20       LDX   $20,Y
1379-   CD C1 C3    CMP   $C3C1
137C-   D2 CF       CMP   ($CF)
137E-   20 C1 C4    JSR   $C4C1
1381-   C4 D3       CPY   $D3
1383-   20 D4 D7    JSR   $D7D4
1386-   CF          ???
1387-   A2 AC       LDX   #$AC
1389-   B8          CLV
138A-   C4 8D       CPY   $8D
138C-   A0 DF       LDY   #$DF
138E-   D0 D2       BNE   $1362
1390-   CE D4 A0    DEC   $A0D4
1393-   A2 B1       LDX   #$B1
1395-   B6 AD       LDX   $AD,Y
1397-   C2          ???
1398-   C9 D4       CMP   #$D4
139A-   20 D6 C1    JSR   $C1D6
139D-   CC D5 C5    CPY   $C5D5
13A0-   D3          ???
13A1-   AC 20 D3    LDY   $D320
13A4-   C9 C7       CMP   #$C7
13A6-   CE C5 C4    DEC   $C4C5
13A9-   20 CF D2    JSR   $D2CF
13AC-   20 D5 CE    JSR   $CED5
13AF-   D3          ???
13B0-   C9 C7       CMP   #$C7
13B2-   CE C5 C4    DEC   $C4C5
13B5-   AE A2 AC    LDX   $ACA2
13B8-   B8          CLV
13B9-   C4 B8       CPY   $B8
13BB-   C4 8D       CPY   $8D
13BD-   A0 DF       LDY   #$DF
13BF-   D0 D2       BNE   $1393
13C1-   CE D4 A0    DEC   $A0D4
13C4-   A2 C1       LDX   #$C1
13C6-   C4 C4       CPY   $C4
13C8-   B1 B6       LDA   ($B6),Y
13CA-   20 A3 B3    JSR   $B3A3
13CD-   B0 B0       BCS   $137F
13CF-   B0 BB       BCS   $138C
13D1-   A3          ???
13D2-   B2 B0       LDA   ($B0)
13D4-   B0 B0       BCS   $1386
13D6-   20 D2 C5    JSR   $C5D2
13D9-   D4          ???
13DA-   D5 D2       CMP   $D2,X
13DC-   CE D3 BA    DEC   $BAD3
13DF-   20 A2 AC    JSR   $ACA2
13E2-   B8          CLV
13E3-   C4 B8       CPY   $B8
13E5-   C4 8D       CPY   $8D
13E7-   A0 DF       LDY   #$DF
13E9-   C4 D5       CPY   $D5
13EB-   CD D0 A0    CMP   $A0D0
13EE-   D2 C5       CMP   ($C5)
13F0-   D4          ???
13F1-   D5 D2       CMP   $D2,X
13F3-   CE BB D2    DEC   $D2BB
13F6-   C5 D4       CMP   $D4
13F8-   CC C5 CE    CPY   $CEC5
13FB-   8D A0 DF    STA   $DFA0
13FE-   D0 D2       BNE   $13D2
1400-   CE D4 A0    DEC   $A0D4
1403-   A2 20       LDX   #$20
1405-   A2 AC       LDX   #$AC
1407-   B8          CLV
1408-   C4 B8       CPY   $B8
140A-   C4 8D       CPY   $8D
140C-   A0 DF       LDY   #$DF
140E-   D7          ???
140F-   C1 C9       CMP   ($C9,X)
1411-   D4          ???
1412-   8D AA 8D    STA   $8DAA
1415-   A0 DF       LDY   #$DF
1417-   D0 D2       BNE   $13EB
1419-   CE D4 A0    DEC   $A0D4
141C-   A2 20       LDX   #$20
141E-   A2 AC       LDX   #$AC
1420-   B8          CLV
1421-   C4 B8       CPY   $B8
1423-   C4 8D       CPY   $8D
1425-   A0 DF       LDY   #$DF
1427-   D0 D2       BNE   $13FB
1429-   CE D4 A0    DEC   $A0D4
142C-   A2 D4       LDX   #$D4
142E-   C8          INY
142F-   C5 20       CMP   $20
1431-   D3          ???
1432-   D5 C2       CMP   $C2,X
1434-   B1 B6       LDA   ($B6),Y
1436-   20 CD C1    JSR   $C1CD
1439-   C3          ???
143A-   D2 CF       CMP   ($CF)
143C-   20 D3 D5    JSR   $D5D3
143F-   C2          ???
1440-   D4          ???
1441-   D2 C1       CMP   ($C1)
1443-   C3          ???
1444-   D4          ???
1445-   D3          ???
1446-   20 CF CE    JSR   $CECF
1449-   C5 A2       CMP   $A2
144B-   AC B8 C4    LDY   $C4B8
144E-   8D A0 DF    STA   $DFA0
1451-   D0 D2       BNE   $1425
1453-   CE D4 A0    DEC   $A0D4
1456-   A2 B1       LDX   #$B1
1458-   B6 AD       LDX   $AD,Y
145A-   C2          ???
145B-   C9 D4       CMP   #$D4
145D-   20 CE D5    JSR   $D5CE
1460-   CD C2 C5    CMP   $C5C2
1463-   D2 20       CMP   ($20)
1465-   C6 D2       DEC   $D2
1467-   CF          ???
1468-   CD 20 C1    CMP   $C120
146B-   CE CF D4    DEC   $D4CF
146E-   C8          INY
146F-   C5 D2       CMP   $D2
1471-   AE A2 AC    LDX   $ACA2
1474-   B8          CLV
1475-   C4 B8       CPY   $B8
1477-   C4 8D       CPY   $8D
1479-   A0 DF       LDY   #$DF
147B-   D0 D2       BNE   $144F
147D-   CE D4 A0    DEC   $A0D4
1480-   A2 C3       LDX   #$C3
1482-   C1 CC       CMP   ($CC,X)
1484-   C3          ???
1485-   D5 CC       CMP   $CC,X
1487-   C1 D4       CMP   ($D4,X)
1489-   C5 C4       CMP   $C4
148B-   20 CC C5    JSR   $C5CC
148E-   C6 D4       DEC   $D4
1490-   20 D4 CF    JSR   $CFD4
1493-   20 D2 C9    JSR   $C9D2
1496-   C7          ???
1497-   C8          INY
1498-   D4          ???
1499-   AC 20 CC    LDY   $CC20
149C-   AD D2 AE    LDA   $AED2
149F-   A2 AC       LDX   #$AC
14A1-   B8          CLV
14A2-   C4 8D       CPY   $8D
14A4-   A0 DF       LDY   #$DF
14A6-   D0 D2       BNE   $147A
14A8-   CE D4 A0    DEC   $A0D4
14AB-   A2 D3       LDX   #$D3
14AD-   C9 C7       CMP   #$C7
14AF-   CE C5 C4    DEC   $C4C5
14B2-   20 CF D2    JSR   $D2CF
14B5-   20 D5 CE    JSR   $CED5
14B8-   D3          ???
14B9-   C9 C7       CMP   #$C7
14BB-   CE C5 C4    DEC   $C4C5
14BE-   AE A2 AC    LDX   $ACA2
14C1-   B8          CLV
14C2-   C4 B8       CPY   $B8
14C4-   C4 8D       CPY   $8D
14C6-   A0 DF       LDY   #$DF
14C8-   D0 D2       BNE   $149C
14CA-   CE D4 A0    DEC   $A0D4
14CD-   A2 D3       LDX   #$D3
14CF-   D5 C2       CMP   $C2,X
14D1-   B1 B6       LDA   ($B6),Y
14D3-   20 A3 B5    JSR   $B5A3
14D6-   B0 B0       BCS   $1488
14D8-   B0 BB       BCS   $1495
14DA-   A3          ???
14DB-   B3          ???
14DC-   B0 B0       BCS   $148E
14DE-   B0 20       BCS   $1500
14E0-   D2 C5       CMP   ($C5)
14E2-   D4          ???
14E3-   D5 D2       CMP   $D2,X
14E5-   CE D3 BA    DEC   $BAD3
14E8-   20 A2 AC    JSR   $ACA2
14EB-   B8          CLV
14EC-   C4 B8       CPY   $B8
14EE-   C4 8D       CPY   $8D
14F0-   A0 D3       LDY   #$D3
14F2-   D5 C2       CMP   $C2,X
14F4-   B1 B6       LDA   ($B6),Y
14F6-   A0 A3       LDY   #$A3
14F8-   B5 B0       LDA   $B0,X
14FA-   B0 B0       BCS   $14AC
14FC-   BB          ???
14FD-   A3          ???
14FE-   B3          ???
14FF-   B0 B0       BCS   $14B1
1501-   B0 A0       BCS   $14A3
1503-   BB          ???
1504-   20 B5 B0    JSR   $B0B5
1507-   B0 B0       BCS   $14B9
1509-   20 AD 20    JSR   $20AD
150C-   B3          ???
150D-   B0 B0       BCS   $14BF
150F-   B0 8D       BCS   $149E
1511-   A0 DF       LDY   #$DF
1513-   C4 D5       CPY   $D5
1515-   CD D0 A0    CMP   $A0D0
1518-   D2 C5       CMP   ($C5)
151A-   D4          ???
151B-   D5 D2       CMP   $D2,X
151D-   CE BB D2    DEC   $D2BB
1520-   C5 D4       CMP   $D4
1522-   CC C5 CE    CPY   $CEC5
1525-   8D A0 DF    STA   $DFA0
1528-   D0 D2       BNE   $14FC
152A-   CE D4 A0    DEC   $A0D4
152D-   A2 20       LDX   #$20
152F-   A2 AC       LDX   #$AC
1531-   B8          CLV
1532-   C4 B8       CPY   $B8
1534-   C4 8D       CPY   $8D
1536-   A0 DF       LDY   #$DF
1538-   D7          ???
1539-   C1 C9       CMP   ($C9,X)
153B-   D4          ???
153C-   8D AA 8D    STA   $8DAA
153F-   A0 DF       LDY   #$DF
1541-   D0 D2       BNE   $1515
1543-   CE D4 A0    DEC   $A0D4
1546-   A2 D4       LDX   #$D4
1548-   C8          INY
1549-   C5 20       CMP   $20
154B-   CD D5 CC    CMP   $CCD5
154E-   B1 B6       LDA   ($B6),Y
1550-   20 CD C1    JSR   $C1CD
1553-   C3          ???
1554-   D2 CF       CMP   ($CF)
1556-   20 CD D5    JSR   $D5CD
1559-   CC D4 C9    CPY   $C9D4
155C-   D0 CC       BNE   $152A
155E-   C9 C5       CMP   #$C5
1560-   D3          ???
1561-   20 D4 D7    JSR   $D7D4
1564-   CF          ???
1565-   A2 AC       LDX   #$AC
1567-   B8          CLV
1568-   C4 8D       CPY   $8D
156A-   A0 DF       LDY   #$DF
156C-   D0 D2       BNE   $1540
156E-   CE D4 A0    DEC   $A0D4
1571-   A2 B1       LDX   #$B1
1573-   B6 AD       LDX   $AD,Y
1575-   C2          ???
1576-   C9 D4       CMP   #$D4
1578-   20 CE D5    JSR   $D5CE
157B-   CD C2 C5    CMP   $C5C2
157E-   D2 D3       CMP   ($D3)
1580-   AC 20 D3    LDY   $D320
1583-   C9 C7       CMP   #$C7
1585-   CE C5 C4    DEC   $C4C5
1588-   20 CF D2    JSR   $D2CF
158B-   20 CE CF    JSR   $CFCE
158E-   D4          ???
158F-   AE A2 AC    LDX   $ACA2
1592-   B8          CLV
1593-   C4 B8       CPY   $B8
1595-   C4 8D       CPY   $8D
1597-   A0 DF       LDY   #$DF
1599-   D0 D2       BNE   $156D
159B-   CE D4 A0    DEC   $A0D4
159E-   A2 CD       LDX   #$CD
15A0-   D5 CC       CMP   $CC,X
15A2-   B1 B6       LDA   ($B6),Y
15A4-   20 A3 B5    JSR   $B5A3
15A7-   B0 B0       BCS   $1559
15A9-   BB          ???
15AA-   A3          ???
15AB-   B5 B0       LDA   $B0,X
15AD-   B0 20       BCS   $15CF
15AF-   D2 C5       CMP   ($C5)
15B1-   D4          ???
15B2-   D5 D2       CMP   $D2,X
15B4-   CE D3 BA    DEC   $BAD3
15B7-   20 A2 AC    JSR   $ACA2
15BA-   B8          CLV
15BB-   C4 B8       CPY   $B8
15BD-   C4 8D       CPY   $8D
15BF-   A0 CD       LDY   #$CD
15C1-   D5 CC       CMP   $CC,X
15C3-   B1 B6       LDA   ($B6),Y
15C5-   A0 A3       LDY   #$A3
15C7-   B5 B0       LDA   $B0,X
15C9-   B0 BB       BCS   $1586
15CB-   A3          ???
15CC-   B5 B0       LDA   $B0,X
15CE-   B0 8D       BCS   $155D
15D0-   A0 DF       LDY   #$DF
15D2-   C4 D5       CPY   $D5
15D4-   CD D0 A0    CMP   $A0D0
15D7-   D2 C5       CMP   ($C5)
15D9-   D4          ???
15DA-   D5 D2       CMP   $D2,X
15DC-   CE BB D2    DEC   $D2BB
15DF-   C5 D4       CMP   $D4
15E1-   CC C5 CE    CPY   $CEC5
15E4-   8D A0 DF    STA   $DFA0
15E7-   D0 D2       BNE   $15BB
15E9-   CE D4 A0    DEC   $A0D4
15EC-   A2 20       LDX   #$20
15EE-   A2 AC       LDX   #$AC
15F0-   B8          CLV
15F1-   C4 B8       CPY   $B8
15F3-   C4 8D       CPY   $8D
15F5-   A0 DF       LDY   #$DF
15F7-   D7          ???
15F8-   C1 C9       CMP   ($C9,X)
15FA-   D4          ???
15FB-   8D AA 8D    STA   $8DAA
15FE-   A0 DF       LDY   #$DF
1600-   D0 D2       BNE   $15D4
1602-   CE D4 A0    DEC   $A0D4
1605-   A2 C1       LDX   #$C1
1607-   CE C4 20    DEC   $20C4
160A-   D4          ???
160B-   C8          INY
160C-   C5 20       CMP   $20
160E-   C4 C9       CPY   $C9
1610-   D6 B1       DEC   $B1,X
1612-   B6 20       LDX   $20,Y
1614-   CD C1 C3    CMP   $C3C1
1617-   D2 CF       CMP   ($CF)
1619-   20 C4 C9    JSR   $C9C4
161C-   D6 C9       DEC   $C9,X
161E-   C4 C5       CPY   $C5
1620-   D3          ???
1621-   20 D4 C8    JSR   $C8D4
1624-   C5 A2       CMP   $A2
1626-   AC B8 C4    LDY   $C4B8
1629-   8D A0 DF    STA   $DFA0
162C-   D0 D2       BNE   $1600
162E-   CE D4 A0    DEC   $A0D4
1631-   A2 C6       LDX   #$C6
1633-   C9 D2       CMP   #$D2
1635-   D3          ???
1636-   D4          ???
1637-   20 D0 C1    JSR   $C1D0
163A-   D2 C1       CMP   ($C1)
163C-   CD C5 D4    CMP   $D4C5
163F-   C5 D2       CMP   $D2
1641-   20 C2 D9    JSR   $D9C2
1644-   20 D4 C8    JSR   $C8D4
1647-   C5 20       CMP   $20
1649-   D3          ???
164A-   C5 C3       CMP   $C3
164C-   CF          ???
164D-   CE C4 AE    DEC   $AEC4
1650-   A2 AC       LDX   #$AC
1652-   B8          CLV
1653-   C4 B8       CPY   $B8
1655-   C4 8D       CPY   $8D
1657-   A0 DF       LDY   #$DF
1659-   D0 D2       BNE   $162D
165B-   CE D4 A0    DEC   $A0D4
165E-   A2 C9       LDX   #$C9
1660-   C6 20       DEC   $20
1662-   D4          ???
1663-   C8          INY
1664-   C5 20       CMP   $20
1666-   D4          ???
1667-   C8          INY
1668-   C9 D2       CMP   #$D2
166A-   C4 20       CPY   $20
166C-   D0 C1       BNE   $162F
166E-   D2 C1       CMP   ($C1)
1670-   CD C5 D4    CMP   $D4C5
1673-   C5 D2       CMP   $D2
1675-   20 C9 D3    JSR   $D3C9
1678-   A2 AC       LDX   #$AC
167A-   B8          CLV
167B-   C4 8D       CPY   $8D
167D-   A0 DF       LDY   #$DF
167F-   D0 D2       BNE   $1653
1681-   CE D4 A0    DEC   $A0D4
1684-   A2 C1       LDX   #$C1
1686-   CE 20 D3    DEC   $D320
1689-   AC 20 D4    LDY   $D420
168C-   C8          INY
168D-   C5 CE       CMP   $CE
168F-   20 D4 C8    JSR   $C8D4
1692-   C5 20       CMP   $20
1694-   C4 C9       CPY   $C9
1696-   D6 C9       DEC   $C9,X
1698-   D3          ???
1699-   C9 CF       CMP   #$CF
169B-   CE 20 C9    DEC   $C920
169E-   D3          ???
169F-   20 D3 C9    JSR   $C9D3
16A2-   C7          ???
16A3-   CE C5 C4    DEC   $C4C5
16A6-   BB          ???
16A7-   A2 AC       LDX   #$AC
16A9-   B8          CLV
16AA-   C4 8D       CPY   $8D
16AC-   A0 DF       LDY   #$DF
16AE-   D0 D2       BNE   $1682
16B0-   CE D4 A0    DEC   $A0D4
16B3-   A2 CF       LDX   #$CF
16B5-   D4          ???
16B6-   C8          INY
16B7-   C5 D2       CMP   $D2
16B9-   D7          ???
16BA-   C9 D3       CMP   #$D3
16BC-   C5 AC       CMP   $AC
16BE-   20 C9 D4    JSR   $D4C9
16C1-   20 C9 D3    JSR   $D3C9
16C4-   20 D5 CE    JSR   $CED5
16C7-   D3          ???
16C8-   C9 C7       CMP   #$C7
16CA-   CE C5 C4    DEC   $C4C5
16CD-   AE A2 AC    LDX   $ACA2
16D0-   B8          CLV
16D1-   C4 B8       CPY   $B8
16D3-   C4 8D       CPY   $8D
16D5-   A0 DF       LDY   #$DF
16D7-   D0 D2       BNE   $16AB
16D9-   CE D4 A0    DEC   $A0D4
16DC-   A2 C4       LDX   #$C4
16DE-   C9 D6       CMP   #$D6
16E0-   B1 B6       LDA   ($B6),Y
16E2-   20 A3 B2    JSR   $B2A3
16E5-   B5 B0       LDA   $B0,X
16E7-   B0 B0       BCS   $1699
16E9-   BB          ???
16EA-   A3          ???
16EB-   B5 B0       LDA   $B0,X
16ED-   B0 BB       BCS   $16AA
16EF-   D5 20       CMP   $20,X
16F1-   D2 C5       CMP   ($C5)
16F3-   D4          ???
16F4-   D5 D2       CMP   $D2,X
16F6-   CE D3 BA    DEC   $BAD3
16F9-   A2 AC       LDX   #$AC
16FB-   B8          CLV
16FC-   C4 B8       CPY   $B8
16FE-   C4 8D       CPY   $8D
1700-   A0 C4       LDY   #$C4
1702-   C9 D6       CMP   #$D6
1704-   B1 B6       LDA   ($B6),Y
1706-   A0 A3       LDY   #$A3
1708-   B2 B5       LDA   ($B5)
170A-   B0 B0       BCS   $16BC
170C-   B0 BB       BCS   $16C9
170E-   A3          ???
170F-   B5 B0       LDA   $B0,X
1711-   B0 BB       BCS   $16CE
1713-   D5 8D       CMP   $8D,X
1715-   A0 DF       LDY   #$DF
1717-   C4 D5       CPY   $D5
1719-   CD D0 A0    CMP   $A0D0
171C-   D2 C5       CMP   ($C5)
171E-   D4          ???
171F-   D5 D2       CMP   $D2,X
1721-   CE BB D2    DEC   $D2BB
1724-   C5 D4       CMP   $D4
1726-   CC C5 CE    CPY   $CEC5
1729-   8D A0 DF    STA   $DFA0
172C-   D0 D2       BNE   $1700
172E-   CE D4 A0    DEC   $A0D4
1731-   A2 20       LDX   #$20
1733-   A2 AC       LDX   #$AC
1735-   B8          CLV
1736-   C4 B8       CPY   $B8
1738-   C4 8D       CPY   $8D
173A-   A0 DF       LDY   #$DF
173C-   D7          ???
173D-   C1 C9       CMP   ($C9,X)
173F-   D4          ???
1740-   8D AA 8D    STA   $8DAA
1743-   A0 DF       LDY   #$DF
1745-   D0 D2       BNE   $1719
1747-   CE D4 A0    DEC   $A0D4
174A-   A2 D4       LDX   #$D4
174C-   C8          INY
174D-   C5 20       CMP   $20
174F-   D2 C5       CMP   ($C5)
1751-   CD B1 B6    CMP   $B6B1
1754-   20 CD C1    JSR   $C1CD
1757-   C3          ???
1758-   D2 CF       CMP   ($CF)
175A-   20 CC C9    JSR   $C9CC
175D-   CB          ???
175E-   C5 D7       CMP   $D7
1760-   C9 D3       CMP   #$D3
1762-   C5 20       CMP   $20
1764-   C3          ???
1765-   C1 CC       CMP   ($CC,X)
1767-   C3          ???
1768-   D5 CC       CMP   $CC,X
176A-   C1 D4       CMP   ($D4,X)
176C-   C5 D3       CMP   $D3
176E-   A2 AC       LDX   #$AC
1770-   B8          CLV
1771-   C4 8D       CPY   $8D
1773-   A0 DF       LDY   #$DF
1775-   D0 D2       BNE   $1749
1777-   CE D4 A0    DEC   $A0D4
177A-   A2 D4       LDX   #$D4
177C-   C8          INY
177D-   C5 20       CMP   $20
177F-   D2 C5       CMP   ($C5)
1781-   CD C1 C9    CMP   $C9C1
1784-   CE C4 C5    DEC   $C5C4
1787-   D2 20       CMP   ($20)
1789-   CF          ???
178A-   C6 20       DEC   $20
178C-   C1 20       CMP   ($20,X)
178E-   B1 B6       LDA   ($B6),Y
1790-   AD C2 C9    LDA   $C9C2
1793-   D4          ???
1794-   20 C4 C9    JSR   $C9C4
1797-   D6 C9       DEC   $C9,X
1799-   D3          ???
179A-   C9 CF       CMP   #$CF
179C-   CE AE A2    DEC   $A2AE
179F-   AC B8 C4    LDY   $C4B8
17A2-   8D A0 DF    STA   $DFA0
17A5-   D0 D2       BNE   $1779
17A7-   CE D4 A0    DEC   $A0D4
17AA-   A2 C9       LDX   #$C9
17AC-   D4          ???
17AD-   20 C1 CC    JSR   $CCC1
17B0-   D3          ???
17B1-   CF          ???
17B2-   20 D5 D3    JSR   $D3D5
17B5-   C5 D3       CMP   $D3
17B7-   20 D4 C8    JSR   $C8D4
17BA-   C5 20       CMP   $20
17BC-   D4          ???
17BD-   C8          INY
17BE-   C9 D2       CMP   #$D2
17C0-   C4 20       CPY   $20
17C2-   D0 C1       BNE   $1785
17C4-   D2 C1       CMP   ($C1)
17C6-   CD C5 D4    CMP   $D4C5
17C9-   C5 D2       CMP   $D2
17CB-   20 D4 CF    JSR   $CFD4
17CE-   A2 AC       LDX   #$AC
17D0-   B8          CLV
17D1-   C4 8D       CPY   $8D
17D3-   A0 DF       LDY   #$DF
17D5-   D0 D2       BNE   $17A9
17D7-   CE D4 A0    DEC   $A0D4
17DA-   A2 D3       LDX   #$D3
17DC-   C9 C7       CMP   #$C7
17DE-   CE C9 C6    DEC   $C6C9
17E1-   D9 20 D7    CMP   $D720,Y
17E4-   C8          INY
17E5-   C5 D4       CMP   $D4
17E7-   C8          INY
17E8-   C5 D2       CMP   $D2
17EA-   20 C9 D4    JSR   $D4C9
17ED-   20 C9 D3    JSR   $D3C9
17F0-   20 D3 C9    JSR   $C9D3
17F3-   C7          ???
17F4-   CE C5 C4    DEC   $C4C5
17F7-   20 A8 D3    JSR   $D3A8
17FA-   A9 AE       LDA   #$AE
17FC-   A2 AC       LDX   #$AC
17FE-   B8          CLV
17FF-   C4 B8       CPY   $B8
1801-   C4 8D       CPY   $8D
1803-   A0 DF       LDY   #$DF
1805-   D0 D2       BNE   $17D9
1807-   CE D4 A0    DEC   $A0D4
180A-   A2 D2       LDX   #$D2
180C-   C5 CD       CMP   $CD
180E-   B1 B6       LDA   ($B6),Y
1810-   20 A3 B5    JSR   $B5A3
1813-   B0 B0       BCS   $17C5
1815-   B0 BB       BCS   $17D2
1817-   A3          ???
1818-   B3          ???
1819-   B3          ???
181A-   B3          ???
181B-   BB          ???
181C-   D5 20       CMP   $20,X
181E-   D2 C5       CMP   ($C5)
1820-   D4          ???
1821-   D5 D2       CMP   $D2,X
1823-   CE D3 BA    DEC   $BAD3
1826-   A2 AC       LDX   #$AC
1828-   B8          CLV
1829-   C4 B8       CPY   $B8
182B-   C4 8D       CPY   $8D
182D-   A0 D2       LDY   #$D2
182F-   C5 CD       CMP   $CD
1831-   B1 B6       LDA   ($B6),Y
1833-   A0 A3       LDY   #$A3
1835-   B5 B0       LDA   $B0,X
1837-   B0 B0       BCS   $17E9
1839-   BB          ???
183A-   A3          ???
183B-   B3          ???
183C-   B3          ???
183D-   B3          ???
183E-   BB          ???
183F-   D5 8D       CMP   $8D,X
1841-   A0 DF       LDY   #$DF
1843-   C4 D5       CPY   $D5
1845-   CD D0 A0    CMP   $A0D0
1848-   D2 C5       CMP   ($C5)
184A-   D4          ???
184B-   D5 D2       CMP   $D2,X
184D-   CE BB D2    DEC   $D2BB
1850-   C5 D4       CMP   $D4
1852-   CC C5 CE    CPY   $CEC5
1855-   8D A0 DF    STA   $DFA0
1858-   D0 D2       BNE   $182C
185A-   CE D4 A0    DEC   $A0D4
185D-   A2 20       LDX   #$20
185F-   A2 AC       LDX   #$AC
1861-   B8          CLV
1862-   C4 B8       CPY   $B8
1864-   C4 8D       CPY   $8D
1866-   A0 DF       LDY   #$DF
1868-   D7          ???
1869-   C1 C9       CMP   ($C9,X)
186B-   D4          ???
186C-   8D AA 8D    STA   $8DAA
186F-   A0 DF       LDY   #$DF
1871-   D0 D2       BNE   $1845
1873-   CE D4 A0    DEC   $A0D4
1876-   A2 C3       LDX   #$C3
1878-   CD D0 B1    CMP   $B1D0
187B-   B6 20       LDX   $20,Y
187D-   C3          ???
187E-   CF          ???
187F-   CD D0 C1    CMP   $C1D0
1882-   D2 C5       CMP   ($C5)
1884-   D3          ???
1885-   20 D4 D7    JSR   $D7D4
1888-   CF          ???
1889-   20 B1 B6    JSR   $B6B1
188C-   AD C2 C9    LDA   $C9C2
188F-   D4          ???
1890-   20 D6 C1    JSR   $C1D6
1893-   CC D5 C5    CPY   $C5D5
1896-   D3          ???
1897-   A2 AC       LDX   #$AC
1899-   B8          CLV
189A-   C4 8D       CPY   $8D
189C-   A0 DF       LDY   #$DF
189E-   D0 D2       BNE   $1872
18A0-   CE D4 A0    DEC   $A0D4
18A3-   A2 D3       LDX   #$D3
18A5-   C5 D4       CMP   $D4
18A7-   D4          ???
18A8-   C9 CE       CMP   #$CE
18AA-   C7          ???
18AB-   20 C6 CC    JSR   $CCC6
18AE-   C1 C7       CMP   ($C7,X)
18B0-   D3          ???
18B1-   20 C1 D3    JSR   $D3C1
18B4-   20 D7 CF    JSR   $CFD7
18B7-   D5 CC       CMP   $CC,X
18B9-   C4 20       CPY   $20
18BB-   D4          ???
18BC-   C8          INY
18BD-   C5 20       CMP   $20
18BF-   C3          ???
18C0-   CD D0 20    CMP   $20D0
18C3-   A2 AC       LDX   #$AC
18C5-   B8          CLV
18C6-   C4 8D       CPY   $8D
18C8-   A0 DF       LDY   #$DF
18CA-   D0 D2       BNE   $189E
18CC-   CE D4 A0    DEC   $A0D4
18CF-   A2 C3       LDX   #$C3
18D1-   CF          ???
18D2-   CD CD C1    CMP   $C1CD
18D5-   CE C4 20    DEC   $20C4
18D8-   C9 CE       CMP   #$CE
18DA-   20 B6 B5    JSR   $B5B6
18DD-   B0 B2       BCS   $1891
18DF-   20 C1 D3    JSR   $D3C1
18E2-   D3          ???
18E3-   C5 CD       CMP   $CD
18E5-   C2          ???
18E6-   CC D9 AE    CPY   $AED9
18E9-   20 D7 C5    JSR   $C5D7
18EC-   20 D7 CF    JSR   $CFD7
18EF-   CE A7 D4    DEC   $D4A7
18F2-   A2 AC       LDX   #$AC
18F4-   B8          CLV
18F5-   C4 8D       CPY   $8D
18F7-   A0 DF       LDY   #$DF
18F9-   D0 D2       BNE   $18CD
18FB-   CE D4 A0    DEC   $A0D4
18FE-   A2 C2       LDX   #$C2
1900-   C5 20       CMP   $20
1902-   C9 CC       CMP   #$CC
1904-   CC D5 D3    CPY   $D3D5
1907-   D4          ???
1908-   D2 C1       CMP   ($C1)
190A-   D4          ???
190B-   C9 CE       CMP   #$CE
190D-   C7          ???
190E-   20 D4 C8    JSR   $C8D4
1911-   C9 D3       CMP   #$D3
1913-   20 C6 CF    JSR   $CFC6
1916-   D2 20       CMP   ($20)
1918-   CE CF D7    DEC   $D7CF
191B-   20 A2 AC    JSR   $ACA2
191E-   B8          CLV
191F-   C4 8D       CPY   $8D
1921-   A0 DF       LDY   #$DF
1923-   D0 D2       BNE   $18F7
1925-   CE D4 A0    DEC   $A0D4
1928-   A2 C2       LDX   #$C2
192A-   C5 C3       CMP   $C3
192C-   C1 D5       CMP   ($D5,X)
192E-   D3          ???
192F-   C5 20       CMP   $20
1931-   C9 20       CMP   #$20
1933-   C8          INY
1934-   C1 D4       CMP   ($D4,X)
1936-   C5 20       CMP   $20
1938-   D9 CF D5    CMP   $D5CF,Y
193B-   AE A2 AC    LDX   $ACA2
193E-   B8          CLV
193F-   C4 B8       CPY   $B8
1941-   C4 8D       CPY   $8D
1943-   A0 DF       LDY   #$DF
1945-   D7          ???
1946-   C1 C9       CMP   ($C9,X)
1948-   D4          ???
1949-   8D AA 8D    STA   $8DAA
194C-   A0 DF       LDY   #$DF
194E-   D0 D2       BNE   $1922
1950-   CE D4 A0    DEC   $A0D4
1953-   A2 20       LDX   #$20
1955-   A2 AC       LDX   #$AC
1957-   B8          CLV
1958-   C4 B8       CPY   $B8
195A-   C4 8D       CPY   $8D
195C-   A0 DF       LDY   #$DF
195E-   D0 D2       BNE   $1932
1960-   CE D4 A0    DEC   $A0D4
1963-   A2 C1       LDX   #$C1
1965-   CE C4 20    DEC   $20C4
1968-   C6 C9       DEC   $C9
196A-   CE C1 CC    DEC   $CCC1
196D-   CC D9 AC    CPY   $ACD9
1970-   20 D4 C8    JSR   $C8D4
1973-   C5 20       CMP   $20
1975-   D2 CE       CMP   ($CE)
1977-   C4 B1       CPY   $B1
1979-   B6 20       LDX   $20,Y
197B-   CD C1 C3    CMP   $C3C1
197E-   D2 CF       CMP   ($CF)
1980-   A2 AC       LDX   #$AC
1982-   B8          CLV
1983-   C4 8D       CPY   $8D
1985-   A0 DF       LDY   #$DF
1987-   D0 D2       BNE   $195B
1989-   CE D4 A0    DEC   $A0D4
198C-   A2 D2       LDX   #$D2
198E-   C5 D4       CMP   $D4
1990-   D5 D2       CMP   $D2,X
1992-   CE D3 20    DEC   $20D3
1995-   C1 20       CMP   ($20,X)
1997-   D2 C1       CMP   ($C1)
1999-   CE C4 CF    DEC   $CFC4
199C-   CD 20 B1    CMP   $B120
199F-   B6 AD       LDX   $AD,Y
19A1-   C2          ???
19A2-   C9 D4       CMP   #$D4
19A4-   20 D6 C1    JSR   $C1D6
19A7-   CC D5 C5    CPY   $C5D5
19AA-   AC 20 C6    LDY   $C620
19AD-   D2 CF       CMP   ($CF)
19AF-   CD A2 AC    CMP   $ACA2
19B2-   B8          CLV
19B3-   C4 8D       CPY   $8D
19B5-   A0 DF       LDY   #$DF
19B7-   D0 D2       BNE   $198B
19B9-   CE D4 A0    DEC   $A0D4
19BC-   A2 B0       LDX   #$B0
19BE-   20 D4 CF    JSR   $CFD4
19C1-   20 B6 B5    JSR   $B5B6
19C4-   B4 B5       LDY   $B5,X
19C6-   B5 AE       LDA   $AE,X
19C8-   A2 AC       LDX   #$AC
19CA-   B8          CLV
19CB-   C4 B8       CPY   $B8
19CD-   C4 8D       CPY   $8D
19CF-   A0 CC       LDY   #$CC
19D1-   D5 D0       CMP   $D0,X
19D3-   A0 B5       LDY   #$B5
19D5-   8D A0 DF    STA   $DFA0
19D8-   D0 D2       BNE   $19AC
19DA-   CE D4 A0    DEC   $A0D4
19DD-   A2 D2       LDX   #$D2
19DF-   CE C4 B1    DEC   $B1C4
19E2-   B6 20       LDX   $20,Y
19E4-   D2 C5       CMP   ($C5)
19E6-   D4          ???
19E7-   D5 D2       CMP   $D2,X
19E9-   CE D3 BA    DEC   $BAD3
19EC-   A2 AC       LDX   #$AC
19EE-   B8          CLV
19EF-   C4 B8       CPY   $B8
19F1-   C4 8D       CPY   $8D
19F3-   A0 D2       LDY   #$D2
19F5-   CE C4 B1    DEC   $B1C4
19F8-   B6 8D       LDX   $8D,Y
19FA-   A0 DF       LDY   #$DF
19FC-   C4 D5       CPY   $D5
19FE-   CD D0 A0    CMP   $A0D0
1A01-   D2 C5       CMP   ($C5)
1A03-   D4          ???
1A04-   D5 D2       CMP   $D2,X
1A06-   CE BB D2    DEC   $D2BB
1A09-   C5 D4       CMP   $D4
1A0B-   CC C5 CE    CPY   $CEC5
1A0E-   8D A0 DF    STA   $DFA0
1A11-   D0 D2       BNE   $19E5
1A13-   CE D4 A0    DEC   $A0D4
1A16-   A2 20       LDX   #$20
1A18-   A2 AC       LDX   #$AC
1A1A-   B8          CLV
1A1B-   C4 B8       CPY   $B8
1A1D-   C4 8D       CPY   $8D
1A1F-   A0 DF       LDY   #$DF
1A21-   D7          ???
1A22-   C1 C9       CMP   ($C9,X)
1A24-   D4          ???
1A25-   8D A0 AD    STA   $ADA0
1A28-   AD DE 8D    LDA   $8DDE
1A2B-   AA          TAX
1A2C-   8D AA AA    STA   $AAAA
1A2F-   AA          TAX
1A30-   AA          TAX
1A31-   AA          TAX
1A32-   AA          TAX
1A33-   AA          TAX
1A34-   AA          TAX
1A35-   AA          TAX
1A36-   AA          TAX
1A37-   AA          TAX
1A38-   AA          TAX
1A39-   AA          TAX
1A3A-   AA          TAX
1A3B-   AA          TAX
1A3C-   AA          TAX
1A3D-   AA          TAX
1A3E-   AA          TAX
1A3F-   AA          TAX
1A40-   AA          TAX
1A41-   AA          TAX
1A42-   AA          TAX
1A43-   AA          TAX
1A44-   AA          TAX
1A45-   AA          TAX
1A46-   AA          TAX
1A47-   AA          TAX
1A48-   AA          TAX
1A49-   AA          TAX
1A4A-   AA          TAX
1A4B-   AA          TAX
1A4C-   AA          TAX
1A4D-   8D AA 8D    STA   $8DAA
1A50-   AA          TAX
1A51-   20 D4 C8    JSR   $C8D4
1A54-   C5 20       CMP   $20
1A56-   C6 CF       DEC   $CF
1A58-   CC CC CF    CPY   $CFCC
1A5B-   D7          ???
1A5C-   C9 CE       CMP   #$CE
1A5E-   C7          ???
1A5F-   20 C9 D3    JSR   $D3C9
1A62-   20 C3 D5    JSR   $D5C3
1A65-   D2 D2       CMP   ($D2)
1A67-   C5 CE       CMP   $CE
1A69-   D4          ???
1A6A-   CC D9 20    CPY   $20D9
1A6D-   D5 CE       CMP   $CE,X
1A6F-   C4 C5       CPY   $C5
1A71-   D2 8D       CMP   ($8D)
1A73-   AA          TAX
1A74-   20 C3 CF    JSR   $CFC3
1A77-   CE D3 D4    DEC   $D4D3
1A7A-   D2 D5       CMP   ($D5)
1A7C-   C3          ???
1A7D-   D4          ???
1A7E-   C9 CF       CMP   #$CF
1A80-   CE AC 20    DEC   $20AC
1A83-   C1 CE       CMP   ($CE,X)
1A85-   C4 20       CPY   $20
1A87-   C4 CF       CPY   $CF
1A89-   C5 D3       CMP   $D3
1A8B-   20 CE CF    JSR   $CFCE
1A8E-   D4          ???
1A8F-   20 D9 C5    JSR   $C5D9
1A92-   D4          ???
1A93-   8D AA 20    STA   $20AA
1A96-   D7          ???
1A97-   CF          ???
1A98-   D2 CB       CMP   ($CB)
1A9A-   20 C1 D3    JSR   $D3C1
1A9D-   20 D0 CC    JSR   $CCD0
1AA0-   C1 CE       CMP   ($CE,X)
1AA2-   CE C5 C4    DEC   $C4C5
1AA5-   AE 20 C6    LDX   $C620
1AA8-   CC CF C1    CPY   $C1CF
1AAB-   D4          ???
1AAC-   C9 CE       CMP   #$CE
1AAE-   C7          ???
1AAF-   20 D0 CF    JSR   $CFD0
1AB2-   C9 CE       CMP   #$CE
1AB4-   D4          ???
1AB5-   8D AA 20    STA   $20AA
1AB8-   D2 CF       CMP   ($CF)
1ABA-   D5 D4       CMP   $D4,X
1ABC-   C9 CE       CMP   #$CE
1ABE-   C5 D3       CMP   $D3
1AC0-   20 D7 C9    JSR   $C9D7
1AC3-   CC CC 20    CPY   $20CC
1AC6-   C2          ???
1AC7-   C5 20       CMP   $20
1AC9-   C1 C4       CMP   ($C4,X)
1ACB-   C4 C5       CPY   $C5
1ACD-   C4 20       CPY   $20
1ACF-   C9 CE       CMP   #$CE
1AD1-   20 D4 C8    JSR   $C8D4
1AD4-   C5 20       CMP   $20
1AD6-   CE C5 D8    DEC   $D8C5
1AD9-   D4          ???
1ADA-   8D AA 20    STA   $20AA
1ADD-   CD C1 CA    CMP   $CAC1
1AE0-   CF          ???
1AE1-   D2 20       CMP   ($20)
1AE3-   D6 C5       DEC   $C5,X
1AE5-   D2 D3       CMP   ($D3)
1AE7-   C9 CF       CMP   #$CF
1AE9-   CE 20 D2    DEC   $D220
1AEC-   C5 CC       CMP   $CC
1AEE-   C5 C1       CMP   $C1
1AF0-   D3          ???
1AF1-   C5 AE       CMP   $AE
1AF3-   8D AA 8D    STA   $8DAA
1AF6-   AA          TAX
1AF7-   AA          TAX
1AF8-   AA          TAX
1AF9-   AA          TAX
1AFA-   AA          TAX
1AFB-   AA          TAX
1AFC-   AA          TAX
1AFD-   AA          TAX
1AFE-   AA          TAX
1AFF-   AA          TAX
1B00-   AA          TAX
1B01-   AA          TAX
1B02-   AA          TAX
1B03-   AA          TAX
1B04-   AA          TAX
1B05-   AA          TAX
1B06-   AA          TAX
1B07-   AA          TAX
1B08-   AA          TAX
1B09-   AA          TAX
1B0A-   AA          TAX
1B0B-   AA          TAX
1B0C-   AA          TAX
1B0D-   AA          TAX
1B0E-   AA          TAX
1B0F-   AA          TAX
1B10-   AA          TAX
1B11-   AA          TAX
1B12-   AA          TAX
1B13-   AA          TAX
1B14-   AA          TAX
1B15-   AA          TAX
1B16-   8D AA 8D    STA   $8DAA
1B19-   A0 DF       LDY   #$DF
1B1B-   D0 D2       BNE   $1AEF
1B1D-   CE D4 A0    DEC   $A0D4
1B20-   A2 20       LDX   #$20
1B22-   A2 AC       LDX   #$AC
1B24-   B8          CLV
1B25-   C4 B8       CPY   $B8
1B27-   C4 B8       CPY   $B8
1B29-   C4 B8       CPY   $B8
1B2B-   C4 B8       CPY   $B8
1B2D-   C4 B8       CPY   $B8
1B2F-   C4 B8       CPY   $B8
1B31-   C4 B8       CPY   $B8
1B33-   C4 8D       CPY   $8D
1B35-   A0 DF       LDY   #$DF
1B37-   D0 D2       BNE   $1B0B
1B39-   CE D4 A0    DEC   $A0D4
1B3C-   A2 C6       LDX   #$C6
1B3E-   CC CF C1    CPY   $C1CF
1B41-   D4          ???
1B42-   C9 CE       CMP   #$CE
1B44-   C7          ???
1B45-   AD D0 CF    LDA   $CFD0
1B48-   C9 CE       CMP   #$CE
1B4A-   D4          ???
1B4B-   20 C3 C1    JSR   $C1C3
1B4E-   CC C3 D5    CPY   $D5C3
1B51-   CC C1 D4    CPY   $D4C1
1B54-   C9 CF       CMP   #$CF
1B56-   CE A2 AC    DEC   $ACA2
1B59-   B8          CLV
1B5A-   C4 8D       CPY   $8D
1B5C-   A0 DF       LDY   #$DF
1B5E-   D0 D2       BNE   $1B32
1B60-   CE D4 A0    DEC   $A0D4
1B63-   A2 AD       LDX   #$AD
1B65-   AD AD AD    LDA   $ADAD
1B68-   AD AD AD    LDA   $ADAD
1B6B-   AD AD AD    LDA   $ADAD
1B6E-   AD AD AD    LDA   $ADAD
1B71-   AD AD AD    LDA   $ADAD
1B74-   AD AD AD    LDA   $ADAD
1B77-   AD AD AD    LDA   $ADAD
1B7A-   AD AD AD    LDA   $ADAD
1B7D-   AD A2 AC    LDA   $ACA2
1B80-   B8          CLV
1B81-   C4 B8       CPY   $B8
1B83-   C4 8D       CPY   $8D
1B85-   A0 DF       LDY   #$DF
1B87-   D0 D2       BNE   $1B5B
1B89-   CE D4 A0    DEC   $A0D4
1B8C-   A2 D4       LDX   #$D4
1B8E-   C8          INY
1B8F-   C9 D3       CMP   #$D3
1B91-   20 CC C9    JSR   $C9CC
1B94-   C2          ???
1B95-   D2 C1       CMP   ($C1)
1B97-   D2 D9       CMP   ($D9)
1B99-   20 D5 D3    JSR   $D3D5
1B9C-   C5 D3       CMP   $D3
1B9E-   20 D4 C8    JSR   $C8D4
1BA1-   C5 20       CMP   $20
1BA3-   C1 D0       CMP   ($D0,X)
1BA5-   D0 CC       BNE   $1B73
1BA7-   C5 D3       CMP   $D3
1BA9-   CF          ???
1BAA-   C6 D4       DEC   $D4
1BAC-   A2 AC       LDX   #$AC
1BAE-   B8          CLV
1BAF-   C4 8D       CPY   $8D
1BB1-   A0 DF       LDY   #$DF
1BB3-   D0 D2       BNE   $1B87
1BB5-   CE D4 A0    DEC   $A0D4
1BB8-   A2 D2       LDX   #$D2
1BBA-   CF          ???
1BBB-   D5 D4       CMP   $D4,X
1BBD-   C9 CE       CMP   #$CE
1BBF-   C5 D3       CMP   $D3
1BC1-   20 C6 CF    JSR   $CFC6
1BC4-   D2 20       CMP   ($20)
1BC6-   C6 CC       DEC   $CC
1BC8-   CF          ???
1BC9-   C1 D4       CMP   ($D4,X)
1BCB-   C9 CE       CMP   #$CE
1BCD-   C7          ???
1BCE-   AD D0 CF    LDA   $CFD0
1BD1-   C9 CE       CMP   #$CE
1BD3-   D4          ???
1BD4-   A2 AC       LDX   #$AC
1BD6-   B8          CLV
1BD7-   C4 8D       CPY   $8D
1BD9-   A0 DF       LDY   #$DF
1BDB-   D0 D2       BNE   $1BAF
1BDD-   CE D4 A0    DEC   $A0D4
1BE0-   A2 C1       LDX   #$C1
1BE2-   D2 C9       CMP   ($C9)
1BE4-   D4          ???
1BE5-   C8          INY
1BE6-   CD C5 D4    CMP   $D4C5
1BE9-   C9 C3       CMP   #$C3
1BEB-   AC 20 D7    LDY   $D720
1BEE-   D2 C9       CMP   ($C9)
1BF0-   D4          ???
1BF1-   D4          ???
1BF2-   C5 CE       CMP   $CE
1BF4-   20 CF D2    JSR   $D2CF
1BF7-   C9 C7       CMP   #$C7
1BF9-   C9 CE       CMP   #$CE
1BFB-   C1 CC       CMP   ($CC,X)
1BFD-   CC D9 A2    CPY   $A2D9
1C00-   AC B8 C4    LDY   $C4B8
1C03-   8D A0 DF    STA   $DFA0
1C06-   D0 D2       BNE   $1BDA
1C08-   CE D4 A0    DEC   $A0D4
1C0B-   A2 C2       LDX   #$C2
1C0D-   D9 20 D3    CMP   $D320,Y
1C10-   D4          ???
1C11-   C5 D6       CMP   $D6
1C13-   C5 20       CMP   $20
1C15-   D7          ???
1C16-   CF          ???
1C17-   DA          PHX
1C18-   CE C9 C1    DEC   $C1C9
1C1B-   CB          ???
1C1C-   AE 20 D4    LDX   $D420
1C1F-   C8          INY
1C20-   C5 D3       CMP   $D3
1C22-   C5 20       CMP   $20
1C24-   C1 D2       CMP   ($D2,X)
1C26-   C5 A2       CMP   $A2
1C28-   AC B8 C4    LDY   $C4B8
1C2B-   8D A0 DF    STA   $DFA0
1C2E-   D0 D2       BNE   $1C02
1C30-   CE D4 A0    DEC   $A0D4
1C33-   A2 D0       LDX   #$D0
1C35-   D2 C5       CMP   ($C5)
1C37-   D3          ???
1C38-   C5 CE       CMP   $CE
1C3A-   D4          ???
1C3B-   20 C9 CE    JSR   $CEC9
1C3E-   20 C5 D6    JSR   $D6C5
1C41-   C5 D2       CMP   $D2
1C43-   D9 20 C1    CMP   $C120,Y
1C46-   D0 D0       BNE   $1C18
1C48-   CC C5 20    CPY   $20C5
1C4B-   C9 C9       CMP   #$C9
1C4D-   20 CD CF    JSR   $CFCD
1C50-   C4 C5       CPY   $C5
1C52-   CC A2 AC    CPY   $ACA2
1C55-   B8          CLV
1C56-   C4 8D       CPY   $8D
1C58-   A0 DF       LDY   #$DF
1C5A-   D0 D2       BNE   $1C2E
1C5C-   CE D4 A0    DEC   $A0D4
1C5F-   A2 C6       LDX   #$C6
1C61-   D2 CF       CMP   ($CF)
1C63-   CD 20 D4    CMP   $D420
1C66-   C8          INY
1C67-   C5 20       CMP   $20
1C69-   C1 D0       CMP   ($D0,X)
1C6B-   D0 CC       BNE   $1C39
1C6D-   C5 20       CMP   $20
1C6F-   DD DB AB    CMP   $ABDB,X
1C72-   20 C1 CE    JSR   $CEC1
1C75-   C4 20       CPY   $20
1C77-   C6 CF       DEC   $CF
1C79-   D2 D7       CMP   ($D7)
1C7B-   C1 D2       CMP   ($D2,X)
1C7D-   C4 AE       CPY   $AE
1C7F-   A2 AC       LDX   #$AC
1C81-   B8          CLV
1C82-   C4 8D       CPY   $8D
1C84-   A0 DF       LDY   #$DF
1C86-   D0 D2       BNE   $1C5A
1C88-   CE D4 A0    DEC   $A0D4
1C8B-   A2 20       LDX   #$20
1C8D-   A2 AC       LDX   #$AC
1C8F-   B8          CLV
1C90-   C4 B8       CPY   $B8
1C92-   C4 8D       CPY   $8D
1C94-   A0 DF       LDY   #$DF
1C96-   D7          ???
1C97-   C1 C9       CMP   ($C9,X)
1C99-   D4          ???
1C9A-   8D A0 DF    STA   $DFA0
1C9D-   D0 D2       BNE   $1C71
1C9F-   CE D4 A0    DEC   $A0D4
1CA2-   A2 C6       LDX   #$C6
1CA4-   CC CF C1    CPY   $C1CF
1CA7-   D4          ???
1CA8-   C9 CE       CMP   #$CE
1CAA-   C7          ???
1CAB-   AD D0 CF    LDA   $CFD0
1CAE-   C9 CE       CMP   #$CE
1CB0-   D4          ???
1CB1-   20 D6 C1    JSR   $C1D6
1CB4-   CC D5 C5    CPY   $C5D5
1CB7-   D3          ???
1CB8-   20 C1 D2    JSR   $D2C1
1CBB-   C5 20       CMP   $20
1CBD-   D3          ???
1CBE-   D4          ???
1CBF-   CF          ???
1CC0-   D2 C5       CMP   ($C5)
1CC2-   C4 A2       CPY   $A2
1CC4-   AC B8 C4    LDY   $C4B8
1CC7-   8D A0 DF    STA   $DFA0
1CCA-   D0 D2       BNE   $1C9E
1CCC-   CE D4 A0    DEC   $A0D4
1CCF-   A2 D5       LDX   #$D5
1CD1-   D3          ???
1CD2-   C9 CE       CMP   #$CE
1CD4-   C7          ???
1CD5-   20 D3 C3    JSR   $C3D3
1CD8-   C9 C5       CMP   #$C5
1CDA-   CE D4 C9    DEC   $C9D4
1CDD-   C6 C9       DEC   $C9
1CDF-   C3          ???
1CE0-   20 CE CF    JSR   $CFCE
1CE3-   D4          ???
1CE4-   C1 D4       CMP   ($D4,X)
1CE6-   C9 CF       CMP   #$CF
1CE8-   CE AC 20    DEC   $20AC
1CEB-   D7          ???
1CEC-   C8          INY
1CED-   C5 D2       CMP   $D2
1CEF-   C5 A2       CMP   $A2
1CF1-   AC B8 C4    LDY   $C4B8
1CF4-   8D A0 DF    STA   $DFA0
1CF7-   D0 D2       BNE   $1CCB
1CF9-   CE D4 A0    DEC   $A0D4
1CFC-   A2 D4       LDX   #$D4
1CFE-   C8          INY
1CFF-   C5 20       CMP   $20
1D01-   C6 C9       DEC   $C9
1D03-   D2 D3       CMP   ($D3)
1D05-   D4          ???
1D06-   20 C2 D9    JSR   $D9C2
1D09-   D4          ???
1D0A-   C5 20       CMP   $20
1D0C-   C9 D3       CMP   #$D3
1D0E-   20 D4 C8    JSR   $C8D4
1D11-   C5 20       CMP   $20
1D13-   C5 D8       CMP   $D8
1D15-   D0 CF       BNE   $1CE6
1D17-   CE C5 CE    DEC   $CEC5
1D1A-   D4          ???
1D1B-   AC A2 AC    LDY   $ACA2
1D1E-   B8          CLV
1D1F-   C4 8D       CPY   $8D
1D21-   A0 DF       LDY   #$DF
1D23-   D0 D2       BNE   $1CF7
1D25-   CE D4 A0    DEC   $A0D4
1D28-   A2 D4       LDX   #$D4
1D2A-   C8          INY
1D2B-   C5 20       CMP   $20
1D2D-   D3          ???
1D2E-   C5 C3       CMP   $C3
1D30-   CF          ???
1D31-   CE C4 20    DEC   $20C4
1D34-   D4          ???
1D35-   C8          INY
1D36-   D2 CF       CMP   ($CF)
1D38-   D5 C7       CMP   $C7,X
1D3A-   C8          INY
1D3B-   20 C6 C9    JSR   $C9C6
1D3E-   C6 D4       DEC   $D4
1D40-   C8          INY
1D41-   20 C2 D9    JSR   $D9C2
1D44-   D4          ???
1D45-   C5 D3       CMP   $D3
1D47-   A2 AC       LDX   #$AC
1D49-   B8          CLV
1D4A-   C4 8D       CPY   $8D
1D4C-   A0 DF       LDY   #$DF
1D4E-   D0 D2       BNE   $1D22
1D50-   CE D4 A0    DEC   $A0D4
1D53-   A2 C1       LDX   #$C1
1D55-   D2 C5       CMP   ($C5)
1D57-   20 D4 C8    JSR   $C8D4
1D5A-   C5 20       CMP   $20
1D5C-   CD C1 CE    CMP   $CEC1
1D5F-   D4          ???
1D60-   C9 D3       CMP   #$D3
1D62-   D3          ???
1D63-   C1 AC       CMP   ($AC,X)
1D65-   20 C1 CE    JSR   $CEC1
1D68-   C4 20       CPY   $20
1D6A-   D4          ???
1D6B-   C8          INY
1D6C-   C5 20       CMP   $20
1D6E-   D3          ???
1D6F-   C9 D8       CMP   #$D8
1D71-   D4          ???
1D72-   C8          INY
1D73-   A2 AC       LDX   #$AC
1D75-   B8          CLV
1D76-   C4 8D       CPY   $8D
1D78-   A0 DF       LDY   #$DF
1D7A-   D0 D2       BNE   $1D4E
1D7C-   CE D4 A0    DEC   $A0D4
1D7F-   A2 C2       LDX   #$C2
1D81-   D9 D4 C5    CMP   $C5D4,Y
1D84-   20 D4 C8    JSR   $C8D4
1D87-   C5 20       CMP   $20
1D89-   D3          ???
1D8A-   C9 C7       CMP   #$C7
1D8C-   CE AE A2    DEC   $A2AE
1D8F-   AC B8 C4    LDY   $C4B8
1D92-   B8          CLV
1D93-   C4 8D       CPY   $8D
1D95-   A0 DF       LDY   #$DF
1D97-   D7          ???
1D98-   C1 C9       CMP   ($C9,X)
1D9A-   D4          ???
1D9B-   8D A0 DF    STA   $DFA0
1D9E-   D0 D2       BNE   $1D72
1DA0-   CE D4 A0    DEC   $A0D4
1DA3-   A2 C5       LDX   #$C5
1DA5-   D8          CLD
1DA6-   D0 20       BNE   $1DC8
1DA8-   20 20 CD    JSR   $CD20
1DAB-   C1 CE       CMP   ($CE,X)
1DAD-   D4          ???
1DAE-   C9 D3       CMP   #$D3
1DB0-   D3          ???
1DB1-   C1 20       CMP   ($20,X)
1DB3-   20 20 20    JSR   $2020
1DB6-   20 D3 C9    JSR   $C9D3
1DB9-   C7          ???
1DBA-   CE A2 AC    DEC   $ACA2
1DBD-   B8          CLV
1DBE-   C4 8D       CPY   $8D
1DC0-   A0 DF       LDY   #$DF
1DC2-   D0 D2       BNE   $1D96
1DC4-   CE D4 A0    DEC   $A0D4
1DC7-   A2 B0       LDX   #$B0
1DC9-   B0 20       BCS   $1DEB
1DCB-   20 20 20    JSR   $2020
1DCE-   B0 B1       BCS   $1D81
1DD0-   20 B0 B2    JSR   $B2B0
1DD3-   20 B0 B3    JSR   $B3B0
1DD6-   20 B0 B4    JSR   $B4B0
1DD9-   20 20 B0    JSR   $B020
1DDC-   B5 A2       LDA   $A2,X
1DDE-   AC B8 C4    LDY   $C4B8
1DE1-   B8          CLV
1DE2-   C4 B8       CPY   $B8
1DE4-   C4 8D       CPY   $8D
1DE6-   A0 CC       LDY   #$CC
1DE8-   C4 C1       CPY   $C1
1DEA-   A0 A3       LDY   #$A3
1DEC-   A4 B8       LDY   $B8
1DEE-   B4 A0       LDY   $A0,X
1DF0-   BB          ???
1DF1-   20 BD 20    JSR   $20BD
1DF4-   A4 B8       LDY   $B8
1DF6-   B0 20       BCS   $1E18
1DF8-   AB          ???
1DF9-   20 C5 D8    JSR   $D8C5
1DFC-   D0 CF       BNE   $1DCD
1DFE-   CE C5 CE    DEC   $CEC5
1E01-   D4          ???
1E02-   BB          ???
1E03-   20 AD B1    JSR   $B1AD
1E06-   20 BD 20    JSR   $20BD
1E09-   A4 B7       LDY   $B7
1E0B-   B9 8D A0    LDA   $A08D,Y
1E0E-   D3          ???
1E0F-   D4          ???
1E10-   C1 A0       CMP   ($A0,X)
1E12-   A4 B3       LDY   $B3
1E14-   B0 B0       BCS   $1DC6
1E16-   8D A0 CC    STA   $CCA0
1E19-   C4 C1       CPY   $C1
1E1B-   A0 A3       LDY   #$A3
1E1D-   A4 C1       LDY   $C1
1E1F-   B0 A0       BCS   $1DC1
1E21-   BB          ???
1E22-   20 CD C1    JSR   $C1CD
1E25-   CE D4 C9    DEC   $C9D4
1E28-   D3          ???
1E29-   D3          ???
1E2A-   C1 8D       CMP   ($8D,X)
1E2C-   A0 D3       LDY   #$D3
1E2E-   D4          ???
1E2F-   C1 A0       CMP   ($A0,X)
1E31-   A4 B3       LDY   $B3
1E33-   B0 B1       BCS   $1DE6
1E35-   A0 BB       LDY   #$BB
1E37-   20 D3 D4    JSR   $D4D3
1E3A-   CF          ???
1E3B-   D2 C5       CMP   ($C5)
1E3D-   C4 20       CPY   $20
1E3F-   CD CF D3    CMP   $D3CF
1E42-   D4          ???
1E43-   20 D3 C9    JSR   $C9D3
1E46-   C7          ???
1E47-   CE C9 C6    DEC   $C6C9
1E4A-   C9 C3       CMP   #$C3
1E4C-   C1 CE       CMP   ($CE,X)
1E4E-   D4          ???
1E4F-   8D A0 CC    STA   $CCA0
1E52-   C4 C1       CPY   $C1
1E54-   A0 A3       LDY   #$A3
1E56-   B0 B0       BCS   $1E08
1E58-   8D A0 D3    STA   $D3A0
1E5B-   D4          ???
1E5C-   C1 A0       CMP   ($A0,X)
1E5E-   A4 B3       LDY   $B3
1E60-   B0 B2       BCS   $1E14
1E62-   8D A0 D3    STA   $D3A0
1E65-   D4          ???
1E66-   C1 A0       CMP   ($A0,X)
1E68-   A4 B3       LDY   $B3
1E6A-   B0 B3       BCS   $1E1F
1E6C-   A0 BB       LDY   #$BB
1E6E-   20 CC C5    JSR   $C5CC
1E71-   C6 D4       DEC   $D4
1E73-   20 D4 CF    JSR   $CFD4
1E76-   20 D2 C9    JSR   $C9D2
1E79-   C7          ???
1E7A-   C8          INY
1E7B-   D4          ???
1E7C-   AE 8D A0    LDX   $A08D
1E7F-   D3          ???
1E80-   D4          ???
1E81-   C1 A0       CMP   ($A0,X)
1E83-   A4 B3       LDY   $B3
1E85-   B0 B4       BCS   $1E3B
1E87-   8D A0 CC    STA   $CCA0
1E8A-   C4 C1       CPY   $C1
1E8C-   A0 A3       LDY   #$A3
1E8E-   A4 C6       LDY   $C6
1E90-   C6 8D       DEC   $8D
1E92-   A0 D3       LDY   #$D3
1E94-   D4          ???
1E95-   C1 A0       CMP   ($A0,X)
1E97-   A4 B3       LDY   $B3
1E99-   B0 B5       BCS   $1E50
1E9B-   A0 BB       LDY   #$BB
1E9D-   20 C6 C6    JSR   $C6C6
1EA0-   BD 20 CE    LDA   $CE20,X
1EA3-   C5 C7       CMP   $C7
1EA5-   C1 D4       CMP   ($D4,X)
1EA7-   C9 D6       CMP   #$D6
1EA9-   C5 AC       CMP   $AC
1EAB-   20 B0 20    JSR   $20B0
1EAE-   BD 20 D0    LDA   $D020,X
1EB1-   CF          ???
1EB2-   D3          ???
1EB3-   C9 D4       CMP   #$D4
1EB5-   C9 D6       CMP   #$D6
1EB7-   C5 8D       CMP   $8D
1EB9-   A0 DF       LDY   #$DF
1EBB-   C4 D5       CPY   $D5
1EBD-   CD D0 A0    CMP   $A0D0
1EC0-   A4 B3       LDY   $B3
1EC2-   B0 B0       BCS   $1E74
1EC4-   BB          ???
1EC5-   A3          ???
1EC6-   B6 8D       LDX   $8D,Y
1EC8-   AA          TAX
1EC9-   8D AA AA    STA   $AAAA
1ECC-   20 B2 B5    JSR   $B5B2
1ECF-   C5 B1       CMP   $B1
1ED1-   B0 DE       BCS   $1EB1
1ED3-   AD B1 20    LDA   $20B1
1ED6-   BD 20 B2    LDA   $B220,X
1ED9-   AE B5 8D    LDX   $8DB5
1EDC-   AA          TAX
1EDD-   8D A0 DF    STA   $DFA0
1EE0-   D7          ???
1EE1-   C1 C9       CMP   ($C9,X)
1EE3-   D4          ???
1EE4-   8D A0 DF    STA   $DFA0
1EE7-   D0 D2       BNE   $1EBB
1EE9-   CE D4 A0    DEC   $A0D4
1EEC-   A2 D3       LDX   #$D3
1EEE-   CF          ???
1EEF-   AC 20 CC    LDY   $CC20
1EF2-   C5 D4       CMP   $D4
1EF4-   A7          ???
1EF5-   D3          ???
1EF6-   20 D0 D5    JSR   $D5D0
1EF9-   D4          ???
1EFA-   20 B2 AE    JSR   $AEB2
1EFD-   B5 20       LDA   $20,X
1EFF-   C9 CE       CMP   #$CE
1F01-   20 A4 B3    JSR   $B3A4
1F04-   B0 B0       BCS   $1EB6
1F06-   20 C1 CE    JSR   $CEC1
1F09-   C4 A2       CPY   $A2
1F0B-   AC B8 C4    LDY   $C4B8
1F0E-   8D A0 DF    STA   $DFA0
1F11-   D0 D2       BNE   $1EE5
1F13-   CE D4 A0    DEC   $A0D4
1F16-   A2 B1       LDX   #$B1
1F18-   B0 20       BCS   $1F3A
1F1A-   C9 CE       CMP   #$CE
1F1C-   20 A4 B3    JSR   $B3A4
1F1F-   B1 B0       LDA   ($B0),Y
1F21-   AC 20 D4    LDY   $D420
1F24-   C8          INY
1F25-   C5 CE       CMP   $CE
1F27-   20 C1 C4    JSR   $C4C1
1F2A-   C4 20       CPY   $20
1F2C-   D4          ???
1F2D-   C8          INY
1F2E-   C5 CD       CMP   $CD
1F30-   AE A2 AC    LDX   $ACA2
1F33-   B8          CLV
1F34-   C4 B8       CPY   $B8
1F36-   C4 8D       CPY   $8D
1F38-   A0 DF       LDY   #$DF
1F3A-   D0 D2       BNE   $1F0E
1F3C-   CE D4 A0    DEC   $A0D4
1F3F-   A2 B2       LDX   #$B2
1F41-   AE B5 20    LDX   $20B5
1F44-   BD 20 B2    LDA   $B220,X
1F47-   B5 C5       LDA   $C5,X
1F49-   AD B1 20    LDA   $20B1
1F4C-   D3          ???
1F4D-   C3          ???
1F4E-   C9 C5       CMP   #$C5
1F50-   CE D4 C9    DEC   $C9D4
1F53-   C6 C9       DEC   $C9
1F55-   C3          ???
1F56-   20 CE CF    JSR   $CFCE
1F59-   D4          ???
1F5A-   C1 D4       CMP   ($D4,X)
1F5C-   C9 CF       CMP   #$CF
1F5E-   CE A2 AC    DEC   $ACA2
1F61-   B8          CLV
1F62-   C4 B8       CPY   $B8
1F64-   C4 8D       CPY   $8D
1F66-   A0 DF       LDY   #$DF
1F68-   D0 D2       BNE   $1F3C
1F6A-   CE D4 A0    DEC   $A0D4
1F6D-   A2 20       LDX   #$20
1F6F-   20 20 20    JSR   $2020
1F72-   BD 20 B0    LDA   $B020,X
1F75-   B1 20       LDA   ($20),Y
1F77-   B3          ???
1F78-   B7          ???
1F79-   20 B0 B0    JSR   $B0B0
1F7C-   20 B0 B0    JSR   $B0B0
1F7F-   20 B0 B0    JSR   $B0B0
1F82-   20 C6 C6    JSR   $C6C6
1F85-   A2 AC       LDX   #$AC
1F87-   B8          CLV
1F88-   C4 B8       CPY   $B8
1F8A-   C4 8D       CPY   $8D
1F8C-   A0 DF       LDY   #$DF
1F8E-   D0 D2       BNE   $1F62
1F90-   CE D4 A0    DEC   $A0D4
1F93-   A2 B1       LDX   #$B1
1F95-   B0 20       BCS   $1FB7
1F97-   BD 20 B1    LDA   $B120,X
1F9A-   C5 AB       CMP   $AB
1F9C-   B1 A2       LDA   ($A2),Y
1F9E-   AC B8 C4    LDY   $C4B8
1FA1-   8D A0 DF    STA   $DFA0
1FA4-   D0 D2       BNE   $1F78
1FA6-   CE D4 A0    DEC   $A0D4
1FA9-   A2 20       LDX   #$20
1FAB-   20 20 BD    JSR   $BD20
1FAE-   20 B0 B1    JSR   $B1B0
1FB1-   20 B0 B1    JSR   $B1B0
1FB4-   20 B0 B0    JSR   $B0B0
1FB7-   20 B0 B0    JSR   $B0B0
1FBA-   20 B0 B0    JSR   $B0B0
1FBD-   20 B0 B0    JSR   $B0B0
1FC0-   A2 AC       LDX   #$AC
1FC2-   B8          CLV
1FC3-   C4 B8       CPY   $B8
1FC5-   C4 8D       CPY   $8D
1FC7-   A0 DF       LDY   #$DF
1FC9-   D0 D2       BNE   $1F9D
1FCB-   CE D4 A0    DEC   $A0D4
1FCE-   A2 20       LDX   #$20
1FD0-   A2 AC       LDX   #$AC
1FD2-   B8          CLV
1FD3-   C4 B8       CPY   $B8
1FD5-   C4 B8       CPY   $B8
1FD7-   C4 8D       CPY   $8D
1FD9-   A0 CC       LDY   #$CC
1FDB-   C4 C1       CPY   $C1
1FDD-   A0 A3       LDY   #$A3
1FDF-   A4 B8       LDY   $B8
1FE1-   B4 8D       LDY   $8D,X
1FE3-   A0 CC       LDY   #$CC
1FE5-   C4 C1       CPY   $C1
1FE7-   A0 A3       LDY   #$A3
1FE9-   A4 C1       LDY   $C1
1FEB-   B0 8D       BCS   $1F7A
1FED-   A0 D3       LDY   #$D3
1FEF-   D4          ???
1FF0-   C1 A0       CMP   ($A0,X)
1FF2-   A4 B3       LDY   $B3
1FF4-   B1 B0       LDA   ($B0),Y
1FF6-   8D A0 D3    STA   $D3A0
1FF9-   D4          ???
1FFA-   C1 A0       CMP   ($A0,X)
1FFC-   A4 B3       LDY   $B3
1FFE-   B1 B1       LDA   ($B1),Y
2000-   8D A0 CC    STA   $CCA0
2003-   C4 C1       CPY   $C1
2005-   A0 A3       LDY   #$A3
2007-   B0 8D       BCS   $1F96
2009-   A0 D3       LDY   #$D3
200B-   D4          ???
200C-   C1 A0       CMP   ($A0,X)
200E-   A4 B3       LDY   $B3
2010-   B1 B2       LDA   ($B2),Y
2012-   8D A0 D3    STA   $D3A0
2015-   D4          ???
2016-   C1 A0       CMP   ($A0,X)
2018-   A4 B3       LDY   $B3
201A-   B1 B3       LDA   ($B3),Y
201C-   8D A0 D3    STA   $D3A0
201F-   D4          ???
2020-   C1 A0       CMP   ($A0,X)
2022-   A4 B3       LDY   $B3
2024-   B1 B4       LDA   ($B4),Y
2026-   8D A0 D3    STA   $D3A0
2029-   D4          ???
202A-   C1 A0       CMP   ($A0,X)
202C-   A4 B3       LDY   $B3
202E-   B1 B5       LDA   ($B5),Y
2030-   8D A0 DF    STA   $DFA0
2033-   D7          ???
2034-   C1 C9       CMP   ($C9,X)
2036-   D4          ???
2037-   8D A0 DF    STA   $DFA0
203A-   D0 D2       BNE   $200E
203C-   CE D4 A0    DEC   $A0D4
203F-   A2 20       LDX   #$20
2041-   A2 AC       LDX   #$AC
2043-   B8          CLV
2044-   C4 B8       CPY   $B8
2046-   C4 8D       CPY   $8D
2048-   A0 DF       LDY   #$DF
204A-   D0 D2       BNE   $201E
204C-   CE D4 A0    DEC   $A0D4
204F-   A2 CE       LDX   #$CE
2051-   CF          ???
2052-   D7          ???
2053-   20 CC C5    JSR   $C5CC
2056-   D4          ???
2057-   A7          ???
2058-   D3          ???
2059-   20 C1 C4    JSR   $C4C1
205C-   C4 20       CPY   $20
205E-   D4          ???
205F-   C8          INY
2060-   C5 CD       CMP   $CD
2062-   20 D7 C9    JSR   $C9D7
2065-   D4          ???
2066-   C8          INY
2067-   20 D4 C8    JSR   $C8D4
206A-   C5 A2       CMP   $A2
206C-   AC B8 C4    LDY   $C4B8
206F-   8D A0 DF    STA   $DFA0
2072-   D0 D2       BNE   $2046
2074-   CE D4 A0    DEC   $A0D4
2077-   A2 C6       LDX   #$C6
2079-   D0 C1       BNE   $203C
207B-   C4 C4       CPY   $C4
207D-   20 CD C1    JSR   $C1CD
2080-   C3          ???
2081-   D2 CF       CMP   ($CF)
2083-   20 D4 CF    JSR   $CFD4
2086-   20 D3 C5    JSR   $C5D3
2089-   C5 20       CMP   $20
208B-   D4          ???
208C-   C8          INY
208D-   C5 20       CMP   $20
208F-   D2 C5       CMP   ($C5)
2091-   D3          ???
2092-   D5 CC       CMP   $CC,X
2094-   D4          ???
2095-   AE A2 AC    LDX   $ACA2
2098-   B8          CLV
2099-   C4 B8       CPY   $B8
209B-   C4 8D       CPY   $8D
209D-   A0 DF       LDY   #$DF
209F-   D0 D2       BNE   $2073
20A1-   CE D4 A0    DEC   $A0D4
20A4-   A2 C6       LDX   #$C6
20A6-   D0 C1       BNE   $2069
20A8-   C4 C4       CPY   $C4
20AA-   20 A4 B3    JSR   $B3A4
20AD-   B0 B0       BCS   $205F
20AF-   BB          ???
20B0-   A4 B3       LDY   $B3
20B2-   B1 B0       LDA   ($B0),Y
20B4-   20 D2 C5    JSR   $C5D2
20B7-   D4          ???
20B8-   D5 D2       CMP   $D2,X
20BA-   CE D3 BA    DEC   $BAD3
20BD-   A2 AC       LDX   #$AC
20BF-   B8          CLV
20C0-   C4 B8       CPY   $B8
20C2-   C4 8D       CPY   $8D
20C4-   A0 C6       LDY   #$C6
20C6-   D0 C1       BNE   $2089
20C8-   C4 C4       CPY   $C4
20CA-   A0 A4       LDY   #$A4
20CC-   B3          ???
20CD-   B0 B0       BCS   $207F
20CF-   BB          ???
20D0-   A4 B3       LDY   $B3
20D2-   B1 B0       LDA   ($B0),Y
20D4-   8D A0 DF    STA   $DFA0
20D7-   C4 D5       CPY   $D5
20D9-   CD D0 A0    CMP   $A0D0
20DC-   D2 C5       CMP   ($C5)
20DE-   D4          ???
20DF-   D5 D2       CMP   $D2,X
20E1-   CE BB D2    DEC   $D2BB
20E4-   C5 D4       CMP   $D4
20E6-   CC C5 CE    CPY   $CEC5
20E9-   8D AA 8D    STA   $8DAA
20EC-   AA          TAX
20ED-   AA          TAX
20EE-   AA          TAX
20EF-   AA          TAX
20F0-   AA          TAX
20F1-   AA          TAX
20F2-   AA          TAX
20F3-   AA          TAX
20F4-   AA          TAX
20F5-   AA          TAX
20F6-   AA          TAX
20F7-   AA          TAX
20F8-   AA          TAX
20F9-   AA          TAX
20FA-   AA          TAX
20FB-   AA          TAX
20FC-   AA          TAX
20FD-   AA          TAX
20FE-   AA          TAX
20FF-   AA          TAX
2100-   AA          TAX
2101-   AA          TAX
2102-   AA          TAX
2103-   AA          TAX
2104-   AA          TAX
2105-   AA          TAX
2106-   AA          TAX
2107-   AA          TAX
2108-   AA          TAX
2109-   AA          TAX
210A-   AA          TAX
210B-   AA          TAX
210C-   8D AA 8D    STA   $8DAA
210F-   AA          TAX
2110-   20 C5 CE    JSR   $CEC5
2113-   C4 20       CPY   $20
2115-   CF          ???
2116-   C6 20       DEC   $20
2118-   C3          ???
2119-   CF          ???
211A-   CE D3 D4    DEC   $D4D3
211D-   D2 D5       CMP   ($D5)
211F-   C3          ???
2120-   D4          ???
2121-   C9 CF       CMP   #$CF
2123-   CE 8D AA    DEC   $AA8D
2126-   8D AA AA    STA   $AAAA
2129-   AA          TAX
212A-   AA          TAX
212B-   AA          TAX
212C-   AA          TAX
212D-   AA          TAX
212E-   AA          TAX
212F-   AA          TAX
2130-   AA          TAX
2131-   AA          TAX
2132-   AA          TAX
2133-   AA          TAX
2134-   AA          TAX
2135-   AA          TAX
2136-   AA          TAX
2137-   AA          TAX
2138-   AA          TAX
2139-   AA          TAX
213A-   AA          TAX
213B-   AA          TAX
213C-   AA          TAX
213D-   AA          TAX
213E-   AA          TAX
213F-   AA          TAX
2140-   AA          TAX
2141-   AA          TAX
2142-   AA          TAX
2143-   AA          TAX
2144-   AA          TAX
2145-   AA          TAX
2146-   AA          TAX
2147-   8D AA 8D    STA   $8DAA
214A-   A0 CA       LDY   #$CA
214C-   CD D0 A0    CMP   $A0D0
214F-   D2 C5       CMP   ($C5)
2151-   C5 CE       CMP   $CE
2153-   D4          ???
2154-   D2 D9       CMP   ($D9)
2156-   8D AA 8D    STA   $8DAA
2159-   AA          TAX
215A-   E0 E0       CPX   #$E0
215C-   E0 E0       CPX   #$E0
215E-   E0 E0       CPX   #$E0
2160-   E0 E0       CPX   #$E0
2162-   E0 E0       CPX   #$E0
2164-   E0 E0       CPX   #$E0
2166-   E0 E0       CPX   #$E0
2168-   E0 E0       CPX   #$E0
216A-   E0 E0       CPX   #$E0
216C-   E0 E0       CPX   #$E0
216E-   E0 E0       CPX   #$E0
2170-   E0 E0       CPX   #$E0
2172-   E0 E0       CPX   #$E0
2174-   E0 E0       CPX   #$E0
2176-   E0 E0       CPX   #$E0
2178-   AA          TAX
2179-   8D AA 20    STA   $20AA
217C-   20 20 20    JSR   $2020
217F-   20 20 20    JSR   $2020
2182-   20 C2 CF    JSR   $CFC2
2185-   D4          ???
2186-   D4          ???
2187-   CF          ???
2188-   CD 20 C9    CMP   $C920
218B-   CE C3 CC    DEC   $CCC3
218E-   D5 C4       CMP   $C4,X
2190-   C5 D3       CMP   $D3
2192-   20 20 20    JSR   $2020
2195-   20 20 20    JSR   $2020
2198-   20 AA 8D    JSR   $8DAA
219B-   AA          TAX
219C-   AC AC AC    LDY   $ACAC
219F-   AC AC AC    LDY   $ACAC
21A2-   AC AC AC    LDY   $ACAC
21A5-   AC AC AC    LDY   $ACAC
21A8-   AC AC AC    LDY   $ACAC
21AB-   AC AC AC    LDY   $ACAC
21AE-   AC AC AC    LDY   $ACAC
21B1-   AC AC AC    LDY   $ACAC
21B4-   AC AC AC    LDY   $ACAC
21B7-   AC AC AC    LDY   $ACAC
21BA-   AA          TAX
21BB-   8D AA 8D    STA   $8DAA
21BE-   AA          TAX
21BF-   AA          TAX
21C0-   20 C2 CF    JSR   $CFC2
21C3-   D4          ???
21C4-   D4          ???
21C5-   CF          ???
21C6-   CD 20 C9    CMP   $C920
21C9-   CE C3 CC    DEC   $CCC3
21CC-   D5 C4       CMP   $C4,X
21CE-   C5 D3       CMP   $D3
21D0-   8D AA 8D    STA   $8DAA
21D3-   A0 D0       LDY   #$D0
21D5-   D5 D4       CMP   $D4,X
21D7-   A0 D2       LDY   #$D2
21D9-   C5 D1       CMP   $D1
21DB-   D5 C9       CMP   $C9,X
21DD-   D2 C5       CMP   ($C5)
21DF-   C4 AE       CPY   $AE
21E1-   CC C9 C2    CPY   $C2C9
21E4-   AE CD C9    LDX   $C9CD
21E7-   CE 8D AA    DEC   $AA8D
21EA-   8D AA AA    STA   $AAAA
21ED-   20 C9 CE    JSR   $CEC9
21F0-   C4 C9       CPY   $C9
21F2-   D6 C9       DEC   $C9,X
21F4-   C4 D5       CPY   $D5
21F6-   C1 CC       CMP   ($CC,X)
21F8-   20 D3 D5    JSR   $D5D3
21FB-   C2          ???
21FC-   D2 CF       CMP   ($CF)
21FE-   D5 D4       CMP   $D4,X
2200-   C9 CE       CMP   #$CE
2202-   C5 20       CMP   $20
2204-   C9 CE       CMP   #$CE
2206-   C3          ???
2207-   CC D5 C4    CPY   $C4D5
220A-   C5 D3       CMP   $D3
220C-   8D AA 8D    STA   $8DAA
220F-   AA          TAX
2210-   AA          TAX
2211-   20 B8 AD    JSR   $ADB8
2214-   C2          ???
2215-   C9 D4       CMP   #$D4
2217-   20 CD C1    JSR   $C1CD
221A-   D4          ???
221B-   C8          INY
221C-   20 D3 D5    JSR   $D5D3
221F-   C2          ???
2220-   D2 CF       CMP   ($CF)
2222-   D5 D4       CMP   $D4,X
2224-   C9 CE       CMP   #$CE
2226-   C5 D3       CMP   $D3
2228-   8D AA 8D    STA   $8DAA
222B-   A0 D0       LDY   #$D0
222D-   D5 D4       CMP   $D4,X
222F-   A0 CD       LDY   #$CD
2231-   D5 CC       CMP   $CC,X
2233-   D4          ???
2234-   B8          CLV
2235-   AE D3 D5    LDX   $D5D3
2238-   C2          ???
2239-   AE CD C9    LDX   $C9CD
223C-   CE 8D A0    DEC   $A08D
223F-   D0 D5       BNE   $2216
2241-   D4          ???
2242-   A0 C4       LDY   #$C4
2244-   C9 D6       CMP   #$D6
2246-   C4 B8       CPY   $B8
2248-   AE D3 D5    LDX   $D5D3
224B-   C2          ???
224C-   AE CD C9    LDX   $C9CD
224F-   CE 8D A0    DEC   $A08D
2252-   D0 D5       BNE   $2229
2254-   D4          ???
2255-   A0 D2       LDY   #$D2
2257-   C1 CE       CMP   ($CE,X)
2259-   C4 B8       CPY   $B8
225B-   AE D3 D5    LDX   $D5D3
225E-   C2          ???
225F-   AE CD C9    LDX   $C9CD
2262-   CE 8D A0    DEC   $A08D
2265-   D0 D5       BNE   $223C
2267-   D4          ???
2268-   A0 D2       LDY   #$D2
226A-   C1 CE       CMP   ($CE,X)
226C-   C4 C2       CPY   $C2
226E-   AE D3 D5    LDX   $D5D3
2271-   C2          ???
2272-   AE CD C9    LDX   $C9CD
2275-   CE 8D AA    DEC   $AA8D
2278-   8D AA AA    STA   $AAAA
227B-   20 B1 B6    JSR   $B6B1
227E-   AD C2 C9    LDA   $C9C2
2281-   D4          ???
2282-   20 CD C1    JSR   $C1CD
2285-   D4          ???
2286-   C8          INY
2287-   20 D3 D5    JSR   $D5D3
228A-   C2          ???
228B-   D2 CF       CMP   ($CF)
228D-   D5 D4       CMP   $D4,X
228F-   C9 CE       CMP   #$CE
2291-   C5 D3       CMP   $D3
2293-   8D AA 8D    STA   $8DAA
2296-   A0 D0       LDY   #$D0
2298-   D5 D4       CMP   $D4,X
229A-   A0 C1       LDY   #$C1
229C-   C4 C4       CPY   $C4
229E-   C9 D4       CMP   #$D4
22A0-   B1 B6       LDA   ($B6),Y
22A2-   AE D3 D5    LDX   $D5D3
22A5-   C2          ???
22A6-   AE CD C9    LDX   $C9CD
22A9-   CE 8D A0    DEC   $A08D
22AC-   D0 D5       BNE   $2283
22AE-   D4          ???
22AF-   A0 D3       LDY   #$D3
22B1-   D5 C2       CMP   $C2,X
22B3-   D4          ???
22B4-   B1 B6       LDA   ($B6),Y
22B6-   AE D3 D5    LDX   $D5D3
22B9-   C2          ???
22BA-   AE CD C9    LDX   $C9CD
22BD-   CE 8D A0    DEC   $A08D
22C0-   D0 D5       BNE   $2297
22C2-   D4          ???
22C3-   A0 C3       LDY   #$C3
22C5-   CF          ???
22C6-   CD D0 B1    CMP   $B1D0
22C9-   B6 AE       LDX   $AE,Y
22CB-   D3          ???
22CC-   D5 C2       CMP   $C2,X
22CE-   AE CD C9    LDX   $C9CD
22D1-   CE 8D A0    DEC   $A08D
22D4-   D0 D5       BNE   $22AB
22D6-   D4          ???
22D7-   A0 CD       LDY   #$CD
22D9-   D5 CC       CMP   $CC,X
22DB-   D4          ???
22DC-   B1 B6       LDA   ($B6),Y
22DE-   AE D3 D5    LDX   $D5D3
22E1-   C2          ???
22E2-   AE CD C9    LDX   $C9CD
22E5-   CE 8D A0    DEC   $A08D
22E8-   D0 D5       BNE   $22BF
22EA-   D4          ???
22EB-   A0 C4       LDY   #$C4
22ED-   C9 D6       CMP   #$D6
22EF-   C4 B1       CPY   $B1
22F1-   B6 AE       LDX   $AE,Y
22F3-   D3          ???
22F4-   D5 C2       CMP   $C2,X
22F6-   AE CD C9    LDX   $C9CD
22F9-   CE 8D A0    DEC   $A08D
22FC-   D0 D5       BNE   $22D3
22FE-   D4          ???
22FF-   A0 D2       LDY   #$D2
2301-   C1 CE       CMP   ($CE,X)
2303-   C4 B1       CPY   $B1
2305-   B6 AE       LDX   $AE,Y
2307-   D3          ???
2308-   D5 C2       CMP   $C2,X
230A-   AE CD C9    LDX   $C9CD
230D-   CE 8D AA    DEC   $AA8D
2310-   8D 00 00    STA   $0000
