0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 D3    LDY   $D320,X
0950-   D4          ???
0951-   D2 C9       CMP   ($C9)
0953-   CE C7 D3    DEC   $D3C7
0956-   20 C4 C5    JSR   $C5C4
0959-   CD CF 20    CMP   $20CF
095C-   BE AD 20    LDX   $20AD,Y
095F-   20 20 20    JSR   $2020
0962-   20 20 AA    JSR   $AA20
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B2    JSR   $B220
09D4-   B0 AD       BCS   $0983
09D6-   CA          DEX
09D7-   C1 CE       CMP   ($CE,X)
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B9       LDA   ($B9),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 D4       LDY   #$D4
0AF8-   D2 A0       CMP   ($A0)
0AFA-   CF          ???
0AFB-   CE 8D A0    DEC   $A08D
0AFE-   C5 D8       CMP   $D8
0B00-   D0 A0       BNE   $0AA2
0B02-   CF          ???
0B03-   CE CC D9    DEC   $D9CC
0B06-   8D A0 C4    STA   $C4A0
0B09-   D3          ???
0B0A-   CB          ???
0B0B-   A0 D3       LDY   #$D3
0B0D-   D4          ???
0B0E-   D2 C9       CMP   ($C9)
0B10-   CE C7 D3    DEC   $D3C7
0B13-   AE C4 C5    LDX   $C5C4
0B16-   CD CF 8D    CMP   $8DCF
0B19-   A0 CF       LDY   #$CF
0B1B-   C2          ???
0B1C-   CA          DEX
0B1D-   A0 A4       LDY   #$A4
0B1F-   C2          ???
0B20-   C6 C5       DEC   $C5
0B22-   B0 8D       BCS   $0AB1
0B24-   A0 CF       LDY   #$CF
0B26-   D2 C7       CMP   ($C7)
0B28-   A0 A4       LDY   #$A4
0B2A-   B6 B0       LDX   $B0,Y
0B2C-   B0 B0       BCS   $0ADE
0B2E-   8D AA 8D    STA   $8DAA
0B31-   AA          TAX
0B32-   E0 E0       CPX   #$E0
0B34-   E0 E0       CPX   #$E0
0B36-   E0 E0       CPX   #$E0
0B38-   E0 E0       CPX   #$E0
0B3A-   E0 E0       CPX   #$E0
0B3C-   E0 E0       CPX   #$E0
0B3E-   E0 E0       CPX   #$E0
0B40-   E0 E0       CPX   #$E0
0B42-   E0 E0       CPX   #$E0
0B44-   E0 E0       CPX   #$E0
0B46-   E0 E0       CPX   #$E0
0B48-   E0 E0       CPX   #$E0
0B4A-   E0 E0       CPX   #$E0
0B4C-   E0 E0       CPX   #$E0
0B4E-   E0 E0       CPX   #$E0
0B50-   AA          TAX
0B51-   8D AA 20    STA   $20AA
0B54-   20 D4 CF    JSR   $CFD4
0B57-   D0 20       BNE   $0B79
0B59-   C9 CE       CMP   #$CE
0B5B-   C3          ???
0B5C-   CC D5 C4    CPY   $C4D5
0B5F-   C5 D3       CMP   $D3
0B61-   20 A8 D0    JSR   $D0A8
0B64-   D5 D4       CMP   $D4,X
0B66-   D3          ???
0B67-   AC 20 CD    LDY   $CD20
0B6A-   C1 C3       CMP   ($C3,X)
0B6C-   D2 CF       CMP   ($CF)
0B6E-   D3          ???
0B6F-   A9 20       LDA   #$20
0B71-   AA          TAX
0B72-   8D AA AC    STA   $ACAA
0B75-   AC AC AC    LDY   $ACAC
0B78-   AC AC AC    LDY   $ACAC
0B7B-   AC AC AC    LDY   $ACAC
0B7E-   AC AC AC    LDY   $ACAC
0B81-   AC AC AC    LDY   $ACAC
0B84-   AC AC AC    LDY   $ACAC
0B87-   AC AC AC    LDY   $ACAC
0B8A-   AC AC AC    LDY   $ACAC
0B8D-   AC AC AC    LDY   $ACAC
0B90-   AC AC AA    LDY   $AAAC
0B93-   8D AA 8D    STA   $8DAA
0B96-   A0 D0       LDY   #$D0
0B98-   D5 D4       CMP   $D4,X
0B9A-   A0 D2       LDY   #$D2
0B9C-   C5 D1       CMP   $D1
0B9E-   D5 C9       CMP   $C9,X
0BA0-   D2 C5       CMP   ($C5)
0BA2-   C4 AE       CPY   $AE
0BA4-   D6 C1       DEC   $C1,X
0BA6-   D2 D3       CMP   ($D3)
0BA8-   8D A0 D5    STA   $D5A0
0BAB-   D3          ???
0BAC-   C5 A0       CMP   $A0
0BAE-   D2 C5       CMP   ($C5)
0BB0-   D1 D5       CMP   ($D5),Y
0BB2-   C9 D2       CMP   #$D2
0BB4-   C5 C4       CMP   $C4
0BB6-   AE CD C1    LDX   $C1CD
0BB9-   C3          ???
0BBA-   AE CD C9    LDX   $C9CD
0BBD-   CE 8D A0    DEC   $A08D
0BC0-   D0 D5       BNE   $0B97
0BC2-   D4          ???
0BC3-   A0 D2       LDY   #$D2
0BC5-   C5 D1       CMP   $D1
0BC7-   D5 C9       CMP   $C9,X
0BC9-   D2 C5       CMP   ($C5)
0BCB-   C4 AE       CPY   $AE
0BCD-   C8          INY
0BCE-   CF          ???
0BCF-   CF          ???
0BD0-   CB          ???
0BD1-   D3          ???
0BD2-   AE CD C9    LDX   $C9CD
0BD5-   CE 8D A0    DEC   $A08D
0BD8-   D5 D3       CMP   $D3,X
0BDA-   C5 A0       CMP   $A0
0BDC-   D3          ???
0BDD-   D4          ???
0BDE-   D2 C9       CMP   ($C9)
0BE0-   CE C7 D3    DEC   $D3C7
0BE3-   AE CD C1    LDX   $C1CD
0BE6-   C3          ???
0BE7-   AE CD C9    LDX   $C9CD
0BEA-   CE 8D A0    DEC   $A08D
0BED-   D0 D5       BNE   $0BC4
0BEF-   D4          ???
0BF0-   A0 D3       LDY   #$D3
0BF2-   D4          ???
0BF3-   D2 C9       CMP   ($C9)
0BF5-   CE C7 D3    DEC   $D3C7
0BF8-   AE C8 CF    LDX   $CFC8
0BFB-   CF          ???
0BFC-   CB          ???
0BFD-   D3          ???
0BFE-   8D AA 8D    STA   $8DAA
0C01-   AA          TAX
0C02-   8D AA E0    STA   $E0AA
0C05-   E0 E0       CPX   #$E0
0C07-   E0 E0       CPX   #$E0
0C09-   E0 E0       CPX   #$E0
0C0B-   E0 E0       CPX   #$E0
0C0D-   E0 E0       CPX   #$E0
0C0F-   E0 E0       CPX   #$E0
0C11-   E0 E0       CPX   #$E0
0C13-   E0 E0       CPX   #$E0
0C15-   E0 E0       CPX   #$E0
0C17-   E0 E0       CPX   #$E0
0C19-   E0 E0       CPX   #$E0
0C1B-   E0 E0       CPX   #$E0
0C1D-   E0 E0       CPX   #$E0
0C1F-   E0 E0       CPX   #$E0
0C21-   E0 AA       CPX   #$AA
0C23-   8D AA 20    STA   $20AA
0C26-   20 20 20    JSR   $2020
0C29-   20 20 D0    JSR   $D020
0C2C-   D2 CF       CMP   ($CF)
0C2E-   C7          ???
0C2F-   D2 C1       CMP   ($C1)
0C31-   CD 20 CD    CMP   $CD20
0C34-   C1 C9       CMP   ($C9,X)
0C36-   CE 20 C2    DEC   $C220
0C39-   CF          ???
0C3A-   C4 D9       CPY   $D9
0C3C-   20 20 20    JSR   $2020
0C3F-   20 20 20    JSR   $2020
0C42-   20 AA 8D    JSR   $8DAA
0C45-   AA          TAX
0C46-   AC AC AC    LDY   $ACAC
0C49-   AC AC AC    LDY   $ACAC
0C4C-   AC AC AC    LDY   $ACAC
0C4F-   AC AC AC    LDY   $ACAC
0C52-   AC AC AC    LDY   $ACAC
0C55-   AC AC AC    LDY   $ACAC
0C58-   AC AC AC    LDY   $ACAC
0C5B-   AC AC AC    LDY   $ACAC
0C5E-   AC AC AC    LDY   $ACAC
0C61-   AC AC AC    LDY   $ACAC
0C64-   AA          TAX
0C65-   8D AA 8D    STA   $8DAA
0C68-   A0 DF       LDY   #$DF
0C6A-   D0 D2       BNE   $0C3E
0C6C-   CE D4 A0    DEC   $A0D4
0C6F-   A2 20       LDX   #$20
0C71-   A2 AC       LDX   #$AC
0C73-   B8          CLV
0C74-   C4 B8       CPY   $B8
0C76-   C4 B8       CPY   $B8
0C78-   C4 B8       CPY   $B8
0C7A-   C4 8D       CPY   $8D
0C7C-   A0 DF       LDY   #$DF
0C7E-   D0 D2       BNE   $0C52
0C80-   CE D4 A0    DEC   $A0D4
0C83-   A2 D3       LDX   #$D3
0C85-   D4          ???
0C86-   D2 C9       CMP   ($C9)
0C88-   CE C7 D3    DEC   $D3C7
0C8B-   20 CC C9    JSR   $C9CC
0C8E-   C2          ???
0C8F-   D2 C1       CMP   ($C1)
0C91-   D2 D9       CMP   ($D9)
0C93-   20 C4 C5    JSR   $C5C4
0C96-   CD CF A2    CMP   $A2CF
0C99-   AC B8 C4    LDY   $C4B8
0C9C-   8D A0 DF    STA   $DFA0
0C9F-   D0 D2       BNE   $0C73
0CA1-   CE D4 A0    DEC   $A0D4
0CA4-   A2 AD       LDX   #$AD
0CA6-   AD AD AD    LDA   $ADAD
0CA9-   AD AD AD    LDA   $ADAD
0CAC-   AD AD AD    LDA   $ADAD
0CAF-   AD AD AD    LDA   $ADAD
0CB2-   AD AD AD    LDA   $ADAD
0CB5-   AD AD AD    LDA   $ADAD
0CB8-   AD A2 AC    LDA   $ACA2
0CBB-   B8          CLV
0CBC-   C4 8D       CPY   $8D
0CBE-   A0 DF       LDY   #$DF
0CC0-   D0 D2       BNE   $0C94
0CC2-   CE D4 A0    DEC   $A0D4
0CC5-   A2 20       LDX   #$20
0CC7-   A2 AC       LDX   #$AC
0CC9-   B8          CLV
0CCA-   C4 8D       CPY   $8D
0CCC-   A0 DF       LDY   #$DF
0CCE-   D0 D2       BNE   $0CA2
0CD0-   CE D4 A0    DEC   $A0D4
0CD3-   A2 D4       LDX   #$D4
0CD5-   C8          INY
0CD6-   C5 20       CMP   $20
0CD8-   D3          ???
0CD9-   C3          ???
0CDA-   CD D0 20    CMP   $20D0
0CDD-   CD C1 C3    CMP   $C3C1
0CE0-   D2 CF       CMP   ($CF)
0CE2-   20 C3 CF    JSR   $CFC3
0CE5-   CD D0 C1    CMP   $C1D0
0CE8-   D2 C5       CMP   ($C5)
0CEA-   D3          ???
0CEB-   20 D4 D7    JSR   $D7D4
0CEE-   CF          ???
0CEF-   20 A2 AC    JSR   $ACA2
0CF2-   B8          CLV
0CF3-   C4 8D       CPY   $8D
0CF5-   A0 DF       LDY   #$DF
0CF7-   D0 D2       BNE   $0CCB
0CF9-   CE D4 A0    DEC   $A0D4
0CFC-   A2 D3       LDX   #$D3
0CFE-   D4          ???
0CFF-   D2 C9       CMP   ($C9)
0D01-   CE C7 D3    DEC   $D3C7
0D04-   20 C1 CE    JSR   $CEC1
0D07-   C4 20       CPY   $20
0D09-   D3          ???
0D0A-   C5 D4       CMP   $D4
0D0C-   D3          ???
0D0D-   20 D4 C8    JSR   $C8D4
0D10-   C5 20       CMP   $20
0D12-   C6 CC       DEC   $CC
0D14-   C1 C7       CMP   ($C7,X)
0D16-   D3          ???
0D17-   A2 AC       LDX   #$AC
0D19-   B8          CLV
0D1A-   C4 8D       CPY   $8D
0D1C-   A0 DF       LDY   #$DF
0D1E-   D0 D2       BNE   $0CF2
0D20-   CE D4 A0    DEC   $A0D4
0D23-   A2 C1       LDX   #$C1
0D25-   C3          ???
0D26-   C3          ???
0D27-   CF          ???
0D28-   D2 C4       CMP   ($C4)
0D2A-   C9 CE       CMP   #$CE
0D2C-   C7          ???
0D2D-   CC D9 AE    CPY   $AED9
0D30-   20 C9 C6    JSR   $C6C9
0D33-   20 D4 C8    JSR   $C8D4
0D36-   C5 20       CMP   $20
0D38-   D4          ???
0D39-   D7          ???
0D3A-   CF          ???
0D3B-   20 C1 D2    JSR   $D2C1
0D3E-   C5 20       CMP   $20
0D40-   C5 D1       CMP   $D1
0D42-   D5 C1       CMP   $C1,X
0D44-   CC AC A2    CPY   $A2AC
0D47-   AC B8 C4    LDY   $C4B8
0D4A-   8D A0 DF    STA   $DFA0
0D4D-   D0 D2       BNE   $0D21
0D4F-   CE D4 A0    DEC   $A0D4
0D52-   A2 D4       LDX   #$D4
0D54-   C8          INY
0D55-   C5 CE       CMP   $CE
0D57-   20 AE DA    JSR   $DAAE
0D5A-   20 C9 D3    JSR   $D3C9
0D5D-   20 D3 C5    JSR   $C5D3
0D60-   D4          ???
0D61-   20 D4 CF    JSR   $CFD4
0D64-   20 DA C5    JSR   $C5DA
0D67-   D2 CF       CMP   ($CF)
0D69-   BB          ???
0D6A-   20 C9 C6    JSR   $C6C9
0D6D-   20 CE CF    JSR   $CFCE
0D70-   D4          ???
0D71-   AC 20 B1    LDY   $B120
0D74-   AE A2 AC    LDX   $ACA2
0D77-   B8          CLV
0D78-   C4 B8       CPY   $B8
0D7A-   C4 8D       CPY   $8D
0D7C-   A0 DF       LDY   #$DF
0D7E-   D0 D2       BNE   $0D52
0D80-   CE D4 A0    DEC   $A0D4
0D83-   A2 C9       LDX   #$C9
0D85-   C6 20       DEC   $20
0D87-   D3          ???
0D88-   D4          ???
0D89-   D2 C9       CMP   ($C9)
0D8B-   CE C7 B1    DEC   $B1C7
0D8E-   20 CC C5    JSR   $C5CC
0D91-   CE C7 D4    DEC   $D4C7
0D94-   C8          INY
0D95-   20 BE 20    JSR   $20BE
0D98-   D3          ???
0D99-   D4          ???
0D9A-   D2 C9       CMP   ($C9)
0D9C-   CE C7 B2    DEC   $B2C7
0D9F-   20 CC C5    JSR   $C5CC
0DA2-   CE C7 D4    DEC   $D4C7
0DA5-   C8          INY
0DA6-   AC A2 AC    LDY   $ACA2
0DA9-   B8          CLV
0DAA-   C4 8D       CPY   $8D
0DAC-   A0 DF       LDY   #$DF
0DAE-   D0 D2       BNE   $0D82
0DB0-   CE D4 A0    DEC   $A0D4
0DB3-   A2 AE       LDX   #$AE
0DB5-   C3          ???
0DB6-   A8          TAY
0DB7-   C1 D2       CMP   ($D2,X)
0DB9-   D2 D9       CMP   ($D9)
0DBB-   A9 20       LDA   #$20
0DBD-   BD 20 B0    LDA   $B020,X
0DC0-   BB          ???
0DC1-   20 C5 CC    JSR   $CCC5
0DC4-   D3          ???
0DC5-   C5 AC       CMP   $AC
0DC7-   20 AE C3    JSR   $C3AE
0DCA-   20 BD 20    JSR   $20BD
0DCD-   B1 AE       LDA   ($AE),Y
0DCF-   A2 AC       LDX   #$AC
0DD1-   B8          CLV
0DD2-   C4 B8       CPY   $B8
0DD4-   C4 8D       CPY   $8D
0DD6-   A0 DF       LDY   #$DF
0DD8-   D0 D2       BNE   $0DAC
0DDA-   CE D4 A0    DEC   $A0D4
0DDD-   A2 D3       LDX   #$D3
0DDF-   CF          ???
0DE0-   AC 20 D7    LDY   $D720
0DE3-   C5 20       CMP   $20
0DE5-   C3          ???
0DE6-   C1 CE       CMP   ($CE,X)
0DE8-   20 C3 CF    JSR   $CFC3
0DEB-   CD D0 C1    CMP   $C1D0
0DEE-   D2 C5       CMP   ($C5)
0DF0-   20 D4 C8    JSR   $C8D4
0DF3-   C5 20       CMP   $20
0DF5-   CC C9 D4    CPY   $D4C9
0DF8-   C5 D2       CMP   $D2
0DFA-   C1 CC       CMP   ($CC,X)
0DFC-   20 A7 C1    JSR   $C1A7
0DFF-   A7          ???
0E00-   A2 AC       LDX   #$AC
0E02-   B8          CLV
0E03-   C4 8D       CPY   $8D
0E05-   A0 DF       LDY   #$DF
0E07-   D0 D2       BNE   $0DDB
0E09-   CE D4 A0    DEC   $A0D4
0E0C-   A2 D4       LDX   #$D4
0E0E-   CF          ???
0E0F-   20 D4 C8    JSR   $C8D4
0E12-   C5 20       CMP   $20
0E14-   D6 C1       DEC   $C1,X
0E16-   CC D5 C5    CPY   $C5D5
0E19-   20 D3 D4    JSR   $D4D3
0E1C-   CF          ???
0E1D-   D2 C5       CMP   ($C5)
0E1F-   C4 20       CPY   $20
0E21-   C9 CE       CMP   #$CE
0E23-   20 C1 D3    JSR   $D3C1
0E26-   D4          ???
0E27-   D2 AC       CMP   ($AC)
0E29-   20 D7 C8    JSR   $C8D7
0E2C-   C9 C3       CMP   #$C3
0E2E-   C8          INY
0E2F-   A2 AC       LDX   #$AC
0E31-   B8          CLV
0E32-   C4 8D       CPY   $8D
0E34-   A0 DF       LDY   #$DF
0E36-   D0 D2       BNE   $0E0A
0E38-   CE D4 A0    DEC   $A0D4
0E3B-   A2 C8       LDX   #$C8
0E3D-   CF          ???
0E3E-   CC C4 D3    CPY   $D3C4
0E41-   20 D4 C8    JSR   $C8D4
0E44-   C5 20       CMP   $20
0E46-   D3          ???
0E47-   C1 CD       CMP   ($CD,X)
0E49-   C5 20       CMP   $20
0E4B-   D3          ???
0E4C-   D4          ???
0E4D-   D2 C9       CMP   ($C9)
0E4F-   CE C7 AC    DEC   $ACC7
0E52-   20 D4 C8    JSR   $C8D4
0E55-   C5 CE       CMP   $CE
0E57-   20 D5 D3    JSR   $D3D5
0E5A-   C5 20       CMP   $20
0E5C-   C2          ???
0E5D-   CE C5 20    DEC   $20C5
0E60-   D4          ???
0E61-   CF          ???
0E62-   A2 AC       LDX   #$AC
0E64-   B8          CLV
0E65-   C4 8D       CPY   $8D
0E67-   A0 DF       LDY   #$DF
0E69-   D0 D2       BNE   $0E3D
0E6B-   CE D4 A0    DEC   $A0D4
0E6E-   A2 D4       LDX   #$D4
0E70-   C5 D3       CMP   $D3
0E72-   D4          ???
0E73-   20 C9 C6    JSR   $C6C9
0E76-   20 D4 C8    JSR   $C8D4
0E79-   C5 D9       CMP   $D9
0E7B-   20 C1 D2    JSR   $D2C1
0E7E-   C5 20       CMP   $20
0E80-   C5 D1       CMP   $D1
0E82-   D5 C1       CMP   $C1,X
0E84-   CC AE A2    CPY   $A2AE
0E87-   AC B8 C4    LDY   $C4B8
0E8A-   B8          CLV
0E8B-   C4 8D       CPY   $8D
0E8D-   A0 D3       LDY   #$D3
0E8F-   C3          ???
0E90-   CD D0 A0    CMP   $A0D0
0E93-   A2 C1       LDX   #$C1
0E95-   A2 BB       LDX   #$BB
0E97-   C1 D3       CMP   ($D3,X)
0E99-   D4          ???
0E9A-   D2 8D       CMP   ($8D)
0E9C-   A0 C2       LDY   #$C2
0E9E-   CE C5 A0    DEC   $A0C5
0EA1-   D0 C5       BNE   $0E68
0EA3-   A0 BB       LDY   #$BB
0EA5-   20 C9 D3    JSR   $D3C9
0EA8-   20 DA C5    JSR   $C5DA
0EAB-   D2 CF       CMP   ($CF)
0EAD-   20 C6 CC    JSR   $CCC6
0EB0-   C1 C7       CMP   ($C7,X)
0EB2-   20 B1 BF    JSR   $BFB1
0EB5-   20 C2 D2    JSR   $D2C2
0EB8-   C1 CE       CMP   ($CE,X)
0EBA-   C3          ???
0EBB-   C8          INY
0EBC-   20 C9 C6    JSR   $C6C9
0EBF-   20 D3 CF    JSR   $CFD3
0EC2-   8D A0 CA    STA   $CAA0
0EC5-   CD D0 A0    CMP   $A0D0
0EC8-   C3          ???
0EC9-   CF          ???
0ECA-   CE D4 8D    DEC   $8DD4
0ECD-   D0 C5       BNE   $0E94
0ECF-   8D A0 DF    STA   $DFA0
0ED2-   D0 D2       BNE   $0EA6
0ED4-   CE D4 A0    DEC   $A0D4
0ED7-   A2 D4       LDX   #$D4
0ED9-   C8          INY
0EDA-   C5 20       CMP   $20
0EDC-   CC C9 D4    CPY   $D4C9
0EDF-   C5 D2       CMP   $D2
0EE1-   C1 CC       CMP   ($CC,X)
0EE3-   20 C1 20    JSR   $20C1
0EE6-   C1 CE       CMP   ($CE,X)
0EE8-   C4 20       CPY   $20
0EEA-   D4          ???
0EEB-   C8          INY
0EEC-   C5 20       CMP   $20
0EEE-   C1 20       CMP   ($20,X)
0EF0-   D3          ???
0EF1-   D4          ???
0EF2-   D2 C9       CMP   ($C9)
0EF4-   CE C7 20    DEC   $20C7
0EF7-   C1 D2       CMP   ($D2,X)
0EF9-   C5 A2       CMP   $A2
0EFB-   AC B8 C4    LDY   $C4B8
0EFE-   8D A0 DF    STA   $DFA0
0F01-   D0 D2       BNE   $0ED5
0F03-   CE D4 A0    DEC   $A0D4
0F06-   A2 C5       LDX   #$C5
0F08-   D1 D5       CMP   ($D5),Y
0F0A-   C1 CC       CMP   ($CC,X)
0F0C-   AE A2 AC    LDX   $ACA2
0F0F-   B8          CLV
0F10-   C4 B8       CPY   $B8
0F12-   C4 B8       CPY   $B8
0F14-   C4 8D       CPY   $8D
0F16-   C3          ???
0F17-   CF          ???
0F18-   CE D4 8D    DEC   $8DD4
0F1B-   A0 DF       LDY   #$DF
0F1D-   D7          ???
0F1E-   C1 C9       CMP   ($C9,X)
0F20-   D4          ???
0F21-   8D A0 DF    STA   $DFA0
0F24-   D0 D2       BNE   $0EF8
0F26-   CE D4 A0    DEC   $A0D4
0F29-   A2 CE       LDX   #$CE
0F2B-   CF          ???
0F2C-   D4          ???
0F2D-   C5 20       CMP   $20
0F2F-   D4          ???
0F30-   C8          INY
0F31-   C1 D4       CMP   ($D4,X)
0F33-   20 CF CE    JSR   $CECF
0F36-   CC D9 20    CPY   $20D9
0F39-   C1 20       CMP   ($20,X)
0F3B-   D3          ???
0F3C-   C9 CE       CMP   #$CE
0F3E-   C7          ???
0F3F-   CC C5 20    CPY   $20C5
0F42-   D0 C1       BNE   $0F05
0F44-   D2 C1       CMP   ($C1)
0F46-   CD C5 D4    CMP   $D4C5
0F49-   C5 D2       CMP   $D2
0F4B-   A2 AC       LDX   #$AC
0F4D-   B8          CLV
0F4E-   C4 8D       CPY   $8D
0F50-   A0 DF       LDY   #$DF
0F52-   D0 D2       BNE   $0F26
0F54-   CE D4 A0    DEC   $A0D4
0F57-   A2 CD       LDX   #$CD
0F59-   C1 D9       CMP   ($D9,X)
0F5B-   20 C2 C5    JSR   $C5C2
0F5E-   20 C1 20    JSR   $20C1
0F61-   CC C9 D4    CPY   $D4C9
0F64-   C5 D2       CMP   $D2
0F66-   C1 CC       CMP   ($CC,X)
0F68-   20 D3 D4    JSR   $D4D3
0F6B-   D2 C9       CMP   ($C9)
0F6D-   CE C7 20    DEC   $20C7
0F70-   C9 CE       CMP   #$CE
0F72-   20 D3 C3    JSR   $C3D3
0F75-   CD D0 BB    CMP   $BBD0
0F78-   A2 AC       LDX   #$AC
0F7A-   B8          CLV
0F7B-   C4 8D       CPY   $8D
0F7D-   A0 DF       LDY   #$DF
0F7F-   D0 D2       BNE   $0F53
0F81-   CE D4 A0    DEC   $A0D4
0F84-   A2 D4       LDX   #$D4
0F86-   C8          INY
0F87-   C9 D3       CMP   #$D3
0F89-   20 D3 C1    JSR   $C1D3
0F8C-   CD C5 20    CMP   $20C5
0F8F-   D2 D5       CMP   ($D5)
0F91-   CC C5 20    CPY   $20C5
0F94-   C1 D0       CMP   ($D0,X)
0F96-   D0 CC       BNE   $0F64
0F98-   C9 C5       CMP   #$C5
0F9A-   D3          ???
0F9B-   20 D4 CF    JSR   $CFD4
0F9E-   20 C1 CC    JSR   $CCC1
0FA1-   CC 20 CD    CPY   $CD20
0FA4-   C1 C3       CMP   ($C3,X)
0FA6-   D2 CF       CMP   ($CF)
0FA8-   D3          ???
0FA9-   A2 AC       LDX   #$AC
0FAB-   B8          CLV
0FAC-   C4 8D       CPY   $8D
0FAE-   A0 DF       LDY   #$DF
0FB0-   D0 D2       BNE   $0F84
0FB2-   CE D4 A0    DEC   $A0D4
0FB5-   A2 D4       LDX   #$D4
0FB7-   C8          INY
0FB8-   C1 D4       CMP   ($D4,X)
0FBA-   20 C1 C3    JSR   $C3C1
0FBD-   C3          ???
0FBE-   C5 D0       CMP   $D0
0FC0-   D4          ???
0FC1-   20 D3 D4    JSR   $D4D3
0FC4-   D2 C9       CMP   ($C9)
0FC6-   CE C7 D3    DEC   $D3C7
0FC9-   20 C1 D3    JSR   $D3C1
0FCC-   20 D0 C1    JSR   $C1D0
0FCF-   D2 C1       CMP   ($C1)
0FD1-   CD C5 D4    CMP   $D4C5
0FD4-   C5 D2       CMP   $D2
0FD6-   D3          ???
0FD7-   AE A2 AC    LDX   $ACA2
0FDA-   B8          CLV
0FDB-   C4 B8       CPY   $B8
0FDD-   C4 8D       CPY   $8D
0FDF-   A0 DF       LDY   #$DF
0FE1-   D0 D2       BNE   $0FB5
0FE3-   CE D4 A0    DEC   $A0D4
0FE6-   A2 D9       LDX   #$D9
0FE8-   CF          ???
0FE9-   D5 20       CMP   $20,X
0FEB-   C3          ???
0FEC-   C1 CE       CMP   ($CE,X)
0FEE-   20 C1 CC    JSR   $CCC1
0FF1-   D3          ???
0FF2-   CF          ???
0FF3-   20 D5 D3    JSR   $D3D5
0FF6-   C5 20       CMP   $20
0FF8-   D3          ???
0FF9-   C3          ???
0FFA-   CD D0 20    CMP   $20D0
0FFD-   D4          ???
0FFE-   CF          ???
0FFF-   20 C3 CF    JSR   $CFC3
1002-   CD D0 C1    CMP   $C1D0
1005-   D2 C5       CMP   ($C5)
1007-   A2 AC       LDX   #$AC
1009-   B8          CLV
100A-   C4 8D       CPY   $8D
100C-   A0 DF       LDY   #$DF
100E-   D0 D2       BNE   $0FE2
1010-   CE D4 A0    DEC   $A0D4
1013-   A2 D4       LDX   #$D4
1015-   C8          INY
1016-   C5 20       CMP   $20
1018-   CC C5 CE    CPY   $CEC5
101B-   C7          ???
101C-   D4          ???
101D-   C8          INY
101E-   D3          ???
101F-   20 CF C6    JSR   $C6CF
1022-   20 D4 D7    JSR   $D7D4
1025-   CF          ???
1026-   20 C4 C9    JSR   $C9C4
1029-   C6 C6       DEC   $C6
102B-   C5 D2       CMP   $D2
102D-   C5 CE       CMP   $CE
102F-   D4          ???
1030-   20 D3 D4    JSR   $D4D3
1033-   D2 C9       CMP   ($C9)
1035-   CE C7 D3    DEC   $D3C7
1038-   AE A2 AC    LDX   $ACA2
103B-   B8          CLV
103C-   C4 B8       CPY   $B8
103E-   C4 8D       CPY   $8D
1040-   A0 DF       LDY   #$DF
1042-   D0 D2       BNE   $1016
1044-   CE D4 A0    DEC   $A0D4
1047-   A2 D4       LDX   #$D4
1049-   C8          INY
104A-   C5 20       CMP   $20
104C-   C3          ???
104D-   C1 D2       CMP   ($D2,X)
104F-   D2 D9       CMP   ($D9)
1051-   20 C6 CC    JSR   $CCC6
1054-   C1 C7       CMP   ($C7,X)
1056-   20 C9 D3    JSR   $D3C9
1059-   20 D3 C5    JSR   $C5D3
105C-   D4          ???
105D-   20 D4 CF    JSR   $CFD4
1060-   20 B0 20    JSR   $20B0
1063-   C9 C6       CMP   #$C6
1065-   20 D4 C8    JSR   $C8D4
1068-   C5 A2       CMP   $A2
106A-   AC B8 C4    LDY   $C4B8
106D-   8D A0 DF    STA   $DFA0
1070-   D0 D2       BNE   $1044
1072-   CE D4 A0    DEC   $A0D4
1075-   A2 C6       LDX   #$C6
1077-   C9 D2       CMP   #$D2
1079-   D3          ???
107A-   D4          ???
107B-   20 D3 D4    JSR   $D4D3
107E-   D2 C9       CMP   ($C9)
1080-   CE C7 20    DEC   $20C7
1083-   C8          INY
1084-   C1 D3       CMP   ($D3,X)
1086-   20 C1 20    JSR   $20C1
1089-   CC C5 CE    CPY   $CEC5
108C-   C7          ???
108D-   D4          ???
108E-   C8          INY
108F-   20 BE 20    JSR   $20BE
1092-   D4          ???
1093-   C8          INY
1094-   C1 CE       CMP   ($CE,X)
1096-   20 D4 C8    JSR   $C8D4
1099-   C5 20       CMP   $20
109B-   A2 AC       LDX   #$AC
109D-   B8          CLV
109E-   C4 8D       CPY   $8D
10A0-   A0 DF       LDY   #$DF
10A2-   D0 D2       BNE   $1076
10A4-   CE D4 A0    DEC   $A0D4
10A7-   A2 D3       LDX   #$D3
10A9-   C5 C3       CMP   $C3
10AB-   CF          ???
10AC-   CE C4 20    DEC   $20C4
10AF-   D3          ???
10B0-   D4          ???
10B1-   D2 C9       CMP   ($C9)
10B3-   CE C7 A7    DEC   $A7C7
10B6-   D3          ???
10B7-   20 CC C5    JSR   $C5CC
10BA-   CE C7 D4    DEC   $D4C7
10BD-   C8          INY
10BE-   AE 20 D4    LDX   $D420
10C1-   C8          INY
10C2-   C9 D3       CMP   #$D3
10C4-   20 C3 C1    JSR   $C1C3
10C7-   CE 20 D4    DEC   $D420
10CA-   C8          INY
10CB-   C5 CE       CMP   $CE
10CD-   A2 AC       LDX   #$AC
10CF-   B8          CLV
10D0-   C4 8D       CPY   $8D
10D2-   A0 DF       LDY   #$DF
10D4-   D0 D2       BNE   $10A8
10D6-   CE D4 A0    DEC   $A0D4
10D9-   A2 C2       LDX   #$C2
10DB-   C5 20       CMP   $20
10DD-   D4          ???
10DE-   C5 D3       CMP   $D3
10E0-   D4          ???
10E1-   C5 C4       CMP   $C4
10E3-   20 D7 C9    JSR   $C9D7
10E6-   D4          ???
10E7-   C8          INY
10E8-   20 C2 C3    JSR   $C3C2
10EB-   D3          ???
10EC-   AE A2 AC    LDX   $ACA2
10EF-   B8          CLV
10F0-   C4 B8       CPY   $B8
10F2-   C4 8D       CPY   $8D
10F4-   A0 DF       LDY   #$DF
10F6-   D0 D2       BNE   $10CA
10F8-   CE D4 A0    DEC   $A0D4
10FB-   A2 D3       LDX   #$D3
10FD-   CF          ???
10FE-   20 C9 C6    JSR   $C6C9
1101-   20 D7 C5    JSR   $C5D7
1104-   20 C3 CF    JSR   $CFC3
1107-   CD D0 C1    CMP   $C1D0
110A-   D2 C5       CMP   ($C5)
110C-   20 D4 C8    JSR   $C8D4
110F-   C5 20       CMP   $20
1111-   CC C9 D4    CPY   $D4C9
1114-   C5 D2       CMP   $D2
1116-   C1 CC       CMP   ($CC,X)
1118-   20 A7 C1    JSR   $C1A7
111B-   C1 A7       CMP   ($A7,X)
111D-   20 A2 AC    JSR   $ACA2
1120-   B8          CLV
1121-   C4 8D       CPY   $8D
1123-   A0 DF       LDY   #$DF
1125-   D0 D2       BNE   $10F9
1127-   CE D4 A0    DEC   $A0D4
112A-   A2 D4       LDX   #$D4
112C-   CF          ???
112D-   20 D4 C8    JSR   $C8D4
1130-   C5 20       CMP   $20
1132-   D3          ???
1133-   C1 CD       CMP   ($CD,X)
1135-   C5 20       CMP   $20
1137-   C1 D3       CMP   ($D3,X)
1139-   D4          ???
113A-   D2 AC       CMP   ($AC)
113C-   20 D7 C5    JSR   $C5D7
113F-   20 D7 C9    JSR   $C9D7
1142-   CC CC 20    CPY   $20CC
1145-   C6 C9       DEC   $C9
1147-   CE C4 20    DEC   $20C4
114A-   D4          ???
114B-   C8          INY
114C-   C1 D4       CMP   ($D4,X)
114E-   A2 AC       LDX   #$AC
1150-   B8          CLV
1151-   C4 8D       CPY   $8D
1153-   A0 DF       LDY   #$DF
1155-   D0 D2       BNE   $1129
1157-   CE D4 A0    DEC   $A0D4
115A-   A2 D4       LDX   #$D4
115C-   C8          INY
115D-   C5 20       CMP   $20
115F-   CC C9 D4    CPY   $D4C9
1162-   C5 D2       CMP   $D2
1164-   C1 CC       CMP   ($CC,X)
1166-   20 C8 C1    JSR   $C1C8
1169-   D3          ???
116A-   20 C1 20    JSR   $20C1
116D-   C7          ???
116E-   D2 C5       CMP   ($C5)
1170-   C1 D4       CMP   ($D4,X)
1172-   C5 D2       CMP   $D2
1174-   20 CC C5    JSR   $C5CC
1177-   CE C7 D4    DEC   $D4C7
117A-   C8          INY
117B-   AE A2 AC    LDX   $ACA2
117E-   B8          CLV
117F-   C4 B8       CPY   $B8
1181-   C4 8D       CPY   $8D
1183-   AA          TAX
1184-   8D A0 D3    STA   $D3A0
1187-   C3          ???
1188-   CD D0 A0    CMP   $A0D0
118B-   A2 C1       LDX   #$C1
118D-   C1 A2       CMP   ($A2,X)
118F-   BB          ???
1190-   C1 D3       CMP   ($D3,X)
1192-   D4          ???
1193-   D2 8D       CMP   ($8D)
1195-   A0 C2       LDY   #$C2
1197-   C3          ???
1198-   D3          ???
1199-   A0 CC       LDY   #$CC
119B-   C5 8D       CMP   $8D
119D-   A0 CA       LDY   #$CA
119F-   CD D0 A0    CMP   $A0D0
11A2-   C3          ???
11A3-   CF          ???
11A4-   CE D4 B2    DEC   $B2D4
11A7-   8D CC C5    STA   $C5CC
11AA-   8D A0 DF    STA   $DFA0
11AD-   D0 D2       BNE   $1181
11AF-   CE D4 A0    DEC   $A0D4
11B2-   A2 D4       LDX   #$D4
11B4-   C8          INY
11B5-   C5 20       CMP   $20
11B7-   CC C9 D4    CPY   $D4C9
11BA-   C5 D2       CMP   $D2
11BC-   C1 CC       CMP   ($CC,X)
11BE-   20 A7 C1    JSR   $C1A7
11C1-   C1 A7       CMP   ($A7,X)
11C3-   20 C9 D3    JSR   $D3C9
11C6-   20 C7 D2    JSR   $D2C7
11C9-   C5 C1       CMP   $C1
11CB-   D4          ???
11CC-   C5 D2       CMP   $D2
11CE-   20 D4 C8    JSR   $C8D4
11D1-   C1 CE       CMP   ($CE,X)
11D3-   20 A2 AC    JSR   $ACA2
11D6-   B8          CLV
11D7-   C4 8D       CPY   $8D
11D9-   A0 DF       LDY   #$DF
11DB-   D0 D2       BNE   $11AF
11DD-   CE D4 A0    DEC   $A0D4
11E0-   A2 C1       LDX   #$C1
11E2-   D3          ???
11E3-   D4          ???
11E4-   D2 AC       CMP   ($AC)
11E6-   20 D7 C8    JSR   $C8D7
11E9-   C9 C3       CMP   #$C3
11EB-   C8          INY
11EC-   20 C8 CF    JSR   $CFC8
11EF-   CC C4 D3    CPY   $D3C4
11F2-   20 A7 C1    JSR   $C1A7
11F5-   A7          ???
11F6-   AE A2 AC    LDX   $ACA2
11F9-   B8          CLV
11FA-   C4 B8       CPY   $B8
11FC-   C4 B8       CPY   $B8
11FE-   C4 8D       CPY   $8D
1200-   C3          ???
1201-   CF          ???
1202-   CE D4 B2    DEC   $B2D4
1205-   8D A0 DF    STA   $DFA0
1208-   D7          ???
1209-   C1 C9       CMP   ($C9,X)
120B-   D4          ???
120C-   8D AA 8D    STA   $8DAA
120F-   A0 DF       LDY   #$DF
1211-   D0 D2       BNE   $11E5
1213-   CE D4 A0    DEC   $A0D4
1216-   A2 20       LDX   #$20
1218-   A2 AC       LDX   #$AC
121A-   B8          CLV
121B-   C4 B8       CPY   $B8
121D-   C4 B8       CPY   $B8
121F-   C4 B8       CPY   $B8
1221-   C4 8D       CPY   $8D
1223-   A0 DF       LDY   #$DF
1225-   D0 D2       BNE   $11F9
1227-   CE D4 A0    DEC   $A0D4
122A-   A2 D4       LDX   #$D4
122C-   C8          INY
122D-   C5 20       CMP   $20
122F-   D3          ???
1230-   C3          ???
1231-   C1 D4       CMP   ($D4,X)
1233-   20 CD C1    JSR   $C1CD
1236-   C3          ???
1237-   D2 CF       CMP   ($CF)
1239-   20 C3 CF    JSR   $CFC3
123C-   CE C3 C1    DEC   $C1C3
123F-   D4          ???
1240-   C5 CE       CMP   $CE
1242-   C1 D4       CMP   ($D4,X)
1244-   C5 D3       CMP   $D3
1246-   A2 AC       LDX   #$AC
1248-   B8          CLV
1249-   C4 8D       CPY   $8D
124B-   A0 DF       LDY   #$DF
124D-   D0 D2       BNE   $1221
124F-   CE D4 A0    DEC   $A0D4
1252-   A2 C1       LDX   #$C1
1254-   20 D3 C5    JSR   $C5D3
1257-   C3          ???
1258-   CF          ???
1259-   CE C4 20    DEC   $20C4
125C-   C7          ???
125D-   C9 D6       CMP   #$D6
125F-   C5 CE       CMP   $CE
1261-   20 D3 D4    JSR   $D4D3
1264-   D2 C9       CMP   ($C9)
1266-   CE C7 20    DEC   $20C7
1269-   D4          ???
126A-   CF          ???
126B-   20 C1 20    JSR   $20C1
126E-   A2 AC       LDX   #$AC
1270-   B8          CLV
1271-   C4 8D       CPY   $8D
1273-   A0 DF       LDY   #$DF
1275-   D0 D2       BNE   $1249
1277-   CE D4 A0    DEC   $A0D4
127A-   A2 C6       LDX   #$C6
127C-   C9 D2       CMP   #$D2
127E-   D3          ???
127F-   D4          ???
1280-   20 C7 C9    JSR   $C9C7
1283-   D6 C5       DEC   $C5,X
1285-   CE 20 D3    DEC   $D320
1288-   D4          ???
1289-   D2 C9       CMP   ($C9)
128B-   CE C7 AE    DEC   $AEC7
128E-   20 C5 C9    JSR   $C9C5
1291-   D4          ???
1292-   C8          INY
1293-   C5 D2       CMP   $D2
1295-   20 D0 C1    JSR   $C1D0
1298-   D2 C1       CMP   ($C1)
129A-   CD C5 D4    CMP   $D4C5
129D-   C5 D2       CMP   $D2
129F-   A2 AC       LDX   #$AC
12A1-   B8          CLV
12A2-   C4 8D       CPY   $8D
12A4-   A0 DF       LDY   #$DF
12A6-   D0 D2       BNE   $127A
12A8-   CE D4 A0    DEC   $A0D4
12AB-   A2 CD       LDX   #$CD
12AD-   C1 D9       CMP   ($D9,X)
12AF-   20 C2 C5    JSR   $C5C2
12B2-   20 C1 20    JSR   $20C1
12B5-   CC C9 D4    CPY   $D4C9
12B8-   C5 D2       CMP   $D2
12BA-   C1 CC       CMP   ($CC,X)
12BC-   20 D3 D4    JSR   $D4D3
12BF-   D2 C9       CMP   ($C9)
12C1-   CE C7 AC    DEC   $ACC7
12C4-   20 C2 D5    JSR   $D5C2
12C7-   D4          ???
12C8-   20 CE C5    JSR   $C5CE
12CB-   D6 C5       DEC   $C5,X
12CD-   D2 20       CMP   ($20)
12CF-   C2          ???
12D0-   CF          ???
12D1-   D4          ???
12D2-   C8          INY
12D3-   AE A2 AC    LDX   $ACA2
12D6-   B8          CLV
12D7-   C4 B8       CPY   $B8
12D9-   C4 8D       CPY   $8D
12DB-   A0 DF       LDY   #$DF
12DD-   D0 D2       BNE   $12B1
12DF-   CE D4 A0    DEC   $A0D4
12E2-   A2 D3       LDX   #$D3
12E4-   C3          ???
12E5-   C1 D4       CMP   ($D4,X)
12E7-   20 A7 D7    JSR   $D7A7
12EA-   D4          ???
12EB-   C6 20       DEC   $20
12ED-   C9 D3       CMP   #$D3
12EF-   20 A7 BB    JSR   $BBA7
12F2-   C1 D3       CMP   ($D3,X)
12F4-   D4          ???
12F5-   D2 BB       CMP   ($BB)
12F7-   A3          ???
12F8-   B5 B0       LDA   $B0,X
12FA-   20 D2 C5    JSR   $C5D2
12FD-   D4          ???
12FE-   D5 D2       CMP   $D2,X
1300-   CE D3 BA    DEC   $BAD3
1303-   20 A2 AC    JSR   $ACA2
1306-   B8          CLV
1307-   C4 B8       CPY   $B8
1309-   C4 8D       CPY   $8D
130B-   A0 D3       LDY   #$D3
130D-   C3          ???
130E-   C1 D4       CMP   ($D4,X)
1310-   A0 A2       LDY   #$A2
1312-   D7          ???
1313-   D4          ???
1314-   C6 20       DEC   $20
1316-   C9 D3       CMP   #$D3
1318-   20 A2 BB    JSR   $BBA2
131B-   C1 D3       CMP   ($D3,X)
131D-   D4          ???
131E-   D2 BB       CMP   ($BB)
1320-   A3          ???
1321-   B5 B0       LDA   $B0,X
1323-   8D A0 D3    STA   $D3A0
1326-   D0 D2       BNE   $12FA
1328-   CE A0 D2    DEC   $D2A0
132B-   C5 D4       CMP   $D4
132D-   D5 D2       CMP   $D2,X
132F-   CE 8D A0    DEC   $A08D
1332-   DF          ???
1333-   D0 D2       BNE   $1307
1335-   CE D4 A0    DEC   $A0D4
1338-   A2 20       LDX   #$20
133A-   A2 AC       LDX   #$AC
133C-   B8          CLV
133D-   C4 B8       CPY   $B8
133F-   C4 B8       CPY   $B8
1341-   C4 8D       CPY   $8D
1343-   A0 DF       LDY   #$DF
1345-   D7          ???
1346-   C1 C9       CMP   ($C9,X)
1348-   D4          ???
1349-   8D AA 8D    STA   $8DAA
134C-   A0 DF       LDY   #$DF
134E-   D0 D2       BNE   $1322
1350-   CE D4 A0    DEC   $A0D4
1353-   A2 D4       LDX   #$D4
1355-   CF          ???
1356-   20 D3 C8    JSR   $C8D3
1359-   CF          ???
135A-   D7          ???
135B-   20 D4 C8    JSR   $C8D4
135E-   C5 20       CMP   $20
1360-   D2 C5       CMP   ($C5)
1362-   D3          ???
1363-   D5 CC       CMP   $CC,X
1365-   D4          ???
1366-   20 CF C6    JSR   $C6CF
1369-   20 D3 C3    JSR   $C3D3
136C-   C1 D4       CMP   ($D4,X)
136E-   AC A2 AC    LDY   $ACA2
1371-   B8          CLV
1372-   C4 8D       CPY   $8D
1374-   A0 DF       LDY   #$DF
1376-   D0 D2       BNE   $134A
1378-   CE D4 A0    DEC   $A0D4
137B-   A2 D7       LDX   #$D7
137D-   C5 20       CMP   $20
137F-   D5 D3       CMP   $D3,X
1381-   C5 C4       CMP   $C4
1383-   20 D4 C8    JSR   $C8D4
1386-   C5 20       CMP   $20
1388-   D3          ???
1389-   D0 D2       BNE   $135D
138B-   CE 20 CD    DEC   $CD20
138E-   C1 C3       CMP   ($C3,X)
1390-   D2 CF       CMP   ($CF)
1392-   AC 20 D7    LDY   $D720
1395-   C8          INY
1396-   C9 C3       CMP   #$C3
1398-   C8          INY
1399-   A2 AC       LDX   #$AC
139B-   B8          CLV
139C-   C4 8D       CPY   $8D
139E-   A0 DF       LDY   #$DF
13A0-   D0 D2       BNE   $1374
13A2-   CE D4 A0    DEC   $A0D4
13A5-   A2 D3       LDX   #$D3
13A7-   C9 CD       CMP   #$CD
13A9-   D0 CC       BNE   $1377
13AB-   D9 20 D0    CMP   $D020,Y
13AE-   D2 C9       CMP   ($C9)
13B0-   CE D4 D3    DEC   $D3D4
13B3-   20 C1 20    JSR   $20C1
13B6-   D3          ???
13B7-   D4          ???
13B8-   D2 C9       CMP   ($C9)
13BA-   CE C7 AE    DEC   $AEC7
13BD-   20 D4 C8    JSR   $C8D4
13C0-   C9 D3       CMP   #$D3
13C2-   A2 AC       LDX   #$AC
13C4-   B8          CLV
13C5-   C4 8D       CPY   $8D
13C7-   A0 DF       LDY   #$DF
13C9-   D0 D2       BNE   $139D
13CB-   CE D4 A0    DEC   $A0D4
13CE-   A2 D7       LDX   #$D7
13D0-   CF          ???
13D1-   D2 CB       CMP   ($CB)
13D3-   D3          ???
13D4-   20 C4 C9    JSR   $C9C4
13D7-   C6 C6       DEC   $C6
13D9-   C5 D2       CMP   $D2
13DB-   C5 CE       CMP   $CE
13DD-   D4          ???
13DE-   CC D9 20    CPY   $20D9
13E1-   D4          ???
13E2-   C8          INY
13E3-   C1 CE       CMP   ($CE,X)
13E5-   20 D4 C8    JSR   $C8D4
13E8-   C5 20       CMP   $20
13EA-   D0 D2       BNE   $13BE
13EC-   C9 CE       CMP   #$CE
13EE-   D4          ???
13EF-   A2 AC       LDX   #$AC
13F1-   B8          CLV
13F2-   C4 8D       CPY   $8D
13F4-   A0 DF       LDY   #$DF
13F6-   D0 D2       BNE   $13CA
13F8-   CE D4 A0    DEC   $A0D4
13FB-   A2 D2       LDX   #$D2
13FD-   CF          ???
13FE-   D5 D4       CMP   $D4,X
1400-   C9 CE       CMP   #$CE
1402-   C5 D3       CMP   $D3
1404-   20 C9 CE    JSR   $CEC9
1407-   20 D3 D4    JSR   $D4D3
140A-   C4 C9       CPY   $C9
140C-   CF          ???
140D-   20 CF D2    JSR   $D2CF
1410-   20 D4 C8    JSR   $C8D4
1413-   C5 20       CMP   $20
1415-   DF          ???
1416-   D0 D2       BNE   $13EA
1418-   CE D4 A2    DEC   $A2D4
141B-   AC B8 C4    LDY   $C4B8
141E-   8D A0 DF    STA   $DFA0
1421-   D0 D2       BNE   $13F5
1423-   CE D4 A0    DEC   $A0D4
1426-   A2 D2       LDX   #$D2
1428-   CF          ???
1429-   D5 D4       CMP   $D4,X
142B-   C9 CE       CMP   #$CE
142D-   C5 AC       CMP   $AC
142F-   20 C1 D3    JSR   $D3C1
1432-   20 C9 D4    JSR   $D4C9
1435-   20 C3 C1    JSR   $C1C3
1438-   CE 20 CF    DEC   $CF20
143B-   CE CC D9    DEC   $D9CC
143E-   20 C8 C1    JSR   $C1C8
1441-   CE C4 CC    DEC   $CCC4
1444-   C5 A2       CMP   $A2
1446-   AC B8 C4    LDY   $C4B8
1449-   8D A0 DF    STA   $DFA0
144C-   D0 D2       BNE   $1420
144E-   CE D4 A0    DEC   $A0D4
1451-   A2 C1       LDX   #$C1
1453-   20 D3 D4    JSR   $D4D3
1456-   D2 C9       CMP   ($C9)
1458-   CE C7 20    DEC   $20C7
145B-   C1 C4       CMP   ($C4,X)
145D-   C4 D2       CPY   $D2
145F-   C5 D3       CMP   $D3
1461-   D3          ???
1462-   AE A2 AC    LDX   $ACA2
1465-   B8          CLV
1466-   C4 B8       CPY   $B8
1468-   C4 8D       CPY   $8D
146A-   A0 DF       LDY   #$DF
146C-   D0 D2       BNE   $1440
146E-   CE D4 A0    DEC   $A0D4
1471-   A2 D3       LDX   #$D3
1473-   D0 D2       BNE   $1447
1475-   CE 20 C2    DEC   $C220
1478-   D3          ???
1479-   D4          ???
147A-   D2 20       CMP   ($20)
147C-   D2 C5       CMP   ($C5)
147E-   D4          ???
147F-   D5 D2       CMP   $D2,X
1481-   CE D3 BA    DEC   $BAD3
1484-   20 A2 8D    JSR   $8DA2
1487-   A0 D3       LDY   #$D3
1489-   D0 D2       BNE   $145D
148B-   CE A0 C2    DEC   $C2A0
148E-   D3          ???
148F-   D4          ???
1490-   D2 8D       CMP   ($8D)
1492-   A0 DF       LDY   #$DF
1494-   D0 D2       BNE   $1468
1496-   CE D4 A0    DEC   $A0D4
1499-   A2 20       LDX   #$20
149B-   A2 AC       LDX   #$AC
149D-   B8          CLV
149E-   C4 B8       CPY   $B8
14A0-   C4 B8       CPY   $B8
14A2-   C4 8D       CPY   $8D
14A4-   A0 DF       LDY   #$DF
14A6-   D7          ???
14A7-   C1 C9       CMP   ($C9,X)
14A9-   D4          ???
14AA-   8D A0 DF    STA   $DFA0
14AD-   D0 D2       BNE   $1481
14AF-   CE D4 A0    DEC   $A0D4
14B2-   A2 20       LDX   #$20
14B4-   A2 AC       LDX   #$AC
14B6-   B8          CLV
14B7-   C4 B8       CPY   $B8
14B9-   C4 B8       CPY   $B8
14BB-   C4 8D       CPY   $8D
14BD-   A0 DF       LDY   #$DF
14BF-   D0 D2       BNE   $1493
14C1-   CE D4 A0    DEC   $A0D4
14C4-   A2 D4       LDX   #$D4
14C6-   CF          ???
14C7-   D3          ???
14C8-   D4          ???
14C9-   D2 20       CMP   ($20)
14CB-   C3          ???
14CC-   CF          ???
14CD-   CE D6 C5    DEC   $C5D6
14D0-   D2 D4       CMP   ($D4)
14D2-   D3          ???
14D3-   20 C1 20    JSR   $20C1
14D6-   B1 B6       LDA   ($B6),Y
14D8-   AD C2 C9    LDA   $C9C2
14DB-   D4          ???
14DC-   20 C9 CE    JSR   $CEC9
14DF-   D4          ???
14E0-   C5 C7       CMP   $C7
14E2-   C5 D2       CMP   $D2
14E4-   20 C9 CE    JSR   $CEC9
14E7-   D4          ???
14E8-   CF          ???
14E9-   A2 AC       LDX   #$AC
14EB-   B8          CLV
14EC-   C4 8D       CPY   $8D
14EE-   A0 DF       LDY   #$DF
14F0-   D0 D2       BNE   $14C4
14F2-   CE D4 A0    DEC   $A0D4
14F5-   A2 C9       LDX   #$C9
14F7-   D4          ???
14F8-   D3          ???
14F9-   20 D3 D4    JSR   $D4D3
14FC-   D2 C9       CMP   ($C9)
14FE-   CE C7 20    DEC   $20C7
1501-   C5 D1       CMP   $D1
1503-   D5 C9       CMP   $C9,X
1505-   D6 C1       DEC   $C1,X
1507-   CC C5 CE    CPY   $CEC5
150A-   D4          ???
150B-   AE 20 D4    LDX   $D420
150E-   C8          INY
150F-   C9 D3       CMP   #$D3
1511-   20 C3 C1    JSR   $C1C3
1514-   CE A2 AC    DEC   $ACA2
1517-   B8          CLV
1518-   C4 8D       CPY   $8D
151A-   A0 DF       LDY   #$DF
151C-   D0 D2       BNE   $14F0
151E-   CE D4 A0    DEC   $A0D4
1521-   A2 C5       LDX   #$C5
1523-   C9 D4       CMP   #$D4
1525-   C8          INY
1526-   C5 D2       CMP   $D2
1528-   20 C2 C5    JSR   $C5C2
152B-   20 C1 20    JSR   $20C1
152E-   CC C9 D4    CPY   $D4C9
1531-   C5 D2       CMP   $D2
1533-   C1 CC       CMP   ($CC,X)
1535-   20 CF D2    JSR   $D2CF
1538-   20 C1 CE    JSR   $CEC1
153B-   20 C1 C4    JSR   $C4C1
153E-   C4 D2       CPY   $D2
1540-   C5 D3       CMP   $D3
1542-   D3          ???
1543-   AE A2 8D    LDX   $8DA2
1546-   A0 DF       LDY   #$DF
1548-   D0 D2       BNE   $151C
154A-   CE D4 A0    DEC   $A0D4
154D-   A2 20       LDX   #$20
154F-   A2 AC       LDX   #$AC
1551-   B8          CLV
1552-   C4 B8       CPY   $B8
1554-   C4 8D       CPY   $8D
1556-   A0 DF       LDY   #$DF
1558-   D0 D2       BNE   $152C
155A-   CE D4 A0    DEC   $A0D4
155D-   A2 D4       LDX   #$D4
155F-   CF          ???
1560-   D3          ???
1561-   D4          ???
1562-   D2 20       CMP   ($20)
1564-   A3          ???
1565-   B5 B0       LDA   $B0,X
1567-   B0 B0       BCS   $1519
1569-   20 D2 C5    JSR   $C5D2
156C-   D4          ???
156D-   D5 D2       CMP   $D2,X
156F-   CE D3 BA    DEC   $BAD3
1572-   20 A2 8D    JSR   $8DA2
1575-   A0 D4       LDY   #$D4
1577-   CF          ???
1578-   D3          ???
1579-   D4          ???
157A-   D2 A0       CMP   ($A0)
157C-   A3          ???
157D-   B5 B0       LDA   $B0,X
157F-   B0 B0       BCS   $1531
1581-   8D A0 D3    STA   $D3A0
1584-   D0 D2       BNE   $1558
1586-   CE A0 D2    DEC   $D2A0
1589-   C5 D4       CMP   $D4
158B-   D5 D2       CMP   $D2,X
158D-   CE 8D A0    DEC   $A08D
1590-   DF          ???
1591-   D0 D2       BNE   $1565
1593-   CE D4 A0    DEC   $A0D4
1596-   A2 20       LDX   #$20
1598-   A2 AC       LDX   #$AC
159A-   B8          CLV
159B-   C4 B8       CPY   $B8
159D-   C4 8D       CPY   $8D
159F-   A0 DF       LDY   #$DF
15A1-   D0 D2       BNE   $1575
15A3-   CE D4 A0    DEC   $A0D4
15A6-   A2 D4       LDX   #$D4
15A8-   CF          ???
15A9-   D3          ???
15AA-   D4          ???
15AB-   D2 20       CMP   ($20)
15AD-   A4 B3       LDY   $B3
15AF-   B0 B0       BCS   $1561
15B1-   20 D2 C5    JSR   $C5D2
15B4-   D4          ???
15B5-   D5 D2       CMP   $D2,X
15B7-   CE D3 20    DEC   $20D3
15BA-   A2 8D       LDX   #$8D
15BC-   A0 CC       LDY   #$CC
15BE-   C4 C1       CPY   $C1
15C0-   A0 A3       LDY   #$A3
15C2-   A4 C6       LDY   $C6
15C4-   C6 8D       DEC   $8D
15C6-   A0 D3       LDY   #$D3
15C8-   D4          ???
15C9-   C1 A0       CMP   ($A0,X)
15CB-   A4 B3       LDY   $B3
15CD-   B0 B0       BCS   $157F
15CF-   8D A0 D3    STA   $D3A0
15D2-   D4          ???
15D3-   C1 A0       CMP   ($A0,X)
15D5-   A4 B3       LDY   $B3
15D7-   B0 B1       BCS   $158A
15D9-   8D A0 D4    STA   $D4A0
15DC-   CF          ???
15DD-   D3          ???
15DE-   D4          ???
15DF-   D2 A0       CMP   ($A0)
15E1-   A4 B3       LDY   $B3
15E3-   B0 B0       BCS   $1595
15E5-   8D A0 D3    STA   $D3A0
15E8-   D0 D2       BNE   $15BC
15EA-   CE A0 D2    DEC   $D2A0
15ED-   C5 D4       CMP   $D4
15EF-   D5 D2       CMP   $D2,X
15F1-   CE 8D A0    DEC   $A08D
15F4-   DF          ???
15F5-   D0 D2       BNE   $15C9
15F7-   CE D4 A0    DEC   $A0D4
15FA-   A2 20       LDX   #$20
15FC-   A2 AC       LDX   #$AC
15FE-   B8          CLV
15FF-   C4 B8       CPY   $B8
1601-   C4 8D       CPY   $8D
1603-   A0 DF       LDY   #$DF
1605-   D0 D2       BNE   $15D9
1607-   CE D4 A0    DEC   $A0D4
160A-   A2 CE       LDX   #$CE
160C-   CF          ???
160D-   D4          ???
160E-   C5 20       CMP   $20
1610-   D4          ???
1611-   C8          INY
1612-   C1 D4       CMP   ($D4,X)
1614-   20 A4 C6    JSR   $C6A4
1617-   C6 C6       DEC   $C6
1619-   C6 20       DEC   $20
161B-   D2 C5       CMP   ($C5)
161D-   D4          ???
161E-   D5 D2       CMP   $D2,X
1620-   CE D3 20    DEC   $20D3
1623-   AD B1 20    LDA   $20B1
1626-   C2          ???
1627-   C5 C3       CMP   $C3
1629-   C1 D5       CMP   ($D5,X)
162B-   D3          ???
162C-   C5 A2       CMP   $A2
162E-   AC B8 C4    LDY   $C4B8
1631-   8D A0 DF    STA   $DFA0
1634-   D0 D2       BNE   $1608
1636-   CE D4 A0    DEC   $A0D4
1639-   A2 D4       LDX   #$D4
163B-   C8          INY
163C-   C5 20       CMP   $20
163E-   D4          ???
163F-   CF          ???
1640-   D3          ???
1641-   D4          ???
1642-   D2 20       CMP   ($20)
1644-   D2 CF       CMP   ($CF)
1646-   D5 D4       CMP   $D4,X
1648-   C9 CE       CMP   #$CE
164A-   C5 20       CMP   $20
164C-   C1 D3       CMP   ($D3,X)
164E-   D3          ???
164F-   D5 CD       CMP   $CD,X
1651-   C5 D3       CMP   $D3
1653-   20 C1 20    JSR   $20C1
1656-   A2 AC       LDX   #$AC
1658-   B8          CLV
1659-   C4 8D       CPY   $8D
165B-   A0 DF       LDY   #$DF
165D-   D0 D2       BNE   $1631
165F-   CE D4 A0    DEC   $A0D4
1662-   A2 D3       LDX   #$D3
1664-   C9 C7       CMP   #$C7
1666-   CE C5 C4    DEC   $C4C5
1669-   20 D6 C1    JSR   $C1D6
166C-   CC D5 C5    CPY   $C5D5
166F-   AE 20 A2    LDX   $A220
1672-   8D A0 DF    STA   $DFA0
1675-   D0 D2       BNE   $1649
1677-   CE D4 A0    DEC   $A0D4
167A-   A2 20       LDX   #$20
167C-   A2 AC       LDX   #$AC
167E-   B8          CLV
167F-   C4 B8       CPY   $B8
1681-   C4 B8       CPY   $B8
1683-   C4 8D       CPY   $8D
1685-   A0 DF       LDY   #$DF
1687-   D7          ???
1688-   C1 C9       CMP   ($C9,X)
168A-   D4          ???
168B-   8D AA 8D    STA   $8DAA
168E-   A0 DF       LDY   #$DF
1690-   D0 D2       BNE   $1664
1692-   CE D4 A0    DEC   $A0D4
1695-   A2 20       LDX   #$20
1697-   A2 AC       LDX   #$AC
1699-   B8          CLV
169A-   C4 B8       CPY   $B8
169C-   C4 B8       CPY   $B8
169E-   C4 8D       CPY   $8D
16A0-   A0 DF       LDY   #$DF
16A2-   D0 D2       BNE   $1676
16A4-   CE D4 A0    DEC   $A0D4
16A7-   A2 C1       LDX   #$C1
16A9-   CE C4 20    DEC   $20C4
16AC-   D4          ???
16AD-   C8          INY
16AE-   C5 20       CMP   $20
16B0-   D4          ???
16B1-   CF          ???
16B2-   CE D5 CD    DEC   $CDD5
16B5-   20 CD C1    JSR   $C1CD
16B8-   C3          ???
16B9-   D2 CF       CMP   ($CF)
16BB-   20 C4 CF    JSR   $CFC4
16BE-   C5 D3       CMP   $D3
16C0-   20 D4 C8    JSR   $C8D4
16C3-   C5 A2       CMP   $A2
16C5-   AC B8 C4    LDY   $C4B8
16C8-   8D A0 DF    STA   $DFA0
16CB-   D0 D2       BNE   $169F
16CD-   CE D4 A0    DEC   $A0D4
16D0-   A2 CF       LDX   #$CF
16D2-   D0 D0       BNE   $16A4
16D4-   CF          ???
16D5-   D3          ???
16D6-   C9 D4       CMP   #$D4
16D8-   C5 BA       CMP   $BA
16DA-   20 C9 D4    JSR   $D4C9
16DD-   20 D2 C5    JSR   $C5D2
16E0-   D4          ???
16E1-   D5 D2       CMP   $D2,X
16E3-   CE D3 20    DEC   $20D3
16E6-   C1 20       CMP   ($20,X)
16E8-   B1 B6       LDA   ($B6),Y
16EA-   AD C2 C9    LDA   $C9C2
16ED-   D4          ???
16EE-   20 A2 AC    JSR   $ACA2
16F1-   B8          CLV
16F2-   C4 8D       CPY   $8D
16F4-   A0 DF       LDY   #$DF
16F6-   D0 D2       BNE   $16CA
16F8-   CE D4 A0    DEC   $A0D4
16FB-   A2 C9       LDX   #$C9
16FD-   CE D4 C5    DEC   $C5D4
1700-   C7          ???
1701-   C5 D2       CMP   $D2
1703-   20 D6 C1    JSR   $C1D6
1706-   CC D5 C5    CPY   $C5D5
1709-   20 C3 CF    JSR   $CFC3
170C-   CE C5 D2    DEC   $D2C5
170F-   D4          ???
1710-   C5 C4       CMP   $C4
1712-   20 C6 D2    JSR   $D2C6
1715-   CF          ???
1716-   CD 20 C9    CMP   $C920
1719-   D4          ???
171A-   D3          ???
171B-   A2 AC       LDX   #$AC
171D-   B8          CLV
171E-   C4 8D       CPY   $8D
1720-   A0 DF       LDY   #$DF
1722-   D0 D2       BNE   $16F6
1724-   CE D4 A0    DEC   $A0D4
1727-   A2 D3       LDX   #$D3
1729-   D4          ???
172A-   D2 C9       CMP   ($C9)
172C-   CE C7 20    DEC   $20C7
172F-   C5 D1       CMP   $D1
1731-   D5 C9       CMP   $C9,X
1733-   D6 C1       DEC   $C1,X
1735-   CC C5 CE    CPY   $CEC5
1738-   D4          ???
1739-   AE 20 D4    LDX   $D420
173C-   C8          INY
173D-   D5 D3       CMP   $D3,X
173F-   BA          TSX
1740-   A2 AC       LDX   #$AC
1742-   B8          CLV
1743-   C4 B8       CPY   $B8
1745-   C4 8D       CPY   $8D
1747-   A0 DF       LDY   #$DF
1749-   D0 D2       BNE   $171D
174B-   CE D4 A0    DEC   $A0D4
174E-   A2 D4       LDX   #$D4
1750-   CF          ???
1751-   CE D5 CD    DEC   $CDD5
1754-   20 A7 B2    JSR   $B2A7
1757-   B5 B5       LDA   $B5,X
1759-   A7          ???
175A-   20 D2 C5    JSR   $C5D2
175D-   D4          ???
175E-   D5 D2       CMP   $D2,X
1760-   CE D3 BA    DEC   $BAD3
1763-   A2 AC       LDX   #$AC
1765-   B8          CLV
1766-   C4 8D       CPY   $8D
1768-   A0 D4       LDY   #$D4
176A-   CF          ???
176B-   CE D5 CD    DEC   $CDD5
176E-   A0 A2       LDY   #$A2
1770-   B2 B5       LDA   ($B5)
1772-   B5 A2       LDA   $A2,X
1774-   8D A0 DF    STA   $DFA0
1777-   C4 D5       CPY   $D5
1779-   CD D0 A0    CMP   $A0D0
177C-   D2 C5       CMP   ($C5)
177E-   D4          ???
177F-   D5 D2       CMP   $D2,X
1781-   CE BB D2    DEC   $D2BB
1784-   C5 D4       CMP   $D4
1786-   CC C5 CE    CPY   $CEC5
1789-   8D A0 DF    STA   $DFA0
178C-   D0 D2       BNE   $1760
178E-   CE D4 A0    DEC   $A0D4
1791-   A2 20       LDX   #$20
1793-   A2 AC       LDX   #$AC
1795-   B8          CLV
1796-   C4 B8       CPY   $B8
1798-   C4 B8       CPY   $B8
179A-   C4 8D       CPY   $8D
179C-   A0 DF       LDY   #$DF
179E-   D7          ???
179F-   C1 C9       CMP   ($C9,X)
17A1-   D4          ???
17A2-   8D AA 8D    STA   $8DAA
17A5-   A0 DF       LDY   #$DF
17A7-   D0 D2       BNE   $177B
17A9-   CE D4 A0    DEC   $A0D4
17AC-   A2 20       LDX   #$20
17AE-   A2 AC       LDX   #$AC
17B0-   B8          CLV
17B1-   C4 B8       CPY   $B8
17B3-   C4 B8       CPY   $B8
17B5-   C4 B8       CPY   $B8
17B7-   C4 8D       CPY   $8D
17B9-   A0 DF       LDY   #$DF
17BB-   D0 D2       BNE   $178F
17BD-   CE D4 A0    DEC   $A0D4
17C0-   A2 D3       LDX   #$D3
17C2-   D5 C2       CMP   $C2,X
17C4-   D3          ???
17C5-   D4          ???
17C6-   D2 C9       CMP   ($C9)
17C8-   CE C7 20    DEC   $20C7
17CB-   D2 CF       CMP   ($CF)
17CD-   D5 D4       CMP   $D4,X
17CF-   C9 CE       CMP   #$CE
17D1-   C5 D3       CMP   $D3
17D3-   AF          ???
17D4-   CD C1 C3    CMP   $C3C1
17D7-   D2 CF       CMP   ($CF)
17D9-   D3          ???
17DA-   A2 AC       LDX   #$AC
17DC-   B8          CLV
17DD-   C4 8D       CPY   $8D
17DF-   A0 DF       LDY   #$DF
17E1-   D0 D2       BNE   $17B5
17E3-   CE D4 A0    DEC   $A0D4
17E6-   A2 AD       LDX   #$AD
17E8-   AD AD AD    LDA   $ADAD
17EB-   AD AD AD    LDA   $ADAD
17EE-   AD AD AD    LDA   $ADAD
17F1-   AD AD AD    LDA   $ADAD
17F4-   AD AD AD    LDA   $ADAD
17F7-   AD AD AD    LDA   $ADAD
17FA-   AD AD AD    LDA   $ADAD
17FD-   AD AD AD    LDA   $ADAD
1800-   A2 AC       LDX   #$AC
1802-   B8          CLV
1803-   C4 B8       CPY   $B8
1805-   C4 8D       CPY   $8D
1807-   A0 DF       LDY   #$DF
1809-   D0 D2       BNE   $17DD
180B-   CE D4 A0    DEC   $A0D4
180E-   A2 D3       LDX   #$D3
1810-   D0 CF       BNE   $17E1
1812-   D3          ???
1813-   20 C6 C9    JSR   $C9C6
1816-   CE C4 D3    DEC   $D3C4
1819-   20 D4 C8    JSR   $C8D4
181C-   C5 20       CMP   $20
181E-   D0 CF       BNE   $17EF
1820-   D3          ???
1821-   C9 D4       CMP   #$D4
1823-   C9 CF       CMP   #$CF
1825-   CE 20 CF    DEC   $CF20
1828-   C6 A2       DEC   $A2
182A-   AC B8 C4    LDY   $C4B8
182D-   8D A0 DF    STA   $DFA0
1830-   D0 D2       BNE   $1804
1832-   CE D4 A0    DEC   $A0D4
1835-   A2 C1       LDX   #$C1
1837-   20 D3 D5    JSR   $D5D3
183A-   C2          ???
183B-   D3          ???
183C-   D4          ???
183D-   D2 C9       CMP   ($C9)
183F-   CE C7 20    DEC   $20C7
1842-   D7          ???
1843-   C9 D4       CMP   #$D4
1845-   C8          INY
1846-   C9 CE       CMP   #$CE
1848-   20 C1 CE    JSR   $CEC1
184B-   CF          ???
184C-   D4          ???
184D-   C8          INY
184E-   C5 D2       CMP   $D2
1850-   A2 AC       LDX   #$AC
1852-   B8          CLV
1853-   C4 8D       CPY   $8D
1855-   A0 DF       LDY   #$DF
1857-   D0 D2       BNE   $182B
1859-   CE D4 A0    DEC   $A0D4
185C-   A2 D3       LDX   #$D3
185E-   D4          ???
185F-   D2 C9       CMP   ($C9)
1861-   CE C7 AE    DEC   $AEC7
1864-   A2 AC       LDX   #$AC
1866-   B8          CLV
1867-   C4 B8       CPY   $B8
1869-   C4 8D       CPY   $8D
186B-   A0 DF       LDY   #$DF
186D-   D0 D2       BNE   $1841
186F-   CE D4 A0    DEC   $A0D4
1872-   A2 D3       LDX   #$D3
1874-   D0 CF       BNE   $1845
1876-   D3          ???
1877-   20 A7 D4    JSR   $D4A7
187A-   C8          INY
187B-   C9 D3       CMP   #$D3
187D-   20 C9 D3    JSR   $D3C9
1880-   20 C1 20    JSR   $20C1
1883-   D3          ???
1884-   D4          ???
1885-   D2 C9       CMP   ($C9)
1887-   CE C7 A7    DEC   $A7C7
188A-   BB          ???
188B-   C1 D3       CMP   ($D3,X)
188D-   D4          ???
188E-   D2 20       CMP   ($20)
1890-   D2 C5       CMP   ($C5)
1892-   D4          ???
1893-   D5 D2       CMP   $D2,X
1895-   CE D3 BA    DEC   $BAD3
1898-   20 A2 8D    JSR   $8DA2
189B-   A0 D3       LDY   #$D3
189D-   D0 CF       BNE   $186E
189F-   D3          ???
18A0-   A0 A2       LDY   #$A2
18A2-   D4          ???
18A3-   C8          INY
18A4-   C9 D3       CMP   #$D3
18A6-   20 C9 D3    JSR   $D3C9
18A9-   20 C1 20    JSR   $20C1
18AC-   D3          ???
18AD-   D4          ???
18AE-   D2 C9       CMP   ($C9)
18B0-   CE C7 A2    DEC   $A2C7
18B3-   BB          ???
18B4-   C1 D3       CMP   ($D3,X)
18B6-   D4          ???
18B7-   D2 8D       CMP   ($8D)
18B9-   A0 D3       LDY   #$D3
18BB-   D4          ???
18BC-   C1 A0       CMP   ($A0,X)
18BE-   A4 B3       LDY   $B3
18C0-   B0 B0       BCS   $1872
18C2-   8D A0 CC    STA   $CCA0
18C5-   C4 C1       CPY   $C1
18C7-   A0 A3       LDY   #$A3
18C9-   B0 8D       BCS   $1858
18CB-   A0 D3       LDY   #$D3
18CD-   D4          ???
18CE-   C1 A0       CMP   ($A0,X)
18D0-   A4 B3       LDY   $B3
18D2-   B0 B1       BCS   $1885
18D4-   A0 BB       LDY   #$BB
18D6-   20 C3 CC    JSR   $CCC3
18D9-   C5 C1       CMP   $C1
18DB-   D2 20       CMP   ($20)
18DD-   C8          INY
18DE-   C9 20       CMP   #$20
18E0-   C2          ???
18E1-   D9 D4 C5    CMP   $C5D4,Y
18E4-   8D A0 D4    STA   $D4A0
18E7-   CF          ???
18E8-   D3          ???
18E9-   D4          ???
18EA-   D2 A0       CMP   ($A0)
18EC-   A4 B3       LDY   $B3
18EE-   B0 B0       BCS   $18A0
18F0-   8D A0 D3    STA   $D3A0
18F3-   D0 D2       BNE   $18C7
18F5-   CE A0 D2    DEC   $D2A0
18F8-   C5 D4       CMP   $D4
18FA-   D5 D2       CMP   $D2,X
18FC-   CE 8D A0    DEC   $A08D
18FF-   DF          ???
1900-   D0 D2       BNE   $18D4
1902-   CE D4 A0    DEC   $A0D4
1905-   A2 20       LDX   #$20
1907-   A2 AC       LDX   #$AC
1909-   B8          CLV
190A-   C4 B8       CPY   $B8
190C-   C4 B8       CPY   $B8
190E-   C4 8D       CPY   $8D
1910-   AA          TAX
1911-   8D A0 DF    STA   $DFA0
1914-   D0 D2       BNE   $18E8
1916-   CE D4 A0    DEC   $A0D4
1919-   A2 20       LDX   #$20
191B-   A2 AC       LDX   #$AC
191D-   B8          CLV
191E-   C4 B8       CPY   $B8
1920-   C4 B8       CPY   $B8
1922-   C4 8D       CPY   $8D
1924-   A0 DF       LDY   #$DF
1926-   D0 D2       BNE   $18FA
1928-   CE D4 A0    DEC   $A0D4
192B-   A2 D4       LDX   #$D4
192D-   C8          INY
192E-   C5 20       CMP   $20
1930-   D3          ???
1931-   C3          ???
1932-   D0 D9       BNE   $190D
1934-   20 CD C1    JSR   $C1CD
1937-   C3          ???
1938-   D2 CF       CMP   ($CF)
193A-   20 C3 CF    JSR   $CFC3
193D-   D0 C9       BNE   $1908
193F-   C5 D3       CMP   $D3
1941-   20 C1 20    JSR   $20C1
1944-   A2 AC       LDX   #$AC
1946-   B8          CLV
1947-   C4 8D       CPY   $8D
1949-   A0 DF       LDY   #$DF
194B-   D0 D2       BNE   $191F
194D-   CE D4 A0    DEC   $A0D4
1950-   A2 D3       LDX   #$D3
1952-   D5 C2       CMP   $C2,X
1954-   D3          ???
1955-   D4          ???
1956-   D2 C9       CMP   ($C9)
1958-   CE C7 20    DEC   $20C7
195B-   C6 D2       DEC   $D2
195D-   CF          ???
195E-   CD 20 C1    CMP   $C120
1961-   CE CF D4    DEC   $D4CF
1964-   C8          INY
1965-   C5 D2       CMP   $D2
1967-   20 D3 D4    JSR   $D4D3
196A-   D2 C9       CMP   ($C9)
196C-   CE C7 A2    DEC   $A2C7
196F-   AC B8 C4    LDY   $C4B8
1972-   8D A0 DF    STA   $DFA0
1975-   D0 D2       BNE   $1949
1977-   CE D4 A0    DEC   $A0D4
197A-   A2 C1       LDX   #$C1
197C-   D4          ???
197D-   20 D4 C8    JSR   $C8D4
1980-   C5 20       CMP   $20
1982-   D3          ???
1983-   D0 C5       BNE   $194A
1985-   C3          ???
1986-   C9 C6       CMP   #$C6
1988-   C9 C5       CMP   #$C5
198A-   C4 20       CPY   $20
198C-   C9 CE       CMP   #$CE
198E-   C4 C5       CPY   $C5
1990-   D8          CLD
1991-   AC 20 C8    LDY   $C820
1994-   CF          ???
1995-   CC C4 C9    CPY   $C9C4
1998-   CE C7 A2    DEC   $A2C7
199B-   AC B8 C4    LDY   $C4B8
199E-   8D A0 DF    STA   $DFA0
19A1-   D0 D2       BNE   $1975
19A3-   CE D4 A0    DEC   $A0D4
19A6-   A2 D4       LDX   #$D4
19A8-   C8          INY
19A9-   C5 20       CMP   $20
19AB-   D3          ???
19AC-   D5 C2       CMP   $C2,X
19AE-   D3          ???
19AF-   D4          ???
19B0-   D2 C9       CMP   ($C9)
19B2-   CE C7 20    DEC   $20C7
19B5-   C9 CE       CMP   #$CE
19B7-   20 DB D2    JSR   $D2DB
19BA-   C5 D4       CMP   $D4
19BC-   D5 D2       CMP   $D2,X
19BE-   CE DD AE    DEC   $AEDD
19C1-   A2 AC       LDX   #$AC
19C3-   B8          CLV
19C4-   C4 B8       CPY   $B8
19C6-   C4 8D       CPY   $8D
19C8-   A0 DF       LDY   #$DF
19CA-   D0 D2       BNE   $199E
19CC-   CE D4 A0    DEC   $A0D4
19CF-   A2 D3       LDX   #$D3
19D1-   C3          ???
19D2-   D0 D9       BNE   $19AD
19D4-   20 A7 C1    JSR   $C1A7
19D7-   C2          ???
19D8-   C3          ???
19D9-   C4 C5       CPY   $C5
19DB-   C6 C7       DEC   $C7
19DD-   C8          INY
19DE-   C9 CA       CMP   #$CA
19E0-   CB          ???
19E1-   A7          ???
19E2-   BB          ???
19E3-   A3          ???
19E4-   B2 BB       LDA   ($BB)
19E6-   A3          ???
19E7-   B4 BB       LDY   $BB,X
19E9-   A3          ???
19EA-   B5 B0       LDA   $B0,X
19EC-   20 D2 C5    JSR   $C5D2
19EF-   D4          ???
19F0-   D5 D2       CMP   $D2,X
19F2-   CE D3 BA    DEC   $BAD3
19F5-   20 A2 8D    JSR   $8DA2
19F8-   A0 D3       LDY   #$D3
19FA-   C3          ???
19FB-   D0 D9       BNE   $19D6
19FD-   A0 A2       LDY   #$A2
19FF-   C1 C2       CMP   ($C2,X)
1A01-   C3          ???
1A02-   C4 C5       CPY   $C5
1A04-   C6 C7       DEC   $C7
1A06-   C8          INY
1A07-   C9 CA       CMP   #$CA
1A09-   CB          ???
1A0A-   A2 BB       LDX   #$BB
1A0C-   A3          ???
1A0D-   B2 BB       LDA   ($BB)
1A0F-   A3          ???
1A10-   B4 BB       LDY   $BB,X
1A12-   A3          ???
1A13-   A4 C6       LDY   $C6
1A15-   C6 8D       DEC   $8D
1A17-   A0 D3       LDY   #$D3
1A19-   D0 D2       BNE   $19ED
1A1B-   CE A0 D2    DEC   $D2A0
1A1E-   C5 D4       CMP   $D4
1A20-   D5 D2       CMP   $D2,X
1A22-   CE 8D A0    DEC   $A08D
1A25-   DF          ???
1A26-   D0 D2       BNE   $19FA
1A28-   CE D4 A0    DEC   $A0D4
1A2B-   A2 20       LDX   #$20
1A2D-   A2 AC       LDX   #$AC
1A2F-   B8          CLV
1A30-   C4 B8       CPY   $B8
1A32-   C4 B8       CPY   $B8
1A34-   C4 8D       CPY   $8D
1A36-   A0 DF       LDY   #$DF
1A38-   D7          ???
1A39-   C1 C9       CMP   ($C9,X)
1A3B-   D4          ???
1A3C-   8D AA 8D    STA   $8DAA
1A3F-   A0 DF       LDY   #$DF
1A41-   D0 D2       BNE   $1A15
1A43-   CE D4 A0    DEC   $A0D4
1A46-   A2 20       LDX   #$20
1A48-   A2 AC       LDX   #$AC
1A4A-   B8          CLV
1A4B-   C4 B8       CPY   $B8
1A4D-   C4 B8       CPY   $B8
1A4F-   C4 B8       CPY   $B8
1A51-   C4 B8       CPY   $B8
1A53-   C4 8D       CPY   $8D
1A55-   A0 DF       LDY   #$DF
1A57-   D0 D2       BNE   $1A2B
1A59-   CE D4 A0    DEC   $A0D4
1A5C-   A2 D4       LDX   #$D4
1A5E-   C8          INY
1A5F-   C5 20       CMP   $20
1A61-   D3          ???
1A62-   C4 C5       CPY   $C5
1A64-   CC 20 CD    CPY   $CD20
1A67-   C1 C3       CMP   ($C3,X)
1A69-   D2 CF       CMP   ($CF)
1A6B-   20 C4 C5    JSR   $C5C4
1A6E-   CC C5 D4    CPY   $D4C5
1A71-   C5 D3       CMP   $D3
1A73-   20 C1 20    JSR   $20C1
1A76-   D3          ???
1A77-   D5 C2       CMP   $C2,X
1A79-   D3          ???
1A7A-   D4          ???
1A7B-   D2 C9       CMP   ($C9)
1A7D-   CE C7 A2    DEC   $A2C7
1A80-   AC B8 C4    LDY   $C4B8
1A83-   8D A0 DF    STA   $DFA0
1A86-   D0 D2       BNE   $1A5A
1A88-   CE D4 A0    DEC   $A0D4
1A8B-   A2 C6       LDX   #$C6
1A8D-   D2 CF       CMP   ($CF)
1A8F-   CD 20 D4    CMP   $D420
1A92-   C8          INY
1A93-   C5 20       CMP   $20
1A95-   C7          ???
1A96-   C9 D6       CMP   #$D6
1A98-   C5 CE       CMP   $CE
1A9A-   20 D3 CF    JSR   $CFD3
1A9D-   D5 D2       CMP   $D2,X
1A9F-   C3          ???
1AA0-   C5 20       CMP   $20
1AA2-   D3          ???
1AA3-   D4          ???
1AA4-   D2 C9       CMP   ($C9)
1AA6-   CE C7 AE    DEC   $AEC7
1AA9-   20 CE CF    JSR   $CFCE
1AAC-   D4          ???
1AAD-   C5 20       CMP   $20
1AAF-   A2 AC       LDX   #$AC
1AB1-   B8          CLV
1AB2-   C4 8D       CPY   $8D
1AB4-   A0 DF       LDY   #$DF
1AB6-   D0 D2       BNE   $1A8A
1AB8-   CE D4 A0    DEC   $A0D4
1ABB-   A2 D4       LDX   #$D4
1ABD-   C8          INY
1ABE-   C1 D4       CMP   ($D4,X)
1AC0-   20 D4 C8    JSR   $C8D4
1AC3-   C5 20       CMP   $20
1AC5-   D3          ???
1AC6-   CF          ???
1AC7-   D5 D2       CMP   $D2,X
1AC9-   C3          ???
1ACA-   C5 20       CMP   $20
1ACC-   D3          ???
1ACD-   D4          ???
1ACE-   D2 C9       CMP   ($C9)
1AD0-   CE C7 20    DEC   $20C7
1AD3-   CD D5 D3    CMP   $D3D5
1AD6-   D4          ???
1AD7-   20 CE CF    JSR   $CFCE
1ADA-   D4          ???
1ADB-   A2 AC       LDX   #$AC
1ADD-   B8          CLV
1ADE-   C4 8D       CPY   $8D
1AE0-   A0 DF       LDY   #$DF
1AE2-   D0 D2       BNE   $1AB6
1AE4-   CE D4 A0    DEC   $A0D4
1AE7-   A2 C2       LDX   #$C2
1AE9-   C5 20       CMP   $20
1AEB-   C1 20       CMP   ($20,X)
1AED-   CC C9 D4    CPY   $D4C9
1AF0-   C5 D2       CMP   $D2
1AF2-   C1 CC       CMP   ($CC,X)
1AF4-   20 C2 C5    JSR   $C5C2
1AF7-   C3          ???
1AF8-   C1 D5       CMP   ($D5,X)
1AFA-   D3          ???
1AFB-   C5 20       CMP   $20
1AFD-   D4          ???
1AFE-   C8          INY
1AFF-   C9 D3       CMP   #$D3
1B01-   20 D2 CF    JSR   $CFD2
1B04-   D5 D4       CMP   $D4,X
1B06-   C9 CE       CMP   #$CE
1B08-   C5 A2       CMP   $A2
1B0A-   AC B8 C4    LDY   $C4B8
1B0D-   8D A0 DF    STA   $DFA0
1B10-   D0 D2       BNE   $1AE4
1B12-   CE D4 A0    DEC   $A0D4
1B15-   A2 C1       LDX   #$C1
1B17-   CC D4 C5    CPY   $C5D4
1B1A-   D2 D3       CMP   ($D3)
1B1C-   20 D4 C8    JSR   $C8D4
1B1F-   C5 20       CMP   $20
1B21-   D3          ???
1B22-   D4          ???
1B23-   D2 C9       CMP   ($C9)
1B25-   CE C7 20    DEC   $20C7
1B28-   D0 C1       BNE   $1AEB
1B2A-   D3          ???
1B2B-   D3          ???
1B2C-   C5 C4       CMP   $C4
1B2E-   20 D4 CF    JSR   $CFD4
1B31-   20 C9 D4    JSR   $D4C9
1B34-   AE A2 AC    LDX   $ACA2
1B37-   B8          CLV
1B38-   C4 B8       CPY   $B8
1B3A-   C4 8D       CPY   $8D
1B3C-   A0 DF       LDY   #$DF
1B3E-   D0 D2       BNE   $1B12
1B40-   CE D4 A0    DEC   $A0D4
1B43-   A2 C9       LDX   #$C9
1B45-   C6 20       DEC   $20
1B47-   CC D3 D4    CPY   $D4D3
1B4A-   D2 20       CMP   ($20)
1B4C-   C8          INY
1B4D-   CF          ???
1B4E-   CC C4 D3    CPY   $D3C4
1B51-   20 A7 D4    JSR   $D4A7
1B54-   C8          INY
1B55-   C9 D3       CMP   #$D3
1B57-   20 C9 D3    JSR   $D3C9
1B5A-   20 C1 20    JSR   $20C1
1B5D-   D3          ???
1B5E-   D4          ???
1B5F-   D2 C9       CMP   ($C9)
1B61-   CE C7 AE    DEC   $AEC7
1B64-   A7          ???
1B65-   A2 AC       LDX   #$AC
1B67-   B8          CLV
1B68-   C4 8D       CPY   $8D
1B6A-   A0 DF       LDY   #$DF
1B6C-   D0 D2       BNE   $1B40
1B6E-   CE D4 A0    DEC   $A0D4
1B71-   A2 D4       LDX   #$D4
1B73-   C8          INY
1B74-   C5 CE       CMP   $CE
1B76-   20 D3 C4    JSR   $C4D3
1B79-   C5 CC       CMP   $CC
1B7B-   20 CC D3    JSR   $D3CC
1B7E-   D4          ???
1B7F-   D2 BB       CMP   ($BB)
1B81-   A3          ???
1B82-   B1 BB       LDA   ($BB),Y
1B84-   A3          ???
1B85-   B7          ???
1B86-   20 D2 C5    JSR   $C5D2
1B89-   D4          ???
1B8A-   D5 D2       CMP   $D2,X
1B8C-   CE D3 BA    DEC   $BAD3
1B8F-   20 A2 AC    JSR   $ACA2
1B92-   B8          CLV
1B93-   C4 B8       CPY   $B8
1B95-   C4 8D       CPY   $8D
1B97-   A0 D3       LDY   #$D3
1B99-   C4 C5       CPY   $C5
1B9B-   CC A0 CC    CPY   $CCA0
1B9E-   D3          ???
1B9F-   D4          ???
1BA0-   D2 BB       CMP   ($BB)
1BA2-   A3          ???
1BA3-   B1 BB       LDA   ($BB),Y
1BA5-   A3          ???
1BA6-   B7          ???
1BA7-   8D A0 D3    STA   $D3A0
1BAA-   D0 D2       BNE   $1B7E
1BAC-   CE A0 CC    DEC   $CCA0
1BAF-   D3          ???
1BB0-   D4          ???
1BB1-   D2 8D       CMP   ($8D)
1BB3-   A0 DF       LDY   #$DF
1BB5-   D0 D2       BNE   $1B89
1BB7-   CE D4 A0    DEC   $A0D4
1BBA-   A2 20       LDX   #$20
1BBC-   A2 AC       LDX   #$AC
1BBE-   B8          CLV
1BBF-   C4 B8       CPY   $B8
1BC1-   C4 B8       CPY   $B8
1BC3-   C4 B8       CPY   $B8
1BC5-   C4 8D       CPY   $8D
1BC7-   A0 DF       LDY   #$DF
1BC9-   D7          ???
1BCA-   C1 C9       CMP   ($C9,X)
1BCC-   D4          ???
1BCD-   8D AA 8D    STA   $8DAA
1BD0-   A0 DF       LDY   #$DF
1BD2-   D0 D2       BNE   $1BA6
1BD4-   CE D4 A0    DEC   $A0D4
1BD7-   A2 D4       LDX   #$D4
1BD9-   C8          INY
1BDA-   C5 20       CMP   $20
1BDC-   D3          ???
1BDD-   C9 CE       CMP   #$CE
1BDF-   D3          ???
1BE0-   20 CD C1    JSR   $C1CD
1BE3-   C3          ???
1BE4-   D2 CF       CMP   ($CF)
1BE6-   20 C4 CF    JSR   $CFC4
1BE9-   C5 D3       CMP   $D3
1BEB-   20 D4 C8    JSR   $C8D4
1BEE-   C5 20       CMP   $20
1BF0-   A2 AC       LDX   #$AC
1BF2-   B8          CLV
1BF3-   C4 8D       CPY   $8D
1BF5-   A0 DF       LDY   #$DF
1BF7-   D0 D2       BNE   $1BCB
1BF9-   CE D4 A0    DEC   $A0D4
1BFC-   A2 CF       LDX   #$CF
1BFE-   D0 D0       BNE   $1BD0
1C00-   CF          ???
1C01-   D3          ???
1C02-   C9 D4       CMP   #$D4
1C04-   C5 20       CMP   $20
1C06-   CF          ???
1C07-   C6 20       DEC   $20
1C09-   D3          ???
1C0A-   C4 C5       CPY   $C5
1C0C-   CC BA 20    CPY   $20BA
1C0F-   C9 D4       CMP   #$D4
1C11-   20 C9 CE    JSR   $CEC9
1C14-   D3          ???
1C15-   C5 D2       CMP   $D2
1C17-   D4          ???
1C18-   D3          ???
1C19-   A2 AC       LDX   #$AC
1C1B-   B8          CLV
1C1C-   C4 8D       CPY   $8D
1C1E-   A0 DF       LDY   #$DF
1C20-   D0 D2       BNE   $1BF4
1C22-   CE D4 A0    DEC   $A0D4
1C25-   A2 C1       LDX   #$C1
1C27-   20 D3 D5    JSR   $D5D3
1C2A-   C2          ???
1C2B-   D3          ???
1C2C-   D4          ???
1C2D-   D2 C9       CMP   ($C9)
1C2F-   CE C7 20    DEC   $20C7
1C32-   C9 CE       CMP   #$CE
1C34-   D4          ???
1C35-   CF          ???
1C36-   20 C1 20    JSR   $20C1
1C39-   D0 C1       BNE   $1BFC
1C3B-   D2 C5       CMP   ($C5)
1C3D-   CE D4 20    DEC   $20D4
1C40-   D3          ???
1C41-   D4          ???
1C42-   D2 C9       CMP   ($C9)
1C44-   CE C7 A2    DEC   $A2C7
1C47-   AC B8 C4    LDY   $C4B8
1C4A-   8D A0 DF    STA   $DFA0
1C4D-   D0 D2       BNE   $1C21
1C4F-   CE D4 A0    DEC   $A0D4
1C52-   A2 C1       LDX   #$C1
1C54-   D4          ???
1C55-   20 D4 C8    JSR   $C8D4
1C58-   C5 20       CMP   $20
1C5A-   C7          ???
1C5B-   C9 D6       CMP   #$D6
1C5D-   C5 CE       CMP   $CE
1C5F-   20 C9 CE    JSR   $CEC9
1C62-   C4 C5       CPY   $C5
1C64-   D8          CLD
1C65-   AE 20 CE    LDX   $CE20
1C68-   CF          ???
1C69-   D4          ???
1C6A-   C5 20       CMP   $20
1C6C-   D4          ???
1C6D-   C8          INY
1C6E-   C1 D4       CMP   ($D4,X)
1C70-   A2 AC       LDX   #$AC
1C72-   B8          CLV
1C73-   C4 8D       CPY   $8D
1C75-   A0 DF       LDY   #$DF
1C77-   D0 D2       BNE   $1C4B
1C79-   CE D4 A0    DEC   $A0D4
1C7C-   A2 D7       LDX   #$D7
1C7E-   C8          INY
1C7F-   C9 CC       CMP   #$CC
1C81-   C5 20       CMP   $20
1C83-   D4          ???
1C84-   C8          INY
1C85-   C5 20       CMP   $20
1C87-   D0 C1       BNE   $1C4A
1C89-   D2 C5       CMP   ($C5)
1C8B-   CE D4 20    DEC   $20D4
1C8E-   D3          ???
1C8F-   D4          ???
1C90-   D2 C9       CMP   ($C9)
1C92-   CE C7 20    DEC   $20C7
1C95-   C3          ???
1C96-   C1 CE       CMP   ($CE,X)
1C98-   CE CF D4    DEC   $D4CF
1C9B-   20 C2 C5    JSR   $C5C2
1C9E-   20 A2 AC    JSR   $ACA2
1CA1-   B8          CLV
1CA2-   C4 8D       CPY   $8D
1CA4-   A0 DF       LDY   #$DF
1CA6-   D0 D2       BNE   $1C7A
1CA8-   CE D4 A0    DEC   $A0D4
1CAB-   A2 C1       LDX   #$C1
1CAD-   20 CC C9    JSR   $C9CC
1CB0-   D4          ???
1CB1-   C5 D2       CMP   $D2
1CB3-   C1 CC       CMP   ($CC,X)
1CB5-   AC 20 D4    LDY   $D420
1CB8-   C8          INY
1CB9-   C5 20       CMP   $20
1CBB-   D3          ???
1CBC-   D5 C2       CMP   $C2,X
1CBE-   D3          ???
1CBF-   D4          ???
1CC0-   D2 C9       CMP   ($C9)
1CC2-   CE C7 20    DEC   $20C7
1CC5-   C9 D4       CMP   #$D4
1CC7-   D3          ???
1CC8-   C5 CC       CMP   $CC
1CCA-   C6 20       DEC   $20
1CCC-   C3          ???
1CCD-   C1 CE       CMP   ($CE,X)
1CCF-   20 C2 C5    JSR   $C5C2
1CD2-   AE A2 AC    LDX   $ACA2
1CD5-   B8          CLV
1CD6-   C4 B8       CPY   $B8
1CD8-   C4 8D       CPY   $8D
1CDA-   A0 DF       LDY   #$DF
1CDC-   D0 D2       BNE   $1CB0
1CDE-   CE D4 A0    DEC   $A0D4
1CE1-   A2 D4       LDX   #$D4
1CE3-   C8          INY
1CE4-   D5 D3       CMP   $D3,X
1CE6-   20 D3 C9    JSR   $C9D3
1CE9-   CE D3 20    DEC   $20D3
1CEC-   CC D3 D4    CPY   $D4D3
1CEF-   D2 BB       CMP   ($BB)
1CF1-   A3          ???
1CF2-   B1 BB       LDA   ($BB),Y
1CF4-   A3          ???
1CF5-   B5 B0       LDA   $B0,X
1CF7-   BB          ???
1CF8-   A7          ???
1CF9-   D4          ???
1CFA-   C8          INY
1CFB-   C9 D3       CMP   #$D3
1CFD-   20 C9 D3    JSR   $D3C9
1D00-   20 CE CF    JSR   $CFCE
1D03-   D4          ???
1D04-   A7          ???
1D05-   A2 AC       LDX   #$AC
1D07-   B8          CLV
1D08-   C4 8D       CPY   $8D
1D0A-   A0 DF       LDY   #$DF
1D0C-   D0 D2       BNE   $1CE0
1D0E-   CE D4 A0    DEC   $A0D4
1D11-   A2 D2       LDX   #$D2
1D13-   C5 D4       CMP   $D4
1D15-   D5 D2       CMP   $D2,X
1D17-   CE D3 BA    DEC   $BAD3
1D1A-   20 A2 AC    JSR   $ACA2
1D1D-   B8          CLV
1D1E-   C4 8D       CPY   $8D
1D20-   A0 D3       LDY   #$D3
1D22-   C9 CE       CMP   #$CE
1D24-   D3          ???
1D25-   A0 CC       LDY   #$CC
1D27-   D3          ???
1D28-   D4          ???
1D29-   D2 BB       CMP   ($BB)
1D2B-   A3          ???
1D2C-   B1 BB       LDA   ($BB),Y
1D2E-   A3          ???
1D2F-   B5 B0       LDA   $B0,X
1D31-   BB          ???
1D32-   A2 D4       LDX   #$D4
1D34-   C8          INY
1D35-   C9 D3       CMP   #$D3
1D37-   A0 C9       LDY   #$C9
1D39-   D3          ???
1D3A-   A0 CE       LDY   #$CE
1D3C-   CF          ???
1D3D-   D4          ???
1D3E-   A2 8D       LDX   #$8D
1D40-   A0 D3       LDY   #$D3
1D42-   D0 D2       BNE   $1D16
1D44-   CE A0 CC    DEC   $CCA0
1D47-   D3          ???
1D48-   D4          ???
1D49-   D2 8D       CMP   ($8D)
1D4B-   A0 DF       LDY   #$DF
1D4D-   D0 D2       BNE   $1D21
1D4F-   CE D4 A0    DEC   $A0D4
1D52-   A2 20       LDX   #$20
1D54-   A2 AC       LDX   #$AC
1D56-   B8          CLV
1D57-   C4 B8       CPY   $B8
1D59-   C4 B8       CPY   $B8
1D5B-   C4 B8       CPY   $B8
1D5D-   C4 8D       CPY   $8D
1D5F-   A0 DF       LDY   #$DF
1D61-   D7          ???
1D62-   C1 C9       CMP   ($C9,X)
1D64-   D4          ???
1D65-   8D 8D AA    STA   $AA8D
1D68-   8D A0 CA    STA   $CAA0
1D6B-   CD D0 A0    CMP   $A0D0
1D6E-   D2 C5       CMP   ($C5)
1D70-   C5 CE       CMP   $CE
1D72-   D4          ???
1D73-   D2 D9       CMP   ($D9)
1D75-   8D AA 8D    STA   $8DAA
1D78-   C1 D3       CMP   ($D3,X)
1D7A-   D4          ???
1D7B-   D2 A0       CMP   ($A0)
1D7D-   D3          ???
1D7E-   D4          ???
1D7F-   D2 A0       CMP   ($A0)
1D81-   A2 C1       LDX   #$C1
1D83-   A2 8D       LDX   #$8D
1D85-   C2          ???
1D86-   D3          ???
1D87-   D4          ???
1D88-   D2 A0       CMP   ($A0)
1D8A-   D3          ???
1D8B-   D4          ???
1D8C-   D2 A0       CMP   ($A0)
1D8E-   A2 C2       LDX   #$C2
1D90-   A2 8D       LDX   #$8D
1D92-   CC D3 D4    CPY   $D4D3
1D95-   D2 A0       CMP   ($A0)
1D97-   D3          ???
1D98-   D4          ???
1D99-   D2 A0       CMP   ($A0)
1D9B-   A2 D4       LDX   #$D4
1D9D-   C8          INY
1D9E-   C9 D3       CMP   #$D3
1DA0-   20 C9 D3    JSR   $D3C9
1DA3-   20 C1 20    JSR   $20C1
1DA6-   D3          ???
1DA7-   D4          ???
1DA8-   D2 C9       CMP   ($C9)
1DAA-   CE C7 AE    DEC   $AEC7
1DAD-   A2 8D       LDX   #$8D
1DAF-   AA          TAX
1DB0-   8D AA E0    STA   $E0AA
1DB3-   E0 E0       CPX   #$E0
1DB5-   E0 E0       CPX   #$E0
1DB7-   E0 E0       CPX   #$E0
1DB9-   E0 E0       CPX   #$E0
1DBB-   E0 E0       CPX   #$E0
1DBD-   E0 E0       CPX   #$E0
1DBF-   E0 E0       CPX   #$E0
1DC1-   E0 E0       CPX   #$E0
1DC3-   E0 E0       CPX   #$E0
1DC5-   E0 E0       CPX   #$E0
1DC7-   E0 E0       CPX   #$E0
1DC9-   E0 E0       CPX   #$E0
1DCB-   E0 E0       CPX   #$E0
1DCD-   E0 E0       CPX   #$E0
1DCF-   E0 AA       CPX   #$AA
1DD1-   8D AA 20    STA   $20AA
1DD4-   20 20 20    JSR   $2020
1DD7-   20 20 20    JSR   $2020
1DDA-   20 C2 CF    JSR   $CFC2
1DDD-   D4          ???
1DDE-   D4          ???
1DDF-   CF          ???
1DE0-   CD 20 C9    CMP   $C920
1DE3-   CE C3 CC    DEC   $CCC3
1DE6-   D5 C4       CMP   $C4,X
1DE8-   C5 D3       CMP   $D3
1DEA-   20 20 20    JSR   $2020
1DED-   20 20 20    JSR   $2020
1DF0-   20 AA 8D    JSR   $8DAA
1DF3-   AA          TAX
1DF4-   AC AC AC    LDY   $ACAC
1DF7-   AC AC AC    LDY   $ACAC
1DFA-   AC AC AC    LDY   $ACAC
1DFD-   AC AC AC    LDY   $ACAC
1E00-   AC AC AC    LDY   $ACAC
1E03-   AC AC AC    LDY   $ACAC
1E06-   AC AC AC    LDY   $ACAC
1E09-   AC AC AC    LDY   $ACAC
1E0C-   AC AC AC    LDY   $ACAC
1E0F-   AC AC AC    LDY   $ACAC
1E12-   AA          TAX
1E13-   8D AA 8D    STA   $8DAA
1E16-   AA          TAX
1E17-   AA          TAX
1E18-   20 C2 CF    JSR   $CFC2
1E1B-   D4          ???
1E1C-   D4          ???
1E1D-   CF          ???
1E1E-   CD 20 C9    CMP   $C920
1E21-   CE C3 CC    DEC   $CCC3
1E24-   D5 C4       CMP   $C4,X
1E26-   C5 D3       CMP   $D3
1E28-   8D AA 8D    STA   $8DAA
1E2B-   A0 D0       LDY   #$D0
1E2D-   D5 D4       CMP   $D4,X
1E2F-   A0 D2       LDY   #$D2
1E31-   C5 D1       CMP   $D1
1E33-   D5 C9       CMP   $C9,X
1E35-   D2 C5       CMP   ($C5)
1E37-   C4 AE       CPY   $AE
1E39-   CC C9 C2    CPY   $C2C9
1E3C-   AE CD C9    LDX   $C9CD
1E3F-   CE 8D AA    DEC   $AA8D
1E42-   8D AA AA    STA   $AAAA
1E45-   20 C9 CE    JSR   $CEC9
1E48-   C4 C9       CPY   $C9
1E4A-   D6 C9       DEC   $C9,X
1E4C-   C4 D5       CPY   $D5
1E4E-   C1 CC       CMP   ($CC,X)
1E50-   20 D3 D5    JSR   $D5D3
1E53-   C2          ???
1E54-   D2 CF       CMP   ($CF)
1E56-   D5 D4       CMP   $D4,X
1E58-   C9 CE       CMP   #$CE
1E5A-   C5 20       CMP   $20
1E5C-   C9 CE       CMP   #$CE
1E5E-   C3          ???
1E5F-   CC D5 C4    CPY   $C4D5
1E62-   C5 D3       CMP   $D3
1E64-   8D AA 8D    STA   $8DAA
1E67-   AA          TAX
1E68-   AA          TAX
1E69-   20 D3 D4    JSR   $D4D3
1E6C-   D2 C9       CMP   ($C9)
1E6E-   CE C7 20    DEC   $20C7
1E71-   D3          ???
1E72-   D5 C2       CMP   $C2,X
1E74-   D2 CF       CMP   ($CF)
1E76-   D5 D4       CMP   $D4,X
1E78-   C9 CE       CMP   #$CE
1E7A-   C5 D3       CMP   $D3
1E7C-   8D AA 8D    STA   $8DAA
1E7F-   A0 D0       LDY   #$D0
1E81-   D5 D4       CMP   $D4,X
1E83-   A0 CE       LDY   #$CE
1E85-   D5 CD       CMP   $CD,X
1E87-   B2 D3       LDA   ($D3)
1E89-   D4          ???
1E8A-   D2 AE       CMP   ($AE)
1E8C-   D3          ???
1E8D-   D5 C2       CMP   $C2,X
1E8F-   AE CD C9    LDX   $C9CD
1E92-   CE 8D A0    DEC   $A08D
1E95-   D0 D5       BNE   $1E6C
1E97-   D4          ???
1E98-   A0 D0       LDY   #$D0
1E9A-   D2 CE       CMP   ($CE)
1E9C-   D3          ???
1E9D-   D4          ???
1E9E-   D2 AE       CMP   ($AE)
1EA0-   D3          ???
1EA1-   D5 C2       CMP   $C2,X
1EA3-   AE CD C9    LDX   $C9CD
1EA6-   CE 8D A0    DEC   $A08D
1EA9-   D0 D5       BNE   $1E80
1EAB-   D4          ???
1EAC-   A0 D3       LDY   #$D3
1EAE-   D4          ???
1EAF-   D2 C3       CMP   ($C3)
1EB1-   C1 D4       CMP   ($D4,X)
1EB3-   AE D3 D5    LDX   $D5D3
1EB6-   C2          ???
1EB7-   AE CD C9    LDX   $C9CD
1EBA-   CE 8D A0    DEC   $A08D
1EBD-   D0 D5       BNE   $1E94
1EBF-   D4          ???
1EC0-   A0 D3       LDY   #$D3
1EC2-   D4          ???
1EC3-   D2 C3       CMP   ($C3)
1EC5-   CF          ???
1EC6-   CD D0 AE    CMP   $AED0
1EC9-   D3          ???
1ECA-   D5 C2       CMP   $C2,X
1ECC-   AE CD C9    LDX   $C9CD
1ECF-   CE 8D A0    DEC   $A08D
1ED2-   D0 D5       BNE   $1EA9
1ED4-   D4          ???
1ED5-   A0 D3       LDY   #$D3
1ED7-   D4          ???
1ED8-   D2 B2       CMP   ($B2)
1EDA-   CE D5 CD    DEC   $CDD5
1EDD-   AE D3 D5    LDX   $D5D3
1EE0-   C2          ???
1EE1-   AE CD C9    LDX   $C9CD
1EE4-   CE 8D AA    DEC   $AA8D
1EE7-   8D AA AA    STA   $AAAA
1EEA-   20 D3 D5    JSR   $D5D3
1EED-   C2          ???
1EEE-   D3          ???
1EEF-   D4          ???
1EF0-   D2 C9       CMP   ($C9)
1EF2-   CE C7 20    DEC   $20C7
1EF5-   D3          ???
1EF6-   D5 C2       CMP   $C2,X
1EF8-   D2 CF       CMP   ($CF)
1EFA-   D5 D4       CMP   $D4,X
1EFC-   C9 CE       CMP   #$CE
1EFE-   C5 D3       CMP   $D3
1F00-   8D AA 8D    STA   $8DAA
1F03-   A0 D0       LDY   #$D0
1F05-   D5 D4       CMP   $D4,X
1F07-   A0 D3       LDY   #$D3
1F09-   D5 C2       CMP   $C2,X
1F0B-   C3          ???
1F0C-   CF          ???
1F0D-   D0 D9       BNE   $1EE8
1F0F-   AE D3 D5    LDX   $D5D3
1F12-   C2          ???
1F13-   AE CD C9    LDX   $C9CD
1F16-   CE 8D A0    DEC   $A08D
1F19-   D0 D5       BNE   $1EF0
1F1B-   D4          ???
1F1C-   A0 D3       LDY   #$D3
1F1E-   D5 C2       CMP   $C2,X
1F20-   C4 C5       CPY   $C5
1F22-   CC AE D3    CPY   $D3AE
1F25-   D5 C2       CMP   $C2,X
1F27-   AE CD C9    LDX   $C9CD
1F2A-   CE 8D A0    DEC   $A08D
1F2D-   D0 D5       BNE   $1F04
1F2F-   D4          ???
1F30-   A0 D3       LDY   #$D3
1F32-   D5 C2       CMP   $C2,X
1F34-   C9 CE       CMP   #$CE
1F36-   D3          ???
1F37-   AE D3 D5    LDX   $D5D3
1F3A-   C2          ???
1F3B-   AE CD C9    LDX   $C9CD
1F3E-   CE 8D A0    DEC   $A08D
1F41-   D0 D5       BNE   $1F18
1F43-   D4          ???
1F44-   A0 D3       LDY   #$D3
1F46-   D5 C2       CMP   $C2,X
1F48-   D0 CF       BNE   $1F19
1F4A-   D3          ???
1F4B-   AE D3 D5    LDX   $D5D3
1F4E-   C2          ???
1F4F-   AE CD C9    LDX   $C9CD
1F52-   CE 8D AA    DEC   $AA8D
1F55-   8D 00 00    STA   $0000
