0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 D3    LDY   $D320,X
0950-   D4          ???
0951-   D2 C9       CMP   ($C9)
0953-   CE C7 D3    DEC   $D3C7
0956-   20 C4 C5    JSR   $C5C4
0959-   CD CF 20    CMP   $20CF
095C-   BE AD 20    LDX   $20AD,Y
095F-   20 20 20    JSR   $2020
0962-   20 20 AA    JSR   $AA20
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B2    JSR   $B220
09D4-   B0 AD       BCS   $0983
09D6-   CA          DEX
09D7-   C1 CE       CMP   ($CE,X)
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B9       LDA   ($B9),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 D4       LDY   #$D4
0AF8-   D2 A0       CMP   ($A0)
0AFA-   CF          ???
0AFB-   CE 8D A0    DEC   $A08D
0AFE-   C5 D8       CMP   $D8
0B00-   D0 A0       BNE   $0AA2
0B02-   CF          ???
0B03-   CE CC D9    DEC   $D9CC
0B06-   8D A0 C4    STA   $C4A0
0B09-   D3          ???
0B0A-   CB          ???
0B0B-   A0 D3       LDY   #$D3
0B0D-   D4          ???
0B0E-   D2 C9       CMP   ($C9)
0B10-   CE C7 D3    DEC   $D3C7
0B13-   AE C4 C5    LDX   $C5C4
0B16-   CD CF 8D    CMP   $8DCF
0B19-   A0 CF       LDY   #$CF
0B1B-   C2          ???
0B1C-   CA          DEX
0B1D-   A0 A4       LDY   #$A4
0B1F-   C2          ???
0B20-   C6 C5       DEC   $C5
0B22-   B0 8D       BCS   $0AB1
0B24-   A0 CF       LDY   #$CF
0B26-   D2 C7       CMP   ($C7)
0B28-   A0 A4       LDY   #$A4
0B2A-   B6 B0       LDX   $B0,Y
0B2C-   B0 B0       BCS   $0ADE
0B2E-   8D AA 8D    STA   $8DAA
0B31-   AA          TAX
0B32-   E0 E0       CPX   #$E0
0B34-   E0 E0       CPX   #$E0
0B36-   E0 E0       CPX   #$E0
0B38-   E0 E0       CPX   #$E0
0B3A-   E0 E0       CPX   #$E0
0B3C-   E0 E0       CPX   #$E0
0B3E-   E0 E0       CPX   #$E0
0B40-   E0 E0       CPX   #$E0
0B42-   E0 E0       CPX   #$E0
0B44-   E0 E0       CPX   #$E0
0B46-   E0 E0       CPX   #$E0
0B48-   E0 E0       CPX   #$E0
0B4A-   E0 E0       CPX   #$E0
0B4C-   E0 E0       CPX   #$E0
0B4E-   E0 E0       CPX   #$E0
0B50-   AA          TAX
0B51-   8D AA 20    STA   $20AA
0B54-   20 D4 CF    JSR   $CFD4
0B57-   D0 20       BNE   $0B79
0B59-   C9 CE       CMP   #$CE
0B5B-   C3          ???
0B5C-   CC D5 C4    CPY   $C4D5
0B5F-   C5 D3       CMP   $D3
0B61-   20 A8 D0    JSR   $D0A8
0B64-   D5 D4       CMP   $D4,X
0B66-   D3          ???
0B67-   AC 20 CD    LDY   $CD20
0B6A-   C1 C3       CMP   ($C3,X)
0B6C-   D2 CF       CMP   ($CF)
0B6E-   D3          ???
0B6F-   A9 20       LDA   #$20
0B71-   AA          TAX
0B72-   8D AA AC    STA   $ACAA
0B75-   AC AC AC    LDY   $ACAC
0B78-   AC AC AC    LDY   $ACAC
0B7B-   AC AC AC    LDY   $ACAC
0B7E-   AC AC AC    LDY   $ACAC
0B81-   AC AC AC    LDY   $ACAC
0B84-   AC AC AC    LDY   $ACAC
0B87-   AC AC AC    LDY   $ACAC
0B8A-   AC AC AC    LDY   $ACAC
0B8D-   AC AC AC    LDY   $ACAC
0B90-   AC AC AA    LDY   $AAAC
0B93-   8D AA 8D    STA   $8DAA
0B96-   A0 D0       LDY   #$D0
0B98-   D5 D4       CMP   $D4,X
0B9A-   A0 CD       LDY   #$CD
0B9C-   C9 CE       CMP   #$CE
0B9E-   AE D6 C1    LDX   $C1D6
0BA1-   D2 D3       CMP   ($D3)
0BA3-   AE D2 C5    LDX   $C5D2
0BA6-   D1 D5       CMP   ($D5),Y
0BA8-   C9 D2       CMP   #$D2
0BAA-   C5 C4       CMP   $C4
0BAC-   8D A0 D5    STA   $D5A0
0BAF-   D3          ???
0BB0-   C5 A0       CMP   $A0
0BB2-   CD C9 CE    CMP   $CEC9
0BB5-   AE CD C1    LDX   $C1CD
0BB8-   C3          ???
0BB9-   AE D2 C5    LDX   $C5D2
0BBC-   D1 D5       CMP   ($D5),Y
0BBE-   C9 D2       CMP   #$D2
0BC0-   C5 C4       CMP   $C4
0BC2-   8D A0 D0    STA   $D0A0
0BC5-   D5 D4       CMP   $D4,X
0BC7-   A0 CD       LDY   #$CD
0BC9-   C9 CE       CMP   #$CE
0BCB-   AE C8 CF    LDX   $CFC8
0BCE-   CF          ???
0BCF-   CB          ???
0BD0-   D3          ???
0BD1-   AE D2 C5    LDX   $C5D2
0BD4-   D1 D5       CMP   ($D5),Y
0BD6-   C9 D2       CMP   #$D2
0BD8-   C5 C4       CMP   $C4
0BDA-   8D A0 D5    STA   $D5A0
0BDD-   D3          ???
0BDE-   C5 A0       CMP   $A0
0BE0-   CD C9 CE    CMP   $CEC9
0BE3-   AE CD C1    LDX   $C1CD
0BE6-   C3          ???
0BE7-   AE D3 D4    LDX   $D4D3
0BEA-   D2 C9       CMP   ($C9)
0BEC-   CE C7 D3    DEC   $D3C7
0BEF-   8D A0 D0    STA   $D0A0
0BF2-   D5 D4       CMP   $D4,X
0BF4-   A0 CD       LDY   #$CD
0BF6-   C9 CE       CMP   #$CE
0BF8-   AE C8 CF    LDX   $CFC8
0BFB-   CF          ???
0BFC-   CB          ???
0BFD-   D3          ???
0BFE-   AE D3 D4    LDX   $D4D3
0C01-   D2 C9       CMP   ($C9)
0C03-   CE C7 D3    DEC   $D3C7
0C06-   8D AA 8D    STA   $8DAA
0C09-   AA          TAX
0C0A-   E0 E0       CPX   #$E0
0C0C-   E0 E0       CPX   #$E0
0C0E-   E0 E0       CPX   #$E0
0C10-   E0 E0       CPX   #$E0
0C12-   E0 E0       CPX   #$E0
0C14-   E0 E0       CPX   #$E0
0C16-   E0 E0       CPX   #$E0
0C18-   E0 E0       CPX   #$E0
0C1A-   E0 E0       CPX   #$E0
0C1C-   E0 E0       CPX   #$E0
0C1E-   E0 E0       CPX   #$E0
0C20-   E0 E0       CPX   #$E0
0C22-   E0 E0       CPX   #$E0
0C24-   E0 E0       CPX   #$E0
0C26-   E0 E0       CPX   #$E0
0C28-   AA          TAX
0C29-   8D AA 20    STA   $20AA
0C2C-   20 20 20    JSR   $2020
0C2F-   20 20 D0    JSR   $D020
0C32-   D2 CF       CMP   ($CF)
0C34-   C7          ???
0C35-   D2 C1       CMP   ($C1)
0C37-   CD 20 CD    CMP   $CD20
0C3A-   C1 C9       CMP   ($C9,X)
0C3C-   CE 20 C2    DEC   $C220
0C3F-   CF          ???
0C40-   C4 D9       CPY   $D9
0C42-   20 20 20    JSR   $2020
0C45-   20 20 20    JSR   $2020
0C48-   20 AA 8D    JSR   $8DAA
0C4B-   AA          TAX
0C4C-   AC AC AC    LDY   $ACAC
0C4F-   AC AC AC    LDY   $ACAC
0C52-   AC AC AC    LDY   $ACAC
0C55-   AC AC AC    LDY   $ACAC
0C58-   AC AC AC    LDY   $ACAC
0C5B-   AC AC AC    LDY   $ACAC
0C5E-   AC AC AC    LDY   $ACAC
0C61-   AC AC AC    LDY   $ACAC
0C64-   AC AC AC    LDY   $ACAC
0C67-   AC AC AC    LDY   $ACAC
0C6A-   AA          TAX
0C6B-   8D AA 8D    STA   $8DAA
0C6E-   A0 DF       LDY   #$DF
0C70-   D0 D2       BNE   $0C44
0C72-   CE D4 A0    DEC   $A0D4
0C75-   A2 20       LDX   #$20
0C77-   A2 AC       LDX   #$AC
0C79-   B8          CLV
0C7A-   C4 B8       CPY   $B8
0C7C-   C4 B8       CPY   $B8
0C7E-   C4 B8       CPY   $B8
0C80-   C4 8D       CPY   $8D
0C82-   A0 DF       LDY   #$DF
0C84-   D0 D2       BNE   $0C58
0C86-   CE D4 A0    DEC   $A0D4
0C89-   A2 D3       LDX   #$D3
0C8B-   D4          ???
0C8C-   D2 C9       CMP   ($C9)
0C8E-   CE C7 D3    DEC   $D3C7
0C91-   20 CC C9    JSR   $C9CC
0C94-   C2          ???
0C95-   D2 C1       CMP   ($C1)
0C97-   D2 D9       CMP   ($D9)
0C99-   20 C4 C5    JSR   $C5C4
0C9C-   CD CF A2    CMP   $A2CF
0C9F-   AC B8 C4    LDY   $C4B8
0CA2-   8D A0 DF    STA   $DFA0
0CA5-   D0 D2       BNE   $0C79
0CA7-   CE D4 A0    DEC   $A0D4
0CAA-   A2 AD       LDX   #$AD
0CAC-   AD AD AD    LDA   $ADAD
0CAF-   AD AD AD    LDA   $ADAD
0CB2-   AD AD AD    LDA   $ADAD
0CB5-   AD AD AD    LDA   $ADAD
0CB8-   AD AD AD    LDA   $ADAD
0CBB-   AD AD AD    LDA   $ADAD
0CBE-   AD A2 AC    LDA   $ACA2
0CC1-   B8          CLV
0CC2-   C4 8D       CPY   $8D
0CC4-   A0 DF       LDY   #$DF
0CC6-   D0 D2       BNE   $0C9A
0CC8-   CE D4 A0    DEC   $A0D4
0CCB-   A2 20       LDX   #$20
0CCD-   A2 AC       LDX   #$AC
0CCF-   B8          CLV
0CD0-   C4 8D       CPY   $8D
0CD2-   A0 DF       LDY   #$DF
0CD4-   D0 D2       BNE   $0CA8
0CD6-   CE D4 A0    DEC   $A0D4
0CD9-   A2 D4       LDX   #$D4
0CDB-   C8          INY
0CDC-   C5 20       CMP   $20
0CDE-   D3          ???
0CDF-   C3          ???
0CE0-   CD D0 20    CMP   $20D0
0CE3-   CD C1 C3    CMP   $C3C1
0CE6-   D2 CF       CMP   ($CF)
0CE8-   20 C3 CF    JSR   $CFC3
0CEB-   CD D0 C1    CMP   $C1D0
0CEE-   D2 C5       CMP   ($C5)
0CF0-   D3          ???
0CF1-   20 D4 D7    JSR   $D7D4
0CF4-   CF          ???
0CF5-   20 A2 AC    JSR   $ACA2
0CF8-   B8          CLV
0CF9-   C4 8D       CPY   $8D
0CFB-   A0 DF       LDY   #$DF
0CFD-   D0 D2       BNE   $0CD1
0CFF-   CE D4 A0    DEC   $A0D4
0D02-   A2 D3       LDX   #$D3
0D04-   D4          ???
0D05-   D2 C9       CMP   ($C9)
0D07-   CE C7 D3    DEC   $D3C7
0D0A-   20 C1 CE    JSR   $CEC1
0D0D-   C4 20       CPY   $20
0D0F-   D3          ???
0D10-   C5 D4       CMP   $D4
0D12-   D3          ???
0D13-   20 D4 C8    JSR   $C8D4
0D16-   C5 20       CMP   $20
0D18-   C6 CC       DEC   $CC
0D1A-   C1 C7       CMP   ($C7,X)
0D1C-   D3          ???
0D1D-   A2 AC       LDX   #$AC
0D1F-   B8          CLV
0D20-   C4 8D       CPY   $8D
0D22-   A0 DF       LDY   #$DF
0D24-   D0 D2       BNE   $0CF8
0D26-   CE D4 A0    DEC   $A0D4
0D29-   A2 C1       LDX   #$C1
0D2B-   C3          ???
0D2C-   C3          ???
0D2D-   CF          ???
0D2E-   D2 C4       CMP   ($C4)
0D30-   C9 CE       CMP   #$CE
0D32-   C7          ???
0D33-   CC D9 AE    CPY   $AED9
0D36-   20 C9 C6    JSR   $C6C9
0D39-   20 D4 C8    JSR   $C8D4
0D3C-   C5 20       CMP   $20
0D3E-   D4          ???
0D3F-   D7          ???
0D40-   CF          ???
0D41-   20 C1 D2    JSR   $D2C1
0D44-   C5 20       CMP   $20
0D46-   C5 D1       CMP   $D1
0D48-   D5 C1       CMP   $C1,X
0D4A-   CC AC A2    CPY   $A2AC
0D4D-   AC B8 C4    LDY   $C4B8
0D50-   8D A0 DF    STA   $DFA0
0D53-   D0 D2       BNE   $0D27
0D55-   CE D4 A0    DEC   $A0D4
0D58-   A2 D4       LDX   #$D4
0D5A-   C8          INY
0D5B-   C5 CE       CMP   $CE
0D5D-   20 AE DA    JSR   $DAAE
0D60-   20 C9 D3    JSR   $D3C9
0D63-   20 D3 C5    JSR   $C5D3
0D66-   D4          ???
0D67-   20 D4 CF    JSR   $CFD4
0D6A-   20 DA C5    JSR   $C5DA
0D6D-   D2 CF       CMP   ($CF)
0D6F-   BB          ???
0D70-   20 C9 C6    JSR   $C6C9
0D73-   20 CE CF    JSR   $CFCE
0D76-   D4          ???
0D77-   AC 20 B1    LDY   $B120
0D7A-   AE A2 AC    LDX   $ACA2
0D7D-   B8          CLV
0D7E-   C4 B8       CPY   $B8
0D80-   C4 8D       CPY   $8D
0D82-   A0 DF       LDY   #$DF
0D84-   D0 D2       BNE   $0D58
0D86-   CE D4 A0    DEC   $A0D4
0D89-   A2 C9       LDX   #$C9
0D8B-   C6 20       DEC   $20
0D8D-   D3          ???
0D8E-   D4          ???
0D8F-   D2 C9       CMP   ($C9)
0D91-   CE C7 B1    DEC   $B1C7
0D94-   20 CC C5    JSR   $C5CC
0D97-   CE C7 D4    DEC   $D4C7
0D9A-   C8          INY
0D9B-   20 BE 20    JSR   $20BE
0D9E-   D3          ???
0D9F-   D4          ???
0DA0-   D2 C9       CMP   ($C9)
0DA2-   CE C7 B2    DEC   $B2C7
0DA5-   20 CC C5    JSR   $C5CC
0DA8-   CE C7 D4    DEC   $D4C7
0DAB-   C8          INY
0DAC-   AC A2 AC    LDY   $ACA2
0DAF-   B8          CLV
0DB0-   C4 8D       CPY   $8D
0DB2-   A0 DF       LDY   #$DF
0DB4-   D0 D2       BNE   $0D88
0DB6-   CE D4 A0    DEC   $A0D4
0DB9-   A2 AE       LDX   #$AE
0DBB-   C3          ???
0DBC-   A8          TAY
0DBD-   C1 D2       CMP   ($D2,X)
0DBF-   D2 D9       CMP   ($D9)
0DC1-   A9 20       LDA   #$20
0DC3-   BD 20 B0    LDA   $B020,X
0DC6-   BB          ???
0DC7-   20 C5 CC    JSR   $CCC5
0DCA-   D3          ???
0DCB-   C5 AC       CMP   $AC
0DCD-   20 AE C3    JSR   $C3AE
0DD0-   20 BD 20    JSR   $20BD
0DD3-   B1 AE       LDA   ($AE),Y
0DD5-   A2 AC       LDX   #$AC
0DD7-   B8          CLV
0DD8-   C4 B8       CPY   $B8
0DDA-   C4 8D       CPY   $8D
0DDC-   A0 DF       LDY   #$DF
0DDE-   D0 D2       BNE   $0DB2
0DE0-   CE D4 A0    DEC   $A0D4
0DE3-   A2 D3       LDX   #$D3
0DE5-   CF          ???
0DE6-   AC 20 D7    LDY   $D720
0DE9-   C5 20       CMP   $20
0DEB-   C3          ???
0DEC-   C1 CE       CMP   ($CE,X)
0DEE-   20 C3 CF    JSR   $CFC3
0DF1-   CD D0 C1    CMP   $C1D0
0DF4-   D2 C5       CMP   ($C5)
0DF6-   20 D4 C8    JSR   $C8D4
0DF9-   C5 20       CMP   $20
0DFB-   CC C9 D4    CPY   $D4C9
0DFE-   C5 D2       CMP   $D2
0E00-   C1 CC       CMP   ($CC,X)
0E02-   20 A7 C1    JSR   $C1A7
0E05-   A7          ???
0E06-   A2 AC       LDX   #$AC
0E08-   B8          CLV
0E09-   C4 8D       CPY   $8D
0E0B-   A0 DF       LDY   #$DF
0E0D-   D0 D2       BNE   $0DE1
0E0F-   CE D4 A0    DEC   $A0D4
0E12-   A2 D4       LDX   #$D4
0E14-   CF          ???
0E15-   20 D4 C8    JSR   $C8D4
0E18-   C5 20       CMP   $20
0E1A-   D6 C1       DEC   $C1,X
0E1C-   CC D5 C5    CPY   $C5D5
0E1F-   20 D3 D4    JSR   $D4D3
0E22-   CF          ???
0E23-   D2 C5       CMP   ($C5)
0E25-   C4 20       CPY   $20
0E27-   C9 CE       CMP   #$CE
0E29-   20 C1 D3    JSR   $D3C1
0E2C-   D4          ???
0E2D-   D2 AC       CMP   ($AC)
0E2F-   20 D7 C8    JSR   $C8D7
0E32-   C9 C3       CMP   #$C3
0E34-   C8          INY
0E35-   A2 AC       LDX   #$AC
0E37-   B8          CLV
0E38-   C4 8D       CPY   $8D
0E3A-   A0 DF       LDY   #$DF
0E3C-   D0 D2       BNE   $0E10
0E3E-   CE D4 A0    DEC   $A0D4
0E41-   A2 C8       LDX   #$C8
0E43-   CF          ???
0E44-   CC C4 D3    CPY   $D3C4
0E47-   20 D4 C8    JSR   $C8D4
0E4A-   C5 20       CMP   $20
0E4C-   D3          ???
0E4D-   C1 CD       CMP   ($CD,X)
0E4F-   C5 20       CMP   $20
0E51-   D3          ???
0E52-   D4          ???
0E53-   D2 C9       CMP   ($C9)
0E55-   CE C7 AC    DEC   $ACC7
0E58-   20 D4 C8    JSR   $C8D4
0E5B-   C5 CE       CMP   $CE
0E5D-   20 D5 D3    JSR   $D3D5
0E60-   C5 20       CMP   $20
0E62-   C2          ???
0E63-   CE C5 20    DEC   $20C5
0E66-   D4          ???
0E67-   CF          ???
0E68-   A2 AC       LDX   #$AC
0E6A-   B8          CLV
0E6B-   C4 8D       CPY   $8D
0E6D-   A0 DF       LDY   #$DF
0E6F-   D0 D2       BNE   $0E43
0E71-   CE D4 A0    DEC   $A0D4
0E74-   A2 D4       LDX   #$D4
0E76-   C5 D3       CMP   $D3
0E78-   D4          ???
0E79-   20 C9 C6    JSR   $C6C9
0E7C-   20 D4 C8    JSR   $C8D4
0E7F-   C5 D9       CMP   $D9
0E81-   20 C1 D2    JSR   $D2C1
0E84-   C5 20       CMP   $20
0E86-   C5 D1       CMP   $D1
0E88-   D5 C1       CMP   $C1,X
0E8A-   CC AE A2    CPY   $A2AE
0E8D-   AC B8 C4    LDY   $C4B8
0E90-   B8          CLV
0E91-   C4 8D       CPY   $8D
0E93-   A0 D3       LDY   #$D3
0E95-   C3          ???
0E96-   CD D0 A0    CMP   $A0D0
0E99-   A2 C1       LDX   #$C1
0E9B-   A2 BB       LDX   #$BB
0E9D-   C1 D3       CMP   ($D3,X)
0E9F-   D4          ???
0EA0-   D2 8D       CMP   ($8D)
0EA2-   A0 C2       LDY   #$C2
0EA4-   CE C5 A0    DEC   $A0C5
0EA7-   D0 C5       BNE   $0E6E
0EA9-   A0 BB       LDY   #$BB
0EAB-   20 C9 D3    JSR   $D3C9
0EAE-   20 DA C5    JSR   $C5DA
0EB1-   D2 CF       CMP   ($CF)
0EB3-   20 C6 CC    JSR   $CCC6
0EB6-   C1 C7       CMP   ($C7,X)
0EB8-   20 B1 BF    JSR   $BFB1
0EBB-   20 C2 D2    JSR   $D2C2
0EBE-   C1 CE       CMP   ($CE,X)
0EC0-   C3          ???
0EC1-   C8          INY
0EC2-   20 C9 C6    JSR   $C6C9
0EC5-   20 D3 CF    JSR   $CFD3
0EC8-   8D A0 CA    STA   $CAA0
0ECB-   CD D0 A0    CMP   $A0D0
0ECE-   C3          ???
0ECF-   CF          ???
0ED0-   CE D4 8D    DEC   $8DD4
0ED3-   D0 C5       BNE   $0E9A
0ED5-   8D A0 DF    STA   $DFA0
0ED8-   D0 D2       BNE   $0EAC
0EDA-   CE D4 A0    DEC   $A0D4
0EDD-   A2 D4       LDX   #$D4
0EDF-   C8          INY
0EE0-   C5 20       CMP   $20
0EE2-   CC C9 D4    CPY   $D4C9
0EE5-   C5 D2       CMP   $D2
0EE7-   C1 CC       CMP   ($CC,X)
0EE9-   20 C1 20    JSR   $20C1
0EEC-   C1 CE       CMP   ($CE,X)
0EEE-   C4 20       CPY   $20
0EF0-   D4          ???
0EF1-   C8          INY
0EF2-   C5 20       CMP   $20
0EF4-   C1 20       CMP   ($20,X)
0EF6-   D3          ???
0EF7-   D4          ???
0EF8-   D2 C9       CMP   ($C9)
0EFA-   CE C7 20    DEC   $20C7
0EFD-   C1 D2       CMP   ($D2,X)
0EFF-   C5 A2       CMP   $A2
0F01-   AC B8 C4    LDY   $C4B8
0F04-   8D A0 DF    STA   $DFA0
0F07-   D0 D2       BNE   $0EDB
0F09-   CE D4 A0    DEC   $A0D4
0F0C-   A2 C5       LDX   #$C5
0F0E-   D1 D5       CMP   ($D5),Y
0F10-   C1 CC       CMP   ($CC,X)
0F12-   AE A2 AC    LDX   $ACA2
0F15-   B8          CLV
0F16-   C4 B8       CPY   $B8
0F18-   C4 B8       CPY   $B8
0F1A-   C4 8D       CPY   $8D
0F1C-   C3          ???
0F1D-   CF          ???
0F1E-   CE D4 8D    DEC   $8DD4
0F21-   A0 DF       LDY   #$DF
0F23-   D7          ???
0F24-   C1 C9       CMP   ($C9,X)
0F26-   D4          ???
0F27-   8D A0 DF    STA   $DFA0
0F2A-   D0 D2       BNE   $0EFE
0F2C-   CE D4 A0    DEC   $A0D4
0F2F-   A2 CE       LDX   #$CE
0F31-   CF          ???
0F32-   D4          ???
0F33-   C5 20       CMP   $20
0F35-   D4          ???
0F36-   C8          INY
0F37-   C1 D4       CMP   ($D4,X)
0F39-   20 CF CE    JSR   $CECF
0F3C-   CC D9 20    CPY   $20D9
0F3F-   C1 20       CMP   ($20,X)
0F41-   D3          ???
0F42-   C9 CE       CMP   #$CE
0F44-   C7          ???
0F45-   CC C5 20    CPY   $20C5
0F48-   D0 C1       BNE   $0F0B
0F4A-   D2 C1       CMP   ($C1)
0F4C-   CD C5 D4    CMP   $D4C5
0F4F-   C5 D2       CMP   $D2
0F51-   A2 AC       LDX   #$AC
0F53-   B8          CLV
0F54-   C4 8D       CPY   $8D
0F56-   A0 DF       LDY   #$DF
0F58-   D0 D2       BNE   $0F2C
0F5A-   CE D4 A0    DEC   $A0D4
0F5D-   A2 CD       LDX   #$CD
0F5F-   C1 D9       CMP   ($D9,X)
0F61-   20 C2 C5    JSR   $C5C2
0F64-   20 C1 20    JSR   $20C1
0F67-   CC C9 D4    CPY   $D4C9
0F6A-   C5 D2       CMP   $D2
0F6C-   C1 CC       CMP   ($CC,X)
0F6E-   20 D3 D4    JSR   $D4D3
0F71-   D2 C9       CMP   ($C9)
0F73-   CE C7 20    DEC   $20C7
0F76-   C9 CE       CMP   #$CE
0F78-   20 D3 C3    JSR   $C3D3
0F7B-   CD D0 BB    CMP   $BBD0
0F7E-   A2 AC       LDX   #$AC
0F80-   B8          CLV
0F81-   C4 8D       CPY   $8D
0F83-   A0 DF       LDY   #$DF
0F85-   D0 D2       BNE   $0F59
0F87-   CE D4 A0    DEC   $A0D4
0F8A-   A2 D4       LDX   #$D4
0F8C-   C8          INY
0F8D-   C9 D3       CMP   #$D3
0F8F-   20 D3 C1    JSR   $C1D3
0F92-   CD C5 20    CMP   $20C5
0F95-   D2 D5       CMP   ($D5)
0F97-   CC C5 20    CPY   $20C5
0F9A-   C1 D0       CMP   ($D0,X)
0F9C-   D0 CC       BNE   $0F6A
0F9E-   C9 C5       CMP   #$C5
0FA0-   D3          ???
0FA1-   20 D4 CF    JSR   $CFD4
0FA4-   20 C1 CC    JSR   $CCC1
0FA7-   CC 20 CD    CPY   $CD20
0FAA-   C1 C3       CMP   ($C3,X)
0FAC-   D2 CF       CMP   ($CF)
0FAE-   D3          ???
0FAF-   A2 AC       LDX   #$AC
0FB1-   B8          CLV
0FB2-   C4 8D       CPY   $8D
0FB4-   A0 DF       LDY   #$DF
0FB6-   D0 D2       BNE   $0F8A
0FB8-   CE D4 A0    DEC   $A0D4
0FBB-   A2 D4       LDX   #$D4
0FBD-   C8          INY
0FBE-   C1 D4       CMP   ($D4,X)
0FC0-   20 C1 C3    JSR   $C3C1
0FC3-   C3          ???
0FC4-   C5 D0       CMP   $D0
0FC6-   D4          ???
0FC7-   20 D3 D4    JSR   $D4D3
0FCA-   D2 C9       CMP   ($C9)
0FCC-   CE C7 D3    DEC   $D3C7
0FCF-   20 C1 D3    JSR   $D3C1
0FD2-   20 D0 C1    JSR   $C1D0
0FD5-   D2 C1       CMP   ($C1)
0FD7-   CD C5 D4    CMP   $D4C5
0FDA-   C5 D2       CMP   $D2
0FDC-   D3          ???
0FDD-   AE A2 AC    LDX   $ACA2
0FE0-   B8          CLV
0FE1-   C4 B8       CPY   $B8
0FE3-   C4 8D       CPY   $8D
0FE5-   A0 DF       LDY   #$DF
0FE7-   D0 D2       BNE   $0FBB
0FE9-   CE D4 A0    DEC   $A0D4
0FEC-   A2 D9       LDX   #$D9
0FEE-   CF          ???
0FEF-   D5 20       CMP   $20,X
0FF1-   C3          ???
0FF2-   C1 CE       CMP   ($CE,X)
0FF4-   20 C1 CC    JSR   $CCC1
0FF7-   D3          ???
0FF8-   CF          ???
0FF9-   20 D5 D3    JSR   $D3D5
0FFC-   C5 20       CMP   $20
0FFE-   D3          ???
0FFF-   C3          ???
1000-   CD D0 20    CMP   $20D0
1003-   D4          ???
1004-   CF          ???
1005-   20 C3 CF    JSR   $CFC3
1008-   CD D0 C1    CMP   $C1D0
100B-   D2 C5       CMP   ($C5)
100D-   A2 AC       LDX   #$AC
100F-   B8          CLV
1010-   C4 8D       CPY   $8D
1012-   A0 DF       LDY   #$DF
1014-   D0 D2       BNE   $0FE8
1016-   CE D4 A0    DEC   $A0D4
1019-   A2 D4       LDX   #$D4
101B-   C8          INY
101C-   C5 20       CMP   $20
101E-   CC C5 CE    CPY   $CEC5
1021-   C7          ???
1022-   D4          ???
1023-   C8          INY
1024-   D3          ???
1025-   20 CF C6    JSR   $C6CF
1028-   20 D4 D7    JSR   $D7D4
102B-   CF          ???
102C-   20 C4 C9    JSR   $C9C4
102F-   C6 C6       DEC   $C6
1031-   C5 D2       CMP   $D2
1033-   C5 CE       CMP   $CE
1035-   D4          ???
1036-   20 D3 D4    JSR   $D4D3
1039-   D2 C9       CMP   ($C9)
103B-   CE C7 D3    DEC   $D3C7
103E-   AE A2 AC    LDX   $ACA2
1041-   B8          CLV
1042-   C4 B8       CPY   $B8
1044-   C4 8D       CPY   $8D
1046-   A0 DF       LDY   #$DF
1048-   D0 D2       BNE   $101C
104A-   CE D4 A0    DEC   $A0D4
104D-   A2 D4       LDX   #$D4
104F-   C8          INY
1050-   C5 20       CMP   $20
1052-   C3          ???
1053-   C1 D2       CMP   ($D2,X)
1055-   D2 D9       CMP   ($D9)
1057-   20 C6 CC    JSR   $CCC6
105A-   C1 C7       CMP   ($C7,X)
105C-   20 C9 D3    JSR   $D3C9
105F-   20 D3 C5    JSR   $C5D3
1062-   D4          ???
1063-   20 D4 CF    JSR   $CFD4
1066-   20 B0 20    JSR   $20B0
1069-   C9 C6       CMP   #$C6
106B-   20 D4 C8    JSR   $C8D4
106E-   C5 A2       CMP   $A2
1070-   AC B8 C4    LDY   $C4B8
1073-   8D A0 DF    STA   $DFA0
1076-   D0 D2       BNE   $104A
1078-   CE D4 A0    DEC   $A0D4
107B-   A2 C6       LDX   #$C6
107D-   C9 D2       CMP   #$D2
107F-   D3          ???
1080-   D4          ???
1081-   20 D3 D4    JSR   $D4D3
1084-   D2 C9       CMP   ($C9)
1086-   CE C7 20    DEC   $20C7
1089-   C8          INY
108A-   C1 D3       CMP   ($D3,X)
108C-   20 C1 20    JSR   $20C1
108F-   CC C5 CE    CPY   $CEC5
1092-   C7          ???
1093-   D4          ???
1094-   C8          INY
1095-   20 BE 20    JSR   $20BE
1098-   D4          ???
1099-   C8          INY
109A-   C1 CE       CMP   ($CE,X)
109C-   20 D4 C8    JSR   $C8D4
109F-   C5 20       CMP   $20
10A1-   A2 AC       LDX   #$AC
10A3-   B8          CLV
10A4-   C4 8D       CPY   $8D
10A6-   A0 DF       LDY   #$DF
10A8-   D0 D2       BNE   $107C
10AA-   CE D4 A0    DEC   $A0D4
10AD-   A2 D3       LDX   #$D3
10AF-   C5 C3       CMP   $C3
10B1-   CF          ???
10B2-   CE C4 20    DEC   $20C4
10B5-   D3          ???
10B6-   D4          ???
10B7-   D2 C9       CMP   ($C9)
10B9-   CE C7 A7    DEC   $A7C7
10BC-   D3          ???
10BD-   20 CC C5    JSR   $C5CC
10C0-   CE C7 D4    DEC   $D4C7
10C3-   C8          INY
10C4-   AE 20 D4    LDX   $D420
10C7-   C8          INY
10C8-   C9 D3       CMP   #$D3
10CA-   20 C3 C1    JSR   $C1C3
10CD-   CE 20 D4    DEC   $D420
10D0-   C8          INY
10D1-   C5 CE       CMP   $CE
10D3-   A2 AC       LDX   #$AC
10D5-   B8          CLV
10D6-   C4 8D       CPY   $8D
10D8-   A0 DF       LDY   #$DF
10DA-   D0 D2       BNE   $10AE
10DC-   CE D4 A0    DEC   $A0D4
10DF-   A2 C2       LDX   #$C2
10E1-   C5 20       CMP   $20
10E3-   D4          ???
10E4-   C5 D3       CMP   $D3
10E6-   D4          ???
10E7-   C5 C4       CMP   $C4
10E9-   20 D7 C9    JSR   $C9D7
10EC-   D4          ???
10ED-   C8          INY
10EE-   20 C2 C3    JSR   $C3C2
10F1-   D3          ???
10F2-   AE A2 AC    LDX   $ACA2
10F5-   B8          CLV
10F6-   C4 B8       CPY   $B8
10F8-   C4 8D       CPY   $8D
10FA-   A0 DF       LDY   #$DF
10FC-   D0 D2       BNE   $10D0
10FE-   CE D4 A0    DEC   $A0D4
1101-   A2 D3       LDX   #$D3
1103-   CF          ???
1104-   20 C9 C6    JSR   $C6C9
1107-   20 D7 C5    JSR   $C5D7
110A-   20 C3 CF    JSR   $CFC3
110D-   CD D0 C1    CMP   $C1D0
1110-   D2 C5       CMP   ($C5)
1112-   20 D4 C8    JSR   $C8D4
1115-   C5 20       CMP   $20
1117-   CC C9 D4    CPY   $D4C9
111A-   C5 D2       CMP   $D2
111C-   C1 CC       CMP   ($CC,X)
111E-   20 A7 C1    JSR   $C1A7
1121-   C1 A7       CMP   ($A7,X)
1123-   20 A2 AC    JSR   $ACA2
1126-   B8          CLV
1127-   C4 8D       CPY   $8D
1129-   A0 DF       LDY   #$DF
112B-   D0 D2       BNE   $10FF
112D-   CE D4 A0    DEC   $A0D4
1130-   A2 D4       LDX   #$D4
1132-   CF          ???
1133-   20 D4 C8    JSR   $C8D4
1136-   C5 20       CMP   $20
1138-   D3          ???
1139-   C1 CD       CMP   ($CD,X)
113B-   C5 20       CMP   $20
113D-   C1 D3       CMP   ($D3,X)
113F-   D4          ???
1140-   D2 AC       CMP   ($AC)
1142-   20 D7 C5    JSR   $C5D7
1145-   20 D7 C9    JSR   $C9D7
1148-   CC CC 20    CPY   $20CC
114B-   C6 C9       DEC   $C9
114D-   CE C4 20    DEC   $20C4
1150-   D4          ???
1151-   C8          INY
1152-   C1 D4       CMP   ($D4,X)
1154-   A2 AC       LDX   #$AC
1156-   B8          CLV
1157-   C4 8D       CPY   $8D
1159-   A0 DF       LDY   #$DF
115B-   D0 D2       BNE   $112F
115D-   CE D4 A0    DEC   $A0D4
1160-   A2 D4       LDX   #$D4
1162-   C8          INY
1163-   C5 20       CMP   $20
1165-   CC C9 D4    CPY   $D4C9
1168-   C5 D2       CMP   $D2
116A-   C1 CC       CMP   ($CC,X)
116C-   20 C8 C1    JSR   $C1C8
116F-   D3          ???
1170-   20 C1 20    JSR   $20C1
1173-   C7          ???
1174-   D2 C5       CMP   ($C5)
1176-   C1 D4       CMP   ($D4,X)
1178-   C5 D2       CMP   $D2
117A-   20 CC C5    JSR   $C5CC
117D-   CE C7 D4    DEC   $D4C7
1180-   C8          INY
1181-   AE A2 AC    LDX   $ACA2
1184-   B8          CLV
1185-   C4 B8       CPY   $B8
1187-   C4 8D       CPY   $8D
1189-   AA          TAX
118A-   8D A0 D3    STA   $D3A0
118D-   C3          ???
118E-   CD D0 A0    CMP   $A0D0
1191-   A2 C1       LDX   #$C1
1193-   C1 A2       CMP   ($A2,X)
1195-   BB          ???
1196-   C1 D3       CMP   ($D3,X)
1198-   D4          ???
1199-   D2 8D       CMP   ($8D)
119B-   A0 C2       LDY   #$C2
119D-   C3          ???
119E-   D3          ???
119F-   A0 CC       LDY   #$CC
11A1-   C5 8D       CMP   $8D
11A3-   A0 CA       LDY   #$CA
11A5-   CD D0 A0    CMP   $A0D0
11A8-   C3          ???
11A9-   CF          ???
11AA-   CE D4 B2    DEC   $B2D4
11AD-   8D CC C5    STA   $C5CC
11B0-   8D A0 DF    STA   $DFA0
11B3-   D0 D2       BNE   $1187
11B5-   CE D4 A0    DEC   $A0D4
11B8-   A2 D4       LDX   #$D4
11BA-   C8          INY
11BB-   C5 20       CMP   $20
11BD-   CC C9 D4    CPY   $D4C9
11C0-   C5 D2       CMP   $D2
11C2-   C1 CC       CMP   ($CC,X)
11C4-   20 A7 C1    JSR   $C1A7
11C7-   C1 A7       CMP   ($A7,X)
11C9-   20 C9 D3    JSR   $D3C9
11CC-   20 C7 D2    JSR   $D2C7
11CF-   C5 C1       CMP   $C1
11D1-   D4          ???
11D2-   C5 D2       CMP   $D2
11D4-   20 D4 C8    JSR   $C8D4
11D7-   C1 CE       CMP   ($CE,X)
11D9-   20 A2 AC    JSR   $ACA2
11DC-   B8          CLV
11DD-   C4 8D       CPY   $8D
11DF-   A0 DF       LDY   #$DF
11E1-   D0 D2       BNE   $11B5
11E3-   CE D4 A0    DEC   $A0D4
11E6-   A2 C1       LDX   #$C1
11E8-   D3          ???
11E9-   D4          ???
11EA-   D2 AC       CMP   ($AC)
11EC-   20 D7 C8    JSR   $C8D7
11EF-   C9 C3       CMP   #$C3
11F1-   C8          INY
11F2-   20 C8 CF    JSR   $CFC8
11F5-   CC C4 D3    CPY   $D3C4
11F8-   20 A7 C1    JSR   $C1A7
11FB-   A7          ???
11FC-   AE A2 AC    LDX   $ACA2
11FF-   B8          CLV
1200-   C4 B8       CPY   $B8
1202-   C4 B8       CPY   $B8
1204-   C4 8D       CPY   $8D
1206-   C3          ???
1207-   CF          ???
1208-   CE D4 B2    DEC   $B2D4
120B-   8D A0 DF    STA   $DFA0
120E-   D7          ???
120F-   C1 C9       CMP   ($C9,X)
1211-   D4          ???
1212-   8D AA 8D    STA   $8DAA
1215-   A0 DF       LDY   #$DF
1217-   D0 D2       BNE   $11EB
1219-   CE D4 A0    DEC   $A0D4
121C-   A2 20       LDX   #$20
121E-   A2 AC       LDX   #$AC
1220-   B8          CLV
1221-   C4 B8       CPY   $B8
1223-   C4 B8       CPY   $B8
1225-   C4 B8       CPY   $B8
1227-   C4 8D       CPY   $8D
1229-   A0 DF       LDY   #$DF
122B-   D0 D2       BNE   $11FF
122D-   CE D4 A0    DEC   $A0D4
1230-   A2 D4       LDX   #$D4
1232-   C8          INY
1233-   C5 20       CMP   $20
1235-   D3          ???
1236-   C3          ???
1237-   C1 D4       CMP   ($D4,X)
1239-   20 CD C1    JSR   $C1CD
123C-   C3          ???
123D-   D2 CF       CMP   ($CF)
123F-   20 C3 CF    JSR   $CFC3
1242-   CE C3 C1    DEC   $C1C3
1245-   D4          ???
1246-   C5 CE       CMP   $CE
1248-   C1 D4       CMP   ($D4,X)
124A-   C5 D3       CMP   $D3
124C-   A2 AC       LDX   #$AC
124E-   B8          CLV
124F-   C4 8D       CPY   $8D
1251-   A0 DF       LDY   #$DF
1253-   D0 D2       BNE   $1227
1255-   CE D4 A0    DEC   $A0D4
1258-   A2 C1       LDX   #$C1
125A-   20 D3 C5    JSR   $C5D3
125D-   C3          ???
125E-   CF          ???
125F-   CE C4 20    DEC   $20C4
1262-   C7          ???
1263-   C9 D6       CMP   #$D6
1265-   C5 CE       CMP   $CE
1267-   20 D3 D4    JSR   $D4D3
126A-   D2 C9       CMP   ($C9)
126C-   CE C7 20    DEC   $20C7
126F-   D4          ???
1270-   CF          ???
1271-   20 C1 20    JSR   $20C1
1274-   A2 AC       LDX   #$AC
1276-   B8          CLV
1277-   C4 8D       CPY   $8D
1279-   A0 DF       LDY   #$DF
127B-   D0 D2       BNE   $124F
127D-   CE D4 A0    DEC   $A0D4
1280-   A2 C6       LDX   #$C6
1282-   C9 D2       CMP   #$D2
1284-   D3          ???
1285-   D4          ???
1286-   20 C7 C9    JSR   $C9C7
1289-   D6 C5       DEC   $C5,X
128B-   CE 20 D3    DEC   $D320
128E-   D4          ???
128F-   D2 C9       CMP   ($C9)
1291-   CE C7 AE    DEC   $AEC7
1294-   20 C5 C9    JSR   $C9C5
1297-   D4          ???
1298-   C8          INY
1299-   C5 D2       CMP   $D2
129B-   20 D0 C1    JSR   $C1D0
129E-   D2 C1       CMP   ($C1)
12A0-   CD C5 D4    CMP   $D4C5
12A3-   C5 D2       CMP   $D2
12A5-   A2 AC       LDX   #$AC
12A7-   B8          CLV
12A8-   C4 8D       CPY   $8D
12AA-   A0 DF       LDY   #$DF
12AC-   D0 D2       BNE   $1280
12AE-   CE D4 A0    DEC   $A0D4
12B1-   A2 CD       LDX   #$CD
12B3-   C1 D9       CMP   ($D9,X)
12B5-   20 C2 C5    JSR   $C5C2
12B8-   20 C1 20    JSR   $20C1
12BB-   CC C9 D4    CPY   $D4C9
12BE-   C5 D2       CMP   $D2
12C0-   C1 CC       CMP   ($CC,X)
12C2-   20 D3 D4    JSR   $D4D3
12C5-   D2 C9       CMP   ($C9)
12C7-   CE C7 AC    DEC   $ACC7
12CA-   20 C2 D5    JSR   $D5C2
12CD-   D4          ???
12CE-   20 CE C5    JSR   $C5CE
12D1-   D6 C5       DEC   $C5,X
12D3-   D2 20       CMP   ($20)
12D5-   C2          ???
12D6-   CF          ???
12D7-   D4          ???
12D8-   C8          INY
12D9-   AE A2 AC    LDX   $ACA2
12DC-   B8          CLV
12DD-   C4 B8       CPY   $B8
12DF-   C4 8D       CPY   $8D
12E1-   A0 DF       LDY   #$DF
12E3-   D0 D2       BNE   $12B7
12E5-   CE D4 A0    DEC   $A0D4
12E8-   A2 D3       LDX   #$D3
12EA-   C3          ???
12EB-   C1 D4       CMP   ($D4,X)
12ED-   20 A7 D7    JSR   $D7A7
12F0-   D4          ???
12F1-   C6 20       DEC   $20
12F3-   C9 D3       CMP   #$D3
12F5-   20 A7 BB    JSR   $BBA7
12F8-   C1 D3       CMP   ($D3,X)
12FA-   D4          ???
12FB-   D2 BB       CMP   ($BB)
12FD-   A3          ???
12FE-   B5 B0       LDA   $B0,X
1300-   20 D2 C5    JSR   $C5D2
1303-   D4          ???
1304-   D5 D2       CMP   $D2,X
1306-   CE D3 BA    DEC   $BAD3
1309-   20 A2 AC    JSR   $ACA2
130C-   B8          CLV
130D-   C4 B8       CPY   $B8
130F-   C4 8D       CPY   $8D
1311-   A0 D3       LDY   #$D3
1313-   C3          ???
1314-   C1 D4       CMP   ($D4,X)
1316-   A0 A2       LDY   #$A2
1318-   D7          ???
1319-   D4          ???
131A-   C6 20       DEC   $20
131C-   C9 D3       CMP   #$D3
131E-   20 A2 BB    JSR   $BBA2
1321-   A3          ???
1322-   C1 D3       CMP   ($D3,X)
1324-   D4          ???
1325-   D2 BB       CMP   ($BB)
1327-   A3          ???
1328-   B5 B0       LDA   $B0,X
132A-   8D A0 D3    STA   $D3A0
132D-   D0 D2       BNE   $1301
132F-   CE A0 A3    DEC   $A3A0
1332-   D2 C5       CMP   ($C5)
1334-   D4          ???
1335-   D5 D2       CMP   $D2,X
1337-   CE 8D A0    DEC   $A08D
133A-   DF          ???
133B-   D0 D2       BNE   $130F
133D-   CE D4 A0    DEC   $A0D4
1340-   A2 20       LDX   #$20
1342-   A2 AC       LDX   #$AC
1344-   B8          CLV
1345-   C4 B8       CPY   $B8
1347-   C4 B8       CPY   $B8
1349-   C4 8D       CPY   $8D
134B-   A0 DF       LDY   #$DF
134D-   D7          ???
134E-   C1 C9       CMP   ($C9,X)
1350-   D4          ???
1351-   8D AA 8D    STA   $8DAA
1354-   A0 DF       LDY   #$DF
1356-   D0 D2       BNE   $132A
1358-   CE D4 A0    DEC   $A0D4
135B-   A2 D4       LDX   #$D4
135D-   CF          ???
135E-   20 D3 C8    JSR   $C8D3
1361-   CF          ???
1362-   D7          ???
1363-   20 D4 C8    JSR   $C8D4
1366-   C5 20       CMP   $20
1368-   D2 C5       CMP   ($C5)
136A-   D3          ???
136B-   D5 CC       CMP   $CC,X
136D-   D4          ???
136E-   20 CF C6    JSR   $C6CF
1371-   20 D3 C3    JSR   $C3D3
1374-   C1 D4       CMP   ($D4,X)
1376-   AC A2 AC    LDY   $ACA2
1379-   B8          CLV
137A-   C4 8D       CPY   $8D
137C-   A0 DF       LDY   #$DF
137E-   D0 D2       BNE   $1352
1380-   CE D4 A0    DEC   $A0D4
1383-   A2 D7       LDX   #$D7
1385-   C5 20       CMP   $20
1387-   D5 D3       CMP   $D3,X
1389-   C5 C4       CMP   $C4
138B-   20 D4 C8    JSR   $C8D4
138E-   C5 20       CMP   $20
1390-   D3          ???
1391-   D0 D2       BNE   $1365
1393-   CE 20 CD    DEC   $CD20
1396-   C1 C3       CMP   ($C3,X)
1398-   D2 CF       CMP   ($CF)
139A-   AC 20 D7    LDY   $D720
139D-   C8          INY
139E-   C9 C3       CMP   #$C3
13A0-   C8          INY
13A1-   A2 AC       LDX   #$AC
13A3-   B8          CLV
13A4-   C4 8D       CPY   $8D
13A6-   A0 DF       LDY   #$DF
13A8-   D0 D2       BNE   $137C
13AA-   CE D4 A0    DEC   $A0D4
13AD-   A2 D3       LDX   #$D3
13AF-   C9 CD       CMP   #$CD
13B1-   D0 CC       BNE   $137F
13B3-   D9 20 D0    CMP   $D020,Y
13B6-   D2 C9       CMP   ($C9)
13B8-   CE D4 D3    DEC   $D3D4
13BB-   20 C1 20    JSR   $20C1
13BE-   D3          ???
13BF-   D4          ???
13C0-   D2 C9       CMP   ($C9)
13C2-   CE C7 AE    DEC   $AEC7
13C5-   20 D4 C8    JSR   $C8D4
13C8-   C9 D3       CMP   #$D3
13CA-   A2 AC       LDX   #$AC
13CC-   B8          CLV
13CD-   C4 8D       CPY   $8D
13CF-   A0 DF       LDY   #$DF
13D1-   D0 D2       BNE   $13A5
13D3-   CE D4 A0    DEC   $A0D4
13D6-   A2 D7       LDX   #$D7
13D8-   CF          ???
13D9-   D2 CB       CMP   ($CB)
13DB-   D3          ???
13DC-   20 C4 C9    JSR   $C9C4
13DF-   C6 C6       DEC   $C6
13E1-   C5 D2       CMP   $D2
13E3-   C5 CE       CMP   $CE
13E5-   D4          ???
13E6-   CC D9 20    CPY   $20D9
13E9-   D4          ???
13EA-   C8          INY
13EB-   C1 CE       CMP   ($CE,X)
13ED-   20 D4 C8    JSR   $C8D4
13F0-   C5 20       CMP   $20
13F2-   D0 D2       BNE   $13C6
13F4-   C9 CE       CMP   #$CE
13F6-   D4          ???
13F7-   A2 AC       LDX   #$AC
13F9-   B8          CLV
13FA-   C4 8D       CPY   $8D
13FC-   A0 DF       LDY   #$DF
13FE-   D0 D2       BNE   $13D2
1400-   CE D4 A0    DEC   $A0D4
1403-   A2 D2       LDX   #$D2
1405-   CF          ???
1406-   D5 D4       CMP   $D4,X
1408-   C9 CE       CMP   #$CE
140A-   C5 D3       CMP   $D3
140C-   20 C9 CE    JSR   $CEC9
140F-   20 D3 D4    JSR   $D4D3
1412-   C4 C9       CPY   $C9
1414-   CF          ???
1415-   20 CF D2    JSR   $D2CF
1418-   20 D4 C8    JSR   $C8D4
141B-   C5 20       CMP   $20
141D-   DF          ???
141E-   D0 D2       BNE   $13F2
1420-   CE D4 A2    DEC   $A2D4
1423-   AC B8 C4    LDY   $C4B8
1426-   8D A0 DF    STA   $DFA0
1429-   D0 D2       BNE   $13FD
142B-   CE D4 A0    DEC   $A0D4
142E-   A2 D2       LDX   #$D2
1430-   CF          ???
1431-   D5 D4       CMP   $D4,X
1433-   C9 CE       CMP   #$CE
1435-   C5 AC       CMP   $AC
1437-   20 C1 D3    JSR   $D3C1
143A-   20 C9 D4    JSR   $D4C9
143D-   20 C3 C1    JSR   $C1C3
1440-   CE 20 CF    DEC   $CF20
1443-   CE CC D9    DEC   $D9CC
1446-   20 C8 C1    JSR   $C1C8
1449-   CE C4 CC    DEC   $CCC4
144C-   C5 A2       CMP   $A2
144E-   AC B8 C4    LDY   $C4B8
1451-   8D A0 DF    STA   $DFA0
1454-   D0 D2       BNE   $1428
1456-   CE D4 A0    DEC   $A0D4
1459-   A2 C1       LDX   #$C1
145B-   20 D3 D4    JSR   $D4D3
145E-   D2 C9       CMP   ($C9)
1460-   CE C7 20    DEC   $20C7
1463-   C1 C4       CMP   ($C4,X)
1465-   C4 D2       CPY   $D2
1467-   C5 D3       CMP   $D3
1469-   D3          ???
146A-   AE A2 AC    LDX   $ACA2
146D-   B8          CLV
146E-   C4 B8       CPY   $B8
1470-   C4 8D       CPY   $8D
1472-   A0 DF       LDY   #$DF
1474-   D0 D2       BNE   $1448
1476-   CE D4 A0    DEC   $A0D4
1479-   A2 D3       LDX   #$D3
147B-   D0 D2       BNE   $144F
147D-   CE 20 C2    DEC   $C220
1480-   D3          ???
1481-   D4          ???
1482-   D2 20       CMP   ($20)
1484-   D2 C5       CMP   ($C5)
1486-   D4          ???
1487-   D5 D2       CMP   $D2,X
1489-   CE D3 BA    DEC   $BAD3
148C-   20 A2 8D    JSR   $8DA2
148F-   A0 D3       LDY   #$D3
1491-   D0 D2       BNE   $1465
1493-   CE A0 A3    DEC   $A3A0
1496-   C2          ???
1497-   D3          ???
1498-   D4          ???
1499-   D2 8D       CMP   ($8D)
149B-   A0 DF       LDY   #$DF
149D-   D0 D2       BNE   $1471
149F-   CE D4 A0    DEC   $A0D4
14A2-   A2 20       LDX   #$20
14A4-   A2 AC       LDX   #$AC
14A6-   B8          CLV
14A7-   C4 B8       CPY   $B8
14A9-   C4 B8       CPY   $B8
14AB-   C4 8D       CPY   $8D
14AD-   A0 DF       LDY   #$DF
14AF-   D7          ???
14B0-   C1 C9       CMP   ($C9,X)
14B2-   D4          ???
14B3-   8D AA 8D    STA   $8DAA
14B6-   A0 DF       LDY   #$DF
14B8-   D0 D2       BNE   $148C
14BA-   CE D4 A0    DEC   $A0D4
14BD-   A2 20       LDX   #$20
14BF-   A2 AC       LDX   #$AC
14C1-   B8          CLV
14C2-   C4 B8       CPY   $B8
14C4-   C4 B8       CPY   $B8
14C6-   C4 B8       CPY   $B8
14C8-   C4 8D       CPY   $8D
14CA-   A0 DF       LDY   #$DF
14CC-   D0 D2       BNE   $14A0
14CE-   CE D4 A0    DEC   $A0D4
14D1-   A2 D3       LDX   #$D3
14D3-   D5 C2       CMP   $C2,X
14D5-   D3          ???
14D6-   D4          ???
14D7-   D2 C9       CMP   ($C9)
14D9-   CE C7 20    DEC   $20C7
14DC-   D2 CF       CMP   ($CF)
14DE-   D5 D4       CMP   $D4,X
14E0-   C9 CE       CMP   #$CE
14E2-   C5 D3       CMP   $D3
14E4-   AF          ???
14E5-   CD C1 C3    CMP   $C3C1
14E8-   D2 CF       CMP   ($CF)
14EA-   D3          ???
14EB-   A2 AC       LDX   #$AC
14ED-   B8          CLV
14EE-   C4 8D       CPY   $8D
14F0-   A0 DF       LDY   #$DF
14F2-   D0 D2       BNE   $14C6
14F4-   CE D4 A0    DEC   $A0D4
14F7-   A2 AD       LDX   #$AD
14F9-   AD AD AD    LDA   $ADAD
14FC-   AD AD AD    LDA   $ADAD
14FF-   AD AD AD    LDA   $ADAD
1502-   AD AD AD    LDA   $ADAD
1505-   AD AD AD    LDA   $ADAD
1508-   AD AD AD    LDA   $ADAD
150B-   AD AD AD    LDA   $ADAD
150E-   AD AD AD    LDA   $ADAD
1511-   A2 AC       LDX   #$AC
1513-   B8          CLV
1514-   C4 B8       CPY   $B8
1516-   C4 8D       CPY   $8D
1518-   A0 DF       LDY   #$DF
151A-   D0 D2       BNE   $14EE
151C-   CE D4 A0    DEC   $A0D4
151F-   A2 D3       LDX   #$D3
1521-   D0 CF       BNE   $14F2
1523-   D3          ???
1524-   20 C6 C9    JSR   $C9C6
1527-   CE C4 D3    DEC   $D3C4
152A-   20 D4 C8    JSR   $C8D4
152D-   C5 20       CMP   $20
152F-   D0 CF       BNE   $1500
1531-   D3          ???
1532-   C9 D4       CMP   #$D4
1534-   C9 CF       CMP   #$CF
1536-   CE 20 CF    DEC   $CF20
1539-   C6 A2       DEC   $A2
153B-   AC B8 C4    LDY   $C4B8
153E-   8D A0 DF    STA   $DFA0
1541-   D0 D2       BNE   $1515
1543-   CE D4 A0    DEC   $A0D4
1546-   A2 C1       LDX   #$C1
1548-   20 D3 D5    JSR   $D5D3
154B-   C2          ???
154C-   D3          ???
154D-   D4          ???
154E-   D2 C9       CMP   ($C9)
1550-   CE C7 20    DEC   $20C7
1553-   D7          ???
1554-   C9 D4       CMP   #$D4
1556-   C8          INY
1557-   C9 CE       CMP   #$CE
1559-   20 C1 CE    JSR   $CEC1
155C-   CF          ???
155D-   D4          ???
155E-   C8          INY
155F-   C5 D2       CMP   $D2
1561-   A2 AC       LDX   #$AC
1563-   B8          CLV
1564-   C4 8D       CPY   $8D
1566-   A0 DF       LDY   #$DF
1568-   D0 D2       BNE   $153C
156A-   CE D4 A0    DEC   $A0D4
156D-   A2 D3       LDX   #$D3
156F-   D4          ???
1570-   D2 C9       CMP   ($C9)
1572-   CE C7 AE    DEC   $AEC7
1575-   A2 AC       LDX   #$AC
1577-   B8          CLV
1578-   C4 B8       CPY   $B8
157A-   C4 8D       CPY   $8D
157C-   A0 DF       LDY   #$DF
157E-   D0 D2       BNE   $1552
1580-   CE D4 A0    DEC   $A0D4
1583-   A2 D3       LDX   #$D3
1585-   D0 CF       BNE   $1556
1587-   D3          ???
1588-   20 A7 D4    JSR   $D4A7
158B-   C8          INY
158C-   C9 D3       CMP   #$D3
158E-   20 C9 D3    JSR   $D3C9
1591-   20 C1 20    JSR   $20C1
1594-   D3          ???
1595-   D4          ???
1596-   D2 C9       CMP   ($C9)
1598-   CE C7 A7    DEC   $A7C7
159B-   BB          ???
159C-   C1 D3       CMP   ($D3,X)
159E-   D4          ???
159F-   D2 20       CMP   ($20)
15A1-   D2 C5       CMP   ($C5)
15A3-   D4          ???
15A4-   D5 D2       CMP   $D2,X
15A6-   CE D3 BA    DEC   $BAD3
15A9-   20 A2 8D    JSR   $8DA2
15AC-   A0 D3       LDY   #$D3
15AE-   D0 CF       BNE   $157F
15B0-   D3          ???
15B1-   A0 A2       LDY   #$A2
15B3-   D4          ???
15B4-   C8          INY
15B5-   C9 D3       CMP   #$D3
15B7-   20 C9 D3    JSR   $D3C9
15BA-   20 C1 20    JSR   $20C1
15BD-   D3          ???
15BE-   D4          ???
15BF-   D2 C9       CMP   ($C9)
15C1-   CE C7 A2    DEC   $A2C7
15C4-   BB          ???
15C5-   A3          ???
15C6-   C1 D3       CMP   ($D3,X)
15C8-   D4          ???
15C9-   D2 8D       CMP   ($8D)
15CB-   A0 D3       LDY   #$D3
15CD-   D4          ???
15CE-   C1 A0       CMP   ($A0,X)
15D0-   A4 B3       LDY   $B3
15D2-   B0 B0       BCS   $1584
15D4-   8D A0 CC    STA   $CCA0
15D7-   C4 C1       CPY   $C1
15D9-   A0 A3       LDY   #$A3
15DB-   B0 8D       BCS   $156A
15DD-   A0 D3       LDY   #$D3
15DF-   D4          ???
15E0-   C1 A0       CMP   ($A0,X)
15E2-   A4 B3       LDY   $B3
15E4-   B0 B1       BCS   $1597
15E6-   A0 BB       LDY   #$BB
15E8-   20 C3 CC    JSR   $CCC3
15EB-   C5 C1       CMP   $C1
15ED-   D2 20       CMP   ($20)
15EF-   C8          INY
15F0-   C9 20       CMP   #$20
15F2-   C2          ???
15F3-   D9 D4 C5    CMP   $C5D4,Y
15F6-   8D A0 C4    STA   $C4A0
15F9-   D5 CD       CMP   $CD,X
15FB-   D0 A0       BNE   $159D
15FD-   A3          ???
15FE-   D2 C5       CMP   ($C5)
1600-   D4          ???
1601-   D5 D2       CMP   $D2,X
1603-   CE BB A3    DEC   $A3BB
1606-   B1 8D       LDA   ($8D),Y
1608-   A0 DF       LDY   #$DF
160A-   D0 D2       BNE   $15DE
160C-   CE D4 A0    DEC   $A0D4
160F-   A2 20       LDX   #$20
1611-   A2 AC       LDX   #$AC
1613-   B8          CLV
1614-   C4 B8       CPY   $B8
1616-   C4 B8       CPY   $B8
1618-   C4 8D       CPY   $8D
161A-   AA          TAX
161B-   8D A0 DF    STA   $DFA0
161E-   D0 D2       BNE   $15F2
1620-   CE D4 A0    DEC   $A0D4
1623-   A2 20       LDX   #$20
1625-   A2 AC       LDX   #$AC
1627-   B8          CLV
1628-   C4 B8       CPY   $B8
162A-   C4 B8       CPY   $B8
162C-   C4 8D       CPY   $8D
162E-   A0 DF       LDY   #$DF
1630-   D0 D2       BNE   $1604
1632-   CE D4 A0    DEC   $A0D4
1635-   A2 D4       LDX   #$D4
1637-   C8          INY
1638-   C5 20       CMP   $20
163A-   D3          ???
163B-   C3          ???
163C-   D0 D9       BNE   $1617
163E-   20 CD C1    JSR   $C1CD
1641-   C3          ???
1642-   D2 CF       CMP   ($CF)
1644-   20 C3 CF    JSR   $CFC3
1647-   D0 C9       BNE   $1612
1649-   C5 D3       CMP   $D3
164B-   20 C1 20    JSR   $20C1
164E-   A2 AC       LDX   #$AC
1650-   B8          CLV
1651-   C4 8D       CPY   $8D
1653-   A0 DF       LDY   #$DF
1655-   D0 D2       BNE   $1629
1657-   CE D4 A0    DEC   $A0D4
165A-   A2 D3       LDX   #$D3
165C-   D5 C2       CMP   $C2,X
165E-   D3          ???
165F-   D4          ???
1660-   D2 C9       CMP   ($C9)
1662-   CE C7 20    DEC   $20C7
1665-   C6 D2       DEC   $D2
1667-   CF          ???
1668-   CD 20 C1    CMP   $C120
166B-   CE CF D4    DEC   $D4CF
166E-   C8          INY
166F-   C5 D2       CMP   $D2
1671-   20 D3 D4    JSR   $D4D3
1674-   D2 C9       CMP   ($C9)
1676-   CE C7 A2    DEC   $A2C7
1679-   AC B8 C4    LDY   $C4B8
167C-   8D A0 DF    STA   $DFA0
167F-   D0 D2       BNE   $1653
1681-   CE D4 A0    DEC   $A0D4
1684-   A2 C1       LDX   #$C1
1686-   D4          ???
1687-   20 D4 C8    JSR   $C8D4
168A-   C5 20       CMP   $20
168C-   D3          ???
168D-   D0 C5       BNE   $1654
168F-   C3          ???
1690-   C9 C6       CMP   #$C6
1692-   C9 C5       CMP   #$C5
1694-   C4 20       CPY   $20
1696-   C9 CE       CMP   #$CE
1698-   C4 C5       CPY   $C5
169A-   D8          CLD
169B-   AC 20 C8    LDY   $C820
169E-   CF          ???
169F-   CC C4 C9    CPY   $C9C4
16A2-   CE C7 A2    DEC   $A2C7
16A5-   AC B8 C4    LDY   $C4B8
16A8-   8D A0 DF    STA   $DFA0
16AB-   D0 D2       BNE   $167F
16AD-   CE D4 A0    DEC   $A0D4
16B0-   A2 D4       LDX   #$D4
16B2-   C8          INY
16B3-   C5 20       CMP   $20
16B5-   D3          ???
16B6-   D5 C2       CMP   $C2,X
16B8-   D3          ???
16B9-   D4          ???
16BA-   D2 C9       CMP   ($C9)
16BC-   CE C7 20    DEC   $20C7
16BF-   C9 CE       CMP   #$CE
16C1-   20 DB D2    JSR   $D2DB
16C4-   C5 D4       CMP   $D4
16C6-   D5 D2       CMP   $D2,X
16C8-   CE DD AE    DEC   $AEDD
16CB-   A2 AC       LDX   #$AC
16CD-   B8          CLV
16CE-   C4 B8       CPY   $B8
16D0-   C4 8D       CPY   $8D
16D2-   A0 DF       LDY   #$DF
16D4-   D0 D2       BNE   $16A8
16D6-   CE D4 A0    DEC   $A0D4
16D9-   A2 D3       LDX   #$D3
16DB-   C3          ???
16DC-   D0 D9       BNE   $16B7
16DE-   20 A7 C1    JSR   $C1A7
16E1-   C2          ???
16E2-   C3          ???
16E3-   C4 C5       CPY   $C5
16E5-   C6 C7       DEC   $C7
16E7-   C8          INY
16E8-   C9 CA       CMP   #$CA
16EA-   CB          ???
16EB-   A7          ???
16EC-   BB          ???
16ED-   A3          ???
16EE-   B2 BB       LDA   ($BB)
16F0-   A3          ???
16F1-   B4 BB       LDY   $BB,X
16F3-   A3          ???
16F4-   B5 B0       LDA   $B0,X
16F6-   20 D2 C5    JSR   $C5D2
16F9-   D4          ???
16FA-   D5 D2       CMP   $D2,X
16FC-   CE D3 BA    DEC   $BAD3
16FF-   20 A2 8D    JSR   $8DA2
1702-   A0 D3       LDY   #$D3
1704-   C3          ???
1705-   D0 D9       BNE   $16E0
1707-   A0 A2       LDY   #$A2
1709-   C1 C2       CMP   ($C2,X)
170B-   C3          ???
170C-   C4 C5       CPY   $C5
170E-   C6 C7       DEC   $C7
1710-   C8          INY
1711-   C9 CA       CMP   #$CA
1713-   CB          ???
1714-   A2 BB       LDX   #$BB
1716-   A3          ???
1717-   B2 BB       LDA   ($BB)
1719-   A3          ???
171A-   B4 BB       LDY   $BB,X
171C-   A3          ???
171D-   A4 C6       LDY   $C6
171F-   C6 8D       DEC   $8D
1721-   A0 D3       LDY   #$D3
1723-   D0 D2       BNE   $16F7
1725-   CE A0 A3    DEC   $A3A0
1728-   D2 C5       CMP   ($C5)
172A-   D4          ???
172B-   D5 D2       CMP   $D2,X
172D-   CE 8D A0    DEC   $A08D
1730-   DF          ???
1731-   D0 D2       BNE   $1705
1733-   CE D4 A0    DEC   $A0D4
1736-   A2 20       LDX   #$20
1738-   A2 AC       LDX   #$AC
173A-   B8          CLV
173B-   C4 B8       CPY   $B8
173D-   C4 B8       CPY   $B8
173F-   C4 8D       CPY   $8D
1741-   A0 DF       LDY   #$DF
1743-   D7          ???
1744-   C1 C9       CMP   ($C9,X)
1746-   D4          ???
1747-   8D AA 8D    STA   $8DAA
174A-   A0 DF       LDY   #$DF
174C-   D0 D2       BNE   $1720
174E-   CE D4 A0    DEC   $A0D4
1751-   A2 20       LDX   #$20
1753-   A2 AC       LDX   #$AC
1755-   B8          CLV
1756-   C4 B8       CPY   $B8
1758-   C4 B8       CPY   $B8
175A-   C4 B8       CPY   $B8
175C-   C4 B8       CPY   $B8
175E-   C4 8D       CPY   $8D
1760-   A0 DF       LDY   #$DF
1762-   D0 D2       BNE   $1736
1764-   CE D4 A0    DEC   $A0D4
1767-   A2 D4       LDX   #$D4
1769-   C8          INY
176A-   C5 20       CMP   $20
176C-   D3          ???
176D-   C4 C5       CPY   $C5
176F-   CC 20 CD    CPY   $CD20
1772-   C1 C3       CMP   ($C3,X)
1774-   D2 CF       CMP   ($CF)
1776-   20 C4 C5    JSR   $C5C4
1779-   CC C5 D4    CPY   $D4C5
177C-   C5 D3       CMP   $D3
177E-   20 C1 20    JSR   $20C1
1781-   D3          ???
1782-   D5 C2       CMP   $C2,X
1784-   D3          ???
1785-   D4          ???
1786-   D2 C9       CMP   ($C9)
1788-   CE C7 A2    DEC   $A2C7
178B-   AC B8 C4    LDY   $C4B8
178E-   8D A0 DF    STA   $DFA0
1791-   D0 D2       BNE   $1765
1793-   CE D4 A0    DEC   $A0D4
1796-   A2 C6       LDX   #$C6
1798-   D2 CF       CMP   ($CF)
179A-   CD 20 D4    CMP   $D420
179D-   C8          INY
179E-   C5 20       CMP   $20
17A0-   C7          ???
17A1-   C9 D6       CMP   #$D6
17A3-   C5 CE       CMP   $CE
17A5-   20 D3 CF    JSR   $CFD3
17A8-   D5 D2       CMP   $D2,X
17AA-   C3          ???
17AB-   C5 20       CMP   $20
17AD-   D3          ???
17AE-   D4          ???
17AF-   D2 C9       CMP   ($C9)
17B1-   CE C7 AE    DEC   $AEC7
17B4-   20 CE CF    JSR   $CFCE
17B7-   D4          ???
17B8-   C5 20       CMP   $20
17BA-   A2 AC       LDX   #$AC
17BC-   B8          CLV
17BD-   C4 8D       CPY   $8D
17BF-   A0 DF       LDY   #$DF
17C1-   D0 D2       BNE   $1795
17C3-   CE D4 A0    DEC   $A0D4
17C6-   A2 D4       LDX   #$D4
17C8-   C8          INY
17C9-   C1 D4       CMP   ($D4,X)
17CB-   20 D4 C8    JSR   $C8D4
17CE-   C5 20       CMP   $20
17D0-   D3          ???
17D1-   CF          ???
17D2-   D5 D2       CMP   $D2,X
17D4-   C3          ???
17D5-   C5 20       CMP   $20
17D7-   D3          ???
17D8-   D4          ???
17D9-   D2 C9       CMP   ($C9)
17DB-   CE C7 20    DEC   $20C7
17DE-   CD D5 D3    CMP   $D3D5
17E1-   D4          ???
17E2-   20 CE CF    JSR   $CFCE
17E5-   D4          ???
17E6-   A2 AC       LDX   #$AC
17E8-   B8          CLV
17E9-   C4 8D       CPY   $8D
17EB-   A0 DF       LDY   #$DF
17ED-   D0 D2       BNE   $17C1
17EF-   CE D4 A0    DEC   $A0D4
17F2-   A2 C2       LDX   #$C2
17F4-   C5 20       CMP   $20
17F6-   C1 20       CMP   ($20,X)
17F8-   CC C9 D4    CPY   $D4C9
17FB-   C5 D2       CMP   $D2
17FD-   C1 CC       CMP   ($CC,X)
17FF-   20 C2 C5    JSR   $C5C2
1802-   C3          ???
1803-   C1 D5       CMP   ($D5,X)
1805-   D3          ???
1806-   C5 20       CMP   $20
1808-   D4          ???
1809-   C8          INY
180A-   C9 D3       CMP   #$D3
180C-   20 D2 CF    JSR   $CFD2
180F-   D5 D4       CMP   $D4,X
1811-   C9 CE       CMP   #$CE
1813-   C5 A2       CMP   $A2
1815-   AC B8 C4    LDY   $C4B8
1818-   8D A0 DF    STA   $DFA0
181B-   D0 D2       BNE   $17EF
181D-   CE D4 A0    DEC   $A0D4
1820-   A2 C1       LDX   #$C1
1822-   CC D4 C5    CPY   $C5D4
1825-   D2 D3       CMP   ($D3)
1827-   20 D4 C8    JSR   $C8D4
182A-   C5 20       CMP   $20
182C-   D3          ???
182D-   D4          ???
182E-   D2 C9       CMP   ($C9)
1830-   CE C7 20    DEC   $20C7
1833-   D0 C1       BNE   $17F6
1835-   D3          ???
1836-   D3          ???
1837-   C5 C4       CMP   $C4
1839-   20 D4 CF    JSR   $CFD4
183C-   20 C9 D4    JSR   $D4C9
183F-   AE A2 AC    LDX   $ACA2
1842-   B8          CLV
1843-   C4 B8       CPY   $B8
1845-   C4 8D       CPY   $8D
1847-   A0 DF       LDY   #$DF
1849-   D0 D2       BNE   $181D
184B-   CE D4 A0    DEC   $A0D4
184E-   A2 C9       LDX   #$C9
1850-   C6 20       DEC   $20
1852-   CC D3 D4    CPY   $D4D3
1855-   D2 20       CMP   ($20)
1857-   C8          INY
1858-   CF          ???
1859-   CC C4 D3    CPY   $D3C4
185C-   20 A7 D4    JSR   $D4A7
185F-   C8          INY
1860-   C9 D3       CMP   #$D3
1862-   20 C9 D3    JSR   $D3C9
1865-   20 C1 20    JSR   $20C1
1868-   D3          ???
1869-   D4          ???
186A-   D2 C9       CMP   ($C9)
186C-   CE C7 AE    DEC   $AEC7
186F-   A7          ???
1870-   A2 AC       LDX   #$AC
1872-   B8          CLV
1873-   C4 8D       CPY   $8D
1875-   A0 DF       LDY   #$DF
1877-   D0 D2       BNE   $184B
1879-   CE D4 A0    DEC   $A0D4
187C-   A2 D4       LDX   #$D4
187E-   C8          INY
187F-   C5 CE       CMP   $CE
1881-   20 D3 C4    JSR   $C4D3
1884-   C5 CC       CMP   $CC
1886-   20 CC D3    JSR   $D3CC
1889-   D4          ???
188A-   D2 BB       CMP   ($BB)
188C-   A3          ???
188D-   B1 BB       LDA   ($BB),Y
188F-   A3          ???
1890-   B7          ???
1891-   20 D2 C5    JSR   $C5D2
1894-   D4          ???
1895-   D5 D2       CMP   $D2,X
1897-   CE D3 BA    DEC   $BAD3
189A-   20 A2 AC    JSR   $ACA2
189D-   B8          CLV
189E-   C4 B8       CPY   $B8
18A0-   C4 8D       CPY   $8D
18A2-   A0 D3       LDY   #$D3
18A4-   C4 C5       CPY   $C5
18A6-   CC A0 A3    CPY   $A3A0
18A9-   CC D3 D4    CPY   $D4D3
18AC-   D2 BB       CMP   ($BB)
18AE-   A3          ???
18AF-   B1 BB       LDA   ($BB),Y
18B1-   A3          ???
18B2-   B7          ???
18B3-   8D A0 D3    STA   $D3A0
18B6-   D0 D2       BNE   $188A
18B8-   CE A0 A3    DEC   $A3A0
18BB-   CC D3 D4    CPY   $D4D3
18BE-   D2 8D       CMP   ($8D)
18C0-   A0 DF       LDY   #$DF
18C2-   D0 D2       BNE   $1896
18C4-   CE D4 A0    DEC   $A0D4
18C7-   A2 20       LDX   #$20
18C9-   A2 AC       LDX   #$AC
18CB-   B8          CLV
18CC-   C4 B8       CPY   $B8
18CE-   C4 B8       CPY   $B8
18D0-   C4 B8       CPY   $B8
18D2-   C4 8D       CPY   $8D
18D4-   A0 DF       LDY   #$DF
18D6-   D7          ???
18D7-   C1 C9       CMP   ($C9,X)
18D9-   D4          ???
18DA-   8D AA 8D    STA   $8DAA
18DD-   A0 DF       LDY   #$DF
18DF-   D0 D2       BNE   $18B3
18E1-   CE D4 A0    DEC   $A0D4
18E4-   A2 D4       LDX   #$D4
18E6-   C8          INY
18E7-   C5 20       CMP   $20
18E9-   D3          ???
18EA-   C9 CE       CMP   #$CE
18EC-   D3          ???
18ED-   20 CD C1    JSR   $C1CD
18F0-   C3          ???
18F1-   D2 CF       CMP   ($CF)
18F3-   20 C4 CF    JSR   $CFC4
18F6-   C5 D3       CMP   $D3
18F8-   20 D4 C8    JSR   $C8D4
18FB-   C5 20       CMP   $20
18FD-   A2 AC       LDX   #$AC
18FF-   B8          CLV
1900-   C4 8D       CPY   $8D
1902-   A0 DF       LDY   #$DF
1904-   D0 D2       BNE   $18D8
1906-   CE D4 A0    DEC   $A0D4
1909-   A2 CF       LDX   #$CF
190B-   D0 D0       BNE   $18DD
190D-   CF          ???
190E-   D3          ???
190F-   C9 D4       CMP   #$D4
1911-   C5 20       CMP   $20
1913-   CF          ???
1914-   C6 20       DEC   $20
1916-   D3          ???
1917-   C4 C5       CPY   $C5
1919-   CC BA 20    CPY   $20BA
191C-   C9 D4       CMP   #$D4
191E-   20 C9 CE    JSR   $CEC9
1921-   D3          ???
1922-   C5 D2       CMP   $D2
1924-   D4          ???
1925-   D3          ???
1926-   A2 AC       LDX   #$AC
1928-   B8          CLV
1929-   C4 8D       CPY   $8D
192B-   A0 DF       LDY   #$DF
192D-   D0 D2       BNE   $1901
192F-   CE D4 A0    DEC   $A0D4
1932-   A2 C1       LDX   #$C1
1934-   20 D3 D5    JSR   $D5D3
1937-   C2          ???
1938-   D3          ???
1939-   D4          ???
193A-   D2 C9       CMP   ($C9)
193C-   CE C7 20    DEC   $20C7
193F-   C9 CE       CMP   #$CE
1941-   D4          ???
1942-   CF          ???
1943-   20 C1 20    JSR   $20C1
1946-   D0 C1       BNE   $1909
1948-   D2 C5       CMP   ($C5)
194A-   CE D4 20    DEC   $20D4
194D-   D3          ???
194E-   D4          ???
194F-   D2 C9       CMP   ($C9)
1951-   CE C7 A2    DEC   $A2C7
1954-   AC B8 C4    LDY   $C4B8
1957-   8D A0 DF    STA   $DFA0
195A-   D0 D2       BNE   $192E
195C-   CE D4 A0    DEC   $A0D4
195F-   A2 C1       LDX   #$C1
1961-   D4          ???
1962-   20 D4 C8    JSR   $C8D4
1965-   C5 20       CMP   $20
1967-   C7          ???
1968-   C9 D6       CMP   #$D6
196A-   C5 CE       CMP   $CE
196C-   20 C9 CE    JSR   $CEC9
196F-   C4 C5       CPY   $C5
1971-   D8          CLD
1972-   AE 20 CE    LDX   $CE20
1975-   CF          ???
1976-   D4          ???
1977-   C5 20       CMP   $20
1979-   D4          ???
197A-   C8          INY
197B-   C1 D4       CMP   ($D4,X)
197D-   A2 AC       LDX   #$AC
197F-   B8          CLV
1980-   C4 8D       CPY   $8D
1982-   A0 DF       LDY   #$DF
1984-   D0 D2       BNE   $1958
1986-   CE D4 A0    DEC   $A0D4
1989-   A2 D7       LDX   #$D7
198B-   C8          INY
198C-   C9 CC       CMP   #$CC
198E-   C5 20       CMP   $20
1990-   D4          ???
1991-   C8          INY
1992-   C5 20       CMP   $20
1994-   D0 C1       BNE   $1957
1996-   D2 C5       CMP   ($C5)
1998-   CE D4 20    DEC   $20D4
199B-   D3          ???
199C-   D4          ???
199D-   D2 C9       CMP   ($C9)
199F-   CE C7 20    DEC   $20C7
19A2-   C3          ???
19A3-   C1 CE       CMP   ($CE,X)
19A5-   CE CF D4    DEC   $D4CF
19A8-   20 C2 C5    JSR   $C5C2
19AB-   20 A2 AC    JSR   $ACA2
19AE-   B8          CLV
19AF-   C4 8D       CPY   $8D
19B1-   A0 DF       LDY   #$DF
19B3-   D0 D2       BNE   $1987
19B5-   CE D4 A0    DEC   $A0D4
19B8-   A2 C1       LDX   #$C1
19BA-   20 CC C9    JSR   $C9CC
19BD-   D4          ???
19BE-   C5 D2       CMP   $D2
19C0-   C1 CC       CMP   ($CC,X)
19C2-   AC 20 D4    LDY   $D420
19C5-   C8          INY
19C6-   C5 20       CMP   $20
19C8-   D3          ???
19C9-   D5 C2       CMP   $C2,X
19CB-   D3          ???
19CC-   D4          ???
19CD-   D2 C9       CMP   ($C9)
19CF-   CE C7 20    DEC   $20C7
19D2-   C9 D4       CMP   #$D4
19D4-   D3          ???
19D5-   C5 CC       CMP   $CC
19D7-   C6 20       DEC   $20
19D9-   C3          ???
19DA-   C1 CE       CMP   ($CE,X)
19DC-   20 C2 C5    JSR   $C5C2
19DF-   AE A2 AC    LDX   $ACA2
19E2-   B8          CLV
19E3-   C4 B8       CPY   $B8
19E5-   C4 8D       CPY   $8D
19E7-   A0 DF       LDY   #$DF
19E9-   D0 D2       BNE   $19BD
19EB-   CE D4 A0    DEC   $A0D4
19EE-   A2 D4       LDX   #$D4
19F0-   C8          INY
19F1-   D5 D3       CMP   $D3,X
19F3-   20 D3 C9    JSR   $C9D3
19F6-   CE D3 20    DEC   $20D3
19F9-   CC D3 D4    CPY   $D4D3
19FC-   D2 BB       CMP   ($BB)
19FE-   A3          ???
19FF-   B1 BB       LDA   ($BB),Y
1A01-   A3          ???
1A02-   B5 B0       LDA   $B0,X
1A04-   BB          ???
1A05-   A7          ???
1A06-   D4          ???
1A07-   C8          INY
1A08-   C9 D3       CMP   #$D3
1A0A-   20 C9 D3    JSR   $D3C9
1A0D-   20 CE CF    JSR   $CFCE
1A10-   D4          ???
1A11-   A7          ???
1A12-   A2 AC       LDX   #$AC
1A14-   B8          CLV
1A15-   C4 8D       CPY   $8D
1A17-   A0 DF       LDY   #$DF
1A19-   D0 D2       BNE   $19ED
1A1B-   CE D4 A0    DEC   $A0D4
1A1E-   A2 D2       LDX   #$D2
1A20-   C5 D4       CMP   $D4
1A22-   D5 D2       CMP   $D2,X
1A24-   CE D3 BA    DEC   $BAD3
1A27-   20 A2 AC    JSR   $ACA2
1A2A-   B8          CLV
1A2B-   C4 8D       CPY   $8D
1A2D-   A0 D3       LDY   #$D3
1A2F-   C9 CE       CMP   #$CE
1A31-   D3          ???
1A32-   A0 A3       LDY   #$A3
1A34-   CC D3 D4    CPY   $D4D3
1A37-   D2 BB       CMP   ($BB)
1A39-   A3          ???
1A3A-   B1 BB       LDA   ($BB),Y
1A3C-   A3          ???
1A3D-   B5 B0       LDA   $B0,X
1A3F-   BB          ???
1A40-   A2 D4       LDX   #$D4
1A42-   C8          INY
1A43-   C9 D3       CMP   #$D3
1A45-   A0 C9       LDY   #$C9
1A47-   D3          ???
1A48-   A0 CE       LDY   #$CE
1A4A-   CF          ???
1A4B-   D4          ???
1A4C-   A2 8D       LDX   #$8D
1A4E-   A0 D3       LDY   #$D3
1A50-   D0 D2       BNE   $1A24
1A52-   CE A0 A3    DEC   $A3A0
1A55-   CC D3 D4    CPY   $D4D3
1A58-   D2 8D       CMP   ($8D)
1A5A-   A0 DF       LDY   #$DF
1A5C-   D0 D2       BNE   $1A30
1A5E-   CE D4 A0    DEC   $A0D4
1A61-   A2 20       LDX   #$20
1A63-   A2 AC       LDX   #$AC
1A65-   B8          CLV
1A66-   C4 B8       CPY   $B8
1A68-   C4 B8       CPY   $B8
1A6A-   C4 B8       CPY   $B8
1A6C-   C4 8D       CPY   $8D
1A6E-   A0 DF       LDY   #$DF
1A70-   D7          ???
1A71-   C1 C9       CMP   ($C9,X)
1A73-   D4          ???
1A74-   8D AA 8D    STA   $8DAA
1A77-   A0 CA       LDY   #$CA
1A79-   CD D0 A0    CMP   $A0D0
1A7C-   D2 C5       CMP   ($C5)
1A7E-   C5 CE       CMP   $CE
1A80-   D4          ???
1A81-   D2 D9       CMP   ($D9)
1A83-   8D AA 8D    STA   $8DAA
1A86-   C1 D3       CMP   ($D3,X)
1A88-   D4          ???
1A89-   D2 A0       CMP   ($A0)
1A8B-   D3          ???
1A8C-   D4          ???
1A8D-   D2 A0       CMP   ($A0)
1A8F-   A2 C1       LDX   #$C1
1A91-   A2 8D       LDX   #$8D
1A93-   C2          ???
1A94-   D3          ???
1A95-   D4          ???
1A96-   D2 A0       CMP   ($A0)
1A98-   D3          ???
1A99-   D4          ???
1A9A-   D2 A0       CMP   ($A0)
1A9C-   A2 C2       LDX   #$C2
1A9E-   A2 8D       LDX   #$8D
1AA0-   CC D3 D4    CPY   $D4D3
1AA3-   D2 A0       CMP   ($A0)
1AA5-   D3          ???
1AA6-   D4          ???
1AA7-   D2 A0       CMP   ($A0)
1AA9-   A2 D4       LDX   #$D4
1AAB-   C8          INY
1AAC-   C9 D3       CMP   #$D3
1AAE-   20 C9 D3    JSR   $D3C9
1AB1-   20 C1 20    JSR   $20C1
1AB4-   D3          ???
1AB5-   D4          ???
1AB6-   D2 C9       CMP   ($C9)
1AB8-   CE C7 AE    DEC   $AEC7
1ABB-   A2 8D       LDX   #$8D
1ABD-   AA          TAX
1ABE-   8D AA E0    STA   $E0AA
1AC1-   E0 E0       CPX   #$E0
1AC3-   E0 E0       CPX   #$E0
1AC5-   E0 E0       CPX   #$E0
1AC7-   E0 E0       CPX   #$E0
1AC9-   E0 E0       CPX   #$E0
1ACB-   E0 E0       CPX   #$E0
1ACD-   E0 E0       CPX   #$E0
1ACF-   E0 E0       CPX   #$E0
1AD1-   E0 E0       CPX   #$E0
1AD3-   E0 E0       CPX   #$E0
1AD5-   E0 E0       CPX   #$E0
1AD7-   E0 E0       CPX   #$E0
1AD9-   E0 E0       CPX   #$E0
1ADB-   E0 E0       CPX   #$E0
1ADD-   E0 AA       CPX   #$AA
1ADF-   8D AA 20    STA   $20AA
1AE2-   20 20 20    JSR   $2020
1AE5-   20 20 20    JSR   $2020
1AE8-   20 C2 CF    JSR   $CFC2
1AEB-   D4          ???
1AEC-   D4          ???
1AED-   CF          ???
1AEE-   CD 20 C9    CMP   $C920
1AF1-   CE C3 CC    DEC   $CCC3
1AF4-   D5 C4       CMP   $C4,X
1AF6-   C5 D3       CMP   $D3
1AF8-   20 20 20    JSR   $2020
1AFB-   20 20 20    JSR   $2020
1AFE-   20 AA 8D    JSR   $8DAA
1B01-   AA          TAX
1B02-   AC AC AC    LDY   $ACAC
1B05-   AC AC AC    LDY   $ACAC
1B08-   AC AC AC    LDY   $ACAC
1B0B-   AC AC AC    LDY   $ACAC
1B0E-   AC AC AC    LDY   $ACAC
1B11-   AC AC AC    LDY   $ACAC
1B14-   AC AC AC    LDY   $ACAC
1B17-   AC AC AC    LDY   $ACAC
1B1A-   AC AC AC    LDY   $ACAC
1B1D-   AC AC AC    LDY   $ACAC
1B20-   AA          TAX
1B21-   8D AA 8D    STA   $8DAA
1B24-   AA          TAX
1B25-   AA          TAX
1B26-   20 C2 CF    JSR   $CFC2
1B29-   D4          ???
1B2A-   D4          ???
1B2B-   CF          ???
1B2C-   CD 20 C9    CMP   $C920
1B2F-   CE C3 CC    DEC   $CCC3
1B32-   D5 C4       CMP   $C4,X
1B34-   C5 D3       CMP   $D3
1B36-   8D AA 8D    STA   $8DAA
1B39-   A0 D0       LDY   #$D0
1B3B-   D5 D4       CMP   $D4,X
1B3D-   A0 CD       LDY   #$CD
1B3F-   C9 CE       CMP   #$CE
1B41-   AE CC C9    LDX   $C9CC
1B44-   C2          ???
1B45-   AE D2 C5    LDX   $C5D2
1B48-   D1 D5       CMP   ($D5),Y
1B4A-   C9 D2       CMP   #$D2
1B4C-   C5 C4       CMP   $C4
1B4E-   8D AA 8D    STA   $8DAA
1B51-   AA          TAX
1B52-   AA          TAX
1B53-   20 C9 CE    JSR   $CEC9
1B56-   C4 C9       CPY   $C9
1B58-   D6 C9       DEC   $C9,X
1B5A-   C4 D5       CPY   $D5
1B5C-   C1 CC       CMP   ($CC,X)
1B5E-   20 D3 D5    JSR   $D5D3
1B61-   C2          ???
1B62-   D2 CF       CMP   ($CF)
1B64-   D5 D4       CMP   $D4,X
1B66-   C9 CE       CMP   #$CE
1B68-   C5 20       CMP   $20
1B6A-   C9 CE       CMP   #$CE
1B6C-   C3          ???
1B6D-   CC D5 C4    CPY   $C4D5
1B70-   C5 D3       CMP   $D3
1B72-   8D AA 8D    STA   $8DAA
1B75-   AA          TAX
1B76-   AA          TAX
1B77-   20 D3 D4    JSR   $D4D3
1B7A-   D2 C9       CMP   ($C9)
1B7C-   CE C7 20    DEC   $20C7
1B7F-   D3          ???
1B80-   D5 C2       CMP   $C2,X
1B82-   D2 CF       CMP   ($CF)
1B84-   D5 D4       CMP   $D4,X
1B86-   C9 CE       CMP   #$CE
1B88-   C5 D3       CMP   $D3
1B8A-   8D AA 8D    STA   $8DAA
1B8D-   A0 D0       LDY   #$D0
1B8F-   D5 D4       CMP   $D4,X
1B91-   A0 CD       LDY   #$CD
1B93-   C9 CE       CMP   #$CE
1B95-   AE D3 D5    LDX   $D5D3
1B98-   C2          ???
1B99-   AE D0 D2    LDX   $D2D0
1B9C-   CE D3 D4    DEC   $D4D3
1B9F-   D2 8D       CMP   ($8D)
1BA1-   A0 D0       LDY   #$D0
1BA3-   D5 D4       CMP   $D4,X
1BA5-   A0 CD       LDY   #$CD
1BA7-   C9 CE       CMP   #$CE
1BA9-   AE D3 D5    LDX   $D5D3
1BAC-   C2          ???
1BAD-   AE D3 D4    LDX   $D4D3
1BB0-   D2 C3       CMP   ($C3)
1BB2-   C1 D4       CMP   ($D4,X)
1BB4-   8D A0 D0    STA   $D0A0
1BB7-   D5 D4       CMP   $D4,X
1BB9-   A0 CD       LDY   #$CD
1BBB-   C9 CE       CMP   #$CE
1BBD-   AE D3 D5    LDX   $D5D3
1BC0-   C2          ???
1BC1-   AE D3 D4    LDX   $D4D3
1BC4-   D2 C3       CMP   ($C3)
1BC6-   CF          ???
1BC7-   CD D0 8D    CMP   $8DD0
1BCA-   AA          TAX
1BCB-   8D AA AA    STA   $AAAA
1BCE-   20 D3 D5    JSR   $D5D3
1BD1-   C2          ???
1BD2-   D3          ???
1BD3-   D4          ???
1BD4-   D2 C9       CMP   ($C9)
1BD6-   CE C7 20    DEC   $20C7
1BD9-   D3          ???
1BDA-   D5 C2       CMP   $C2,X
1BDC-   D2 CF       CMP   ($CF)
1BDE-   D5 D4       CMP   $D4,X
1BE0-   C9 CE       CMP   #$CE
1BE2-   C5 D3       CMP   $D3
1BE4-   8D AA 8D    STA   $8DAA
1BE7-   A0 D0       LDY   #$D0
1BE9-   D5 D4       CMP   $D4,X
1BEB-   A0 CD       LDY   #$CD
1BED-   C9 CE       CMP   #$CE
1BEF-   AE D3 D5    LDX   $D5D3
1BF2-   C2          ???
1BF3-   AE D3 D5    LDX   $D5D3
1BF6-   C2          ???
1BF7-   C3          ???
1BF8-   CF          ???
1BF9-   D0 D9       BNE   $1BD4
1BFB-   8D A0 D0    STA   $D0A0
1BFE-   D5 D4       CMP   $D4,X
1C00-   A0 CD       LDY   #$CD
1C02-   C9 CE       CMP   #$CE
1C04-   AE D3 D5    LDX   $D5D3
1C07-   C2          ???
1C08-   AE D3 D5    LDX   $D5D3
1C0B-   C2          ???
1C0C-   C4 C5       CPY   $C5
1C0E-   CC 8D A0    CPY   $A08D
1C11-   D0 D5       BNE   $1BE8
1C13-   D4          ???
1C14-   A0 CD       LDY   #$CD
1C16-   C9 CE       CMP   #$CE
1C18-   AE D3 D5    LDX   $D5D3
1C1B-   C2          ???
1C1C-   AE D3 D5    LDX   $D5D3
1C1F-   C2          ???
1C20-   C9 CE       CMP   #$CE
1C22-   D3          ???
1C23-   8D A0 D0    STA   $D0A0
1C26-   D5 D4       CMP   $D4,X
1C28-   A0 CD       LDY   #$CD
1C2A-   C9 CE       CMP   #$CE
1C2C-   AE D3 D5    LDX   $D5D3
1C2F-   C2          ???
1C30-   AE D3 D5    LDX   $D5D3
1C33-   C2          ???
1C34-   D0 CF       BNE   $1C05
1C36-   D3          ???
1C37-   8D AA 8D    STA   $8DAA
