0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C1    LDY   $C120,X
0950-   D2 D2       CMP   ($D2)
0952-   C1 D9       CMP   ($D9,X)
0954-   D3          ???
0955-   20 C4 C5    JSR   $C5C4
0958-   CD CF 20    CMP   $20CF
095B-   BE AD 20    LDX   $20AD,Y
095E-   20 20 20    JSR   $2020
0961-   20 20 20    JSR   $2020
0964-   AA          TAX
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B2       BCS   $094E
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B1    JSR   $B120
09D4-   B2 AD       LDA   ($AD)
09D6-   C4 C5       CPY   $C5
09D8-   C3          ???
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B8       LDA   ($B8),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 C4    STA   $C4A0
0B02-   D3          ???
0B03-   CB          ???
0B04-   A0 C1       LDY   #$C1
0B06-   D2 D2       CMP   ($D2)
0B08-   C1 D9       CMP   ($D9,X)
0B0A-   D3          ???
0B0B-   AE C4 C5    LDX   $C5C4
0B0E-   CD CF 8D    CMP   $8DCF
0B11-   A0 CF       LDY   #$CF
0B13-   C2          ???
0B14-   CA          DEX
0B15-   A0 A4       LDY   #$A4
0B17-   C2          ???
0B18-   C6 C5       DEC   $C5
0B1A-   B0 8D       BCS   $0AA9
0B1C-   A0 CF       LDY   #$CF
0B1E-   D2 C7       CMP   ($C7)
0B20-   A0 A4       LDY   #$A4
0B22-   B6 B0       LDX   $B0,Y
0B24-   B0 B0       BCS   $0AD6
0B26-   8D AA 8D    STA   $8DAA
0B29-   AA          TAX
0B2A-   E0 E0       CPX   #$E0
0B2C-   E0 E0       CPX   #$E0
0B2E-   E0 E0       CPX   #$E0
0B30-   E0 E0       CPX   #$E0
0B32-   E0 E0       CPX   #$E0
0B34-   E0 E0       CPX   #$E0
0B36-   E0 E0       CPX   #$E0
0B38-   E0 E0       CPX   #$E0
0B3A-   E0 E0       CPX   #$E0
0B3C-   E0 E0       CPX   #$E0
0B3E-   E0 E0       CPX   #$E0
0B40-   E0 E0       CPX   #$E0
0B42-   E0 E0       CPX   #$E0
0B44-   E0 E0       CPX   #$E0
0B46-   E0 E0       CPX   #$E0
0B48-   AA          TAX
0B49-   8D AA 20    STA   $20AA
0B4C-   20 D4 CF    JSR   $CFD4
0B4F-   D0 20       BNE   $0B71
0B51-   C9 CE       CMP   #$CE
0B53-   C3          ???
0B54-   CC D5 C4    CPY   $C4D5
0B57-   C5 D3       CMP   $D3
0B59-   20 A8 C8    JSR   $C8A8
0B5C-   CF          ???
0B5D-   CF          ???
0B5E-   CB          ???
0B5F-   D3          ???
0B60-   AC CD C1    LDY   $C1CD
0B63-   C3          ???
0B64-   D2 CF       CMP   ($CF)
0B66-   D3          ???
0B67-   A9 20       LDA   #$20
0B69-   AA          TAX
0B6A-   8D AA AC    STA   $ACAA
0B6D-   AC AC AC    LDY   $ACAC
0B70-   AC AC AC    LDY   $ACAC
0B73-   AC AC AC    LDY   $ACAC
0B76-   AC AC AC    LDY   $ACAC
0B79-   AC AC AC    LDY   $ACAC
0B7C-   AC AC AC    LDY   $ACAC
0B7F-   AC AC AC    LDY   $ACAC
0B82-   AC AC AC    LDY   $ACAC
0B85-   AC AC AC    LDY   $ACAC
0B88-   AC AC AA    LDY   $AAAC
0B8B-   8D AA 8D    STA   $8DAA
0B8E-   A0 D0       LDY   #$D0
0B90-   D5 D4       CMP   $D4,X
0B92-   A0 D2       LDY   #$D2
0B94-   C5 D1       CMP   $D1
0B96-   D5 C9       CMP   $C9,X
0B98-   D2 C5       CMP   ($C5)
0B9A-   C4 AE       CPY   $AE
0B9C-   C8          INY
0B9D-   CF          ???
0B9E-   CF          ???
0B9F-   CB          ???
0BA0-   D3          ???
0BA1-   8D A0 D5    STA   $D5A0
0BA4-   D3          ???
0BA5-   C5 A0       CMP   $A0
0BA7-   D2 C5       CMP   ($C5)
0BA9-   D1 D5       CMP   ($D5),Y
0BAB-   C9 D2       CMP   #$D2
0BAD-   C5 C4       CMP   $C4
0BAF-   AE CD C1    LDX   $C1CD
0BB2-   C3          ???
0BB3-   8D A0 D5    STA   $D5A0
0BB6-   D3          ???
0BB7-   C5 A0       CMP   $A0
0BB9-   C1 D2       CMP   ($D2,X)
0BBB-   D2 C1       CMP   ($C1)
0BBD-   D9 D3 AE    CMP   $AED3,Y
0BC0-   CD C1 C3    CMP   $C3C1
0BC3-   8D A0 D0    STA   $D0A0
0BC6-   D5 D4       CMP   $D4,X
0BC8-   A0 C1       LDY   #$C1
0BCA-   D2 D2       CMP   ($D2)
0BCC-   C1 D9       CMP   ($D9,X)
0BCE-   D3          ???
0BCF-   AE C8 CF    LDX   $CFC8
0BD2-   CF          ???
0BD3-   CB          ???
0BD4-   D3          ???
0BD5-   8D AA 8D    STA   $8DAA
0BD8-   AA          TAX
0BD9-   E0 E0       CPX   #$E0
0BDB-   E0 E0       CPX   #$E0
0BDD-   E0 E0       CPX   #$E0
0BDF-   E0 E0       CPX   #$E0
0BE1-   E0 E0       CPX   #$E0
0BE3-   E0 E0       CPX   #$E0
0BE5-   E0 E0       CPX   #$E0
0BE7-   E0 E0       CPX   #$E0
0BE9-   E0 E0       CPX   #$E0
0BEB-   E0 E0       CPX   #$E0
0BED-   E0 E0       CPX   #$E0
0BEF-   E0 E0       CPX   #$E0
0BF1-   E0 E0       CPX   #$E0
0BF3-   E0 E0       CPX   #$E0
0BF5-   E0 E0       CPX   #$E0
0BF7-   AA          TAX
0BF8-   8D AA 20    STA   $20AA
0BFB-   20 20 20    JSR   $2020
0BFE-   20 20 D0    JSR   $D020
0C01-   D2 CF       CMP   ($CF)
0C03-   C7          ???
0C04-   D2 C1       CMP   ($C1)
0C06-   CD 20 CD    CMP   $CD20
0C09-   C1 C9       CMP   ($C9,X)
0C0B-   CE 20 C2    DEC   $C220
0C0E-   CF          ???
0C0F-   C4 D9       CPY   $D9
0C11-   20 20 20    JSR   $2020
0C14-   20 20 20    JSR   $2020
0C17-   20 AA 8D    JSR   $8DAA
0C1A-   AA          TAX
0C1B-   AC AC AC    LDY   $ACAC
0C1E-   AC AC AC    LDY   $ACAC
0C21-   AC AC AC    LDY   $ACAC
0C24-   AC AC AC    LDY   $ACAC
0C27-   AC AC AC    LDY   $ACAC
0C2A-   AC AC AC    LDY   $ACAC
0C2D-   AC AC AC    LDY   $ACAC
0C30-   AC AC AC    LDY   $ACAC
0C33-   AC AC AC    LDY   $ACAC
0C36-   AC AC AC    LDY   $ACAC
0C39-   AA          TAX
0C3A-   8D AA 8D    STA   $8DAA
0C3D-   C1 D2       CMP   ($D2,X)
0C3F-   D2 C1       CMP   ($C1)
0C41-   D9 B1 A0    CMP   $A0B1,Y
0C44-   C5 D1       CMP   $D1
0C46-   D5 A0       CMP   $A0,X
0C48-   A4 B3       LDY   $B3
0C4A-   B0 B0       BCS   $0BFC
0C4C-   8D C1 D2    STA   $D2C1
0C4F-   D2 C1       CMP   ($C1)
0C51-   D9 B2 A0    CMP   $A0B2,Y
0C54-   C5 D1       CMP   $D1
0C56-   D5 A0       CMP   $A0,X
0C58-   A4 B4       LDY   $B4
0C5A-   B0 B0       BCS   $0C0C
0C5C-   B0 8D       BCS   $0BEB
0C5E-   AA          TAX
0C5F-   8D AA AA    STA   $AAAA
0C62-   20 C4 C9    JSR   $C9C4
0C65-   CD B8 B1    CMP   $B1B8
0C68-   20 C3 CC    JSR   $CCC3
0C6B-   C5 C1       CMP   $C1
0C6D-   D2 D3       CMP   ($D3)
0C6F-   20 D4 C8    JSR   $C8D4
0C72-   C5 20       CMP   $20
0C74-   CD C5 CD    CMP   $CDC5
0C77-   CF          ???
0C78-   D2 D9       CMP   ($D9)
0C7A-   20 C1 D4    JSR   $D4C1
0C7D-   20 D4 C8    JSR   $C8D4
0C80-   C5 20       CMP   $20
0C82-   D3          ???
0C83-   D0 C5       BNE   $0C4A
0C85-   C3          ???
0C86-   C9 C6       CMP   #$C6
0C88-   C9 C5       CMP   #$C5
0C8A-   C4 8D       CPY   $8D
0C8C-   AA          TAX
0C8D-   AA          TAX
0C8E-   20 CC CF    JSR   $CFCC
0C91-   C3          ???
0C92-   C1 D4       CMP   ($D4,X)
0C94-   C9 CF       CMP   #$CF
0C96-   CE 20 C1    DEC   $C120
0C99-   CE C4 20    DEC   $20C4
0C9C-   D3          ???
0C9D-   C5 D4       CMP   $D4
0C9F-   D3          ???
0CA0-   20 D5 D0    JSR   $D0D5
0CA3-   20 D4 C8    JSR   $C8D4
0CA6-   C5 20       CMP   $20
0CA8-   C4 C1       CPY   $C1
0CAA-   D4          ???
0CAB-   C1 20       CMP   ($20,X)
0CAD-   C3          ???
0CAE-   CF          ???
0CAF-   CE C6 C9    DEC   $C9C6
0CB2-   C7          ???
0CB3-   D5 D2       CMP   $D2,X
0CB5-   C1 D4       CMP   ($D4,X)
0CB7-   C9 CF       CMP   #$CF
0CB9-   CE 8D AA    DEC   $AA8D
0CBC-   AA          TAX
0CBD-   20 C6 CF    JSR   $CFC6
0CC0-   D2 20       CMP   ($20)
0CC2-   C1 20       CMP   ($20,X)
0CC4-   B1 C4       LDA   ($C4),Y
0CC6-   20 C1 D2    JSR   $D2C1
0CC9-   D2 C1       CMP   ($C1)
0CCB-   D9 20 A8    CMP   $A820,Y
0CCE-   C1 D2       CMP   ($D2,X)
0CD0-   D2 C1       CMP   ($C1)
0CD2-   D9 20 CC    CMP   $CC20,Y
0CD5-   C5 CE       CMP   $CE
0CD7-   C7          ???
0CD8-   D4          ???
0CD9-   C8          INY
0CDA-   AC 20 C5    LDY   $C520
0CDD-   CC C5 CD    CPY   $CDC5
0CE0-   C5 CE       CMP   $CE
0CE2-   D4          ???
0CE3-   20 CC C5    JSR   $C5CC
0CE6-   CE C7 D4    DEC   $D4C7
0CE9-   C8          INY
0CEA-   AC 20 C4    LDY   $C420
0CED-   C1 D4       CMP   ($D4,X)
0CEF-   C1 A9       CMP   ($A9,X)
0CF1-   8D AA 8D    STA   $8DAA
0CF4-   AA          TAX
0CF5-   AA          TAX
0CF6-   20 CD C1    JSR   $C1CD
0CF9-   C3          ???
0CFA-   D2 CF       CMP   ($CF)
0CFC-   BA          TSX
0CFD-   20 C4 C9    JSR   $C9C4
0D00-   CD B8 B1    CMP   $B1B8
0D03-   20 C1 C4    JSR   $C4C1
0D06-   C4 D2       CPY   $D2
0D08-   C5 D3       CMP   $D3
0D0A-   D3          ???
0D0B-   BB          ???
0D0C-   C1 D2       CMP   ($D2,X)
0D0E-   D2 C1       CMP   ($C1)
0D10-   D9 DF D3    CMP   $D3DF,Y
0D13-   C9 DA       CMP   #$DA
0D15-   C5 BB       CMP   $BB
0D17-   C5 CC       CMP   $CC
0D19-   C5 CD       CMP   $CD
0D1B-   C5 CE       CMP   $CE
0D1D-   D4          ???
0D1E-   DF          ???
0D1F-   CC C5 CE    CPY   $CEC5
0D22-   C7          ???
0D23-   D4          ???
0D24-   C8          INY
0D25-   8D AA 8D    STA   $8DAA
0D28-   A0 CC       LDY   #$CC
0D2A-   C4 C1       CPY   $C1
0D2C-   A0 A3       LDY   #$A3
0D2E-   BE C1 D2    LDX   $D2C1,Y
0D31-   D2 C1       CMP   ($C1)
0D33-   D9 B1 A0    CMP   $A0B1,Y
0D36-   BB          ???
0D37-   20 C8 C9    JSR   $C9C8
0D3A-   C7          ???
0D3B-   C8          INY
0D3C-   20 CC CF    JSR   $CFCC
0D3F-   C3          ???
0D40-   C1 D4       CMP   ($D4,X)
0D42-   C9 CF       CMP   #$CF
0D44-   CE 20 C6    DEC   $C620
0D47-   CF          ???
0D48-   D2 20       CMP   ($20)
0D4A-   C1 D2       CMP   ($D2,X)
0D4C-   D2 C1       CMP   ($C1)
0D4E-   D9 8D A0    CMP   $A08D,Y
0D51-   D0 C8       BNE   $0D1B
0D53-   C1 8D       CMP   ($8D,X)
0D55-   A0 CC       LDY   #$CC
0D57-   C4 C1       CPY   $C1
0D59-   A0 A3       LDY   #$A3
0D5B-   BC C1 D2    LDY   $D2C1,X
0D5E-   D2 C1       CMP   ($C1)
0D60-   D9 B1 A0    CMP   $A0B1,Y
0D63-   BB          ???
0D64-   20 CC CF    JSR   $CFCC
0D67-   D7          ???
0D68-   20 CC CF    JSR   $CFCC
0D6B-   C3          ???
0D6C-   C1 D4       CMP   ($D4,X)
0D6E-   C9 CF       CMP   #$CF
0D70-   CE 8D A0    DEC   $A08D
0D73-   D0 C8       BNE   $0D3D
0D75-   C1 8D       CMP   ($8D,X)
0D77-   A0 CC       LDY   #$CC
0D79-   C4 C1       CPY   $C1
0D7B-   A0 A3       LDY   #$A3
0D7D-   B0 B6       BCS   $0D35
0D7F-   A0 BB       LDY   #$BB
0D81-   20 C1 D2    JSR   $D2C1
0D84-   D2 C1       CMP   ($C1)
0D86-   D9 20 CC    CMP   $CC20,Y
0D89-   C5 CE       CMP   $CE
0D8B-   C7          ???
0D8C-   D4          ???
0D8D-   C8          INY
0D8E-   8D A0 D0    STA   $D0A0
0D91-   C8          INY
0D92-   C1 8D       CMP   ($8D,X)
0D94-   A0 CC       LDY   #$CC
0D96-   C4 C1       CPY   $C1
0D98-   A0 A3       LDY   #$A3
0D9A-   B2 A0       LDA   ($A0)
0D9C-   BB          ???
0D9D-   20 C5 CC    JSR   $CCC5
0DA0-   C5 CD       CMP   $CD
0DA2-   C5 CE       CMP   $CE
0DA4-   D4          ???
0DA5-   20 CC C5    JSR   $C5CC
0DA8-   CE C7 D4    DEC   $D4C7
0DAB-   C8          INY
0DAC-   8D A0 D0    STA   $D0A0
0DAF-   C8          INY
0DB0-   C1 8D       CMP   ($8D,X)
0DB2-   A0 CA       LDY   #$CA
0DB4-   D3          ???
0DB5-   D2 A0       CMP   ($A0)
0DB7-   C1 C4       CMP   ($C4,X)
0DB9-   C9 CD       CMP   #$CD
0DBB-   B8          CLV
0DBC-   B1 8D       LDA   ($8D),Y
0DBE-   AA          TAX
0DBF-   8D AA AA    STA   $AAAA
0DC2-   20 CE CF    JSR   $CFCE
0DC5-   D7          ???
0DC6-   20 C3 C8    JSR   $C8C3
0DC9-   C5 C3       CMP   $C3
0DCB-   CB          ???
0DCC-   20 A4 B3    JSR   $B3A4
0DCF-   B0 B0       BCS   $0D81
0DD1-   20 D4 CF    JSR   $CFD4
0DD4-   20 D3 C5    JSR   $C5D3
0DD7-   C5 20       CMP   $20
0DD9-   D2 C5       CMP   ($C5)
0DDB-   D3          ???
0DDC-   D5 CC       CMP   $CC,X
0DDE-   D4          ???
0DDF-   8D AA 8D    STA   $8DAA
0DE2-   A0 CA       LDY   #$CA
0DE4-   D3          ???
0DE5-   D2 A0       CMP   ($A0)
0DE7-   DF          ???
0DE8-   DF          ???
0DE9-   D0 8D       BNE   $0D78
0DEB-   A0 C8       LDY   #$C8
0DED-   C5 D8       CMP   $D8
0DEF-   A0 B8       LDY   #$B8
0DF1-   C4 B8       CPY   $B8
0DF3-   C4 8D       CPY   $8D
0DF5-   A0 C1       LDY   #$C1
0DF7-   D3          ???
0DF8-   C3          ???
0DF9-   A0 A2       LDY   #$A2
0DFB-   B1 AD       LDA   ($AD),Y
0DFD-   C4 C9       CPY   $C9
0DFF-   CD C5 CE    CMP   $CEC5
0E02-   D3          ???
0E03-   C9 CF       CMP   #$CF
0E05-   CE C1 CC    DEC   $CCC1
0E08-   20 C1 D2    JSR   $D2C1
0E0B-   D2 C1       CMP   ($C1)
0E0D-   D9 20 C1    CMP   $C120,Y
0E10-   C6 D4       DEC   $D4
0E12-   C5 D2       CMP   $D2
0E14-   20 C9 CE    JSR   $CEC9
0E17-   C9 D4       CMP   #$D4
0E19-   C9 C1       CMP   #$C1
0E1B-   CC C9 DA    CPY   $DAC9
0E1E-   C9 CE       CMP   #$CE
0E20-   C7          ???
0E21-   A2 8D       LDX   #$8D
0E23-   A0 C8       LDY   #$C8
0E25-   C5 D8       CMP   $D8
0E27-   A0 B8       LDY   #$B8
0E29-   C4 B8       CPY   $B8
0E2B-   C4 8D       CPY   $8D
0E2D-   A0 C1       LDY   #$C1
0E2F-   D3          ???
0E30-   C3          ???
0E31-   A0 A2       LDY   #$A2
0E33-   20 20 20    JSR   $2020
0E36-   20 20 20    JSR   $2020
0E39-   20 20 20    JSR   $2020
0E3C-   20 20 20    JSR   $2020
0E3F-   A2 8D       LDX   #$8D
0E41-   A0 C1       LDY   #$C1
0E43-   D3          ???
0E44-   C3          ???
0E45-   A0 A2       LDY   #$A2
0E47-   B0 20       BCS   $0E69
0E49-   20 20 20    JSR   $2020
0E4C-   20 B1 20    JSR   $20B1
0E4F-   20 20 20    JSR   $2020
0E52-   20 B2 20    JSR   $20B2
0E55-   20 20 20    JSR   $2020
0E58-   20 B3 20    JSR   $20B3
0E5B-   20 20 20    JSR   $2020
0E5E-   20 B4 20    JSR   $20B4
0E61-   20 20 20    JSR   $2020
0E64-   20 B5 20    JSR   $20B5
0E67-   20 20 20    JSR   $2020
0E6A-   20 20 20    JSR   $2020
0E6D-   20 20 A2    JSR   $A220
0E70-   8D A0 C8    STA   $C8A0
0E73-   C5 D8       CMP   $D8
0E75-   A0 B8       LDY   #$B8
0E77-   C4 B0       CPY   $B0
0E79-   B0 8D       BCS   $0E08
0E7B-   A0 CC       LDY   #$CC
0E7D-   C4 C1       CPY   $C1
0E7F-   A0 A3       LDY   #$A3
0E81-   BE A4 B3    LDX   $B3A4,Y
0E84-   B0 B0       BCS   $0E36
0E86-   8D A0 D0    STA   $D0A0
0E89-   C8          INY
0E8A-   C1 8D       CMP   ($8D,X)
0E8C-   A0 CC       LDY   #$CC
0E8E-   C4 C1       CPY   $C1
0E90-   A0 A3       LDY   #$A3
0E92-   BC A4 B3    LDY   $B3A4,X
0E95-   B0 B0       BCS   $0E47
0E97-   8D A0 D0    STA   $D0A0
0E9A-   C8          INY
0E9B-   C1 8D       CMP   ($8D,X)
0E9D-   A0 CC       LDY   #$CC
0E9F-   C4 C1       CPY   $C1
0EA1-   A0 A3       LDY   #$A3
0EA3-   B1 B4       LDA   ($B4),Y
0EA5-   A0 BB       LDY   #$BB
0EA7-   20 C1 D2    JSR   $D2C1
0EAA-   D2 C1       CMP   ($C1)
0EAC-   D9 20 CC    CMP   $CC20,Y
0EAF-   C5 CE       CMP   $CE
0EB1-   C7          ???
0EB2-   D4          ???
0EB3-   C8          INY
0EB4-   20 AB 20    JSR   $20AB
0EB7-   B2 8D       LDA   ($8D)
0EB9-   A0 D0       LDY   #$D0
0EBB-   C8          INY
0EBC-   C1 8D       CMP   ($8D,X)
0EBE-   A0 CA       LDY   #$CA
0EC0-   D3          ???
0EC1-   D2 A0       CMP   ($A0)
0EC3-   DF          ???
0EC4-   DF          ???
0EC5-   C4 D5       CPY   $D5
0EC7-   CD D0 8D    CMP   $8DD0
0ECA-   A0 CA       LDY   #$CA
0ECC-   D3          ???
0ECD-   D2 A0       CMP   ($A0)
0ECF-   DF          ???
0ED0-   DF          ???
0ED1-   D7          ???
0ED2-   8D AA 8D    STA   $8DAA
0ED5-   AA          TAX
0ED6-   AA          TAX
0ED7-   20 CE CF    JSR   $CFCE
0EDA-   D4          ???
0EDB-   C5 20       CMP   $20
0EDD-   D4          ???
0EDE-   C8          INY
0EDF-   C1 D4       CMP   ($D4,X)
0EE1-   20 C9 CE    JSR   $CEC9
0EE4-   C4 C5       CPY   $C5
0EE6-   D8          CLD
0EE7-   C9 CE       CMP   #$CE
0EE9-   C7          ???
0EEA-   20 D3 D4    JSR   $D4D3
0EED-   C1 D2       CMP   ($D2,X)
0EEF-   D4          ???
0EF0-   D3          ???
0EF1-   20 C1 D4    JSR   $D4C1
0EF4-   20 B0 AC    JSR   $ACB0
0EF7-   20 D3 CF    JSR   $CFD3
0EFA-   20 C1 CE    JSR   $CEC1
0EFD-   20 C1 D2    JSR   $D2C1
0F00-   D2 C1       CMP   ($C1)
0F02-   D9 8D AA    CMP   $AA8D,Y
0F05-   AA          TAX
0F06-   20 CF C6    JSR   $C6CF
0F09-   20 D4 C5    JSR   $C5D4
0F0C-   CE 20 C5    DEC   $C520
0F0F-   CC C5 CD    CPY   $CDC5
0F12-   C5 CE       CMP   $CE
0F14-   D4          ???
0F15-   D3          ???
0F16-   20 D7 CF    JSR   $CFD7
0F19-   D5 CC       CMP   $CC,X
0F1B-   C4 20       CPY   $20
0F1D-   C2          ???
0F1E-   C5 20       CMP   $20
0F20-   CC C9 D3    CPY   $D3C9
0F23-   D4          ???
0F24-   C5 C4       CMP   $C4
0F26-   20 C1 D3    JSR   $D3C1
0F29-   20 B0 AE    JSR   $AEB0
0F2C-   AE B9 8D    LDX   $8DB9
0F2F-   AA          TAX
0F30-   8D AA AA    STA   $AAAA
0F33-   20 C1 D0    JSR   $D0C1
0F36-   D5 D4       CMP   $D4,X
0F38-   B8          CLV
0F39-   B1 20       LDA   ($20),Y
0F3B-   C3          ???
0F3C-   CF          ???
0F3D-   D0 C9       BNE   $0F08
0F3F-   C5 D3       CMP   $D3
0F41-   20 C4 C1    JSR   $C1C4
0F44-   D4          ???
0F45-   C1 20       CMP   ($20,X)
0F47-   C6 D2       DEC   $D2
0F49-   CF          ???
0F4A-   CD 20 CF    CMP   $CF20
0F4D-   CE C5 20    DEC   $20C5
0F50-   D3          ???
0F51-   D0 C5       BNE   $0F18
0F53-   C3          ???
0F54-   C9 C6       CMP   #$C6
0F56-   C9 C5       CMP   #$C5
0F58-   C4 20       CPY   $20
0F5A-   CC CF C3    CPY   $C3CF
0F5D-   C1 D4       CMP   ($D4,X)
0F5F-   C9 CF       CMP   #$CF
0F61-   CE 8D AA    DEC   $AA8D
0F64-   AA          TAX
0F65-   20 D4 CF    JSR   $CFD4
0F68-   20 D4 C8    JSR   $C8D4
0F6B-   C5 20       CMP   $20
0F6D-   C5 CC       CMP   $CC
0F6F-   C5 CD       CMP   $CD
0F71-   C5 CE       CMP   $CE
0F73-   D4          ???
0F74-   20 C9 CE    JSR   $CEC9
0F77-   C4 C5       CPY   $C5
0F79-   D8          CLD
0F7A-   C5 C4       CMP   $C4
0F7C-   20 C9 CE    JSR   $CEC9
0F7F-   20 C1 CE    JSR   $CEC1
0F82-   20 C1 D2    JSR   $D2C1
0F85-   D2 C1       CMP   ($C1)
0F87-   D9 20 C1    CMP   $C120,Y
0F8A-   D4          ???
0F8B-   20 C1 CE    JSR   $CEC1
0F8E-   CF          ???
0F8F-   D4          ???
0F90-   C8          INY
0F91-   C5 D2       CMP   $D2
0F93-   8D AA AA    STA   $AAAA
0F96-   20 CC CF    JSR   $CFCC
0F99-   C3          ???
0F9A-   C1 D4       CMP   ($D4,X)
0F9C-   C9 CF       CMP   #$CF
0F9E-   CE AE 8D    DEC   $8DAE
0FA1-   AA          TAX
0FA2-   8D AA AA    STA   $AAAA
0FA5-   AA          TAX
0FA6-   20 CD C1    JSR   $C1CD
0FA9-   C3          ???
0FAA-   D2 CF       CMP   ($CF)
0FAC-   BA          TSX
0FAD-   20 D0 D5    JSR   $D5D0
0FB0-   D4          ???
0FB1-   B8          CLV
0FB2-   B1 20       LDA   ($20),Y
0FB4-   A4 D3       LDY   $D3
0FB6-   D2 C3       CMP   ($C3)
0FB8-   DF          ???
0FB9-   C1 C4       CMP   ($C4,X)
0FBB-   C4 D2       CPY   $D2
0FBD-   BB          ???
0FBE-   C1 D2       CMP   ($D2,X)
0FC0-   D2 C1       CMP   ($C1)
0FC2-   D9 DF C1    CMP   $C1DF,Y
0FC5-   C4 C4       CPY   $C4
0FC7-   D2 BB       CMP   ($BB)
0FC9-   C9 CE       CMP   #$CE
0FCB-   C4 C5       CPY   $C5
0FCD-   D8          CLD
0FCE-   8D AA 8D    STA   $8DAA
0FD1-   A0 CC       LDY   #$CC
0FD3-   C4 C1       CPY   $C1
0FD5-   A0 A3       LDY   #$A3
0FD7-   A4 B4       LDY   $B4
0FD9-   B4 8D       LDY   $8D,X
0FDB-   A0 D3       LDY   #$D3
0FDD-   D4          ???
0FDE-   C1 A0       CMP   ($A0,X)
0FE0-   C1 D2       CMP   ($D2,X)
0FE2-   D2 C1       CMP   ($C1)
0FE4-   D9 B2 8D    CMP   $8DB2,Y
0FE7-   A0 CC       LDY   #$CC
0FE9-   C4 C1       CPY   $C1
0FEB-   A0 A3       LDY   #$A3
0FED-   A4 B5       LDY   $B5
0FEF-   B5 8D       LDA   $8D,X
0FF1-   A0 D3       LDY   #$D3
0FF3-   D4          ???
0FF4-   C1 A0       CMP   ($A0,X)
0FF6-   C1 D2       CMP   ($D2,X)
0FF8-   D2 C1       CMP   ($C1)
0FFA-   D9 B2 AB    CMP   $ABB2,Y
0FFD-   B1 8D       LDA   ($8D),Y
0FFF-   A0 CC       LDY   #$CC
1001-   C4 C1       CPY   $C1
1003-   A0 A3       LDY   #$A3
1005-   BE C1 D2    LDX   $D2C1,Y
1008-   D2 C1       CMP   ($C1)
100A-   D9 B2 A0    CMP   $A0B2,Y
100D-   BB          ???
100E-   20 C1 C4    JSR   $C4C1
1011-   C4 D2       CPY   $D2
1013-   C5 D3       CMP   $D3
1015-   D3          ???
1016-   20 D4 CF    JSR   $CFD4
1019-   20 C3 CF    JSR   $CFC3
101C-   D0 D9       BNE   $0FF7
101E-   8D A0 D0    STA   $D0A0
1021-   C8          INY
1022-   C1 8D       CMP   ($8D,X)
1024-   A0 CC       LDY   #$CC
1026-   C4 C1       CPY   $C1
1028-   A0 A3       LDY   #$A3
102A-   BC C1 D2    LDY   $D2C1,X
102D-   D2 C1       CMP   ($C1)
102F-   D9 B2 8D    CMP   $8DB2,Y
1032-   A0 D0       LDY   #$D0
1034-   C8          INY
1035-   C1 8D       CMP   ($8D,X)
1037-   A0 CC       LDY   #$CC
1039-   C4 C1       CPY   $C1
103B-   A0 A3       LDY   #$A3
103D-   BE C1 D2    LDX   $D2C1,Y
1040-   D2 C1       CMP   ($C1)
1042-   D9 B1 A0    CMP   $A0B1,Y
1045-   BB          ???
1046-   20 C1 D2    JSR   $D2C1
1049-   D2 C1       CMP   ($C1)
104B-   D9 20 C1    CMP   $C120,Y
104E-   C4 C4       CPY   $C4
1050-   D2 C5       CMP   ($C5)
1052-   D3          ???
1053-   D3          ???
1054-   8D A0 D0    STA   $D0A0
1057-   C8          INY
1058-   C1 8D       CMP   ($8D,X)
105A-   A0 CC       LDY   #$CC
105C-   C4 C1       CPY   $C1
105E-   A0 A3       LDY   #$A3
1060-   BC C1 D2    LDY   $D2C1,X
1063-   D2 C1       CMP   ($C1)
1065-   D9 B1 8D    CMP   $8DB1,Y
1068-   A0 D0       LDY   #$D0
106A-   C8          INY
106B-   C1 8D       CMP   ($8D,X)
106D-   A0 CC       LDY   #$CC
106F-   C4 C1       CPY   $C1
1071-   A0 A3       LDY   #$A3
1073-   B2 8D       LDA   ($8D)
1075-   A0 D0       LDY   #$D0
1077-   C8          INY
1078-   C1 A0       CMP   ($A0,X)
107A-   BB          ???
107B-   20 C9 CE    JSR   $CEC9
107E-   C4 C5       CPY   $C5
1080-   D8          CLD
1081-   8D A0 CA    STA   $CAA0
1084-   D3          ???
1085-   D2 A0       CMP   ($A0)
1087-   C1 D0       CMP   ($D0,X)
1089-   D5 D4       CMP   $D4,X
108B-   B8          CLV
108C-   B1 8D       LDA   ($8D),Y
108E-   A0 CA       LDY   #$CA
1090-   D3          ???
1091-   D2 A0       CMP   ($A0)
1093-   DF          ???
1094-   DF          ???
1095-   D0 8D       BNE   $1024
1097-   A0 C8       LDY   #$C8
1099-   C5 D8       CMP   $D8
109B-   A0 B8       LDY   #$B8
109D-   C4 B8       CPY   $B8
109F-   C4 B8       CPY   $B8
10A1-   C4 8D       CPY   $8D
10A3-   A0 C1       LDY   #$C1
10A5-   D3          ???
10A6-   C3          ???
10A7-   A0 A2       LDY   #$A2
10A9-   C1 C6       CMP   ($C6,X)
10AB-   D4          ???
10AC-   C5 D2       CMP   $D2
10AE-   20 D0 D5    JSR   $D5D0
10B1-   D4          ???
10B2-   D4          ???
10B3-   C9 CE       CMP   #$CE
10B5-   C7          ???
10B6-   20 A3 B4    JSR   $B4A3
10B9-   B4 B5       LDY   $B5,X
10BB-   B5 20       LDA   $20,X
10BD-   C1 D4       CMP   ($D4,X)
10BF-   20 C9 CE    JSR   $CEC9
10C2-   C4 C5       CPY   $C5
10C4-   D8          CLD
10C5-   20 B2 A2    JSR   $A2B2
10C8-   8D A0 C8    STA   $C8A0
10CB-   C5 D8       CMP   $D8
10CD-   A0 B8       LDY   #$B8
10CF-   C4 B0       CPY   $B0
10D1-   B0 8D       BCS   $1060
10D3-   A0 CC       LDY   #$CC
10D5-   C4 C1       CPY   $C1
10D7-   A0 A3       LDY   #$A3
10D9-   BE C1 D2    LDX   $D2C1,Y
10DC-   D2 C1       CMP   ($C1)
10DE-   D9 B1 8D    CMP   $8DB1,Y
10E1-   A0 D0       LDY   #$D0
10E3-   C8          INY
10E4-   C1 8D       CMP   ($8D,X)
10E6-   A0 CC       LDY   #$CC
10E8-   C4 C1       CPY   $C1
10EA-   A0 A3       LDY   #$A3
10EC-   BC C1 D2    LDY   $D2C1,X
10EF-   D2 C1       CMP   ($C1)
10F1-   D9 B1 8D    CMP   $8DB1,Y
10F4-   A0 D0       LDY   #$D0
10F6-   C8          INY
10F7-   C1 8D       CMP   ($8D,X)
10F9-   A0 CC       LDY   #$CC
10FB-   C4 C1       CPY   $C1
10FD-   A0 A3       LDY   #$A3
10FF-   B1 B4       LDA   ($B4),Y
1101-   8D A0 D0    STA   $D0A0
1104-   C8          INY
1105-   C1 8D       CMP   ($8D,X)
1107-   A0 CA       LDY   #$CA
1109-   D3          ???
110A-   D2 A0       CMP   ($A0)
110C-   DF          ???
110D-   DF          ???
110E-   C4 D5       CPY   $D5
1110-   CD D0 8D    CMP   $8DD0
1113-   A0 CA       LDY   #$CA
1115-   D3          ???
1116-   D2 A0       CMP   ($A0)
1118-   DF          ???
1119-   DF          ???
111A-   D7          ???
111B-   8D AA 8D    STA   $8DAA
111E-   AA          TAX
111F-   AA          TAX
1120-   20 C1 C7    JSR   $C7C1
1123-   C5 D4       CMP   $D4
1125-   B8          CLV
1126-   B1 20       LDA   ($20),Y
1128-   D2 C5       CMP   ($C5)
112A-   D4          ???
112B-   D5 D2       CMP   $D2,X
112D-   CE D3 20    DEC   $20D3
1130-   D4          ???
1131-   C8          INY
1132-   C5 20       CMP   $20
1134-   CD C5 CD    CMP   $CDC5
1137-   CF          ???
1138-   D2 D9       CMP   ($D9)
113A-   20 C1 C4    JSR   $C4C1
113D-   C4 D2       CPY   $D2
113F-   C5 D3       CMP   $D3
1141-   D3          ???
1142-   20 D7 C8    JSR   $C8D7
1145-   C5 D2       CMP   $D2
1147-   C5 8D       CMP   $8D
1149-   AA          TAX
114A-   AA          TAX
114B-   20 C1 CE    JSR   $CEC1
114E-   20 C5 CC    JSR   $CCC5
1151-   C5 CD       CMP   $CD
1153-   C5 CE       CMP   $CE
1155-   D4          ???
1156-   20 C1 D4    JSR   $D4C1
1159-   20 D4 C8    JSR   $C8D4
115C-   C5 20       CMP   $20
115E-   D3          ???
115F-   D0 C5       BNE   $1126
1161-   C3          ???
1162-   C9 C6       CMP   #$C6
1164-   C9 C5       CMP   #$C5
1166-   C4 20       CPY   $20
1168-   C9 CE       CMP   #$CE
116A-   C4 C5       CPY   $C5
116C-   D8          CLD
116D-   20 C9 CE    JSR   $CEC9
1170-   8D AA AA    STA   $AAAA
1173-   20 D9 20    JSR   $20D9
1176-   A8          TAY
1177-   CC CF D7    CPY   $D7CF
117A-   A9 20       LDA   #$20
117C-   C1 CE       CMP   ($CE,X)
117E-   C4 20       CPY   $20
1180-   D8          CLD
1181-   20 A8 C8    JSR   $C8A8
1184-   C9 C7       CMP   #$C7
1186-   C8          INY
1187-   A9 AC       LDA   #$AC
1189-   20 C1 D3    JSR   $D3C1
118C-   20 D7 C5    JSR   $C5D7
118F-   CC CC 20    CPY   $20CC
1192-   C1 D3       CMP   ($D3,X)
1194-   20 C3 CF    JSR   $CFC3
1197-   D0 C9       BNE   $1162
1199-   C5 D3       CMP   $D3
119B-   8D AA AA    STA   $AAAA
119E-   20 D4 C8    JSR   $C8D4
11A1-   C1 D4       CMP   ($D4,X)
11A3-   20 C5 CC    JSR   $CCC5
11A6-   C5 CD       CMP   $CD
11A8-   C5 CE       CMP   $CE
11AA-   D4          ???
11AB-   20 D4 CF    JSR   $CFD4
11AE-   20 D4 C8    JSR   $C8D4
11B1-   C5 20       CMP   $20
11B3-   DB          ???
11B4-   D2 C5       CMP   ($C5)
11B6-   D4          ???
11B7-   D5 D2       CMP   $D2,X
11B9-   CE DD 20    DEC   $20DD
11BC-   CC CF C3    CPY   $C3CF
11BF-   C1 D4       CMP   ($D4,X)
11C1-   C9 CF       CMP   #$CF
11C3-   CE 8D AA    DEC   $AA8D
11C6-   8D AA AA    STA   $AAAA
11C9-   AA          TAX
11CA-   20 CD C1    JSR   $C1CD
11CD-   C3          ???
11CE-   D2 CF       CMP   ($CF)
11D0-   BA          TSX
11D1-   20 C7 C5    JSR   $C5C7
11D4-   D4          ???
11D5-   B8          CLV
11D6-   B1 20       LDA   ($20),Y
11D8-   A4 C1       LDY   $C1
11DA-   D2 D2       CMP   ($D2)
11DC-   C1 D9       CMP   ($D9,X)
11DE-   DF          ???
11DF-   C1 C4       CMP   ($C4,X)
11E1-   C4 D2       CPY   $D2
11E3-   C5 D3       CMP   $D3
11E5-   D3          ???
11E6-   BB          ???
11E7-   C9 CE       CMP   #$CE
11E9-   C4 C5       CPY   $C5
11EB-   D8          CLD
11EC-   8D AA 8D    STA   $8DAA
11EF-   A0 CC       LDY   #$CC
11F1-   C4 C1       CPY   $C1
11F3-   A0 A3       LDY   #$A3
11F5-   BE C1 D2    LDX   $D2C1,Y
11F8-   D2 C1       CMP   ($C1)
11FA-   D9 B1 8D    CMP   $8DB1,Y
11FD-   A0 D0       LDY   #$D0
11FF-   C8          INY
1200-   C1 8D       CMP   ($8D,X)
1202-   A0 CC       LDY   #$CC
1204-   C4 C1       CPY   $C1
1206-   A0 A3       LDY   #$A3
1208-   BC C1 D2    LDY   $D2C1,X
120B-   D2 C1       CMP   ($C1)
120D-   D9 B1 8D    CMP   $8DB1,Y
1210-   A0 D0       LDY   #$D0
1212-   C8          INY
1213-   C1 8D       CMP   ($8D,X)
1215-   A0 CC       LDY   #$CC
1217-   C4 C1       CPY   $C1
1219-   A0 A3       LDY   #$A3
121B-   B0 B2       BCS   $11CF
121D-   A0 BB       LDY   #$BB
121F-   20 C9 CE    JSR   $CEC9
1222-   C4 C5       CPY   $C5
1224-   D8          CLD
1225-   20 C3 CF    JSR   $CFC3
1228-   CE D4 C1    DEC   $C1D4
122B-   C9 CE       CMP   #$CE
122D-   D3          ???
122E-   20 A3 B4    JSR   $B4A3
1231-   B4 B5       LDY   $B5,X
1233-   B5 8D       LDA   $8D,X
1235-   A0 D0       LDY   #$D0
1237-   C8          INY
1238-   C1 A0       CMP   ($A0,X)
123A-   BB          ???
123B-   20 CF D2    JSR   $D2CF
123E-   20 A2 C4    JSR   $C4A2
1241-   D5 A2       CMP   $A2,X
1243-   20 C9 CE    JSR   $CEC9
1246-   D6 C5       DEC   $C5,X
1248-   D2 D4       CMP   ($D4)
124A-   C5 C4       CMP   $C4
124C-   8D A0 CA    STA   $CAA0
124F-   D3          ???
1250-   D2 A0       CMP   ($A0)
1252-   C1 C7       CMP   ($C7,X)
1254-   C5 D4       CMP   $D4
1256-   B8          CLV
1257-   B1 8D       LDA   ($8D),Y
1259-   AA          TAX
125A-   8D A0 CA    STA   $CAA0
125D-   D3          ???
125E-   D2 A0       CMP   ($A0)
1260-   DF          ???
1261-   DF          ???
1262-   D0 8D       BNE   $11F1
1264-   A0 C8       LDY   #$C8
1266-   C5 D8       CMP   $D8
1268-   A0 B8       LDY   #$B8
126A-   C4 B8       CPY   $B8
126C-   C4 8D       CPY   $8D
126E-   A0 C1       LDY   #$C1
1270-   D3          ???
1271-   C3          ???
1272-   A0 A2       LDY   #$A2
1274-   D2 C5       CMP   ($C5)
1276-   D4          ???
1277-   D5 D2       CMP   $D2,X
1279-   CE 20 D6    DEC   $D620
127C-   C1 CC       CMP   ($CC,X)
127E-   D5 C5       CMP   $C5,X
1280-   20 CF C6    JSR   $C6CF
1283-   20 C7 C5    JSR   $C5C7
1286-   D4          ???
1287-   B8          CLV
1288-   B1 BA       LDA   ($BA),Y
128A-   20 A2 8D    JSR   $8DA2
128D-   A0 C8       LDY   #$C8
128F-   C5 D8       CMP   $D8
1291-   A0 B0       LDY   #$B0
1293-   B0 8D       BCS   $1222
1295-   A0 CC       LDY   #$CC
1297-   C4 C1       CPY   $C1
1299-   A0 D2       LDY   #$D2
129B-   C5 D4       CMP   $D4
129D-   D5 D2       CMP   $D2,X
129F-   CE 8D A0    DEC   $A08D
12A2-   CA          DEX
12A3-   D3          ???
12A4-   D2 A0       CMP   ($A0)
12A6-   A4 C6       LDY   $C6
12A8-   C4 C6       CPY   $C6
12AA-   B0 A0       BCS   $124C
12AC-   BB          ???
12AD-   20 C3 CF    JSR   $CFC3
12B0-   D5 D4       CMP   $D4,X
12B2-   B1 8D       LDA   ($8D),Y
12B4-   A0 CC       LDY   #$CC
12B6-   C4 C1       CPY   $C1
12B8-   A0 D2       LDY   #$D2
12BA-   C5 D4       CMP   $D4
12BC-   D5 D2       CMP   $D2,X
12BE-   CE AB B1    DEC   $B1AB
12C1-   8D A0 CA    STA   $CAA0
12C4-   D3          ???
12C5-   D2 A0       CMP   ($A0)
12C7-   A4 C6       LDY   $C6
12C9-   C4 C6       CPY   $C6
12CB-   B0 8D       BCS   $125A
12CD-   A0 CA       LDY   #$CA
12CF-   D3          ???
12D0-   D2 A0       CMP   ($A0)
12D2-   DF          ???
12D3-   DF          ???
12D4-   D0 8D       BNE   $1263
12D6-   A0 C8       LDY   #$C8
12D8-   C5 D8       CMP   $D8
12DA-   A0 B8       LDY   #$B8
12DC-   C4 B0       CPY   $B0
12DE-   B0 8D       BCS   $126D
12E0-   A0 CA       LDY   #$CA
12E2-   D3          ???
12E3-   D2 A0       CMP   ($A0)
12E5-   DF          ???
12E6-   DF          ???
12E7-   D7          ???
12E8-   8D AA 8D    STA   $8DAA
12EB-   AA          TAX
12EC-   AA          TAX
12ED-   20 C4 C9    JSR   $C9C4
12F0-   CD B8 B2    CMP   $B2B8
12F3-   20 C3 D2    JSR   $D2C3
12F6-   C5 C1       CMP   $C1
12F8-   D4          ???
12F9-   C5 D3       CMP   $D3
12FB-   20 C1 CE    JSR   $CEC1
12FE-   20 B8 C2    JSR   $C2B8
1301-   C9 D4       CMP   #$D4
1303-   AC 20 B2    LDY   $B220
1306-   C4 20       CPY   $20
1308-   C1 D2       CMP   ($D2,X)
130A-   D2 C1       CMP   ($C1)
130C-   D9 20 C1    CMP   $C120,Y
130F-   D4          ???
1310-   20 D4 C8    JSR   $C8D4
1313-   C5 8D       CMP   $8D
1315-   AA          TAX
1316-   AA          TAX
1317-   20 D3 D0    JSR   $D0D3
131A-   C5 C3       CMP   $C3
131C-   C9 C6       CMP   #$C6
131E-   C9 C5       CMP   #$C5
1320-   C4 20       CPY   $20
1322-   CC CF C3    CPY   $C3CF
1325-   C1 D4       CMP   ($D4,X)
1327-   C9 CF       CMP   #$CF
1329-   CE 20 D7    DEC   $D720
132C-   C9 D4       CMP   #$D4
132E-   C8          INY
132F-   20 D4 C8    JSR   $C8D4
1332-   C5 20       CMP   $20
1334-   CC C5 CE    CPY   $CEC5
1337-   C7          ???
1338-   D4          ???
1339-   C8          INY
133A-   20 C1 CE    JSR   $CEC1
133D-   C4 8D       CPY   $8D
133F-   AA          TAX
1340-   AA          TAX
1341-   20 C8 C5    JSR   $C5C8
1344-   C9 C7       CMP   #$C7
1346-   C8          INY
1347-   D4          ???
1348-   20 D0 C1    JSR   $C1D0
134B-   D3          ???
134C-   D3          ???
134D-   C5 C4       CMP   $C4
134F-   20 D6 C9    JSR   $C9D6
1352-   C1 20       CMP   ($20,X)
1354-   D4          ???
1355-   C8          INY
1356-   C5 20       CMP   $20
1358-   D3          ???
1359-   D4          ???
135A-   C1 C3       CMP   ($C3,X)
135C-   CB          ???
135D-   8D AA 8D    STA   $8DAA
1360-   AA          TAX
1361-   AA          TAX
1362-   20 CD C1    JSR   $C1CD
1365-   C3          ???
1366-   D2 CF       CMP   ($CF)
1368-   BA          TSX
1369-   20 C4 C9    JSR   $C9C4
136C-   CD B8 B2    CMP   $B2B8
136F-   20 A4 C1    JSR   $C1A4
1372-   D2 D2       CMP   ($D2)
1374-   C1 D9       CMP   ($D9,X)
1376-   DF          ???
1377-   C1 C4       CMP   ($C4,X)
1379-   C4 D2       CPY   $D2
137B-   BB          ???
137C-   D2 CF       CMP   ($CF)
137E-   D7          ???
137F-   D3          ???
1380-   BB          ???
1381-   C3          ???
1382-   CF          ???
1383-   CC D5 CD    CPY   $CDD5
1386-   CE D3 BB    DEC   $BBD3
1389-   C5 CC       CMP   $CC
138B-   C5 CD       CMP   $CD
138D-   C5 CE       CMP   $CE
138F-   D4          ???
1390-   DF          ???
1391-   CC C5 CE    CPY   $CEC5
1394-   C7          ???
1395-   D4          ???
1396-   C8          INY
1397-   8D AA 8D    STA   $8DAA
139A-   A0 CC       LDY   #$CC
139C-   C4 C1       CPY   $C1
139E-   A0 A3       LDY   #$A3
13A0-   BE C1 D2    LDX   $D2C1,Y
13A3-   D2 C1       CMP   ($C1)
13A5-   D9 B2 8D    CMP   $8DB2,Y
13A8-   A0 D0       LDY   #$D0
13AA-   C8          INY
13AB-   C1 8D       CMP   ($8D,X)
13AD-   A0 CC       LDY   #$CC
13AF-   C4 C1       CPY   $C1
13B1-   A0 A3       LDY   #$A3
13B3-   BC C1 D2    LDY   $D2C1,X
13B6-   D2 C1       CMP   ($C1)
13B8-   D9 B2 A0    CMP   $A0B2,Y
13BB-   BB          ???
13BC-   20 C1 D2    JSR   $D2C1
13BF-   D2 C1       CMP   ($C1)
13C1-   D9 20 C1    CMP   $C120,Y
13C4-   C4 C4       CPY   $C4
13C6-   D2 C5       CMP   ($C5)
13C8-   D3          ???
13C9-   D3          ???
13CA-   8D A0 D0    STA   $D0A0
13CD-   C8          INY
13CE-   C1 8D       CMP   ($8D,X)
13D0-   A0 CC       LDY   #$CC
13D2-   C4 C1       CPY   $C1
13D4-   A0 A3       LDY   #$A3
13D6-   B4 A0       LDY   $A0,X
13D8-   BB          ???
13D9-   20 D8 AD    JSR   $ADD8
13DC-   C4 C9       CPY   $C9
13DE-   CD C5 CE    CMP   $CEC5
13E1-   D3          ???
13E2-   C9 CF       CMP   #$CF
13E4-   CE 8D A0    DEC   $A08D
13E7-   D0 C8       BNE   $13B1
13E9-   C1 8D       CMP   ($8D,X)
13EB-   A0 CC       LDY   #$CC
13ED-   C4 C1       CPY   $C1
13EF-   A0 A3       LDY   #$A3
13F1-   B4 A0       LDY   $A0,X
13F3-   BB          ???
13F4-   20 D9 AD    JSR   $ADD9
13F7-   C4 C9       CPY   $C9
13F9-   CD C5 D3    CMP   $D3C5
13FC-   C9 CF       CMP   #$CF
13FE-   CE 8D A0    DEC   $A08D
1401-   D0 C8       BNE   $13CB
1403-   C1 8D       CMP   ($8D,X)
1405-   A0 CC       LDY   #$CC
1407-   C4 C1       CPY   $C1
1409-   A0 A3       LDY   #$A3
140B-   B1 A0       LDA   ($A0),Y
140D-   BB          ???
140E-   20 C5 CC    JSR   $CCC5
1411-   C5 CD       CMP   $CD
1413-   C5 CE       CMP   $CE
1415-   D4          ???
1416-   20 D3 C9    JSR   $C9D3
1419-   DA          PHX
141A-   C5 8D       CMP   $8D
141C-   A0 D0       LDY   #$D0
141E-   C8          INY
141F-   C1 8D       CMP   ($8D,X)
1421-   A0 CA       LDY   #$CA
1423-   D3          ???
1424-   D2 A0       CMP   ($A0)
1426-   C1 C4       CMP   ($C4,X)
1428-   C9 CD       CMP   #$CD
142A-   B8          CLV
142B-   B2 8D       LDA   ($8D)
142D-   AA          TAX
142E-   8D A0 CA    STA   $CAA0
1431-   D3          ???
1432-   D2 A0       CMP   ($A0)
1434-   DF          ???
1435-   DF          ???
1436-   D0 8D       BNE   $13C5
1438-   A0 C8       LDY   #$C8
143A-   C5 D8       CMP   $D8
143C-   A0 B8       LDY   #$B8
143E-   C4 B8       CPY   $B8
1440-   C4 8D       CPY   $8D
1442-   A0 C1       LDY   #$C1
1444-   D3          ???
1445-   C3          ???
1446-   A0 A2       LDY   #$A2
1448-   B2 AD       LDA   ($AD)
144A-   C4 C9       CPY   $C9
144C-   CD C5 CE    CMP   $CEC5
144F-   D3          ???
1450-   C9 CF       CMP   #$CF
1452-   CE C1 CC    DEC   $CCC1
1455-   20 C1 D2    JSR   $D2C1
1458-   D2 C1       CMP   ($C1)
145A-   D9 AC 20    CMP   $20AC,Y
145D-   C6 C9       DEC   $C9
145F-   D2 D3       CMP   ($D3)
1461-   D4          ???
1462-   20 C9 CE    JSR   $CEC9
1465-   C9 D4       CMP   #$D4
1467-   C9 C1       CMP   #$C1
1469-   CC C9 DA    CPY   $DAC9
146C-   C5 C4       CMP   $C4
146E-   A2 8D       LDX   #$8D
1470-   A0 C8       LDY   #$C8
1472-   C5 D8       CMP   $D8
1474-   A0 B8       LDY   #$B8
1476-   C4 8D       CPY   $8D
1478-   A0 C8       LDY   #$C8
147A-   C5 D8       CMP   $D8
147C-   A0 B0       LDY   #$B0
147E-   B0 8D       BCS   $140D
1480-   A0 CC       LDY   #$CC
1482-   C4 C1       CPY   $C1
1484-   A0 A3       LDY   #$A3
1486-   BE C1 D2    LDX   $D2C1,Y
1489-   D2 C1       CMP   ($C1)
148B-   D9 B2 8D    CMP   $8DB2,Y
148E-   A0 D0       LDY   #$D0
1490-   C8          INY
1491-   C1 8D       CMP   ($8D,X)
1493-   A0 CC       LDY   #$CC
1495-   C4 C1       CPY   $C1
1497-   A0 A3       LDY   #$A3
1499-   BC C1 D2    LDY   $D2C1,X
149C-   D2 C1       CMP   ($C1)
149E-   D9 B2 8D    CMP   $8DB2,Y
14A1-   A0 D0       LDY   #$D0
14A3-   C8          INY
14A4-   C1 8D       CMP   ($8D,X)
14A6-   A0 CC       LDY   #$CC
14A8-   C4 C1       CPY   $C1
14AA-   A0 A3       LDY   #$A3
14AC-   B3          ???
14AD-   8D A0 D0    STA   $D0A0
14B0-   C8          INY
14B1-   C1 8D       CMP   ($8D,X)
14B3-   A0 CA       LDY   #$CA
14B5-   D3          ???
14B6-   D2 A0       CMP   ($A0)
14B8-   DF          ???
14B9-   DF          ???
14BA-   C4 D5       CPY   $D5
14BC-   CD D0 8D    CMP   $8DD0
14BF-   A0 CC       LDY   #$CC
14C1-   C4 C1       CPY   $C1
14C3-   A0 A3       LDY   #$A3
14C5-   BE C1 D2    LDX   $D2C1,Y
14C8-   D2 C1       CMP   ($C1)
14CA-   D9 B2 AB    CMP   $ABB2,Y
14CD-   B3          ???
14CE-   8D A0 D0    STA   $D0A0
14D1-   C8          INY
14D2-   C1 8D       CMP   ($8D,X)
14D4-   A0 CC       LDY   #$CC
14D6-   C4 C1       CPY   $C1
14D8-   A0 A3       LDY   #$A3
14DA-   BC C1 D2    LDY   $D2C1,X
14DD-   D2 C1       CMP   ($C1)
14DF-   D9 B2 AB    CMP   $ABB2,Y
14E2-   B3          ???
14E3-   8D A0 D0    STA   $D0A0
14E6-   C8          INY
14E7-   C1 8D       CMP   ($8D,X)
14E9-   A0 CC       LDY   #$CC
14EB-   C4 C1       CPY   $C1
14ED-   A0 A3       LDY   #$A3
14EF-   B4 8D       LDY   $8D,X
14F1-   A0 D0       LDY   #$D0
14F3-   C8          INY
14F4-   C1 8D       CMP   ($8D,X)
14F6-   A0 CA       LDY   #$CA
14F8-   D3          ???
14F9-   D2 A0       CMP   ($A0)
14FB-   DF          ???
14FC-   DF          ???
14FD-   C4 D5       CPY   $D5
14FF-   CD D0 8D    CMP   $8DD0
1502-   A0 CC       LDY   #$CC
1504-   C4 C1       CPY   $C1
1506-   A0 A3       LDY   #$A3
1508-   BE C1 D2    LDX   $D2C1,Y
150B-   D2 C1       CMP   ($C1)
150D-   D9 B2 AB    CMP   $ABB2,Y
1510-   B7          ???
1511-   8D A0 D0    STA   $D0A0
1514-   C8          INY
1515-   C1 8D       CMP   ($8D,X)
1517-   A0 CC       LDY   #$CC
1519-   C4 C1       CPY   $C1
151B-   A0 A3       LDY   #$A3
151D-   BC C1 D2    LDY   $D2C1,X
1520-   D2 C1       CMP   ($C1)
1522-   D9 B2 AB    CMP   $ABB2,Y
1525-   B7          ???
1526-   8D A0 D0    STA   $D0A0
1529-   C8          INY
152A-   C1 8D       CMP   ($8D,X)
152C-   A0 CC       LDY   #$CC
152E-   C4 C1       CPY   $C1
1530-   A0 A3       LDY   #$A3
1532-   B4 8D       LDY   $8D,X
1534-   A0 D0       LDY   #$D0
1536-   C8          INY
1537-   C1 8D       CMP   ($8D,X)
1539-   A0 CA       LDY   #$CA
153B-   D3          ???
153C-   D2 A0       CMP   ($A0)
153E-   DF          ???
153F-   DF          ???
1540-   C4 D5       CPY   $D5
1542-   CD D0 8D    CMP   $8DD0
1545-   A0 CC       LDY   #$CC
1547-   C4 C1       CPY   $C1
1549-   A0 A3       LDY   #$A3
154B-   BE C1 D2    LDX   $D2C1,Y
154E-   D2 C1       CMP   ($C1)
1550-   D9 B2 AB    CMP   $ABB2,Y
1553-   B1 B1       LDA   ($B1),Y
1555-   8D A0 D0    STA   $D0A0
1558-   C8          INY
1559-   C1 8D       CMP   ($8D,X)
155B-   A0 CC       LDY   #$CC
155D-   C4 C1       CPY   $C1
155F-   A0 A3       LDY   #$A3
1561-   BC C1 D2    LDY   $D2C1,X
1564-   D2 C1       CMP   ($C1)
1566-   D9 B2 AB    CMP   $ABB2,Y
1569-   B1 B1       LDA   ($B1),Y
156B-   8D A0 D0    STA   $D0A0
156E-   C8          INY
156F-   C1 8D       CMP   ($8D,X)
1571-   A0 CC       LDY   #$CC
1573-   C4 C1       CPY   $C1
1575-   A0 A3       LDY   #$A3
1577-   B4 8D       LDY   $8D,X
1579-   A0 D0       LDY   #$D0
157B-   C8          INY
157C-   C1 8D       CMP   ($8D,X)
157E-   A0 CA       LDY   #$CA
1580-   D3          ???
1581-   D2 A0       CMP   ($A0)
1583-   DF          ???
1584-   DF          ???
1585-   C4 D5       CPY   $D5
1587-   CD D0 8D    CMP   $8DD0
158A-   A0 CC       LDY   #$CC
158C-   C4 C1       CPY   $C1
158E-   A0 A3       LDY   #$A3
1590-   BE C1 D2    LDX   $D2C1,Y
1593-   D2 C1       CMP   ($C1)
1595-   D9 B2 AB    CMP   $ABB2,Y
1598-   B1 B5       LDA   ($B5),Y
159A-   8D A0 D0    STA   $D0A0
159D-   C8          INY
159E-   C1 8D       CMP   ($8D,X)
15A0-   A0 CC       LDY   #$CC
15A2-   C4 C1       CPY   $C1
15A4-   A0 A3       LDY   #$A3
15A6-   BC C1 D2    LDY   $D2C1,X
15A9-   D2 C1       CMP   ($C1)
15AB-   D9 B2 AB    CMP   $ABB2,Y
15AE-   B1 B5       LDA   ($B5),Y
15B0-   8D A0 D0    STA   $D0A0
15B3-   C8          INY
15B4-   C1 8D       CMP   ($8D,X)
15B6-   A0 CC       LDY   #$CC
15B8-   C4 C1       CPY   $C1
15BA-   A0 A3       LDY   #$A3
15BC-   B4 8D       LDY   $8D,X
15BE-   A0 D0       LDY   #$D0
15C0-   C8          INY
15C1-   C1 8D       CMP   ($8D,X)
15C3-   A0 CA       LDY   #$CA
15C5-   D3          ???
15C6-   D2 A0       CMP   ($A0)
15C8-   DF          ???
15C9-   DF          ???
15CA-   C4 D5       CPY   $D5
15CC-   CD D0 8D    CMP   $8DD0
15CF-   A0 CA       LDY   #$CA
15D1-   D3          ???
15D2-   D2 A0       CMP   ($A0)
15D4-   DF          ???
15D5-   DF          ???
15D6-   D7          ???
15D7-   8D AA 8D    STA   $8DAA
15DA-   AA          TAX
15DB-   AA          TAX
15DC-   20 C1 D0    JSR   $D0C1
15DF-   D5 D4       CMP   $D4,X
15E1-   B8          CLV
15E2-   B2 20       LDA   ($20)
15E4-   D0 D5       BNE   $15BB
15E6-   D4          ???
15E7-   D3          ???
15E8-   20 D4 C8    JSR   $C8D4
15EB-   C5 20       CMP   $20
15ED-   C4 C1       CPY   $C1
15EF-   D4          ???
15F0-   C1 20       CMP   ($20,X)
15F2-   D3          ???
15F3-   D4          ???
15F4-   CF          ???
15F5-   D2 C5       CMP   ($C5)
15F7-   C4 20       CPY   $20
15F9-   C9 CE       CMP   #$CE
15FB-   20 CF CE    JSR   $CECF
15FE-   C5 20       CMP   $20
1600-   CC CF C3    CPY   $C3CF
1603-   C1 D4       CMP   ($D4,X)
1605-   C9 CF       CMP   #$CF
1607-   CE 8D AA    DEC   $AA8D
160A-   AA          TAX
160B-   20 C9 CE    JSR   $CEC9
160E-   D4          ???
160F-   CF          ???
1610-   20 D4 C8    JSR   $C8D4
1613-   C5 20       CMP   $20
1615-   C1 D2       CMP   ($D2,X)
1617-   D2 C1       CMP   ($C1)
1619-   D9 20 C1    CMP   $C120,Y
161C-   D4          ???
161D-   20 D4 C8    JSR   $C8D4
1620-   C5 20       CMP   $20
1622-   D3          ???
1623-   D0 C5       BNE   $15EA
1625-   C3          ???
1626-   C9 C6       CMP   #$C6
1628-   C9 C5       CMP   #$C5
162A-   C4 20       CPY   $20
162C-   C9 CE       CMP   #$CE
162E-   C4 C5       CPY   $C5
1630-   D8          CLD
1631-   20 D8 AC    JSR   $ACD8
1634-   D9 AE 8D    CMP   $8DAE,Y
1637-   AA          TAX
1638-   8D AA AA    STA   $AAAA
163B-   20 CD C1    JSR   $C1CD
163E-   C3          ???
163F-   D2 CF       CMP   ($CF)
1641-   BA          TSX
1642-   20 D0 D5    JSR   $D5D0
1645-   D4          ???
1646-   B8          CLV
1647-   B2 20       LDA   ($20)
1649-   D3          ???
164A-   D2 C3       CMP   ($C3)
164C-   DF          ???
164D-   C1 C4       CMP   ($C4,X)
164F-   C4 D2       CPY   $D2
1651-   BB          ???
1652-   C1 D2       CMP   ($D2,X)
1654-   D2 C1       CMP   ($C1)
1656-   D9 DF C1    CMP   $C1DF,Y
1659-   C4 C4       CPY   $C4
165B-   D2 BB       CMP   ($BB)
165D-   D2 CF       CMP   ($CF)
165F-   D7          ???
1660-   DF          ???
1661-   C9 CE       CMP   #$CE
1663-   C4 C5       CPY   $C5
1665-   D8          CLD
1666-   BB          ???
1667-   C3          ???
1668-   CF          ???
1669-   CC D5 CD    CPY   $CDD5
166C-   CE DF C9    DEC   $C9DF
166F-   CE C4 C5    DEC   $C5C4
1672-   D8          CLD
1673-   8D AA 8D    STA   $8DAA
1676-   A0 CC       LDY   #$CC
1678-   C4 C1       CPY   $C1
167A-   A0 A3       LDY   #$A3
167C-   B1 B8       LDA   ($B8),Y
167E-   B0 8D       BCS   $160D
1680-   A0 D3       LDY   #$D3
1682-   D4          ???
1683-   C1 A0       CMP   ($A0,X)
1685-   C1 D2       CMP   ($D2,X)
1687-   D2 C1       CMP   ($C1)
1689-   D9 B1 8D    CMP   $8DB1,Y
168C-   8D A0 CC    STA   $CCA0
168F-   C4 C1       CPY   $C1
1691-   A0 A3       LDY   #$A3
1693-   BE C1 D2    LDX   $D2C1,Y
1696-   D2 C1       CMP   ($C1)
1698-   D9 B1 A0    CMP   $A0B1,Y
169B-   BB          ???
169C-   20 D3 D2    JSR   $D2D3
169F-   C3          ???
16A0-   8D A0 D0    STA   $D0A0
16A3-   C8          INY
16A4-   C1 8D       CMP   ($8D,X)
16A6-   A0 CC       LDY   #$CC
16A8-   C4 C1       CPY   $C1
16AA-   A0 A3       LDY   #$A3
16AC-   BC C1 D2    LDY   $D2C1,X
16AF-   D2 C1       CMP   ($C1)
16B1-   D9 B1 8D    CMP   $8DB1,Y
16B4-   A0 D0       LDY   #$D0
16B6-   C8          INY
16B7-   C1 8D       CMP   ($8D,X)
16B9-   A0 CC       LDY   #$CC
16BB-   C4 C1       CPY   $C1
16BD-   A0 A3       LDY   #$A3
16BF-   BE C1 D2    LDX   $D2C1,Y
16C2-   D2 C1       CMP   ($C1)
16C4-   D9 B2 A0    CMP   $A0B2,Y
16C7-   BB          ???
16C8-   20 C4 C5    JSR   $C5C4
16CB-   D3          ???
16CC-   D4          ???
16CD-   8D A0 D0    STA   $D0A0
16D0-   C8          INY
16D1-   C1 8D       CMP   ($8D,X)
16D3-   A0 CC       LDY   #$CC
16D5-   C4 C1       CPY   $C1
16D7-   A0 A3       LDY   #$A3
16D9-   BC C1 D2    LDY   $D2C1,X
16DC-   D2 C1       CMP   ($C1)
16DE-   D9 B2 8D    CMP   $8DB2,Y
16E1-   A0 D0       LDY   #$D0
16E3-   C8          INY
16E4-   C1 8D       CMP   ($8D,X)
16E6-   A0 CC       LDY   #$CC
16E8-   C4 C1       CPY   $C1
16EA-   A0 A3       LDY   #$A3
16EC-   B2 A0       LDA   ($A0)
16EE-   BB          ???
16EF-   20 D8 20    JSR   $20D8
16F2-   C9 CE       CMP   #$CE
16F4-   C4 C5       CPY   $C5
16F6-   D8          CLD
16F7-   8D A0 D0    STA   $D0A0
16FA-   C8          INY
16FB-   C1 8D       CMP   ($8D,X)
16FD-   A0 CC       LDY   #$CC
16FF-   C4 C1       CPY   $C1
1701-   A0 A3       LDY   #$A3
1703-   B3          ???
1704-   8D A0 D0    STA   $D0A0
1707-   C8          INY
1708-   C1 A0       CMP   ($A0,X)
170A-   BB          ???
170B-   20 D9 20    JSR   $20D9
170E-   C9 CE       CMP   #$CE
1710-   C4 C5       CPY   $C5
1712-   D8          CLD
1713-   8D A0 CA    STA   $CAA0
1716-   D3          ???
1717-   D2 A0       CMP   ($A0)
1719-   C1 D0       CMP   ($D0,X)
171B-   D5 D4       CMP   $D4,X
171D-   B8          CLV
171E-   B2 8D       LDA   ($8D)
1720-   AA          TAX
1721-   8D A0 CA    STA   $CAA0
1724-   D3          ???
1725-   D2 A0       CMP   ($A0)
1727-   DF          ???
1728-   DF          ???
1729-   D0 8D       BNE   $16B8
172B-   A0 C8       LDY   #$C8
172D-   C5 D8       CMP   $D8
172F-   A0 B8       LDY   #$B8
1731-   C4 B8       CPY   $B8
1733-   C4 8D       CPY   $8D
1735-   A0 C1       LDY   #$C1
1737-   D3          ???
1738-   C3          ???
1739-   A0 A2       LDY   #$A2
173B-   B2 C4       LDA   ($C4)
173D-   20 C1 D2    JSR   $D2C1
1740-   D2 C1       CMP   ($C1)
1742-   D9 20 C1    CMP   $C120,Y
1745-   C6 D4       DEC   $D4
1747-   C5 D2       CMP   $D2
1749-   20 D0 D5    JSR   $D5D0
174C-   D4          ???
174D-   D4          ???
174E-   C9 CE       CMP   #$CE
1750-   C7          ???
1751-   20 A7 B0    JSR   $B0A7
1754-   B4 A7       LDY   $A7,X
1756-   20 C1 D4    JSR   $D4C1
1759-   20 CC CF    JSR   $CFCC
175C-   C3          ???
175D-   C1 D4       CMP   ($D4,X)
175F-   C9 CF       CMP   #$CF
1761-   CE 20 B2    DEC   $B220
1764-   AC B3 A2    LDY   $A2B3
1767-   8D A0 C8    STA   $C8A0
176A-   C5 D8       CMP   $D8
176C-   A0 B8       LDY   #$B8
176E-   C4 8D       CPY   $8D
1770-   A0 C8       LDY   #$C8
1772-   C5 D8       CMP   $D8
1774-   A0 B0       LDY   #$B0
1776-   B0 8D       BCS   $1705
1778-   A0 CC       LDY   #$CC
177A-   C4 C1       CPY   $C1
177C-   A0 A3       LDY   #$A3
177E-   BE C1 D2    LDX   $D2C1,Y
1781-   D2 C1       CMP   ($C1)
1783-   D9 B2 8D    CMP   $8DB2,Y
1786-   A0 D0       LDY   #$D0
1788-   C8          INY
1789-   C1 8D       CMP   ($8D,X)
178B-   A0 CC       LDY   #$CC
178D-   C4 C1       CPY   $C1
178F-   A0 A3       LDY   #$A3
1791-   BC C1 D2    LDY   $D2C1,X
1794-   D2 C1       CMP   ($C1)
1796-   D9 B2 8D    CMP   $8DB2,Y
1799-   A0 D0       LDY   #$D0
179B-   C8          INY
179C-   C1 8D       CMP   ($8D,X)
179E-   A0 CC       LDY   #$CC
17A0-   C4 C1       CPY   $C1
17A2-   A0 A3       LDY   #$A3
17A4-   B3          ???
17A5-   8D A0 D0    STA   $D0A0
17A8-   C8          INY
17A9-   C1 8D       CMP   ($8D,X)
17AB-   A0 CA       LDY   #$CA
17AD-   D3          ???
17AE-   D2 A0       CMP   ($A0)
17B0-   DF          ???
17B1-   DF          ???
17B2-   C4 D5       CPY   $D5
17B4-   CD D0 8D    CMP   $8DD0
17B7-   A0 CC       LDY   #$CC
17B9-   C4 C1       CPY   $C1
17BB-   A0 A3       LDY   #$A3
17BD-   BE C1 D2    LDX   $D2C1,Y
17C0-   D2 C1       CMP   ($C1)
17C2-   D9 B2 AB    CMP   $ABB2,Y
17C5-   B3          ???
17C6-   8D A0 D0    STA   $D0A0
17C9-   C8          INY
17CA-   C1 8D       CMP   ($8D,X)
17CC-   A0 CC       LDY   #$CC
17CE-   C4 C1       CPY   $C1
17D0-   A0 A3       LDY   #$A3
17D2-   BC C1 D2    LDY   $D2C1,X
17D5-   D2 C1       CMP   ($C1)
17D7-   D9 B2 AB    CMP   $ABB2,Y
17DA-   B3          ???
17DB-   8D A0 D0    STA   $D0A0
17DE-   C8          INY
17DF-   C1 8D       CMP   ($8D,X)
17E1-   A0 CC       LDY   #$CC
17E3-   C4 C1       CPY   $C1
17E5-   A0 A3       LDY   #$A3
17E7-   B4 8D       LDY   $8D,X
17E9-   A0 D0       LDY   #$D0
17EB-   C8          INY
17EC-   C1 8D       CMP   ($8D,X)
17EE-   A0 CA       LDY   #$CA
17F0-   D3          ???
17F1-   D2 A0       CMP   ($A0)
17F3-   DF          ???
17F4-   DF          ???
17F5-   C4 D5       CPY   $D5
17F7-   CD D0 8D    CMP   $8DD0
17FA-   A0 CC       LDY   #$CC
17FC-   C4 C1       CPY   $C1
17FE-   A0 A3       LDY   #$A3
1800-   BE C1 D2    LDX   $D2C1,Y
1803-   D2 C1       CMP   ($C1)
1805-   D9 B2 AB    CMP   $ABB2,Y
1808-   B7          ???
1809-   8D A0 D0    STA   $D0A0
180C-   C8          INY
180D-   C1 8D       CMP   ($8D,X)
180F-   A0 CC       LDY   #$CC
1811-   C4 C1       CPY   $C1
1813-   A0 A3       LDY   #$A3
1815-   BC C1 D2    LDY   $D2C1,X
1818-   D2 C1       CMP   ($C1)
181A-   D9 B2 AB    CMP   $ABB2,Y
181D-   B7          ???
181E-   8D A0 D0    STA   $D0A0
1821-   C8          INY
1822-   C1 8D       CMP   ($8D,X)
1824-   A0 CC       LDY   #$CC
1826-   C4 C1       CPY   $C1
1828-   A0 A3       LDY   #$A3
182A-   B4 8D       LDY   $8D,X
182C-   A0 D0       LDY   #$D0
182E-   C8          INY
182F-   C1 8D       CMP   ($8D,X)
1831-   A0 CA       LDY   #$CA
1833-   D3          ???
1834-   D2 A0       CMP   ($A0)
1836-   DF          ???
1837-   DF          ???
1838-   C4 D5       CPY   $D5
183A-   CD D0 8D    CMP   $8DD0
183D-   A0 CC       LDY   #$CC
183F-   C4 C1       CPY   $C1
1841-   A0 A3       LDY   #$A3
1843-   BE C1 D2    LDX   $D2C1,Y
1846-   D2 C1       CMP   ($C1)
1848-   D9 B2 AB    CMP   $ABB2,Y
184B-   B1 B1       LDA   ($B1),Y
184D-   8D A0 D0    STA   $D0A0
1850-   C8          INY
1851-   C1 8D       CMP   ($8D,X)
1853-   A0 CC       LDY   #$CC
1855-   C4 C1       CPY   $C1
1857-   A0 A3       LDY   #$A3
1859-   BC C1 D2    LDY   $D2C1,X
185C-   D2 C1       CMP   ($C1)
185E-   D9 B2 AB    CMP   $ABB2,Y
1861-   B1 B1       LDA   ($B1),Y
1863-   8D A0 D0    STA   $D0A0
1866-   C8          INY
1867-   C1 8D       CMP   ($8D,X)
1869-   A0 CC       LDY   #$CC
186B-   C4 C1       CPY   $C1
186D-   A0 A3       LDY   #$A3
186F-   B4 8D       LDY   $8D,X
1871-   A0 D0       LDY   #$D0
1873-   C8          INY
1874-   C1 8D       CMP   ($8D,X)
1876-   A0 CA       LDY   #$CA
1878-   D3          ???
1879-   D2 A0       CMP   ($A0)
187B-   DF          ???
187C-   DF          ???
187D-   C4 D5       CPY   $D5
187F-   CD D0 8D    CMP   $8DD0
1882-   A0 CC       LDY   #$CC
1884-   C4 C1       CPY   $C1
1886-   A0 A3       LDY   #$A3
1888-   BE C1 D2    LDX   $D2C1,Y
188B-   D2 C1       CMP   ($C1)
188D-   D9 B2 AB    CMP   $ABB2,Y
1890-   B1 B5       LDA   ($B5),Y
1892-   8D A0 D0    STA   $D0A0
1895-   C8          INY
1896-   C1 8D       CMP   ($8D,X)
1898-   A0 CC       LDY   #$CC
189A-   C4 C1       CPY   $C1
189C-   A0 A3       LDY   #$A3
189E-   BC C1 D2    LDY   $D2C1,X
18A1-   D2 C1       CMP   ($C1)
18A3-   D9 B2 AB    CMP   $ABB2,Y
18A6-   B1 B5       LDA   ($B5),Y
18A8-   8D A0 D0    STA   $D0A0
18AB-   C8          INY
18AC-   C1 8D       CMP   ($8D,X)
18AE-   A0 CC       LDY   #$CC
18B0-   C4 C1       CPY   $C1
18B2-   A0 A3       LDY   #$A3
18B4-   B4 8D       LDY   $8D,X
18B6-   A0 D0       LDY   #$D0
18B8-   C8          INY
18B9-   C1 8D       CMP   ($8D,X)
18BB-   A0 CA       LDY   #$CA
18BD-   D3          ???
18BE-   D2 A0       CMP   ($A0)
18C0-   DF          ???
18C1-   DF          ???
18C2-   C4 D5       CPY   $D5
18C4-   CD D0 8D    CMP   $8DD0
18C7-   A0 CA       LDY   #$CA
18C9-   D3          ???
18CA-   D2 A0       CMP   ($A0)
18CC-   DF          ???
18CD-   DF          ???
18CE-   D7          ???
18CF-   8D AA 8D    STA   $8DAA
18D2-   AA          TAX
18D3-   AA          TAX
18D4-   20 C1 C7    JSR   $C7C1
18D7-   C5 D4       CMP   $D4
18D9-   B8          CLV
18DA-   B2 20       LDA   ($20)
18DC-   C7          ???
18DD-   C5 D4       CMP   $D4
18DF-   D3          ???
18E0-   20 D4 C8    JSR   $C8D4
18E3-   C5 20       CMP   $20
18E5-   CD C5 CD    CMP   $CDC5
18E8-   CF          ???
18E9-   D2 D9       CMP   ($D9)
18EB-   20 CC CF    JSR   $CFCC
18EE-   C3          ???
18EF-   C1 D4       CMP   ($D4,X)
18F1-   C9 CF       CMP   #$CF
18F3-   CE 20 CF    DEC   $CF20
18F6-   C6 20       DEC   $20
18F8-   D4          ???
18F9-   C8          INY
18FA-   C5 20       CMP   $20
18FC-   C5 CC       CMP   $CC
18FE-   C5 CD       CMP   $CD
1900-   C5 CE       CMP   $CE
1902-   D4          ???
1903-   8D AA AA    STA   $AAAA
1906-   20 D3 D4    JSR   $D4D3
1909-   CF          ???
190A-   D2 C5       CMP   ($C5)
190C-   C4 20       CPY   $20
190E-   C1 D4       CMP   ($D4,X)
1910-   20 C9 CE    JSR   $CEC9
1913-   C4 C5       CPY   $C5
1915-   D8          CLD
1916-   20 D8 AC    JSR   $ACD8
1919-   D9 20 C9    CMP   $C920,Y
191C-   CE 20 D4    DEC   $D420
191F-   C8          INY
1920-   C5 20       CMP   $20
1922-   C7          ???
1923-   C9 D6       CMP   #$D6
1925-   C5 CE       CMP   $CE
1927-   20 C1 D2    JSR   $D2C1
192A-   D2 C1       CMP   ($C1)
192C-   D9 D3 20    CMP   $20D3,Y
192F-   C1 CE       CMP   ($CE,X)
1931-   C4 8D       CPY   $8D
1933-   AA          TAX
1934-   AA          TAX
1935-   20 D2 C5    JSR   $C5D2
1938-   D4          ???
1939-   D5 D2       CMP   $D2,X
193B-   CE D3 20    DEC   $20D3
193E-   C9 D4       CMP   #$D4
1940-   20 C9 CE    JSR   $CEC9
1943-   20 D9 20    JSR   $20D9
1946-   A8          TAY
1947-   CC CF D7    CPY   $D7CF
194A-   A9 20       LDA   #$20
194C-   C1 CE       CMP   ($CE,X)
194E-   C4 20       CPY   $20
1950-   D8          CLD
1951-   20 A8 C8    JSR   $C8A8
1954-   C9 C7       CMP   #$C7
1956-   C8          INY
1957-   A9 BB       LDA   #$BB
1959-   20 C4 C1    JSR   $C1C4
195C-   D4          ???
195D-   C1 8D       CMP   ($8D,X)
195F-   AA          TAX
1960-   AA          TAX
1961-   20 C9 CE    JSR   $CEC9
1964-   20 C5 CC    JSR   $CCC5
1967-   C5 CD       CMP   $CD
1969-   C5 CE       CMP   $CE
196B-   D4          ???
196C-   20 C9 D3    JSR   $D3C9
196F-   20 C1 CC    JSR   $CCC1
1972-   D3          ???
1973-   CF          ???
1974-   20 C3 CF    JSR   $CFC3
1977-   D0 C9       BNE   $1942
1979-   C5 C4       CMP   $C4
197B-   20 D4 CF    JSR   $CFD4
197E-   20 DB D2    JSR   $D2DB
1981-   C5 D4       CMP   $D4
1983-   D5 D2       CMP   $D2,X
1985-   CE DD 8D    DEC   $8DDD
1988-   AA          TAX
1989-   8D AA AA    STA   $AAAA
198C-   20 CD C1    JSR   $C1CD
198F-   C3          ???
1990-   D2 CF       CMP   ($CF)
1992-   BA          TSX
1993-   20 C7 C5    JSR   $C5C7
1996-   D4          ???
1997-   B8          CLV
1998-   B2 20       LDA   ($20)
199A-   A4 C1       LDY   $C1
199C-   D2 D2       CMP   ($D2)
199E-   C1 D9       CMP   ($D9,X)
19A0-   DF          ???
19A1-   C1 C4       CMP   ($C4,X)
19A3-   C4 D2       CPY   $D2
19A5-   BB          ???
19A6-   D2 CF       CMP   ($CF)
19A8-   D7          ???
19A9-   DF          ???
19AA-   C9 CE       CMP   #$CE
19AC-   C4 C5       CPY   $C5
19AE-   D8          CLD
19AF-   BB          ???
19B0-   C3          ???
19B1-   CF          ???
19B2-   CC D5 CD    CPY   $CDD5
19B5-   CE DF C9    DEC   $C9DF
19B8-   CE C4 C5    DEC   $C5C4
19BB-   D8          CLD
19BC-   8D AA 8D    STA   $8DAA
19BF-   A0 CC       LDY   #$CC
19C1-   C4 C1       CPY   $C1
19C3-   A0 A3       LDY   #$A3
19C5-   BE C1 D2    LDX   $D2C1,Y
19C8-   D2 C1       CMP   ($C1)
19CA-   D9 B2 8D    CMP   $8DB2,Y
19CD-   A0 D0       LDY   #$D0
19CF-   C8          INY
19D0-   C1 8D       CMP   ($8D,X)
19D2-   A0 CC       LDY   #$CC
19D4-   C4 C1       CPY   $C1
19D6-   A0 A3       LDY   #$A3
19D8-   BC C1 D2    LDY   $D2C1,X
19DB-   D2 C1       CMP   ($C1)
19DD-   D9 B2 8D    CMP   $8DB2,Y
19E0-   A0 D0       LDY   #$D0
19E2-   C8          INY
19E3-   C1 8D       CMP   ($8D,X)
19E5-   A0 CC       LDY   #$CC
19E7-   C4 C1       CPY   $C1
19E9-   A0 A3       LDY   #$A3
19EB-   B2 A0       LDA   ($A0)
19ED-   BB          ???
19EE-   20 D8 20    JSR   $20D8
19F1-   C9 CE       CMP   #$CE
19F3-   C4 C5       CPY   $C5
19F5-   D8          CLD
19F6-   8D A0 D0    STA   $D0A0
19F9-   C8          INY
19FA-   C1 8D       CMP   ($8D,X)
19FC-   A0 CC       LDY   #$CC
19FE-   C4 C1       CPY   $C1
1A00-   A0 A3       LDY   #$A3
1A02-   B3          ???
1A03-   A0 BB       LDY   #$BB
1A05-   20 D9 20    JSR   $20D9
1A08-   C9 CE       CMP   #$CE
1A0A-   C4 C5       CPY   $C5
1A0C-   D8          CLD
1A0D-   8D A0 D0    STA   $D0A0
1A10-   C8          INY
1A11-   C1 8D       CMP   ($8D,X)
1A13-   A0 CA       LDY   #$CA
1A15-   D3          ???
1A16-   D2 A0       CMP   ($A0)
1A18-   C1 C7       CMP   ($C7,X)
1A1A-   C5 D4       CMP   $D4
1A1C-   B8          CLV
1A1D-   B2 8D       LDA   ($8D)
1A1F-   AA          TAX
1A20-   8D A0 CC    STA   $CCA0
1A23-   C4 C1       CPY   $C1
1A25-   A0 D2       LDY   #$D2
1A27-   C5 D4       CMP   $D4
1A29-   D5 D2       CMP   $D2,X
1A2B-   CE 8D A0    DEC   $A08D
1A2E-   CA          DEX
1A2F-   D3          ???
1A30-   D2 A0       CMP   ($A0)
1A32-   DF          ???
1A33-   DF          ???
1A34-   D0 8D       BNE   $19C3
1A36-   A0 C8       LDY   #$C8
1A38-   C5 D8       CMP   $D8
1A3A-   A0 B8       LDY   #$B8
1A3C-   C4 B8       CPY   $B8
1A3E-   C4 8D       CPY   $8D
1A40-   A0 C1       LDY   #$C1
1A42-   D3          ???
1A43-   C3          ???
1A44-   A0 A2       LDY   #$A2
1A46-   D6 C1       DEC   $C1,X
1A48-   CC D5 C5    CPY   $C5D5
1A4B-   20 C1 D4    JSR   $D4C1
1A4E-   20 B2 AC    JSR   $ACB2
1A51-   B3          ???
1A52-   20 D6 C9    JSR   $C9D6
1A55-   C1 20       CMP   ($20,X)
1A57-   C1 C7       CMP   ($C7,X)
1A59-   C5 D4       CMP   $D4
1A5B-   B8          CLV
1A5C-   B2 BA       LDA   ($BA)
1A5E-   20 A2 8D    JSR   $8DA2
1A61-   A0 C8       LDY   #$C8
1A63-   C5 D8       CMP   $D8
1A65-   A0 B0       LDY   #$B0
1A67-   B0 8D       BCS   $19F6
1A69-   A0 CC       LDY   #$CC
1A6B-   C4 C1       CPY   $C1
1A6D-   A0 D2       LDY   #$D2
1A6F-   C5 D4       CMP   $D4
1A71-   D5 D2       CMP   $D2,X
1A73-   CE 8D A0    DEC   $A08D
1A76-   CA          DEX
1A77-   D3          ???
1A78-   D2 A0       CMP   ($A0)
1A7A-   A4 C6       LDY   $C6
1A7C-   C4 C6       CPY   $C6
1A7E-   B0 8D       BCS   $1A0D
1A80-   A0 CA       LDY   #$CA
1A82-   D3          ???
1A83-   D2 A0       CMP   ($A0)
1A85-   DF          ???
1A86-   DF          ???
1A87-   D7          ???
1A88-   8D AA 8D    STA   $8DAA
1A8B-   A0 CA       LDY   #$CA
1A8D-   CD D0 A0    CMP   $A0D0
1A90-   D2 C5       CMP   ($C5)
1A92-   C5 CE       CMP   $CE
1A94-   D4          ???
1A95-   D2 D9       CMP   ($D9)
1A97-   8D AA 8D    STA   $8DAA
1A9A-   AA          TAX
1A9B-   E0 E0       CPX   #$E0
1A9D-   E0 E0       CPX   #$E0
1A9F-   E0 E0       CPX   #$E0
1AA1-   E0 E0       CPX   #$E0
1AA3-   E0 E0       CPX   #$E0
1AA5-   E0 E0       CPX   #$E0
1AA7-   E0 E0       CPX   #$E0
1AA9-   E0 E0       CPX   #$E0
1AAB-   E0 E0       CPX   #$E0
1AAD-   E0 E0       CPX   #$E0
1AAF-   E0 E0       CPX   #$E0
1AB1-   E0 E0       CPX   #$E0
1AB3-   E0 E0       CPX   #$E0
1AB5-   E0 E0       CPX   #$E0
1AB7-   E0 E0       CPX   #$E0
1AB9-   AA          TAX
1ABA-   8D AA 20    STA   $20AA
1ABD-   C2          ???
1ABE-   CF          ???
1ABF-   D4          ???
1AC0-   D4          ???
1AC1-   CF          ???
1AC2-   CD 20 C9    CMP   $C920
1AC5-   CE C3 CC    DEC   $CCC3
1AC8-   D5 C4       CMP   $C4,X
1ACA-   C5 D3       CMP   $D3
1ACC-   20 A8 D2    JSR   $D2A8
1ACF-   CF          ???
1AD0-   D5 D4       CMP   $D4,X
1AD2-   C9 CE       CMP   #$CE
1AD4-   C5 D3       CMP   $D3
1AD6-   A9 20       LDA   #$20
1AD8-   20 20 AA    JSR   $AA20
1ADB-   8D AA AC    STA   $ACAA
1ADE-   AC AC AC    LDY   $ACAC
1AE1-   AC AC AC    LDY   $ACAC
1AE4-   AC AC AC    LDY   $ACAC
1AE7-   AC AC AC    LDY   $ACAC
1AEA-   AC AC AC    LDY   $ACAC
1AED-   AC AC AC    LDY   $ACAC
1AF0-   AC AC AC    LDY   $ACAC
1AF3-   AC AC AC    LDY   $ACAC
1AF6-   AC AC AC    LDY   $ACAC
1AF9-   AC AC AA    LDY   $AAAC
1AFC-   8D AA 8D    STA   $8DAA
1AFF-   A0 D0       LDY   #$D0
1B01-   D5 D4       CMP   $D4,X
1B03-   A0 C1       LDY   #$C1
1B05-   D2 D2       CMP   ($D2)
1B07-   C1 D9       CMP   ($D9,X)
1B09-   D3          ???
1B0A-   B8          CLV
1B0B-   B1 AE       LDA   ($AE),Y
1B0D-   CC C9 C2    CPY   $C2C9
1B10-   8D A0 D0    STA   $D0A0
1B13-   D5 D4       CMP   $D4,X
1B15-   A0 C1       LDY   #$C1
1B17-   D2 D2       CMP   ($D2)
1B19-   C1 D9       CMP   ($D9,X)
1B1B-   D3          ???
1B1C-   B8          CLV
1B1D-   B2 AE       LDA   ($AE)
1B1F-   CC C9 C2    CPY   $C2C9
1B22-   8D A0 D0    STA   $D0A0
1B25-   D5 D4       CMP   $D4,X
1B27-   A0 D2       LDY   #$D2
1B29-   C5 D1       CMP   $D1
1B2B-   D5 C9       CMP   $C9,X
1B2D-   D2 C5       CMP   ($C5)
1B2F-   C4 AE       CPY   $AE
1B31-   CC C9 C2    CPY   $C2C9
1B34-   8D AA 8D    STA   $8DAA
