0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 CD    LDY   $CD20,X
0950-   C1 D4       CMP   ($D4,X)
0952-   C8          INY
0953-   20 20 C4    JSR   $C420
0956-   C5 CD       CMP   $CD
0958-   CF          ???
0959-   20 BE AD    JSR   $ADBE
095C-   20 20 20    JSR   $2020
095F-   20 20 20    JSR   $2020
0962-   20 20 AA    JSR   $AA20
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B2       BCS   $094E
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B1    JSR   $B120
09D4-   B2 AD       LDA   ($AD)
09D6-   C4 C5       CPY   $C5
09D8-   C3          ???
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B8       LDA   ($B8),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 C4    STA   $C4A0
0B02-   D3          ???
0B03-   CB          ???
0B04-   A0 CD       LDY   #$CD
0B06-   C1 D4       CMP   ($D4,X)
0B08-   C8          INY
0B09-   AE C4 C5    LDX   $C5C4
0B0C-   CD CF 8D    CMP   $8DCF
0B0F-   A0 CF       LDY   #$CF
0B11-   C2          ???
0B12-   CA          DEX
0B13-   A0 A4       LDY   #$A4
0B15-   C2          ???
0B16-   C6 C5       DEC   $C5
0B18-   B0 8D       BCS   $0AA7
0B1A-   A0 CF       LDY   #$CF
0B1C-   D2 C7       CMP   ($C7)
0B1E-   A0 A4       LDY   #$A4
0B20-   B6 B0       LDX   $B0,Y
0B22-   B0 B0       BCS   $0AD4
0B24-   8D AA 8D    STA   $8DAA
0B27-   AA          TAX
0B28-   E0 E0       CPX   #$E0
0B2A-   E0 E0       CPX   #$E0
0B2C-   E0 E0       CPX   #$E0
0B2E-   E0 E0       CPX   #$E0
0B30-   E0 E0       CPX   #$E0
0B32-   E0 E0       CPX   #$E0
0B34-   E0 E0       CPX   #$E0
0B36-   E0 E0       CPX   #$E0
0B38-   E0 E0       CPX   #$E0
0B3A-   E0 E0       CPX   #$E0
0B3C-   E0 E0       CPX   #$E0
0B3E-   E0 E0       CPX   #$E0
0B40-   E0 E0       CPX   #$E0
0B42-   E0 E0       CPX   #$E0
0B44-   E0 E0       CPX   #$E0
0B46-   AA          TAX
0B47-   8D AA 20    STA   $20AA
0B4A-   20 D4 CF    JSR   $CFD4
0B4D-   D0 20       BNE   $0B6F
0B4F-   C9 CE       CMP   #$CE
0B51-   C3          ???
0B52-   CC D5 C4    CPY   $C4D5
0B55-   C5 D3       CMP   $D3
0B57-   20 A8 C8    JSR   $C8A8
0B5A-   CF          ???
0B5B-   CF          ???
0B5C-   CB          ???
0B5D-   D3          ???
0B5E-   AC CD C1    LDY   $C1CD
0B61-   C3          ???
0B62-   D2 CF       CMP   ($CF)
0B64-   D3          ???
0B65-   A9 20       LDA   #$20
0B67-   AA          TAX
0B68-   8D AA AC    STA   $ACAA
0B6B-   AC AC AC    LDY   $ACAC
0B6E-   AC AC AC    LDY   $ACAC
0B71-   AC AC AC    LDY   $ACAC
0B74-   AC AC AC    LDY   $ACAC
0B77-   AC AC AC    LDY   $ACAC
0B7A-   AC AC AC    LDY   $ACAC
0B7D-   AC AC AC    LDY   $ACAC
0B80-   AC AC AC    LDY   $ACAC
0B83-   AC AC AC    LDY   $ACAC
0B86-   AC AC AA    LDY   $AAAC
0B89-   8D AA 8D    STA   $8DAA
0B8C-   A0 D0       LDY   #$D0
0B8E-   D5 D4       CMP   $D4,X
0B90-   A0 CD       LDY   #$CD
0B92-   C1 D4       CMP   ($D4,X)
0B94-   C8          INY
0B95-   AE C8 CF    LDX   $CFC8
0B98-   CF          ???
0B99-   CB          ???
0B9A-   D3          ???
0B9B-   8D A0 D5    STA   $D5A0
0B9E-   D3          ???
0B9F-   C5 A0       CMP   $A0
0BA1-   CD C1 D4    CMP   $D4C1
0BA4-   C8          INY
0BA5-   AE CD C1    LDX   $C1CD
0BA8-   C3          ???
0BA9-   8D A0 D0    STA   $D0A0
0BAC-   D5 D4       CMP   $D4,X
0BAE-   A0 D2       LDY   #$D2
0BB0-   C5 D1       CMP   $D1
0BB2-   D5 C9       CMP   $C9,X
0BB4-   D2 C5       CMP   ($C5)
0BB6-   C4 AE       CPY   $AE
0BB8-   C8          INY
0BB9-   CF          ???
0BBA-   CF          ???
0BBB-   CB          ???
0BBC-   D3          ???
0BBD-   8D A0 D5    STA   $D5A0
0BC0-   D3          ???
0BC1-   C5 A0       CMP   $A0
0BC3-   D2 C5       CMP   ($C5)
0BC5-   D1 D5       CMP   ($D5),Y
0BC7-   C9 D2       CMP   #$D2
0BC9-   C5 C4       CMP   $C4
0BCB-   AE CD C1    LDX   $C1CD
0BCE-   C3          ???
0BCF-   8D AA 8D    STA   $8DAA
0BD2-   AA          TAX
0BD3-   E0 E0       CPX   #$E0
0BD5-   E0 E0       CPX   #$E0
0BD7-   E0 E0       CPX   #$E0
0BD9-   E0 E0       CPX   #$E0
0BDB-   E0 E0       CPX   #$E0
0BDD-   E0 E0       CPX   #$E0
0BDF-   E0 E0       CPX   #$E0
0BE1-   E0 E0       CPX   #$E0
0BE3-   E0 E0       CPX   #$E0
0BE5-   E0 E0       CPX   #$E0
0BE7-   E0 E0       CPX   #$E0
0BE9-   E0 E0       CPX   #$E0
0BEB-   E0 E0       CPX   #$E0
0BED-   E0 E0       CPX   #$E0
0BEF-   E0 E0       CPX   #$E0
0BF1-   AA          TAX
0BF2-   8D AA 20    STA   $20AA
0BF5-   20 20 20    JSR   $2020
0BF8-   20 20 D0    JSR   $D020
0BFB-   D2 CF       CMP   ($CF)
0BFD-   C7          ???
0BFE-   D2 C1       CMP   ($C1)
0C00-   CD 20 CD    CMP   $CD20
0C03-   C1 C9       CMP   ($C9,X)
0C05-   CE 20 C2    DEC   $C220
0C08-   CF          ???
0C09-   C4 D9       CPY   $D9
0C0B-   20 20 20    JSR   $2020
0C0E-   20 20 20    JSR   $2020
0C11-   20 AA 8D    JSR   $8DAA
0C14-   AA          TAX
0C15-   AC AC AC    LDY   $ACAC
0C18-   AC AC AC    LDY   $ACAC
0C1B-   AC AC AC    LDY   $ACAC
0C1E-   AC AC AC    LDY   $ACAC
0C21-   AC AC AC    LDY   $ACAC
0C24-   AC AC AC    LDY   $ACAC
0C27-   AC AC AC    LDY   $ACAC
0C2A-   AC AC AC    LDY   $ACAC
0C2D-   AC AC AC    LDY   $ACAC
0C30-   AC AC AC    LDY   $ACAC
0C33-   AA          TAX
0C34-   8D AA 8D    STA   $8DAA
0C37-   A0 CA       LDY   #$CA
0C39-   D3          ???
0C3A-   D2 A0       CMP   ($A0)
0C3C-   A4 C6       LDY   $C6
0C3E-   C3          ???
0C3F-   B5 B8       LDA   $B8,X
0C41-   A0 BB       LDY   #$BB
0C43-   20 C8 CF    JSR   $CFC8
0C46-   CD C5 8D    CMP   $8DC5
0C49-   A0 DF       LDY   #$DF
0C4B-   D0 D2       BNE   $0C1F
0C4D-   CE D4 A0    DEC   $A0D4
0C50-   A2 C9       LDX   #$C9
0C52-   CE D4 C5    DEC   $C5D4
0C55-   C7          ???
0C56-   C5 D2       CMP   $D2
0C58-   20 CD C1    JSR   $C1CD
0C5B-   D4          ???
0C5C-   C8          INY
0C5D-   20 CC C9    JSR   $C9CC
0C60-   C2          ???
0C61-   D2 C1       CMP   ($C1)
0C63-   D2 C9       CMP   ($C9)
0C65-   C5 D3       CMP   $D3
0C67-   20 C1 CE    JSR   $CEC1
0C6A-   C4 A2       CPY   $A2
0C6C-   AC B8 C4    LDY   $C4B8
0C6F-   8D A0 DF    STA   $DFA0
0C72-   D0 D2       BNE   $0C46
0C74-   CE D4 A0    DEC   $A0D4
0C77-   A2 CD       LDX   #$CD
0C79-   C1 C3       CMP   ($C3,X)
0C7B-   D2 CF       CMP   ($CF)
0C7D-   D3          ???
0C7E-   AE 20 20    LDX   $2020
0C81-   20 20 20    JSR   $2020
0C84-   20 20 20    JSR   $2020
0C87-   20 20 20    JSR   $2020
0C8A-   20 20 20    JSR   $2020
0C8D-   20 20 A2    JSR   $A220
0C90-   AC B8 C4    LDY   $C4B8
0C93-   8D A0 DF    STA   $DFA0
0C96-   D0 D2       BNE   $0C6A
0C98-   CE D4 A0    DEC   $A0D4
0C9B-   A2 AD       LDX   #$AD
0C9D-   AD AD AD    LDA   $ADAD
0CA0-   AD AD AD    LDA   $ADAD
0CA3-   AD AD AD    LDA   $ADAD
0CA6-   AD AD AD    LDA   $ADAD
0CA9-   AD AD AD    LDA   $ADAD
0CAC-   AD AD AD    LDA   $ADAD
0CAF-   AD AD AD    LDA   $ADAD
0CB2-   AD AD AD    LDA   $ADAD
0CB5-   A2 AC       LDX   #$AC
0CB7-   B8          CLV
0CB8-   C4 B8       CPY   $B8
0CBA-   C4 8D       CPY   $8D
0CBC-   A0 DF       LDY   #$DF
0CBE-   D0 D2       BNE   $0C92
0CC0-   CE D4 A0    DEC   $A0D4
0CC3-   A2 D4       LDX   #$D4
0CC5-   C8          INY
0CC6-   C5 20       CMP   $20
0CC8-   D2 C1       CMP   ($C1)
0CCA-   CE C4 B8    DEC   $B8C4
0CCD-   20 D2 CF    JSR   $CFD2
0CD0-   D5 D4       CMP   $D4,X
0CD2-   C9 CE       CMP   #$CE
0CD4-   C5 20       CMP   $20
0CD6-   D2 C5       CMP   ($C5)
0CD8-   D4          ???
0CD9-   D5 D2       CMP   $D2,X
0CDB-   CE D3 A2    DEC   $A2D3
0CDE-   AC B8 C4    LDY   $C4B8
0CE1-   8D A0 DF    STA   $DFA0
0CE4-   D0 D2       BNE   $0CB8
0CE6-   CE D4 A0    DEC   $A0D4
0CE9-   A2 C1       LDX   #$C1
0CEB-   20 D0 D3    JSR   $D3D0
0CEE-   C5 D5       CMP   $D5
0CF0-   C4 CF       CPY   $CF
0CF2-   AD D2 C1    LDA   $C1D2
0CF5-   CE C4 CF    DEC   $CFC4
0CF8-   CD 20 D6    CMP   $D620
0CFB-   C1 CC       CMP   ($CC,X)
0CFD-   D5 C5       CMP   $C5,X
0CFF-   20 C2 C5    JSR   $C5C2
0D02-   D4          ???
0D03-   D7          ???
0D04-   C5 C5       CMP   $C5
0D06-   CE A2 AC    DEC   $ACA2
0D09-   B8          CLV
0D0A-   C4 8D       CPY   $8D
0D0C-   A0 DF       LDY   #$DF
0D0E-   D0 D2       BNE   $0CE2
0D10-   CE D4 A0    DEC   $A0D4
0D13-   A2 B1       LDX   #$B1
0D15-   20 C1 CE    JSR   $CEC1
0D18-   C4 20       CPY   $20
0D1A-   B2 B5       LDA   ($B5)
0D1C-   B5 AE       LDA   $AE,X
0D1E-   A2 AC       LDX   #$AC
0D20-   B8          CLV
0D21-   C4 B8       CPY   $B8
0D23-   C4 8D       CPY   $8D
0D25-   A0 CA       LDY   #$CA
0D27-   D3          ???
0D28-   D2 A0       CMP   ($A0)
0D2A-   D2 C1       CMP   ($C1)
0D2C-   CE C4 B8    DEC   $B8C4
0D2F-   8D A0 D3    STA   $D3A0
0D32-   D4          ???
0D33-   C1 A0       CMP   ($A0,X)
0D35-   A4 B3       LDY   $B3
0D37-   B0 B0       BCS   $0CE9
0D39-   8D A0 CA    STA   $CAA0
0D3C-   D3          ???
0D3D-   D2 A0       CMP   ($A0)
0D3F-   D2 C1       CMP   ($C1)
0D41-   CE C4 B8    DEC   $B8C4
0D44-   8D A0 D3    STA   $D3A0
0D47-   D4          ???
0D48-   C1 A0       CMP   ($A0,X)
0D4A-   A4 B3       LDY   $B3
0D4C-   B0 B1       BCS   $0CFF
0D4E-   8D A0 CA    STA   $CAA0
0D51-   D3          ???
0D52-   D2 A0       CMP   ($A0)
0D54-   D2 C1       CMP   ($C1)
0D56-   CE C4 B8    DEC   $B8C4
0D59-   8D A0 D3    STA   $D3A0
0D5C-   D4          ???
0D5D-   C1 A0       CMP   ($A0,X)
0D5F-   A4 B3       LDY   $B3
0D61-   B0 B2       BCS   $0D15
0D63-   8D A0 CA    STA   $CAA0
0D66-   D3          ???
0D67-   D2 A0       CMP   ($A0)
0D69-   D2 C1       CMP   ($C1)
0D6B-   CE C4 B8    DEC   $B8C4
0D6E-   8D A0 D3    STA   $D3A0
0D71-   D4          ???
0D72-   C1 A0       CMP   ($A0,X)
0D74-   A4 B3       LDY   $B3
0D76-   B0 B3       BCS   $0D2B
0D78-   8D A0 CA    STA   $CAA0
0D7B-   D3          ???
0D7C-   D2 A0       CMP   ($A0)
0D7E-   D2 C1       CMP   ($C1)
0D80-   CE C4 B8    DEC   $B8C4
0D83-   8D A0 D3    STA   $D3A0
0D86-   D4          ???
0D87-   C1 A0       CMP   ($A0,X)
0D89-   A4 B3       LDY   $B3
0D8B-   B0 B4       BCS   $0D41
0D8D-   8D A0 DF    STA   $DFA0
0D90-   C4 D5       CPY   $D5
0D92-   CD D0 A0    CMP   $A0D0
0D95-   A4 B3       LDY   $B3
0D97-   B0 B0       BCS   $0D49
0D99-   BB          ???
0D9A-   A3          ???
0D9B-   B5 8D       LDA   $8D,X
0D9D-   A0 DF       LDY   #$DF
0D9F-   D7          ???
0DA0-   C1 C9       CMP   ($C9,X)
0DA2-   D4          ???
0DA3-   8D AA 8D    STA   $8DAA
0DA6-   A0 DF       LDY   #$DF
0DA8-   D0 D2       BNE   $0D7C
0DAA-   CE D4 A0    DEC   $A0D4
0DAD-   A2 20       LDX   #$20
0DAF-   A2 AC       LDX   #$AC
0DB1-   B8          CLV
0DB2-   C4 B8       CPY   $B8
0DB4-   C4 8D       CPY   $8D
0DB6-   A0 DF       LDY   #$DF
0DB8-   D0 D2       BNE   $0D8C
0DBA-   CE D4 A0    DEC   $A0D4
0DBD-   A2 D7       LDX   #$D7
0DBF-   C8          INY
0DC0-   C9 CC       CMP   #$CC
0DC2-   C5 20       CMP   $20
0DC4-   D4          ???
0DC5-   C8          INY
0DC6-   C5 20       CMP   $20
0DC8-   D2 CE       CMP   ($CE)
0DCA-   C4 C2       CPY   $C2
0DCC-   20 CD C1    JSR   $C1CD
0DCF-   C3          ???
0DD0-   D2 CF       CMP   ($CF)
0DD2-   20 D2 C5    JSR   $C5D2
0DD5-   D4          ???
0DD6-   D5 D2       CMP   $D2,X
0DD8-   CE D3 A2    DEC   $A2D3
0DDB-   AC B8 C4    LDY   $C4B8
0DDE-   8D A0 DF    STA   $DFA0
0DE1-   D0 D2       BNE   $0DB5
0DE3-   CE D4 A0    DEC   $A0D4
0DE6-   A2 C1       LDX   #$C1
0DE8-   20 C2 D9    JSR   $D9C2
0DEB-   D4          ???
0DEC-   C5 20       CMP   $20
0DEE-   D6 C1       DEC   $C1,X
0DF0-   CC D5 C5    CPY   $C5D5
0DF3-   20 C2 C5    JSR   $C5C2
0DF6-   D4          ???
0DF7-   D7          ???
0DF8-   C5 C5       CMP   $C5
0DFA-   CE 20 C1    DEC   $C120
0DFD-   20 C7 C9    JSR   $C9C7
0E00-   D6 C5       DEC   $C5,X
0E02-   CE A2 AC    DEC   $ACA2
0E05-   B8          CLV
0E06-   C4 8D       CPY   $8D
0E08-   A0 DF       LDY   #$DF
0E0A-   D0 D2       BNE   $0DDE
0E0C-   CE D4 A0    DEC   $A0D4
0E0F-   A2 CC       LDX   #$CC
0E11-   CF          ???
0E12-   D7          ???
0E13-   20 C1 CE    JSR   $CEC1
0E16-   C4 20       CPY   $20
0E18-   C8          INY
0E19-   C9 C7       CMP   #$C7
0E1B-   C8          INY
0E1C-   20 D6 C1    JSR   $C1D6
0E1F-   CC D5 C5    CPY   $C5D5
0E22-   AE A2 AC    LDX   $ACA2
0E25-   B8          CLV
0E26-   C4 B8       CPY   $B8
0E28-   C4 8D       CPY   $8D
0E2A-   A0 D2       LDY   #$D2
0E2C-   CE C4 C2    DEC   $C2C4
0E2F-   A0 A3       LDY   #$A3
0E31-   A4 C1       LDY   $C1
0E33-   B0 BB       BCS   $0DF0
0E35-   A3          ???
0E36-   A4 C1       LDY   $C1
0E38-   C6 8D       DEC   $8D
0E3A-   A0 D3       LDY   #$D3
0E3C-   D4          ???
0E3D-   C1 A0       CMP   ($A0,X)
0E3F-   A4 B3       LDY   $B3
0E41-   B0 B0       BCS   $0DF3
0E43-   8D A0 D2    STA   $D2A0
0E46-   CE C4 C2    DEC   $C2C4
0E49-   A0 A3       LDY   #$A3
0E4B-   A4 C1       LDY   $C1
0E4D-   B0 BB       BCS   $0E0A
0E4F-   A3          ???
0E50-   A4 C1       LDY   $C1
0E52-   C6 8D       DEC   $8D
0E54-   A0 D3       LDY   #$D3
0E56-   D4          ???
0E57-   C1 A0       CMP   ($A0,X)
0E59-   A4 B3       LDY   $B3
0E5B-   B0 B1       BCS   $0E0E
0E5D-   8D A0 D2    STA   $D2A0
0E60-   CE C4 C2    DEC   $C2C4
0E63-   A0 A3       LDY   #$A3
0E65-   A4 C1       LDY   $C1
0E67-   B0 BB       BCS   $0E24
0E69-   A3          ???
0E6A-   A4 C1       LDY   $C1
0E6C-   C6 8D       DEC   $8D
0E6E-   A0 D3       LDY   #$D3
0E70-   D4          ???
0E71-   C1 A0       CMP   ($A0,X)
0E73-   A4 B3       LDY   $B3
0E75-   B0 B2       BCS   $0E29
0E77-   8D A0 D2    STA   $D2A0
0E7A-   CE C4 C2    DEC   $C2C4
0E7D-   A0 A3       LDY   #$A3
0E7F-   A4 C1       LDY   $C1
0E81-   B0 BB       BCS   $0E3E
0E83-   A3          ???
0E84-   A4 C1       LDY   $C1
0E86-   C6 8D       DEC   $8D
0E88-   A0 D3       LDY   #$D3
0E8A-   D4          ???
0E8B-   C1 A0       CMP   ($A0,X)
0E8D-   A4 B3       LDY   $B3
0E8F-   B0 B3       BCS   $0E44
0E91-   8D A0 D2    STA   $D2A0
0E94-   CE C4 C2    DEC   $C2C4
0E97-   A0 A3       LDY   #$A3
0E99-   A4 C1       LDY   $C1
0E9B-   B0 BB       BCS   $0E58
0E9D-   A3          ???
0E9E-   A4 C1       LDY   $C1
0EA0-   C6 8D       DEC   $8D
0EA2-   A0 D3       LDY   #$D3
0EA4-   D4          ???
0EA5-   C1 A0       CMP   ($A0,X)
0EA7-   A4 B3       LDY   $B3
0EA9-   B0 B4       BCS   $0E5F
0EAB-   8D A0 DF    STA   $DFA0
0EAE-   C4 D5       CPY   $D5
0EB0-   CD D0 A0    CMP   $A0D0
0EB3-   A4 B3       LDY   $B3
0EB5-   B0 B0       BCS   $0E67
0EB7-   BB          ???
0EB8-   A3          ???
0EB9-   B5 8D       LDA   $8D,X
0EBB-   A0 DF       LDY   #$DF
0EBD-   D7          ???
0EBE-   C1 C9       CMP   ($C9,X)
0EC0-   D4          ???
0EC1-   8D AA 8D    STA   $8DAA
0EC4-   A0 DF       LDY   #$DF
0EC6-   D0 D2       BNE   $0E9A
0EC8-   CE D4 A0    DEC   $A0D4
0ECB-   A2 20       LDX   #$20
0ECD-   A2 AC       LDX   #$AC
0ECF-   B8          CLV
0ED0-   C4 B8       CPY   $B8
0ED2-   C4 8D       CPY   $8D
0ED4-   A0 DF       LDY   #$DF
0ED6-   D0 D2       BNE   $0EAA
0ED8-   CE D4 A0    DEC   $A0D4
0EDB-   A2 D4       LDX   #$D4
0EDD-   C8          INY
0EDE-   C5 20       CMP   $20
0EE0-   CD D5 CC    CMP   $CCD5
0EE3-   B8          CLV
0EE4-   20 CD C1    JSR   $C1CD
0EE7-   C3          ???
0EE8-   D2 CF       CMP   ($CF)
0EEA-   20 CD D5    JSR   $D5CD
0EED-   CC D4 C9    CPY   $C9D4
0EF0-   D0 CC       BNE   $0EBE
0EF2-   C9 C5       CMP   #$C5
0EF4-   D3          ???
0EF5-   A2 AC       LDX   #$AC
0EF7-   B8          CLV
0EF8-   C4 8D       CPY   $8D
0EFA-   A0 DF       LDY   #$DF
0EFC-   D0 D2       BNE   $0ED0
0EFE-   CE D4 A0    DEC   $A0D4
0F01-   A2 D4       LDX   #$D4
0F03-   D7          ???
0F04-   CF          ???
0F05-   20 D5 CE    JSR   $CED5
0F08-   D3          ???
0F09-   C9 C7       CMP   #$C7
0F0B-   CE C5 C4    DEC   $C4C5
0F0E-   20 C2 D9    JSR   $D9C2
0F11-   D4          ???
0F12-   C5 D3       CMP   $D3
0F14-   20 C1 CE    JSR   $CEC1
0F17-   C4 20       CPY   $20
0F19-   D2 C5       CMP   ($C5)
0F1B-   D4          ???
0F1C-   D5 D2       CMP   $D2,X
0F1E-   CE D3 A2    DEC   $A2D3
0F21-   AC B8 C4    LDY   $C4B8
0F24-   8D A0 DF    STA   $DFA0
0F27-   D0 D2       BNE   $0EFB
0F29-   CE D4 A0    DEC   $A0D4
0F2C-   A2 C1       LDX   #$C1
0F2E-   20 B1 B6    JSR   $B6B1
0F31-   AD C2 C9    LDA   $C9C2
0F34-   D4          ???
0F35-   20 D2 C5    JSR   $C5D2
0F38-   D3          ???
0F39-   D5 CC       CMP   $CC,X
0F3B-   D4          ???
0F3C-   20 A8 D7    JSR   $D7A8
0F3F-   CF          ???
0F40-   D2 C4       CMP   ($C4)
0F42-   A9 AE       LDA   #$AE
0F44-   A2 AC       LDX   #$AC
0F46-   B8          CLV
0F47-   C4 8D       CPY   $8D
0F49-   A0 DF       LDY   #$DF
0F4B-   D0 D2       BNE   $0F1F
0F4D-   CE D4 A0    DEC   $A0D4
0F50-   A2 CE       LDX   #$CE
0F52-   CF          ???
0F53-   D4          ???
0F54-   C5 20       CMP   $20
0F56-   D4          ???
0F57-   C8          INY
0F58-   C1 D4       CMP   ($D4,X)
0F5A-   20 D4 C8    JSR   $C8D4
0F5D-   C9 D3       CMP   #$D3
0F5F-   20 D2 C5    JSR   $C5D2
0F62-   D3          ???
0F63-   D5 CC       CMP   $CC,X
0F65-   D4          ???
0F66-   20 C9 D3    JSR   $D3C9
0F69-   20 D3 D4    JSR   $D4D3
0F6C-   CF          ???
0F6D-   D2 C5       CMP   ($C5)
0F6F-   C4 A2       CPY   $A2
0F71-   AC B8 C4    LDY   $C4B8
0F74-   8D A0 DF    STA   $DFA0
0F77-   D0 D2       BNE   $0F4B
0F79-   CE D4 A0    DEC   $A0D4
0F7C-   A2 D7       LDX   #$D7
0F7E-   C9 D4       CMP   #$D4
0F80-   C8          INY
0F81-   20 D4 C8    JSR   $C8D4
0F84-   C5 20       CMP   $20
0F86-   CC CF D7    CPY   $D7CF
0F89-   20 C2 D9    JSR   $D9C2
0F8C-   D4          ???
0F8D-   C5 20       CMP   $20
0F8F-   C6 C9       DEC   $C9
0F91-   D2 D3       CMP   ($D3)
0F93-   D4          ???
0F94-   AC 20 D4    LDY   $D420
0F97-   C8          INY
0F98-   C5 CE       CMP   $CE
0F9A-   20 D4 C8    JSR   $C8D4
0F9D-   C5 A2       CMP   $A2
0F9F-   AC B8 C4    LDY   $C4B8
0FA2-   8D A0 DF    STA   $DFA0
0FA5-   D0 D2       BNE   $0F79
0FA7-   CE D4 A0    DEC   $A0D4
0FAA-   A2 C8       LDX   #$C8
0FAC-   C9 C7       CMP   #$C7
0FAE-   C8          INY
0FAF-   20 C2 D9    JSR   $D9C2
0FB2-   D4          ???
0FB3-   C5 AC       CMP   $AC
0FB5-   20 C1 D3    JSR   $D3C1
0FB8-   20 D0 C5    JSR   $C5D0
0FBB-   D2 20       CMP   ($20)
0FBD-   B6 B5       LDX   $B5,Y
0FBF-   B0 B2       BCS   $0F73
0FC1-   20 C3 CF    JSR   $CFC3
0FC4-   CE D6 C5    DEC   $C5D6
0FC7-   CE D4 C9    DEC   $C9D4
0FCA-   CF          ???
0FCB-   CE AE A2    DEC   $A2AE
0FCE-   AC B8 C4    LDY   $C4B8
0FD1-   B8          CLV
0FD2-   C4 8D       CPY   $8D
0FD4-   A0 DF       LDY   #$DF
0FD6-   D0 D2       BNE   $0FAA
0FD8-   CE D4 A0    DEC   $A0D4
0FDB-   A2 BA       LDX   #$BA
0FDD-   BA          TSX
0FDE-   20 CD D5    JSR   $D5CD
0FE1-   CC B8 20    CPY   $20B8
0FE4-   A3          ???
0FE5-   B1 B0       LDA   ($B0),Y
0FE7-   BB          ???
0FE8-   A3          ???
0FE9-   B1 B0       LDA   ($B0),Y
0FEB-   20 D2 C5    JSR   $C5D2
0FEE-   D4          ???
0FEF-   D5 D2       CMP   $D2,X
0FF1-   CE D3 20    DEC   $20D3
0FF4-   A8          TAY
0FF5-   CC AC C8    CPY   $C8AC
0FF8-   A9 BA       LDA   #$BA
0FFA-   A2 AC       LDX   #$AC
0FFC-   B8          CLV
0FFD-   C4 8D       CPY   $8D
0FFF-   A0 CC       LDY   #$CC
1001-   C4 C1       CPY   $C1
1003-   A0 A3       LDY   #$A3
1005-   B1 B0       LDA   ($B0),Y
1007-   8D A0 D3    STA   $D3A0
100A-   D4          ???
100B-   C1 A0       CMP   ($A0,X)
100D-   A4 B3       LDY   $B3
100F-   B0 B0       BCS   $0FC1
1011-   8D A0 CD    STA   $CDA0
1014-   D5 CC       CMP   $CC,X
1016-   B8          CLV
1017-   A0 A3       LDY   #$A3
1019-   B1 B0       LDA   ($B0),Y
101B-   BB          ???
101C-   A4 B3       LDY   $B3
101E-   B0 B0       BCS   $0FD0
1020-   8D A0 DF    STA   $DFA0
1023-   C4 D5       CPY   $D5
1025-   CD D0 A0    CMP   $A0D0
1028-   D2 C5       CMP   ($C5)
102A-   D4          ???
102B-   D5 D2       CMP   $D2,X
102D-   CE BB A3    DEC   $A3BB
1030-   B2 8D       LDA   ($8D)
1032-   A0 DF       LDY   #$DF
1034-   D7          ???
1035-   C1 C9       CMP   ($C9,X)
1037-   D4          ???
1038-   8D A0 DF    STA   $DFA0
103B-   D0 D2       BNE   $100F
103D-   CE D4 A0    DEC   $A0D4
1040-   A2 20       LDX   #$20
1042-   A2 AC       LDX   #$AC
1044-   B8          CLV
1045-   C4 B8       CPY   $B8
1047-   C4 8D       CPY   $8D
1049-   A0 DF       LDY   #$DF
104B-   D0 D2       BNE   $101F
104D-   CE D4 A0    DEC   $A0D4
1050-   A2 BA       LDX   #$BA
1052-   BA          TSX
1053-   20 CD D5    JSR   $D5CD
1056-   CC B8 20    CPY   $20B8
1059-   A3          ???
105A-   B1 B0       LDA   ($B0),Y
105C-   B0 BB       BCS   $1019
105E-   A3          ???
105F-   B1 B0       LDA   ($B0),Y
1061-   B0 20       BCS   $1083
1063-   D2 C5       CMP   ($C5)
1065-   D4          ???
1066-   D5 D2       CMP   $D2,X
1068-   CE D3 20    DEC   $20D3
106B-   A8          TAY
106C-   CC AC C8    CPY   $C8AC
106F-   A9 BA       LDA   #$BA
1071-   A2 AC       LDX   #$AC
1073-   B8          CLV
1074-   C4 8D       CPY   $8D
1076-   A0 CD       LDY   #$CD
1078-   D5 CC       CMP   $CC,X
107A-   B8          CLV
107B-   A0 A3       LDY   #$A3
107D-   B1 B0       LDA   ($B0),Y
107F-   B0 BB       BCS   $103C
1081-   A3          ???
1082-   B1 B0       LDA   ($B0),Y
1084-   B0 8D       BCS   $1013
1086-   A0 DF       LDY   #$DF
1088-   C4 D5       CPY   $D5
108A-   CD D0 A0    CMP   $A0D0
108D-   D2 C5       CMP   ($C5)
108F-   D4          ???
1090-   D5 D2       CMP   $D2,X
1092-   CE BB A3    DEC   $A3BB
1095-   B2 8D       LDA   ($8D)
1097-   A0 DF       LDY   #$DF
1099-   D0 D2       BNE   $106D
109B-   CE D4 A0    DEC   $A0D4
109E-   A2 20       LDX   #$20
10A0-   A2 AC       LDX   #$AC
10A2-   B8          CLV
10A3-   C4 B8       CPY   $B8
10A5-   C4 8D       CPY   $8D
10A7-   A0 DF       LDY   #$DF
10A9-   D7          ???
10AA-   C1 C9       CMP   ($C9,X)
10AC-   D4          ???
10AD-   8D AA 8D    STA   $8DAA
10B0-   A0 DF       LDY   #$DF
10B2-   D0 D2       BNE   $1086
10B4-   CE D4 A0    DEC   $A0D4
10B7-   A2 D4       LDX   #$D4
10B9-   C8          INY
10BA-   C5 20       CMP   $20
10BC-   C4 C9       CPY   $C9
10BE-   D6 B8       DEC   $B8,X
10C0-   20 CD C1    JSR   $C1CD
10C3-   C3          ???
10C4-   D2 CF       CMP   ($CF)
10C6-   20 C4 C9    JSR   $C9C4
10C9-   D6 C9       DEC   $C9,X
10CB-   C4 C5       CPY   $C5
10CD-   D3          ???
10CE-   20 C1 20    JSR   $20C1
10D1-   A2 AC       LDX   #$AC
10D3-   B8          CLV
10D4-   C4 8D       CPY   $8D
10D6-   A0 DF       LDY   #$DF
10D8-   D0 D2       BNE   $10AC
10DA-   CE D4 A0    DEC   $A0D4
10DD-   A2 C4       LDX   #$C4
10DF-   C9 D6       CMP   #$D6
10E1-   C9 C4       CMP   #$C4
10E3-   C5 CE       CMP   $CE
10E5-   C4 20       CPY   $20
10E7-   C2          ???
10E8-   D9 20 C1    CMP   $C120,Y
10EB-   20 C4 C9    JSR   $C9C4
10EE-   D6 C9       DEC   $C9,X
10F0-   D3          ???
10F1-   CF          ???
10F2-   D2 AC       CMP   ($AC)
10F4-   A2 B8       LDX   #$B8
10F6-   C4 8D       CPY   $8D
10F8-   A0 DF       LDY   #$DF
10FA-   D0 D2       BNE   $10CE
10FC-   CE D4 A0    DEC   $A0D4
10FF-   A2 D2       LDX   #$D2
1101-   C5 D4       CMP   $D4
1103-   D5 D2       CMP   $D2,X
1105-   CE C9 CE    DEC   $CEC9
1108-   C7          ???
1109-   20 D4 C8    JSR   $C8D4
110C-   C5 20       CMP   $20
110E-   D1 D5       CMP   ($D5),Y
1110-   CF          ???
1111-   D4          ???
1112-   C9 C5       CMP   #$C5
1114-   CE D4 AE    DEC   $AED4
1117-   A2 AC       LDX   #$AC
1119-   B8          CLV
111A-   C4 8D       CPY   $8D
111C-   A0 DF       LDY   #$DF
111E-   D0 D2       BNE   $10F2
1120-   CE D4 A0    DEC   $A0D4
1123-   A2 C1       LDX   #$C1
1125-   CC CC 20    CPY   $20CC
1128-   D6 C1       DEC   $C1,X
112A-   CC D5 C5    CPY   $C5D5
112D-   D3          ???
112E-   20 C1 D2    JSR   $D2C1
1131-   C5 20       CMP   $20
1133-   D5 CE       CMP   $CE,X
1135-   D3          ???
1136-   C9 C7       CMP   #$C7
1138-   CE C5 C4    DEC   $C4C5
113B-   AE A2 AC    LDX   $ACA2
113E-   B8          CLV
113F-   C4 B8       CPY   $B8
1141-   C4 8D       CPY   $8D
1143-   A0 C4       LDY   #$C4
1145-   C9 D6       CMP   #$D6
1147-   B8          CLV
1148-   A0 A3       LDY   #$A3
114A-   B1 B0       LDA   ($B0),Y
114C-   B0 BB       BCS   $1109
114E-   A3          ???
114F-   B1 B0       LDA   ($B0),Y
1151-   8D A0 DF    STA   $DFA0
1154-   D0 D2       BNE   $1128
1156-   CE D4 A0    DEC   $A0D4
1159-   A2 BA       LDX   #$BA
115B-   BA          TSX
115C-   20 C4 C9    JSR   $C9C4
115F-   D6 B8       DEC   $B8,X
1161-   20 A3 B1    JSR   $B1A3
1164-   B0 B0       BCS   $1116
1166-   BB          ???
1167-   A3          ???
1168-   B1 B0       LDA   ($B0),Y
116A-   20 D2 C5    JSR   $C5D2
116D-   D4          ???
116E-   D5 D2       CMP   $D2,X
1170-   CE D3 BA    DEC   $BAD3
1173-   A2 AC       LDX   #$AC
1175-   B8          CLV
1176-   C4 B8       CPY   $B8
1178-   C4 8D       CPY   $8D
117A-   A0 DF       LDY   #$DF
117C-   C4 D5       CPY   $D5
117E-   CD D0 A0    CMP   $A0D0
1181-   D2 C5       CMP   ($C5)
1183-   D4          ???
1184-   D5 D2       CMP   $D2,X
1186-   CE BB A3    DEC   $A3BB
1189-   B1 8D       LDA   ($8D),Y
118B-   A0 DF       LDY   #$DF
118D-   D7          ???
118E-   C1 C9       CMP   ($C9,X)
1190-   D4          ???
1191-   8D A0 DF    STA   $DFA0
1194-   D0 D2       BNE   $1168
1196-   CE D4 A0    DEC   $A0D4
1199-   A2 BA       LDX   #$BA
119B-   BA          TSX
119C-   C4 C9       CPY   $C9
119E-   D6 B8       DEC   $B8,X
11A0-   20 A3 B2    JSR   $B2A3
11A3-   B0 B0       BCS   $1155
11A5-   BB          ???
11A6-   A3          ???
11A7-   B3          ???
11A8-   B3          ???
11A9-   20 D2 C5    JSR   $C5D2
11AC-   D4          ???
11AD-   D5 D2       CMP   $D2,X
11AF-   CE D3 A2    DEC   $A2D3
11B2-   AC B8 C4    LDY   $C4B8
11B5-   B8          CLV
11B6-   C4 8D       CPY   $8D
11B8-   A0 C4       LDY   #$C4
11BA-   C9 D6       CMP   #$D6
11BC-   B8          CLV
11BD-   A0 A3       LDY   #$A3
11BF-   B2 B0       LDA   ($B0)
11C1-   B0 BB       BCS   $117E
11C3-   A3          ???
11C4-   B3          ???
11C5-   B3          ???
11C6-   8D A0 D3    STA   $D3A0
11C9-   D4          ???
11CA-   D9 A0 A4    CMP   $A4A0,Y
11CD-   B3          ???
11CE-   B0 B0       BCS   $1180
11D0-   A0 BB       LDY   #$BB
11D2-   20 D2 C5    JSR   $C5D2
11D5-   CD C1 C9    CMP   $C9C1
11D8-   CE C4 C5    DEC   $C5C4
11DB-   D2 20       CMP   ($20)
11DD-   C9 CE       CMP   #$CE
11DF-   20 AE D9    JSR   $D9AE
11E2-   8D A0 DF    STA   $DFA0
11E5-   C4 D5       CPY   $D5
11E7-   CD D0 A0    CMP   $A0D0
11EA-   D2 C5       CMP   ($C5)
11EC-   D4          ???
11ED-   D5 D2       CMP   $D2,X
11EF-   CE BB A3    DEC   $A3BB
11F2-   B1 8D       LDA   ($8D),Y
11F4-   A0 DF       LDY   #$DF
11F6-   D0 D2       BNE   $11CA
11F8-   CE D4 A0    DEC   $A0D4
11FB-   A2 20       LDX   #$20
11FD-   A2 AC       LDX   #$AC
11FF-   B8          CLV
1200-   C4 B8       CPY   $B8
1202-   C4 8D       CPY   $8D
1204-   A0 DF       LDY   #$DF
1206-   D0 D2       BNE   $11DA
1208-   CE D4 A0    DEC   $A0D4
120B-   A2 D7       LDX   #$D7
120D-   C9 D4       CMP   #$D4
120F-   C8          INY
1210-   20 C1 20    JSR   $20C1
1213-   D2 C5       CMP   ($C5)
1215-   CD C1 C9    CMP   $C9C1
1218-   CE C4 C5    DEC   $C5C4
121B-   D2 20       CMP   ($20)
121D-   CF          ???
121E-   C6 BA       DEC   $BA
1220-   20 A2 AC    JSR   $ACA2
1223-   B8          CLV
1224-   C4 8D       CPY   $8D
1226-   A0 DF       LDY   #$DF
1228-   C4 D5       CPY   $D5
122A-   CD D0 A0    CMP   $A0D0
122D-   A4 B3       LDY   $B3
122F-   B0 B0       BCS   $11E1
1231-   BB          ???
1232-   A3          ???
1233-   B1 8D       LDA   ($8D),Y
1235-   A0 DF       LDY   #$DF
1237-   D0 D2       BNE   $120B
1239-   CE D4 A0    DEC   $A0D4
123C-   A2 20       LDX   #$20
123E-   A2 AC       LDX   #$AC
1240-   B8          CLV
1241-   C4 B8       CPY   $B8
1243-   C4 8D       CPY   $8D
1245-   A0 DF       LDY   #$DF
1247-   D7          ???
1248-   C1 C9       CMP   ($C9,X)
124A-   D4          ???
124B-   8D AA 8D    STA   $8DAA
124E-   AA          TAX
124F-   AA          TAX
1250-   20 D4 C8    JSR   $C8D4
1253-   C5 20       CMP   $20
1255-   C6 CF       DEC   $CF
1257-   CC CC CF    CPY   $CFCC
125A-   D7          ???
125B-   C9 CE       CMP   #$CE
125D-   C7          ???
125E-   20 C9 D3    JSR   $D3C9
1261-   20 C4 CF    JSR   $CFC4
1264-   CE C5 20    DEC   $20C5
1267-   CA          DEX
1268-   D5 D3       CMP   $D3,X
126A-   D4          ???
126B-   20 D4 CF    JSR   $CFD4
126E-   20 D3 C8    JSR   $C8D3
1271-   CF          ???
1272-   D7          ???
1273-   20 D4 C8    JSR   $C8D4
1276-   C1 D4       CMP   ($D4,X)
1278-   8D AA AA    STA   $AAAA
127B-   20 D4 C8    JSR   $C8D4
127E-   C5 D3       CMP   $D3
1280-   C5 20       CMP   $20
1282-   CD C1 C3    CMP   $C3C1
1285-   D2 CF       CMP   ($CF)
1287-   D3          ???
1288-   20 C1 C3    JSR   $C3C1
128B-   C3          ???
128C-   C5 D0       CMP   $D0
128E-   D4          ???
128F-   20 CC C9    JSR   $C9CC
1292-   D4          ???
1293-   C5 D2       CMP   $D2
1295-   C1 CC       CMP   ($CC,X)
1297-   20 D6 C1    JSR   $C1D6
129A-   CC D5 C5    CPY   $C5D5
129D-   D3          ???
129E-   20 C1 D3    JSR   $D3C1
12A1-   20 D7 C5    JSR   $C5D7
12A4-   CC CC 8D    CPY   $8DCC
12A7-   AA          TAX
12A8-   AA          TAX
12A9-   20 C1 D3    JSR   $D3C1
12AC-   20 D0 CF    JSR   $CFD0
12AF-   C9 CE       CMP   #$CE
12B1-   D4          ???
12B2-   C5 D2       CMP   $D2
12B4-   D3          ???
12B5-   8D AA 8D    STA   $8DAA
12B8-   A0 CC       LDY   #$CC
12BA-   C4 C1       CPY   $C1
12BC-   A0 A3       LDY   #$A3
12BE-   A4 C4       LDY   $C4
12C0-   B0 A0       BCS   $1262
12C2-   BB          ???
12C3-   20 CC CF    JSR   $CFCC
12C6-   C1 C4       CMP   ($C4,X)
12C8-   20 A3 B2    JSR   $B2A3
12CB-   B0 B0       BCS   $127D
12CD-   B0 20       BCS   $12EF
12CF-   C9 CE       CMP   #$CE
12D1-   D4          ???
12D2-   CF          ???
12D3-   20 A4 B3    JSR   $B3A4
12D6-   B0 B0       BCS   $1288
12D8-   8D A0 D3    STA   $D3A0
12DB-   D4          ???
12DC-   C1 A0       CMP   ($A0,X)
12DE-   A4 B3       LDY   $B3
12E0-   B0 B0       BCS   $1292
12E2-   8D A0 CC    STA   $CCA0
12E5-   C4 C1       CPY   $C1
12E7-   A0 A3       LDY   #$A3
12E9-   A4 B0       LDY   $B0
12EB-   B7          ???
12EC-   8D A0 D3    STA   $D3A0
12EF-   D4          ???
12F0-   C1 A0       CMP   ($A0,X)
12F2-   A4 B3       LDY   $B3
12F4-   B0 B1       BCS   $12A7
12F6-   8D A0 CC    STA   $CCA0
12F9-   C4 C1       CPY   $C1
12FB-   A0 A3       LDY   #$A3
12FD-   A4 C2       LDY   $C2
12FF-   B8          CLV
1300-   8D A0 D3    STA   $D3A0
1303-   D4          ???
1304-   C1 A0       CMP   ($A0,X)
1306-   A4 B3       LDY   $B3
1308-   B0 B2       BCS   $12BC
130A-   8D A0 CC    STA   $CCA0
130D-   C4 C1       CPY   $C1
130F-   A0 A3       LDY   #$A3
1311-   A4 B0       LDY   $B0
1313-   C2          ???
1314-   8D A0 D3    STA   $D3A0
1317-   D4          ???
1318-   C1 A0       CMP   ($A0,X)
131A-   A4 B3       LDY   $B3
131C-   B0 B3       BCS   $12D1
131E-   8D A0 C1    STA   $C1A0
1321-   C4 C4       CPY   $C4
1323-   B1 B6       LDA   ($B6),Y
1325-   A0 A4       LDY   #$A4
1327-   B3          ???
1328-   B0 B0       BCS   $12DA
132A-   BB          ???
132B-   A3          ???
132C-   B3          ???
132D-   B0 B0       BCS   $12DF
132F-   B0 8D       BCS   $12BE
1331-   A0 DF       LDY   #$DF
1333-   D0 D2       BNE   $1307
1335-   CE D4 A0    DEC   $A0D4
1338-   A2 20       LDX   #$20
133A-   A2 AC       LDX   #$AC
133C-   B8          CLV
133D-   C4 B8       CPY   $B8
133F-   C4 8D       CPY   $8D
1341-   A0 DF       LDY   #$DF
1343-   D0 D2       BNE   $1317
1345-   CE D4 A0    DEC   $A0D4
1348-   A2 D4       LDX   #$D4
134A-   C8          INY
134B-   C5 20       CMP   $20
134D-   C1 C4       CMP   ($C4,X)
134F-   C4 B1       CPY   $B1
1351-   B6 20       LDX   $20,Y
1353-   CD C1 C3    CMP   $C3C1
1356-   D2 CF       CMP   ($CF)
1358-   20 C1 C4    JSR   $C4C1
135B-   C4 D3       CPY   $D3
135D-   20 D4 D7    JSR   $D7D4
1360-   CF          ???
1361-   A2 AC       LDX   #$AC
1363-   B8          CLV
1364-   C4 8D       CPY   $8D
1366-   A0 DF       LDY   #$DF
1368-   D0 D2       BNE   $133C
136A-   CE D4 A0    DEC   $A0D4
136D-   A2 B1       LDX   #$B1
136F-   B6 AD       LDX   $AD,Y
1371-   C2          ???
1372-   C9 D4       CMP   #$D4
1374-   20 D6 C1    JSR   $C1D6
1377-   CC D5 C5    CPY   $C5D5
137A-   D3          ???
137B-   AC 20 D3    LDY   $D320
137E-   C9 C7       CMP   #$C7
1380-   CE C5 C4    DEC   $C4C5
1383-   20 CF D2    JSR   $D2CF
1386-   20 D5 CE    JSR   $CED5
1389-   D3          ???
138A-   C9 C7       CMP   #$C7
138C-   CE C5 C4    DEC   $C4C5
138F-   AE A2 AC    LDX   $ACA2
1392-   B8          CLV
1393-   C4 B8       CPY   $B8
1395-   C4 8D       CPY   $8D
1397-   A0 DF       LDY   #$DF
1399-   D0 D2       BNE   $136D
139B-   CE D4 A0    DEC   $A0D4
139E-   A2 C1       LDX   #$C1
13A0-   C4 C4       CPY   $C4
13A2-   B1 B6       LDA   ($B6),Y
13A4-   20 A3 B3    JSR   $B3A3
13A7-   B0 B0       BCS   $1359
13A9-   B0 BB       BCS   $1366
13AB-   A3          ???
13AC-   B2 B0       LDA   ($B0)
13AE-   B0 B0       BCS   $1360
13B0-   20 D2 C5    JSR   $C5D2
13B3-   D4          ???
13B4-   D5 D2       CMP   $D2,X
13B6-   CE D3 BA    DEC   $BAD3
13B9-   20 A2 AC    JSR   $ACA2
13BC-   B8          CLV
13BD-   C4 B8       CPY   $B8
13BF-   C4 8D       CPY   $8D
13C1-   A0 DF       LDY   #$DF
13C3-   C4 D5       CPY   $D5
13C5-   CD D0 A0    CMP   $A0D0
13C8-   D2 C5       CMP   ($C5)
13CA-   D4          ???
13CB-   D5 D2       CMP   $D2,X
13CD-   CE BB D2    DEC   $D2BB
13D0-   C5 D4       CMP   $D4
13D2-   CC C5 CE    CPY   $CEC5
13D5-   8D A0 DF    STA   $DFA0
13D8-   D0 D2       BNE   $13AC
13DA-   CE D4 A0    DEC   $A0D4
13DD-   A2 20       LDX   #$20
13DF-   A2 AC       LDX   #$AC
13E1-   B8          CLV
13E2-   C4 B8       CPY   $B8
13E4-   C4 8D       CPY   $8D
13E6-   A0 DF       LDY   #$DF
13E8-   D7          ???
13E9-   C1 C9       CMP   ($C9,X)
13EB-   D4          ???
13EC-   8D AA 8D    STA   $8DAA
13EF-   A0 DF       LDY   #$DF
13F1-   D0 D2       BNE   $13C5
13F3-   CE D4 A0    DEC   $A0D4
13F6-   A2 20       LDX   #$20
13F8-   A2 AC       LDX   #$AC
13FA-   B8          CLV
13FB-   C4 B8       CPY   $B8
13FD-   C4 8D       CPY   $8D
13FF-   A0 DF       LDY   #$DF
1401-   D0 D2       BNE   $13D5
1403-   CE D4 A0    DEC   $A0D4
1406-   A2 D4       LDX   #$D4
1408-   C8          INY
1409-   C5 20       CMP   $20
140B-   D3          ???
140C-   D5 C2       CMP   $C2,X
140E-   B1 B6       LDA   ($B6),Y
1410-   20 CD C1    JSR   $C1CD
1413-   C3          ???
1414-   D2 CF       CMP   ($CF)
1416-   20 D3 D5    JSR   $D5D3
1419-   C2          ???
141A-   D4          ???
141B-   D2 C1       CMP   ($C1)
141D-   C3          ???
141E-   D4          ???
141F-   D3          ???
1420-   20 CF CE    JSR   $CECF
1423-   C5 A2       CMP   $A2
1425-   AC B8 C4    LDY   $C4B8
1428-   8D A0 DF    STA   $DFA0
142B-   D0 D2       BNE   $13FF
142D-   CE D4 A0    DEC   $A0D4
1430-   A2 B1       LDX   #$B1
1432-   B6 AD       LDX   $AD,Y
1434-   C2          ???
1435-   C9 D4       CMP   #$D4
1437-   20 CE D5    JSR   $D5CE
143A-   CD C2 C5    CMP   $C5C2
143D-   D2 20       CMP   ($20)
143F-   C6 D2       DEC   $D2
1441-   CF          ???
1442-   CD 20 C1    CMP   $C120
1445-   CE CF D4    DEC   $D4CF
1448-   C8          INY
1449-   C5 D2       CMP   $D2
144B-   AE A2 AC    LDX   $ACA2
144E-   B8          CLV
144F-   C4 B8       CPY   $B8
1451-   C4 8D       CPY   $8D
1453-   A0 DF       LDY   #$DF
1455-   D0 D2       BNE   $1429
1457-   CE D4 A0    DEC   $A0D4
145A-   A2 C3       LDX   #$C3
145C-   C1 CC       CMP   ($CC,X)
145E-   C3          ???
145F-   D5 CC       CMP   $CC,X
1461-   C1 D4       CMP   ($D4,X)
1463-   C5 C4       CMP   $C4
1465-   20 CC C5    JSR   $C5CC
1468-   C6 D4       DEC   $D4
146A-   20 D4 CF    JSR   $CFD4
146D-   20 D2 C9    JSR   $C9D2
1470-   C7          ???
1471-   C8          INY
1472-   D4          ???
1473-   AC 20 CC    LDY   $CC20
1476-   AD D2 AE    LDA   $AED2
1479-   A2 AC       LDX   #$AC
147B-   B8          CLV
147C-   C4 8D       CPY   $8D
147E-   A0 DF       LDY   #$DF
1480-   D0 D2       BNE   $1454
1482-   CE D4 A0    DEC   $A0D4
1485-   A2 D3       LDX   #$D3
1487-   C9 C7       CMP   #$C7
1489-   CE C5 C4    DEC   $C4C5
148C-   20 CF D2    JSR   $D2CF
148F-   20 D5 CE    JSR   $CED5
1492-   D3          ???
1493-   C9 C7       CMP   #$C7
1495-   CE C5 C4    DEC   $C4C5
1498-   AE A2 AC    LDX   $ACA2
149B-   B8          CLV
149C-   C4 B8       CPY   $B8
149E-   C4 8D       CPY   $8D
14A0-   A0 DF       LDY   #$DF
14A2-   D0 D2       BNE   $1476
14A4-   CE D4 A0    DEC   $A0D4
14A7-   A2 D3       LDX   #$D3
14A9-   D5 C2       CMP   $C2,X
14AB-   B1 B6       LDA   ($B6),Y
14AD-   20 A3 B5    JSR   $B5A3
14B0-   B0 B0       BCS   $1462
14B2-   B0 BB       BCS   $146F
14B4-   A3          ???
14B5-   B3          ???
14B6-   B0 B0       BCS   $1468
14B8-   B0 20       BCS   $14DA
14BA-   D2 C5       CMP   ($C5)
14BC-   D4          ???
14BD-   D5 D2       CMP   $D2,X
14BF-   CE D3 BA    DEC   $BAD3
14C2-   20 A2 AC    JSR   $ACA2
14C5-   B8          CLV
14C6-   C4 B8       CPY   $B8
14C8-   C4 8D       CPY   $8D
14CA-   A0 D3       LDY   #$D3
14CC-   D5 C2       CMP   $C2,X
14CE-   B1 B6       LDA   ($B6),Y
14D0-   A0 A3       LDY   #$A3
14D2-   B5 B0       LDA   $B0,X
14D4-   B0 B0       BCS   $1486
14D6-   BB          ???
14D7-   A3          ???
14D8-   B3          ???
14D9-   B0 B0       BCS   $148B
14DB-   B0 A0       BCS   $147D
14DD-   BB          ???
14DE-   20 B5 B0    JSR   $B0B5
14E1-   B0 B0       BCS   $1493
14E3-   20 AD 20    JSR   $20AD
14E6-   B3          ???
14E7-   B0 B0       BCS   $1499
14E9-   B0 8D       BCS   $1478
14EB-   A0 DF       LDY   #$DF
14ED-   C4 D5       CPY   $D5
14EF-   CD D0 A0    CMP   $A0D0
14F2-   D2 C5       CMP   ($C5)
14F4-   D4          ???
14F5-   D5 D2       CMP   $D2,X
14F7-   CE BB D2    DEC   $D2BB
14FA-   C5 D4       CMP   $D4
14FC-   CC C5 CE    CPY   $CEC5
14FF-   8D A0 DF    STA   $DFA0
1502-   D0 D2       BNE   $14D6
1504-   CE D4 A0    DEC   $A0D4
1507-   A2 20       LDX   #$20
1509-   A2 AC       LDX   #$AC
150B-   B8          CLV
150C-   C4 B8       CPY   $B8
150E-   C4 8D       CPY   $8D
1510-   A0 DF       LDY   #$DF
1512-   D7          ???
1513-   C1 C9       CMP   ($C9,X)
1515-   D4          ???
1516-   8D AA 8D    STA   $8DAA
1519-   A0 DF       LDY   #$DF
151B-   D0 D2       BNE   $14EF
151D-   CE D4 A0    DEC   $A0D4
1520-   A2 D4       LDX   #$D4
1522-   C8          INY
1523-   C5 20       CMP   $20
1525-   CD D5 CC    CMP   $CCD5
1528-   B1 B6       LDA   ($B6),Y
152A-   20 CD C1    JSR   $C1CD
152D-   C3          ???
152E-   D2 CF       CMP   ($CF)
1530-   20 CD D5    JSR   $D5CD
1533-   CC D4 C9    CPY   $C9D4
1536-   D0 CC       BNE   $1504
1538-   C9 C5       CMP   #$C5
153A-   D3          ???
153B-   20 D4 D7    JSR   $D7D4
153E-   CF          ???
153F-   A2 AC       LDX   #$AC
1541-   B8          CLV
1542-   C4 8D       CPY   $8D
1544-   A0 DF       LDY   #$DF
1546-   D0 D2       BNE   $151A
1548-   CE D4 A0    DEC   $A0D4
154B-   A2 B1       LDX   #$B1
154D-   B6 AD       LDX   $AD,Y
154F-   C2          ???
1550-   C9 D4       CMP   #$D4
1552-   20 CE D5    JSR   $D5CE
1555-   CD C2 C5    CMP   $C5C2
1558-   D2 D3       CMP   ($D3)
155A-   AC 20 D3    LDY   $D320
155D-   C9 C7       CMP   #$C7
155F-   CE C5 C4    DEC   $C4C5
1562-   20 CF D2    JSR   $D2CF
1565-   20 CE CF    JSR   $CFCE
1568-   D4          ???
1569-   AE A2 AC    LDX   $ACA2
156C-   B8          CLV
156D-   C4 B8       CPY   $B8
156F-   C4 8D       CPY   $8D
1571-   A0 DF       LDY   #$DF
1573-   D0 D2       BNE   $1547
1575-   CE D4 A0    DEC   $A0D4
1578-   A2 CD       LDX   #$CD
157A-   D5 CC       CMP   $CC,X
157C-   B1 B6       LDA   ($B6),Y
157E-   20 A3 B5    JSR   $B5A3
1581-   B0 B0       BCS   $1533
1583-   BB          ???
1584-   A3          ???
1585-   B5 B0       LDA   $B0,X
1587-   B0 20       BCS   $15A9
1589-   D2 C5       CMP   ($C5)
158B-   D4          ???
158C-   D5 D2       CMP   $D2,X
158E-   CE D3 BA    DEC   $BAD3
1591-   20 A2 AC    JSR   $ACA2
1594-   B8          CLV
1595-   C4 B8       CPY   $B8
1597-   C4 8D       CPY   $8D
1599-   A0 CD       LDY   #$CD
159B-   D5 CC       CMP   $CC,X
159D-   B1 B6       LDA   ($B6),Y
159F-   A0 A3       LDY   #$A3
15A1-   B5 B0       LDA   $B0,X
15A3-   B0 BB       BCS   $1560
15A5-   A3          ???
15A6-   B5 B0       LDA   $B0,X
15A8-   B0 8D       BCS   $1537
15AA-   A0 DF       LDY   #$DF
15AC-   C4 D5       CPY   $D5
15AE-   CD D0 A0    CMP   $A0D0
15B1-   D2 C5       CMP   ($C5)
15B3-   D4          ???
15B4-   D5 D2       CMP   $D2,X
15B6-   CE BB D2    DEC   $D2BB
15B9-   C5 D4       CMP   $D4
15BB-   CC C5 CE    CPY   $CEC5
15BE-   8D A0 DF    STA   $DFA0
15C1-   D0 D2       BNE   $1595
15C3-   CE D4 A0    DEC   $A0D4
15C6-   A2 20       LDX   #$20
15C8-   A2 AC       LDX   #$AC
15CA-   B8          CLV
15CB-   C4 B8       CPY   $B8
15CD-   C4 8D       CPY   $8D
15CF-   A0 DF       LDY   #$DF
15D1-   D7          ???
15D2-   C1 C9       CMP   ($C9,X)
15D4-   D4          ???
15D5-   8D AA 8D    STA   $8DAA
15D8-   A0 DF       LDY   #$DF
15DA-   D0 D2       BNE   $15AE
15DC-   CE D4 A0    DEC   $A0D4
15DF-   A2 C1       LDX   #$C1
15E1-   CE C4 20    DEC   $20C4
15E4-   D4          ???
15E5-   C8          INY
15E6-   C5 20       CMP   $20
15E8-   C4 C9       CPY   $C9
15EA-   D6 B1       DEC   $B1,X
15EC-   B6 20       LDX   $20,Y
15EE-   CD C1 C3    CMP   $C3C1
15F1-   D2 CF       CMP   ($CF)
15F3-   20 C4 C9    JSR   $C9C4
15F6-   D6 C9       DEC   $C9,X
15F8-   C4 C5       CPY   $C5
15FA-   D3          ???
15FB-   20 D4 C8    JSR   $C8D4
15FE-   C5 A2       CMP   $A2
1600-   AC B8 C4    LDY   $C4B8
1603-   8D A0 DF    STA   $DFA0
1606-   D0 D2       BNE   $15DA
1608-   CE D4 A0    DEC   $A0D4
160B-   A2 C6       LDX   #$C6
160D-   C9 D2       CMP   #$D2
160F-   D3          ???
1610-   D4          ???
1611-   20 D0 C1    JSR   $C1D0
1614-   D2 C1       CMP   ($C1)
1616-   CD C5 D4    CMP   $D4C5
1619-   C5 D2       CMP   $D2
161B-   20 C2 D9    JSR   $D9C2
161E-   20 D4 C8    JSR   $C8D4
1621-   C5 20       CMP   $20
1623-   D3          ???
1624-   C5 C3       CMP   $C3
1626-   CF          ???
1627-   CE C4 AE    DEC   $AEC4
162A-   A2 AC       LDX   #$AC
162C-   B8          CLV
162D-   C4 B8       CPY   $B8
162F-   C4 8D       CPY   $8D
1631-   A0 DF       LDY   #$DF
1633-   D0 D2       BNE   $1607
1635-   CE D4 A0    DEC   $A0D4
1638-   A2 C9       LDX   #$C9
163A-   C6 20       DEC   $20
163C-   D4          ???
163D-   C8          INY
163E-   C5 20       CMP   $20
1640-   D4          ???
1641-   C8          INY
1642-   C9 D2       CMP   #$D2
1644-   C4 20       CPY   $20
1646-   D0 C1       BNE   $1609
1648-   D2 C1       CMP   ($C1)
164A-   CD C5 D4    CMP   $D4C5
164D-   C5 D2       CMP   $D2
164F-   20 C9 D3    JSR   $D3C9
1652-   A2 AC       LDX   #$AC
1654-   B8          CLV
1655-   C4 8D       CPY   $8D
1657-   A0 DF       LDY   #$DF
1659-   D0 D2       BNE   $162D
165B-   CE D4 A0    DEC   $A0D4
165E-   A2 C1       LDX   #$C1
1660-   CE 20 D3    DEC   $D320
1663-   AC 20 D4    LDY   $D420
1666-   C8          INY
1667-   C5 CE       CMP   $CE
1669-   20 D4 C8    JSR   $C8D4
166C-   C5 20       CMP   $20
166E-   C4 C9       CPY   $C9
1670-   D6 C9       DEC   $C9,X
1672-   D3          ???
1673-   C9 CF       CMP   #$CF
1675-   CE 20 C9    DEC   $C920
1678-   D3          ???
1679-   20 D3 C9    JSR   $C9D3
167C-   C7          ???
167D-   CE C5 C4    DEC   $C4C5
1680-   BB          ???
1681-   A2 AC       LDX   #$AC
1683-   B8          CLV
1684-   C4 8D       CPY   $8D
1686-   A0 DF       LDY   #$DF
1688-   D0 D2       BNE   $165C
168A-   CE D4 A0    DEC   $A0D4
168D-   A2 CF       LDX   #$CF
168F-   D4          ???
1690-   C8          INY
1691-   C5 D2       CMP   $D2
1693-   D7          ???
1694-   C9 D3       CMP   #$D3
1696-   C5 AC       CMP   $AC
1698-   20 C9 D4    JSR   $D4C9
169B-   20 C9 D3    JSR   $D3C9
169E-   20 D5 CE    JSR   $CED5
16A1-   D3          ???
16A2-   C9 C7       CMP   #$C7
16A4-   CE C5 C4    DEC   $C4C5
16A7-   AE A2 AC    LDX   $ACA2
16AA-   B8          CLV
16AB-   C4 B8       CPY   $B8
16AD-   C4 8D       CPY   $8D
16AF-   A0 DF       LDY   #$DF
16B1-   D0 D2       BNE   $1685
16B3-   CE D4 A0    DEC   $A0D4
16B6-   A2 C4       LDX   #$C4
16B8-   C9 D6       CMP   #$D6
16BA-   B1 B6       LDA   ($B6),Y
16BC-   20 A3 B2    JSR   $B2A3
16BF-   B5 B0       LDA   $B0,X
16C1-   B0 B0       BCS   $1673
16C3-   BB          ???
16C4-   A3          ???
16C5-   B5 B0       LDA   $B0,X
16C7-   B0 BB       BCS   $1684
16C9-   D5 20       CMP   $20,X
16CB-   D2 C5       CMP   ($C5)
16CD-   D4          ???
16CE-   D5 D2       CMP   $D2,X
16D0-   CE D3 BA    DEC   $BAD3
16D3-   A2 AC       LDX   #$AC
16D5-   B8          CLV
16D6-   C4 B8       CPY   $B8
16D8-   C4 8D       CPY   $8D
16DA-   A0 C4       LDY   #$C4
16DC-   C9 D6       CMP   #$D6
16DE-   B1 B6       LDA   ($B6),Y
16E0-   A0 A3       LDY   #$A3
16E2-   B2 B5       LDA   ($B5)
16E4-   B0 B0       BCS   $1696
16E6-   B0 BB       BCS   $16A3
16E8-   A3          ???
16E9-   B5 B0       LDA   $B0,X
16EB-   B0 BB       BCS   $16A8
16ED-   D5 8D       CMP   $8D,X
16EF-   A0 DF       LDY   #$DF
16F1-   C4 D5       CPY   $D5
16F3-   CD D0 A0    CMP   $A0D0
16F6-   D2 C5       CMP   ($C5)
16F8-   D4          ???
16F9-   D5 D2       CMP   $D2,X
16FB-   CE BB D2    DEC   $D2BB
16FE-   C5 D4       CMP   $D4
1700-   CC C5 CE    CPY   $CEC5
1703-   8D A0 DF    STA   $DFA0
1706-   D0 D2       BNE   $16DA
1708-   CE D4 A0    DEC   $A0D4
170B-   A2 20       LDX   #$20
170D-   A2 AC       LDX   #$AC
170F-   B8          CLV
1710-   C4 B8       CPY   $B8
1712-   C4 8D       CPY   $8D
1714-   A0 DF       LDY   #$DF
1716-   D7          ???
1717-   C1 C9       CMP   ($C9,X)
1719-   D4          ???
171A-   8D AA 8D    STA   $8DAA
171D-   A0 DF       LDY   #$DF
171F-   D0 D2       BNE   $16F3
1721-   CE D4 A0    DEC   $A0D4
1724-   A2 D4       LDX   #$D4
1726-   C8          INY
1727-   C5 20       CMP   $20
1729-   D2 C5       CMP   ($C5)
172B-   CD B1 B6    CMP   $B6B1
172E-   20 CD C1    JSR   $C1CD
1731-   C3          ???
1732-   D2 CF       CMP   ($CF)
1734-   20 CC C9    JSR   $C9CC
1737-   CB          ???
1738-   C5 D7       CMP   $D7
173A-   C9 D3       CMP   #$D3
173C-   C5 20       CMP   $20
173E-   C3          ???
173F-   C1 CC       CMP   ($CC,X)
1741-   C3          ???
1742-   D5 CC       CMP   $CC,X
1744-   C1 D4       CMP   ($D4,X)
1746-   C5 D3       CMP   $D3
1748-   A2 AC       LDX   #$AC
174A-   B8          CLV
174B-   C4 8D       CPY   $8D
174D-   A0 DF       LDY   #$DF
174F-   D0 D2       BNE   $1723
1751-   CE D4 A0    DEC   $A0D4
1754-   A2 D4       LDX   #$D4
1756-   C8          INY
1757-   C5 20       CMP   $20
1759-   D2 C5       CMP   ($C5)
175B-   CD C1 C9    CMP   $C9C1
175E-   CE C4 C5    DEC   $C5C4
1761-   D2 20       CMP   ($20)
1763-   CF          ???
1764-   C6 20       DEC   $20
1766-   C1 20       CMP   ($20,X)
1768-   B1 B6       LDA   ($B6),Y
176A-   AD C2 C9    LDA   $C9C2
176D-   D4          ???
176E-   20 C4 C9    JSR   $C9C4
1771-   D6 C9       DEC   $C9,X
1773-   D3          ???
1774-   C9 CF       CMP   #$CF
1776-   CE AE A2    DEC   $A2AE
1779-   AC B8 C4    LDY   $C4B8
177C-   8D A0 DF    STA   $DFA0
177F-   D0 D2       BNE   $1753
1781-   CE D4 A0    DEC   $A0D4
1784-   A2 C9       LDX   #$C9
1786-   D4          ???
1787-   20 C1 CC    JSR   $CCC1
178A-   D3          ???
178B-   CF          ???
178C-   20 D5 D3    JSR   $D3D5
178F-   C5 D3       CMP   $D3
1791-   20 D4 C8    JSR   $C8D4
1794-   C5 20       CMP   $20
1796-   D4          ???
1797-   C8          INY
1798-   C9 D2       CMP   #$D2
179A-   C4 20       CPY   $20
179C-   D0 C1       BNE   $175F
179E-   D2 C1       CMP   ($C1)
17A0-   CD C5 D4    CMP   $D4C5
17A3-   C5 D2       CMP   $D2
17A5-   20 D4 CF    JSR   $CFD4
17A8-   A2 AC       LDX   #$AC
17AA-   B8          CLV
17AB-   C4 8D       CPY   $8D
17AD-   A0 DF       LDY   #$DF
17AF-   D0 D2       BNE   $1783
17B1-   CE D4 A0    DEC   $A0D4
17B4-   A2 D3       LDX   #$D3
17B6-   C9 C7       CMP   #$C7
17B8-   CE C9 C6    DEC   $C6C9
17BB-   D9 20 D7    CMP   $D720,Y
17BE-   C8          INY
17BF-   C5 D4       CMP   $D4
17C1-   C8          INY
17C2-   C5 D2       CMP   $D2
17C4-   20 C9 D4    JSR   $D4C9
17C7-   20 C9 D3    JSR   $D3C9
17CA-   20 D3 C9    JSR   $C9D3
17CD-   C7          ???
17CE-   CE C5 C4    DEC   $C4C5
17D1-   20 A8 D3    JSR   $D3A8
17D4-   A9 AE       LDA   #$AE
17D6-   A2 AC       LDX   #$AC
17D8-   B8          CLV
17D9-   C4 B8       CPY   $B8
17DB-   C4 8D       CPY   $8D
17DD-   A0 DF       LDY   #$DF
17DF-   D0 D2       BNE   $17B3
17E1-   CE D4 A0    DEC   $A0D4
17E4-   A2 D2       LDX   #$D2
17E6-   C5 CD       CMP   $CD
17E8-   B1 B6       LDA   ($B6),Y
17EA-   20 A3 B5    JSR   $B5A3
17ED-   B0 B0       BCS   $179F
17EF-   B0 BB       BCS   $17AC
17F1-   A3          ???
17F2-   B3          ???
17F3-   B3          ???
17F4-   B3          ???
17F5-   BB          ???
17F6-   D5 20       CMP   $20,X
17F8-   D2 C5       CMP   ($C5)
17FA-   D4          ???
17FB-   D5 D2       CMP   $D2,X
17FD-   CE D3 BA    DEC   $BAD3
1800-   A2 AC       LDX   #$AC
1802-   B8          CLV
1803-   C4 B8       CPY   $B8
1805-   C4 8D       CPY   $8D
1807-   A0 D2       LDY   #$D2
1809-   C5 CD       CMP   $CD
180B-   B1 B6       LDA   ($B6),Y
180D-   A0 A3       LDY   #$A3
180F-   B5 B0       LDA   $B0,X
1811-   B0 B0       BCS   $17C3
1813-   BB          ???
1814-   A3          ???
1815-   B3          ???
1816-   B3          ???
1817-   B3          ???
1818-   BB          ???
1819-   D5 8D       CMP   $8D,X
181B-   A0 DF       LDY   #$DF
181D-   C4 D5       CPY   $D5
181F-   CD D0 A0    CMP   $A0D0
1822-   D2 C5       CMP   ($C5)
1824-   D4          ???
1825-   D5 D2       CMP   $D2,X
1827-   CE BB D2    DEC   $D2BB
182A-   C5 D4       CMP   $D4
182C-   CC C5 CE    CPY   $CEC5
182F-   8D A0 DF    STA   $DFA0
1832-   D0 D2       BNE   $1806
1834-   CE D4 A0    DEC   $A0D4
1837-   A2 20       LDX   #$20
1839-   A2 AC       LDX   #$AC
183B-   B8          CLV
183C-   C4 B8       CPY   $B8
183E-   C4 8D       CPY   $8D
1840-   A0 DF       LDY   #$DF
1842-   D7          ???
1843-   C1 C9       CMP   ($C9,X)
1845-   D4          ???
1846-   8D AA 8D    STA   $8DAA
1849-   A0 DF       LDY   #$DF
184B-   D0 D2       BNE   $181F
184D-   CE D4 A0    DEC   $A0D4
1850-   A2 C3       LDX   #$C3
1852-   CD D0 B1    CMP   $B1D0
1855-   B6 20       LDX   $20,Y
1857-   C3          ???
1858-   CF          ???
1859-   CD D0 C1    CMP   $C1D0
185C-   D2 C5       CMP   ($C5)
185E-   D3          ???
185F-   20 D4 D7    JSR   $D7D4
1862-   CF          ???
1863-   20 B1 B6    JSR   $B6B1
1866-   AD C2 C9    LDA   $C9C2
1869-   D4          ???
186A-   20 D6 C1    JSR   $C1D6
186D-   CC D5 C5    CPY   $C5D5
1870-   D3          ???
1871-   A2 AC       LDX   #$AC
1873-   B8          CLV
1874-   C4 8D       CPY   $8D
1876-   A0 DF       LDY   #$DF
1878-   D0 D2       BNE   $184C
187A-   CE D4 A0    DEC   $A0D4
187D-   A2 D3       LDX   #$D3
187F-   C5 D4       CMP   $D4
1881-   D4          ???
1882-   C9 CE       CMP   #$CE
1884-   C7          ???
1885-   20 C6 CC    JSR   $CCC6
1888-   C1 C7       CMP   ($C7,X)
188A-   D3          ???
188B-   20 C1 D3    JSR   $D3C1
188E-   20 D7 CF    JSR   $CFD7
1891-   D5 CC       CMP   $CC,X
1893-   C4 20       CPY   $20
1895-   D4          ???
1896-   C8          INY
1897-   C5 20       CMP   $20
1899-   C3          ???
189A-   CD D0 20    CMP   $20D0
189D-   A2 AC       LDX   #$AC
189F-   B8          CLV
18A0-   C4 8D       CPY   $8D
18A2-   A0 DF       LDY   #$DF
18A4-   D0 D2       BNE   $1878
18A6-   CE D4 A0    DEC   $A0D4
18A9-   A2 C3       LDX   #$C3
18AB-   CF          ???
18AC-   CD CD C1    CMP   $C1CD
18AF-   CE C4 20    DEC   $20C4
18B2-   C9 CE       CMP   #$CE
18B4-   20 B6 B5    JSR   $B5B6
18B7-   B0 B2       BCS   $186B
18B9-   20 C1 D3    JSR   $D3C1
18BC-   D3          ???
18BD-   C5 CD       CMP   $CD
18BF-   C2          ???
18C0-   CC D9 AE    CPY   $AED9
18C3-   20 D7 C5    JSR   $C5D7
18C6-   20 D7 CF    JSR   $CFD7
18C9-   CE A7 D4    DEC   $D4A7
18CC-   A2 AC       LDX   #$AC
18CE-   B8          CLV
18CF-   C4 8D       CPY   $8D
18D1-   A0 DF       LDY   #$DF
18D3-   D0 D2       BNE   $18A7
18D5-   CE D4 A0    DEC   $A0D4
18D8-   A2 C2       LDX   #$C2
18DA-   C5 20       CMP   $20
18DC-   C9 CC       CMP   #$CC
18DE-   CC D5 D3    CPY   $D3D5
18E1-   D4          ???
18E2-   D2 C1       CMP   ($C1)
18E4-   D4          ???
18E5-   C9 CE       CMP   #$CE
18E7-   C7          ???
18E8-   20 D4 C8    JSR   $C8D4
18EB-   C9 D3       CMP   #$D3
18ED-   20 C6 CF    JSR   $CFC6
18F0-   D2 20       CMP   ($20)
18F2-   CE CF D7    DEC   $D7CF
18F5-   20 A2 AC    JSR   $ACA2
18F8-   B8          CLV
18F9-   C4 8D       CPY   $8D
18FB-   A0 DF       LDY   #$DF
18FD-   D0 D2       BNE   $18D1
18FF-   CE D4 A0    DEC   $A0D4
1902-   A2 C2       LDX   #$C2
1904-   C5 C3       CMP   $C3
1906-   C1 D5       CMP   ($D5,X)
1908-   D3          ???
1909-   C5 20       CMP   $20
190B-   C9 20       CMP   #$20
190D-   C8          INY
190E-   C1 D4       CMP   ($D4,X)
1910-   C5 20       CMP   $20
1912-   D9 CF D5    CMP   $D5CF,Y
1915-   AE A2 AC    LDX   $ACA2
1918-   B8          CLV
1919-   C4 B8       CPY   $B8
191B-   C4 8D       CPY   $8D
191D-   A0 DF       LDY   #$DF
191F-   D7          ???
1920-   C1 C9       CMP   ($C9,X)
1922-   D4          ???
1923-   8D AA 8D    STA   $8DAA
1926-   A0 DF       LDY   #$DF
1928-   D0 D2       BNE   $18FC
192A-   CE D4 A0    DEC   $A0D4
192D-   A2 20       LDX   #$20
192F-   A2 AC       LDX   #$AC
1931-   B8          CLV
1932-   C4 B8       CPY   $B8
1934-   C4 8D       CPY   $8D
1936-   A0 DF       LDY   #$DF
1938-   D0 D2       BNE   $190C
193A-   CE D4 A0    DEC   $A0D4
193D-   A2 C1       LDX   #$C1
193F-   CE C4 20    DEC   $20C4
1942-   C6 C9       DEC   $C9
1944-   CE C1 CC    DEC   $CCC1
1947-   CC D9 AC    CPY   $ACD9
194A-   20 D4 C8    JSR   $C8D4
194D-   C5 20       CMP   $20
194F-   D2 CE       CMP   ($CE)
1951-   C4 B1       CPY   $B1
1953-   B6 20       LDX   $20,Y
1955-   CD C1 C3    CMP   $C3C1
1958-   D2 CF       CMP   ($CF)
195A-   A2 AC       LDX   #$AC
195C-   B8          CLV
195D-   C4 8D       CPY   $8D
195F-   A0 DF       LDY   #$DF
1961-   D0 D2       BNE   $1935
1963-   CE D4 A0    DEC   $A0D4
1966-   A2 D2       LDX   #$D2
1968-   C5 D4       CMP   $D4
196A-   D5 D2       CMP   $D2,X
196C-   CE D3 20    DEC   $20D3
196F-   C1 20       CMP   ($20,X)
1971-   D2 C1       CMP   ($C1)
1973-   CE C4 CF    DEC   $CFC4
1976-   CD 20 B1    CMP   $B120
1979-   B6 AD       LDX   $AD,Y
197B-   C2          ???
197C-   C9 D4       CMP   #$D4
197E-   20 D6 C1    JSR   $C1D6
1981-   CC D5 C5    CPY   $C5D5
1984-   AC 20 C6    LDY   $C620
1987-   D2 CF       CMP   ($CF)
1989-   CD A2 AC    CMP   $ACA2
198C-   B8          CLV
198D-   C4 8D       CPY   $8D
198F-   A0 DF       LDY   #$DF
1991-   D0 D2       BNE   $1965
1993-   CE D4 A0    DEC   $A0D4
1996-   A2 B0       LDX   #$B0
1998-   20 D4 CF    JSR   $CFD4
199B-   20 B6 B5    JSR   $B5B6
199E-   B4 B5       LDY   $B5,X
19A0-   B5 AE       LDA   $AE,X
19A2-   A2 AC       LDX   #$AC
19A4-   B8          CLV
19A5-   C4 B8       CPY   $B8
19A7-   C4 8D       CPY   $8D
19A9-   A0 CC       LDY   #$CC
19AB-   D5 D0       CMP   $D0,X
19AD-   A0 B5       LDY   #$B5
19AF-   8D A0 DF    STA   $DFA0
19B2-   D0 D2       BNE   $1986
19B4-   CE D4 A0    DEC   $A0D4
19B7-   A2 D2       LDX   #$D2
19B9-   CE C4 B1    DEC   $B1C4
19BC-   B6 20       LDX   $20,Y
19BE-   D2 C5       CMP   ($C5)
19C0-   D4          ???
19C1-   D5 D2       CMP   $D2,X
19C3-   CE D3 BA    DEC   $BAD3
19C6-   A2 AC       LDX   #$AC
19C8-   B8          CLV
19C9-   C4 B8       CPY   $B8
19CB-   C4 8D       CPY   $8D
19CD-   A0 D2       LDY   #$D2
19CF-   CE C4 B1    DEC   $B1C4
19D2-   B6 8D       LDX   $8D,Y
19D4-   A0 DF       LDY   #$DF
19D6-   C4 D5       CPY   $D5
19D8-   CD D0 A0    CMP   $A0D0
19DB-   D2 C5       CMP   ($C5)
19DD-   D4          ???
19DE-   D5 D2       CMP   $D2,X
19E0-   CE BB D2    DEC   $D2BB
19E3-   C5 D4       CMP   $D4
19E5-   CC C5 CE    CPY   $CEC5
19E8-   8D A0 DF    STA   $DFA0
19EB-   D0 D2       BNE   $19BF
19ED-   CE D4 A0    DEC   $A0D4
19F0-   A2 20       LDX   #$20
19F2-   A2 AC       LDX   #$AC
19F4-   B8          CLV
19F5-   C4 B8       CPY   $B8
19F7-   C4 8D       CPY   $8D
19F9-   A0 DF       LDY   #$DF
19FB-   D7          ???
19FC-   C1 C9       CMP   ($C9,X)
19FE-   D4          ???
19FF-   8D A0 AD    STA   $ADA0
1A02-   AD DE 8D    LDA   $8DDE
1A05-   AA          TAX
1A06-   8D AA AA    STA   $AAAA
1A09-   AA          TAX
1A0A-   AA          TAX
1A0B-   AA          TAX
1A0C-   AA          TAX
1A0D-   AA          TAX
1A0E-   AA          TAX
1A0F-   AA          TAX
1A10-   AA          TAX
1A11-   AA          TAX
1A12-   AA          TAX
1A13-   AA          TAX
1A14-   AA          TAX
1A15-   AA          TAX
1A16-   AA          TAX
1A17-   AA          TAX
1A18-   AA          TAX
1A19-   AA          TAX
1A1A-   AA          TAX
1A1B-   AA          TAX
1A1C-   AA          TAX
1A1D-   AA          TAX
1A1E-   AA          TAX
1A1F-   AA          TAX
1A20-   AA          TAX
1A21-   AA          TAX
1A22-   AA          TAX
1A23-   AA          TAX
1A24-   AA          TAX
1A25-   AA          TAX
1A26-   AA          TAX
1A27-   8D AA 8D    STA   $8DAA
1A2A-   AA          TAX
1A2B-   20 D4 C8    JSR   $C8D4
1A2E-   C5 20       CMP   $20
1A30-   C6 CF       DEC   $CF
1A32-   CC CC CF    CPY   $CFCC
1A35-   D7          ???
1A36-   C9 CE       CMP   #$CE
1A38-   C7          ???
1A39-   20 C9 D3    JSR   $D3C9
1A3C-   20 C3 D5    JSR   $D5C3
1A3F-   D2 D2       CMP   ($D2)
1A41-   C5 CE       CMP   $CE
1A43-   D4          ???
1A44-   CC D9 20    CPY   $20D9
1A47-   D5 CE       CMP   $CE,X
1A49-   C4 C5       CPY   $C5
1A4B-   D2 8D       CMP   ($8D)
1A4D-   AA          TAX
1A4E-   20 C3 CF    JSR   $CFC3
1A51-   CE D3 D4    DEC   $D4D3
1A54-   D2 D5       CMP   ($D5)
1A56-   C3          ???
1A57-   D4          ???
1A58-   C9 CF       CMP   #$CF
1A5A-   CE AC 20    DEC   $20AC
1A5D-   C1 CE       CMP   ($CE,X)
1A5F-   C4 20       CPY   $20
1A61-   C4 CF       CPY   $CF
1A63-   C5 D3       CMP   $D3
1A65-   20 CE CF    JSR   $CFCE
1A68-   D4          ???
1A69-   20 D9 C5    JSR   $C5D9
1A6C-   D4          ???
1A6D-   8D AA 20    STA   $20AA
1A70-   D7          ???
1A71-   CF          ???
1A72-   D2 CB       CMP   ($CB)
1A74-   20 C1 D3    JSR   $D3C1
1A77-   20 D0 CC    JSR   $CCD0
1A7A-   C1 CE       CMP   ($CE,X)
1A7C-   CE C5 C4    DEC   $C4C5
1A7F-   AE 20 C6    LDX   $C620
1A82-   CC CF C1    CPY   $C1CF
1A85-   D4          ???
1A86-   C9 CE       CMP   #$CE
1A88-   C7          ???
1A89-   20 D0 CF    JSR   $CFD0
1A8C-   C9 CE       CMP   #$CE
1A8E-   D4          ???
1A8F-   8D AA 20    STA   $20AA
1A92-   D2 CF       CMP   ($CF)
1A94-   D5 D4       CMP   $D4,X
1A96-   C9 CE       CMP   #$CE
1A98-   C5 D3       CMP   $D3
1A9A-   20 D7 C9    JSR   $C9D7
1A9D-   CC CC 20    CPY   $20CC
1AA0-   C2          ???
1AA1-   C5 20       CMP   $20
1AA3-   C1 C4       CMP   ($C4,X)
1AA5-   C4 C5       CPY   $C5
1AA7-   C4 20       CPY   $20
1AA9-   C9 CE       CMP   #$CE
1AAB-   20 D4 C8    JSR   $C8D4
1AAE-   C5 20       CMP   $20
1AB0-   CE C5 D8    DEC   $D8C5
1AB3-   D4          ???
1AB4-   8D AA 20    STA   $20AA
1AB7-   CD C1 CA    CMP   $CAC1
1ABA-   CF          ???
1ABB-   D2 20       CMP   ($20)
1ABD-   D6 C5       DEC   $C5,X
1ABF-   D2 D3       CMP   ($D3)
1AC1-   C9 CF       CMP   #$CF
1AC3-   CE 20 D2    DEC   $D220
1AC6-   C5 CC       CMP   $CC
1AC8-   C5 C1       CMP   $C1
1ACA-   D3          ???
1ACB-   C5 AE       CMP   $AE
1ACD-   8D AA 8D    STA   $8DAA
1AD0-   AA          TAX
1AD1-   AA          TAX
1AD2-   AA          TAX
1AD3-   AA          TAX
1AD4-   AA          TAX
1AD5-   AA          TAX
1AD6-   AA          TAX
1AD7-   AA          TAX
1AD8-   AA          TAX
1AD9-   AA          TAX
1ADA-   AA          TAX
1ADB-   AA          TAX
1ADC-   AA          TAX
1ADD-   AA          TAX
1ADE-   AA          TAX
1ADF-   AA          TAX
1AE0-   AA          TAX
1AE1-   AA          TAX
1AE2-   AA          TAX
1AE3-   AA          TAX
1AE4-   AA          TAX
1AE5-   AA          TAX
1AE6-   AA          TAX
1AE7-   AA          TAX
1AE8-   AA          TAX
1AE9-   AA          TAX
1AEA-   AA          TAX
1AEB-   AA          TAX
1AEC-   AA          TAX
1AED-   AA          TAX
1AEE-   AA          TAX
1AEF-   AA          TAX
1AF0-   8D AA 8D    STA   $8DAA
1AF3-   A0 DF       LDY   #$DF
1AF5-   D0 D2       BNE   $1AC9
1AF7-   CE D4 A0    DEC   $A0D4
1AFA-   A2 20       LDX   #$20
1AFC-   A2 AC       LDX   #$AC
1AFE-   B8          CLV
1AFF-   C4 B8       CPY   $B8
1B01-   C4 B8       CPY   $B8
1B03-   C4 B8       CPY   $B8
1B05-   C4 B8       CPY   $B8
1B07-   C4 B8       CPY   $B8
1B09-   C4 B8       CPY   $B8
1B0B-   C4 B8       CPY   $B8
1B0D-   C4 8D       CPY   $8D
1B0F-   A0 DF       LDY   #$DF
1B11-   D0 D2       BNE   $1AE5
1B13-   CE D4 A0    DEC   $A0D4
1B16-   A2 C6       LDX   #$C6
1B18-   CC CF C1    CPY   $C1CF
1B1B-   D4          ???
1B1C-   C9 CE       CMP   #$CE
1B1E-   C7          ???
1B1F-   AD D0 CF    LDA   $CFD0
1B22-   C9 CE       CMP   #$CE
1B24-   D4          ???
1B25-   20 C3 C1    JSR   $C1C3
1B28-   CC C3 D5    CPY   $D5C3
1B2B-   CC C1 D4    CPY   $D4C1
1B2E-   C9 CF       CMP   #$CF
1B30-   CE A2 AC    DEC   $ACA2
1B33-   B8          CLV
1B34-   C4 8D       CPY   $8D
1B36-   A0 DF       LDY   #$DF
1B38-   D0 D2       BNE   $1B0C
1B3A-   CE D4 A0    DEC   $A0D4
1B3D-   A2 AD       LDX   #$AD
1B3F-   AD AD AD    LDA   $ADAD
1B42-   AD AD AD    LDA   $ADAD
1B45-   AD AD AD    LDA   $ADAD
1B48-   AD AD AD    LDA   $ADAD
1B4B-   AD AD AD    LDA   $ADAD
1B4E-   AD AD AD    LDA   $ADAD
1B51-   AD AD AD    LDA   $ADAD
1B54-   AD AD AD    LDA   $ADAD
1B57-   AD A2 AC    LDA   $ACA2
1B5A-   B8          CLV
1B5B-   C4 B8       CPY   $B8
1B5D-   C4 8D       CPY   $8D
1B5F-   A0 DF       LDY   #$DF
1B61-   D0 D2       BNE   $1B35
1B63-   CE D4 A0    DEC   $A0D4
1B66-   A2 D4       LDX   #$D4
1B68-   C8          INY
1B69-   C9 D3       CMP   #$D3
1B6B-   20 CC C9    JSR   $C9CC
1B6E-   C2          ???
1B6F-   D2 C1       CMP   ($C1)
1B71-   D2 D9       CMP   ($D9)
1B73-   20 D5 D3    JSR   $D3D5
1B76-   C5 D3       CMP   $D3
1B78-   20 D4 C8    JSR   $C8D4
1B7B-   C5 20       CMP   $20
1B7D-   C1 D0       CMP   ($D0,X)
1B7F-   D0 CC       BNE   $1B4D
1B81-   C5 D3       CMP   $D3
1B83-   CF          ???
1B84-   C6 D4       DEC   $D4
1B86-   A2 AC       LDX   #$AC
1B88-   B8          CLV
1B89-   C4 8D       CPY   $8D
1B8B-   A0 DF       LDY   #$DF
1B8D-   D0 D2       BNE   $1B61
1B8F-   CE D4 A0    DEC   $A0D4
1B92-   A2 D2       LDX   #$D2
1B94-   CF          ???
1B95-   D5 D4       CMP   $D4,X
1B97-   C9 CE       CMP   #$CE
1B99-   C5 D3       CMP   $D3
1B9B-   20 C6 CF    JSR   $CFC6
1B9E-   D2 20       CMP   ($20)
1BA0-   C6 CC       DEC   $CC
1BA2-   CF          ???
1BA3-   C1 D4       CMP   ($D4,X)
1BA5-   C9 CE       CMP   #$CE
1BA7-   C7          ???
1BA8-   AD D0 CF    LDA   $CFD0
1BAB-   C9 CE       CMP   #$CE
1BAD-   D4          ???
1BAE-   A2 AC       LDX   #$AC
1BB0-   B8          CLV
1BB1-   C4 8D       CPY   $8D
1BB3-   A0 DF       LDY   #$DF
1BB5-   D0 D2       BNE   $1B89
1BB7-   CE D4 A0    DEC   $A0D4
1BBA-   A2 C1       LDX   #$C1
1BBC-   D2 C9       CMP   ($C9)
1BBE-   D4          ???
1BBF-   C8          INY
1BC0-   CD C5 D4    CMP   $D4C5
1BC3-   C9 C3       CMP   #$C3
1BC5-   AC 20 D7    LDY   $D720
1BC8-   D2 C9       CMP   ($C9)
1BCA-   D4          ???
1BCB-   D4          ???
1BCC-   C5 CE       CMP   $CE
1BCE-   20 CF D2    JSR   $D2CF
1BD1-   C9 C7       CMP   #$C7
1BD3-   C9 CE       CMP   #$CE
1BD5-   C1 CC       CMP   ($CC,X)
1BD7-   CC D9 A2    CPY   $A2D9
1BDA-   AC B8 C4    LDY   $C4B8
1BDD-   8D A0 DF    STA   $DFA0
1BE0-   D0 D2       BNE   $1BB4
1BE2-   CE D4 A0    DEC   $A0D4
1BE5-   A2 C2       LDX   #$C2
1BE7-   D9 20 D3    CMP   $D320,Y
1BEA-   D4          ???
1BEB-   C5 D6       CMP   $D6
1BED-   C5 20       CMP   $20
1BEF-   D7          ???
1BF0-   CF          ???
1BF1-   DA          PHX
1BF2-   CE C9 C1    DEC   $C1C9
1BF5-   CB          ???
1BF6-   AE 20 D4    LDX   $D420
1BF9-   C8          INY
1BFA-   C5 D3       CMP   $D3
1BFC-   C5 20       CMP   $20
1BFE-   C1 D2       CMP   ($D2,X)
1C00-   C5 A2       CMP   $A2
1C02-   AC B8 C4    LDY   $C4B8
1C05-   8D A0 DF    STA   $DFA0
1C08-   D0 D2       BNE   $1BDC
1C0A-   CE D4 A0    DEC   $A0D4
1C0D-   A2 D0       LDX   #$D0
1C0F-   D2 C5       CMP   ($C5)
1C11-   D3          ???
1C12-   C5 CE       CMP   $CE
1C14-   D4          ???
1C15-   20 C9 CE    JSR   $CEC9
1C18-   20 C5 D6    JSR   $D6C5
1C1B-   C5 D2       CMP   $D2
1C1D-   D9 20 C1    CMP   $C120,Y
1C20-   D0 D0       BNE   $1BF2
1C22-   CC C5 20    CPY   $20C5
1C25-   C9 C9       CMP   #$C9
1C27-   20 CD CF    JSR   $CFCD
1C2A-   C4 C5       CPY   $C5
1C2C-   CC A2 AC    CPY   $ACA2
1C2F-   B8          CLV
1C30-   C4 8D       CPY   $8D
1C32-   A0 DF       LDY   #$DF
1C34-   D0 D2       BNE   $1C08
1C36-   CE D4 A0    DEC   $A0D4
1C39-   A2 C6       LDX   #$C6
1C3B-   D2 CF       CMP   ($CF)
1C3D-   CD 20 D4    CMP   $D420
1C40-   C8          INY
1C41-   C5 20       CMP   $20
1C43-   C1 D0       CMP   ($D0,X)
1C45-   D0 CC       BNE   $1C13
1C47-   C5 20       CMP   $20
1C49-   DD DB AB    CMP   $ABDB,X
1C4C-   20 C1 CE    JSR   $CEC1
1C4F-   C4 20       CPY   $20
1C51-   C6 CF       DEC   $CF
1C53-   D2 D7       CMP   ($D7)
1C55-   C1 D2       CMP   ($D2,X)
1C57-   C4 AE       CPY   $AE
1C59-   A2 AC       LDX   #$AC
1C5B-   B8          CLV
1C5C-   C4 8D       CPY   $8D
1C5E-   A0 DF       LDY   #$DF
1C60-   D0 D2       BNE   $1C34
1C62-   CE D4 A0    DEC   $A0D4
1C65-   A2 20       LDX   #$20
1C67-   A2 AC       LDX   #$AC
1C69-   B8          CLV
1C6A-   C4 B8       CPY   $B8
1C6C-   C4 8D       CPY   $8D
1C6E-   A0 DF       LDY   #$DF
1C70-   D7          ???
1C71-   C1 C9       CMP   ($C9,X)
1C73-   D4          ???
1C74-   8D A0 DF    STA   $DFA0
1C77-   D0 D2       BNE   $1C4B
1C79-   CE D4 A0    DEC   $A0D4
1C7C-   A2 C6       LDX   #$C6
1C7E-   CC CF C1    CPY   $C1CF
1C81-   D4          ???
1C82-   C9 CE       CMP   #$CE
1C84-   C7          ???
1C85-   AD D0 CF    LDA   $CFD0
1C88-   C9 CE       CMP   #$CE
1C8A-   D4          ???
1C8B-   20 D6 C1    JSR   $C1D6
1C8E-   CC D5 C5    CPY   $C5D5
1C91-   D3          ???
1C92-   20 C1 D2    JSR   $D2C1
1C95-   C5 20       CMP   $20
1C97-   D3          ???
1C98-   D4          ???
1C99-   CF          ???
1C9A-   D2 C5       CMP   ($C5)
1C9C-   C4 A2       CPY   $A2
1C9E-   AC B8 C4    LDY   $C4B8
1CA1-   8D A0 DF    STA   $DFA0
1CA4-   D0 D2       BNE   $1C78
1CA6-   CE D4 A0    DEC   $A0D4
1CA9-   A2 D5       LDX   #$D5
1CAB-   D3          ???
1CAC-   C9 CE       CMP   #$CE
1CAE-   C7          ???
1CAF-   20 D3 C3    JSR   $C3D3
1CB2-   C9 C5       CMP   #$C5
1CB4-   CE D4 C9    DEC   $C9D4
1CB7-   C6 C9       DEC   $C9
1CB9-   C3          ???
1CBA-   20 CE CF    JSR   $CFCE
1CBD-   D4          ???
1CBE-   C1 D4       CMP   ($D4,X)
1CC0-   C9 CF       CMP   #$CF
1CC2-   CE AC 20    DEC   $20AC
1CC5-   D7          ???
1CC6-   C8          INY
1CC7-   C5 D2       CMP   $D2
1CC9-   C5 A2       CMP   $A2
1CCB-   AC B8 C4    LDY   $C4B8
1CCE-   8D A0 DF    STA   $DFA0
1CD1-   D0 D2       BNE   $1CA5
1CD3-   CE D4 A0    DEC   $A0D4
1CD6-   A2 D4       LDX   #$D4
1CD8-   C8          INY
1CD9-   C5 20       CMP   $20
1CDB-   C6 C9       DEC   $C9
1CDD-   D2 D3       CMP   ($D3)
1CDF-   D4          ???
1CE0-   20 C2 D9    JSR   $D9C2
1CE3-   D4          ???
1CE4-   C5 20       CMP   $20
1CE6-   C9 D3       CMP   #$D3
1CE8-   20 D4 C8    JSR   $C8D4
1CEB-   C5 20       CMP   $20
1CED-   C5 D8       CMP   $D8
1CEF-   D0 CF       BNE   $1CC0
1CF1-   CE C5 CE    DEC   $CEC5
1CF4-   D4          ???
1CF5-   AC A2 AC    LDY   $ACA2
1CF8-   B8          CLV
1CF9-   C4 8D       CPY   $8D
1CFB-   A0 DF       LDY   #$DF
1CFD-   D0 D2       BNE   $1CD1
1CFF-   CE D4 A0    DEC   $A0D4
1D02-   A2 D4       LDX   #$D4
1D04-   C8          INY
1D05-   C5 20       CMP   $20
1D07-   D3          ???
1D08-   C5 C3       CMP   $C3
1D0A-   CF          ???
1D0B-   CE C4 20    DEC   $20C4
1D0E-   D4          ???
1D0F-   C8          INY
1D10-   D2 CF       CMP   ($CF)
1D12-   D5 C7       CMP   $C7,X
1D14-   C8          INY
1D15-   20 C6 C9    JSR   $C9C6
1D18-   C6 D4       DEC   $D4
1D1A-   C8          INY
1D1B-   20 C2 D9    JSR   $D9C2
1D1E-   D4          ???
1D1F-   C5 D3       CMP   $D3
1D21-   A2 AC       LDX   #$AC
1D23-   B8          CLV
1D24-   C4 8D       CPY   $8D
1D26-   A0 DF       LDY   #$DF
1D28-   D0 D2       BNE   $1CFC
1D2A-   CE D4 A0    DEC   $A0D4
1D2D-   A2 C1       LDX   #$C1
1D2F-   D2 C5       CMP   ($C5)
1D31-   20 D4 C8    JSR   $C8D4
1D34-   C5 20       CMP   $20
1D36-   CD C1 CE    CMP   $CEC1
1D39-   D4          ???
1D3A-   C9 D3       CMP   #$D3
1D3C-   D3          ???
1D3D-   C1 AC       CMP   ($AC,X)
1D3F-   20 C1 CE    JSR   $CEC1
1D42-   C4 20       CPY   $20
1D44-   D4          ???
1D45-   C8          INY
1D46-   C5 20       CMP   $20
1D48-   D3          ???
1D49-   C9 D8       CMP   #$D8
1D4B-   D4          ???
1D4C-   C8          INY
1D4D-   A2 AC       LDX   #$AC
1D4F-   B8          CLV
1D50-   C4 8D       CPY   $8D
1D52-   A0 DF       LDY   #$DF
1D54-   D0 D2       BNE   $1D28
1D56-   CE D4 A0    DEC   $A0D4
1D59-   A2 C2       LDX   #$C2
1D5B-   D9 D4 C5    CMP   $C5D4,Y
1D5E-   20 D4 C8    JSR   $C8D4
1D61-   C5 20       CMP   $20
1D63-   D3          ???
1D64-   C9 C7       CMP   #$C7
1D66-   CE AE A2    DEC   $A2AE
1D69-   AC B8 C4    LDY   $C4B8
1D6C-   B8          CLV
1D6D-   C4 8D       CPY   $8D
1D6F-   A0 DF       LDY   #$DF
1D71-   D7          ???
1D72-   C1 C9       CMP   ($C9,X)
1D74-   D4          ???
1D75-   8D A0 DF    STA   $DFA0
1D78-   D0 D2       BNE   $1D4C
1D7A-   CE D4 A0    DEC   $A0D4
1D7D-   A2 C5       LDX   #$C5
1D7F-   D8          CLD
1D80-   D0 20       BNE   $1DA2
1D82-   20 20 CD    JSR   $CD20
1D85-   C1 CE       CMP   ($CE,X)
1D87-   D4          ???
1D88-   C9 D3       CMP   #$D3
1D8A-   D3          ???
1D8B-   C1 20       CMP   ($20,X)
1D8D-   20 20 20    JSR   $2020
1D90-   20 D3 C9    JSR   $C9D3
1D93-   C7          ???
1D94-   CE A2 AC    DEC   $ACA2
1D97-   B8          CLV
1D98-   C4 8D       CPY   $8D
1D9A-   A0 DF       LDY   #$DF
1D9C-   D0 D2       BNE   $1D70
1D9E-   CE D4 A0    DEC   $A0D4
1DA1-   A2 B0       LDX   #$B0
1DA3-   B0 20       BCS   $1DC5
1DA5-   20 20 20    JSR   $2020
1DA8-   B0 B1       BCS   $1D5B
1DAA-   20 B0 B2    JSR   $B2B0
1DAD-   20 B0 B3    JSR   $B3B0
1DB0-   20 B0 B4    JSR   $B4B0
1DB3-   20 20 B0    JSR   $B020
1DB6-   B5 A2       LDA   $A2,X
1DB8-   AC B8 C4    LDY   $C4B8
1DBB-   B8          CLV
1DBC-   C4 B8       CPY   $B8
1DBE-   C4 8D       CPY   $8D
1DC0-   A0 CC       LDY   #$CC
1DC2-   C4 C1       CPY   $C1
1DC4-   A0 A3       LDY   #$A3
1DC6-   A4 B8       LDY   $B8
1DC8-   B4 A0       LDY   $A0,X
1DCA-   BB          ???
1DCB-   20 BD 20    JSR   $20BD
1DCE-   A4 B8       LDY   $B8
1DD0-   B0 20       BCS   $1DF2
1DD2-   AB          ???
1DD3-   20 C5 D8    JSR   $D8C5
1DD6-   D0 CF       BNE   $1DA7
1DD8-   CE C5 CE    DEC   $CEC5
1DDB-   D4          ???
1DDC-   BB          ???
1DDD-   20 AD B1    JSR   $B1AD
1DE0-   20 BD 20    JSR   $20BD
1DE3-   A4 B7       LDY   $B7
1DE5-   B9 8D A0    LDA   $A08D,Y
1DE8-   D3          ???
1DE9-   D4          ???
1DEA-   C1 A0       CMP   ($A0,X)
1DEC-   A4 B3       LDY   $B3
1DEE-   B0 B0       BCS   $1DA0
1DF0-   8D A0 CC    STA   $CCA0
1DF3-   C4 C1       CPY   $C1
1DF5-   A0 A3       LDY   #$A3
1DF7-   C1 B0       CMP   ($B0,X)
1DF9-   A0 BB       LDY   #$BB
1DFB-   20 CD C1    JSR   $C1CD
1DFE-   CE D4 C9    DEC   $C9D4
1E01-   D3          ???
1E02-   D3          ???
1E03-   C1 8D       CMP   ($8D,X)
1E05-   A0 D3       LDY   #$D3
1E07-   D4          ???
1E08-   C1 A0       CMP   ($A0,X)
1E0A-   A4 B3       LDY   $B3
1E0C-   B0 B1       BCS   $1DBF
1E0E-   A0 BB       LDY   #$BB
1E10-   20 D3 D4    JSR   $D4D3
1E13-   CF          ???
1E14-   D2 C5       CMP   ($C5)
1E16-   C4 20       CPY   $20
1E18-   CD CF D3    CMP   $D3CF
1E1B-   D4          ???
1E1C-   20 D3 C9    JSR   $C9D3
1E1F-   C7          ???
1E20-   CE C9 C6    DEC   $C6C9
1E23-   C9 C3       CMP   #$C3
1E25-   C1 CE       CMP   ($CE,X)
1E27-   D4          ???
1E28-   8D A0 CC    STA   $CCA0
1E2B-   C4 C1       CPY   $C1
1E2D-   A0 A3       LDY   #$A3
1E2F-   B0 B0       BCS   $1DE1
1E31-   8D A0 D3    STA   $D3A0
1E34-   D4          ???
1E35-   C1 A0       CMP   ($A0,X)
1E37-   A4 B3       LDY   $B3
1E39-   B0 B2       BCS   $1DED
1E3B-   8D A0 D3    STA   $D3A0
1E3E-   D4          ???
1E3F-   C1 A0       CMP   ($A0,X)
1E41-   A4 B3       LDY   $B3
1E43-   B0 B3       BCS   $1DF8
1E45-   A0 BB       LDY   #$BB
1E47-   20 CC C5    JSR   $C5CC
1E4A-   C6 D4       DEC   $D4
1E4C-   20 D4 CF    JSR   $CFD4
1E4F-   20 D2 C9    JSR   $C9D2
1E52-   C7          ???
1E53-   C8          INY
1E54-   D4          ???
1E55-   AE 8D A0    LDX   $A08D
1E58-   D3          ???
1E59-   D4          ???
1E5A-   C1 A0       CMP   ($A0,X)
1E5C-   A4 B3       LDY   $B3
1E5E-   B0 B4       BCS   $1E14
1E60-   8D A0 CC    STA   $CCA0
1E63-   C4 C1       CPY   $C1
1E65-   A0 A3       LDY   #$A3
1E67-   A4 C6       LDY   $C6
1E69-   C6 8D       DEC   $8D
1E6B-   A0 D3       LDY   #$D3
1E6D-   D4          ???
1E6E-   C1 A0       CMP   ($A0,X)
1E70-   A4 B3       LDY   $B3
1E72-   B0 B5       BCS   $1E29
1E74-   A0 BB       LDY   #$BB
1E76-   20 C6 C6    JSR   $C6C6
1E79-   BD 20 CE    LDA   $CE20,X
1E7C-   C5 C7       CMP   $C7
1E7E-   C1 D4       CMP   ($D4,X)
1E80-   C9 D6       CMP   #$D6
1E82-   C5 AC       CMP   $AC
1E84-   20 B0 20    JSR   $20B0
1E87-   BD 20 D0    LDA   $D020,X
1E8A-   CF          ???
1E8B-   D3          ???
1E8C-   C9 D4       CMP   #$D4
1E8E-   C9 D6       CMP   #$D6
1E90-   C5 8D       CMP   $8D
1E92-   A0 DF       LDY   #$DF
1E94-   C4 D5       CPY   $D5
1E96-   CD D0 A0    CMP   $A0D0
1E99-   A4 B3       LDY   $B3
1E9B-   B0 B0       BCS   $1E4D
1E9D-   BB          ???
1E9E-   A3          ???
1E9F-   B6 8D       LDX   $8D,Y
1EA1-   AA          TAX
1EA2-   8D AA AA    STA   $AAAA
1EA5-   20 B2 B5    JSR   $B5B2
1EA8-   C5 B1       CMP   $B1
1EAA-   B0 DE       BCS   $1E8A
1EAC-   AD B1 20    LDA   $20B1
1EAF-   BD 20 B2    LDA   $B220,X
1EB2-   AE B5 8D    LDX   $8DB5
1EB5-   AA          TAX
1EB6-   8D A0 DF    STA   $DFA0
1EB9-   D7          ???
1EBA-   C1 C9       CMP   ($C9,X)
1EBC-   D4          ???
1EBD-   8D A0 DF    STA   $DFA0
1EC0-   D0 D2       BNE   $1E94
1EC2-   CE D4 A0    DEC   $A0D4
1EC5-   A2 D3       LDX   #$D3
1EC7-   CF          ???
1EC8-   AC 20 CC    LDY   $CC20
1ECB-   C5 D4       CMP   $D4
1ECD-   A7          ???
1ECE-   D3          ???
1ECF-   20 D0 D5    JSR   $D5D0
1ED2-   D4          ???
1ED3-   20 B2 AE    JSR   $AEB2
1ED6-   B5 20       LDA   $20,X
1ED8-   C9 CE       CMP   #$CE
1EDA-   20 A4 B3    JSR   $B3A4
1EDD-   B0 B0       BCS   $1E8F
1EDF-   20 C1 CE    JSR   $CEC1
1EE2-   C4 A2       CPY   $A2
1EE4-   AC B8 C4    LDY   $C4B8
1EE7-   8D A0 DF    STA   $DFA0
1EEA-   D0 D2       BNE   $1EBE
1EEC-   CE D4 A0    DEC   $A0D4
1EEF-   A2 B1       LDX   #$B1
1EF1-   B0 20       BCS   $1F13
1EF3-   C9 CE       CMP   #$CE
1EF5-   20 A4 B3    JSR   $B3A4
1EF8-   B1 B0       LDA   ($B0),Y
1EFA-   AC 20 D4    LDY   $D420
1EFD-   C8          INY
1EFE-   C5 CE       CMP   $CE
1F00-   20 C1 C4    JSR   $C4C1
1F03-   C4 20       CPY   $20
1F05-   D4          ???
1F06-   C8          INY
1F07-   C5 CD       CMP   $CD
1F09-   AE A2 AC    LDX   $ACA2
1F0C-   B8          CLV
1F0D-   C4 B8       CPY   $B8
1F0F-   C4 8D       CPY   $8D
1F11-   A0 DF       LDY   #$DF
1F13-   D0 D2       BNE   $1EE7
1F15-   CE D4 A0    DEC   $A0D4
1F18-   A2 B2       LDX   #$B2
1F1A-   AE B5 20    LDX   $20B5
1F1D-   BD 20 B2    LDA   $B220,X
1F20-   B5 C5       LDA   $C5,X
1F22-   AD B1 20    LDA   $20B1
1F25-   D3          ???
1F26-   C3          ???
1F27-   C9 C5       CMP   #$C5
1F29-   CE D4 C9    DEC   $C9D4
1F2C-   C6 C9       DEC   $C9
1F2E-   C3          ???
1F2F-   20 CE CF    JSR   $CFCE
1F32-   D4          ???
1F33-   C1 D4       CMP   ($D4,X)
1F35-   C9 CF       CMP   #$CF
1F37-   CE A2 AC    DEC   $ACA2
1F3A-   B8          CLV
1F3B-   C4 B8       CPY   $B8
1F3D-   C4 8D       CPY   $8D
1F3F-   A0 DF       LDY   #$DF
1F41-   D0 D2       BNE   $1F15
1F43-   CE D4 A0    DEC   $A0D4
1F46-   A2 20       LDX   #$20
1F48-   20 20 20    JSR   $2020
1F4B-   BD 20 B0    LDA   $B020,X
1F4E-   B1 20       LDA   ($20),Y
1F50-   B3          ???
1F51-   B7          ???
1F52-   20 B0 B0    JSR   $B0B0
1F55-   20 B0 B0    JSR   $B0B0
1F58-   20 B0 B0    JSR   $B0B0
1F5B-   20 C6 C6    JSR   $C6C6
1F5E-   A2 AC       LDX   #$AC
1F60-   B8          CLV
1F61-   C4 B8       CPY   $B8
1F63-   C4 8D       CPY   $8D
1F65-   A0 DF       LDY   #$DF
1F67-   D0 D2       BNE   $1F3B
1F69-   CE D4 A0    DEC   $A0D4
1F6C-   A2 B1       LDX   #$B1
1F6E-   B0 20       BCS   $1F90
1F70-   BD 20 B1    LDA   $B120,X
1F73-   C5 AB       CMP   $AB
1F75-   B1 A2       LDA   ($A2),Y
1F77-   AC B8 C4    LDY   $C4B8
1F7A-   8D A0 DF    STA   $DFA0
1F7D-   D0 D2       BNE   $1F51
1F7F-   CE D4 A0    DEC   $A0D4
1F82-   A2 20       LDX   #$20
1F84-   20 20 BD    JSR   $BD20
1F87-   20 B0 B1    JSR   $B1B0
1F8A-   20 B0 B1    JSR   $B1B0
1F8D-   20 B0 B0    JSR   $B0B0
1F90-   20 B0 B0    JSR   $B0B0
1F93-   20 B0 B0    JSR   $B0B0
1F96-   20 B0 B0    JSR   $B0B0
1F99-   A2 AC       LDX   #$AC
1F9B-   B8          CLV
1F9C-   C4 B8       CPY   $B8
1F9E-   C4 8D       CPY   $8D
1FA0-   A0 DF       LDY   #$DF
1FA2-   D0 D2       BNE   $1F76
1FA4-   CE D4 A0    DEC   $A0D4
1FA7-   A2 20       LDX   #$20
1FA9-   A2 AC       LDX   #$AC
1FAB-   B8          CLV
1FAC-   C4 B8       CPY   $B8
1FAE-   C4 B8       CPY   $B8
1FB0-   C4 8D       CPY   $8D
1FB2-   A0 CC       LDY   #$CC
1FB4-   C4 C1       CPY   $C1
1FB6-   A0 A3       LDY   #$A3
1FB8-   A4 B8       LDY   $B8
1FBA-   B4 8D       LDY   $8D,X
1FBC-   A0 CC       LDY   #$CC
1FBE-   C4 C1       CPY   $C1
1FC0-   A0 A3       LDY   #$A3
1FC2-   A4 C1       LDY   $C1
1FC4-   B0 8D       BCS   $1F53
1FC6-   A0 D3       LDY   #$D3
1FC8-   D4          ???
1FC9-   C1 A0       CMP   ($A0,X)
1FCB-   A4 B3       LDY   $B3
1FCD-   B1 B0       LDA   ($B0),Y
1FCF-   8D A0 D3    STA   $D3A0
1FD2-   D4          ???
1FD3-   C1 A0       CMP   ($A0,X)
1FD5-   A4 B3       LDY   $B3
1FD7-   B1 B1       LDA   ($B1),Y
1FD9-   8D A0 CC    STA   $CCA0
1FDC-   C4 C1       CPY   $C1
1FDE-   A0 A3       LDY   #$A3
1FE0-   B0 8D       BCS   $1F6F
1FE2-   A0 D3       LDY   #$D3
1FE4-   D4          ???
1FE5-   C1 A0       CMP   ($A0,X)
1FE7-   A4 B3       LDY   $B3
1FE9-   B1 B2       LDA   ($B2),Y
1FEB-   8D A0 D3    STA   $D3A0
1FEE-   D4          ???
1FEF-   C1 A0       CMP   ($A0,X)
1FF1-   A4 B3       LDY   $B3
1FF3-   B1 B3       LDA   ($B3),Y
1FF5-   8D A0 D3    STA   $D3A0
1FF8-   D4          ???
1FF9-   C1 A0       CMP   ($A0,X)
1FFB-   A4 B3       LDY   $B3
1FFD-   B1 B4       LDA   ($B4),Y
1FFF-   8D A0 D3    STA   $D3A0
2002-   D4          ???
2003-   C1 A0       CMP   ($A0,X)
2005-   A4 B3       LDY   $B3
2007-   B1 B5       LDA   ($B5),Y
2009-   8D A0 DF    STA   $DFA0
200C-   D7          ???
200D-   C1 C9       CMP   ($C9,X)
200F-   D4          ???
2010-   8D A0 DF    STA   $DFA0
2013-   D0 D2       BNE   $1FE7
2015-   CE D4 A0    DEC   $A0D4
2018-   A2 20       LDX   #$20
201A-   A2 AC       LDX   #$AC
201C-   B8          CLV
201D-   C4 B8       CPY   $B8
201F-   C4 8D       CPY   $8D
2021-   A0 DF       LDY   #$DF
2023-   D0 D2       BNE   $1FF7
2025-   CE D4 A0    DEC   $A0D4
2028-   A2 CE       LDX   #$CE
202A-   CF          ???
202B-   D7          ???
202C-   20 CC C5    JSR   $C5CC
202F-   D4          ???
2030-   A7          ???
2031-   D3          ???
2032-   20 C1 C4    JSR   $C4C1
2035-   C4 20       CPY   $20
2037-   D4          ???
2038-   C8          INY
2039-   C5 CD       CMP   $CD
203B-   20 D7 C9    JSR   $C9D7
203E-   D4          ???
203F-   C8          INY
2040-   20 D4 C8    JSR   $C8D4
2043-   C5 A2       CMP   $A2
2045-   AC B8 C4    LDY   $C4B8
2048-   8D A0 DF    STA   $DFA0
204B-   D0 D2       BNE   $201F
204D-   CE D4 A0    DEC   $A0D4
2050-   A2 C6       LDX   #$C6
2052-   D0 C1       BNE   $2015
2054-   C4 C4       CPY   $C4
2056-   20 CD C1    JSR   $C1CD
2059-   C3          ???
205A-   D2 CF       CMP   ($CF)
205C-   20 D4 CF    JSR   $CFD4
205F-   20 D3 C5    JSR   $C5D3
2062-   C5 20       CMP   $20
2064-   D4          ???
2065-   C8          INY
2066-   C5 20       CMP   $20
2068-   D2 C5       CMP   ($C5)
206A-   D3          ???
206B-   D5 CC       CMP   $CC,X
206D-   D4          ???
206E-   AE A2 AC    LDX   $ACA2
2071-   B8          CLV
2072-   C4 B8       CPY   $B8
2074-   C4 8D       CPY   $8D
2076-   A0 DF       LDY   #$DF
2078-   D0 D2       BNE   $204C
207A-   CE D4 A0    DEC   $A0D4
207D-   A2 C6       LDX   #$C6
207F-   D0 C1       BNE   $2042
2081-   C4 C4       CPY   $C4
2083-   20 A4 B3    JSR   $B3A4
2086-   B0 B0       BCS   $2038
2088-   BB          ???
2089-   A4 B3       LDY   $B3
208B-   B1 B0       LDA   ($B0),Y
208D-   20 D2 C5    JSR   $C5D2
2090-   D4          ???
2091-   D5 D2       CMP   $D2,X
2093-   CE D3 BA    DEC   $BAD3
2096-   A2 AC       LDX   #$AC
2098-   B8          CLV
2099-   C4 B8       CPY   $B8
209B-   C4 8D       CPY   $8D
209D-   A0 C6       LDY   #$C6
209F-   D0 C1       BNE   $2062
20A1-   C4 C4       CPY   $C4
20A3-   A0 A4       LDY   #$A4
20A5-   B3          ???
20A6-   B0 B0       BCS   $2058
20A8-   BB          ???
20A9-   A4 B3       LDY   $B3
20AB-   B1 B0       LDA   ($B0),Y
20AD-   8D A0 DF    STA   $DFA0
20B0-   C4 D5       CPY   $D5
20B2-   CD D0 A0    CMP   $A0D0
20B5-   D2 C5       CMP   ($C5)
20B7-   D4          ???
20B8-   D5 D2       CMP   $D2,X
20BA-   CE BB D2    DEC   $D2BB
20BD-   C5 D4       CMP   $D4
20BF-   CC C5 CE    CPY   $CEC5
20C2-   8D AA 8D    STA   $8DAA
20C5-   AA          TAX
20C6-   AA          TAX
20C7-   AA          TAX
20C8-   AA          TAX
20C9-   AA          TAX
20CA-   AA          TAX
20CB-   AA          TAX
20CC-   AA          TAX
20CD-   AA          TAX
20CE-   AA          TAX
20CF-   AA          TAX
20D0-   AA          TAX
20D1-   AA          TAX
20D2-   AA          TAX
20D3-   AA          TAX
20D4-   AA          TAX
20D5-   AA          TAX
20D6-   AA          TAX
20D7-   AA          TAX
20D8-   AA          TAX
20D9-   AA          TAX
20DA-   AA          TAX
20DB-   AA          TAX
20DC-   AA          TAX
20DD-   AA          TAX
20DE-   AA          TAX
20DF-   AA          TAX
20E0-   AA          TAX
20E1-   AA          TAX
20E2-   AA          TAX
20E3-   AA          TAX
20E4-   AA          TAX
20E5-   8D AA 8D    STA   $8DAA
20E8-   AA          TAX
20E9-   20 C5 CE    JSR   $CEC5
20EC-   C4 20       CPY   $20
20EE-   CF          ???
20EF-   C6 20       DEC   $20
20F1-   C3          ???
20F2-   CF          ???
20F3-   CE D3 D4    DEC   $D4D3
20F6-   D2 D5       CMP   ($D5)
20F8-   C3          ???
20F9-   D4          ???
20FA-   C9 CF       CMP   #$CF
20FC-   CE 8D AA    DEC   $AA8D
20FF-   8D AA AA    STA   $AAAA
2102-   AA          TAX
2103-   AA          TAX
2104-   AA          TAX
2105-   AA          TAX
2106-   AA          TAX
2107-   AA          TAX
2108-   AA          TAX
2109-   AA          TAX
210A-   AA          TAX
210B-   AA          TAX
210C-   AA          TAX
210D-   AA          TAX
210E-   AA          TAX
210F-   AA          TAX
2110-   AA          TAX
2111-   AA          TAX
2112-   AA          TAX
2113-   AA          TAX
2114-   AA          TAX
2115-   AA          TAX
2116-   AA          TAX
2117-   AA          TAX
2118-   AA          TAX
2119-   AA          TAX
211A-   AA          TAX
211B-   AA          TAX
211C-   AA          TAX
211D-   AA          TAX
211E-   AA          TAX
211F-   AA          TAX
2120-   8D AA 8D    STA   $8DAA
2123-   A0 CA       LDY   #$CA
2125-   CD D0 A0    CMP   $A0D0
2128-   D2 C5       CMP   ($C5)
212A-   C5 CE       CMP   $CE
212C-   D4          ???
212D-   D2 D9       CMP   ($D9)
212F-   8D AA 8D    STA   $8DAA
2132-   AA          TAX
2133-   E0 E0       CPX   #$E0
2135-   E0 E0       CPX   #$E0
2137-   E0 E0       CPX   #$E0
2139-   E0 E0       CPX   #$E0
213B-   E0 E0       CPX   #$E0
213D-   E0 E0       CPX   #$E0
213F-   E0 E0       CPX   #$E0
2141-   E0 E0       CPX   #$E0
2143-   E0 E0       CPX   #$E0
2145-   E0 E0       CPX   #$E0
2147-   E0 E0       CPX   #$E0
2149-   E0 E0       CPX   #$E0
214B-   E0 E0       CPX   #$E0
214D-   E0 E0       CPX   #$E0
214F-   E0 E0       CPX   #$E0
2151-   AA          TAX
2152-   8D AA 20    STA   $20AA
2155-   20 20 20    JSR   $2020
2158-   20 20 20    JSR   $2020
215B-   20 C2 CF    JSR   $CFC2
215E-   D4          ???
215F-   D4          ???
2160-   CF          ???
2161-   CD 20 C9    CMP   $C920
2164-   CE C3 CC    DEC   $CCC3
2167-   D5 C4       CMP   $C4,X
2169-   C5 D3       CMP   $D3
216B-   20 20 20    JSR   $2020
216E-   20 20 20    JSR   $2020
2171-   20 AA 8D    JSR   $8DAA
2174-   AA          TAX
2175-   AC AC AC    LDY   $ACAC
2178-   AC AC AC    LDY   $ACAC
217B-   AC AC AC    LDY   $ACAC
217E-   AC AC AC    LDY   $ACAC
2181-   AC AC AC    LDY   $ACAC
2184-   AC AC AC    LDY   $ACAC
2187-   AC AC AC    LDY   $ACAC
218A-   AC AC AC    LDY   $ACAC
218D-   AC AC AC    LDY   $ACAC
2190-   AC AC AC    LDY   $ACAC
2193-   AA          TAX
2194-   8D AA 8D    STA   $8DAA
2197-   AA          TAX
2198-   AA          TAX
2199-   20 C2 CF    JSR   $CFC2
219C-   D4          ???
219D-   D4          ???
219E-   CF          ???
219F-   CD 20 C9    CMP   $C920
21A2-   CE C3 CC    DEC   $CCC3
21A5-   D5 C4       CMP   $C4,X
21A7-   C5 D3       CMP   $D3
21A9-   8D AA 8D    STA   $8DAA
21AC-   A0 D0       LDY   #$D0
21AE-   D5 D4       CMP   $D4,X
21B0-   A0 CD       LDY   #$CD
21B2-   C1 D4       CMP   ($D4,X)
21B4-   C8          INY
21B5-   B8          CLV
21B6-   AE CC C9    LDX   $C9CC
21B9-   C2          ???
21BA-   8D A0 D0    STA   $D0A0
21BD-   D5 D4       CMP   $D4,X
21BF-   A0 CD       LDY   #$CD
21C1-   C1 D4       CMP   ($D4,X)
21C3-   C8          INY
21C4-   B1 B6       LDA   ($B6),Y
21C6-   AE CC C9    LDX   $C9CC
21C9-   C2          ???
21CA-   8D A0 D0    STA   $D0A0
21CD-   D5 D4       CMP   $D4,X
21CF-   A0 D2       LDY   #$D2
21D1-   C5 D1       CMP   $D1
21D3-   D5 C9       CMP   $C9,X
21D5-   D2 C5       CMP   ($C5)
21D7-   C4 AE       CPY   $AE
21D9-   CC C9 C2    CPY   $C2C9
21DC-   8D AA 8D    STA   $8DAA
