0901-   AA          TAX
0902-   AA          TAX
0903-   AA          TAX
0904-   AA          TAX
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   8D AA 20    STA   $20AA
0924-   20 20 20    JSR   $2020
0927-   20 20 20    JSR   $2020
092A-   20 20 20    JSR   $2020
092D-   20 20 20    JSR   $2020
0930-   20 20 20    JSR   $2020
0933-   20 20 20    JSR   $2020
0936-   20 20 20    JSR   $2020
0939-   20 20 20    JSR   $2020
093C-   20 20 20    JSR   $2020
093F-   20 20 AA    JSR   $AA20
0942-   8D AA 20    STA   $20AA
0945-   CD C1 CB    CMP   $CBC1
0948-   C5 C5       CMP   $C5
094A-   D8          CLD
094B-   C5 C3       CMP   $C3
094D-   20 20 20    JSR   $2020
0950-   20 20 20    JSR   $2020
0953-   20 20 20    JSR   $2020
0956-   20 20 20    JSR   $2020
0959-   20 20 20    JSR   $2020
095C-   20 20 20    JSR   $2020
095F-   20 20 20    JSR   $2020
0962-   AA          TAX
0963-   8D AA 20    STA   $20AA
0966-   20 20 20    JSR   $2020
0969-   20 20 20    JSR   $2020
096C-   20 20 20    JSR   $2020
096F-   20 20 20    JSR   $2020
0972-   20 20 20    JSR   $2020
0975-   20 20 20    JSR   $2020
0978-   20 20 20    JSR   $2020
097B-   20 20 20    JSR   $2020
097E-   20 20 20    JSR   $2020
0981-   20 20 AA    JSR   $AA20
0984-   8D AA 20    STA   $20AA
0987-   C3          ???
0988-   D2 C5       CMP   ($C5)
098A-   C1 D4       CMP   ($D4,X)
098C-   C5 D3       CMP   $D3
098E-   20 C1 CE    JSR   $CEC1
0991-   20 C5 D8    JSR   $D8C5
0994-   C5 C3       CMP   $C3
0996-   20 C6 C9    JSR   $C9C6
0999-   CC C5 20    CPY   $20C5
099C-   D4          ???
099D-   C8          INY
099E-   C1 D4       CMP   ($D4,X)
09A0-   20 20 20    JSR   $2020
09A3-   20 AA 8D    JSR   $8DAA
09A6-   AA          TAX
09A7-   20 D2 D5    JSR   $D5D2
09AA-   CE D3 20    DEC   $20D3
09AD-   C1 20       CMP   ($20,X)
09AF-   C2          ???
09B0-   C9 CE       CMP   #$CE
09B2-   C1 D2       CMP   ($D2,X)
09B4-   D9 AE 20    CMP   $20AE,Y
09B7-   CE C5 C3    DEC   $C3C5
09BA-   C5 D3       CMP   $D3
09BC-   D3          ???
09BD-   C1 D2       CMP   ($D2,X)
09BF-   D9 20 C6    CMP   $C620,Y
09C2-   CF          ???
09C3-   D2 20       CMP   ($20)
09C5-   AA          TAX
09C6-   8D AA 20    STA   $20AA
09C9-   C1 CE       CMP   ($CE,X)
09CB-   D9 20 C6    CMP   $C620,Y
09CE-   C9 CC       CMP   #$CC
09D0-   C5 20       CMP   $20
09D2-   CF          ???
09D3-   D0 C5       BNE   $099A
09D5-   D2 C1       CMP   ($C1)
09D7-   D4          ???
09D8-   C9 CF       CMP   #$CF
09DA-   CE D3 AE    DEC   $AED3
09DD-   20 20 20    JSR   $2020
09E0-   20 20 20    JSR   $2020
09E3-   20 20 20    JSR   $2020
09E6-   AA          TAX
09E7-   8D AA 20    STA   $20AA
09EA-   20 20 20    JSR   $2020
09ED-   20 20 20    JSR   $2020
09F0-   20 20 20    JSR   $2020
09F3-   20 20 20    JSR   $2020
09F6-   20 20 20    JSR   $2020
09F9-   20 20 20    JSR   $2020
09FC-   20 20 20    JSR   $2020
09FF-   20 20 20    JSR   $2020
0A02-   20 20 20    JSR   $2020
0A05-   20 20 AA    JSR   $AA20
0A08-   8D AA 20    STA   $20AA
0A0B-   CE CF D4    DEC   $D4CF
0A0E-   C5 20       CMP   $20
0A10-   D4          ???
0A11-   C8          INY
0A12-   C1 D4       CMP   ($D4,X)
0A14-   20 C9 D2    JSR   $D2C9
0A17-   CF          ???
0A18-   CE C9 C3    DEC   $C3C9
0A1B-   C1 CC       CMP   ($CC,X)
0A1D-   CC D9 AC    CPY   $ACD9
0A20-   20 D4 C8    JSR   $C8D4
0A23-   C9 D3       CMP   #$D3
0A25-   20 20 20    JSR   $2020
0A28-   AA          TAX
0A29-   8D AA 20    STA   $20AA
0A2C-   D0 D2       BNE   $0A00
0A2E-   CF          ???
0A2F-   C7          ???
0A30-   D2 C1       CMP   ($C1)
0A32-   CD 20 C9    CMP   $C920
0A35-   D4          ???
0A36-   D3          ???
0A37-   C5 CC       CMP   $CC
0A39-   C6 20       DEC   $20
0A3B-   C8          INY
0A3C-   C1 D3       CMP   ($D3,X)
0A3E-   20 D4 CF    JSR   $CFD4
0A41-   20 C2 C5    JSR   $C5C2
0A44-   20 D2 D5    JSR   $D5D2
0A47-   CE 20 AA    DEC   $AA20
0A4A-   8D AA 20    STA   $20AA
0A4D-   D4          ???
0A4E-   C8          INY
0A4F-   D2 CF       CMP   ($CF)
0A51-   D5 C7       CMP   $C7,X
0A53-   C8          INY
0A54-   20 C1 CE    JSR   $CEC1
0A57-   20 C5 D8    JSR   $D8C5
0A5A-   C5 C3       CMP   $C3
0A5C-   20 C6 C9    JSR   $C9C6
0A5F-   CC C5 AE    CPY   $AEC5
0A62-   AE AE 20    LDX   $20AE
0A65-   20 20 20    JSR   $2020
0A68-   20 20 AA    JSR   $AA20
0A6B-   8D AA 20    STA   $20AA
0A6E-   20 20 20    JSR   $2020
0A71-   20 20 20    JSR   $2020
0A74-   20 20 20    JSR   $2020
0A77-   20 20 20    JSR   $2020
0A7A-   20 20 20    JSR   $2020
0A7D-   20 20 20    JSR   $2020
0A80-   20 20 20    JSR   $2020
0A83-   20 20 20    JSR   $2020
0A86-   20 20 20    JSR   $2020
0A89-   20 20 AA    JSR   $AA20
0A8C-   8D AA AA    STA   $AAAA
0A8F-   AA          TAX
0A90-   AA          TAX
0A91-   AA          TAX
0A92-   AA          TAX
0A93-   AA          TAX
0A94-   AA          TAX
0A95-   AA          TAX
0A96-   AA          TAX
0A97-   AA          TAX
0A98-   AA          TAX
0A99-   AA          TAX
0A9A-   AA          TAX
0A9B-   AA          TAX
0A9C-   AA          TAX
0A9D-   AA          TAX
0A9E-   AA          TAX
0A9F-   AA          TAX
0AA0-   AA          TAX
0AA1-   AA          TAX
0AA2-   AA          TAX
0AA3-   AA          TAX
0AA4-   AA          TAX
0AA5-   AA          TAX
0AA6-   AA          TAX
0AA7-   AA          TAX
0AA8-   AA          TAX
0AA9-   AA          TAX
0AAA-   AA          TAX
0AAB-   AA          TAX
0AAC-   AA          TAX
0AAD-   8D AA 8D    STA   $8DAA
0AB0-   AA          TAX
0AB1-   AA          TAX
0AB2-   20 C1 D3    JSR   $D3C1
0AB5-   D3          ???
0AB6-   C5 CD       CMP   $CD
0AB8-   C2          ???
0AB9-   CC C5 D2    CPY   $D2C5
0ABC-   20 C4 C9    JSR   $C9C4
0ABF-   D2 C5       CMP   ($C5)
0AC1-   C3          ???
0AC2-   D4          ???
0AC3-   C9 D6       CMP   #$D6
0AC5-   C5 D3       CMP   $D3
0AC7-   8D AA 8D    STA   $8DAA
0ACA-   A0 C3       LDY   #$C3
0ACC-   D9 C3 A0    CMP   $A0C3,Y
0ACF-   C1 D6       CMP   ($D6,X)
0AD1-   C5 8D       CMP   $8D
0AD3-   A0 C5       LDY   #$C5
0AD5-   D8          CLD
0AD6-   D0 A0       BNE   $0A78
0AD8-   CF          ???
0AD9-   CE CC D9    DEC   $D9CC
0ADC-   A0 BB       LDY   #$BB
0ADE-   20 D4 D5    JSR   $D5D4
0AE1-   D2 CE       CMP   ($CE)
0AE3-   20 CF C6    JSR   $C6CF
0AE6-   C6 20       DEC   $20
0AE8-   CC C1 D4    CPY   $D4C1
0AEB-   C5 D2       CMP   $D2
0AED-   8D A0 C4    STA   $C4A0
0AF0-   D3          ???
0AF1-   CB          ???
0AF2-   A0 CD       LDY   #$CD
0AF4-   C1 CB       CMP   ($CB,X)
0AF6-   C5 C5       CMP   $C5
0AF8-   D8          CLD
0AF9-   C5 C3       CMP   $C3
0AFB-   8D A0 D4    STA   $D4A0
0AFE-   D2 A0       CMP   ($A0)
0B00-   CF          ???
0B01-   CE 8D A0    DEC   $A08D
0B04-   CF          ???
0B05-   C2          ???
0B06-   CA          DEX
0B07-   A0 A4       LDY   #$A4
0B09-   C2          ???
0B0A-   C6 C5       DEC   $C5
0B0C-   B0 8D       BCS   $0A9B
0B0E-   A0 CF       LDY   #$CF
0B10-   D2 C7       CMP   ($C7)
0B12-   A0 A4       LDY   #$A4
0B14-   B6 B0       LDX   $B0,Y
0B16-   B0 B0       BCS   $0AC8
0B18-   8D AA 8D    STA   $8DAA
0B1B-   AA          TAX
0B1C-   AA          TAX
0B1D-   AA          TAX
0B1E-   AA          TAX
0B1F-   AA          TAX
0B20-   AA          TAX
0B21-   AA          TAX
0B22-   AA          TAX
0B23-   AA          TAX
0B24-   AA          TAX
0B25-   AA          TAX
0B26-   AA          TAX
0B27-   AA          TAX
0B28-   AA          TAX
0B29-   AA          TAX
0B2A-   AA          TAX
0B2B-   AA          TAX
0B2C-   AA          TAX
0B2D-   AA          TAX
0B2E-   AA          TAX
0B2F-   AA          TAX
0B30-   AA          TAX
0B31-   AA          TAX
0B32-   AA          TAX
0B33-   AA          TAX
0B34-   AA          TAX
0B35-   AA          TAX
0B36-   AA          TAX
0B37-   AA          TAX
0B38-   AA          TAX
0B39-   AA          TAX
0B3A-   AA          TAX
0B3B-   8D AA 20    STA   $20AA
0B3E-   20 20 20    JSR   $2020
0B41-   20 20 20    JSR   $2020
0B44-   20 20 20    JSR   $2020
0B47-   20 20 20    JSR   $2020
0B4A-   20 20 20    JSR   $2020
0B4D-   20 20 20    JSR   $2020
0B50-   20 20 20    JSR   $2020
0B53-   20 20 20    JSR   $2020
0B56-   20 20 20    JSR   $2020
0B59-   20 20 AA    JSR   $AA20
0B5C-   8D AA 20    STA   $20AA
0B5F-   C8          INY
0B60-   C5 C1       CMP   $C1
0B62-   C4 C5       CPY   $C5
0B64-   D2 AC       CMP   ($AC)
0B66-   20 C8 CF    JSR   $CFC8
0B69-   CF          ???
0B6A-   CB          ???
0B6B-   D3          ???
0B6C-   20 C1 CE    JSR   $CEC1
0B6F-   C4 20       CPY   $20
0B71-   CD C1 C3    CMP   $C3C1
0B74-   D2 CF       CMP   ($CF)
0B76-   D3          ???
0B77-   20 20 20    JSR   $2020
0B7A-   20 20 AA    JSR   $AA20
0B7D-   8D AA 20    STA   $20AA
0B80-   20 20 20    JSR   $2020
0B83-   20 20 20    JSR   $2020
0B86-   20 20 20    JSR   $2020
0B89-   20 20 20    JSR   $2020
0B8C-   20 20 20    JSR   $2020
0B8F-   20 20 20    JSR   $2020
0B92-   20 20 20    JSR   $2020
0B95-   20 20 20    JSR   $2020
0B98-   20 20 20    JSR   $2020
0B9B-   20 20 AA    JSR   $AA20
0B9E-   8D AA AA    STA   $AAAA
0BA1-   AA          TAX
0BA2-   AA          TAX
0BA3-   AA          TAX
0BA4-   AA          TAX
0BA5-   AA          TAX
0BA6-   AA          TAX
0BA7-   AA          TAX
0BA8-   AA          TAX
0BA9-   AA          TAX
0BAA-   AA          TAX
0BAB-   AA          TAX
0BAC-   AA          TAX
0BAD-   AA          TAX
0BAE-   AA          TAX
0BAF-   AA          TAX
0BB0-   AA          TAX
0BB1-   AA          TAX
0BB2-   AA          TAX
0BB3-   AA          TAX
0BB4-   AA          TAX
0BB5-   AA          TAX
0BB6-   AA          TAX
0BB7-   AA          TAX
0BB8-   AA          TAX
0BB9-   AA          TAX
0BBA-   AA          TAX
0BBB-   AA          TAX
0BBC-   AA          TAX
0BBD-   AA          TAX
0BBE-   AA          TAX
0BBF-   8D AA 8D    STA   $8DAA
0BC2-   A0 D0       LDY   #$D0
0BC4-   D5 D4       CMP   $D4,X
0BC6-   A0 CD       LDY   #$CD
0BC8-   C9 CE       CMP   #$CE
0BCA-   AE D6 C1    LDX   $C1D6
0BCD-   D2 D3       CMP   ($D3)
0BCF-   AE D2 C5    LDX   $C5D2
0BD2-   D1 D5       CMP   ($D5),Y
0BD4-   C9 D2       CMP   #$D2
0BD6-   C5 C4       CMP   $C4
0BD8-   8D A0 D5    STA   $D5A0
0BDB-   D3          ???
0BDC-   C5 A0       CMP   $A0
0BDE-   CD C9 CE    CMP   $CEC9
0BE1-   AE CD C1    LDX   $C1CD
0BE4-   C3          ???
0BE5-   AE D3 D4    LDX   $D4D3
0BE8-   D2 C9       CMP   ($C9)
0BEA-   CE C7 D3    DEC   $D3C7
0BED-   8D A0 D5    STA   $D5A0
0BF0-   D3          ???
0BF1-   C5 A0       CMP   $A0
0BF3-   CD C9 CE    CMP   $CEC9
0BF6-   AE CD C1    LDX   $C1CD
0BF9-   C3          ???
0BFA-   AE D2 C5    LDX   $C5D2
0BFD-   D1 D5       CMP   ($D5),Y
0BFF-   C9 D2       CMP   #$D2
0C01-   C5 C4       CMP   $C4
0C03-   8D A0 D5    STA   $D5A0
0C06-   D3          ???
0C07-   C5 A0       CMP   $A0
0C09-   CD C9 CE    CMP   $CEC9
0C0C-   AE CD C1    LDX   $C1CD
0C0F-   C3          ???
0C10-   AE C6 C9    LDX   $C9C6
0C13-   CC C5 C9    CPY   $C9C5
0C16-   CF          ???
0C17-   8D A0 D5    STA   $D5A0
0C1A-   D3          ???
0C1B-   C5 A0       CMP   $A0
0C1D-   CD C9 CE    CMP   $CEC9
0C20-   AE CD C1    LDX   $C1CD
0C23-   C3          ???
0C24-   AE D3 D4    LDX   $D4D3
0C27-   C4 C9       CPY   $C9
0C29-   CF          ???
0C2A-   8D A0 D0    STA   $D0A0
0C2D-   D5 D4       CMP   $D4,X
0C2F-   A0 CD       LDY   #$CD
0C31-   C9 CE       CMP   #$CE
0C33-   AE C8 CF    LDX   $CFC8
0C36-   CF          ???
0C37-   CB          ???
0C38-   D3          ???
0C39-   AE D2 C5    LDX   $C5D2
0C3C-   D1 D5       CMP   ($D5),Y
0C3E-   C9 D2       CMP   #$D2
0C40-   C5 C4       CMP   $C4
0C42-   8D A0 D0    STA   $D0A0
0C45-   D5 D4       CMP   $D4,X
0C47-   A0 CD       LDY   #$CD
0C49-   C9 CE       CMP   #$CE
0C4B-   AE C8 CF    LDX   $CFC8
0C4E-   CF          ???
0C4F-   CB          ???
0C50-   D3          ???
0C51-   AE D3 D4    LDX   $D4D3
0C54-   C4 C9       CPY   $C9
0C56-   CF          ???
0C57-   8D A0 D0    STA   $D0A0
0C5A-   D5 D4       CMP   $D4,X
0C5C-   A0 CD       LDY   #$CD
0C5E-   C9 CE       CMP   #$CE
0C60-   AE C8 CF    LDX   $CFC8
0C63-   CF          ???
0C64-   CB          ???
0C65-   D3          ???
0C66-   AE C6 C9    LDX   $C9C6
0C69-   CC C5 C9    CPY   $C9C5
0C6C-   CF          ???
0C6D-   8D A0 D0    STA   $D0A0
0C70-   D5 D4       CMP   $D4,X
0C72-   A0 CD       LDY   #$CD
0C74-   C9 CE       CMP   #$CE
0C76-   AE C8 CF    LDX   $CFC8
0C79-   CF          ???
0C7A-   CB          ???
0C7B-   D3          ???
0C7C-   AE D3 D4    LDX   $D4D3
0C7F-   D2 C9       CMP   ($C9)
0C81-   CE C7 D3    DEC   $D3C7
0C84-   8D AA 8D    STA   $8DAA
0C87-   AA          TAX
0C88-   AA          TAX
0C89-   AA          TAX
0C8A-   AA          TAX
0C8B-   AA          TAX
0C8C-   AA          TAX
0C8D-   AA          TAX
0C8E-   AA          TAX
0C8F-   AA          TAX
0C90-   AA          TAX
0C91-   AA          TAX
0C92-   AA          TAX
0C93-   AA          TAX
0C94-   AA          TAX
0C95-   AA          TAX
0C96-   AA          TAX
0C97-   AA          TAX
0C98-   AA          TAX
0C99-   AA          TAX
0C9A-   AA          TAX
0C9B-   AA          TAX
0C9C-   AA          TAX
0C9D-   AA          TAX
0C9E-   AA          TAX
0C9F-   AA          TAX
0CA0-   AA          TAX
0CA1-   AA          TAX
0CA2-   AA          TAX
0CA3-   AA          TAX
0CA4-   AA          TAX
0CA5-   AA          TAX
0CA6-   AA          TAX
0CA7-   8D AA 20    STA   $20AA
0CAA-   20 20 20    JSR   $2020
0CAD-   20 20 20    JSR   $2020
0CB0-   20 20 20    JSR   $2020
0CB3-   20 20 20    JSR   $2020
0CB6-   20 20 20    JSR   $2020
0CB9-   20 20 20    JSR   $2020
0CBC-   20 20 20    JSR   $2020
0CBF-   20 20 20    JSR   $2020
0CC2-   20 20 20    JSR   $2020
0CC5-   20 20 AA    JSR   $AA20
0CC8-   8D AA 20    STA   $20AA
0CCB-   C3          ???
0CCC-   CF          ???
0CCD-   CE D3 D4    DEC   $D4D3
0CD0-   C1 CE       CMP   ($CE,X)
0CD2-   D4          ???
0CD3-   20 C4 C5    JSR   $C5C4
0CD6-   C3          ???
0CD7-   CC C1 D2    CPY   $D2C1
0CDA-   C1 D4       CMP   ($D4,X)
0CDC-   C9 CF       CMP   #$CF
0CDE-   CE D3 20    DEC   $20D3
0CE1-   20 20 20    JSR   $2020
0CE4-   20 20 20    JSR   $2020
0CE7-   20 AA 8D    JSR   $8DAA
0CEA-   AA          TAX
0CEB-   20 20 20    JSR   $2020
0CEE-   20 20 20    JSR   $2020
0CF1-   20 20 20    JSR   $2020
0CF4-   20 20 20    JSR   $2020
0CF7-   20 20 20    JSR   $2020
0CFA-   20 20 20    JSR   $2020
0CFD-   20 20 20    JSR   $2020
0D00-   20 20 20    JSR   $2020
0D03-   20 20 20    JSR   $2020
0D06-   20 20 20    JSR   $2020
0D09-   AA          TAX
0D0A-   8D AA AA    STA   $AAAA
0D0D-   AA          TAX
0D0E-   AA          TAX
0D0F-   AA          TAX
0D10-   AA          TAX
0D11-   AA          TAX
0D12-   AA          TAX
0D13-   AA          TAX
0D14-   AA          TAX
0D15-   AA          TAX
0D16-   AA          TAX
0D17-   AA          TAX
0D18-   AA          TAX
0D19-   AA          TAX
0D1A-   AA          TAX
0D1B-   AA          TAX
0D1C-   AA          TAX
0D1D-   AA          TAX
0D1E-   AA          TAX
0D1F-   AA          TAX
0D20-   AA          TAX
0D21-   AA          TAX
0D22-   AA          TAX
0D23-   AA          TAX
0D24-   AA          TAX
0D25-   AA          TAX
0D26-   AA          TAX
0D27-   AA          TAX
0D28-   AA          TAX
0D29-   AA          TAX
0D2A-   AA          TAX
0D2B-   8D AA 8D    STA   $8DAA
0D2E-   AA          TAX
0D2F-   8D AA AA    STA   $AAAA
0D32-   AA          TAX
0D33-   AA          TAX
0D34-   AA          TAX
0D35-   AA          TAX
0D36-   AA          TAX
0D37-   AA          TAX
0D38-   AA          TAX
0D39-   AA          TAX
0D3A-   AA          TAX
0D3B-   AA          TAX
0D3C-   AA          TAX
0D3D-   AA          TAX
0D3E-   AA          TAX
0D3F-   AA          TAX
0D40-   AA          TAX
0D41-   AA          TAX
0D42-   AA          TAX
0D43-   AA          TAX
0D44-   AA          TAX
0D45-   AA          TAX
0D46-   AA          TAX
0D47-   AA          TAX
0D48-   AA          TAX
0D49-   AA          TAX
0D4A-   AA          TAX
0D4B-   AA          TAX
0D4C-   AA          TAX
0D4D-   AA          TAX
0D4E-   AA          TAX
0D4F-   AA          TAX
0D50-   8D AA 20    STA   $20AA
0D53-   20 20 20    JSR   $2020
0D56-   20 20 20    JSR   $2020
0D59-   20 20 20    JSR   $2020
0D5C-   20 20 20    JSR   $2020
0D5F-   20 20 20    JSR   $2020
0D62-   20 20 20    JSR   $2020
0D65-   20 20 20    JSR   $2020
0D68-   20 20 20    JSR   $2020
0D6B-   20 20 20    JSR   $2020
0D6E-   20 20 AA    JSR   $AA20
0D71-   8D AA 20    STA   $20AA
0D74-   CD C1 C9    CMP   $C9C1
0D77-   CE 20 D0    DEC   $D020
0D7A-   D2 CF       CMP   ($CF)
0D7C-   C7          ???
0D7D-   D2 C1       CMP   ($C1)
0D7F-   CD 20 CC    CMP   $CC20
0D82-   CF          ???
0D83-   CF          ???
0D84-   D0 20       BNE   $0DA6
0D86-   20 20 20    JSR   $2020
0D89-   20 20 20    JSR   $2020
0D8C-   20 20 20    JSR   $2020
0D8F-   20 20 AA    JSR   $AA20
0D92-   8D AA 20    STA   $20AA
0D95-   20 20 20    JSR   $2020
0D98-   20 20 20    JSR   $2020
0D9B-   20 20 20    JSR   $2020
0D9E-   20 20 20    JSR   $2020
0DA1-   20 20 20    JSR   $2020
0DA4-   20 20 20    JSR   $2020
0DA7-   20 20 20    JSR   $2020
0DAA-   20 20 20    JSR   $2020
0DAD-   20 20 20    JSR   $2020
0DB0-   20 20 AA    JSR   $AA20
0DB3-   8D AA AA    STA   $AAAA
0DB6-   AA          TAX
0DB7-   AA          TAX
0DB8-   AA          TAX
0DB9-   AA          TAX
0DBA-   AA          TAX
0DBB-   AA          TAX
0DBC-   AA          TAX
0DBD-   AA          TAX
0DBE-   AA          TAX
0DBF-   AA          TAX
0DC0-   AA          TAX
0DC1-   AA          TAX
0DC2-   AA          TAX
0DC3-   AA          TAX
0DC4-   AA          TAX
0DC5-   AA          TAX
0DC6-   AA          TAX
0DC7-   AA          TAX
0DC8-   AA          TAX
0DC9-   AA          TAX
0DCA-   AA          TAX
0DCB-   AA          TAX
0DCC-   AA          TAX
0DCD-   AA          TAX
0DCE-   AA          TAX
0DCF-   AA          TAX
0DD0-   AA          TAX
0DD1-   AA          TAX
0DD2-   AA          TAX
0DD3-   AA          TAX
0DD4-   8D AA 8D    STA   $8DAA
0DD7-   A0 CA       LDY   #$CA
0DD9-   D3          ???
0DDA-   D2 A0       CMP   ($A0)
0DDC-   C8          INY
0DDD-   CF          ???
0DDE-   CD C5 8D    CMP   $8DC5
0DE1-   A0 D0       LDY   #$D0
0DE3-   D2 CE       CMP   ($CE)
0DE5-   A0 A2       LDY   #$A2
0DE7-   AA          TAX
0DE8-   AA          TAX
0DE9-   AA          TAX
0DEA-   AA          TAX
0DEB-   AA          TAX
0DEC-   AA          TAX
0DED-   AA          TAX
0DEE-   AA          TAX
0DEF-   AA          TAX
0DF0-   AA          TAX
0DF1-   AA          TAX
0DF2-   AA          TAX
0DF3-   AA          TAX
0DF4-   AA          TAX
0DF5-   AA          TAX
0DF6-   AA          TAX
0DF7-   AA          TAX
0DF8-   AA          TAX
0DF9-   AA          TAX
0DFA-   AA          TAX
0DFB-   AA          TAX
0DFC-   AA          TAX
0DFD-   AA          TAX
0DFE-   AA          TAX
0DFF-   A2 AC       LDX   #$AC
0E01-   B8          CLV
0E02-   C4 8D       CPY   $8D
0E04-   A0 D0       LDY   #$D0
0E06-   D2 CE       CMP   ($CE)
0E08-   A0 A2       LDY   #$A2
0E0A-   AA          TAX
0E0B-   20 20 20    JSR   $2020
0E0E-   20 20 20    JSR   $2020
0E11-   20 20 20    JSR   $2020
0E14-   20 20 20    JSR   $2020
0E17-   20 20 20    JSR   $2020
0E1A-   20 20 20    JSR   $2020
0E1D-   20 20 20    JSR   $2020
0E20-   20 AA A2    JSR   $A2AA
0E23-   AC B8 C4    LDY   $C4B8
0E26-   8D A0 D0    STA   $D0A0
0E29-   D2 CE       CMP   ($CE)
0E2B-   A0 A2       LDY   #$A2
0E2D-   AA          TAX
0E2E-   20 C5 D8    JSR   $D8C5
0E31-   C5 C3       CMP   $C3
0E33-   20 C6 C9    JSR   $C9C6
0E36-   CC C5 20    CPY   $20C5
0E39-   CD C1 CB    CMP   $CBC1
0E3C-   C5 D2       CMP   $D2
0E3E-   20 C6 CF    JSR   $CFC6
0E41-   D2 20       CMP   ($20)
0E43-   20 AA A2    JSR   $A2AA
0E46-   AC B8 C4    LDY   $C4B8
0E49-   8D A0 D0    STA   $D0A0
0E4C-   D2 CE       CMP   ($CE)
0E4E-   A0 A2       LDY   #$A2
0E50-   AA          TAX
0E51-   20 C2 C9    JSR   $C9C2
0E54-   CE C1 D2    DEC   $D2C1
0E57-   D9 20 D0    CMP   $D020,Y
0E5A-   D2 CF       CMP   ($CF)
0E5C-   C7          ???
0E5D-   D2 C1       CMP   ($C1)
0E5F-   CD D3 20    CMP   $20D3
0E62-   D4          ???
0E63-   C8          INY
0E64-   C1 D4       CMP   ($D4,X)
0E66-   20 AA A2    JSR   $A2AA
0E69-   AC B8 C4    LDY   $C4B8
0E6C-   8D A0 D0    STA   $D0A0
0E6F-   D2 CE       CMP   ($CE)
0E71-   A0 A2       LDY   #$A2
0E73-   AA          TAX
0E74-   20 D5 D3    JSR   $D3D5
0E77-   C5 20       CMP   $20
0E79-   C1 D0       CMP   ($D0,X)
0E7B-   D0 CC       BNE   $0E49
0E7D-   C5 D3       CMP   $D3
0E7F-   CF          ???
0E80-   C6 D4       DEC   $D4
0E82-   AE 20 20    LDX   $2020
0E85-   20 20 20    JSR   $2020
0E88-   20 20 AA    JSR   $AA20
0E8B-   A2 AC       LDX   #$AC
0E8D-   B8          CLV
0E8E-   C4 8D       CPY   $8D
0E90-   A0 D0       LDY   #$D0
0E92-   D2 CE       CMP   ($CE)
0E94-   A0 A2       LDY   #$A2
0E96-   AA          TAX
0E97-   20 20 20    JSR   $2020
0E9A-   20 20 20    JSR   $2020
0E9D-   20 20 20    JSR   $2020
0EA0-   20 20 20    JSR   $2020
0EA3-   20 20 20    JSR   $2020
0EA6-   20 20 20    JSR   $2020
0EA9-   20 20 20    JSR   $2020
0EAC-   20 AA 20    JSR   $20AA
0EAF-   A2 AC       LDX   #$AC
0EB1-   B8          CLV
0EB2-   C4 8D       CPY   $8D
0EB4-   A0 D0       LDY   #$D0
0EB6-   D2 CE       CMP   ($CE)
0EB8-   A0 A2       LDY   #$A2
0EBA-   AA          TAX
0EBB-   AA          TAX
0EBC-   AA          TAX
0EBD-   AA          TAX
0EBE-   AA          TAX
0EBF-   AA          TAX
0EC0-   AA          TAX
0EC1-   AA          TAX
0EC2-   AA          TAX
0EC3-   AA          TAX
0EC4-   AA          TAX
0EC5-   AA          TAX
0EC6-   AA          TAX
0EC7-   AA          TAX
0EC8-   AA          TAX
0EC9-   AA          TAX
0ECA-   AA          TAX
0ECB-   AA          TAX
0ECC-   AA          TAX
0ECD-   AA          TAX
0ECE-   AA          TAX
0ECF-   AA          TAX
0ED0-   AA          TAX
0ED1-   AA          TAX
0ED2-   A2 AC       LDX   #$AC
0ED4-   B8          CLV
0ED5-   C4 B8       CPY   $B8
0ED7-   C4 B8       CPY   $B8
0ED9-   C4 8D       CPY   $8D
0EDB-   AA          TAX
0EDC-   8D A0 D0    STA   $D0A0
0EDF-   D2 CE       CMP   ($CE)
0EE1-   A0 A2       LDY   #$A2
0EE3-   C2          ???
0EE4-   C9 CE       CMP   #$CE
0EE6-   20 C6 C9    JSR   $C9C6
0EE9-   CC C5 CE    CPY   $CEC5
0EEC-   C1 CD       CMP   ($CD,X)
0EEE-   C5 BA       CMP   $BA
0EF0-   20 A2 8D    JSR   $8DA2
0EF3-   A0 C9       LDY   #$C9
0EF5-   CE D0 8D    DEC   $8DD0
0EF8-   A0 CC       LDY   #$CC
0EFA-   C4 C1       CPY   $C1
0EFC-   A0 D2       LDY   #$D2
0EFE-   C5 D4       CMP   $D4
0F00-   CC C5 CE    CPY   $CEC5
0F03-   8D A0 C7    STA   $C7A0
0F06-   D2 C5       CMP   ($C5)
0F08-   D4          ???
0F09-   A0 A3       LDY   #$A3
0F0B-   C2          ???
0F0C-   CE C1 CD    DEC   $CDC1
0F0F-   C5 A0       CMP   $A0
0F11-   BB          ???
0F12-   20 D4 D2    JSR   $D2D4
0F15-   C1 CE       CMP   ($CE,X)
0F17-   D3          ???
0F18-   C6 C5       DEC   $C5
0F1A-   D2 20       CMP   ($20)
0F1C-   D2 C5       CMP   ($C5)
0F1E-   D4          ???
0F1F-   D5 D2       CMP   $D2,X
0F21-   CE 20 D4    DEC   $D420
0F24-   CF          ???
0F25-   20 C2 CE    JSR   $CEC2
0F28-   C1 CD       CMP   ($CD,X)
0F2A-   C5 8D       CMP   $8D
0F2C-   AA          TAX
0F2D-   8D A0 D0    STA   $D0A0
0F30-   D2 CE       CMP   ($CE)
0F32-   A0 A2       LDY   #$A2
0F34-   C2          ???
0F35-   C9 CE       CMP   #$CE
0F37-   20 D3 D4    JSR   $D4D3
0F3A-   C1 D2       CMP   ($D2,X)
0F3C-   D4          ???
0F3D-   C9 CE       CMP   #$CE
0F3F-   C7          ???
0F40-   20 C1 C4    JSR   $C4C1
0F43-   C4 D2       CPY   $D2
0F45-   C5 D3       CMP   $D3
0F47-   D3          ???
0F48-   BA          TSX
0F49-   20 A2 8D    JSR   $8DA2
0F4C-   A0 C9       LDY   #$C9
0F4E-   CE D0 8D    DEC   $8DD0
0F51-   A0 CC       LDY   #$CC
0F53-   C4 C1       CPY   $C1
0F55-   A0 D2       LDY   #$D2
0F57-   C5 D4       CMP   $D4
0F59-   CC C5 CE    CPY   $CEC5
0F5C-   8D A0 C7    STA   $C7A0
0F5F-   D2 C5       CMP   ($C5)
0F61-   D4          ???
0F62-   A0 A3       LDY   #$A3
0F64-   C2          ???
0F65-   CC CF C3    CPY   $C3CF
0F68-   8D AA 8D    STA   $8DAA
0F6B-   A0 D3       LDY   #$D3
0F6D-   C3          ???
0F6E-   C1 D4       CMP   ($D4,X)
0F70-   A0 A2       LDY   #$A2
0F72-   C7          ???
0F73-   CF          ???
0F74-   AE A2 BB    LDX   $BBA2
0F77-   A3          ???
0F78-   C2          ???
0F79-   CE C1 CD    DEC   $CDC1
0F7C-   C5 BB       CMP   $BB
0F7E-   A3          ???
0F7F-   B2 B0       LDA   ($B0)
0F81-   20 BB 20    JSR   $20BB
0F84-   D0 D2       BNE   $0F58
0F86-   C5 C6       CMP   $C6
0F88-   C9 D8       CMP   #$D8
0F8A-   20 CE C1    JSR   $C1CE
0F8D-   CD C5 20    CMP   $20C5
0F90-   D7          ???
0F91-   C9 D4       CMP   #$D4
0F93-   C8          INY
0F94-   20 C7 CF    JSR   $CFC7
0F97-   AE 8D AA    LDX   $AA8D
0F9A-   8D A0 C7    STA   $C7A0
0F9D-   D2 C5       CMP   ($C5)
0F9F-   D4          ???
0FA0-   A0 A3       LDY   #$A3
0FA2-   D4          ???
0FA3-   CE C1 CD    DEC   $CDC1
0FA6-   C5 A0       CMP   $A0
0FA8-   BB          ???
0FA9-   20 D3 D4    JSR   $D4D3
0FAC-   CF          ???
0FAD-   D2 C5       CMP   ($C5)
0FAF-   20 D2 C5    JSR   $C5D2
0FB2-   D3          ???
0FB3-   D5 CC       CMP   $CC,X
0FB5-   D4          ???
0FB6-   C9 CE       CMP   #$CE
0FB8-   C7          ???
0FB9-   20 D3 D4    JSR   $D4D3
0FBC-   D2 C9       CMP   ($C9)
0FBE-   CE C7 20    DEC   $20C7
0FC1-   C9 CE       CMP   #$CE
0FC3-   20 D4 CE    JSR   $CED4
0FC6-   C1 CD       CMP   ($CD,X)
0FC8-   C5 8D       CMP   $8D
0FCA-   AA          TAX
0FCB-   8D A0 D0    STA   $D0A0
0FCE-   D2 CE       CMP   ($CE)
0FD0-   A0 A2       LDY   #$A2
0FD2-   20 A2 AC    JSR   $ACA2
0FD5-   B8          CLV
0FD6-   C4 8D       CPY   $8D
0FD8-   A0 D0       LDY   #$D0
0FDA-   D2 CE       CMP   ($CE)
0FDC-   A0 A2       LDY   #$A2
0FDE-   C2          ???
0FDF-   D5 C9       CMP   $C9,X
0FE1-   CC C4 C9    CPY   $C9C4
0FE4-   CE C7 20    DEC   $20C7
0FE7-   C6 C9       DEC   $C9
0FE9-   CC C5 BA    CPY   $BAC5
0FEC-   20 A2 8D    JSR   $8DA2
0FEF-   A0 D3       LDY   #$D3
0FF1-   D0 D2       BNE   $0FC5
0FF3-   CE A0 A3    DEC   $A3A0
0FF6-   D4          ???
0FF7-   CE C1 CD    DEC   $CDC1
0FFA-   C5 8D       CMP   $8D
0FFC-   A0 D0       LDY   #$D0
0FFE-   D2 CE       CMP   ($CE)
1000-   A0 A2       LDY   #$A2
1002-   20 A2 AC    JSR   $ACA2
1005-   B8          CLV
1006-   C4 B8       CPY   $B8
1008-   C4 8D       CPY   $8D
100A-   AA          TAX
100B-   8D AA AA    STA   $AAAA
100E-   20 CF D0    JSR   $D0CF
1011-   C5 CE       CMP   $CE
1013-   20 C6 C9    JSR   $C9C6
1016-   CC C5 20    CPY   $20C5
1019-   C6 CF       DEC   $CF
101B-   D2 20       CMP   ($20)
101D-   D7          ???
101E-   D2 C9       CMP   ($C9)
1020-   D4          ???
1021-   C9 CE       CMP   #$CE
1023-   C7          ???
1024-   8D AA 8D    STA   $8DAA
1027-   A0 D3       LDY   #$D3
1029-   C3          ???
102A-   C1 D4       CMP   ($D4,X)
102C-   A0 A2       LDY   #$A2
102E-   CF          ???
102F-   D0 C5       BNE   $0FF6
1031-   CE 20 A2    DEC   $A220
1034-   BB          ???
1035-   A3          ???
1036-   D4          ???
1037-   CE C1 CD    DEC   $CDC1
103A-   C5 BB       CMP   $BB
103C-   A3          ???
103D-   B2 B5       LDA   ($B5)
103F-   B5 8D       LDA   $8D,X
1041-   A0 C3       LDY   #$C3
1043-   CD C4 A0    CMP   $A0C4
1046-   A3          ???
1047-   D2 C5       CMP   ($C5)
1049-   D4          ???
104A-   D5 D2       CMP   $D2,X
104C-   CE 8D A0    DEC   $A08D
104F-   D3          ???
1050-   C3          ???
1051-   C1 D4       CMP   ($D4,X)
1053-   A0 A2       LDY   #$A2
1055-   D7          ???
1056-   D2 C9       CMP   ($C9)
1058-   D4          ???
1059-   C5 20       CMP   $20
105B-   A2 BB       LDX   #$BB
105D-   A3          ???
105E-   D4          ???
105F-   CE C1 CD    DEC   $CDC1
1062-   C5 BB       CMP   $BB
1064-   A3          ???
1065-   B2 B5       LDA   ($B5)
1067-   B5 8D       LDA   $8D,X
1069-   A0 C3       LDY   #$C3
106B-   CD C4 A0    CMP   $A0C4
106E-   A3          ???
106F-   D2 C5       CMP   ($C5)
1071-   D4          ???
1072-   D5 D2       CMP   $D2,X
1074-   CE 8D AA    DEC   $AA8D
1077-   8D AA AA    STA   $AAAA
107A-   20 D0 D2    JSR   $D2D0
107D-   C9 CE       CMP   #$CE
107F-   D4          ???
1080-   20 D4 CF    JSR   $CFD4
1083-   20 C6 C9    JSR   $C9C6
1086-   CC C5 8D    CPY   $8DC5
1089-   AA          TAX
108A-   8D A0 D3    STA   $D3A0
108D-   C3          ???
108E-   C1 D4       CMP   ($D4,X)
1090-   A0 A2       LDY   #$A2
1092-   C2          ???
1093-   CC CF C1    CPY   $C1CF
1096-   C4 20       CPY   $20
1098-   A2 BB       LDX   #$BB
109A-   A3          ???
109B-   C2          ???
109C-   CE C1 CD    DEC   $CDC1
109F-   C5 BB       CMP   $BB
10A1-   A3          ???
10A2-   B2 B5       LDA   ($B5)
10A4-   B5 8D       LDA   $8D,X
10A6-   A0 C6       LDY   #$C6
10A8-   D0 D2       BNE   $107C
10AA-   CE A0 A3    DEC   $A3A0
10AD-   D2 C5       CMP   ($C5)
10AF-   D4          ???
10B0-   D5 D2       CMP   $D2,X
10B2-   CE 8D A0    DEC   $A08D
10B5-   CC C4 C1    CPY   $C1C4
10B8-   A0 A3       LDY   #$A3
10BA-   A4 B8       LDY   $B8
10BC-   C4 8D       CPY   $8D
10BE-   A0 CA       LDY   #$CA
10C0-   D3          ???
10C1-   D2 A0       CMP   ($A0)
10C3-   C6 C3       DEC   $C3
10C5-   CF          ???
10C6-   D5 D4       CMP   $D4,X
10C8-   8D A0 C6    STA   $C6A0
10CB-   D0 D2       BNE   $109F
10CD-   CE A0 A2    DEC   $A2A0
10D0-   C3          ???
10D1-   C1 CC       CMP   ($CC,X)
10D3-   CC 20 AD    CPY   $AD20
10D6-   B1 B5       LDA   ($B5),Y
10D8-   B1 A2       LDA   ($A2),Y
10DA-   8D A0 D3    STA   $D3A0
10DD-   C3          ???
10DE-   C1 D4       CMP   ($D4,X)
10E0-   A0 A3       LDY   #$A3
10E2-   C2          ???
10E3-   CC CF C3    CPY   $C3CF
10E6-   BB          ???
10E7-   A2 C7       LDX   #$C7
10E9-   A2 BB       LDX   #$BB
10EB-   A3          ???
10EC-   B2 B5       LDA   ($B5)
10EE-   B5 8D       LDA   $8D,X
10F0-   A0 C6       LDY   #$C6
10F2-   D0 D2       BNE   $10C6
10F4-   CE A0 A3    DEC   $A3A0
10F7-   D2 C5       CMP   ($C5)
10F9-   D4          ???
10FA-   D5 D2       CMP   $D2,X
10FC-   CE 8D AA    DEC   $AA8D
10FF-   8D AA AA    STA   $AAAA
1102-   20 C3 CC    JSR   $CCC3
1105-   CF          ???
1106-   D3          ???
1107-   C5 20       CMP   $20
1109-   C6 C9       DEC   $C9
110B-   CC C5 8D    CPY   $8DC5
110E-   AA          TAX
110F-   8D A0 D3    STA   $D3A0
1112-   C3          ???
1113-   C1 D4       CMP   ($D4,X)
1115-   A0 A2       LDY   #$A2
1117-   C3          ???
1118-   CC CF D3    CPY   $D3CF
111B-   C5 20       CMP   $20
111D-   A2 BB       LDX   #$BB
111F-   A3          ???
1120-   D4          ???
1121-   CE C1 CD    DEC   $CDC1
1124-   C5 BB       CMP   $BB
1126-   A3          ???
1127-   B2 B5       LDA   ($B5)
1129-   B5 8D       LDA   $8D,X
112B-   A0 C3       LDY   #$C3
112D-   CD C4 A0    CMP   $A0C4
1130-   A3          ???
1131-   D2 C5       CMP   ($C5)
1133-   D4          ???
1134-   D5 D2       CMP   $D2,X
1136-   CE 8D AA    DEC   $AA8D
1139-   8D A0 D0    STA   $D0A0
113C-   D2 CE       CMP   ($CE)
113E-   A0 A2       LDY   #$A2
1140-   C4 CF       CPY   $CF
1142-   CE C5 A1    DEC   $A1C5
1145-   A2 AC       LDX   #$AC
1147-   B8          CLV
1148-   C4 B8       CPY   $B8
114A-   C4 8D       CPY   $8D
114C-   A0 CA       LDY   #$CA
114E-   CD D0 A0    CMP   $A0D0
1151-   D2 C5       CMP   ($C5)
1153-   C5 CE       CMP   $CE
1155-   D4          ???
1156-   D2 D9       CMP   ($D9)
1158-   8D AA 8D    STA   $8DAA
115B-   AA          TAX
115C-   AA          TAX
115D-   AA          TAX
115E-   AA          TAX
115F-   AA          TAX
1160-   AA          TAX
1161-   AA          TAX
1162-   AA          TAX
1163-   AA          TAX
1164-   AA          TAX
1165-   AA          TAX
1166-   AA          TAX
1167-   AA          TAX
1168-   AA          TAX
1169-   AA          TAX
116A-   AA          TAX
116B-   AA          TAX
116C-   AA          TAX
116D-   AA          TAX
116E-   AA          TAX
116F-   AA          TAX
1170-   AA          TAX
1171-   AA          TAX
1172-   AA          TAX
1173-   AA          TAX
1174-   AA          TAX
1175-   AA          TAX
1176-   AA          TAX
1177-   AA          TAX
1178-   AA          TAX
1179-   AA          TAX
117A-   AA          TAX
117B-   8D AA 20    STA   $20AA
117E-   20 20 20    JSR   $2020
1181-   20 20 20    JSR   $2020
1184-   20 20 20    JSR   $2020
1187-   20 20 20    JSR   $2020
118A-   20 20 20    JSR   $2020
118D-   20 20 20    JSR   $2020
1190-   20 20 20    JSR   $2020
1193-   20 20 20    JSR   $2020
1196-   20 20 20    JSR   $2020
1199-   20 20 AA    JSR   $AA20
119C-   8D AA 20    STA   $20AA
119F-   D6 C1       DEC   $C1,X
11A1-   D2 C9       CMP   ($C9)
11A3-   C1 C2       CMP   ($C2,X)
11A5-   CC C5 D3    CPY   $D3C5
11A8-   20 20 20    JSR   $2020
11AB-   20 20 20    JSR   $2020
11AE-   20 20 20    JSR   $2020
11B1-   20 20 20    JSR   $2020
11B4-   20 20 20    JSR   $2020
11B7-   20 20 20    JSR   $2020
11BA-   20 20 AA    JSR   $AA20
11BD-   8D AA 20    STA   $20AA
11C0-   20 20 20    JSR   $2020
11C3-   20 20 20    JSR   $2020
11C6-   20 20 20    JSR   $2020
11C9-   20 20 20    JSR   $2020
11CC-   20 20 20    JSR   $2020
11CF-   20 20 20    JSR   $2020
11D2-   20 20 20    JSR   $2020
11D5-   20 20 20    JSR   $2020
11D8-   20 20 20    JSR   $2020
11DB-   20 20 AA    JSR   $AA20
11DE-   8D AA AA    STA   $AAAA
11E1-   AA          TAX
11E2-   AA          TAX
11E3-   AA          TAX
11E4-   AA          TAX
11E5-   AA          TAX
11E6-   AA          TAX
11E7-   AA          TAX
11E8-   AA          TAX
11E9-   AA          TAX
11EA-   AA          TAX
11EB-   AA          TAX
11EC-   AA          TAX
11ED-   AA          TAX
11EE-   AA          TAX
11EF-   AA          TAX
11F0-   AA          TAX
11F1-   AA          TAX
11F2-   AA          TAX
11F3-   AA          TAX
11F4-   AA          TAX
11F5-   AA          TAX
11F6-   AA          TAX
11F7-   AA          TAX
11F8-   AA          TAX
11F9-   AA          TAX
11FA-   AA          TAX
11FB-   AA          TAX
11FC-   AA          TAX
11FD-   AA          TAX
11FE-   AA          TAX
11FF-   8D AA 8D    STA   $8DAA
1202-   C2          ???
1203-   CE C1 CD    DEC   $CDC1
1206-   C5 A0       CMP   $A0
1208-   C4 D3       CPY   $D3
120A-   A0 B2       LDY   #$B2
120C-   B0 8D       BCS   $119B
120E-   D4          ???
120F-   CE C1 CD    DEC   $CDC1
1212-   C5 A0       CMP   $A0
1214-   C4 D3       CPY   $D3
1216-   A0 B2       LDY   #$B2
1218-   B0 8D       BCS   $11A7
121A-   C2          ???
121B-   CC CF C3    CPY   $C3CF
121E-   A0 C4       LDY   #$C4
1220-   D3          ???
1221-   A0 B1       LDY   #$B1
1223-   B0 8D       BCS   $11B2
1225-   CC C9 CE    CPY   $CEC9
1228-   C5 A0       CMP   $A0
122A-   C4 D3       CPY   $D3
122C-   A0 B4       LDY   #$B4
122E-   B0 8D       BCS   $11BD
1230-   C8          INY
1231-   C5 C1       CMP   $C1
1233-   C4 A0       CPY   $A0
1235-   C1 D3       CMP   ($D3,X)
1237-   C3          ???
1238-   A0 A2       LDY   #$A2
123A-   D2 C5       CMP   ($C5)
123C-   CD 20 AA    CMP   $AA20
123F-   AA          TAX
1240-   20 D4 C8    JSR   $C8D4
1243-   C9 D3       CMP   #$D3
1245-   20 C6 C9    JSR   $C9C6
1248-   CC C5 D3    CPY   $D3C5
124B-   20 C2 CC    JSR   $CCC2
124E-   CF          ???
124F-   C1 C4       CMP   ($C4,X)
1251-   D3          ???
1252-   A2 AC       LDX   #$AC
1254-   B8          CLV
1255-   C4 8D       CPY   $8D
1257-   A0 C1       LDY   #$C1
1259-   D3          ???
125A-   C3          ???
125B-   A0 A2       LDY   #$A2
125D-   D2 C5       CMP   ($C5)
125F-   CD 20 AA    CMP   $AA20
1262-   AA          TAX
1263-   20 C1 20    JSR   $20C1
1266-   C2          ???
1267-   C9 CE       CMP   #$CE
1269-   C1 D2       CMP   ($D2,X)
126B-   D9 20 D0    CMP   $D020,Y
126E-   D2 CF       CMP   ($CF)
1270-   C7          ???
1271-   D2 C1       CMP   ($C1)
1273-   CD 20 C9    CMP   $C920
1276-   CE D4 CF    DEC   $CFD4
1279-   A2 AC       LDX   #$AC
127B-   B8          CLV
127C-   C4 8D       CPY   $8D
127E-   A0 C1       LDY   #$C1
1280-   D3          ???
1281-   C3          ???
1282-   A0 A2       LDY   #$A2
1284-   D2 C5       CMP   ($C5)
1286-   CD 20 AA    CMP   $AA20
1289-   AA          TAX
128A-   20 CD C5    JSR   $C5CD
128D-   CD CF D2    CMP   $D2CF
1290-   D9 20 D4    CMP   $D420,Y
1293-   C8          INY
1294-   C5 CE       CMP   $CE
1296-   20 C5 D8    JSR   $D8C5
1299-   C5 C3       CMP   $C3
129B-   D5 D4       CMP   $D4,X
129D-   C5 D3       CMP   $D3
129F-   20 C9 D4    JSR   $D4C9
12A2-   A2 AC       LDX   #$AC
12A4-   B8          CLV
12A5-   C4 8D       CPY   $8D
12A7-   A0 C1       LDY   #$C1
12A9-   D3          ???
12AA-   C3          ???
12AB-   A0 A2       LDY   #$A2
12AD-   D2 C5       CMP   ($C5)
12AF-   CD 20 AA    CMP   $AA20
12B2-   AA          TAX
12B3-   20 D6 C9    JSR   $C9D6
12B6-   C1 20       CMP   ($20,X)
12B8-   D4          ???
12B9-   C8          INY
12BA-   C5 20       CMP   $20
12BC-   CD CF CE    CMP   $CECF
12BF-   C9 D4       CMP   #$D4
12C1-   CF          ???
12C2-   D2 AE       CMP   ($AE)
12C4-   20 D4 C8    JSR   $C8D4
12C7-   C9 D3       CMP   #$D3
12C9-   20 C9 D3    JSR   $D3C9
12CC-   A2 AC       LDX   #$AC
12CE-   B8          CLV
12CF-   C4 8D       CPY   $8D
12D1-   A0 C1       LDY   #$C1
12D3-   D3          ???
12D4-   C3          ???
12D5-   A0 A2       LDY   #$A2
12D7-   D2 C5       CMP   ($C5)
12D9-   CD 20 AA    CMP   $AA20
12DC-   AA          TAX
12DD-   20 CE C5    JSR   $C5CE
12E0-   C3          ???
12E1-   C5 D3       CMP   $D3
12E3-   D3          ???
12E4-   C1 D2       CMP   ($D2,X)
12E6-   D9 20 C6    CMP   $C620,Y
12E9-   CF          ???
12EA-   D2 20       CMP   ($20)
12EC-   C3          ???
12ED-   C5 D2       CMP   $D2
12EF-   D4          ???
12F0-   C1 C9       CMP   ($C9,X)
12F2-   CE 20 A2    DEC   $A220
12F5-   AC B8 C4    LDY   $C4B8
12F8-   8D A0 C1    STA   $C1A0
12FB-   D3          ???
12FC-   C3          ???
12FD-   A0 A2       LDY   #$A2
12FF-   D2 C5       CMP   ($C5)
1301-   CD 20 AA    CMP   $AA20
1304-   AA          TAX
1305-   20 C5 D8    JSR   $D8C5
1308-   C5 C3       CMP   $C3
130A-   D5 D4       CMP   $D4,X
130C-   C1 C2       CMP   ($C2,X)
130E-   CC C5 D3    CPY   $D3C5
1311-   20 D4 C8    JSR   $C8D4
1314-   C1 D4       CMP   ($D4,X)
1316-   20 D5 D3    JSR   $D3D5
1319-   C5 20       CMP   $20
131B-   C1 D0       CMP   ($D0,X)
131D-   D0 CC       BNE   $12EB
131F-   C5 D3       CMP   $D3
1321-   CF          ???
1322-   C6 D4       DEC   $D4
1324-   A2 AC       LDX   #$AC
1326-   B8          CLV
1327-   C4 8D       CPY   $8D
1329-   A0 C1       LDY   #$C1
132B-   D3          ???
132C-   C3          ???
132D-   A0 A2       LDY   #$A2
132F-   D2 C5       CMP   ($C5)
1331-   CD 20 AA    CMP   $AA20
1334-   AA          TAX
1335-   20 D2 CF    JSR   $CFD2
1338-   D5 D4       CMP   $D4,X
133A-   C9 CE       CMP   #$CE
133C-   C5 D3       CMP   $D3
133E-   AE A2 AC    LDX   $ACA2
1341-   B8          CLV
1342-   C4 8D       CPY   $8D
1344-   A0 C1       LDY   #$C1
1346-   D3          ???
1347-   C3          ???
1348-   A0 A2       LDY   #$A2
134A-   D2 C5       CMP   ($C5)
134C-   CD 20 AA    CMP   $AA20
134F-   AA          TAX
1350-   A2 AC       LDX   #$AC
1352-   B8          CLV
1353-   C4 B0       CPY   $B0
1355-   B0 8D       BCS   $12E4
1357-   AA          TAX
1358-   8D AA AA    STA   $AAAA
135B-   AA          TAX
135C-   AA          TAX
135D-   AA          TAX
135E-   AA          TAX
135F-   AA          TAX
1360-   AA          TAX
1361-   AA          TAX
1362-   AA          TAX
1363-   AA          TAX
1364-   AA          TAX
1365-   AA          TAX
1366-   AA          TAX
1367-   AA          TAX
1368-   AA          TAX
1369-   AA          TAX
136A-   AA          TAX
136B-   AA          TAX
136C-   AA          TAX
136D-   AA          TAX
136E-   AA          TAX
136F-   AA          TAX
1370-   AA          TAX
1371-   AA          TAX
1372-   AA          TAX
1373-   AA          TAX
1374-   AA          TAX
1375-   AA          TAX
1376-   AA          TAX
1377-   AA          TAX
1378-   AA          TAX
1379-   8D AA 20    STA   $20AA
137C-   20 20 20    JSR   $2020
137F-   20 20 20    JSR   $2020
1382-   20 20 20    JSR   $2020
1385-   20 20 20    JSR   $2020
1388-   20 20 20    JSR   $2020
138B-   20 20 20    JSR   $2020
138E-   20 20 20    JSR   $2020
1391-   20 20 20    JSR   $2020
1394-   20 20 20    JSR   $2020
1397-   20 20 AA    JSR   $AA20
139A-   8D AA 20    STA   $20AA
139D-   20 CC CF    JSR   $CFCC
13A0-   D7          ???
13A1-   AD CC C5    LDA   $C5CC
13A4-   D6 C5       DEC   $C5,X
13A6-   CC 20 D2    CPY   $D220
13A9-   CF          ???
13AA-   D5 D4       CMP   $D4,X
13AC-   C9 CE       CMP   #$CE
13AE-   C5 D3       CMP   $D3
13B0-   20 20 20    JSR   $2020
13B3-   20 20 20    JSR   $2020
13B6-   20 20 20    JSR   $2020
13B9-   20 AA 8D    JSR   $8DAA
13BC-   AA          TAX
13BD-   20 20 20    JSR   $2020
13C0-   20 20 20    JSR   $2020
13C3-   20 20 20    JSR   $2020
13C6-   20 20 20    JSR   $2020
13C9-   20 20 20    JSR   $2020
13CC-   20 20 20    JSR   $2020
13CF-   20 20 20    JSR   $2020
13D2-   20 20 20    JSR   $2020
13D5-   20 20 20    JSR   $2020
13D8-   20 20 20    JSR   $2020
13DB-   AA          TAX
13DC-   8D AA AA    STA   $AAAA
13DF-   AA          TAX
13E0-   AA          TAX
13E1-   AA          TAX
13E2-   AA          TAX
13E3-   AA          TAX
13E4-   AA          TAX
13E5-   AA          TAX
13E6-   AA          TAX
13E7-   AA          TAX
13E8-   AA          TAX
13E9-   AA          TAX
13EA-   AA          TAX
13EB-   AA          TAX
13EC-   AA          TAX
13ED-   AA          TAX
13EE-   AA          TAX
13EF-   AA          TAX
13F0-   AA          TAX
13F1-   AA          TAX
13F2-   AA          TAX
13F3-   AA          TAX
13F4-   AA          TAX
13F5-   AA          TAX
13F6-   AA          TAX
13F7-   AA          TAX
13F8-   AA          TAX
13F9-   AA          TAX
13FA-   AA          TAX
13FB-   AA          TAX
13FC-   AA          TAX
13FD-   8D AA 8D    STA   $8DAA
1400-   A0 D0       LDY   #$D0
1402-   D5 D4       CMP   $D4,X
1404-   A0 CD       LDY   #$CD
1406-   C9 CE       CMP   #$CE
1408-   AE CC C9    LDX   $C9CC
140B-   C2          ???
140C-   AE D2 C5    LDX   $C5D2
140F-   D1 D5       CMP   ($D5),Y
1411-   C9 D2       CMP   #$D2
1413-   C5 C4       CMP   $C4
1415-   8D AA 8D    STA   $8DAA
1418-   AA          TAX
1419-   AA          TAX
141A-   20 C9 CE    JSR   $CEC9
141D-   C4 C9       CPY   $C9
141F-   D6 C9       DEC   $C9,X
1421-   C4 D5       CPY   $D5
1423-   C1 CC       CMP   ($CC,X)
1425-   20 D3 D5    JSR   $D5D3
1428-   C2          ???
1429-   D2 CF       CMP   ($CF)
142B-   D5 D4       CMP   $D4,X
142D-   C9 CE       CMP   #$CE
142F-   C5 D3       CMP   $D3
1431-   8D AA 8D    STA   $8DAA
1434-   AA          TAX
1435-   AA          TAX
1436-   AA          TAX
1437-   20 C6 C9    JSR   $C9C6
143A-   CC C5 C9    CPY   $C9C5
143D-   CF          ???
143E-   8D AA 8D    STA   $8DAA
1441-   A0 D0       LDY   #$D0
1443-   D5 D4       CMP   $D4,X
1445-   A0 CD       LDY   #$CD
1447-   C9 CE       CMP   #$CE
1449-   AE D3 D5    LDX   $D5D3
144C-   C2          ???
144D-   AE C6 D0    LDX   $D0C6
1450-   D2 C9       CMP   ($C9)
1452-   CE D4 8D    DEC   $8DD4
1455-   A0 D0       LDY   #$D0
1457-   D5 D4       CMP   $D4,X
1459-   A0 CD       LDY   #$CD
145B-   C9 CE       CMP   #$CE
145D-   AE D3 D5    LDX   $D5D3
1460-   C2          ???
1461-   AE C4 CF    LDX   $CFC4
1464-   D3          ???
1465-   C3          ???
1466-   CD C4 8D    CMP   $8DC4
1469-   A0 D0       LDY   #$D0
146B-   D5 D4       CMP   $D4,X
146D-   A0 CD       LDY   #$CD
146F-   C9 CE       CMP   #$CE
1471-   AE D3 D5    LDX   $D5D3
1474-   C2          ???
1475-   AE C6 D0    LDX   $D0C6
1478-   D3          ???
1479-   D4          ???
147A-   D2 8D       CMP   ($8D)
147C-   AA          TAX
147D-   8D AA AA    STA   $AAAA
1480-   AA          TAX
1481-   20 D3 D4    JSR   $D4D3
1484-   C4 C9       CPY   $C9
1486-   CF          ???
1487-   8D AA 8D    STA   $8DAA
148A-   A0 D0       LDY   #$D0
148C-   D5 D4       CMP   $D4,X
148E-   A0 CD       LDY   #$CD
1490-   C9 CE       CMP   #$CE
1492-   AE D3 D5    LDX   $D5D3
1495-   C2          ???
1496-   AE C4 D0    LDX   $D0C4
1499-   D2 C9       CMP   ($C9)
149B-   CE D4 8D    DEC   $8DD4
149E-   A0 D0       LDY   #$D0
14A0-   D5 D4       CMP   $D4,X
14A2-   A0 CD       LDY   #$CD
14A4-   C9 CE       CMP   #$CE
14A6-   AE D3 D5    LDX   $D5D3
14A9-   C2          ???
14AA-   AE D8 D0    LDX   $D0D8
14AD-   D2 C9       CMP   ($C9)
14AF-   CE D4 8D    DEC   $8DD4
14B2-   A0 D0       LDY   #$D0
14B4-   D5 D4       CMP   $D4,X
14B6-   A0 CD       LDY   #$CD
14B8-   C9 CE       CMP   #$CE
14BA-   AE D3 D5    LDX   $D5D3
14BD-   C2          ???
14BE-   AE D3 C9    LDX   $C9D3
14C1-   CE D0 D5    DEC   $D5D0
14C4-   D4          ???
14C5-   8D AA 8D    STA   $8DAA
14C8-   AA          TAX
14C9-   AA          TAX
14CA-   AA          TAX
14CB-   20 D3 D4    JSR   $D4D3
14CE-   D2 C9       CMP   ($C9)
14D0-   CE C7 D3    DEC   $D3C7
14D3-   8D AA 8D    STA   $8DAA
14D6-   A0 D0       LDY   #$D0
14D8-   D5 D4       CMP   $D4,X
14DA-   A0 CD       LDY   #$CD
14DC-   C9 CE       CMP   #$CE
14DE-   AE D3 D5    LDX   $D5D3
14E1-   C2          ???
14E2-   AE D3 D4    LDX   $D4D3
14E5-   D2 C3       CMP   ($C3)
14E7-   C1 D4       CMP   ($D4,X)
14E9-   8D A0 D0    STA   $D0A0
14EC-   D5 D4       CMP   $D4,X
14EE-   A0 CD       LDY   #$CD
14F0-   C9 CE       CMP   #$CE
14F2-   AE D3 D5    LDX   $D5D3
14F5-   C2          ???
14F6-   AE D0 D2    LDX   $D2D0
14F9-   CE D3 D4    DEC   $D4D3
14FC-   D2 8D       CMP   ($8D)
14FE-   AA          TAX
14FF-   8D 00 00    STA   $0000
