0901-   AA          TAX
0902-   AA          TAX
0903-   AA          TAX
0904-   AA          TAX
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   8D AA 20    STA   $20AA
0924-   20 20 20    JSR   $2020
0927-   20 20 20    JSR   $2020
092A-   20 20 20    JSR   $2020
092D-   20 20 20    JSR   $2020
0930-   20 20 20    JSR   $2020
0933-   20 20 20    JSR   $2020
0936-   20 20 20    JSR   $2020
0939-   20 20 20    JSR   $2020
093C-   20 20 20    JSR   $2020
093F-   20 20 AA    JSR   $AA20
0942-   8D AA 20    STA   $20AA
0945-   C1 D3       CMP   ($D3,X)
0947-   D3          ???
0948-   C5 CD       CMP   $CD
094A-   C2          ???
094B-   CC D9 20    CPY   $20D9
094E-   CC C9 D3    CPY   $D3C9
0951-   D4          ???
0952-   C9 CE       CMP   #$CE
0954-   C7          ???
0955-   20 CD C9    JSR   $C9CD
0958-   CE C9 C6    DEC   $C6C9
095B-   C9 C5       CMP   #$C5
095D-   D2 20       CMP   ($20)
095F-   20 20 20    JSR   $2020
0962-   AA          TAX
0963-   8D AA 20    STA   $20AA
0966-   20 20 20    JSR   $2020
0969-   20 20 20    JSR   $2020
096C-   20 20 20    JSR   $2020
096F-   20 20 20    JSR   $2020
0972-   20 20 20    JSR   $2020
0975-   20 20 20    JSR   $2020
0978-   20 20 20    JSR   $2020
097B-   20 20 20    JSR   $2020
097E-   20 20 20    JSR   $2020
0981-   20 20 AA    JSR   $AA20
0984-   8D AA 20    STA   $20AA
0987-   C1 20       CMP   ($20,X)
0989-   D0 D2       BNE   $095D
098B-   CF          ???
098C-   C7          ???
098D-   D2 C1       CMP   ($C1)
098F-   CD 20 D4    CMP   $D420
0992-   C8          INY
0993-   C1 D4       CMP   ($D4,X)
0995-   20 D2 C5    JSR   $C5D2
0998-   CD CF D6    CMP   $D6CF
099B-   C5 D3       CMP   $D3
099D-   20 20 20    JSR   $2020
09A0-   20 20 20    JSR   $2020
09A3-   20 AA 8D    JSR   $8DAA
09A6-   AA          TAX
09A7-   20 C3 CF    JSR   $CFC3
09AA-   CD CD C5    CMP   $C5CD
09AD-   CE D4 D3    DEC   $D3D4
09B0-   20 C6 D2    JSR   $D2C6
09B3-   CF          ???
09B4-   CD 20 C1    CMP   $C120
09B7-   D3          ???
09B8-   D3          ???
09B9-   C5 CD       CMP   $CD
09BB-   C2          ???
09BC-   CC D9 20    CPY   $20D9
09BF-   C3          ???
09C0-   CF          ???
09C1-   C4 C5       CPY   $C5
09C3-   AE 20 AA    LDX   $AA20
09C6-   8D AA 20    STA   $20AA
09C9-   20 20 20    JSR   $2020
09CC-   20 20 20    JSR   $2020
09CF-   20 20 20    JSR   $2020
09D2-   20 20 20    JSR   $2020
09D5-   20 20 20    JSR   $2020
09D8-   20 20 20    JSR   $2020
09DB-   20 20 20    JSR   $2020
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 AA    JSR   $AA20
09E7-   8D AA AA    STA   $AAAA
09EA-   AA          TAX
09EB-   AA          TAX
09EC-   AA          TAX
09ED-   AA          TAX
09EE-   AA          TAX
09EF-   AA          TAX
09F0-   AA          TAX
09F1-   AA          TAX
09F2-   AA          TAX
09F3-   AA          TAX
09F4-   AA          TAX
09F5-   AA          TAX
09F6-   AA          TAX
09F7-   AA          TAX
09F8-   AA          TAX
09F9-   AA          TAX
09FA-   AA          TAX
09FB-   AA          TAX
09FC-   AA          TAX
09FD-   AA          TAX
09FE-   AA          TAX
09FF-   AA          TAX
0A00-   AA          TAX
0A01-   AA          TAX
0A02-   AA          TAX
0A03-   AA          TAX
0A04-   AA          TAX
0A05-   AA          TAX
0A06-   AA          TAX
0A07-   AA          TAX
0A08-   8D AA 8D    STA   $8DAA
0A0B-   AA          TAX
0A0C-   AA          TAX
0A0D-   20 C1 D3    JSR   $D3C1
0A10-   D3          ???
0A11-   C5 CD       CMP   $CD
0A13-   C2          ???
0A14-   CC C5 D2    CPY   $D2C5
0A17-   20 C4 C9    JSR   $C9C4
0A1A-   D2 C5       CMP   ($C5)
0A1C-   C3          ???
0A1D-   D4          ???
0A1E-   C9 D6       CMP   #$D6
0A20-   C5 D3       CMP   $D3
0A22-   8D AA 8D    STA   $8DAA
0A25-   A0 C3       LDY   #$C3
0A27-   D9 C3 A0    CMP   $A0C3,Y
0A2A-   C1 D6       CMP   ($D6,X)
0A2C-   C5 8D       CMP   $8D
0A2E-   A0 C5       LDY   #$C5
0A30-   D8          CLD
0A31-   D0 A0       BNE   $09D3
0A33-   CF          ???
0A34-   C6 C6       DEC   $C6
0A36-   8D A0 C4    STA   $C4A0
0A39-   D3          ???
0A3A-   CB          ???
0A3B-   A0 CD       LDY   #$CD
0A3D-   C9 CE       CMP   #$CE
0A3F-   C9 C6       CMP   #$C6
0A41-   D9 8D A0    CMP   $A08D,Y
0A44-   D4          ???
0A45-   D2 A0       CMP   ($A0)
0A47-   CF          ???
0A48-   CE 8D A0    DEC   $A08D
0A4B-   CF          ???
0A4C-   C2          ???
0A4D-   CA          DEX
0A4E-   A0 A4       LDY   #$A4
0A50-   C2          ???
0A51-   C6 C5       DEC   $C5
0A53-   B0 8D       BCS   $09E2
0A55-   A0 CF       LDY   #$CF
0A57-   D2 C7       CMP   ($C7)
0A59-   A0 A4       LDY   #$A4
0A5B-   B7          ???
0A5C-   B0 B0       BCS   $0A0E
0A5E-   B0 8D       BCS   $09ED
0A60-   AA          TAX
0A61-   8D AA AA    STA   $AAAA
0A64-   AA          TAX
0A65-   AA          TAX
0A66-   AA          TAX
0A67-   AA          TAX
0A68-   AA          TAX
0A69-   AA          TAX
0A6A-   AA          TAX
0A6B-   AA          TAX
0A6C-   AA          TAX
0A6D-   AA          TAX
0A6E-   AA          TAX
0A6F-   AA          TAX
0A70-   AA          TAX
0A71-   AA          TAX
0A72-   AA          TAX
0A73-   AA          TAX
0A74-   AA          TAX
0A75-   AA          TAX
0A76-   AA          TAX
0A77-   AA          TAX
0A78-   AA          TAX
0A79-   AA          TAX
0A7A-   AA          TAX
0A7B-   AA          TAX
0A7C-   AA          TAX
0A7D-   AA          TAX
0A7E-   AA          TAX
0A7F-   AA          TAX
0A80-   AA          TAX
0A81-   AA          TAX
0A82-   8D AA 20    STA   $20AA
0A85-   20 20 20    JSR   $2020
0A88-   20 20 20    JSR   $2020
0A8B-   20 20 20    JSR   $2020
0A8E-   20 20 20    JSR   $2020
0A91-   20 20 20    JSR   $2020
0A94-   20 20 20    JSR   $2020
0A97-   20 20 20    JSR   $2020
0A9A-   20 20 20    JSR   $2020
0A9D-   20 20 20    JSR   $2020
0AA0-   20 20 AA    JSR   $AA20
0AA3-   8D AA 20    STA   $20AA
0AA6-   C8          INY
0AA7-   C5 C1       CMP   $C1
0AA9-   C4 C5       CPY   $C5
0AAB-   D2 AC       CMP   ($AC)
0AAD-   20 C8 CF    JSR   $CFC8
0AB0-   CF          ???
0AB1-   CB          ???
0AB2-   D3          ???
0AB3-   20 C1 CE    JSR   $CEC1
0AB6-   C4 20       CPY   $20
0AB8-   CD C1 C3    CMP   $C3C1
0ABB-   D2 CF       CMP   ($CF)
0ABD-   D3          ???
0ABE-   20 20 20    JSR   $2020
0AC1-   20 20 AA    JSR   $AA20
0AC4-   8D AA 20    STA   $20AA
0AC7-   20 20 20    JSR   $2020
0ACA-   20 20 20    JSR   $2020
0ACD-   20 20 20    JSR   $2020
0AD0-   20 20 20    JSR   $2020
0AD3-   20 20 20    JSR   $2020
0AD6-   20 20 20    JSR   $2020
0AD9-   20 20 20    JSR   $2020
0ADC-   20 20 20    JSR   $2020
0ADF-   20 20 20    JSR   $2020
0AE2-   20 20 AA    JSR   $AA20
0AE5-   8D AA AA    STA   $AAAA
0AE8-   AA          TAX
0AE9-   AA          TAX
0AEA-   AA          TAX
0AEB-   AA          TAX
0AEC-   AA          TAX
0AED-   AA          TAX
0AEE-   AA          TAX
0AEF-   AA          TAX
0AF0-   AA          TAX
0AF1-   AA          TAX
0AF2-   AA          TAX
0AF3-   AA          TAX
0AF4-   AA          TAX
0AF5-   AA          TAX
0AF6-   AA          TAX
0AF7-   AA          TAX
0AF8-   AA          TAX
0AF9-   AA          TAX
0AFA-   AA          TAX
0AFB-   AA          TAX
0AFC-   AA          TAX
0AFD-   AA          TAX
0AFE-   AA          TAX
0AFF-   AA          TAX
0B00-   AA          TAX
0B01-   AA          TAX
0B02-   AA          TAX
0B03-   AA          TAX
0B04-   AA          TAX
0B05-   AA          TAX
0B06-   8D AA 8D    STA   $8DAA
0B09-   A0 D0       LDY   #$D0
0B0B-   D5 D4       CMP   $D4,X
0B0D-   A0 CD       LDY   #$CD
0B0F-   C9 CE       CMP   #$CE
0B11-   AE D6 C1    LDX   $C1D6
0B14-   D2 D3       CMP   ($D3)
0B16-   AE D2 C5    LDX   $C5D2
0B19-   D1 D5       CMP   ($D5),Y
0B1B-   C9 D2       CMP   #$D2
0B1D-   C5 C4       CMP   $C4
0B1F-   8D A0 D5    STA   $D5A0
0B22-   D3          ???
0B23-   C5 A0       CMP   $A0
0B25-   CD C9 CE    CMP   $CEC9
0B28-   AE CD C1    LDX   $C1CD
0B2B-   C3          ???
0B2C-   AE D2 C5    LDX   $C5D2
0B2F-   D1 D5       CMP   ($D5),Y
0B31-   C9 D2       CMP   #$D2
0B33-   C5 C4       CMP   $C4
0B35-   8D A0 D0    STA   $D0A0
0B38-   D5 D4       CMP   $D4,X
0B3A-   A0 CD       LDY   #$CD
0B3C-   C9 CE       CMP   #$CE
0B3E-   AE C8 CF    LDX   $CFC8
0B41-   CF          ???
0B42-   CB          ???
0B43-   D3          ???
0B44-   AE D2 C5    LDX   $C5D2
0B47-   D1 D5       CMP   ($D5),Y
0B49-   C9 D2       CMP   #$D2
0B4B-   C5 C4       CMP   $C4
0B4D-   8D A0 D5    STA   $D5A0
0B50-   D3          ???
0B51-   C5 A0       CMP   $A0
0B53-   CD C9 CE    CMP   $CEC9
0B56-   AE CD C1    LDX   $C1CD
0B59-   C3          ???
0B5A-   AE D3 D4    LDX   $D4D3
0B5D-   C4 C9       CPY   $C9
0B5F-   CF          ???
0B60-   8D A0 D0    STA   $D0A0
0B63-   D5 D4       CMP   $D4,X
0B65-   A0 CD       LDY   #$CD
0B67-   C9 CE       CMP   #$CE
0B69-   AE C8 CF    LDX   $CFC8
0B6C-   CF          ???
0B6D-   CB          ???
0B6E-   D3          ???
0B6F-   AE D3 D4    LDX   $D4D3
0B72-   C4 C9       CPY   $C9
0B74-   CF          ???
0B75-   8D A0 D5    STA   $D5A0
0B78-   D3          ???
0B79-   C5 A0       CMP   $A0
0B7B-   CD C9 CE    CMP   $CEC9
0B7E-   AE CD C1    LDX   $C1CD
0B81-   C3          ???
0B82-   AE C6 C9    LDX   $C9C6
0B85-   CC C5 C9    CPY   $C9C5
0B88-   CF          ???
0B89-   8D A0 D0    STA   $D0A0
0B8C-   D5 D4       CMP   $D4,X
0B8E-   A0 CD       LDY   #$CD
0B90-   C9 CE       CMP   #$CE
0B92-   AE C8 CF    LDX   $CFC8
0B95-   CF          ???
0B96-   CB          ???
0B97-   D3          ???
0B98-   AE C6 C9    LDX   $C9C6
0B9B-   CC C5 C9    CPY   $C9C5
0B9E-   CF          ???
0B9F-   8D A0 D5    STA   $D5A0
0BA2-   D3          ???
0BA3-   C5 A0       CMP   $A0
0BA5-   CD C9 CE    CMP   $CEC9
0BA8-   AE CD C1    LDX   $C1CD
0BAB-   C3          ???
0BAC-   AE D3 D4    LDX   $D4D3
0BAF-   D2 C9       CMP   ($C9)
0BB1-   CE C7 D3    DEC   $D3C7
0BB4-   8D A0 D0    STA   $D0A0
0BB7-   D5 D4       CMP   $D4,X
0BB9-   A0 CD       LDY   #$CD
0BBB-   C9 CE       CMP   #$CE
0BBD-   AE C8 CF    LDX   $CFC8
0BC0-   CF          ???
0BC1-   CB          ???
0BC2-   D3          ???
0BC3-   AE D3 D4    LDX   $D4D3
0BC6-   D2 C9       CMP   ($C9)
0BC8-   CE C7 D3    DEC   $D3C7
0BCB-   8D AA 8D    STA   $8DAA
0BCE-   AA          TAX
0BCF-   AA          TAX
0BD0-   AA          TAX
0BD1-   AA          TAX
0BD2-   AA          TAX
0BD3-   AA          TAX
0BD4-   AA          TAX
0BD5-   AA          TAX
0BD6-   AA          TAX
0BD7-   AA          TAX
0BD8-   AA          TAX
0BD9-   AA          TAX
0BDA-   AA          TAX
0BDB-   AA          TAX
0BDC-   AA          TAX
0BDD-   AA          TAX
0BDE-   AA          TAX
0BDF-   AA          TAX
0BE0-   AA          TAX
0BE1-   AA          TAX
0BE2-   AA          TAX
0BE3-   AA          TAX
0BE4-   AA          TAX
0BE5-   AA          TAX
0BE6-   AA          TAX
0BE7-   AA          TAX
0BE8-   AA          TAX
0BE9-   AA          TAX
0BEA-   AA          TAX
0BEB-   AA          TAX
0BEC-   AA          TAX
0BED-   AA          TAX
0BEE-   8D AA 20    STA   $20AA
0BF1-   20 20 20    JSR   $2020
0BF4-   20 20 20    JSR   $2020
0BF7-   20 20 20    JSR   $2020
0BFA-   20 20 20    JSR   $2020
0BFD-   20 20 20    JSR   $2020
0C00-   20 20 20    JSR   $2020
0C03-   20 20 20    JSR   $2020
0C06-   20 20 20    JSR   $2020
0C09-   20 20 20    JSR   $2020
0C0C-   20 20 AA    JSR   $AA20
0C0F-   8D AA 20    STA   $20AA
0C12-   CD C1 C9    CMP   $C9C1
0C15-   CE 20 D0    DEC   $D020
0C18-   D2 CF       CMP   ($CF)
0C1A-   C7          ???
0C1B-   D2 C1       CMP   ($C1)
0C1D-   CD 20 CC    CMP   $CC20
0C20-   CF          ???
0C21-   CF          ???
0C22-   D0 20       BNE   $0C44
0C24-   20 20 20    JSR   $2020
0C27-   20 20 20    JSR   $2020
0C2A-   20 20 20    JSR   $2020
0C2D-   20 20 AA    JSR   $AA20
0C30-   8D AA 20    STA   $20AA
0C33-   20 20 20    JSR   $2020
0C36-   20 20 20    JSR   $2020
0C39-   20 20 20    JSR   $2020
0C3C-   20 20 20    JSR   $2020
0C3F-   20 20 20    JSR   $2020
0C42-   20 20 20    JSR   $2020
0C45-   20 20 20    JSR   $2020
0C48-   20 20 20    JSR   $2020
0C4B-   20 20 20    JSR   $2020
0C4E-   20 20 AA    JSR   $AA20
0C51-   8D AA AA    STA   $AAAA
0C54-   AA          TAX
0C55-   AA          TAX
0C56-   AA          TAX
0C57-   AA          TAX
0C58-   AA          TAX
0C59-   AA          TAX
0C5A-   AA          TAX
0C5B-   AA          TAX
0C5C-   AA          TAX
0C5D-   AA          TAX
0C5E-   AA          TAX
0C5F-   AA          TAX
0C60-   AA          TAX
0C61-   AA          TAX
0C62-   AA          TAX
0C63-   AA          TAX
0C64-   AA          TAX
0C65-   AA          TAX
0C66-   AA          TAX
0C67-   AA          TAX
0C68-   AA          TAX
0C69-   AA          TAX
0C6A-   AA          TAX
0C6B-   AA          TAX
0C6C-   AA          TAX
0C6D-   AA          TAX
0C6E-   AA          TAX
0C6F-   AA          TAX
0C70-   AA          TAX
0C71-   AA          TAX
0C72-   8D AA 8D    STA   $8DAA
0C75-   C2          ???
0C76-   C5 C7       CMP   $C7
0C78-   C9 CE       CMP   #$CE
0C7A-   8D AA 8D    STA   $8DAA
0C7D-   A0 CA       LDY   #$CA
0C7F-   D3          ???
0C80-   D2 A0       CMP   ($A0)
0C82-   C9 CE       CMP   #$CE
0C84-   C9 D4       CMP   #$D4
0C86-   8D A0 CA    STA   $CAA0
0C89-   D3          ???
0C8A-   D2 A0       CMP   ($A0)
0C8C-   C7          ???
0C8D-   C5 D4       CMP   $D4
0C8F-   CE C1 CD    DEC   $CDC1
0C92-   C5 D3       CMP   $D3
0C94-   8D A0 CA    STA   $CAA0
0C97-   D3          ???
0C98-   D2 A0       CMP   ($A0)
0C9A-   C4 C5       CPY   $C5
0C9C-   CC CD C9    CPY   $C9CD
0C9F-   CE 8D A0    DEC   $A08D
0CA2-   CA          DEX
0CA3-   CD D0 A0    CMP   $A0D0
0CA6-   C6 C3       DEC   $C3
0CA8-   CF          ???
0CA9-   D0 D9       BNE   $0C84
0CAB-   8D AA 8D    STA   $8DAA
0CAE-   A0 CA       LDY   #$CA
0CB0-   CD D0 A0    CMP   $A0D0
0CB3-   D2 C5       CMP   ($C5)
0CB5-   C5 CE       CMP   $CE
0CB7-   D4          ???
0CB8-   D2 D9       CMP   ($D9)
0CBA-   8D AA 8D    STA   $8DAA
0CBD-   AA          TAX
0CBE-   AA          TAX
0CBF-   AA          TAX
0CC0-   AA          TAX
0CC1-   AA          TAX
0CC2-   AA          TAX
0CC3-   AA          TAX
0CC4-   AA          TAX
0CC5-   AA          TAX
0CC6-   AA          TAX
0CC7-   AA          TAX
0CC8-   AA          TAX
0CC9-   AA          TAX
0CCA-   AA          TAX
0CCB-   AA          TAX
0CCC-   AA          TAX
0CCD-   AA          TAX
0CCE-   AA          TAX
0CCF-   AA          TAX
0CD0-   AA          TAX
0CD1-   AA          TAX
0CD2-   AA          TAX
0CD3-   AA          TAX
0CD4-   AA          TAX
0CD5-   AA          TAX
0CD6-   AA          TAX
0CD7-   AA          TAX
0CD8-   AA          TAX
0CD9-   AA          TAX
0CDA-   AA          TAX
0CDB-   AA          TAX
0CDC-   AA          TAX
0CDD-   8D AA 20    STA   $20AA
0CE0-   20 20 20    JSR   $2020
0CE3-   20 20 20    JSR   $2020
0CE6-   20 20 20    JSR   $2020
0CE9-   20 20 20    JSR   $2020
0CEC-   20 20 20    JSR   $2020
0CEF-   20 20 20    JSR   $2020
0CF2-   20 20 20    JSR   $2020
0CF5-   20 20 20    JSR   $2020
0CF8-   20 20 20    JSR   $2020
0CFB-   20 20 AA    JSR   $AA20
0CFE-   8D AA 20    STA   $20AA
0D01-   C9 CE       CMP   #$CE
0D03-   C9 D4       CMP   #$D4
0D05-   20 20 20    JSR   $2020
0D08-   20 20 20    JSR   $2020
0D0B-   20 20 20    JSR   $2020
0D0E-   20 20 20    JSR   $2020
0D11-   20 20 20    JSR   $2020
0D14-   20 20 20    JSR   $2020
0D17-   20 20 20    JSR   $2020
0D1A-   20 20 20    JSR   $2020
0D1D-   20 AA 8D    JSR   $8DAA
0D20-   AA          TAX
0D21-   20 20 20    JSR   $2020
0D24-   20 20 20    JSR   $2020
0D27-   20 20 20    JSR   $2020
0D2A-   20 20 20    JSR   $2020
0D2D-   20 20 20    JSR   $2020
0D30-   20 20 20    JSR   $2020
0D33-   20 20 20    JSR   $2020
0D36-   20 20 20    JSR   $2020
0D39-   20 20 20    JSR   $2020
0D3C-   20 20 20    JSR   $2020
0D3F-   AA          TAX
0D40-   8D AA AA    STA   $AAAA
0D43-   AA          TAX
0D44-   AA          TAX
0D45-   AA          TAX
0D46-   AA          TAX
0D47-   AA          TAX
0D48-   AA          TAX
0D49-   AA          TAX
0D4A-   AA          TAX
0D4B-   AA          TAX
0D4C-   AA          TAX
0D4D-   AA          TAX
0D4E-   AA          TAX
0D4F-   AA          TAX
0D50-   AA          TAX
0D51-   AA          TAX
0D52-   AA          TAX
0D53-   AA          TAX
0D54-   AA          TAX
0D55-   AA          TAX
0D56-   AA          TAX
0D57-   AA          TAX
0D58-   AA          TAX
0D59-   AA          TAX
0D5A-   AA          TAX
0D5B-   AA          TAX
0D5C-   AA          TAX
0D5D-   AA          TAX
0D5E-   AA          TAX
0D5F-   AA          TAX
0D60-   AA          TAX
0D61-   8D AA 8D    STA   $8DAA
0D64-   C9 CE       CMP   #$CE
0D66-   C9 D4       CMP   #$D4
0D68-   8D AA 8D    STA   $8DAA
0D6B-   AA          TAX
0D6C-   AA          TAX
0D6D-   20 D2 C5    JSR   $C5D2
0D70-   D3          ???
0D71-   C5 D4       CMP   $D4
0D73-   20 C5 D2    JSR   $D2C5
0D76-   D2 CF       CMP   ($CF)
0D78-   D2 20       CMP   ($20)
0D7A-   C8          INY
0D7B-   C1 CE       CMP   ($CE,X)
0D7D-   C4 CC       CPY   $CC
0D7F-   C9 CE       CMP   #$CE
0D81-   C7          ???
0D82-   8D AA 8D    STA   $8DAA
0D85-   A0 C1       LDY   #$C1
0D87-   CD CF C4    CMP   $C4CF
0D8A-   C5 8D       CMP   $8D
0D8C-   A0 CC       LDY   #$CC
0D8E-   C4 C1       CPY   $C1
0D90-   A0 A3       LDY   #$A3
0D92-   A4 B0       LDY   $B0
0D94-   B0 8D       BCS   $0D23
0D96-   A0 D3       LDY   #$D3
0D98-   D4          ???
0D99-   C1 A0       CMP   ($A0,X)
0D9B-   A4 C4       LDY   $C4
0D9D-   B8          CLV
0D9E-   8D AA 8D    STA   $8DAA
0DA1-   A0 CC       LDY   #$CC
0DA3-   C4 C1       CPY   $C1
0DA5-   A0 A3       LDY   #$A3
0DA7-   B2 B1       LDA   ($B1)
0DA9-   A0 BB       LDY   #$BB
0DAB-   20 D3 C5    JSR   $C5D3
0DAE-   CE C4 20    DEC   $20C4
0DB1-   DE D5 20    DEC   $20D5,X
0DB4-   D4          ???
0DB5-   CF          ???
0DB6-   20 C3 CF    JSR   $CFC3
0DB9-   D5 D4       CMP   $D4,X
0DBB-   20 D4 CF    JSR   $CFD4
0DBE-   8D A0 CA    STA   $CAA0
0DC1-   D3          ???
0DC2-   D2 A0       CMP   ($A0)
0DC4-   C3          ???
0DC5-   CF          ???
0DC6-   D5 D4       CMP   $D4,X
0DC8-   A0 BB       LDY   #$BB
0DCA-   20 C5 CE    JSR   $CEC5
0DCD-   D3          ???
0DCE-   D5 D2       CMP   $D2,X
0DD0-   C5 20       CMP   $20
0DD2-   B4 B0       LDY   $B0,X
0DD4-   C3          ???
0DD5-   CF          ???
0DD6-   CC 20 CD    CPY   $CD20
0DD9-   CF          ???
0DDA-   C4 C5       CPY   $C5
0DDC-   8D A0 CC    STA   $CCA0
0DDF-   C4 C1       CPY   $C1
0DE1-   A0 A3       LDY   #$A3
0DE3-   B0 B0       BCS   $0D95
0DE5-   8D A0 D3    STA   $D3A0
0DE8-   D4          ???
0DE9-   C1 A0       CMP   ($A0,X)
0DEB-   C1 C4       CMP   ($C4,X)
0DED-   C4 D4       CPY   $D4
0DEF-   8D A0 D3    STA   $D3A0
0DF2-   D4          ???
0DF3-   C1 A0       CMP   ($A0,X)
0DF5-   D7          ???
0DF6-   D2 C9       CMP   ($C9)
0DF8-   D4          ???
0DF9-   C5 CF       CMP   $CF
0DFB-   C6 C6       DEC   $C6
0DFD-   8D A0 D2    STA   $D2A0
0E00-   D4          ???
0E01-   D3          ???
0E02-   8D AA 8D    STA   $8DAA
0E05-   AA          TAX
0E06-   AA          TAX
0E07-   AA          TAX
0E08-   AA          TAX
0E09-   AA          TAX
0E0A-   AA          TAX
0E0B-   AA          TAX
0E0C-   AA          TAX
0E0D-   AA          TAX
0E0E-   AA          TAX
0E0F-   AA          TAX
0E10-   AA          TAX
0E11-   AA          TAX
0E12-   AA          TAX
0E13-   AA          TAX
0E14-   AA          TAX
0E15-   AA          TAX
0E16-   AA          TAX
0E17-   AA          TAX
0E18-   AA          TAX
0E19-   AA          TAX
0E1A-   AA          TAX
0E1B-   AA          TAX
0E1C-   AA          TAX
0E1D-   AA          TAX
0E1E-   AA          TAX
0E1F-   AA          TAX
0E20-   AA          TAX
0E21-   AA          TAX
0E22-   AA          TAX
0E23-   AA          TAX
0E24-   AA          TAX
0E25-   8D AA 20    STA   $20AA
0E28-   20 20 20    JSR   $2020
0E2B-   20 20 20    JSR   $2020
0E2E-   20 20 20    JSR   $2020
0E31-   20 20 20    JSR   $2020
0E34-   20 20 20    JSR   $2020
0E37-   20 20 20    JSR   $2020
0E3A-   20 20 20    JSR   $2020
0E3D-   20 20 20    JSR   $2020
0E40-   20 20 20    JSR   $2020
0E43-   20 20 AA    JSR   $AA20
0E46-   8D AA 20    STA   $20AA
0E49-   C7          ???
0E4A-   C5 D4       CMP   $D4
0E4C-   CE C1 CD    DEC   $CDC1
0E4F-   C5 D3       CMP   $D3
0E51-   20 20 20    JSR   $2020
0E54-   20 20 20    JSR   $2020
0E57-   20 20 20    JSR   $2020
0E5A-   20 20 20    JSR   $2020
0E5D-   20 20 20    JSR   $2020
0E60-   20 20 20    JSR   $2020
0E63-   20 20 20    JSR   $2020
0E66-   AA          TAX
0E67-   8D AA 20    STA   $20AA
0E6A-   20 20 20    JSR   $2020
0E6D-   20 20 20    JSR   $2020
0E70-   20 20 20    JSR   $2020
0E73-   20 20 20    JSR   $2020
0E76-   20 20 20    JSR   $2020
0E79-   20 20 20    JSR   $2020
0E7C-   20 20 20    JSR   $2020
0E7F-   20 20 20    JSR   $2020
0E82-   20 20 20    JSR   $2020
0E85-   20 20 AA    JSR   $AA20
0E88-   8D AA AA    STA   $AAAA
0E8B-   AA          TAX
0E8C-   AA          TAX
0E8D-   AA          TAX
0E8E-   AA          TAX
0E8F-   AA          TAX
0E90-   AA          TAX
0E91-   AA          TAX
0E92-   AA          TAX
0E93-   AA          TAX
0E94-   AA          TAX
0E95-   AA          TAX
0E96-   AA          TAX
0E97-   AA          TAX
0E98-   AA          TAX
0E99-   AA          TAX
0E9A-   AA          TAX
0E9B-   AA          TAX
0E9C-   AA          TAX
0E9D-   AA          TAX
0E9E-   AA          TAX
0E9F-   AA          TAX
0EA0-   AA          TAX
0EA1-   AA          TAX
0EA2-   AA          TAX
0EA3-   AA          TAX
0EA4-   AA          TAX
0EA5-   AA          TAX
0EA6-   AA          TAX
0EA7-   AA          TAX
0EA8-   AA          TAX
0EA9-   8D AA 8D    STA   $8DAA
0EAC-   C7          ???
0EAD-   C5 D4       CMP   $D4
0EAF-   CE C1 CD    DEC   $CDC1
0EB2-   C5 D3       CMP   $D3
0EB4-   8D AA 8D    STA   $8DAA
0EB7-   A0 CA       LDY   #$CA
0EB9-   D3          ???
0EBA-   D2 A0       CMP   ($A0)
0EBC-   C8          INY
0EBD-   CF          ???
0EBE-   CD C5 8D    CMP   $8DC5
0EC1-   A0 D0       LDY   #$D0
0EC3-   D2 CE       CMP   ($CE)
0EC5-   A0 A2       LDY   #$A2
0EC7-   C1 D3       CMP   ($D3,X)
0EC9-   D3          ???
0ECA-   C5 CD       CMP   $CD
0ECC-   C2          ???
0ECD-   CC D9 20    CPY   $20D9
0ED0-   C3          ???
0ED1-   CF          ???
0ED2-   C4 C5       CPY   $C5
0ED4-   20 CD C9    JSR   $C9CD
0ED7-   CE C9 C6    DEC   $C6C9
0EDA-   C9 C5       CMP   #$C5
0EDC-   D2 A2       CMP   ($A2)
0EDE-   AC B8 C4    LDY   $C4B8
0EE1-   8D A0 D0    STA   $D0A0
0EE4-   D2 CE       CMP   ($CE)
0EE6-   A0 A2       LDY   #$A2
0EE8-   BD BD BD    LDA   $BDBD,X
0EEB-   BD BD BD    LDA   $BDBD,X
0EEE-   BD BD BD    LDA   $BDBD,X
0EF1-   BD BD BD    LDA   $BDBD,X
0EF4-   BD BD BD    LDA   $BDBD,X
0EF7-   BD BD BD    LDA   $BDBD,X
0EFA-   BD BD BD    LDA   $BDBD,X
0EFD-   BD A2 AC    LDA   $ACA2,X
0F00-   B8          CLV
0F01-   C4 B8       CPY   $B8
0F03-   C4 8D       CPY   $8D
0F05-   A0 D0       LDY   #$D0
0F07-   D2 CE       CMP   ($CE)
0F09-   A0 A2       LDY   #$A2
0F0B-   D4          ???
0F0C-   C8          INY
0F0D-   C9 D3       CMP   #$D3
0F0F-   20 D0 D2    JSR   $D2D0
0F12-   CF          ???
0F13-   C7          ???
0F14-   D2 C1       CMP   ($C1)
0F16-   CD 20 D3    CMP   $D320
0F19-   D4          ???
0F1A-   D2 C9       CMP   ($C9)
0F1C-   D0 D3       BNE   $0EF1
0F1E-   20 C1 A2    JSR   $A2C1
0F21-   AC B8 C4    LDY   $C4B8
0F24-   8D A0 D0    STA   $D0A0
0F27-   D2 CE       CMP   ($CE)
0F29-   A0 A2       LDY   #$A2
0F2B-   D0 D2       BNE   $0EFF
0F2D-   CF          ???
0F2E-   C7          ???
0F2F-   D2 C1       CMP   ($C1)
0F31-   CD 20 CF    CMP   $CF20
0F34-   C6 20       DEC   $20
0F36-   C9 D4       CMP   #$D4
0F38-   D3          ???
0F39-   20 C3 CF    JSR   $CFC3
0F3C-   CD CD C5    CMP   $C5CD
0F3F-   CE D4 D3    DEC   $D3D4
0F42-   A2 AC       LDX   #$AC
0F44-   B8          CLV
0F45-   C4 8D       CPY   $8D
0F47-   A0 D0       LDY   #$D0
0F49-   D2 CE       CMP   ($CE)
0F4B-   A0 A2       LDY   #$A2
0F4D-   C1 CE       CMP   ($CE,X)
0F4F-   C4 20       CPY   $20
0F51-   D3          ???
0F52-   D4          ???
0F53-   CF          ???
0F54-   D2 C5       CMP   ($C5)
0F56-   D3          ???
0F57-   20 D4 C8    JSR   $C8D4
0F5A-   C5 20       CMP   $20
0F5C-   D2 C5       CMP   ($C5)
0F5E-   D3          ???
0F5F-   D5 CC       CMP   $CC,X
0F61-   D4          ???
0F62-   C9 CE       CMP   #$CE
0F64-   C7          ???
0F65-   A2 AC       LDX   #$AC
0F67-   B8          CLV
0F68-   C4 8D       CPY   $8D
0F6A-   A0 D0       LDY   #$D0
0F6C-   D2 CE       CMP   ($CE)
0F6E-   A0 A2       LDY   #$A2
0F70-   C6 C9       DEC   $C9
0F72-   CC C5 20    CPY   $20C5
0F75-   D7          ???
0F76-   C9 CE       CMP   #$CE
0F78-   20 C1 20    JSR   $20C1
0F7B-   CD C9 CE    CMP   $CEC9
0F7E-   AE 20 D0    LDX   $D020
0F81-   D2 C5       CMP   ($C5)
0F83-   C6 C9       DEC   $C9
0F85-   D8          CLD
0F86-   AE A2 AC    LDX   $ACA2
0F89-   B8          CLV
0F8A-   C4 B8       CPY   $B8
0F8C-   C4 8D       CPY   $8D
0F8E-   AA          TAX
0F8F-   8D BA D1    STA   $D1BA
0F92-   D5 C5       CMP   $C5,X
0F94-   D2 D9       CMP   ($D9)
0F96-   8D A0 D0    STA   $D0A0
0F99-   D2 CE       CMP   ($CE)
0F9B-   A0 A2       LDY   #$A2
0F9D-   C6 C9       DEC   $C9
0F9F-   CC C5 20    CPY   $20C5
0FA2-   D4          ???
0FA3-   CF          ???
0FA4-   20 CD C9    JSR   $C9CD
0FA7-   CE C9 C6    DEC   $C6C9
0FAA-   D9 20 A2    CMP   $A220,Y
0FAD-   AC B8 C4    LDY   $C4B8
0FB0-   8D A0 D0    STA   $D0A0
0FB3-   D2 CE       CMP   ($CE)
0FB5-   A0 A2       LDY   #$A2
0FB7-   A8          TAY
0FB8-   D2 C5       CMP   ($C5)
0FBA-   D4          ???
0FBB-   D5 D2       CMP   $D2,X
0FBD-   CE 20 C6    DEC   $C620
0FC0-   CF          ???
0FC1-   D2 20       CMP   ($20)
0FC3-   C3          ???
0FC4-   C1 D4       CMP   ($D4,X)
0FC6-   C1 CC       CMP   ($CC,X)
0FC8-   CF          ???
0FC9-   C7          ???
0FCA-   A9 BA       LDA   #$BA
0FCC-   20 A2 8D    JSR   $8DA2
0FCF-   A0 C9       LDY   #$C9
0FD1-   CE D0 8D    DEC   $8DD0
0FD4-   A0 CC       LDY   #$CC
0FD6-   C4 C1       CPY   $C1
0FD8-   A0 D2       LDY   #$D2
0FDA-   C5 D4       CMP   $D4
0FDC-   CC C5 CE    CPY   $CEC5
0FDF-   8D A0 C3    STA   $C3A0
0FE2-   CD D0 A0    CMP   $A0D0
0FE5-   A3          ???
0FE6-   B0 A0       BCS   $0F88
0FE8-   BB          ???
0FE9-   20 C9 C6    JSR   $C6C9
0FEC-   20 CE CF    JSR   $CFCE
0FEF-   D4          ???
0FF0-   20 CA D5    JSR   $D5CA
0FF3-   D3          ???
0FF4-   D4          ???
0FF5-   20 C3 D2    JSR   $D2C3
0FF8-   AC 20 D4    LDY   $D420
0FFB-   C8          INY
0FFC-   C5 CE       CMP   $CE
0FFE-   8D A0 C2    STA   $C2A0
1001-   CE C5 A0    DEC   $A0C5
1004-   BA          TSX
1005-   CE C1 CD    DEC   $CDC1
1008-   C5 D3       CMP   $D3
100A-   A0 BB       LDY   #$BB
100C-   20 C7 CF    JSR   $CFC7
100F-   20 D4 CF    JSR   $CFD4
1012-   20 CE C1    JSR   $C1CE
1015-   CD C5 D3    CMP   $D3C5
1018-   8D A0 C3    STA   $C3A0
101B-   CD C4 A0    CMP   $A0C4
101E-   A2 C3       LDX   #$C3
1020-   C1 D4       CMP   ($D4,X)
1022-   C1 CC       CMP   ($CC,X)
1024-   CF          ???
1025-   C7          ???
1026-   A2 20       LDX   #$20
1028-   BB          ???
1029-   20 CF D4    JSR   $D4CF
102C-   C8          INY
102D-   C5 D2       CMP   $D2
102F-   D7          ???
1030-   C9 D3       CMP   #$D3
1032-   C5 AC       CMP   $AC
1034-   20 C3 C1    JSR   $C1C3
1037-   D4          ???
1038-   8D A0 D0    STA   $D0A0
103B-   D2 CE       CMP   ($CE)
103D-   A0 A2       LDY   #$A2
103F-   20 A2 AC    JSR   $ACA2
1042-   B8          CLV
1043-   C4 8D       CPY   $8D
1045-   A0 CA       LDY   #$CA
1047-   CD D0 A0    CMP   $A0D0
104A-   BA          TSX
104B-   D1 D5       CMP   ($D5),Y
104D-   C5 D2       CMP   $D2
104F-   D9 8D BA    CMP   $BA8D,Y
1052-   CE C1 CD    DEC   $CDC1
1055-   C5 D3       CMP   $D3
1057-   8D 20 A0    STA   $A020
105A-   C7          ???
105B-   D2 C5       CMP   ($C5)
105D-   D4          ???
105E-   A0 A3       LDY   #$A3
1060-   D3          ???
1061-   CE C1 CD    DEC   $CDC1
1064-   C5 8D       CMP   $8D
1066-   A0 C7       LDY   #$C7
1068-   D2 C5       CMP   ($C5)
106A-   D4          ???
106B-   A0 A3       LDY   #$A3
106D-   C4 CE       CPY   $CE
106F-   C1 CD       CMP   ($CD,X)
1071-   C5 8D       CMP   $8D
1073-   AA          TAX
1074-   8D AA AA    STA   $AAAA
1077-   20 CE C5    JSR   $C5CE
107A-   C5 C4       CMP   $C4
107C-   20 D4 CF    JSR   $CFD4
107F-   20 C3 C8    JSR   $C8C3
1082-   C5 C3       CMP   $C3
1084-   CB          ???
1085-   20 C9 C6    JSR   $C6C9
1088-   20 D3 D4    JSR   $D4D3
108B-   C1 D2       CMP   ($D2,X)
108D-   D4          ???
108E-   C9 CE       CMP   #$CE
1090-   C7          ???
1091-   20 D7 C9    JSR   $C9D7
1094-   D4          ???
1095-   C8          INY
1096-   20 D4 AE    JSR   $AED4
1099-   BB          ???
109A-   20 C9 C6    JSR   $C6C9
109D-   20 D3 CF    JSR   $CFD3
10A0-   AC 20 C9    LDY   $C920
10A3-   CE D3 C5    DEC   $C5D3
10A6-   D2 D4       CMP   ($D4)
10A8-   8D AA AA    STA   $AAAA
10AB-   20 CD C9    JSR   $C9CD
10AE-   CE AE 20    DEC   $20AE
10B1-   C1 C6       CMP   ($C6,X)
10B3-   D4          ???
10B4-   C5 D2       CMP   $D2
10B6-   20 D4 AE    JSR   $AED4
10B9-   20 CF D4    JSR   $D4CF
10BC-   C8          INY
10BD-   C5 D2       CMP   $D2
10BF-   D7          ???
10C0-   C9 D3       CMP   #$D3
10C2-   C5 AC       CMP   $AC
10C4-   20 CA D5    JSR   $D5CA
10C7-   D3          ???
10C8-   D4          ???
10C9-   20 D0 D2    JSR   $D2D0
10CC-   C5 C6       CMP   $C6
10CE-   C9 D8       CMP   #$D8
10D0-   AE 8D AA    LDX   $AA8D
10D3-   8D A0 D3    STA   $D3A0
10D6-   D0 CF       BNE   $10A7
10D8-   D3          ???
10D9-   A0 A3       LDY   #$A3
10DB-   D3          ???
10DC-   CE C1 CD    DEC   $CDC1
10DF-   C5 BB       CMP   $BB
10E1-   A2 D4       LDX   #$D4
10E3-   AE A2 8D    LDX   $8DA2
10E6-   A0 CC       LDY   #$CC
10E8-   C4 C1       CPY   $C1
10EA-   A0 D2       LDY   #$D2
10EC-   C5 D4       CMP   $D4
10EE-   D5 D2       CMP   $D2,X
10F0-   CE 8D A0    DEC   $A08D
10F3-   C3          ???
10F4-   CD D0 A0    CMP   $A0D0
10F7-   A3          ???
10F8-   B1 A0       LDA   ($A0),Y
10FA-   BB          ???
10FB-   20 C9 C6    JSR   $C6C9
10FE-   20 D3 D4    JSR   $D4D3
1101-   D2 C9       CMP   ($C9)
1103-   CE C7 20    DEC   $20C7
1106-   C2          ???
1107-   C5 C7       CMP   $C7
1109-   C9 CE       CMP   #$CE
110B-   D3          ???
110C-   20 D7 C9    JSR   $C9D7
110F-   D4          ???
1110-   C8          INY
1111-   20 A2 D4    JSR   $D4A2
1114-   AE A2 8D    LDX   $8DA2
1117-   A0 C2       LDY   #$C2
1119-   CE C5 A0    DEC   $A0C5
111C-   BA          TSX
111D-   C3          ???
111E-   CF          ???
111F-   CE D4 CE    DEC   $CED4
1122-   A0 BB       LDY   #$BB
1124-   20 C4 C5    JSR   $C5C4
1127-   CC C5 D4    CPY   $D4C5
112A-   C5 20       CMP   $20
112C-   D4          ???
112D-   AE 20 C6    LDX   $C620
1130-   D2 CF       CMP   ($CF)
1132-   CD 20 D3    CMP   $D320
1135-   D4          ???
1136-   D2 C9       CMP   ($C9)
1138-   CE C7 8D    DEC   $8DC7
113B-   A0 D3       LDY   #$D3
113D-   C4 C5       CPY   $C5
113F-   CC A0 A3    CPY   $A3A0
1142-   C4 CE       CPY   $CE
1144-   C1 CD       CMP   ($CD,X)
1146-   C5 BB       CMP   $BB
1148-   A3          ???
1149-   B1 BB       LDA   ($BB),Y
114B-   A3          ???
114C-   B2 8D       LDA   ($8D)
114E-   A0 CC       LDY   #$CC
1150-   C4 C1       CPY   $C1
1152-   A0 A3       LDY   #$A3
1154-   A4 C6       LDY   $C6
1156-   C6 8D       DEC   $8D
1158-   A0 D3       LDY   #$D3
115A-   D4          ???
115B-   C1 A0       CMP   ($A0,X)
115D-   C1 C4       CMP   ($C4,X)
115F-   C4 D4       CPY   $D4
1161-   8D BA C3    STA   $C3BA
1164-   CF          ???
1165-   CE D4 CE    DEC   $CED4
1168-   8D A0 D3    STA   $D3A0
116B-   C3          ???
116C-   C1 D4       CMP   ($D4,X)
116E-   A0 A2       LDY   #$A2
1170-   CD C9 CE    CMP   $CEC9
1173-   AE A2 BB    LDX   $BBA2
1176-   A3          ???
1177-   C4 CE       CPY   $CE
1179-   C1 CD       CMP   ($CD,X)
117B-   C5 BB       CMP   $BB
117D-   A3          ???
117E-   B3          ???
117F-   B0 8D       BCS   $110E
1181-   A0 CC       LDY   #$CC
1183-   C4 C1       CPY   $C1
1185-   A0 D2       LDY   #$D2
1187-   C5 D4       CMP   $D4
1189-   CC C5 CE    CPY   $CEC5
118C-   8D A0 C7    STA   $C7A0
118F-   D2 C5       CMP   ($C5)
1191-   D4          ???
1192-   A0 C4       LDY   #$C4
1194-   CE C1 CD    DEC   $CDC1
1197-   C5 20       CMP   $20
1199-   BB          ???
119A-   20 D3 C3    JSR   $C3D3
119D-   C1 D4       CMP   ($D4,X)
119F-   20 D0 D5    JSR   $D5D0
11A2-   D4          ???
11A3-   D3          ???
11A4-   20 CC C5    JSR   $C5CC
11A7-   CE C7 D4    DEC   $D4C7
11AA-   C8          INY
11AB-   20 C2 D9    JSR   $D9C2
11AE-   D4          ???
11AF-   C5 8D       CMP   $8D
11B1-   BB          ???
11B2-   20 C9 CE    JSR   $CEC9
11B5-   20 D2 C5    JSR   $C5D2
11B8-   D4          ???
11B9-   D5 D2       CMP   $D2,X
11BB-   CE 20 C1    DEC   $C120
11BE-   D3          ???
11BF-   20 D7 C5    JSR   $C5D7
11C2-   CC CC 20    CPY   $20CC
11C5-   C1 D3       CMP   ($D3,X)
11C7-   20 D2 C5    JSR   $C5D2
11CA-   D4          ???
11CB-   CC C5 CE    CPY   $CEC5
11CE-   8D AA 8D    STA   $8DAA
11D1-   AA          TAX
11D2-   AA          TAX
11D3-   20 CE CF    JSR   $CFCE
11D6-   D7          ???
11D7-   20 C1 C4    JSR   $C4C1
11DA-   C4 20       CPY   $20
11DC-   C2          ???
11DD-   C1 C3       CMP   ($C3,X)
11DF-   CB          ???
11E0-   20 A2 D4    JSR   $D4A2
11E3-   AE A2 20    LDX   $20A2
11E6-   D0 D2       BNE   $11BA
11E8-   C5 C6       CMP   $C6
11EA-   C9 D8       CMP   #$D8
11EC-   20 C9 C6    JSR   $C6C9
11EF-   20 CE C5    JSR   $C5CE
11F2-   C5 C4       CMP   $C4
11F4-   C5 C4       CMP   $C4
11F6-   8D AA 8D    STA   $8DAA
11F9-   A0 CC       LDY   #$CC
11FB-   C4 C1       CPY   $C1
11FD-   A0 C1       LDY   #$C1
11FF-   C4 C4       CPY   $C4
1201-   D4          ???
1202-   8D A0 C3    STA   $C3A0
1205-   CD D0 A0    CMP   $A0D0
1208-   A3          ???
1209-   A4 C6       LDY   $C6
120B-   C6 8D       DEC   $8D
120D-   A0 C2       LDY   #$C2
120F-   CE C5 A0    DEC   $A0C5
1212-   D3          ???
1213-   CB          ???
1214-   C9 D0       CMP   #$D0
1216-   D4          ???
1217-   8D A0 D3    STA   $D3A0
121A-   C3          ???
121B-   C1 D4       CMP   ($D4,X)
121D-   A0 A2       LDY   #$A2
121F-   D4          ???
1220-   AE A2 BB    LDX   $BBA2
1223-   C4 CE       CPY   $CE
1225-   C1 CD       CMP   ($CD,X)
1227-   C5 BB       CMP   $BB
1229-   A3          ???
122A-   B3          ???
122B-   B0 8D       BCS   $11BA
122D-   A0 C7       LDY   #$C7
122F-   D2 C5       CMP   ($C5)
1231-   D4          ???
1232-   A0 A3       LDY   #$A3
1234-   C4 CE       CPY   $CE
1236-   C1 CD       CMP   ($CD,X)
1238-   C5 8D       CMP   $8D
123A-   D3          ???
123B-   CB          ???
123C-   C9 D0       CMP   #$D0
123E-   D4          ???
123F-   8D A0 D2    STA   $D2A0
1242-   D4          ???
1243-   D3          ???
1244-   8D AA 8D    STA   $8DAA
1247-   AA          TAX
1248-   AA          TAX
1249-   AA          TAX
124A-   AA          TAX
124B-   AA          TAX
124C-   AA          TAX
124D-   AA          TAX
124E-   AA          TAX
124F-   AA          TAX
1250-   AA          TAX
1251-   AA          TAX
1252-   AA          TAX
1253-   AA          TAX
1254-   AA          TAX
1255-   AA          TAX
1256-   AA          TAX
1257-   AA          TAX
1258-   AA          TAX
1259-   AA          TAX
125A-   AA          TAX
125B-   AA          TAX
125C-   AA          TAX
125D-   AA          TAX
125E-   AA          TAX
125F-   AA          TAX
1260-   AA          TAX
1261-   AA          TAX
1262-   AA          TAX
1263-   AA          TAX
1264-   AA          TAX
1265-   AA          TAX
1266-   AA          TAX
1267-   8D AA 20    STA   $20AA
126A-   20 20 20    JSR   $2020
126D-   20 20 20    JSR   $2020
1270-   20 20 20    JSR   $2020
1273-   20 20 20    JSR   $2020
1276-   20 20 20    JSR   $2020
1279-   20 20 20    JSR   $2020
127C-   20 20 20    JSR   $2020
127F-   20 20 20    JSR   $2020
1282-   20 20 20    JSR   $2020
1285-   20 20 AA    JSR   $AA20
1288-   8D AA 20    STA   $20AA
128B-   C4 C5       CPY   $C5
128D-   CC CD C9    CPY   $C9CD
1290-   CE 20 20    DEC   $2020
1293-   20 20 20    JSR   $2020
1296-   20 20 20    JSR   $2020
1299-   20 20 20    JSR   $2020
129C-   20 20 20    JSR   $2020
129F-   20 20 20    JSR   $2020
12A2-   20 20 20    JSR   $2020
12A5-   20 20 20    JSR   $2020
12A8-   AA          TAX
12A9-   8D AA 20    STA   $20AA
12AC-   20 20 20    JSR   $2020
12AF-   20 20 20    JSR   $2020
12B2-   20 20 20    JSR   $2020
12B5-   20 20 20    JSR   $2020
12B8-   20 20 20    JSR   $2020
12BB-   20 20 20    JSR   $2020
12BE-   20 20 20    JSR   $2020
12C1-   20 20 20    JSR   $2020
12C4-   20 20 20    JSR   $2020
12C7-   20 20 AA    JSR   $AA20
12CA-   8D AA AA    STA   $AAAA
12CD-   AA          TAX
12CE-   AA          TAX
12CF-   AA          TAX
12D0-   AA          TAX
12D1-   AA          TAX
12D2-   AA          TAX
12D3-   AA          TAX
12D4-   AA          TAX
12D5-   AA          TAX
12D6-   AA          TAX
12D7-   AA          TAX
12D8-   AA          TAX
12D9-   AA          TAX
12DA-   AA          TAX
12DB-   AA          TAX
12DC-   AA          TAX
12DD-   AA          TAX
12DE-   AA          TAX
12DF-   AA          TAX
12E0-   AA          TAX
12E1-   AA          TAX
12E2-   AA          TAX
12E3-   AA          TAX
12E4-   AA          TAX
12E5-   AA          TAX
12E6-   AA          TAX
12E7-   AA          TAX
12E8-   AA          TAX
12E9-   AA          TAX
12EA-   AA          TAX
12EB-   8D AA 8D    STA   $8DAA
12EE-   C4 C5       CPY   $C5
12F0-   CC CD C9    CPY   $C9CD
12F3-   CE 8D AA    DEC   $AA8D
12F6-   8D AA AA    STA   $AAAA
12F9-   20 C8 C9    JSR   $C9C8
12FC-   CA          DEX
12FD-   C1 C3       CMP   ($C3,X)
12FF-   CB          ???
1300-   20 C5 D2    JSR   $D2C5
1303-   D2 CF       CMP   ($CF)
1305-   D2 20       CMP   ($20)
1307-   C8          INY
1308-   C1 CE       CMP   ($CE,X)
130A-   C4 CC       CPY   $CC
130C-   C9 CE       CMP   #$CE
130E-   C7          ???
130F-   8D AA 8D    STA   $8DAA
1312-   A0 CC       LDY   #$CC
1314-   C4 C1       CPY   $C1
1316-   A0 A3       LDY   #$A3
1318-   A4 C6       LDY   $C6
131A-   C6 8D       DEC   $8D
131C-   A0 D3       LDY   #$D3
131E-   D4          ???
131F-   C1 A0       CMP   ($A0,X)
1321-   A4 C4       LDY   $C4
1323-   B8          CLV
1324-   8D AA 8D    STA   $8DAA
1327-   AA          TAX
1328-   AA          TAX
1329-   20 D3 C5    JSR   $C5D3
132C-   D4          ???
132D-   20 C5 D2    JSR   $D2C5
1330-   D2 CF       CMP   ($CF)
1332-   D2 20       CMP   ($20)
1334-   C3          ???
1335-   CF          ???
1336-   CE D4 D2    DEC   $D2D4
1339-   CF          ???
133A-   CC 20 D4    CPY   $D420
133D-   CF          ???
133E-   20 C3 CF    JSR   $CFC3
1341-   CE D4 C9    DEC   $C9D4
1344-   CE D5 C5    DEC   $C5D5
1347-   8D AA AA    STA   $AAAA
134A-   20 C6 C9    JSR   $C9C6
134D-   CC C5 20    CPY   $20C5
1350-   D4          ???
1351-   CF          ???
1352-   20 C4 C5    JSR   $C5C4
1355-   CC C5 D4    CPY   $D4C5
1358-   C5 20       CMP   $20
135A-   C4 CF       CPY   $CF
135C-   C5 D3       CMP   $D3
135E-   CE A7 D4    DEC   $D4A7
1361-   20 C5 D8    JSR   $D8C5
1364-   C9 D3       CMP   #$D3
1366-   D4          ???
1367-   8D AA 8D    STA   $8DAA
136A-   A0 CC       LDY   #$CC
136C-   C4 C1       CPY   $C1
136E-   A0 A3       LDY   #$A3
1370-   BC BA C4    LDY   $C4BA,X
1373-   C5 CC       CMP   $CC
1375-   C3          ???
1376-   CF          ???
1377-   CE D4 8D    DEC   $8DD4
137A-   A0 D3       LDY   #$D3
137C-   D4          ???
137D-   C1 A0       CMP   ($A0,X)
137F-   A4 B9       LDY   $B9
1381-   C4 B5       CPY   $B5
1383-   C1 8D       CMP   ($8D,X)
1385-   A0 CC       LDY   #$CC
1387-   C4 C1       CPY   $C1
1389-   A0 A3       LDY   #$A3
138B-   BE BA C4    LDX   $C4BA,Y
138E-   C5 CC       CMP   $CC
1390-   C3          ???
1391-   CF          ???
1392-   CE D4 8D    DEC   $8DD4
1395-   A0 D3       LDY   #$D3
1397-   D4          ???
1398-   C1 A0       CMP   ($A0,X)
139A-   A4 B9       LDY   $B9
139C-   C4 B5       CPY   $B5
139E-   C2          ???
139F-   8D AA 8D    STA   $8DAA
13A2-   A0 D3       LDY   #$D3
13A4-   C3          ???
13A5-   C1 D4       CMP   ($D4,X)
13A7-   A0 A2       LDY   #$A2
13A9-   C4 C5       CPY   $C5
13AB-   CC C5 D4    CPY   $D4C5
13AE-   C5 20       CMP   $20
13B0-   A2 BB       LDX   #$BB
13B2-   A3          ???
13B3-   C4 CE       CPY   $CE
13B5-   C1 CD       CMP   ($CD,X)
13B7-   C5 BB       CMP   $BB
13B9-   A3          ???
13BA-   B5 B0       LDA   $B0,X
13BC-   20 BB 20    JSR   $20BB
13BF-   C4 C5       CPY   $C5
13C1-   CC C5 D4    CPY   $D4C5
13C4-   C5 20       CMP   $20
13C6-   D0 D2       BNE   $139A
13C8-   C5 D6       CMP   $D6
13CA-   C9 CF       CMP   #$CF
13CC-   D5 D3       CMP   $D3,X
13CE-   20 C9 C6    JSR   $C6C9
13D1-   20 C5 D8    JSR   $D8C5
13D4-   C9 D3       CMP   #$D3
13D6-   D4          ???
13D7-   D3          ???
13D8-   8D A0 C3    STA   $C3A0
13DB-   CD C4 A0    CMP   $A0C4
13DE-   A3          ???
13DF-   D2 C5       CMP   ($C5)
13E1-   D4          ???
13E2-   D5 D2       CMP   $D2,X
13E4-   CE 8D AA    DEC   $AA8D
13E7-   8D BA C4    STA   $C4BA
13EA-   C5 CC       CMP   $CC
13EC-   C3          ???
13ED-   CF          ???
13EE-   CE D4 8D    DEC   $8DD4
13F1-   A0 D2       LDY   #$D2
13F3-   D4          ???
13F4-   D3          ???
13F5-   8D AA 8D    STA   $8DAA
13F8-   AA          TAX
13F9-   AA          TAX
13FA-   AA          TAX
13FB-   AA          TAX
13FC-   AA          TAX
13FD-   AA          TAX
13FE-   AA          TAX
13FF-   AA          TAX
1400-   AA          TAX
1401-   AA          TAX
1402-   AA          TAX
1403-   AA          TAX
1404-   AA          TAX
1405-   AA          TAX
1406-   AA          TAX
1407-   AA          TAX
1408-   AA          TAX
1409-   AA          TAX
140A-   AA          TAX
140B-   AA          TAX
140C-   AA          TAX
140D-   AA          TAX
140E-   AA          TAX
140F-   AA          TAX
1410-   AA          TAX
1411-   AA          TAX
1412-   AA          TAX
1413-   AA          TAX
1414-   AA          TAX
1415-   AA          TAX
1416-   AA          TAX
1417-   AA          TAX
1418-   8D AA 20    STA   $20AA
141B-   20 20 20    JSR   $2020
141E-   20 20 20    JSR   $2020
1421-   20 20 20    JSR   $2020
1424-   20 20 20    JSR   $2020
1427-   20 20 20    JSR   $2020
142A-   20 20 20    JSR   $2020
142D-   20 20 20    JSR   $2020
1430-   20 20 20    JSR   $2020
1433-   20 20 20    JSR   $2020
1436-   20 20 AA    JSR   $AA20
1439-   8D AA 20    STA   $20AA
143C-   CD C1 C9    CMP   $C9C1
143F-   CE 20 C6    DEC   $C620
1442-   C9 CC       CMP   #$CC
1444-   C5 20       CMP   $20
1446-   C3          ???
1447-   CF          ???
1448-   D0 D9       BNE   $1423
144A-   20 CC CF    JSR   $CFCC
144D-   CF          ???
144E-   D0 20       BNE   $1470
1450-   20 20 20    JSR   $2020
1453-   20 20 20    JSR   $2020
1456-   20 20 20    JSR   $2020
1459-   AA          TAX
145A-   8D AA 20    STA   $20AA
145D-   20 20 20    JSR   $2020
1460-   20 20 20    JSR   $2020
1463-   20 20 20    JSR   $2020
1466-   20 20 20    JSR   $2020
1469-   20 20 20    JSR   $2020
146C-   20 20 20    JSR   $2020
146F-   20 20 20    JSR   $2020
1472-   20 20 20    JSR   $2020
1475-   20 20 20    JSR   $2020
1478-   20 20 AA    JSR   $AA20
147B-   8D AA AA    STA   $AAAA
147E-   AA          TAX
147F-   AA          TAX
1480-   AA          TAX
1481-   AA          TAX
1482-   AA          TAX
1483-   AA          TAX
1484-   AA          TAX
1485-   AA          TAX
1486-   AA          TAX
1487-   AA          TAX
1488-   AA          TAX
1489-   AA          TAX
148A-   AA          TAX
148B-   AA          TAX
148C-   AA          TAX
148D-   AA          TAX
148E-   AA          TAX
148F-   AA          TAX
1490-   AA          TAX
1491-   AA          TAX
1492-   AA          TAX
1493-   AA          TAX
1494-   AA          TAX
1495-   AA          TAX
1496-   AA          TAX
1497-   AA          TAX
1498-   AA          TAX
1499-   AA          TAX
149A-   AA          TAX
149B-   AA          TAX
149C-   8D AA 8D    STA   $8DAA
149F-   C6 C3       DEC   $C3
14A1-   CF          ???
14A2-   D0 D9       BNE   $147D
14A4-   8D AA 8D    STA   $8DAA
14A7-   A0 D0       LDY   #$D0
14A9-   D2 CE       CMP   ($CE)
14AB-   A0 A2       LDY   #$A2
14AD-   CD C9 CE    CMP   $CEC9
14B0-   C9 C6       CMP   #$C6
14B2-   D9 C9 CE    CMP   $CEC9,Y
14B5-   C7          ???
14B6-   AE AE AE    LDX   $AEAE
14B9-   A2 AC       LDX   #$AC
14BB-   B8          CLV
14BC-   C4 B8       CPY   $B8
14BE-   C4 8D       CPY   $8D
14C0-   AA          TAX
14C1-   8D A0 CA    STA   $CAA0
14C4-   D3          ???
14C5-   D2 A0       CMP   ($A0)
14C7-   D3          ???
14C8-   C5 D4       CMP   $D4
14CA-   C6 C9       DEC   $C9
14CC-   CC C5 C5    CPY   $C5C5
14CF-   D2 D2       CMP   ($D2)
14D1-   8D A0 CA    STA   $CAA0
14D4-   D3          ???
14D5-   D2 A0       CMP   ($A0)
14D7-   CF          ???
14D8-   D0 C5       BNE   $149F
14DA-   CE C6 C9    DEC   $C9C6
14DD-   CC C5 D3    CPY   $D3C5
14E0-   8D AA 8D    STA   $8DAA
14E3-   AA          TAX
14E4-   AA          TAX
14E5-   20 D4 C8    JSR   $C8D4
14E8-   C5 20       CMP   $20
14EA-   C6 CF       DEC   $CF
14EC-   CC CC CF    CPY   $CFCC
14EF-   D7          ???
14F0-   C9 CE       CMP   #$CE
14F2-   C7          ???
14F3-   20 CC CF    JSR   $CFCC
14F6-   CF          ???
14F7-   D0 20       BNE   $1519
14F9-   C5 CE       CMP   $CE
14FB-   C4 D3       CPY   $D3
14FD-   20 D7 C8    JSR   $C8D7
1500-   C5 CE       CMP   $CE
1502-   8D AA AA    STA   $AAAA
1505-   20 D4 C8    JSR   $C8D4
1508-   C5 20       CMP   $20
150A-   C5 CE       CMP   $CE
150C-   C4 20       CPY   $20
150E-   CF          ???
150F-   C6 20       DEC   $20
1511-   D4          ???
1512-   C8          INY
1513-   C5 20       CMP   $20
1515-   D3          ???
1516-   CF          ???
1517-   D5 D2       CMP   $D2,X
1519-   C3          ???
151A-   C5 20       CMP   $20
151C-   C6 C9       DEC   $C9
151E-   CC C5 8D    CPY   $8DC5
1521-   AA          TAX
1522-   AA          TAX
1523-   20 C9 D3    JSR   $D3C9
1526-   20 D2 C5    JSR   $C5D2
1529-   C1 C3       CMP   ($C3,X)
152B-   C8          INY
152C-   C5 C4       CMP   $C4
152E-   AC 20 D0    LDY   $D020
1531-   D2 CF       CMP   ($CF)
1533-   CD D0 D4    CMP   $D4D0
1536-   C9 CE       CMP   #$CE
1538-   C7          ???
1539-   20 C1 CE    JSR   $CEC1
153C-   20 C5 D2    JSR   $D2C5
153F-   D2 CF       CMP   ($CF)
1541-   D2 8D       CMP   ($8D)
1543-   AA          TAX
1544-   AA          TAX
1545-   20 D4 C8    JSR   $C8D4
1548-   C1 D4       CMP   ($D4,X)
154A-   20 C7 C5    JSR   $C5C7
154D-   D4          ???
154E-   D3          ???
154F-   20 C8 C1    JSR   $C1C8
1552-   CE C4 CC    DEC   $CCC4
1555-   C5 C4       CMP   $C4
1557-   20 C2 D9    JSR   $D9C2
155A-   20 C6 C3    JSR   $C3C6
155D-   CC CF D3    CPY   $D3CF
1560-   C5 8D       CMP   $8D
1562-   AA          TAX
1563-   8D BA C3    STA   $C3BA
1566-   CF          ???
1567-   D0 D9       BNE   $1542
1569-   CC CF CF    CPY   $CFCF
156C-   D0 8D       BNE   $14FB
156E-   A0 CA       LDY   #$CA
1570-   D3          ???
1571-   D2 A0       CMP   ($A0)
1573-   D2 C5       CMP   ($C5)
1575-   C1 C4       CMP   ($C4,X)
1577-   D3          ???
1578-   D2 C3       CMP   ($C3)
157A-   8D A0 CA    STA   $CAA0
157D-   D3          ???
157E-   D2 A0       CMP   ($A0)
1580-   C3          ???
1581-   C8          INY
1582-   CB          ???
1583-   C3          ???
1584-   CF          ???
1585-   CD CD C5    CMP   $C5CD
1588-   CE D4 8D    DEC   $8DD4
158B-   A0 CA       LDY   #$CA
158D-   D3          ???
158E-   D2 A0       CMP   ($A0)
1590-   D7          ???
1591-   D2 C9       CMP   ($C9)
1593-   D4          ???
1594-   C5 C4       CMP   $C4
1596-   C5 D3       CMP   $D3
1598-   D4          ???
1599-   8D BA CC    STA   $CCBA
159C-   CF          ???
159D-   CF          ???
159E-   D0 C5       BNE   $1565
15A0-   CE C4 A0    DEC   $A0C4
15A3-   CA          DEX
15A4-   CD D0 A0    CMP   $A0D0
15A7-   BA          TSX
15A8-   C3          ???
15A9-   CF          ???
15AA-   D0 D9       BNE   $1585
15AC-   CC CF CF    CPY   $CFCF
15AF-   D0 8D       BNE   $153E
15B1-   AA          TAX
15B2-   8D AA AA    STA   $AAAA
15B5-   AA          TAX
15B6-   AA          TAX
15B7-   AA          TAX
15B8-   AA          TAX
15B9-   AA          TAX
15BA-   AA          TAX
15BB-   AA          TAX
15BC-   AA          TAX
15BD-   AA          TAX
15BE-   AA          TAX
15BF-   AA          TAX
15C0-   AA          TAX
15C1-   AA          TAX
15C2-   AA          TAX
15C3-   AA          TAX
15C4-   AA          TAX
15C5-   AA          TAX
15C6-   AA          TAX
15C7-   AA          TAX
15C8-   AA          TAX
15C9-   AA          TAX
15CA-   AA          TAX
15CB-   AA          TAX
15CC-   AA          TAX
15CD-   AA          TAX
15CE-   AA          TAX
15CF-   AA          TAX
15D0-   AA          TAX
15D1-   AA          TAX
15D2-   AA          TAX
15D3-   8D AA 20    STA   $20AA
15D6-   20 20 20    JSR   $2020
15D9-   20 20 20    JSR   $2020
15DC-   20 20 20    JSR   $2020
15DF-   20 20 20    JSR   $2020
15E2-   20 20 20    JSR   $2020
15E5-   20 20 20    JSR   $2020
15E8-   20 20 20    JSR   $2020
15EB-   20 20 20    JSR   $2020
15EE-   20 20 20    JSR   $2020
15F1-   20 20 AA    JSR   $AA20
15F4-   8D AA 20    STA   $20AA
15F7-   D3          ???
15F8-   C5 D4       CMP   $D4
15FA-   C6 C9       DEC   $C9
15FC-   CC C5 C5    CPY   $C5C5
15FF-   D2 D2       CMP   ($D2)
1601-   20 20 20    JSR   $2020
1604-   20 20 20    JSR   $2020
1607-   20 20 20    JSR   $2020
160A-   20 20 20    JSR   $2020
160D-   20 20 20    JSR   $2020
1610-   20 20 20    JSR   $2020
1613-   20 AA 8D    JSR   $8DAA
1616-   AA          TAX
1617-   20 20 20    JSR   $2020
161A-   20 20 20    JSR   $2020
161D-   20 20 20    JSR   $2020
1620-   20 20 20    JSR   $2020
1623-   20 20 20    JSR   $2020
1626-   20 20 20    JSR   $2020
1629-   20 20 20    JSR   $2020
162C-   20 20 20    JSR   $2020
162F-   20 20 20    JSR   $2020
1632-   20 20 20    JSR   $2020
1635-   AA          TAX
1636-   8D AA AA    STA   $AAAA
1639-   AA          TAX
163A-   AA          TAX
163B-   AA          TAX
163C-   AA          TAX
163D-   AA          TAX
163E-   AA          TAX
163F-   AA          TAX
1640-   AA          TAX
1641-   AA          TAX
1642-   AA          TAX
1643-   AA          TAX
1644-   AA          TAX
1645-   AA          TAX
1646-   AA          TAX
1647-   AA          TAX
1648-   AA          TAX
1649-   AA          TAX
164A-   AA          TAX
164B-   AA          TAX
164C-   AA          TAX
164D-   AA          TAX
164E-   AA          TAX
164F-   AA          TAX
1650-   AA          TAX
1651-   AA          TAX
1652-   AA          TAX
1653-   AA          TAX
1654-   AA          TAX
1655-   AA          TAX
1656-   AA          TAX
1657-   8D AA 8D    STA   $8DAA
165A-   D3          ???
165B-   C5 D4       CMP   $D4
165D-   C6 C9       DEC   $C9
165F-   CC C5 C5    CPY   $C5C5
1662-   D2 D2       CMP   ($D2)
1664-   8D AA 8D    STA   $8DAA
1667-   AA          TAX
1668-   AA          TAX
1669-   20 D3 C5    JSR   $C5D3
166C-   D4          ???
166D-   20 C5 D2    JSR   $D2C5
1670-   D2 CF       CMP   ($CF)
1672-   D2 20       CMP   ($20)
1674-   C3          ???
1675-   CF          ???
1676-   CE D4 D2    DEC   $D2D4
1679-   CF          ???
167A-   CC 20 D4    CPY   $D420
167D-   CF          ???
167E-   20 C6 C9    JSR   $C9C6
1681-   CC C5 20    CPY   $20C5
1684-   C3          ???
1685-   CC CF D3    CPY   $D3CF
1688-   C9 CE       CMP   #$CE
168A-   C7          ???
168B-   20 D2 CF    JSR   $CFD2
168E-   D5 D4       CMP   $D4,X
1690-   C9 CE       CMP   #$CE
1692-   C5 8D       CMP   $8D
1694-   AA          TAX
1695-   8D A0 CC    STA   $CCA0
1698-   C4 C1       CPY   $C1
169A-   A0 A3       LDY   #$A3
169C-   BC C6 C3    LDY   $C3C6,X
169F-   CC CF D3    CPY   $D3CF
16A2-   C5 8D       CMP   $8D
16A4-   A0 D3       LDY   #$D3
16A6-   D4          ???
16A7-   C1 A0       CMP   ($A0,X)
16A9-   A4 B9       LDY   $B9
16AB-   C4 B5       CPY   $B5
16AD-   C1 8D       CMP   ($8D,X)
16AF-   A0 CC       LDY   #$CC
16B1-   C4 C1       CPY   $C1
16B3-   A0 A3       LDY   #$A3
16B5-   BE C6 C3    LDX   $C3C6,Y
16B8-   CC CF D3    CPY   $D3CF
16BB-   C5 8D       CMP   $8D
16BD-   A0 D3       LDY   #$D3
16BF-   D4          ???
16C0-   C1 A0       CMP   ($A0,X)
16C2-   A4 B9       LDY   $B9
16C4-   C4 B5       CPY   $B5
16C6-   C2          ???
16C7-   8D A0 D2    STA   $D2A0
16CA-   D4          ???
16CB-   D3          ???
16CC-   8D AA 8D    STA   $8DAA
16CF-   AA          TAX
16D0-   AA          TAX
16D1-   AA          TAX
16D2-   AA          TAX
16D3-   AA          TAX
16D4-   AA          TAX
16D5-   AA          TAX
16D6-   AA          TAX
16D7-   AA          TAX
16D8-   AA          TAX
16D9-   AA          TAX
16DA-   AA          TAX
16DB-   AA          TAX
16DC-   AA          TAX
16DD-   AA          TAX
16DE-   AA          TAX
16DF-   AA          TAX
16E0-   AA          TAX
16E1-   AA          TAX
16E2-   AA          TAX
16E3-   AA          TAX
16E4-   AA          TAX
16E5-   AA          TAX
16E6-   AA          TAX
16E7-   AA          TAX
16E8-   AA          TAX
16E9-   AA          TAX
16EA-   AA          TAX
16EB-   AA          TAX
16EC-   AA          TAX
16ED-   AA          TAX
16EE-   AA          TAX
16EF-   8D AA 20    STA   $20AA
16F2-   20 20 20    JSR   $2020
16F5-   20 20 20    JSR   $2020
16F8-   20 20 20    JSR   $2020
16FB-   20 20 20    JSR   $2020
16FE-   20 20 20    JSR   $2020
1701-   20 20 20    JSR   $2020
1704-   20 20 20    JSR   $2020
1707-   20 20 20    JSR   $2020
170A-   20 20 20    JSR   $2020
170D-   20 20 AA    JSR   $AA20
1710-   8D AA 20    STA   $20AA
1713-   CF          ???
1714-   D0 C5       BNE   $16DB
1716-   CE C6 C9    DEC   $C9C6
1719-   CC C5 D3    CPY   $D3C5
171C-   20 20 20    JSR   $2020
171F-   20 20 20    JSR   $2020
1722-   20 20 20    JSR   $2020
1725-   20 20 20    JSR   $2020
1728-   20 20 20    JSR   $2020
172B-   20 20 20    JSR   $2020
172E-   20 20 AA    JSR   $AA20
1731-   8D AA 20    STA   $20AA
1734-   20 20 20    JSR   $2020
1737-   20 20 20    JSR   $2020
173A-   20 20 20    JSR   $2020
173D-   20 20 20    JSR   $2020
1740-   20 20 20    JSR   $2020
1743-   20 20 20    JSR   $2020
1746-   20 20 20    JSR   $2020
1749-   20 20 20    JSR   $2020
174C-   20 20 20    JSR   $2020
174F-   20 20 AA    JSR   $AA20
1752-   8D AA AA    STA   $AAAA
1755-   AA          TAX
1756-   AA          TAX
1757-   AA          TAX
1758-   AA          TAX
1759-   AA          TAX
175A-   AA          TAX
175B-   AA          TAX
175C-   AA          TAX
175D-   AA          TAX
175E-   AA          TAX
175F-   AA          TAX
1760-   AA          TAX
1761-   AA          TAX
1762-   AA          TAX
1763-   AA          TAX
1764-   AA          TAX
1765-   AA          TAX
1766-   AA          TAX
1767-   AA          TAX
1768-   AA          TAX
1769-   AA          TAX
176A-   AA          TAX
176B-   AA          TAX
176C-   AA          TAX
176D-   AA          TAX
176E-   AA          TAX
176F-   AA          TAX
1770-   AA          TAX
1771-   AA          TAX
1772-   AA          TAX
1773-   8D AA 8D    STA   $8DAA
1776-   CF          ???
1777-   D0 C5       BNE   $173E
1779-   CE C6 C9    DEC   $C9C6
177C-   CC C5 D3    CPY   $D3C5
177F-   8D AA 8D    STA   $8DAA
1782-   AA          TAX
1783-   AA          TAX
1784-   20 CF D0    JSR   $D0CF
1787-   C5 CE       CMP   $CE
1789-   20 D3 CF    JSR   $CFD3
178C-   D5 D2       CMP   $D2,X
178E-   C3          ???
178F-   C5 20       CMP   $20
1791-   C1 CE       CMP   ($CE,X)
1793-   C4 20       CPY   $20
1795-   C4 C5       CPY   $C5
1797-   D3          ???
1798-   D4          ???
1799-   C9 CE       CMP   #$CE
179B-   C1 D4       CMP   ($D4,X)
179D-   C9 CF       CMP   #$CF
179F-   CE 20 C6    DEC   $C620
17A2-   C9 CC       CMP   #$CC
17A4-   C5 D3       CMP   $D3
17A6-   8D AA 8D    STA   $8DAA
17A9-   A0 D3       LDY   #$D3
17AB-   C3          ???
17AC-   C1 D4       CMP   ($D4,X)
17AE-   A0 A2       LDY   #$A2
17B0-   CF          ???
17B1-   D0 C5       BNE   $1778
17B3-   CE 20 A2    DEC   $A220
17B6-   BB          ???
17B7-   A3          ???
17B8-   D3          ???
17B9-   CE C1 CD    DEC   $CDC1
17BC-   C5 BB       CMP   $BB
17BE-   A3          ???
17BF-   B8          CLV
17C0-   B0 8D       BCS   $174F
17C2-   A0 C3       LDY   #$C3
17C4-   CD C4 A0    CMP   $A0C4
17C7-   A3          ???
17C8-   D2 C5       CMP   ($C5)
17CA-   D4          ???
17CB-   D5 D2       CMP   $D2,X
17CD-   CE 8D A0    DEC   $A08D
17D0-   D3          ???
17D1-   C3          ???
17D2-   C1 D4       CMP   ($D4,X)
17D4-   A0 A2       LDY   #$A2
17D6-   CF          ???
17D7-   D0 C5       BNE   $179E
17D9-   CE 20 A2    DEC   $A220
17DC-   BB          ???
17DD-   A3          ???
17DE-   C4 CE       CPY   $CE
17E0-   C1 CD       CMP   ($CD,X)
17E2-   C5 BB       CMP   $BB
17E4-   A3          ???
17E5-   B8          CLV
17E6-   B0 8D       BCS   $1775
17E8-   A0 C3       LDY   #$C3
17EA-   CD C4 A0    CMP   $A0C4
17ED-   A3          ???
17EE-   D2 C5       CMP   ($C5)
17F0-   D4          ???
17F1-   D5 D2       CMP   $D2,X
17F3-   CE 8D A0    DEC   $A08D
17F6-   D2 D4       CMP   ($D4)
17F8-   D3          ???
17F9-   8D AA 8D    STA   $8DAA
17FC-   AA          TAX
17FD-   AA          TAX
17FE-   AA          TAX
17FF-   AA          TAX
1800-   AA          TAX
1801-   AA          TAX
1802-   AA          TAX
1803-   AA          TAX
1804-   AA          TAX
1805-   AA          TAX
1806-   AA          TAX
1807-   AA          TAX
1808-   AA          TAX
1809-   AA          TAX
180A-   AA          TAX
180B-   AA          TAX
180C-   AA          TAX
180D-   AA          TAX
180E-   AA          TAX
180F-   AA          TAX
1810-   AA          TAX
1811-   AA          TAX
1812-   AA          TAX
1813-   AA          TAX
1814-   AA          TAX
1815-   AA          TAX
1816-   AA          TAX
1817-   AA          TAX
1818-   AA          TAX
1819-   AA          TAX
181A-   AA          TAX
181B-   AA          TAX
181C-   8D AA 20    STA   $20AA
181F-   20 20 20    JSR   $2020
1822-   20 20 20    JSR   $2020
1825-   20 20 20    JSR   $2020
1828-   20 20 20    JSR   $2020
182B-   20 20 20    JSR   $2020
182E-   20 20 20    JSR   $2020
1831-   20 20 20    JSR   $2020
1834-   20 20 20    JSR   $2020
1837-   20 20 20    JSR   $2020
183A-   20 20 AA    JSR   $AA20
183D-   8D AA 20    STA   $20AA
1840-   D2 C5       CMP   ($C5)
1842-   C1 C4       CMP   ($C4,X)
1844-   D3          ???
1845-   D2 C3       CMP   ($C3)
1847-   20 20 20    JSR   $2020
184A-   20 20 20    JSR   $2020
184D-   20 20 20    JSR   $2020
1850-   20 20 20    JSR   $2020
1853-   20 20 20    JSR   $2020
1856-   20 20 20    JSR   $2020
1859-   20 20 20    JSR   $2020
185C-   20 AA 8D    JSR   $8DAA
185F-   AA          TAX
1860-   20 20 20    JSR   $2020
1863-   20 20 20    JSR   $2020
1866-   20 20 20    JSR   $2020
1869-   20 20 20    JSR   $2020
186C-   20 20 20    JSR   $2020
186F-   20 20 20    JSR   $2020
1872-   20 20 20    JSR   $2020
1875-   20 20 20    JSR   $2020
1878-   20 20 20    JSR   $2020
187B-   20 20 20    JSR   $2020
187E-   AA          TAX
187F-   8D AA AA    STA   $AAAA
1882-   AA          TAX
1883-   AA          TAX
1884-   AA          TAX
1885-   AA          TAX
1886-   AA          TAX
1887-   AA          TAX
1888-   AA          TAX
1889-   AA          TAX
188A-   AA          TAX
188B-   AA          TAX
188C-   AA          TAX
188D-   AA          TAX
188E-   AA          TAX
188F-   AA          TAX
1890-   AA          TAX
1891-   AA          TAX
1892-   AA          TAX
1893-   AA          TAX
1894-   AA          TAX
1895-   AA          TAX
1896-   AA          TAX
1897-   AA          TAX
1898-   AA          TAX
1899-   AA          TAX
189A-   AA          TAX
189B-   AA          TAX
189C-   AA          TAX
189D-   AA          TAX
189E-   AA          TAX
189F-   AA          TAX
18A0-   8D AA 8D    STA   $8DAA
18A3-   D2 C5       CMP   ($C5)
18A5-   C1 C4       CMP   ($C4,X)
18A7-   D3          ???
18A8-   D2 C3       CMP   ($C3)
18AA-   8D AA 8D    STA   $8DAA
18AD-   AA          TAX
18AE-   AA          TAX
18AF-   20 C3 CC    JSR   $CCC3
18B2-   C5 C1       CMP   $C1
18B4-   D2 20       CMP   ($20)
18B6-   C2          ???
18B7-   D5 C6       CMP   $C6,X
18B9-   C6 C5       DEC   $C5
18BB-   D2 20       CMP   ($20)
18BD-   D0 CF       BNE   $188E
18BF-   C9 CE       CMP   #$CE
18C1-   D4          ???
18C2-   C5 D2       CMP   $D2
18C4-   AC 20 D3    LDY   $D320
18C7-   C5 D4       CMP   $D4
18C9-   20 D4 CF    JSR   $CFD4
18CC-   20 D2 C5    JSR   $C5D2
18CF-   C1 C4       CMP   ($C4,X)
18D1-   20 D3 CF    JSR   $CFD3
18D4-   D5 D2       CMP   $D2,X
18D6-   C3          ???
18D7-   C5 8D       CMP   $8D
18D9-   AA          TAX
18DA-   8D A0 CC    STA   $CCA0
18DD-   C4 C1       CPY   $C1
18DF-   A0 A3       LDY   #$A3
18E1-   B1 8D       LDA   ($8D),Y
18E3-   A0 D3       LDY   #$D3
18E5-   D4          ???
18E6-   C1 A0       CMP   ($A0,X)
18E8-   C3          ???
18E9-   C3          ???
18EA-   CE D4 8D    DEC   $8DD4
18ED-   A0 D3       LDY   #$D3
18EF-   C3          ???
18F0-   C1 D4       CMP   ($D4,X)
18F2-   A0 A2       LDY   #$A2
18F4-   D2 C5       CMP   ($C5)
18F6-   C1 C4       CMP   ($C4,X)
18F8-   20 A2 BB    JSR   $BBA2
18FB-   A3          ???
18FC-   D3          ???
18FD-   CE C1 CD    DEC   $CDC1
1900-   C5 BB       CMP   $BB
1902-   A3          ???
1903-   B8          CLV
1904-   B0 8D       BCS   $1893
1906-   A0 C3       LDY   #$C3
1908-   CD C4 A0    CMP   $A0C4
190B-   A3          ???
190C-   D2 C5       CMP   ($C5)
190E-   D4          ???
190F-   D5 D2       CMP   $D2,X
1911-   CE 8D BA    DEC   $BA8D
1914-   CC D0 8D    CPY   $8DD0
1917-   A0 C7       LDY   #$C7
1919-   CB          ???
191A-   C5 D9       CMP   $D9
191C-   A0 BB       LDY   #$BB
191E-   20 C1 D3    JSR   $D3C1
1921-   C3          ???
1922-   C9 C9       CMP   #$C9
1924-   20 C3 C8    JSR   $C8C3
1927-   C1 D2       CMP   ($D2,X)
1929-   20 D3 D4    JSR   $D4D3
192C-   CF          ???
192D-   D2 C5       CMP   ($C5)
192F-   C4 20       CPY   $20
1931-   C9 CE       CMP   #$CE
1933-   20 AE C1    JSR   $C1AE
1936-   8D A0 CC    STA   $CCA0
1939-   C4 D9       CPY   $D9
193B-   A0 C3       LDY   #$C3
193D-   C3          ???
193E-   CE D4 8D    DEC   $8DD4
1941-   A0 D3       LDY   #$D3
1943-   D4          ???
1944-   C1 A0       CMP   ($A0,X)
1946-   CC C9 CE    CPY   $CEC9
1949-   C5 AC       CMP   $AC
194B-   D9 8D A0    CMP   $A08D,Y
194E-   C3          ???
194F-   CD D0 A0    CMP   $A0D0
1952-   A3          ???
1953-   A4 B8       LDY   $B8
1955-   C4 A0       CPY   $A0
1957-   BB          ???
1958-   20 C9 D3    JSR   $D3C9
195B-   20 D4 C8    JSR   $C8D4
195E-   C9 D3       CMP   #$D3
1960-   20 C1 20    JSR   $20C1
1963-   C3          ???
1964-   C1 D2       CMP   ($D2,X)
1966-   D2 C9       CMP   ($C9)
1968-   C1 C7       CMP   ($C7,X)
196A-   C5 20       CMP   $20
196C-   D2 C5       CMP   ($C5)
196E-   D4          ???
196F-   D5 D2       CMP   $D2,X
1971-   CE BF 8D    DEC   $8DBF
1974-   A0 C2       LDY   #$C2
1976-   C5 D1       CMP   $D1
1978-   A0 BA       LDY   #$BA
197A-   D8          CLD
197B-   CC D0 A0    CPY   $A0D0
197E-   BB          ???
197F-   20 D9 C5    JSR   $C5D9
1982-   D3          ???
1983-   AC 20 C5    LDY   $C520
1986-   D8          CLD
1987-   C9 D4       CMP   #$D4
1989-   20 CC CF    JSR   $CFCC
198C-   CF          ???
198D-   D0 8D       BNE   $191C
198F-   A0 C9       LDY   #$C9
1991-   CE C3 A0    DEC   $A0C3
1994-   C3          ???
1995-   C3          ???
1996-   CE D4 A0    DEC   $A0D4
1999-   BB          ???
199A-   20 C9 CE    JSR   $CEC9
199D-   C3          ???
199E-   D2 C5       CMP   ($C5)
19A0-   C1 D3       CMP   ($D3,X)
19A2-   C5 20       CMP   $20
19A4-   C2          ???
19A5-   D5 C6       CMP   $C6,X
19A7-   C6 C5       DEC   $C5
19A9-   D2 20       CMP   ($20)
19AB-   D0 CF       BNE   $197C
19AD-   C9 CE       CMP   #$CE
19AF-   D4          ???
19B0-   C5 D2       CMP   $D2
19B2-   8D A0 CA    STA   $CAA0
19B5-   CD D0 A0    CMP   $A0D0
19B8-   BA          TSX
19B9-   CC D0 A0    CPY   $A0D0
19BC-   BB          ???
19BD-   20 CB C5    JSR   $C5CB
19C0-   C5 D0       CMP   $D0
19C2-   20 CF CE    JSR   $CECF
19C5-   20 D2 C5    JSR   $C5D2
19C8-   C1 C4       CMP   ($C4,X)
19CA-   C9 CE       CMP   #$CE
19CC-   C7          ???
19CD-   8D BA D8    STA   $D8BA
19D0-   CC D0 8D    CPY   $8DD0
19D3-   A0 CC       LDY   #$CC
19D5-   C4 C1       CPY   $C1
19D7-   A0 C3       LDY   #$C3
19D9-   C3          ???
19DA-   CE D4 8D    DEC   $8DD4
19DD-   A0 D3       LDY   #$D3
19DF-   D4          ???
19E0-   C1 A0       CMP   ($A0,X)
19E2-   CC C9 CE    CPY   $CEC9
19E5-   C5 8D       CMP   $8D
19E7-   A0 D2       LDY   #$D2
19E9-   D4          ???
19EA-   D3          ???
19EB-   8D AA 8D    STA   $8DAA
19EE-   AA          TAX
19EF-   AA          TAX
19F0-   AA          TAX
19F1-   AA          TAX
19F2-   AA          TAX
19F3-   AA          TAX
19F4-   AA          TAX
19F5-   AA          TAX
19F6-   AA          TAX
19F7-   AA          TAX
19F8-   AA          TAX
19F9-   AA          TAX
19FA-   AA          TAX
19FB-   AA          TAX
19FC-   AA          TAX
19FD-   AA          TAX
19FE-   AA          TAX
19FF-   AA          TAX
1A00-   AA          TAX
1A01-   AA          TAX
1A02-   AA          TAX
1A03-   AA          TAX
1A04-   AA          TAX
1A05-   AA          TAX
1A06-   AA          TAX
1A07-   AA          TAX
1A08-   AA          TAX
1A09-   AA          TAX
1A0A-   AA          TAX
1A0B-   AA          TAX
1A0C-   AA          TAX
1A0D-   AA          TAX
1A0E-   8D AA 20    STA   $20AA
1A11-   20 20 20    JSR   $2020
1A14-   20 20 20    JSR   $2020
1A17-   20 20 20    JSR   $2020
1A1A-   20 20 20    JSR   $2020
1A1D-   20 20 20    JSR   $2020
1A20-   20 20 20    JSR   $2020
1A23-   20 20 20    JSR   $2020
1A26-   20 20 20    JSR   $2020
1A29-   20 20 20    JSR   $2020
1A2C-   20 20 AA    JSR   $AA20
1A2F-   8D AA 20    STA   $20AA
1A32-   C3          ???
1A33-   C8          INY
1A34-   CB          ???
1A35-   C3          ???
1A36-   CF          ???
1A37-   CD CD C5    CMP   $C5CD
1A3A-   CE D4 20    DEC   $20D4
1A3D-   20 20 20    JSR   $2020
1A40-   20 20 20    JSR   $2020
1A43-   20 20 20    JSR   $2020
1A46-   20 20 20    JSR   $2020
1A49-   20 20 20    JSR   $2020
1A4C-   20 20 20    JSR   $2020
1A4F-   AA          TAX
1A50-   8D AA 20    STA   $20AA
1A53-   20 20 20    JSR   $2020
1A56-   20 20 20    JSR   $2020
1A59-   20 20 20    JSR   $2020
1A5C-   20 20 20    JSR   $2020
1A5F-   20 20 20    JSR   $2020
1A62-   20 20 20    JSR   $2020
1A65-   20 20 20    JSR   $2020
1A68-   20 20 20    JSR   $2020
1A6B-   20 20 20    JSR   $2020
1A6E-   20 20 AA    JSR   $AA20
1A71-   8D AA AA    STA   $AAAA
1A74-   AA          TAX
1A75-   AA          TAX
1A76-   AA          TAX
1A77-   AA          TAX
1A78-   AA          TAX
1A79-   AA          TAX
1A7A-   AA          TAX
1A7B-   AA          TAX
1A7C-   AA          TAX
1A7D-   AA          TAX
1A7E-   AA          TAX
1A7F-   AA          TAX
1A80-   AA          TAX
1A81-   AA          TAX
1A82-   AA          TAX
1A83-   AA          TAX
1A84-   AA          TAX
1A85-   AA          TAX
1A86-   AA          TAX
1A87-   AA          TAX
1A88-   AA          TAX
1A89-   AA          TAX
1A8A-   AA          TAX
1A8B-   AA          TAX
1A8C-   AA          TAX
1A8D-   AA          TAX
1A8E-   AA          TAX
1A8F-   AA          TAX
1A90-   AA          TAX
1A91-   AA          TAX
1A92-   8D AA 8D    STA   $8DAA
1A95-   C3          ???
1A96-   C8          INY
1A97-   CB          ???
1A98-   C3          ???
1A99-   CF          ???
1A9A-   CD CD C5    CMP   $C5CD
1A9D-   CE D4 8D    DEC   $8DD4
1AA0-   AA          TAX
1AA1-   8D AA AA    STA   $AAAA
1AA4-   20 CE CF    JSR   $CFCE
1AA7-   D7          ???
1AA8-   20 C3 C8    JSR   $C8C3
1AAB-   C5 C3       CMP   $C3
1AAD-   CB          ???
1AAE-   20 C9 C6    JSR   $C6C9
1AB1-   20 CC C9    JSR   $C9CC
1AB4-   CE C5 20    DEC   $20C5
1AB7-   C2          ???
1AB8-   C5 C7       CMP   $C7
1ABA-   C9 CE       CMP   #$CE
1ABC-   D3          ???
1ABD-   20 D7 C9    JSR   $C9D7
1AC0-   D4          ???
1AC1-   C8          INY
1AC2-   20 AA 8D    JSR   $8DAA
1AC5-   AA          TAX
1AC6-   8D A0 CC    STA   $CCA0
1AC9-   C4 C1       CPY   $C1
1ACB-   A0 CC       LDY   #$CC
1ACD-   C9 CE       CMP   #$CE
1ACF-   C5 AB       CMP   $AB
1AD1-   B1 8D       LDA   ($8D),Y
1AD3-   A0 C3       LDY   #$C3
1AD5-   CD D0 A0    CMP   $A0D0
1AD8-   A3          ???
1AD9-   B1 B7       LDA   ($B7),Y
1ADB-   B0 A0       BCS   $1A7D
1ADD-   BB          ???
1ADE-   20 AA 20    JSR   $20AA
1AE1-   C3          ???
1AE2-   C8          INY
1AE3-   C1 D2       CMP   ($D2,X)
1AE5-   C1 C3       CMP   ($C3,X)
1AE7-   D4          ???
1AE8-   C5 D2       CMP   $D2
1AEA-   8D A0 C2    STA   $C2A0
1AED-   CE C5 A0    DEC   $A0C5
1AF0-   BA          TSX
1AF1-   D3          ???
1AF2-   C5 CD       CMP   $CD
1AF4-   C9 D4       CMP   #$D4
1AF6-   C5 D3       CMP   $D3
1AF8-   D4          ???
1AF9-   8D A0 CC    STA   $CCA0
1AFC-   C4 C1       CPY   $C1
1AFE-   A0 A3       LDY   #$A3
1B00-   A4 C6       LDY   $C6
1B02-   C6 8D       DEC   $8D
1B04-   A0 D3       LDY   #$D3
1B06-   D4          ???
1B07-   C1 A0       CMP   ($A0,X)
1B09-   D7          ???
1B0A-   D2 C9       CMP   ($C9)
1B0C-   D4          ???
1B0D-   C5 CF       CMP   $CF
1B0F-   C6 C6       DEC   $C6
1B11-   8D AA 8D    STA   $8DAA
1B14-   BA          TSX
1B15-   D3          ???
1B16-   C5 CD       CMP   $CD
1B18-   C9 D4       CMP   #$D4
1B1A-   C5 D3       CMP   $D3
1B1C-   D4          ???
1B1D-   8D AA 8D    STA   $8DAA
1B20-   AA          TAX
1B21-   AA          TAX
1B22-   20 CE CF    JSR   $CFCE
1B25-   D7          ???
1B26-   20 D4 C5    JSR   $C5D4
1B29-   D3          ???
1B2A-   D4          ???
1B2B-   20 C6 CF    JSR   $CFC6
1B2E-   D2 20       CMP   ($20)
1B30-   D3          ???
1B31-   D5 C2       CMP   $C2,X
1B33-   D3          ???
1B34-   D4          ???
1B35-   D2 C9       CMP   ($C9)
1B37-   CE C7 20    DEC   $20C7
1B3A-   A2 20       LDX   #$20
1B3C-   BB          ???
1B3D-   20 A2 8D    JSR   $8DA2
1B40-   AA          TAX
1B41-   8D A0 CC    STA   $CCA0
1B44-   C4 C1       CPY   $C1
1B46-   A0 CC       LDY   #$CC
1B48-   C9 CE       CMP   #$CE
1B4A-   C5 A0       CMP   $A0
1B4C-   BB          ???
1B4D-   20 D3 D4    JSR   $D4D3
1B50-   C1 D2       CMP   ($D2,X)
1B52-   D4          ???
1B53-   20 C1 D4    JSR   $D4C1
1B56-   20 C5 CE    JSR   $CEC5
1B59-   C4 20       CPY   $20
1B5B-   CF          ???
1B5C-   C6 20       DEC   $20
1B5E-   D3          ???
1B5F-   D4          ???
1B60-   D2 C9       CMP   ($C9)
1B62-   CE C7 8D    DEC   $8DC7
1B65-   A0 D3       LDY   #$D3
1B67-   D4          ???
1B68-   C1 A0       CMP   ($A0,X)
1B6A-   C3          ???
1B6B-   C3          ???
1B6C-   CE D4 8D    DEC   $8DD4
1B6F-   A0 C4       LDY   #$C4
1B71-   C5 C3       CMP   $C3
1B73-   A0 C3       LDY   #$C3
1B75-   C3          ???
1B76-   CE D4 8D    DEC   $8DD4
1B79-   AA          TAX
1B7A-   8D BA D3    STA   $D3BA
1B7D-   C5 CD       CMP   $CD
1B7F-   C9 CC       CMP   #$CC
1B81-   D0 8D       BNE   $1B10
1B83-   A0 CC       LDY   #$CC
1B85-   C4 D9       CPY   $D9
1B87-   A0 C3       LDY   #$C3
1B89-   C3          ???
1B8A-   CE D4 8D    DEC   $8DD4
1B8D-   A0 CC       LDY   #$CC
1B8F-   C4 C1       CPY   $C1
1B91-   A0 CC       LDY   #$CC
1B93-   C9 CE       CMP   #$CE
1B95-   C5 AC       CMP   $AC
1B97-   D9 8D A0    CMP   $A08D,Y
1B9A-   C3          ???
1B9B-   CD D0 A0    CMP   $A0D0
1B9E-   A3          ???
1B9F-   A4 C2       LDY   $C2
1BA1-   C2          ???
1BA2-   A0 BB       LDY   #$BB
1BA4-   20 A2 BB    JSR   $BBA2
1BA7-   A2 20       LDX   #$20
1BA9-   C3          ???
1BAA-   C8          INY
1BAB-   C1 D2       CMP   ($D2,X)
1BAD-   C1 C3       CMP   ($C3,X)
1BAF-   D4          ???
1BB0-   C5 D2       CMP   $D2
1BB2-   8D A0 C2    STA   $C2A0
1BB5-   C5 D1       CMP   $D1
1BB7-   A0 BA       LDY   #$BA
1BB9-   D3          ???
1BBA-   C5 CD       CMP   $CD
1BBC-   C9 C6       CMP   #$C6
1BBE-   8D A0 C3    STA   $C3A0
1BC1-   D0 D9       BNE   $1B9C
1BC3-   A0 A3       LDY   #$A3
1BC5-   B0 8D       BCS   $1B54
1BC7-   A0 C2       LDY   #$C2
1BC9-   C5 D1       CMP   $D1
1BCB-   A0 BA       LDY   #$BA
1BCD-   D8          CLD
1BCE-   D3          ???
1BCF-   C5 CD       CMP   $CD
1BD1-   C9 CC       CMP   #$CC
1BD3-   D0 8D       BNE   $1B62
1BD5-   A0 C4       LDY   #$C4
1BD7-   C5 C3       CMP   $C3
1BD9-   A0 C3       LDY   #$C3
1BDB-   C3          ???
1BDC-   CE D4 8D    DEC   $8DD4
1BDF-   A0 CA       LDY   #$CA
1BE1-   CD D0 A0    CMP   $A0D0
1BE4-   BA          TSX
1BE5-   D3          ???
1BE6-   C5 CD       CMP   $CD
1BE8-   C9 CC       CMP   #$CC
1BEA-   D0 8D       BNE   $1B79
1BEC-   AA          TAX
1BED-   8D BA D3    STA   $D3BA
1BF0-   C5 CD       CMP   $CD
1BF2-   C9 C6       CMP   #$C6
1BF4-   8D A0 CC    STA   $CCA0
1BF7-   C4 D9       CPY   $D9
1BF9-   A0 C3       LDY   #$C3
1BFB-   C3          ???
1BFC-   CE D4 8D    DEC   $8DD4
1BFF-   A0 C9       LDY   #$C9
1C01-   CE D9 8D    DEC   $8DD9
1C04-   A0 CC       LDY   #$CC
1C06-   C4 C1       CPY   $C1
1C08-   A0 CC       LDY   #$CC
1C0A-   C9 CE       CMP   #$CE
1C0C-   C5 AC       CMP   $AC
1C0E-   D9 8D A0    CMP   $A08D,Y
1C11-   C3          ???
1C12-   CD D0 A0    CMP   $A0D0
1C15-   A3          ???
1C16-   A4 B2       LDY   $B2
1C18-   B0 A0       BCS   $1BBA
1C1A-   BB          ???
1C1B-   20 C9 D3    JSR   $D3C9
1C1E-   20 CE C5    JSR   $C5CE
1C21-   D8          CLD
1C22-   D4          ???
1C23-   20 C3 C8    JSR   $C8C3
1C26-   C1 D2       CMP   ($D2,X)
1C28-   20 C1 20    JSR   $20C1
1C2B-   D3          ???
1C2C-   D0 C1       BNE   $1BEF
1C2E-   C3          ???
1C2F-   C5 BF       CMP   $BF
1C31-   8D A0 C2    STA   $C2A0
1C34-   CE C5 A0    DEC   $A0C5
1C37-   BA          TSX
1C38-   D8          CLD
1C39-   D3          ???
1C3A-   C5 CD       CMP   $CD
1C3C-   C9 CC       CMP   #$CC
1C3E-   D0 8D       BNE   $1BCD
1C40-   A0 CC       LDY   #$CC
1C42-   C4 C1       CPY   $C1
1C44-   A0 A3       LDY   #$A3
1C46-   A4 B8       LDY   $B8
1C48-   C4 8D       CPY   $8D
1C4A-   A0 CC       LDY   #$CC
1C4C-   C4 D9       CPY   $D9
1C4E-   A0 C3       LDY   #$C3
1C50-   C3          ???
1C51-   CE D4 8D    DEC   $8DD4
1C54-   A0 D3       LDY   #$D3
1C56-   D4          ???
1C57-   C1 A0       CMP   ($A0,X)
1C59-   CC C9 CE    CPY   $CEC9
1C5C-   C5 AC       CMP   $AC
1C5E-   D9 8D BA    CMP   $BA8D,Y
1C61-   D8          CLD
1C62-   D3          ???
1C63-   C5 CD       CMP   $CD
1C65-   C9 CC       CMP   #$CC
1C67-   D0 8D       BNE   $1BF6
1C69-   A0 D2       LDY   #$D2
1C6B-   D4          ???
1C6C-   D3          ???
1C6D-   8D AA 8D    STA   $8DAA
1C70-   AA          TAX
1C71-   AA          TAX
1C72-   AA          TAX
1C73-   AA          TAX
1C74-   AA          TAX
1C75-   AA          TAX
1C76-   AA          TAX
1C77-   AA          TAX
1C78-   AA          TAX
1C79-   AA          TAX
1C7A-   AA          TAX
1C7B-   AA          TAX
1C7C-   AA          TAX
1C7D-   AA          TAX
1C7E-   AA          TAX
1C7F-   AA          TAX
1C80-   AA          TAX
1C81-   AA          TAX
1C82-   AA          TAX
1C83-   AA          TAX
1C84-   AA          TAX
1C85-   AA          TAX
1C86-   AA          TAX
1C87-   AA          TAX
1C88-   AA          TAX
1C89-   AA          TAX
1C8A-   AA          TAX
1C8B-   AA          TAX
1C8C-   AA          TAX
1C8D-   AA          TAX
1C8E-   AA          TAX
1C8F-   AA          TAX
1C90-   8D AA 20    STA   $20AA
1C93-   20 20 20    JSR   $2020
1C96-   20 20 20    JSR   $2020
1C99-   20 20 20    JSR   $2020
1C9C-   20 20 20    JSR   $2020
1C9F-   20 20 20    JSR   $2020
1CA2-   20 20 20    JSR   $2020
1CA5-   20 20 20    JSR   $2020
1CA8-   20 20 20    JSR   $2020
1CAB-   20 20 20    JSR   $2020
1CAE-   20 20 AA    JSR   $AA20
1CB1-   8D AA 20    STA   $20AA
1CB4-   D7          ???
1CB5-   D2 C9       CMP   ($C9)
1CB7-   D4          ???
1CB8-   C5 C4       CMP   $C4
1CBA-   C5 D3       CMP   $D3
1CBC-   D4          ???
1CBD-   20 20 20    JSR   $2020
1CC0-   20 20 20    JSR   $2020
1CC3-   20 20 20    JSR   $2020
1CC6-   20 20 20    JSR   $2020
1CC9-   20 20 20    JSR   $2020
1CCC-   20 20 20    JSR   $2020
1CCF-   20 20 AA    JSR   $AA20
1CD2-   8D AA 20    STA   $20AA
1CD5-   20 20 20    JSR   $2020
1CD8-   20 20 20    JSR   $2020
1CDB-   20 20 20    JSR   $2020
1CDE-   20 20 20    JSR   $2020
1CE1-   20 20 20    JSR   $2020
1CE4-   20 20 20    JSR   $2020
1CE7-   20 20 20    JSR   $2020
1CEA-   20 20 20    JSR   $2020
1CED-   20 20 20    JSR   $2020
1CF0-   20 20 AA    JSR   $AA20
1CF3-   8D AA AA    STA   $AAAA
1CF6-   AA          TAX
1CF7-   AA          TAX
1CF8-   AA          TAX
1CF9-   AA          TAX
1CFA-   AA          TAX
1CFB-   AA          TAX
1CFC-   AA          TAX
1CFD-   AA          TAX
1CFE-   AA          TAX
1CFF-   AA          TAX
1D00-   AA          TAX
1D01-   AA          TAX
1D02-   AA          TAX
1D03-   AA          TAX
1D04-   AA          TAX
1D05-   AA          TAX
1D06-   AA          TAX
1D07-   AA          TAX
1D08-   AA          TAX
1D09-   AA          TAX
1D0A-   AA          TAX
1D0B-   AA          TAX
1D0C-   AA          TAX
1D0D-   AA          TAX
1D0E-   AA          TAX
1D0F-   AA          TAX
1D10-   AA          TAX
1D11-   AA          TAX
1D12-   AA          TAX
1D13-   AA          TAX
1D14-   8D AA 8D    STA   $8DAA
1D17-   D7          ???
1D18-   D2 C9       CMP   ($C9)
1D1A-   D4          ???
1D1B-   C5 C4       CMP   $C4
1D1D-   C5 D3       CMP   $D3
1D1F-   D4          ???
1D20-   8D AA 8D    STA   $8DAA
1D23-   A0 CC       LDY   #$CC
1D25-   C4 C1       CPY   $C1
1D27-   A0 D7       LDY   #$D7
1D29-   D2 C9       CMP   ($C9)
1D2B-   D4          ???
1D2C-   C5 CF       CMP   $CF
1D2E-   C6 C6       DEC   $C6
1D30-   8D A0 C3    STA   $C3A0
1D33-   CD D0 A0    CMP   $A0D0
1D36-   A3          ???
1D37-   A4 C6       LDY   $C6
1D39-   C6 8D       DEC   $8D
1D3B-   A0 C2       LDY   #$C2
1D3D-   C5 D1       CMP   $D1
1D3F-   A0 BA       LDY   #$BA
1D41-   D8          CLD
1D42-   D7          ???
1D43-   CC D0 8D    CPY   $8DD0
1D46-   AA          TAX
1D47-   8D AA AA    STA   $AAAA
1D4A-   20 C3 CC    JSR   $CCC3
1D4D-   C5 C1       CMP   $C1
1D4F-   D2 20       CMP   ($20)
1D51-   C3          ???
1D52-   CF          ???
1D53-   D5 CE       CMP   $CE,X
1D55-   D4          ???
1D56-   C5 D2       CMP   $D2
1D58-   AC 20 D3    LDY   $D320
1D5B-   C5 D4       CMP   $D4
1D5D-   20 D4 CF    JSR   $CFD4
1D60-   20 D7 D2    JSR   $D2D7
1D63-   C9 D4       CMP   #$D4
1D65-   C5 20       CMP   $20
1D67-   C4 C5       CPY   $C5
1D69-   D3          ???
1D6A-   D4          ???
1D6B-   8D AA 8D    STA   $8DAA
1D6E-   A0 CC       LDY   #$CC
1D70-   C4 C1       CPY   $C1
1D72-   A0 A3       LDY   #$A3
1D74-   B1 8D       LDA   ($8D),Y
1D76-   A0 D3       LDY   #$D3
1D78-   D4          ???
1D79-   C1 A0       CMP   ($A0,X)
1D7B-   C3          ???
1D7C-   C3          ???
1D7D-   CE D4 8D    DEC   $8DD4
1D80-   A0 D3       LDY   #$D3
1D82-   C3          ???
1D83-   C1 D4       CMP   ($D4,X)
1D85-   A0 A2       LDY   #$A2
1D87-   D7          ???
1D88-   D2 C9       CMP   ($C9)
1D8A-   D4          ???
1D8B-   C5 20       CMP   $20
1D8D-   A2 BB       LDX   #$BB
1D8F-   A3          ???
1D90-   C4 CE       CPY   $CE
1D92-   C1 CD       CMP   ($CD,X)
1D94-   C5 BB       CMP   $BB
1D96-   A3          ???
1D97-   B8          CLV
1D98-   B0 8D       BCS   $1D27
1D9A-   A0 C3       LDY   #$C3
1D9C-   CD C4 A0    CMP   $A0C4
1D9F-   A3          ???
1DA0-   D2 C5       CMP   ($C5)
1DA2-   D4          ???
1DA3-   D5 D2       CMP   $D2,X
1DA5-   CE 8D AA    DEC   $AA8D
1DA8-   8D BA D7    STA   $D7BA
1DAB-   CC D0 A0    CPY   $A0D0
1DAE-   BB          ???
1DAF-   20 D7 D2    JSR   $D2D7
1DB2-   C9 D4       CMP   #$D4
1DB4-   C5 20       CMP   $20
1DB6-   CC CF CF    CPY   $CFCF
1DB9-   D0 8D       BNE   $1D48
1DBB-   A0 CC       LDY   #$CC
1DBD-   C4 D9       CPY   $D9
1DBF-   A0 C3       LDY   #$C3
1DC1-   C3          ???
1DC2-   CE D4 8D    DEC   $8DD4
1DC5-   A0 CC       LDY   #$CC
1DC7-   C4 C1       CPY   $C1
1DC9-   A0 CC       LDY   #$CC
1DCB-   C9 CE       CMP   #$CE
1DCD-   C5 AC       CMP   $AC
1DCF-   D9 8D A0    CMP   $A08D,Y
1DD2-   C3          ???
1DD3-   CD D0 A0    CMP   $A0D0
1DD6-   A3          ???
1DD7-   A4 B8       LDY   $B8
1DD9-   C4 A0       CPY   $A0
1DDB-   BB          ???
1DDC-   20 D7 C1    JSR   $C1D7
1DDF-   D3          ???
1DE0-   20 C9 D4    JSR   $D4C9
1DE3-   20 C1 20    JSR   $20C1
1DE6-   C3          ???
1DE7-   D2 BF       CMP   ($BF)
1DE9-   8D A0 C2    STA   $C2A0
1DEC-   C5 D1       CMP   $D1
1DEE-   A0 BA       LDY   #$BA
1DF0-   D8          CLD
1DF1-   D7          ???
1DF2-   CC D0 A0    CPY   $A0D0
1DF5-   BB          ???
1DF6-   20 D9 C5    JSR   $C5D9
1DF9-   D0 AC       BNE   $1DA7
1DFB-   20 C5 D8    JSR   $D8C5
1DFE-   C9 D4       CMP   #$D4
1E00-   20 CC CF    JSR   $CFCC
1E03-   CF          ???
1E04-   D0 8D       BNE   $1D93
1E06-   A0 CA       LDY   #$CA
1E08-   D3          ???
1E09-   D2 A0       CMP   ($A0)
1E0B-   C6 C3       DEC   $C3
1E0D-   CF          ???
1E0E-   D5 D4       CMP   $D4,X
1E10-   A0 BB       LDY   #$BB
1E12-   20 D0 D2    JSR   $D2D0
1E15-   C9 CE       CMP   #$CE
1E17-   D4          ???
1E18-   20 D4 CF    JSR   $CFD4
1E1B-   20 C6 C9    JSR   $C9C6
1E1E-   CC C5 8D    CPY   $8DC5
1E21-   A0 C9       LDY   #$C9
1E23-   CE C3 A0    DEC   $A0C3
1E26-   C3          ???
1E27-   C3          ???
1E28-   CE D4 8D    DEC   $8DD4
1E2B-   A0 CA       LDY   #$CA
1E2D-   CD D0 A0    CMP   $A0D0
1E30-   BA          TSX
1E31-   D7          ???
1E32-   CC D0 8D    CPY   $8DD0
1E35-   BA          TSX
1E36-   D8          CLD
1E37-   D7          ???
1E38-   CC D0 8D    CPY   $8DD0
1E3B-   A0 CC       LDY   #$CC
1E3D-   C4 C1       CPY   $C1
1E3F-   A0 A3       LDY   #$A3
1E41-   B0 B0       BCS   $1DF3
1E43-   8D A0 D3    STA   $D3A0
1E46-   D4          ???
1E47-   C1 A0       CMP   ($A0,X)
1E49-   D7          ???
1E4A-   D2 C9       CMP   ($C9)
1E4C-   D4          ???
1E4D-   C5 CF       CMP   $CF
1E4F-   C6 C6       DEC   $C6
1E51-   8D A0 D2    STA   $D2A0
1E54-   D4          ???
1E55-   D3          ???
1E56-   8D AA 8D    STA   $8DAA
1E59-   AA          TAX
1E5A-   AA          TAX
1E5B-   AA          TAX
1E5C-   AA          TAX
1E5D-   AA          TAX
1E5E-   AA          TAX
1E5F-   AA          TAX
1E60-   AA          TAX
1E61-   AA          TAX
1E62-   AA          TAX
1E63-   AA          TAX
1E64-   AA          TAX
1E65-   AA          TAX
1E66-   AA          TAX
1E67-   AA          TAX
1E68-   AA          TAX
1E69-   AA          TAX
1E6A-   AA          TAX
1E6B-   AA          TAX
1E6C-   AA          TAX
1E6D-   AA          TAX
1E6E-   AA          TAX
1E6F-   AA          TAX
1E70-   AA          TAX
1E71-   AA          TAX
1E72-   AA          TAX
1E73-   AA          TAX
1E74-   AA          TAX
1E75-   AA          TAX
1E76-   AA          TAX
1E77-   AA          TAX
1E78-   AA          TAX
1E79-   8D AA 20    STA   $20AA
1E7C-   20 20 20    JSR   $2020
1E7F-   20 20 20    JSR   $2020
1E82-   20 20 20    JSR   $2020
1E85-   20 20 20    JSR   $2020
1E88-   20 20 20    JSR   $2020
1E8B-   20 20 20    JSR   $2020
1E8E-   20 20 20    JSR   $2020
1E91-   20 20 20    JSR   $2020
1E94-   20 20 20    JSR   $2020
1E97-   20 20 AA    JSR   $AA20
1E9A-   8D AA 20    STA   $20AA
1E9D-   C6 C3       DEC   $C3
1E9F-   CC CF D3    CPY   $D3CF
1EA2-   C5 20       CMP   $20
1EA4-   20 20 20    JSR   $2020
1EA7-   20 20 20    JSR   $2020
1EAA-   20 20 20    JSR   $2020
1EAD-   20 20 20    JSR   $2020
1EB0-   20 20 20    JSR   $2020
1EB3-   20 20 20    JSR   $2020
1EB6-   20 20 20    JSR   $2020
1EB9-   20 AA 8D    JSR   $8DAA
1EBC-   AA          TAX
1EBD-   20 20 20    JSR   $2020
1EC0-   20 20 20    JSR   $2020
1EC3-   20 20 20    JSR   $2020
1EC6-   20 20 20    JSR   $2020
1EC9-   20 20 20    JSR   $2020
1ECC-   20 20 20    JSR   $2020
1ECF-   20 20 20    JSR   $2020
1ED2-   20 20 20    JSR   $2020
1ED5-   20 20 20    JSR   $2020
1ED8-   20 20 20    JSR   $2020
1EDB-   AA          TAX
1EDC-   8D AA AA    STA   $AAAA
1EDF-   AA          TAX
1EE0-   AA          TAX
1EE1-   AA          TAX
1EE2-   AA          TAX
1EE3-   AA          TAX
1EE4-   AA          TAX
1EE5-   AA          TAX
1EE6-   AA          TAX
1EE7-   AA          TAX
1EE8-   AA          TAX
1EE9-   AA          TAX
1EEA-   AA          TAX
1EEB-   AA          TAX
1EEC-   AA          TAX
1EED-   AA          TAX
1EEE-   AA          TAX
1EEF-   AA          TAX
1EF0-   AA          TAX
1EF1-   AA          TAX
1EF2-   AA          TAX
1EF3-   AA          TAX
1EF4-   AA          TAX
1EF5-   AA          TAX
1EF6-   AA          TAX
1EF7-   AA          TAX
1EF8-   AA          TAX
1EF9-   AA          TAX
1EFA-   AA          TAX
1EFB-   AA          TAX
1EFC-   AA          TAX
1EFD-   8D AA 8D    STA   $8DAA
1F00-   C6 C3       DEC   $C3
1F02-   CC CF D3    CPY   $D3CF
1F05-   C5 8D       CMP   $8D
1F07-   AA          TAX
1F08-   8D AA AA    STA   $AAAA
1F0B-   20 CE CF    JSR   $CFCE
1F0E-   D7          ???
1F0F-   20 C3 CC    JSR   $CCC3
1F12-   CF          ???
1F13-   D3          ???
1F14-   C5 20       CMP   $20
1F16-   D3          ???
1F17-   CF          ???
1F18-   D5 D2       CMP   $D2,X
1F1A-   C3          ???
1F1B-   C5 20       CMP   $20
1F1D-   C1 CE       CMP   ($CE,X)
1F1F-   C4 20       CPY   $20
1F21-   C4 C5       CPY   $C5
1F23-   D3          ???
1F24-   D4          ???
1F25-   C9 CE       CMP   #$CE
1F27-   C1 D4       CMP   ($D4,X)
1F29-   C9 CF       CMP   #$CF
1F2B-   CE 20 C6    DEC   $C620
1F2E-   C9 CC       CMP   #$CC
1F30-   C5 D3       CMP   $D3
1F32-   8D AA AA    STA   $AAAA
1F35-   20 C1 C6    JSR   $C6C1
1F38-   D4          ???
1F39-   C5 D2       CMP   $D2
1F3B-   20 C5 CE    JSR   $CEC5
1F3E-   C4 20       CPY   $20
1F40-   CF          ???
1F41-   C6 20       DEC   $20
1F43-   C6 C9       DEC   $C9
1F45-   CC C5 20    CPY   $20C5
1F48-   C5 D2       CMP   $D2
1F4A-   D2 CF       CMP   ($CF)
1F4C-   D2 8D       CMP   ($8D)
1F4E-   AA          TAX
1F4F-   8D A0 D3    STA   $D3A0
1F52-   C3          ???
1F53-   C1 D4       CMP   ($D4,X)
1F55-   A0 A2       LDY   #$A2
1F57-   C3          ???
1F58-   CC CF D3    CPY   $D3CF
1F5B-   C5 20       CMP   $20
1F5D-   A2 BB       LDX   #$BB
1F5F-   A3          ???
1F60-   D3          ???
1F61-   CE C1 CD    DEC   $CDC1
1F64-   C5 BB       CMP   $BB
1F66-   A3          ???
1F67-   B8          CLV
1F68-   B0 8D       BCS   $1EF7
1F6A-   A0 C3       LDY   #$C3
1F6C-   CD C4 A0    CMP   $A0C4
1F6F-   A3          ???
1F70-   D2 C5       CMP   ($C5)
1F72-   D4          ???
1F73-   D5 D2       CMP   $D2,X
1F75-   CE 8D AA    DEC   $AA8D
1F78-   8D A0 D3    STA   $D3A0
1F7B-   C3          ???
1F7C-   C1 D4       CMP   ($D4,X)
1F7E-   A0 A2       LDY   #$A2
1F80-   C3          ???
1F81-   CC CF D3    CPY   $D3CF
1F84-   C5 20       CMP   $20
1F86-   A2 BB       LDX   #$BB
1F88-   A3          ???
1F89-   C4 CE       CPY   $CE
1F8B-   C1 CD       CMP   ($CD,X)
1F8D-   C5 BB       CMP   $BB
1F8F-   A3          ???
1F90-   B8          CLV
1F91-   B0 8D       BCS   $1F20
1F93-   A0 C3       LDY   #$C3
1F95-   CD C4 A0    CMP   $A0C4
1F98-   A3          ???
1F99-   D2 C5       CMP   ($C5)
1F9B-   D4          ???
1F9C-   D5 D2       CMP   $D2,X
1F9E-   CE 8D AA    DEC   $AA8D
1FA1-   8D A0 D0    STA   $D0A0
1FA4-   D2 CE       CMP   ($CE)
1FA6-   A0 A2       LDY   #$A2
1FA8-   C4 CF       CPY   $CF
1FAA-   CE C5 A1    DEC   $A1C5
1FAD-   A2 AC       LDX   #$AC
1FAF-   B8          CLV
1FB0-   C4 B8       CPY   $B8
1FB2-   C4 8D       CPY   $8D
1FB4-   A0 D0       LDY   #$D0
1FB6-   D2 CE       CMP   ($CE)
1FB8-   A0 A2       LDY   #$A2
1FBA-   D7          ???
1FBB-   CF          ???
1FBC-   D5 CC       CMP   $CC,X
1FBE-   C4 20       CPY   $20
1FC0-   D9 CF D5    CMP   $D5CF,Y
1FC3-   20 CC C9    JSR   $C9CC
1FC6-   CB          ???
1FC7-   C5 20       CMP   $20
1FC9-   D4          ???
1FCA-   CF          ???
1FCB-   20 CD C9    JSR   $C9CD
1FCE-   CE C9 C6    DEC   $C6C9
1FD1-   D9 20 C1    CMP   $C120,Y
1FD4-   CE CF D4    DEC   $D4CF
1FD7-   C8          INY
1FD8-   C5 D2       CMP   $D2
1FDA-   BF          ???
1FDB-   20 A2 8D    JSR   $8DA2
1FDE-   A0 C9       LDY   #$C9
1FE0-   CE D0 8D    DEC   $8DD0
1FE3-   A0 CC       LDY   #$CC
1FE5-   C4 C1       CPY   $C1
1FE7-   A0 D2       LDY   #$D2
1FE9-   C5 D4       CMP   $D4
1FEB-   D5 D2       CMP   $D2,X
1FED-   CE AB B1    DEC   $B1AB
1FF0-   8D A0 C3    STA   $C3A0
1FF3-   CD D0 A0    CMP   $A0D0
1FF6-   A3          ???
1FF7-   B2 B1       LDA   ($B1)
1FF9-   B7          ???
1FFA-   A0 BB       LDY   #$BB
1FFC-   20 A7 D9    JSR   $D9A7
1FFF-   A7          ???
2000-   20 CC C5    JSR   $C5CC
2003-   D4          ???
2004-   D4          ???
2005-   C5 D2       CMP   $D2
2007-   8D A0 C2    STA   $C2A0
200A-   CE C5 A0    DEC   $A0C5
200D-   C6 C9       DEC   $C9
200F-   CE 8D A0    DEC   $A08D
2012-   D0 CC       BNE   $1FE0
2014-   C1 8D       CMP   ($8D,X)
2016-   A0 D0       LDY   #$D0
2018-   CC C1 8D    CPY   $8DC1
201B-   A0 D0       LDY   #$D0
201D-   CC C1 8D    CPY   $8DC1
2020-   A0 CA       LDY   #$CA
2022-   CD D0 A0    CMP   $A0D0
2025-   C2          ???
2026-   C5 C7       CMP   $C7
2028-   C9 CE       CMP   #$CE
202A-   8D C6 C9    STA   $C9C6
202D-   CE 8D AA    DEC   $AA8D
2030-   8D A0 D0    STA   $D0A0
2033-   CC C1 8D    CPY   $8DC1
2036-   A0 D0       LDY   #$D0
2038-   CC C1 8D    CPY   $8DC1
203B-   A0 CA       LDY   #$CA
203D-   CD D0 A0    CMP   $A0D0
2040-   D2 C5       CMP   ($C5)
2042-   C5 CE       CMP   $CE
2044-   D4          ???
2045-   D2 D9       CMP   ($D9)
2047-   8D AA 8D    STA   $8DAA
204A-   AA          TAX
204B-   AA          TAX
204C-   AA          TAX
204D-   AA          TAX
204E-   AA          TAX
204F-   AA          TAX
2050-   AA          TAX
2051-   AA          TAX
2052-   AA          TAX
2053-   AA          TAX
2054-   AA          TAX
2055-   AA          TAX
2056-   AA          TAX
2057-   AA          TAX
2058-   AA          TAX
2059-   AA          TAX
205A-   AA          TAX
205B-   AA          TAX
205C-   AA          TAX
205D-   AA          TAX
205E-   AA          TAX
205F-   AA          TAX
2060-   AA          TAX
2061-   AA          TAX
2062-   AA          TAX
2063-   AA          TAX
2064-   AA          TAX
2065-   AA          TAX
2066-   AA          TAX
2067-   AA          TAX
2068-   AA          TAX
2069-   AA          TAX
206A-   8D AA 20    STA   $20AA
206D-   20 20 20    JSR   $2020
2070-   20 20 20    JSR   $2020
2073-   20 20 20    JSR   $2020
2076-   20 20 20    JSR   $2020
2079-   20 20 20    JSR   $2020
207C-   20 20 20    JSR   $2020
207F-   20 20 20    JSR   $2020
2082-   20 20 20    JSR   $2020
2085-   20 20 20    JSR   $2020
2088-   20 20 AA    JSR   $AA20
208B-   8D AA 20    STA   $20AA
208E-   D6 C1       DEC   $C1,X
2090-   D2 C9       CMP   ($C9)
2092-   C1 C2       CMP   ($C2,X)
2094-   CC C5 D3    CPY   $D3C5
2097-   20 20 20    JSR   $2020
209A-   20 20 20    JSR   $2020
209D-   20 20 20    JSR   $2020
20A0-   20 20 20    JSR   $2020
20A3-   20 20 20    JSR   $2020
20A6-   20 20 20    JSR   $2020
20A9-   20 20 AA    JSR   $AA20
20AC-   8D AA 20    STA   $20AA
20AF-   20 20 20    JSR   $2020
20B2-   20 20 20    JSR   $2020
20B5-   20 20 20    JSR   $2020
20B8-   20 20 20    JSR   $2020
20BB-   20 20 20    JSR   $2020
20BE-   20 20 20    JSR   $2020
20C1-   20 20 20    JSR   $2020
20C4-   20 20 20    JSR   $2020
20C7-   20 20 20    JSR   $2020
20CA-   20 20 AA    JSR   $AA20
20CD-   8D AA AA    STA   $AAAA
20D0-   AA          TAX
20D1-   AA          TAX
20D2-   AA          TAX
20D3-   AA          TAX
20D4-   AA          TAX
20D5-   AA          TAX
20D6-   AA          TAX
20D7-   AA          TAX
20D8-   AA          TAX
20D9-   AA          TAX
20DA-   AA          TAX
20DB-   AA          TAX
20DC-   AA          TAX
20DD-   AA          TAX
20DE-   AA          TAX
20DF-   AA          TAX
20E0-   AA          TAX
20E1-   AA          TAX
20E2-   AA          TAX
20E3-   AA          TAX
20E4-   AA          TAX
20E5-   AA          TAX
20E6-   AA          TAX
20E7-   AA          TAX
20E8-   AA          TAX
20E9-   AA          TAX
20EA-   AA          TAX
20EB-   AA          TAX
20EC-   AA          TAX
20ED-   AA          TAX
20EE-   8D AA 8D    STA   $8DAA
20F1-   D3          ???
20F2-   CE C1 CD    DEC   $CDC1
20F5-   C5 A0       CMP   $A0
20F7-   C4 D3       CPY   $D3
20F9-   A0 B4       LDY   #$B4
20FB-   B0 A0       BCS   $209D
20FD-   BB          ???
20FE-   20 D3 CF    JSR   $CFD3
2101-   D5 D2       CMP   $D2,X
2103-   C3          ???
2104-   C5 20       CMP   $20
2106-   C6 C9       DEC   $C9
2108-   CC C5 20    CPY   $20C5
210B-   CE C1 CD    DEC   $CDC1
210E-   C5 8D       CMP   $8D
2110-   C4 CE       CPY   $CE
2112-   C1 CD       CMP   ($CD,X)
2114-   C5 A0       CMP   $A0
2116-   C4 D3       CPY   $D3
2118-   A0 B4       LDY   #$B4
211A-   B0 A0       BCS   $20BC
211C-   BB          ???
211D-   20 C4 C5    JSR   $C5C4
2120-   D3          ???
2121-   D4          ???
2122-   20 C6 C9    JSR   $C9C6
2125-   CC C5 20    CPY   $20C5
2128-   CE C1 CD    DEC   $CDC1
212B-   C5 8D       CMP   $8D
212D-   C3          ???
212E-   C3          ???
212F-   CE D4 A0    DEC   $A0D4
2132-   C4 D3       CPY   $D3
2134-   A0 B2       LDY   #$B2
2136-   A0 BB       LDY   #$BB
2138-   20 D3 C5    JSR   $C5D3
213B-   C3          ???
213C-   CF          ???
213D-   CE C4 20    DEC   $20C4
2140-   C3          ???
2141-   CF          ???
2142-   D5 CE       CMP   $CE,X
2144-   D4          ???
2145-   C5 D2       CMP   $D2
2147-   8D D4 C5    STA   $C5D4
214A-   CD D0 A0    CMP   $A0D0
214D-   C4 D3       CPY   $D3
214F-   A0 B2       LDY   #$B2
2151-   8D D7 D2    STA   $D2D7
2154-   C9 D4       CMP   #$D4
2156-   C5 CF       CMP   $CF
2158-   C6 C6       DEC   $C6
215A-   A0 C4       LDY   #$C4
215C-   D3          ???
215D-   A0 B2       LDY   #$B2
215F-   8D C1 C4    STA   $C4C1
2162-   C4 D4       CPY   $D4
2164-   A0 C8       LDY   #$C8
2166-   C5 D8       CMP   $D8
2168-   A0 B0       LDY   #$B0
216A-   B0 8D       BCS   $20F9
216C-   CC C9 CE    CPY   $CEC9
216F-   C5 A0       CMP   $A0
2171-   C4 D3       CPY   $D3
2173-   A0 B2       LDY   #$B2
2175-   B0 B0       BCS   $2127
2177-   8D AA 8D    STA   $8DAA
217A-   AA          TAX
217B-   AA          TAX
217C-   AA          TAX
217D-   AA          TAX
217E-   AA          TAX
217F-   AA          TAX
2180-   AA          TAX
2181-   AA          TAX
2182-   AA          TAX
2183-   AA          TAX
2184-   AA          TAX
2185-   AA          TAX
2186-   AA          TAX
2187-   AA          TAX
2188-   AA          TAX
2189-   AA          TAX
218A-   AA          TAX
218B-   AA          TAX
218C-   AA          TAX
218D-   AA          TAX
218E-   AA          TAX
218F-   AA          TAX
2190-   AA          TAX
2191-   AA          TAX
2192-   AA          TAX
2193-   AA          TAX
2194-   AA          TAX
2195-   AA          TAX
2196-   AA          TAX
2197-   AA          TAX
2198-   AA          TAX
2199-   AA          TAX
219A-   8D AA 20    STA   $20AA
219D-   20 20 20    JSR   $2020
21A0-   20 20 20    JSR   $2020
21A3-   20 20 20    JSR   $2020
21A6-   20 20 20    JSR   $2020
21A9-   20 20 20    JSR   $2020
21AC-   20 20 20    JSR   $2020
21AF-   20 20 20    JSR   $2020
21B2-   20 20 20    JSR   $2020
21B5-   20 20 20    JSR   $2020
21B8-   20 20 AA    JSR   $AA20
21BB-   8D AA 20    STA   $20AA
21BE-   20 CC CF    JSR   $CFCC
21C1-   D7          ???
21C2-   AD CC C5    LDA   $C5CC
21C5-   D6 C5       DEC   $C5,X
21C7-   CC 20 D2    CPY   $D220
21CA-   CF          ???
21CB-   D5 D4       CMP   $D4,X
21CD-   C9 CE       CMP   #$CE
21CF-   C5 D3       CMP   $D3
21D1-   20 20 20    JSR   $2020
21D4-   20 20 20    JSR   $2020
21D7-   20 20 20    JSR   $2020
21DA-   20 AA 8D    JSR   $8DAA
21DD-   AA          TAX
21DE-   20 20 20    JSR   $2020
21E1-   20 20 20    JSR   $2020
21E4-   20 20 20    JSR   $2020
21E7-   20 20 20    JSR   $2020
21EA-   20 20 20    JSR   $2020
21ED-   20 20 20    JSR   $2020
21F0-   20 20 20    JSR   $2020
21F3-   20 20 20    JSR   $2020
21F6-   20 20 20    JSR   $2020
21F9-   20 20 20    JSR   $2020
21FC-   AA          TAX
21FD-   8D AA AA    STA   $AAAA
2200-   AA          TAX
2201-   AA          TAX
2202-   AA          TAX
2203-   AA          TAX
2204-   AA          TAX
2205-   AA          TAX
2206-   AA          TAX
2207-   AA          TAX
2208-   AA          TAX
2209-   AA          TAX
220A-   AA          TAX
220B-   AA          TAX
220C-   AA          TAX
220D-   AA          TAX
220E-   AA          TAX
220F-   AA          TAX
2210-   AA          TAX
2211-   AA          TAX
2212-   AA          TAX
2213-   AA          TAX
2214-   AA          TAX
2215-   AA          TAX
2216-   AA          TAX
2217-   AA          TAX
2218-   AA          TAX
2219-   AA          TAX
221A-   AA          TAX
221B-   AA          TAX
221C-   AA          TAX
221D-   AA          TAX
221E-   8D AA 8D    STA   $8DAA
2221-   A0 D0       LDY   #$D0
2223-   D5 D4       CMP   $D4,X
2225-   A0 CD       LDY   #$CD
2227-   C9 CE       CMP   #$CE
2229-   AE CC C9    LDX   $C9CC
222C-   C2          ???
222D-   AE D2 C5    LDX   $C5D2
2230-   D1 D5       CMP   ($D5),Y
2232-   C9 D2       CMP   #$D2
2234-   C5 C4       CMP   $C4
2236-   8D AA 8D    STA   $8DAA
2239-   AA          TAX
223A-   AA          TAX
223B-   20 C9 CE    JSR   $CEC9
223E-   C4 C9       CPY   $C9
2240-   D6 C9       DEC   $C9,X
2242-   C4 D5       CPY   $D5
2244-   C1 CC       CMP   ($CC,X)
2246-   20 D3 D5    JSR   $D5D3
2249-   C2          ???
224A-   D2 CF       CMP   ($CF)
224C-   D5 D4       CMP   $D4,X
224E-   C9 CE       CMP   #$CE
2250-   C5 D3       CMP   $D3
2252-   8D AA 8D    STA   $8DAA
2255-   AA          TAX
2256-   AA          TAX
2257-   AA          TAX
2258-   20 D3 D4    JSR   $D4D3
225B-   D2 C9       CMP   ($C9)
225D-   CE C7 D3    DEC   $D3C7
2260-   8D AA 8D    STA   $8DAA
2263-   A0 D0       LDY   #$D0
2265-   D5 D4       CMP   $D4,X
2267-   A0 CD       LDY   #$CD
2269-   C9 CE       CMP   #$CE
226B-   AE D3 D5    LDX   $D5D3
226E-   C2          ???
226F-   AE D3 D4    LDX   $D4D3
2272-   D2 C3       CMP   ($C3)
2274-   C1 D4       CMP   ($D4,X)
2276-   8D A0 D0    STA   $D0A0
2279-   D5 D4       CMP   $D4,X
227B-   A0 CD       LDY   #$CD
227D-   C9 CE       CMP   #$CE
227F-   AE D3 D5    LDX   $D5D3
2282-   C2          ???
2283-   AE D3 D5    LDX   $D5D3
2286-   C2          ???
2287-   D0 CF       BNE   $2258
2289-   D3          ???
228A-   8D A0 D0    STA   $D0A0
228D-   D5 D4       CMP   $D4,X
228F-   A0 CD       LDY   #$CD
2291-   C9 CE       CMP   #$CE
2293-   AE D3 D5    LDX   $D5D3
2296-   C2          ???
2297-   AE D0 D2    LDX   $D2D0
229A-   CE D3 D4    DEC   $D4D3
229D-   D2 8D       CMP   ($8D)
229F-   A0 D0       LDY   #$D0
22A1-   D5 D4       CMP   $D4,X
22A3-   A0 CD       LDY   #$CD
22A5-   C9 CE       CMP   #$CE
22A7-   AE D3 D5    LDX   $D5D3
22AA-   C2          ???
22AB-   AE D3 D5    LDX   $D5D3
22AE-   C2          ???
22AF-   C4 C5       CPY   $C5
22B1-   CC 8D AA    CPY   $AA8D
22B4-   8D AA AA    STA   $AAAA
22B7-   AA          TAX
22B8-   20 D3 D4    JSR   $D4D3
22BB-   C4 C9       CPY   $C9
22BD-   CF          ???
22BE-   8D AA 8D    STA   $8DAA
22C1-   A0 D0       LDY   #$D0
22C3-   D5 D4       CMP   $D4,X
22C5-   A0 CD       LDY   #$CD
22C7-   C9 CE       CMP   #$CE
22C9-   AE D3 D5    LDX   $D5D3
22CC-   C2          ???
22CD-   AE C4 D0    LDX   $D0C4
22D0-   D2 C9       CMP   ($C9)
22D2-   CE D4 8D    DEC   $8DD4
22D5-   A0 D0       LDY   #$D0
22D7-   D5 D4       CMP   $D4,X
22D9-   A0 CD       LDY   #$CD
22DB-   C9 CE       CMP   #$CE
22DD-   AE D3 D5    LDX   $D5D3
22E0-   C2          ???
22E1-   AE D8 D0    LDX   $D0D8
22E4-   D2 C9       CMP   ($C9)
22E6-   CE D4 8D    DEC   $8DD4
22E9-   A0 D0       LDY   #$D0
22EB-   D5 D4       CMP   $D4,X
22ED-   A0 CD       LDY   #$CD
22EF-   C9 CE       CMP   #$CE
22F1-   AE D3 D5    LDX   $D5D3
22F4-   C2          ???
22F5-   AE D3 C9    LDX   $C9D3
22F8-   CE D0 D5    DEC   $D5D0
22FB-   D4          ???
22FC-   8D AA 8D    STA   $8DAA
22FF-   AA          TAX
2300-   AA          TAX
2301-   AA          TAX
2302-   20 C6 C9    JSR   $C9C6
2305-   CC C5 C9    CPY   $C9C5
2308-   CF          ???
2309-   8D AA 8D    STA   $8DAA
230C-   A0 D0       LDY   #$D0
230E-   D5 D4       CMP   $D4,X
2310-   A0 CD       LDY   #$CD
2312-   C9 CE       CMP   #$CE
2314-   AE D3 D5    LDX   $D5D3
2317-   C2          ???
2318-   AE C4 CF    LDX   $CFC4
231B-   D3          ???
231C-   C3          ???
231D-   CD C4 8D    CMP   $8DC4
2320-   A0 D0       LDY   #$D0
2322-   D5 D4       CMP   $D4,X
2324-   A0 CD       LDY   #$CD
2326-   C9 CE       CMP   #$CE
2328-   AE D3 D5    LDX   $D5D3
232B-   C2          ???
232C-   AE C6 C9    LDX   $C9C6
232F-   CE D0 D5    DEC   $D5D0
2332-   D4          ???
2333-   8D A0 D0    STA   $D0A0
2336-   D5 D4       CMP   $D4,X
2338-   A0 CD       LDY   #$CD
233A-   C9 CE       CMP   #$CE
233C-   AE D3 D5    LDX   $D5D3
233F-   C2          ???
2340-   AE C6 D0    LDX   $D0C6
2343-   D2 C9       CMP   ($C9)
2345-   CE D4 8D    DEC   $8DD4
2348-   A0 D0       LDY   #$D0
234A-   D5 D4       CMP   $D4,X
234C-   A0 CD       LDY   #$CD
234E-   C9 CE       CMP   #$CE
2350-   AE D3 D5    LDX   $D5D3
2353-   C2          ???
2354-   AE C6 D0    LDX   $D0C6
2357-   D3          ???
2358-   D4          ???
2359-   D2 8D       CMP   ($8D)
235B-   AA          TAX
235C-   8D 00 00    STA   $0000
