0901-   AA          TAX
0902-   AA          TAX
0903-   AA          TAX
0904-   AA          TAX
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   8D AA 20    STA   $20AA
0924-   20 20 20    JSR   $2020
0927-   20 20 20    JSR   $2020
092A-   20 20 20    JSR   $2020
092D-   20 20 20    JSR   $2020
0930-   20 20 20    JSR   $2020
0933-   20 20 20    JSR   $2020
0936-   20 20 20    JSR   $2020
0939-   20 20 20    JSR   $2020
093C-   20 20 20    JSR   $2020
093F-   20 20 AA    JSR   $AA20
0942-   8D AA 20    STA   $20AA
0945-   D4          ???
0946-   D9 D0 C5    CMP   $C5D0,Y
0949-   20 BA BA    JSR   $BABA
094C-   20 CF D5    JSR   $D5CF
094F-   D4          ???
0950-   D0 D5       BNE   $0927
0952-   D4          ???
0953-   20 C6 C9    JSR   $C9C6
0956-   CC C5 20    CPY   $20C5
0959-   C3          ???
095A-   CF          ???
095B-   CE D4 C5    DEC   $C5D4
095E-   CE D4 D3    DEC   $D3D4
0961-   20 AA 8D    JSR   $8DAA
0964-   AA          TAX
0965-   20 20 20    JSR   $2020
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   AA          TAX
0984-   8D AA AA    STA   $AAAA
0987-   AA          TAX
0988-   AA          TAX
0989-   AA          TAX
098A-   AA          TAX
098B-   AA          TAX
098C-   AA          TAX
098D-   AA          TAX
098E-   AA          TAX
098F-   AA          TAX
0990-   AA          TAX
0991-   AA          TAX
0992-   AA          TAX
0993-   AA          TAX
0994-   AA          TAX
0995-   AA          TAX
0996-   AA          TAX
0997-   AA          TAX
0998-   AA          TAX
0999-   AA          TAX
099A-   AA          TAX
099B-   AA          TAX
099C-   AA          TAX
099D-   AA          TAX
099E-   AA          TAX
099F-   AA          TAX
09A0-   AA          TAX
09A1-   AA          TAX
09A2-   AA          TAX
09A3-   AA          TAX
09A4-   AA          TAX
09A5-   8D AA 8D    STA   $8DAA
09A8-   AA          TAX
09A9-   AA          TAX
09AA-   20 C1 D3    JSR   $D3C1
09AD-   D3          ???
09AE-   C5 CD       CMP   $CD
09B0-   C2          ???
09B1-   CC C5 D2    CPY   $D2C5
09B4-   20 C4 C9    JSR   $C9C4
09B7-   D2 C5       CMP   ($C5)
09B9-   C3          ???
09BA-   D4          ???
09BB-   C9 D6       CMP   #$D6
09BD-   C5 D3       CMP   $D3
09BF-   8D AA 8D    STA   $8DAA
09C2-   A0 C3       LDY   #$C3
09C4-   D9 C3 A0    CMP   $A0C3,Y
09C7-   C1 D6       CMP   ($D6,X)
09C9-   C5 8D       CMP   $8D
09CB-   A0 C5       LDY   #$C5
09CD-   D8          CLD
09CE-   D0 A0       BNE   $0970
09D0-   CF          ???
09D1-   CE CC D9    DEC   $D9CC
09D4-   A0 BB       LDY   #$BB
09D6-   20 D4 D5    JSR   $D5D4
09D9-   D2 CE       CMP   ($CE)
09DB-   20 CF C6    JSR   $C6CF
09DE-   C6 20       DEC   $20
09E0-   CC C1 D4    CPY   $D4C1
09E3-   C5 D2       CMP   $D2
09E5-   8D A0 C4    STA   $C4A0
09E8-   D3          ???
09E9-   CB          ???
09EA-   A0 D2       LDY   #$D2
09EC-   C4 C6       CPY   $C6
09EE-   8D A0 D4    STA   $D4A0
09F1-   D2 A0       CMP   ($A0)
09F3-   CF          ???
09F4-   CE 8D A0    DEC   $A08D
09F7-   CF          ???
09F8-   C2          ???
09F9-   CA          DEX
09FA-   A0 A4       LDY   #$A4
09FC-   C2          ???
09FD-   C6 C5       DEC   $C5
09FF-   B0 8D       BCS   $098E
0A01-   A0 CF       LDY   #$CF
0A03-   D2 C7       CMP   ($C7)
0A05-   A0 A4       LDY   #$A4
0A07-   B7          ???
0A08-   B0 B0       BCS   $09BA
0A0A-   B0 8D       BCS   $0999
0A0C-   AA          TAX
0A0D-   8D AA AA    STA   $AAAA
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   AA          TAX
0A2C-   AA          TAX
0A2D-   AA          TAX
0A2E-   8D AA 20    STA   $20AA
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 20    JSR   $2020
0A4C-   20 20 AA    JSR   $AA20
0A4F-   8D AA 20    STA   $20AA
0A52-   C8          INY
0A53-   C5 C1       CMP   $C1
0A55-   C4 C5       CPY   $C5
0A57-   D2 AC       CMP   ($AC)
0A59-   20 C8 CF    JSR   $CFC8
0A5C-   CF          ???
0A5D-   CB          ???
0A5E-   D3          ???
0A5F-   20 C1 CE    JSR   $CEC1
0A62-   C4 20       CPY   $20
0A64-   CD C1 C3    CMP   $C3C1
0A67-   D2 CF       CMP   ($CF)
0A69-   D3          ???
0A6A-   20 20 20    JSR   $2020
0A6D-   20 20 AA    JSR   $AA20
0A70-   8D AA 20    STA   $20AA
0A73-   20 20 20    JSR   $2020
0A76-   20 20 20    JSR   $2020
0A79-   20 20 20    JSR   $2020
0A7C-   20 20 20    JSR   $2020
0A7F-   20 20 20    JSR   $2020
0A82-   20 20 20    JSR   $2020
0A85-   20 20 20    JSR   $2020
0A88-   20 20 20    JSR   $2020
0A8B-   20 20 20    JSR   $2020
0A8E-   20 20 AA    JSR   $AA20
0A91-   8D AA AA    STA   $AAAA
0A94-   AA          TAX
0A95-   AA          TAX
0A96-   AA          TAX
0A97-   AA          TAX
0A98-   AA          TAX
0A99-   AA          TAX
0A9A-   AA          TAX
0A9B-   AA          TAX
0A9C-   AA          TAX
0A9D-   AA          TAX
0A9E-   AA          TAX
0A9F-   AA          TAX
0AA0-   AA          TAX
0AA1-   AA          TAX
0AA2-   AA          TAX
0AA3-   AA          TAX
0AA4-   AA          TAX
0AA5-   AA          TAX
0AA6-   AA          TAX
0AA7-   AA          TAX
0AA8-   AA          TAX
0AA9-   AA          TAX
0AAA-   AA          TAX
0AAB-   AA          TAX
0AAC-   AA          TAX
0AAD-   AA          TAX
0AAE-   AA          TAX
0AAF-   AA          TAX
0AB0-   AA          TAX
0AB1-   AA          TAX
0AB2-   8D AA 8D    STA   $8DAA
0AB5-   A0 D0       LDY   #$D0
0AB7-   D5 D4       CMP   $D4,X
0AB9-   A0 CD       LDY   #$CD
0ABB-   C9 CE       CMP   #$CE
0ABD-   AE D6 C1    LDX   $C1D6
0AC0-   D2 D3       CMP   ($D3)
0AC2-   AE D2 C5    LDX   $C5D2
0AC5-   D1 D5       CMP   ($D5),Y
0AC7-   C9 D2       CMP   #$D2
0AC9-   C5 C4       CMP   $C4
0ACB-   8D A0 D5    STA   $D5A0
0ACE-   D3          ???
0ACF-   C5 A0       CMP   $A0
0AD1-   CD C9 CE    CMP   $CEC9
0AD4-   AE CD C1    LDX   $C1CD
0AD7-   C3          ???
0AD8-   AE D3 D4    LDX   $D4D3
0ADB-   D2 C9       CMP   ($C9)
0ADD-   CE C7 D3    DEC   $D3C7
0AE0-   8D A0 D5    STA   $D5A0
0AE3-   D3          ???
0AE4-   C5 A0       CMP   $A0
0AE6-   CD C9 CE    CMP   $CEC9
0AE9-   AE CD C1    LDX   $C1CD
0AEC-   C3          ???
0AED-   AE D2 C5    LDX   $C5D2
0AF0-   D1 D5       CMP   ($D5),Y
0AF2-   C9 D2       CMP   #$D2
0AF4-   C5 C4       CMP   $C4
0AF6-   8D A0 D5    STA   $D5A0
0AF9-   D3          ???
0AFA-   C5 A0       CMP   $A0
0AFC-   CD C9 CE    CMP   $CEC9
0AFF-   AE CD C1    LDX   $C1CD
0B02-   C3          ???
0B03-   AE C6 C9    LDX   $C9C6
0B06-   CC C5 C9    CPY   $C9C5
0B09-   CF          ???
0B0A-   8D A0 D5    STA   $D5A0
0B0D-   D3          ???
0B0E-   C5 A0       CMP   $A0
0B10-   CD C9 CE    CMP   $CEC9
0B13-   AE CD C1    LDX   $C1CD
0B16-   C3          ???
0B17-   AE D3 D4    LDX   $D4D3
0B1A-   C4 C9       CPY   $C9
0B1C-   CF          ???
0B1D-   8D A0 D0    STA   $D0A0
0B20-   D5 D4       CMP   $D4,X
0B22-   A0 CD       LDY   #$CD
0B24-   C9 CE       CMP   #$CE
0B26-   AE C8 CF    LDX   $CFC8
0B29-   CF          ???
0B2A-   CB          ???
0B2B-   D3          ???
0B2C-   AE D2 C5    LDX   $C5D2
0B2F-   D1 D5       CMP   ($D5),Y
0B31-   C9 D2       CMP   #$D2
0B33-   C5 C4       CMP   $C4
0B35-   8D A0 D0    STA   $D0A0
0B38-   D5 D4       CMP   $D4,X
0B3A-   A0 CD       LDY   #$CD
0B3C-   C9 CE       CMP   #$CE
0B3E-   AE C8 CF    LDX   $CFC8
0B41-   CF          ???
0B42-   CB          ???
0B43-   D3          ???
0B44-   AE D3 D4    LDX   $D4D3
0B47-   C4 C9       CPY   $C9
0B49-   CF          ???
0B4A-   8D A0 D0    STA   $D0A0
0B4D-   D5 D4       CMP   $D4,X
0B4F-   A0 CD       LDY   #$CD
0B51-   C9 CE       CMP   #$CE
0B53-   AE C8 CF    LDX   $CFC8
0B56-   CF          ???
0B57-   CB          ???
0B58-   D3          ???
0B59-   AE C6 C9    LDX   $C9C6
0B5C-   CC C5 C9    CPY   $C9C5
0B5F-   CF          ???
0B60-   8D A0 D0    STA   $D0A0
0B63-   D5 D4       CMP   $D4,X
0B65-   A0 CD       LDY   #$CD
0B67-   C9 CE       CMP   #$CE
0B69-   AE C8 CF    LDX   $CFC8
0B6C-   CF          ???
0B6D-   CB          ???
0B6E-   D3          ???
0B6F-   AE D3 D4    LDX   $D4D3
0B72-   D2 C9       CMP   ($C9)
0B74-   CE C7 D3    DEC   $D3C7
0B77-   8D AA 8D    STA   $8DAA
0B7A-   AA          TAX
0B7B-   AA          TAX
0B7C-   AA          TAX
0B7D-   AA          TAX
0B7E-   AA          TAX
0B7F-   AA          TAX
0B80-   AA          TAX
0B81-   AA          TAX
0B82-   AA          TAX
0B83-   AA          TAX
0B84-   AA          TAX
0B85-   AA          TAX
0B86-   AA          TAX
0B87-   AA          TAX
0B88-   AA          TAX
0B89-   AA          TAX
0B8A-   AA          TAX
0B8B-   AA          TAX
0B8C-   AA          TAX
0B8D-   AA          TAX
0B8E-   AA          TAX
0B8F-   AA          TAX
0B90-   AA          TAX
0B91-   AA          TAX
0B92-   AA          TAX
0B93-   AA          TAX
0B94-   AA          TAX
0B95-   AA          TAX
0B96-   AA          TAX
0B97-   AA          TAX
0B98-   AA          TAX
0B99-   AA          TAX
0B9A-   8D AA 20    STA   $20AA
0B9D-   20 20 20    JSR   $2020
0BA0-   20 20 20    JSR   $2020
0BA3-   20 20 20    JSR   $2020
0BA6-   20 20 20    JSR   $2020
0BA9-   20 20 20    JSR   $2020
0BAC-   20 20 20    JSR   $2020
0BAF-   20 20 20    JSR   $2020
0BB2-   20 20 20    JSR   $2020
0BB5-   20 20 20    JSR   $2020
0BB8-   20 20 AA    JSR   $AA20
0BBB-   8D AA 20    STA   $20AA
0BBE-   CD C1 C9    CMP   $C9C1
0BC1-   CE 20 D0    DEC   $D020
0BC4-   D2 CF       CMP   ($CF)
0BC6-   C7          ???
0BC7-   D2 C1       CMP   ($C1)
0BC9-   CD 20 CC    CMP   $CC20
0BCC-   CF          ???
0BCD-   CF          ???
0BCE-   D0 20       BNE   $0BF0
0BD0-   20 20 20    JSR   $2020
0BD3-   20 20 20    JSR   $2020
0BD6-   20 20 20    JSR   $2020
0BD9-   20 20 AA    JSR   $AA20
0BDC-   8D AA 20    STA   $20AA
0BDF-   20 20 20    JSR   $2020
0BE2-   20 20 20    JSR   $2020
0BE5-   20 20 20    JSR   $2020
0BE8-   20 20 20    JSR   $2020
0BEB-   20 20 20    JSR   $2020
0BEE-   20 20 20    JSR   $2020
0BF1-   20 20 20    JSR   $2020
0BF4-   20 20 20    JSR   $2020
0BF7-   20 20 20    JSR   $2020
0BFA-   20 20 AA    JSR   $AA20
0BFD-   8D AA AA    STA   $AAAA
0C00-   AA          TAX
0C01-   AA          TAX
0C02-   AA          TAX
0C03-   AA          TAX
0C04-   AA          TAX
0C05-   AA          TAX
0C06-   AA          TAX
0C07-   AA          TAX
0C08-   AA          TAX
0C09-   AA          TAX
0C0A-   AA          TAX
0C0B-   AA          TAX
0C0C-   AA          TAX
0C0D-   AA          TAX
0C0E-   AA          TAX
0C0F-   AA          TAX
0C10-   AA          TAX
0C11-   AA          TAX
0C12-   AA          TAX
0C13-   AA          TAX
0C14-   AA          TAX
0C15-   AA          TAX
0C16-   AA          TAX
0C17-   AA          TAX
0C18-   AA          TAX
0C19-   AA          TAX
0C1A-   AA          TAX
0C1B-   AA          TAX
0C1C-   AA          TAX
0C1D-   AA          TAX
0C1E-   8D AA 8D    STA   $8DAA
0C21-   CC C9 D3    CPY   $D3C9
0C24-   D4          ???
0C25-   C9 CE       CMP   #$CE
0C27-   C7          ???
0C28-   A0 C5       LDY   #$C5
0C2A-   D1 D5       CMP   ($D5),Y
0C2C-   A0 A4       LDY   #$A4
0C2E-   B2 B0       LDA   ($B0)
0C30-   B0 B0       BCS   $0BE2
0C32-   8D C2 D9    STA   $D9C2
0C35-   D4          ???
0C36-   C5 D3       CMP   $D3
0C38-   A0 C5       LDY   #$C5
0C3A-   D1 D5       CMP   ($D5),Y
0C3C-   A0 B0       LDY   #$B0
0C3E-   B8          CLV
0C3F-   8D AA 8D    STA   $8DAA
0C42-   A0 CA       LDY   #$CA
0C44-   D3          ???
0C45-   D2 A0       CMP   ($A0)
0C47-   C9 CE       CMP   #$CE
0C49-   C9 D4       CMP   #$D4
0C4B-   8D A0 CA    STA   $CAA0
0C4E-   D3          ???
0C4F-   D2 A0       CMP   ($A0)
0C51-   CF          ???
0C52-   D0 C5       BNE   $0C19
0C54-   CE C6 C9    DEC   $C9C6
0C57-   CC C5 8D    CPY   $8DC5
0C5A-   AA          TAX
0C5B-   8D A0 CA    STA   $CAA0
0C5E-   CD D0 A0    CMP   $A0D0
0C61-   D2 C5       CMP   ($C5)
0C63-   C5 CE       CMP   $CE
0C65-   D4          ???
0C66-   D2 D9       CMP   ($D9)
0C68-   8D AA 8D    STA   $8DAA
0C6B-   AA          TAX
0C6C-   AA          TAX
0C6D-   AA          TAX
0C6E-   AA          TAX
0C6F-   AA          TAX
0C70-   AA          TAX
0C71-   AA          TAX
0C72-   AA          TAX
0C73-   AA          TAX
0C74-   AA          TAX
0C75-   AA          TAX
0C76-   AA          TAX
0C77-   AA          TAX
0C78-   AA          TAX
0C79-   AA          TAX
0C7A-   AA          TAX
0C7B-   AA          TAX
0C7C-   AA          TAX
0C7D-   AA          TAX
0C7E-   AA          TAX
0C7F-   AA          TAX
0C80-   AA          TAX
0C81-   AA          TAX
0C82-   AA          TAX
0C83-   AA          TAX
0C84-   AA          TAX
0C85-   AA          TAX
0C86-   AA          TAX
0C87-   AA          TAX
0C88-   AA          TAX
0C89-   AA          TAX
0C8A-   AA          TAX
0C8B-   8D AA 20    STA   $20AA
0C8E-   20 20 20    JSR   $2020
0C91-   20 20 20    JSR   $2020
0C94-   20 20 20    JSR   $2020
0C97-   20 20 20    JSR   $2020
0C9A-   20 20 20    JSR   $2020
0C9D-   20 20 20    JSR   $2020
0CA0-   20 20 20    JSR   $2020
0CA3-   20 20 20    JSR   $2020
0CA6-   20 20 20    JSR   $2020
0CA9-   20 20 AA    JSR   $AA20
0CAC-   8D AA 20    STA   $20AA
0CAF-   C9 CE       CMP   #$CE
0CB1-   C9 D4       CMP   #$D4
0CB3-   20 20 20    JSR   $2020
0CB6-   20 20 20    JSR   $2020
0CB9-   20 20 20    JSR   $2020
0CBC-   20 20 20    JSR   $2020
0CBF-   20 20 20    JSR   $2020
0CC2-   20 20 20    JSR   $2020
0CC5-   20 20 20    JSR   $2020
0CC8-   20 20 20    JSR   $2020
0CCB-   20 AA 8D    JSR   $8DAA
0CCE-   AA          TAX
0CCF-   20 20 20    JSR   $2020
0CD2-   20 20 20    JSR   $2020
0CD5-   20 20 20    JSR   $2020
0CD8-   20 20 20    JSR   $2020
0CDB-   20 20 20    JSR   $2020
0CDE-   20 20 20    JSR   $2020
0CE1-   20 20 20    JSR   $2020
0CE4-   20 20 20    JSR   $2020
0CE7-   20 20 20    JSR   $2020
0CEA-   20 20 20    JSR   $2020
0CED-   AA          TAX
0CEE-   8D AA AA    STA   $AAAA
0CF1-   AA          TAX
0CF2-   AA          TAX
0CF3-   AA          TAX
0CF4-   AA          TAX
0CF5-   AA          TAX
0CF6-   AA          TAX
0CF7-   AA          TAX
0CF8-   AA          TAX
0CF9-   AA          TAX
0CFA-   AA          TAX
0CFB-   AA          TAX
0CFC-   AA          TAX
0CFD-   AA          TAX
0CFE-   AA          TAX
0CFF-   AA          TAX
0D00-   AA          TAX
0D01-   AA          TAX
0D02-   AA          TAX
0D03-   AA          TAX
0D04-   AA          TAX
0D05-   AA          TAX
0D06-   AA          TAX
0D07-   AA          TAX
0D08-   AA          TAX
0D09-   AA          TAX
0D0A-   AA          TAX
0D0B-   AA          TAX
0D0C-   AA          TAX
0D0D-   AA          TAX
0D0E-   AA          TAX
0D0F-   8D AA 8D    STA   $8DAA
0D12-   C9 CE       CMP   #$CE
0D14-   C9 D4       CMP   #$D4
0D16-   8D AA 8D    STA   $8DAA
0D19-   A0 C1       LDY   #$C1
0D1B-   CD CF C4    CMP   $C4CF
0D1E-   C5 8D       CMP   $8D
0D20-   A0 CC       LDY   #$CC
0D22-   C4 C1       CPY   $C1
0D24-   A0 A3       LDY   #$A3
0D26-   A4 B0       LDY   $B0
0D28-   B0 8D       BCS   $0CB7
0D2A-   A0 D3       LDY   #$D3
0D2C-   D4          ???
0D2D-   C1 A0       CMP   ($A0,X)
0D2F-   A4 C4       LDY   $C4
0D31-   B8          CLV
0D32-   8D AA 8D    STA   $8DAA
0D35-   A0 CC       LDY   #$CC
0D37-   C4 C1       CPY   $C1
0D39-   A0 A3       LDY   #$A3
0D3B-   B0 B0       BCS   $0CED
0D3D-   8D A0 D3    STA   $D3A0
0D40-   D4          ???
0D41-   C1 A0       CMP   ($A0,X)
0D43-   D4          ???
0D44-   C6 CF       DEC   $CF
0D46-   D5 CE       CMP   $CE,X
0D48-   C4 8D       CPY   $8D
0D4A-   A0 D2       LDY   #$D2
0D4C-   D4          ???
0D4D-   D3          ???
0D4E-   8D AA 8D    STA   $8DAA
0D51-   AA          TAX
0D52-   8D AA AA    STA   $AAAA
0D55-   AA          TAX
0D56-   AA          TAX
0D57-   AA          TAX
0D58-   AA          TAX
0D59-   AA          TAX
0D5A-   AA          TAX
0D5B-   AA          TAX
0D5C-   AA          TAX
0D5D-   AA          TAX
0D5E-   AA          TAX
0D5F-   AA          TAX
0D60-   AA          TAX
0D61-   AA          TAX
0D62-   AA          TAX
0D63-   AA          TAX
0D64-   AA          TAX
0D65-   AA          TAX
0D66-   AA          TAX
0D67-   AA          TAX
0D68-   AA          TAX
0D69-   AA          TAX
0D6A-   AA          TAX
0D6B-   AA          TAX
0D6C-   AA          TAX
0D6D-   AA          TAX
0D6E-   AA          TAX
0D6F-   AA          TAX
0D70-   AA          TAX
0D71-   AA          TAX
0D72-   AA          TAX
0D73-   8D AA 20    STA   $20AA
0D76-   20 20 20    JSR   $2020
0D79-   20 20 20    JSR   $2020
0D7C-   20 20 20    JSR   $2020
0D7F-   20 20 20    JSR   $2020
0D82-   20 20 20    JSR   $2020
0D85-   20 20 20    JSR   $2020
0D88-   20 20 20    JSR   $2020
0D8B-   20 20 20    JSR   $2020
0D8E-   20 20 20    JSR   $2020
0D91-   20 20 AA    JSR   $AA20
0D94-   8D AA 20    STA   $20AA
0D97-   CF          ???
0D98-   D0 C5       BNE   $0D5F
0D9A-   CE C6 C9    DEC   $C9C6
0D9D-   CC C5 20    CPY   $20C5
0DA0-   20 20 20    JSR   $2020
0DA3-   20 20 20    JSR   $2020
0DA6-   20 20 20    JSR   $2020
0DA9-   20 20 20    JSR   $2020
0DAC-   20 20 20    JSR   $2020
0DAF-   20 20 20    JSR   $2020
0DB2-   20 20 AA    JSR   $AA20
0DB5-   8D AA 20    STA   $20AA
0DB8-   20 20 20    JSR   $2020
0DBB-   20 20 20    JSR   $2020
0DBE-   20 20 20    JSR   $2020
0DC1-   20 20 20    JSR   $2020
0DC4-   20 20 20    JSR   $2020
0DC7-   20 20 20    JSR   $2020
0DCA-   20 20 20    JSR   $2020
0DCD-   20 20 20    JSR   $2020
0DD0-   20 20 20    JSR   $2020
0DD3-   20 20 AA    JSR   $AA20
0DD6-   8D AA AA    STA   $AAAA
0DD9-   AA          TAX
0DDA-   AA          TAX
0DDB-   AA          TAX
0DDC-   AA          TAX
0DDD-   AA          TAX
0DDE-   AA          TAX
0DDF-   AA          TAX
0DE0-   AA          TAX
0DE1-   AA          TAX
0DE2-   AA          TAX
0DE3-   AA          TAX
0DE4-   AA          TAX
0DE5-   AA          TAX
0DE6-   AA          TAX
0DE7-   AA          TAX
0DE8-   AA          TAX
0DE9-   AA          TAX
0DEA-   AA          TAX
0DEB-   AA          TAX
0DEC-   AA          TAX
0DED-   AA          TAX
0DEE-   AA          TAX
0DEF-   AA          TAX
0DF0-   AA          TAX
0DF1-   AA          TAX
0DF2-   AA          TAX
0DF3-   AA          TAX
0DF4-   AA          TAX
0DF5-   AA          TAX
0DF6-   AA          TAX
0DF7-   8D AA 8D    STA   $8DAA
0DFA-   CF          ???
0DFB-   D0 C5       BNE   $0DC2
0DFD-   CE C6 C9    DEC   $C9C6
0E00-   CC C5 8D    CPY   $8DC5
0E03-   AA          TAX
0E04-   8D A0 CA    STA   $CAA0
0E07-   D3          ???
0E08-   D2 A0       CMP   ($A0)
0E0A-   C7          ???
0E0B-   C5 D4       CMP   $D4
0E0D-   CE C1 CD    DEC   $CDC1
0E10-   C5 8D       CMP   $8D
0E12-   A0 CA       LDY   #$CA
0E14-   D3          ???
0E15-   D2 A0       CMP   ($A0)
0E17-   C3          ???
0E18-   C8          INY
0E19-   CB          ???
0E1A-   C5 D8       CMP   $D8
0E1C-   C9 D3       CMP   #$D3
0E1E-   D4          ???
0E1F-   8D A0 CA    STA   $CAA0
0E22-   D3          ???
0E23-   D2 A0       CMP   ($A0)
0E25-   C3          ???
0E26-   C8          INY
0E27-   CB          ???
0E28-   D4          ???
0E29-   D9 D0 C5    CMP   $C5D0,Y
0E2C-   8D A0 CA    STA   $CAA0
0E2F-   D3          ???
0E30-   D2 A0       CMP   ($A0)
0E32-   CF          ???
0E33-   D0 C5       BNE   $0DFA
0E35-   CE C9 D4    DEC   $D4C9
0E38-   8D A0 D2    STA   $D2A0
0E3B-   D4          ???
0E3C-   D3          ???
0E3D-   8D AA 8D    STA   $8DAA
0E40-   AA          TAX
0E41-   AA          TAX
0E42-   AA          TAX
0E43-   AA          TAX
0E44-   AA          TAX
0E45-   8D AA AA    STA   $AAAA
0E48-   AA          TAX
0E49-   AA          TAX
0E4A-   AA          TAX
0E4B-   20 C7 C5    JSR   $C5C7
0E4E-   D4          ???
0E4F-   CE C1 CD    DEC   $CDC1
0E52-   C5 8D       CMP   $8D
0E54-   AA          TAX
0E55-   AA          TAX
0E56-   AA          TAX
0E57-   AA          TAX
0E58-   AA          TAX
0E59-   8D AA 8D    STA   $8DAA
0E5C-   C7          ???
0E5D-   C5 D4       CMP   $D4
0E5F-   CE C1 CD    DEC   $CDC1
0E62-   C5 8D       CMP   $8D
0E64-   AA          TAX
0E65-   8D A0 D0    STA   $D0A0
0E68-   D2 CE       CMP   ($CE)
0E6A-   A0 A2       LDY   #$A2
0E6C-   20 A2 AC    JSR   $ACA2
0E6F-   B8          CLV
0E70-   C4 B8       CPY   $B8
0E72-   C4 8D       CPY   $8D
0E74-   A0 D0       LDY   #$D0
0E76-   D2 CE       CMP   ($CE)
0E78-   A0 A2       LDY   #$A2
0E7A-   C6 C9       DEC   $C9
0E7C-   CC C5 20    CPY   $20C5
0E7F-   D4          ???
0E80-   CF          ???
0E81-   20 D0 D2    JSR   $D2D0
0E84-   C9 CE       CMP   #$CE
0E86-   D4          ???
0E87-   BA          TSX
0E88-   20 A2 8D    JSR   $8DA2
0E8B-   A0 C9       LDY   #$C9
0E8D-   CE D0 8D    DEC   $8DD0
0E90-   A0 C7       LDY   #$C7
0E92-   D2 C5       CMP   ($C5)
0E94-   D4          ???
0E95-   A0 A3       LDY   #$A3
0E97-   C6 CE       DEC   $CE
0E99-   C1 CD       CMP   ($CD,X)
0E9B-   C5 8D       CMP   $8D
0E9D-   A0 D2       LDY   #$D2
0E9F-   D4          ???
0EA0-   D3          ???
0EA1-   8D AA 8D    STA   $8DAA
0EA4-   AA          TAX
0EA5-   AA          TAX
0EA6-   AA          TAX
0EA7-   AA          TAX
0EA8-   AA          TAX
0EA9-   8D AA AA    STA   $AAAA
0EAC-   AA          TAX
0EAD-   AA          TAX
0EAE-   AA          TAX
0EAF-   20 C3 C8    JSR   $C8C3
0EB2-   CB          ???
0EB3-   C5 D8       CMP   $D8
0EB5-   C9 D3       CMP   #$D3
0EB7-   D4          ???
0EB8-   8D AA AA    STA   $AAAA
0EBB-   AA          TAX
0EBC-   AA          TAX
0EBD-   AA          TAX
0EBE-   8D AA 8D    STA   $8DAA
0EC1-   C3          ???
0EC2-   C8          INY
0EC3-   CB          ???
0EC4-   C5 D8       CMP   $D8
0EC6-   C9 D3       CMP   #$D3
0EC8-   D4          ???
0EC9-   8D A0 C5    STA   $C5A0
0ECC-   D2 D2       CMP   ($D2)
0ECE-   C8          INY
0ECF-   A0 A3       LDY   #$A3
0ED1-   BA          TSX
0ED2-   CE CF C5    DEC   $C5CF
0ED5-   D8          CLD
0ED6-   C9 D3       CMP   #$D3
0ED8-   D4          ???
0ED9-   8D A0 D3    STA   $D3A0
0EDC-   C3          ???
0EDD-   C1 D4       CMP   ($D4,X)
0EDF-   A0 A2       LDY   #$A2
0EE1-   D6 C5       DEC   $C5,X
0EE3-   D2 C9       CMP   ($C9)
0EE5-   C6 D9       DEC   $D9
0EE7-   20 A2 BB    JSR   $BBA2
0EEA-   A3          ???
0EEB-   C6 CE       DEC   $CE
0EED-   C1 CD       CMP   ($CD,X)
0EEF-   C5 BB       CMP   $BB
0EF1-   A3          ???
0EF2-   B1 B0       LDA   ($B0),Y
0EF4-   B0 8D       BCS   $0E83
0EF6-   A0 C3       LDY   #$C3
0EF8-   CD C4 A0    CMP   $A0C4
0EFB-   A3          ???
0EFC-   D2 C5       CMP   ($C5)
0EFE-   D4          ???
0EFF-   D5 D2       CMP   $D2,X
0F01-   CE 8D A0    DEC   $A08D
0F04-   D2 D4       CMP   ($D4)
0F06-   D3          ???
0F07-   8D AA 8D    STA   $8DAA
0F0A-   BA          TSX
0F0B-   CE CF C5    DEC   $C5CF
0F0E-   D8          CLD
0F0F-   C9 D3       CMP   #$D3
0F11-   D4          ???
0F12-   8D A0 D0    STA   $D0A0
0F15-   D2 CE       CMP   ($CE)
0F17-   A0 A2       LDY   #$A2
0F19-   20 A2 AC    JSR   $ACA2
0F1C-   B8          CLV
0F1D-   C4 B8       CPY   $B8
0F1F-   C4 8D       CPY   $8D
0F21-   A0 CC       LDY   #$CC
0F23-   C4 C1       CPY   $C1
0F25-   A0 A3       LDY   #$A3
0F27-   B7          ???
0F28-   8D A0 CA    STA   $CAA0
0F2B-   D3          ???
0F2C-   D2 A0       CMP   ($A0)
0F2E-   C3          ???
0F2F-   CF          ???
0F30-   D5 D4       CMP   $D4,X
0F32-   8D A0 D0    STA   $D0A0
0F35-   D2 CE       CMP   ($CE)
0F37-   A0 A2       LDY   #$A2
0F39-   C5 D2       CMP   $D2
0F3B-   D2 CF       CMP   ($CF)
0F3D-   D2 BA       CMP   ($BA)
0F3F-   20 C6 C9    JSR   $C9C6
0F42-   CC C5 20    CPY   $20C5
0F45-   C4 CF       CPY   $CF
0F47-   C5 D3       CMP   $D3
0F49-   CE A7 D4    DEC   $D4A7
0F4C-   20 C5 D8    JSR   $D8C5
0F4F-   C9 D3       CMP   #$D3
0F51-   D4          ???
0F52-   A2 AC       LDX   #$AC
0F54-   B8          CLV
0F55-   C4 B8       CPY   $B8
0F57-   C4 8D       CPY   $8D
0F59-   A0 D0       LDY   #$D0
0F5B-   CC C1 8D    CPY   $8DC1
0F5E-   A0 D0       LDY   #$D0
0F60-   CC C1 8D    CPY   $8DC1
0F63-   A0 CA       LDY   #$CA
0F65-   CD D0 A0    CMP   $A0D0
0F68-   D2 C5       CMP   ($C5)
0F6A-   C5 CE       CMP   $CE
0F6C-   D4          ???
0F6D-   D2 D9       CMP   ($D9)
0F6F-   8D AA 8D    STA   $8DAA
0F72-   AA          TAX
0F73-   AA          TAX
0F74-   AA          TAX
0F75-   AA          TAX
0F76-   AA          TAX
0F77-   8D AA AA    STA   $AAAA
0F7A-   AA          TAX
0F7B-   AA          TAX
0F7C-   AA          TAX
0F7D-   20 C3 C8    JSR   $C8C3
0F80-   CB          ???
0F81-   D4          ???
0F82-   D9 D0 C5    CMP   $C5D0,Y
0F85-   8D AA AA    STA   $AAAA
0F88-   AA          TAX
0F89-   AA          TAX
0F8A-   AA          TAX
0F8B-   8D AA 8D    STA   $8DAA
0F8E-   C3          ???
0F8F-   C8          INY
0F90-   CB          ???
0F91-   D4          ???
0F92-   D9 D0 C5    CMP   $C5D0,Y
0F95-   8D A0 C5    STA   $C5A0
0F98-   D2 D2       CMP   ($D2)
0F9A-   C8          INY
0F9B-   A0 BA       LDY   #$BA
0F9D-   D4          ???
0F9E-   D8          CLD
0F9F-   D4          ???
0FA0-   C6 8D       DEC   $8D
0FA2-   A0 D3       LDY   #$D3
0FA4-   C3          ???
0FA5-   C1 D4       CMP   ($D4,X)
0FA7-   A0 A2       LDY   #$A2
0FA9-   C2          ???
0FAA-   CC CF C1    CPY   $C1CF
0FAD-   C4 20       CPY   $20
0FAF-   A2 BB       LDX   #$BB
0FB1-   A3          ???
0FB2-   C6 CE       DEC   $CE
0FB4-   C1 CD       CMP   ($CD,X)
0FB6-   C5 BB       CMP   $BB
0FB8-   A3          ???
0FB9-   B1 B0       LDA   ($B0),Y
0FBB-   B0 8D       BCS   $0F4A
0FBD-   A0 C7       LDY   #$C7
0FBF-   D2 C5       CMP   ($C5)
0FC1-   D4          ???
0FC2-   A0 A3       LDY   #$A3
0FC4-   C2          ???
0FC5-   CC CF C1    CPY   $C1CF
0FC8-   C4 B1       CPY   $B1
0FCA-   8D A0 D3    STA   $D3A0
0FCD-   C3          ???
0FCE-   C1 D4       CMP   ($D4,X)
0FD0-   A0 A3       LDY   #$A3
0FD2-   C2          ???
0FD3-   CC CF C1    CPY   $C1CF
0FD6-   C4 B1       CPY   $B1
0FD8-   BB          ???
0FD9-   A2 AC       LDX   #$AC
0FDB-   C1 A4       CMP   ($A4,X)
0FDD-   B2 B0       LDA   ($B0)
0FDF-   B0 B0       BCS   $0F91
0FE1-   A2 BB       LDX   #$BB
0FE3-   A3          ???
0FE4-   B1 B0       LDA   ($B0),Y
0FE6-   B0 8D       BCS   $0F75
0FE8-   A0 C3       LDY   #$C3
0FEA-   CD C4 A0    CMP   $A0C4
0FED-   A3          ???
0FEE-   D2 C5       CMP   ($C5)
0FF0-   D4          ???
0FF1-   D5 D2       CMP   $D2,X
0FF3-   CE 8D A0    DEC   $A08D
0FF6-   CC C4 C1    CPY   $C1C4
0FF9-   A0 A3       LDY   #$A3
0FFB-   A4 C6       LDY   $C6
0FFD-   C6 8D       DEC   $8D
0FFF-   A0 D3       LDY   #$D3
1001-   D4          ???
1002-   C1 A0       CMP   ($A0,X)
1004-   C6 D4       DEC   $D4
1006-   D9 D0 C5    CMP   $C5D0,Y
1009-   8D A0 CC    STA   $CCA0
100C-   C4 C1       CPY   $C1
100E-   A0 D4       LDY   #$D4
1010-   C6 CF       DEC   $CF
1012-   D5 CE       CMP   $CE,X
1014-   C4 8D       CPY   $8D
1016-   A0 C3       LDY   #$C3
1018-   CD D0 A0    CMP   $A0D0
101B-   A3          ???
101C-   A4 C6       LDY   $C6
101E-   C6 8D       DEC   $8D
1020-   A0 C2       LDY   #$C2
1022-   C5 D1       CMP   $D1
1024-   A0 BA       LDY   #$BA
1026-   D4          ???
1027-   D4          ???
1028-   D9 D0 C5    CMP   $C5D0,Y
102B-   8D A0 D2    STA   $D2A0
102E-   D4          ???
102F-   D3          ???
1030-   8D BA D4    STA   $D4BA
1033-   D4          ???
1034-   D9 D0 C5    CMP   $C5D0,Y
1037-   8D A0 CC    STA   $CCA0
103A-   C4 C1       CPY   $C1
103C-   A0 A3       LDY   #$A3
103E-   B0 8D       BCS   $0FCD
1040-   A0 D3       LDY   #$D3
1042-   D4          ???
1043-   C1 A0       CMP   ($A0,X)
1045-   C6 D4       DEC   $D4
1047-   D9 D0 C5    CMP   $C5D0,Y
104A-   8D A0 D2    STA   $D2A0
104D-   D4          ???
104E-   D3          ???
104F-   8D BA D4    STA   $D4BA
1052-   D8          CLD
1053-   D4          ???
1054-   C6 8D       DEC   $8D
1056-   A0 CC       LDY   #$CC
1058-   C4 C1       CPY   $C1
105A-   A0 A3       LDY   #$A3
105C-   A4 C6       LDY   $C6
105E-   C6 8D       DEC   $8D
1060-   A0 D3       LDY   #$D3
1062-   D4          ???
1063-   C1 A0       CMP   ($A0,X)
1065-   D4          ???
1066-   C6 CF       DEC   $CF
1068-   D5 CE       CMP   $CE,X
106A-   C4 8D       CPY   $8D
106C-   A0 CC       LDY   #$CC
106E-   C4 C1       CPY   $C1
1070-   A0 A3       LDY   #$A3
1072-   A4 B0       LDY   $B0
1074-   B0 8D       BCS   $1003
1076-   A0 D3       LDY   #$D3
1078-   D4          ???
1079-   C1 A0       CMP   ($A0,X)
107B-   A4 C4       LDY   $C4
107D-   B8          CLV
107E-   8D A0 D2    STA   $D2A0
1081-   D4          ???
1082-   D3          ???
1083-   8D AA 8D    STA   $8DAA
1086-   AA          TAX
1087-   AA          TAX
1088-   AA          TAX
1089-   AA          TAX
108A-   AA          TAX
108B-   8D AA AA    STA   $AAAA
108E-   AA          TAX
108F-   AA          TAX
1090-   AA          TAX
1091-   20 CF D0    JSR   $D0CF
1094-   C5 CE       CMP   $CE
1096-   C9 D4       CMP   #$D4
1098-   8D AA AA    STA   $AAAA
109B-   AA          TAX
109C-   AA          TAX
109D-   AA          TAX
109E-   8D AA 8D    STA   $8DAA
10A1-   CF          ???
10A2-   D0 C5       BNE   $1069
10A4-   CE C9 D4    DEC   $D4C9
10A7-   8D A0 CC    STA   $CCA0
10AA-   C4 C1       CPY   $C1
10AC-   A0 C6       LDY   #$C6
10AE-   D4          ???
10AF-   D9 D0 C5    CMP   $C5D0,Y
10B2-   8D A0 C3    STA   $C3A0
10B5-   CD D0 A0    CMP   $A0D0
10B8-   A3          ???
10B9-   B0 8D       BCS   $1048
10BB-   A0 C2       LDY   #$C2
10BD-   C5 D1       CMP   $D1
10BF-   A0 BA       LDY   #$BA
10C1-   C7          ???
10C2-   CF          ???
10C3-   D4          ???
10C4-   D8          CLD
10C5-   D4          ???
10C6-   8D A0 CA    STA   $CAA0
10C9-   CD D0 A0    CMP   $A0D0
10CC-   BA          TSX
10CD-   C8          INY
10CE-   C5 D8       CMP   $D8
10D0-   C4 C9       CPY   $C9
10D2-   D3          ???
10D3-   D0 8D       BNE   $1062
10D5-   BA          TSX
10D6-   C7          ???
10D7-   CF          ???
10D8-   D4          ???
10D9-   D8          CLD
10DA-   D4          ???
10DB-   8D A0 CA    STA   $CAA0
10DE-   CD D0 A0    CMP   $A0D0
10E1-   BA          TSX
10E2-   D4          ???
10E3-   D8          CLD
10E4-   D4          ???
10E5-   C4 C9       CPY   $C9
10E7-   D3          ???
10E8-   D0 8D       BNE   $1077
10EA-   BA          TSX
10EB-   C8          INY
10EC-   C5 D8       CMP   $D8
10EE-   C4 C9       CPY   $C9
10F0-   D3          ???
10F1-   D0 8D       BNE   $1080
10F3-   AA          TAX
10F4-   8D AA AA    STA   $AAAA
10F7-   20 C3 CF    JSR   $CFC3
10FA-   C4 C5       CPY   $C5
10FC-   20 D7 C1    JSR   $C1D7
10FF-   D3          ???
1100-   20 C1 CC    JSR   $CCC1
1103-   D2 C5       CMP   ($C5)
1105-   C1 C4       CMP   ($C4,X)
1107-   D9 20 C2    CMP   $C220,Y
110A-   CC CF C1    CPY   $C1CF
110D-   C4 C5       CPY   $C5
110F-   C4 AC       CPY   $AC
1111-   20 D3 CF    JSR   $CFD3
1114-   20 CE CF    JSR   $CFCE
1117-   D7          ???
1118-   8D AA AA    STA   $AAAA
111B-   20 CA D5    JSR   $D5CA
111E-   D3          ???
111F-   D4          ???
1120-   20 C6 C9    JSR   $C9C6
1123-   CE C4 20    DEC   $20C4
1126-   D4          ???
1127-   C8          INY
1128-   C5 20       CMP   $20
112A-   C1 C4       CMP   ($C4,X)
112C-   C4 D2       CPY   $D2
112E-   C5 D3       CMP   $D3
1130-   D3          ???
1131-   20 C9 D4    JSR   $D4C9
1134-   A7          ???
1135-   D3          ???
1136-   20 C1 D4    JSR   $D4C1
1139-   8D AA 8D    STA   $8DAA
113C-   A0 CC       LDY   #$CC
113E-   C4 C1       CPY   $C1
1140-   A0 A4       LDY   #$A4
1142-   C1 C1       CMP   ($C1,X)
1144-   B7          ???
1145-   B2 A0       LDA   ($A0)
1147-   BB          ???
1148-   20 CC CF    JSR   $CFCC
114B-   C1 C4       CMP   ($C4,X)
114D-   C9 CE       CMP   #$CE
114F-   C7          ???
1150-   20 C1 C4    JSR   $C4C1
1153-   C4 D2       CPY   $D2
1155-   C5 D3       CMP   $D3
1157-   D3          ???
1158-   20 CF C6    JSR   $C6CF
115B-   20 C6 C9    JSR   $C9C6
115E-   CC C5 8D    CPY   $8DC5
1161-   A0 D3       LDY   #$D3
1163-   D4          ???
1164-   C1 A0       CMP   ($A0,X)
1166-   CC C4 C1    CPY   $C1C4
1169-   C4 C4       CPY   $C4
116B-   D2 8D       CMP   ($8D)
116D-   A0 CC       LDY   #$CC
116F-   C4 C1       CPY   $C1
1171-   A0 A4       LDY   #$A4
1173-   C1 C1       CMP   ($C1,X)
1175-   B7          ???
1176-   B3          ???
1177-   8D A0 D3    STA   $D3A0
117A-   D4          ???
117B-   C1 A0       CMP   ($A0,X)
117D-   CC C4 C1    CPY   $C1C4
1180-   C4 C4       CPY   $C4
1182-   D2 AB       CMP   ($AB)
1184-   B1 8D       LDA   ($8D),Y
1186-   A0 D0       LDY   #$D0
1188-   D2 CE       CMP   ($CE)
118A-   A0 A2       LDY   #$A2
118C-   20 A2 AC    JSR   $ACA2
118F-   B8          CLV
1190-   C4 B8       CPY   $B8
1192-   C4 8D       CPY   $8D
1194-   AA          TAX
1195-   8D A0 CC    STA   $CCA0
1198-   C4 C1       CPY   $C1
119A-   A0 A4       LDY   #$A4
119C-   C1 C1       CMP   ($C1,X)
119E-   B6 B0       LDX   $B0,Y
11A0-   A0 BB       LDY   #$BB
11A2-   20 CC CF    JSR   $CFCC
11A5-   C1 C4       CMP   ($C4,X)
11A7-   C9 CE       CMP   #$CE
11A9-   C7          ???
11AA-   20 CC C5    JSR   $C5CC
11AD-   CE C7 D4    DEC   $D4C7
11B0-   C8          INY
11B1-   8D A0 D3    STA   $D3A0
11B4-   D4          ???
11B5-   C1 A0       CMP   ($A0,X)
11B7-   CC C4 CC    CPY   $CCC4
11BA-   C5 CE       CMP   $CE
11BC-   8D A0 CC    STA   $CCA0
11BF-   C4 C1       CPY   $C1
11C1-   A0 A4       LDY   #$A4
11C3-   C1 C1       CMP   ($C1,X)
11C5-   B6 B1       LDX   $B1,Y
11C7-   8D A0 D3    STA   $D3A0
11CA-   D4          ???
11CB-   C1 A0       CMP   ($A0,X)
11CD-   CC C4 CC    CPY   $CCC4
11D0-   C5 CE       CMP   $CE
11D2-   AB          ???
11D3-   B1 8D       LDA   ($8D),Y
11D5-   A0 D0       LDY   #$D0
11D7-   D2 CE       CMP   ($CE)
11D9-   A0 A2       LDY   #$A2
11DB-   CC C5 CE    CPY   $CEC5
11DE-   C7          ???
11DF-   D4          ???
11E0-   C8          INY
11E1-   BA          TSX
11E2-   20 A8 CC    JSR   $CCA8
11E5-   CF          ???
11E6-   D7          ???
11E7-   20 C2 D9    JSR   $D9C2
11EA-   D4          ???
11EB-   C5 AC       CMP   $AC
11ED-   20 C8 C9    JSR   $C9C8
11F0-   C7          ???
11F1-   C8          INY
11F2-   20 C2 D9    JSR   $D9C2
11F5-   D4          ???
11F6-   C5 A9       CMP   $A9
11F8-   A2 AC       LDX   #$AC
11FA-   B8          CLV
11FB-   C4 8D       CPY   $8D
11FD-   A0 C4       LDY   #$C4
11FF-   D5 CD       CMP   $CD,X
1201-   D0 A0       BNE   $11A3
1203-   A3          ???
1204-   CC C4 CC    CPY   $CCC4
1207-   C5 CE       CMP   $CE
1209-   BB          ???
120A-   A3          ???
120B-   B2 8D       LDA   ($8D)
120D-   A0 D0       LDY   #$D0
120F-   D2 CE       CMP   ($CE)
1211-   A0 A2       LDY   #$A2
1213-   20 A2 AC    JSR   $ACA2
1216-   B8          CLV
1217-   C4 8D       CPY   $8D
1219-   A0 DF       LDY   #$DF
121B-   D7          ???
121C-   C1 C9       CMP   ($C9,X)
121E-   D4          ???
121F-   8D AA 8D    STA   $8DAA
1222-   BA          TSX
1223-   C2          ???
1224-   C5 C7       CMP   $C7
1226-   C8          INY
1227-   C5 D8       CMP   $D8
1229-   CF          ???
122A-   D5 D4       CMP   $D4,X
122C-   8D A0 CC    STA   $CCA0
122F-   C4 C1       CPY   $C1
1231-   A0 A3       LDY   #$A3
1233-   B0 8D       BCS   $11C2
1235-   A0 D3       LDY   #$D3
1237-   D4          ???
1238-   C1 A0       CMP   ($A0,X)
123A-   C3          ???
123B-   CE D4 B1    DEC   $B1D4
123E-   8D A0 CC    STA   $CCA0
1241-   C4 C1       CPY   $C1
1243-   A0 A3       LDY   #$A3
1245-   BC CC C9    LDY   $C9CC,X
1248-   D3          ???
1249-   D4          ???
124A-   C9 CE       CMP   #$CE
124C-   C7          ???
124D-   8D A0 D3    STA   $D3A0
1250-   D4          ???
1251-   C1 A0       CMP   ($A0,X)
1253-   CC C9 CE    CPY   $CEC9
1256-   C5 8D       CMP   $8D
1258-   A0 CC       LDY   #$CC
125A-   C4 C1       CPY   $C1
125C-   A0 A3       LDY   #$A3
125E-   BE CC C9    LDX   $C9CC,Y
1261-   D3          ???
1262-   D4          ???
1263-   C9 CE       CMP   #$CE
1265-   C7          ???
1266-   8D A0 D3    STA   $D3A0
1269-   D4          ???
126A-   C1 A0       CMP   ($A0,X)
126C-   CC C9 CE    CPY   $CEC9
126F-   C5 AB       CMP   $AB
1271-   B1 8D       LDA   ($8D),Y
1273-   BA          TSX
1274-   C8          INY
1275-   C5 D8       CMP   $D8
1277-   CC D0 B1    CPY   $B1D0
127A-   8D AA 8D    STA   $8DAA
127D-   AA          TAX
127E-   C4 D5       CPY   $D5
1280-   CD D0 20    CMP   $20D0
1283-   CC C9 CE    CPY   $CEC9
1286-   C5 BB       CMP   $BB
1288-   A3          ???
1289-   C2          ???
128A-   D9 D4 C5    CMP   $C5D4,Y
128D-   D3          ???
128E-   8D AA 8D    STA   $8DAA
1291-   AA          TAX
1292-   8D A0 CC    STA   $CCA0
1295-   C4 C1       CPY   $C1
1297-   A0 CC       LDY   #$CC
1299-   C9 CE       CMP   #$CE
129B-   C5 8D       CMP   $8D
129D-   A0 D3       LDY   #$D3
129F-   D4          ???
12A0-   C1 A0       CMP   ($A0,X)
12A2-   C1 C4       CMP   ($C4,X)
12A4-   C4 D2       CPY   $D2
12A6-   B3          ???
12A7-   8D A0 CC    STA   $CCA0
12AA-   C4 C1       CPY   $C1
12AC-   A0 CC       LDY   #$CC
12AE-   C9 CE       CMP   #$CE
12B0-   C5 AB       CMP   $AB
12B2-   B1 8D       LDA   ($8D),Y
12B4-   A0 D3       LDY   #$D3
12B6-   D4          ???
12B7-   C1 A0       CMP   ($A0,X)
12B9-   C1 C4       CMP   ($C4,X)
12BB-   C4 D2       CPY   $D2
12BD-   B3          ???
12BE-   AB          ???
12BF-   B1 8D       LDA   ($8D),Y
12C1-   AA          TAX
12C2-   8D A0 CC    STA   $CCA0
12C5-   C4 C1       CPY   $C1
12C7-   A0 C1       LDY   #$C1
12C9-   C4 C4       CPY   $C4
12CB-   D2 B3       CMP   ($B3)
12CD-   AB          ???
12CE-   B1 8D       LDA   ($8D),Y
12D0-   A0 C1       LDY   #$C1
12D2-   CE C4 A0    DEC   $A0C4
12D5-   A3          ???
12D6-   A4 C6       LDY   $C6
12D8-   B0 8D       BCS   $1267
12DA-   A0 CC       LDY   #$CC
12DC-   D3          ???
12DD-   D2 8D       CMP   ($8D)
12DF-   A0 CC       LDY   #$CC
12E1-   D3          ???
12E2-   D2 8D       CMP   ($8D)
12E4-   A0 CC       LDY   #$CC
12E6-   D3          ???
12E7-   D2 8D       CMP   ($8D)
12E9-   A0 CC       LDY   #$CC
12EB-   D3          ???
12EC-   D2 8D       CMP   ($8D)
12EE-   A0 D4       LDY   #$D4
12F0-   C1 D8       CMP   ($D8,X)
12F2-   8D A0 CC    STA   $CCA0
12F5-   C4 C1       CPY   $C1
12F7-   A0 C8       LDY   #$C8
12F9-   C5 D8       CMP   $D8
12FB-   D4          ???
12FC-   C1 C2       CMP   ($C2,X)
12FE-   AC D8 8D    LDY   $8DD8
1301-   A0 CA       LDY   #$CA
1303-   D3          ???
1304-   D2 A0       CMP   ($A0)
1306-   C3          ???
1307-   CF          ???
1308-   D5 D4       CMP   $D4,X
130A-   8D AA 8D    STA   $8DAA
130D-   A0 CC       LDY   #$CC
130F-   C4 C1       CPY   $C1
1311-   A0 C1       LDY   #$C1
1313-   C4 C4       CPY   $C4
1315-   D2 B3       CMP   ($B3)
1317-   AB          ???
1318-   B1 8D       LDA   ($8D),Y
131A-   A0 C1       LDY   #$C1
131C-   CE C4 A0    DEC   $A0C4
131F-   A3          ???
1320-   A4 B0       LDY   $B0
1322-   C6 8D       DEC   $8D
1324-   A0 D4       LDY   #$D4
1326-   C1 D8       CMP   ($D8,X)
1328-   8D A0 CC    STA   $CCA0
132B-   C4 C1       CPY   $C1
132D-   A0 C8       LDY   #$C8
132F-   C5 D8       CMP   $D8
1331-   D4          ???
1332-   C1 C2       CMP   ($C2,X)
1334-   AC D8 8D    LDY   $8DD8
1337-   A0 CA       LDY   #$CA
1339-   D3          ???
133A-   D2 A0       CMP   ($A0)
133C-   C3          ???
133D-   CF          ???
133E-   D5 D4       CMP   $D4,X
1340-   8D AA 8D    STA   $8DAA
1343-   A0 CC       LDY   #$CC
1345-   C4 C1       CPY   $C1
1347-   A0 C1       LDY   #$C1
1349-   C4 C4       CPY   $C4
134B-   D2 B3       CMP   ($B3)
134D-   8D A0 C1    STA   $C1A0
1350-   CE C4 A0    DEC   $A0C4
1353-   A3          ???
1354-   A4 C6       LDY   $C6
1356-   B0 8D       BCS   $12E5
1358-   A0 CC       LDY   #$CC
135A-   D3          ???
135B-   D2 8D       CMP   ($8D)
135D-   A0 CC       LDY   #$CC
135F-   D3          ???
1360-   D2 8D       CMP   ($8D)
1362-   A0 CC       LDY   #$CC
1364-   D3          ???
1365-   D2 8D       CMP   ($8D)
1367-   A0 CC       LDY   #$CC
1369-   D3          ???
136A-   D2 8D       CMP   ($8D)
136C-   A0 D4       LDY   #$D4
136E-   C1 D8       CMP   ($D8,X)
1370-   8D A0 CC    STA   $CCA0
1373-   C4 C1       CPY   $C1
1375-   A0 C8       LDY   #$C8
1377-   C5 D8       CMP   $D8
1379-   D4          ???
137A-   C1 C2       CMP   ($C2,X)
137C-   AC D8 8D    LDY   $8DD8
137F-   A0 CA       LDY   #$CA
1381-   D3          ???
1382-   D2 A0       CMP   ($A0)
1384-   C3          ???
1385-   CF          ???
1386-   D5 D4       CMP   $D4,X
1388-   8D A0 CC    STA   $CCA0
138B-   C4 C1       CPY   $C1
138D-   A0 C1       LDY   #$C1
138F-   C4 C4       CPY   $C4
1391-   D2 B3       CMP   ($B3)
1393-   8D A0 C1    STA   $C1A0
1396-   CE C4 A0    DEC   $A0C4
1399-   A3          ???
139A-   A4 B0       LDY   $B0
139C-   C6 8D       DEC   $8D
139E-   A0 D4       LDY   #$D4
13A0-   C1 D8       CMP   ($D8,X)
13A2-   8D A0 CC    STA   $CCA0
13A5-   C4 C1       CPY   $C1
13A7-   A0 C8       LDY   #$C8
13A9-   C5 D8       CMP   $D8
13AB-   D4          ???
13AC-   C1 C2       CMP   ($C2,X)
13AE-   AC D8 8D    LDY   $8DD8
13B1-   A0 CA       LDY   #$CA
13B3-   D3          ???
13B4-   D2 A0       CMP   ($A0)
13B6-   C3          ???
13B7-   CF          ???
13B8-   D5 D4       CMP   $D4,X
13BA-   8D AA 8D    STA   $8DAA
13BD-   A0 CC       LDY   #$CC
13BF-   C4 C1       CPY   $C1
13C1-   A0 A3       LDY   #$A3
13C3-   B1 B8       LDA   ($B8),Y
13C5-   B6 A0       LDX   $A0,Y
13C7-   BB          ???
13C8-   20 A2 BA    JSR   $BAA2
13CB-   A2 8D       LDX   #$8D
13CD-   A0 CA       LDY   #$CA
13CF-   D3          ???
13D0-   D2 A0       CMP   ($A0)
13D2-   C3          ???
13D3-   CF          ???
13D4-   D5 D4       CMP   $D4,X
13D6-   8D A0 CC    STA   $CCA0
13D9-   C4 C1       CPY   $C1
13DB-   A0 A3       LDY   #$A3
13DD-   B1 B6       LDA   ($B6),Y
13DF-   B0 A0       BCS   $1381
13E1-   A2 20       LDX   #$20
13E3-   A2 8D       LDX   #$8D
13E5-   A0 CA       LDY   #$CA
13E7-   D3          ???
13E8-   D2 A0       CMP   ($A0)
13EA-   C3          ???
13EB-   CF          ???
13EC-   D5 D4       CMP   $D4,X
13EE-   8D AA 8D    STA   $8DAA
13F1-   A0 CC       LDY   #$CC
13F3-   C4 D9       CPY   $D9
13F5-   A0 A3       LDY   #$A3
13F7-   B0 8D       BCS   $1386
13F9-   BA          TSX
13FA-   C4 CC       CPY   $CC
13FC-   D0 8D       BNE   $138B
13FE-   A0 CC       LDY   #$CC
1400-   C4 C1       CPY   $C1
1402-   A0 A8       LDY   #$A8
1404-   C1 C4       CMP   ($C4,X)
1406-   C4 D2       CPY   $D2
1408-   B3          ???
1409-   A9 AC       LDA   #$AC
140B-   D9 8D A0    CMP   $A08D,Y
140E-   C1 CE       CMP   ($CE,X)
1410-   C4 A0       CPY   $A0
1412-   A3          ???
1413-   A4 C6       LDY   $C6
1415-   B0 8D       BCS   $13A4
1417-   A0 CC       LDY   #$CC
1419-   D3          ???
141A-   D2 8D       CMP   ($8D)
141C-   A0 CC       LDY   #$CC
141E-   D3          ???
141F-   D2 8D       CMP   ($8D)
1421-   A0 CC       LDY   #$CC
1423-   D3          ???
1424-   D2 8D       CMP   ($8D)
1426-   A0 CC       LDY   #$CC
1428-   D3          ???
1429-   D2 8D       CMP   ($8D)
142B-   A0 D3       LDY   #$D3
142D-   D4          ???
142E-   C1 A0       CMP   ($A0,X)
1430-   CC C5 C6    CPY   $C6C5
1433-   D4          ???
1434-   8D A0 CC    STA   $CCA0
1437-   C4 C1       CPY   $C1
1439-   A0 A8       LDY   #$A8
143B-   C1 C4       CMP   ($C4,X)
143D-   C4 D2       CPY   $D2
143F-   B3          ???
1440-   A9 AC       LDA   #$AC
1442-   D9 8D A0    CMP   $A08D,Y
1445-   C1 CE       CMP   ($CE,X)
1447-   C4 A0       CPY   $A0
1449-   A3          ???
144A-   A4 B0       LDY   $B0
144C-   C6 8D       DEC   $8D
144E-   A0 D3       LDY   #$D3
1450-   D4          ???
1451-   C1 A0       CMP   ($A0,X)
1453-   D2 C9       CMP   ($C9)
1455-   C7          ???
1456-   C8          INY
1457-   D4          ???
1458-   8D A0 CC    STA   $CCA0
145B-   C4 D8       CPY   $D8
145D-   A0 CC       LDY   #$CC
145F-   C5 C6       CMP   $C6
1461-   D4          ???
1462-   8D A0 CC    STA   $CCA0
1465-   C4 C1       CPY   $C1
1467-   A0 C8       LDY   #$C8
1469-   C5 D8       CMP   $D8
146B-   D4          ???
146C-   C1 C2       CMP   ($C2,X)
146E-   AC D8 8D    LDY   $8DD8
1471-   A0 CA       LDY   #$CA
1473-   D3          ???
1474-   D2 A0       CMP   ($A0)
1476-   C3          ???
1477-   CF          ???
1478-   D5 D4       CMP   $D4,X
147A-   8D A0 CC    STA   $CCA0
147D-   C4 D8       CPY   $D8
147F-   A0 D2       LDY   #$D2
1481-   C9 C7       CMP   #$C7
1483-   C8          INY
1484-   D4          ???
1485-   8D A0 CC    STA   $CCA0
1488-   C4 C1       CPY   $C1
148A-   A0 C8       LDY   #$C8
148C-   C5 D8       CMP   $D8
148E-   D4          ???
148F-   C1 C2       CMP   ($C2,X)
1491-   AC D8 8D    LDY   $8DD8
1494-   A0 CA       LDY   #$CA
1496-   D3          ???
1497-   D2 A0       CMP   ($A0)
1499-   C3          ???
149A-   CF          ???
149B-   D5 D4       CMP   $D4,X
149D-   8D A0 CC    STA   $CCA0
14A0-   C4 C1       CPY   $C1
14A2-   A0 A3       LDY   #$A3
14A4-   B1 B6       LDA   ($B6),Y
14A6-   B0 8D       BCS   $1435
14A8-   A0 CA       LDY   #$CA
14AA-   D3          ???
14AB-   D2 A0       CMP   ($A0)
14AD-   C3          ???
14AE-   CF          ???
14AF-   D5 D4       CMP   $D4,X
14B1-   8D A0 C9    STA   $C9A0
14B4-   CE D9 8D    DEC   $8DD9
14B7-   A0 C3       LDY   #$C3
14B9-   D0 D9       BNE   $1494
14BB-   A0 A3       LDY   #$A3
14BD-   C2          ???
14BE-   D9 D4 C5    CMP   $C5D4,Y
14C1-   D3          ???
14C2-   8D A0 C2    STA   $C2A0
14C5-   CE C5 A0    DEC   $A0C5
14C8-   BA          TSX
14C9-   C4 CC       CPY   $CC
14CB-   D0 8D       BNE   $145A
14CD-   AA          TAX
14CE-   8D A0 D0    STA   $D0A0
14D1-   D2 CE       CMP   ($CE)
14D3-   A0 A2       LDY   #$A2
14D5-   20 A2 AC    JSR   $ACA2
14D8-   B8          CLV
14D9-   C4 8D       CPY   $8D
14DB-   AA          TAX
14DC-   8D A0 C9    STA   $C9A0
14DF-   CE C3 A0    DEC   $A0C3
14E2-   C3          ???
14E3-   CE D4 B1    DEC   $B1D4
14E6-   8D A0 CC    STA   $CCA0
14E9-   C4 C1       CPY   $C1
14EB-   A0 C3       LDY   #$C3
14ED-   CE D4 B1    DEC   $B1D4
14F0-   8D A0 C3    STA   $C3A0
14F3-   CD D0 A0    CMP   $A0D0
14F6-   A3          ???
14F7-   B2 B0       LDA   ($B0)
14F9-   8D A0 C2    STA   $C2A0
14FC-   CE C5 A0    DEC   $A0C5
14FF-   BA          TSX
1500-   CE CF D7    DEC   $D7CF
1503-   C1 C9       CMP   ($C9,X)
1505-   D4          ???
1506-   8D A0 DF    STA   $DFA0
1509-   D7          ???
150A-   C1 C9       CMP   ($C9,X)
150C-   D4          ???
150D-   8D A0 CC    STA   $CCA0
1510-   C4 C1       CPY   $C1
1512-   A0 A3       LDY   #$A3
1514-   B0 8D       BCS   $14A3
1516-   A0 D3       LDY   #$D3
1518-   D4          ???
1519-   C1 A0       CMP   ($A0,X)
151B-   C3          ???
151C-   CE D4 B1    DEC   $B1D4
151F-   8D BA CE    STA   $CEBA
1522-   CF          ???
1523-   D7          ???
1524-   C1 C9       CMP   ($C9,X)
1526-   D4          ???
1527-   8D A0 CC    STA   $CCA0
152A-   C4 C1       CPY   $C1
152C-   A0 CC       LDY   #$CC
152E-   C9 CE       CMP   #$CE
1530-   C5 8D       CMP   $8D
1532-   A0 C3       LDY   #$C3
1534-   CC C3 8D    CPY   $8DC3
1537-   A0 C1       LDY   #$C1
1539-   C4 C3       CPY   $C3
153B-   A0 A3       LDY   #$A3
153D-   C2          ???
153E-   D9 D4 C5    CMP   $C5D4,Y
1541-   D3          ???
1542-   8D A0 C2    STA   $C2A0
1545-   C3          ???
1546-   C3          ???
1547-   A0 BA       LDY   #$BA
1549-   CE CF C1    DEC   $C1CF
154C-   C4 C4       CPY   $C4
154E-   C8          INY
154F-   C9 8D       CMP   #$8D
1551-   A0 C9       LDY   #$C9
1553-   CE C3 A0    DEC   $A0C3
1556-   CC C9 CE    CPY   $CEC9
1559-   C5 AB       CMP   $AB
155B-   B1 8D       LDA   ($8D),Y
155D-   BA          TSX
155E-   CE CF C1    DEC   $C1CF
1561-   C4 C4       CPY   $C4
1563-   C8          INY
1564-   C9 8D       CMP   #$8D
1566-   AA          TAX
1567-   8D AA AA    STA   $AAAA
156A-   20 CE CF    JSR   $CFCE
156D-   D7          ???
156E-   20 C3 C8    JSR   $C8C3
1571-   C5 C3       CMP   $C3
1573-   CB          ???
1574-   20 C9 C6    JSR   $C6C9
1577-   20 BC BD    JSR   $BDBC
157A-   20 C2 C9    JSR   $C9C2
157D-   CE C1 D2    DEC   $D2C1
1580-   D9 20 CC    CMP   $CC20,Y
1583-   C5 CE       CMP   $CE
1585-   C7          ???
1586-   D4          ???
1587-   C8          INY
1588-   8D AA 8D    STA   $8DAA
158B-   A0 D3       LDY   #$D3
158D-   D4          ???
158E-   C1 A0       CMP   ($A0,X)
1590-   CC C9 CE    CPY   $CEC9
1593-   C5 8D       CMP   $8D
1595-   AA          TAX
1596-   8D A0 CC    STA   $CCA0
1599-   C4 C1       CPY   $C1
159B-   A0 CC       LDY   #$CC
159D-   C9 D3       CMP   #$D3
159F-   D4          ???
15A0-   C9 CE       CMP   #$CE
15A2-   C7          ???
15A3-   8D A0 C1    STA   $C1A0
15A6-   C4 C3       CPY   $C3
15A8-   A0 CC       LDY   #$CC
15AA-   C4 CC       CPY   $CC
15AC-   C5 CE       CMP   $CE
15AE-   8D A0 D3    STA   $D3A0
15B1-   D4          ???
15B2-   C1 A0       CMP   ($A0,X)
15B4-   D4          ???
15B5-   C5 CD       CMP   $CD
15B7-   D0 8D       BNE   $1546
15B9-   A0 CC       LDY   #$CC
15BB-   C4 C1       CPY   $C1
15BD-   A0 CC       LDY   #$CC
15BF-   C9 D3       CMP   #$D3
15C1-   D4          ???
15C2-   C9 CE       CMP   #$CE
15C4-   C7          ???
15C5-   AB          ???
15C6-   B1 8D       LDA   ($8D),Y
15C8-   A0 C1       LDY   #$C1
15CA-   C4 C3       CPY   $C3
15CC-   A0 CC       LDY   #$CC
15CE-   C4 CC       CPY   $CC
15D0-   C5 CE       CMP   $CE
15D2-   AB          ???
15D3-   B1 8D       LDA   ($8D),Y
15D5-   A0 D3       LDY   #$D3
15D7-   D4          ???
15D8-   C1 A0       CMP   ($A0,X)
15DA-   D4          ???
15DB-   C5 CD       CMP   $CD
15DD-   D0 AB       BNE   $158A
15DF-   B1 8D       LDA   ($8D),Y
15E1-   AA          TAX
15E2-   8D A0 CC    STA   $CCA0
15E5-   C4 C1       CPY   $C1
15E7-   A0 CC       LDY   #$CC
15E9-   C9 CE       CMP   #$CE
15EB-   C5 AB       CMP   $AB
15ED-   B1 8D       LDA   ($8D),Y
15EF-   A0 C3       LDY   #$C3
15F1-   CD D0 A0    CMP   $A0D0
15F4-   D4          ???
15F5-   C5 CD       CMP   $CD
15F7-   D0 AB       BNE   $15A4
15F9-   B1 8D       LDA   ($8D),Y
15FB-   A0 C2       LDY   #$C2
15FD-   CE C5 A0    DEC   $A0C5
1600-   BA          TSX
1601-   D2 C5       CMP   ($C5)
1603-   CC CF CF    CPY   $CFCF
1606-   D0 8D       BNE   $1595
1608-   A0 CC       LDY   #$CC
160A-   C4 C1       CPY   $C1
160C-   A0 CC       LDY   #$CC
160E-   C9 CE       CMP   #$CE
1610-   C5 8D       CMP   $8D
1612-   A0 C3       LDY   #$C3
1614-   CD D0 A0    CMP   $A0D0
1617-   D4          ???
1618-   C5 CD       CMP   $CD
161A-   D0 8D       BNE   $15A9
161C-   A0 C2       LDY   #$C2
161E-   C5 D1       CMP   $D1
1620-   A0 BA       LDY   #$BA
1622-   D2 C5       CMP   ($C5)
1624-   CC CF CF    CPY   $CFCF
1627-   D0 8D       BNE   $15B6
1629-   A0 C2       LDY   #$C2
162B-   C3          ???
162C-   D3          ???
162D-   A0 BA       LDY   #$BA
162F-   D1 D5       CMP   ($D5),Y
1631-   C9 D4       CMP   #$D4
1633-   CC D0 8D    CPY   $8DD0
1636-   BA          TSX
1637-   D2 C5       CMP   ($C5)
1639-   CC CF CF    CPY   $CFCF
163C-   D0 8D       BNE   $15CB
163E-   A0 CA       LDY   #$CA
1640-   CD D0 A0    CMP   $A0D0
1643-   BA          TSX
1644-   C8          INY
1645-   C5 D8       CMP   $D8
1647-   CC D0 B1    CPY   $B1D0
164A-   8D BA D1    STA   $D1BA
164D-   D5 C9       CMP   $C9,X
164F-   D4          ???
1650-   CC D0 8D    CPY   $8DD0
1653-   A0 D2       LDY   #$D2
1655-   D4          ???
1656-   D3          ???
1657-   8D BA D4    STA   $D4BA
165A-   D8          CLD
165B-   D4          ???
165C-   C4 C9       CPY   $C9
165E-   D3          ???
165F-   D0 8D       BNE   $15EE
1661-   A0 C5       LDY   #$C5
1663-   D2 D2       CMP   ($D2)
1665-   C8          INY
1666-   A0 A3       LDY   #$A3
1668-   BA          TSX
1669-   C2          ???
166A-   C1 D3       CMP   ($D3,X)
166C-   C9 C3       CMP   #$C3
166E-   8D A0 D3    STA   $D3A0
1671-   C3          ???
1672-   C1 D4       CMP   ($D4,X)
1674-   A0 A2       LDY   #$A2
1676-   CF          ???
1677-   D0 C5       BNE   $163E
1679-   CE 20 A2    DEC   $A220
167C-   BB          ???
167D-   A3          ???
167E-   C6 CE       DEC   $CE
1680-   C1 CD       CMP   ($CD,X)
1682-   C5 BB       CMP   $BB
1684-   A3          ???
1685-   B1 B0       LDA   ($B0),Y
1687-   B0 8D       BCS   $1616
1689-   A0 C3       LDY   #$C3
168B-   CD C4 A0    CMP   $A0C4
168E-   A3          ???
168F-   D2 C5       CMP   ($C5)
1691-   D4          ???
1692-   D5 D2       CMP   $D2,X
1694-   CE 8D A0    DEC   $A08D
1697-   D3          ???
1698-   C3          ???
1699-   C1 D4       CMP   ($D4,X)
169B-   A0 A2       LDY   #$A2
169D-   D2 C5       CMP   ($C5)
169F-   C1 C4       CMP   ($C4,X)
16A1-   20 A2 BB    JSR   $BBA2
16A4-   A3          ???
16A5-   C6 CE       DEC   $CE
16A7-   C1 CD       CMP   ($CD,X)
16A9-   C5 BB       CMP   $BB
16AB-   A3          ???
16AC-   B1 B0       LDA   ($B0),Y
16AE-   B0 8D       BCS   $163D
16B0-   A0 C3       LDY   #$C3
16B2-   CD C4 A0    CMP   $A0C4
16B5-   A3          ???
16B6-   D2 C5       CMP   ($C5)
16B8-   D4          ???
16B9-   D5 D2       CMP   $D2,X
16BB-   CE 8D A0    DEC   $A08D
16BE-   C5 D2       CMP   $D2
16C0-   D2 C8       CMP   ($C8)
16C2-   A0 A3       LDY   #$A3
16C4-   BA          TSX
16C5-   D4          ???
16C6-   D8          CLD
16C7-   D4          ???
16C8-   C4 CF       CPY   $CF
16CA-   CE C5 8D    DEC   $8DC5
16CD-   A0 CC       LDY   #$CC
16CF-   C4 D9       CPY   $D9
16D1-   A0 A3       LDY   #$A3
16D3-   B0 8D       BCS   $1662
16D5-   A0 D3       LDY   #$D3
16D7-   D4          ???
16D8-   D9 A0 C3    CMP   $C3A0,Y
16DB-   CE D4 B2    DEC   $B2D4
16DE-   8D BA D4    STA   $D4BA
16E1-   CC D0 B0    CPY   $B0D0
16E4-   8D A0 CC    STA   $CCA0
16E7-   C4 D9       CPY   $D9
16E9-   A0 A3       LDY   #$A3
16EB-   B1 8D       LDA   ($8D),Y
16ED-   A0 D3       LDY   #$D3
16EF-   D4          ???
16F0-   D9 A0 C3    CMP   $C3A0,Y
16F3-   CE D4 B1    DEC   $B1D4
16F6-   8D BA D4    STA   $D4BA
16F9-   CC D0 B1    CPY   $B1D0
16FC-   8D A0 C7    STA   $C7A0
16FF-   CB          ???
1700-   C5 D9       CMP   $D9
1702-   8D A0 CC    STA   $CCA0
1705-   C4 D9       CPY   $D9
1707-   A0 C3       LDY   #$C3
1709-   CE D4 B1    DEC   $B1D4
170C-   8D AA C1    STA   $C1AA
170F-   CE C4 20    DEC   $20C4
1712-   A3          ???
1713-   A4 B0       LDY   $B0
1715-   C6 8D       DEC   $8D
1717-   A0 D3       LDY   #$D3
1719-   D4          ???
171A-   C1 A0       CMP   ($A0,X)
171C-   CC C9 CE    CPY   $CEC9
171F-   C5 AC       CMP   $AC
1721-   D9 8D A0    CMP   $A08D,Y
1724-   C3          ???
1725-   CD D0 A0    CMP   $A0D0
1728-   A3          ???
1729-   A4 B8       LDY   $B8
172B-   C4 A0       CPY   $A0
172D-   BB          ???
172E-   20 C9 D3    JSR   $D3C9
1731-   20 C9 D4    JSR   $D4C9
1734-   20 D2 C5    JSR   $C5D2
1737-   D4          ???
1738-   D5 D2       CMP   $D2,X
173A-   CE 20 C3    DEC   $C320
173D-   C8          INY
173E-   C1 D2       CMP   ($D2,X)
1740-   BF          ???
1741-   8D A0 C2    STA   $C2A0
1744-   C5 D1       CMP   $D1
1746-   A0 BA       LDY   #$BA
1748-   D4          ???
1749-   C3          ???
174A-   CF          ???
174B-   CE D4 8D    DEC   $8DD4
174E-   A0 C3       LDY   #$C3
1750-   D0 D9       BNE   $172B
1752-   A0 A3       LDY   #$A3
1754-   B2 B5       LDA   ($B5)
1756-   B5 8D       LDA   $8D,X
1758-   A0 C2       LDY   #$C2
175A-   C5 D1       CMP   $D1
175C-   A0 BA       LDY   #$BA
175E-   D4          ???
175F-   C3          ???
1760-   CF          ???
1761-   CE D4 8D    DEC   $8DD4
1764-   A0 C9       LDY   #$C9
1766-   CE C3 A0    DEC   $A0C3
1769-   C3          ???
176A-   CE D4 B1    DEC   $B1D4
176D-   8D A0 CA    STA   $CAA0
1770-   CD D0 A0    CMP   $A0D0
1773-   BA          TSX
1774-   D4          ???
1775-   CC D0 B1    CPY   $B1D0
1778-   8D BA D4    STA   $D4BA
177B-   C3          ???
177C-   CF          ???
177D-   CE D4 8D    DEC   $8DD4
1780-   A0 C9       LDY   #$C9
1782-   CE C3 A0    DEC   $A0C3
1785-   C3          ???
1786-   CE D4 B2    DEC   $B2D4
1789-   8D A0 CC    STA   $CCA0
178C-   C4 D9       CPY   $D9
178E-   A0 C3       LDY   #$C3
1790-   CE D4 B1    DEC   $B1D4
1793-   8D A0 D3    STA   $D3A0
1796-   D4          ???
1797-   D9 A0 CC    CMP   $CCA0,Y
179A-   C9 CE       CMP   #$CE
179C-   C5 A0       CMP   $A0
179E-   BB          ???
179F-   20 D3 D4    JSR   $D4D3
17A2-   CF          ???
17A3-   D2 C5       CMP   ($C5)
17A5-   20 CC C5    JSR   $C5CC
17A8-   CE C7 D4    DEC   $D4C7
17AB-   C8          INY
17AC-   8D A0 D3    STA   $D3A0
17AF-   D0 D2       BNE   $1783
17B1-   CE A0 A3    DEC   $A3A0
17B4-   CC C9 CE    CPY   $CEC9
17B7-   C5 8D       CMP   $8D
17B9-   A0 CC       LDY   #$CC
17BB-   C4 D9       CPY   $D9
17BD-   A0 C3       LDY   #$C3
17BF-   CE D4 B2    DEC   $B2D4
17C2-   8D A0 C3    STA   $C3A0
17C5-   D0 D9       BNE   $17A0
17C7-   A0 A3       LDY   #$A3
17C9-   B2 B0       LDA   ($B0)
17CB-   8D A0 C2    STA   $C2A0
17CE-   CE C5 A0    DEC   $A0C5
17D1-   BA          TSX
17D2-   D4          ???
17D3-   C3          ???
17D4-   CF          ???
17D5-   CE 8D BA    DEC   $BA8D
17D8-   CB          ???
17D9-   D7          ???
17DA-   8D A0 CC    STA   $CCA0
17DD-   C4 C1       CPY   $C1
17DF-   A0 A4       LDY   #$A4
17E1-   C3          ???
17E2-   B0 B0       BCS   $1794
17E4-   B0 A0       BCS   $1786
17E6-   BB          ???
17E7-   20 C3 C8    JSR   $C8C3
17EA-   C5 C3       CMP   $C3
17EC-   CB          ???
17ED-   20 C6 CF    JSR   $CFC6
17F0-   D2 20       CMP   ($20)
17F2-   CB          ???
17F3-   C5 D9       CMP   $D9
17F5-   D0 D2       BNE   $17C9
17F7-   C5 D3       CMP   $D3
17F9-   D3          ???
17FA-   8D A0 C2    STA   $C2A0
17FD-   D0 CC       BNE   $17CB
17FF-   A0 BA       LDY   #$BA
1801-   CB          ???
1802-   D7          ???
1803-   A0 BB       LDY   #$BB
1805-   20 CB C5    JSR   $C5CB
1808-   C5 D0       CMP   $D0
180A-   20 D7 C1    JSR   $C1D7
180D-   C9 D4       CMP   #$D4
180F-   C9 CE       CMP   #$CE
1811-   C7          ???
1812-   8D A0 C1    STA   $C1A0
1815-   CE C4 A0    DEC   $A0C4
1818-   A3          ???
1819-   A4 B7       LDY   $B7
181B-   C6 A0       DEC   $A0
181D-   BB          ???
181E-   20 D4 D5    JSR   $D5D4
1821-   D2 CE       CMP   ($CE)
1823-   20 CF C6    JSR   $C6CF
1826-   C6 20       DEC   $20
1828-   C2          ???
1829-   C9 D4       CMP   #$D4
182B-   20 B7 8D    JSR   $8DB7
182E-   A0 D3       LDY   #$D3
1830-   D4          ???
1831-   C1 A0       CMP   ($A0,X)
1833-   A4 C3       LDY   $C3
1835-   B0 B1       BCS   $17E8
1837-   B0 A0       BCS   $17D9
1839-   BB          ???
183A-   20 C3 CC    JSR   $CCC3
183D-   C5 C1       CMP   $C1
183F-   D2 20       CMP   ($20)
1841-   CB          ???
1842-   C5 D9       CMP   $D9
1844-   C2          ???
1845-   CF          ???
1846-   C1 D2       CMP   ($D2,X)
1848-   C4 20       CPY   $20
184A-   D3          ???
184B-   D4          ???
184C-   D2 CF       CMP   ($CF)
184E-   C2          ???
184F-   C5 8D       CMP   $8D
1851-   A0 CC       LDY   #$CC
1853-   C4 D9       CPY   $D9
1855-   A0 A3       LDY   #$A3
1857-   B0 8D       BCS   $17E6
1859-   A0 D3       LDY   #$D3
185B-   D4          ???
185C-   D9 A0 C3    CMP   $C3A0,Y
185F-   CE D4 B2    DEC   $B2D4
1862-   8D BA D4    STA   $D4BA
1865-   C3          ???
1866-   CF          ???
1867-   CE 8D A0    DEC   $A08D
186A-   CA          DEX
186B-   CD D0 A0    CMP   $A0D0
186E-   BA          TSX
186F-   D4          ???
1870-   CC D0 B0    CPY   $B0D0
1873-   8D BA D4    STA   $D4BA
1876-   D8          CLD
1877-   D4          ???
1878-   C4 CF       CPY   $CF
187A-   CE C5 8D    DEC   $8DC5
187D-   A0 D3       LDY   #$D3
187F-   C3          ???
1880-   C1 D4       CMP   ($D4,X)
1882-   A0 A2       LDY   #$A2
1884-   C3          ???
1885-   CC CF D3    CPY   $D3CF
1888-   C5 20       CMP   $20
188A-   A2 BB       LDX   #$BB
188C-   A3          ???
188D-   C6 CE       DEC   $CE
188F-   C1 CD       CMP   ($CD,X)
1891-   C5 BB       CMP   $BB
1893-   A3          ???
1894-   B1 B0       LDA   ($B0),Y
1896-   B0 8D       BCS   $1825
1898-   A0 C3       LDY   #$C3
189A-   CD C4 A0    CMP   $A0C4
189D-   A3          ???
189E-   D2 C5       CMP   ($C5)
18A0-   D4          ???
18A1-   D5 D2       CMP   $D2,X
18A3-   CE 8D A0    DEC   $A08D
18A6-   D0 CC       BNE   $1874
18A8-   C1 8D       CMP   ($8D,X)
18AA-   A0 CA       LDY   #$CA
18AC-   CD D0 A0    CMP   $A0D0
18AF-   D2 C5       CMP   ($C5)
18B1-   C5 CE       CMP   $CE
18B3-   D4          ???
18B4-   D2 D9       CMP   ($D9)
18B6-   8D AA 8D    STA   $8DAA
18B9-   AA          TAX
18BA-   AA          TAX
18BB-   AA          TAX
18BC-   20 C2 C1    JSR   $C1C2
18BF-   D3          ???
18C0-   C9 C3       CMP   #$C3
18C2-   20 CC C9    JSR   $C9CC
18C5-   D3          ???
18C6-   D4          ???
18C7-   C9 CE       CMP   #$CE
18C9-   C7          ???
18CA-   8D AA 8D    STA   $8DAA
18CD-   BA          TSX
18CE-   C2          ???
18CF-   C1 D3       CMP   ($D3,X)
18D1-   C9 C3       CMP   #$C3
18D3-   8D A0 C3    STA   $C3A0
18D6-   CD C4 A0    CMP   $A0C4
18D9-   A2 C3       LDX   #$C3
18DB-   CC CF D3    CPY   $D3CF
18DE-   C5 A2       CMP   $A2
18E0-   8D A0 D0    STA   $D0A0
18E3-   D2 CE       CMP   ($CE)
18E5-   A0 A2       LDY   #$A2
18E7-   D4          ???
18E8-   D9 D0 C5    CMP   $C5D0,Y
18EB-   20 DB CC    JSR   $CCDB
18EE-   C9 D3       CMP   #$D3
18F0-   D4          ???
18F1-   DD 20 D4    CMP   $D420,X
18F4-   CF          ???
18F5-   20 D2 C5    JSR   $C5D2
18F8-   C1 C4       CMP   ($C4,X)
18FA-   A2 AC       LDX   #$AC
18FC-   B8          CLV
18FD-   C4 8D       CPY   $8D
18FF-   A0 D0       LDY   #$D0
1901-   D2 CE       CMP   ($CE)
1903-   A0 A2       LDY   #$A2
1905-   D4          ???
1906-   C8          INY
1907-   C5 20       CMP   $20
1909-   C2          ???
190A-   C1 D3       CMP   ($D3,X)
190C-   C9 C3       CMP   #$C3
190E-   20 CC C9    JSR   $C9CC
1911-   D3          ???
1912-   D4          ???
1913-   C9 CE       CMP   #$CE
1915-   C7          ???
1916-   AE A2 AC    LDX   $ACA2
1919-   B8          CLV
191A-   C4 B8       CPY   $B8
191C-   C4 8D       CPY   $8D
191E-   A0 D3       LDY   #$D3
1920-   C3          ???
1921-   C1 D4       CMP   ($D4,X)
1923-   A0 A2       LDY   #$A2
1925-   CC CF C1    CPY   $C1CF
1928-   C4 20       CPY   $20
192A-   A2 BB       LDX   #$BB
192C-   A3          ???
192D-   C6 CE       DEC   $CE
192F-   C1 CD       CMP   ($CD,X)
1931-   C5 BB       CMP   $BB
1933-   A3          ???
1934-   B1 B0       LDA   ($B0),Y
1936-   B0 8D       BCS   $18C5
1938-   A0 C3       LDY   #$C3
193A-   CD C4 A0    CMP   $A0C4
193D-   A3          ???
193E-   D2 C5       CMP   ($C5)
1940-   D4          ???
1941-   D5 D2       CMP   $D2,X
1943-   CE 8D A0    DEC   $A08D
1946-   CA          DEX
1947-   CD D0 A0    CMP   $A0D0
194A-   D2 C5       CMP   ($C5)
194C-   C5 CE       CMP   $CE
194E-   D4          ???
194F-   D2 D9       CMP   ($D9)
1951-   8D AA 8D    STA   $8DAA
1954-   AA          TAX
1955-   AA          TAX
1956-   AA          TAX
1957-   AA          TAX
1958-   AA          TAX
1959-   AA          TAX
195A-   AA          TAX
195B-   AA          TAX
195C-   AA          TAX
195D-   AA          TAX
195E-   AA          TAX
195F-   AA          TAX
1960-   AA          TAX
1961-   AA          TAX
1962-   AA          TAX
1963-   AA          TAX
1964-   AA          TAX
1965-   AA          TAX
1966-   AA          TAX
1967-   AA          TAX
1968-   AA          TAX
1969-   AA          TAX
196A-   AA          TAX
196B-   AA          TAX
196C-   AA          TAX
196D-   AA          TAX
196E-   AA          TAX
196F-   AA          TAX
1970-   AA          TAX
1971-   AA          TAX
1972-   AA          TAX
1973-   AA          TAX
1974-   8D AA 20    STA   $20AA
1977-   20 20 20    JSR   $2020
197A-   20 20 20    JSR   $2020
197D-   20 20 20    JSR   $2020
1980-   20 20 20    JSR   $2020
1983-   20 20 20    JSR   $2020
1986-   20 20 20    JSR   $2020
1989-   20 20 20    JSR   $2020
198C-   20 20 20    JSR   $2020
198F-   20 20 20    JSR   $2020
1992-   20 20 AA    JSR   $AA20
1995-   8D AA 20    STA   $20AA
1998-   D6 C1       DEC   $C1,X
199A-   D2 C9       CMP   ($C9)
199C-   C1 C2       CMP   ($C2,X)
199E-   CC C5 D3    CPY   $D3C5
19A1-   20 20 20    JSR   $2020
19A4-   20 20 20    JSR   $2020
19A7-   20 20 20    JSR   $2020
19AA-   20 20 20    JSR   $2020
19AD-   20 20 20    JSR   $2020
19B0-   20 20 20    JSR   $2020
19B3-   20 20 AA    JSR   $AA20
19B6-   8D AA 20    STA   $20AA
19B9-   20 20 20    JSR   $2020
19BC-   20 20 20    JSR   $2020
19BF-   20 20 20    JSR   $2020
19C2-   20 20 20    JSR   $2020
19C5-   20 20 20    JSR   $2020
19C8-   20 20 20    JSR   $2020
19CB-   20 20 20    JSR   $2020
19CE-   20 20 20    JSR   $2020
19D1-   20 20 20    JSR   $2020
19D4-   20 20 AA    JSR   $AA20
19D7-   8D AA AA    STA   $AAAA
19DA-   AA          TAX
19DB-   AA          TAX
19DC-   AA          TAX
19DD-   AA          TAX
19DE-   AA          TAX
19DF-   AA          TAX
19E0-   AA          TAX
19E1-   AA          TAX
19E2-   AA          TAX
19E3-   AA          TAX
19E4-   AA          TAX
19E5-   AA          TAX
19E6-   AA          TAX
19E7-   AA          TAX
19E8-   AA          TAX
19E9-   AA          TAX
19EA-   AA          TAX
19EB-   AA          TAX
19EC-   AA          TAX
19ED-   AA          TAX
19EE-   AA          TAX
19EF-   AA          TAX
19F0-   AA          TAX
19F1-   AA          TAX
19F2-   AA          TAX
19F3-   AA          TAX
19F4-   AA          TAX
19F5-   AA          TAX
19F6-   AA          TAX
19F7-   AA          TAX
19F8-   8D AA 8D    STA   $8DAA
19FB-   C6 D4       DEC   $D4
19FD-   D9 D0 C5    CMP   $C5D0,Y
1A00-   A0 C4       LDY   #$C4
1A02-   D3          ???
1A03-   A0 B2       LDY   #$B2
1A05-   8D D4 C6    STA   $C6D4
1A08-   CF          ???
1A09-   D5 CE       CMP   $CE,X
1A0B-   C4 A0       CPY   $A0
1A0D-   C4 D3       CPY   $D3
1A0F-   A0 B1       LDY   #$B1
1A11-   8D C6 CE    STA   $CEC6
1A14-   C1 CD       CMP   ($CD,X)
1A16-   C5 A0       CMP   $A0
1A18-   C4 D3       CPY   $D3
1A1A-   A0 B5       LDY   #$B5
1A1C-   B0 8D       BCS   $19AB
1A1E-   C3          ???
1A1F-   CE D4 B1    DEC   $B1D4
1A22-   A0 C4       LDY   #$C4
1A24-   D3          ???
1A25-   A0 B2       LDY   #$B2
1A27-   8D C3 CE    STA   $CEC3
1A2A-   D4          ???
1A2B-   B2 A0       LDA   ($A0)
1A2D-   C4 D3       CPY   $D3
1A2F-   A0 B1       LDY   #$B1
1A31-   8D D4 C5    STA   $C5D4
1A34-   CD D0 A0    CMP   $A0D0
1A37-   C4 D3       CPY   $D3
1A39-   A0 B2       LDY   #$B2
1A3B-   8D CC C4    STA   $C4CC
1A3E-   C1 C4       CMP   ($C4,X)
1A40-   C4 D2       CPY   $D2
1A42-   A0 C4       LDY   #$C4
1A44-   D3          ???
1A45-   A0 B2       LDY   #$B2
1A47-   8D CC C4    STA   $C4CC
1A4A-   CC C5 CE    CPY   $CEC5
1A4D-   A0 C4       LDY   #$C4
1A4F-   D3          ???
1A50-   A0 B2       LDY   #$B2
1A52-   8D CC C5    STA   $C5CC
1A55-   C6 D4       DEC   $D4
1A57-   A0 C4       LDY   #$C4
1A59-   D3          ???
1A5A-   A0 B1       LDY   #$B1
1A5C-   8D D2 C9    STA   $C9D2
1A5F-   C7          ???
1A60-   C8          INY
1A61-   D4          ???
1A62-   A0 C4       LDY   #$C4
1A64-   D3          ???
1A65-   A0 B2       LDY   #$B2
1A67-   8D CC C9    STA   $C9CC
1A6A-   CE C5 A0    DEC   $A0C5
1A6D-   C4 D3       CPY   $D3
1A6F-   A0 B2       LDY   #$B2
1A71-   B5 B6       LDA   $B6,X
1A73-   8D C2 CC    STA   $CCC2
1A76-   CF          ???
1A77-   C1 C4       CMP   ($C4,X)
1A79-   B1 A0       LDA   ($A0),Y
1A7B-   C4 D3       CPY   $D3
1A7D-   A0 B2       LDY   #$B2
1A7F-   B5 B6       LDA   $B6,X
1A81-   8D C2 CC    STA   $CCC2
1A84-   CF          ???
1A85-   C1 C4       CMP   ($C4,X)
1A87-   B2 A0       LDA   ($A0)
1A89-   C4 D3       CPY   $D3
1A8B-   A0 B2       LDY   #$B2
1A8D-   B5 B6       LDA   $B6,X
1A8F-   8D AA 8D    STA   $8DAA
1A92-   AA          TAX
1A93-   AA          TAX
1A94-   AA          TAX
1A95-   AA          TAX
1A96-   AA          TAX
1A97-   AA          TAX
1A98-   AA          TAX
1A99-   AA          TAX
1A9A-   AA          TAX
1A9B-   AA          TAX
1A9C-   AA          TAX
1A9D-   AA          TAX
1A9E-   AA          TAX
1A9F-   AA          TAX
1AA0-   AA          TAX
1AA1-   AA          TAX
1AA2-   AA          TAX
1AA3-   AA          TAX
1AA4-   AA          TAX
1AA5-   AA          TAX
1AA6-   AA          TAX
1AA7-   AA          TAX
1AA8-   AA          TAX
1AA9-   AA          TAX
1AAA-   AA          TAX
1AAB-   AA          TAX
1AAC-   AA          TAX
1AAD-   AA          TAX
1AAE-   AA          TAX
1AAF-   AA          TAX
1AB0-   AA          TAX
1AB1-   AA          TAX
1AB2-   8D AA 20    STA   $20AA
1AB5-   20 20 20    JSR   $2020
1AB8-   20 20 20    JSR   $2020
1ABB-   20 20 20    JSR   $2020
1ABE-   20 20 20    JSR   $2020
1AC1-   20 20 20    JSR   $2020
1AC4-   20 20 20    JSR   $2020
1AC7-   20 20 20    JSR   $2020
1ACA-   20 20 20    JSR   $2020
1ACD-   20 20 20    JSR   $2020
1AD0-   20 20 AA    JSR   $AA20
1AD3-   8D AA 20    STA   $20AA
1AD6-   20 CC CF    JSR   $CFCC
1AD9-   D7          ???
1ADA-   AD CC C5    LDA   $C5CC
1ADD-   D6 C5       DEC   $C5,X
1ADF-   CC 20 D2    CPY   $D220
1AE2-   CF          ???
1AE3-   D5 D4       CMP   $D4,X
1AE5-   C9 CE       CMP   #$CE
1AE7-   C5 D3       CMP   $D3
1AE9-   20 20 20    JSR   $2020
1AEC-   20 20 20    JSR   $2020
1AEF-   20 20 20    JSR   $2020
1AF2-   20 AA 8D    JSR   $8DAA
1AF5-   AA          TAX
1AF6-   20 20 20    JSR   $2020
1AF9-   20 20 20    JSR   $2020
1AFC-   20 20 20    JSR   $2020
1AFF-   20 20 20    JSR   $2020
1B02-   20 20 20    JSR   $2020
1B05-   20 20 20    JSR   $2020
1B08-   20 20 20    JSR   $2020
1B0B-   20 20 20    JSR   $2020
1B0E-   20 20 20    JSR   $2020
1B11-   20 20 20    JSR   $2020
1B14-   AA          TAX
1B15-   8D AA AA    STA   $AAAA
1B18-   AA          TAX
1B19-   AA          TAX
1B1A-   AA          TAX
1B1B-   AA          TAX
1B1C-   AA          TAX
1B1D-   AA          TAX
1B1E-   AA          TAX
1B1F-   AA          TAX
1B20-   AA          TAX
1B21-   AA          TAX
1B22-   AA          TAX
1B23-   AA          TAX
1B24-   AA          TAX
1B25-   AA          TAX
1B26-   AA          TAX
1B27-   AA          TAX
1B28-   AA          TAX
1B29-   AA          TAX
1B2A-   AA          TAX
1B2B-   AA          TAX
1B2C-   AA          TAX
1B2D-   AA          TAX
1B2E-   AA          TAX
1B2F-   AA          TAX
1B30-   AA          TAX
1B31-   AA          TAX
1B32-   AA          TAX
1B33-   AA          TAX
1B34-   AA          TAX
1B35-   AA          TAX
1B36-   8D AA 8D    STA   $8DAA
1B39-   A0 D0       LDY   #$D0
1B3B-   D5 D4       CMP   $D4,X
1B3D-   A0 CD       LDY   #$CD
1B3F-   C9 CE       CMP   #$CE
1B41-   AE CC C9    LDX   $C9CC
1B44-   C2          ???
1B45-   AE D2 C5    LDX   $C5D2
1B48-   D1 D5       CMP   ($D5),Y
1B4A-   C9 D2       CMP   #$D2
1B4C-   C5 C4       CMP   $C4
1B4E-   8D AA 8D    STA   $8DAA
1B51-   AA          TAX
1B52-   AA          TAX
1B53-   20 C9 CE    JSR   $CEC9
1B56-   C4 C9       CPY   $C9
1B58-   D6 C9       DEC   $C9,X
1B5A-   C4 D5       CPY   $D5
1B5C-   C1 CC       CMP   ($CC,X)
1B5E-   20 D3 D5    JSR   $D5D3
1B61-   C2          ???
1B62-   D2 CF       CMP   ($CF)
1B64-   D5 D4       CMP   $D4,X
1B66-   C9 CE       CMP   #$CE
1B68-   C5 D3       CMP   $D3
1B6A-   8D AA 8D    STA   $8DAA
1B6D-   AA          TAX
1B6E-   AA          TAX
1B6F-   AA          TAX
1B70-   20 C6 C9    JSR   $C9C6
1B73-   CC C5 C9    CPY   $C9C5
1B76-   CF          ???
1B77-   8D AA 8D    STA   $8DAA
1B7A-   A0 D0       LDY   #$D0
1B7C-   D5 D4       CMP   $D4,X
1B7E-   A0 CD       LDY   #$CD
1B80-   C9 CE       CMP   #$CE
1B82-   AE D3 D5    LDX   $D5D3
1B85-   C2          ???
1B86-   AE C6 D0    LDX   $D0C6
1B89-   D2 C9       CMP   ($C9)
1B8B-   CE D4 8D    DEC   $8DD4
1B8E-   A0 D0       LDY   #$D0
1B90-   D5 D4       CMP   $D4,X
1B92-   A0 CD       LDY   #$CD
1B94-   C9 CE       CMP   #$CE
1B96-   AE D3 D5    LDX   $D5D3
1B99-   C2          ???
1B9A-   AE C4 CF    LDX   $CFC4
1B9D-   D3          ???
1B9E-   C3          ???
1B9F-   CD C4 8D    CMP   $8DC4
1BA2-   A0 D0       LDY   #$D0
1BA4-   D5 D4       CMP   $D4,X
1BA6-   A0 CD       LDY   #$CD
1BA8-   C9 CE       CMP   #$CE
1BAA-   AE D3 D5    LDX   $D5D3
1BAD-   C2          ???
1BAE-   AE C6 D0    LDX   $D0C6
1BB1-   D3          ???
1BB2-   D4          ???
1BB3-   D2 8D       CMP   ($8D)
1BB5-   AA          TAX
1BB6-   8D AA AA    STA   $AAAA
1BB9-   AA          TAX
1BBA-   20 D3 D4    JSR   $D4D3
1BBD-   C4 C9       CPY   $C9
1BBF-   CF          ???
1BC0-   8D AA 8D    STA   $8DAA
1BC3-   A0 D0       LDY   #$D0
1BC5-   D5 D4       CMP   $D4,X
1BC7-   A0 CD       LDY   #$CD
1BC9-   C9 CE       CMP   #$CE
1BCB-   AE D3 D5    LDX   $D5D3
1BCE-   C2          ???
1BCF-   AE C4 D0    LDX   $D0C4
1BD2-   D2 C9       CMP   ($C9)
1BD4-   CE D4 8D    DEC   $8DD4
1BD7-   A0 D0       LDY   #$D0
1BD9-   D5 D4       CMP   $D4,X
1BDB-   A0 CD       LDY   #$CD
1BDD-   C9 CE       CMP   #$CE
1BDF-   AE D3 D5    LDX   $D5D3
1BE2-   C2          ???
1BE3-   AE D8 D0    LDX   $D0D8
1BE6-   D2 C9       CMP   ($C9)
1BE8-   CE D4 8D    DEC   $8DD4
1BEB-   A0 D0       LDY   #$D0
1BED-   D5 D4       CMP   $D4,X
1BEF-   A0 CD       LDY   #$CD
1BF1-   C9 CE       CMP   #$CE
1BF3-   AE D3 D5    LDX   $D5D3
1BF6-   C2          ???
1BF7-   AE D3 C9    LDX   $C9D3
1BFA-   CE D0 D5    DEC   $D5D0
1BFD-   D4          ???
1BFE-   8D AA 8D    STA   $8DAA
1C01-   AA          TAX
1C02-   AA          TAX
1C03-   AA          TAX
1C04-   20 D3 D4    JSR   $D4D3
1C07-   D2 C9       CMP   ($C9)
1C09-   CE C7 D3    DEC   $D3C7
1C0C-   8D AA 8D    STA   $8DAA
1C0F-   A0 D0       LDY   #$D0
1C11-   D5 D4       CMP   $D4,X
1C13-   A0 CD       LDY   #$CD
1C15-   C9 CE       CMP   #$CE
1C17-   AE D3 D5    LDX   $D5D3
1C1A-   C2          ???
1C1B-   AE D3 D4    LDX   $D4D3
1C1E-   D2 C3       CMP   ($C3)
1C20-   C1 D4       CMP   ($D4,X)
1C22-   8D A0 D0    STA   $D0A0
1C25-   D5 D4       CMP   $D4,X
1C27-   A0 CD       LDY   #$CD
1C29-   C9 CE       CMP   #$CE
1C2B-   AE D3 D5    LDX   $D5D3
1C2E-   C2          ???
1C2F-   AE D0 D2    LDX   $D2D0
1C32-   CE D3 D4    DEC   $D4D3
1C35-   D2 8D       CMP   ($8D)
1C37-   AA          TAX
1C38-   8D 00 00    STA   $0000
