0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C1    LDY   $C120,X
0950-   D2 D2       CMP   ($D2)
0952-   C1 D9       CMP   ($D9,X)
0954-   D3          ???
0955-   20 C4 C5    JSR   $C5C4
0958-   CD CF 20    CMP   $20CF
095B-   BE AD 20    LDX   $20AD,Y
095E-   20 20 20    JSR   $2020
0961-   20 20 20    JSR   $2020
0964-   AA          TAX
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B1    JSR   $B120
09D4-   B5 AD       LDA   $AD,X
09D6-   CA          DEX
09D7-   C1 CE       CMP   ($CE,X)
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B9       LDA   ($B9),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 D4    STA   $D4A0
0B02-   D2 A0       CMP   ($A0)
0B04-   CF          ???
0B05-   CE 8D A0    DEC   $A08D
0B08-   C4 D3       CPY   $D3
0B0A-   CB          ???
0B0B-   A0 C1       LDY   #$C1
0B0D-   D2 D2       CMP   ($D2)
0B0F-   C1 D9       CMP   ($D9,X)
0B11-   D3          ???
0B12-   AE C4 C5    LDX   $C5C4
0B15-   CD CF 8D    CMP   $8DCF
0B18-   A0 CF       LDY   #$CF
0B1A-   C2          ???
0B1B-   CA          DEX
0B1C-   A0 A4       LDY   #$A4
0B1E-   C2          ???
0B1F-   C6 C5       DEC   $C5
0B21-   B0 8D       BCS   $0AB0
0B23-   A0 CF       LDY   #$CF
0B25-   D2 C7       CMP   ($C7)
0B27-   A0 A4       LDY   #$A4
0B29-   B6 B0       LDX   $B0,Y
0B2B-   B0 B0       BCS   $0ADD
0B2D-   8D AA 8D    STA   $8DAA
0B30-   AA          TAX
0B31-   E0 E0       CPX   #$E0
0B33-   E0 E0       CPX   #$E0
0B35-   E0 E0       CPX   #$E0
0B37-   E0 E0       CPX   #$E0
0B39-   E0 E0       CPX   #$E0
0B3B-   E0 E0       CPX   #$E0
0B3D-   E0 E0       CPX   #$E0
0B3F-   E0 E0       CPX   #$E0
0B41-   E0 E0       CPX   #$E0
0B43-   E0 E0       CPX   #$E0
0B45-   E0 E0       CPX   #$E0
0B47-   E0 E0       CPX   #$E0
0B49-   E0 E0       CPX   #$E0
0B4B-   E0 E0       CPX   #$E0
0B4D-   E0 E0       CPX   #$E0
0B4F-   AA          TAX
0B50-   8D AA 20    STA   $20AA
0B53-   20 D4 CF    JSR   $CFD4
0B56-   D0 20       BNE   $0B78
0B58-   C9 CE       CMP   #$CE
0B5A-   C3          ???
0B5B-   CC D5 C4    CPY   $C4D5
0B5E-   C5 D3       CMP   $D3
0B60-   20 A8 C8    JSR   $C8A8
0B63-   CF          ???
0B64-   CF          ???
0B65-   CB          ???
0B66-   D3          ???
0B67-   AC CD C1    LDY   $C1CD
0B6A-   C3          ???
0B6B-   D2 CF       CMP   ($CF)
0B6D-   D3          ???
0B6E-   A9 20       LDA   #$20
0B70-   AA          TAX
0B71-   8D AA AC    STA   $ACAA
0B74-   AC AC AC    LDY   $ACAC
0B77-   AC AC AC    LDY   $ACAC
0B7A-   AC AC AC    LDY   $ACAC
0B7D-   AC AC AC    LDY   $ACAC
0B80-   AC AC AC    LDY   $ACAC
0B83-   AC AC AC    LDY   $ACAC
0B86-   AC AC AC    LDY   $ACAC
0B89-   AC AC AC    LDY   $ACAC
0B8C-   AC AC AC    LDY   $ACAC
0B8F-   AC AC AA    LDY   $AAAC
0B92-   8D AA 8D    STA   $8DAA
0B95-   A0 D0       LDY   #$D0
0B97-   D5 D4       CMP   $D4,X
0B99-   A0 D2       LDY   #$D2
0B9B-   C5 D1       CMP   $D1
0B9D-   D5 C9       CMP   $C9,X
0B9F-   D2 C5       CMP   ($C5)
0BA1-   C4 AE       CPY   $AE
0BA3-   D6 C1       DEC   $C1,X
0BA5-   D2 D3       CMP   ($D3)
0BA7-   8D A0 D0    STA   $D0A0
0BAA-   D5 D4       CMP   $D4,X
0BAC-   A0 D2       LDY   #$D2
0BAE-   C5 D1       CMP   $D1
0BB0-   D5 C9       CMP   $C9,X
0BB2-   D2 C5       CMP   ($C5)
0BB4-   C4 AE       CPY   $AE
0BB6-   C8          INY
0BB7-   CF          ???
0BB8-   CF          ???
0BB9-   CB          ???
0BBA-   D3          ???
0BBB-   AE CD C9    LDX   $C9CD
0BBE-   CE 8D A0    DEC   $A08D
0BC1-   D5 D3       CMP   $D3,X
0BC3-   C5 A0       CMP   $A0
0BC5-   D2 C5       CMP   ($C5)
0BC7-   D1 D5       CMP   ($D5),Y
0BC9-   C9 D2       CMP   #$D2
0BCB-   C5 C4       CMP   $C4
0BCD-   AE CD C1    LDX   $C1CD
0BD0-   C3          ???
0BD1-   AE CD C9    LDX   $C9CD
0BD4-   CE 8D A0    DEC   $A08D
0BD7-   D5 D3       CMP   $D3,X
0BD9-   C5 A0       CMP   $A0
0BDB-   C1 D2       CMP   ($D2,X)
0BDD-   D2 C1       CMP   ($C1)
0BDF-   D9 D3 AE    CMP   $AED3,Y
0BE2-   CD C1 C3    CMP   $C3C1
0BE5-   AE CD C9    LDX   $C9CD
0BE8-   CE 8D A0    DEC   $A08D
0BEB-   D0 D5       BNE   $0BC2
0BED-   D4          ???
0BEE-   A0 C1       LDY   #$C1
0BF0-   D2 D2       CMP   ($D2)
0BF2-   C1 D9       CMP   ($D9,X)
0BF4-   D3          ???
0BF5-   AE C8 CF    LDX   $CFC8
0BF8-   CF          ???
0BF9-   CB          ???
0BFA-   D3          ???
0BFB-   8D AA 8D    STA   $8DAA
0BFE-   AA          TAX
0BFF-   E0 E0       CPX   #$E0
0C01-   E0 E0       CPX   #$E0
0C03-   E0 E0       CPX   #$E0
0C05-   E0 E0       CPX   #$E0
0C07-   E0 E0       CPX   #$E0
0C09-   E0 E0       CPX   #$E0
0C0B-   E0 E0       CPX   #$E0
0C0D-   E0 E0       CPX   #$E0
0C0F-   E0 E0       CPX   #$E0
0C11-   E0 E0       CPX   #$E0
0C13-   E0 E0       CPX   #$E0
0C15-   E0 E0       CPX   #$E0
0C17-   E0 E0       CPX   #$E0
0C19-   E0 E0       CPX   #$E0
0C1B-   E0 E0       CPX   #$E0
0C1D-   AA          TAX
0C1E-   8D AA 20    STA   $20AA
0C21-   20 20 20    JSR   $2020
0C24-   20 20 D0    JSR   $D020
0C27-   D2 CF       CMP   ($CF)
0C29-   C7          ???
0C2A-   D2 C1       CMP   ($C1)
0C2C-   CD 20 CD    CMP   $CD20
0C2F-   C1 C9       CMP   ($C9,X)
0C31-   CE 20 C2    DEC   $C220
0C34-   CF          ???
0C35-   C4 D9       CPY   $D9
0C37-   20 20 20    JSR   $2020
0C3A-   20 20 20    JSR   $2020
0C3D-   20 AA 8D    JSR   $8DAA
0C40-   AA          TAX
0C41-   AC AC AC    LDY   $ACAC
0C44-   AC AC AC    LDY   $ACAC
0C47-   AC AC AC    LDY   $ACAC
0C4A-   AC AC AC    LDY   $ACAC
0C4D-   AC AC AC    LDY   $ACAC
0C50-   AC AC AC    LDY   $ACAC
0C53-   AC AC AC    LDY   $ACAC
0C56-   AC AC AC    LDY   $ACAC
0C59-   AC AC AC    LDY   $ACAC
0C5C-   AC AC AC    LDY   $ACAC
0C5F-   AA          TAX
0C60-   8D AA 8D    STA   $8DAA
0C63-   C1 D2       CMP   ($D2,X)
0C65-   D2 C1       CMP   ($C1)
0C67-   D9 B1 A0    CMP   $A0B1,Y
0C6A-   C5 D1       CMP   $D1
0C6C-   D5 A0       CMP   $A0,X
0C6E-   A4 B3       LDY   $B3
0C70-   B0 B0       BCS   $0C22
0C72-   8D C1 D2    STA   $D2C1
0C75-   D2 C1       CMP   ($C1)
0C77-   D9 B2 A0    CMP   $A0B2,Y
0C7A-   C5 D1       CMP   $D1
0C7C-   D5 A0       CMP   $A0,X
0C7E-   A4 B4       LDY   $B4
0C80-   B0 B0       BCS   $0C32
0C82-   B0 8D       BCS   $0C11
0C84-   AA          TAX
0C85-   8D AA AA    STA   $AAAA
0C88-   20 C4 C9    JSR   $C9C4
0C8B-   CD B8 B1    CMP   $B1B8
0C8E-   20 C3 CC    JSR   $CCC3
0C91-   C5 C1       CMP   $C1
0C93-   D2 D3       CMP   ($D3)
0C95-   20 D4 C8    JSR   $C8D4
0C98-   C5 20       CMP   $20
0C9A-   CD C5 CD    CMP   $CDC5
0C9D-   CF          ???
0C9E-   D2 D9       CMP   ($D9)
0CA0-   20 C1 D4    JSR   $D4C1
0CA3-   20 D4 C8    JSR   $C8D4
0CA6-   C5 20       CMP   $20
0CA8-   D3          ???
0CA9-   D0 C5       BNE   $0C70
0CAB-   C3          ???
0CAC-   C9 C6       CMP   #$C6
0CAE-   C9 C5       CMP   #$C5
0CB0-   C4 8D       CPY   $8D
0CB2-   AA          TAX
0CB3-   AA          TAX
0CB4-   20 CC CF    JSR   $CFCC
0CB7-   C3          ???
0CB8-   C1 D4       CMP   ($D4,X)
0CBA-   C9 CF       CMP   #$CF
0CBC-   CE 20 C1    DEC   $C120
0CBF-   CE C4 20    DEC   $20C4
0CC2-   D3          ???
0CC3-   C5 D4       CMP   $D4
0CC5-   D3          ???
0CC6-   20 D5 D0    JSR   $D0D5
0CC9-   20 D4 C8    JSR   $C8D4
0CCC-   C5 20       CMP   $20
0CCE-   C4 C1       CPY   $C1
0CD0-   D4          ???
0CD1-   C1 20       CMP   ($20,X)
0CD3-   C3          ???
0CD4-   CF          ???
0CD5-   CE C6 C9    DEC   $C9C6
0CD8-   C7          ???
0CD9-   D5 D2       CMP   $D2,X
0CDB-   C1 D4       CMP   ($D4,X)
0CDD-   C9 CF       CMP   #$CF
0CDF-   CE 8D AA    DEC   $AA8D
0CE2-   AA          TAX
0CE3-   20 C6 CF    JSR   $CFC6
0CE6-   D2 20       CMP   ($20)
0CE8-   C1 20       CMP   ($20,X)
0CEA-   B1 C4       LDA   ($C4),Y
0CEC-   20 C1 D2    JSR   $D2C1
0CEF-   D2 C1       CMP   ($C1)
0CF1-   D9 20 A8    CMP   $A820,Y
0CF4-   C1 D2       CMP   ($D2,X)
0CF6-   D2 C1       CMP   ($C1)
0CF8-   D9 20 CC    CMP   $CC20,Y
0CFB-   C5 CE       CMP   $CE
0CFD-   C7          ???
0CFE-   D4          ???
0CFF-   C8          INY
0D00-   AC 20 C5    LDY   $C520
0D03-   CC C5 CD    CPY   $CDC5
0D06-   C5 CE       CMP   $CE
0D08-   D4          ???
0D09-   20 CC C5    JSR   $C5CC
0D0C-   CE C7 D4    DEC   $D4C7
0D0F-   C8          INY
0D10-   AC 20 C4    LDY   $C420
0D13-   C1 D4       CMP   ($D4,X)
0D15-   C1 A9       CMP   ($A9,X)
0D17-   8D AA 8D    STA   $8DAA
0D1A-   AA          TAX
0D1B-   AA          TAX
0D1C-   20 CD C1    JSR   $C1CD
0D1F-   C3          ???
0D20-   D2 CF       CMP   ($CF)
0D22-   BA          TSX
0D23-   20 C4 C9    JSR   $C9C4
0D26-   CD B8 B1    CMP   $B1B8
0D29-   20 C1 C4    JSR   $C4C1
0D2C-   C4 D2       CPY   $D2
0D2E-   C5 D3       CMP   $D3
0D30-   D3          ???
0D31-   BB          ???
0D32-   C1 D2       CMP   ($D2,X)
0D34-   D2 C1       CMP   ($C1)
0D36-   D9 DF D3    CMP   $D3DF,Y
0D39-   C9 DA       CMP   #$DA
0D3B-   C5 BB       CMP   $BB
0D3D-   C5 CC       CMP   $CC
0D3F-   C5 CD       CMP   $CD
0D41-   C5 CE       CMP   $CE
0D43-   D4          ???
0D44-   DF          ???
0D45-   CC C5 CE    CPY   $CEC5
0D48-   C7          ???
0D49-   D4          ???
0D4A-   C8          INY
0D4B-   BB          ???
0D4C-   C6 C9       DEC   $C9
0D4E-   CC CC DF    CPY   $DFCC
0D51-   D6 C1       DEC   $C1,X
0D53-   CC 8D AA    CPY   $AA8D
0D56-   8D AA AA    STA   $AAAA
0D59-   20 CE CF    JSR   $CFCE
0D5C-   D4          ???
0D5D-   C5 20       CMP   $20
0D5F-   D4          ???
0D60-   C8          INY
0D61-   C1 D4       CMP   ($D4,X)
0D63-   20 C9 CE    JSR   $CEC9
0D66-   C4 C5       CPY   $C5
0D68-   D8          CLD
0D69-   C9 CE       CMP   #$CE
0D6B-   C7          ???
0D6C-   20 D3 D4    JSR   $D4D3
0D6F-   C1 D2       CMP   ($D2,X)
0D71-   D4          ???
0D72-   D3          ???
0D73-   20 C1 D4    JSR   $D4C1
0D76-   20 B0 AC    JSR   $ACB0
0D79-   20 D3 CF    JSR   $CFD3
0D7C-   20 C1 CE    JSR   $CEC1
0D7F-   20 C1 D2    JSR   $D2C1
0D82-   D2 C1       CMP   ($C1)
0D84-   D9 8D AA    CMP   $AA8D,Y
0D87-   AA          TAX
0D88-   20 CF C6    JSR   $C6CF
0D8B-   20 D4 C5    JSR   $C5D4
0D8E-   CE 20 C5    DEC   $C520
0D91-   CC C5 CD    CPY   $CDC5
0D94-   C5 CE       CMP   $CE
0D96-   D4          ???
0D97-   D3          ???
0D98-   20 D7 CF    JSR   $CFD7
0D9B-   D5 CC       CMP   $CC,X
0D9D-   C4 20       CPY   $20
0D9F-   C2          ???
0DA0-   C5 20       CMP   $20
0DA2-   CC C9 D3    CPY   $D3C9
0DA5-   D4          ???
0DA6-   C5 C4       CMP   $C4
0DA8-   20 C1 D3    JSR   $D3C1
0DAB-   20 B0 AE    JSR   $AEB0
0DAE-   AE B9 8D    LDX   $8DB9
0DB1-   AA          TAX
0DB2-   8D A0 DF    STA   $DFA0
0DB5-   D0 D2       BNE   $0D89
0DB7-   CE D4 A0    DEC   $A0D4
0DBA-   A2 20       LDX   #$20
0DBC-   A2 AC       LDX   #$AC
0DBE-   B8          CLV
0DBF-   C4 B8       CPY   $B8
0DC1-   C4 8D       CPY   $8D
0DC3-   A0 DF       LDY   #$DF
0DC5-   D0 D2       BNE   $0D99
0DC7-   CE D4 A0    DEC   $A0D4
0DCA-   A2 D4       LDX   #$D4
0DCC-   C8          INY
0DCD-   C5 20       CMP   $20
0DCF-   C4 C9       CPY   $C9
0DD1-   CD B8 B1    CMP   $B1B8
0DD4-   20 CD C1    JSR   $C1CD
0DD7-   C3          ???
0DD8-   D2 CF       CMP   ($CF)
0DDA-   20 D3 C9    JSR   $C9D3
0DDD-   CD D0 CC    CMP   $CCD0
0DE0-   D9 20 D3    CMP   $D320,Y
0DE3-   C5 D4       CMP   $D4
0DE5-   D3          ???
0DE6-   A2 AC       LDX   #$AC
0DE8-   B8          CLV
0DE9-   C4 8D       CPY   $8D
0DEB-   A0 DF       LDY   #$DF
0DED-   D0 D2       BNE   $0DC1
0DEF-   CE D4 A0    DEC   $A0D4
0DF2-   A2 D5       LDX   #$D5
0DF4-   D0 20       BNE   $0E16
0DF6-   C1 20       CMP   ($20,X)
0DF8-   CF          ???
0DF9-   CE C5 AD    DEC   $ADC5
0DFC-   C4 C9       CPY   $C9
0DFE-   CD C5 CE    CMP   $CEC5
0E01-   D3          ???
0E02-   C9 CF       CMP   #$CF
0E04-   CE C1 CC    DEC   $CCC1
0E07-   20 C1 D2    JSR   $D2C1
0E0A-   D2 C1       CMP   ($C1)
0E0C-   D9 20 CF    CMP   $CF20,Y
0E0F-   C6 A2       DEC   $A2
0E11-   AC B8 C4    LDY   $C4B8
0E14-   8D A0 DF    STA   $DFA0
0E17-   D0 D2       BNE   $0DEB
0E19-   CE D4 A0    DEC   $A0D4
0E1C-   A2 D4       LDX   #$D4
0E1E-   C8          INY
0E1F-   C5 20       CMP   $20
0E21-   C7          ???
0E22-   C9 D6       CMP   #$D6
0E24-   C5 CE       CMP   $CE
0E26-   20 D3 C9    JSR   $C9D3
0E29-   DA          PHX
0E2A-   C5 20       CMP   $20
0E2C-   D7          ???
0E2D-   C9 D4       CMP   #$D4
0E2F-   C8          INY
0E30-   20 C5 CC    JSR   $CCC5
0E33-   C5 CD       CMP   $CD
0E35-   C5 CE       CMP   $CE
0E37-   D4          ???
0E38-   D3          ???
0E39-   20 CF C6    JSR   $C6CF
0E3C-   A2 AC       LDX   #$AC
0E3E-   B8          CLV
0E3F-   C4 8D       CPY   $8D
0E41-   A0 DF       LDY   #$DF
0E43-   D0 D2       BNE   $0E17
0E45-   CE D4 A0    DEC   $A0D4
0E48-   A2 C1       LDX   #$C1
0E4A-   20 C7 C9    JSR   $C9C7
0E4D-   D6 C5       DEC   $C5,X
0E4F-   CE 20 CC    DEC   $CC20
0E52-   C5 CE       CMP   $CE
0E54-   C7          ???
0E55-   D4          ???
0E56-   C8          INY
0E57-   AE A2 AC    LDX   $ACA2
0E5A-   B8          CLV
0E5B-   C4 B8       CPY   $B8
0E5D-   C4 8D       CPY   $8D
0E5F-   A0 DF       LDY   #$DF
0E61-   D0 D2       BNE   $0E35
0E63-   CE D4 A0    DEC   $A0D4
0E66-   A2 C4       LDX   #$C4
0E68-   C9 CD       CMP   #$CD
0E6A-   B8          CLV
0E6B-   B1 20       LDA   ($20),Y
0E6D-   C1 D2       CMP   ($D2,X)
0E6F-   D2 C1       CMP   ($C1)
0E71-   D9 B1 BB    CMP   $BBB1,Y
0E74-   A3          ???
0E75-   B1 B0       LDA   ($B0),Y
0E77-   BB          ???
0E78-   A3          ???
0E79-   B1 BB       LDA   ($BB),Y
0E7B-   A3          ???
0E7C-   A4 C1       LDY   $C1
0E7E-   C1 20       CMP   ($20,X)
0E80-   D2 C5       CMP   ($C5)
0E82-   D4          ???
0E83-   D5 D2       CMP   $D2,X
0E85-   CE D3 BA    DEC   $BAD3
0E88-   A2 AC       LDX   #$AC
0E8A-   B8          CLV
0E8B-   C4 B8       CPY   $B8
0E8D-   C4 8D       CPY   $8D
0E8F-   A0 C4       LDY   #$C4
0E91-   C9 CD       CMP   #$CD
0E93-   B8          CLV
0E94-   B1 A0       LDA   ($A0),Y
0E96-   C1 D2       CMP   ($D2,X)
0E98-   D2 C1       CMP   ($C1)
0E9A-   D9 B1 BB    CMP   $BBB1,Y
0E9D-   A3          ???
0E9E-   B1 B0       LDA   ($B0),Y
0EA0-   BB          ???
0EA1-   A3          ???
0EA2-   B1 BB       LDA   ($BB),Y
0EA4-   A3          ???
0EA5-   A4 C1       LDY   $C1
0EA7-   C1 8D       CMP   ($8D,X)
0EA9-   A0 DF       LDY   #$DF
0EAB-   C4 D5       CPY   $D5
0EAD-   CD D0 A0    CMP   $A0D0
0EB0-   C1 D2       CMP   ($D2,X)
0EB2-   D2 C1       CMP   ($C1)
0EB4-   D9 B1 BB    CMP   $BBB1,Y
0EB7-   A3          ???
0EB8-   B2 8D       LDA   ($8D)
0EBA-   A0 DF       LDY   #$DF
0EBC-   C4 D5       CPY   $D5
0EBE-   CD D0 A0    CMP   $A0D0
0EC1-   C1 D2       CMP   ($D2,X)
0EC3-   D2 C1       CMP   ($C1)
0EC5-   D9 B1 AB    CMP   $ABB1,Y
0EC8-   B2 BB       LDA   ($BB)
0ECA-   A3          ???
0ECB-   B5 8D       LDA   $8D,X
0ECD-   A0 DF       LDY   #$DF
0ECF-   C4 D5       CPY   $D5
0ED1-   CD D0 A0    CMP   $A0D0
0ED4-   C1 D2       CMP   ($D2,X)
0ED6-   D2 C1       CMP   ($C1)
0ED8-   D9 B1 AB    CMP   $ABB1,Y
0EDB-   B7          ???
0EDC-   BB          ???
0EDD-   A3          ???
0EDE-   B5 8D       LDA   $8D,X
0EE0-   A0 DF       LDY   #$DF
0EE2-   D0 D2       BNE   $0EB6
0EE4-   CE D4 A0    DEC   $A0D4
0EE7-   A2 20       LDX   #$20
0EE9-   A2 AC       LDX   #$AC
0EEB-   B8          CLV
0EEC-   C4 B8       CPY   $B8
0EEE-   C4 8D       CPY   $8D
0EF0-   A0 DF       LDY   #$DF
0EF2-   D7          ???
0EF3-   C1 C9       CMP   ($C9,X)
0EF5-   D4          ???
0EF6-   8D AA 8D    STA   $8DAA
0EF9-   AA          TAX
0EFA-   AA          TAX
0EFB-   20 D0 D5    JSR   $D5D0
0EFE-   D4          ???
0EFF-   B8          CLV
0F00-   B1 20       LDA   ($20),Y
0F02-   D0 D5       BNE   $0ED9
0F04-   D4          ???
0F05-   D3          ???
0F06-   20 D4 C8    JSR   $C8D4
0F09-   C5 20       CMP   $20
0F0B-   D6 C1       DEC   $C1,X
0F0D-   CC D5 C5    CPY   $C5D5
0F10-   20 C1 D4    JSR   $D4C1
0F13-   20 C1 20    JSR   $20C1
0F16-   D3          ???
0F17-   D0 C5       BNE   $0EDE
0F19-   C3          ???
0F1A-   C9 C6       CMP   #$C6
0F1C-   C9 C5       CMP   #$C5
0F1E-   C4 20       CPY   $20
0F20-   C1 C4       CMP   ($C4,X)
0F22-   C4 D2       CPY   $D2
0F24-   C5 D3       CMP   $D3
0F26-   D3          ???
0F27-   8D AA AA    STA   $AAAA
0F2A-   20 C9 CE    JSR   $CEC9
0F2D-   D4          ???
0F2E-   CF          ???
0F2F-   20 D4 C8    JSR   $C8D4
0F32-   C5 20       CMP   $20
0F34-   C1 D2       CMP   ($D2,X)
0F36-   D2 C1       CMP   ($C1)
0F38-   D9 20 C1    CMP   $C120,Y
0F3B-   D4          ???
0F3C-   20 D4 C8    JSR   $C8D4
0F3F-   C5 20       CMP   $20
0F41-   D3          ???
0F42-   D0 C5       BNE   $0F09
0F44-   C3          ???
0F45-   C9 C6       CMP   #$C6
0F47-   C9 C5       CMP   #$C5
0F49-   C4 20       CPY   $20
0F4B-   C9 CE       CMP   #$CE
0F4D-   C4 C5       CPY   $C5
0F4F-   D8          CLD
0F50-   AE 8D AA    LDX   $AA8D
0F53-   8D AA AA    STA   $AAAA
0F56-   20 CD C1    JSR   $C1CD
0F59-   C3          ???
0F5A-   D2 CF       CMP   ($CF)
0F5C-   BA          TSX
0F5D-   20 D0 D5    JSR   $D5D0
0F60-   D4          ???
0F61-   B8          CLV
0F62-   B1 20       LDA   ($20),Y
0F64-   D3          ???
0F65-   D2 C3       CMP   ($C3)
0F67-   DF          ???
0F68-   C1 C4       CMP   ($C4,X)
0F6A-   C4 D2       CPY   $D2
0F6C-   BB          ???
0F6D-   C4 C5       CPY   $C5
0F6F-   D3          ???
0F70-   D4          ???
0F71-   DF          ???
0F72-   C1 D2       CMP   ($D2,X)
0F74-   D2 C1       CMP   ($C1)
0F76-   D9 BB C9    CMP   $C9BB,Y
0F79-   CE C4 C5    DEC   $C5C4
0F7C-   D8          CLD
0F7D-   8D AA 8D    STA   $8DAA
0F80-   A0 DF       LDY   #$DF
0F82-   D0 D2       BNE   $0F56
0F84-   CE D4 A0    DEC   $A0D4
0F87-   A2 D4       LDX   #$D4
0F89-   C8          INY
0F8A-   C5 20       CMP   $20
0F8C-   D0 D5       BNE   $0F63
0F8E-   D4          ???
0F8F-   B8          CLV
0F90-   B1 20       LDA   ($20),Y
0F92-   CD C1 C3    CMP   $C3C1
0F95-   D2 CF       CMP   ($CF)
0F97-   20 D0 D5    JSR   $D5D0
0F9A-   D4          ???
0F9B-   D3          ???
0F9C-   20 D4 C8    JSR   $C8D4
0F9F-   C5 20       CMP   $20
0FA1-   D6 C1       DEC   $C1,X
0FA3-   CC D5 C5    CPY   $C5D5
0FA6-   20 C6 CF    JSR   $CFC6
0FA9-   D5 CE       CMP   $CE,X
0FAB-   C4 A2       CPY   $A2
0FAD-   AC B8 C4    LDY   $C4B8
0FB0-   8D A0 DF    STA   $DFA0
0FB3-   D0 D2       BNE   $0F87
0FB5-   CE D4 A0    DEC   $A0D4
0FB8-   A2 C1       LDX   #$C1
0FBA-   D4          ???
0FBB-   20 D4 C8    JSR   $C8D4
0FBE-   C5 20       CMP   $20
0FC0-   D3          ???
0FC1-   D0 C5       BNE   $0F88
0FC3-   C3          ???
0FC4-   C9 C6       CMP   #$C6
0FC6-   C9 C5       CMP   #$C5
0FC8-   C4 20       CPY   $20
0FCA-   C1 C4       CMP   ($C4,X)
0FCC-   C4 D2       CPY   $D2
0FCE-   C5 D3       CMP   $D3
0FD0-   D3          ???
0FD1-   20 C1 CE    JSR   $CEC1
0FD4-   C4 20       CPY   $20
0FD6-   D4          ???
0FD7-   C8          INY
0FD8-   C5 CE       CMP   $CE
0FDA-   A2 AC       LDX   #$AC
0FDC-   B8          CLV
0FDD-   C4 8D       CPY   $8D
0FDF-   A0 DF       LDY   #$DF
0FE1-   D0 D2       BNE   $0FB5
0FE3-   CE D4 A0    DEC   $A0D4
0FE6-   A2 C9       LDX   #$C9
0FE8-   CE D3 C5    DEC   $C5D3
0FEB-   D2 D4       CMP   ($D4)
0FED-   D3          ???
0FEE-   20 C9 D4    JSR   $D4C9
0FF1-   20 C9 CE    JSR   $CEC9
0FF4-   D4          ???
0FF5-   CF          ???
0FF6-   20 D4 C8    JSR   $C8D4
0FF9-   C5 20       CMP   $20
0FFB-   C7          ???
0FFC-   C9 D6       CMP   #$D6
0FFE-   C5 CE       CMP   $CE
1000-   20 C1 D2    JSR   $D2C1
1003-   D2 C1       CMP   ($C1)
1005-   D9 20 C1    CMP   $C120,Y
1008-   CE C4 A2    DEC   $A2C4
100B-   AC B8 C4    LDY   $C4B8
100E-   8D A0 DF    STA   $DFA0
1011-   D0 D2       BNE   $0FE5
1013-   CE D4 A0    DEC   $A0D4
1016-   A2 C9       LDX   #$C9
1018-   CE C4 C5    DEC   $C5C4
101B-   D8          CLD
101C-   AE A2 AC    LDX   $ACA2
101F-   B8          CLV
1020-   C4 B8       CPY   $B8
1022-   C4 8D       CPY   $8D
1024-   A0 DF       LDY   #$DF
1026-   D0 D2       BNE   $0FFA
1028-   CE D4 A0    DEC   $A0D4
102B-   A2 D3       LDX   #$D3
102D-   CF          ???
102E-   AC 20 D0    LDY   $D020
1031-   D5 D4       CMP   $D4,X
1033-   B8          CLV
1034-   B1 20       LDA   ($20),Y
1036-   A4 B3       LDY   $B3
1038-   B2 B0       LDA   ($B0)
103A-   BB          ???
103B-   C1 D2       CMP   ($D2,X)
103D-   D2 C1       CMP   ($C1)
103F-   D9 B1 BB    CMP   $BBB1,Y
1042-   A3          ???
1043-   B1 20       LDA   ($20),Y
1045-   C1 CE       CMP   ($CE,X)
1047-   C4 20       CPY   $20
1049-   A2 AC       LDX   #$AC
104B-   B8          CLV
104C-   C4 8D       CPY   $8D
104E-   A0 DF       LDY   #$DF
1050-   D0 D2       BNE   $1024
1052-   CE D4 A0    DEC   $A0D4
1055-   A2 D0       LDX   #$D0
1057-   D5 D4       CMP   $D4,X
1059-   B8          CLV
105A-   B1 20       LDA   ($20),Y
105C-   A4 B3       LDY   $B3
105E-   B2 B1       LDA   ($B1)
1060-   BB          ???
1061-   C1 D2       CMP   ($D2,X)
1063-   D2 C1       CMP   ($C1)
1065-   D9 B1 BB    CMP   $BBB1,Y
1068-   A3          ???
1069-   B2 20       LDA   ($20)
106B-   D2 C5       CMP   ($C5)
106D-   D3          ???
106E-   D5 CC       CMP   $CC,X
1070-   D4          ???
1071-   D3          ???
1072-   20 C9 CE    JSR   $CEC9
1075-   BA          TSX
1076-   20 A2 AC    JSR   $ACA2
1079-   B8          CLV
107A-   C4 B8       CPY   $B8
107C-   C4 8D       CPY   $8D
107E-   A0 CC       LDY   #$CC
1080-   C4 C1       CPY   $C1
1082-   A0 A3       LDY   #$A3
1084-   A4 C2       LDY   $C2
1086-   C2          ???
1087-   8D A0 D3    STA   $D3A0
108A-   D4          ???
108B-   C1 A0       CMP   ($A0,X)
108D-   A4 B3       LDY   $B3
108F-   B2 B0       LDA   ($B0)
1091-   8D A0 CC    STA   $CCA0
1094-   C4 C1       CPY   $C1
1096-   A0 A3       LDY   #$A3
1098-   A4 C3       LDY   $C3
109A-   C3          ???
109B-   8D A0 D3    STA   $D3A0
109E-   D4          ???
109F-   C1 A0       CMP   ($A0,X)
10A1-   A4 B3       LDY   $B3
10A3-   B2 B1       LDA   ($B1)
10A5-   8D A0 D0    STA   $D0A0
10A8-   D5 D4       CMP   $D4,X
10AA-   B8          CLV
10AB-   B1 A0       LDA   ($A0),Y
10AD-   A4 B3       LDY   $B3
10AF-   B2 B0       LDA   ($B0)
10B1-   BB          ???
10B2-   C1 D2       CMP   ($D2,X)
10B4-   D2 C1       CMP   ($C1)
10B6-   D9 B1 BB    CMP   $BBB1,Y
10B9-   A3          ???
10BA-   B1 8D       LDA   ($8D),Y
10BC-   A0 D0       LDY   #$D0
10BE-   D5 D4       CMP   $D4,X
10C0-   B8          CLV
10C1-   B1 A0       LDA   ($A0),Y
10C3-   A4 B3       LDY   $B3
10C5-   B2 B1       LDA   ($B1)
10C7-   BB          ???
10C8-   C1 D2       CMP   ($D2,X)
10CA-   D2 C1       CMP   ($C1)
10CC-   D9 B1 BB    CMP   $BBB1,Y
10CF-   A3          ???
10D0-   B2 8D       LDA   ($8D)
10D2-   A0 DF       LDY   #$DF
10D4-   C4 D5       CPY   $D5
10D6-   CD D0 A0    CMP   $A0D0
10D9-   C1 D2       CMP   ($D2,X)
10DB-   D2 C1       CMP   ($C1)
10DD-   D9 B1 BB    CMP   $BBB1,Y
10E0-   A3          ???
10E1-   B2 8D       LDA   ($8D)
10E3-   A0 DF       LDY   #$DF
10E5-   C4 D5       CPY   $D5
10E7-   CD D0 A0    CMP   $A0D0
10EA-   C1 D2       CMP   ($D2,X)
10EC-   D2 C1       CMP   ($C1)
10EE-   D9 B1 AB    CMP   $ABB1,Y
10F1-   B2 BB       LDA   ($BB)
10F3-   A3          ???
10F4-   B5 8D       LDA   $8D,X
10F6-   A0 DF       LDY   #$DF
10F8-   C4 D5       CPY   $D5
10FA-   CD D0 A0    CMP   $A0D0
10FD-   C1 D2       CMP   ($D2,X)
10FF-   D2 C1       CMP   ($C1)
1101-   D9 B1 AB    CMP   $ABB1,Y
1104-   B7          ???
1105-   BB          ???
1106-   A3          ???
1107-   B5 8D       LDA   $8D,X
1109-   A0 DF       LDY   #$DF
110B-   D0 D2       BNE   $10DF
110D-   CE D4 A0    DEC   $A0D4
1110-   A2 20       LDX   #$20
1112-   A2 AC       LDX   #$AC
1114-   B8          CLV
1115-   C4 B8       CPY   $B8
1117-   C4 8D       CPY   $8D
1119-   A0 DF       LDY   #$DF
111B-   D7          ???
111C-   C1 C9       CMP   ($C9,X)
111E-   D4          ???
111F-   8D AA 8D    STA   $8DAA
1122-   A0 DF       LDY   #$DF
1124-   D0 D2       BNE   $10F8
1126-   CE D4 A0    DEC   $A0D4
1129-   A2 CE       LDX   #$CE
112B-   CF          ???
112C-   D4          ???
112D-   C5 20       CMP   $20
112F-   D4          ???
1130-   C8          INY
1131-   C1 D4       CMP   ($D4,X)
1133-   20 C9 C6    JSR   $C6C9
1136-   20 D9 CF    JSR   $CFD9
1139-   D5 D2       CMP   $D2,X
113B-   20 C5 CC    JSR   $CCC5
113E-   C5 CD       CMP   $CD
1140-   C5 CE       CMP   $CE
1142-   D4          ???
1143-   20 D3 C9    JSR   $C9D3
1146-   DA          PHX
1147-   C5 A2       CMP   $A2
1149-   AC B8 C4    LDY   $C4B8
114C-   8D A0 DF    STA   $DFA0
114F-   D0 D2       BNE   $1123
1151-   CE D4 A0    DEC   $A0D4
1154-   A2 C9       LDX   #$C9
1156-   D3          ???
1157-   20 CF CE    JSR   $CECF
115A-   C5 20       CMP   $20
115C-   C2          ???
115D-   D9 D4 C5    CMP   $C5D4,Y
1160-   AE CF CE    LDX   $CECF
1163-   CC D9 20    CPY   $20D9
1166-   CF          ???
1167-   CE C5 20    DEC   $20C5
116A-   C2          ???
116B-   D9 D4 C5    CMP   $C5D4,Y
116E-   20 C9 D3    JSR   $D3C9
1171-   20 C3 CF    JSR   $CFC3
1174-   D0 C9       BNE   $113F
1176-   C5 C4       CMP   $C4
1178-   BB          ???
1179-   A2 AC       LDX   #$AC
117B-   B8          CLV
117C-   C4 8D       CPY   $8D
117E-   A0 DF       LDY   #$DF
1180-   D0 D2       BNE   $1154
1182-   CE D4 A0    DEC   $A0D4
1185-   A2 C9       LDX   #$C9
1187-   C6 20       DEC   $20
1189-   D4          ???
118A-   D7          ???
118B-   CF          ???
118C-   20 C2 D9    JSR   $D9C2
118F-   D4          ???
1190-   C5 D3       CMP   $D3
1192-   AC 20 D4    LDY   $D420
1195-   C8          INY
1196-   C5 CE       CMP   $CE
1198-   20 D4 D7    JSR   $D7D4
119B-   CF          ???
119C-   20 C1 D2    JSR   $D2C1
119F-   C5 20       CMP   $20
11A1-   C3          ???
11A2-   CF          ???
11A3-   D0 C9       BNE   $116E
11A5-   C5 C4       CMP   $C4
11A7-   AC A2 AC    LDY   $ACA2
11AA-   B8          CLV
11AB-   C4 8D       CPY   $8D
11AD-   A0 DF       LDY   #$DF
11AF-   D0 D2       BNE   $1183
11B1-   CE D4 A0    DEC   $A0D4
11B4-   A2 C1       LDX   #$C1
11B6-   CE C4 20    DEC   $20C4
11B9-   D3          ???
11BA-   CF          ???
11BB-   20 CF CE    JSR   $CECF
11BE-   AE 20 D4    LDX   $D420
11C1-   C8          INY
11C2-   D5 D3       CMP   $D3,X
11C4-   20 D4 C8    JSR   $C8D4
11C7-   C5 20       CMP   $20
11C9-   C6 CF       DEC   $CF
11CB-   CC CC CF    CPY   $CFCC
11CE-   D7          ???
11CF-   C9 CE       CMP   #$CE
11D1-   C7          ???
11D2-   BA          TSX
11D3-   A2 AC       LDX   #$AC
11D5-   B8          CLV
11D6-   C4 B8       CPY   $B8
11D8-   C4 8D       CPY   $8D
11DA-   A0 DF       LDY   #$DF
11DC-   D0 D2       BNE   $11B0
11DE-   CE D4 A0    DEC   $A0D4
11E1-   A2 C4       LDX   #$C4
11E3-   C9 CD       CMP   #$CD
11E5-   B8          CLV
11E6-   B1 20       LDA   ($20),Y
11E8-   C1 D2       CMP   ($D2,X)
11EA-   D2 C1       CMP   ($C1)
11EC-   D9 B2 BB    CMP   $BBB2,Y
11EF-   A3          ???
11F0-   B1 B0       LDA   ($B0),Y
11F2-   BB          ???
11F3-   A3          ???
11F4-   B2 BB       LDA   ($BB)
11F6-   A3          ???
11F7-   A4 C5       LDY   $C5
11F9-   C5 A2       CMP   $A2
11FB-   AC B8 C4    LDY   $C4B8
11FE-   8D A0 DF    STA   $DFA0
1201-   D0 D2       BNE   $11D5
1203-   CE D4 A0    DEC   $A0D4
1206-   A2 D0       LDX   #$D0
1208-   D5 D4       CMP   $D4,X
120A-   B8          CLV
120B-   B1 20       LDA   ($20),Y
120D-   A4 B3       LDY   $B3
120F-   B2 B0       LDA   ($B0)
1211-   BB          ???
1212-   C1 D2       CMP   ($D2,X)
1214-   D2 C1       CMP   ($C1)
1216-   D9 B2 BB    CMP   $BBB2,Y
1219-   A3          ???
121A-   B8          CLV
121B-   A2 AC       LDX   #$AC
121D-   B8          CLV
121E-   C4 B8       CPY   $B8
1220-   C4 8D       CPY   $8D
1222-   A0 DF       LDY   #$DF
1224-   D0 D2       BNE   $11F8
1226-   CE D4 A0    DEC   $A0D4
1229-   A2 D2       LDX   #$D2
122B-   C5 D3       CMP   $D3
122D-   D5 CC       CMP   $CC,X
122F-   D4          ???
1230-   D3          ???
1231-   20 C9 CE    JSR   $CEC9
1234-   20 D4 C8    JSR   $C8D4
1237-   C5 20       CMP   $20
1239-   C6 CF       DEC   $CF
123B-   CC CC CF    CPY   $CFCC
123E-   D7          ???
123F-   C9 CE       CMP   #$CE
1241-   C7          ???
1242-   BA          TSX
1243-   A2 AC       LDX   #$AC
1245-   B8          CLV
1246-   C4 B8       CPY   $B8
1248-   C4 8D       CPY   $8D
124A-   A0 C4       LDY   #$C4
124C-   C9 CD       CMP   #$CD
124E-   B8          CLV
124F-   B1 A0       LDA   ($A0),Y
1251-   C1 D2       CMP   ($D2,X)
1253-   D2 C1       CMP   ($C1)
1255-   D9 B2 BB    CMP   $BBB2,Y
1258-   A3          ???
1259-   B1 B0       LDA   ($B0),Y
125B-   BB          ???
125C-   A3          ???
125D-   B2 BB       LDA   ($BB)
125F-   A3          ???
1260-   A4 C5       LDY   $C5
1262-   C5 8D       CMP   $8D
1264-   A0 D0       LDY   #$D0
1266-   D5 D4       CMP   $D4,X
1268-   B8          CLV
1269-   B1 A0       LDA   ($A0),Y
126B-   A4 B3       LDY   $B3
126D-   B2 B0       LDA   ($B0)
126F-   BB          ???
1270-   C1 D2       CMP   ($D2,X)
1272-   D2 C1       CMP   ($C1)
1274-   D9 B2 BB    CMP   $BBB2,Y
1277-   A3          ???
1278-   B8          CLV
1279-   8D A0 DF    STA   $DFA0
127C-   C4 D5       CPY   $D5
127E-   CD D0 A0    CMP   $A0D0
1281-   C1 D2       CMP   ($D2,X)
1283-   D2 C1       CMP   ($C1)
1285-   D9 B2 BB    CMP   $BBB2,Y
1288-   A3          ???
1289-   B0 B2       BCS   $123D
128B-   8D A0 DF    STA   $DFA0
128E-   C4 D5       CPY   $D5
1290-   CD D0 A0    CMP   $A0D0
1293-   C1 D2       CMP   ($D2,X)
1295-   D2 C1       CMP   ($C1)
1297-   D9 B2 AB    CMP   $ABB2,Y
129A-   B2 BB       LDA   ($BB)
129C-   A3          ???
129D-   B5 8D       LDA   $8D,X
129F-   A0 DF       LDY   #$DF
12A1-   C4 D5       CPY   $D5
12A3-   CD D0 A0    CMP   $A0D0
12A6-   C1 D2       CMP   ($D2,X)
12A8-   D2 C1       CMP   ($C1)
12AA-   D9 B2 AB    CMP   $ABB2,Y
12AD-   B7          ???
12AE-   BB          ???
12AF-   A3          ???
12B0-   B5 8D       LDA   $8D,X
12B2-   A0 DF       LDY   #$DF
12B4-   C4 D5       CPY   $D5
12B6-   CD D0 A0    CMP   $A0D0
12B9-   C1 D2       CMP   ($D2,X)
12BB-   D2 C1       CMP   ($C1)
12BD-   D9 B2 AB    CMP   $ABB2,Y
12C0-   B1 B2       LDA   ($B2),Y
12C2-   BB          ???
12C3-   A3          ???
12C4-   B5 8D       LDA   $8D,X
12C6-   A0 DF       LDY   #$DF
12C8-   C4 D5       CPY   $D5
12CA-   CD D0 A0    CMP   $A0D0
12CD-   C1 D2       CMP   ($D2,X)
12CF-   D2 C1       CMP   ($C1)
12D1-   D9 B2 AB    CMP   $ABB2,Y
12D4-   B1 B7       LDA   ($B7),Y
12D6-   BB          ???
12D7-   A3          ???
12D8-   B5 8D       LDA   $8D,X
12DA-   A0 DF       LDY   #$DF
12DC-   D7          ???
12DD-   C1 C9       CMP   ($C9,X)
12DF-   D4          ???
12E0-   8D A0 DF    STA   $DFA0
12E3-   D0 D2       BNE   $12B7
12E5-   CE D4 A0    DEC   $A0D4
12E8-   A2 20       LDX   #$20
12EA-   A2 AC       LDX   #$AC
12EC-   B8          CLV
12ED-   C4 B8       CPY   $B8
12EF-   C4 8D       CPY   $8D
12F1-   A0 DF       LDY   #$DF
12F3-   D0 D2       BNE   $12C7
12F5-   CE D4 A0    DEC   $A0D4
12F8-   A2 C1       LDX   #$C1
12FA-   CC D3 CF    CPY   $CFD3
12FD-   20 CE CF    JSR   $CFCE
1300-   D4          ???
1301-   C5 20       CMP   $20
1303-   D4          ???
1304-   C8          INY
1305-   C1 D4       CMP   ($D4,X)
1307-   20 C2 C5    JSR   $C5C2
130A-   C3          ???
130B-   C1 D5       CMP   ($D5,X)
130D-   D3          ???
130E-   C5 20       CMP   $20
1310-   C5 CC       CMP   $CC
1312-   C5 CD       CMP   $CD
1314-   C5 CE       CMP   $CE
1316-   D4          ???
1317-   20 D3 C9    JSR   $C9D3
131A-   DA          PHX
131B-   C5 D3       CMP   $D3
131D-   A2 AC       LDX   #$AC
131F-   B8          CLV
1320-   C4 8D       CPY   $8D
1322-   A0 DF       LDY   #$DF
1324-   D0 D2       BNE   $12F8
1326-   CE D4 A0    DEC   $A0D4
1329-   A2 C3       LDX   #$C3
132B-   C1 CE       CMP   ($CE,X)
132D-   20 D6 C1    JSR   $C1D6
1330-   D2 D9       CMP   ($D9)
1332-   20 C6 D2    JSR   $D2C6
1335-   CF          ???
1336-   CD 20 B1    CMP   $B120
1339-   20 C2 D9    JSR   $D9C2
133C-   D4          ???
133D-   C5 20       CMP   $20
133F-   D4          ???
1340-   CF          ???
1341-   20 B2 B5    JSR   $B5B2
1344-   B5 20       LDA   $20,X
1346-   C2          ???
1347-   D9 D4 C5    CMP   $C5D4,Y
134A-   D3          ???
134B-   AC A2 AC    LDY   $ACA2
134E-   B8          CLV
134F-   C4 8D       CPY   $8D
1351-   A0 DF       LDY   #$DF
1353-   D0 D2       BNE   $1327
1355-   CE D4 A0    DEC   $A0D4
1358-   A2 C1       LDX   #$C1
135A-   CC CC CF    CPY   $CFCC
135D-   D7          ???
135E-   C9 CE       CMP   #$CE
1360-   C7          ???
1361-   20 CC C9    JSR   $C9CC
1364-   D4          ???
1365-   C5 D2       CMP   $D2
1367-   C1 CC       CMP   ($CC,X)
1369-   20 D6 C1    JSR   $C1D6
136C-   CC D5 C5    CPY   $C5D5
136F-   D3          ???
1370-   20 C9 D3    JSR   $D3C9
1373-   20 C9 CD    JSR   $CDC9
1376-   D0 D2       BNE   $134A
1378-   C1 C3       CMP   ($C3,X)
137A-   D4          ???
137B-   C9 C3       CMP   #$C3
137D-   C1 CC       CMP   ($CC,X)
137F-   AE A2 AC    LDX   $ACA2
1382-   B8          CLV
1383-   C4 8D       CPY   $8D
1385-   A0 DF       LDY   #$DF
1387-   D0 D2       BNE   $135B
1389-   CE D4 A0    DEC   $A0D4
138C-   A2 D4       LDX   #$D4
138E-   C8          INY
138F-   D5 D3       CMP   $D3,X
1391-   AC 20 C2    LDY   $C220
1394-   C5 20       CMP   $20
1396-   D3          ???
1397-   D5 D2       CMP   $D2,X
1399-   C5 20       CMP   $20
139B-   D4          ???
139C-   CF          ???
139D-   20 D5 D4    JSR   $D4D5
13A0-   C9 CC       CMP   #$CC
13A2-   C9 DA       CMP   #$DA
13A4-   C5 20       CMP   $20
13A6-   C1 20       CMP   ($20,X)
13A8-   D0 CF       BNE   $1379
13AA-   D2 D4       CMP   ($D4)
13AC-   C9 CF       CMP   #$CF
13AE-   CE A2 AC    DEC   $ACA2
13B1-   B8          CLV
13B2-   C4 8D       CPY   $8D
13B4-   A0 DF       LDY   #$DF
13B6-   D0 D2       BNE   $138A
13B8-   CE D4 A0    DEC   $A0D4
13BB-   A2 CF       LDX   #$CF
13BD-   C6 20       DEC   $20
13BF-   CD C5 CD    CMP   $CDC5
13C2-   20 C6 CF    JSR   $CFC6
13C5-   D2 20       CMP   ($20)
13C7-   D0 C1       BNE   $138A
13C9-   D3          ???
13CA-   D3          ???
13CB-   C9 CE       CMP   #$CE
13CD-   C7          ???
13CE-   20 D4 CF    JSR   $CFD4
13D1-   20 C1 CE    JSR   $CEC1
13D4-   C4 20       CPY   $20
13D6-   C6 D2       DEC   $D2
13D8-   CF          ???
13D9-   CD 20 C1    CMP   $C120
13DC-   D2 D2       CMP   ($D2)
13DE-   C1 D9       CMP   ($D9,X)
13E0-   20 A2 AC    JSR   $ACA2
13E3-   B8          CLV
13E4-   C4 8D       CPY   $8D
13E6-   A0 DF       LDY   #$DF
13E8-   D0 D2       BNE   $13BC
13EA-   CE D4 A0    DEC   $A0D4
13ED-   A2 D3       LDX   #$D3
13EF-   D5 C2       CMP   $C2,X
13F1-   D2 CF       CMP   ($CF)
13F3-   D5 D4       CMP   $D4,X
13F5-   C9 CE       CMP   #$CE
13F7-   C5 D3       CMP   $D3
13F9-   AE 20 D4    LDX   $D420
13FC-   C8          INY
13FD-   C5 20       CMP   $20
13FF-   DB          ???
1400-   D0 C1       BNE   $13C3
1402-   D2 C1       CMP   ($C1)
1404-   CD DD 20    CMP   $20DD
1407-   C1 C4       CMP   ($C4,X)
1409-   C4 D2       CPY   $D2
140B-   20 C9 D3    JSR   $D3C9
140E-   20 C7 CF    JSR   $CFC7
1411-   CF          ???
1412-   C4 A2       CPY   $A2
1414-   AC B8 C4    LDY   $C4B8
1417-   8D A0 DF    STA   $DFA0
141A-   D0 D2       BNE   $13EE
141C-   CE D4 A0    DEC   $A0D4
141F-   A2 C6       LDX   #$C6
1421-   CF          ???
1422-   D2 20       CMP   ($20)
1424-   D4          ???
1425-   C8          INY
1426-   C9 D3       CMP   #$D3
1428-   AE A2 AC    LDX   $ACA2
142B-   B8          CLV
142C-   C4 B8       CPY   $B8
142E-   C4 8D       CPY   $8D
1430-   A0 DF       LDY   #$DF
1432-   D7          ???
1433-   C1 C9       CMP   ($C9,X)
1435-   D4          ???
1436-   8D AA 8D    STA   $8DAA
1439-   A0 DF       LDY   #$DF
143B-   D0 D2       BNE   $140F
143D-   CE D4 A0    DEC   $A0D4
1440-   A2 20       LDX   #$20
1442-   A2 AC       LDX   #$AC
1444-   B8          CLV
1445-   C4 B8       CPY   $B8
1447-   C4 8D       CPY   $8D
1449-   AA          TAX
144A-   8D AA AA    STA   $AAAA
144D-   20 C7 C5    JSR   $C5C7
1450-   D4          ???
1451-   B8          CLV
1452-   B1 20       LDA   ($20),Y
1454-   D3          ???
1455-   C9 CD       CMP   #$CD
1457-   D0 CC       BNE   $1425
1459-   D9 20 D2    CMP   $D220,Y
145C-   C5 D4       CMP   $D4
145E-   D2 C9       CMP   ($C9)
1460-   C5 D6       CMP   $D6
1462-   C5 D3       CMP   $D3
1464-   20 D4 C8    JSR   $C8D4
1467-   C5 20       CMP   $20
1469-   D6 C1       DEC   $C1,X
146B-   CC D5 C5    CPY   $C5D5
146E-   20 C9 CE    JSR   $CEC9
1471-   20 C1 CE    JSR   $CEC1
1474-   8D AA AA    STA   $AAAA
1477-   20 C1 D2    JSR   $D2C1
147A-   D2 C1       CMP   ($C1)
147C-   D9 20 C1    CMP   $C120,Y
147F-   D4          ???
1480-   20 D4 C8    JSR   $C8D4
1483-   C5 20       CMP   $20
1485-   C7          ???
1486-   C9 D6       CMP   #$D6
1488-   C5 CE       CMP   $CE
148A-   20 C9 CE    JSR   $CEC9
148D-   C4 C5       CPY   $C5
148F-   D8          CLD
1490-   C5 C4       CMP   $C4
1492-   20 C5 CC    JSR   $CCC5
1495-   C5 CD       CMP   $CD
1497-   C5 CE       CMP   $CE
1499-   D4          ???
149A-   20 C9 CE    JSR   $CEC9
149D-   8D AA AA    STA   $AAAA
14A0-   20 DB D2    JSR   $D2DB
14A3-   C5 D4       CMP   $D4
14A5-   D5 D2       CMP   $D2,X
14A7-   CE DD AE    DEC   $AEDD
14AA-   8D AA 8D    STA   $8DAA
14AD-   AA          TAX
14AE-   AA          TAX
14AF-   20 CD C1    JSR   $C1CD
14B2-   C3          ???
14B3-   D2 CF       CMP   ($CF)
14B5-   BA          TSX
14B6-   20 C7 C5    JSR   $C5C7
14B9-   D4          ???
14BA-   B8          CLV
14BB-   B1 20       LDA   ($20),Y
14BD-   C1 D2       CMP   ($D2,X)
14BF-   D2 C1       CMP   ($C1)
14C1-   D9 DF C1    CMP   $C1DF,Y
14C4-   C4 C4       CPY   $C4
14C6-   D2 BB       CMP   ($BB)
14C8-   C9 CE       CMP   #$CE
14CA-   C4 C5       CPY   $C5
14CC-   D8          CLD
14CD-   8D AA 8D    STA   $8DAA
14D0-   A0 DF       LDY   #$DF
14D2-   D0 D2       BNE   $14A6
14D4-   CE D4 A0    DEC   $A0D4
14D7-   A2 D4       LDX   #$D4
14D9-   C8          INY
14DA-   C5 20       CMP   $20
14DC-   C7          ???
14DD-   C5 D4       CMP   $D4
14DF-   B8          CLV
14E0-   B1 20       LDA   ($20),Y
14E2-   CD C1 C3    CMP   $C3C1
14E5-   D2 CF       CMP   ($CF)
14E7-   20 C7 C5    JSR   $C5C7
14EA-   D4          ???
14EB-   D3          ???
14EC-   20 D4 C8    JSR   $C8D4
14EF-   C5 20       CMP   $20
14F1-   D6 C1       DEC   $C1,X
14F3-   CC D5 C5    CPY   $C5D5
14F6-   20 C8 C5    JSR   $C5C8
14F9-   CC C4 A2    CPY   $A2C4
14FC-   AC B8 C4    LDY   $C4B8
14FF-   8D A0 DF    STA   $DFA0
1502-   D0 D2       BNE   $14D6
1504-   CE D4 A0    DEC   $A0D4
1507-   A2 C9       LDX   #$C9
1509-   CE 20 D4    DEC   $D420
150C-   C8          INY
150D-   C5 20       CMP   $20
150F-   C7          ???
1510-   C9 D6       CMP   #$D6
1512-   C5 CE       CMP   $CE
1514-   20 C5 CC    JSR   $CCC5
1517-   C5 CD       CMP   $CD
1519-   C5 CE       CMP   $CE
151B-   D4          ???
151C-   20 C9 CE    JSR   $CEC9
151F-   20 D4 C8    JSR   $C8D4
1522-   C5 20       CMP   $20
1524-   C7          ???
1525-   C9 D6       CMP   #$D6
1527-   C5 CE       CMP   $CE
1529-   A2 AC       LDX   #$AC
152B-   B8          CLV
152C-   C4 8D       CPY   $8D
152E-   A0 DF       LDY   #$DF
1530-   D0 D2       BNE   $1504
1532-   CE D4 A0    DEC   $A0D4
1535-   A2 C1       LDX   #$C1
1537-   D2 D2       CMP   ($D2)
1539-   C1 D9       CMP   ($D9,X)
153B-   AE 20 D4    LDX   $D420
153E-   C8          INY
153F-   D5 D3       CMP   $D3,X
1541-   A2 AC       LDX   #$AC
1543-   B8          CLV
1544-   C4 B8       CPY   $B8
1546-   C4 8D       CPY   $8D
1548-   A0 DF       LDY   #$DF
154A-   D0 D2       BNE   $151E
154C-   CE D4 A0    DEC   $A0D4
154F-   A2 C7       LDX   #$C7
1551-   C5 D4       CMP   $D4
1553-   B8          CLV
1554-   B1 20       LDA   ($20),Y
1556-   C1 D2       CMP   ($D2,X)
1558-   D2 C1       CMP   ($C1)
155A-   D9 B2 BB    CMP   $BBB2,Y
155D-   A3          ???
155E-   B8          CLV
155F-   20 D2 C5    JSR   $C5D2
1562-   D4          ???
1563-   D5 D2       CMP   $D2,X
1565-   CE D3 BA    DEC   $BAD3
1568-   A2 AC       LDX   #$AC
156A-   B8          CLV
156B-   C4 B8       CPY   $B8
156D-   C4 8D       CPY   $8D
156F-   A0 C7       LDY   #$C7
1571-   C5 D4       CMP   $D4
1573-   B8          CLV
1574-   B1 A0       LDA   ($A0),Y
1576-   C1 D2       CMP   ($D2,X)
1578-   D2 C1       CMP   ($C1)
157A-   D9 B2 BB    CMP   $BBB2,Y
157D-   A3          ???
157E-   B8          CLV
157F-   8D A0 DF    STA   $DFA0
1582-   C4 D5       CPY   $D5
1584-   CD D0 A0    CMP   $A0D0
1587-   D2 C5       CMP   ($C5)
1589-   D4          ???
158A-   D5 D2       CMP   $D2,X
158C-   CE BB D2    DEC   $D2BB
158F-   C5 D4       CMP   $D4
1591-   CC C5 CE    CPY   $CEC5
1594-   8D A0 DF    STA   $DFA0
1597-   D0 D2       BNE   $156B
1599-   CE D4 A0    DEC   $A0D4
159C-   A2 20       LDX   #$20
159E-   A2 AC       LDX   #$AC
15A0-   B8          CLV
15A1-   C4 B8       CPY   $B8
15A3-   C4 8D       CPY   $8D
15A5-   A0 DF       LDY   #$DF
15A7-   D7          ???
15A8-   C1 C9       CMP   ($C9,X)
15AA-   D4          ???
15AB-   8D AA 8D    STA   $8DAA
15AE-   AA          TAX
15AF-   AA          TAX
15B0-   20 C4 C9    JSR   $C9C4
15B3-   CD B8 B2    CMP   $B2B8
15B6-   20 C3 D2    JSR   $D2C3
15B9-   C5 C1       CMP   $C1
15BB-   D4          ???
15BC-   C5 D3       CMP   $D3
15BE-   20 C1 20    JSR   $20C1
15C1-   B2 AD       LDA   ($AD)
15C3-   C4 C9       CPY   $C9
15C5-   CD C5 CE    CMP   $CEC5
15C8-   D3          ???
15C9-   C9 CF       CMP   #$CF
15CB-   CE C1 CC    DEC   $CCC1
15CE-   20 C1 D2    JSR   $D2C1
15D1-   D2 C1       CMP   ($C1)
15D3-   D9 20 D7    CMP   $D720,Y
15D6-   C9 D4       CMP   #$D4
15D8-   C8          INY
15D9-   20 D4 C8    JSR   $C8D4
15DC-   C5 8D       CMP   $8D
15DE-   AA          TAX
15DF-   AA          TAX
15E0-   20 D3 D0    JSR   $D0D3
15E3-   C5 C3       CMP   $C3
15E5-   C9 C6       CMP   #$C6
15E7-   C9 C5       CMP   #$C5
15E9-   C4 20       CPY   $20
15EB-   C5 CC       CMP   $CC
15ED-   C5 CD       CMP   $CD
15EF-   C5 CE       CMP   $CE
15F1-   D4          ???
15F2-   20 CC C5    JSR   $C5CC
15F5-   CE C7 D4    DEC   $D4C7
15F8-   C8          INY
15F9-   20 C1 CE    JSR   $CEC1
15FC-   C4 20       CPY   $20
15FE-   D8          CLD
15FF-   AC D9 20    LDY   $20D9
1602-   C4 C9       CPY   $C9
1604-   CD C5 CE    CMP   $CEC5
1607-   D3          ???
1608-   C9 CF       CMP   #$CF
160A-   CE D3 8D    DEC   $8DD3
160D-   AA          TAX
160E-   8D AA AA    STA   $AAAA
1611-   20 CD C1    JSR   $C1CD
1614-   C3          ???
1615-   D2 CF       CMP   ($CF)
1617-   BA          TSX
1618-   20 C4 C9    JSR   $C9C4
161B-   CD B8 B2    CMP   $B2B8
161E-   20 C1 D2    JSR   $D2C1
1621-   D2 C1       CMP   ($C1)
1623-   D9 DF C1    CMP   $C1DF,Y
1626-   C4 C4       CPY   $C4
1628-   D2 BB       CMP   ($BB)
162A-   D8          CLD
162B-   DF          ???
162C-   C4 C9       CPY   $C9
162E-   CD BB D9    CMP   $D9BB
1631-   DF          ???
1632-   C4 C9       CPY   $C9
1634-   CD BB C5    CMP   $C5BB
1637-   CC C5 CD    CPY   $CDC5
163A-   DF          ???
163B-   CC C5 CE    CPY   $CEC5
163E-   C7          ???
163F-   D4          ???
1640-   C8          INY
1641-   8D AA 8D    STA   $8DAA
1644-   A0 C4       LDY   #$C4
1646-   C9 CD       CMP   #$CD
1648-   B8          CLV
1649-   B2 A0       LDA   ($A0)
164B-   C1 D2       CMP   ($D2,X)
164D-   D2 C1       CMP   ($C1)
164F-   D9 B2 BB    CMP   $BBB2,Y
1652-   A3          ???
1653-   B1 B0       LDA   ($B0),Y
1655-   BB          ???
1656-   A3          ???
1657-   B1 B0       LDA   ($B0),Y
1659-   BB          ???
165A-   A3          ???
165B-   B1 BB       LDA   ($BB),Y
165D-   A3          ???
165E-   A4 B2       LDY   $B2
1660-   C4 8D       CPY   $8D
1662-   A0 DF       LDY   #$DF
1664-   D0 D2       BNE   $1638
1666-   CE D4 A0    DEC   $A0D4
1669-   A2 C4       LDX   #$C4
166B-   C9 CD       CMP   #$CD
166D-   B8          CLV
166E-   B2 20       LDA   ($20)
1670-   C3          ???
1671-   D2 C5       CMP   ($C5)
1673-   C1 D4       CMP   ($D4,X)
1675-   C5 D3       CMP   $D3
1677-   20 C1 CE    JSR   $CEC1
167A-   20 C1 D2    JSR   $D2C1
167D-   D2 C1       CMP   ($C1)
167F-   D9 20 CC    CMP   $CC20,Y
1682-   C9 CB       CMP   #$CB
1684-   C5 20       CMP   $20
1686-   C4 C9       CPY   $C9
1688-   CD B8 B1    CMP   $B1B8
168B-   AC A2 AC    LDY   $ACA2
168E-   B8          CLV
168F-   C4 8D       CPY   $8D
1691-   A0 DF       LDY   #$DF
1693-   D0 D2       BNE   $1667
1695-   CE D4 A0    DEC   $A0D4
1698-   A2 C2       LDX   #$C2
169A-   D5 D4       CMP   $D4,X
169C-   20 C9 CE    JSR   $CEC9
169F-   20 B2 AD    JSR   $ADB2
16A2-   C4 C9       CPY   $C9
16A4-   CD C5 CE    CMP   $CEC5
16A7-   D3          ???
16A8-   C9 CF       CMP   #$CF
16AA-   CE D3 20    DEC   $20D3
16AD-   C9 CE       CMP   #$CE
16AF-   D3          ???
16B0-   D4          ???
16B1-   C5 C1       CMP   $C1
16B3-   C4 20       CPY   $20
16B5-   CF          ???
16B6-   C6 20       DEC   $20
16B8-   CF          ???
16B9-   CE C5 AE    DEC   $AEC5
16BC-   A2 AC       LDX   #$AC
16BE-   B8          CLV
16BF-   C4 B8       CPY   $B8
16C1-   C4 8D       CPY   $8D
16C3-   A0 DF       LDY   #$DF
16C5-   D0 D2       BNE   $1699
16C7-   CE D4 A0    DEC   $A0D4
16CA-   A2 D4       LDX   #$D4
16CC-   C8          INY
16CD-   D5 D3       CMP   $D3,X
16CF-   20 C4 C9    JSR   $C9C4
16D2-   CD B8 B2    CMP   $B2B8
16D5-   20 C1 D2    JSR   $D2C1
16D8-   D2 C1       CMP   ($C1)
16DA-   D9 B2 BB    CMP   $BBB2,Y
16DD-   A3          ???
16DE-   B1 B0       LDA   ($B0),Y
16E0-   BB          ???
16E1-   A3          ???
16E2-   B1 B0       LDA   ($B0),Y
16E4-   BB          ???
16E5-   A3          ???
16E6-   B1 BB       LDA   ($BB),Y
16E8-   A3          ???
16E9-   A4 B2       LDY   $B2
16EB-   C4 20       CPY   $20
16ED-   D2 C5       CMP   ($C5)
16EF-   D4          ???
16F0-   D5 D2       CMP   $D2,X
16F2-   CE D3 BA    DEC   $BAD3
16F5-   20 A2 AC    JSR   $ACA2
16F8-   B8          CLV
16F9-   C4 B8       CPY   $B8
16FB-   C4 8D       CPY   $8D
16FD-   A0 DF       LDY   #$DF
16FF-   C4 D5       CPY   $D5
1701-   CD D0 A0    CMP   $A0D0
1704-   C1 D2       CMP   ($D2,X)
1706-   D2 C1       CMP   ($C1)
1708-   D9 B2 BB    CMP   $BBB2,Y
170B-   A3          ???
170C-   B0 B3       BCS   $16C1
170E-   8D A0 DF    STA   $DFA0
1711-   C4 D5       CPY   $D5
1713-   CD D0 A0    CMP   $A0D0
1716-   C1 D2       CMP   ($D2,X)
1718-   D2 C1       CMP   ($C1)
171A-   D9 B2 AB    CMP   $ABB2,Y
171D-   B0 B3       BCS   $16D2
171F-   BB          ???
1720-   A3          ???
1721-   B1 B0       LDA   ($B0),Y
1723-   8D A0 DF    STA   $DFA0
1726-   C4 D5       CPY   $D5
1728-   CD D0 A0    CMP   $A0D0
172B-   C1 D2       CMP   ($D2,X)
172D-   D2 C1       CMP   ($C1)
172F-   D9 B2 AB    CMP   $ABB2,Y
1732-   B1 B3       LDA   ($B3),Y
1734-   BB          ???
1735-   A3          ???
1736-   B1 B0       LDA   ($B0),Y
1738-   8D A0 DF    STA   $DFA0
173B-   C4 D5       CPY   $D5
173D-   CD D0 A0    CMP   $A0D0
1740-   C1 D2       CMP   ($D2,X)
1742-   D2 C1       CMP   ($C1)
1744-   D9 B2 AB    CMP   $ABB2,Y
1747-   B2 B3       LDA   ($B3)
1749-   BB          ???
174A-   A3          ???
174B-   B1 B0       LDA   ($B0),Y
174D-   8D A0 DF    STA   $DFA0
1750-   C4 D5       CPY   $D5
1752-   CD D0 A0    CMP   $A0D0
1755-   C1 D2       CMP   ($D2,X)
1757-   D2 C1       CMP   ($C1)
1759-   D9 B2 AB    CMP   $ABB2,Y
175C-   B3          ???
175D-   B3          ???
175E-   BB          ???
175F-   A3          ???
1760-   B1 B0       LDA   ($B0),Y
1762-   8D A0 DF    STA   $DFA0
1765-   C4 D5       CPY   $D5
1767-   CD D0 A0    CMP   $A0D0
176A-   C1 D2       CMP   ($D2,X)
176C-   D2 C1       CMP   ($C1)
176E-   D9 B2 AB    CMP   $ABB2,Y
1771-   B4 B3       LDY   $B3,X
1773-   BB          ???
1774-   A3          ???
1775-   B1 B0       LDA   ($B0),Y
1777-   8D A0 DF    STA   $DFA0
177A-   C4 D5       CPY   $D5
177C-   CD D0 A0    CMP   $A0D0
177F-   C1 D2       CMP   ($D2,X)
1781-   D2 C1       CMP   ($C1)
1783-   D9 B2 AB    CMP   $ABB2,Y
1786-   B5 B3       LDA   $B3,X
1788-   BB          ???
1789-   A3          ???
178A-   B1 B0       LDA   ($B0),Y
178C-   8D A0 DF    STA   $DFA0
178F-   C4 D5       CPY   $D5
1791-   CD D0 A0    CMP   $A0D0
1794-   C1 D2       CMP   ($D2,X)
1796-   D2 C1       CMP   ($C1)
1798-   D9 B2 AB    CMP   $ABB2,Y
179B-   B6 B3       LDX   $B3,Y
179D-   BB          ???
179E-   A3          ???
179F-   B1 B0       LDA   ($B0),Y
17A1-   8D A0 DF    STA   $DFA0
17A4-   C4 D5       CPY   $D5
17A6-   CD D0 A0    CMP   $A0D0
17A9-   C1 D2       CMP   ($D2,X)
17AB-   D2 C1       CMP   ($C1)
17AD-   D9 B2 AB    CMP   $ABB2,Y
17B0-   B7          ???
17B1-   B3          ???
17B2-   BB          ???
17B3-   A3          ???
17B4-   B1 B0       LDA   ($B0),Y
17B6-   8D A0 DF    STA   $DFA0
17B9-   C4 D5       CPY   $D5
17BB-   CD D0 A0    CMP   $A0D0
17BE-   C1 D2       CMP   ($D2,X)
17C0-   D2 C1       CMP   ($C1)
17C2-   D9 B2 AB    CMP   $ABB2,Y
17C5-   B8          CLV
17C6-   B3          ???
17C7-   BB          ???
17C8-   A3          ???
17C9-   B1 B0       LDA   ($B0),Y
17CB-   8D A0 DF    STA   $DFA0
17CE-   C4 D5       CPY   $D5
17D0-   CD D0 A0    CMP   $A0D0
17D3-   C1 D2       CMP   ($D2,X)
17D5-   D2 C1       CMP   ($C1)
17D7-   D9 B2 AB    CMP   $ABB2,Y
17DA-   B9 B3 BB    LDA   $BBB3,Y
17DD-   A3          ???
17DE-   B1 B0       LDA   ($B0),Y
17E0-   8D A0 DF    STA   $DFA0
17E3-   D0 D2       BNE   $17B7
17E5-   CE D4 A0    DEC   $A0D4
17E8-   A2 20       LDX   #$20
17EA-   A2 AC       LDX   #$AC
17EC-   B8          CLV
17ED-   C4 B8       CPY   $B8
17EF-   C4 8D       CPY   $8D
17F1-   A0 DF       LDY   #$DF
17F3-   D7          ???
17F4-   C1 C9       CMP   ($C9,X)
17F6-   D4          ???
17F7-   8D AA 8D    STA   $8DAA
17FA-   AA          TAX
17FB-   AA          TAX
17FC-   20 D4 C8    JSR   $C8D4
17FF-   C5 20       CMP   $20
1801-   D0 D5       BNE   $17D8
1803-   D4          ???
1804-   B8          CLV
1805-   B2 20       LDA   ($20)
1807-   CD C1 C3    CMP   $C3C1
180A-   D2 CF       CMP   ($CF)
180C-   20 CD C9    JSR   $C9CD
180F-   D2 D2       CMP   ($D2)
1811-   CF          ???
1812-   D2 D3       CMP   ($D3)
1814-   20 D0 D5    JSR   $D5D0
1817-   D4          ???
1818-   B8          CLV
1819-   B1 AC       LDA   ($AC),Y
181B-   20 C2 D5    JSR   $D5C2
181E-   D4          ???
181F-   20 C9 CE    JSR   $CEC9
1822-   20 B2 20    JSR   $20B2
1825-   C4 C9       CPY   $C9
1827-   CD C5 CE    CMP   $CEC5
182A-   D3          ???
182B-   C9 CF       CMP   #$CF
182D-   CE D3 AE    DEC   $AED3
1830-   8D AA AA    STA   $AAAA
1833-   20 C9 CE    JSR   $CEC9
1836-   20 D3 C8    JSR   $C8D3
1839-   CF          ???
183A-   D2 D4       CMP   ($D4)
183C-   AC 20 C9    LDY   $C920
183F-   D4          ???
1840-   20 D3 C9    JSR   $C9D3
1843-   CD D0 CC    CMP   $CCD0
1846-   D9 20 D0    CMP   $D020,Y
1849-   D5 D4       CMP   $D4,X
184B-   D3          ???
184C-   20 D4 C8    JSR   $C8D4
184F-   C5 20       CMP   $20
1851-   D3          ???
1852-   D4          ???
1853-   D2 C9       CMP   ($C9)
1855-   CE C7 20    DEC   $20C7
1858-   CF          ???
1859-   C6 20       DEC   $20
185B-   C2          ???
185C-   D9 D4 C5    CMP   $C5D4,Y
185F-   D3          ???
1860-   8D AA AA    STA   $AAAA
1863-   20 C6 CF    JSR   $CFC6
1866-   D5 CE       CMP   $CE,X
1868-   C4 20       CPY   $20
186A-   C1 D4       CMP   ($D4,X)
186C-   20 D3 CF    JSR   $CFD3
186F-   D5 D2       CMP   $D2,X
1871-   C3          ???
1872-   C5 DF       CMP   $DF
1874-   C1 C4       CMP   ($C4,X)
1876-   C4 D2       CPY   $D2
1878-   20 D4 C8    JSR   $C8D4
187B-   C1 D4       CMP   ($D4,X)
187D-   20 C3 CF    JSR   $CFC3
1880-   D2 D2       CMP   ($D2)
1882-   C5 CC       CMP   $CC
1884-   C1 D4       CMP   ($D4,X)
1886-   C5 20       CMP   $20
1888-   D4          ???
1889-   CF          ???
188A-   20 D4 C8    JSR   $C8D4
188D-   C5 20       CMP   $20
188F-   C1 D2       CMP   ($D2,X)
1891-   D2 C1       CMP   ($C1)
1893-   D9 A7 D3    CMP   $D3A7,Y
1896-   8D AA AA    STA   $AAAA
1899-   20 C5 CC    JSR   $CCC5
189C-   C5 CD       CMP   $CD
189E-   C5 CE       CMP   $CE
18A0-   D4          ???
18A1-   20 CC C5    JSR   $C5CC
18A4-   CE C7 D4    DEC   $D4C7
18A7-   C8          INY
18A8-   20 C9 CE    JSR   $CEC9
18AB-   D4          ???
18AC-   CF          ???
18AD-   20 D4 C8    JSR   $C8D4
18B0-   C5 20       CMP   $20
18B2-   D3          ???
18B3-   D0 C5       BNE   $187A
18B5-   C3          ???
18B6-   C9 C6       CMP   #$C6
18B8-   C9 C5       CMP   #$C5
18BA-   C4 20       CPY   $20
18BC-   D8          CLD
18BD-   AC D9 20    LDY   $20D9
18C0-   C9 CE       CMP   #$CE
18C2-   C4 C5       CPY   $C5
18C4-   D8          CLD
18C5-   AE 8D AA    LDX   $AA8D
18C8-   8D AA AA    STA   $AAAA
18CB-   20 CD C1    JSR   $C1CD
18CE-   C3          ???
18CF-   D2 CF       CMP   ($CF)
18D1-   BA          TSX
18D2-   20 D0 D5    JSR   $D5D0
18D5-   D4          ???
18D6-   B8          CLV
18D7-   B2 20       LDA   ($20)
18D9-   D3          ???
18DA-   CF          ???
18DB-   D5 D2       CMP   $D2,X
18DD-   C3          ???
18DE-   C5 DF       CMP   $DF
18E0-   C1 C4       CMP   ($C4,X)
18E2-   C4 D2       CPY   $D2
18E4-   BB          ???
18E5-   C1 D2       CMP   ($D2,X)
18E7-   D2 C1       CMP   ($C1)
18E9-   D9 DF C1    CMP   $C1DF,Y
18EC-   C4 C4       CPY   $C4
18EE-   D2 BB       CMP   ($BB)
18F0-   D8          CLD
18F1-   DF          ???
18F2-   C9 CE       CMP   #$CE
18F4-   C4 C5       CPY   $C5
18F6-   D8          CLD
18F7-   BB          ???
18F8-   D9 DF C9    CMP   $C9DF,Y
18FB-   CE C4 C5    DEC   $C5C4
18FE-   D8          CLD
18FF-   8D AA 8D    STA   $8DAA
1902-   A0 DF       LDY   #$DF
1904-   D0 D2       BNE   $18D8
1906-   CE D4 A0    DEC   $A0D4
1909-   A2 D0       LDX   #$D0
190B-   D5 D4       CMP   $D4,X
190D-   B8          CLV
190E-   B2 20       LDA   ($20)
1910-   C1 C3       CMP   ($C3,X)
1912-   D4          ???
1913-   D3          ???
1914-   20 CC C9    JSR   $C9CC
1917-   CB          ???
1918-   C5 20       CMP   $20
191A-   D0 D5       BNE   $18F1
191C-   D4          ???
191D-   B8          CLV
191E-   B1 AC       LDA   ($AC),Y
1920-   20 C2 D5    JSR   $D5C2
1923-   D4          ???
1924-   20 C9 CE    JSR   $CEC9
1927-   20 D4 D7    JSR   $D7D4
192A-   CF          ???
192B-   A2 AC       LDX   #$AC
192D-   B8          CLV
192E-   C4 8D       CPY   $8D
1930-   A0 DF       LDY   #$DF
1932-   D0 D2       BNE   $1906
1934-   CE D4 A0    DEC   $A0D4
1937-   A2 C4       LDX   #$C4
1939-   C9 CD       CMP   #$CD
193B-   C5 CE       CMP   $CE
193D-   D3          ???
193E-   C9 CF       CMP   #$CF
1940-   CE D3 AE    DEC   $AED3
1943-   20 A2 AC    JSR   $ACA2
1946-   B8          CLV
1947-   C4 B8       CPY   $B8
1949-   C4 8D       CPY   $8D
194B-   A0 DF       LDY   #$DF
194D-   D0 D2       BNE   $1921
194F-   CE D4 A0    DEC   $A0D4
1952-   A2 D3       LDX   #$D3
1954-   CF          ???
1955-   BA          TSX
1956-   20 D0 D5    JSR   $D5D0
1959-   D4          ???
195A-   B8          CLV
195B-   B2 20       LDA   ($20)
195D-   A4 B3       LDY   $B3
195F-   B2 B0       LDA   ($B0)
1961-   BB          ???
1962-   C1 D2       CMP   ($D2,X)
1964-   D2 C1       CMP   ($C1)
1966-   D9 B2 BB    CMP   $BBB2,Y
1969-   A3          ???
196A-   B1 BB       LDA   ($BB),Y
196C-   A3          ???
196D-   B5 20       LDA   $20,X
196F-   D2 C5       CMP   ($C5)
1971-   D4          ???
1972-   D5 D2       CMP   $D2,X
1974-   CE D3 A2    DEC   $A2D3
1977-   AC B8 C4    LDY   $C4B8
197A-   B8          CLV
197B-   C4 8D       CPY   $8D
197D-   A0 CC       LDY   #$CC
197F-   C4 C1       CPY   $C1
1981-   A0 A3       LDY   #$A3
1983-   A4 B0       LDY   $B0
1985-   C6 8D       DEC   $8D
1987-   A0 D3       LDY   #$D3
1989-   D4          ???
198A-   C1 A0       CMP   ($A0,X)
198C-   A4 B3       LDY   $B3
198E-   B2 B0       LDA   ($B0)
1990-   8D A0 CC    STA   $CCA0
1993-   C4 C1       CPY   $C1
1995-   A0 A3       LDY   #$A3
1997-   A4 C6       LDY   $C6
1999-   C6 8D       DEC   $8D
199B-   A0 D3       LDY   #$D3
199D-   D4          ???
199E-   C1 A0       CMP   ($A0,X)
19A0-   A4 B3       LDY   $B3
19A2-   B2 B1       LDA   ($B1)
19A4-   8D A0 D0    STA   $D0A0
19A7-   D5 D4       CMP   $D4,X
19A9-   B8          CLV
19AA-   B2 A0       LDA   ($A0)
19AC-   A4 B3       LDY   $B3
19AE-   B2 B0       LDA   ($B0)
19B0-   BB          ???
19B1-   C1 D2       CMP   ($D2,X)
19B3-   D2 C1       CMP   ($C1)
19B5-   D9 B2 BB    CMP   $BBB2,Y
19B8-   A3          ???
19B9-   B0 B1       BCS   $196C
19BB-   BB          ???
19BC-   A3          ???
19BD-   B0 B5       BCS   $1974
19BF-   8D A0 DF    STA   $DFA0
19C2-   C4 D5       CPY   $D5
19C4-   CD D0 A0    CMP   $A0D0
19C7-   C1 D2       CMP   ($D2,X)
19C9-   D2 C1       CMP   ($C1)
19CB-   D9 B2 BB    CMP   $BBB2,Y
19CE-   A3          ???
19CF-   B0 B3       BCS   $1984
19D1-   8D A0 DF    STA   $DFA0
19D4-   C4 D5       CPY   $D5
19D6-   CD D0 A0    CMP   $A0D0
19D9-   C1 D2       CMP   ($D2,X)
19DB-   D2 C1       CMP   ($C1)
19DD-   D9 B2 AB    CMP   $ABB2,Y
19E0-   B0 B3       BCS   $1995
19E2-   BB          ???
19E3-   A3          ???
19E4-   B1 B0       LDA   ($B0),Y
19E6-   8D A0 DF    STA   $DFA0
19E9-   C4 D5       CPY   $D5
19EB-   CD D0 A0    CMP   $A0D0
19EE-   C1 D2       CMP   ($D2,X)
19F0-   D2 C1       CMP   ($C1)
19F2-   D9 B2 AB    CMP   $ABB2,Y
19F5-   B1 B3       LDA   ($B3),Y
19F7-   BB          ???
19F8-   A3          ???
19F9-   B1 B0       LDA   ($B0),Y
19FB-   8D A0 DF    STA   $DFA0
19FE-   C4 D5       CPY   $D5
1A00-   CD D0 A0    CMP   $A0D0
1A03-   C1 D2       CMP   ($D2,X)
1A05-   D2 C1       CMP   ($C1)
1A07-   D9 B2 AB    CMP   $ABB2,Y
1A0A-   B2 B3       LDA   ($B3)
1A0C-   BB          ???
1A0D-   A3          ???
1A0E-   B1 B0       LDA   ($B0),Y
1A10-   8D A0 DF    STA   $DFA0
1A13-   C4 D5       CPY   $D5
1A15-   CD D0 A0    CMP   $A0D0
1A18-   C1 D2       CMP   ($D2,X)
1A1A-   D2 C1       CMP   ($C1)
1A1C-   D9 B2 AB    CMP   $ABB2,Y
1A1F-   B3          ???
1A20-   B3          ???
1A21-   BB          ???
1A22-   A3          ???
1A23-   B1 B0       LDA   ($B0),Y
1A25-   8D A0 DF    STA   $DFA0
1A28-   C4 D5       CPY   $D5
1A2A-   CD D0 A0    CMP   $A0D0
1A2D-   C1 D2       CMP   ($D2,X)
1A2F-   D2 C1       CMP   ($C1)
1A31-   D9 B2 AB    CMP   $ABB2,Y
1A34-   B4 B3       LDY   $B3,X
1A36-   BB          ???
1A37-   A3          ???
1A38-   B1 B0       LDA   ($B0),Y
1A3A-   8D A0 DF    STA   $DFA0
1A3D-   C4 D5       CPY   $D5
1A3F-   CD D0 A0    CMP   $A0D0
1A42-   C1 D2       CMP   ($D2,X)
1A44-   D2 C1       CMP   ($C1)
1A46-   D9 B2 AB    CMP   $ABB2,Y
1A49-   B5 B3       LDA   $B3,X
1A4B-   BB          ???
1A4C-   A3          ???
1A4D-   B1 B0       LDA   ($B0),Y
1A4F-   8D A0 DF    STA   $DFA0
1A52-   C4 D5       CPY   $D5
1A54-   CD D0 A0    CMP   $A0D0
1A57-   C1 D2       CMP   ($D2,X)
1A59-   D2 C1       CMP   ($C1)
1A5B-   D9 B2 AB    CMP   $ABB2,Y
1A5E-   B6 B3       LDX   $B3,Y
1A60-   BB          ???
1A61-   A3          ???
1A62-   B1 B0       LDA   ($B0),Y
1A64-   8D A0 DF    STA   $DFA0
1A67-   C4 D5       CPY   $D5
1A69-   CD D0 A0    CMP   $A0D0
1A6C-   C1 D2       CMP   ($D2,X)
1A6E-   D2 C1       CMP   ($C1)
1A70-   D9 B2 AB    CMP   $ABB2,Y
1A73-   B7          ???
1A74-   B3          ???
1A75-   BB          ???
1A76-   A3          ???
1A77-   B1 B0       LDA   ($B0),Y
1A79-   8D A0 DF    STA   $DFA0
1A7C-   C4 D5       CPY   $D5
1A7E-   CD D0 A0    CMP   $A0D0
1A81-   C1 D2       CMP   ($D2,X)
1A83-   D2 C1       CMP   ($C1)
1A85-   D9 B2 AB    CMP   $ABB2,Y
1A88-   B8          CLV
1A89-   B3          ???
1A8A-   BB          ???
1A8B-   A3          ???
1A8C-   B1 B0       LDA   ($B0),Y
1A8E-   8D A0 DF    STA   $DFA0
1A91-   C4 D5       CPY   $D5
1A93-   CD D0 A0    CMP   $A0D0
1A96-   C1 D2       CMP   ($D2,X)
1A98-   D2 C1       CMP   ($C1)
1A9A-   D9 B2 AB    CMP   $ABB2,Y
1A9D-   B9 B3 BB    LDA   $BBB3,Y
1AA0-   A3          ???
1AA1-   B1 B0       LDA   ($B0),Y
1AA3-   8D A0 DF    STA   $DFA0
1AA6-   D0 D2       BNE   $1A7A
1AA8-   CE D4 A0    DEC   $A0D4
1AAB-   A2 20       LDX   #$20
1AAD-   A2 AC       LDX   #$AC
1AAF-   B8          CLV
1AB0-   C4 B8       CPY   $B8
1AB2-   C4 8D       CPY   $8D
1AB4-   A0 DF       LDY   #$DF
1AB6-   D7          ???
1AB7-   C1 C9       CMP   ($C9,X)
1AB9-   D4          ???
1ABA-   8D AA 8D    STA   $8DAA
1ABD-   AA          TAX
1ABE-   AA          TAX
1ABF-   20 C6 C9    JSR   $C9C6
1AC2-   CE C1 CC    DEC   $CCC1
1AC5-   CC D9 AC    CPY   $ACD9
1AC8-   20 C7 C5    JSR   $C5C7
1ACB-   D4          ???
1ACC-   B8          CLV
1ACD-   B2 20       LDA   ($20)
1ACF-   C7          ???
1AD0-   C5 D4       CMP   $D4
1AD2-   D3          ???
1AD3-   20 D4 C8    JSR   $C8D4
1AD6-   C5 20       CMP   $20
1AD8-   D6 C1       DEC   $C1,X
1ADA-   CC D5 C5    CPY   $C5D5
1ADD-   20 C1 D4    JSR   $D4C1
1AE0-   20 C1 20    JSR   $20C1
1AE3-   C7          ???
1AE4-   C9 D6       CMP   #$D6
1AE6-   C5 CE       CMP   $CE
1AE8-   20 D8 AC    JSR   $ACD8
1AEB-   D9 8D AA    CMP   $AA8D,Y
1AEE-   AA          TAX
1AEF-   20 C9 CE    JSR   $CEC9
1AF2-   C4 C5       CPY   $C5
1AF4-   D8          CLD
1AF5-   20 C1 CE    JSR   $CEC1
1AF8-   C4 20       CPY   $20
1AFA-   D0 CC       BNE   $1AC8
1AFC-   C1 C3       CMP   ($C3,X)
1AFE-   C5 D3       CMP   $D3
1B00-   20 C9 D4    JSR   $D4C9
1B03-   20 C9 CE    JSR   $CEC9
1B06-   20 DB D2    JSR   $D2DB
1B09-   C5 D4       CMP   $D4
1B0B-   D5 D2       CMP   $D2,X
1B0D-   CE DD 20    DEC   $20DD
1B10-   D7          ???
1B11-   C9 D4       CMP   #$D4
1B13-   C8          INY
1B14-   20 D4 C8    JSR   $C8D4
1B17-   C5 8D       CMP   $8D
1B19-   AA          TAX
1B1A-   AA          TAX
1B1B-   20 C5 CC    JSR   $CCC5
1B1E-   C5 CD       CMP   $CD
1B20-   C5 CE       CMP   $CE
1B22-   D4          ???
1B23-   20 CC C5    JSR   $C5CC
1B26-   CE C7 D4    DEC   $D4C7
1B29-   C8          INY
1B2A-   20 C9 CE    JSR   $CEC9
1B2D-   20 DB D2    JSR   $D2DB
1B30-   C5 D4       CMP   $D4
1B32-   CC C5 CE    CPY   $CEC5
1B35-   DD AE 8D    CMP   $8DAE,X
1B38-   AA          TAX
1B39-   8D AA AA    STA   $AAAA
1B3C-   20 CD C1    JSR   $C1CD
1B3F-   C3          ???
1B40-   D2 CF       CMP   ($CF)
1B42-   BA          TSX
1B43-   20 C7 C5    JSR   $C5C7
1B46-   D4          ???
1B47-   B8          CLV
1B48-   B2 20       LDA   ($20)
1B4A-   C1 D2       CMP   ($D2,X)
1B4C-   D2 C1       CMP   ($C1)
1B4E-   D9 DF C1    CMP   $C1DF,Y
1B51-   C4 C4       CPY   $C4
1B53-   D2 BB       CMP   ($BB)
1B55-   D8          CLD
1B56-   DF          ???
1B57-   C9 CE       CMP   #$CE
1B59-   C4 C5       CPY   $C5
1B5B-   D8          CLD
1B5C-   BB          ???
1B5D-   D9 DF C9    CMP   $C9DF,Y
1B60-   CE C4 C5    DEC   $C5C4
1B63-   D8          CLD
1B64-   8D AA 8D    STA   $8DAA
1B67-   A0 DF       LDY   #$DF
1B69-   D0 D2       BNE   $1B3D
1B6B-   CE D4 A0    DEC   $A0D4
1B6E-   A2 CC       LDX   #$CC
1B70-   C9 CB       CMP   #$CB
1B72-   C5 D7       CMP   $D7
1B74-   C9 D3       CMP   #$D3
1B76-   C5 AC       CMP   $AC
1B78-   20 C7 C5    JSR   $C5C7
1B7B-   D4          ???
1B7C-   B8          CLV
1B7D-   B2 20       LDA   ($20)
1B7F-   C1 C3       CMP   ($C3,X)
1B81-   D4          ???
1B82-   D3          ???
1B83-   20 CC C9    JSR   $C9CC
1B86-   CB          ???
1B87-   C5 20       CMP   $20
1B89-   C7          ???
1B8A-   C5 D4       CMP   $D4
1B8C-   B8          CLV
1B8D-   B1 AC       LDA   ($AC),Y
1B8F-   A2 AC       LDX   #$AC
1B91-   B8          CLV
1B92-   C4 8D       CPY   $8D
1B94-   A0 DF       LDY   #$DF
1B96-   D0 D2       BNE   $1B6A
1B98-   CE D4 A0    DEC   $A0D4
1B9B-   A2 C2       LDX   #$C2
1B9D-   D5 D4       CMP   $D4,X
1B9F-   20 C9 CE    JSR   $CEC9
1BA2-   20 D4 D7    JSR   $D7D4
1BA5-   CF          ???
1BA6-   20 C4 C9    JSR   $C9C4
1BA9-   CD C5 CE    CMP   $CEC5
1BAC-   D3          ???
1BAD-   C9 CF       CMP   #$CF
1BAF-   CE D3 AE    DEC   $AED3
1BB2-   20 A2 AC    JSR   $ACA2
1BB5-   B8          CLV
1BB6-   C4 B8       CPY   $B8
1BB8-   C4 8D       CPY   $8D
1BBA-   A0 DF       LDY   #$DF
1BBC-   D0 D2       BNE   $1B90
1BBE-   CE D4 A0    DEC   $A0D4
1BC1-   A2 D4       LDX   #$D4
1BC3-   C8          INY
1BC4-   D5 D3       CMP   $D3,X
1BC6-   BA          TSX
1BC7-   20 C7 C5    JSR   $C5C7
1BCA-   D4          ???
1BCB-   B8          CLV
1BCC-   B2 20       LDA   ($20)
1BCE-   C1 D2       CMP   ($D2,X)
1BD0-   D2 C1       CMP   ($C1)
1BD2-   D9 B2 BB    CMP   $BBB2,Y
1BD5-   A3          ???
1BD6-   B1 BB       LDA   ($BB),Y
1BD8-   A3          ???
1BD9-   B5 20       LDA   $20,X
1BDB-   D2 C5       CMP   ($C5)
1BDD-   D4          ???
1BDE-   D5 D2       CMP   $D2,X
1BE0-   CE D3 BA    DEC   $BAD3
1BE3-   A2 AC       LDX   #$AC
1BE5-   B8          CLV
1BE6-   C4 B8       CPY   $B8
1BE8-   C4 8D       CPY   $8D
1BEA-   A0 C7       LDY   #$C7
1BEC-   C5 D4       CMP   $D4
1BEE-   B8          CLV
1BEF-   B2 A0       LDA   ($A0)
1BF1-   C1 D2       CMP   ($D2,X)
1BF3-   D2 C1       CMP   ($C1)
1BF5-   D9 B2 BB    CMP   $BBB2,Y
1BF8-   A3          ???
1BF9-   B1 BB       LDA   ($BB),Y
1BFB-   A3          ???
1BFC-   B5 8D       LDA   $8D,X
1BFE-   A0 DF       LDY   #$DF
1C00-   C4 D5       CPY   $D5
1C02-   CD D0 A0    CMP   $A0D0
1C05-   D2 C5       CMP   ($C5)
1C07-   D4          ???
1C08-   D5 D2       CMP   $D2,X
1C0A-   CE BB D2    DEC   $D2BB
1C0D-   C5 D4       CMP   $D4
1C0F-   CC C5 CE    CPY   $CEC5
1C12-   8D A0 DF    STA   $DFA0
1C15-   D7          ???
1C16-   C1 C9       CMP   ($C9,X)
1C18-   D4          ???
1C19-   8D AA 8D    STA   $8DAA
1C1C-   A0 DF       LDY   #$DF
1C1E-   D0 D2       BNE   $1BF2
1C20-   CE D4 A0    DEC   $A0D4
1C23-   A2 20       LDX   #$20
1C25-   A2 AC       LDX   #$AC
1C27-   B8          CLV
1C28-   C4 B8       CPY   $B8
1C2A-   C4 8D       CPY   $8D
1C2C-   A0 DF       LDY   #$DF
1C2E-   D0 D2       BNE   $1C02
1C30-   CE D4 A0    DEC   $A0D4
1C33-   A2 C6       LDX   #$C6
1C35-   C9 CE       CMP   #$CE
1C37-   AE A2 AC    LDX   $ACA2
1C3A-   B8          CLV
1C3B-   C4 B8       CPY   $B8
1C3D-   C4 B8       CPY   $B8
1C3F-   C4 8D       CPY   $8D
1C41-   AA          TAX
1C42-   8D A0 CA    STA   $CAA0
1C45-   CD D0 A0    CMP   $A0D0
1C48-   D2 C5       CMP   ($C5)
1C4A-   C5 CE       CMP   $CE
1C4C-   D4          ???
1C4D-   D2 D9       CMP   ($D9)
1C4F-   8D AA 8D    STA   $8DAA
1C52-   AA          TAX
1C53-   E0 E0       CPX   #$E0
1C55-   E0 E0       CPX   #$E0
1C57-   E0 E0       CPX   #$E0
1C59-   E0 E0       CPX   #$E0
1C5B-   E0 E0       CPX   #$E0
1C5D-   E0 E0       CPX   #$E0
1C5F-   E0 E0       CPX   #$E0
1C61-   E0 E0       CPX   #$E0
1C63-   E0 E0       CPX   #$E0
1C65-   E0 E0       CPX   #$E0
1C67-   E0 E0       CPX   #$E0
1C69-   E0 E0       CPX   #$E0
1C6B-   E0 E0       CPX   #$E0
1C6D-   E0 E0       CPX   #$E0
1C6F-   E0 E0       CPX   #$E0
1C71-   AA          TAX
1C72-   8D AA 20    STA   $20AA
1C75-   C2          ???
1C76-   CF          ???
1C77-   D4          ???
1C78-   D4          ???
1C79-   CF          ???
1C7A-   CD 20 C9    CMP   $C920
1C7D-   CE C3 CC    DEC   $CCC3
1C80-   D5 C4       CMP   $C4,X
1C82-   C5 D3       CMP   $D3
1C84-   20 A8 D2    JSR   $D2A8
1C87-   CF          ???
1C88-   D5 D4       CMP   $D4,X
1C8A-   C9 CE       CMP   #$CE
1C8C-   C5 D3       CMP   $D3
1C8E-   A9 20       LDA   #$20
1C90-   20 20 AA    JSR   $AA20
1C93-   8D AA AC    STA   $ACAA
1C96-   AC AC AC    LDY   $ACAC
1C99-   AC AC AC    LDY   $ACAC
1C9C-   AC AC AC    LDY   $ACAC
1C9F-   AC AC AC    LDY   $ACAC
1CA2-   AC AC AC    LDY   $ACAC
1CA5-   AC AC AC    LDY   $ACAC
1CA8-   AC AC AC    LDY   $ACAC
1CAB-   AC AC AC    LDY   $ACAC
1CAE-   AC AC AC    LDY   $ACAC
1CB1-   AC AC AA    LDY   $AAAC
1CB4-   8D AA 8D    STA   $8DAA
1CB7-   A0 D0       LDY   #$D0
1CB9-   D5 D4       CMP   $D4,X
1CBB-   A0 D2       LDY   #$D2
1CBD-   C5 D1       CMP   $D1
1CBF-   D5 C9       CMP   $C9,X
1CC1-   D2 C5       CMP   ($C5)
1CC3-   C4 AE       CPY   $AE
1CC5-   CC C9 C2    CPY   $C2C9
1CC8-   AE CD C9    LDX   $C9CD
1CCB-   CE 8D AA    DEC   $AA8D
1CCE-   8D AA AA    STA   $AAAA
1CD1-   20 C9 CE    JSR   $CEC9
1CD4-   C4 C9       CPY   $C9
1CD6-   D6 C9       DEC   $C9,X
1CD8-   C4 D5       CPY   $D5
1CDA-   C1 CC       CMP   ($CC,X)
1CDC-   20 D3 D5    JSR   $D5D3
1CDF-   C2          ???
1CE0-   D2 CF       CMP   ($CF)
1CE2-   D5 D4       CMP   $D4,X
1CE4-   C9 CE       CMP   #$CE
1CE6-   C5 20       CMP   $20
1CE8-   C9 CE       CMP   #$CE
1CEA-   C3          ???
1CEB-   CC D5 C4    CPY   $C4D5
1CEE-   C5 D3       CMP   $D3
1CF0-   8D AA 8D    STA   $8DAA
1CF3-   AA          TAX
1CF4-   AA          TAX
1CF5-   20 B8 AD    JSR   $ADB8
1CF8-   C2          ???
1CF9-   C9 D4       CMP   #$D4
1CFB-   20 B1 AD    JSR   $ADB1
1CFE-   C4 C9       CPY   $C9
1D00-   CD C5 CE    CMP   $CEC5
1D03-   D3          ???
1D04-   C9 CF       CMP   #$CF
1D06-   CE C1 CC    DEC   $CCC1
1D09-   20 C1 D2    JSR   $D2C1
1D0C-   D2 C1       CMP   ($C1)
1D0E-   D9 20 D3    CMP   $D320,Y
1D11-   D5 C2       CMP   $C2,X
1D13-   D2 CF       CMP   ($CF)
1D15-   D5 D4       CMP   $D4,X
1D17-   C9 CE       CMP   #$CE
1D19-   C5 D3       CMP   $D3
1D1B-   8D AA 8D    STA   $8DAA
1D1E-   A0 D0       LDY   #$D0
1D20-   D5 D4       CMP   $D4,X
1D22-   A0 C1       LDY   #$C1
1D24-   C4 C9       CPY   $C9
1D26-   CD B8 B1    CMP   $B1B8
1D29-   AE D3 D5    LDX   $D5D3
1D2C-   C2          ???
1D2D-   AE CD C9    LDX   $C9CD
1D30-   CE 8D A0    DEC   $A08D
1D33-   D0 D5       BNE   $1D0A
1D35-   D4          ???
1D36-   A0 C1       LDY   #$C1
1D38-   C7          ???
1D39-   C5 D4       CMP   $D4
1D3B-   B8          CLV
1D3C-   B1 AE       LDA   ($AE),Y
1D3E-   D3          ???
1D3F-   D5 C2       CMP   $C2,X
1D41-   AE CD C9    LDX   $C9CD
1D44-   CE 8D A0    DEC   $A08D
1D47-   D0 D5       BNE   $1D1E
1D49-   D4          ???
1D4A-   A0 C1       LDY   #$C1
1D4C-   D0 D5       BNE   $1D23
1D4E-   D4          ???
1D4F-   B8          CLV
1D50-   B1 AE       LDA   ($AE),Y
1D52-   D3          ???
1D53-   D5 C2       CMP   $C2,X
1D55-   AE CD C9    LDX   $C9CD
1D58-   CE 8D AA    DEC   $AA8D
1D5B-   8D AA AA    STA   $AAAA
1D5E-   20 B8 AD    JSR   $ADB8
1D61-   C2          ???
1D62-   C9 D4       CMP   #$D4
1D64-   20 B2 AD    JSR   $ADB2
1D67-   C4 C9       CPY   $C9
1D69-   CD C5 CE    CMP   $CEC5
1D6C-   D3          ???
1D6D-   C9 CF       CMP   #$CF
1D6F-   CE C1 CC    DEC   $CCC1
1D72-   20 C1 D2    JSR   $D2C1
1D75-   D2 C1       CMP   ($C1)
1D77-   D9 20 D3    CMP   $D320,Y
1D7A-   D5 C2       CMP   $C2,X
1D7C-   D2 CF       CMP   ($CF)
1D7E-   D5 D4       CMP   $D4,X
1D80-   C9 CE       CMP   #$CE
1D82-   C5 D3       CMP   $D3
1D84-   8D AA 8D    STA   $8DAA
1D87-   A0 D0       LDY   #$D0
1D89-   D5 D4       CMP   $D4,X
1D8B-   A0 C1       LDY   #$C1
1D8D-   C4 C9       CPY   $C9
1D8F-   CD B8 B2    CMP   $B2B8
1D92-   AE D3 D5    LDX   $D5D3
1D95-   C2          ???
1D96-   AE CD C9    LDX   $C9CD
1D99-   CE 8D A0    DEC   $A08D
1D9C-   D0 D5       BNE   $1D73
1D9E-   D4          ???
1D9F-   A0 C1       LDY   #$C1
1DA1-   C7          ???
1DA2-   C5 D4       CMP   $D4
1DA4-   B8          CLV
1DA5-   B2 AE       LDA   ($AE)
1DA7-   D3          ???
1DA8-   D5 C2       CMP   $C2,X
1DAA-   AE CD C9    LDX   $C9CD
1DAD-   CE 8D A0    DEC   $A08D
1DB0-   D0 D5       BNE   $1D87
1DB2-   D4          ???
1DB3-   A0 C1       LDY   #$C1
1DB5-   D0 D5       BNE   $1D8C
1DB7-   D4          ???
1DB8-   B8          CLV
1DB9-   B2 AE       LDA   ($AE)
1DBB-   D3          ???
1DBC-   D5 C2       CMP   $C2,X
1DBE-   AE CD C9    LDX   $C9CD
1DC1-   CE 8D AA    DEC   $AA8D
1DC4-   8D 00 00    STA   $0000
