0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C1    LDY   $C120,X
0950-   D2 D2       CMP   ($D2)
0952-   C1 D9       CMP   ($D9,X)
0954-   D3          ???
0955-   20 C4 C5    JSR   $C5C4
0958-   CD CF 20    CMP   $20CF
095B-   BE AD 20    LDX   $20AD,Y
095E-   20 20 20    JSR   $2020
0961-   20 20 20    JSR   $2020
0964-   AA          TAX
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B1    JSR   $B120
09D4-   B5 AD       LDA   $AD,X
09D6-   CA          DEX
09D7-   C1 CE       CMP   ($CE,X)
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B9       LDA   ($B9),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   C6 C6       DEC   $C6
0AFE-   8D A0 D4    STA   $D4A0
0B01-   D2 A0       CMP   ($A0)
0B03-   CF          ???
0B04-   CE 8D A0    DEC   $A08D
0B07-   C4 D3       CPY   $D3
0B09-   CB          ???
0B0A-   A0 C1       LDY   #$C1
0B0C-   D2 D2       CMP   ($D2)
0B0E-   C1 D9       CMP   ($D9,X)
0B10-   D3          ???
0B11-   AE C4 C5    LDX   $C5C4
0B14-   CD CF 8D    CMP   $8DCF
0B17-   A0 CF       LDY   #$CF
0B19-   C2          ???
0B1A-   CA          DEX
0B1B-   A0 A4       LDY   #$A4
0B1D-   C2          ???
0B1E-   C6 C5       DEC   $C5
0B20-   B0 8D       BCS   $0AAF
0B22-   A0 CF       LDY   #$CF
0B24-   D2 C7       CMP   ($C7)
0B26-   A0 A4       LDY   #$A4
0B28-   B6 B0       LDX   $B0,Y
0B2A-   B0 B0       BCS   $0ADC
0B2C-   8D AA 8D    STA   $8DAA
0B2F-   AA          TAX
0B30-   E0 E0       CPX   #$E0
0B32-   E0 E0       CPX   #$E0
0B34-   E0 E0       CPX   #$E0
0B36-   E0 E0       CPX   #$E0
0B38-   E0 E0       CPX   #$E0
0B3A-   E0 E0       CPX   #$E0
0B3C-   E0 E0       CPX   #$E0
0B3E-   E0 E0       CPX   #$E0
0B40-   E0 E0       CPX   #$E0
0B42-   E0 E0       CPX   #$E0
0B44-   E0 E0       CPX   #$E0
0B46-   E0 E0       CPX   #$E0
0B48-   E0 E0       CPX   #$E0
0B4A-   E0 E0       CPX   #$E0
0B4C-   E0 E0       CPX   #$E0
0B4E-   AA          TAX
0B4F-   8D AA 20    STA   $20AA
0B52-   20 D4 CF    JSR   $CFD4
0B55-   D0 20       BNE   $0B77
0B57-   C9 CE       CMP   #$CE
0B59-   C3          ???
0B5A-   CC D5 C4    CPY   $C4D5
0B5D-   C5 D3       CMP   $D3
0B5F-   20 A8 C8    JSR   $C8A8
0B62-   CF          ???
0B63-   CF          ???
0B64-   CB          ???
0B65-   D3          ???
0B66-   AC CD C1    LDY   $C1CD
0B69-   C3          ???
0B6A-   D2 CF       CMP   ($CF)
0B6C-   D3          ???
0B6D-   A9 20       LDA   #$20
0B6F-   AA          TAX
0B70-   8D AA AC    STA   $ACAA
0B73-   AC AC AC    LDY   $ACAC
0B76-   AC AC AC    LDY   $ACAC
0B79-   AC AC AC    LDY   $ACAC
0B7C-   AC AC AC    LDY   $ACAC
0B7F-   AC AC AC    LDY   $ACAC
0B82-   AC AC AC    LDY   $ACAC
0B85-   AC AC AC    LDY   $ACAC
0B88-   AC AC AC    LDY   $ACAC
0B8B-   AC AC AC    LDY   $ACAC
0B8E-   AC AC AA    LDY   $AAAC
0B91-   8D AA 8D    STA   $8DAA
0B94-   A0 D0       LDY   #$D0
0B96-   D5 D4       CMP   $D4,X
0B98-   A0 CD       LDY   #$CD
0B9A-   C9 CE       CMP   #$CE
0B9C-   AE D6 C1    LDX   $C1D6
0B9F-   D2 D3       CMP   ($D3)
0BA1-   AE D2 C5    LDX   $C5D2
0BA4-   D1 D5       CMP   ($D5),Y
0BA6-   C9 D2       CMP   #$D2
0BA8-   C5 C4       CMP   $C4
0BAA-   8D A0 D0    STA   $D0A0
0BAD-   D5 D4       CMP   $D4,X
0BAF-   A0 CD       LDY   #$CD
0BB1-   C9 CE       CMP   #$CE
0BB3-   AE C8 CF    LDX   $CFC8
0BB6-   CF          ???
0BB7-   CB          ???
0BB8-   D3          ???
0BB9-   AE D2 C5    LDX   $C5D2
0BBC-   D1 D5       CMP   ($D5),Y
0BBE-   C9 D2       CMP   #$D2
0BC0-   C5 C4       CMP   $C4
0BC2-   8D A0 D5    STA   $D5A0
0BC5-   D3          ???
0BC6-   C5 A0       CMP   $A0
0BC8-   CD C9 CE    CMP   $CEC9
0BCB-   AE CD C1    LDX   $C1CD
0BCE-   C3          ???
0BCF-   AE D2 C5    LDX   $C5D2
0BD2-   D1 D5       CMP   ($D5),Y
0BD4-   C9 D2       CMP   #$D2
0BD6-   C5 C4       CMP   $C4
0BD8-   8D A0 D5    STA   $D5A0
0BDB-   D3          ???
0BDC-   C5 A0       CMP   $A0
0BDE-   CD C9 CE    CMP   $CEC9
0BE1-   AE CD C1    LDX   $C1CD
0BE4-   C3          ???
0BE5-   AE C1 D2    LDX   $D2C1
0BE8-   D2 C1       CMP   ($C1)
0BEA-   D9 D3 8D    CMP   $8DD3,Y
0BED-   A0 D0       LDY   #$D0
0BEF-   D5 D4       CMP   $D4,X
0BF1-   A0 CD       LDY   #$CD
0BF3-   C9 CE       CMP   #$CE
0BF5-   AE C8 CF    LDX   $CFC8
0BF8-   CF          ???
0BF9-   CB          ???
0BFA-   D3          ???
0BFB-   AE C1 D2    LDX   $D2C1
0BFE-   D2 C1       CMP   ($C1)
0C00-   D9 D3 8D    CMP   $8DD3,Y
0C03-   AA          TAX
0C04-   8D AA E0    STA   $E0AA
0C07-   E0 E0       CPX   #$E0
0C09-   E0 E0       CPX   #$E0
0C0B-   E0 E0       CPX   #$E0
0C0D-   E0 E0       CPX   #$E0
0C0F-   E0 E0       CPX   #$E0
0C11-   E0 E0       CPX   #$E0
0C13-   E0 E0       CPX   #$E0
0C15-   E0 E0       CPX   #$E0
0C17-   E0 E0       CPX   #$E0
0C19-   E0 E0       CPX   #$E0
0C1B-   E0 E0       CPX   #$E0
0C1D-   E0 E0       CPX   #$E0
0C1F-   E0 E0       CPX   #$E0
0C21-   E0 E0       CPX   #$E0
0C23-   E0 AA       CPX   #$AA
0C25-   8D AA 20    STA   $20AA
0C28-   20 20 20    JSR   $2020
0C2B-   20 20 D0    JSR   $D020
0C2E-   D2 CF       CMP   ($CF)
0C30-   C7          ???
0C31-   D2 C1       CMP   ($C1)
0C33-   CD 20 CD    CMP   $CD20
0C36-   C1 C9       CMP   ($C9,X)
0C38-   CE 20 C2    DEC   $C220
0C3B-   CF          ???
0C3C-   C4 D9       CPY   $D9
0C3E-   20 20 20    JSR   $2020
0C41-   20 20 20    JSR   $2020
0C44-   20 AA 8D    JSR   $8DAA
0C47-   AA          TAX
0C48-   AC AC AC    LDY   $ACAC
0C4B-   AC AC AC    LDY   $ACAC
0C4E-   AC AC AC    LDY   $ACAC
0C51-   AC AC AC    LDY   $ACAC
0C54-   AC AC AC    LDY   $ACAC
0C57-   AC AC AC    LDY   $ACAC
0C5A-   AC AC AC    LDY   $ACAC
0C5D-   AC AC AC    LDY   $ACAC
0C60-   AC AC AC    LDY   $ACAC
0C63-   AC AC AC    LDY   $ACAC
0C66-   AA          TAX
0C67-   8D AA 8D    STA   $8DAA
0C6A-   C1 D2       CMP   ($D2,X)
0C6C-   D2 C1       CMP   ($C1)
0C6E-   D9 B1 A0    CMP   $A0B1,Y
0C71-   C5 D1       CMP   $D1
0C73-   D5 A0       CMP   $A0,X
0C75-   A4 B3       LDY   $B3
0C77-   B0 B0       BCS   $0C29
0C79-   8D C1 D2    STA   $D2C1
0C7C-   D2 C1       CMP   ($C1)
0C7E-   D9 B2 A0    CMP   $A0B2,Y
0C81-   C5 D1       CMP   $D1
0C83-   D5 A0       CMP   $A0,X
0C85-   A4 B4       LDY   $B4
0C87-   B0 B0       BCS   $0C39
0C89-   B0 8D       BCS   $0C18
0C8B-   AA          TAX
0C8C-   8D AA AA    STA   $AAAA
0C8F-   20 C4 C9    JSR   $C9C4
0C92-   CD B8 B1    CMP   $B1B8
0C95-   20 C3 CC    JSR   $CCC3
0C98-   C5 C1       CMP   $C1
0C9A-   D2 D3       CMP   ($D3)
0C9C-   20 D4 C8    JSR   $C8D4
0C9F-   C5 20       CMP   $20
0CA1-   CD C5 CD    CMP   $CDC5
0CA4-   CF          ???
0CA5-   D2 D9       CMP   ($D9)
0CA7-   20 C1 D4    JSR   $D4C1
0CAA-   20 D4 C8    JSR   $C8D4
0CAD-   C5 20       CMP   $20
0CAF-   D3          ???
0CB0-   D0 C5       BNE   $0C77
0CB2-   C3          ???
0CB3-   C9 C6       CMP   #$C6
0CB5-   C9 C5       CMP   #$C5
0CB7-   C4 8D       CPY   $8D
0CB9-   AA          TAX
0CBA-   AA          TAX
0CBB-   20 CC CF    JSR   $CFCC
0CBE-   C3          ???
0CBF-   C1 D4       CMP   ($D4,X)
0CC1-   C9 CF       CMP   #$CF
0CC3-   CE 20 C1    DEC   $C120
0CC6-   CE C4 20    DEC   $20C4
0CC9-   D3          ???
0CCA-   C5 D4       CMP   $D4
0CCC-   D3          ???
0CCD-   20 D5 D0    JSR   $D0D5
0CD0-   20 D4 C8    JSR   $C8D4
0CD3-   C5 20       CMP   $20
0CD5-   C4 C1       CPY   $C1
0CD7-   D4          ???
0CD8-   C1 20       CMP   ($20,X)
0CDA-   C3          ???
0CDB-   CF          ???
0CDC-   CE C6 C9    DEC   $C9C6
0CDF-   C7          ???
0CE0-   D5 D2       CMP   $D2,X
0CE2-   C1 D4       CMP   ($D4,X)
0CE4-   C9 CF       CMP   #$CF
0CE6-   CE 8D AA    DEC   $AA8D
0CE9-   AA          TAX
0CEA-   20 C6 CF    JSR   $CFC6
0CED-   D2 20       CMP   ($20)
0CEF-   C1 20       CMP   ($20,X)
0CF1-   B1 C4       LDA   ($C4),Y
0CF3-   20 C1 D2    JSR   $D2C1
0CF6-   D2 C1       CMP   ($C1)
0CF8-   D9 20 A8    CMP   $A820,Y
0CFB-   C1 D2       CMP   ($D2,X)
0CFD-   D2 C1       CMP   ($C1)
0CFF-   D9 20 CC    CMP   $CC20,Y
0D02-   C5 CE       CMP   $CE
0D04-   C7          ???
0D05-   D4          ???
0D06-   C8          INY
0D07-   AC 20 C5    LDY   $C520
0D0A-   CC C5 CD    CPY   $CDC5
0D0D-   C5 CE       CMP   $CE
0D0F-   D4          ???
0D10-   20 CC C5    JSR   $C5CC
0D13-   CE C7 D4    DEC   $D4C7
0D16-   C8          INY
0D17-   AC 20 C4    LDY   $C420
0D1A-   C1 D4       CMP   ($D4,X)
0D1C-   C1 A9       CMP   ($A9,X)
0D1E-   8D AA 8D    STA   $8DAA
0D21-   AA          TAX
0D22-   AA          TAX
0D23-   20 CD C1    JSR   $C1CD
0D26-   C3          ???
0D27-   D2 CF       CMP   ($CF)
0D29-   BA          TSX
0D2A-   20 C4 C9    JSR   $C9C4
0D2D-   CD B8 B1    CMP   $B1B8
0D30-   20 C1 C4    JSR   $C4C1
0D33-   C4 D2       CPY   $D2
0D35-   C5 D3       CMP   $D3
0D37-   D3          ???
0D38-   BB          ???
0D39-   C1 D2       CMP   ($D2,X)
0D3B-   D2 C1       CMP   ($C1)
0D3D-   D9 DF D3    CMP   $D3DF,Y
0D40-   C9 DA       CMP   #$DA
0D42-   C5 BB       CMP   $BB
0D44-   C5 CC       CMP   $CC
0D46-   C5 CD       CMP   $CD
0D48-   C5 CE       CMP   $CE
0D4A-   D4          ???
0D4B-   DF          ???
0D4C-   CC C5 CE    CPY   $CEC5
0D4F-   C7          ???
0D50-   D4          ???
0D51-   C8          INY
0D52-   BB          ???
0D53-   C6 C9       DEC   $C9
0D55-   CC CC DF    CPY   $DFCC
0D58-   D6 C1       DEC   $C1,X
0D5A-   CC 8D AA    CPY   $AA8D
0D5D-   8D AA AA    STA   $AAAA
0D60-   20 CE CF    JSR   $CFCE
0D63-   D4          ???
0D64-   C5 20       CMP   $20
0D66-   D4          ???
0D67-   C8          INY
0D68-   C1 D4       CMP   ($D4,X)
0D6A-   20 C9 CE    JSR   $CEC9
0D6D-   C4 C5       CPY   $C5
0D6F-   D8          CLD
0D70-   C9 CE       CMP   #$CE
0D72-   C7          ???
0D73-   20 D3 D4    JSR   $D4D3
0D76-   C1 D2       CMP   ($D2,X)
0D78-   D4          ???
0D79-   D3          ???
0D7A-   20 C1 D4    JSR   $D4C1
0D7D-   20 B0 AC    JSR   $ACB0
0D80-   20 D3 CF    JSR   $CFD3
0D83-   20 C1 CE    JSR   $CEC1
0D86-   20 C1 D2    JSR   $D2C1
0D89-   D2 C1       CMP   ($C1)
0D8B-   D9 8D AA    CMP   $AA8D,Y
0D8E-   AA          TAX
0D8F-   20 CF C6    JSR   $C6CF
0D92-   20 D4 C5    JSR   $C5D4
0D95-   CE 20 C5    DEC   $C520
0D98-   CC C5 CD    CPY   $CDC5
0D9B-   C5 CE       CMP   $CE
0D9D-   D4          ???
0D9E-   D3          ???
0D9F-   20 D7 CF    JSR   $CFD7
0DA2-   D5 CC       CMP   $CC,X
0DA4-   C4 20       CPY   $20
0DA6-   C2          ???
0DA7-   C5 20       CMP   $20
0DA9-   CC C9 D3    CPY   $D3C9
0DAC-   D4          ???
0DAD-   C5 C4       CMP   $C4
0DAF-   20 C1 D3    JSR   $D3C1
0DB2-   20 B0 AE    JSR   $AEB0
0DB5-   AE B9 8D    LDX   $8DB9
0DB8-   AA          TAX
0DB9-   8D A0 DF    STA   $DFA0
0DBC-   D0 D2       BNE   $0D90
0DBE-   CE D4 A0    DEC   $A0D4
0DC1-   A2 20       LDX   #$20
0DC3-   A2 AC       LDX   #$AC
0DC5-   B8          CLV
0DC6-   C4 B8       CPY   $B8
0DC8-   C4 8D       CPY   $8D
0DCA-   A0 DF       LDY   #$DF
0DCC-   D0 D2       BNE   $0DA0
0DCE-   CE D4 A0    DEC   $A0D4
0DD1-   A2 D4       LDX   #$D4
0DD3-   C8          INY
0DD4-   C5 20       CMP   $20
0DD6-   C4 C9       CPY   $C9
0DD8-   CD B8 B1    CMP   $B1B8
0DDB-   20 CD C1    JSR   $C1CD
0DDE-   C3          ???
0DDF-   D2 CF       CMP   ($CF)
0DE1-   20 D3 C9    JSR   $C9D3
0DE4-   CD D0 CC    CMP   $CCD0
0DE7-   D9 20 D3    CMP   $D320,Y
0DEA-   C5 D4       CMP   $D4
0DEC-   D3          ???
0DED-   A2 AC       LDX   #$AC
0DEF-   B8          CLV
0DF0-   C4 8D       CPY   $8D
0DF2-   A0 DF       LDY   #$DF
0DF4-   D0 D2       BNE   $0DC8
0DF6-   CE D4 A0    DEC   $A0D4
0DF9-   A2 D5       LDX   #$D5
0DFB-   D0 20       BNE   $0E1D
0DFD-   C1 20       CMP   ($20,X)
0DFF-   CF          ???
0E00-   CE C5 AD    DEC   $ADC5
0E03-   C4 C9       CPY   $C9
0E05-   CD C5 CE    CMP   $CEC5
0E08-   D3          ???
0E09-   C9 CF       CMP   #$CF
0E0B-   CE C1 CC    DEC   $CCC1
0E0E-   20 C1 D2    JSR   $D2C1
0E11-   D2 C1       CMP   ($C1)
0E13-   D9 20 CF    CMP   $CF20,Y
0E16-   C6 A2       DEC   $A2
0E18-   AC B8 C4    LDY   $C4B8
0E1B-   8D A0 DF    STA   $DFA0
0E1E-   D0 D2       BNE   $0DF2
0E20-   CE D4 A0    DEC   $A0D4
0E23-   A2 D4       LDX   #$D4
0E25-   C8          INY
0E26-   C5 20       CMP   $20
0E28-   C7          ???
0E29-   C9 D6       CMP   #$D6
0E2B-   C5 CE       CMP   $CE
0E2D-   20 D3 C9    JSR   $C9D3
0E30-   DA          PHX
0E31-   C5 20       CMP   $20
0E33-   D7          ???
0E34-   C9 D4       CMP   #$D4
0E36-   C8          INY
0E37-   20 C5 CC    JSR   $CCC5
0E3A-   C5 CD       CMP   $CD
0E3C-   C5 CE       CMP   $CE
0E3E-   D4          ???
0E3F-   D3          ???
0E40-   20 CF C6    JSR   $C6CF
0E43-   A2 AC       LDX   #$AC
0E45-   B8          CLV
0E46-   C4 8D       CPY   $8D
0E48-   A0 DF       LDY   #$DF
0E4A-   D0 D2       BNE   $0E1E
0E4C-   CE D4 A0    DEC   $A0D4
0E4F-   A2 C1       LDX   #$C1
0E51-   20 C7 C9    JSR   $C9C7
0E54-   D6 C5       DEC   $C5,X
0E56-   CE 20 CC    DEC   $CC20
0E59-   C5 CE       CMP   $CE
0E5B-   C7          ???
0E5C-   D4          ???
0E5D-   C8          INY
0E5E-   AE A2 AC    LDX   $ACA2
0E61-   B8          CLV
0E62-   C4 B8       CPY   $B8
0E64-   C4 8D       CPY   $8D
0E66-   A0 DF       LDY   #$DF
0E68-   D0 D2       BNE   $0E3C
0E6A-   CE D4 A0    DEC   $A0D4
0E6D-   A2 C4       LDX   #$C4
0E6F-   C9 CD       CMP   #$CD
0E71-   B8          CLV
0E72-   B1 20       LDA   ($20),Y
0E74-   A3          ???
0E75-   C1 D2       CMP   ($D2,X)
0E77-   D2 C1       CMP   ($C1)
0E79-   D9 B1 BB    CMP   $BBB1,Y
0E7C-   A3          ???
0E7D-   B1 B0       LDA   ($B0),Y
0E7F-   BB          ???
0E80-   A3          ???
0E81-   B1 BB       LDA   ($BB),Y
0E83-   A3          ???
0E84-   A4 C1       LDY   $C1
0E86-   C1 20       CMP   ($20,X)
0E88-   D2 C5       CMP   ($C5)
0E8A-   D4          ???
0E8B-   D5 D2       CMP   $D2,X
0E8D-   CE D3 BA    DEC   $BAD3
0E90-   A2 AC       LDX   #$AC
0E92-   B8          CLV
0E93-   C4 B8       CPY   $B8
0E95-   C4 8D       CPY   $8D
0E97-   A0 C4       LDY   #$C4
0E99-   C9 CD       CMP   #$CD
0E9B-   B8          CLV
0E9C-   B1 A0       LDA   ($A0),Y
0E9E-   A3          ???
0E9F-   C1 D2       CMP   ($D2,X)
0EA1-   D2 C1       CMP   ($C1)
0EA3-   D9 B1 BB    CMP   $BBB1,Y
0EA6-   A3          ???
0EA7-   B1 B0       LDA   ($B0),Y
0EA9-   BB          ???
0EAA-   A3          ???
0EAB-   B1 BB       LDA   ($BB),Y
0EAD-   A3          ???
0EAE-   A4 C1       LDY   $C1
0EB0-   C1 8D       CMP   ($8D,X)
0EB2-   A0 C4       LDY   #$C4
0EB4-   D5 CD       CMP   $CD,X
0EB6-   D0 A0       BNE   $0E58
0EB8-   A3          ???
0EB9-   C1 D2       CMP   ($D2,X)
0EBB-   D2 C1       CMP   ($C1)
0EBD-   D9 B1 BB    CMP   $BBB1,Y
0EC0-   A3          ???
0EC1-   B2 8D       LDA   ($8D)
0EC3-   A0 C4       LDY   #$C4
0EC5-   D5 CD       CMP   $CD,X
0EC7-   D0 A0       BNE   $0E69
0EC9-   A3          ???
0ECA-   C1 D2       CMP   ($D2,X)
0ECC-   D2 C1       CMP   ($C1)
0ECE-   D9 B1 AB    CMP   $ABB1,Y
0ED1-   B2 BB       LDA   ($BB)
0ED3-   A3          ???
0ED4-   B5 8D       LDA   $8D,X
0ED6-   A0 C4       LDY   #$C4
0ED8-   D5 CD       CMP   $CD,X
0EDA-   D0 A0       BNE   $0E7C
0EDC-   A3          ???
0EDD-   C1 D2       CMP   ($D2,X)
0EDF-   D2 C1       CMP   ($C1)
0EE1-   D9 B1 AB    CMP   $ABB1,Y
0EE4-   B7          ???
0EE5-   BB          ???
0EE6-   A3          ???
0EE7-   B5 8D       LDA   $8D,X
0EE9-   A0 DF       LDY   #$DF
0EEB-   D0 D2       BNE   $0EBF
0EED-   CE D4 A0    DEC   $A0D4
0EF0-   A2 20       LDX   #$20
0EF2-   A2 AC       LDX   #$AC
0EF4-   B8          CLV
0EF5-   C4 B8       CPY   $B8
0EF7-   C4 8D       CPY   $8D
0EF9-   A0 DF       LDY   #$DF
0EFB-   D7          ???
0EFC-   C1 C9       CMP   ($C9,X)
0EFE-   D4          ???
0EFF-   8D AA 8D    STA   $8DAA
0F02-   AA          TAX
0F03-   AA          TAX
0F04-   20 D0 D5    JSR   $D5D0
0F07-   D4          ???
0F08-   B8          CLV
0F09-   B1 20       LDA   ($20),Y
0F0B-   D0 D5       BNE   $0EE2
0F0D-   D4          ???
0F0E-   D3          ???
0F0F-   20 D4 C8    JSR   $C8D4
0F12-   C5 20       CMP   $20
0F14-   D6 C1       DEC   $C1,X
0F16-   CC D5 C5    CPY   $C5D5
0F19-   20 C1 D4    JSR   $D4C1
0F1C-   20 C1 20    JSR   $20C1
0F1F-   D3          ???
0F20-   D0 C5       BNE   $0EE7
0F22-   C3          ???
0F23-   C9 C6       CMP   #$C6
0F25-   C9 C5       CMP   #$C5
0F27-   C4 20       CPY   $20
0F29-   C1 C4       CMP   ($C4,X)
0F2B-   C4 D2       CPY   $D2
0F2D-   C5 D3       CMP   $D3
0F2F-   D3          ???
0F30-   8D AA AA    STA   $AAAA
0F33-   20 C9 CE    JSR   $CEC9
0F36-   D4          ???
0F37-   CF          ???
0F38-   20 D4 C8    JSR   $C8D4
0F3B-   C5 20       CMP   $20
0F3D-   C1 D2       CMP   ($D2,X)
0F3F-   D2 C1       CMP   ($C1)
0F41-   D9 20 C1    CMP   $C120,Y
0F44-   D4          ???
0F45-   20 D4 C8    JSR   $C8D4
0F48-   C5 20       CMP   $20
0F4A-   D3          ???
0F4B-   D0 C5       BNE   $0F12
0F4D-   C3          ???
0F4E-   C9 C6       CMP   #$C6
0F50-   C9 C5       CMP   #$C5
0F52-   C4 20       CPY   $20
0F54-   C9 CE       CMP   #$CE
0F56-   C4 C5       CPY   $C5
0F58-   D8          CLD
0F59-   AE 8D AA    LDX   $AA8D
0F5C-   8D AA AA    STA   $AAAA
0F5F-   20 CD C1    JSR   $C1CD
0F62-   C3          ???
0F63-   D2 CF       CMP   ($CF)
0F65-   BA          TSX
0F66-   20 D0 D5    JSR   $D5D0
0F69-   D4          ???
0F6A-   B8          CLV
0F6B-   B1 20       LDA   ($20),Y
0F6D-   D3          ???
0F6E-   D2 C3       CMP   ($C3)
0F70-   DF          ???
0F71-   C1 C4       CMP   ($C4,X)
0F73-   C4 D2       CPY   $D2
0F75-   BB          ???
0F76-   C4 C5       CPY   $C5
0F78-   D3          ???
0F79-   D4          ???
0F7A-   DF          ???
0F7B-   C1 D2       CMP   ($D2,X)
0F7D-   D2 C1       CMP   ($C1)
0F7F-   D9 BB C9    CMP   $C9BB,Y
0F82-   CE C4 C5    DEC   $C5C4
0F85-   D8          CLD
0F86-   8D AA 8D    STA   $8DAA
0F89-   A0 DF       LDY   #$DF
0F8B-   D0 D2       BNE   $0F5F
0F8D-   CE D4 A0    DEC   $A0D4
0F90-   A2 D4       LDX   #$D4
0F92-   C8          INY
0F93-   C5 20       CMP   $20
0F95-   D0 D5       BNE   $0F6C
0F97-   D4          ???
0F98-   B8          CLV
0F99-   B1 20       LDA   ($20),Y
0F9B-   CD C1 C3    CMP   $C3C1
0F9E-   D2 CF       CMP   ($CF)
0FA0-   20 D0 D5    JSR   $D5D0
0FA3-   D4          ???
0FA4-   D3          ???
0FA5-   20 D4 C8    JSR   $C8D4
0FA8-   C5 20       CMP   $20
0FAA-   D6 C1       DEC   $C1,X
0FAC-   CC D5 C5    CPY   $C5D5
0FAF-   20 C6 CF    JSR   $CFC6
0FB2-   D5 CE       CMP   $CE,X
0FB4-   C4 A2       CPY   $A2
0FB6-   AC B8 C4    LDY   $C4B8
0FB9-   8D A0 DF    STA   $DFA0
0FBC-   D0 D2       BNE   $0F90
0FBE-   CE D4 A0    DEC   $A0D4
0FC1-   A2 C1       LDX   #$C1
0FC3-   D4          ???
0FC4-   20 D4 C8    JSR   $C8D4
0FC7-   C5 20       CMP   $20
0FC9-   D3          ???
0FCA-   D0 C5       BNE   $0F91
0FCC-   C3          ???
0FCD-   C9 C6       CMP   #$C6
0FCF-   C9 C5       CMP   #$C5
0FD1-   C4 20       CPY   $20
0FD3-   C1 C4       CMP   ($C4,X)
0FD5-   C4 D2       CPY   $D2
0FD7-   C5 D3       CMP   $D3
0FD9-   D3          ???
0FDA-   20 C1 CE    JSR   $CEC1
0FDD-   C4 20       CPY   $20
0FDF-   D4          ???
0FE0-   C8          INY
0FE1-   C5 CE       CMP   $CE
0FE3-   A2 AC       LDX   #$AC
0FE5-   B8          CLV
0FE6-   C4 8D       CPY   $8D
0FE8-   A0 DF       LDY   #$DF
0FEA-   D0 D2       BNE   $0FBE
0FEC-   CE D4 A0    DEC   $A0D4
0FEF-   A2 C9       LDX   #$C9
0FF1-   CE D3 C5    DEC   $C5D3
0FF4-   D2 D4       CMP   ($D4)
0FF6-   D3          ???
0FF7-   20 C9 D4    JSR   $D4C9
0FFA-   20 C9 CE    JSR   $CEC9
0FFD-   D4          ???
0FFE-   CF          ???
0FFF-   20 D4 C8    JSR   $C8D4
1002-   C5 20       CMP   $20
1004-   C7          ???
1005-   C9 D6       CMP   #$D6
1007-   C5 CE       CMP   $CE
1009-   20 C1 D2    JSR   $D2C1
100C-   D2 C1       CMP   ($C1)
100E-   D9 20 C1    CMP   $C120,Y
1011-   CE C4 A2    DEC   $A2C4
1014-   AC B8 C4    LDY   $C4B8
1017-   8D A0 DF    STA   $DFA0
101A-   D0 D2       BNE   $0FEE
101C-   CE D4 A0    DEC   $A0D4
101F-   A2 C9       LDX   #$C9
1021-   CE C4 C5    DEC   $C5C4
1024-   D8          CLD
1025-   AE A2 AC    LDX   $ACA2
1028-   B8          CLV
1029-   C4 B8       CPY   $B8
102B-   C4 8D       CPY   $8D
102D-   A0 DF       LDY   #$DF
102F-   D0 D2       BNE   $1003
1031-   CE D4 A0    DEC   $A0D4
1034-   A2 D3       LDX   #$D3
1036-   CF          ???
1037-   AC 20 D0    LDY   $D020
103A-   D5 D4       CMP   $D4,X
103C-   B8          CLV
103D-   B1 20       LDA   ($20),Y
103F-   A3          ???
1040-   A4 B3       LDY   $B3
1042-   B2 B0       LDA   ($B0)
1044-   BB          ???
1045-   A3          ???
1046-   C1 D2       CMP   ($D2,X)
1048-   D2 C1       CMP   ($C1)
104A-   D9 B1 BB    CMP   $BBB1,Y
104D-   A3          ???
104E-   B1 20       LDA   ($20),Y
1050-   C1 CE       CMP   ($CE,X)
1052-   C4 20       CPY   $20
1054-   A2 AC       LDX   #$AC
1056-   B8          CLV
1057-   C4 8D       CPY   $8D
1059-   A0 DF       LDY   #$DF
105B-   D0 D2       BNE   $102F
105D-   CE D4 A0    DEC   $A0D4
1060-   A2 D0       LDX   #$D0
1062-   D5 D4       CMP   $D4,X
1064-   B8          CLV
1065-   B1 20       LDA   ($20),Y
1067-   A3          ???
1068-   A4 B3       LDY   $B3
106A-   B2 B1       LDA   ($B1)
106C-   BB          ???
106D-   A3          ???
106E-   C1 D2       CMP   ($D2,X)
1070-   D2 C1       CMP   ($C1)
1072-   D9 B1 BB    CMP   $BBB1,Y
1075-   A3          ???
1076-   B2 20       LDA   ($20)
1078-   D2 C5       CMP   ($C5)
107A-   D3          ???
107B-   D5 CC       CMP   $CC,X
107D-   D4          ???
107E-   D3          ???
107F-   20 C9 CE    JSR   $CEC9
1082-   BA          TSX
1083-   20 A2 AC    JSR   $ACA2
1086-   B8          CLV
1087-   C4 B8       CPY   $B8
1089-   C4 8D       CPY   $8D
108B-   A0 CC       LDY   #$CC
108D-   C4 C1       CPY   $C1
108F-   A0 A3       LDY   #$A3
1091-   A4 C2       LDY   $C2
1093-   C2          ???
1094-   8D A0 D3    STA   $D3A0
1097-   D4          ???
1098-   C1 A0       CMP   ($A0,X)
109A-   A4 B3       LDY   $B3
109C-   B2 B0       LDA   ($B0)
109E-   8D A0 CC    STA   $CCA0
10A1-   C4 C1       CPY   $C1
10A3-   A0 A3       LDY   #$A3
10A5-   A4 C3       LDY   $C3
10A7-   C3          ???
10A8-   8D A0 D3    STA   $D3A0
10AB-   D4          ???
10AC-   C1 A0       CMP   ($A0,X)
10AE-   A4 B3       LDY   $B3
10B0-   B2 B1       LDA   ($B1)
10B2-   8D A0 D0    STA   $D0A0
10B5-   D5 D4       CMP   $D4,X
10B7-   B8          CLV
10B8-   B1 A0       LDA   ($A0),Y
10BA-   A3          ???
10BB-   A4 B3       LDY   $B3
10BD-   B2 B0       LDA   ($B0)
10BF-   BB          ???
10C0-   A3          ???
10C1-   C1 D2       CMP   ($D2,X)
10C3-   D2 C1       CMP   ($C1)
10C5-   D9 B1 BB    CMP   $BBB1,Y
10C8-   A3          ???
10C9-   B1 8D       LDA   ($8D),Y
10CB-   A0 D0       LDY   #$D0
10CD-   D5 D4       CMP   $D4,X
10CF-   B8          CLV
10D0-   B1 A0       LDA   ($A0),Y
10D2-   A3          ???
10D3-   A4 B3       LDY   $B3
10D5-   B2 B1       LDA   ($B1)
10D7-   BB          ???
10D8-   A3          ???
10D9-   C1 D2       CMP   ($D2,X)
10DB-   D2 C1       CMP   ($C1)
10DD-   D9 B1 BB    CMP   $BBB1,Y
10E0-   A3          ???
10E1-   B2 8D       LDA   ($8D)
10E3-   A0 C4       LDY   #$C4
10E5-   D5 CD       CMP   $CD,X
10E7-   D0 A0       BNE   $1089
10E9-   A3          ???
10EA-   C1 D2       CMP   ($D2,X)
10EC-   D2 C1       CMP   ($C1)
10EE-   D9 B1 BB    CMP   $BBB1,Y
10F1-   A3          ???
10F2-   B2 8D       LDA   ($8D)
10F4-   A0 C4       LDY   #$C4
10F6-   D5 CD       CMP   $CD,X
10F8-   D0 A0       BNE   $109A
10FA-   A3          ???
10FB-   C1 D2       CMP   ($D2,X)
10FD-   D2 C1       CMP   ($C1)
10FF-   D9 B1 AB    CMP   $ABB1,Y
1102-   B2 BB       LDA   ($BB)
1104-   A3          ???
1105-   B5 8D       LDA   $8D,X
1107-   A0 C4       LDY   #$C4
1109-   D5 CD       CMP   $CD,X
110B-   D0 A0       BNE   $10AD
110D-   A3          ???
110E-   C1 D2       CMP   ($D2,X)
1110-   D2 C1       CMP   ($C1)
1112-   D9 B1 AB    CMP   $ABB1,Y
1115-   B7          ???
1116-   BB          ???
1117-   A3          ???
1118-   B5 8D       LDA   $8D,X
111A-   A0 DF       LDY   #$DF
111C-   D0 D2       BNE   $10F0
111E-   CE D4 A0    DEC   $A0D4
1121-   A2 20       LDX   #$20
1123-   A2 AC       LDX   #$AC
1125-   B8          CLV
1126-   C4 B8       CPY   $B8
1128-   C4 8D       CPY   $8D
112A-   A0 DF       LDY   #$DF
112C-   D7          ???
112D-   C1 C9       CMP   ($C9,X)
112F-   D4          ???
1130-   8D AA 8D    STA   $8DAA
1133-   A0 DF       LDY   #$DF
1135-   D0 D2       BNE   $1109
1137-   CE D4 A0    DEC   $A0D4
113A-   A2 CE       LDX   #$CE
113C-   CF          ???
113D-   D4          ???
113E-   C5 20       CMP   $20
1140-   D4          ???
1141-   C8          INY
1142-   C1 D4       CMP   ($D4,X)
1144-   20 C9 C6    JSR   $C6C9
1147-   20 D9 CF    JSR   $CFD9
114A-   D5 D2       CMP   $D2,X
114C-   20 C5 CC    JSR   $CCC5
114F-   C5 CD       CMP   $CD
1151-   C5 CE       CMP   $CE
1153-   D4          ???
1154-   20 D3 C9    JSR   $C9D3
1157-   DA          PHX
1158-   C5 A2       CMP   $A2
115A-   AC B8 C4    LDY   $C4B8
115D-   8D A0 DF    STA   $DFA0
1160-   D0 D2       BNE   $1134
1162-   CE D4 A0    DEC   $A0D4
1165-   A2 C9       LDX   #$C9
1167-   D3          ???
1168-   20 CF CE    JSR   $CECF
116B-   C5 20       CMP   $20
116D-   C2          ???
116E-   D9 D4 C5    CMP   $C5D4,Y
1171-   AE CF CE    LDX   $CECF
1174-   CC D9 20    CPY   $20D9
1177-   CF          ???
1178-   CE C5 20    DEC   $20C5
117B-   C2          ???
117C-   D9 D4 C5    CMP   $C5D4,Y
117F-   20 C9 D3    JSR   $D3C9
1182-   20 C3 CF    JSR   $CFC3
1185-   D0 C9       BNE   $1150
1187-   C5 C4       CMP   $C4
1189-   BB          ???
118A-   A2 AC       LDX   #$AC
118C-   B8          CLV
118D-   C4 8D       CPY   $8D
118F-   A0 DF       LDY   #$DF
1191-   D0 D2       BNE   $1165
1193-   CE D4 A0    DEC   $A0D4
1196-   A2 C9       LDX   #$C9
1198-   C6 20       DEC   $20
119A-   D4          ???
119B-   D7          ???
119C-   CF          ???
119D-   20 C2 D9    JSR   $D9C2
11A0-   D4          ???
11A1-   C5 D3       CMP   $D3
11A3-   AC 20 D4    LDY   $D420
11A6-   C8          INY
11A7-   C5 CE       CMP   $CE
11A9-   20 D4 D7    JSR   $D7D4
11AC-   CF          ???
11AD-   20 C1 D2    JSR   $D2C1
11B0-   C5 20       CMP   $20
11B2-   C3          ???
11B3-   CF          ???
11B4-   D0 C9       BNE   $117F
11B6-   C5 C4       CMP   $C4
11B8-   AC A2 AC    LDY   $ACA2
11BB-   B8          CLV
11BC-   C4 8D       CPY   $8D
11BE-   A0 DF       LDY   #$DF
11C0-   D0 D2       BNE   $1194
11C2-   CE D4 A0    DEC   $A0D4
11C5-   A2 C1       LDX   #$C1
11C7-   CE C4 20    DEC   $20C4
11CA-   D3          ???
11CB-   CF          ???
11CC-   20 CF CE    JSR   $CECF
11CF-   AE 20 D4    LDX   $D420
11D2-   C8          INY
11D3-   D5 D3       CMP   $D3,X
11D5-   20 D4 C8    JSR   $C8D4
11D8-   C5 20       CMP   $20
11DA-   C6 CF       DEC   $CF
11DC-   CC CC CF    CPY   $CFCC
11DF-   D7          ???
11E0-   C9 CE       CMP   #$CE
11E2-   C7          ???
11E3-   BA          TSX
11E4-   A2 AC       LDX   #$AC
11E6-   B8          CLV
11E7-   C4 B8       CPY   $B8
11E9-   C4 8D       CPY   $8D
11EB-   A0 DF       LDY   #$DF
11ED-   D0 D2       BNE   $11C1
11EF-   CE D4 A0    DEC   $A0D4
11F2-   A2 C4       LDX   #$C4
11F4-   C9 CD       CMP   #$CD
11F6-   B8          CLV
11F7-   B1 20       LDA   ($20),Y
11F9-   C1 D2       CMP   ($D2,X)
11FB-   D2 C1       CMP   ($C1)
11FD-   D9 B2 BB    CMP   $BBB2,Y
1200-   A3          ???
1201-   B1 B0       LDA   ($B0),Y
1203-   BB          ???
1204-   A3          ???
1205-   B2 BB       LDA   ($BB)
1207-   A3          ???
1208-   A4 C5       LDY   $C5
120A-   C5 A2       CMP   $A2
120C-   AC B8 C4    LDY   $C4B8
120F-   8D A0 DF    STA   $DFA0
1212-   D0 D2       BNE   $11E6
1214-   CE D4 A0    DEC   $A0D4
1217-   A2 D0       LDX   #$D0
1219-   D5 D4       CMP   $D4,X
121B-   B8          CLV
121C-   B1 20       LDA   ($20),Y
121E-   A4 B3       LDY   $B3
1220-   B2 B0       LDA   ($B0)
1222-   BB          ???
1223-   C1 D2       CMP   ($D2,X)
1225-   D2 C1       CMP   ($C1)
1227-   D9 B2 BB    CMP   $BBB2,Y
122A-   A3          ???
122B-   B8          CLV
122C-   A2 AC       LDX   #$AC
122E-   B8          CLV
122F-   C4 B8       CPY   $B8
1231-   C4 8D       CPY   $8D
1233-   A0 DF       LDY   #$DF
1235-   D0 D2       BNE   $1209
1237-   CE D4 A0    DEC   $A0D4
123A-   A2 D2       LDX   #$D2
123C-   C5 D3       CMP   $D3
123E-   D5 CC       CMP   $CC,X
1240-   D4          ???
1241-   D3          ???
1242-   20 C9 CE    JSR   $CEC9
1245-   20 D4 C8    JSR   $C8D4
1248-   C5 20       CMP   $20
124A-   C6 CF       DEC   $CF
124C-   CC CC CF    CPY   $CFCC
124F-   D7          ???
1250-   C9 CE       CMP   #$CE
1252-   C7          ???
1253-   BA          TSX
1254-   A2 AC       LDX   #$AC
1256-   B8          CLV
1257-   C4 B8       CPY   $B8
1259-   C4 8D       CPY   $8D
125B-   A0 C4       LDY   #$C4
125D-   C9 CD       CMP   #$CD
125F-   B8          CLV
1260-   B1 A0       LDA   ($A0),Y
1262-   A3          ???
1263-   C1 D2       CMP   ($D2,X)
1265-   D2 C1       CMP   ($C1)
1267-   D9 B2 BB    CMP   $BBB2,Y
126A-   A3          ???
126B-   B1 B0       LDA   ($B0),Y
126D-   BB          ???
126E-   A3          ???
126F-   B2 BB       LDA   ($BB)
1271-   A3          ???
1272-   A4 C5       LDY   $C5
1274-   C5 8D       CMP   $8D
1276-   A0 D0       LDY   #$D0
1278-   D5 D4       CMP   $D4,X
127A-   B8          CLV
127B-   B1 A0       LDA   ($A0),Y
127D-   A3          ???
127E-   A4 B3       LDY   $B3
1280-   B2 B0       LDA   ($B0)
1282-   BB          ???
1283-   A3          ???
1284-   C1 D2       CMP   ($D2,X)
1286-   D2 C1       CMP   ($C1)
1288-   D9 B2 BB    CMP   $BBB2,Y
128B-   A3          ???
128C-   B8          CLV
128D-   8D A0 C4    STA   $C4A0
1290-   D5 CD       CMP   $CD,X
1292-   D0 A0       BNE   $1234
1294-   A3          ???
1295-   C1 D2       CMP   ($D2,X)
1297-   D2 C1       CMP   ($C1)
1299-   D9 B2 BB    CMP   $BBB2,Y
129C-   A3          ???
129D-   B0 B2       BCS   $1251
129F-   8D A0 C4    STA   $C4A0
12A2-   D5 CD       CMP   $CD,X
12A4-   D0 A0       BNE   $1246
12A6-   A3          ???
12A7-   C1 D2       CMP   ($D2,X)
12A9-   D2 C1       CMP   ($C1)
12AB-   D9 B2 AB    CMP   $ABB2,Y
12AE-   B2 BB       LDA   ($BB)
12B0-   A3          ???
12B1-   B5 8D       LDA   $8D,X
12B3-   A0 C4       LDY   #$C4
12B5-   D5 CD       CMP   $CD,X
12B7-   D0 A0       BNE   $1259
12B9-   A3          ???
12BA-   C1 D2       CMP   ($D2,X)
12BC-   D2 C1       CMP   ($C1)
12BE-   D9 B2 AB    CMP   $ABB2,Y
12C1-   B7          ???
12C2-   BB          ???
12C3-   A3          ???
12C4-   B5 8D       LDA   $8D,X
12C6-   A0 C4       LDY   #$C4
12C8-   D5 CD       CMP   $CD,X
12CA-   D0 A0       BNE   $126C
12CC-   A3          ???
12CD-   C1 D2       CMP   ($D2,X)
12CF-   D2 C1       CMP   ($C1)
12D1-   D9 B2 AB    CMP   $ABB2,Y
12D4-   B1 B2       LDA   ($B2),Y
12D6-   BB          ???
12D7-   A3          ???
12D8-   B5 8D       LDA   $8D,X
12DA-   A0 C4       LDY   #$C4
12DC-   D5 CD       CMP   $CD,X
12DE-   D0 A0       BNE   $1280
12E0-   A3          ???
12E1-   C1 D2       CMP   ($D2,X)
12E3-   D2 C1       CMP   ($C1)
12E5-   D9 B2 AB    CMP   $ABB2,Y
12E8-   B1 B7       LDA   ($B7),Y
12EA-   BB          ???
12EB-   A3          ???
12EC-   B5 8D       LDA   $8D,X
12EE-   A0 DF       LDY   #$DF
12F0-   D7          ???
12F1-   C1 C9       CMP   ($C9,X)
12F3-   D4          ???
12F4-   8D A0 DF    STA   $DFA0
12F7-   D0 D2       BNE   $12CB
12F9-   CE D4 A0    DEC   $A0D4
12FC-   A2 20       LDX   #$20
12FE-   A2 AC       LDX   #$AC
1300-   B8          CLV
1301-   C4 B8       CPY   $B8
1303-   C4 8D       CPY   $8D
1305-   A0 DF       LDY   #$DF
1307-   D0 D2       BNE   $12DB
1309-   CE D4 A0    DEC   $A0D4
130C-   A2 C1       LDX   #$C1
130E-   CC D3 CF    CPY   $CFD3
1311-   20 CE CF    JSR   $CFCE
1314-   D4          ???
1315-   C5 20       CMP   $20
1317-   D4          ???
1318-   C8          INY
1319-   C1 D4       CMP   ($D4,X)
131B-   20 C2 C5    JSR   $C5C2
131E-   C3          ???
131F-   C1 D5       CMP   ($D5,X)
1321-   D3          ???
1322-   C5 20       CMP   $20
1324-   C5 CC       CMP   $CC
1326-   C5 CD       CMP   $CD
1328-   C5 CE       CMP   $CE
132A-   D4          ???
132B-   20 D3 C9    JSR   $C9D3
132E-   DA          PHX
132F-   C5 D3       CMP   $D3
1331-   A2 AC       LDX   #$AC
1333-   B8          CLV
1334-   C4 8D       CPY   $8D
1336-   A0 DF       LDY   #$DF
1338-   D0 D2       BNE   $130C
133A-   CE D4 A0    DEC   $A0D4
133D-   A2 C3       LDX   #$C3
133F-   C1 CE       CMP   ($CE,X)
1341-   20 D6 C1    JSR   $C1D6
1344-   D2 D9       CMP   ($D9)
1346-   20 C6 D2    JSR   $D2C6
1349-   CF          ???
134A-   CD 20 B1    CMP   $B120
134D-   20 C2 D9    JSR   $D9C2
1350-   D4          ???
1351-   C5 20       CMP   $20
1353-   D4          ???
1354-   CF          ???
1355-   20 B2 B5    JSR   $B5B2
1358-   B5 20       LDA   $20,X
135A-   C2          ???
135B-   D9 D4 C5    CMP   $C5D4,Y
135E-   D3          ???
135F-   AC A2 AC    LDY   $ACA2
1362-   B8          CLV
1363-   C4 8D       CPY   $8D
1365-   A0 DF       LDY   #$DF
1367-   D0 D2       BNE   $133B
1369-   CE D4 A0    DEC   $A0D4
136C-   A2 C1       LDX   #$C1
136E-   CC CC CF    CPY   $CFCC
1371-   D7          ???
1372-   C9 CE       CMP   #$CE
1374-   C7          ???
1375-   20 CC C9    JSR   $C9CC
1378-   D4          ???
1379-   C5 D2       CMP   $D2
137B-   C1 CC       CMP   ($CC,X)
137D-   20 D6 C1    JSR   $C1D6
1380-   CC D5 C5    CPY   $C5D5
1383-   D3          ???
1384-   20 C9 D3    JSR   $D3C9
1387-   20 C9 CD    JSR   $CDC9
138A-   D0 D2       BNE   $135E
138C-   C1 C3       CMP   ($C3,X)
138E-   D4          ???
138F-   C9 C3       CMP   #$C3
1391-   C1 CC       CMP   ($CC,X)
1393-   AE A2 AC    LDX   $ACA2
1396-   B8          CLV
1397-   C4 8D       CPY   $8D
1399-   A0 DF       LDY   #$DF
139B-   D0 D2       BNE   $136F
139D-   CE D4 A0    DEC   $A0D4
13A0-   A2 D4       LDX   #$D4
13A2-   C8          INY
13A3-   D5 D3       CMP   $D3,X
13A5-   AC 20 C2    LDY   $C220
13A8-   C5 20       CMP   $20
13AA-   D3          ???
13AB-   D5 D2       CMP   $D2,X
13AD-   C5 20       CMP   $20
13AF-   D4          ???
13B0-   CF          ???
13B1-   20 D5 D4    JSR   $D4D5
13B4-   C9 CC       CMP   #$CC
13B6-   C9 DA       CMP   #$DA
13B8-   C5 20       CMP   $20
13BA-   C1 20       CMP   ($20,X)
13BC-   D0 CF       BNE   $138D
13BE-   D2 D4       CMP   ($D4)
13C0-   C9 CF       CMP   #$CF
13C2-   CE A2 AC    DEC   $ACA2
13C5-   B8          CLV
13C6-   C4 8D       CPY   $8D
13C8-   A0 DF       LDY   #$DF
13CA-   D0 D2       BNE   $139E
13CC-   CE D4 A0    DEC   $A0D4
13CF-   A2 CF       LDX   #$CF
13D1-   C6 20       DEC   $20
13D3-   CD C5 CD    CMP   $CDC5
13D6-   20 C6 CF    JSR   $CFC6
13D9-   D2 20       CMP   ($20)
13DB-   D0 C1       BNE   $139E
13DD-   D3          ???
13DE-   D3          ???
13DF-   C9 CE       CMP   #$CE
13E1-   C7          ???
13E2-   20 D4 CF    JSR   $CFD4
13E5-   20 C1 CE    JSR   $CEC1
13E8-   C4 20       CPY   $20
13EA-   C6 D2       DEC   $D2
13EC-   CF          ???
13ED-   CD 20 C1    CMP   $C120
13F0-   D2 D2       CMP   ($D2)
13F2-   C1 D9       CMP   ($D9,X)
13F4-   20 A2 AC    JSR   $ACA2
13F7-   B8          CLV
13F8-   C4 8D       CPY   $8D
13FA-   A0 DF       LDY   #$DF
13FC-   D0 D2       BNE   $13D0
13FE-   CE D4 A0    DEC   $A0D4
1401-   A2 D3       LDX   #$D3
1403-   D5 C2       CMP   $C2,X
1405-   D2 CF       CMP   ($CF)
1407-   D5 D4       CMP   $D4,X
1409-   C9 CE       CMP   #$CE
140B-   C5 D3       CMP   $D3
140D-   AE 20 D4    LDX   $D420
1410-   C8          INY
1411-   C5 20       CMP   $20
1413-   DB          ???
1414-   D0 C1       BNE   $13D7
1416-   D2 C1       CMP   ($C1)
1418-   CD DD 20    CMP   $20DD
141B-   C1 C4       CMP   ($C4,X)
141D-   C4 D2       CPY   $D2
141F-   20 C9 D3    JSR   $D3C9
1422-   20 C7 CF    JSR   $CFC7
1425-   CF          ???
1426-   C4 A2       CPY   $A2
1428-   AC B8 C4    LDY   $C4B8
142B-   8D A0 DF    STA   $DFA0
142E-   D0 D2       BNE   $1402
1430-   CE D4 A0    DEC   $A0D4
1433-   A2 C6       LDX   #$C6
1435-   CF          ???
1436-   D2 20       CMP   ($20)
1438-   D4          ???
1439-   C8          INY
143A-   C9 D3       CMP   #$D3
143C-   AE A2 AC    LDX   $ACA2
143F-   B8          CLV
1440-   C4 B8       CPY   $B8
1442-   C4 8D       CPY   $8D
1444-   A0 DF       LDY   #$DF
1446-   D7          ???
1447-   C1 C9       CMP   ($C9,X)
1449-   D4          ???
144A-   8D AA 8D    STA   $8DAA
144D-   A0 DF       LDY   #$DF
144F-   D0 D2       BNE   $1423
1451-   CE D4 A0    DEC   $A0D4
1454-   A2 20       LDX   #$20
1456-   A2 AC       LDX   #$AC
1458-   B8          CLV
1459-   C4 B8       CPY   $B8
145B-   C4 8D       CPY   $8D
145D-   AA          TAX
145E-   8D AA AA    STA   $AAAA
1461-   20 C7 C5    JSR   $C5C7
1464-   D4          ???
1465-   B8          CLV
1466-   B1 20       LDA   ($20),Y
1468-   D3          ???
1469-   C9 CD       CMP   #$CD
146B-   D0 CC       BNE   $1439
146D-   D9 20 D2    CMP   $D220,Y
1470-   C5 D4       CMP   $D4
1472-   D2 C9       CMP   ($C9)
1474-   C5 D6       CMP   $D6
1476-   C5 D3       CMP   $D3
1478-   20 D4 C8    JSR   $C8D4
147B-   C5 20       CMP   $20
147D-   D6 C1       DEC   $C1,X
147F-   CC D5 C5    CPY   $C5D5
1482-   20 C9 CE    JSR   $CEC9
1485-   20 C1 CE    JSR   $CEC1
1488-   8D AA AA    STA   $AAAA
148B-   20 C1 D2    JSR   $D2C1
148E-   D2 C1       CMP   ($C1)
1490-   D9 20 C1    CMP   $C120,Y
1493-   D4          ???
1494-   20 D4 C8    JSR   $C8D4
1497-   C5 20       CMP   $20
1499-   C7          ???
149A-   C9 D6       CMP   #$D6
149C-   C5 CE       CMP   $CE
149E-   20 C9 CE    JSR   $CEC9
14A1-   C4 C5       CPY   $C5
14A3-   D8          CLD
14A4-   C5 C4       CMP   $C4
14A6-   20 C5 CC    JSR   $CCC5
14A9-   C5 CD       CMP   $CD
14AB-   C5 CE       CMP   $CE
14AD-   D4          ???
14AE-   20 C9 CE    JSR   $CEC9
14B1-   8D AA AA    STA   $AAAA
14B4-   20 DB D2    JSR   $D2DB
14B7-   C5 D4       CMP   $D4
14B9-   D5 D2       CMP   $D2,X
14BB-   CE DD AE    DEC   $AEDD
14BE-   8D AA 8D    STA   $8DAA
14C1-   AA          TAX
14C2-   AA          TAX
14C3-   20 CD C1    JSR   $C1CD
14C6-   C3          ???
14C7-   D2 CF       CMP   ($CF)
14C9-   BA          TSX
14CA-   20 C7 C5    JSR   $C5C7
14CD-   D4          ???
14CE-   B8          CLV
14CF-   B1 20       LDA   ($20),Y
14D1-   C1 D2       CMP   ($D2,X)
14D3-   D2 C1       CMP   ($C1)
14D5-   D9 DF C1    CMP   $C1DF,Y
14D8-   C4 C4       CPY   $C4
14DA-   D2 BB       CMP   ($BB)
14DC-   C9 CE       CMP   #$CE
14DE-   C4 C5       CPY   $C5
14E0-   D8          CLD
14E1-   8D AA 8D    STA   $8DAA
14E4-   A0 DF       LDY   #$DF
14E6-   D0 D2       BNE   $14BA
14E8-   CE D4 A0    DEC   $A0D4
14EB-   A2 D4       LDX   #$D4
14ED-   C8          INY
14EE-   C5 20       CMP   $20
14F0-   C7          ???
14F1-   C5 D4       CMP   $D4
14F3-   B8          CLV
14F4-   B1 20       LDA   ($20),Y
14F6-   CD C1 C3    CMP   $C3C1
14F9-   D2 CF       CMP   ($CF)
14FB-   20 C7 C5    JSR   $C5C7
14FE-   D4          ???
14FF-   D3          ???
1500-   20 D4 C8    JSR   $C8D4
1503-   C5 20       CMP   $20
1505-   D6 C1       DEC   $C1,X
1507-   CC D5 C5    CPY   $C5D5
150A-   20 C8 C5    JSR   $C5C8
150D-   CC C4 A2    CPY   $A2C4
1510-   AC B8 C4    LDY   $C4B8
1513-   8D A0 DF    STA   $DFA0
1516-   D0 D2       BNE   $14EA
1518-   CE D4 A0    DEC   $A0D4
151B-   A2 C9       LDX   #$C9
151D-   CE 20 D4    DEC   $D420
1520-   C8          INY
1521-   C5 20       CMP   $20
1523-   C7          ???
1524-   C9 D6       CMP   #$D6
1526-   C5 CE       CMP   $CE
1528-   20 C5 CC    JSR   $CCC5
152B-   C5 CD       CMP   $CD
152D-   C5 CE       CMP   $CE
152F-   D4          ???
1530-   20 C9 CE    JSR   $CEC9
1533-   20 D4 C8    JSR   $C8D4
1536-   C5 20       CMP   $20
1538-   C7          ???
1539-   C9 D6       CMP   #$D6
153B-   C5 CE       CMP   $CE
153D-   A2 AC       LDX   #$AC
153F-   B8          CLV
1540-   C4 8D       CPY   $8D
1542-   A0 DF       LDY   #$DF
1544-   D0 D2       BNE   $1518
1546-   CE D4 A0    DEC   $A0D4
1549-   A2 C1       LDX   #$C1
154B-   D2 D2       CMP   ($D2)
154D-   C1 D9       CMP   ($D9,X)
154F-   AE 20 D4    LDX   $D420
1552-   C8          INY
1553-   D5 D3       CMP   $D3,X
1555-   A2 AC       LDX   #$AC
1557-   B8          CLV
1558-   C4 B8       CPY   $B8
155A-   C4 8D       CPY   $8D
155C-   A0 DF       LDY   #$DF
155E-   D0 D2       BNE   $1532
1560-   CE D4 A0    DEC   $A0D4
1563-   A2 C7       LDX   #$C7
1565-   C5 D4       CMP   $D4
1567-   B8          CLV
1568-   B1 20       LDA   ($20),Y
156A-   C1 D2       CMP   ($D2,X)
156C-   D2 C1       CMP   ($C1)
156E-   D9 B2 BB    CMP   $BBB2,Y
1571-   A3          ???
1572-   B8          CLV
1573-   20 D2 C5    JSR   $C5D2
1576-   D4          ???
1577-   D5 D2       CMP   $D2,X
1579-   CE D3 BA    DEC   $BAD3
157C-   A2 AC       LDX   #$AC
157E-   B8          CLV
157F-   C4 B8       CPY   $B8
1581-   C4 8D       CPY   $8D
1583-   A0 C7       LDY   #$C7
1585-   C5 D4       CMP   $D4
1587-   B8          CLV
1588-   B1 A0       LDA   ($A0),Y
158A-   A3          ???
158B-   C1 D2       CMP   ($D2,X)
158D-   D2 C1       CMP   ($C1)
158F-   D9 B2 BB    CMP   $BBB2,Y
1592-   A3          ???
1593-   B8          CLV
1594-   8D A0 C4    STA   $C4A0
1597-   D5 CD       CMP   $CD,X
1599-   D0 A0       BNE   $153B
159B-   A3          ???
159C-   D2 C5       CMP   ($C5)
159E-   D4          ???
159F-   D5 D2       CMP   $D2,X
15A1-   CE BB D2    DEC   $D2BB
15A4-   C5 D4       CMP   $D4
15A6-   CC C5 CE    CPY   $CEC5
15A9-   8D A0 DF    STA   $DFA0
15AC-   D0 D2       BNE   $1580
15AE-   CE D4 A0    DEC   $A0D4
15B1-   A2 20       LDX   #$20
15B3-   A2 AC       LDX   #$AC
15B5-   B8          CLV
15B6-   C4 B8       CPY   $B8
15B8-   C4 8D       CPY   $8D
15BA-   A0 DF       LDY   #$DF
15BC-   D7          ???
15BD-   C1 C9       CMP   ($C9,X)
15BF-   D4          ???
15C0-   8D AA 8D    STA   $8DAA
15C3-   AA          TAX
15C4-   AA          TAX
15C5-   20 C4 C9    JSR   $C9C4
15C8-   CD B8 B2    CMP   $B2B8
15CB-   20 C3 D2    JSR   $D2C3
15CE-   C5 C1       CMP   $C1
15D0-   D4          ???
15D1-   C5 D3       CMP   $D3
15D3-   20 C1 20    JSR   $20C1
15D6-   B2 AD       LDA   ($AD)
15D8-   C4 C9       CPY   $C9
15DA-   CD C5 CE    CMP   $CEC5
15DD-   D3          ???
15DE-   C9 CF       CMP   #$CF
15E0-   CE C1 CC    DEC   $CCC1
15E3-   20 C1 D2    JSR   $D2C1
15E6-   D2 C1       CMP   ($C1)
15E8-   D9 20 D7    CMP   $D720,Y
15EB-   C9 D4       CMP   #$D4
15ED-   C8          INY
15EE-   20 D4 C8    JSR   $C8D4
15F1-   C5 8D       CMP   $8D
15F3-   AA          TAX
15F4-   AA          TAX
15F5-   20 D3 D0    JSR   $D0D3
15F8-   C5 C3       CMP   $C3
15FA-   C9 C6       CMP   #$C6
15FC-   C9 C5       CMP   #$C5
15FE-   C4 20       CPY   $20
1600-   C5 CC       CMP   $CC
1602-   C5 CD       CMP   $CD
1604-   C5 CE       CMP   $CE
1606-   D4          ???
1607-   20 CC C5    JSR   $C5CC
160A-   CE C7 D4    DEC   $D4C7
160D-   C8          INY
160E-   20 C1 CE    JSR   $CEC1
1611-   C4 20       CPY   $20
1613-   D8          CLD
1614-   AC D9 20    LDY   $20D9
1617-   C4 C9       CPY   $C9
1619-   CD C5 CE    CMP   $CEC5
161C-   D3          ???
161D-   C9 CF       CMP   #$CF
161F-   CE D3 8D    DEC   $8DD3
1622-   AA          TAX
1623-   8D AA AA    STA   $AAAA
1626-   20 CD C1    JSR   $C1CD
1629-   C3          ???
162A-   D2 CF       CMP   ($CF)
162C-   BA          TSX
162D-   20 C4 C9    JSR   $C9C4
1630-   CD B8 B2    CMP   $B2B8
1633-   20 C1 D2    JSR   $D2C1
1636-   D2 C1       CMP   ($C1)
1638-   D9 DF C1    CMP   $C1DF,Y
163B-   C4 C4       CPY   $C4
163D-   D2 BB       CMP   ($BB)
163F-   D8          CLD
1640-   DF          ???
1641-   C4 C9       CPY   $C9
1643-   CD BB D9    CMP   $D9BB
1646-   DF          ???
1647-   C4 C9       CPY   $C9
1649-   CD BB C5    CMP   $C5BB
164C-   CC C5 CD    CPY   $CDC5
164F-   DF          ???
1650-   CC C5 CE    CPY   $CEC5
1653-   C7          ???
1654-   D4          ???
1655-   C8          INY
1656-   8D AA 8D    STA   $8DAA
1659-   A0 C4       LDY   #$C4
165B-   C9 CD       CMP   #$CD
165D-   B8          CLV
165E-   B2 A0       LDA   ($A0)
1660-   A3          ???
1661-   C1 D2       CMP   ($D2,X)
1663-   D2 C1       CMP   ($C1)
1665-   D9 B2 BB    CMP   $BBB2,Y
1668-   A3          ???
1669-   B1 B0       LDA   ($B0),Y
166B-   BB          ???
166C-   A3          ???
166D-   B1 B0       LDA   ($B0),Y
166F-   BB          ???
1670-   A3          ???
1671-   B1 BB       LDA   ($BB),Y
1673-   A3          ???
1674-   A4 B2       LDY   $B2
1676-   C4 8D       CPY   $8D
1678-   A0 DF       LDY   #$DF
167A-   D0 D2       BNE   $164E
167C-   CE D4 A0    DEC   $A0D4
167F-   A2 C4       LDX   #$C4
1681-   C9 CD       CMP   #$CD
1683-   B8          CLV
1684-   B2 20       LDA   ($20)
1686-   C3          ???
1687-   D2 C5       CMP   ($C5)
1689-   C1 D4       CMP   ($D4,X)
168B-   C5 D3       CMP   $D3
168D-   20 C1 CE    JSR   $CEC1
1690-   20 C1 D2    JSR   $D2C1
1693-   D2 C1       CMP   ($C1)
1695-   D9 20 CC    CMP   $CC20,Y
1698-   C9 CB       CMP   #$CB
169A-   C5 20       CMP   $20
169C-   C4 C9       CPY   $C9
169E-   CD B8 B1    CMP   $B1B8
16A1-   AC A2 AC    LDY   $ACA2
16A4-   B8          CLV
16A5-   C4 8D       CPY   $8D
16A7-   A0 DF       LDY   #$DF
16A9-   D0 D2       BNE   $167D
16AB-   CE D4 A0    DEC   $A0D4
16AE-   A2 C2       LDX   #$C2
16B0-   D5 D4       CMP   $D4,X
16B2-   20 C9 CE    JSR   $CEC9
16B5-   20 B2 AD    JSR   $ADB2
16B8-   C4 C9       CPY   $C9
16BA-   CD C5 CE    CMP   $CEC5
16BD-   D3          ???
16BE-   C9 CF       CMP   #$CF
16C0-   CE D3 20    DEC   $20D3
16C3-   C9 CE       CMP   #$CE
16C5-   D3          ???
16C6-   D4          ???
16C7-   C5 C1       CMP   $C1
16C9-   C4 20       CPY   $20
16CB-   CF          ???
16CC-   C6 20       DEC   $20
16CE-   CF          ???
16CF-   CE C5 AE    DEC   $AEC5
16D2-   A2 AC       LDX   #$AC
16D4-   B8          CLV
16D5-   C4 B8       CPY   $B8
16D7-   C4 8D       CPY   $8D
16D9-   A0 DF       LDY   #$DF
16DB-   D0 D2       BNE   $16AF
16DD-   CE D4 A0    DEC   $A0D4
16E0-   A2 D4       LDX   #$D4
16E2-   C8          INY
16E3-   D5 D3       CMP   $D3,X
16E5-   20 C4 C9    JSR   $C9C4
16E8-   CD B8 B2    CMP   $B2B8
16EB-   20 C1 D2    JSR   $D2C1
16EE-   D2 C1       CMP   ($C1)
16F0-   D9 B2 BB    CMP   $BBB2,Y
16F3-   A3          ???
16F4-   B1 B0       LDA   ($B0),Y
16F6-   BB          ???
16F7-   A3          ???
16F8-   B1 B0       LDA   ($B0),Y
16FA-   BB          ???
16FB-   A3          ???
16FC-   B1 BB       LDA   ($BB),Y
16FE-   A3          ???
16FF-   A4 B2       LDY   $B2
1701-   C4 20       CPY   $20
1703-   D2 C5       CMP   ($C5)
1705-   D4          ???
1706-   D5 D2       CMP   $D2,X
1708-   CE D3 BA    DEC   $BAD3
170B-   20 A2 AC    JSR   $ACA2
170E-   B8          CLV
170F-   C4 B8       CPY   $B8
1711-   C4 8D       CPY   $8D
1713-   A0 C4       LDY   #$C4
1715-   D5 CD       CMP   $CD,X
1717-   D0 A0       BNE   $16B9
1719-   A3          ???
171A-   C1 D2       CMP   ($D2,X)
171C-   D2 C1       CMP   ($C1)
171E-   D9 B2 BB    CMP   $BBB2,Y
1721-   A3          ???
1722-   B0 B3       BCS   $16D7
1724-   8D A0 C4    STA   $C4A0
1727-   D5 CD       CMP   $CD,X
1729-   D0 A0       BNE   $16CB
172B-   A3          ???
172C-   C1 D2       CMP   ($D2,X)
172E-   D2 C1       CMP   ($C1)
1730-   D9 B2 AB    CMP   $ABB2,Y
1733-   B0 B3       BCS   $16E8
1735-   BB          ???
1736-   A3          ???
1737-   B1 B0       LDA   ($B0),Y
1739-   8D A0 C4    STA   $C4A0
173C-   D5 CD       CMP   $CD,X
173E-   D0 A0       BNE   $16E0
1740-   A3          ???
1741-   C1 D2       CMP   ($D2,X)
1743-   D2 C1       CMP   ($C1)
1745-   D9 B2 AB    CMP   $ABB2,Y
1748-   B1 B3       LDA   ($B3),Y
174A-   BB          ???
174B-   A3          ???
174C-   B1 B0       LDA   ($B0),Y
174E-   8D A0 C4    STA   $C4A0
1751-   D5 CD       CMP   $CD,X
1753-   D0 A0       BNE   $16F5
1755-   A3          ???
1756-   C1 D2       CMP   ($D2,X)
1758-   D2 C1       CMP   ($C1)
175A-   D9 B2 AB    CMP   $ABB2,Y
175D-   B2 B3       LDA   ($B3)
175F-   BB          ???
1760-   A3          ???
1761-   B1 B0       LDA   ($B0),Y
1763-   8D A0 C4    STA   $C4A0
1766-   D5 CD       CMP   $CD,X
1768-   D0 A0       BNE   $170A
176A-   A3          ???
176B-   C1 D2       CMP   ($D2,X)
176D-   D2 C1       CMP   ($C1)
176F-   D9 B2 AB    CMP   $ABB2,Y
1772-   B3          ???
1773-   B3          ???
1774-   BB          ???
1775-   A3          ???
1776-   B1 B0       LDA   ($B0),Y
1778-   8D A0 C4    STA   $C4A0
177B-   D5 CD       CMP   $CD,X
177D-   D0 A0       BNE   $171F
177F-   A3          ???
1780-   C1 D2       CMP   ($D2,X)
1782-   D2 C1       CMP   ($C1)
1784-   D9 B2 AB    CMP   $ABB2,Y
1787-   B4 B3       LDY   $B3,X
1789-   BB          ???
178A-   A3          ???
178B-   B1 B0       LDA   ($B0),Y
178D-   8D A0 C4    STA   $C4A0
1790-   D5 CD       CMP   $CD,X
1792-   D0 A0       BNE   $1734
1794-   A3          ???
1795-   C1 D2       CMP   ($D2,X)
1797-   D2 C1       CMP   ($C1)
1799-   D9 B2 AB    CMP   $ABB2,Y
179C-   B5 B3       LDA   $B3,X
179E-   BB          ???
179F-   A3          ???
17A0-   B1 B0       LDA   ($B0),Y
17A2-   8D A0 C4    STA   $C4A0
17A5-   D5 CD       CMP   $CD,X
17A7-   D0 A0       BNE   $1749
17A9-   A3          ???
17AA-   C1 D2       CMP   ($D2,X)
17AC-   D2 C1       CMP   ($C1)
17AE-   D9 B2 AB    CMP   $ABB2,Y
17B1-   B6 B3       LDX   $B3,Y
17B3-   BB          ???
17B4-   A3          ???
17B5-   B1 B0       LDA   ($B0),Y
17B7-   8D A0 C4    STA   $C4A0
17BA-   D5 CD       CMP   $CD,X
17BC-   D0 A0       BNE   $175E
17BE-   A3          ???
17BF-   C1 D2       CMP   ($D2,X)
17C1-   D2 C1       CMP   ($C1)
17C3-   D9 B2 AB    CMP   $ABB2,Y
17C6-   B7          ???
17C7-   B3          ???
17C8-   BB          ???
17C9-   A3          ???
17CA-   B1 B0       LDA   ($B0),Y
17CC-   8D A0 C4    STA   $C4A0
17CF-   D5 CD       CMP   $CD,X
17D1-   D0 A0       BNE   $1773
17D3-   A3          ???
17D4-   C1 D2       CMP   ($D2,X)
17D6-   D2 C1       CMP   ($C1)
17D8-   D9 B2 AB    CMP   $ABB2,Y
17DB-   B8          CLV
17DC-   B3          ???
17DD-   BB          ???
17DE-   A3          ???
17DF-   B1 B0       LDA   ($B0),Y
17E1-   8D A0 C4    STA   $C4A0
17E4-   D5 CD       CMP   $CD,X
17E6-   D0 A0       BNE   $1788
17E8-   A3          ???
17E9-   C1 D2       CMP   ($D2,X)
17EB-   D2 C1       CMP   ($C1)
17ED-   D9 B2 AB    CMP   $ABB2,Y
17F0-   B9 B3 BB    LDA   $BBB3,Y
17F3-   A3          ???
17F4-   B1 B0       LDA   ($B0),Y
17F6-   8D A0 DF    STA   $DFA0
17F9-   D0 D2       BNE   $17CD
17FB-   CE D4 A0    DEC   $A0D4
17FE-   A2 20       LDX   #$20
1800-   A2 AC       LDX   #$AC
1802-   B8          CLV
1803-   C4 B8       CPY   $B8
1805-   C4 8D       CPY   $8D
1807-   A0 DF       LDY   #$DF
1809-   D7          ???
180A-   C1 C9       CMP   ($C9,X)
180C-   D4          ???
180D-   8D AA 8D    STA   $8DAA
1810-   AA          TAX
1811-   AA          TAX
1812-   20 D4 C8    JSR   $C8D4
1815-   C5 20       CMP   $20
1817-   D0 D5       BNE   $17EE
1819-   D4          ???
181A-   B8          CLV
181B-   B2 20       LDA   ($20)
181D-   CD C1 C3    CMP   $C3C1
1820-   D2 CF       CMP   ($CF)
1822-   20 CD C9    JSR   $C9CD
1825-   D2 D2       CMP   ($D2)
1827-   CF          ???
1828-   D2 D3       CMP   ($D3)
182A-   20 D0 D5    JSR   $D5D0
182D-   D4          ???
182E-   B8          CLV
182F-   B1 AC       LDA   ($AC),Y
1831-   20 C2 D5    JSR   $D5C2
1834-   D4          ???
1835-   20 C9 CE    JSR   $CEC9
1838-   20 B2 20    JSR   $20B2
183B-   C4 C9       CPY   $C9
183D-   CD C5 CE    CMP   $CEC5
1840-   D3          ???
1841-   C9 CF       CMP   #$CF
1843-   CE D3 AE    DEC   $AED3
1846-   8D AA AA    STA   $AAAA
1849-   20 C9 CE    JSR   $CEC9
184C-   20 D3 C8    JSR   $C8D3
184F-   CF          ???
1850-   D2 D4       CMP   ($D4)
1852-   AC 20 C9    LDY   $C920
1855-   D4          ???
1856-   20 D3 C9    JSR   $C9D3
1859-   CD D0 CC    CMP   $CCD0
185C-   D9 20 D0    CMP   $D020,Y
185F-   D5 D4       CMP   $D4,X
1861-   D3          ???
1862-   20 D4 C8    JSR   $C8D4
1865-   C5 20       CMP   $20
1867-   D3          ???
1868-   D4          ???
1869-   D2 C9       CMP   ($C9)
186B-   CE C7 20    DEC   $20C7
186E-   CF          ???
186F-   C6 20       DEC   $20
1871-   C2          ???
1872-   D9 D4 C5    CMP   $C5D4,Y
1875-   D3          ???
1876-   8D AA AA    STA   $AAAA
1879-   20 C6 CF    JSR   $CFC6
187C-   D5 CE       CMP   $CE,X
187E-   C4 20       CPY   $20
1880-   C1 D4       CMP   ($D4,X)
1882-   20 D3 CF    JSR   $CFD3
1885-   D5 D2       CMP   $D2,X
1887-   C3          ???
1888-   C5 DF       CMP   $DF
188A-   C1 C4       CMP   ($C4,X)
188C-   C4 D2       CPY   $D2
188E-   20 D4 C8    JSR   $C8D4
1891-   C1 D4       CMP   ($D4,X)
1893-   20 C3 CF    JSR   $CFC3
1896-   D2 D2       CMP   ($D2)
1898-   C5 CC       CMP   $CC
189A-   C1 D4       CMP   ($D4,X)
189C-   C5 20       CMP   $20
189E-   D4          ???
189F-   CF          ???
18A0-   20 D4 C8    JSR   $C8D4
18A3-   C5 20       CMP   $20
18A5-   C1 D2       CMP   ($D2,X)
18A7-   D2 C1       CMP   ($C1)
18A9-   D9 A7 D3    CMP   $D3A7,Y
18AC-   8D AA AA    STA   $AAAA
18AF-   20 C5 CC    JSR   $CCC5
18B2-   C5 CD       CMP   $CD
18B4-   C5 CE       CMP   $CE
18B6-   D4          ???
18B7-   20 CC C5    JSR   $C5CC
18BA-   CE C7 D4    DEC   $D4C7
18BD-   C8          INY
18BE-   20 C9 CE    JSR   $CEC9
18C1-   D4          ???
18C2-   CF          ???
18C3-   20 D4 C8    JSR   $C8D4
18C6-   C5 20       CMP   $20
18C8-   D3          ???
18C9-   D0 C5       BNE   $1890
18CB-   C3          ???
18CC-   C9 C6       CMP   #$C6
18CE-   C9 C5       CMP   #$C5
18D0-   C4 20       CPY   $20
18D2-   D8          CLD
18D3-   AC D9 20    LDY   $20D9
18D6-   C9 CE       CMP   #$CE
18D8-   C4 C5       CPY   $C5
18DA-   D8          CLD
18DB-   AE 8D AA    LDX   $AA8D
18DE-   8D AA AA    STA   $AAAA
18E1-   20 CD C1    JSR   $C1CD
18E4-   C3          ???
18E5-   D2 CF       CMP   ($CF)
18E7-   BA          TSX
18E8-   20 D0 D5    JSR   $D5D0
18EB-   D4          ???
18EC-   B8          CLV
18ED-   B2 20       LDA   ($20)
18EF-   D3          ???
18F0-   CF          ???
18F1-   D5 D2       CMP   $D2,X
18F3-   C3          ???
18F4-   C5 DF       CMP   $DF
18F6-   C1 C4       CMP   ($C4,X)
18F8-   C4 D2       CPY   $D2
18FA-   BB          ???
18FB-   C1 D2       CMP   ($D2,X)
18FD-   D2 C1       CMP   ($C1)
18FF-   D9 DF C1    CMP   $C1DF,Y
1902-   C4 C4       CPY   $C4
1904-   D2 BB       CMP   ($BB)
1906-   D8          CLD
1907-   DF          ???
1908-   C9 CE       CMP   #$CE
190A-   C4 C5       CPY   $C5
190C-   D8          CLD
190D-   BB          ???
190E-   D9 DF C9    CMP   $C9DF,Y
1911-   CE C4 C5    DEC   $C5C4
1914-   D8          CLD
1915-   8D AA 8D    STA   $8DAA
1918-   A0 DF       LDY   #$DF
191A-   D0 D2       BNE   $18EE
191C-   CE D4 A0    DEC   $A0D4
191F-   A2 D0       LDX   #$D0
1921-   D5 D4       CMP   $D4,X
1923-   B8          CLV
1924-   B2 20       LDA   ($20)
1926-   C1 C3       CMP   ($C3,X)
1928-   D4          ???
1929-   D3          ???
192A-   20 CC C9    JSR   $C9CC
192D-   CB          ???
192E-   C5 20       CMP   $20
1930-   D0 D5       BNE   $1907
1932-   D4          ???
1933-   B8          CLV
1934-   B1 AC       LDA   ($AC),Y
1936-   20 C2 D5    JSR   $D5C2
1939-   D4          ???
193A-   20 C9 CE    JSR   $CEC9
193D-   20 D4 D7    JSR   $D7D4
1940-   CF          ???
1941-   A2 AC       LDX   #$AC
1943-   B8          CLV
1944-   C4 8D       CPY   $8D
1946-   A0 DF       LDY   #$DF
1948-   D0 D2       BNE   $191C
194A-   CE D4 A0    DEC   $A0D4
194D-   A2 C4       LDX   #$C4
194F-   C9 CD       CMP   #$CD
1951-   C5 CE       CMP   $CE
1953-   D3          ???
1954-   C9 CF       CMP   #$CF
1956-   CE D3 AE    DEC   $AED3
1959-   20 A2 AC    JSR   $ACA2
195C-   B8          CLV
195D-   C4 B8       CPY   $B8
195F-   C4 8D       CPY   $8D
1961-   A0 DF       LDY   #$DF
1963-   D0 D2       BNE   $1937
1965-   CE D4 A0    DEC   $A0D4
1968-   A2 D3       LDX   #$D3
196A-   CF          ???
196B-   BA          TSX
196C-   20 D0 D5    JSR   $D5D0
196F-   D4          ???
1970-   B8          CLV
1971-   B2 20       LDA   ($20)
1973-   A4 B3       LDY   $B3
1975-   B2 B0       LDA   ($B0)
1977-   BB          ???
1978-   C1 D2       CMP   ($D2,X)
197A-   D2 C1       CMP   ($C1)
197C-   D9 B2 BB    CMP   $BBB2,Y
197F-   A3          ???
1980-   B1 BB       LDA   ($BB),Y
1982-   A3          ???
1983-   B5 20       LDA   $20,X
1985-   D2 C5       CMP   ($C5)
1987-   D4          ???
1988-   D5 D2       CMP   $D2,X
198A-   CE D3 A2    DEC   $A2D3
198D-   AC B8 C4    LDY   $C4B8
1990-   B8          CLV
1991-   C4 8D       CPY   $8D
1993-   A0 CC       LDY   #$CC
1995-   C4 C1       CPY   $C1
1997-   A0 A3       LDY   #$A3
1999-   A4 B0       LDY   $B0
199B-   C6 8D       DEC   $8D
199D-   A0 D3       LDY   #$D3
199F-   D4          ???
19A0-   C1 A0       CMP   ($A0,X)
19A2-   A4 B3       LDY   $B3
19A4-   B2 B0       LDA   ($B0)
19A6-   8D A0 CC    STA   $CCA0
19A9-   C4 C1       CPY   $C1
19AB-   A0 A3       LDY   #$A3
19AD-   A4 C6       LDY   $C6
19AF-   C6 8D       DEC   $8D
19B1-   A0 D3       LDY   #$D3
19B3-   D4          ???
19B4-   C1 A0       CMP   ($A0,X)
19B6-   A4 B3       LDY   $B3
19B8-   B2 B1       LDA   ($B1)
19BA-   8D A0 D0    STA   $D0A0
19BD-   D5 D4       CMP   $D4,X
19BF-   B8          CLV
19C0-   B2 A0       LDA   ($A0)
19C2-   A3          ???
19C3-   A4 B3       LDY   $B3
19C5-   B2 B0       LDA   ($B0)
19C7-   BB          ???
19C8-   A3          ???
19C9-   C1 D2       CMP   ($D2,X)
19CB-   D2 C1       CMP   ($C1)
19CD-   D9 B2 BB    CMP   $BBB2,Y
19D0-   A3          ???
19D1-   B0 BB       BCS   $198E
19D3-   A3          ???
19D4-   B0 8D       BCS   $1963
19D6-   A0 D0       LDY   #$D0
19D8-   D5 D4       CMP   $D4,X
19DA-   B8          CLV
19DB-   B2 A0       LDA   ($A0)
19DD-   A3          ???
19DE-   A4 B3       LDY   $B3
19E0-   B2 B0       LDA   ($B0)
19E2-   BB          ???
19E3-   A3          ???
19E4-   C1 D2       CMP   ($D2,X)
19E6-   D2 C1       CMP   ($C1)
19E8-   D9 B2 BB    CMP   $BBB2,Y
19EB-   A3          ???
19EC-   B1 BB       LDA   ($BB),Y
19EE-   A3          ???
19EF-   B5 8D       LDA   $8D,X
19F1-   A0 C4       LDY   #$C4
19F3-   D5 CD       CMP   $CD,X
19F5-   D0 A0       BNE   $1997
19F7-   A3          ???
19F8-   C1 D2       CMP   ($D2,X)
19FA-   D2 C1       CMP   ($C1)
19FC-   D9 B2 BB    CMP   $BBB2,Y
19FF-   A3          ???
1A00-   B0 B3       BCS   $19B5
1A02-   8D A0 C4    STA   $C4A0
1A05-   D5 CD       CMP   $CD,X
1A07-   D0 A0       BNE   $19A9
1A09-   A3          ???
1A0A-   C1 D2       CMP   ($D2,X)
1A0C-   D2 C1       CMP   ($C1)
1A0E-   D9 B2 AB    CMP   $ABB2,Y
1A11-   B0 B3       BCS   $19C6
1A13-   BB          ???
1A14-   A3          ???
1A15-   B1 B0       LDA   ($B0),Y
1A17-   8D A0 C4    STA   $C4A0
1A1A-   D5 CD       CMP   $CD,X
1A1C-   D0 A0       BNE   $19BE
1A1E-   A3          ???
1A1F-   C1 D2       CMP   ($D2,X)
1A21-   D2 C1       CMP   ($C1)
1A23-   D9 B2 AB    CMP   $ABB2,Y
1A26-   B1 B3       LDA   ($B3),Y
1A28-   BB          ???
1A29-   A3          ???
1A2A-   B1 B0       LDA   ($B0),Y
1A2C-   8D A0 C4    STA   $C4A0
1A2F-   D5 CD       CMP   $CD,X
1A31-   D0 A0       BNE   $19D3
1A33-   A3          ???
1A34-   C1 D2       CMP   ($D2,X)
1A36-   D2 C1       CMP   ($C1)
1A38-   D9 B2 AB    CMP   $ABB2,Y
1A3B-   B2 B3       LDA   ($B3)
1A3D-   BB          ???
1A3E-   A3          ???
1A3F-   B1 B0       LDA   ($B0),Y
1A41-   8D A0 C4    STA   $C4A0
1A44-   D5 CD       CMP   $CD,X
1A46-   D0 A0       BNE   $19E8
1A48-   A3          ???
1A49-   C1 D2       CMP   ($D2,X)
1A4B-   D2 C1       CMP   ($C1)
1A4D-   D9 B2 AB    CMP   $ABB2,Y
1A50-   B3          ???
1A51-   B3          ???
1A52-   BB          ???
1A53-   A3          ???
1A54-   B1 B0       LDA   ($B0),Y
1A56-   8D A0 C4    STA   $C4A0
1A59-   D5 CD       CMP   $CD,X
1A5B-   D0 A0       BNE   $19FD
1A5D-   A3          ???
1A5E-   C1 D2       CMP   ($D2,X)
1A60-   D2 C1       CMP   ($C1)
1A62-   D9 B2 AB    CMP   $ABB2,Y
1A65-   B4 B3       LDY   $B3,X
1A67-   BB          ???
1A68-   A3          ???
1A69-   B1 B0       LDA   ($B0),Y
1A6B-   8D A0 C4    STA   $C4A0
1A6E-   D5 CD       CMP   $CD,X
1A70-   D0 A0       BNE   $1A12
1A72-   A3          ???
1A73-   C1 D2       CMP   ($D2,X)
1A75-   D2 C1       CMP   ($C1)
1A77-   D9 B2 AB    CMP   $ABB2,Y
1A7A-   B5 B3       LDA   $B3,X
1A7C-   BB          ???
1A7D-   A3          ???
1A7E-   B1 B0       LDA   ($B0),Y
1A80-   8D A0 C4    STA   $C4A0
1A83-   D5 CD       CMP   $CD,X
1A85-   D0 A0       BNE   $1A27
1A87-   A3          ???
1A88-   C1 D2       CMP   ($D2,X)
1A8A-   D2 C1       CMP   ($C1)
1A8C-   D9 B2 AB    CMP   $ABB2,Y
1A8F-   B6 B3       LDX   $B3,Y
1A91-   BB          ???
1A92-   A3          ???
1A93-   B1 B0       LDA   ($B0),Y
1A95-   8D A0 C4    STA   $C4A0
1A98-   D5 CD       CMP   $CD,X
1A9A-   D0 A0       BNE   $1A3C
1A9C-   A3          ???
1A9D-   C1 D2       CMP   ($D2,X)
1A9F-   D2 C1       CMP   ($C1)
1AA1-   D9 B2 AB    CMP   $ABB2,Y
1AA4-   B7          ???
1AA5-   B3          ???
1AA6-   BB          ???
1AA7-   A3          ???
1AA8-   B1 B0       LDA   ($B0),Y
1AAA-   8D A0 C4    STA   $C4A0
1AAD-   D5 CD       CMP   $CD,X
1AAF-   D0 A0       BNE   $1A51
1AB1-   A3          ???
1AB2-   C1 D2       CMP   ($D2,X)
1AB4-   D2 C1       CMP   ($C1)
1AB6-   D9 B2 AB    CMP   $ABB2,Y
1AB9-   B8          CLV
1ABA-   B3          ???
1ABB-   BB          ???
1ABC-   A3          ???
1ABD-   B1 B0       LDA   ($B0),Y
1ABF-   8D A0 C4    STA   $C4A0
1AC2-   D5 CD       CMP   $CD,X
1AC4-   D0 A0       BNE   $1A66
1AC6-   A3          ???
1AC7-   C1 D2       CMP   ($D2,X)
1AC9-   D2 C1       CMP   ($C1)
1ACB-   D9 B2 AB    CMP   $ABB2,Y
1ACE-   B9 B3 BB    LDA   $BBB3,Y
1AD1-   A3          ???
1AD2-   B1 B0       LDA   ($B0),Y
1AD4-   8D A0 DF    STA   $DFA0
1AD7-   D0 D2       BNE   $1AAB
1AD9-   CE D4 A0    DEC   $A0D4
1ADC-   A2 20       LDX   #$20
1ADE-   A2 AC       LDX   #$AC
1AE0-   B8          CLV
1AE1-   C4 B8       CPY   $B8
1AE3-   C4 8D       CPY   $8D
1AE5-   A0 DF       LDY   #$DF
1AE7-   D7          ???
1AE8-   C1 C9       CMP   ($C9,X)
1AEA-   D4          ???
1AEB-   8D AA 8D    STA   $8DAA
1AEE-   AA          TAX
1AEF-   AA          TAX
1AF0-   20 C6 C9    JSR   $C9C6
1AF3-   CE C1 CC    DEC   $CCC1
1AF6-   CC D9 AC    CPY   $ACD9
1AF9-   20 C7 C5    JSR   $C5C7
1AFC-   D4          ???
1AFD-   B8          CLV
1AFE-   B2 20       LDA   ($20)
1B00-   C7          ???
1B01-   C5 D4       CMP   $D4
1B03-   D3          ???
1B04-   20 D4 C8    JSR   $C8D4
1B07-   C5 20       CMP   $20
1B09-   D6 C1       DEC   $C1,X
1B0B-   CC D5 C5    CPY   $C5D5
1B0E-   20 C1 D4    JSR   $D4C1
1B11-   20 C1 20    JSR   $20C1
1B14-   C7          ???
1B15-   C9 D6       CMP   #$D6
1B17-   C5 CE       CMP   $CE
1B19-   20 D8 AC    JSR   $ACD8
1B1C-   D9 8D AA    CMP   $AA8D,Y
1B1F-   AA          TAX
1B20-   20 C9 CE    JSR   $CEC9
1B23-   C4 C5       CPY   $C5
1B25-   D8          CLD
1B26-   20 C1 CE    JSR   $CEC1
1B29-   C4 20       CPY   $20
1B2B-   D0 CC       BNE   $1AF9
1B2D-   C1 C3       CMP   ($C3,X)
1B2F-   C5 D3       CMP   $D3
1B31-   20 C9 D4    JSR   $D4C9
1B34-   20 C9 CE    JSR   $CEC9
1B37-   20 DB D2    JSR   $D2DB
1B3A-   C5 D4       CMP   $D4
1B3C-   D5 D2       CMP   $D2,X
1B3E-   CE DD 20    DEC   $20DD
1B41-   D7          ???
1B42-   C9 D4       CMP   #$D4
1B44-   C8          INY
1B45-   20 D4 C8    JSR   $C8D4
1B48-   C5 8D       CMP   $8D
1B4A-   AA          TAX
1B4B-   AA          TAX
1B4C-   20 C5 CC    JSR   $CCC5
1B4F-   C5 CD       CMP   $CD
1B51-   C5 CE       CMP   $CE
1B53-   D4          ???
1B54-   20 CC C5    JSR   $C5CC
1B57-   CE C7 D4    DEC   $D4C7
1B5A-   C8          INY
1B5B-   20 C9 CE    JSR   $CEC9
1B5E-   20 DB D2    JSR   $D2DB
1B61-   C5 D4       CMP   $D4
1B63-   CC C5 CE    CPY   $CEC5
1B66-   DD AE 8D    CMP   $8DAE,X
1B69-   AA          TAX
1B6A-   8D AA AA    STA   $AAAA
1B6D-   20 CD C1    JSR   $C1CD
1B70-   C3          ???
1B71-   D2 CF       CMP   ($CF)
1B73-   BA          TSX
1B74-   20 C7 C5    JSR   $C5C7
1B77-   D4          ???
1B78-   B8          CLV
1B79-   B2 20       LDA   ($20)
1B7B-   C1 D2       CMP   ($D2,X)
1B7D-   D2 C1       CMP   ($C1)
1B7F-   D9 DF C1    CMP   $C1DF,Y
1B82-   C4 C4       CPY   $C4
1B84-   D2 BB       CMP   ($BB)
1B86-   D8          CLD
1B87-   DF          ???
1B88-   C9 CE       CMP   #$CE
1B8A-   C4 C5       CPY   $C5
1B8C-   D8          CLD
1B8D-   BB          ???
1B8E-   D9 DF C9    CMP   $C9DF,Y
1B91-   CE C4 C5    DEC   $C5C4
1B94-   D8          CLD
1B95-   8D AA 8D    STA   $8DAA
1B98-   A0 DF       LDY   #$DF
1B9A-   D0 D2       BNE   $1B6E
1B9C-   CE D4 A0    DEC   $A0D4
1B9F-   A2 CC       LDX   #$CC
1BA1-   C9 CB       CMP   #$CB
1BA3-   C5 D7       CMP   $D7
1BA5-   C9 D3       CMP   #$D3
1BA7-   C5 AC       CMP   $AC
1BA9-   20 C7 C5    JSR   $C5C7
1BAC-   D4          ???
1BAD-   B8          CLV
1BAE-   B2 20       LDA   ($20)
1BB0-   C1 C3       CMP   ($C3,X)
1BB2-   D4          ???
1BB3-   D3          ???
1BB4-   20 CC C9    JSR   $C9CC
1BB7-   CB          ???
1BB8-   C5 20       CMP   $20
1BBA-   C7          ???
1BBB-   C5 D4       CMP   $D4
1BBD-   B8          CLV
1BBE-   B1 AC       LDA   ($AC),Y
1BC0-   A2 AC       LDX   #$AC
1BC2-   B8          CLV
1BC3-   C4 8D       CPY   $8D
1BC5-   A0 DF       LDY   #$DF
1BC7-   D0 D2       BNE   $1B9B
1BC9-   CE D4 A0    DEC   $A0D4
1BCC-   A2 C2       LDX   #$C2
1BCE-   D5 D4       CMP   $D4,X
1BD0-   20 C9 CE    JSR   $CEC9
1BD3-   20 D4 D7    JSR   $D7D4
1BD6-   CF          ???
1BD7-   20 C4 C9    JSR   $C9C4
1BDA-   CD C5 CE    CMP   $CEC5
1BDD-   D3          ???
1BDE-   C9 CF       CMP   #$CF
1BE0-   CE D3 AE    DEC   $AED3
1BE3-   20 A2 AC    JSR   $ACA2
1BE6-   B8          CLV
1BE7-   C4 B8       CPY   $B8
1BE9-   C4 8D       CPY   $8D
1BEB-   A0 DF       LDY   #$DF
1BED-   D0 D2       BNE   $1BC1
1BEF-   CE D4 A0    DEC   $A0D4
1BF2-   A2 D4       LDX   #$D4
1BF4-   C8          INY
1BF5-   D5 D3       CMP   $D3,X
1BF7-   BA          TSX
1BF8-   20 C7 C5    JSR   $C5C7
1BFB-   D4          ???
1BFC-   B8          CLV
1BFD-   B2 20       LDA   ($20)
1BFF-   C1 D2       CMP   ($D2,X)
1C01-   D2 C1       CMP   ($C1)
1C03-   D9 B2 BB    CMP   $BBB2,Y
1C06-   A3          ???
1C07-   B1 BB       LDA   ($BB),Y
1C09-   A3          ???
1C0A-   B5 20       LDA   $20,X
1C0C-   D2 C5       CMP   ($C5)
1C0E-   D4          ???
1C0F-   D5 D2       CMP   $D2,X
1C11-   CE D3 BA    DEC   $BAD3
1C14-   A2 AC       LDX   #$AC
1C16-   B8          CLV
1C17-   C4 B8       CPY   $B8
1C19-   C4 8D       CPY   $8D
1C1B-   A0 C7       LDY   #$C7
1C1D-   C5 D4       CMP   $D4
1C1F-   B8          CLV
1C20-   B2 A0       LDA   ($A0)
1C22-   A3          ???
1C23-   C1 D2       CMP   ($D2,X)
1C25-   D2 C1       CMP   ($C1)
1C27-   D9 B2 BB    CMP   $BBB2,Y
1C2A-   A3          ???
1C2B-   B1 BB       LDA   ($BB),Y
1C2D-   A3          ???
1C2E-   B0 B5       BCS   $1BE5
1C30-   8D A0 C4    STA   $C4A0
1C33-   D5 CD       CMP   $CD,X
1C35-   D0 A0       BNE   $1BD7
1C37-   A3          ???
1C38-   D2 C5       CMP   ($C5)
1C3A-   D4          ???
1C3B-   D5 D2       CMP   $D2,X
1C3D-   CE BB D2    DEC   $D2BB
1C40-   C5 D4       CMP   $D4
1C42-   CC C5 CE    CPY   $CEC5
1C45-   8D A0 DF    STA   $DFA0
1C48-   D7          ???
1C49-   C1 C9       CMP   ($C9,X)
1C4B-   D4          ???
1C4C-   8D AA 8D    STA   $8DAA
1C4F-   AA          TAX
1C50-   AA          TAX
1C51-   20 C4 C9    JSR   $C9C4
1C54-   CD B1 B6    CMP   $B6B1
1C57-   B1 20       LDA   ($20),Y
1C59-   C3          ???
1C5A-   D2 C5       CMP   ($C5)
1C5C-   C1 D4       CMP   ($D4,X)
1C5E-   C5 D3       CMP   $D3
1C60-   20 C1 20    JSR   $20C1
1C63-   B1 B6       LDA   ($B6),Y
1C65-   AD C2 C9    LDA   $C9C2
1C68-   D4          ???
1C69-   AC 20 B1    LDY   $B120
1C6C-   AD C4 C9    LDA   $C9C4
1C6F-   CD C5 CE    CMP   $CEC5
1C72-   D3          ???
1C73-   C9 CF       CMP   #$CF
1C75-   CE C1 CC    DEC   $CCC1
1C78-   20 C1 D2    JSR   $D2C1
1C7B-   D2 C1       CMP   ($C1)
1C7D-   D9 AE 8D    CMP   $8DAE,Y
1C80-   AA          TAX
1C81-   8D A0 DF    STA   $DFA0
1C84-   D0 D2       BNE   $1C58
1C86-   CE D4 A0    DEC   $A0D4
1C89-   A2 20       LDX   #$20
1C8B-   A2 AC       LDX   #$AC
1C8D-   B8          CLV
1C8E-   C4 B8       CPY   $B8
1C90-   C4 8D       CPY   $8D
1C92-   A0 DF       LDY   #$DF
1C94-   D0 D2       BNE   $1C68
1C96-   CE D4 A0    DEC   $A0D4
1C99-   A2 C4       LDX   #$C4
1C9B-   C9 CD       CMP   #$CD
1C9D-   B1 B6       LDA   ($B6),Y
1C9F-   B1 20       LDA   ($20),Y
1CA1-   C3          ???
1CA2-   D2 C5       CMP   ($C5)
1CA4-   C1 D4       CMP   ($D4,X)
1CA6-   C5 D3       CMP   $D3
1CA8-   20 C1 20    JSR   $20C1
1CAB-   B1 B6       LDA   ($B6),Y
1CAD-   AD C2 C9    LDA   $C9C2
1CB0-   D4          ???
1CB1-   AC 20 B1    LDY   $B120
1CB4-   C4 A2       CPY   $A2
1CB6-   AC B8 C4    LDY   $C4B8
1CB9-   8D A0 DF    STA   $DFA0
1CBC-   D0 D2       BNE   $1C90
1CBE-   CE D4 A0    DEC   $A0D4
1CC1-   A2 C1       LDX   #$C1
1CC3-   D2 D2       CMP   ($D2)
1CC5-   C1 D9       CMP   ($D9,X)
1CC7-   20 D7 C9    JSR   $C9D7
1CCA-   D4          ???
1CCB-   C8          INY
1CCC-   20 C1 20    JSR   $20C1
1CCF-   CD C1 D8    CMP   $D8C1
1CD2-   C9 CD       CMP   #$CD
1CD4-   D5 CD       CMP   $CD,X
1CD6-   20 C5 CC    JSR   $CCC5
1CD9-   C5 CD       CMP   $CD
1CDB-   C5 CE       CMP   $CE
1CDD-   D4          ???
1CDE-   A2 AC       LDX   #$AC
1CE0-   B8          CLV
1CE1-   C4 8D       CPY   $8D
1CE3-   A0 DF       LDY   #$DF
1CE5-   D0 D2       BNE   $1CB9
1CE7-   CE D4 A0    DEC   $A0D4
1CEA-   A2 CC       LDX   #$CC
1CEC-   C5 CE       CMP   $CE
1CEE-   C7          ???
1CEF-   D4          ???
1CF0-   C8          INY
1CF1-   20 CF C6    JSR   $C6CF
1CF4-   20 B1 20    JSR   $20B1
1CF7-   C2          ???
1CF8-   D9 D4 C5    CMP   $C5D4,Y
1CFB-   20 A8 B2    JSR   $B2A8
1CFE-   B5 B5       LDA   $B5,X
1D00-   A9 AE       LDA   #$AE
1D02-   A2 AC       LDX   #$AC
1D04-   B8          CLV
1D05-   C4 B8       CPY   $B8
1D07-   C4 8D       CPY   $8D
1D09-   A0 DF       LDY   #$DF
1D0B-   D0 D2       BNE   $1CDF
1D0D-   CE D4 A0    DEC   $A0D4
1D10-   A2 D3       LDX   #$D3
1D12-   CF          ???
1D13-   AC 20 C4    LDY   $C420
1D16-   C9 CD       CMP   #$CD
1D18-   B1 B6       LDA   ($B6),Y
1D1A-   B1 20       LDA   ($20),Y
1D1C-   C1 D2       CMP   ($D2,X)
1D1E-   D2 C1       CMP   ($C1)
1D20-   D9 B2 BB    CMP   $BBB2,Y
1D23-   A3          ???
1D24-   B3          ???
1D25-   B0 B0       BCS   $1CD7
1D27-   BB          ???
1D28-   A3          ???
1D29-   B1 BB       LDA   ($BB),Y
1D2B-   A3          ???
1D2C-   A4 B6       LDY   $B6
1D2E-   B6 A2       LDX   $A2,Y
1D30-   AC B8 C4    LDY   $C4B8
1D33-   8D A0 DF    STA   $DFA0
1D36-   D0 D2       BNE   $1D0A
1D38-   CE D4 A0    DEC   $A0D4
1D3B-   A2 D2       LDX   #$D2
1D3D-   C5 D4       CMP   $D4
1D3F-   D5 D2       CMP   $D2,X
1D41-   CE D3 BA    DEC   $BAD3
1D44-   A2 AC       LDX   #$AC
1D46-   B8          CLV
1D47-   C4 B8       CPY   $B8
1D49-   C4 8D       CPY   $8D
1D4B-   A0 C4       LDY   #$C4
1D4D-   C9 CD       CMP   #$CD
1D4F-   B1 B6       LDA   ($B6),Y
1D51-   B1 A0       LDA   ($A0),Y
1D53-   A3          ???
1D54-   C1 D2       CMP   ($D2,X)
1D56-   D2 C1       CMP   ($C1)
1D58-   D9 B2 BB    CMP   $BBB2,Y
1D5B-   A3          ???
1D5C-   B3          ???
1D5D-   B0 B0       BCS   $1D0F
1D5F-   BB          ???
1D60-   A3          ???
1D61-   B1 BB       LDA   ($BB),Y
1D63-   A3          ???
1D64-   A4 B6       LDY   $B6
1D66-   B6 8D       LDX   $8D,Y
1D68-   A0 C4       LDY   #$C4
1D6A-   D5 CD       CMP   $CD,X
1D6C-   D0 A0       BNE   $1D0E
1D6E-   A3          ???
1D6F-   C1 D2       CMP   ($D2,X)
1D71-   D2 C1       CMP   ($C1)
1D73-   D9 B2 BB    CMP   $BBB2,Y
1D76-   A3          ???
1D77-   B2 B5       LDA   ($B5)
1D79-   B5 8D       LDA   $8D,X
1D7B-   A0 DF       LDY   #$DF
1D7D-   D7          ???
1D7E-   C1 C9       CMP   ($C9,X)
1D80-   D4          ???
1D81-   8D A0 CC    STA   $CCA0
1D84-   C4 C1       CPY   $C1
1D86-   A0 A3       LDY   #$A3
1D88-   A4 B0       LDY   $B0
1D8A-   C6 8D       DEC   $8D
1D8C-   A0 D3       LDY   #$D3
1D8E-   D4          ???
1D8F-   C1 A0       CMP   ($A0,X)
1D91-   A4 B3       LDY   $B3
1D93-   B0 B0       BCS   $1D45
1D95-   8D A0 CC    STA   $CCA0
1D98-   C4 C1       CPY   $C1
1D9A-   A0 A3       LDY   #$A3
1D9C-   A4 B0       LDY   $B0
1D9E-   C6 8D       DEC   $8D
1DA0-   A0 D3       LDY   #$D3
1DA2-   D4          ???
1DA3-   C1 A0       CMP   ($A0,X)
1DA5-   A4 B3       LDY   $B3
1DA7-   B0 B1       BCS   $1D5A
1DA9-   8D A0 DF    STA   $DFA0
1DAC-   D0 D2       BNE   $1D80
1DAE-   CE D4 20    DEC   $20D4
1DB1-   A2 20       LDX   #$20
1DB3-   A2 AC       LDX   #$AC
1DB5-   B8          CLV
1DB6-   C4 B8       CPY   $B8
1DB8-   C4 8D       CPY   $8D
1DBA-   A0 D0       LDY   #$D0
1DBC-   D5 D4       CMP   $D4,X
1DBE-   B1 B6       LDA   ($B6),Y
1DC0-   B1 20       LDA   ($20),Y
1DC2-   A3          ???
1DC3-   A4 B3       LDY   $B3
1DC5-   B0 B0       BCS   $1D77
1DC7-   BB          ???
1DC8-   A3          ???
1DC9-   C1 D2       CMP   ($D2,X)
1DCB-   D2 C1       CMP   ($C1)
1DCD-   D9 B2 BB    CMP   $BBB2,Y
1DD0-   A3          ???
1DD1-   B3          ???
1DD2-   B0 B0       BCS   $1D84
1DD4-   8D A0 DF    STA   $DFA0
1DD7-   D0 D2       BNE   $1DAB
1DD9-   CE D4 A0    DEC   $A0D4
1DDC-   A2 20       LDX   #$20
1DDE-   A2 AC       LDX   #$AC
1DE0-   B8          CLV
1DE1-   C4 B8       CPY   $B8
1DE3-   C4 8D       CPY   $8D
1DE5-   A0 DF       LDY   #$DF
1DE7-   D0 D2       BNE   $1DBB
1DE9-   CE D4 A0    DEC   $A0D4
1DEC-   A2 D0       LDX   #$D0
1DEE-   D5 D4       CMP   $D4,X
1DF0-   B1 B6       LDA   ($B6),Y
1DF2-   B1 20       LDA   ($20),Y
1DF4-   D0 D5       BNE   $1DCB
1DF6-   D4          ???
1DF7-   D3          ???
1DF8-   20 C1 20    JSR   $20C1
1DFB-   D6 C1       DEC   $C1,X
1DFD-   CC D5 C5    CPY   $C5D5
1E00-   20 D0 D2    JSR   $D2D0
1E03-   CF          ???
1E04-   D6 C9       DEC   $C9,X
1E06-   C4 C5       CPY   $C5
1E08-   C4 A2       CPY   $A2
1E0A-   AC B8 C4    LDY   $C4B8
1E0D-   8D A0 DF    STA   $DFA0
1E10-   D0 D2       BNE   $1DE4
1E12-   CE D4 A0    DEC   $A0D4
1E15-   A2 C1       LDX   #$C1
1E17-   D4          ???
1E18-   20 C1 20    JSR   $20C1
1E1B-   C7          ???
1E1C-   C9 D6       CMP   #$D6
1E1E-   C5 CE       CMP   $CE
1E20-   20 CD C5    JSR   $C5CD
1E23-   CD CF D2    CMP   $D2CF
1E26-   D9 20 C1    CMP   $C120,Y
1E29-   C4 C4       CPY   $C4
1E2B-   D2 C5       CMP   ($C5)
1E2D-   D3          ???
1E2E-   D3          ???
1E2F-   A2 AC       LDX   #$AC
1E31-   B8          CLV
1E32-   C4 8D       CPY   $8D
1E34-   A0 DF       LDY   #$DF
1E36-   D0 D2       BNE   $1E0A
1E38-   CE D4 A0    DEC   $A0D4
1E3B-   A2 C9       LDX   #$C9
1E3D-   CE D4 CF    DEC   $CFD4
1E40-   20 D4 C8    JSR   $C8D4
1E43-   C5 20       CMP   $20
1E45-   D3          ???
1E46-   D0 C5       BNE   $1E0D
1E48-   C3          ???
1E49-   C9 C6       CMP   #$C6
1E4B-   C9 C5       CMP   #$C5
1E4D-   C4 20       CPY   $20
1E4F-   B1 B6       LDA   ($B6),Y
1E51-   AD C2 C9    LDA   $C9C2
1E54-   D4          ???
1E55-   A2 AC       LDX   #$AC
1E57-   B8          CLV
1E58-   C4 8D       CPY   $8D
1E5A-   A0 DF       LDY   #$DF
1E5C-   D0 D2       BNE   $1E30
1E5E-   CE D4 A0    DEC   $A0D4
1E61-   A2 C1       LDX   #$C1
1E63-   D2 D2       CMP   ($D2)
1E65-   C1 D9       CMP   ($D9,X)
1E67-   20 C1 D4    JSR   $D4C1
1E6A-   20 D4 C8    JSR   $C8D4
1E6D-   C5 20       CMP   $20
1E6F-   C7          ???
1E70-   C9 D6       CMP   #$D6
1E72-   C5 CE       CMP   $CE
1E74-   20 C9 CE    JSR   $CEC9
1E77-   C4 C5       CPY   $C5
1E79-   D8          CLD
1E7A-   AE A2 AC    LDX   $ACA2
1E7D-   B8          CLV
1E7E-   C4 B8       CPY   $B8
1E80-   C4 8D       CPY   $8D
1E82-   A0 DF       LDY   #$DF
1E84-   D0 D2       BNE   $1E58
1E86-   CE D4 A0    DEC   $A0D4
1E89-   A2 D0       LDX   #$D0
1E8B-   D5 D4       CMP   $D4,X
1E8D-   B1 B6       LDA   ($B6),Y
1E8F-   B1 20       LDA   ($20),Y
1E91-   A4 B3       LDY   $B3
1E93-   B0 B0       BCS   $1E45
1E95-   BB          ???
1E96-   C1 D2       CMP   ($D2,X)
1E98-   D2 C1       CMP   ($C1)
1E9A-   D9 B2 BB    CMP   $BBB2,Y
1E9D-   A3          ???
1E9E-   B3          ???
1E9F-   B0 B0       BCS   $1E51
1EA1-   20 D2 C5    JSR   $C5D2
1EA4-   D4          ???
1EA5-   D5 D2       CMP   $D2,X
1EA7-   CE D3 BA    DEC   $BAD3
1EAA-   A2 AC       LDX   #$AC
1EAC-   B8          CLV
1EAD-   C4 B8       CPY   $B8
1EAF-   C4 8D       CPY   $8D
1EB1-   A0 C4       LDY   #$C4
1EB3-   D5 CD       CMP   $CD,X
1EB5-   D0 20       BNE   $1ED7
1EB7-   A3          ???
1EB8-   C1 D2       CMP   ($D2,X)
1EBA-   D2 C1       CMP   ($C1)
1EBC-   D9 B2 BB    CMP   $BBB2,Y
1EBF-   A3          ???
1EC0-   B2 B5       LDA   ($B5)
1EC2-   B5 8D       LDA   $8D,X
1EC4-   A0 C4       LDY   #$C4
1EC6-   D5 CD       CMP   $CD,X
1EC8-   D0 A0       BNE   $1E6A
1ECA-   A3          ???
1ECB-   C1 D2       CMP   ($D2,X)
1ECD-   D2 C1       CMP   ($C1)
1ECF-   D9 B2 AB    CMP   $ABB2,Y
1ED2-   B2 B5       LDA   ($B5)
1ED4-   B5 BB       LDA   $BB,X
1ED6-   A3          ???
1ED7-   B5 B0       LDA   $B0,X
1ED9-   8D A0 DF    STA   $DFA0
1EDC-   D7          ???
1EDD-   C1 C9       CMP   ($C9,X)
1EDF-   D4          ???
1EE0-   8D AA 8D    STA   $8DAA
1EE3-   A0 DF       LDY   #$DF
1EE5-   D0 D2       BNE   $1EB9
1EE7-   CE D4 A0    DEC   $A0D4
1EEA-   A2 20       LDX   #$20
1EEC-   A2 AC       LDX   #$AC
1EEE-   B8          CLV
1EEF-   C4 B8       CPY   $B8
1EF1-   C4 8D       CPY   $8D
1EF3-   A0 DF       LDY   #$DF
1EF5-   D0 D2       BNE   $1EC9
1EF7-   CE D4 A0    DEC   $A0D4
1EFA-   A2 C1       LDX   #$C1
1EFC-   CE C4 20    DEC   $20C4
1EFF-   C7          ???
1F00-   C5 D4       CMP   $D4
1F02-   B1 B6       LDA   ($B6),Y
1F04-   B1 AC       LDA   ($AC),Y
1F06-   20 C5 D8    JSR   $D8C5
1F09-   D0 C5       BNE   $1ED0
1F0B-   C3          ???
1F0C-   D4          ???
1F0D-   C5 C4       CMP   $C4
1F0F-   CC D9 AC    CPY   $ACD9
1F12-   20 C7 C5    JSR   $C5C7
1F15-   D4          ???
1F16-   D3          ???
1F17-   20 D4 C8    JSR   $C8D4
1F1A-   C5 20       CMP   $20
1F1C-   A2 AC       LDX   #$AC
1F1E-   B8          CLV
1F1F-   C4 8D       CPY   $8D
1F21-   A0 DF       LDY   #$DF
1F23-   D0 D2       BNE   $1EF7
1F25-   CE D4 A0    DEC   $A0D4
1F28-   A2 D6       LDX   #$D6
1F2A-   C1 CC       CMP   ($CC,X)
1F2C-   D5 C5       CMP   $C5,X
1F2E-   20 D3 D4    JSR   $D4D3
1F31-   CF          ???
1F32-   D2 C5       CMP   ($C5)
1F34-   C4 20       CPY   $20
1F36-   C9 CE       CMP   #$CE
1F38-   20 C1 CE    JSR   $CEC1
1F3B-   20 C1 D2    JSR   $D2C1
1F3E-   D2 C1       CMP   ($C1)
1F40-   D9 20 C1    CMP   $C120,Y
1F43-   D4          ???
1F44-   A2 AC       LDX   #$AC
1F46-   B8          CLV
1F47-   C4 8D       CPY   $8D
1F49-   A0 DF       LDY   #$DF
1F4B-   D0 D2       BNE   $1F1F
1F4D-   CE D4 A0    DEC   $A0D4
1F50-   A2 D4       LDX   #$D4
1F52-   C8          INY
1F53-   C5 20       CMP   $20
1F55-   C7          ???
1F56-   C9 D6       CMP   #$D6
1F58-   C5 CE       CMP   $CE
1F5A-   20 C5 CC    JSR   $CCC5
1F5D-   C5 CD       CMP   $CD
1F5F-   C5 CE       CMP   $CE
1F61-   D4          ???
1F62-   AE A2 AC    LDX   $ACA2
1F65-   B8          CLV
1F66-   C4 B8       CPY   $B8
1F68-   C4 8D       CPY   $8D
1F6A-   A0 DF       LDY   #$DF
1F6C-   D0 D2       BNE   $1F40
1F6E-   CE D4 A0    DEC   $A0D4
1F71-   A2 D3       LDX   #$D3
1F73-   CF          ???
1F74-   AC 20 C7    LDY   $C720
1F77-   C5 D4       CMP   $D4
1F79-   B8          CLV
1F7A-   B1 20       LDA   ($20),Y
1F7C-   C1 D2       CMP   ($D2,X)
1F7E-   D2 C1       CMP   ($C1)
1F80-   D9 B2 BB    CMP   $BBB2,Y
1F83-   A3          ???
1F84-   B3          ???
1F85-   B0 B0       BCS   $1F37
1F87-   20 D2 C5    JSR   $C5D2
1F8A-   D4          ???
1F8B-   D5 D2       CMP   $D2,X
1F8D-   CE D3 BA    DEC   $BAD3
1F90-   A2 AC       LDX   #$AC
1F92-   B8          CLV
1F93-   C4 B8       CPY   $B8
1F95-   C4 8D       CPY   $8D
1F97-   8D A0 C7    STA   $C7A0
1F9A-   C5 D4       CMP   $D4
1F9C-   B1 B6       LDA   ($B6),Y
1F9E-   B1 A0       LDA   ($A0),Y
1FA0-   A3          ???
1FA1-   C1 D2       CMP   ($D2,X)
1FA3-   D2 C1       CMP   ($C1)
1FA5-   D9 B2 BB    CMP   $BBB2,Y
1FA8-   A3          ???
1FA9-   B3          ???
1FAA-   B0 B0       BCS   $1F5C
1FAC-   8D A0 DF    STA   $DFA0
1FAF-   D0 D2       BNE   $1F83
1FB1-   CE D4 A0    DEC   $A0D4
1FB4-   A2 20       LDX   #$20
1FB6-   A2 AC       LDX   #$AC
1FB8-   B8          CLV
1FB9-   C4 B8       CPY   $B8
1FBB-   C4 8D       CPY   $8D
1FBD-   A0 C4       LDY   #$C4
1FBF-   D5 CD       CMP   $CD,X
1FC1-   D0 A0       BNE   $1F63
1FC3-   A3          ???
1FC4-   D2 C5       CMP   ($C5)
1FC6-   D4          ???
1FC7-   D5 D2       CMP   $D2,X
1FC9-   CE BB D2    DEC   $D2BB
1FCC-   C5 D4       CMP   $D4
1FCE-   CC C5 CE    CPY   $CEC5
1FD1-   8D AA 8D    STA   $8DAA
1FD4-   A0 DF       LDY   #$DF
1FD6-   D7          ???
1FD7-   C1 C9       CMP   ($C9,X)
1FD9-   D4          ???
1FDA-   8D AA 8D    STA   $8DAA
1FDD-   AA          TAX
1FDE-   AA          TAX
1FDF-   20 B1 B6    JSR   $B6B1
1FE2-   AD C2 C9    LDA   $C9C2
1FE5-   D4          ???
1FE6-   AC 20 B2    LDY   $B220
1FE9-   C4 20       CPY   $20
1FEB-   C1 D2       CMP   ($D2,X)
1FED-   D2 C1       CMP   ($C1)
1FEF-   D9 D3 8D    CMP   $8DD3,Y
1FF2-   AA          TAX
1FF3-   8D AA AA    STA   $AAAA
1FF6-   20 C1 C4    JSR   $C4C1
1FF9-   C9 CD       CMP   #$CD
1FFB-   B1 B6       LDA   ($B6),Y
1FFD-   B2 20       LDA   ($20)
1FFF-   C3          ???
2000-   D2 C5       CMP   ($C5)
2002-   C1 D4       CMP   ($D4,X)
2004-   C5 D3       CMP   $D3
2006-   20 C1 20    JSR   $20C1
2009-   B2 C4       LDA   ($C4)
200B-   20 C1 D2    JSR   $D2C1
200E-   D2 C1       CMP   ($C1)
2010-   D9 20 D7    CMP   $D720,Y
2013-   C9 D4       CMP   #$D4
2015-   C8          INY
2016-   20 C5 CC    JSR   $CCC5
2019-   C5 CD       CMP   $CD
201B-   C5 CE       CMP   $CE
201D-   D4          ???
201E-   D3          ???
201F-   8D AA AA    STA   $AAAA
2022-   20 CF C6    JSR   $C6CF
2025-   20 CE A8    JSR   $A8CE
2028-   C2          ???
2029-   D9 D4 C5    CMP   $C5D4,Y
202C-   A9 20       LDA   #$20
202E-   CC C5 CE    CPY   $CEC5
2031-   C7          ???
2032-   D4          ???
2033-   C8          INY
2034-   AE 20 C9    LDX   $C920
2037-   C6 20       DEC   $20
2039-   D8          CLD
203A-   20 AA 20    JSR   $20AA
203D-   D9 20 AB    CMP   $AB20,Y
2040-   20 B5 20    JSR   $20B5
2043-   BE 20 A3    LDX   $A320,Y
2046-   A4 C6       LDY   $C6
2048-   C6 C6       DEC   $C6
204A-   C6 AC       DEC   $AC
204C-   8D AA AA    STA   $AAAA
204F-   20 C5 D2    JSR   $D2C5
2052-   D2 CF       CMP   ($CF)
2054-   D2 20       CMP   ($20)
2056-   C9 D3       CMP   #$D3
2058-   20 D2 C5    JSR   $C5D2
205B-   D4          ???
205C-   D5 D2       CMP   $D2,X
205E-   CE C5 C4    DEC   $C4C5
2061-   AE 8D AA    LDX   $AA8D
2064-   8D A0 C4    STA   $C4A0
2067-   C9 CD       CMP   #$CD
2069-   B1 B6       LDA   ($B6),Y
206B-   B2 A0       LDA   ($A0)
206D-   A3          ???
206E-   C1 D2       CMP   ($D2,X)
2070-   D2 C1       CMP   ($C1)
2072-   D9 B2 BB    CMP   $BBB2,Y
2075-   A3          ???
2076-   B3          ???
2077-   B0 B0       BCS   $2029
2079-   BB          ???
207A-   A3          ???
207B-   B2 BB       LDA   ($BB)
207D-   A3          ???
207E-   B1 BB       LDA   ($BB),Y
2080-   A3          ???
2081-   A4 B3       LDY   $B3
2083-   C6 8D       DEC   $8D
2085-   A0 DF       LDY   #$DF
2087-   D0 D2       BNE   $205B
2089-   CE D4 A0    DEC   $A0D4
208C-   A2 20       LDX   #$20
208E-   A2 AC       LDX   #$AC
2090-   B8          CLV
2091-   C4 B8       CPY   $B8
2093-   C4 8D       CPY   $8D
2095-   A0 DF       LDY   #$DF
2097-   D0 D2       BNE   $206B
2099-   CE D4 A0    DEC   $A0D4
209C-   A2 D4       LDX   #$D4
209E-   C8          INY
209F-   C5 20       CMP   $20
20A1-   C4 C9       CPY   $C9
20A3-   CD B1 B6    CMP   $B6B1
20A6-   B2 20       LDA   ($20)
20A8-   CD C1 C3    CMP   $C3C1
20AB-   D2 CF       CMP   ($CF)
20AD-   20 C3 D2    JSR   $D2C3
20B0-   C5 C1       CMP   $C1
20B2-   D4          ???
20B3-   C5 D3       CMP   $D3
20B5-   20 C1 A2    JSR   $A2C1
20B8-   AC B8 C4    LDY   $C4B8
20BB-   8D A0 DF    STA   $DFA0
20BE-   D0 D2       BNE   $2092
20C0-   CE D4 A0    DEC   $A0D4
20C3-   A2 D4       LDX   #$D4
20C5-   D7          ???
20C6-   CF          ???
20C7-   20 C4 C9    JSR   $C9C4
20CA-   CD C5 CE    CMP   $CEC5
20CD-   D3          ???
20CE-   C9 CF       CMP   #$CF
20D0-   CE C1 CC    DEC   $CCC1
20D3-   AC 20 B1    LDY   $B120
20D6-   B6 AD       LDX   $AD,Y
20D8-   C2          ???
20D9-   C9 D4       CMP   #$D4
20DB-   20 C1 D2    JSR   $D2C1
20DE-   D2 C1       CMP   ($C1)
20E0-   D9 A2 AC    CMP   $ACA2,Y
20E3-   B8          CLV
20E4-   C4 8D       CPY   $8D
20E6-   A0 DF       LDY   #$DF
20E8-   D0 D2       BNE   $20BC
20EA-   CE D4 A0    DEC   $A0D4
20ED-   A2 D7       LDX   #$D7
20EF-   C9 D4       CMP   #$D4
20F1-   C8          INY
20F2-   20 D4 C8    JSR   $C8D4
20F5-   C5 20       CMP   $20
20F7-   D3          ???
20F8-   D0 C5       BNE   $20BF
20FA-   C3          ???
20FB-   C9 C6       CMP   #$C6
20FD-   C9 C5       CMP   #$C5
20FF-   C4 20       CPY   $20
2101-   D2 CF       CMP   ($CF)
2103-   D7          ???
2104-   D3          ???
2105-   20 C1 CE    JSR   $CEC1
2108-   C4 A2       CPY   $A2
210A-   AC B8 C4    LDY   $C4B8
210D-   8D A0 DF    STA   $DFA0
2110-   D0 D2       BNE   $20E4
2112-   CE D4 A0    DEC   $A0D4
2115-   A2 C3       LDX   #$C3
2117-   CF          ???
2118-   CC D5 CD    CPY   $CDD5
211B-   CE D3 20    DEC   $20D3
211E-   C1 CE       CMP   ($CE,X)
2120-   C4 20       CPY   $20
2122-   C5 CC       CMP   $CC
2124-   C5 CD       CMP   $CD
2126-   C5 CE       CMP   $CE
2128-   D4          ???
2129-   20 CC C5    JSR   $C5CC
212C-   CE C7 D4    DEC   $D4C7
212F-   C8          INY
2130-   AE A2 AC    LDX   $ACA2
2133-   B8          CLV
2134-   C4 B8       CPY   $B8
2136-   C4 8D       CPY   $8D
2138-   A0 DF       LDY   #$DF
213A-   D0 D2       BNE   $210E
213C-   CE D4 A0    DEC   $A0D4
213F-   A2 D3       LDX   #$D3
2141-   CF          ???
2142-   20 C4 C9    JSR   $C9C4
2145-   CD B1 B6    CMP   $B6B1
2148-   B2 20       LDA   ($20)
214A-   C1 D2       CMP   ($D2,X)
214C-   D2 C1       CMP   ($C1)
214E-   D9 B2 BB    CMP   $BBB2,Y
2151-   A3          ???
2152-   B3          ???
2153-   B0 B0       BCS   $2105
2155-   BB          ???
2156-   A3          ???
2157-   B2 BB       LDA   ($BB)
2159-   A3          ???
215A-   B1 BB       LDA   ($BB),Y
215C-   A3          ???
215D-   A4 B3       LDY   $B3
215F-   C6 A2       DEC   $A2
2161-   AC B8 C4    LDY   $C4B8
2164-   8D A0 DF    STA   $DFA0
2167-   D0 D2       BNE   $213B
2169-   CE D4 A0    DEC   $A0D4
216C-   A2 D2       LDX   #$D2
216E-   C5 D4       CMP   $D4
2170-   D5 D2       CMP   $D2,X
2172-   CE D3 BA    DEC   $BAD3
2175-   20 A2 AC    JSR   $ACA2
2178-   B8          CLV
2179-   C4 B8       CPY   $B8
217B-   C4 8D       CPY   $8D
217D-   A0 DF       LDY   #$DF
217F-   D7          ???
2180-   C1 C9       CMP   ($C9,X)
2182-   D4          ???
2183-   8D A0 C4    STA   $C4A0
2186-   D5 CD       CMP   $CD,X
2188-   D0 A0       BNE   $212A
218A-   A3          ???
218B-   C1 D2       CMP   ($D2,X)
218D-   D2 C1       CMP   ($C1)
218F-   D9 B2 BB    CMP   $BBB2,Y
2192-   A3          ???
2193-   B2 B0       LDA   ($B0)
2195-   B0 8D       BCS   $2124
2197-   A0 C4       LDY   #$C4
2199-   D5 CD       CMP   $CD,X
219B-   D0 A0       BNE   $213D
219D-   A3          ???
219E-   C1 D2       CMP   ($D2,X)
21A0-   D2 C1       CMP   ($C1)
21A2-   D9 B2 AB    CMP   $ABB2,Y
21A5-   B2 B0       LDA   ($B0)
21A7-   B0 BB       BCS   $2164
21A9-   A3          ???
21AA-   B2 B0       LDA   ($B0)
21AC-   B0 8D       BCS   $213B
21AE-   A0 DF       LDY   #$DF
21B0-   D7          ???
21B1-   C1 C9       CMP   ($C9,X)
21B3-   D4          ???
21B4-   8D A0 C4    STA   $C4A0
21B7-   D5 CD       CMP   $CD,X
21B9-   D0 A0       BNE   $215B
21BB-   A3          ???
21BC-   C1 D2       CMP   ($D2,X)
21BE-   D2 C1       CMP   ($C1)
21C0-   D9 B2 AB    CMP   $ABB2,Y
21C3-   B4 B0       LDY   $B0,X
21C5-   B0 BB       BCS   $2182
21C7-   A3          ???
21C8-   B2 B0       LDA   ($B0)
21CA-   B0 8D       BCS   $2159
21CC-   A0 C4       LDY   #$C4
21CE-   D5 CD       CMP   $CD,X
21D0-   D0 A0       BNE   $2172
21D2-   A3          ???
21D3-   C1 D2       CMP   ($D2,X)
21D5-   D2 C1       CMP   ($C1)
21D7-   D9 B2 AB    CMP   $ABB2,Y
21DA-   B6 B0       LDX   $B0,Y
21DC-   B0 BB       BCS   $2199
21DE-   A3          ???
21DF-   B1 B0       LDA   ($B0),Y
21E1-   8D A0 DF    STA   $DFA0
21E4-   D7          ???
21E5-   C1 C9       CMP   ($C9,X)
21E7-   D4          ???
21E8-   8D AA 8D    STA   $8DAA
21EB-   AA          TAX
21EC-   AA          TAX
21ED-   20 D0 D5    JSR   $D5D0
21F0-   D4          ???
21F1-   B1 B6       LDA   ($B6),Y
21F3-   B2 8D       LDA   ($8D)
21F5-   AA          TAX
21F6-   8D A0 DF    STA   $DFA0
21F9-   D0 D2       BNE   $21CD
21FB-   CE D4 A0    DEC   $A0D4
21FE-   A2 20       LDX   #$20
2200-   A2 AC       LDX   #$AC
2202-   B8          CLV
2203-   C4 B8       CPY   $B8
2205-   C4 B8       CPY   $B8
2207-   C4 B8       CPY   $B8
2209-   C4 8D       CPY   $8D
220B-   A0 DF       LDY   #$DF
220D-   D0 D2       BNE   $21E1
220F-   CE D4 A0    DEC   $A0D4
2212-   A2 CC       LDX   #$CC
2214-   C9 CB       CMP   #$CB
2216-   C5 20       CMP   $20
2218-   CD C1 C3    CMP   $C3C1
221B-   D2 CF       CMP   ($CF)
221D-   D3          ???
221E-   20 C1 C2    JSR   $C2C1
2221-   CF          ???
2222-   D6 C5       DEC   $C5,X
2224-   AC 20 D0    LDY   $D020
2227-   D5 D4       CMP   $D4,X
2229-   B1 B6       LDA   ($B6),Y
222B-   B2 A2       LDA   ($A2)
222D-   AC B8 C4    LDY   $C4B8
2230-   8D A0 DF    STA   $DFA0
2233-   D0 D2       BNE   $2207
2235-   CE D4 A0    DEC   $A0D4
2238-   A2 D0       LDX   #$D0
223A-   D5 D4       CMP   $D4,X
223C-   D3          ???
223D-   20 C1 20    JSR   $20C1
2240-   C7          ???
2241-   C9 D6       CMP   #$D6
2243-   C5 CE       CMP   $CE
2245-   20 D6 C1    JSR   $C1D6
2248-   CC D5 C5    CPY   $C5D5
224B-   20 C9 CE    JSR   $CEC9
224E-   D4          ???
224F-   CF          ???
2250-   20 D4 C8    JSR   $C8D4
2253-   C5 20       CMP   $20
2255-   A2 AC       LDX   #$AC
2257-   B8          CLV
2258-   C4 8D       CPY   $8D
225A-   A0 DF       LDY   #$DF
225C-   D0 D2       BNE   $2230
225E-   CE D4 A0    DEC   $A0D4
2261-   A2 D3       LDX   #$D3
2263-   D0 C5       BNE   $222A
2265-   C3          ???
2266-   C9 C6       CMP   #$C6
2268-   C9 C5       CMP   #$C5
226A-   C4 20       CPY   $20
226C-   C9 CE       CMP   #$CE
226E-   C4 C5       CPY   $C5
2270-   D8          CLD
2271-   20 CF C6    JSR   $C6CF
2274-   20 C1 20    JSR   $20C1
2277-   B1 B6       LDA   ($B6),Y
2279-   C2          ???
227A-   C9 D4       CMP   #$D4
227C-   AC 20 B3    LDY   $B320
227F-   C4 20       CPY   $20
2281-   C1 D2       CMP   ($D2,X)
2283-   D2 C1       CMP   ($C1)
2285-   D9 AE A2    CMP   $A2AE,Y
2288-   AC B8 C4    LDY   $C4B8
228B-   B8          CLV
228C-   C4 8D       CPY   $8D
228E-   A0 DF       LDY   #$DF
2290-   D0 D2       BNE   $2264
2292-   CE D4 A0    DEC   $A0D4
2295-   A2 D4       LDX   #$D4
2297-   C8          INY
2298-   C5 20       CMP   $20
229A-   C6 CF       DEC   $CF
229C-   CC CC CF    CPY   $CFCC
229F-   D7          ???
22A0-   C9 CE       CMP   #$CE
22A2-   C7          ???
22A3-   20 CC CF    JSR   $CFCC
22A6-   CF          ???
22A7-   D0 D3       BNE   $227C
22A9-   20 D4 C8    JSR   $C8D4
22AC-   D2 CF       CMP   ($CF)
22AE-   D5 C7       CMP   $C7,X
22B0-   C8          INY
22B1-   20 D8 20    JSR   $20D8
22B4-   C1 CE       CMP   ($CE,X)
22B6-   C4 20       CPY   $20
22B8-   D9 AC A2    CMP   $A2AC,Y
22BB-   AC B8 C4    LDY   $C4B8
22BE-   8D A0 DF    STA   $DFA0
22C1-   D0 D2       BNE   $2295
22C3-   CE D4 A0    DEC   $A0D4
22C6-   A2 C6       LDX   #$C6
22C8-   C9 CC       CMP   #$CC
22CA-   CC C9 CE    CPY   $CEC9
22CD-   C7          ???
22CE-   20 D4 C8    JSR   $C8D4
22D1-   C5 20       CMP   $20
22D3-   C1 D2       CMP   ($D2,X)
22D5-   D2 C1       CMP   ($C1)
22D7-   D9 D3 20    CMP   $20D3,Y
22DA-   D7          ???
22DB-   C9 D4       CMP   #$D4
22DD-   C8          INY
22DE-   20 B0 AD    JSR   $ADB0
22E1-   B3          ???
22E2-   B0 B0       BCS   $2294
22E4-   20 C9 CE    JSR   $CEC9
22E7-   20 C5 C1    JSR   $C1C5
22EA-   C3          ???
22EB-   C8          INY
22EC-   20 D2 CF    JSR   $CFD2
22EF-   D7          ???
22F0-   AE A2 AC    LDX   $ACA2
22F3-   B8          CLV
22F4-   C4 B8       CPY   $B8
22F6-   C4 8D       CPY   $8D
22F8-   A0 DF       LDY   #$DF
22FA-   D7          ???
22FB-   C1 C9       CMP   ($C9,X)
22FD-   D4          ???
22FE-   8D AA 8D    STA   $8DAA
2301-   A0 CC       LDY   #$CC
2303-   C4 C1       CPY   $C1
2305-   A0 A3       LDY   #$A3
2307-   B0 8D       BCS   $2296
2309-   A0 D3       LDY   #$D3
230B-   D4          ???
230C-   C1 A0       CMP   ($A0,X)
230E-   D8          CLD
230F-   C3          ???
2310-   CE D4 8D    DEC   $8DD4
2313-   A0 D3       LDY   #$D3
2315-   D4          ???
2316-   C1 A0       CMP   ($A0,X)
2318-   D9 C3 CE    CMP   $CEC3,Y
231B-   D4          ???
231C-   8D A0 D3    STA   $D3A0
231F-   D4          ???
2320-   C1 A0       CMP   ($A0,X)
2322-   D8          CLD
2323-   C3          ???
2324-   CE D4 AB    DEC   $ABD4
2327-   B1 8D       LDA   ($8D),Y
2329-   A0 D3       LDY   #$D3
232B-   D4          ???
232C-   C1 A0       CMP   ($A0,X)
232E-   D9 C3 CE    CMP   $CEC3,Y
2331-   D4          ???
2332-   AB          ???
2333-   B1 8D       LDA   ($8D),Y
2335-   AA          TAX
2336-   8D D3 D4    STA   $D4D3
2339-   C1 D2       CMP   ($D2,X)
233B-   D4          ???
233C-   CC D0 8D    CPY   $8DD0
233F-   A0 D0       LDY   #$D0
2341-   D5 D4       CMP   $D4,X
2343-   B1 B6       LDA   ($B6),Y
2345-   B2 A0       LDA   ($A0)
2347-   A3          ???
2348-   D8          CLD
2349-   C3          ???
234A-   CE D4 BB    DEC   $BBD4
234D-   A3          ???
234E-   C1 D2       CMP   ($D2,X)
2350-   D2 C1       CMP   ($C1)
2352-   D9 B2 BB    CMP   $BBB2,Y
2355-   D8          CLD
2356-   C3          ???
2357-   CE D4 BB    DEC   $BBD4
235A-   D9 C3 CE    CMP   $CEC3,Y
235D-   D4          ???
235E-   8D A0 C3    STA   $C3A0
2361-   CC C3 8D    CPY   $8DC3
2364-   A0 CC       LDY   #$CC
2366-   C4 C1       CPY   $C1
2368-   A0 D8       LDY   #$D8
236A-   C3          ???
236B-   CE D4 8D    DEC   $8DD4
236E-   A0 C1       LDY   #$C1
2370-   C4 C3       CPY   $C3
2372-   A0 A3       LDY   #$A3
2374-   B1 8D       LDA   ($8D),Y
2376-   A0 C2       LDY   #$C2
2378-   C3          ???
2379-   C3          ???
237A-   A0 C3       LDY   #$C3
237C-   CF          ???
237D-   CE D4 D8    DEC   $D8D4
2380-   8D A0 C9    STA   $C9A0
2383-   CE C3 A0    DEC   $A0C3
2386-   D8          CLD
2387-   C3          ???
2388-   CE D4 AB    DEC   $ABD4
238B-   B1 8D       LDA   ($8D),Y
238D-   C3          ???
238E-   CF          ???
238F-   CE D4 D8    DEC   $D8D4
2392-   8D A0 D3    STA   $D3A0
2395-   D4          ???
2396-   C1 A0       CMP   ($A0,X)
2398-   D8          CLD
2399-   C3          ???
239A-   CE D4 8D    DEC   $8DD4
239D-   A0 CC       LDY   #$CC
239F-   C4 C1       CPY   $C1
23A1-   A0 D8       LDY   #$D8
23A3-   C3          ???
23A4-   CE D4 8D    DEC   $8DD4
23A7-   A0 C3       LDY   #$C3
23A9-   CD D0 A0    CMP   $A0D0
23AC-   A3          ???
23AD-   BC B3 B0    LDY   $B0B3,X
23B0-   B0 A0       BCS   $2352
23B2-   BB          ???
23B3-   20 CE CF    JSR   $CFCE
23B6-   D4          ???
23B7-   C5 20       CMP   $20
23B9-   D4          ???
23BA-   C8          INY
23BB-   C1 D4       CMP   ($D4,X)
23BD-   20 D4 C8    JSR   $C8D4
23C0-   C9 D3       CMP   #$D3
23C2-   20 C4 CF    JSR   $CFC4
23C5-   C5 D3       CMP   $D3
23C7-   CE A7 D4    DEC   $D4A7
23CA-   8D A0 C2    STA   $C2A0
23CD-   CE C5 A0    DEC   $A0C5
23D0-   D3          ???
23D1-   D4          ???
23D2-   C1 D2       CMP   ($D2,X)
23D4-   D4          ???
23D5-   CC D0 A0    CPY   $A0D0
23D8-   BB          ???
23D9-   20 C6 C9    JSR   $C9C6
23DC-   CC CC 20    CPY   $20CC
23DF-   D4          ???
23E0-   C8          INY
23E1-   C5 20       CMP   $20
23E3-   D7          ???
23E4-   C8          INY
23E5-   CF          ???
23E6-   CC C5 20    CPY   $20C5
23E9-   C1 D2       CMP   ($D2,X)
23EB-   D2 C1       CMP   ($C1)
23ED-   D9 AC 8D    CMP   $8DAC,Y
23F0-   AA          TAX
23F1-   20 20 20    JSR   $2020
23F4-   20 20 20    JSR   $2020
23F7-   20 20 20    JSR   $2020
23FA-   20 20 20    JSR   $2020
23FD-   20 20 20    JSR   $2020
2400-   20 20 20    JSR   $2020
2403-   20 20 20    JSR   $2020
2406-   20 20 20    JSR   $2020
2409-   20 20 20    JSR   $2020
240C-   D3          ???
240D-   C9 CE       CMP   #$CE
240F-   C3          ???
2410-   C5 20       CMP   $20
2412-   D7          ???
2413-   C5 A7       CMP   $A7
2415-   D2 C5       CMP   ($C5)
2417-   20 D5 D3    JSR   $D3D5
241A-   C9 CE       CMP   #$CE
241C-   C7          ???
241D-   20 C1 20    JSR   $20C1
2420-   C2          ???
2421-   D9 D4 C5    CMP   $C5D4,Y
2424-   8D A0 C3    STA   $C3A0
2427-   CC C3 A0    CPY   $A0C3
242A-   A0 BB       LDY   #$BB
242C-   20 CC CF    JSR   $CFCC
242F-   CF          ???
2430-   D0 8D       BNE   $23BF
2432-   A0 CC       LDY   #$CC
2434-   C4 C1       CPY   $C1
2436-   A0 D9       LDY   #$D9
2438-   C3          ???
2439-   CE D4 8D    DEC   $8DD4
243C-   A0 C1       LDY   #$C1
243E-   C4 C3       CPY   $C3
2440-   A0 A3       LDY   #$A3
2442-   B1 8D       LDA   ($8D),Y
2444-   A0 C2       LDY   #$C2
2446-   C3          ???
2447-   C3          ???
2448-   A0 C3       LDY   #$C3
244A-   CF          ???
244B-   CE D4 8D    DEC   $8DD4
244E-   A0 C9       LDY   #$C9
2450-   CE C3 A0    DEC   $A0C3
2453-   D9 C3 CE    CMP   $CEC3,Y
2456-   D4          ???
2457-   AB          ???
2458-   B1 8D       LDA   ($8D),Y
245A-   C3          ???
245B-   CF          ???
245C-   CE D4 8D    DEC   $8DD4
245F-   A0 D3       LDY   #$D3
2461-   D4          ???
2462-   C1 A0       CMP   ($A0,X)
2464-   D9 C3 CE    CMP   $CEC3,Y
2467-   D4          ???
2468-   8D A0 C3    STA   $C3A0
246B-   CD D0 A0    CMP   $A0D0
246E-   A3          ???
246F-   B3          ???
2470-   8D A0 C2    STA   $C2A0
2473-   CE C5 A0    DEC   $A0C5
2476-   D3          ???
2477-   D4          ???
2478-   C1 D2       CMP   ($D2,X)
247A-   D4          ???
247B-   CC D0 8D    CPY   $8DD0
247E-   AA          TAX
247F-   8D A0 C4    STA   $C4A0
2482-   D5 CD       CMP   $CD,X
2484-   D0 A0       BNE   $2426
2486-   A3          ???
2487-   C1 D2       CMP   ($D2,X)
2489-   D2 C1       CMP   ($C1)
248B-   D9 B2 BB    CMP   $BBB2,Y
248E-   A3          ???
248F-   B2 B0       LDA   ($B0)
2491-   B0 8D       BCS   $2420
2493-   A0 C4       LDY   #$C4
2495-   D5 CD       CMP   $CD,X
2497-   D0 A0       BNE   $2439
2499-   A3          ???
249A-   C1 D2       CMP   ($D2,X)
249C-   D2 C1       CMP   ($C1)
249E-   D9 B2 AB    CMP   $ABB2,Y
24A1-   B2 B0       LDA   ($B0)
24A3-   B0 BB       BCS   $2460
24A5-   A3          ???
24A6-   B2 B0       LDA   ($B0)
24A8-   B0 8D       BCS   $2437
24AA-   A0 DF       LDY   #$DF
24AC-   D7          ???
24AD-   C1 C9       CMP   ($C9,X)
24AF-   D4          ???
24B0-   8D A0 C4    STA   $C4A0
24B3-   D5 CD       CMP   $CD,X
24B5-   D0 A0       BNE   $2457
24B7-   A3          ???
24B8-   C1 D2       CMP   ($D2,X)
24BA-   D2 C1       CMP   ($C1)
24BC-   D9 B2 AB    CMP   $ABB2,Y
24BF-   B4 B0       LDY   $B0,X
24C1-   B0 BB       BCS   $247E
24C3-   A3          ???
24C4-   B2 B0       LDA   ($B0)
24C6-   B0 8D       BCS   $2455
24C8-   A0 C4       LDY   #$C4
24CA-   D5 CD       CMP   $CD,X
24CC-   D0 A0       BNE   $246E
24CE-   A3          ???
24CF-   C1 D2       CMP   ($D2,X)
24D1-   D2 C1       CMP   ($C1)
24D3-   D9 B2 AB    CMP   $ABB2,Y
24D6-   B6 B0       LDX   $B0,Y
24D8-   B0 BB       BCS   $2495
24DA-   A3          ???
24DB-   B1 B0       LDA   ($B0),Y
24DD-   8D A0 DF    STA   $DFA0
24E0-   D7          ???
24E1-   C1 C9       CMP   ($C9,X)
24E3-   D4          ???
24E4-   8D AA 8D    STA   $8DAA
24E7-   AA          TAX
24E8-   AA          TAX
24E9-   20 C7 C5    JSR   $C5C7
24EC-   D4          ???
24ED-   B1 B6       LDA   ($B6),Y
24EF-   B2 8D       LDA   ($8D)
24F1-   AA          TAX
24F2-   8D A0 DF    STA   $DFA0
24F5-   D0 D2       BNE   $24C9
24F7-   CE D4 A0    DEC   $A0D4
24FA-   A2 20       LDX   #$20
24FC-   A2 AC       LDX   #$AC
24FE-   B8          CLV
24FF-   C4 B8       CPY   $B8
2501-   C4 8D       CPY   $8D
2503-   A0 DF       LDY   #$DF
2505-   D0 D2       BNE   $24D9
2507-   CE D4 A0    DEC   $A0D4
250A-   A2 C7       LDX   #$C7
250C-   C5 D4       CMP   $D4
250E-   B1 B6       LDA   ($B6),Y
2510-   B2 AC       LDA   ($AC)
2512-   20 CC C9    JSR   $C9CC
2515-   CB          ???
2516-   C5 20       CMP   $20
2518-   C9 D4       CMP   #$D4
251A-   D3          ???
251B-   20 D3 C9    JSR   $C9D3
251E-   D3          ???
251F-   D4          ???
2520-   C5 D2       CMP   $D2
2522-   20 D2 CF    JSR   $CFD2
2525-   D5 D4       CMP   $D4,X
2527-   C9 CE       CMP   #$CE
2529-   C5 D3       CMP   $D3
252B-   AC A2 AC    LDY   $ACA2
252E-   B8          CLV
252F-   C4 8D       CPY   $8D
2531-   A0 DF       LDY   #$DF
2533-   D0 D2       BNE   $2507
2535-   CE D4 A0    DEC   $A0D4
2538-   A2 C7       LDX   #$C7
253A-   C5 D4       CMP   $D4
253C-   D3          ???
253D-   20 C1 20    JSR   $20C1
2540-   D6 C1       DEC   $C1,X
2542-   CC D5 C5    CPY   $C5D5
2545-   20 C6 D2    JSR   $D2C6
2548-   CF          ???
2549-   CD 20 C1    CMP   $C120
254C-   20 B1 B6    JSR   $B6B1
254F-   C2          ???
2550-   C9 D4       CMP   #$D4
2552-   AC B2 C4    LDY   $C4B2
2555-   A2 AC       LDX   #$AC
2557-   B8          CLV
2558-   C4 8D       CPY   $8D
255A-   A0 DF       LDY   #$DF
255C-   D0 D2       BNE   $2530
255E-   CE D4 A0    DEC   $A0D4
2561-   A2 C1       LDX   #$C1
2563-   D2 D2       CMP   ($D2)
2565-   C1 D9       CMP   ($D9,X)
2567-   20 C1 CE    JSR   $CEC1
256A-   C4 20       CPY   $20
256C-   D3          ???
256D-   D4          ???
256E-   CF          ???
256F-   D2 C5       CMP   ($C5)
2571-   D3          ???
2572-   20 C9 D4    JSR   $D4C9
2575-   20 C9 CE    JSR   $CEC9
2578-   20 D2 C5    JSR   $C5D2
257B-   D4          ???
257C-   D5 D2       CMP   $D2,X
257E-   CE AE A2    DEC   $A2AE
2581-   AC B8 C4    LDY   $C4B8
2584-   B8          CLV
2585-   C4 8D       CPY   $8D
2587-   A0 DF       LDY   #$DF
2589-   D0 D2       BNE   $255D
258B-   CE D4 A0    DEC   $A0D4
258E-   A2 D4       LDX   #$D4
2590-   C8          INY
2591-   D5 D3       CMP   $D3,X
2593-   20 C7 C5    JSR   $C5C7
2596-   D4          ???
2597-   B1 B6       LDA   ($B6),Y
2599-   B2 20       LDA   ($20)
259B-   C1 D2       CMP   ($D2,X)
259D-   D2 C1       CMP   ($C1)
259F-   D9 B2 BB    CMP   $BBB2,Y
25A2-   A3          ???
25A3-   B1 B0       LDA   ($B0),Y
25A5-   B0 BB       BCS   $2562
25A7-   A3          ???
25A8-   B0 20       BCS   $25CA
25AA-   D2 C5       CMP   ($C5)
25AC-   D4          ???
25AD-   D5 D2       CMP   $D2,X
25AF-   CE D3 BA    DEC   $BAD3
25B2-   20 A2 AC    JSR   $ACA2
25B5-   B8          CLV
25B6-   C4 B8       CPY   $B8
25B8-   C4 8D       CPY   $8D
25BA-   A0 C7       LDY   #$C7
25BC-   C5 D4       CMP   $D4
25BE-   B1 B6       LDA   ($B6),Y
25C0-   B2 A0       LDA   ($A0)
25C2-   A3          ???
25C3-   C1 D2       CMP   ($D2,X)
25C5-   D2 C1       CMP   ($C1)
25C7-   D9 B2 BB    CMP   $BBB2,Y
25CA-   A3          ???
25CB-   B1 B0       LDA   ($B0),Y
25CD-   B0 BB       BCS   $258A
25CF-   A3          ???
25D0-   B0 8D       BCS   $255F
25D2-   A0 C4       LDY   #$C4
25D4-   D5 CD       CMP   $CD,X
25D6-   D0 A0       BNE   $2578
25D8-   A3          ???
25D9-   D2 C5       CMP   ($C5)
25DB-   D4          ???
25DC-   D5 D2       CMP   $D2,X
25DE-   CE BB D2    DEC   $D2BB
25E1-   C5 D4       CMP   $D4
25E3-   CC C5 CE    CPY   $CEC5
25E6-   8D A0 DF    STA   $DFA0
25E9-   D7          ???
25EA-   C1 C9       CMP   ($C9,X)
25EC-   D4          ???
25ED-   8D AA 8D    STA   $8DAA
25F0-   A0 DF       LDY   #$DF
25F2-   D0 D2       BNE   $25C6
25F4-   CE D4 A0    DEC   $A0D4
25F7-   A2 20       LDX   #$20
25F9-   A2 AC       LDX   #$AC
25FB-   B8          CLV
25FC-   C4 B8       CPY   $B8
25FE-   C4 8D       CPY   $8D
2600-   A0 DF       LDY   #$DF
2602-   D0 D2       BNE   $25D6
2604-   CE D4 A0    DEC   $A0D4
2607-   A2 C6       LDX   #$C6
2609-   C9 CE       CMP   #$CE
260B-   AE A2 AC    LDX   $ACA2
260E-   B8          CLV
260F-   C4 B8       CPY   $B8
2611-   C4 B8       CPY   $B8
2613-   C4 8D       CPY   $8D
2615-   AA          TAX
2616-   8D A0 CA    STA   $CAA0
2619-   CD D0 A0    CMP   $A0D0
261C-   D2 C5       CMP   ($C5)
261E-   C5 CE       CMP   $CE
2620-   D4          ???
2621-   D2 D9       CMP   ($D9)
2623-   8D AA 8D    STA   $8DAA
2626-   AA          TAX
2627-   E0 E0       CPX   #$E0
2629-   E0 E0       CPX   #$E0
262B-   E0 E0       CPX   #$E0
262D-   E0 E0       CPX   #$E0
262F-   E0 E0       CPX   #$E0
2631-   E0 E0       CPX   #$E0
2633-   E0 E0       CPX   #$E0
2635-   E0 E0       CPX   #$E0
2637-   E0 E0       CPX   #$E0
2639-   E0 E0       CPX   #$E0
263B-   E0 E0       CPX   #$E0
263D-   E0 E0       CPX   #$E0
263F-   E0 E0       CPX   #$E0
2641-   E0 E0       CPX   #$E0
2643-   E0 E0       CPX   #$E0
2645-   AA          TAX
2646-   8D AA 20    STA   $20AA
2649-   C2          ???
264A-   CF          ???
264B-   D4          ???
264C-   D4          ???
264D-   CF          ???
264E-   CD 20 C9    CMP   $C920
2651-   CE C3 CC    DEC   $CCC3
2654-   D5 C4       CMP   $C4,X
2656-   C5 D3       CMP   $D3
2658-   20 A8 D2    JSR   $D2A8
265B-   CF          ???
265C-   D5 D4       CMP   $D4,X
265E-   C9 CE       CMP   #$CE
2660-   C5 D3       CMP   $D3
2662-   A9 20       LDA   #$20
2664-   20 20 AA    JSR   $AA20
2667-   8D AA AC    STA   $ACAA
266A-   AC AC AC    LDY   $ACAC
266D-   AC AC AC    LDY   $ACAC
2670-   AC AC AC    LDY   $ACAC
2673-   AC AC AC    LDY   $ACAC
2676-   AC AC AC    LDY   $ACAC
2679-   AC AC AC    LDY   $ACAC
267C-   AC AC AC    LDY   $ACAC
267F-   AC AC AC    LDY   $ACAC
2682-   AC AC AC    LDY   $ACAC
2685-   AC AC AA    LDY   $AAAC
2688-   8D AA 8D    STA   $8DAA
268B-   A0 D0       LDY   #$D0
268D-   D5 D4       CMP   $D4,X
268F-   A0 CD       LDY   #$CD
2691-   C9 CE       CMP   #$CE
2693-   AE CC C9    LDX   $C9CC
2696-   C2          ???
2697-   AE D2 C5    LDX   $C5D2
269A-   D1 D5       CMP   ($D5),Y
269C-   C9 D2       CMP   #$D2
269E-   C5 C4       CMP   $C4
26A0-   8D AA 8D    STA   $8DAA
26A3-   AA          TAX
26A4-   AA          TAX
26A5-   20 C9 CE    JSR   $CEC9
26A8-   C4 C9       CPY   $C9
26AA-   D6 C9       DEC   $C9,X
26AC-   C4 D5       CPY   $D5
26AE-   C1 CC       CMP   ($CC,X)
26B0-   20 D3 D5    JSR   $D5D3
26B3-   C2          ???
26B4-   D2 CF       CMP   ($CF)
26B6-   D5 D4       CMP   $D4,X
26B8-   C9 CE       CMP   #$CE
26BA-   C5 20       CMP   $20
26BC-   C9 CE       CMP   #$CE
26BE-   C3          ???
26BF-   CC D5 C4    CPY   $C4D5
26C2-   C5 D3       CMP   $D3
26C4-   8D AA 8D    STA   $8DAA
26C7-   AA          TAX
26C8-   AA          TAX
26C9-   20 B8 AD    JSR   $ADB8
26CC-   C2          ???
26CD-   C9 D4       CMP   #$D4
26CF-   20 B1 AD    JSR   $ADB1
26D2-   C4 C9       CPY   $C9
26D4-   CD C5 CE    CMP   $CEC5
26D7-   D3          ???
26D8-   C9 CF       CMP   #$CF
26DA-   CE C1 CC    DEC   $CCC1
26DD-   20 C1 D2    JSR   $D2C1
26E0-   D2 C1       CMP   ($C1)
26E2-   D9 20 D3    CMP   $D320,Y
26E5-   D5 C2       CMP   $C2,X
26E7-   D2 CF       CMP   ($CF)
26E9-   D5 D4       CMP   $D4,X
26EB-   C9 CE       CMP   #$CE
26ED-   C5 D3       CMP   $D3
26EF-   8D AA 8D    STA   $8DAA
26F2-   A0 D0       LDY   #$D0
26F4-   D5 D4       CMP   $D4,X
26F6-   A0 CD       LDY   #$CD
26F8-   C9 CE       CMP   #$CE
26FA-   AE D3 D5    LDX   $D5D3
26FD-   C2          ???
26FE-   AE C1 C4    LDX   $C4C1
2701-   C9 CD       CMP   #$CD
2703-   B8          CLV
2704-   B1 8D       LDA   ($8D),Y
2706-   A0 D0       LDY   #$D0
2708-   D5 D4       CMP   $D4,X
270A-   A0 CD       LDY   #$CD
270C-   C9 CE       CMP   #$CE
270E-   AE D3 D5    LDX   $D5D3
2711-   C2          ???
2712-   AE C1 C7    LDX   $C7C1
2715-   C5 D4       CMP   $D4
2717-   B8          CLV
2718-   B1 8D       LDA   ($8D),Y
271A-   A0 D0       LDY   #$D0
271C-   D5 D4       CMP   $D4,X
271E-   A0 CD       LDY   #$CD
2720-   C9 CE       CMP   #$CE
2722-   AE D3 D5    LDX   $D5D3
2725-   C2          ???
2726-   AE C1 D0    LDX   $D0C1
2729-   D5 D4       CMP   $D4,X
272B-   B8          CLV
272C-   B1 8D       LDA   ($8D),Y
272E-   AA          TAX
272F-   8D AA AA    STA   $AAAA
2732-   20 B8 AD    JSR   $ADB8
2735-   C2          ???
2736-   C9 D4       CMP   #$D4
2738-   20 B2 AD    JSR   $ADB2
273B-   C4 C9       CPY   $C9
273D-   CD C5 CE    CMP   $CEC5
2740-   D3          ???
2741-   C9 CF       CMP   #$CF
2743-   CE C1 CC    DEC   $CCC1
2746-   20 C1 D2    JSR   $D2C1
2749-   D2 C1       CMP   ($C1)
274B-   D9 20 D3    CMP   $D320,Y
274E-   D5 C2       CMP   $C2,X
2750-   D2 CF       CMP   ($CF)
2752-   D5 D4       CMP   $D4,X
2754-   C9 CE       CMP   #$CE
2756-   C5 D3       CMP   $D3
2758-   8D AA 8D    STA   $8DAA
275B-   A0 D0       LDY   #$D0
275D-   D5 D4       CMP   $D4,X
275F-   A0 CD       LDY   #$CD
2761-   C9 CE       CMP   #$CE
2763-   AE D3 D5    LDX   $D5D3
2766-   C2          ???
2767-   AE C1 C4    LDX   $C4C1
276A-   C9 CD       CMP   #$CD
276C-   B8          CLV
276D-   B2 8D       LDA   ($8D)
276F-   A0 D0       LDY   #$D0
2771-   D5 D4       CMP   $D4,X
2773-   A0 CD       LDY   #$CD
2775-   C9 CE       CMP   #$CE
2777-   AE D3 D5    LDX   $D5D3
277A-   C2          ???
277B-   AE C1 C7    LDX   $C7C1
277E-   C5 D4       CMP   $D4
2780-   B8          CLV
2781-   B2 8D       LDA   ($8D)
2783-   A0 D0       LDY   #$D0
2785-   D5 D4       CMP   $D4,X
2787-   A0 CD       LDY   #$CD
2789-   C9 CE       CMP   #$CE
278B-   AE D3 D5    LDX   $D5D3
278E-   C2          ???
278F-   AE C1 D0    LDX   $D0C1
2792-   D5 D4       CMP   $D4,X
2794-   B8          CLV
2795-   B2 8D       LDA   ($8D)
2797-   AA          TAX
2798-   8D AA AA    STA   $AAAA
279B-   20 B1 B6    JSR   $B6B1
279E-   AD C2 C9    LDA   $C9C2
27A1-   D4          ???
27A2-   20 B1 AD    JSR   $ADB1
27A5-   C4 C9       CPY   $C9
27A7-   CD C5 CE    CMP   $CEC5
27AA-   D3          ???
27AB-   C9 CF       CMP   #$CF
27AD-   CE C1 CC    DEC   $CCC1
27B0-   20 C1 D2    JSR   $D2C1
27B3-   D2 C1       CMP   ($C1)
27B5-   D9 D3 8D    CMP   $8DD3,Y
27B8-   AA          TAX
27B9-   8D A0 D0    STA   $D0A0
27BC-   D5 D4       CMP   $D4,X
27BE-   A0 CD       LDY   #$CD
27C0-   C9 CE       CMP   #$CE
27C2-   AE D3 D5    LDX   $D5D3
27C5-   C2          ???
27C6-   AE C1 C4    LDX   $C4C1
27C9-   C9 CD       CMP   #$CD
27CB-   B1 B6       LDA   ($B6),Y
27CD-   B1 8D       LDA   ($8D),Y
27CF-   A0 D0       LDY   #$D0
27D1-   D5 D4       CMP   $D4,X
27D3-   A0 CD       LDY   #$CD
27D5-   C9 CE       CMP   #$CE
27D7-   AE D3 D5    LDX   $D5D3
27DA-   C2          ???
27DB-   AE C1 D0    LDX   $D0C1
27DE-   D5 D4       CMP   $D4,X
27E0-   B1 B6       LDA   ($B6),Y
27E2-   B1 8D       LDA   ($8D),Y
27E4-   A0 D0       LDY   #$D0
27E6-   D5 D4       CMP   $D4,X
27E8-   A0 CD       LDY   #$CD
27EA-   C9 CE       CMP   #$CE
27EC-   AE D3 D5    LDX   $D5D3
27EF-   C2          ???
27F0-   AE C1 C7    LDX   $C7C1
27F3-   C5 D4       CMP   $D4
27F5-   B1 B6       LDA   ($B6),Y
27F7-   B1 8D       LDA   ($8D),Y
27F9-   AA          TAX
27FA-   8D AA AA    STA   $AAAA
27FD-   20 B1 B6    JSR   $B6B1
2800-   AD C2 C9    LDA   $C9C2
2803-   D4          ???
2804-   20 B2 AD    JSR   $ADB2
2807-   C4 C9       CPY   $C9
2809-   CD C5 CE    CMP   $CEC5
280C-   D3          ???
280D-   C9 CF       CMP   #$CF
280F-   CE C1 CC    DEC   $CCC1
2812-   20 C1 D2    JSR   $D2C1
2815-   D2 C1       CMP   ($C1)
2817-   D9 D3 8D    CMP   $8DD3,Y
281A-   AA          TAX
281B-   8D A0 D0    STA   $D0A0
281E-   D5 D4       CMP   $D4,X
2820-   A0 CD       LDY   #$CD
2822-   C9 CE       CMP   #$CE
2824-   AE D3 D5    LDX   $D5D3
2827-   C2          ???
2828-   AE C1 C4    LDX   $C4C1
282B-   C9 CD       CMP   #$CD
282D-   B1 B6       LDA   ($B6),Y
282F-   B2 8D       LDA   ($8D)
2831-   A0 D0       LDY   #$D0
2833-   D5 D4       CMP   $D4,X
2835-   A0 CD       LDY   #$CD
2837-   C9 CE       CMP   #$CE
2839-   AE D3 D5    LDX   $D5D3
283C-   C2          ???
283D-   AE C1 D0    LDX   $D0C1
2840-   D5 D4       CMP   $D4,X
2842-   B1 B6       LDA   ($B6),Y
2844-   B2 8D       LDA   ($8D)
2846-   A0 D0       LDY   #$D0
2848-   D5 D4       CMP   $D4,X
284A-   A0 CD       LDY   #$CD
284C-   C9 CE       CMP   #$CE
284E-   AE D3 D5    LDX   $D5D3
2851-   C2          ???
2852-   AE C1 C7    LDX   $C7C1
2855-   C5 D4       CMP   $D4
2857-   B1 B6       LDA   ($B6),Y
2859-   B2 8D       LDA   ($8D)
285B-   AA          TAX
285C-   8D D8 C3    STA   $C3D8
285F-   CE D4 A0    DEC   $A0D4
2862-   C4 D3       CPY   $D3
2864-   A0 B2       LDY   #$B2
2866-   8D D9 C3    STA   $C3D9
2869-   CE D4 A0    DEC   $A0D4
286C-   C4 D3       CPY   $D3
286E-   A0 B2       LDY   #$B2
2870-   8D 00 00    STA   $0000
