0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C6    LDY   $C620,X
0950-   C9 CC       CMP   #$CC
0952-   C5 C9       CMP   $C9
0954-   CF          ???
0955-   20 20 C4    JSR   $C420
0958-   C5 CD       CMP   $CD
095A-   CF          ???
095B-   20 BE AD    JSR   $ADBE
095E-   20 20 20    JSR   $2020
0961-   20 20 20    JSR   $2020
0964-   AA          TAX
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B2    JSR   $B220
09D4-   B1 AD       LDA   ($AD),Y
09D6-   CA          DEX
09D7-   C1 CE       CMP   ($CE,X)
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B9       LDA   ($B9),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 D4    STA   $D4A0
0B02-   D2 A0       CMP   ($A0)
0B04-   CF          ???
0B05-   CE 8D A0    DEC   $A08D
0B08-   C4 D3       CPY   $D3
0B0A-   CB          ???
0B0B-   A0 C6       LDY   #$C6
0B0D-   C9 CC       CMP   #$CC
0B0F-   C5 C9       CMP   $C9
0B11-   CF          ???
0B12-   AE C4 C5    LDX   $C5C4
0B15-   CD CF 8D    CMP   $8DCF
0B18-   A0 CF       LDY   #$CF
0B1A-   C2          ???
0B1B-   CA          DEX
0B1C-   A0 A4       LDY   #$A4
0B1E-   C2          ???
0B1F-   C6 C5       DEC   $C5
0B21-   B0 8D       BCS   $0AB0
0B23-   A0 CF       LDY   #$CF
0B25-   D2 C7       CMP   ($C7)
0B27-   A0 A4       LDY   #$A4
0B29-   B6 B0       LDX   $B0,Y
0B2B-   B0 B0       BCS   $0ADD
0B2D-   8D AA 8D    STA   $8DAA
0B30-   AA          TAX
0B31-   E0 E0       CPX   #$E0
0B33-   E0 E0       CPX   #$E0
0B35-   E0 E0       CPX   #$E0
0B37-   E0 E0       CPX   #$E0
0B39-   E0 E0       CPX   #$E0
0B3B-   E0 E0       CPX   #$E0
0B3D-   E0 E0       CPX   #$E0
0B3F-   E0 E0       CPX   #$E0
0B41-   E0 E0       CPX   #$E0
0B43-   E0 E0       CPX   #$E0
0B45-   E0 E0       CPX   #$E0
0B47-   E0 E0       CPX   #$E0
0B49-   E0 E0       CPX   #$E0
0B4B-   E0 E0       CPX   #$E0
0B4D-   E0 E0       CPX   #$E0
0B4F-   AA          TAX
0B50-   8D AA 20    STA   $20AA
0B53-   20 D4 CF    JSR   $CFD4
0B56-   D0 20       BNE   $0B78
0B58-   C9 CE       CMP   #$CE
0B5A-   C3          ???
0B5B-   CC D5 C4    CPY   $C4D5
0B5E-   C5 D3       CMP   $D3
0B60-   20 A8 C8    JSR   $C8A8
0B63-   CF          ???
0B64-   CF          ???
0B65-   CB          ???
0B66-   D3          ???
0B67-   AC CD C1    LDY   $C1CD
0B6A-   C3          ???
0B6B-   D2 CF       CMP   ($CF)
0B6D-   D3          ???
0B6E-   A9 20       LDA   #$20
0B70-   AA          TAX
0B71-   8D AA AC    STA   $ACAA
0B74-   AC AC AC    LDY   $ACAC
0B77-   AC AC AC    LDY   $ACAC
0B7A-   AC AC AC    LDY   $ACAC
0B7D-   AC AC AC    LDY   $ACAC
0B80-   AC AC AC    LDY   $ACAC
0B83-   AC AC AC    LDY   $ACAC
0B86-   AC AC AC    LDY   $ACAC
0B89-   AC AC AC    LDY   $ACAC
0B8C-   AC AC AC    LDY   $ACAC
0B8F-   AC AC AA    LDY   $AAAC
0B92-   8D AA 8D    STA   $8DAA
0B95-   A0 D0       LDY   #$D0
0B97-   D5 D4       CMP   $D4,X
0B99-   A0 CD       LDY   #$CD
0B9B-   C9 CE       CMP   #$CE
0B9D-   AE D6 C1    LDX   $C1D6
0BA0-   D2 D3       CMP   ($D3)
0BA2-   AE D2 C5    LDX   $C5D2
0BA5-   D1 D5       CMP   ($D5),Y
0BA7-   C9 D2       CMP   #$D2
0BA9-   C5 C4       CMP   $C4
0BAB-   8D A0 D5    STA   $D5A0
0BAE-   D3          ???
0BAF-   C5 A0       CMP   $A0
0BB1-   CD C9 CE    CMP   $CEC9
0BB4-   AE CD C1    LDX   $C1CD
0BB7-   C3          ???
0BB8-   AE D2 C5    LDX   $C5D2
0BBB-   D1 D5       CMP   ($D5),Y
0BBD-   C9 D2       CMP   #$D2
0BBF-   C5 C4       CMP   $C4
0BC1-   8D A0 D0    STA   $D0A0
0BC4-   D5 D4       CMP   $D4,X
0BC6-   A0 CD       LDY   #$CD
0BC8-   C9 CE       CMP   #$CE
0BCA-   AE C8 CF    LDX   $CFC8
0BCD-   CF          ???
0BCE-   CB          ???
0BCF-   D3          ???
0BD0-   AE D2 C5    LDX   $C5D2
0BD3-   D1 D5       CMP   ($D5),Y
0BD5-   C9 D2       CMP   #$D2
0BD7-   C5 C4       CMP   $C4
0BD9-   8D A0 D5    STA   $D5A0
0BDC-   D3          ???
0BDD-   C5 A0       CMP   $A0
0BDF-   CD C9 CE    CMP   $CEC9
0BE2-   AE CD C1    LDX   $C1CD
0BE5-   C3          ???
0BE6-   AE C6 C9    LDX   $C9C6
0BE9-   CC C5 C9    CPY   $C9C5
0BEC-   CF          ???
0BED-   8D A0 D0    STA   $D0A0
0BF0-   D5 D4       CMP   $D4,X
0BF2-   A0 CD       LDY   #$CD
0BF4-   C9 CE       CMP   #$CE
0BF6-   AE C8 CF    LDX   $CFC8
0BF9-   CF          ???
0BFA-   CB          ???
0BFB-   D3          ???
0BFC-   AE C6 C9    LDX   $C9C6
0BFF-   CC C5 C9    CPY   $C9C5
0C02-   CF          ???
0C03-   8D AA 8D    STA   $8DAA
0C06-   AA          TAX
0C07-   E0 E0       CPX   #$E0
0C09-   E0 E0       CPX   #$E0
0C0B-   E0 E0       CPX   #$E0
0C0D-   E0 E0       CPX   #$E0
0C0F-   E0 E0       CPX   #$E0
0C11-   E0 E0       CPX   #$E0
0C13-   E0 E0       CPX   #$E0
0C15-   E0 E0       CPX   #$E0
0C17-   E0 E0       CPX   #$E0
0C19-   E0 E0       CPX   #$E0
0C1B-   E0 E0       CPX   #$E0
0C1D-   E0 E0       CPX   #$E0
0C1F-   E0 E0       CPX   #$E0
0C21-   E0 E0       CPX   #$E0
0C23-   E0 E0       CPX   #$E0
0C25-   AA          TAX
0C26-   8D AA 20    STA   $20AA
0C29-   20 20 20    JSR   $2020
0C2C-   20 20 D0    JSR   $D020
0C2F-   D2 CF       CMP   ($CF)
0C31-   C7          ???
0C32-   D2 C1       CMP   ($C1)
0C34-   CD 20 CD    CMP   $CD20
0C37-   C1 C9       CMP   ($C9,X)
0C39-   CE 20 C2    DEC   $C220
0C3C-   CF          ???
0C3D-   C4 D9       CPY   $D9
0C3F-   20 20 20    JSR   $2020
0C42-   20 20 20    JSR   $2020
0C45-   20 AA 8D    JSR   $8DAA
0C48-   AA          TAX
0C49-   AC AC AC    LDY   $ACAC
0C4C-   AC AC AC    LDY   $ACAC
0C4F-   AC AC AC    LDY   $ACAC
0C52-   AC AC AC    LDY   $ACAC
0C55-   AC AC AC    LDY   $ACAC
0C58-   AC AC AC    LDY   $ACAC
0C5B-   AC AC AC    LDY   $ACAC
0C5E-   AC AC AC    LDY   $ACAC
0C61-   AC AC AC    LDY   $ACAC
0C64-   AC AC AC    LDY   $ACAC
0C67-   AA          TAX
0C68-   8D AA 8D    STA   $8DAA
0C6B-   AA          TAX
0C6C-   AA          TAX
0C6D-   AA          TAX
0C6E-   AA          TAX
0C6F-   AA          TAX
0C70-   AA          TAX
0C71-   AA          TAX
0C72-   AA          TAX
0C73-   AA          TAX
0C74-   AA          TAX
0C75-   AA          TAX
0C76-   AA          TAX
0C77-   AA          TAX
0C78-   AA          TAX
0C79-   AA          TAX
0C7A-   AA          TAX
0C7B-   AA          TAX
0C7C-   AA          TAX
0C7D-   AA          TAX
0C7E-   AA          TAX
0C7F-   AA          TAX
0C80-   AA          TAX
0C81-   AA          TAX
0C82-   AA          TAX
0C83-   AA          TAX
0C84-   AA          TAX
0C85-   AA          TAX
0C86-   AA          TAX
0C87-   AA          TAX
0C88-   AA          TAX
0C89-   AA          TAX
0C8A-   AA          TAX
0C8B-   8D AA AA    STA   $AAAA
0C8E-   AA          TAX
0C8F-   AA          TAX
0C90-   AA          TAX
0C91-   AA          TAX
0C92-   AA          TAX
0C93-   AA          TAX
0C94-   AA          TAX
0C95-   AA          TAX
0C96-   AA          TAX
0C97-   AA          TAX
0C98-   AA          TAX
0C99-   AA          TAX
0C9A-   AA          TAX
0C9B-   AA          TAX
0C9C-   AA          TAX
0C9D-   AA          TAX
0C9E-   AA          TAX
0C9F-   AA          TAX
0CA0-   AA          TAX
0CA1-   AA          TAX
0CA2-   AA          TAX
0CA3-   AA          TAX
0CA4-   AA          TAX
0CA5-   AA          TAX
0CA6-   AA          TAX
0CA7-   AA          TAX
0CA8-   AA          TAX
0CA9-   AA          TAX
0CAA-   AA          TAX
0CAB-   AA          TAX
0CAC-   8D AA 20    STA   $20AA
0CAF-   20 20 20    JSR   $2020
0CB2-   20 20 20    JSR   $2020
0CB5-   20 20 20    JSR   $2020
0CB8-   20 20 20    JSR   $2020
0CBB-   20 20 20    JSR   $2020
0CBE-   20 20 20    JSR   $2020
0CC1-   20 20 20    JSR   $2020
0CC4-   20 20 20    JSR   $2020
0CC7-   20 20 20    JSR   $2020
0CCA-   20 20 AA    JSR   $AA20
0CCD-   8D AA 20    STA   $20AA
0CD0-   CE CF D4    DEC   $D4CF
0CD3-   C5 BA       CMP   $BA
0CD5-   20 C6 CF    JSR   $CFC6
0CD8-   D2 20       CMP   ($20)
0CDA-   D4          ???
0CDB-   C8          INY
0CDC-   C9 D3       CMP   #$D3
0CDE-   20 D4 CF    JSR   $CFD4
0CE1-   20 D7 CF    JSR   $CFD7
0CE4-   D2 CB       CMP   ($CB)
0CE6-   20 20 20    JSR   $2020
0CE9-   20 20 20    JSR   $2020
0CEC-   20 AA 8D    JSR   $8DAA
0CEF-   AA          TAX
0CF0-   20 D0 D2    JSR   $D2D0
0CF3-   CF          ???
0CF4-   D0 C5       BNE   $0CBB
0CF6-   D2 CC       CMP   ($CC)
0CF8-   D9 AC 20    CMP   $20AC,Y
0CFB-   D4          ???
0CFC-   C8          INY
0CFD-   C5 20       CMP   $20
0CFF-   C4 C5       CPY   $C5
0D01-   CD CF 20    CMP   $20CF
0D04-   C8          INY
0D05-   C1 D3       CMP   ($D3,X)
0D07-   20 D4 CF    JSR   $CFD4
0D0A-   20 C2 C5    JSR   $C5C2
0D0D-   20 AA 8D    JSR   $8DAA
0D10-   AA          TAX
0D11-   20 C2 CC    JSR   $CCC2
0D14-   CF          ???
0D15-   C1 C4       CMP   ($C4,X)
0D17-   C5 C4       CMP   $C4
0D19-   AC 20 D4    LDY   $D420
0D1C-   C8          INY
0D1D-   C5 CE       CMP   $CE
0D1F-   20 C5 D8    JSR   $D8C5
0D22-   C5 C3       CMP   $C3
0D24-   D5 D4       CMP   $D4,X
0D26-   C5 C4       CMP   $C4
0D28-   20 D6 C9    JSR   $C9D6
0D2B-   C1 20       CMP   ($20,X)
0D2D-   20 20 AA    JSR   $AA20
0D30-   8D AA 20    STA   $20AA
0D33-   D4          ???
0D34-   C8          INY
0D35-   C5 20       CMP   $20
0D37-   CD CF CE    CMP   $CECF
0D3A-   C9 D4       CMP   #$D4
0D3C-   CF          ???
0D3D-   D2 20       CMP   ($20)
0D3F-   A8          TAY
0D40-   B6 B0       LDX   $B0,Y
0D42-   B0 B0       BCS   $0CF4
0D44-   C7          ???
0D45-   A9 AE       LDA   #$AE
0D47-   20 C9 C6    JSR   $C6C9
0D4A-   20 D4 C8    JSR   $C8D4
0D4D-   C9 D3       CMP   #$D3
0D4F-   20 AA 8D    JSR   $8DAA
0D52-   AA          TAX
0D53-   20 C9 D3    JSR   $D3C9
0D56-   20 CE CF    JSR   $CFCE
0D59-   D4          ???
0D5A-   20 C4 CF    JSR   $CFC4
0D5D-   CE C5 AC    DEC   $ACC5
0D60-   20 D9 CF    JSR   $CFD9
0D63-   D5 20       CMP   $20,X
0D65-   D7          ???
0D66-   C9 CC       CMP   #$CC
0D68-   CC 20 C7    CPY   $C720
0D6B-   C5 D4       CMP   $D4
0D6D-   20 C1 20    JSR   $20C1
0D70-   20 AA 8D    JSR   $8DAA
0D73-   AA          TAX
0D74-   20 A2 C6    JSR   $C6A2
0D77-   C9 CC       CMP   #$CC
0D79-   C5 20       CMP   $20
0D7B-   CE CF D4    DEC   $D4CF
0D7E-   20 C6 CF    JSR   $CFC6
0D81-   D5 CE       CMP   $CE,X
0D83-   C4 A2       CPY   $A2
0D85-   20 C5 D2    JSR   $D2C5
0D88-   D2 CF       CMP   ($CF)
0D8A-   D2 20       CMP   ($20)
0D8C-   D7          ???
0D8D-   C8          INY
0D8E-   C5 CE       CMP   $CE
0D90-   20 20 AA    JSR   $AA20
0D93-   8D AA 20    STA   $20AA
0D96-   C4 CF       CPY   $CF
0D98-   C9 CE       CMP   #$CE
0D9A-   C7          ???
0D9B-   20 C6 C9    JSR   $C9C6
0D9E-   CC C5 20    CPY   $20C5
0DA1-   CF          ???
0DA2-   D0 C5       BNE   $0D69
0DA4-   D2 C1       CMP   ($C1)
0DA6-   D4          ???
0DA7-   C9 CF       CMP   #$CF
0DA9-   CE D3 AE    DEC   $AED3
0DAC-   20 20 20    JSR   $2020
0DAF-   20 20 20    JSR   $2020
0DB2-   20 AA 8D    JSR   $8DAA
0DB5-   AA          TAX
0DB6-   20 20 20    JSR   $2020
0DB9-   20 20 20    JSR   $2020
0DBC-   20 20 20    JSR   $2020
0DBF-   20 20 20    JSR   $2020
0DC2-   20 20 20    JSR   $2020
0DC5-   20 20 20    JSR   $2020
0DC8-   20 20 20    JSR   $2020
0DCB-   20 20 20    JSR   $2020
0DCE-   20 20 20    JSR   $2020
0DD1-   20 20 20    JSR   $2020
0DD4-   AA          TAX
0DD5-   8D AA 20    STA   $20AA
0DD8-   C6 CF       DEC   $CF
0DDA-   D2 20       CMP   ($20)
0DDC-   D9 CF D5    CMP   $D5CF,Y
0DDF-   D2 20       CMP   ($20)
0DE1-   CF          ???
0DE2-   D7          ???
0DE3-   CE 20 D0    DEC   $D020
0DE6-   D2 CF       CMP   ($CF)
0DE8-   CA          DEX
0DE9-   C5 C3       CMP   $C3
0DEB-   D4          ???
0DEC-   D3          ???
0DED-   AC 20 C1    LDY   $C120
0DF0-   20 D7 C1    JSR   $C1D7
0DF3-   D9 20 AA    CMP   $AA20,Y
0DF6-   8D AA 20    STA   $20AA
0DF9-   D4          ???
0DFA-   CF          ???
0DFB-   20 D7 CF    JSR   $CFD7
0DFE-   D2 CB       CMP   ($CB)
0E00-   20 C1 D2    JSR   $D2C1
0E03-   CF          ???
0E04-   D5 CE       CMP   $CE,X
0E06-   C4 20       CPY   $20
0E08-   D4          ???
0E09-   C8          INY
0E0A-   C9 D3       CMP   #$D3
0E0C-   20 C9 D3    JSR   $D3C9
0E0F-   20 D4 CF    JSR   $CFD4
0E12-   20 20 20    JSR   $2020
0E15-   20 AA 8D    JSR   $8DAA
0E18-   AA          TAX
0E19-   20 D5 D3    JSR   $D3D5
0E1C-   C5 20       CMP   $20
0E1E-   C1 CE       CMP   ($CE,X)
0E20-   20 C5 D8    JSR   $D8C5
0E23-   C5 C3       CMP   $C3
0E25-   20 C6 C9    JSR   $C9C6
0E28-   CC C5 20    CPY   $20C5
0E2B-   D4          ???
0E2C-   CF          ???
0E2D-   20 C2 CC    JSR   $CCC2
0E30-   CF          ???
0E31-   C1 C4       CMP   ($C4,X)
0E33-   20 20 20    JSR   $2020
0E36-   20 AA 8D    JSR   $8DAA
0E39-   AA          TAX
0E3A-   20 C1 CE    JSR   $CEC1
0E3D-   C4 20       CPY   $20
0E3F-   C5 D8       CMP   $D8
0E41-   C5 C3       CMP   $C3
0E43-   D5 D4       CMP   $D4,X
0E45-   C5 20       CMP   $20
0E47-   D4          ???
0E48-   C8          INY
0E49-   C5 20       CMP   $20
0E4B-   C3          ???
0E4C-   CF          ???
0E4D-   C4 C5       CPY   $C5
0E4F-   AE 20 20    LDX   $2020
0E52-   20 20 20    JSR   $2020
0E55-   20 20 20    JSR   $2020
0E58-   AA          TAX
0E59-   8D AA 20    STA   $20AA
0E5C-   20 20 20    JSR   $2020
0E5F-   20 20 20    JSR   $2020
0E62-   20 20 20    JSR   $2020
0E65-   20 20 20    JSR   $2020
0E68-   20 20 20    JSR   $2020
0E6B-   20 20 20    JSR   $2020
0E6E-   20 20 20    JSR   $2020
0E71-   20 20 20    JSR   $2020
0E74-   20 20 20    JSR   $2020
0E77-   20 20 AA    JSR   $AA20
0E7A-   8D AA AA    STA   $AAAA
0E7D-   AA          TAX
0E7E-   AA          TAX
0E7F-   AA          TAX
0E80-   AA          TAX
0E81-   AA          TAX
0E82-   AA          TAX
0E83-   AA          TAX
0E84-   AA          TAX
0E85-   AA          TAX
0E86-   AA          TAX
0E87-   AA          TAX
0E88-   AA          TAX
0E89-   AA          TAX
0E8A-   AA          TAX
0E8B-   AA          TAX
0E8C-   AA          TAX
0E8D-   AA          TAX
0E8E-   AA          TAX
0E8F-   AA          TAX
0E90-   AA          TAX
0E91-   AA          TAX
0E92-   AA          TAX
0E93-   AA          TAX
0E94-   AA          TAX
0E95-   AA          TAX
0E96-   AA          TAX
0E97-   AA          TAX
0E98-   AA          TAX
0E99-   AA          TAX
0E9A-   AA          TAX
0E9B-   8D AA AA    STA   $AAAA
0E9E-   AA          TAX
0E9F-   AA          TAX
0EA0-   AA          TAX
0EA1-   AA          TAX
0EA2-   AA          TAX
0EA3-   AA          TAX
0EA4-   AA          TAX
0EA5-   AA          TAX
0EA6-   AA          TAX
0EA7-   AA          TAX
0EA8-   AA          TAX
0EA9-   AA          TAX
0EAA-   AA          TAX
0EAB-   AA          TAX
0EAC-   AA          TAX
0EAD-   AA          TAX
0EAE-   AA          TAX
0EAF-   AA          TAX
0EB0-   AA          TAX
0EB1-   AA          TAX
0EB2-   AA          TAX
0EB3-   AA          TAX
0EB4-   AA          TAX
0EB5-   AA          TAX
0EB6-   AA          TAX
0EB7-   AA          TAX
0EB8-   AA          TAX
0EB9-   AA          TAX
0EBA-   AA          TAX
0EBB-   AA          TAX
0EBC-   8D AA 8D    STA   $8DAA
0EBF-   A0 DF       LDY   #$DF
0EC1-   D0 D2       BNE   $0E95
0EC3-   CE D4 A0    DEC   $A0D4
0EC6-   A2 20       LDX   #$20
0EC8-   A2 AC       LDX   #$AC
0ECA-   B8          CLV
0ECB-   C4 B8       CPY   $B8
0ECD-   C4 B8       CPY   $B8
0ECF-   C4 B8       CPY   $B8
0ED1-   C4 B8       CPY   $B8
0ED3-   C4 8D       CPY   $8D
0ED5-   A0 DF       LDY   #$DF
0ED7-   D0 D2       BNE   $0EAB
0ED9-   CE D4 A0    DEC   $A0D4
0EDC-   A2 C6       LDX   #$C6
0EDE-   C9 CC       CMP   #$CC
0EE0-   C5 20       CMP   $20
0EE2-   C9 CE       CMP   #$CE
0EE4-   D0 D5       BNE   $0EBB
0EE6-   D4          ???
0EE7-   AF          ???
0EE8-   CF          ???
0EE9-   D5 D4       CMP   $D4,X
0EEB-   D0 D5       BNE   $0EC2
0EED-   D4          ???
0EEE-   20 CD C1    JSR   $C1CD
0EF1-   C3          ???
0EF2-   D2 CF       CMP   ($CF)
0EF4-   D3          ???
0EF5-   A2 AC       LDX   #$AC
0EF7-   B8          CLV
0EF8-   C4 8D       CPY   $8D
0EFA-   A0 DF       LDY   #$DF
0EFC-   D0 D2       BNE   $0ED0
0EFE-   CE D4 A0    DEC   $A0D4
0F01-   A2 AD       LDX   #$AD
0F03-   AD AD AD    LDA   $ADAD
0F06-   AD AD AD    LDA   $ADAD
0F09-   AD AD AD    LDA   $ADAD
0F0C-   AD AD AD    LDA   $ADAD
0F0F-   AD AD AD    LDA   $ADAD
0F12-   AD AD AD    LDA   $ADAD
0F15-   AD AD AD    LDA   $ADAD
0F18-   AD AD A2    LDA   $A2AD
0F1B-   AC B8 C4    LDY   $C4B8
0F1E-   B8          CLV
0F1F-   C4 8D       CPY   $8D
0F21-   A0 DF       LDY   #$DF
0F23-   D0 D2       BNE   $0EF7
0F25-   CE D4 A0    DEC   $A0D4
0F28-   A2 D4       LDX   #$D4
0F2A-   C8          INY
0F2B-   C5 20       CMP   $20
0F2D-   C2          ???
0F2E-   D3          ???
0F2F-   C1 D6       CMP   ($D6,X)
0F31-   C5 20       CMP   $20
0F33-   CD C1 C3    CMP   $C3C1
0F36-   D2 CF       CMP   ($CF)
0F38-   20 D3 C1    JSR   $C1D3
0F3B-   D6 C5       DEC   $C5,X
0F3D-   D3          ???
0F3E-   20 D4 C8    JSR   $C8D4
0F41-   C5 20       CMP   $20
0F43-   C7          ???
0F44-   C9 D6       CMP   #$D6
0F46-   C5 CE       CMP   $CE
0F48-   A2 AC       LDX   #$AC
0F4A-   B8          CLV
0F4B-   C4 8D       CPY   $8D
0F4D-   A0 DF       LDY   #$DF
0F4F-   D0 D2       BNE   $0F23
0F51-   CE D4 A0    DEC   $A0D4
0F54-   A2 C1       LDX   #$C1
0F56-   C4 C4       CPY   $C4
0F58-   D2 C5       CMP   ($C5)
0F5A-   D3          ???
0F5B-   D3          ???
0F5C-   20 D2 C1    JSR   $C1D2
0F5F-   CE C7 C5    DEC   $C5C7
0F62-   20 D5 CE    JSR   $CED5
0F65-   C4 C5       CPY   $C5
0F67-   D2 20       CMP   ($20)
0F69-   D4          ???
0F6A-   C8          INY
0F6B-   C5 20       CMP   $20
0F6D-   D3          ???
0F6E-   D0 C5       BNE   $0F35
0F70-   C3          ???
0F71-   C9 C6       CMP   #$C6
0F73-   C9 C5       CMP   #$C5
0F75-   C4 A2       CPY   $A2
0F77-   AC B8 C4    LDY   $C4B8
0F7A-   8D A0 DF    STA   $DFA0
0F7D-   D0 D2       BNE   $0F51
0F7F-   CE D4 A0    DEC   $A0D4
0F82-   A2 C2       LDX   #$C2
0F84-   C9 CE       CMP   #$CE
0F86-   C1 D2       CMP   ($D2,X)
0F88-   D9 20 C6    CMP   $C620,Y
0F8B-   C9 CC       CMP   #$CC
0F8D-   C5 AE       CMP   $AE
0F8F-   20 D4 C8    JSR   $C8D4
0F92-   C5 20       CMP   $20
0F94-   C1 D2       CMP   ($D2,X)
0F96-   C7          ???
0F97-   D5 CD       CMP   $CD,X
0F99-   C5 CE       CMP   $CE
0F9B-   D4          ???
0F9C-   20 C9 D3    JSR   $D3C9
0F9F-   20 D3 C9    JSR   $C9D3
0FA2-   CD D0 CC    CMP   $CCD0
0FA5-   D9 A2 AC    CMP   $ACA2,Y
0FA8-   B8          CLV
0FA9-   C4 8D       CPY   $8D
0FAB-   A0 DF       LDY   #$DF
0FAD-   D0 D2       BNE   $0F81
0FAF-   CE D4 A0    DEC   $A0D4
0FB2-   A2 C1       LDX   #$C1
0FB4-   20 D3 D4    JSR   $D4D3
0FB7-   D2 C9       CMP   ($C9)
0FB9-   CE C7 20    DEC   $20C7
0FBC-   D4          ???
0FBD-   C8          INY
0FBE-   C1 D4       CMP   ($D4,X)
0FC0-   20 D7 CF    JSR   $CFD7
0FC3-   D5 CC       CMP   $CC,X
0FC5-   C4 20       CPY   $20
0FC7-   CD C1 D4    CMP   $D4C1
0FCA-   C3          ???
0FCB-   C8          INY
0FCC-   20 D4 C8    JSR   $C8D4
0FCF-   C5 20       CMP   $20
0FD1-   C1 D2       CMP   ($D2,X)
0FD3-   C7          ???
0FD4-   D5 CD       CMP   $CD,X
0FD6-   C5 CE       CMP   $CE
0FD8-   D4          ???
0FD9-   D3          ???
0FDA-   A2 AC       LDX   #$AC
0FDC-   B8          CLV
0FDD-   C4 8D       CPY   $8D
0FDF-   A0 DF       LDY   #$DF
0FE1-   D0 D2       BNE   $0FB5
0FE3-   CE D4 A0    DEC   $A0D4
0FE6-   A2 CF       LDX   #$CF
0FE8-   C6 20       DEC   $20
0FEA-   C1 20       CMP   ($20,X)
0FEC-   D4          ???
0FED-   D9 D0 C9    CMP   $C9D0,Y
0FF0-   C3          ???
0FF1-   C1 CC       CMP   ($CC,X)
0FF3-   20 C2 D3    JSR   $D3C2
0FF6-   C1 D6       CMP   ($D6,X)
0FF8-   C5 20       CMP   $20
0FFA-   D3          ???
0FFB-   D4          ???
0FFC-   C1 D4       CMP   ($D4,X)
0FFE-   C5 CD       CMP   $CD
1000-   C5 CE       CMP   $CE
1002-   D4          ???
1003-   20 C9 CE    JSR   $CEC9
1006-   20 C4 CF    JSR   $CFC4
1009-   D3          ???
100A-   AE A2 AC    LDX   $ACA2
100D-   B8          CLV
100E-   C4 B8       CPY   $B8
1010-   C4 8D       CPY   $8D
1012-   A0 DF       LDY   #$DF
1014-   D0 D2       BNE   $0FE8
1016-   CE D4 A0    DEC   $A0D4
1019-   A2 C2       LDX   #$C2
101B-   D3          ???
101C-   C1 D6       CMP   ($D6,X)
101E-   C5 20       CMP   $20
1020-   A7          ???
1021-   D4          ???
1022-   C5 D3       CMP   $D3
1024-   D4          ???
1025-   AC C1 A4    LDY   $A4C1
1028-   B8          CLV
1029-   B0 B0       BCS   $0FDB
102B-   AC CC A4    LDY   $A4CC
102E-   B1 B0       LDA   ($B0),Y
1030-   B0 A7       BCS   $0FD9
1032-   20 D3 C1    JSR   $C1D3
1035-   D6 C5       DEC   $C5,X
1037-   D3          ???
1038-   20 D4 C8    JSR   $C8D4
103B-   C5 A2       CMP   $A2
103D-   AC B8 C4    LDY   $C4B8
1040-   8D A0 DF    STA   $DFA0
1043-   D0 D2       BNE   $1017
1045-   CE D4 A0    DEC   $A0D4
1048-   A2 A4       LDX   #$A4
104A-   B1 B0       LDA   ($B0),Y
104C-   B0 20       BCS   $106E
104E-   C2          ???
104F-   D9 D4 C5    CMP   $C5D4,Y
1052-   D3          ???
1053-   20 CC CF    JSR   $CFCC
1056-   C3          ???
1057-   C1 D4       CMP   ($D4,X)
1059-   C5 C4       CMP   $C4
105B-   20 C1 D4    JSR   $D4C1
105E-   20 A4 B8    JSR   $B8A4
1061-   B0 B0       BCS   $1013
1063-   20 C9 CE    JSR   $CEC9
1066-   20 D4 C8    JSR   $C8D4
1069-   C5 20       CMP   $20
106B-   C6 C9       DEC   $C9
106D-   CC C5 A2    CPY   $A2C5
1070-   AC B8 C4    LDY   $C4B8
1073-   8D A0 DF    STA   $DFA0
1076-   D0 D2       BNE   $104A
1078-   CE D4 A0    DEC   $A0D4
107B-   A2 D4       LDX   #$D4
107D-   C5 D3       CMP   $D3
107F-   D4          ???
1080-   AE A2 AC    LDX   $ACA2
1083-   B8          CLV
1084-   C4 B8       CPY   $B8
1086-   C4 8D       CPY   $8D
1088-   A0 DF       LDY   #$DF
108A-   D0 D2       BNE   $105E
108C-   CE D4 A0    DEC   $A0D4
108F-   A2 CC       LDX   #$CC
1091-   C5 D4       CMP   $D4
1093-   A7          ???
1094-   D3          ???
1095-   20 D0 D5    JSR   $D5D0
1098-   D4          ???
1099-   20 D3 CF    JSR   $CFD3
109C-   CD C5 D4    CMP   $D4C5
109F-   C8          INY
10A0-   C9 CE       CMP   #$CE
10A2-   C7          ???
10A3-   20 C9 CE    JSR   $CEC9
10A6-   D4          ???
10A7-   CF          ???
10A8-   20 A4 B3    JSR   $B3A4
10AB-   B0 B0       BCS   $105D
10AD-   20 D4 CF    JSR   $CFD4
10B0-   A2 AC       LDX   #$AC
10B2-   B8          CLV
10B3-   C4 8D       CPY   $8D
10B5-   A0 DF       LDY   #$DF
10B7-   D0 D2       BNE   $108B
10B9-   CE D4 A0    DEC   $A0D4
10BC-   A2 D4       LDX   #$D4
10BE-   C5 D3       CMP   $D3
10C0-   D4          ???
10C1-   20 C9 D4    JSR   $D4C9
10C4-   20 CF D5    JSR   $D5CF
10C7-   D4          ???
10C8-   AE A2 AC    LDX   $ACA2
10CB-   B8          CLV
10CC-   C4 B8       CPY   $B8
10CE-   C4 8D       CPY   $8D
10D0-   A0 CC       LDY   #$CC
10D2-   C4 D9       CPY   $D9
10D4-   A0 A3       LDY   #$A3
10D6-   B0 8D       BCS   $1065
10D8-   CC D0 8D    CPY   $8DD0
10DB-   A0 D4       LDY   #$D4
10DD-   D9 C1 8D    CMP   $8DC1,Y
10E0-   A0 D3       LDY   #$D3
10E2-   D4          ???
10E3-   C1 A0       CMP   ($A0,X)
10E5-   A4 B8       LDY   $B8
10E7-   B0 B0       BCS   $1099
10E9-   AC D9 8D    LDY   $8DD9
10EC-   A0 C9       LDY   #$C9
10EE-   CE D9 8D    DEC   $8DD9
10F1-   A0 C3       LDY   #$C3
10F3-   D0 D9       BNE   $10CE
10F5-   A0 A3       LDY   #$A3
10F7-   A4 B1       LDY   $B1
10F9-   B0 B0       BCS   $10AB
10FB-   8D A0 C2    STA   $C2A0
10FE-   CE C5 A0    DEC   $A0C5
1101-   CC D0 8D    CPY   $8DD0
1104-   A0 DF       LDY   #$DF
1106-   D7          ???
1107-   C1 C9       CMP   ($C9,X)
1109-   D4          ???
110A-   8D A0 C4    STA   $C4A0
110D-   D5 CD       CMP   $CD,X
110F-   D0 A0       BNE   $10B1
1111-   A3          ???
1112-   A4 B8       LDY   $B8
1114-   B0 B0       BCS   $10C6
1116-   BB          ???
1117-   A3          ???
1118-   A4 B1       LDY   $B1
111A-   B0 B0       BCS   $10CC
111C-   8D A0 DF    STA   $DFA0
111F-   D7          ???
1120-   C1 C9       CMP   ($C9,X)
1122-   D4          ???
1123-   8D A0 DF    STA   $DFA0
1126-   D0 D2       BNE   $10FA
1128-   CE D4 A0    DEC   $A0D4
112B-   A2 20       LDX   #$20
112D-   A2 AC       LDX   #$AC
112F-   B8          CLV
1130-   C4 B8       CPY   $B8
1132-   C4 8D       CPY   $8D
1134-   A0 DF       LDY   #$DF
1136-   D0 D2       BNE   $110A
1138-   CE D4 20    DEC   $20D4
113B-   A2 C2       LDX   #$C2
113D-   D3          ???
113E-   C1 D6       CMP   ($D6,X)
1140-   C5 20       CMP   $20
1142-   A7          ???
1143-   D4          ???
1144-   C5 D3       CMP   $D3
1146-   D4          ???
1147-   AC C1 A4    LDY   $A4C1
114A-   B8          CLV
114B-   B0 B0       BCS   $10FD
114D-   AC CC A4    LDY   $A4CC
1150-   B1 B0       LDA   ($B0),Y
1152-   B0 A7       BCS   $10FB
1154-   AE AE AE    LDX   $AEAE
1157-   AE A2 8D    LDX   $8DA2
115A-   A0 C2       LDY   #$C2
115C-   D3          ???
115D-   C1 D6       CMP   ($D6,X)
115F-   C5 20       CMP   $20
1161-   A2 D4       LDX   #$D4
1163-   C5 D3       CMP   $D3
1165-   D4          ???
1166-   AC C1 A4    LDY   $A4C1
1169-   B8          CLV
116A-   B0 B0       BCS   $111C
116C-   AC CC A4    LDY   $A4CC
116F-   B1 B0       LDA   ($B0),Y
1171-   B0 A2       BCS   $1115
1173-   8D A0 DF    STA   $DFA0
1176-   D0 D2       BNE   $114A
1178-   CE D4 A0    DEC   $A0D4
117B-   A2 C4       LDX   #$C4
117D-   CF          ???
117E-   CE C5 A1    DEC   $A1C5
1181-   A2 AC       LDX   #$AC
1183-   B8          CLV
1184-   C4 B8       CPY   $B8
1186-   C4 8D       CPY   $8D
1188-   A0 DF       LDY   #$DF
118A-   D0 D2       BNE   $115E
118C-   CE D4 A0    DEC   $A0D4
118F-   A2 CE       LDX   #$CE
1191-   CF          ???
1192-   D7          ???
1193-   20 CC C5    JSR   $C5CC
1196-   D4          ???
1197-   A7          ???
1198-   D3          ???
1199-   20 C3 CC    JSR   $CCC3
119C-   C5 C1       CMP   $C1
119E-   D2 20       CMP   ($20)
11A0-   A4 B1       LDY   $B1
11A2-   B0 B0       BCS   $1154
11A4-   20 C2 D9    JSR   $D9C2
11A7-   D4          ???
11A8-   C5 D3       CMP   $D3
11AA-   20 C1 D4    JSR   $D4C1
11AD-   A2 AC       LDX   #$AC
11AF-   B8          CLV
11B0-   C4 8D       CPY   $8D
11B2-   A0 DF       LDY   #$DF
11B4-   D0 D2       BNE   $1188
11B6-   CE D4 A0    DEC   $A0D4
11B9-   A2 A4       LDX   #$A4
11BB-   B8          CLV
11BC-   B0 B0       BCS   $116E
11BE-   20 C2 C5    JSR   $C5C2
11C1-   C6 CF       DEC   $CF
11C3-   D2 C5       CMP   ($C5)
11C5-   20 D7 C5    JSR   $C5D7
11C8-   20 D2 C5    JSR   $C5D2
11CB-   CC CF C1    CPY   $C1CF
11CE-   C4 20       CPY   $20
11D0-   C9 D4       CMP   #$D4
11D2-   20 D7 C9    JSR   $C9D7
11D5-   D4          ???
11D6-   C8          INY
11D7-   20 C2 CC    JSR   $CCC2
11DA-   CF          ???
11DB-   C1 C4       CMP   ($C4,X)
11DD-   AE A2 AC    LDX   $ACA2
11E0-   B8          CLV
11E1-   C4 B8       CPY   $B8
11E3-   C4 8D       CPY   $8D
11E5-   A0 CC       LDY   #$CC
11E7-   C4 D9       CPY   $D9
11E9-   A0 A3       LDY   #$A3
11EB-   B0 8D       BCS   $117A
11ED-   CC D0 B2    CPY   $B2D0
11F0-   8D A0 CC    STA   $CCA0
11F3-   C4 C1       CPY   $C1
11F5-   A0 A3       LDY   #$A3
11F7-   B0 8D       BCS   $1186
11F9-   A0 D3       LDY   #$D3
11FB-   D4          ???
11FC-   C1 A0       CMP   ($A0,X)
11FE-   A4 B8       LDY   $B8
1200-   B0 B0       BCS   $11B2
1202-   AC D9 8D    LDY   $8DD9
1205-   A0 C9       LDY   #$C9
1207-   CE D9 8D    DEC   $8DD9
120A-   A0 C3       LDY   #$C3
120C-   D0 D9       BNE   $11E7
120E-   A0 A3       LDY   #$A3
1210-   A4 B1       LDY   $B1
1212-   B0 B0       BCS   $11C4
1214-   8D A0 C2    STA   $C2A0
1217-   CE C5 A0    DEC   $A0C5
121A-   CC D0 B2    CPY   $B2D0
121D-   8D A0 C4    STA   $C4A0
1220-   D5 CD       CMP   $CD,X
1222-   D0 A0       BNE   $11C4
1224-   A3          ???
1225-   A4 B8       LDY   $B8
1227-   B0 B0       BCS   $11D9
1229-   BB          ???
122A-   A3          ???
122B-   A4 B1       LDY   $B1
122D-   B0 B0       BCS   $11DF
122F-   8D AA 8D    STA   $8DAA
1232-   A0 DF       LDY   #$DF
1234-   D0 D2       BNE   $1208
1236-   CE D4 A0    DEC   $A0D4
1239-   A2 20       LDX   #$20
123B-   A2 AC       LDX   #$AC
123D-   B8          CLV
123E-   C4 B8       CPY   $B8
1240-   C4 8D       CPY   $8D
1242-   A0 DF       LDY   #$DF
1244-   D0 D2       BNE   $1218
1246-   CE D4 A0    DEC   $A0D4
1249-   A2 CE       LDX   #$CE
124B-   CF          ???
124C-   D7          ???
124D-   20 D7 C5    JSR   $C5D7
1250-   20 C3 C1    JSR   $C1C3
1253-   CE 20 C2    DEC   $C220
1256-   CC CF C1    CPY   $C1CF
1259-   C4 20       CPY   $20
125B-   D4          ???
125C-   C5 D3       CMP   $D3
125E-   D4          ???
125F-   20 D4 CF    JSR   $CFD4
1262-   20 C7 C5    JSR   $C5C7
1265-   D4          ???
1266-   20 A4 B8    JSR   $B8A4
1269-   B0 B0       BCS   $121B
126B-   A2 AC       LDX   #$AC
126D-   B8          CLV
126E-   C4 8D       CPY   $8D
1270-   A0 DF       LDY   #$DF
1272-   D0 D2       BNE   $1246
1274-   CE D4 A0    DEC   $A0D4
1277-   A2 C2       LDX   #$C2
1279-   C1 C3       CMP   ($C3,X)
127B-   CB          ???
127C-   20 C9 CE    JSR   $CEC9
127F-   D4          ???
1280-   CF          ???
1281-   20 D4 C8    JSR   $C8D4
1284-   C5 20       CMP   $20
1286-   D3          ???
1287-   D4          ???
1288-   C1 D4       CMP   ($D4,X)
128A-   C5 20       CMP   $20
128C-   D7          ???
128D-   C5 20       CMP   $20
128F-   D0 D5       BNE   $1266
1291-   D4          ???
1292-   20 C9 D4    JSR   $D4C9
1295-   AE A2 AC    LDX   $ACA2
1298-   B8          CLV
1299-   C4 B8       CPY   $B8
129B-   C4 8D       CPY   $8D
129D-   A0 DF       LDY   #$DF
129F-   D0 D2       BNE   $1273
12A1-   CE D4 A0    DEC   $A0D4
12A4-   A2 C2       LDX   #$C2
12A6-   CC CF C1    CPY   $C1CF
12A9-   C4 20       CPY   $20
12AB-   A7          ???
12AC-   D4          ???
12AD-   C5 D3       CMP   $D3
12AF-   D4          ???
12B0-   A7          ???
12B1-   AE AE AE    LDX   $AEAE
12B4-   A2 AC       LDX   #$AC
12B6-   B8          CLV
12B7-   C4 8D       CPY   $8D
12B9-   A0 DF       LDY   #$DF
12BB-   D7          ???
12BC-   C1 C9       CMP   ($C9,X)
12BE-   D4          ???
12BF-   8D A0 C2    STA   $C2A0
12C2-   CC CF C1    CPY   $C1CF
12C5-   C4 A0       CPY   $A0
12C7-   A2 D4       LDX   #$D4
12C9-   C5 D3       CMP   $D3
12CB-   D4          ???
12CC-   A2 8D       LDX   #$8D
12CE-   A0 DF       LDY   #$DF
12D0-   D0 D2       BNE   $12A4
12D2-   CE D4 A0    DEC   $A0D4
12D5-   A2 20       LDX   #$20
12D7-   A2 AC       LDX   #$AC
12D9-   B8          CLV
12DA-   C4 B8       CPY   $B8
12DC-   C4 8D       CPY   $8D
12DE-   A0 DF       LDY   #$DF
12E0-   D0 D2       BNE   $12B4
12E2-   CE D4 A0    DEC   $A0D4
12E5-   A2 C4       LDX   #$C4
12E7-   CF          ???
12E8-   CE C5 A1    DEC   $A1C5
12EB-   A2 AC       LDX   #$AC
12ED-   B8          CLV
12EE-   C4 B8       CPY   $B8
12F0-   C4 8D       CPY   $8D
12F2-   A0 C4       LDY   #$C4
12F4-   D5 CD       CMP   $CD,X
12F6-   D0 A0       BNE   $1298
12F8-   A3          ???
12F9-   A4 B0       LDY   $B0
12FB-   B8          CLV
12FC-   B0 B0       BCS   $12AE
12FE-   BB          ???
12FF-   A3          ???
1300-   A4 B1       LDY   $B1
1302-   B0 B0       BCS   $12B4
1304-   8D A0 DF    STA   $DFA0
1307-   D0 D2       BNE   $12DB
1309-   CE D4 A0    DEC   $A0D4
130C-   A2 20       LDX   #$20
130E-   A2 AC       LDX   #$AC
1310-   B8          CLV
1311-   C4 B8       CPY   $B8
1313-   C4 8D       CPY   $8D
1315-   A0 DF       LDY   #$DF
1317-   D7          ???
1318-   C1 C9       CMP   ($C9,X)
131A-   D4          ???
131B-   8D AA 8D    STA   $8DAA
131E-   A0 DF       LDY   #$DF
1320-   D0 D2       BNE   $12F4
1322-   CE D4 A0    DEC   $A0D4
1325-   A2 D4       LDX   #$D4
1327-   C8          INY
1328-   C5 20       CMP   $20
132A-   C3          ???
132B-   CD C4 20    CMP   $20C4
132E-   CD C1 C3    CMP   $C3C1
1331-   D2 CF       CMP   ($CF)
1333-   20 D3 C9    JSR   $C9D3
1336-   CD D0 CC    CMP   $CCD0
1339-   D9 20 C5    CMP   $C520,Y
133C-   D8          CLD
133D-   C5 C3       CMP   $C3
133F-   D5 D4       CMP   $D4,X
1341-   C5 D3       CMP   $D3
1343-   20 C1 A2    JSR   $A2C1
1346-   AC B8 C4    LDY   $C4B8
1349-   8D A0 DF    STA   $DFA0
134C-   D0 D2       BNE   $1320
134E-   CE D4 A0    DEC   $A0D4
1351-   A2 C4       LDX   #$C4
1353-   CF          ???
1354-   D3          ???
1355-   20 C3 CF    JSR   $CFC3
1358-   CD CD C1    CMP   $C1CD
135B-   CE C4 AC    DEC   $ACC4
135E-   20 C1 CC    JSR   $CCC1
1361-   CF          ???
1362-   CE C7 20    DEC   $20C7
1365-   D7          ???
1366-   C9 D4       CMP   #$D4
1368-   C8          INY
1369-   20 C1 CE    JSR   $CEC1
136C-   D9 20 C1    CMP   $C120,Y
136F-   D2 C7       CMP   ($C7)
1371-   D5 CD       CMP   $CD,X
1373-   C5 CE       CMP   $CE
1375-   D4          ???
1376-   D3          ???
1377-   A2 AC       LDX   #$AC
1379-   B8          CLV
137A-   C4 8D       CPY   $8D
137C-   A0 DF       LDY   #$DF
137E-   D0 D2       BNE   $1352
1380-   CE D4 A0    DEC   $A0D4
1383-   A2 D0       LDX   #$D0
1385-   C1 D3       CMP   ($D3,X)
1387-   D3          ???
1388-   C5 C4       CMP   $C4
138A-   20 D4 CF    JSR   $CFD4
138D-   20 C9 D4    JSR   $D4C9
1390-   AE 20 C3    LDX   $C320
1393-   CD C4 20    CMP   $20C4
1396-   A7          ???
1397-   C3          ???
1398-   C1 D4       CMP   ($D4,X)
139A-   C1 CC       CMP   ($CC,X)
139C-   CF          ???
139D-   C7          ???
139E-   A7          ???
139F-   AC 20 C6    LDY   $C620
13A2-   CF          ???
13A3-   D2 20       CMP   ($20)
13A5-   C9 CE       CMP   #$CE
13A7-   D3          ???
13A8-   D4          ???
13A9-   C1 CE       CMP   ($CE,X)
13AB-   C3          ???
13AC-   C5 AC       CMP   $AC
13AE-   A2 AC       LDX   #$AC
13B0-   B8          CLV
13B1-   C4 8D       CPY   $8D
13B3-   A0 DF       LDY   #$DF
13B5-   D0 D2       BNE   $1389
13B7-   CE D4 A0    DEC   $A0D4
13BA-   A2 D2       LDX   #$D2
13BC-   C5 D4       CMP   $D4
13BE-   D5 D2       CMP   $D2,X
13C0-   CE D3 BA    DEC   $BAD3
13C3-   A2 AC       LDX   #$AC
13C5-   B8          CLV
13C6-   C4 B8       CPY   $B8
13C8-   C4 8D       CPY   $8D
13CA-   A0 DF       LDY   #$DF
13CC-   D7          ???
13CD-   C1 C9       CMP   ($C9,X)
13CF-   D4          ???
13D0-   8D A0 C3    STA   $C3A0
13D3-   CD C4 A0    CMP   $A0C4
13D6-   A2 C3       LDX   #$C3
13D8-   C1 D4       CMP   ($D4,X)
13DA-   C1 CC       CMP   ($CC,X)
13DC-   CF          ???
13DD-   C7          ???
13DE-   A2 8D       LDX   #$8D
13E0-   A0 DF       LDY   #$DF
13E2-   D7          ???
13E3-   C1 C9       CMP   ($C9,X)
13E5-   D4          ???
13E6-   8D AA 8D    STA   $8DAA
13E9-   AA          TAX
13EA-   AA          TAX
13EB-   20 C9 C6    JSR   $C6C9
13EE-   20 D7 C5    JSR   $C5D7
13F1-   20 C1 D2    JSR   $D2C1
13F4-   C5 20       CMP   $20
13F6-   D4          ???
13F7-   CF          ???
13F8-   20 D2 C5    JSR   $C5D2
13FB-   C1 C4       CMP   ($C4,X)
13FD-   20 CF D2    JSR   $D2CF
1400-   20 D7 D2    JSR   $D2D7
1403-   C9 D4       CMP   #$D4
1405-   C5 20       CMP   $20
1407-   C6 C9       DEC   $C9
1409-   CC C5 D3    CPY   $D3C5
140C-   AC 20 D7    LDY   $D720
140F-   C5 20       CMP   $20
1411-   C8          INY
1412-   C1 D6       CMP   ($D6,X)
1414-   C5 20       CMP   $20
1416-   D4          ???
1417-   CF          ???
1418-   20 C6 CF    JSR   $CFC6
141B-   CF          ???
141C-   CC 8D AA    CPY   $AA8D
141F-   AA          TAX
1420-   20 D4 C8    JSR   $C8D4
1423-   C5 20       CMP   $20
1425-   C3          ???
1426-   CF          ???
1427-   CD D0 D5    CMP   $D5D0
142A-   D4          ???
142B-   C5 D2       CMP   $D2
142D-   20 D4 CF    JSR   $CFD4
1430-   20 D4 C8    JSR   $C8D4
1433-   C9 CE       CMP   #$CE
1435-   CB          ???
1436-   20 C9 D4    JSR   $D4C9
1439-   A7          ???
143A-   D3          ???
143B-   20 C9 CE    JSR   $CEC9
143E-   20 C1 D0    JSR   $D0C1
1441-   D0 CC       BNE   $140F
1443-   C5 D3       CMP   $D3
1445-   CF          ???
1446-   C6 D4       DEC   $D4
1448-   20 CD CF    JSR   $CFCD
144B-   C4 C5       CPY   $C5
144D-   AE 20 D4    LDX   $D420
1450-   C8          INY
1451-   C9 D3       CMP   #$D3
1453-   8D AA AA    STA   $AAAA
1456-   20 C9 D3    JSR   $D3C9
1459-   20 C1 C3    JSR   $C3C1
145C-   C3          ???
145D-   CF          ???
145E-   CD D0 CC    CMP   $CCD0
1461-   C9 D3       CMP   #$D3
1463-   C8          INY
1464-   C5 C4       CMP   $C4
1466-   20 D7 C9    JSR   $C9D7
1469-   D4          ???
146A-   C8          INY
146B-   20 D4 C8    JSR   $C8D4
146E-   C5 20       CMP   $20
1470-   C1 CD       CMP   ($CD,X)
1472-   CF          ???
1473-   C4 C5       CPY   $C5
1475-   20 CD C1    JSR   $C1CD
1478-   C3          ???
1479-   D2 CF       CMP   ($CF)
147B-   AE 20 D7    LDX   $D720
147E-   C9 D4       CMP   #$D4
1480-   C8          INY
1481-   20 C2 C9    JSR   $C9C2
1484-   CE D3 C1    DEC   $C1D3
1487-   D6 C5       DEC   $C5,X
1489-   8D AA AA    STA   $AAAA
148C-   20 C1 CE    JSR   $CEC1
148F-   C4 20       CPY   $20
1491-   C2          ???
1492-   C9 CE       CMP   #$CE
1494-   CC CF C1    CPY   $C1CF
1497-   C4 AC       CPY   $AC
1499-   20 D4 C8    JSR   $C8D4
149C-   C9 D3       CMP   #$D3
149E-   20 C9 D3    JSR   $D3C9
14A1-   20 C1 CC    JSR   $CCC1
14A4-   D2 C5       CMP   ($C5)
14A6-   C1 C4       CMP   ($C4,X)
14A8-   D9 20 C4    CMP   $C420,Y
14AB-   CF          ???
14AC-   CE C5 AC    DEC   $ACC5
14AF-   20 D3 CF    JSR   $CFD3
14B2-   20 D4 C5    JSR   $C5D4
14B5-   C3          ???
14B6-   C8          INY
14B7-   CE C9 C3    DEC   $C3C9
14BA-   C1 CC       CMP   ($CC,X)
14BC-   CC D9 8D    CPY   $8DD9
14BF-   AA          TAX
14C0-   AA          TAX
14C1-   20 D7 C5    JSR   $C5D7
14C4-   20 C4 CF    JSR   $CFC4
14C7-   CE A7 D4    DEC   $D4A7
14CA-   20 C8 C1    JSR   $C1C8
14CD-   D6 C5       DEC   $C5,X
14CF-   20 D4 CF    JSR   $CFD4
14D2-   20 C4 CF    JSR   $CFC4
14D5-   20 C9 D4    JSR   $D4C9
14D8-   20 C8 C5    JSR   $C5C8
14DB-   D2 C5       CMP   ($C5)
14DD-   AE 20 C8    LDX   $C820
14E0-   CF          ???
14E1-   D7          ???
14E2-   C5 D6       CMP   $D6
14E4-   C5 D2       CMP   $D2
14E6-   AC 20 D4    LDY   $D420
14E9-   C8          INY
14EA-   C5 20       CMP   $20
14EC-   C3          ???
14ED-   CD C4 8D    CMP   $8DC4
14F0-   AA          TAX
14F1-   AA          TAX
14F2-   20 D2 CF    JSR   $CFD2
14F5-   D5 D4       CMP   $D4,X
14F7-   C9 CE       CMP   #$CE
14F9-   C5 20       CMP   $20
14FB-   C4 CF       CPY   $CF
14FD-   C5 D3       CMP   $D3
14FF-   CE A7 D4    DEC   $D4A7
1502-   20 D3 C5    JSR   $C5D3
1505-   D4          ???
1506-   20 C9 D4    JSR   $D4C9
1509-   20 D5 D0    JSR   $D0D5
150C-   20 C1 D5    JSR   $D5C1
150F-   D4          ???
1510-   CF          ???
1511-   CD C1 D4    CMP   $D4C1
1514-   C9 C3       CMP   #$C3
1516-   C1 CC       CMP   ($CC,X)
1518-   CC D9 AC    CPY   $ACD9
151B-   20 D3 CF    JSR   $CFD3
151E-   20 C2 C5    JSR   $C5C2
1521-   20 D3 D5    JSR   $D5D3
1524-   D2 C5       CMP   ($C5)
1526-   8D AA AA    STA   $AAAA
1529-   20 D4 CF    JSR   $CFD4
152C-   20 C9 CE    JSR   $CEC9
152F-   C3          ???
1530-   CC D5 C4    CPY   $C4D5
1533-   C5 20       CMP   $20
1535-   D4          ???
1536-   C8          INY
1537-   C9 D3       CMP   #$D3
1539-   20 C2 C5    JSR   $C5C2
153C-   C6 CF       DEC   $CF
153E-   D2 C5       CMP   ($C5)
1540-   20 CF D0    JSR   $D0CF
1543-   C5 CE       CMP   $CE
1545-   C9 CE       CMP   #$CE
1547-   C7          ???
1548-   20 D4 C5    JSR   $C5D4
154B-   D8          CLD
154C-   D4          ???
154D-   20 C6 C9    JSR   $C9C6
1550-   CC C5 D3    CPY   $D3C5
1553-   AE 8D AA    LDX   $AA8D
1556-   8D A0 C1    STA   $C1A0
1559-   CD CF C4    CMP   $C4CF
155C-   C5 8D       CMP   $8D
155E-   AA          TAX
155F-   8D A0 DF    STA   $DFA0
1562-   D0 D2       BNE   $1536
1564-   CE D4 A0    DEC   $A0D4
1567-   A2 20       LDX   #$20
1569-   A2 AC       LDX   #$AC
156B-   B8          CLV
156C-   C4 B8       CPY   $B8
156E-   C4 B8       CPY   $B8
1570-   C4 8D       CPY   $8D
1572-   A0 DF       LDY   #$DF
1574-   D0 D2       BNE   $1548
1576-   CE D4 A0    DEC   $A0D4
1579-   A2 D4       LDX   #$D4
157B-   D9 D0 C9    CMP   $C9D0,Y
157E-   C3          ???
157F-   C1 CC       CMP   ($CC,X)
1581-   CC D9 AC    CPY   $ACD9
1584-   20 D4 C8    JSR   $C8D4
1587-   C5 20       CMP   $20
1589-   C3          ???
158A-   CD C4 20    CMP   $20C4
158D-   CD C1 C3    CMP   $C3C1
1590-   D2 CF       CMP   ($CF)
1592-   20 C9 D3    JSR   $D3C9
1595-   20 C1 CC    JSR   $CCC1
1598-   D3          ???
1599-   CF          ???
159A-   A2 AC       LDX   #$AC
159C-   B8          CLV
159D-   C4 8D       CPY   $8D
159F-   A0 DF       LDY   #$DF
15A1-   D0 D2       BNE   $1575
15A3-   CE D4 A0    DEC   $A0D4
15A6-   A2 D5       LDX   #$D5
15A8-   D3          ???
15A9-   C5 C4       CMP   $C4
15AB-   20 C6 CF    JSR   $CFC6
15AE-   D2 20       CMP   ($20)
15B0-   D0 D2       BNE   $1584
15B2-   C5 D0       CMP   $D0
15B4-   C1 D2       CMP   ($D2,X)
15B6-   C9 CE       CMP   #$CE
15B8-   C7          ???
15B9-   20 D4 CF    JSR   $CFD4
15BC-   20 D2 C5    JSR   $C5D2
15BF-   C1 C4       CMP   ($C4,X)
15C1-   20 CF D2    JSR   $D2CF
15C4-   20 D7 D2    JSR   $D2D7
15C7-   C9 D4       CMP   #$D4
15C9-   C5 A2       CMP   $A2
15CB-   AC B8 C4    LDY   $C4B8
15CE-   8D A0 DF    STA   $DFA0
15D1-   D0 D2       BNE   $15A5
15D3-   CE D4 A0    DEC   $A0D4
15D6-   A2 D4       LDX   #$D4
15D8-   C5 D8       CMP   $D8
15DA-   D4          ???
15DB-   20 C6 C9    JSR   $C9C6
15DE-   CC C5 D3    CPY   $D3C5
15E1-   AE 20 C8    LDX   $C820
15E4-   CF          ???
15E5-   D7          ???
15E6-   C5 D6       CMP   $D6
15E8-   C5 D2       CMP   $D2
15EA-   AC 20 C2    LDY   $C220
15ED-   C5 C6       CMP   $C6
15EF-   CF          ???
15F0-   D2 C5       CMP   ($C5)
15F2-   20 D4 C8    JSR   $C8D4
15F5-   C9 D3       CMP   #$D3
15F7-   20 C3 C1    JSR   $C1C3
15FA-   CE A2 AC    DEC   $ACA2
15FD-   B8          CLV
15FE-   C4 8D       CPY   $8D
1600-   A0 DF       LDY   #$DF
1602-   D0 D2       BNE   $15D6
1604-   CE D4 A0    DEC   $A0D4
1607-   A2 C2       LDX   #$C2
1609-   C5 20       CMP   $20
160B-   C1 C3       CMP   ($C3,X)
160D-   C3          ???
160E-   CF          ???
160F-   CD D0 CC    CMP   $CCD0
1612-   C9 D3       CMP   #$D3
1614-   C8          INY
1615-   C5 C4       CMP   $C4
1617-   AC 20 D4    LDY   $D420
161A-   C8          INY
161B-   C5 20       CMP   $20
161D-   D4          ???
161E-   CD CF C4    CMP   $C4CF
1621-   C5 20       CMP   $20
1623-   CD C1 C3    CMP   $C3C1
1626-   D2 CF       CMP   ($CF)
1628-   A2 AC       LDX   #$AC
162A-   B8          CLV
162B-   C4 8D       CPY   $8D
162D-   A0 DF       LDY   #$DF
162F-   D0 D2       BNE   $1603
1631-   CE D4 A0    DEC   $A0D4
1634-   A2 CD       LDX   #$CD
1636-   D5 D3       CMP   $D3,X
1638-   D4          ???
1639-   20 C2 C5    JSR   $C5C2
163C-   20 D2 D5    JSR   $D5D2
163F-   CE 20 D4    DEC   $D420
1642-   CF          ???
1643-   20 D4 D2    JSR   $D2D4
1646-   C9 C3       CMP   #$C3
1648-   CB          ???
1649-   20 C1 D0    JSR   $D0C1
164C-   D0 CC       BNE   $161A
164E-   C5 D3       CMP   $D3
1650-   CF          ???
1651-   C6 D4       DEC   $D4
1653-   20 C9 CE    JSR   $CEC9
1656-   D4          ???
1657-   CF          ???
1658-   A2 AC       LDX   #$AC
165A-   B8          CLV
165B-   C4 8D       CPY   $8D
165D-   A0 DF       LDY   #$DF
165F-   D0 D2       BNE   $1633
1661-   CE D4 A0    DEC   $A0D4
1664-   A2 C2       LDX   #$C2
1666-   C5 CC       CMP   $CC
1668-   C9 C5       CMP   #$C5
166A-   D6 C9       DEC   $C9,X
166C-   CE C7 20    DEC   $20C7
166F-   C9 D4       CMP   #$D4
1671-   20 C9 D3    JSR   $D3C9
1674-   CE A7 D4    DEC   $D4A7
1677-   20 C9 CE    JSR   $CEC9
167A-   20 C9 CD    JSR   $CDC9
167D-   CD C5 C4    CMP   $C4C5
1680-   C9 C1       CMP   #$C1
1682-   D4          ???
1683-   C5 20       CMP   $20
1685-   CD CF C4    CMP   $C4CF
1688-   C5 AE       CMP   $AE
168A-   A2 AC       LDX   #$AC
168C-   B8          CLV
168D-   C4 B8       CPY   $B8
168F-   C4 8D       CPY   $8D
1691-   A0 DF       LDY   #$DF
1693-   D0 D2       BNE   $1667
1695-   CE D4 A0    DEC   $A0D4
1698-   A2 D4       LDX   #$D4
169A-   CD CF C4    CMP   $C4CF
169D-   C5 20       CMP   $20
169F-   C8          INY
16A0-   C1 D3       CMP   ($D3,X)
16A2-   20 CE CF    JSR   $CFCE
16A5-   20 C1 D2    JSR   $D2C1
16A8-   C7          ???
16A9-   D5 CD       CMP   $CD,X
16AB-   C5 CE       CMP   $CE
16AD-   D4          ???
16AE-   D3          ???
16AF-   AE 20 D4    LDX   $D420
16B2-   C8          INY
16B3-   D5 D3       CMP   $D3,X
16B5-   AC 20 D4    LDY   $D420
16B8-   C8          INY
16B9-   C5 A2       CMP   $A2
16BB-   AC B8 C4    LDY   $C4B8
16BE-   8D A0 DF    STA   $DFA0
16C1-   D0 D2       BNE   $1695
16C3-   CE D4 A0    DEC   $A0D4
16C6-   A2 C6       LDX   #$C6
16C8-   CF          ???
16C9-   CC CC CF    CPY   $CFCC
16CC-   D7          ???
16CD-   C9 CE       CMP   #$CE
16CF-   C7          ???
16D0-   20 D0 D2    JSR   $D2D0
16D3-   C5 D0       CMP   $D0
16D5-   C1 D2       CMP   ($D2,X)
16D7-   C5 D3       CMP   $D3
16D9-   20 D5 D3    JSR   $D3D5
16DC-   20 D4 CF    JSR   $CFD4
16DF-   20 CF D0    JSR   $D0CF
16E2-   C5 CE       CMP   $CE
16E4-   20 C1 20    JSR   $20C1
16E7-   D4          ???
16E8-   C5 D8       CMP   $D8
16EA-   D4          ???
16EB-   A2 AC       LDX   #$AC
16ED-   B8          CLV
16EE-   C4 8D       CPY   $8D
16F0-   A0 DF       LDY   #$DF
16F2-   D0 D2       BNE   $16C6
16F4-   CE D4 A0    DEC   $A0D4
16F7-   A2 C6       LDX   #$C6
16F9-   C9 CC       CMP   #$CC
16FB-   C5 20       CMP   $20
16FD-   D4          ???
16FE-   CF          ???
16FF-   20 C2 C5    JSR   $C5C2
1702-   20 D7 D2    JSR   $D2D7
1705-   C9 D4       CMP   #$D4
1707-   D4          ???
1708-   C5 CE       CMP   $CE
170A-   20 D4 CF    JSR   $CFD4
170D-   BA          TSX
170E-   A2 AC       LDX   #$AC
1710-   B8          CLV
1711-   C4 B8       CPY   $B8
1713-   C4 8D       CPY   $8D
1715-   A0 DF       LDY   #$DF
1717-   D0 D2       BNE   $16EB
1719-   CE D4 A0    DEC   $A0D4
171C-   A2 D4       LDX   #$D4
171E-   CD C4 CF    CMP   $CFC4
1721-   C5 A2       CMP   $A2
1723-   AC B8 C4    LDY   $C4B8
1726-   8D A0 DF    STA   $DFA0
1729-   D0 D2       BNE   $16FD
172B-   CE D4 A0    DEC   $A0D4
172E-   A2 C3       LDX   #$C3
1730-   CD C4 20    CMP   $20C4
1733-   A7          ???
1734-   CF          ???
1735-   D0 C5       BNE   $16FC
1737-   CE 20 D4    DEC   $D420
173A-   AE D4 C5    LDX   $C5D4
173D-   D8          CLD
173E-   D4          ???
173F-   C6 C9       DEC   $C9
1741-   CC C5 A7    CPY   $A7C5
1744-   A2 AC       LDX   #$AC
1746-   B8          CLV
1747-   C4 8D       CPY   $8D
1749-   A0 DF       LDY   #$DF
174B-   D0 D2       BNE   $171F
174D-   CE D4 A0    DEC   $A0D4
1750-   A2 C3       LDX   #$C3
1752-   CD C4 20    CMP   $20C4
1755-   A7          ???
1756-   D7          ???
1757-   D2 C9       CMP   ($C9)
1759-   D4          ???
175A-   C5 20       CMP   $20
175C-   D4          ???
175D-   AE D4 C5    LDX   $C5D4
1760-   D8          CLD
1761-   D4          ???
1762-   C6 C9       DEC   $C9
1764-   CC C5 A7    CPY   $A7C5
1767-   A2 AC       LDX   #$AC
1769-   B8          CLV
176A-   C4 B8       CPY   $B8
176C-   C4 8D       CPY   $8D
176E-   A0 DF       LDY   #$DF
1770-   D7          ???
1771-   C1 C9       CMP   ($C9,X)
1773-   D4          ???
1774-   8D AA 8D    STA   $8DAA
1777-   A0 DF       LDY   #$DF
1779-   D0 D2       BNE   $174D
177B-   CE D4 A0    DEC   $A0D4
177E-   A2 D7       LDX   #$D7
1780-   C5 20       CMP   $20
1782-   C3          ???
1783-   C1 CE       CMP   ($CE,X)
1785-   20 CE CF    JSR   $CFCE
1788-   D7          ???
1789-   20 D0 D2    JSR   $D2D0
178C-   C9 CE       CMP   #$CE
178E-   D4          ???
178F-   20 D4 CF    JSR   $CFD4
1792-   20 D4 C8    JSR   $C8D4
1795-   C9 D3       CMP   #$D3
1797-   20 C6 C9    JSR   $C9C6
179A-   CC C5 20    CPY   $20C5
179D-   D7          ???
179E-   C9 D4       CMP   #$D4
17A0-   C8          INY
17A1-   A2 AC       LDX   #$AC
17A3-   B8          CLV
17A4-   C4 8D       CPY   $8D
17A6-   A0 DF       LDY   #$DF
17A8-   D0 D2       BNE   $177C
17AA-   CE D4 A0    DEC   $A0D4
17AD-   A2 D4       LDX   #$D4
17AF-   C8          INY
17B0-   C5 20       CMP   $20
17B2-   C6 D0       DEC   $D0
17B4-   D2 CE       CMP   ($CE)
17B6-   20 CD C1    JSR   $C1CD
17B9-   C3          ???
17BA-   D2 CF       CMP   ($CF)
17BC-   AE 20 D4    LDX   $D420
17BF-   C8          INY
17C0-   C9 D3       CMP   #$D3
17C2-   20 CD C1    JSR   $C1CD
17C5-   C3          ???
17C6-   D2 CF       CMP   ($CF)
17C8-   20 C5 C9    JSR   $C9C5
17CB-   D4          ???
17CC-   C8          INY
17CD-   C5 D2       CMP   $D2
17CF-   A2 AC       LDX   #$AC
17D1-   B8          CLV
17D2-   C4 8D       CPY   $8D
17D4-   A0 DF       LDY   #$DF
17D6-   D0 D2       BNE   $17AA
17D8-   CE D4 A0    DEC   $A0D4
17DB-   A2 D0       LDX   #$D0
17DD-   D2 C9       CMP   ($C9)
17DF-   CE D4 D3    DEC   $D3D4
17E2-   20 C1 20    JSR   $20C1
17E5-   C7          ???
17E6-   C9 D6       CMP   #$D6
17E8-   C5 CE       CMP   $CE
17EA-   20 CC C9    JSR   $C9CC
17ED-   CE C5 20    DEC   $20C5
17F0-   CF          ???
17F1-   C6 20       DEC   $20
17F3-   D4          ???
17F4-   C5 D8       CMP   $D8
17F6-   D4          ???
17F7-   20 D4 CF    JSR   $CFD4
17FA-   20 D4 C8    JSR   $C8D4
17FD-   C5 20       CMP   $20
17FF-   C6 C9       DEC   $C9
1801-   CC C5 AC    CPY   $ACC5
1804-   A2 AC       LDX   #$AC
1806-   B8          CLV
1807-   C4 8D       CPY   $8D
1809-   A0 DF       LDY   #$DF
180B-   D0 D2       BNE   $17DF
180D-   CE D4 A0    DEC   $A0D4
1810-   A2 C6       LDX   #$C6
1812-   CF          ???
1813-   CC CC CF    CPY   $CFCC
1816-   D7          ???
1817-   C5 C4       CMP   $C4
1819-   20 C2 D9    JSR   $D9C2
181C-   20 C1 20    JSR   $20C1
181F-   D2 C5       CMP   ($C5)
1821-   D4          ???
1822-   D5 D2       CMP   $D2,X
1824-   CE 20 A8    DEC   $A820
1827-   A4 B8       LDY   $B8
1829-   C4 A9       CPY   $A9
182B-   AC 20 CF    LDY   $CF20
182E-   D2 20       CMP   ($20)
1830-   D0 D2       BNE   $1804
1832-   C9 CE       CMP   #$CE
1834-   D4          ???
1835-   D3          ???
1836-   A2 AC       LDX   #$AC
1838-   B8          CLV
1839-   C4 8D       CPY   $8D
183B-   A0 DF       LDY   #$DF
183D-   D0 D2       BNE   $1811
183F-   CE D4 A0    DEC   $A0D4
1842-   A2 D4       LDX   #$D4
1844-   C8          INY
1845-   C5 20       CMP   $20
1847-   C3          ???
1848-   C8          INY
1849-   C1 D2       CMP   ($D2,X)
184B-   C1 C3       CMP   ($C3,X)
184D-   D4          ???
184E-   C5 D2       CMP   $D2
1850-   D3          ???
1851-   20 C9 CE    JSR   $CEC9
1854-   20 C1 20    JSR   $20C1
1857-   D3          ???
1858-   D4          ???
1859-   D2 C9       CMP   ($C9)
185B-   CE C7 20    DEC   $20C7
185E-   C1 D4       CMP   ($D4,X)
1860-   20 C1 20    JSR   $20C1
1863-   C7          ???
1864-   C9 D6       CMP   #$D6
1866-   C5 CE       CMP   $CE
1868-   A2 AC       LDX   #$AC
186A-   B8          CLV
186B-   C4 8D       CPY   $8D
186D-   A0 DF       LDY   #$DF
186F-   D0 D2       BNE   $1843
1871-   CE D4 A0    DEC   $A0D4
1874-   A2 C1       LDX   #$C1
1876-   C4 C4       CPY   $C4
1878-   D2 C5       CMP   ($C5)
187A-   D3          ???
187B-   D3          ???
187C-   AE 20 C9    LDX   $C920
187F-   CE 20 D4    DEC   $D420
1882-   C8          INY
1883-   C5 20       CMP   $20
1885-   CC C1 D4    CPY   $D4C1
1888-   D4          ???
1889-   C5 D2       CMP   $D2
188B-   20 C3 C1    JSR   $C1C3
188E-   D3          ???
188F-   C5 AC       CMP   $AC
1891-   20 D4 C8    JSR   $C8D4
1894-   C5 20       CMP   $20
1896-   CC C5 CE    CPY   $CEC5
1899-   C7          ???
189A-   D4          ???
189B-   C8          INY
189C-   A2 AC       LDX   #$AC
189E-   B8          CLV
189F-   C4 8D       CPY   $8D
18A1-   A0 DF       LDY   #$DF
18A3-   D0 D2       BNE   $1877
18A5-   CE D4 A0    DEC   $A0D4
18A8-   A2 CF       LDX   #$CF
18AA-   C6 20       DEC   $20
18AC-   D4          ???
18AD-   C8          INY
18AE-   C5 20       CMP   $20
18B0-   D3          ???
18B1-   D4          ???
18B2-   D2 C9       CMP   ($C9)
18B4-   CE C7 20    DEC   $20C7
18B7-   C9 D3       CMP   #$D3
18B9-   20 CE CF    JSR   $CFCE
18BC-   D4          ???
18BD-   20 D0 D2    JSR   $D2D0
18C0-   C5 D3       CMP   $D3
18C2-   C5 D2       CMP   $D2
18C4-   D6 C5       DEC   $C5,X
18C6-   C4 BB       CPY   $BB
18C8-   20 CF CE    JSR   $CECF
18CB-   CC D9 A2    CPY   $A2D9
18CE-   AC B8 C4    LDY   $C4B8
18D1-   8D A0 DF    STA   $DFA0
18D4-   D0 D2       BNE   $18A8
18D6-   CE D4 A0    DEC   $A0D4
18D9-   A2 D4       LDX   #$D4
18DB-   C8          INY
18DC-   C5 20       CMP   $20
18DE-   C1 D3       CMP   ($D3,X)
18E0-   C3          ???
18E1-   C9 C9       CMP   #$C9
18E3-   20 C9 D3    JSR   $D3C9
18E6-   AE A2 AC    LDX   $ACA2
18E9-   B8          CLV
18EA-   C4 B8       CPY   $B8
18EC-   C4 8D       CPY   $8D
18EE-   A0 DF       LDY   #$DF
18F0-   D0 D2       BNE   $18C4
18F2-   CE D4 A0    DEC   $A0D4
18F5-   A2 C6       LDX   #$C6
18F7-   D0 D2       BNE   $18CB
18F9-   CE 20 A7    DEC   $A720
18FC-   C1 CC       CMP   ($CC,X)
18FE-   CC 20 C9    CPY   $C920
1901-   D3          ???
1902-   20 D7 C5    JSR   $C5D7
1905-   CC CC 20    CPY   $20CC
1908-   D4          ???
1909-   C8          INY
190A-   C1 D4       CMP   ($D4,X)
190C-   20 C5 CE    JSR   $CEC5
190F-   C4 D3       CPY   $D3
1911-   20 D7 C5    JSR   $C5D7
1914-   CC CC AE    CPY   $AECC
1917-   A7          ???
1918-   A2 AC       LDX   #$AC
191A-   B8          CLV
191B-   C4 8D       CPY   $8D
191D-   A0 DF       LDY   #$DF
191F-   D0 D2       BNE   $18F3
1921-   CE D4 A0    DEC   $A0D4
1924-   A2 C6       LDX   #$C6
1926-   D0 D2       BNE   $18FA
1928-   CE 20 D2    DEC   $D220
192B-   C5 D4       CMP   $D4
192D-   CF          ???
192E-   D2 D4       CMP   ($D4)
1930-   A2 AC       LDX   #$AC
1932-   B8          CLV
1933-   C4 B8       CPY   $B8
1935-   C4 8D       CPY   $8D
1937-   A0 C3       LDY   #$C3
1939-   CD C4 A0    CMP   $A0C4
193C-   A2 CF       LDX   #$CF
193E-   D0 C5       BNE   $1905
1940-   CE 20 D4    DEC   $D420
1943-   AE D4 C5    LDX   $C5D4
1946-   D8          CLD
1947-   D4          ???
1948-   C6 C9       DEC   $C9
194A-   CC C5 A2    CPY   $A2C5
194D-   8D A0 C3    STA   $C3A0
1950-   CD C4 A0    CMP   $A0C4
1953-   A2 D7       LDX   #$D7
1955-   D2 C9       CMP   ($C9)
1957-   D4          ???
1958-   C5 20       CMP   $20
195A-   D4          ???
195B-   AE D4 C5    LDX   $C5D4
195E-   D8          CLD
195F-   D4          ???
1960-   C6 C9       DEC   $C9
1962-   CC C5 A2    CPY   $A2C5
1965-   8D A0 C6    STA   $C6A0
1968-   D0 D2       BNE   $193C
196A-   CE A0 A2    DEC   $A2A0
196D-   C1 CC       CMP   ($CC,X)
196F-   CC 20 C9    CPY   $C920
1972-   D3          ???
1973-   20 D7 C5    JSR   $C5D7
1976-   CC CC 20    CPY   $20CC
1979-   D4          ???
197A-   C8          INY
197B-   C1 D4       CMP   ($D4,X)
197D-   20 C5 CE    JSR   $CEC5
1980-   C4 D3       CPY   $D3
1982-   20 D7 C5    JSR   $C5D7
1985-   CC CC AE    CPY   $AECC
1988-   A2 8D       LDX   #$8D
198A-   A0 C6       LDY   #$C6
198C-   D0 D2       BNE   $1960
198E-   CE A0 A3    DEC   $A3A0
1991-   D2 C5       CMP   ($C5)
1993-   D4          ???
1994-   CF          ???
1995-   D2 D4       CMP   ($D4)
1997-   8D A0 C3    STA   $C3A0
199A-   CD C4 A0    CMP   $A0C4
199D-   A2 C3       LDX   #$C3
199F-   CC CF D3    CPY   $D3CF
19A2-   C5 20       CMP   $20
19A4-   D4          ???
19A5-   AE D4 C5    LDX   $C5D4
19A8-   D8          CLD
19A9-   D4          ???
19AA-   C6 C9       DEC   $C9
19AC-   CC C5 A2    CPY   $A2C5
19AF-   8D A0 DF    STA   $DFA0
19B2-   D0 D2       BNE   $1986
19B4-   CE D4 A0    DEC   $A0D4
19B7-   A2 20       LDX   #$20
19B9-   A2 AC       LDX   #$AC
19BB-   B8          CLV
19BC-   C4 B8       CPY   $B8
19BE-   C4 B8       CPY   $B8
19C0-   C4 8D       CPY   $8D
19C2-   A0 DF       LDY   #$DF
19C4-   D0 D2       BNE   $1998
19C6-   CE D4 A0    DEC   $A0D4
19C9-   A2 D0       LDX   #$D0
19CB-   D5 D4       CMP   $D4,X
19CD-   D3          ???
19CE-   20 D4 C8    JSR   $C8D4
19D1-   C5 20       CMP   $20
19D3-   CC C9 D4    CPY   $D4C9
19D6-   C5 D2       CMP   $D2
19D8-   C1 CC       CMP   ($CC,X)
19DA-   20 D0 C8    JSR   $C8D0
19DD-   D2 C1       CMP   ($C1)
19DF-   D3          ???
19E0-   C5 20       CMP   $20
19E2-   C1 CE       CMP   ($CE,X)
19E4-   C4 20       CPY   $20
19E6-   C1 20       CMP   ($20,X)
19E8-   D0 C8       BNE   $19B2
19EA-   D2 C1       CMP   ($C1)
19EC-   D3          ???
19ED-   C5 A2       CMP   $A2
19EF-   AC B8 C4    LDY   $C4B8
19F2-   8D A0 DF    STA   $DFA0
19F5-   D0 D2       BNE   $19C9
19F7-   CE D4 A0    DEC   $A0D4
19FA-   A2 D3       LDX   #$D3
19FC-   D4          ???
19FD-   CF          ???
19FE-   D2 C5       CMP   ($C5)
1A00-   C4 20       CPY   $20
1A02-   C9 CE       CMP   #$CE
1A04-   20 D4 C8    JSR   $C8D4
1A07-   C5 20       CMP   $20
1A09-   D2 C5       CMP   ($C5)
1A0B-   D4          ???
1A0C-   CF          ???
1A0D-   D2 D4       CMP   ($D4)
1A0F-   20 C1 C4    JSR   $C4C1
1A12-   C4 D2       CPY   $D2
1A14-   C5 D3       CMP   $D3
1A16-   D3          ???
1A17-   20 C9 CE    JSR   $CEC9
1A1A-   D4          ???
1A1B-   CF          ???
1A1C-   A2 AC       LDX   #$AC
1A1E-   B8          CLV
1A1F-   C4 8D       CPY   $8D
1A21-   A0 DF       LDY   #$DF
1A23-   D0 D2       BNE   $19F7
1A25-   CE D4 A0    DEC   $A0D4
1A28-   A2 D4       LDX   #$D4
1A2A-   C8          INY
1A2B-   C5 20       CMP   $20
1A2D-   C6 C9       DEC   $C9
1A2F-   CC C5 AE    CPY   $AEC5
1A32-   A2 AC       LDX   #$AC
1A34-   B8          CLV
1A35-   C4 8D       CPY   $8D
1A37-   A0 DF       LDY   #$DF
1A39-   D7          ???
1A3A-   C1 C9       CMP   ($C9,X)
1A3C-   D4          ???
1A3D-   8D A0 DF    STA   $DFA0
1A40-   D0 D2       BNE   $1A14
1A42-   CE D4 A0    DEC   $A0D4
1A45-   A2 20       LDX   #$20
1A47-   A2 AC       LDX   #$AC
1A49-   B8          CLV
1A4A-   C4 B8       CPY   $B8
1A4C-   C4 B8       CPY   $B8
1A4E-   C4 8D       CPY   $8D
1A50-   A0 DF       LDY   #$DF
1A52-   D0 D2       BNE   $1A26
1A54-   CE D4 A0    DEC   $A0D4
1A57-   A2 D4       LDX   #$D4
1A59-   C8          INY
1A5A-   C5 CE       CMP   $CE
1A5C-   AC 20 CC    LDY   $CC20
1A5F-   C9 CB       CMP   #$CB
1A61-   C5 20       CMP   $20
1A63-   C1 CC       CMP   ($CC,X)
1A65-   D7          ???
1A66-   C1 D9       CMP   ($D9,X)
1A68-   D3          ???
1A69-   AC 20 D7    LDY   $D720
1A6C-   C5 20       CMP   $20
1A6E-   CD D5 D3    CMP   $D3D5
1A71-   D4          ???
1A72-   20 C3 CC    JSR   $CCC3
1A75-   CF          ???
1A76-   D3          ???
1A77-   C5 A2       CMP   $A2
1A79-   AC B8 C4    LDY   $C4B8
1A7C-   8D A0 DF    STA   $DFA0
1A7F-   D0 D2       BNE   $1A53
1A81-   CE D4 A0    DEC   $A0D4
1A84-   A2 D4       LDX   #$D4
1A86-   C8          INY
1A87-   C5 20       CMP   $20
1A89-   C6 C9       DEC   $C9
1A8B-   CC C5 20    CPY   $20C5
1A8E-   D6 C9       DEC   $C9,X
1A90-   C1 20       CMP   ($20,X)
1A92-   C3          ???
1A93-   CD C4 BA    CMP   $BAC4
1A96-   A2 AC       LDX   #$AC
1A98-   B8          CLV
1A99-   C4 B8       CPY   $B8
1A9B-   C4 8D       CPY   $8D
1A9D-   A0 DF       LDY   #$DF
1A9F-   D0 D2       BNE   $1A73
1AA1-   CE D4 A0    DEC   $A0D4
1AA4-   A2 C3       LDX   #$C3
1AA6-   CD C4 20    CMP   $20C4
1AA9-   A7          ???
1AAA-   C3          ???
1AAB-   CC CF D3    CPY   $D3CF
1AAE-   C5 20       CMP   $20
1AB0-   D4          ???
1AB1-   AE D4 C5    LDX   $C5D4
1AB4-   D8          CLD
1AB5-   D4          ???
1AB6-   C6 C9       DEC   $C9
1AB8-   CC C5 A7    CPY   $A7C5
1ABB-   A2 AC       LDX   #$AC
1ABD-   B8          CLV
1ABE-   C4 B8       CPY   $B8
1AC0-   C4 B8       CPY   $B8
1AC2-   C4 8D       CPY   $8D
1AC4-   A0 DF       LDY   #$DF
1AC6-   D7          ???
1AC7-   C1 C9       CMP   ($C9,X)
1AC9-   D4          ???
1ACA-   8D A0 DF    STA   $DFA0
1ACD-   D0 D2       BNE   $1AA1
1ACF-   CE D4 A0    DEC   $A0D4
1AD2-   A2 C6       LDX   #$C6
1AD4-   C9 CE       CMP   #$CE
1AD6-   C1 CC       CMP   ($CC,X)
1AD8-   CC D9 AC    CPY   $ACD9
1ADB-   20 D4 CF    JSR   $CFD4
1ADE-   20 D2 C5    JSR   $C5D2
1AE1-   C1 C4       CMP   ($C4,X)
1AE3-   20 D4 C8    JSR   $C8D4
1AE6-   C9 D3       CMP   #$D3
1AE8-   20 D4 C5    JSR   $C5D4
1AEB-   D8          CLD
1AEC-   D4          ???
1AED-   20 C6 C9    JSR   $C9C6
1AF0-   CC C5 A2    CPY   $A2C5
1AF3-   AC B8 C4    LDY   $C4B8
1AF6-   8D A0 DF    STA   $DFA0
1AF9-   D0 D2       BNE   $1ACD
1AFB-   CE D4 A0    DEC   $A0D4
1AFE-   A2 D7       LDX   #$D7
1B00-   C5 20       CMP   $20
1B02-   D3          ???
1B03-   C9 CD       CMP   #$CD
1B05-   D0 CC       BNE   $1AD3
1B07-   D9 20 CE    CMP   $CE20,Y
1B0A-   C5 C5       CMP   $C5
1B0C-   C4 20       CPY   $20
1B0E-   D4          ???
1B0F-   CF          ???
1B10-   20 CF D0    JSR   $D0CF
1B13-   C5 CE       CMP   $CE
1B15-   20 D4 C8    JSR   $C8D4
1B18-   C5 A2       CMP   $A2
1B1A-   AC B8 C4    LDY   $C4B8
1B1D-   8D A0 DF    STA   $DFA0
1B20-   D0 D2       BNE   $1AF4
1B22-   CE D4 A0    DEC   $A0D4
1B25-   A2 C6       LDX   #$C6
1B27-   C9 CC       CMP   #$CC
1B29-   C5 20       CMP   $20
1B2B-   C6 CF       DEC   $CF
1B2D-   D2 20       CMP   ($20)
1B2F-   D2 C5       CMP   ($C5)
1B31-   C1 C4       CMP   ($C4,X)
1B33-   C9 CE       CMP   #$CE
1B35-   C7          ???
1B36-   20 D6 C9    JSR   $C9D6
1B39-   C1 20       CMP   ($20,X)
1B3B-   D4          ???
1B3C-   C8          INY
1B3D-   C5 20       CMP   $20
1B3F-   C3          ???
1B40-   CD C4 20    CMP   $20C4
1B43-   CD C1 C3    CMP   $C3C1
1B46-   D2 CF       CMP   ($CF)
1B48-   AC A2 AC    LDY   $ACA2
1B4B-   B8          CLV
1B4C-   C4 8D       CPY   $8D
1B4E-   A0 DF       LDY   #$DF
1B50-   D0 D2       BNE   $1B24
1B52-   CE D4 A0    DEC   $A0D4
1B55-   A2 D4       LDX   #$D4
1B57-   C8          INY
1B58-   C5 CE       CMP   $CE
1B5A-   20 D5 D3    JSR   $D3D5
1B5D-   C5 20       CMP   $20
1B5F-   D4          ???
1B60-   C8          INY
1B61-   C5 20       CMP   $20
1B63-   C6 C9       DEC   $C9
1B65-   CE D0 20    DEC   $20D0
1B68-   CD C1 C3    CMP   $C3C1
1B6B-   D2 CF       CMP   ($CF)
1B6D-   20 D4 CF    JSR   $CFD4
1B70-   20 D2 C5    JSR   $C5D2
1B73-   C1 C4       CMP   ($C4,X)
1B75-   20 C1 20    JSR   $20C1
1B78-   A2 AC       LDX   #$AC
1B7A-   B8          CLV
1B7B-   C4 8D       CPY   $8D
1B7D-   A0 DF       LDY   #$DF
1B7F-   D0 D2       BNE   $1B53
1B81-   CE D4 A0    DEC   $A0D4
1B84-   A2 CC       LDX   #$CC
1B86-   C9 CE       CMP   #$CE
1B88-   C5 20       CMP   $20
1B8A-   CF          ???
1B8B-   C6 20       DEC   $20
1B8D-   D4          ???
1B8E-   C5 D8       CMP   $D8
1B90-   D4          ???
1B91-   20 C1 CE    JSR   $CEC1
1B94-   C4 20       CPY   $20
1B96-   D3          ???
1B97-   D4          ???
1B98-   CF          ???
1B99-   D2 C5       CMP   ($C5)
1B9B-   20 C9 D4    JSR   $D4C9
1B9E-   20 C9 CE    JSR   $CEC9
1BA1-   A2 AC       LDX   #$AC
1BA3-   B8          CLV
1BA4-   C4 8D       CPY   $8D
1BA6-   A0 DF       LDY   #$DF
1BA8-   D0 D2       BNE   $1B7C
1BAA-   CE D4 A0    DEC   $A0D4
1BAD-   A2 CD       LDX   #$CD
1BAF-   C5 CD       CMP   $CD
1BB1-   CF          ???
1BB2-   D2 D9       CMP   ($D9)
1BB4-   BA          TSX
1BB5-   A2 AC       LDX   #$AC
1BB7-   B8          CLV
1BB8-   C4 B8       CPY   $B8
1BBA-   C4 8D       CPY   $8D
1BBC-   A0 DF       LDY   #$DF
1BBE-   D0 D2       BNE   $1B92
1BC0-   CE D4 A0    DEC   $A0D4
1BC3-   A2 C3       LDX   #$C3
1BC5-   CD C4 20    CMP   $20C4
1BC8-   A7          ???
1BC9-   CF          ???
1BCA-   D0 C5       BNE   $1B91
1BCC-   CE 20 D4    DEC   $D420
1BCF-   AE D4 C5    LDX   $C5D4
1BD2-   D8          CLD
1BD3-   D4          ???
1BD4-   C6 C9       DEC   $C9
1BD6-   CC C5 A7    CPY   $A7C5
1BD9-   A2 AC       LDX   #$AC
1BDB-   B8          CLV
1BDC-   C4 8D       CPY   $8D
1BDE-   A0 DF       LDY   #$DF
1BE0-   D0 D2       BNE   $1BB4
1BE2-   CE D4 A0    DEC   $A0D4
1BE5-   A2 C3       LDX   #$C3
1BE7-   CD C4 20    CMP   $20C4
1BEA-   A7          ???
1BEB-   D2 C5       CMP   ($C5)
1BED-   C1 C4       CMP   ($C4,X)
1BEF-   20 D4 AE    JSR   $AED4
1BF2-   D4          ???
1BF3-   C5 D8       CMP   $D8
1BF5-   D4          ???
1BF6-   C6 C9       DEC   $C9
1BF8-   CC C5 A7    CPY   $A7C5
1BFB-   A2 AC       LDX   #$AC
1BFD-   B8          CLV
1BFE-   C4 8D       CPY   $8D
1C00-   A0 DF       LDY   #$DF
1C02-   D0 D2       BNE   $1BD6
1C04-   CE D4 A0    DEC   $A0D4
1C07-   A2 C6       LDX   #$C6
1C09-   C9 CE       CMP   #$CE
1C0B-   D0 20       BNE   $1C2D
1C0D-   D2 C5       CMP   ($C5)
1C0F-   D4          ???
1C10-   D5 D2       CMP   $D2,X
1C12-   CE A2 AC    DEC   $ACA2
1C15-   B8          CLV
1C16-   C4 8D       CPY   $8D
1C18-   A0 DF       LDY   #$DF
1C1A-   D0 D2       BNE   $1BEE
1C1C-   CE D4 A0    DEC   $A0D4
1C1F-   A2 C6       LDX   #$C6
1C21-   C9 CE       CMP   #$CE
1C23-   D0 20       BNE   $1C45
1C25-   D0 C1       BNE   $1BE8
1C27-   D2 C1       CMP   ($C1)
1C29-   CD A2 AC    CMP   $ACA2
1C2C-   B8          CLV
1C2D-   C4 8D       CPY   $8D
1C2F-   A0 DF       LDY   #$DF
1C31-   D0 D2       BNE   $1C05
1C33-   CE D4 A0    DEC   $A0D4
1C36-   A2 C3       LDX   #$C3
1C38-   CD C4 20    CMP   $20C4
1C3B-   A7          ???
1C3C-   C3          ???
1C3D-   CC CF D3    CPY   $D3CF
1C40-   C5 20       CMP   $20
1C42-   D4          ???
1C43-   AE D4 C5    LDX   $C5D4
1C46-   D8          CLD
1C47-   D4          ???
1C48-   C6 C9       DEC   $C9
1C4A-   CC C5 A7    CPY   $A7C5
1C4D-   A2 AC       LDX   #$AC
1C4F-   B8          CLV
1C50-   C4 B8       CPY   $B8
1C52-   C4 8D       CPY   $8D
1C54-   A0 C3       LDY   #$C3
1C56-   CD C4 A0    CMP   $A0C4
1C59-   A2 CF       LDX   #$CF
1C5B-   D0 C5       BNE   $1C22
1C5D-   CE 20 D4    DEC   $D420
1C60-   AE D4 C5    LDX   $C5D4
1C63-   D8          CLD
1C64-   D4          ???
1C65-   C6 C9       DEC   $C9
1C67-   CC C5 A2    CPY   $A2C5
1C6A-   8D A0 C3    STA   $C3A0
1C6D-   CD C4 A0    CMP   $A0C4
1C70-   A2 D2       LDX   #$D2
1C72-   C5 C1       CMP   $C1
1C74-   C4 20       CPY   $20
1C76-   D4          ???
1C77-   AE D4 C5    LDX   $C5D4
1C7A-   D8          CLD
1C7B-   D4          ???
1C7C-   C6 C9       DEC   $C9
1C7E-   CC C5 A2    CPY   $A2C5
1C81-   8D A0 C6    STA   $C6A0
1C84-   C9 CE       CMP   #$CE
1C86-   D0 A0       BNE   $1C28
1C88-   A3          ???
1C89-   D2 C5       CMP   ($C5)
1C8B-   D4          ???
1C8C-   D5 D2       CMP   $D2,X
1C8E-   CE 8D A0    DEC   $A08D
1C91-   C6 C9       DEC   $C9
1C93-   CE D0 A0    DEC   $A0D0
1C96-   A3          ???
1C97-   D0 C1       BNE   $1C5A
1C99-   D2 C1       CMP   ($C1)
1C9B-   CD 8D A0    CMP   $A08D
1C9E-   C3          ???
1C9F-   CD C4 A0    CMP   $A0C4
1CA2-   A2 C3       LDX   #$C3
1CA4-   CC CF D3    CPY   $D3CF
1CA7-   C5 20       CMP   $20
1CA9-   D4          ???
1CAA-   AE D4 C5    LDX   $C5D4
1CAD-   D8          CLD
1CAE-   D4          ???
1CAF-   C6 C9       DEC   $C9
1CB1-   CC C5 A2    CPY   $A2C5
1CB4-   8D A0 DF    STA   $DFA0
1CB7-   D7          ???
1CB8-   C1 C9       CMP   ($C9,X)
1CBA-   D4          ???
1CBB-   8D A0 C4    STA   $C4A0
1CBE-   D5 CD       CMP   $CD,X
1CC0-   D0 A0       BNE   $1C62
1CC2-   A3          ???
1CC3-   D2 C5       CMP   ($C5)
1CC5-   D4          ???
1CC6-   D5 D2       CMP   $D2,X
1CC8-   CE BB D2    DEC   $D2BB
1CCB-   C5 D4       CMP   $D4
1CCD-   D5 D2       CMP   $D2,X
1CCF-   CE 8D A0    DEC   $A08D
1CD2-   C4 D5       CPY   $D5
1CD4-   CD D0 A0    CMP   $A0D0
1CD7-   A3          ???
1CD8-   D0 C1       BNE   $1C9B
1CDA-   D2 C1       CMP   ($C1)
1CDC-   CD BB D0    CMP   $D0BB
1CDF-   C1 D2       CMP   ($D2,X)
1CE1-   C1 CD       CMP   ($CD,X)
1CE3-   8D A0 DF    STA   $DFA0
1CE6-   D7          ???
1CE7-   C1 C9       CMP   ($C9,X)
1CE9-   D4          ???
1CEA-   8D AA 8D    STA   $8DAA
1CED-   A0 DF       LDY   #$DF
1CEF-   D0 D2       BNE   $1CC3
1CF1-   CE D4 A0    DEC   $A0D4
1CF4-   A2 20       LDX   #$20
1CF6-   A2 AC       LDX   #$AC
1CF8-   B8          CLV
1CF9-   C4 B8       CPY   $B8
1CFB-   C4 8D       CPY   $8D
1CFD-   A0 DF       LDY   #$DF
1CFF-   D0 D2       BNE   $1CD3
1D01-   CE D4 A0    DEC   $A0D4
1D04-   A2 D4       LDX   #$D4
1D06-   C8          INY
1D07-   C5 D3       CMP   $D3
1D09-   C5 20       CMP   $20
1D0B-   D3          ???
1D0C-   D4          ???
1D0D-   D2 C9       CMP   ($C9)
1D0F-   CE C7 D3    DEC   $D3C7
1D12-   20 C1 D2    JSR   $D2C1
1D15-   C5 20       CMP   $20
1D17-   CE CF D7    DEC   $D7CF
1D1A-   20 D3 D4    JSR   $D4D3
1D1D-   CF          ???
1D1E-   D2 C5       CMP   ($C5)
1D20-   C4 20       CPY   $20
1D22-   C9 CE       CMP   #$CE
1D24-   A2 AC       LDX   #$AC
1D26-   B8          CLV
1D27-   C4 8D       CPY   $8D
1D29-   A0 DF       LDY   #$DF
1D2B-   D0 D2       BNE   $1CFF
1D2D-   CE D4 A0    DEC   $A0D4
1D30-   A2 DB       LDX   #$DB
1D32-   D2 C5       CMP   ($C5)
1D34-   D4          ???
1D35-   D5 D2       CMP   $D2,X
1D37-   CE DD 20    DEC   $20DD
1D3A-   C1 CE       CMP   ($CE,X)
1D3C-   C4 20       CPY   $20
1D3E-   DB          ???
1D3F-   D0 C1       BNE   $1D02
1D41-   D2 C1       CMP   ($C1)
1D43-   CD DD AC    CMP   $ACDD
1D46-   20 D2 C5    JSR   $C5D2
1D49-   D3          ???
1D4A-   D0 C5       BNE   $1D11
1D4C-   C3          ???
1D4D-   D4          ???
1D4E-   C9 D6       CMP   #$D6
1D50-   C5 CC       CMP   $CC
1D52-   D9 AC A2    CMP   $A2AC,Y
1D55-   AC B8 C4    LDY   $C4B8
1D58-   8D A0 DF    STA   $DFA0
1D5B-   D0 D2       BNE   $1D2F
1D5D-   CE D4 A0    DEC   $A0D4
1D60-   A2 D7       LDX   #$D7
1D62-   C9 D4       CMP   #$D4
1D64-   C8          INY
1D65-   20 C1 20    JSR   $20C1
1D68-   D0 D2       BNE   $1D3C
1D6A-   C5 C3       CMP   $C3
1D6C-   C5 C4       CMP   $C4
1D6E-   C9 CE       CMP   #$CE
1D70-   C7          ???
1D71-   20 CC C5    JSR   $C5CC
1D74-   CE C7 D4    DEC   $D4C7
1D77-   C8          INY
1D78-   20 C2 D9    JSR   $D9C2
1D7B-   D4          ???
1D7C-   C5 AE       CMP   $AE
1D7E-   20 D4 C8    JSR   $C8D4
1D81-   C5 D3       CMP   $D3
1D83-   C5 A2       CMP   $A2
1D85-   AC B8 C4    LDY   $C4B8
1D88-   8D A0 DF    STA   $DFA0
1D8B-   D0 D2       BNE   $1D5F
1D8D-   CE D4 A0    DEC   $A0D4
1D90-   A2 C3       LDX   #$C3
1D92-   C1 CE       CMP   ($CE,X)
1D94-   20 C2 C5    JSR   $C5C2
1D97-   20 D0 D2    JSR   $D2D0
1D9A-   C9 CE       CMP   #$CE
1D9C-   D4          ???
1D9D-   C5 C4       CMP   $C4
1D9F-   20 D7 C9    JSR   $C9D7
1DA2-   D4          ???
1DA3-   C8          INY
1DA4-   20 D4 C8    JSR   $C8D4
1DA7-   C5 20       CMP   $20
1DA9-   D3          ???
1DAA-   D0 D2       BNE   $1D7E
1DAC-   CE 20 CD    DEC   $CD20
1DAF-   C1 C3       CMP   ($C3,X)
1DB1-   D2 CF       CMP   ($CF)
1DB3-   A2 AC       LDX   #$AC
1DB5-   B8          CLV
1DB6-   C4 8D       CPY   $8D
1DB8-   A0 DF       LDY   #$DF
1DBA-   D0 D2       BNE   $1D8E
1DBC-   CE D4 A0    DEC   $A0D4
1DBF-   A2 C6       LDX   #$C6
1DC1-   CF          ???
1DC2-   D5 CE       CMP   $CE,X
1DC4-   C4 20       CPY   $20
1DC6-   C9 CE       CMP   #$CE
1DC8-   20 D4 C8    JSR   $C8D4
1DCB-   C5 20       CMP   $20
1DCD-   D3          ???
1DCE-   D4          ???
1DCF-   D2 C9       CMP   ($C9)
1DD1-   CE C7 D3    DEC   $D3C7
1DD4-   20 CC C9    JSR   $C9CC
1DD7-   C2          ???
1DD8-   D2 C1       CMP   ($C1)
1DDA-   D2 D9       CMP   ($D9)
1DDC-   AE A2 AC    LDX   $ACA2
1DDF-   B8          CLV
1DE0-   C4 B8       CPY   $B8
1DE2-   C4 B8       CPY   $B8
1DE4-   C4 8D       CPY   $8D
1DE6-   A0 DF       LDY   #$DF
1DE8-   D7          ???
1DE9-   C1 C9       CMP   ($C9,X)
1DEB-   D4          ???
1DEC-   8D AA 8D    STA   $8DAA
1DEF-   AA          TAX
1DF0-   AA          TAX
1DF1-   AA          TAX
1DF2-   AA          TAX
1DF3-   AA          TAX
1DF4-   AA          TAX
1DF5-   AA          TAX
1DF6-   AA          TAX
1DF7-   AA          TAX
1DF8-   AA          TAX
1DF9-   AA          TAX
1DFA-   AA          TAX
1DFB-   AA          TAX
1DFC-   AA          TAX
1DFD-   AA          TAX
1DFE-   AA          TAX
1DFF-   AA          TAX
1E00-   AA          TAX
1E01-   AA          TAX
1E02-   AA          TAX
1E03-   AA          TAX
1E04-   AA          TAX
1E05-   AA          TAX
1E06-   AA          TAX
1E07-   AA          TAX
1E08-   AA          TAX
1E09-   AA          TAX
1E0A-   AA          TAX
1E0B-   AA          TAX
1E0C-   AA          TAX
1E0D-   AA          TAX
1E0E-   AA          TAX
1E0F-   8D AA AA    STA   $AAAA
1E12-   AA          TAX
1E13-   AA          TAX
1E14-   AA          TAX
1E15-   AA          TAX
1E16-   AA          TAX
1E17-   AA          TAX
1E18-   AA          TAX
1E19-   AA          TAX
1E1A-   AA          TAX
1E1B-   AA          TAX
1E1C-   AA          TAX
1E1D-   AA          TAX
1E1E-   AA          TAX
1E1F-   AA          TAX
1E20-   AA          TAX
1E21-   AA          TAX
1E22-   AA          TAX
1E23-   AA          TAX
1E24-   AA          TAX
1E25-   AA          TAX
1E26-   AA          TAX
1E27-   AA          TAX
1E28-   AA          TAX
1E29-   AA          TAX
1E2A-   AA          TAX
1E2B-   AA          TAX
1E2C-   AA          TAX
1E2D-   AA          TAX
1E2E-   AA          TAX
1E2F-   AA          TAX
1E30-   8D AA AA    STA   $AAAA
1E33-   AA          TAX
1E34-   AA          TAX
1E35-   AA          TAX
1E36-   AA          TAX
1E37-   AA          TAX
1E38-   AA          TAX
1E39-   AA          TAX
1E3A-   AA          TAX
1E3B-   AA          TAX
1E3C-   AA          TAX
1E3D-   AA          TAX
1E3E-   AA          TAX
1E3F-   AA          TAX
1E40-   AA          TAX
1E41-   AA          TAX
1E42-   AA          TAX
1E43-   AA          TAX
1E44-   AA          TAX
1E45-   AA          TAX
1E46-   AA          TAX
1E47-   AA          TAX
1E48-   AA          TAX
1E49-   AA          TAX
1E4A-   AA          TAX
1E4B-   AA          TAX
1E4C-   AA          TAX
1E4D-   AA          TAX
1E4E-   AA          TAX
1E4F-   AA          TAX
1E50-   AA          TAX
1E51-   8D AA 20    STA   $20AA
1E54-   20 20 20    JSR   $2020
1E57-   20 20 20    JSR   $2020
1E5A-   20 20 20    JSR   $2020
1E5D-   20 20 20    JSR   $2020
1E60-   20 20 20    JSR   $2020
1E63-   20 20 20    JSR   $2020
1E66-   20 20 20    JSR   $2020
1E69-   20 20 20    JSR   $2020
1E6C-   20 20 20    JSR   $2020
1E6F-   20 20 AA    JSR   $AA20
1E72-   8D AA 20    STA   $20AA
1E75-   20 20 D7    JSR   $D720
1E78-   20 C1 20    JSR   $20C1
1E7B-   D2 20       CMP   ($20)
1E7D-   CE 20 C9    DEC   $C920
1E80-   20 CE 20    JSR   $20CE
1E83-   C7          ???
1E84-   20 20 20    JSR   $2020
1E87-   20 20 20    JSR   $2020
1E8A-   20 20 20    JSR   $2020
1E8D-   20 20 20    JSR   $2020
1E90-   20 20 AA    JSR   $AA20
1E93-   8D AA 20    STA   $20AA
1E96-   20 20 20    JSR   $2020
1E99-   20 20 20    JSR   $2020
1E9C-   20 20 20    JSR   $2020
1E9F-   20 20 20    JSR   $2020
1EA2-   20 20 20    JSR   $2020
1EA5-   20 20 20    JSR   $2020
1EA8-   20 20 20    JSR   $2020
1EAB-   20 20 20    JSR   $2020
1EAE-   20 20 20    JSR   $2020
1EB1-   20 20 AA    JSR   $AA20
1EB4-   8D AA AA    STA   $AAAA
1EB7-   AA          TAX
1EB8-   AA          TAX
1EB9-   AA          TAX
1EBA-   AA          TAX
1EBB-   AA          TAX
1EBC-   AA          TAX
1EBD-   AA          TAX
1EBE-   AA          TAX
1EBF-   AA          TAX
1EC0-   AA          TAX
1EC1-   AA          TAX
1EC2-   AA          TAX
1EC3-   AA          TAX
1EC4-   AA          TAX
1EC5-   AA          TAX
1EC6-   AA          TAX
1EC7-   AA          TAX
1EC8-   AA          TAX
1EC9-   AA          TAX
1ECA-   AA          TAX
1ECB-   AA          TAX
1ECC-   AA          TAX
1ECD-   AA          TAX
1ECE-   AA          TAX
1ECF-   AA          TAX
1ED0-   AA          TAX
1ED1-   AA          TAX
1ED2-   AA          TAX
1ED3-   AA          TAX
1ED4-   AA          TAX
1ED5-   8D AA AA    STA   $AAAA
1ED8-   AA          TAX
1ED9-   AA          TAX
1EDA-   AA          TAX
1EDB-   AA          TAX
1EDC-   AA          TAX
1EDD-   AA          TAX
1EDE-   AA          TAX
1EDF-   AA          TAX
1EE0-   AA          TAX
1EE1-   AA          TAX
1EE2-   AA          TAX
1EE3-   AA          TAX
1EE4-   AA          TAX
1EE5-   AA          TAX
1EE6-   AA          TAX
1EE7-   AA          TAX
1EE8-   AA          TAX
1EE9-   AA          TAX
1EEA-   AA          TAX
1EEB-   AA          TAX
1EEC-   AA          TAX
1EED-   AA          TAX
1EEE-   AA          TAX
1EEF-   AA          TAX
1EF0-   AA          TAX
1EF1-   AA          TAX
1EF2-   AA          TAX
1EF3-   AA          TAX
1EF4-   AA          TAX
1EF5-   AA          TAX
1EF6-   8D AA AA    STA   $AAAA
1EF9-   AA          TAX
1EFA-   AA          TAX
1EFB-   AA          TAX
1EFC-   AA          TAX
1EFD-   AA          TAX
1EFE-   AA          TAX
1EFF-   AA          TAX
1F00-   AA          TAX
1F01-   AA          TAX
1F02-   AA          TAX
1F03-   AA          TAX
1F04-   AA          TAX
1F05-   AA          TAX
1F06-   AA          TAX
1F07-   AA          TAX
1F08-   AA          TAX
1F09-   AA          TAX
1F0A-   AA          TAX
1F0B-   AA          TAX
1F0C-   AA          TAX
1F0D-   AA          TAX
1F0E-   AA          TAX
1F0F-   AA          TAX
1F10-   AA          TAX
1F11-   AA          TAX
1F12-   AA          TAX
1F13-   AA          TAX
1F14-   AA          TAX
1F15-   AA          TAX
1F16-   AA          TAX
1F17-   8D AA 8D    STA   $8DAA
1F1A-   A0 DF       LDY   #$DF
1F1C-   D0 D2       BNE   $1EF0
1F1E-   CE D4 A0    DEC   $A0D4
1F21-   A2 AA       LDX   #$AA
1F23-   AA          TAX
1F24-   AA          TAX
1F25-   AA          TAX
1F26-   AA          TAX
1F27-   AA          TAX
1F28-   AA          TAX
1F29-   AA          TAX
1F2A-   AA          TAX
1F2B-   AA          TAX
1F2C-   AA          TAX
1F2D-   AA          TAX
1F2E-   AA          TAX
1F2F-   AA          TAX
1F30-   AA          TAX
1F31-   AA          TAX
1F32-   AA          TAX
1F33-   AA          TAX
1F34-   AA          TAX
1F35-   AA          TAX
1F36-   AA          TAX
1F37-   AA          TAX
1F38-   AA          TAX
1F39-   AA          TAX
1F3A-   AA          TAX
1F3B-   AA          TAX
1F3C-   AA          TAX
1F3D-   AA          TAX
1F3E-   AA          TAX
1F3F-   AA          TAX
1F40-   AA          TAX
1F41-   AA          TAX
1F42-   A2 AC       LDX   #$AC
1F44-   B8          CLV
1F45-   C4 8D       CPY   $8D
1F47-   A0 DF       LDY   #$DF
1F49-   D0 D2       BNE   $1F1D
1F4B-   CE D4 A0    DEC   $A0D4
1F4E-   A2 AA       LDX   #$AA
1F50-   AA          TAX
1F51-   AA          TAX
1F52-   AA          TAX
1F53-   AA          TAX
1F54-   AA          TAX
1F55-   AA          TAX
1F56-   AA          TAX
1F57-   AA          TAX
1F58-   AA          TAX
1F59-   AA          TAX
1F5A-   AA          TAX
1F5B-   AA          TAX
1F5C-   AA          TAX
1F5D-   AA          TAX
1F5E-   AA          TAX
1F5F-   AA          TAX
1F60-   AA          TAX
1F61-   AA          TAX
1F62-   AA          TAX
1F63-   AA          TAX
1F64-   AA          TAX
1F65-   AA          TAX
1F66-   AA          TAX
1F67-   AA          TAX
1F68-   AA          TAX
1F69-   AA          TAX
1F6A-   AA          TAX
1F6B-   AA          TAX
1F6C-   AA          TAX
1F6D-   AA          TAX
1F6E-   AA          TAX
1F6F-   A2 AC       LDX   #$AC
1F71-   B8          CLV
1F72-   C4 B8       CPY   $B8
1F74-   C4 8D       CPY   $8D
1F76-   A0 DF       LDY   #$DF
1F78-   D0 D2       BNE   $1F4C
1F7A-   CE D4 A0    DEC   $A0D4
1F7D-   A2 20       LDX   #$20
1F7F-   20 20 20    JSR   $2020
1F82-   20 20 D7    JSR   $D720
1F85-   C1 D2       CMP   ($D2,X)
1F87-   CE C9 CE    DEC   $CEC9
1F8A-   C7          ???
1F8B-   A1 A1       LDA   ($A1,X)
1F8D-   A1 A2       LDA   ($A2,X)
1F8F-   AC B8 C4    LDY   $C4B8
1F92-   B8          CLV
1F93-   C4 8D       CPY   $8D
1F95-   A0 DF       LDY   #$DF
1F97-   D0 D2       BNE   $1F6B
1F99-   CE D4 A0    DEC   $A0D4
1F9C-   A2 AA       LDX   #$AA
1F9E-   AA          TAX
1F9F-   AA          TAX
1FA0-   AA          TAX
1FA1-   AA          TAX
1FA2-   AA          TAX
1FA3-   AA          TAX
1FA4-   AA          TAX
1FA5-   AA          TAX
1FA6-   AA          TAX
1FA7-   AA          TAX
1FA8-   AA          TAX
1FA9-   AA          TAX
1FAA-   AA          TAX
1FAB-   AA          TAX
1FAC-   AA          TAX
1FAD-   AA          TAX
1FAE-   AA          TAX
1FAF-   AA          TAX
1FB0-   AA          TAX
1FB1-   AA          TAX
1FB2-   AA          TAX
1FB3-   AA          TAX
1FB4-   AA          TAX
1FB5-   AA          TAX
1FB6-   AA          TAX
1FB7-   AA          TAX
1FB8-   AA          TAX
1FB9-   AA          TAX
1FBA-   AA          TAX
1FBB-   AA          TAX
1FBC-   AA          TAX
1FBD-   A2 AC       LDX   #$AC
1FBF-   B8          CLV
1FC0-   C4 8D       CPY   $8D
1FC2-   A0 DF       LDY   #$DF
1FC4-   D0 D2       BNE   $1F98
1FC6-   CE D4 A0    DEC   $A0D4
1FC9-   A2 AA       LDX   #$AA
1FCB-   AA          TAX
1FCC-   AA          TAX
1FCD-   AA          TAX
1FCE-   AA          TAX
1FCF-   AA          TAX
1FD0-   AA          TAX
1FD1-   AA          TAX
1FD2-   AA          TAX
1FD3-   AA          TAX
1FD4-   AA          TAX
1FD5-   AA          TAX
1FD6-   AA          TAX
1FD7-   AA          TAX
1FD8-   AA          TAX
1FD9-   AA          TAX
1FDA-   AA          TAX
1FDB-   AA          TAX
1FDC-   AA          TAX
1FDD-   AA          TAX
1FDE-   AA          TAX
1FDF-   AA          TAX
1FE0-   AA          TAX
1FE1-   AA          TAX
1FE2-   AA          TAX
1FE3-   AA          TAX
1FE4-   AA          TAX
1FE5-   AA          TAX
1FE6-   AA          TAX
1FE7-   AA          TAX
1FE8-   AA          TAX
1FE9-   AA          TAX
1FEA-   A2 AC       LDX   #$AC
1FEC-   B8          CLV
1FED-   C4 B8       CPY   $B8
1FEF-   C4 8D       CPY   $8D
1FF1-   A0 DF       LDY   #$DF
1FF3-   D0 D2       BNE   $1FC7
1FF5-   CE D4 A0    DEC   $A0D4
1FF8-   A2 C1       LDX   #$C1
1FFA-   D4          ???
1FFB-   20 D4 C8    JSR   $C8D4
1FFE-   C9 D3       CMP   #$D3
2000-   20 D0 CF    JSR   $CFD0
2003-   C9 CE       CMP   #$CE
2005-   D4          ???
2006-   AC 20 D9    LDY   $D920
2009-   CF          ???
200A-   D5 20       CMP   $20,X
200C-   D7          ???
200D-   C1 CE       CMP   ($CE,X)
200F-   D4          ???
2010-   20 D4 CF    JSR   $CFD4
2013-   20 C5 CA    JSR   $CAC5
2016-   C5 C3       CMP   $C3
2018-   D4          ???
2019-   A2 AC       LDX   #$AC
201B-   B8          CLV
201C-   C4 8D       CPY   $8D
201E-   A0 DF       LDY   #$DF
2020-   D0 D2       BNE   $1FF4
2022-   CE D4 A0    DEC   $A0D4
2025-   A2 D4       LDX   #$D4
2027-   C8          INY
2028-   C5 20       CMP   $20
202A-   C3          ???
202B-   D5 D2       CMP   $D2,X
202D-   D2 C5       CMP   ($C5)
202F-   CE D4 20    DEC   $20D4
2032-   C4 C9       CPY   $C9
2034-   D3          ???
2035-   CB          ???
2036-   AC 20 C1    LDY   $C120
2039-   CE C4 20    DEC   $20C4
203C-   D0 D5       BNE   $2013
203E-   D4          ???
203F-   20 C9 CE    JSR   $CEC9
2042-   A2 AC       LDX   #$AC
2044-   B8          CLV
2045-   C4 8D       CPY   $8D
2047-   A0 DF       LDY   #$DF
2049-   D0 D2       BNE   $201D
204B-   CE D4 A0    DEC   $A0D4
204E-   A2 C1       LDX   #$C1
2050-   20 C4 C9    JSR   $C9C4
2053-   D3          ???
2054-   CB          ???
2055-   20 D4 C8    JSR   $C8D4
2058-   C1 D4       CMP   ($D4,X)
205A-   20 D9 CF    JSR   $CFD9
205D-   D5 20       CMP   $20,X
205F-   C4 CF       CPY   $CF
2061-   CE A7 D4    DEC   $D4A7
2064-   20 CD C9    JSR   $C9CD
2067-   CE C4 20    DEC   $20C4
206A-   A2 AC       LDX   #$AC
206C-   B8          CLV
206D-   C4 8D       CPY   $8D
206F-   A0 DF       LDY   #$DF
2071-   D0 D2       BNE   $2045
2073-   CE D4 A0    DEC   $A0D4
2076-   A2 C8       LDX   #$C8
2078-   C1 D6       CMP   ($D6,X)
207A-   C9 CE       CMP   #$CE
207C-   C7          ???
207D-   20 D4 CF    JSR   $CFD4
2080-   20 D2 C5    JSR   $C5D2
2083-   C6 CF       DEC   $CF
2085-   D2 CD       CMP   ($CD)
2087-   C1 D4       CMP   ($D4,X)
2089-   AE 20 A2    LDX   $A220
208C-   AC B8 C4    LDY   $C4B8
208F-   B8          CLV
2090-   C4 8D       CPY   $8D
2092-   A0 DF       LDY   #$DF
2094-   D0 D2       BNE   $2068
2096-   CE D4 A0    DEC   $A0D4
2099-   A2 D4       LDX   #$D4
209B-   C8          INY
209C-   C5 20       CMP   $20
209E-   D2 C5       CMP   ($C5)
20A0-   D3          ???
20A1-   D4          ???
20A2-   20 CF C6    JSR   $C6CF
20A5-   20 D4 C8    JSR   $C8D4
20A8-   C5 20       CMP   $20
20AA-   D2 CF       CMP   ($CF)
20AC-   D5 D4       CMP   $D4,X
20AE-   C9 CE       CMP   #$CE
20B0-   C5 D3       CMP   $D3
20B2-   20 C1 D2    JSR   $D2C1
20B5-   C5 A2       CMP   $A2
20B7-   AC B8 C4    LDY   $C4B8
20BA-   8D A0 DF    STA   $DFA0
20BD-   D0 D2       BNE   $2091
20BF-   CE D4 A0    DEC   $A0D4
20C2-   A2 CC       LDX   #$CC
20C4-   CF          ???
20C5-   D7          ???
20C6-   20 CC C5    JSR   $C5CC
20C9-   D6 C5       DEC   $C5,X
20CB-   CC 20 C4    CPY   $C420
20CE-   C9 D3       CMP   #$D3
20D0-   CB          ???
20D1-   20 C1 C3    JSR   $C3C1
20D4-   C3          ???
20D5-   C5 D3       CMP   $D3
20D7-   D3          ???
20D8-   20 D0 D2    JSR   $D2D0
20DB-   CF          ???
20DC-   C3          ???
20DD-   C5 C4       CMP   $C4
20DF-   D5 D2       CMP   $D2,X
20E1-   C5 D3       CMP   $D3
20E3-   AC A2 AC    LDY   $ACA2
20E6-   B8          CLV
20E7-   C4 8D       CPY   $8D
20E9-   A0 DF       LDY   #$DF
20EB-   D0 D2       BNE   $20BF
20ED-   CE D4 A0    DEC   $A0D4
20F0-   A2 C1       LDX   #$C1
20F2-   CE C4 20    DEC   $20C4
20F5-   C3          ???
20F6-   C1 CE       CMP   ($CE,X)
20F8-   20 D3 C5    JSR   $C5D3
20FB-   D2 C9       CMP   ($C9)
20FD-   CF          ???
20FE-   D5 D3       CMP   $D3,X
2100-   CC D9 20    CPY   $20D9
2103-   C4 C1       CPY   $C1
2105-   CD C1 C7    CMP   $C7C1
2108-   C5 20       CMP   $20
210A-   C1 20       CMP   ($20,X)
210C-   C4 C9       CPY   $C9
210E-   D3          ???
210F-   CB          ???
2110-   A1 A2       LDA   ($A2,X)
2112-   AC B8 C4    LDY   $C4B8
2115-   B8          CLV
2116-   C4 8D       CPY   $8D
2118-   A0 DF       LDY   #$DF
211A-   D0 D2       BNE   $20EE
211C-   CE D4 A0    DEC   $A0D4
211F-   A2 BC       LDX   #$BC
2121-   BC BC 20    LDY   $20BC,X
2124-   D0 D2       BNE   $20F8
2126-   C5 D3       CMP   $D3
2128-   D3          ???
2129-   20 C1 20    JSR   $20C1
212C-   CB          ???
212D-   C5 D9       CMP   $D9
212F-   20 CF CE    JSR   $CECF
2132-   C3          ???
2133-   C5 20       CMP   $20
2135-   D9 CF D5    CMP   $D5CF,Y
2138-   A7          ???
2139-   D2 C5       CMP   ($C5)
213B-   20 D2 C5    JSR   $C5D2
213E-   C1 C4       CMP   ($C4,X)
2140-   D9 20 BE    CMP   $BE20,Y
2143-   BE BE A2    LDX   $A2BE,Y
2146-   AC B8 C4    LDY   $C4B8
2149-   B8          CLV
214A-   C4 8D       CPY   $8D
214C-   A0 DF       LDY   #$DF
214E-   D7          ???
214F-   C1 C9       CMP   ($C9,X)
2151-   D4          ???
2152-   8D AA 8D    STA   $8DAA
2155-   A0 DF       LDY   #$DF
2157-   D0 D2       BNE   $212B
2159-   CE D4 A0    DEC   $A0D4
215C-   A2 CC       LDX   #$CC
215E-   CF          ???
215F-   D7          ???
2160-   AD CC C5    LDA   $C5CC
2163-   D6 C5       DEC   $C5,X
2165-   CC 20 C4    CPY   $C420
2168-   C9 D3       CMP   #$D3
216A-   CB          ???
216B-   20 C1 C3    JSR   $C3C1
216E-   C3          ???
216F-   C5 D3       CMP   $D3
2171-   D3          ???
2172-   20 C9 D3    JSR   $D3C9
2175-   20 C4 CF    JSR   $CFC4
2178-   CE C5 20    DEC   $20C5
217B-   D6 C9       DEC   $C9,X
217D-   C1 A2       CMP   ($A2,X)
217F-   AC B8 C4    LDY   $C4B8
2182-   8D A0 DF    STA   $DFA0
2185-   D0 D2       BNE   $2159
2187-   CE D4 A0    DEC   $A0D4
218A-   A2 D4       LDX   #$D4
218C-   C8          INY
218D-   C5 20       CMP   $20
218F-   D3          ???
2190-   D4          ???
2191-   C1 CE       CMP   ($CE,X)
2193-   C4 C1       CPY   $C1
2195-   D2 C4       CMP   ($C4)
2197-   20 D2 D7    JSR   $D7D2
219A-   D4          ???
219B-   D3          ???
219C-   20 D2 CF    JSR   $CFD2
219F-   D5 D4       CMP   $D4,X
21A1-   C9 CE       CMP   #$CE
21A3-   C5 AC       CMP   $AC
21A5-   20 D7 C9    JSR   $C9D7
21A8-   D4          ???
21A9-   C8          INY
21AA-   20 C1 A2    JSR   $A2C1
21AD-   AC B8 C4    LDY   $C4B8
21B0-   8D A0 DF    STA   $DFA0
21B3-   D0 D2       BNE   $2187
21B5-   CE D4 A0    DEC   $A0D4
21B8-   A2 C6       LDX   #$C6
21BA-   C5 D7       CMP   $D7
21BC-   20 CD C1    JSR   $C1CD
21BF-   C3          ???
21C0-   D2 CF       CMP   ($CF)
21C2-   D3          ???
21C3-   20 D4 C8    JSR   $C8D4
21C6-   D2 CF       CMP   ($CF)
21C8-   D7          ???
21C9-   CE 20 C9    DEC   $C920
21CC-   CE 20 D4    DEC   $D420
21CF-   CF          ???
21D0-   20 CD C1    JSR   $C1CD
21D3-   CB          ???
21D4-   C5 20       CMP   $20
21D6-   C9 D4       CMP   #$D4
21D8-   20 AA C6    JSR   $C6AA
21DB-   C5 C5       CMP   $C5
21DD-   CC AA A2    CPY   $A2AA
21E0-   AC B8 C4    LDY   $C4B8
21E3-   8D A0 DF    STA   $DFA0
21E6-   D0 D2       BNE   $21BA
21E8-   CE D4 A0    DEC   $A0D4
21EB-   A2 CD       LDX   #$CD
21ED-   CF          ???
21EE-   D2 C5       CMP   ($C5)
21F0-   20 D3 C5    JSR   $C5D3
21F3-   D2 C9       CMP   ($C9)
21F5-   C1 CC       CMP   ($CC,X)
21F7-   C9 DA       CMP   #$DA
21F9-   C5 C4       CMP   $C4
21FB-   AE 20 D4    LDX   $D420
21FE-   C8          INY
21FF-   C5 20       CMP   $20
2201-   C6 CF       DEC   $CF
2203-   CC CC CF    CPY   $CFCC
2206-   D7          ???
2207-   C9 CE       CMP   #$CE
2209-   C7          ???
220A-   20 CD C1    JSR   $C1CD
220D-   C3          ???
220E-   D2 CF       CMP   ($CF)
2210-   D3          ???
2211-   A2 AC       LDX   #$AC
2213-   B8          CLV
2214-   C4 8D       CPY   $8D
2216-   A0 DF       LDY   #$DF
2218-   D0 D2       BNE   $21EC
221A-   CE D4 A0    DEC   $A0D4
221D-   A2 C1       LDX   #$C1
221F-   CC D4 C5    CPY   $C5D4
2222-   D2 20       CMP   ($20)
2224-   D4          ???
2225-   C8          INY
2226-   C5 20       CMP   $20
2228-   D2 D7       CMP   ($D7)
222A-   D4          ???
222B-   D3          ???
222C-   20 D2 CF    JSR   $CFD2
222F-   D5 D4       CMP   $D4,X
2231-   C9 CE       CMP   #$CE
2233-   C5 A7       CMP   $A7
2235-   D3          ???
2236-   20 C2 C5    JSR   $C5C2
2239-   C1 C8       CMP   ($C8,X)
223B-   D6 C9       DEC   $C9,X
223D-   CF          ???
223E-   D2 BA       CMP   ($BA)
2240-   A2 AC       LDX   #$AC
2242-   B8          CLV
2243-   C4 B8       CPY   $B8
2245-   C4 8D       CPY   $8D
2247-   A0 DF       LDY   #$DF
2249-   D0 D2       BNE   $221D
224B-   CE D4 A0    DEC   $A0D4
224E-   A2 D3       LDX   #$D3
2250-   CC CF D4    CPY   $D4CF
2253-   20 BA 20    JSR   $20BA
2256-   D3          ???
2257-   C5 D4       CMP   $D4
2259-   D3          ???
225A-   20 D4 C8    JSR   $C8D4
225D-   C5 20       CMP   $20
225F-   D2 D7       CMP   ($D7)
2261-   D4          ???
2262-   D3          ???
2263-   20 D3 CC    JSR   $CCD3
2266-   CF          ???
2267-   D4          ???
2268-   A2 AC       LDX   #$AC
226A-   B8          CLV
226B-   C4 8D       CPY   $8D
226D-   A0 DF       LDY   #$DF
226F-   D0 D2       BNE   $2243
2271-   CE D4 A0    DEC   $A0D4
2274-   A2 C4       LDX   #$C4
2276-   D2 C9       CMP   ($C9)
2278-   D6 C5       DEC   $C5,X
227A-   BA          TSX
227B-   20 D3 C5    JSR   $C5D3
227E-   D4          ???
227F-   D3          ???
2280-   20 D4 C8    JSR   $C8D4
2283-   C5 20       CMP   $20
2285-   D2 D7       CMP   ($D7)
2287-   D4          ???
2288-   D3          ???
2289-   20 C4 D2    JSR   $D2C4
228C-   C9 D6       CMP   #$D6
228E-   C5 A2       CMP   $A2
2290-   AC B8 C4    LDY   $C4B8
2293-   8D A0 DF    STA   $DFA0
2296-   D0 D2       BNE   $226A
2298-   CE D4 A0    DEC   $A0D4
229B-   A2 D4       LDX   #$D4
229D-   D2 C1       CMP   ($C1)
229F-   C3          ???
22A0-   CB          ???
22A1-   BA          TSX
22A2-   20 D3 C5    JSR   $C5D3
22A5-   D4          ???
22A6-   D3          ???
22A7-   20 D4 C8    JSR   $C8D4
22AA-   C5 20       CMP   $20
22AC-   D4          ???
22AD-   D2 C1       CMP   ($C1)
22AF-   C3          ???
22B0-   CB          ???
22B1-   20 D4 CF    JSR   $CFD4
22B4-   20 C2 C5    JSR   $C5C2
22B7-   20 D7 D2    JSR   $D2D7
22BA-   C9 D4       CMP   #$D4
22BC-   D4          ???
22BD-   C5 CE       CMP   $CE
22BF-   AF          ???
22C0-   D2 C5       CMP   ($C5)
22C2-   C1 C4       CMP   ($C4,X)
22C4-   A2 AC       LDX   #$AC
22C6-   B8          CLV
22C7-   C4 8D       CPY   $8D
22C9-   A0 DF       LDY   #$DF
22CB-   D0 D2       BNE   $229F
22CD-   CE D4 A0    DEC   $A0D4
22D0-   A2 D3       LDX   #$D3
22D2-   C5 C3       CMP   $C3
22D4-   D4          ???
22D5-   20 BA 20    JSR   $20BA
22D8-   D3          ???
22D9-   C5 D4       CMP   $D4
22DB-   D3          ???
22DC-   20 D4 C8    JSR   $C8D4
22DF-   C5 20       CMP   $20
22E1-   D3          ???
22E2-   C5 C3       CMP   $C3
22E4-   D4          ???
22E5-   CF          ???
22E6-   D2 20       CMP   ($20)
22E8-   D4          ???
22E9-   CF          ???
22EA-   20 C2 C5    JSR   $C5C2
22ED-   20 D2 C5    JSR   $C5D2
22F0-   C1 C4       CMP   ($C4,X)
22F2-   AF          ???
22F3-   D7          ???
22F4-   D2 C9       CMP   ($C9)
22F6-   D4          ???
22F7-   D4          ???
22F8-   C5 CE       CMP   $CE
22FA-   A2 AC       LDX   #$AC
22FC-   B8          CLV
22FD-   C4 8D       CPY   $8D
22FF-   A0 DF       LDY   #$DF
2301-   D0 D2       BNE   $22D5
2303-   CE D4 A0    DEC   $A0D4
2306-   A2 D3       LDX   #$D3
2308-   C5 D4       CMP   $D4
230A-   C4 D2       CPY   $D2
230C-   BA          TSX
230D-   20 D3 C5    JSR   $C5D3
2310-   D4          ???
2311-   20 D2 D7    JSR   $D7D2
2314-   D4          ???
2315-   D3          ???
2316-   20 D4 CF    JSR   $CFD4
2319-   20 D2 C5    JSR   $C5D2
231C-   C1 C4       CMP   ($C4,X)
231E-   20 CD CF    JSR   $CFCD
2321-   C4 C5       CPY   $C5
2323-   A2 AC       LDX   #$AC
2325-   B8          CLV
2326-   C4 8D       CPY   $8D
2328-   A0 DF       LDY   #$DF
232A-   D0 D2       BNE   $22FE
232C-   CE D4 A0    DEC   $A0D4
232F-   A2 D3       LDX   #$D3
2331-   C5 D4       CMP   $D4
2333-   C4 D7       CPY   $D7
2335-   BA          TSX
2336-   20 D3 C5    JSR   $C5D3
2339-   D4          ???
233A-   20 D2 D7    JSR   $D7D2
233D-   D4          ???
233E-   D3          ???
233F-   20 D4 CF    JSR   $CFD4
2342-   20 D7 D2    JSR   $D2D7
2345-   C9 D4       CMP   #$D4
2347-   C5 20       CMP   $20
2349-   CD CF C4    CMP   $C4CF
234C-   C5 A2       CMP   $A2
234E-   AC B8 C4    LDY   $C4B8
2351-   8D A0 DF    STA   $DFA0
2354-   D0 D2       BNE   $2328
2356-   CE D4 A0    DEC   $A0D4
2359-   A2 C4       LDX   #$C4
235B-   C2          ???
235C-   D5 C6       CMP   $C6,X
235E-   C6 BA       DEC   $BA
2360-   20 D3 C5    JSR   $C5D3
2363-   D4          ???
2364-   20 D4 C8    JSR   $C8D4
2367-   C5 20       CMP   $20
2369-   D2 C5       CMP   ($C5)
236B-   C1 C4       CMP   ($C4,X)
236D-   AF          ???
236E-   D7          ???
236F-   D2 C9       CMP   ($C9)
2371-   D4          ???
2372-   C5 20       CMP   $20
2374-   C2          ???
2375-   D5 C6       CMP   $C6,X
2377-   C6 C5       DEC   $C5
2379-   D2 20       CMP   ($20)
237B-   C1 C4       CMP   ($C4,X)
237D-   C4 D2       CPY   $D2
237F-   C5 D3       CMP   $D3
2381-   D3          ???
2382-   A2 AC       LDX   #$AC
2384-   B8          CLV
2385-   C4 B8       CPY   $B8
2387-   C4 8D       CPY   $8D
2389-   A0 DF       LDY   #$DF
238B-   D7          ???
238C-   C1 C9       CMP   ($C9,X)
238E-   D4          ???
238F-   8D A0 DF    STA   $DFA0
2392-   D0 D2       BNE   $2366
2394-   CE D4 A0    DEC   $A0D4
2397-   A2 C5       LDX   #$C5
2399-   C1 C3       CMP   ($C3,X)
239B-   C8          INY
239C-   20 CF C6    JSR   $C6CF
239F-   20 D4 C8    JSR   $C8D4
23A2-   C5 D3       CMP   $D3
23A4-   C5 20       CMP   $20
23A6-   D3          ???
23A7-   C5 D4       CMP   $D4
23A9-   D4          ???
23AA-   C9 CE       CMP   #$CE
23AC-   C7          ???
23AD-   D3          ???
23AE-   20 C1 D2    JSR   $D2C1
23B1-   C5 20       CMP   $20
23B3-   C9 CE       CMP   #$CE
23B5-   C8          INY
23B6-   C5 D2       CMP   $D2
23B8-   C9 D4       CMP   #$D4
23BA-   C5 C4       CMP   $C4
23BC-   A2 AC       LDX   #$AC
23BE-   B8          CLV
23BF-   C4 8D       CPY   $8D
23C1-   A0 DF       LDY   #$DF
23C3-   D0 D2       BNE   $2397
23C5-   CE D4 A0    DEC   $A0D4
23C8-   A2 C6       LDX   #$C6
23CA-   D2 CF       CMP   ($CF)
23CC-   CD 20 D4    CMP   $D420
23CF-   C8          INY
23D0-   C5 20       CMP   $20
23D2-   D0 D2       BNE   $23A6
23D4-   C5 D6       CMP   $D6
23D6-   C9 CF       CMP   #$CF
23D8-   D5 D3       CMP   $D3,X
23DA-   20 D3 D4    JSR   $D4D3
23DD-   C1 D4       CMP   ($D4,X)
23DF-   C5 BB       CMP   $BB
23E1-   20 C9 C6    JSR   $C6C9
23E4-   20 D9 CF    JSR   $CFD9
23E7-   D5 20       CMP   $20,X
23E9-   C1 D2       CMP   ($D2,X)
23EB-   C5 A2       CMP   $A2
23ED-   AC B8 C4    LDY   $C4B8
23F0-   8D A0 DF    STA   $DFA0
23F3-   D0 D2       BNE   $23C7
23F5-   CE D4 A0    DEC   $A0D4
23F8-   A2 C1       LDX   #$C1
23FA-   CC D2 C5    CPY   $C5D2
23FD-   C1 C4       CMP   ($C4,X)
23FF-   D9 20 D5    CMP   $D520,Y
2402-   D3          ???
2403-   C9 CE       CMP   #$CE
2405-   C7          ???
2406-   20 D3 C5    JSR   $C5D3
2409-   C3          ???
240A-   D4          ???
240B-   CF          ???
240C-   D2 20       CMP   ($20)
240E-   B6 AC       LDX   $AC,Y
2410-   20 C4 D2    JSR   $D2C4
2413-   C9 D6       CMP   #$D6
2415-   C5 20       CMP   $20
2417-   B1 AC       LDA   ($AC),Y
2419-   20 C6 CF    JSR   $CFC6
241C-   D2 A2       CMP   ($A2)
241E-   AC B8 C4    LDY   $C4B8
2421-   8D A0 DF    STA   $DFA0
2424-   D0 D2       BNE   $23F8
2426-   CE D4 A0    DEC   $A0D4
2429-   A2 C5       LDX   #$C5
242B-   D8          CLD
242C-   C1 CD       CMP   ($CD,X)
242E-   D0 CC       BNE   $23FC
2430-   C5 AC       CMP   $AC
2432-   20 D4 C8    JSR   $C8D4
2435-   C5 CE       CMP   $CE
2437-   20 D9 CF    JSR   $CFD9
243A-   D5 20       CMP   $20,X
243C-   C4 CF       CPY   $CF
243E-   CE A7 D4    DEC   $D4A7
2441-   20 C8 C1    JSR   $C1C8
2444-   D6 C5       DEC   $C5,X
2446-   20 D4 CF    JSR   $CFD4
2449-   20 D3 C5    JSR   $C5D3
244C-   D4          ???
244D-   20 C9 D4    JSR   $D4C9
2450-   20 C1 C7    JSR   $C7C1
2453-   C1 C9       CMP   ($C9,X)
2455-   CE A2 AC    DEC   $ACA2
2458-   B8          CLV
2459-   C4 8D       CPY   $8D
245B-   A0 DF       LDY   #$DF
245D-   D0 D2       BNE   $2431
245F-   CE D4 A0    DEC   $A0D4
2462-   A2 D5       LDX   #$D5
2464-   CE CC C5    DEC   $C5CC
2467-   D3          ???
2468-   D3          ???
2469-   20 D9 CF    JSR   $CFD9
246C-   D5 20       CMP   $20,X
246E-   D7          ???
246F-   C1 CE       CMP   ($CE,X)
2471-   D4          ???
2472-   20 D4 C8    JSR   $C8D4
2475-   CF          ???
2476-   D3          ???
2477-   C5 20       CMP   $20
2479-   D3          ???
247A-   C5 D4       CMP   $D4
247C-   D4          ???
247D-   C9 CE       CMP   #$CE
247F-   C7          ???
2480-   D3          ???
2481-   20 C3 C8    JSR   $C8C3
2484-   C1 CE       CMP   ($CE,X)
2486-   C7          ???
2487-   C5 C4       CMP   $C4
2489-   AE A2 AC    LDX   $ACA2
248C-   B8          CLV
248D-   C4 8D       CPY   $8D
248F-   A0 DF       LDY   #$DF
2491-   D0 D2       BNE   $2465
2493-   CE D4 A0    DEC   $A0D4
2496-   A2 D4       LDX   #$D4
2498-   C8          INY
2499-   C9 D3       CMP   #$D3
249B-   20 CC C9    JSR   $C9CC
249E-   C2          ???
249F-   D2 C1       CMP   ($C1)
24A1-   D2 D9       CMP   ($D9)
24A3-   20 C1 CC    JSR   $CCC1
24A6-   D3          ???
24A7-   CF          ???
24A8-   20 D5 D3    JSR   $D3D5
24AB-   C5 D3       CMP   $D3
24AD-   20 D4 C8    JSR   $C8D4
24B0-   C5 20       CMP   $20
24B2-   D3          ???
24B3-   C1 CD       CMP   ($CD,X)
24B5-   C5 20       CMP   $20
24B7-   C9 CF       CMP   #$CF
24B9-   C2          ???
24BA-   A2 AC       LDX   #$AC
24BC-   B8          CLV
24BD-   C4 8D       CPY   $8D
24BF-   A0 DF       LDY   #$DF
24C1-   D0 D2       BNE   $2495
24C3-   CE D4 A0    DEC   $A0D4
24C6-   A2 D4       LDX   #$D4
24C8-   C1 C2       CMP   ($C2,X)
24CA-   CC C5 20    CPY   $20C5
24CD-   C1 D3       CMP   ($D3,X)
24CF-   20 D4 C8    JSR   $C8D4
24D2-   C5 20       CMP   $20
24D4-   CF          ???
24D5-   D0 C5       BNE   $249C
24D7-   D2 C1       CMP   ($C1)
24D9-   D4          ???
24DA-   C9 CE       CMP   #$CE
24DC-   C7          ???
24DD-   20 D3 D9    JSR   $D9D3
24E0-   D3          ???
24E1-   D4          ???
24E2-   C5 CD       CMP   $CD
24E4-   20 A8 C4    JSR   $C4A8
24E7-   CF          ???
24E8-   D3          ???
24E9-   20 CF D2    JSR   $D2CF
24EC-   A2 AC       LDX   #$AC
24EE-   B8          CLV
24EF-   C4 8D       CPY   $8D
24F1-   A0 DF       LDY   #$DF
24F3-   D0 D2       BNE   $24C7
24F5-   CE D4 A0    DEC   $A0D4
24F8-   A2 D0       LDX   #$D0
24FA-   D2 CF       CMP   ($CF)
24FC-   C4 CF       CPY   $CF
24FE-   D3          ???
24FF-   A9 20       LDA   #$20
2501-   D4          ???
2502-   CF          ???
2503-   20 C3 C1    JSR   $C1C3
2506-   D2 D2       CMP   ($D2)
2508-   D9 20 CF    CMP   $CF20,Y
250B-   D6 C5       DEC   $C5,X
250D-   D2 20       CMP   ($20)
250F-   C1 CE       CMP   ($CE,X)
2511-   D9 20 D0    CMP   $D020,Y
2514-   D2 C5       CMP   ($C5)
2516-   D6 C9       DEC   $C9,X
2518-   CF          ???
2519-   D5 D3       CMP   $D3,X
251B-   20 D3 C5    JSR   $C5D3
251E-   D4          ???
251F-   D4          ???
2520-   C9 CE       CMP   #$CE
2522-   C7          ???
2523-   D3          ???
2524-   AE A2 AC    LDX   $ACA2
2527-   B8          CLV
2528-   C4 B8       CPY   $B8
252A-   C4 8D       CPY   $8D
252C-   A0 DF       LDY   #$DF
252E-   D7          ???
252F-   C1 C9       CMP   ($C9,X)
2531-   D4          ???
2532-   8D AA 8D    STA   $8DAA
2535-   A0 DF       LDY   #$DF
2537-   D0 D2       BNE   $250B
2539-   CE D4 A0    DEC   $A0D4
253C-   A2 CF       LDX   #$CF
253E-   CE C3 C5    DEC   $C5C3
2541-   20 D4 C8    JSR   $C8D4
2544-   C5 20       CMP   $20
2546-   D3          ???
2547-   C5 D4       CMP   $D4
2549-   D4          ???
254A-   C9 CE       CMP   #$CE
254C-   C7          ???
254D-   D3          ???
254E-   20 C1 D2    JSR   $D2C1
2551-   C5 20       CMP   $20
2553-   C1 D3       CMP   ($D3,X)
2555-   20 C4 C5    JSR   $C5C4
2558-   D3          ???
2559-   C9 D2       CMP   #$D2
255B-   C5 C4       CMP   $C4
255D-   AC A2 AC    LDY   $ACA2
2560-   B8          CLV
2561-   C4 8D       CPY   $8D
2563-   A0 DF       LDY   #$DF
2565-   D0 D2       BNE   $2539
2567-   CE D4 A0    DEC   $A0D4
256A-   A2 D9       LDX   #$D9
256C-   CF          ???
256D-   D5 20       CMP   $20,X
256F-   D5 D3       CMP   $D3,X
2571-   C5 20       CMP   $20
2573-   D4          ???
2574-   C8          INY
2575-   C5 20       CMP   $20
2577-   C4 D2       CPY   $D2
2579-   D7          ???
257A-   D4          ???
257B-   D3          ???
257C-   20 CD C1    JSR   $C1CD
257F-   C3          ???
2580-   D2 CF       CMP   ($CF)
2582-   20 D4 CF    JSR   $CFD4
2585-   20 C3 C1    JSR   $C1C3
2588-   CC CC A2    CPY   $A2CC
258B-   AC B8 C4    LDY   $C4B8
258E-   8D A0 DF    STA   $DFA0
2591-   D0 D2       BNE   $2565
2593-   CE D4 A0    DEC   $A0D4
2596-   A2 D4       LDX   #$D4
2598-   C8          INY
2599-   C5 20       CMP   $20
259B-   D2 D7       CMP   ($D7)
259D-   D4          ???
259E-   D3          ???
259F-   20 D2 CF    JSR   $CFD2
25A2-   D5 D4       CMP   $D4,X
25A4-   C9 CE       CMP   #$CE
25A6-   C5 20       CMP   $20
25A8-   D4          ???
25A9-   CF          ???
25AA-   20 CD C1    JSR   $C1CD
25AD-   CB          ???
25AE-   C5 20       CMP   $20
25B0-   D4          ???
25B1-   C8          INY
25B2-   C5 20       CMP   $20
25B4-   A2 AC       LDX   #$AC
25B6-   B8          CLV
25B7-   C4 8D       CPY   $8D
25B9-   A0 DF       LDY   #$DF
25BB-   D0 D2       BNE   $258F
25BD-   CE D4 A0    DEC   $A0D4
25C0-   A2 C1       LDX   #$C1
25C2-   D0 D0       BNE   $2594
25C4-   D2 CF       CMP   ($CF)
25C6-   D0 D2       BNE   $259A
25C8-   C9 C1       CMP   #$C1
25CA-   D4          ???
25CB-   C5 20       CMP   $20
25CD-   D2 C5       CMP   ($C5)
25CF-   C1 C4       CMP   ($C4,X)
25D1-   20 CF D2    JSR   $D2CF
25D4-   20 D7 D2    JSR   $D2D7
25D7-   C9 D4       CMP   #$D4
25D9-   C5 20       CMP   $20
25DB-   C3          ???
25DC-   C8          INY
25DD-   C1 CE       CMP   ($CE,X)
25DF-   C7          ???
25E0-   C5 20       CMP   $20
25E2-   D4          ???
25E3-   CF          ???
25E4-   A2 AC       LDX   #$AC
25E6-   B8          CLV
25E7-   C4 8D       CPY   $8D
25E9-   A0 DF       LDY   #$DF
25EB-   D0 D2       BNE   $25BF
25ED-   CE D4 A0    DEC   $A0D4
25F0-   A2 D4       LDX   #$D4
25F2-   C8          INY
25F3-   C5 20       CMP   $20
25F5-   C4 C9       CPY   $C9
25F7-   D3          ???
25F8-   CB          ???
25F9-   AE A2 AC    LDX   $ACA2
25FC-   B8          CLV
25FD-   C4 B8       CPY   $B8
25FF-   C4 8D       CPY   $8D
2601-   A0 DF       LDY   #$DF
2603-   D0 D2       BNE   $25D7
2605-   CE D4 A0    DEC   $A0D4
2608-   A2 C6       LDX   #$C6
260A-   CF          ???
260B-   D2 20       CMP   ($20)
260D-   D4          ???
260E-   C8          INY
260F-   C5 20       CMP   $20
2611-   D3          ???
2612-   C1 CB       CMP   ($CB,X)
2614-   C5 20       CMP   $20
2616-   CF          ???
2617-   C6 20       DEC   $20
2619-   D0 CC       BNE   $25E7
261B-   C1 D9       CMP   ($D9,X)
261D-   C9 CE       CMP   #$CE
261F-   C7          ???
2620-   20 C9 D4    JSR   $D4C9
2623-   20 D3 C1    JSR   $C1D3
2626-   C6 C5       DEC   $C5
2628-   AC A2 AC    LDY   $ACA2
262B-   B8          CLV
262C-   C4 8D       CPY   $8D
262E-   A0 DF       LDY   #$DF
2630-   D0 D2       BNE   $2604
2632-   CE D4 A0    DEC   $A0D4
2635-   A2 D7       LDX   #$D7
2637-   C5 20       CMP   $20
2639-   D7          ???
263A-   CF          ???
263B-   CE A7 D4    DEC   $D4A7
263E-   20 C2 C5    JSR   $C5C2
2641-   20 C4 CF    JSR   $CFC4
2644-   C9 CE       CMP   #$CE
2646-   C7          ???
2647-   20 D4 C8    JSR   $C8D4
264A-   C1 D4       CMP   ($D4,X)
264C-   20 C8 C5    JSR   $C5C8
264F-   D2 C5       CMP   ($C5)
2651-   AD AD D9    LDA   $D9AD
2654-   CF          ???
2655-   D5 20       CMP   $20,X
2657-   C3          ???
2658-   C1 CE       CMP   ($CE,X)
265A-   A2 AC       LDX   #$AC
265C-   B8          CLV
265D-   C4 8D       CPY   $8D
265F-   A0 DF       LDY   #$DF
2661-   D0 D2       BNE   $2635
2663-   CE D4 A0    DEC   $A0D4
2666-   A2 C5       LDX   #$C5
2668-   D8          CLD
2669-   D0 C5       BNE   $2630
266B-   D2 C9       CMP   ($C9)
266D-   CD C5 CE    CMP   $CEC5
2670-   D4          ???
2671-   20 CF CE    JSR   $CECF
2674-   20 D9 CF    JSR   $CFD9
2677-   D5 D2       CMP   $D2,X
2679-   20 CF D7    JSR   $D7CF
267C-   CE 20 D7    DEC   $D720
267F-   C9 D4       CMP   #$D4
2681-   C8          INY
2682-   20 D4 C8    JSR   $C8D4
2685-   C5 D3       CMP   $D3
2687-   C5 20       CMP   $20
2689-   C3          ???
268A-   C1 CC       CMP   ($CC,X)
268C-   CC D3 BB    CPY   $BBD3
268F-   A2 AC       LDX   #$AC
2691-   B8          CLV
2692-   C4 8D       CPY   $8D
2694-   A0 DF       LDY   #$DF
2696-   D0 D2       BNE   $266A
2698-   CE D4 A0    DEC   $A0D4
269B-   A2 D4       LDX   #$D4
269D-   C8          INY
269E-   C1 D4       CMP   ($D4,X)
26A0-   20 D7 C1    JSR   $C1D7
26A3-   D9 20 C9    CMP   $C920,Y
26A6-   C6 20       DEC   $20
26A8-   D3          ???
26A9-   CF          ???
26AA-   CD C5 D4    CMP   $D4C5
26AD-   C8          INY
26AE-   C9 CE       CMP   #$CE
26B0-   C7          ???
26B1-   20 C2 C1    JSR   $C1C2
26B4-   C4 20       CPY   $20
26B6-   C8          INY
26B7-   C1 D0       CMP   ($D0,X)
26B9-   D0 C5       BNE   $2680
26BB-   CE D3 AC    DEC   $ACD3
26BE-   A2 AC       LDX   #$AC
26C0-   B8          CLV
26C1-   C4 8D       CPY   $8D
26C3-   A0 DF       LDY   #$DF
26C5-   D0 D2       BNE   $2699
26C7-   CE D4 A0    DEC   $A0D4
26CA-   A2 C9       LDX   #$C9
26CC-   D4          ???
26CD-   A7          ???
26CE-   D3          ???
26CF-   20 CF CE    JSR   $CECF
26D2-   20 D9 CF    JSR   $CFD9
26D5-   D5 AD       CMP   $AD,X
26D7-   AD CE CF    LDA   $CFCE
26DA-   D4          ???
26DB-   20 CD C5    JSR   $C5CD
26DE-   A1 20       LDA   ($20,X)
26E0-   BA          TSX
26E1-   A9 A2       LDA   #$A2
26E3-   AC B8 C4    LDY   $C4B8
26E6-   B8          CLV
26E7-   C4 B8       CPY   $B8
26E9-   C4 8D       CPY   $8D
26EB-   A0 DF       LDY   #$DF
26ED-   D7          ???
26EE-   C1 C9       CMP   ($C9,X)
26F0-   D4          ???
26F1-   8D AA 8D    STA   $8DAA
26F4-   A0 CA       LDY   #$CA
26F6-   CD D0 A0    CMP   $A0D0
26F9-   D2 C5       CMP   ($C5)
26FB-   C5 CE       CMP   $CE
26FD-   D4          ???
26FE-   D2 D9       CMP   ($D9)
2700-   8D AA 8D    STA   $8DAA
2703-   D2 C5       CMP   ($C5)
2705-   D4          ???
2706-   CF          ???
2707-   D2 D4       CMP   ($D4)
2709-   A0 D3       LDY   #$D3
270B-   D4          ???
270C-   D2 A0       CMP   ($A0)
270E-   A2 C9       LDX   #$C9
2710-   C6 20       DEC   $20
2712-   D9 CF D5    CMP   $D5CF,Y
2715-   20 C1 D2    JSR   $D2C1
2718-   C5 20       CMP   $20
271A-   D2 C9       CMP   ($C9)
271C-   C3          ???
271D-   C8          INY
271E-   AC 20 C1    LDY   $C120
2721-   CE D9 C8    DEC   $C8D9
2724-   CF          ???
2725-   D7          ???
2726-   AE AE AE    LDX   $AEAE
2729-   A2 8D       LDX   #$8D
272B-   AA          TAX
272C-   8D AA E0    STA   $E0AA
272F-   E0 E0       CPX   #$E0
2731-   E0 E0       CPX   #$E0
2733-   E0 E0       CPX   #$E0
2735-   E0 E0       CPX   #$E0
2737-   E0 E0       CPX   #$E0
2739-   E0 E0       CPX   #$E0
273B-   E0 E0       CPX   #$E0
273D-   E0 E0       CPX   #$E0
273F-   E0 E0       CPX   #$E0
2741-   E0 E0       CPX   #$E0
2743-   E0 E0       CPX   #$E0
2745-   E0 E0       CPX   #$E0
2747-   E0 E0       CPX   #$E0
2749-   E0 E0       CPX   #$E0
274B-   E0 AA       CPX   #$AA
274D-   8D AA 20    STA   $20AA
2750-   20 20 20    JSR   $2020
2753-   20 20 20    JSR   $2020
2756-   20 C2 CF    JSR   $CFC2
2759-   D4          ???
275A-   D4          ???
275B-   CF          ???
275C-   CD 20 C9    CMP   $C920
275F-   CE C3 CC    DEC   $CCC3
2762-   D5 C4       CMP   $C4,X
2764-   C5 D3       CMP   $D3
2766-   20 20 20    JSR   $2020
2769-   20 20 20    JSR   $2020
276C-   20 AA 8D    JSR   $8DAA
276F-   AA          TAX
2770-   AC AC AC    LDY   $ACAC
2773-   AC AC AC    LDY   $ACAC
2776-   AC AC AC    LDY   $ACAC
2779-   AC AC AC    LDY   $ACAC
277C-   AC AC AC    LDY   $ACAC
277F-   AC AC AC    LDY   $ACAC
2782-   AC AC AC    LDY   $ACAC
2785-   AC AC AC    LDY   $ACAC
2788-   AC AC AC    LDY   $ACAC
278B-   AC AC AC    LDY   $ACAC
278E-   AA          TAX
278F-   8D AA 8D    STA   $8DAA
2792-   A0 D0       LDY   #$D0
2794-   D5 D4       CMP   $D4,X
2796-   A0 CD       LDY   #$CD
2798-   C9 CE       CMP   #$CE
279A-   AE CC C9    LDX   $C9CC
279D-   C2          ???
279E-   AE D2 C5    LDX   $C5D2
27A1-   D1 D5       CMP   ($D5),Y
27A3-   C9 D2       CMP   #$D2
27A5-   C5 C4       CMP   $C4
27A7-   8D AA 8D    STA   $8DAA
27AA-   AA          TAX
27AB-   AA          TAX
27AC-   20 C9 CE    JSR   $CEC9
27AF-   C4 C9       CPY   $C9
27B1-   D6 C9       DEC   $C9,X
27B3-   C4 D5       CPY   $D5
27B5-   C1 CC       CMP   ($CC,X)
27B7-   20 D3 D5    JSR   $D5D3
27BA-   C2          ???
27BB-   D2 CF       CMP   ($CF)
27BD-   D5 D4       CMP   $D4,X
27BF-   C9 CE       CMP   #$CE
27C1-   C5 D3       CMP   $D3
27C3-   8D AA 8D    STA   $8DAA
27C6-   AA          TAX
27C7-   AA          TAX
27C8-   20 C6 C9    JSR   $C9C6
27CB-   CC C5 C9    CPY   $C9C5
27CE-   CF          ???
27CF-   20 D3 D5    JSR   $D5D3
27D2-   C2          ???
27D3-   D2 CF       CMP   ($CF)
27D5-   D5 D4       CMP   $D4,X
27D7-   C9 CE       CMP   #$CE
27D9-   C5 D3       CMP   $D3
27DB-   8D AA 8D    STA   $8DAA
27DE-   A0 D0       LDY   #$D0
27E0-   D5 D4       CMP   $D4,X
27E2-   A0 CD       LDY   #$CD
27E4-   C9 CE       CMP   #$CE
27E6-   AE D3 D5    LDX   $D5D3
27E9-   C2          ???
27EA-   AE C2 C9    LDX   $C9C2
27ED-   CE CC CF    DEC   $CFCC
27F0-   C1 C4       CMP   ($C4,X)
27F2-   8D A0 D0    STA   $D0A0
27F5-   D5 D4       CMP   $D4,X
27F7-   A0 CD       LDY   #$CD
27F9-   C9 CE       CMP   #$CE
27FB-   AE D3 D5    LDX   $D5D3
27FE-   C2          ???
27FF-   AE C2 C9    LDX   $C9C2
2802-   CE D3 C1    DEC   $C1D3
2805-   D6 C5       DEC   $C5,X
2807-   8D A0 D0    STA   $D0A0
280A-   D5 D4       CMP   $D4,X
280C-   A0 CD       LDY   #$CD
280E-   C9 CE       CMP   #$CE
2810-   AE D3 D5    LDX   $D5D3
2813-   C2          ???
2814-   AE C4 C9    LDX   $C9C4
2817-   D3          ???
2818-   CB          ???
2819-   CF          ???
281A-   D0 8D       BNE   $27A9
281C-   A0 D0       LDY   #$D0
281E-   D5 D4       CMP   $D4,X
2820-   A0 CD       LDY   #$CD
2822-   C9 CE       CMP   #$CE
2824-   AE D3 D5    LDX   $D5D3
2827-   C2          ???
2828-   AE C4 CF    LDX   $CFC4
282B-   D3          ???
282C-   C3          ???
282D-   CD C4 8D    CMP   $8DC4
2830-   A0 D0       LDY   #$D0
2832-   D5 D4       CMP   $D4,X
2834-   A0 CD       LDY   #$CD
2836-   C9 CE       CMP   #$CE
2838-   AE D3 D5    LDX   $D5D3
283B-   C2          ???
283C-   AE C6 C9    LDX   $C9C6
283F-   CE D0 D5    DEC   $D5D0
2842-   D4          ???
2843-   8D A0 D0    STA   $D0A0
2846-   D5 D4       CMP   $D4,X
2848-   A0 CD       LDY   #$CD
284A-   C9 CE       CMP   #$CE
284C-   AE D3 D5    LDX   $D5D3
284F-   C2          ???
2850-   AE C6 D0    LDX   $D0C6
2853-   D2 C9       CMP   ($C9)
2855-   CE D4 8D    DEC   $8DD4
2858-   A0 D0       LDY   #$D0
285A-   D5 D4       CMP   $D4,X
285C-   A0 CD       LDY   #$CD
285E-   C9 CE       CMP   #$CE
2860-   AE D3 D5    LDX   $D5D3
2863-   C2          ???
2864-   AE C6 D0    LDX   $D0C6
2867-   D3          ???
2868-   D4          ???
2869-   D2 8D       CMP   ($8D)
