0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C6    LDY   $C620,X
0950-   C9 CC       CMP   #$CC
0952-   C5 C9       CMP   $C9
0954-   CF          ???
0955-   20 20 C4    JSR   $C420
0958-   C5 CD       CMP   $CD
095A-   CF          ???
095B-   20 BE AD    JSR   $ADBE
095E-   20 20 20    JSR   $2020
0961-   20 20 20    JSR   $2020
0964-   AA          TAX
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B2    JSR   $B220
09D4-   B1 AD       LDA   ($AD),Y
09D6-   CA          DEX
09D7-   C1 CE       CMP   ($CE,X)
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B9       LDA   ($B9),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 D4    STA   $D4A0
0B02-   D2 A0       CMP   ($A0)
0B04-   CF          ???
0B05-   CE 8D A0    DEC   $A08D
0B08-   C4 D3       CPY   $D3
0B0A-   CB          ???
0B0B-   A0 C6       LDY   #$C6
0B0D-   C9 CC       CMP   #$CC
0B0F-   C5 C9       CMP   $C9
0B11-   CF          ???
0B12-   AE C4 C5    LDX   $C5C4
0B15-   CD CF 8D    CMP   $8DCF
0B18-   A0 CF       LDY   #$CF
0B1A-   C2          ???
0B1B-   CA          DEX
0B1C-   A0 A4       LDY   #$A4
0B1E-   C2          ???
0B1F-   C6 C5       DEC   $C5
0B21-   B0 8D       BCS   $0AB0
0B23-   A0 CF       LDY   #$CF
0B25-   D2 C7       CMP   ($C7)
0B27-   A0 A4       LDY   #$A4
0B29-   B6 B0       LDX   $B0,Y
0B2B-   B0 B0       BCS   $0ADD
0B2D-   8D AA 8D    STA   $8DAA
0B30-   AA          TAX
0B31-   E0 E0       CPX   #$E0
0B33-   E0 E0       CPX   #$E0
0B35-   E0 E0       CPX   #$E0
0B37-   E0 E0       CPX   #$E0
0B39-   E0 E0       CPX   #$E0
0B3B-   E0 E0       CPX   #$E0
0B3D-   E0 E0       CPX   #$E0
0B3F-   E0 E0       CPX   #$E0
0B41-   E0 E0       CPX   #$E0
0B43-   E0 E0       CPX   #$E0
0B45-   E0 E0       CPX   #$E0
0B47-   E0 E0       CPX   #$E0
0B49-   E0 E0       CPX   #$E0
0B4B-   E0 E0       CPX   #$E0
0B4D-   E0 E0       CPX   #$E0
0B4F-   AA          TAX
0B50-   8D AA 20    STA   $20AA
0B53-   20 D4 CF    JSR   $CFD4
0B56-   D0 20       BNE   $0B78
0B58-   C9 CE       CMP   #$CE
0B5A-   C3          ???
0B5B-   CC D5 C4    CPY   $C4D5
0B5E-   C5 D3       CMP   $D3
0B60-   20 A8 C8    JSR   $C8A8
0B63-   CF          ???
0B64-   CF          ???
0B65-   CB          ???
0B66-   D3          ???
0B67-   AC CD C1    LDY   $C1CD
0B6A-   C3          ???
0B6B-   D2 CF       CMP   ($CF)
0B6D-   D3          ???
0B6E-   A9 20       LDA   #$20
0B70-   AA          TAX
0B71-   8D AA AC    STA   $ACAA
0B74-   AC AC AC    LDY   $ACAC
0B77-   AC AC AC    LDY   $ACAC
0B7A-   AC AC AC    LDY   $ACAC
0B7D-   AC AC AC    LDY   $ACAC
0B80-   AC AC AC    LDY   $ACAC
0B83-   AC AC AC    LDY   $ACAC
0B86-   AC AC AC    LDY   $ACAC
0B89-   AC AC AC    LDY   $ACAC
0B8C-   AC AC AC    LDY   $ACAC
0B8F-   AC AC AA    LDY   $AAAC
0B92-   8D AA 8D    STA   $8DAA
0B95-   A0 D0       LDY   #$D0
0B97-   D5 D4       CMP   $D4,X
0B99-   A0 D2       LDY   #$D2
0B9B-   C5 D1       CMP   $D1
0B9D-   D5 C9       CMP   $C9,X
0B9F-   D2 C5       CMP   ($C5)
0BA1-   C4 AE       CPY   $AE
0BA3-   D6 C1       DEC   $C1,X
0BA5-   D2 D3       CMP   ($D3)
0BA7-   8D A0 D5    STA   $D5A0
0BAA-   D3          ???
0BAB-   C5 A0       CMP   $A0
0BAD-   D2 C5       CMP   ($C5)
0BAF-   D1 D5       CMP   ($D5),Y
0BB1-   C9 D2       CMP   #$D2
0BB3-   C5 C4       CMP   $C4
0BB5-   AE CD C1    LDX   $C1CD
0BB8-   C3          ???
0BB9-   AE CD C9    LDX   $C9CD
0BBC-   CE 8D A0    DEC   $A08D
0BBF-   D0 D5       BNE   $0B96
0BC1-   D4          ???
0BC2-   A0 D2       LDY   #$D2
0BC4-   C5 D1       CMP   $D1
0BC6-   D5 C9       CMP   $C9,X
0BC8-   D2 C5       CMP   ($C5)
0BCA-   C4 AE       CPY   $AE
0BCC-   C8          INY
0BCD-   CF          ???
0BCE-   CF          ???
0BCF-   CB          ???
0BD0-   D3          ???
0BD1-   AE CD C9    LDX   $C9CD
0BD4-   CE 8D A0    DEC   $A08D
0BD7-   D5 D3       CMP   $D3,X
0BD9-   C5 A0       CMP   $A0
0BDB-   C6 C9       DEC   $C9
0BDD-   CC C5 C9    CPY   $C9C5
0BE0-   CF          ???
0BE1-   AE CD C1    LDX   $C1CD
0BE4-   C3          ???
0BE5-   AE CD C9    LDX   $C9CD
0BE8-   CE 8D A0    DEC   $A08D
0BEB-   D0 D5       BNE   $0BC2
0BED-   D4          ???
0BEE-   A0 C6       LDY   #$C6
0BF0-   C9 CC       CMP   #$CC
0BF2-   C5 C9       CMP   $C9
0BF4-   CF          ???
0BF5-   AE C8 CF    LDX   $CFC8
0BF8-   CF          ???
0BF9-   CB          ???
0BFA-   D3          ???
0BFB-   8D AA 8D    STA   $8DAA
0BFE-   AA          TAX
0BFF-   E0 E0       CPX   #$E0
0C01-   E0 E0       CPX   #$E0
0C03-   E0 E0       CPX   #$E0
0C05-   E0 E0       CPX   #$E0
0C07-   E0 E0       CPX   #$E0
0C09-   E0 E0       CPX   #$E0
0C0B-   E0 E0       CPX   #$E0
0C0D-   E0 E0       CPX   #$E0
0C0F-   E0 E0       CPX   #$E0
0C11-   E0 E0       CPX   #$E0
0C13-   E0 E0       CPX   #$E0
0C15-   E0 E0       CPX   #$E0
0C17-   E0 E0       CPX   #$E0
0C19-   E0 E0       CPX   #$E0
0C1B-   E0 E0       CPX   #$E0
0C1D-   AA          TAX
0C1E-   8D AA 20    STA   $20AA
0C21-   20 20 20    JSR   $2020
0C24-   20 20 D0    JSR   $D020
0C27-   D2 CF       CMP   ($CF)
0C29-   C7          ???
0C2A-   D2 C1       CMP   ($C1)
0C2C-   CD 20 CD    CMP   $CD20
0C2F-   C1 C9       CMP   ($C9,X)
0C31-   CE 20 C2    DEC   $C220
0C34-   CF          ???
0C35-   C4 D9       CPY   $D9
0C37-   20 20 20    JSR   $2020
0C3A-   20 20 20    JSR   $2020
0C3D-   20 AA 8D    JSR   $8DAA
0C40-   AA          TAX
0C41-   AC AC AC    LDY   $ACAC
0C44-   AC AC AC    LDY   $ACAC
0C47-   AC AC AC    LDY   $ACAC
0C4A-   AC AC AC    LDY   $ACAC
0C4D-   AC AC AC    LDY   $ACAC
0C50-   AC AC AC    LDY   $ACAC
0C53-   AC AC AC    LDY   $ACAC
0C56-   AC AC AC    LDY   $ACAC
0C59-   AC AC AC    LDY   $ACAC
0C5C-   AC AC AC    LDY   $ACAC
0C5F-   AA          TAX
0C60-   8D AA 8D    STA   $8DAA
0C63-   AA          TAX
0C64-   AA          TAX
0C65-   AA          TAX
0C66-   AA          TAX
0C67-   AA          TAX
0C68-   AA          TAX
0C69-   AA          TAX
0C6A-   AA          TAX
0C6B-   AA          TAX
0C6C-   AA          TAX
0C6D-   AA          TAX
0C6E-   AA          TAX
0C6F-   AA          TAX
0C70-   AA          TAX
0C71-   AA          TAX
0C72-   AA          TAX
0C73-   AA          TAX
0C74-   AA          TAX
0C75-   AA          TAX
0C76-   AA          TAX
0C77-   AA          TAX
0C78-   AA          TAX
0C79-   AA          TAX
0C7A-   AA          TAX
0C7B-   AA          TAX
0C7C-   AA          TAX
0C7D-   AA          TAX
0C7E-   AA          TAX
0C7F-   AA          TAX
0C80-   AA          TAX
0C81-   AA          TAX
0C82-   AA          TAX
0C83-   8D AA AA    STA   $AAAA
0C86-   AA          TAX
0C87-   AA          TAX
0C88-   AA          TAX
0C89-   AA          TAX
0C8A-   AA          TAX
0C8B-   AA          TAX
0C8C-   AA          TAX
0C8D-   AA          TAX
0C8E-   AA          TAX
0C8F-   AA          TAX
0C90-   AA          TAX
0C91-   AA          TAX
0C92-   AA          TAX
0C93-   AA          TAX
0C94-   AA          TAX
0C95-   AA          TAX
0C96-   AA          TAX
0C97-   AA          TAX
0C98-   AA          TAX
0C99-   AA          TAX
0C9A-   AA          TAX
0C9B-   AA          TAX
0C9C-   AA          TAX
0C9D-   AA          TAX
0C9E-   AA          TAX
0C9F-   AA          TAX
0CA0-   AA          TAX
0CA1-   AA          TAX
0CA2-   AA          TAX
0CA3-   AA          TAX
0CA4-   8D AA 20    STA   $20AA
0CA7-   20 20 20    JSR   $2020
0CAA-   20 20 20    JSR   $2020
0CAD-   20 20 20    JSR   $2020
0CB0-   20 20 20    JSR   $2020
0CB3-   20 20 20    JSR   $2020
0CB6-   20 20 20    JSR   $2020
0CB9-   20 20 20    JSR   $2020
0CBC-   20 20 20    JSR   $2020
0CBF-   20 20 20    JSR   $2020
0CC2-   20 20 AA    JSR   $AA20
0CC5-   8D AA 20    STA   $20AA
0CC8-   CE CF D4    DEC   $D4CF
0CCB-   C5 BA       CMP   $BA
0CCD-   20 C6 CF    JSR   $CFC6
0CD0-   D2 20       CMP   ($20)
0CD2-   D4          ???
0CD3-   C8          INY
0CD4-   C9 D3       CMP   #$D3
0CD6-   20 D4 CF    JSR   $CFD4
0CD9-   20 D7 CF    JSR   $CFD7
0CDC-   D2 CB       CMP   ($CB)
0CDE-   20 20 20    JSR   $2020
0CE1-   20 20 20    JSR   $2020
0CE4-   20 AA 8D    JSR   $8DAA
0CE7-   AA          TAX
0CE8-   20 D0 D2    JSR   $D2D0
0CEB-   CF          ???
0CEC-   D0 C5       BNE   $0CB3
0CEE-   D2 CC       CMP   ($CC)
0CF0-   D9 AC 20    CMP   $20AC,Y
0CF3-   D4          ???
0CF4-   C8          INY
0CF5-   C5 20       CMP   $20
0CF7-   C4 C5       CPY   $C5
0CF9-   CD CF 20    CMP   $20CF
0CFC-   C8          INY
0CFD-   C1 D3       CMP   ($D3,X)
0CFF-   20 D4 CF    JSR   $CFD4
0D02-   20 C2 C5    JSR   $C5C2
0D05-   20 AA 8D    JSR   $8DAA
0D08-   AA          TAX
0D09-   20 C2 CC    JSR   $CCC2
0D0C-   CF          ???
0D0D-   C1 C4       CMP   ($C4,X)
0D0F-   C5 C4       CMP   $C4
0D11-   AC 20 D4    LDY   $D420
0D14-   C8          INY
0D15-   C5 CE       CMP   $CE
0D17-   20 C5 D8    JSR   $D8C5
0D1A-   C5 C3       CMP   $C3
0D1C-   D5 D4       CMP   $D4,X
0D1E-   C5 C4       CMP   $C4
0D20-   20 D6 C9    JSR   $C9D6
0D23-   C1 20       CMP   ($20,X)
0D25-   20 20 AA    JSR   $AA20
0D28-   8D AA 20    STA   $20AA
0D2B-   D4          ???
0D2C-   C8          INY
0D2D-   C5 20       CMP   $20
0D2F-   CD CF CE    CMP   $CECF
0D32-   C9 D4       CMP   #$D4
0D34-   CF          ???
0D35-   D2 20       CMP   ($20)
0D37-   A8          TAY
0D38-   B6 B0       LDX   $B0,Y
0D3A-   B0 B0       BCS   $0CEC
0D3C-   C7          ???
0D3D-   A9 AE       LDA   #$AE
0D3F-   20 C9 C6    JSR   $C6C9
0D42-   20 D4 C8    JSR   $C8D4
0D45-   C9 D3       CMP   #$D3
0D47-   20 AA 8D    JSR   $8DAA
0D4A-   AA          TAX
0D4B-   20 C9 D3    JSR   $D3C9
0D4E-   20 CE CF    JSR   $CFCE
0D51-   D4          ???
0D52-   20 C4 CF    JSR   $CFC4
0D55-   CE C5 AC    DEC   $ACC5
0D58-   20 D9 CF    JSR   $CFD9
0D5B-   D5 20       CMP   $20,X
0D5D-   D7          ???
0D5E-   C9 CC       CMP   #$CC
0D60-   CC 20 C7    CPY   $C720
0D63-   C5 D4       CMP   $D4
0D65-   20 C1 20    JSR   $20C1
0D68-   20 AA 8D    JSR   $8DAA
0D6B-   AA          TAX
0D6C-   20 A2 C6    JSR   $C6A2
0D6F-   C9 CC       CMP   #$CC
0D71-   C5 20       CMP   $20
0D73-   CE CF D4    DEC   $D4CF
0D76-   20 C6 CF    JSR   $CFC6
0D79-   D5 CE       CMP   $CE,X
0D7B-   C4 A2       CPY   $A2
0D7D-   20 C5 D2    JSR   $D2C5
0D80-   D2 CF       CMP   ($CF)
0D82-   D2 20       CMP   ($20)
0D84-   D7          ???
0D85-   C8          INY
0D86-   C5 CE       CMP   $CE
0D88-   20 20 AA    JSR   $AA20
0D8B-   8D AA 20    STA   $20AA
0D8E-   C4 CF       CPY   $CF
0D90-   C9 CE       CMP   #$CE
0D92-   C7          ???
0D93-   20 C6 C9    JSR   $C9C6
0D96-   CC C5 20    CPY   $20C5
0D99-   CF          ???
0D9A-   D0 C5       BNE   $0D61
0D9C-   D2 C1       CMP   ($C1)
0D9E-   D4          ???
0D9F-   C9 CF       CMP   #$CF
0DA1-   CE D3 AE    DEC   $AED3
0DA4-   20 20 20    JSR   $2020
0DA7-   20 20 20    JSR   $2020
0DAA-   20 AA 8D    JSR   $8DAA
0DAD-   AA          TAX
0DAE-   20 20 20    JSR   $2020
0DB1-   20 20 20    JSR   $2020
0DB4-   20 20 20    JSR   $2020
0DB7-   20 20 20    JSR   $2020
0DBA-   20 20 20    JSR   $2020
0DBD-   20 20 20    JSR   $2020
0DC0-   20 20 20    JSR   $2020
0DC3-   20 20 20    JSR   $2020
0DC6-   20 20 20    JSR   $2020
0DC9-   20 20 20    JSR   $2020
0DCC-   AA          TAX
0DCD-   8D AA 20    STA   $20AA
0DD0-   C6 CF       DEC   $CF
0DD2-   D2 20       CMP   ($20)
0DD4-   D9 CF D5    CMP   $D5CF,Y
0DD7-   D2 20       CMP   ($20)
0DD9-   CF          ???
0DDA-   D7          ???
0DDB-   CE 20 D0    DEC   $D020
0DDE-   D2 CF       CMP   ($CF)
0DE0-   CA          DEX
0DE1-   C5 C3       CMP   $C3
0DE3-   D4          ???
0DE4-   D3          ???
0DE5-   AC 20 C1    LDY   $C120
0DE8-   20 D7 C1    JSR   $C1D7
0DEB-   D9 20 AA    CMP   $AA20,Y
0DEE-   8D AA 20    STA   $20AA
0DF1-   D4          ???
0DF2-   CF          ???
0DF3-   20 D7 CF    JSR   $CFD7
0DF6-   D2 CB       CMP   ($CB)
0DF8-   20 C1 D2    JSR   $D2C1
0DFB-   CF          ???
0DFC-   D5 CE       CMP   $CE,X
0DFE-   C4 20       CPY   $20
0E00-   D4          ???
0E01-   C8          INY
0E02-   C9 D3       CMP   #$D3
0E04-   20 C9 D3    JSR   $D3C9
0E07-   20 D4 CF    JSR   $CFD4
0E0A-   20 20 20    JSR   $2020
0E0D-   20 AA 8D    JSR   $8DAA
0E10-   AA          TAX
0E11-   20 D5 D3    JSR   $D3D5
0E14-   C5 20       CMP   $20
0E16-   C1 CE       CMP   ($CE,X)
0E18-   20 C5 D8    JSR   $D8C5
0E1B-   C5 C3       CMP   $C3
0E1D-   20 C6 C9    JSR   $C9C6
0E20-   CC C5 20    CPY   $20C5
0E23-   D4          ???
0E24-   CF          ???
0E25-   20 C2 CC    JSR   $CCC2
0E28-   CF          ???
0E29-   C1 C4       CMP   ($C4,X)
0E2B-   20 20 20    JSR   $2020
0E2E-   20 AA 8D    JSR   $8DAA
0E31-   AA          TAX
0E32-   20 C1 CE    JSR   $CEC1
0E35-   C4 20       CPY   $20
0E37-   C5 D8       CMP   $D8
0E39-   C5 C3       CMP   $C3
0E3B-   D5 D4       CMP   $D4,X
0E3D-   C5 20       CMP   $20
0E3F-   D4          ???
0E40-   C8          INY
0E41-   C5 20       CMP   $20
0E43-   C3          ???
0E44-   CF          ???
0E45-   C4 C5       CPY   $C5
0E47-   AE 20 20    LDX   $2020
0E4A-   20 20 20    JSR   $2020
0E4D-   20 20 20    JSR   $2020
0E50-   AA          TAX
0E51-   8D AA 20    STA   $20AA
0E54-   20 20 20    JSR   $2020
0E57-   20 20 20    JSR   $2020
0E5A-   20 20 20    JSR   $2020
0E5D-   20 20 20    JSR   $2020
0E60-   20 20 20    JSR   $2020
0E63-   20 20 20    JSR   $2020
0E66-   20 20 20    JSR   $2020
0E69-   20 20 20    JSR   $2020
0E6C-   20 20 20    JSR   $2020
0E6F-   20 20 AA    JSR   $AA20
0E72-   8D AA AA    STA   $AAAA
0E75-   AA          TAX
0E76-   AA          TAX
0E77-   AA          TAX
0E78-   AA          TAX
0E79-   AA          TAX
0E7A-   AA          TAX
0E7B-   AA          TAX
0E7C-   AA          TAX
0E7D-   AA          TAX
0E7E-   AA          TAX
0E7F-   AA          TAX
0E80-   AA          TAX
0E81-   AA          TAX
0E82-   AA          TAX
0E83-   AA          TAX
0E84-   AA          TAX
0E85-   AA          TAX
0E86-   AA          TAX
0E87-   AA          TAX
0E88-   AA          TAX
0E89-   AA          TAX
0E8A-   AA          TAX
0E8B-   AA          TAX
0E8C-   AA          TAX
0E8D-   AA          TAX
0E8E-   AA          TAX
0E8F-   AA          TAX
0E90-   AA          TAX
0E91-   AA          TAX
0E92-   AA          TAX
0E93-   8D AA AA    STA   $AAAA
0E96-   AA          TAX
0E97-   AA          TAX
0E98-   AA          TAX
0E99-   AA          TAX
0E9A-   AA          TAX
0E9B-   AA          TAX
0E9C-   AA          TAX
0E9D-   AA          TAX
0E9E-   AA          TAX
0E9F-   AA          TAX
0EA0-   AA          TAX
0EA1-   AA          TAX
0EA2-   AA          TAX
0EA3-   AA          TAX
0EA4-   AA          TAX
0EA5-   AA          TAX
0EA6-   AA          TAX
0EA7-   AA          TAX
0EA8-   AA          TAX
0EA9-   AA          TAX
0EAA-   AA          TAX
0EAB-   AA          TAX
0EAC-   AA          TAX
0EAD-   AA          TAX
0EAE-   AA          TAX
0EAF-   AA          TAX
0EB0-   AA          TAX
0EB1-   AA          TAX
0EB2-   AA          TAX
0EB3-   AA          TAX
0EB4-   8D AA 8D    STA   $8DAA
0EB7-   A0 DF       LDY   #$DF
0EB9-   D0 D2       BNE   $0E8D
0EBB-   CE D4 A0    DEC   $A0D4
0EBE-   A2 20       LDX   #$20
0EC0-   A2 AC       LDX   #$AC
0EC2-   B8          CLV
0EC3-   C4 B8       CPY   $B8
0EC5-   C4 B8       CPY   $B8
0EC7-   C4 B8       CPY   $B8
0EC9-   C4 B8       CPY   $B8
0ECB-   C4 8D       CPY   $8D
0ECD-   A0 DF       LDY   #$DF
0ECF-   D0 D2       BNE   $0EA3
0ED1-   CE D4 A0    DEC   $A0D4
0ED4-   A2 C6       LDX   #$C6
0ED6-   C9 CC       CMP   #$CC
0ED8-   C5 20       CMP   $20
0EDA-   C9 CE       CMP   #$CE
0EDC-   D0 D5       BNE   $0EB3
0EDE-   D4          ???
0EDF-   AF          ???
0EE0-   CF          ???
0EE1-   D5 D4       CMP   $D4,X
0EE3-   D0 D5       BNE   $0EBA
0EE5-   D4          ???
0EE6-   20 CD C1    JSR   $C1CD
0EE9-   C3          ???
0EEA-   D2 CF       CMP   ($CF)
0EEC-   D3          ???
0EED-   A2 AC       LDX   #$AC
0EEF-   B8          CLV
0EF0-   C4 8D       CPY   $8D
0EF2-   A0 DF       LDY   #$DF
0EF4-   D0 D2       BNE   $0EC8
0EF6-   CE D4 A0    DEC   $A0D4
0EF9-   A2 AD       LDX   #$AD
0EFB-   AD AD AD    LDA   $ADAD
0EFE-   AD AD AD    LDA   $ADAD
0F01-   AD AD AD    LDA   $ADAD
0F04-   AD AD AD    LDA   $ADAD
0F07-   AD AD AD    LDA   $ADAD
0F0A-   AD AD AD    LDA   $ADAD
0F0D-   AD AD AD    LDA   $ADAD
0F10-   AD AD A2    LDA   $A2AD
0F13-   AC B8 C4    LDY   $C4B8
0F16-   B8          CLV
0F17-   C4 8D       CPY   $8D
0F19-   A0 DF       LDY   #$DF
0F1B-   D0 D2       BNE   $0EEF
0F1D-   CE D4 A0    DEC   $A0D4
0F20-   A2 D4       LDX   #$D4
0F22-   C8          INY
0F23-   C5 20       CMP   $20
0F25-   C2          ???
0F26-   D3          ???
0F27-   C1 D6       CMP   ($D6,X)
0F29-   C5 20       CMP   $20
0F2B-   CD C1 C3    CMP   $C3C1
0F2E-   D2 CF       CMP   ($CF)
0F30-   20 D3 C1    JSR   $C1D3
0F33-   D6 C5       DEC   $C5,X
0F35-   D3          ???
0F36-   20 D4 C8    JSR   $C8D4
0F39-   C5 20       CMP   $20
0F3B-   C7          ???
0F3C-   C9 D6       CMP   #$D6
0F3E-   C5 CE       CMP   $CE
0F40-   A2 AC       LDX   #$AC
0F42-   B8          CLV
0F43-   C4 8D       CPY   $8D
0F45-   A0 DF       LDY   #$DF
0F47-   D0 D2       BNE   $0F1B
0F49-   CE D4 A0    DEC   $A0D4
0F4C-   A2 C1       LDX   #$C1
0F4E-   C4 C4       CPY   $C4
0F50-   D2 C5       CMP   ($C5)
0F52-   D3          ???
0F53-   D3          ???
0F54-   20 D2 C1    JSR   $C1D2
0F57-   CE C7 C5    DEC   $C5C7
0F5A-   20 D5 CE    JSR   $CED5
0F5D-   C4 C5       CPY   $C5
0F5F-   D2 20       CMP   ($20)
0F61-   D4          ???
0F62-   C8          INY
0F63-   C5 20       CMP   $20
0F65-   D3          ???
0F66-   D0 C5       BNE   $0F2D
0F68-   C3          ???
0F69-   C9 C6       CMP   #$C6
0F6B-   C9 C5       CMP   #$C5
0F6D-   C4 A2       CPY   $A2
0F6F-   AC B8 C4    LDY   $C4B8
0F72-   8D A0 DF    STA   $DFA0
0F75-   D0 D2       BNE   $0F49
0F77-   CE D4 A0    DEC   $A0D4
0F7A-   A2 C2       LDX   #$C2
0F7C-   C9 CE       CMP   #$CE
0F7E-   C1 D2       CMP   ($D2,X)
0F80-   D9 20 C6    CMP   $C620,Y
0F83-   C9 CC       CMP   #$CC
0F85-   C5 AE       CMP   $AE
0F87-   20 D4 C8    JSR   $C8D4
0F8A-   C5 20       CMP   $20
0F8C-   C1 D2       CMP   ($D2,X)
0F8E-   C7          ???
0F8F-   D5 CD       CMP   $CD,X
0F91-   C5 CE       CMP   $CE
0F93-   D4          ???
0F94-   20 C9 D3    JSR   $D3C9
0F97-   20 D3 C9    JSR   $C9D3
0F9A-   CD D0 CC    CMP   $CCD0
0F9D-   D9 A2 AC    CMP   $ACA2,Y
0FA0-   B8          CLV
0FA1-   C4 8D       CPY   $8D
0FA3-   A0 DF       LDY   #$DF
0FA5-   D0 D2       BNE   $0F79
0FA7-   CE D4 A0    DEC   $A0D4
0FAA-   A2 C1       LDX   #$C1
0FAC-   20 D3 D4    JSR   $D4D3
0FAF-   D2 C9       CMP   ($C9)
0FB1-   CE C7 20    DEC   $20C7
0FB4-   D4          ???
0FB5-   C8          INY
0FB6-   C1 D4       CMP   ($D4,X)
0FB8-   20 D7 CF    JSR   $CFD7
0FBB-   D5 CC       CMP   $CC,X
0FBD-   C4 20       CPY   $20
0FBF-   CD C1 D4    CMP   $D4C1
0FC2-   C3          ???
0FC3-   C8          INY
0FC4-   20 D4 C8    JSR   $C8D4
0FC7-   C5 20       CMP   $20
0FC9-   C1 D2       CMP   ($D2,X)
0FCB-   C7          ???
0FCC-   D5 CD       CMP   $CD,X
0FCE-   C5 CE       CMP   $CE
0FD0-   D4          ???
0FD1-   D3          ???
0FD2-   A2 AC       LDX   #$AC
0FD4-   B8          CLV
0FD5-   C4 8D       CPY   $8D
0FD7-   A0 DF       LDY   #$DF
0FD9-   D0 D2       BNE   $0FAD
0FDB-   CE D4 A0    DEC   $A0D4
0FDE-   A2 CF       LDX   #$CF
0FE0-   C6 20       DEC   $20
0FE2-   C1 20       CMP   ($20,X)
0FE4-   D4          ???
0FE5-   D9 D0 C9    CMP   $C9D0,Y
0FE8-   C3          ???
0FE9-   C1 CC       CMP   ($CC,X)
0FEB-   20 C2 D3    JSR   $D3C2
0FEE-   C1 D6       CMP   ($D6,X)
0FF0-   C5 20       CMP   $20
0FF2-   D3          ???
0FF3-   D4          ???
0FF4-   C1 D4       CMP   ($D4,X)
0FF6-   C5 CD       CMP   $CD
0FF8-   C5 CE       CMP   $CE
0FFA-   D4          ???
0FFB-   20 C9 CE    JSR   $CEC9
0FFE-   20 C4 CF    JSR   $CFC4
1001-   D3          ???
1002-   AE A2 AC    LDX   $ACA2
1005-   B8          CLV
1006-   C4 B8       CPY   $B8
1008-   C4 8D       CPY   $8D
100A-   A0 DF       LDY   #$DF
100C-   D0 D2       BNE   $0FE0
100E-   CE D4 A0    DEC   $A0D4
1011-   A2 C2       LDX   #$C2
1013-   D3          ???
1014-   C1 D6       CMP   ($D6,X)
1016-   C5 20       CMP   $20
1018-   A7          ???
1019-   D4          ???
101A-   C5 D3       CMP   $D3
101C-   D4          ???
101D-   AC C1 A4    LDY   $A4C1
1020-   B8          CLV
1021-   B0 B0       BCS   $0FD3
1023-   AC CC A4    LDY   $A4CC
1026-   B1 B0       LDA   ($B0),Y
1028-   B0 A7       BCS   $0FD1
102A-   20 D3 C1    JSR   $C1D3
102D-   D6 C5       DEC   $C5,X
102F-   D3          ???
1030-   20 D4 C8    JSR   $C8D4
1033-   C5 A2       CMP   $A2
1035-   AC B8 C4    LDY   $C4B8
1038-   8D A0 DF    STA   $DFA0
103B-   D0 D2       BNE   $100F
103D-   CE D4 A0    DEC   $A0D4
1040-   A2 A4       LDX   #$A4
1042-   B1 B0       LDA   ($B0),Y
1044-   B0 20       BCS   $1066
1046-   C2          ???
1047-   D9 D4 C5    CMP   $C5D4,Y
104A-   D3          ???
104B-   20 CC CF    JSR   $CFCC
104E-   C3          ???
104F-   C1 D4       CMP   ($D4,X)
1051-   C5 C4       CMP   $C4
1053-   20 C1 D4    JSR   $D4C1
1056-   20 A4 B8    JSR   $B8A4
1059-   B0 B0       BCS   $100B
105B-   20 C9 CE    JSR   $CEC9
105E-   20 D4 C8    JSR   $C8D4
1061-   C5 20       CMP   $20
1063-   C6 C9       DEC   $C9
1065-   CC C5 A2    CPY   $A2C5
1068-   AC B8 C4    LDY   $C4B8
106B-   8D A0 DF    STA   $DFA0
106E-   D0 D2       BNE   $1042
1070-   CE D4 A0    DEC   $A0D4
1073-   A2 D4       LDX   #$D4
1075-   C5 D3       CMP   $D3
1077-   D4          ???
1078-   AE A2 AC    LDX   $ACA2
107B-   B8          CLV
107C-   C4 B8       CPY   $B8
107E-   C4 8D       CPY   $8D
1080-   A0 DF       LDY   #$DF
1082-   D0 D2       BNE   $1056
1084-   CE D4 A0    DEC   $A0D4
1087-   A2 CC       LDX   #$CC
1089-   C5 D4       CMP   $D4
108B-   A7          ???
108C-   D3          ???
108D-   20 D0 D5    JSR   $D5D0
1090-   D4          ???
1091-   20 D3 CF    JSR   $CFD3
1094-   CD C5 D4    CMP   $D4C5
1097-   C8          INY
1098-   C9 CE       CMP   #$CE
109A-   C7          ???
109B-   20 C9 CE    JSR   $CEC9
109E-   D4          ???
109F-   CF          ???
10A0-   20 A4 B3    JSR   $B3A4
10A3-   B0 B0       BCS   $1055
10A5-   20 D4 CF    JSR   $CFD4
10A8-   A2 AC       LDX   #$AC
10AA-   B8          CLV
10AB-   C4 8D       CPY   $8D
10AD-   A0 DF       LDY   #$DF
10AF-   D0 D2       BNE   $1083
10B1-   CE D4 A0    DEC   $A0D4
10B4-   A2 D4       LDX   #$D4
10B6-   C5 D3       CMP   $D3
10B8-   D4          ???
10B9-   20 C9 D4    JSR   $D4C9
10BC-   20 CF D5    JSR   $D5CF
10BF-   D4          ???
10C0-   AE A2 AC    LDX   $ACA2
10C3-   B8          CLV
10C4-   C4 B8       CPY   $B8
10C6-   C4 8D       CPY   $8D
10C8-   A0 CC       LDY   #$CC
10CA-   C4 D9       CPY   $D9
10CC-   A0 A3       LDY   #$A3
10CE-   B0 8D       BCS   $105D
10D0-   CC D0 8D    CPY   $8DD0
10D3-   A0 D4       LDY   #$D4
10D5-   D9 C1 8D    CMP   $8DC1,Y
10D8-   A0 D3       LDY   #$D3
10DA-   D4          ???
10DB-   C1 A0       CMP   ($A0,X)
10DD-   A4 B8       LDY   $B8
10DF-   B0 B0       BCS   $1091
10E1-   AC D9 8D    LDY   $8DD9
10E4-   A0 C9       LDY   #$C9
10E6-   CE D9 8D    DEC   $8DD9
10E9-   A0 C3       LDY   #$C3
10EB-   D0 D9       BNE   $10C6
10ED-   A0 A3       LDY   #$A3
10EF-   A4 B1       LDY   $B1
10F1-   B0 B0       BCS   $10A3
10F3-   8D A0 C2    STA   $C2A0
10F6-   CE C5 A0    DEC   $A0C5
10F9-   CC D0 8D    CPY   $8DD0
10FC-   A0 DF       LDY   #$DF
10FE-   D7          ???
10FF-   C1 C9       CMP   ($C9,X)
1101-   D4          ???
1102-   8D A0 DF    STA   $DFA0
1105-   C4 D5       CPY   $D5
1107-   CD D0 A0    CMP   $A0D0
110A-   A4 B8       LDY   $B8
110C-   B0 B0       BCS   $10BE
110E-   BB          ???
110F-   A3          ???
1110-   A4 B1       LDY   $B1
1112-   B0 B0       BCS   $10C4
1114-   8D A0 DF    STA   $DFA0
1117-   D7          ???
1118-   C1 C9       CMP   ($C9,X)
111A-   D4          ???
111B-   8D A0 DF    STA   $DFA0
111E-   D0 D2       BNE   $10F2
1120-   CE D4 A0    DEC   $A0D4
1123-   A2 20       LDX   #$20
1125-   A2 AC       LDX   #$AC
1127-   B8          CLV
1128-   C4 B8       CPY   $B8
112A-   C4 8D       CPY   $8D
112C-   A0 DF       LDY   #$DF
112E-   D0 D2       BNE   $1102
1130-   CE D4 20    DEC   $20D4
1133-   A2 C2       LDX   #$C2
1135-   D3          ???
1136-   C1 D6       CMP   ($D6,X)
1138-   C5 20       CMP   $20
113A-   A7          ???
113B-   D4          ???
113C-   C5 D3       CMP   $D3
113E-   D4          ???
113F-   AC C1 A4    LDY   $A4C1
1142-   B8          CLV
1143-   B0 B0       BCS   $10F5
1145-   AC CC A4    LDY   $A4CC
1148-   B1 B0       LDA   ($B0),Y
114A-   B0 A7       BCS   $10F3
114C-   AE AE AE    LDX   $AEAE
114F-   AE A2 8D    LDX   $8DA2
1152-   A0 C2       LDY   #$C2
1154-   D3          ???
1155-   C1 D6       CMP   ($D6,X)
1157-   C5 20       CMP   $20
1159-   A2 D4       LDX   #$D4
115B-   C5 D3       CMP   $D3
115D-   D4          ???
115E-   AC C1 A4    LDY   $A4C1
1161-   B8          CLV
1162-   B0 B0       BCS   $1114
1164-   AC CC A4    LDY   $A4CC
1167-   B1 B0       LDA   ($B0),Y
1169-   B0 A2       BCS   $110D
116B-   8D A0 DF    STA   $DFA0
116E-   D0 D2       BNE   $1142
1170-   CE D4 A0    DEC   $A0D4
1173-   A2 C4       LDX   #$C4
1175-   CF          ???
1176-   CE C5 A1    DEC   $A1C5
1179-   A2 AC       LDX   #$AC
117B-   B8          CLV
117C-   C4 B8       CPY   $B8
117E-   C4 8D       CPY   $8D
1180-   A0 DF       LDY   #$DF
1182-   D0 D2       BNE   $1156
1184-   CE D4 A0    DEC   $A0D4
1187-   A2 CE       LDX   #$CE
1189-   CF          ???
118A-   D7          ???
118B-   20 CC C5    JSR   $C5CC
118E-   D4          ???
118F-   A7          ???
1190-   D3          ???
1191-   20 C3 CC    JSR   $CCC3
1194-   C5 C1       CMP   $C1
1196-   D2 20       CMP   ($20)
1198-   A4 B1       LDY   $B1
119A-   B0 B0       BCS   $114C
119C-   20 C2 D9    JSR   $D9C2
119F-   D4          ???
11A0-   C5 D3       CMP   $D3
11A2-   20 C1 D4    JSR   $D4C1
11A5-   A2 AC       LDX   #$AC
11A7-   B8          CLV
11A8-   C4 8D       CPY   $8D
11AA-   A0 DF       LDY   #$DF
11AC-   D0 D2       BNE   $1180
11AE-   CE D4 A0    DEC   $A0D4
11B1-   A2 A4       LDX   #$A4
11B3-   B8          CLV
11B4-   B0 B0       BCS   $1166
11B6-   20 C2 C5    JSR   $C5C2
11B9-   C6 CF       DEC   $CF
11BB-   D2 C5       CMP   ($C5)
11BD-   20 D7 C5    JSR   $C5D7
11C0-   20 D2 C5    JSR   $C5D2
11C3-   CC CF C1    CPY   $C1CF
11C6-   C4 20       CPY   $20
11C8-   C9 D4       CMP   #$D4
11CA-   20 D7 C9    JSR   $C9D7
11CD-   D4          ???
11CE-   C8          INY
11CF-   20 C2 CC    JSR   $CCC2
11D2-   CF          ???
11D3-   C1 C4       CMP   ($C4,X)
11D5-   AE A2 AC    LDX   $ACA2
11D8-   B8          CLV
11D9-   C4 B8       CPY   $B8
11DB-   C4 8D       CPY   $8D
11DD-   A0 CC       LDY   #$CC
11DF-   C4 D9       CPY   $D9
11E1-   A0 A3       LDY   #$A3
11E3-   B0 8D       BCS   $1172
11E5-   CC D0 B2    CPY   $B2D0
11E8-   8D A0 CC    STA   $CCA0
11EB-   C4 C1       CPY   $C1
11ED-   A0 A3       LDY   #$A3
11EF-   B0 8D       BCS   $117E
11F1-   A0 D3       LDY   #$D3
11F3-   D4          ???
11F4-   C1 A0       CMP   ($A0,X)
11F6-   A4 B8       LDY   $B8
11F8-   B0 B0       BCS   $11AA
11FA-   AC D9 8D    LDY   $8DD9
11FD-   A0 C9       LDY   #$C9
11FF-   CE D9 8D    DEC   $8DD9
1202-   A0 C3       LDY   #$C3
1204-   D0 D9       BNE   $11DF
1206-   A0 A3       LDY   #$A3
1208-   A4 B1       LDY   $B1
120A-   B0 B0       BCS   $11BC
120C-   8D A0 C2    STA   $C2A0
120F-   CE C5 A0    DEC   $A0C5
1212-   CC D0 B2    CPY   $B2D0
1215-   8D A0 DF    STA   $DFA0
1218-   C4 D5       CPY   $D5
121A-   CD D0 A0    CMP   $A0D0
121D-   A4 B8       LDY   $B8
121F-   B0 B0       BCS   $11D1
1221-   BB          ???
1222-   A3          ???
1223-   A4 B1       LDY   $B1
1225-   B0 B0       BCS   $11D7
1227-   8D AA 8D    STA   $8DAA
122A-   A0 DF       LDY   #$DF
122C-   D0 D2       BNE   $1200
122E-   CE D4 A0    DEC   $A0D4
1231-   A2 20       LDX   #$20
1233-   A2 AC       LDX   #$AC
1235-   B8          CLV
1236-   C4 B8       CPY   $B8
1238-   C4 8D       CPY   $8D
123A-   A0 DF       LDY   #$DF
123C-   D0 D2       BNE   $1210
123E-   CE D4 A0    DEC   $A0D4
1241-   A2 CE       LDX   #$CE
1243-   CF          ???
1244-   D7          ???
1245-   20 D7 C5    JSR   $C5D7
1248-   20 C3 C1    JSR   $C1C3
124B-   CE 20 C2    DEC   $C220
124E-   CC CF C1    CPY   $C1CF
1251-   C4 20       CPY   $20
1253-   D4          ???
1254-   C5 D3       CMP   $D3
1256-   D4          ???
1257-   20 D4 CF    JSR   $CFD4
125A-   20 C7 C5    JSR   $C5C7
125D-   D4          ???
125E-   20 A4 B8    JSR   $B8A4
1261-   B0 B0       BCS   $1213
1263-   A2 AC       LDX   #$AC
1265-   B8          CLV
1266-   C4 8D       CPY   $8D
1268-   A0 DF       LDY   #$DF
126A-   D0 D2       BNE   $123E
126C-   CE D4 A0    DEC   $A0D4
126F-   A2 C2       LDX   #$C2
1271-   C1 C3       CMP   ($C3,X)
1273-   CB          ???
1274-   20 C9 CE    JSR   $CEC9
1277-   D4          ???
1278-   CF          ???
1279-   20 D4 C8    JSR   $C8D4
127C-   C5 20       CMP   $20
127E-   D3          ???
127F-   D4          ???
1280-   C1 D4       CMP   ($D4,X)
1282-   C5 20       CMP   $20
1284-   D7          ???
1285-   C5 20       CMP   $20
1287-   D0 D5       BNE   $125E
1289-   D4          ???
128A-   20 C9 D4    JSR   $D4C9
128D-   AE A2 AC    LDX   $ACA2
1290-   B8          CLV
1291-   C4 B8       CPY   $B8
1293-   C4 8D       CPY   $8D
1295-   A0 DF       LDY   #$DF
1297-   D0 D2       BNE   $126B
1299-   CE D4 A0    DEC   $A0D4
129C-   A2 C2       LDX   #$C2
129E-   CC CF C1    CPY   $C1CF
12A1-   C4 20       CPY   $20
12A3-   A7          ???
12A4-   D4          ???
12A5-   C5 D3       CMP   $D3
12A7-   D4          ???
12A8-   A7          ???
12A9-   AE AE AE    LDX   $AEAE
12AC-   A2 AC       LDX   #$AC
12AE-   B8          CLV
12AF-   C4 8D       CPY   $8D
12B1-   A0 DF       LDY   #$DF
12B3-   D7          ???
12B4-   C1 C9       CMP   ($C9,X)
12B6-   D4          ???
12B7-   8D A0 C2    STA   $C2A0
12BA-   CC CF C1    CPY   $C1CF
12BD-   C4 A0       CPY   $A0
12BF-   A2 D4       LDX   #$D4
12C1-   C5 D3       CMP   $D3
12C3-   D4          ???
12C4-   A2 8D       LDX   #$8D
12C6-   A0 DF       LDY   #$DF
12C8-   D0 D2       BNE   $129C
12CA-   CE D4 A0    DEC   $A0D4
12CD-   A2 20       LDX   #$20
12CF-   A2 AC       LDX   #$AC
12D1-   B8          CLV
12D2-   C4 B8       CPY   $B8
12D4-   C4 8D       CPY   $8D
12D6-   A0 DF       LDY   #$DF
12D8-   D0 D2       BNE   $12AC
12DA-   CE D4 A0    DEC   $A0D4
12DD-   A2 C4       LDX   #$C4
12DF-   CF          ???
12E0-   CE C5 A1    DEC   $A1C5
12E3-   A2 AC       LDX   #$AC
12E5-   B8          CLV
12E6-   C4 B8       CPY   $B8
12E8-   C4 8D       CPY   $8D
12EA-   A0 DF       LDY   #$DF
12EC-   C4 D5       CPY   $D5
12EE-   CD D0 A0    CMP   $A0D0
12F1-   A4 B0       LDY   $B0
12F3-   B8          CLV
12F4-   B0 B0       BCS   $12A6
12F6-   BB          ???
12F7-   A3          ???
12F8-   A4 B1       LDY   $B1
12FA-   B0 B0       BCS   $12AC
12FC-   8D A0 DF    STA   $DFA0
12FF-   D0 D2       BNE   $12D3
1301-   CE D4 A0    DEC   $A0D4
1304-   A2 20       LDX   #$20
1306-   A2 AC       LDX   #$AC
1308-   B8          CLV
1309-   C4 B8       CPY   $B8
130B-   C4 8D       CPY   $8D
130D-   A0 DF       LDY   #$DF
130F-   D7          ???
1310-   C1 C9       CMP   ($C9,X)
1312-   D4          ???
1313-   8D AA 8D    STA   $8DAA
1316-   A0 DF       LDY   #$DF
1318-   D0 D2       BNE   $12EC
131A-   CE D4 A0    DEC   $A0D4
131D-   A2 D4       LDX   #$D4
131F-   C8          INY
1320-   C5 20       CMP   $20
1322-   C3          ???
1323-   CD C4 20    CMP   $20C4
1326-   CD C1 C3    CMP   $C3C1
1329-   D2 CF       CMP   ($CF)
132B-   20 D3 C9    JSR   $C9D3
132E-   CD D0 CC    CMP   $CCD0
1331-   D9 20 C5    CMP   $C520,Y
1334-   D8          CLD
1335-   C5 C3       CMP   $C3
1337-   D5 D4       CMP   $D4,X
1339-   C5 D3       CMP   $D3
133B-   20 C1 A2    JSR   $A2C1
133E-   AC B8 C4    LDY   $C4B8
1341-   8D A0 DF    STA   $DFA0
1344-   D0 D2       BNE   $1318
1346-   CE D4 A0    DEC   $A0D4
1349-   A2 C4       LDX   #$C4
134B-   CF          ???
134C-   D3          ???
134D-   20 C3 CF    JSR   $CFC3
1350-   CD CD C1    CMP   $C1CD
1353-   CE C4 AC    DEC   $ACC4
1356-   20 C1 CC    JSR   $CCC1
1359-   CF          ???
135A-   CE C7 20    DEC   $20C7
135D-   D7          ???
135E-   C9 D4       CMP   #$D4
1360-   C8          INY
1361-   20 C1 CE    JSR   $CEC1
1364-   D9 20 C1    CMP   $C120,Y
1367-   D2 C7       CMP   ($C7)
1369-   D5 CD       CMP   $CD,X
136B-   C5 CE       CMP   $CE
136D-   D4          ???
136E-   D3          ???
136F-   A2 AC       LDX   #$AC
1371-   B8          CLV
1372-   C4 8D       CPY   $8D
1374-   A0 DF       LDY   #$DF
1376-   D0 D2       BNE   $134A
1378-   CE D4 A0    DEC   $A0D4
137B-   A2 D0       LDX   #$D0
137D-   C1 D3       CMP   ($D3,X)
137F-   D3          ???
1380-   C5 C4       CMP   $C4
1382-   20 D4 CF    JSR   $CFD4
1385-   20 C9 D4    JSR   $D4C9
1388-   AE 20 C3    LDX   $C320
138B-   CD C4 20    CMP   $20C4
138E-   A7          ???
138F-   C3          ???
1390-   C1 D4       CMP   ($D4,X)
1392-   C1 CC       CMP   ($CC,X)
1394-   CF          ???
1395-   C7          ???
1396-   A7          ???
1397-   AC 20 C6    LDY   $C620
139A-   CF          ???
139B-   D2 20       CMP   ($20)
139D-   C9 CE       CMP   #$CE
139F-   D3          ???
13A0-   D4          ???
13A1-   C1 CE       CMP   ($CE,X)
13A3-   C3          ???
13A4-   C5 AC       CMP   $AC
13A6-   A2 AC       LDX   #$AC
13A8-   B8          CLV
13A9-   C4 8D       CPY   $8D
13AB-   A0 DF       LDY   #$DF
13AD-   D0 D2       BNE   $1381
13AF-   CE D4 A0    DEC   $A0D4
13B2-   A2 D2       LDX   #$D2
13B4-   C5 D4       CMP   $D4
13B6-   D5 D2       CMP   $D2,X
13B8-   CE D3 BA    DEC   $BAD3
13BB-   A2 AC       LDX   #$AC
13BD-   B8          CLV
13BE-   C4 B8       CPY   $B8
13C0-   C4 8D       CPY   $8D
13C2-   A0 DF       LDY   #$DF
13C4-   D7          ???
13C5-   C1 C9       CMP   ($C9,X)
13C7-   D4          ???
13C8-   8D A0 C3    STA   $C3A0
13CB-   CD C4 A0    CMP   $A0C4
13CE-   A2 C3       LDX   #$C3
13D0-   C1 D4       CMP   ($D4,X)
13D2-   C1 CC       CMP   ($CC,X)
13D4-   CF          ???
13D5-   C7          ???
13D6-   A2 8D       LDX   #$8D
13D8-   A0 DF       LDY   #$DF
13DA-   D7          ???
13DB-   C1 C9       CMP   ($C9,X)
13DD-   D4          ???
13DE-   8D AA 8D    STA   $8DAA
13E1-   AA          TAX
13E2-   AA          TAX
13E3-   20 C9 C6    JSR   $C6C9
13E6-   20 D7 C5    JSR   $C5D7
13E9-   20 C1 D2    JSR   $D2C1
13EC-   C5 20       CMP   $20
13EE-   D4          ???
13EF-   CF          ???
13F0-   20 D2 C5    JSR   $C5D2
13F3-   C1 C4       CMP   ($C4,X)
13F5-   20 CF D2    JSR   $D2CF
13F8-   20 D7 D2    JSR   $D2D7
13FB-   C9 D4       CMP   #$D4
13FD-   C5 20       CMP   $20
13FF-   C6 C9       DEC   $C9
1401-   CC C5 D3    CPY   $D3C5
1404-   AC 20 D7    LDY   $D720
1407-   C5 20       CMP   $20
1409-   C8          INY
140A-   C1 D6       CMP   ($D6,X)
140C-   C5 20       CMP   $20
140E-   D4          ???
140F-   CF          ???
1410-   20 C6 CF    JSR   $CFC6
1413-   CF          ???
1414-   CC 8D AA    CPY   $AA8D
1417-   AA          TAX
1418-   20 D4 C8    JSR   $C8D4
141B-   C5 20       CMP   $20
141D-   C3          ???
141E-   CF          ???
141F-   CD D0 D5    CMP   $D5D0
1422-   D4          ???
1423-   C5 D2       CMP   $D2
1425-   20 D4 CF    JSR   $CFD4
1428-   20 D4 C8    JSR   $C8D4
142B-   C9 CE       CMP   #$CE
142D-   CB          ???
142E-   20 C9 D4    JSR   $D4C9
1431-   A7          ???
1432-   D3          ???
1433-   20 C9 CE    JSR   $CEC9
1436-   20 C1 D0    JSR   $D0C1
1439-   D0 CC       BNE   $1407
143B-   C5 D3       CMP   $D3
143D-   CF          ???
143E-   C6 D4       DEC   $D4
1440-   20 CD CF    JSR   $CFCD
1443-   C4 C5       CPY   $C5
1445-   AE 20 D4    LDX   $D420
1448-   C8          INY
1449-   C9 D3       CMP   #$D3
144B-   8D AA AA    STA   $AAAA
144E-   20 C9 D3    JSR   $D3C9
1451-   20 C1 C3    JSR   $C3C1
1454-   C3          ???
1455-   CF          ???
1456-   CD D0 CC    CMP   $CCD0
1459-   C9 D3       CMP   #$D3
145B-   C8          INY
145C-   C5 C4       CMP   $C4
145E-   20 D7 C9    JSR   $C9D7
1461-   D4          ???
1462-   C8          INY
1463-   20 D4 C8    JSR   $C8D4
1466-   C5 20       CMP   $20
1468-   C1 CD       CMP   ($CD,X)
146A-   CF          ???
146B-   C4 C5       CPY   $C5
146D-   20 CD C1    JSR   $C1CD
1470-   C3          ???
1471-   D2 CF       CMP   ($CF)
1473-   AE 20 D7    LDX   $D720
1476-   C9 D4       CMP   #$D4
1478-   C8          INY
1479-   20 C2 C9    JSR   $C9C2
147C-   CE D3 C1    DEC   $C1D3
147F-   D6 C5       DEC   $C5,X
1481-   8D AA AA    STA   $AAAA
1484-   20 C1 CE    JSR   $CEC1
1487-   C4 20       CPY   $20
1489-   C2          ???
148A-   C9 CE       CMP   #$CE
148C-   CC CF C1    CPY   $C1CF
148F-   C4 AC       CPY   $AC
1491-   20 D4 C8    JSR   $C8D4
1494-   C9 D3       CMP   #$D3
1496-   20 C9 D3    JSR   $D3C9
1499-   20 C1 CC    JSR   $CCC1
149C-   D2 C5       CMP   ($C5)
149E-   C1 C4       CMP   ($C4,X)
14A0-   D9 20 C4    CMP   $C420,Y
14A3-   CF          ???
14A4-   CE C5 AC    DEC   $ACC5
14A7-   20 D3 CF    JSR   $CFD3
14AA-   20 D4 C5    JSR   $C5D4
14AD-   C3          ???
14AE-   C8          INY
14AF-   CE C9 C3    DEC   $C3C9
14B2-   C1 CC       CMP   ($CC,X)
14B4-   CC D9 8D    CPY   $8DD9
14B7-   AA          TAX
14B8-   AA          TAX
14B9-   20 D7 C5    JSR   $C5D7
14BC-   20 C4 CF    JSR   $CFC4
14BF-   CE A7 D4    DEC   $D4A7
14C2-   20 C8 C1    JSR   $C1C8
14C5-   D6 C5       DEC   $C5,X
14C7-   20 D4 CF    JSR   $CFD4
14CA-   20 C4 CF    JSR   $CFC4
14CD-   20 C9 D4    JSR   $D4C9
14D0-   20 C8 C5    JSR   $C5C8
14D3-   D2 C5       CMP   ($C5)
14D5-   AE 20 C8    LDX   $C820
14D8-   CF          ???
14D9-   D7          ???
14DA-   C5 D6       CMP   $D6
14DC-   C5 D2       CMP   $D2
14DE-   AC 20 D4    LDY   $D420
14E1-   C8          INY
14E2-   C5 20       CMP   $20
14E4-   C3          ???
14E5-   CD C4 8D    CMP   $8DC4
14E8-   AA          TAX
14E9-   AA          TAX
14EA-   20 D2 CF    JSR   $CFD2
14ED-   D5 D4       CMP   $D4,X
14EF-   C9 CE       CMP   #$CE
14F1-   C5 20       CMP   $20
14F3-   C4 CF       CPY   $CF
14F5-   C5 D3       CMP   $D3
14F7-   CE A7 D4    DEC   $D4A7
14FA-   20 D3 C5    JSR   $C5D3
14FD-   D4          ???
14FE-   20 C9 D4    JSR   $D4C9
1501-   20 D5 D0    JSR   $D0D5
1504-   20 C1 D5    JSR   $D5C1
1507-   D4          ???
1508-   CF          ???
1509-   CD C1 D4    CMP   $D4C1
150C-   C9 C3       CMP   #$C3
150E-   C1 CC       CMP   ($CC,X)
1510-   CC D9 AC    CPY   $ACD9
1513-   20 D3 CF    JSR   $CFD3
1516-   20 C2 C5    JSR   $C5C2
1519-   20 D3 D5    JSR   $D5D3
151C-   D2 C5       CMP   ($C5)
151E-   8D AA AA    STA   $AAAA
1521-   20 D4 CF    JSR   $CFD4
1524-   20 C9 CE    JSR   $CEC9
1527-   C3          ???
1528-   CC D5 C4    CPY   $C4D5
152B-   C5 20       CMP   $20
152D-   D4          ???
152E-   C8          INY
152F-   C9 D3       CMP   #$D3
1531-   20 C2 C5    JSR   $C5C2
1534-   C6 CF       DEC   $CF
1536-   D2 C5       CMP   ($C5)
1538-   20 CF D0    JSR   $D0CF
153B-   C5 CE       CMP   $CE
153D-   C9 CE       CMP   #$CE
153F-   C7          ???
1540-   20 D4 C5    JSR   $C5D4
1543-   D8          CLD
1544-   D4          ???
1545-   20 C6 C9    JSR   $C9C6
1548-   CC C5 D3    CPY   $D3C5
154B-   AE 8D AA    LDX   $AA8D
154E-   8D A0 C1    STA   $C1A0
1551-   CD CF C4    CMP   $C4CF
1554-   C5 8D       CMP   $8D
1556-   AA          TAX
1557-   8D A0 DF    STA   $DFA0
155A-   D0 D2       BNE   $152E
155C-   CE D4 A0    DEC   $A0D4
155F-   A2 20       LDX   #$20
1561-   A2 AC       LDX   #$AC
1563-   B8          CLV
1564-   C4 B8       CPY   $B8
1566-   C4 B8       CPY   $B8
1568-   C4 8D       CPY   $8D
156A-   A0 DF       LDY   #$DF
156C-   D0 D2       BNE   $1540
156E-   CE D4 A0    DEC   $A0D4
1571-   A2 D4       LDX   #$D4
1573-   D9 D0 C9    CMP   $C9D0,Y
1576-   C3          ???
1577-   C1 CC       CMP   ($CC,X)
1579-   CC D9 AC    CPY   $ACD9
157C-   20 D4 C8    JSR   $C8D4
157F-   C5 20       CMP   $20
1581-   C3          ???
1582-   CD C4 20    CMP   $20C4
1585-   CD C1 C3    CMP   $C3C1
1588-   D2 CF       CMP   ($CF)
158A-   20 C9 D3    JSR   $D3C9
158D-   20 C1 CC    JSR   $CCC1
1590-   D3          ???
1591-   CF          ???
1592-   A2 AC       LDX   #$AC
1594-   B8          CLV
1595-   C4 8D       CPY   $8D
1597-   A0 DF       LDY   #$DF
1599-   D0 D2       BNE   $156D
159B-   CE D4 A0    DEC   $A0D4
159E-   A2 D5       LDX   #$D5
15A0-   D3          ???
15A1-   C5 C4       CMP   $C4
15A3-   20 C6 CF    JSR   $CFC6
15A6-   D2 20       CMP   ($20)
15A8-   D0 D2       BNE   $157C
15AA-   C5 D0       CMP   $D0
15AC-   C1 D2       CMP   ($D2,X)
15AE-   C9 CE       CMP   #$CE
15B0-   C7          ???
15B1-   20 D4 CF    JSR   $CFD4
15B4-   20 D2 C5    JSR   $C5D2
15B7-   C1 C4       CMP   ($C4,X)
15B9-   20 CF D2    JSR   $D2CF
15BC-   20 D7 D2    JSR   $D2D7
15BF-   C9 D4       CMP   #$D4
15C1-   C5 A2       CMP   $A2
15C3-   AC B8 C4    LDY   $C4B8
15C6-   8D A0 DF    STA   $DFA0
15C9-   D0 D2       BNE   $159D
15CB-   CE D4 A0    DEC   $A0D4
15CE-   A2 D4       LDX   #$D4
15D0-   C5 D8       CMP   $D8
15D2-   D4          ???
15D3-   20 C6 C9    JSR   $C9C6
15D6-   CC C5 D3    CPY   $D3C5
15D9-   AE 20 C8    LDX   $C820
15DC-   CF          ???
15DD-   D7          ???
15DE-   C5 D6       CMP   $D6
15E0-   C5 D2       CMP   $D2
15E2-   AC 20 C2    LDY   $C220
15E5-   C5 C6       CMP   $C6
15E7-   CF          ???
15E8-   D2 C5       CMP   ($C5)
15EA-   20 D4 C8    JSR   $C8D4
15ED-   C9 D3       CMP   #$D3
15EF-   20 C3 C1    JSR   $C1C3
15F2-   CE A2 AC    DEC   $ACA2
15F5-   B8          CLV
15F6-   C4 8D       CPY   $8D
15F8-   A0 DF       LDY   #$DF
15FA-   D0 D2       BNE   $15CE
15FC-   CE D4 A0    DEC   $A0D4
15FF-   A2 C2       LDX   #$C2
1601-   C5 20       CMP   $20
1603-   C1 C3       CMP   ($C3,X)
1605-   C3          ???
1606-   CF          ???
1607-   CD D0 CC    CMP   $CCD0
160A-   C9 D3       CMP   #$D3
160C-   C8          INY
160D-   C5 C4       CMP   $C4
160F-   AC 20 D4    LDY   $D420
1612-   C8          INY
1613-   C5 20       CMP   $20
1615-   D4          ???
1616-   CD CF C4    CMP   $C4CF
1619-   C5 20       CMP   $20
161B-   CD C1 C3    CMP   $C3C1
161E-   D2 CF       CMP   ($CF)
1620-   A2 AC       LDX   #$AC
1622-   B8          CLV
1623-   C4 8D       CPY   $8D
1625-   A0 DF       LDY   #$DF
1627-   D0 D2       BNE   $15FB
1629-   CE D4 A0    DEC   $A0D4
162C-   A2 CD       LDX   #$CD
162E-   D5 D3       CMP   $D3,X
1630-   D4          ???
1631-   20 C2 C5    JSR   $C5C2
1634-   20 D2 D5    JSR   $D5D2
1637-   CE 20 D4    DEC   $D420
163A-   CF          ???
163B-   20 D4 D2    JSR   $D2D4
163E-   C9 C3       CMP   #$C3
1640-   CB          ???
1641-   20 C1 D0    JSR   $D0C1
1644-   D0 CC       BNE   $1612
1646-   C5 D3       CMP   $D3
1648-   CF          ???
1649-   C6 D4       DEC   $D4
164B-   20 C9 CE    JSR   $CEC9
164E-   D4          ???
164F-   CF          ???
1650-   A2 AC       LDX   #$AC
1652-   B8          CLV
1653-   C4 8D       CPY   $8D
1655-   A0 DF       LDY   #$DF
1657-   D0 D2       BNE   $162B
1659-   CE D4 A0    DEC   $A0D4
165C-   A2 C2       LDX   #$C2
165E-   C5 CC       CMP   $CC
1660-   C9 C5       CMP   #$C5
1662-   D6 C9       DEC   $C9,X
1664-   CE C7 20    DEC   $20C7
1667-   C9 D4       CMP   #$D4
1669-   20 C9 D3    JSR   $D3C9
166C-   CE A7 D4    DEC   $D4A7
166F-   20 C9 CE    JSR   $CEC9
1672-   20 C9 CD    JSR   $CDC9
1675-   CD C5 C4    CMP   $C4C5
1678-   C9 C1       CMP   #$C1
167A-   D4          ???
167B-   C5 20       CMP   $20
167D-   CD CF C4    CMP   $C4CF
1680-   C5 AE       CMP   $AE
1682-   A2 AC       LDX   #$AC
1684-   B8          CLV
1685-   C4 B8       CPY   $B8
1687-   C4 8D       CPY   $8D
1689-   A0 DF       LDY   #$DF
168B-   D0 D2       BNE   $165F
168D-   CE D4 A0    DEC   $A0D4
1690-   A2 D4       LDX   #$D4
1692-   CD CF C4    CMP   $C4CF
1695-   C5 20       CMP   $20
1697-   C8          INY
1698-   C1 D3       CMP   ($D3,X)
169A-   20 CE CF    JSR   $CFCE
169D-   20 C1 D2    JSR   $D2C1
16A0-   C7          ???
16A1-   D5 CD       CMP   $CD,X
16A3-   C5 CE       CMP   $CE
16A5-   D4          ???
16A6-   D3          ???
16A7-   AE 20 D4    LDX   $D420
16AA-   C8          INY
16AB-   D5 D3       CMP   $D3,X
16AD-   AC 20 D4    LDY   $D420
16B0-   C8          INY
16B1-   C5 A2       CMP   $A2
16B3-   AC B8 C4    LDY   $C4B8
16B6-   8D A0 DF    STA   $DFA0
16B9-   D0 D2       BNE   $168D
16BB-   CE D4 A0    DEC   $A0D4
16BE-   A2 C6       LDX   #$C6
16C0-   CF          ???
16C1-   CC CC CF    CPY   $CFCC
16C4-   D7          ???
16C5-   C9 CE       CMP   #$CE
16C7-   C7          ???
16C8-   20 D0 D2    JSR   $D2D0
16CB-   C5 D0       CMP   $D0
16CD-   C1 D2       CMP   ($D2,X)
16CF-   C5 D3       CMP   $D3
16D1-   20 D5 D3    JSR   $D3D5
16D4-   20 D4 CF    JSR   $CFD4
16D7-   20 CF D0    JSR   $D0CF
16DA-   C5 CE       CMP   $CE
16DC-   20 C1 20    JSR   $20C1
16DF-   D4          ???
16E0-   C5 D8       CMP   $D8
16E2-   D4          ???
16E3-   A2 AC       LDX   #$AC
16E5-   B8          CLV
16E6-   C4 8D       CPY   $8D
16E8-   A0 DF       LDY   #$DF
16EA-   D0 D2       BNE   $16BE
16EC-   CE D4 A0    DEC   $A0D4
16EF-   A2 C6       LDX   #$C6
16F1-   C9 CC       CMP   #$CC
16F3-   C5 20       CMP   $20
16F5-   D4          ???
16F6-   CF          ???
16F7-   20 C2 C5    JSR   $C5C2
16FA-   20 D7 D2    JSR   $D2D7
16FD-   C9 D4       CMP   #$D4
16FF-   D4          ???
1700-   C5 CE       CMP   $CE
1702-   20 D4 CF    JSR   $CFD4
1705-   BA          TSX
1706-   A2 AC       LDX   #$AC
1708-   B8          CLV
1709-   C4 B8       CPY   $B8
170B-   C4 8D       CPY   $8D
170D-   A0 DF       LDY   #$DF
170F-   D0 D2       BNE   $16E3
1711-   CE D4 A0    DEC   $A0D4
1714-   A2 D4       LDX   #$D4
1716-   CD C4 CF    CMP   $CFC4
1719-   C5 A2       CMP   $A2
171B-   AC B8 C4    LDY   $C4B8
171E-   8D A0 DF    STA   $DFA0
1721-   D0 D2       BNE   $16F5
1723-   CE D4 A0    DEC   $A0D4
1726-   A2 C3       LDX   #$C3
1728-   CD C4 20    CMP   $20C4
172B-   A7          ???
172C-   CF          ???
172D-   D0 C5       BNE   $16F4
172F-   CE 20 D4    DEC   $D420
1732-   AE D4 C5    LDX   $C5D4
1735-   D8          CLD
1736-   D4          ???
1737-   C6 C9       DEC   $C9
1739-   CC C5 A7    CPY   $A7C5
173C-   A2 AC       LDX   #$AC
173E-   B8          CLV
173F-   C4 8D       CPY   $8D
1741-   A0 DF       LDY   #$DF
1743-   D0 D2       BNE   $1717
1745-   CE D4 A0    DEC   $A0D4
1748-   A2 C3       LDX   #$C3
174A-   CD C4 20    CMP   $20C4
174D-   A7          ???
174E-   D7          ???
174F-   D2 C9       CMP   ($C9)
1751-   D4          ???
1752-   C5 20       CMP   $20
1754-   D4          ???
1755-   AE D4 C5    LDX   $C5D4
1758-   D8          CLD
1759-   D4          ???
175A-   C6 C9       DEC   $C9
175C-   CC C5 A7    CPY   $A7C5
175F-   A2 AC       LDX   #$AC
1761-   B8          CLV
1762-   C4 B8       CPY   $B8
1764-   C4 8D       CPY   $8D
1766-   A0 DF       LDY   #$DF
1768-   D7          ???
1769-   C1 C9       CMP   ($C9,X)
176B-   D4          ???
176C-   8D AA 8D    STA   $8DAA
176F-   A0 DF       LDY   #$DF
1771-   D0 D2       BNE   $1745
1773-   CE D4 A0    DEC   $A0D4
1776-   A2 D7       LDX   #$D7
1778-   C5 20       CMP   $20
177A-   C3          ???
177B-   C1 CE       CMP   ($CE,X)
177D-   20 CE CF    JSR   $CFCE
1780-   D7          ???
1781-   20 D0 D2    JSR   $D2D0
1784-   C9 CE       CMP   #$CE
1786-   D4          ???
1787-   20 D4 CF    JSR   $CFD4
178A-   20 D4 C8    JSR   $C8D4
178D-   C9 D3       CMP   #$D3
178F-   20 C6 C9    JSR   $C9C6
1792-   CC C5 20    CPY   $20C5
1795-   D7          ???
1796-   C9 D4       CMP   #$D4
1798-   C8          INY
1799-   A2 AC       LDX   #$AC
179B-   B8          CLV
179C-   C4 8D       CPY   $8D
179E-   A0 DF       LDY   #$DF
17A0-   D0 D2       BNE   $1774
17A2-   CE D4 A0    DEC   $A0D4
17A5-   A2 D4       LDX   #$D4
17A7-   C8          INY
17A8-   C5 20       CMP   $20
17AA-   C6 D0       DEC   $D0
17AC-   D2 CE       CMP   ($CE)
17AE-   20 CD C1    JSR   $C1CD
17B1-   C3          ???
17B2-   D2 CF       CMP   ($CF)
17B4-   AE 20 D4    LDX   $D420
17B7-   C8          INY
17B8-   C9 D3       CMP   #$D3
17BA-   20 CD C1    JSR   $C1CD
17BD-   C3          ???
17BE-   D2 CF       CMP   ($CF)
17C0-   20 C5 C9    JSR   $C9C5
17C3-   D4          ???
17C4-   C8          INY
17C5-   C5 D2       CMP   $D2
17C7-   A2 AC       LDX   #$AC
17C9-   B8          CLV
17CA-   C4 8D       CPY   $8D
17CC-   A0 DF       LDY   #$DF
17CE-   D0 D2       BNE   $17A2
17D0-   CE D4 A0    DEC   $A0D4
17D3-   A2 D0       LDX   #$D0
17D5-   D2 C9       CMP   ($C9)
17D7-   CE D4 D3    DEC   $D3D4
17DA-   20 C1 20    JSR   $20C1
17DD-   C7          ???
17DE-   C9 D6       CMP   #$D6
17E0-   C5 CE       CMP   $CE
17E2-   20 CC C9    JSR   $C9CC
17E5-   CE C5 20    DEC   $20C5
17E8-   CF          ???
17E9-   C6 20       DEC   $20
17EB-   D4          ???
17EC-   C5 D8       CMP   $D8
17EE-   D4          ???
17EF-   20 D4 CF    JSR   $CFD4
17F2-   20 D4 C8    JSR   $C8D4
17F5-   C5 20       CMP   $20
17F7-   C6 C9       DEC   $C9
17F9-   CC C5 AC    CPY   $ACC5
17FC-   A2 AC       LDX   #$AC
17FE-   B8          CLV
17FF-   C4 8D       CPY   $8D
1801-   A0 DF       LDY   #$DF
1803-   D0 D2       BNE   $17D7
1805-   CE D4 A0    DEC   $A0D4
1808-   A2 C6       LDX   #$C6
180A-   CF          ???
180B-   CC CC CF    CPY   $CFCC
180E-   D7          ???
180F-   C5 C4       CMP   $C4
1811-   20 C2 D9    JSR   $D9C2
1814-   20 C1 20    JSR   $20C1
1817-   D2 C5       CMP   ($C5)
1819-   D4          ???
181A-   D5 D2       CMP   $D2,X
181C-   CE 20 A8    DEC   $A820
181F-   A4 B8       LDY   $B8
1821-   C4 A9       CPY   $A9
1823-   AC 20 CF    LDY   $CF20
1826-   D2 20       CMP   ($20)
1828-   D0 D2       BNE   $17FC
182A-   C9 CE       CMP   #$CE
182C-   D4          ???
182D-   D3          ???
182E-   A2 AC       LDX   #$AC
1830-   B8          CLV
1831-   C4 8D       CPY   $8D
1833-   A0 DF       LDY   #$DF
1835-   D0 D2       BNE   $1809
1837-   CE D4 A0    DEC   $A0D4
183A-   A2 D4       LDX   #$D4
183C-   C8          INY
183D-   C5 20       CMP   $20
183F-   C3          ???
1840-   C8          INY
1841-   C1 D2       CMP   ($D2,X)
1843-   C1 C3       CMP   ($C3,X)
1845-   D4          ???
1846-   C5 D2       CMP   $D2
1848-   D3          ???
1849-   20 C9 CE    JSR   $CEC9
184C-   20 C1 20    JSR   $20C1
184F-   D3          ???
1850-   D4          ???
1851-   D2 C9       CMP   ($C9)
1853-   CE C7 20    DEC   $20C7
1856-   C1 D4       CMP   ($D4,X)
1858-   20 C1 20    JSR   $20C1
185B-   C7          ???
185C-   C9 D6       CMP   #$D6
185E-   C5 CE       CMP   $CE
1860-   A2 AC       LDX   #$AC
1862-   B8          CLV
1863-   C4 8D       CPY   $8D
1865-   A0 DF       LDY   #$DF
1867-   D0 D2       BNE   $183B
1869-   CE D4 A0    DEC   $A0D4
186C-   A2 C1       LDX   #$C1
186E-   C4 C4       CPY   $C4
1870-   D2 C5       CMP   ($C5)
1872-   D3          ???
1873-   D3          ???
1874-   AE 20 C9    LDX   $C920
1877-   CE 20 D4    DEC   $D420
187A-   C8          INY
187B-   C5 20       CMP   $20
187D-   CC C1 D4    CPY   $D4C1
1880-   D4          ???
1881-   C5 D2       CMP   $D2
1883-   20 C3 C1    JSR   $C1C3
1886-   D3          ???
1887-   C5 AC       CMP   $AC
1889-   20 D4 C8    JSR   $C8D4
188C-   C5 20       CMP   $20
188E-   CC C5 CE    CPY   $CEC5
1891-   C7          ???
1892-   D4          ???
1893-   C8          INY
1894-   A2 AC       LDX   #$AC
1896-   B8          CLV
1897-   C4 8D       CPY   $8D
1899-   A0 DF       LDY   #$DF
189B-   D0 D2       BNE   $186F
189D-   CE D4 A0    DEC   $A0D4
18A0-   A2 CF       LDX   #$CF
18A2-   C6 20       DEC   $20
18A4-   D4          ???
18A5-   C8          INY
18A6-   C5 20       CMP   $20
18A8-   D3          ???
18A9-   D4          ???
18AA-   D2 C9       CMP   ($C9)
18AC-   CE C7 20    DEC   $20C7
18AF-   C9 D3       CMP   #$D3
18B1-   20 CE CF    JSR   $CFCE
18B4-   D4          ???
18B5-   20 D0 D2    JSR   $D2D0
18B8-   C5 D3       CMP   $D3
18BA-   C5 D2       CMP   $D2
18BC-   D6 C5       DEC   $C5,X
18BE-   C4 BB       CPY   $BB
18C0-   20 CF CE    JSR   $CECF
18C3-   CC D9 A2    CPY   $A2D9
18C6-   AC B8 C4    LDY   $C4B8
18C9-   8D A0 DF    STA   $DFA0
18CC-   D0 D2       BNE   $18A0
18CE-   CE D4 A0    DEC   $A0D4
18D1-   A2 D4       LDX   #$D4
18D3-   C8          INY
18D4-   C5 20       CMP   $20
18D6-   C1 D3       CMP   ($D3,X)
18D8-   C3          ???
18D9-   C9 C9       CMP   #$C9
18DB-   20 C9 D3    JSR   $D3C9
18DE-   AE A2 AC    LDX   $ACA2
18E1-   B8          CLV
18E2-   C4 B8       CPY   $B8
18E4-   C4 8D       CPY   $8D
18E6-   A0 DF       LDY   #$DF
18E8-   D0 D2       BNE   $18BC
18EA-   CE D4 A0    DEC   $A0D4
18ED-   A2 C6       LDX   #$C6
18EF-   D0 D2       BNE   $18C3
18F1-   CE 20 A7    DEC   $A720
18F4-   C1 CC       CMP   ($CC,X)
18F6-   CC 20 C9    CPY   $C920
18F9-   D3          ???
18FA-   20 D7 C5    JSR   $C5D7
18FD-   CC CC 20    CPY   $20CC
1900-   D4          ???
1901-   C8          INY
1902-   C1 D4       CMP   ($D4,X)
1904-   20 C5 CE    JSR   $CEC5
1907-   C4 D3       CPY   $D3
1909-   20 D7 C5    JSR   $C5D7
190C-   CC CC AE    CPY   $AECC
190F-   A7          ???
1910-   A2 AC       LDX   #$AC
1912-   B8          CLV
1913-   C4 8D       CPY   $8D
1915-   A0 DF       LDY   #$DF
1917-   D0 D2       BNE   $18EB
1919-   CE D4 A0    DEC   $A0D4
191C-   A2 C6       LDX   #$C6
191E-   D0 D2       BNE   $18F2
1920-   CE 20 D2    DEC   $D220
1923-   C5 D4       CMP   $D4
1925-   CF          ???
1926-   D2 D4       CMP   ($D4)
1928-   A2 AC       LDX   #$AC
192A-   B8          CLV
192B-   C4 B8       CPY   $B8
192D-   C4 8D       CPY   $8D
192F-   A0 C3       LDY   #$C3
1931-   CD C4 A0    CMP   $A0C4
1934-   A2 CF       LDX   #$CF
1936-   D0 C5       BNE   $18FD
1938-   CE 20 D4    DEC   $D420
193B-   AE D4 C5    LDX   $C5D4
193E-   D8          CLD
193F-   D4          ???
1940-   C6 C9       DEC   $C9
1942-   CC C5 A2    CPY   $A2C5
1945-   8D A0 C3    STA   $C3A0
1948-   CD C4 A0    CMP   $A0C4
194B-   A2 D7       LDX   #$D7
194D-   D2 C9       CMP   ($C9)
194F-   D4          ???
1950-   C5 20       CMP   $20
1952-   D4          ???
1953-   AE D4 C5    LDX   $C5D4
1956-   D8          CLD
1957-   D4          ???
1958-   C6 C9       DEC   $C9
195A-   CC C5 A2    CPY   $A2C5
195D-   8D A0 C6    STA   $C6A0
1960-   D0 D2       BNE   $1934
1962-   CE A0 A2    DEC   $A2A0
1965-   C1 CC       CMP   ($CC,X)
1967-   CC 20 C9    CPY   $C920
196A-   D3          ???
196B-   20 D7 C5    JSR   $C5D7
196E-   CC CC 20    CPY   $20CC
1971-   D4          ???
1972-   C8          INY
1973-   C1 D4       CMP   ($D4,X)
1975-   20 C5 CE    JSR   $CEC5
1978-   C4 D3       CPY   $D3
197A-   20 D7 C5    JSR   $C5D7
197D-   CC CC AE    CPY   $AECC
1980-   A2 8D       LDX   #$8D
1982-   A0 C6       LDY   #$C6
1984-   D0 D2       BNE   $1958
1986-   CE A0 D2    DEC   $D2A0
1989-   C5 D4       CMP   $D4
198B-   CF          ???
198C-   D2 D4       CMP   ($D4)
198E-   8D A0 C3    STA   $C3A0
1991-   CD C4 A0    CMP   $A0C4
1994-   A2 C3       LDX   #$C3
1996-   CC CF D3    CPY   $D3CF
1999-   C5 20       CMP   $20
199B-   D4          ???
199C-   AE D4 C5    LDX   $C5D4
199F-   D8          CLD
19A0-   D4          ???
19A1-   C6 C9       DEC   $C9
19A3-   CC C5 A2    CPY   $A2C5
19A6-   8D A0 DF    STA   $DFA0
19A9-   D0 D2       BNE   $197D
19AB-   CE D4 A0    DEC   $A0D4
19AE-   A2 20       LDX   #$20
19B0-   A2 AC       LDX   #$AC
19B2-   B8          CLV
19B3-   C4 B8       CPY   $B8
19B5-   C4 B8       CPY   $B8
19B7-   C4 8D       CPY   $8D
19B9-   A0 DF       LDY   #$DF
19BB-   D0 D2       BNE   $198F
19BD-   CE D4 A0    DEC   $A0D4
19C0-   A2 D0       LDX   #$D0
19C2-   D5 D4       CMP   $D4,X
19C4-   D3          ???
19C5-   20 D4 C8    JSR   $C8D4
19C8-   C5 20       CMP   $20
19CA-   CC C9 D4    CPY   $D4C9
19CD-   C5 D2       CMP   $D2
19CF-   C1 CC       CMP   ($CC,X)
19D1-   20 D0 C8    JSR   $C8D0
19D4-   D2 C1       CMP   ($C1)
19D6-   D3          ???
19D7-   C5 20       CMP   $20
19D9-   C1 CE       CMP   ($CE,X)
19DB-   C4 20       CPY   $20
19DD-   C1 20       CMP   ($20,X)
19DF-   D0 C8       BNE   $19A9
19E1-   D2 C1       CMP   ($C1)
19E3-   D3          ???
19E4-   C5 A2       CMP   $A2
19E6-   AC B8 C4    LDY   $C4B8
19E9-   8D A0 DF    STA   $DFA0
19EC-   D0 D2       BNE   $19C0
19EE-   CE D4 A0    DEC   $A0D4
19F1-   A2 D3       LDX   #$D3
19F3-   D4          ???
19F4-   CF          ???
19F5-   D2 C5       CMP   ($C5)
19F7-   C4 20       CPY   $20
19F9-   C9 CE       CMP   #$CE
19FB-   20 D4 C8    JSR   $C8D4
19FE-   C5 20       CMP   $20
1A00-   D2 C5       CMP   ($C5)
1A02-   D4          ???
1A03-   CF          ???
1A04-   D2 D4       CMP   ($D4)
1A06-   20 C1 C4    JSR   $C4C1
1A09-   C4 D2       CPY   $D2
1A0B-   C5 D3       CMP   $D3
1A0D-   D3          ???
1A0E-   20 C9 CE    JSR   $CEC9
1A11-   D4          ???
1A12-   CF          ???
1A13-   A2 AC       LDX   #$AC
1A15-   B8          CLV
1A16-   C4 8D       CPY   $8D
1A18-   A0 DF       LDY   #$DF
1A1A-   D0 D2       BNE   $19EE
1A1C-   CE D4 A0    DEC   $A0D4
1A1F-   A2 D4       LDX   #$D4
1A21-   C8          INY
1A22-   C5 20       CMP   $20
1A24-   C6 C9       DEC   $C9
1A26-   CC C5 AE    CPY   $AEC5
1A29-   A2 AC       LDX   #$AC
1A2B-   B8          CLV
1A2C-   C4 8D       CPY   $8D
1A2E-   A0 DF       LDY   #$DF
1A30-   D7          ???
1A31-   C1 C9       CMP   ($C9,X)
1A33-   D4          ???
1A34-   8D A0 DF    STA   $DFA0
1A37-   D0 D2       BNE   $1A0B
1A39-   CE D4 A0    DEC   $A0D4
1A3C-   A2 20       LDX   #$20
1A3E-   A2 AC       LDX   #$AC
1A40-   B8          CLV
1A41-   C4 B8       CPY   $B8
1A43-   C4 B8       CPY   $B8
1A45-   C4 8D       CPY   $8D
1A47-   A0 DF       LDY   #$DF
1A49-   D0 D2       BNE   $1A1D
1A4B-   CE D4 A0    DEC   $A0D4
1A4E-   A2 D4       LDX   #$D4
1A50-   C8          INY
1A51-   C5 CE       CMP   $CE
1A53-   AC 20 CC    LDY   $CC20
1A56-   C9 CB       CMP   #$CB
1A58-   C5 20       CMP   $20
1A5A-   C1 CC       CMP   ($CC,X)
1A5C-   D7          ???
1A5D-   C1 D9       CMP   ($D9,X)
1A5F-   D3          ???
1A60-   AC 20 D7    LDY   $D720
1A63-   C5 20       CMP   $20
1A65-   CD D5 D3    CMP   $D3D5
1A68-   D4          ???
1A69-   20 C3 CC    JSR   $CCC3
1A6C-   CF          ???
1A6D-   D3          ???
1A6E-   C5 A2       CMP   $A2
1A70-   AC B8 C4    LDY   $C4B8
1A73-   8D A0 DF    STA   $DFA0
1A76-   D0 D2       BNE   $1A4A
1A78-   CE D4 A0    DEC   $A0D4
1A7B-   A2 D4       LDX   #$D4
1A7D-   C8          INY
1A7E-   C5 20       CMP   $20
1A80-   C6 C9       DEC   $C9
1A82-   CC C5 20    CPY   $20C5
1A85-   D6 C9       DEC   $C9,X
1A87-   C1 20       CMP   ($20,X)
1A89-   C3          ???
1A8A-   CD C4 BA    CMP   $BAC4
1A8D-   A2 AC       LDX   #$AC
1A8F-   B8          CLV
1A90-   C4 B8       CPY   $B8
1A92-   C4 8D       CPY   $8D
1A94-   A0 DF       LDY   #$DF
1A96-   D0 D2       BNE   $1A6A
1A98-   CE D4 A0    DEC   $A0D4
1A9B-   A2 C3       LDX   #$C3
1A9D-   CD C4 20    CMP   $20C4
1AA0-   A7          ???
1AA1-   C3          ???
1AA2-   CC CF D3    CPY   $D3CF
1AA5-   C5 20       CMP   $20
1AA7-   D4          ???
1AA8-   AE D4 C5    LDX   $C5D4
1AAB-   D8          CLD
1AAC-   D4          ???
1AAD-   C6 C9       DEC   $C9
1AAF-   CC C5 A7    CPY   $A7C5
1AB2-   A2 AC       LDX   #$AC
1AB4-   B8          CLV
1AB5-   C4 B8       CPY   $B8
1AB7-   C4 B8       CPY   $B8
1AB9-   C4 8D       CPY   $8D
1ABB-   A0 DF       LDY   #$DF
1ABD-   D7          ???
1ABE-   C1 C9       CMP   ($C9,X)
1AC0-   D4          ???
1AC1-   8D A0 DF    STA   $DFA0
1AC4-   D0 D2       BNE   $1A98
1AC6-   CE D4 A0    DEC   $A0D4
1AC9-   A2 C6       LDX   #$C6
1ACB-   C9 CE       CMP   #$CE
1ACD-   C1 CC       CMP   ($CC,X)
1ACF-   CC D9 AC    CPY   $ACD9
1AD2-   20 D4 CF    JSR   $CFD4
1AD5-   20 D2 C5    JSR   $C5D2
1AD8-   C1 C4       CMP   ($C4,X)
1ADA-   20 D4 C8    JSR   $C8D4
1ADD-   C9 D3       CMP   #$D3
1ADF-   20 D4 C5    JSR   $C5D4
1AE2-   D8          CLD
1AE3-   D4          ???
1AE4-   20 C6 C9    JSR   $C9C6
1AE7-   CC C5 A2    CPY   $A2C5
1AEA-   AC B8 C4    LDY   $C4B8
1AED-   8D A0 DF    STA   $DFA0
1AF0-   D0 D2       BNE   $1AC4
1AF2-   CE D4 A0    DEC   $A0D4
1AF5-   A2 D7       LDX   #$D7
1AF7-   C5 20       CMP   $20
1AF9-   D3          ???
1AFA-   C9 CD       CMP   #$CD
1AFC-   D0 CC       BNE   $1ACA
1AFE-   D9 20 CE    CMP   $CE20,Y
1B01-   C5 C5       CMP   $C5
1B03-   C4 20       CPY   $20
1B05-   D4          ???
1B06-   CF          ???
1B07-   20 CF D0    JSR   $D0CF
1B0A-   C5 CE       CMP   $CE
1B0C-   20 D4 C8    JSR   $C8D4
1B0F-   C5 A2       CMP   $A2
1B11-   AC B8 C4    LDY   $C4B8
1B14-   8D A0 DF    STA   $DFA0
1B17-   D0 D2       BNE   $1AEB
1B19-   CE D4 A0    DEC   $A0D4
1B1C-   A2 C6       LDX   #$C6
1B1E-   C9 CC       CMP   #$CC
1B20-   C5 20       CMP   $20
1B22-   C6 CF       DEC   $CF
1B24-   D2 20       CMP   ($20)
1B26-   D2 C5       CMP   ($C5)
1B28-   C1 C4       CMP   ($C4,X)
1B2A-   C9 CE       CMP   #$CE
1B2C-   C7          ???
1B2D-   20 D6 C9    JSR   $C9D6
1B30-   C1 20       CMP   ($20,X)
1B32-   D4          ???
1B33-   C8          INY
1B34-   C5 20       CMP   $20
1B36-   C3          ???
1B37-   CD C4 20    CMP   $20C4
1B3A-   CD C1 C3    CMP   $C3C1
1B3D-   D2 CF       CMP   ($CF)
1B3F-   AC A2 AC    LDY   $ACA2
1B42-   B8          CLV
1B43-   C4 8D       CPY   $8D
1B45-   A0 DF       LDY   #$DF
1B47-   D0 D2       BNE   $1B1B
1B49-   CE D4 A0    DEC   $A0D4
1B4C-   A2 D4       LDX   #$D4
1B4E-   C8          INY
1B4F-   C5 CE       CMP   $CE
1B51-   20 D5 D3    JSR   $D3D5
1B54-   C5 20       CMP   $20
1B56-   D4          ???
1B57-   C8          INY
1B58-   C5 20       CMP   $20
1B5A-   C6 C9       DEC   $C9
1B5C-   CE D0 20    DEC   $20D0
1B5F-   CD C1 C3    CMP   $C3C1
1B62-   D2 CF       CMP   ($CF)
1B64-   20 D4 CF    JSR   $CFD4
1B67-   20 D2 C5    JSR   $C5D2
1B6A-   C1 C4       CMP   ($C4,X)
1B6C-   20 C1 20    JSR   $20C1
1B6F-   A2 AC       LDX   #$AC
1B71-   B8          CLV
1B72-   C4 8D       CPY   $8D
1B74-   A0 DF       LDY   #$DF
1B76-   D0 D2       BNE   $1B4A
1B78-   CE D4 A0    DEC   $A0D4
1B7B-   A2 CC       LDX   #$CC
1B7D-   C9 CE       CMP   #$CE
1B7F-   C5 20       CMP   $20
1B81-   CF          ???
1B82-   C6 20       DEC   $20
1B84-   D4          ???
1B85-   C5 D8       CMP   $D8
1B87-   D4          ???
1B88-   20 C1 CE    JSR   $CEC1
1B8B-   C4 20       CPY   $20
1B8D-   D3          ???
1B8E-   D4          ???
1B8F-   CF          ???
1B90-   D2 C5       CMP   ($C5)
1B92-   20 C9 D4    JSR   $D4C9
1B95-   20 C9 CE    JSR   $CEC9
1B98-   A2 AC       LDX   #$AC
1B9A-   B8          CLV
1B9B-   C4 8D       CPY   $8D
1B9D-   A0 DF       LDY   #$DF
1B9F-   D0 D2       BNE   $1B73
1BA1-   CE D4 A0    DEC   $A0D4
1BA4-   A2 CD       LDX   #$CD
1BA6-   C5 CD       CMP   $CD
1BA8-   CF          ???
1BA9-   D2 D9       CMP   ($D9)
1BAB-   BA          TSX
1BAC-   A2 AC       LDX   #$AC
1BAE-   B8          CLV
1BAF-   C4 B8       CPY   $B8
1BB1-   C4 8D       CPY   $8D
1BB3-   A0 DF       LDY   #$DF
1BB5-   D0 D2       BNE   $1B89
1BB7-   CE D4 A0    DEC   $A0D4
1BBA-   A2 C3       LDX   #$C3
1BBC-   CD C4 20    CMP   $20C4
1BBF-   A7          ???
1BC0-   CF          ???
1BC1-   D0 C5       BNE   $1B88
1BC3-   CE 20 D4    DEC   $D420
1BC6-   AE D4 C5    LDX   $C5D4
1BC9-   D8          CLD
1BCA-   D4          ???
1BCB-   C6 C9       DEC   $C9
1BCD-   CC C5 A7    CPY   $A7C5
1BD0-   A2 AC       LDX   #$AC
1BD2-   B8          CLV
1BD3-   C4 8D       CPY   $8D
1BD5-   A0 DF       LDY   #$DF
1BD7-   D0 D2       BNE   $1BAB
1BD9-   CE D4 A0    DEC   $A0D4
1BDC-   A2 C3       LDX   #$C3
1BDE-   CD C4 20    CMP   $20C4
1BE1-   A7          ???
1BE2-   D2 C5       CMP   ($C5)
1BE4-   C1 C4       CMP   ($C4,X)
1BE6-   20 D4 AE    JSR   $AED4
1BE9-   D4          ???
1BEA-   C5 D8       CMP   $D8
1BEC-   D4          ???
1BED-   C6 C9       DEC   $C9
1BEF-   CC C5 A7    CPY   $A7C5
1BF2-   A2 AC       LDX   #$AC
1BF4-   B8          CLV
1BF5-   C4 8D       CPY   $8D
1BF7-   A0 DF       LDY   #$DF
1BF9-   D0 D2       BNE   $1BCD
1BFB-   CE D4 A0    DEC   $A0D4
1BFE-   A2 C6       LDX   #$C6
1C00-   C9 CE       CMP   #$CE
1C02-   D0 20       BNE   $1C24
1C04-   D2 C5       CMP   ($C5)
1C06-   D4          ???
1C07-   D5 D2       CMP   $D2,X
1C09-   CE A2 AC    DEC   $ACA2
1C0C-   B8          CLV
1C0D-   C4 8D       CPY   $8D
1C0F-   A0 DF       LDY   #$DF
1C11-   D0 D2       BNE   $1BE5
1C13-   CE D4 A0    DEC   $A0D4
1C16-   A2 C6       LDX   #$C6
1C18-   C9 CE       CMP   #$CE
1C1A-   D0 20       BNE   $1C3C
1C1C-   D0 C1       BNE   $1BDF
1C1E-   D2 C1       CMP   ($C1)
1C20-   CD A2 AC    CMP   $ACA2
1C23-   B8          CLV
1C24-   C4 8D       CPY   $8D
1C26-   A0 DF       LDY   #$DF
1C28-   D0 D2       BNE   $1BFC
1C2A-   CE D4 A0    DEC   $A0D4
1C2D-   A2 C3       LDX   #$C3
1C2F-   CD C4 20    CMP   $20C4
1C32-   A7          ???
1C33-   C3          ???
1C34-   CC CF D3    CPY   $D3CF
1C37-   C5 20       CMP   $20
1C39-   D4          ???
1C3A-   AE D4 C5    LDX   $C5D4
1C3D-   D8          CLD
1C3E-   D4          ???
1C3F-   C6 C9       DEC   $C9
1C41-   CC C5 A7    CPY   $A7C5
1C44-   A2 AC       LDX   #$AC
1C46-   B8          CLV
1C47-   C4 B8       CPY   $B8
1C49-   C4 8D       CPY   $8D
1C4B-   A0 C3       LDY   #$C3
1C4D-   CD C4 A0    CMP   $A0C4
1C50-   A2 CF       LDX   #$CF
1C52-   D0 C5       BNE   $1C19
1C54-   CE 20 D4    DEC   $D420
1C57-   AE D4 C5    LDX   $C5D4
1C5A-   D8          CLD
1C5B-   D4          ???
1C5C-   C6 C9       DEC   $C9
1C5E-   CC C5 A2    CPY   $A2C5
1C61-   8D A0 C3    STA   $C3A0
1C64-   CD C4 A0    CMP   $A0C4
1C67-   A2 D2       LDX   #$D2
1C69-   C5 C1       CMP   $C1
1C6B-   C4 20       CPY   $20
1C6D-   D4          ???
1C6E-   AE D4 C5    LDX   $C5D4
1C71-   D8          CLD
1C72-   D4          ???
1C73-   C6 C9       DEC   $C9
1C75-   CC C5 A2    CPY   $A2C5
1C78-   8D A0 C6    STA   $C6A0
1C7B-   C9 CE       CMP   #$CE
1C7D-   D0 A0       BNE   $1C1F
1C7F-   D2 C5       CMP   ($C5)
1C81-   D4          ???
1C82-   D5 D2       CMP   $D2,X
1C84-   CE 8D A0    DEC   $A08D
1C87-   C6 C9       DEC   $C9
1C89-   CE D0 A0    DEC   $A0D0
1C8C-   D0 C1       BNE   $1C4F
1C8E-   D2 C1       CMP   ($C1)
1C90-   CD 8D A0    CMP   $A08D
1C93-   C3          ???
1C94-   CD C4 A0    CMP   $A0C4
1C97-   A2 C3       LDX   #$C3
1C99-   CC CF D3    CPY   $D3CF
1C9C-   C5 20       CMP   $20
1C9E-   D4          ???
1C9F-   AE D4 C5    LDX   $C5D4
1CA2-   D8          CLD
1CA3-   D4          ???
1CA4-   C6 C9       DEC   $C9
1CA6-   CC C5 A2    CPY   $A2C5
1CA9-   8D A0 DF    STA   $DFA0
1CAC-   D7          ???
1CAD-   C1 C9       CMP   ($C9,X)
1CAF-   D4          ???
1CB0-   8D A0 DF    STA   $DFA0
1CB3-   C4 D5       CPY   $D5
1CB5-   CD D0 A0    CMP   $A0D0
1CB8-   D2 C5       CMP   ($C5)
1CBA-   D4          ???
1CBB-   D5 D2       CMP   $D2,X
1CBD-   CE BB D2    DEC   $D2BB
1CC0-   C5 D4       CMP   $D4
1CC2-   D5 D2       CMP   $D2,X
1CC4-   CE 8D A0    DEC   $A08D
1CC7-   DF          ???
1CC8-   C4 D5       CPY   $D5
1CCA-   CD D0 A0    CMP   $A0D0
1CCD-   D0 C1       BNE   $1C90
1CCF-   D2 C1       CMP   ($C1)
1CD1-   CD BB D0    CMP   $D0BB
1CD4-   C1 D2       CMP   ($D2,X)
1CD6-   C1 CD       CMP   ($CD,X)
1CD8-   8D A0 DF    STA   $DFA0
1CDB-   D7          ???
1CDC-   C1 C9       CMP   ($C9,X)
1CDE-   D4          ???
1CDF-   8D AA 8D    STA   $8DAA
1CE2-   A0 DF       LDY   #$DF
1CE4-   D0 D2       BNE   $1CB8
1CE6-   CE D4 A0    DEC   $A0D4
1CE9-   A2 20       LDX   #$20
1CEB-   A2 AC       LDX   #$AC
1CED-   B8          CLV
1CEE-   C4 B8       CPY   $B8
1CF0-   C4 8D       CPY   $8D
1CF2-   A0 DF       LDY   #$DF
1CF4-   D0 D2       BNE   $1CC8
1CF6-   CE D4 A0    DEC   $A0D4
1CF9-   A2 D4       LDX   #$D4
1CFB-   C8          INY
1CFC-   C5 D3       CMP   $D3
1CFE-   C5 20       CMP   $20
1D00-   D3          ???
1D01-   D4          ???
1D02-   D2 C9       CMP   ($C9)
1D04-   CE C7 D3    DEC   $D3C7
1D07-   20 C1 D2    JSR   $D2C1
1D0A-   C5 20       CMP   $20
1D0C-   CE CF D7    DEC   $D7CF
1D0F-   20 D3 D4    JSR   $D4D3
1D12-   CF          ???
1D13-   D2 C5       CMP   ($C5)
1D15-   C4 20       CPY   $20
1D17-   C9 CE       CMP   #$CE
1D19-   A2 AC       LDX   #$AC
1D1B-   B8          CLV
1D1C-   C4 8D       CPY   $8D
1D1E-   A0 DF       LDY   #$DF
1D20-   D0 D2       BNE   $1CF4
1D22-   CE D4 A0    DEC   $A0D4
1D25-   A2 DB       LDX   #$DB
1D27-   D2 C5       CMP   ($C5)
1D29-   D4          ???
1D2A-   D5 D2       CMP   $D2,X
1D2C-   CE DD 20    DEC   $20DD
1D2F-   C1 CE       CMP   ($CE,X)
1D31-   C4 20       CPY   $20
1D33-   DB          ???
1D34-   D0 C1       BNE   $1CF7
1D36-   D2 C1       CMP   ($C1)
1D38-   CD DD AC    CMP   $ACDD
1D3B-   20 D2 C5    JSR   $C5D2
1D3E-   D3          ???
1D3F-   D0 C5       BNE   $1D06
1D41-   C3          ???
1D42-   D4          ???
1D43-   C9 D6       CMP   #$D6
1D45-   C5 CC       CMP   $CC
1D47-   D9 AC A2    CMP   $A2AC,Y
1D4A-   AC B8 C4    LDY   $C4B8
1D4D-   8D A0 DF    STA   $DFA0
1D50-   D0 D2       BNE   $1D24
1D52-   CE D4 A0    DEC   $A0D4
1D55-   A2 D7       LDX   #$D7
1D57-   C9 D4       CMP   #$D4
1D59-   C8          INY
1D5A-   20 C1 20    JSR   $20C1
1D5D-   D0 D2       BNE   $1D31
1D5F-   C5 C3       CMP   $C3
1D61-   C5 C4       CMP   $C4
1D63-   C9 CE       CMP   #$CE
1D65-   C7          ???
1D66-   20 CC C5    JSR   $C5CC
1D69-   CE C7 D4    DEC   $D4C7
1D6C-   C8          INY
1D6D-   20 C2 D9    JSR   $D9C2
1D70-   D4          ???
1D71-   C5 AE       CMP   $AE
1D73-   20 D4 C8    JSR   $C8D4
1D76-   C5 D3       CMP   $D3
1D78-   C5 A2       CMP   $A2
1D7A-   AC B8 C4    LDY   $C4B8
1D7D-   8D A0 DF    STA   $DFA0
1D80-   D0 D2       BNE   $1D54
1D82-   CE D4 A0    DEC   $A0D4
1D85-   A2 C3       LDX   #$C3
1D87-   C1 CE       CMP   ($CE,X)
1D89-   20 C2 C5    JSR   $C5C2
1D8C-   20 D0 D2    JSR   $D2D0
1D8F-   C9 CE       CMP   #$CE
1D91-   D4          ???
1D92-   C5 C4       CMP   $C4
1D94-   20 D7 C9    JSR   $C9D7
1D97-   D4          ???
1D98-   C8          INY
1D99-   20 D4 C8    JSR   $C8D4
1D9C-   C5 20       CMP   $20
1D9E-   D3          ???
1D9F-   D0 D2       BNE   $1D73
1DA1-   CE 20 CD    DEC   $CD20
1DA4-   C1 C3       CMP   ($C3,X)
1DA6-   D2 CF       CMP   ($CF)
1DA8-   A2 AC       LDX   #$AC
1DAA-   B8          CLV
1DAB-   C4 8D       CPY   $8D
1DAD-   A0 DF       LDY   #$DF
1DAF-   D0 D2       BNE   $1D83
1DB1-   CE D4 A0    DEC   $A0D4
1DB4-   A2 C6       LDX   #$C6
1DB6-   CF          ???
1DB7-   D5 CE       CMP   $CE,X
1DB9-   C4 20       CPY   $20
1DBB-   C9 CE       CMP   #$CE
1DBD-   20 D4 C8    JSR   $C8D4
1DC0-   C5 20       CMP   $20
1DC2-   D3          ???
1DC3-   D4          ???
1DC4-   D2 C9       CMP   ($C9)
1DC6-   CE C7 D3    DEC   $D3C7
1DC9-   20 CC C9    JSR   $C9CC
1DCC-   C2          ???
1DCD-   D2 C1       CMP   ($C1)
1DCF-   D2 D9       CMP   ($D9)
1DD1-   AE A2 AC    LDX   $ACA2
1DD4-   B8          CLV
1DD5-   C4 B8       CPY   $B8
1DD7-   C4 B8       CPY   $B8
1DD9-   C4 8D       CPY   $8D
1DDB-   A0 DF       LDY   #$DF
1DDD-   D7          ???
1DDE-   C1 C9       CMP   ($C9,X)
1DE0-   D4          ???
1DE1-   8D AA 8D    STA   $8DAA
1DE4-   AA          TAX
1DE5-   AA          TAX
1DE6-   AA          TAX
1DE7-   AA          TAX
1DE8-   AA          TAX
1DE9-   AA          TAX
1DEA-   AA          TAX
1DEB-   AA          TAX
1DEC-   AA          TAX
1DED-   AA          TAX
1DEE-   AA          TAX
1DEF-   AA          TAX
1DF0-   AA          TAX
1DF1-   AA          TAX
1DF2-   AA          TAX
1DF3-   AA          TAX
1DF4-   AA          TAX
1DF5-   AA          TAX
1DF6-   AA          TAX
1DF7-   AA          TAX
1DF8-   AA          TAX
1DF9-   AA          TAX
1DFA-   AA          TAX
1DFB-   AA          TAX
1DFC-   AA          TAX
1DFD-   AA          TAX
1DFE-   AA          TAX
1DFF-   AA          TAX
1E00-   AA          TAX
1E01-   AA          TAX
1E02-   AA          TAX
1E03-   AA          TAX
1E04-   8D AA AA    STA   $AAAA
1E07-   AA          TAX
1E08-   AA          TAX
1E09-   AA          TAX
1E0A-   AA          TAX
1E0B-   AA          TAX
1E0C-   AA          TAX
1E0D-   AA          TAX
1E0E-   AA          TAX
1E0F-   AA          TAX
1E10-   AA          TAX
1E11-   AA          TAX
1E12-   AA          TAX
1E13-   AA          TAX
1E14-   AA          TAX
1E15-   AA          TAX
1E16-   AA          TAX
1E17-   AA          TAX
1E18-   AA          TAX
1E19-   AA          TAX
1E1A-   AA          TAX
1E1B-   AA          TAX
1E1C-   AA          TAX
1E1D-   AA          TAX
1E1E-   AA          TAX
1E1F-   AA          TAX
1E20-   AA          TAX
1E21-   AA          TAX
1E22-   AA          TAX
1E23-   AA          TAX
1E24-   AA          TAX
1E25-   8D AA AA    STA   $AAAA
1E28-   AA          TAX
1E29-   AA          TAX
1E2A-   AA          TAX
1E2B-   AA          TAX
1E2C-   AA          TAX
1E2D-   AA          TAX
1E2E-   AA          TAX
1E2F-   AA          TAX
1E30-   AA          TAX
1E31-   AA          TAX
1E32-   AA          TAX
1E33-   AA          TAX
1E34-   AA          TAX
1E35-   AA          TAX
1E36-   AA          TAX
1E37-   AA          TAX
1E38-   AA          TAX
1E39-   AA          TAX
1E3A-   AA          TAX
1E3B-   AA          TAX
1E3C-   AA          TAX
1E3D-   AA          TAX
1E3E-   AA          TAX
1E3F-   AA          TAX
1E40-   AA          TAX
1E41-   AA          TAX
1E42-   AA          TAX
1E43-   AA          TAX
1E44-   AA          TAX
1E45-   AA          TAX
1E46-   8D AA 20    STA   $20AA
1E49-   20 20 20    JSR   $2020
1E4C-   20 20 20    JSR   $2020
1E4F-   20 20 20    JSR   $2020
1E52-   20 20 20    JSR   $2020
1E55-   20 20 20    JSR   $2020
1E58-   20 20 20    JSR   $2020
1E5B-   20 20 20    JSR   $2020
1E5E-   20 20 20    JSR   $2020
1E61-   20 20 20    JSR   $2020
1E64-   20 20 AA    JSR   $AA20
1E67-   8D AA 20    STA   $20AA
1E6A-   20 20 D7    JSR   $D720
1E6D-   20 C1 20    JSR   $20C1
1E70-   D2 20       CMP   ($20)
1E72-   CE 20 C9    DEC   $C920
1E75-   20 CE 20    JSR   $20CE
1E78-   C7          ???
1E79-   20 20 20    JSR   $2020
1E7C-   20 20 20    JSR   $2020
1E7F-   20 20 20    JSR   $2020
1E82-   20 20 20    JSR   $2020
1E85-   20 20 AA    JSR   $AA20
1E88-   8D AA 20    STA   $20AA
1E8B-   20 20 20    JSR   $2020
1E8E-   20 20 20    JSR   $2020
1E91-   20 20 20    JSR   $2020
1E94-   20 20 20    JSR   $2020
1E97-   20 20 20    JSR   $2020
1E9A-   20 20 20    JSR   $2020
1E9D-   20 20 20    JSR   $2020
1EA0-   20 20 20    JSR   $2020
1EA3-   20 20 20    JSR   $2020
1EA6-   20 20 AA    JSR   $AA20
1EA9-   8D AA AA    STA   $AAAA
1EAC-   AA          TAX
1EAD-   AA          TAX
1EAE-   AA          TAX
1EAF-   AA          TAX
1EB0-   AA          TAX
1EB1-   AA          TAX
1EB2-   AA          TAX
1EB3-   AA          TAX
1EB4-   AA          TAX
1EB5-   AA          TAX
1EB6-   AA          TAX
1EB7-   AA          TAX
1EB8-   AA          TAX
1EB9-   AA          TAX
1EBA-   AA          TAX
1EBB-   AA          TAX
1EBC-   AA          TAX
1EBD-   AA          TAX
1EBE-   AA          TAX
1EBF-   AA          TAX
1EC0-   AA          TAX
1EC1-   AA          TAX
1EC2-   AA          TAX
1EC3-   AA          TAX
1EC4-   AA          TAX
1EC5-   AA          TAX
1EC6-   AA          TAX
1EC7-   AA          TAX
1EC8-   AA          TAX
1EC9-   AA          TAX
1ECA-   8D AA AA    STA   $AAAA
1ECD-   AA          TAX
1ECE-   AA          TAX
1ECF-   AA          TAX
1ED0-   AA          TAX
1ED1-   AA          TAX
1ED2-   AA          TAX
1ED3-   AA          TAX
1ED4-   AA          TAX
1ED5-   AA          TAX
1ED6-   AA          TAX
1ED7-   AA          TAX
1ED8-   AA          TAX
1ED9-   AA          TAX
1EDA-   AA          TAX
1EDB-   AA          TAX
1EDC-   AA          TAX
1EDD-   AA          TAX
1EDE-   AA          TAX
1EDF-   AA          TAX
1EE0-   AA          TAX
1EE1-   AA          TAX
1EE2-   AA          TAX
1EE3-   AA          TAX
1EE4-   AA          TAX
1EE5-   AA          TAX
1EE6-   AA          TAX
1EE7-   AA          TAX
1EE8-   AA          TAX
1EE9-   AA          TAX
1EEA-   AA          TAX
1EEB-   8D AA AA    STA   $AAAA
1EEE-   AA          TAX
1EEF-   AA          TAX
1EF0-   AA          TAX
1EF1-   AA          TAX
1EF2-   AA          TAX
1EF3-   AA          TAX
1EF4-   AA          TAX
1EF5-   AA          TAX
1EF6-   AA          TAX
1EF7-   AA          TAX
1EF8-   AA          TAX
1EF9-   AA          TAX
1EFA-   AA          TAX
1EFB-   AA          TAX
1EFC-   AA          TAX
1EFD-   AA          TAX
1EFE-   AA          TAX
1EFF-   AA          TAX
1F00-   AA          TAX
1F01-   AA          TAX
1F02-   AA          TAX
1F03-   AA          TAX
1F04-   AA          TAX
1F05-   AA          TAX
1F06-   AA          TAX
1F07-   AA          TAX
1F08-   AA          TAX
1F09-   AA          TAX
1F0A-   AA          TAX
1F0B-   AA          TAX
1F0C-   8D AA 8D    STA   $8DAA
1F0F-   A0 DF       LDY   #$DF
1F11-   D0 D2       BNE   $1EE5
1F13-   CE D4 A0    DEC   $A0D4
1F16-   A2 AA       LDX   #$AA
1F18-   AA          TAX
1F19-   AA          TAX
1F1A-   AA          TAX
1F1B-   AA          TAX
1F1C-   AA          TAX
1F1D-   AA          TAX
1F1E-   AA          TAX
1F1F-   AA          TAX
1F20-   AA          TAX
1F21-   AA          TAX
1F22-   AA          TAX
1F23-   AA          TAX
1F24-   AA          TAX
1F25-   AA          TAX
1F26-   AA          TAX
1F27-   AA          TAX
1F28-   AA          TAX
1F29-   AA          TAX
1F2A-   AA          TAX
1F2B-   AA          TAX
1F2C-   AA          TAX
1F2D-   AA          TAX
1F2E-   AA          TAX
1F2F-   AA          TAX
1F30-   AA          TAX
1F31-   AA          TAX
1F32-   AA          TAX
1F33-   AA          TAX
1F34-   AA          TAX
1F35-   AA          TAX
1F36-   AA          TAX
1F37-   A2 AC       LDX   #$AC
1F39-   B8          CLV
1F3A-   C4 8D       CPY   $8D
1F3C-   A0 DF       LDY   #$DF
1F3E-   D0 D2       BNE   $1F12
1F40-   CE D4 A0    DEC   $A0D4
1F43-   A2 AA       LDX   #$AA
1F45-   AA          TAX
1F46-   AA          TAX
1F47-   AA          TAX
1F48-   AA          TAX
1F49-   AA          TAX
1F4A-   AA          TAX
1F4B-   AA          TAX
1F4C-   AA          TAX
1F4D-   AA          TAX
1F4E-   AA          TAX
1F4F-   AA          TAX
1F50-   AA          TAX
1F51-   AA          TAX
1F52-   AA          TAX
1F53-   AA          TAX
1F54-   AA          TAX
1F55-   AA          TAX
1F56-   AA          TAX
1F57-   AA          TAX
1F58-   AA          TAX
1F59-   AA          TAX
1F5A-   AA          TAX
1F5B-   AA          TAX
1F5C-   AA          TAX
1F5D-   AA          TAX
1F5E-   AA          TAX
1F5F-   AA          TAX
1F60-   AA          TAX
1F61-   AA          TAX
1F62-   AA          TAX
1F63-   AA          TAX
1F64-   A2 AC       LDX   #$AC
1F66-   B8          CLV
1F67-   C4 B8       CPY   $B8
1F69-   C4 8D       CPY   $8D
1F6B-   A0 DF       LDY   #$DF
1F6D-   D0 D2       BNE   $1F41
1F6F-   CE D4 A0    DEC   $A0D4
1F72-   A2 20       LDX   #$20
1F74-   20 20 20    JSR   $2020
1F77-   20 20 D7    JSR   $D720
1F7A-   C1 D2       CMP   ($D2,X)
1F7C-   CE C9 CE    DEC   $CEC9
1F7F-   C7          ???
1F80-   A1 A1       LDA   ($A1,X)
1F82-   A1 A2       LDA   ($A2,X)
1F84-   AC B8 C4    LDY   $C4B8
1F87-   B8          CLV
1F88-   C4 8D       CPY   $8D
1F8A-   A0 DF       LDY   #$DF
1F8C-   D0 D2       BNE   $1F60
1F8E-   CE D4 A0    DEC   $A0D4
1F91-   A2 AA       LDX   #$AA
1F93-   AA          TAX
1F94-   AA          TAX
1F95-   AA          TAX
1F96-   AA          TAX
1F97-   AA          TAX
1F98-   AA          TAX
1F99-   AA          TAX
1F9A-   AA          TAX
1F9B-   AA          TAX
1F9C-   AA          TAX
1F9D-   AA          TAX
1F9E-   AA          TAX
1F9F-   AA          TAX
1FA0-   AA          TAX
1FA1-   AA          TAX
1FA2-   AA          TAX
1FA3-   AA          TAX
1FA4-   AA          TAX
1FA5-   AA          TAX
1FA6-   AA          TAX
1FA7-   AA          TAX
1FA8-   AA          TAX
1FA9-   AA          TAX
1FAA-   AA          TAX
1FAB-   AA          TAX
1FAC-   AA          TAX
1FAD-   AA          TAX
1FAE-   AA          TAX
1FAF-   AA          TAX
1FB0-   AA          TAX
1FB1-   AA          TAX
1FB2-   A2 AC       LDX   #$AC
1FB4-   B8          CLV
1FB5-   C4 8D       CPY   $8D
1FB7-   A0 DF       LDY   #$DF
1FB9-   D0 D2       BNE   $1F8D
1FBB-   CE D4 A0    DEC   $A0D4
1FBE-   A2 AA       LDX   #$AA
1FC0-   AA          TAX
1FC1-   AA          TAX
1FC2-   AA          TAX
1FC3-   AA          TAX
1FC4-   AA          TAX
1FC5-   AA          TAX
1FC6-   AA          TAX
1FC7-   AA          TAX
1FC8-   AA          TAX
1FC9-   AA          TAX
1FCA-   AA          TAX
1FCB-   AA          TAX
1FCC-   AA          TAX
1FCD-   AA          TAX
1FCE-   AA          TAX
1FCF-   AA          TAX
1FD0-   AA          TAX
1FD1-   AA          TAX
1FD2-   AA          TAX
1FD3-   AA          TAX
1FD4-   AA          TAX
1FD5-   AA          TAX
1FD6-   AA          TAX
1FD7-   AA          TAX
1FD8-   AA          TAX
1FD9-   AA          TAX
1FDA-   AA          TAX
1FDB-   AA          TAX
1FDC-   AA          TAX
1FDD-   AA          TAX
1FDE-   AA          TAX
1FDF-   A2 AC       LDX   #$AC
1FE1-   B8          CLV
1FE2-   C4 B8       CPY   $B8
1FE4-   C4 8D       CPY   $8D
1FE6-   A0 DF       LDY   #$DF
1FE8-   D0 D2       BNE   $1FBC
1FEA-   CE D4 A0    DEC   $A0D4
1FED-   A2 C1       LDX   #$C1
1FEF-   D4          ???
1FF0-   20 D4 C8    JSR   $C8D4
1FF3-   C9 D3       CMP   #$D3
1FF5-   20 D0 CF    JSR   $CFD0
1FF8-   C9 CE       CMP   #$CE
1FFA-   D4          ???
1FFB-   AC 20 D9    LDY   $D920
1FFE-   CF          ???
1FFF-   D5 20       CMP   $20,X
2001-   D7          ???
2002-   C1 CE       CMP   ($CE,X)
2004-   D4          ???
2005-   20 D4 CF    JSR   $CFD4
2008-   20 C5 CA    JSR   $CAC5
200B-   C5 C3       CMP   $C3
200D-   D4          ???
200E-   A2 AC       LDX   #$AC
2010-   B8          CLV
2011-   C4 8D       CPY   $8D
2013-   A0 DF       LDY   #$DF
2015-   D0 D2       BNE   $1FE9
2017-   CE D4 A0    DEC   $A0D4
201A-   A2 D4       LDX   #$D4
201C-   C8          INY
201D-   C5 20       CMP   $20
201F-   C3          ???
2020-   D5 D2       CMP   $D2,X
2022-   D2 C5       CMP   ($C5)
2024-   CE D4 20    DEC   $20D4
2027-   C4 C9       CPY   $C9
2029-   D3          ???
202A-   CB          ???
202B-   AC 20 C1    LDY   $C120
202E-   CE C4 20    DEC   $20C4
2031-   D0 D5       BNE   $2008
2033-   D4          ???
2034-   20 C9 CE    JSR   $CEC9
2037-   A2 AC       LDX   #$AC
2039-   B8          CLV
203A-   C4 8D       CPY   $8D
203C-   A0 DF       LDY   #$DF
203E-   D0 D2       BNE   $2012
2040-   CE D4 A0    DEC   $A0D4
2043-   A2 C1       LDX   #$C1
2045-   20 C4 C9    JSR   $C9C4
2048-   D3          ???
2049-   CB          ???
204A-   20 D4 C8    JSR   $C8D4
204D-   C1 D4       CMP   ($D4,X)
204F-   20 D9 CF    JSR   $CFD9
2052-   D5 20       CMP   $20,X
2054-   C4 CF       CPY   $CF
2056-   CE A7 D4    DEC   $D4A7
2059-   20 CD C9    JSR   $C9CD
205C-   CE C4 20    DEC   $20C4
205F-   A2 AC       LDX   #$AC
2061-   B8          CLV
2062-   C4 8D       CPY   $8D
2064-   A0 DF       LDY   #$DF
2066-   D0 D2       BNE   $203A
2068-   CE D4 A0    DEC   $A0D4
206B-   A2 C8       LDX   #$C8
206D-   C1 D6       CMP   ($D6,X)
206F-   C9 CE       CMP   #$CE
2071-   C7          ???
2072-   20 D4 CF    JSR   $CFD4
2075-   20 D2 C5    JSR   $C5D2
2078-   C6 CF       DEC   $CF
207A-   D2 CD       CMP   ($CD)
207C-   C1 D4       CMP   ($D4,X)
207E-   AE 20 A2    LDX   $A220
2081-   AC B8 C4    LDY   $C4B8
2084-   B8          CLV
2085-   C4 8D       CPY   $8D
2087-   A0 DF       LDY   #$DF
2089-   D0 D2       BNE   $205D
208B-   CE D4 A0    DEC   $A0D4
208E-   A2 D4       LDX   #$D4
2090-   C8          INY
2091-   C5 20       CMP   $20
2093-   D2 C5       CMP   ($C5)
2095-   D3          ???
2096-   D4          ???
2097-   20 CF C6    JSR   $C6CF
209A-   20 D4 C8    JSR   $C8D4
209D-   C5 20       CMP   $20
209F-   D2 CF       CMP   ($CF)
20A1-   D5 D4       CMP   $D4,X
20A3-   C9 CE       CMP   #$CE
20A5-   C5 D3       CMP   $D3
20A7-   20 C1 D2    JSR   $D2C1
20AA-   C5 A2       CMP   $A2
20AC-   AC B8 C4    LDY   $C4B8
20AF-   8D A0 DF    STA   $DFA0
20B2-   D0 D2       BNE   $2086
20B4-   CE D4 A0    DEC   $A0D4
20B7-   A2 CC       LDX   #$CC
20B9-   CF          ???
20BA-   D7          ???
20BB-   20 CC C5    JSR   $C5CC
20BE-   D6 C5       DEC   $C5,X
20C0-   CC 20 C4    CPY   $C420
20C3-   C9 D3       CMP   #$D3
20C5-   CB          ???
20C6-   20 C1 C3    JSR   $C3C1
20C9-   C3          ???
20CA-   C5 D3       CMP   $D3
20CC-   D3          ???
20CD-   20 D0 D2    JSR   $D2D0
20D0-   CF          ???
20D1-   C3          ???
20D2-   C5 C4       CMP   $C4
20D4-   D5 D2       CMP   $D2,X
20D6-   C5 D3       CMP   $D3
20D8-   AC A2 AC    LDY   $ACA2
20DB-   B8          CLV
20DC-   C4 8D       CPY   $8D
20DE-   A0 DF       LDY   #$DF
20E0-   D0 D2       BNE   $20B4
20E2-   CE D4 A0    DEC   $A0D4
20E5-   A2 C1       LDX   #$C1
20E7-   CE C4 20    DEC   $20C4
20EA-   C3          ???
20EB-   C1 CE       CMP   ($CE,X)
20ED-   20 D3 C5    JSR   $C5D3
20F0-   D2 C9       CMP   ($C9)
20F2-   CF          ???
20F3-   D5 D3       CMP   $D3,X
20F5-   CC D9 20    CPY   $20D9
20F8-   C4 C1       CPY   $C1
20FA-   CD C1 C7    CMP   $C7C1
20FD-   C5 20       CMP   $20
20FF-   C1 20       CMP   ($20,X)
2101-   C4 C9       CPY   $C9
2103-   D3          ???
2104-   CB          ???
2105-   A1 A2       LDA   ($A2,X)
2107-   AC B8 C4    LDY   $C4B8
210A-   B8          CLV
210B-   C4 8D       CPY   $8D
210D-   A0 DF       LDY   #$DF
210F-   D0 D2       BNE   $20E3
2111-   CE D4 A0    DEC   $A0D4
2114-   A2 BC       LDX   #$BC
2116-   BC BC 20    LDY   $20BC,X
2119-   D0 D2       BNE   $20ED
211B-   C5 D3       CMP   $D3
211D-   D3          ???
211E-   20 C1 20    JSR   $20C1
2121-   CB          ???
2122-   C5 D9       CMP   $D9
2124-   20 CF CE    JSR   $CECF
2127-   C3          ???
2128-   C5 20       CMP   $20
212A-   D9 CF D5    CMP   $D5CF,Y
212D-   A7          ???
212E-   D2 C5       CMP   ($C5)
2130-   20 D2 C5    JSR   $C5D2
2133-   C1 C4       CMP   ($C4,X)
2135-   D9 20 BE    CMP   $BE20,Y
2138-   BE BE A2    LDX   $A2BE,Y
213B-   AC B8 C4    LDY   $C4B8
213E-   B8          CLV
213F-   C4 8D       CPY   $8D
2141-   A0 DF       LDY   #$DF
2143-   D7          ???
2144-   C1 C9       CMP   ($C9,X)
2146-   D4          ???
2147-   8D AA 8D    STA   $8DAA
214A-   A0 DF       LDY   #$DF
214C-   D0 D2       BNE   $2120
214E-   CE D4 A0    DEC   $A0D4
2151-   A2 CC       LDX   #$CC
2153-   CF          ???
2154-   D7          ???
2155-   AD CC C5    LDA   $C5CC
2158-   D6 C5       DEC   $C5,X
215A-   CC 20 C4    CPY   $C420
215D-   C9 D3       CMP   #$D3
215F-   CB          ???
2160-   20 C1 C3    JSR   $C3C1
2163-   C3          ???
2164-   C5 D3       CMP   $D3
2166-   D3          ???
2167-   20 C9 D3    JSR   $D3C9
216A-   20 C4 CF    JSR   $CFC4
216D-   CE C5 20    DEC   $20C5
2170-   D6 C9       DEC   $C9,X
2172-   C1 A2       CMP   ($A2,X)
2174-   AC B8 C4    LDY   $C4B8
2177-   8D A0 DF    STA   $DFA0
217A-   D0 D2       BNE   $214E
217C-   CE D4 A0    DEC   $A0D4
217F-   A2 D4       LDX   #$D4
2181-   C8          INY
2182-   C5 20       CMP   $20
2184-   D3          ???
2185-   D4          ???
2186-   C1 CE       CMP   ($CE,X)
2188-   C4 C1       CPY   $C1
218A-   D2 C4       CMP   ($C4)
218C-   20 D2 D7    JSR   $D7D2
218F-   D4          ???
2190-   D3          ???
2191-   20 D2 CF    JSR   $CFD2
2194-   D5 D4       CMP   $D4,X
2196-   C9 CE       CMP   #$CE
2198-   C5 AC       CMP   $AC
219A-   20 D7 C9    JSR   $C9D7
219D-   D4          ???
219E-   C8          INY
219F-   20 C1 A2    JSR   $A2C1
21A2-   AC B8 C4    LDY   $C4B8
21A5-   8D A0 DF    STA   $DFA0
21A8-   D0 D2       BNE   $217C
21AA-   CE D4 A0    DEC   $A0D4
21AD-   A2 C6       LDX   #$C6
21AF-   C5 D7       CMP   $D7
21B1-   20 CD C1    JSR   $C1CD
21B4-   C3          ???
21B5-   D2 CF       CMP   ($CF)
21B7-   D3          ???
21B8-   20 D4 C8    JSR   $C8D4
21BB-   D2 CF       CMP   ($CF)
21BD-   D7          ???
21BE-   CE 20 C9    DEC   $C920
21C1-   CE 20 D4    DEC   $D420
21C4-   CF          ???
21C5-   20 CD C1    JSR   $C1CD
21C8-   CB          ???
21C9-   C5 20       CMP   $20
21CB-   C9 D4       CMP   #$D4
21CD-   20 AA C6    JSR   $C6AA
21D0-   C5 C5       CMP   $C5
21D2-   CC AA A2    CPY   $A2AA
21D5-   AC B8 C4    LDY   $C4B8
21D8-   8D A0 DF    STA   $DFA0
21DB-   D0 D2       BNE   $21AF
21DD-   CE D4 A0    DEC   $A0D4
21E0-   A2 CD       LDX   #$CD
21E2-   CF          ???
21E3-   D2 C5       CMP   ($C5)
21E5-   20 D3 C5    JSR   $C5D3
21E8-   D2 C9       CMP   ($C9)
21EA-   C1 CC       CMP   ($CC,X)
21EC-   C9 DA       CMP   #$DA
21EE-   C5 C4       CMP   $C4
21F0-   AE 20 D4    LDX   $D420
21F3-   C8          INY
21F4-   C5 20       CMP   $20
21F6-   C6 CF       DEC   $CF
21F8-   CC CC CF    CPY   $CFCC
21FB-   D7          ???
21FC-   C9 CE       CMP   #$CE
21FE-   C7          ???
21FF-   20 CD C1    JSR   $C1CD
2202-   C3          ???
2203-   D2 CF       CMP   ($CF)
2205-   D3          ???
2206-   A2 AC       LDX   #$AC
2208-   B8          CLV
2209-   C4 8D       CPY   $8D
220B-   A0 DF       LDY   #$DF
220D-   D0 D2       BNE   $21E1
220F-   CE D4 A0    DEC   $A0D4
2212-   A2 C1       LDX   #$C1
2214-   CC D4 C5    CPY   $C5D4
2217-   D2 20       CMP   ($20)
2219-   D4          ???
221A-   C8          INY
221B-   C5 20       CMP   $20
221D-   D2 D7       CMP   ($D7)
221F-   D4          ???
2220-   D3          ???
2221-   20 D2 CF    JSR   $CFD2
2224-   D5 D4       CMP   $D4,X
2226-   C9 CE       CMP   #$CE
2228-   C5 A7       CMP   $A7
222A-   D3          ???
222B-   20 C2 C5    JSR   $C5C2
222E-   C1 C8       CMP   ($C8,X)
2230-   D6 C9       DEC   $C9,X
2232-   CF          ???
2233-   D2 BA       CMP   ($BA)
2235-   A2 AC       LDX   #$AC
2237-   B8          CLV
2238-   C4 B8       CPY   $B8
223A-   C4 8D       CPY   $8D
223C-   A0 DF       LDY   #$DF
223E-   D0 D2       BNE   $2212
2240-   CE D4 A0    DEC   $A0D4
2243-   A2 D3       LDX   #$D3
2245-   CC CF D4    CPY   $D4CF
2248-   20 BA 20    JSR   $20BA
224B-   D3          ???
224C-   C5 D4       CMP   $D4
224E-   D3          ???
224F-   20 D4 C8    JSR   $C8D4
2252-   C5 20       CMP   $20
2254-   D2 D7       CMP   ($D7)
2256-   D4          ???
2257-   D3          ???
2258-   20 D3 CC    JSR   $CCD3
225B-   CF          ???
225C-   D4          ???
225D-   A2 AC       LDX   #$AC
225F-   B8          CLV
2260-   C4 8D       CPY   $8D
2262-   A0 DF       LDY   #$DF
2264-   D0 D2       BNE   $2238
2266-   CE D4 A0    DEC   $A0D4
2269-   A2 C4       LDX   #$C4
226B-   D2 C9       CMP   ($C9)
226D-   D6 C5       DEC   $C5,X
226F-   BA          TSX
2270-   20 D3 C5    JSR   $C5D3
2273-   D4          ???
2274-   D3          ???
2275-   20 D4 C8    JSR   $C8D4
2278-   C5 20       CMP   $20
227A-   D2 D7       CMP   ($D7)
227C-   D4          ???
227D-   D3          ???
227E-   20 C4 D2    JSR   $D2C4
2281-   C9 D6       CMP   #$D6
2283-   C5 A2       CMP   $A2
2285-   AC B8 C4    LDY   $C4B8
2288-   8D A0 DF    STA   $DFA0
228B-   D0 D2       BNE   $225F
228D-   CE D4 A0    DEC   $A0D4
2290-   A2 D4       LDX   #$D4
2292-   D2 C1       CMP   ($C1)
2294-   C3          ???
2295-   CB          ???
2296-   BA          TSX
2297-   20 D3 C5    JSR   $C5D3
229A-   D4          ???
229B-   D3          ???
229C-   20 D4 C8    JSR   $C8D4
229F-   C5 20       CMP   $20
22A1-   D4          ???
22A2-   D2 C1       CMP   ($C1)
22A4-   C3          ???
22A5-   CB          ???
22A6-   20 D4 CF    JSR   $CFD4
22A9-   20 C2 C5    JSR   $C5C2
22AC-   20 D7 D2    JSR   $D2D7
22AF-   C9 D4       CMP   #$D4
22B1-   D4          ???
22B2-   C5 CE       CMP   $CE
22B4-   AF          ???
22B5-   D2 C5       CMP   ($C5)
22B7-   C1 C4       CMP   ($C4,X)
22B9-   A2 AC       LDX   #$AC
22BB-   B8          CLV
22BC-   C4 8D       CPY   $8D
22BE-   A0 DF       LDY   #$DF
22C0-   D0 D2       BNE   $2294
22C2-   CE D4 A0    DEC   $A0D4
22C5-   A2 D3       LDX   #$D3
22C7-   C5 C3       CMP   $C3
22C9-   D4          ???
22CA-   20 BA 20    JSR   $20BA
22CD-   D3          ???
22CE-   C5 D4       CMP   $D4
22D0-   D3          ???
22D1-   20 D4 C8    JSR   $C8D4
22D4-   C5 20       CMP   $20
22D6-   D3          ???
22D7-   C5 C3       CMP   $C3
22D9-   D4          ???
22DA-   CF          ???
22DB-   D2 20       CMP   ($20)
22DD-   D4          ???
22DE-   CF          ???
22DF-   20 C2 C5    JSR   $C5C2
22E2-   20 D2 C5    JSR   $C5D2
22E5-   C1 C4       CMP   ($C4,X)
22E7-   AF          ???
22E8-   D7          ???
22E9-   D2 C9       CMP   ($C9)
22EB-   D4          ???
22EC-   D4          ???
22ED-   C5 CE       CMP   $CE
22EF-   A2 AC       LDX   #$AC
22F1-   B8          CLV
22F2-   C4 8D       CPY   $8D
22F4-   A0 DF       LDY   #$DF
22F6-   D0 D2       BNE   $22CA
22F8-   CE D4 A0    DEC   $A0D4
22FB-   A2 D3       LDX   #$D3
22FD-   C5 D4       CMP   $D4
22FF-   C4 D2       CPY   $D2
2301-   BA          TSX
2302-   20 D3 C5    JSR   $C5D3
2305-   D4          ???
2306-   20 D2 D7    JSR   $D7D2
2309-   D4          ???
230A-   D3          ???
230B-   20 D4 CF    JSR   $CFD4
230E-   20 D2 C5    JSR   $C5D2
2311-   C1 C4       CMP   ($C4,X)
2313-   20 CD CF    JSR   $CFCD
2316-   C4 C5       CPY   $C5
2318-   A2 AC       LDX   #$AC
231A-   B8          CLV
231B-   C4 8D       CPY   $8D
231D-   A0 DF       LDY   #$DF
231F-   D0 D2       BNE   $22F3
2321-   CE D4 A0    DEC   $A0D4
2324-   A2 D3       LDX   #$D3
2326-   C5 D4       CMP   $D4
2328-   C4 D7       CPY   $D7
232A-   BA          TSX
232B-   20 D3 C5    JSR   $C5D3
232E-   D4          ???
232F-   20 D2 D7    JSR   $D7D2
2332-   D4          ???
2333-   D3          ???
2334-   20 D4 CF    JSR   $CFD4
2337-   20 D7 D2    JSR   $D2D7
233A-   C9 D4       CMP   #$D4
233C-   C5 20       CMP   $20
233E-   CD CF C4    CMP   $C4CF
2341-   C5 A2       CMP   $A2
2343-   AC B8 C4    LDY   $C4B8
2346-   8D A0 DF    STA   $DFA0
2349-   D0 D2       BNE   $231D
234B-   CE D4 A0    DEC   $A0D4
234E-   A2 C4       LDX   #$C4
2350-   C2          ???
2351-   D5 C6       CMP   $C6,X
2353-   C6 BA       DEC   $BA
2355-   20 D3 C5    JSR   $C5D3
2358-   D4          ???
2359-   20 D4 C8    JSR   $C8D4
235C-   C5 20       CMP   $20
235E-   D2 C5       CMP   ($C5)
2360-   C1 C4       CMP   ($C4,X)
2362-   AF          ???
2363-   D7          ???
2364-   D2 C9       CMP   ($C9)
2366-   D4          ???
2367-   C5 20       CMP   $20
2369-   C2          ???
236A-   D5 C6       CMP   $C6,X
236C-   C6 C5       DEC   $C5
236E-   D2 20       CMP   ($20)
2370-   C1 C4       CMP   ($C4,X)
2372-   C4 D2       CPY   $D2
2374-   C5 D3       CMP   $D3
2376-   D3          ???
2377-   A2 AC       LDX   #$AC
2379-   B8          CLV
237A-   C4 B8       CPY   $B8
237C-   C4 8D       CPY   $8D
237E-   A0 DF       LDY   #$DF
2380-   D7          ???
2381-   C1 C9       CMP   ($C9,X)
2383-   D4          ???
2384-   8D A0 DF    STA   $DFA0
2387-   D0 D2       BNE   $235B
2389-   CE D4 A0    DEC   $A0D4
238C-   A2 C5       LDX   #$C5
238E-   C1 C3       CMP   ($C3,X)
2390-   C8          INY
2391-   20 CF C6    JSR   $C6CF
2394-   20 D4 C8    JSR   $C8D4
2397-   C5 D3       CMP   $D3
2399-   C5 20       CMP   $20
239B-   D3          ???
239C-   C5 D4       CMP   $D4
239E-   D4          ???
239F-   C9 CE       CMP   #$CE
23A1-   C7          ???
23A2-   D3          ???
23A3-   20 C1 D2    JSR   $D2C1
23A6-   C5 20       CMP   $20
23A8-   C9 CE       CMP   #$CE
23AA-   C8          INY
23AB-   C5 D2       CMP   $D2
23AD-   C9 D4       CMP   #$D4
23AF-   C5 C4       CMP   $C4
23B1-   A2 AC       LDX   #$AC
23B3-   B8          CLV
23B4-   C4 8D       CPY   $8D
23B6-   A0 DF       LDY   #$DF
23B8-   D0 D2       BNE   $238C
23BA-   CE D4 A0    DEC   $A0D4
23BD-   A2 C6       LDX   #$C6
23BF-   D2 CF       CMP   ($CF)
23C1-   CD 20 D4    CMP   $D420
23C4-   C8          INY
23C5-   C5 20       CMP   $20
23C7-   D0 D2       BNE   $239B
23C9-   C5 D6       CMP   $D6
23CB-   C9 CF       CMP   #$CF
23CD-   D5 D3       CMP   $D3,X
23CF-   20 D3 D4    JSR   $D4D3
23D2-   C1 D4       CMP   ($D4,X)
23D4-   C5 BB       CMP   $BB
23D6-   20 C9 C6    JSR   $C6C9
23D9-   20 D9 CF    JSR   $CFD9
23DC-   D5 20       CMP   $20,X
23DE-   C1 D2       CMP   ($D2,X)
23E0-   C5 A2       CMP   $A2
23E2-   AC B8 C4    LDY   $C4B8
23E5-   8D A0 DF    STA   $DFA0
23E8-   D0 D2       BNE   $23BC
23EA-   CE D4 A0    DEC   $A0D4
23ED-   A2 C1       LDX   #$C1
23EF-   CC D2 C5    CPY   $C5D2
23F2-   C1 C4       CMP   ($C4,X)
23F4-   D9 20 D5    CMP   $D520,Y
23F7-   D3          ???
23F8-   C9 CE       CMP   #$CE
23FA-   C7          ???
23FB-   20 D3 C5    JSR   $C5D3
23FE-   C3          ???
23FF-   D4          ???
2400-   CF          ???
2401-   D2 20       CMP   ($20)
2403-   B6 AC       LDX   $AC,Y
2405-   20 C4 D2    JSR   $D2C4
2408-   C9 D6       CMP   #$D6
240A-   C5 20       CMP   $20
240C-   B1 AC       LDA   ($AC),Y
240E-   20 C6 CF    JSR   $CFC6
2411-   D2 A2       CMP   ($A2)
2413-   AC B8 C4    LDY   $C4B8
2416-   8D A0 DF    STA   $DFA0
2419-   D0 D2       BNE   $23ED
241B-   CE D4 A0    DEC   $A0D4
241E-   A2 C5       LDX   #$C5
2420-   D8          CLD
2421-   C1 CD       CMP   ($CD,X)
2423-   D0 CC       BNE   $23F1
2425-   C5 AC       CMP   $AC
2427-   20 D4 C8    JSR   $C8D4
242A-   C5 CE       CMP   $CE
242C-   20 D9 CF    JSR   $CFD9
242F-   D5 20       CMP   $20,X
2431-   C4 CF       CPY   $CF
2433-   CE A7 D4    DEC   $D4A7
2436-   20 C8 C1    JSR   $C1C8
2439-   D6 C5       DEC   $C5,X
243B-   20 D4 CF    JSR   $CFD4
243E-   20 D3 C5    JSR   $C5D3
2441-   D4          ???
2442-   20 C9 D4    JSR   $D4C9
2445-   20 C1 C7    JSR   $C7C1
2448-   C1 C9       CMP   ($C9,X)
244A-   CE A2 AC    DEC   $ACA2
244D-   B8          CLV
244E-   C4 8D       CPY   $8D
2450-   A0 DF       LDY   #$DF
2452-   D0 D2       BNE   $2426
2454-   CE D4 A0    DEC   $A0D4
2457-   A2 D5       LDX   #$D5
2459-   CE CC C5    DEC   $C5CC
245C-   D3          ???
245D-   D3          ???
245E-   20 D9 CF    JSR   $CFD9
2461-   D5 20       CMP   $20,X
2463-   D7          ???
2464-   C1 CE       CMP   ($CE,X)
2466-   D4          ???
2467-   20 D4 C8    JSR   $C8D4
246A-   CF          ???
246B-   D3          ???
246C-   C5 20       CMP   $20
246E-   D3          ???
246F-   C5 D4       CMP   $D4
2471-   D4          ???
2472-   C9 CE       CMP   #$CE
2474-   C7          ???
2475-   D3          ???
2476-   20 C3 C8    JSR   $C8C3
2479-   C1 CE       CMP   ($CE,X)
247B-   C7          ???
247C-   C5 C4       CMP   $C4
247E-   AE A2 AC    LDX   $ACA2
2481-   B8          CLV
2482-   C4 8D       CPY   $8D
2484-   A0 DF       LDY   #$DF
2486-   D0 D2       BNE   $245A
2488-   CE D4 A0    DEC   $A0D4
248B-   A2 D4       LDX   #$D4
248D-   C8          INY
248E-   C9 D3       CMP   #$D3
2490-   20 CC C9    JSR   $C9CC
2493-   C2          ???
2494-   D2 C1       CMP   ($C1)
2496-   D2 D9       CMP   ($D9)
2498-   20 C1 CC    JSR   $CCC1
249B-   D3          ???
249C-   CF          ???
249D-   20 D5 D3    JSR   $D3D5
24A0-   C5 D3       CMP   $D3
24A2-   20 D4 C8    JSR   $C8D4
24A5-   C5 20       CMP   $20
24A7-   D3          ???
24A8-   C1 CD       CMP   ($CD,X)
24AA-   C5 20       CMP   $20
24AC-   C9 CF       CMP   #$CF
24AE-   C2          ???
24AF-   A2 AC       LDX   #$AC
24B1-   B8          CLV
24B2-   C4 8D       CPY   $8D
24B4-   A0 DF       LDY   #$DF
24B6-   D0 D2       BNE   $248A
24B8-   CE D4 A0    DEC   $A0D4
24BB-   A2 D4       LDX   #$D4
24BD-   C1 C2       CMP   ($C2,X)
24BF-   CC C5 20    CPY   $20C5
24C2-   C1 D3       CMP   ($D3,X)
24C4-   20 D4 C8    JSR   $C8D4
24C7-   C5 20       CMP   $20
24C9-   CF          ???
24CA-   D0 C5       BNE   $2491
24CC-   D2 C1       CMP   ($C1)
24CE-   D4          ???
24CF-   C9 CE       CMP   #$CE
24D1-   C7          ???
24D2-   20 D3 D9    JSR   $D9D3
24D5-   D3          ???
24D6-   D4          ???
24D7-   C5 CD       CMP   $CD
24D9-   20 A8 C4    JSR   $C4A8
24DC-   CF          ???
24DD-   D3          ???
24DE-   20 CF D2    JSR   $D2CF
24E1-   A2 AC       LDX   #$AC
24E3-   B8          CLV
24E4-   C4 8D       CPY   $8D
24E6-   A0 DF       LDY   #$DF
24E8-   D0 D2       BNE   $24BC
24EA-   CE D4 A0    DEC   $A0D4
24ED-   A2 D0       LDX   #$D0
24EF-   D2 CF       CMP   ($CF)
24F1-   C4 CF       CPY   $CF
24F3-   D3          ???
24F4-   A9 20       LDA   #$20
24F6-   D4          ???
24F7-   CF          ???
24F8-   20 C3 C1    JSR   $C1C3
24FB-   D2 D2       CMP   ($D2)
24FD-   D9 20 CF    CMP   $CF20,Y
2500-   D6 C5       DEC   $C5,X
2502-   D2 20       CMP   ($20)
2504-   C1 CE       CMP   ($CE,X)
2506-   D9 20 D0    CMP   $D020,Y
2509-   D2 C5       CMP   ($C5)
250B-   D6 C9       DEC   $C9,X
250D-   CF          ???
250E-   D5 D3       CMP   $D3,X
2510-   20 D3 C5    JSR   $C5D3
2513-   D4          ???
2514-   D4          ???
2515-   C9 CE       CMP   #$CE
2517-   C7          ???
2518-   D3          ???
2519-   AE A2 AC    LDX   $ACA2
251C-   B8          CLV
251D-   C4 B8       CPY   $B8
251F-   C4 8D       CPY   $8D
2521-   A0 DF       LDY   #$DF
2523-   D7          ???
2524-   C1 C9       CMP   ($C9,X)
2526-   D4          ???
2527-   8D AA 8D    STA   $8DAA
252A-   A0 DF       LDY   #$DF
252C-   D0 D2       BNE   $2500
252E-   CE D4 A0    DEC   $A0D4
2531-   A2 CF       LDX   #$CF
2533-   CE C3 C5    DEC   $C5C3
2536-   20 D4 C8    JSR   $C8D4
2539-   C5 20       CMP   $20
253B-   D3          ???
253C-   C5 D4       CMP   $D4
253E-   D4          ???
253F-   C9 CE       CMP   #$CE
2541-   C7          ???
2542-   D3          ???
2543-   20 C1 D2    JSR   $D2C1
2546-   C5 20       CMP   $20
2548-   C1 D3       CMP   ($D3,X)
254A-   20 C4 C5    JSR   $C5C4
254D-   D3          ???
254E-   C9 D2       CMP   #$D2
2550-   C5 C4       CMP   $C4
2552-   AC A2 AC    LDY   $ACA2
2555-   B8          CLV
2556-   C4 8D       CPY   $8D
2558-   A0 DF       LDY   #$DF
255A-   D0 D2       BNE   $252E
255C-   CE D4 A0    DEC   $A0D4
255F-   A2 D9       LDX   #$D9
2561-   CF          ???
2562-   D5 20       CMP   $20,X
2564-   D5 D3       CMP   $D3,X
2566-   C5 20       CMP   $20
2568-   D4          ???
2569-   C8          INY
256A-   C5 20       CMP   $20
256C-   C4 D2       CPY   $D2
256E-   D7          ???
256F-   D4          ???
2570-   D3          ???
2571-   20 CD C1    JSR   $C1CD
2574-   C3          ???
2575-   D2 CF       CMP   ($CF)
2577-   20 D4 CF    JSR   $CFD4
257A-   20 C3 C1    JSR   $C1C3
257D-   CC CC A2    CPY   $A2CC
2580-   AC B8 C4    LDY   $C4B8
2583-   8D A0 DF    STA   $DFA0
2586-   D0 D2       BNE   $255A
2588-   CE D4 A0    DEC   $A0D4
258B-   A2 D4       LDX   #$D4
258D-   C8          INY
258E-   C5 20       CMP   $20
2590-   D2 D7       CMP   ($D7)
2592-   D4          ???
2593-   D3          ???
2594-   20 D2 CF    JSR   $CFD2
2597-   D5 D4       CMP   $D4,X
2599-   C9 CE       CMP   #$CE
259B-   C5 20       CMP   $20
259D-   D4          ???
259E-   CF          ???
259F-   20 CD C1    JSR   $C1CD
25A2-   CB          ???
25A3-   C5 20       CMP   $20
25A5-   D4          ???
25A6-   C8          INY
25A7-   C5 20       CMP   $20
25A9-   A2 AC       LDX   #$AC
25AB-   B8          CLV
25AC-   C4 8D       CPY   $8D
25AE-   A0 DF       LDY   #$DF
25B0-   D0 D2       BNE   $2584
25B2-   CE D4 A0    DEC   $A0D4
25B5-   A2 C1       LDX   #$C1
25B7-   D0 D0       BNE   $2589
25B9-   D2 CF       CMP   ($CF)
25BB-   D0 D2       BNE   $258F
25BD-   C9 C1       CMP   #$C1
25BF-   D4          ???
25C0-   C5 20       CMP   $20
25C2-   D2 C5       CMP   ($C5)
25C4-   C1 C4       CMP   ($C4,X)
25C6-   20 CF D2    JSR   $D2CF
25C9-   20 D7 D2    JSR   $D2D7
25CC-   C9 D4       CMP   #$D4
25CE-   C5 20       CMP   $20
25D0-   C3          ???
25D1-   C8          INY
25D2-   C1 CE       CMP   ($CE,X)
25D4-   C7          ???
25D5-   C5 20       CMP   $20
25D7-   D4          ???
25D8-   CF          ???
25D9-   A2 AC       LDX   #$AC
25DB-   B8          CLV
25DC-   C4 8D       CPY   $8D
25DE-   A0 DF       LDY   #$DF
25E0-   D0 D2       BNE   $25B4
25E2-   CE D4 A0    DEC   $A0D4
25E5-   A2 D4       LDX   #$D4
25E7-   C8          INY
25E8-   C5 20       CMP   $20
25EA-   C4 C9       CPY   $C9
25EC-   D3          ???
25ED-   CB          ???
25EE-   AE A2 AC    LDX   $ACA2
25F1-   B8          CLV
25F2-   C4 B8       CPY   $B8
25F4-   C4 8D       CPY   $8D
25F6-   A0 DF       LDY   #$DF
25F8-   D0 D2       BNE   $25CC
25FA-   CE D4 A0    DEC   $A0D4
25FD-   A2 C6       LDX   #$C6
25FF-   CF          ???
2600-   D2 20       CMP   ($20)
2602-   D4          ???
2603-   C8          INY
2604-   C5 20       CMP   $20
2606-   D3          ???
2607-   C1 CB       CMP   ($CB,X)
2609-   C5 20       CMP   $20
260B-   CF          ???
260C-   C6 20       DEC   $20
260E-   D0 CC       BNE   $25DC
2610-   C1 D9       CMP   ($D9,X)
2612-   C9 CE       CMP   #$CE
2614-   C7          ???
2615-   20 C9 D4    JSR   $D4C9
2618-   20 D3 C1    JSR   $C1D3
261B-   C6 C5       DEC   $C5
261D-   AC A2 AC    LDY   $ACA2
2620-   B8          CLV
2621-   C4 8D       CPY   $8D
2623-   A0 DF       LDY   #$DF
2625-   D0 D2       BNE   $25F9
2627-   CE D4 A0    DEC   $A0D4
262A-   A2 D7       LDX   #$D7
262C-   C5 20       CMP   $20
262E-   D7          ???
262F-   CF          ???
2630-   CE A7 D4    DEC   $D4A7
2633-   20 C2 C5    JSR   $C5C2
2636-   20 C4 CF    JSR   $CFC4
2639-   C9 CE       CMP   #$CE
263B-   C7          ???
263C-   20 D4 C8    JSR   $C8D4
263F-   C1 D4       CMP   ($D4,X)
2641-   20 C8 C5    JSR   $C5C8
2644-   D2 C5       CMP   ($C5)
2646-   AD AD D9    LDA   $D9AD
2649-   CF          ???
264A-   D5 20       CMP   $20,X
264C-   C3          ???
264D-   C1 CE       CMP   ($CE,X)
264F-   A2 AC       LDX   #$AC
2651-   B8          CLV
2652-   C4 8D       CPY   $8D
2654-   A0 DF       LDY   #$DF
2656-   D0 D2       BNE   $262A
2658-   CE D4 A0    DEC   $A0D4
265B-   A2 C5       LDX   #$C5
265D-   D8          CLD
265E-   D0 C5       BNE   $2625
2660-   D2 C9       CMP   ($C9)
2662-   CD C5 CE    CMP   $CEC5
2665-   D4          ???
2666-   20 CF CE    JSR   $CECF
2669-   20 D9 CF    JSR   $CFD9
266C-   D5 D2       CMP   $D2,X
266E-   20 CF D7    JSR   $D7CF
2671-   CE 20 D7    DEC   $D720
2674-   C9 D4       CMP   #$D4
2676-   C8          INY
2677-   20 D4 C8    JSR   $C8D4
267A-   C5 D3       CMP   $D3
267C-   C5 20       CMP   $20
267E-   C3          ???
267F-   C1 CC       CMP   ($CC,X)
2681-   CC D3 BB    CPY   $BBD3
2684-   A2 AC       LDX   #$AC
2686-   B8          CLV
2687-   C4 8D       CPY   $8D
2689-   A0 DF       LDY   #$DF
268B-   D0 D2       BNE   $265F
268D-   CE D4 A0    DEC   $A0D4
2690-   A2 D4       LDX   #$D4
2692-   C8          INY
2693-   C1 D4       CMP   ($D4,X)
2695-   20 D7 C1    JSR   $C1D7
2698-   D9 20 C9    CMP   $C920,Y
269B-   C6 20       DEC   $20
269D-   D3          ???
269E-   CF          ???
269F-   CD C5 D4    CMP   $D4C5
26A2-   C8          INY
26A3-   C9 CE       CMP   #$CE
26A5-   C7          ???
26A6-   20 C2 C1    JSR   $C1C2
26A9-   C4 20       CPY   $20
26AB-   C8          INY
26AC-   C1 D0       CMP   ($D0,X)
26AE-   D0 C5       BNE   $2675
26B0-   CE D3 AC    DEC   $ACD3
26B3-   A2 AC       LDX   #$AC
26B5-   B8          CLV
26B6-   C4 8D       CPY   $8D
26B8-   A0 DF       LDY   #$DF
26BA-   D0 D2       BNE   $268E
26BC-   CE D4 A0    DEC   $A0D4
26BF-   A2 C9       LDX   #$C9
26C1-   D4          ???
26C2-   A7          ???
26C3-   D3          ???
26C4-   20 CF CE    JSR   $CECF
26C7-   20 D9 CF    JSR   $CFD9
26CA-   D5 AD       CMP   $AD,X
26CC-   AD CE CF    LDA   $CFCE
26CF-   D4          ???
26D0-   20 CD C5    JSR   $C5CD
26D3-   A1 20       LDA   ($20,X)
26D5-   BA          TSX
26D6-   A9 A2       LDA   #$A2
26D8-   AC B8 C4    LDY   $C4B8
26DB-   B8          CLV
26DC-   C4 B8       CPY   $B8
26DE-   C4 8D       CPY   $8D
26E0-   A0 DF       LDY   #$DF
26E2-   D7          ???
26E3-   C1 C9       CMP   ($C9,X)
26E5-   D4          ???
26E6-   8D AA 8D    STA   $8DAA
26E9-   A0 CA       LDY   #$CA
26EB-   CD D0 A0    CMP   $A0D0
26EE-   D2 C5       CMP   ($C5)
26F0-   C5 CE       CMP   $CE
26F2-   D4          ???
26F3-   D2 D9       CMP   ($D9)
26F5-   8D AA 8D    STA   $8DAA
26F8-   D2 C5       CMP   ($C5)
26FA-   D4          ???
26FB-   CF          ???
26FC-   D2 D4       CMP   ($D4)
26FE-   A0 D3       LDY   #$D3
2700-   D4          ???
2701-   D2 A0       CMP   ($A0)
2703-   A2 C9       LDX   #$C9
2705-   C6 20       DEC   $20
2707-   D9 CF D5    CMP   $D5CF,Y
270A-   20 C1 D2    JSR   $D2C1
270D-   C5 20       CMP   $20
270F-   D2 C9       CMP   ($C9)
2711-   C3          ???
2712-   C8          INY
2713-   AC 20 C1    LDY   $C120
2716-   CE D9 C8    DEC   $C8D9
2719-   CF          ???
271A-   D7          ???
271B-   AE AE AE    LDX   $AEAE
271E-   A2 8D       LDX   #$8D
2720-   AA          TAX
2721-   8D AA E0    STA   $E0AA
2724-   E0 E0       CPX   #$E0
2726-   E0 E0       CPX   #$E0
2728-   E0 E0       CPX   #$E0
272A-   E0 E0       CPX   #$E0
272C-   E0 E0       CPX   #$E0
272E-   E0 E0       CPX   #$E0
2730-   E0 E0       CPX   #$E0
2732-   E0 E0       CPX   #$E0
2734-   E0 E0       CPX   #$E0
2736-   E0 E0       CPX   #$E0
2738-   E0 E0       CPX   #$E0
273A-   E0 E0       CPX   #$E0
273C-   E0 E0       CPX   #$E0
273E-   E0 E0       CPX   #$E0
2740-   E0 AA       CPX   #$AA
2742-   8D AA 20    STA   $20AA
2745-   20 20 20    JSR   $2020
2748-   20 20 20    JSR   $2020
274B-   20 C2 CF    JSR   $CFC2
274E-   D4          ???
274F-   D4          ???
2750-   CF          ???
2751-   CD 20 C9    CMP   $C920
2754-   CE C3 CC    DEC   $CCC3
2757-   D5 C4       CMP   $C4,X
2759-   C5 D3       CMP   $D3
275B-   20 20 20    JSR   $2020
275E-   20 20 20    JSR   $2020
2761-   20 AA 8D    JSR   $8DAA
2764-   AA          TAX
2765-   AC AC AC    LDY   $ACAC
2768-   AC AC AC    LDY   $ACAC
276B-   AC AC AC    LDY   $ACAC
276E-   AC AC AC    LDY   $ACAC
2771-   AC AC AC    LDY   $ACAC
2774-   AC AC AC    LDY   $ACAC
2777-   AC AC AC    LDY   $ACAC
277A-   AC AC AC    LDY   $ACAC
277D-   AC AC AC    LDY   $ACAC
2780-   AC AC AC    LDY   $ACAC
2783-   AA          TAX
2784-   8D AA 8D    STA   $8DAA
2787-   A0 D0       LDY   #$D0
2789-   D5 D4       CMP   $D4,X
278B-   A0 D2       LDY   #$D2
278D-   C5 D1       CMP   $D1
278F-   D5 C9       CMP   $C9,X
2791-   D2 C5       CMP   ($C5)
2793-   C4 AE       CPY   $AE
2795-   CC C9 C2    CPY   $C2C9
2798-   AE CD C9    LDX   $C9CD
279B-   CE 8D AA    DEC   $AA8D
279E-   8D AA AA    STA   $AAAA
27A1-   20 C9 CE    JSR   $CEC9
27A4-   C4 C9       CPY   $C9
27A6-   D6 C9       DEC   $C9,X
27A8-   C4 D5       CPY   $D5
27AA-   C1 CC       CMP   ($CC,X)
27AC-   20 D3 D5    JSR   $D5D3
27AF-   C2          ???
27B0-   D2 CF       CMP   ($CF)
27B2-   D5 D4       CMP   $D4,X
27B4-   C9 CE       CMP   #$CE
27B6-   C5 D3       CMP   $D3
27B8-   8D AA 8D    STA   $8DAA
27BB-   AA          TAX
27BC-   AA          TAX
27BD-   20 C6 C9    JSR   $C9C6
27C0-   CC C5 C9    CPY   $C9C5
27C3-   CF          ???
27C4-   20 D3 D5    JSR   $D5D3
27C7-   C2          ???
27C8-   D2 CF       CMP   ($CF)
27CA-   D5 D4       CMP   $D4,X
27CC-   C9 CE       CMP   #$CE
27CE-   C5 D3       CMP   $D3
27D0-   8D AA 8D    STA   $8DAA
27D3-   A0 D0       LDY   #$D0
27D5-   D5 D4       CMP   $D4,X
27D7-   A0 C2       LDY   #$C2
27D9-   C9 CE       CMP   #$CE
27DB-   CC CF C1    CPY   $C1CF
27DE-   C4 AE       CPY   $AE
27E0-   D3          ???
27E1-   D5 C2       CMP   $C2,X
27E3-   AE CD C9    LDX   $C9CD
27E6-   CE 8D A0    DEC   $A08D
27E9-   D0 D5       BNE   $27C0
27EB-   D4          ???
27EC-   A0 C2       LDY   #$C2
27EE-   C9 CE       CMP   #$CE
27F0-   D3          ???
27F1-   C1 D6       CMP   ($D6,X)
27F3-   C5 AE       CMP   $AE
27F5-   D3          ???
27F6-   D5 C2       CMP   $C2,X
27F8-   AE CD C9    LDX   $C9CD
27FB-   CE 8D A0    DEC   $A08D
27FE-   D0 D5       BNE   $27D5
2800-   D4          ???
2801-   A0 C4       LDY   #$C4
2803-   C9 D3       CMP   #$D3
2805-   CB          ???
2806-   CF          ???
2807-   D0 AE       BNE   $27B7
2809-   D3          ???
280A-   D5 C2       CMP   $C2,X
280C-   AE CD C9    LDX   $C9CD
280F-   CE 8D A0    DEC   $A08D
2812-   D0 D5       BNE   $27E9
2814-   D4          ???
2815-   A0 C4       LDY   #$C4
2817-   CF          ???
2818-   D3          ???
2819-   C3          ???
281A-   CD C4 AE    CMP   $AEC4
281D-   D3          ???
281E-   D5 C2       CMP   $C2,X
2820-   AE CD C9    LDX   $C9CD
2823-   CE 8D A0    DEC   $A08D
2826-   D0 D5       BNE   $27FD
2828-   D4          ???
2829-   A0 C6       LDY   #$C6
282B-   C9 CE       CMP   #$CE
282D-   D0 D5       BNE   $2804
282F-   D4          ???
2830-   AE D3 D5    LDX   $D5D3
2833-   C2          ???
2834-   AE CD C9    LDX   $C9CD
2837-   CE 8D A0    DEC   $A08D
283A-   D0 D5       BNE   $2811
283C-   D4          ???
283D-   A0 C6       LDY   #$C6
283F-   D0 D2       BNE   $2813
2841-   C9 CE       CMP   #$CE
2843-   D4          ???
2844-   AE D3 D5    LDX   $D5D3
2847-   C2          ???
2848-   AE CD C9    LDX   $C9CD
284B-   CE 8D A0    DEC   $A08D
284E-   D0 D5       BNE   $2825
2850-   D4          ???
2851-   A0 C6       LDY   #$C6
2853-   D0 D3       BNE   $2828
2855-   D4          ???
2856-   D2 AE       CMP   ($AE)
2858-   D3          ???
2859-   D5 C2       CMP   $C2,X
285B-   AE CD C9    LDX   $C9CD
285E-   CE 8D AA    DEC   $AA8D
2861-   8D 00 00    STA   $0000
