0901-   AA          TAX
0902-   8D AA E0    STA   $E0AA
0905-   E0 E0       CPX   #$E0
0907-   E0 E0       CPX   #$E0
0909-   E0 E0       CPX   #$E0
090B-   E0 E0       CPX   #$E0
090D-   E0 E0       CPX   #$E0
090F-   E0 E0       CPX   #$E0
0911-   E0 E0       CPX   #$E0
0913-   E0 E0       CPX   #$E0
0915-   E0 E0       CPX   #$E0
0917-   E0 E0       CPX   #$E0
0919-   E0 E0       CPX   #$E0
091B-   E0 E0       CPX   #$E0
091D-   E0 E0       CPX   #$E0
091F-   E0 E0       CPX   #$E0
0921-   E0 AA       CPX   #$AA
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 AD    JSR   $AD20
092C-   BC 20 C3    LDY   $C320,X
092F-   CF          ???
0930-   CD CD CF    CMP   $CFCD
0933-   CE 20 C4    DEC   $C420
0936-   C5 CD       CMP   $CD
0938-   CF          ???
0939-   20 A9 AD    JSR   $ADA9
093C-   20 20 20    JSR   $2020
093F-   20 20 20    JSR   $2020
0942-   20 AA 8D    JSR   $8DAA
0945-   AA          TAX
0946-   20 20 20    JSR   $2020
0949-   20 20 20    JSR   $2020
094C-   20 20 20    JSR   $2020
094F-   20 20 20    JSR   $2020
0952-   20 20 20    JSR   $2020
0955-   20 20 20    JSR   $2020
0958-   20 20 20    JSR   $2020
095B-   20 20 20    JSR   $2020
095E-   20 20 20    JSR   $2020
0961-   20 20 20    JSR   $2020
0964-   AA          TAX
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 D6 C5    JSR   $C5D6
0971-   D2 D3       CMP   ($D3)
0973-   C9 CF       CMP   #$CF
0975-   CE 20 B0    DEC   $B020
0978-   AE B4 AE    LDX   $AEB4
097B-   B0 20       BCS   $099D
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   20 20 20    JSR   $2020
0992-   20 20 20    JSR   $2020
0995-   20 20 20    JSR   $2020
0998-   20 20 20    JSR   $2020
099B-   20 20 20    JSR   $2020
099E-   20 20 20    JSR   $2020
09A1-   20 20 20    JSR   $2020
09A4-   20 20 AA    JSR   $AA20
09A7-   8D AA 20    STA   $20AA
09AA-   20 20 20    JSR   $2020
09AD-   20 20 20    JSR   $2020
09B0-   20 20 B2    JSR   $B220
09B3-   B8          CLV
09B4-   AD C1 D0    LDA   $D0C1
09B7-   D2 AD       CMP   ($AD)
09B9-   B2 B0       LDA   ($B0)
09BB-   B1 B9       LDA   ($B9),Y
09BD-   20 20 20    JSR   $2020
09C0-   20 20 20    JSR   $2020
09C3-   20 20 20    JSR   $2020
09C6-   20 AA 8D    JSR   $8DAA
09C9-   AA          TAX
09CA-   20 20 20    JSR   $2020
09CD-   20 20 20    JSR   $2020
09D0-   20 20 20    JSR   $2020
09D3-   20 20 20    JSR   $2020
09D6-   20 20 20    JSR   $2020
09D9-   20 20 20    JSR   $2020
09DC-   20 20 20    JSR   $2020
09DF-   20 20 20    JSR   $2020
09E2-   20 20 20    JSR   $2020
09E5-   20 20 20    JSR   $2020
09E8-   AA          TAX
09E9-   8D AA 20    STA   $20AA
09EC-   20 20 20    JSR   $2020
09EF-   20 20 20    JSR   $2020
09F2-   CE C1 D4    DEC   $D4C1
09F5-   C8          INY
09F6-   C1 CE       CMP   ($CE,X)
09F8-   20 C4 AE    JSR   $AEC4
09FB-   20 D2 C9    JSR   $C9D2
09FE-   C7          ???
09FF-   C7          ???
0A00-   D3          ???
0A01-   20 20 20    JSR   $2020
0A04-   20 20 20    JSR   $2020
0A07-   20 20 AA    JSR   $AA20
0A0A-   8D AA 20    STA   $20AA
0A0D-   20 20 CE    JSR   $CE20
0A10-   C1 D4       CMP   ($D4,X)
0A12-   C8          INY
0A13-   C1 CE       CMP   ($CE,X)
0A15-   AE D2 C9    LDX   $C9D2
0A18-   C7          ???
0A19-   C7          ???
0A1A-   D3          ???
0A1B-   C0 CF       CPY   #$CF
0A1D-   D5 D4       CMP   $D4,X
0A1F-   CC CF CF    CPY   $CFCF
0A22-   CB          ???
0A23-   AE C3 CF    LDX   $CFC3
0A26-   CD 20 20    CMP   $2020
0A29-   20 AA 8D    JSR   $8DAA
0A2C-   AA          TAX
0A2D-   AC AC AC    LDY   $ACAC
0A30-   AC AC AC    LDY   $ACAC
0A33-   AC AC AC    LDY   $ACAC
0A36-   AC AC AC    LDY   $ACAC
0A39-   AC AC AC    LDY   $ACAC
0A3C-   AC AC AC    LDY   $ACAC
0A3F-   AC AC AC    LDY   $ACAC
0A42-   AC AC AC    LDY   $ACAC
0A45-   AC AC AC    LDY   $ACAC
0A48-   AC AC AC    LDY   $ACAC
0A4B-   AA          TAX
0A4C-   8D AA 8D    STA   $8DAA
0A4F-   AA          TAX
0A50-   AA          TAX
0A51-   20 C1 D3    JSR   $D3C1
0A54-   D3          ???
0A55-   C5 CD       CMP   $CD
0A57-   C2          ???
0A58-   CC C5 D2    CPY   $D2C5
0A5B-   20 C4 C9    JSR   $C9C4
0A5E-   D2 C5       CMP   ($C5)
0A60-   C3          ???
0A61-   D4          ???
0A62-   C9 D6       CMP   #$D6
0A64-   C5 D3       CMP   $D3
0A66-   8D AA 8D    STA   $8DAA
0A69-   A0 CC       LDY   #$CC
0A6B-   D3          ???
0A6C-   D4          ???
0A6D-   A0 CF       LDY   #$CF
0A6F-   C6 C6       DEC   $C6
0A71-   8D A0 C3    STA   $C3A0
0A74-   D9 C3 A0    CMP   $A0C3,Y
0A77-   C1 D6       CMP   ($D6,X)
0A79-   C5 8D       CMP   $8D
0A7B-   A0 C5       LDY   #$C5
0A7D-   D8          CLD
0A7E-   D0 A0       BNE   $0A20
0A80-   CF          ???
0A81-   C6 C6       DEC   $C6
0A83-   8D A0 D4    STA   $D4A0
0A86-   D2 A0       CMP   ($A0)
0A88-   CF          ???
0A89-   CE 8D A0    DEC   $A08D
0A8C-   C4 D3       CPY   $D3
0A8E-   CB          ???
0A8F-   A0 C1       LDY   #$C1
0A91-   D0 D0       BNE   $0A63
0A93-   CC C5 C3    CPY   $C3C5
0A96-   C8          INY
0A97-   CF          ???
0A98-   D0 AE       BNE   $0A48
0A9A-   C4 C5       CPY   $C5
0A9C-   CD CF 8D    CMP   $8DCF
0A9F-   A0 CF       LDY   #$CF
0AA1-   C2          ???
0AA2-   CA          DEX
0AA3-   A0 A4       LDY   #$A4
0AA5-   C2          ???
0AA6-   C6 C5       DEC   $C5
0AA8-   B0 8D       BCS   $0A37
0AAA-   A0 CF       LDY   #$CF
0AAC-   D2 C7       CMP   ($C7)
0AAE-   A0 A4       LDY   #$A4
0AB0-   B6 B0       LDX   $B0,Y
0AB2-   B0 B0       BCS   $0A64
0AB4-   8D AA 8D    STA   $8DAA
0AB7-   AA          TAX
0AB8-   E0 E0       CPX   #$E0
0ABA-   E0 E0       CPX   #$E0
0ABC-   E0 E0       CPX   #$E0
0ABE-   E0 E0       CPX   #$E0
0AC0-   E0 E0       CPX   #$E0
0AC2-   E0 E0       CPX   #$E0
0AC4-   E0 E0       CPX   #$E0
0AC6-   E0 E0       CPX   #$E0
0AC8-   E0 E0       CPX   #$E0
0ACA-   E0 E0       CPX   #$E0
0ACC-   E0 E0       CPX   #$E0
0ACE-   E0 E0       CPX   #$E0
0AD0-   E0 E0       CPX   #$E0
0AD2-   E0 E0       CPX   #$E0
0AD4-   E0 E0       CPX   #$E0
0AD6-   AA          TAX
0AD7-   8D AA 20    STA   $20AA
0ADA-   20 D4 CF    JSR   $CFD4
0ADD-   D0 20       BNE   $0AFF
0ADF-   C9 CE       CMP   #$CE
0AE1-   C3          ???
0AE2-   CC D5 C4    CPY   $C4D5
0AE5-   C5 D3       CMP   $D3
0AE7-   20 A8 C8    JSR   $C8A8
0AEA-   CF          ???
0AEB-   CF          ???
0AEC-   CB          ???
0AED-   D3          ???
0AEE-   AC CD C1    LDY   $C1CD
0AF1-   C3          ???
0AF2-   D2 CF       CMP   ($CF)
0AF4-   D3          ???
0AF5-   A9 20       LDA   #$20
0AF7-   AA          TAX
0AF8-   8D AA AC    STA   $ACAA
0AFB-   AC AC AC    LDY   $ACAC
0AFE-   AC AC AC    LDY   $ACAC
0B01-   AC AC AC    LDY   $ACAC
0B04-   AC AC AC    LDY   $ACAC
0B07-   AC AC AC    LDY   $ACAC
0B0A-   AC AC AC    LDY   $ACAC
0B0D-   AC AC AC    LDY   $ACAC
0B10-   AC AC AC    LDY   $ACAC
0B13-   AC AC AC    LDY   $ACAC
0B16-   AC AC AA    LDY   $AAAC
0B19-   8D AA 8D    STA   $8DAA
0B1C-   A0 D0       LDY   #$D0
0B1E-   D5 D4       CMP   $D4,X
0B20-   A0 CD       LDY   #$CD
0B22-   C9 CE       CMP   #$CE
0B24-   AE C8 C5    LDX   $C5C8
0B27-   C1 C4       CMP   ($C4,X)
0B29-   AE D2 C5    LDX   $C5D2
0B2C-   D1 D5       CMP   ($D5),Y
0B2E-   C9 D2       CMP   #$D2
0B30-   C5 C4       CMP   $C4
0B32-   8D A0 D0    STA   $D0A0
0B35-   D5 D4       CMP   $D4,X
0B37-   A0 CD       LDY   #$CD
0B39-   C9 CE       CMP   #$CE
0B3B-   AE C8 CF    LDX   $CFC8
0B3E-   CF          ???
0B3F-   CB          ???
0B40-   D3          ???
0B41-   AE D3 D4    LDX   $D4D3
0B44-   C4 C9       CPY   $C9
0B46-   CF          ???
0B47-   8D A0 D5    STA   $D5A0
0B4A-   D3          ???
0B4B-   C5 A0       CMP   $A0
0B4D-   CD C9 CE    CMP   $CEC9
0B50-   AE CD C1    LDX   $C1CD
0B53-   C3          ???
0B54-   AE D2 C5    LDX   $C5D2
0B57-   D1 D5       CMP   ($D5),Y
0B59-   C9 D2       CMP   #$D2
0B5B-   C5 C4       CMP   $C4
0B5D-   8D A0 D5    STA   $D5A0
0B60-   D3          ???
0B61-   C5 A0       CMP   $A0
0B63-   CD C9 CE    CMP   $CEC9
0B66-   AE CD C1    LDX   $C1CD
0B69-   C3          ???
0B6A-   AE D3 D4    LDX   $D4D3
0B6D-   C4 C9       CPY   $C9
0B6F-   CF          ???
0B70-   8D A0 D5    STA   $D5A0
0B73-   D3          ???
0B74-   C5 A0       CMP   $A0
0B76-   CD C1 C3    CMP   $C3C1
0B79-   AE C9 C6    LDX   $C6C9
0B7C-   D3          ???
0B7D-   D4          ???
0B7E-   D2 D5       CMP   ($D5)
0B80-   C3          ???
0B81-   D4          ???
0B82-   8D A0 D5    STA   $D5A0
0B85-   D3          ???
0B86-   C5 A0       CMP   $A0
0B88-   CD C1 C3    CMP   $C3C1
0B8B-   AE CC CF    LDX   $CFCC
0B8E-   CF          ???
0B8F-   D0 D3       BNE   $0B64
0B91-   D4          ???
0B92-   D2 D5       CMP   ($D5)
0B94-   C3          ???
0B95-   D4          ???
0B96-   8D A0 CC    STA   $CCA0
0B99-   D3          ???
0B9A-   D4          ???
0B9B-   A0 CF       LDY   #$CF
0B9D-   CE 8D A0    DEC   $A08D
0BA0-   D5 D3       CMP   $D3,X
0BA2-   C5 A0       CMP   $A0
0BA4-   CD C1 C3    CMP   $C3C1
0BA7-   AE C1 D0    LDX   $D0C1
0BAA-   D0 CC       BNE   $0B78
0BAC-   C5 C3       CMP   $C3
0BAE-   C8          INY
0BAF-   CF          ???
0BB0-   D0 8D       BNE   $0B3F
0BB2-   AA          TAX
0BB3-   8D AA E0    STA   $E0AA
0BB6-   E0 E0       CPX   #$E0
0BB8-   E0 E0       CPX   #$E0
0BBA-   E0 E0       CPX   #$E0
0BBC-   E0 E0       CPX   #$E0
0BBE-   E0 E0       CPX   #$E0
0BC0-   E0 E0       CPX   #$E0
0BC2-   E0 E0       CPX   #$E0
0BC4-   E0 E0       CPX   #$E0
0BC6-   E0 E0       CPX   #$E0
0BC8-   E0 E0       CPX   #$E0
0BCA-   E0 E0       CPX   #$E0
0BCC-   E0 E0       CPX   #$E0
0BCE-   E0 E0       CPX   #$E0
0BD0-   E0 E0       CPX   #$E0
0BD2-   E0 AA       CPX   #$AA
0BD4-   8D AA 20    STA   $20AA
0BD7-   20 20 20    JSR   $2020
0BDA-   20 20 D0    JSR   $D020
0BDD-   D2 CF       CMP   ($CF)
0BDF-   C7          ???
0BE0-   D2 C1       CMP   ($C1)
0BE2-   CD 20 CD    CMP   $CD20
0BE5-   C1 C9       CMP   ($C9,X)
0BE7-   CE 20 C2    DEC   $C220
0BEA-   CF          ???
0BEB-   C4 D9       CPY   $D9
0BED-   20 20 20    JSR   $2020
0BF0-   20 20 20    JSR   $2020
0BF3-   20 AA 8D    JSR   $8DAA
0BF6-   AA          TAX
0BF7-   AC AC AC    LDY   $ACAC
0BFA-   AC AC AC    LDY   $ACAC
0BFD-   AC AC AC    LDY   $ACAC
0C00-   AC AC AC    LDY   $ACAC
0C03-   AC AC AC    LDY   $ACAC
0C06-   AC AC AC    LDY   $ACAC
0C09-   AC AC AC    LDY   $ACAC
0C0C-   AC AC AC    LDY   $ACAC
0C0F-   AC AC AC    LDY   $ACAC
0C12-   AC AC AC    LDY   $ACAC
0C15-   AA          TAX
0C16-   8D AA 8D    STA   $8DAA
0C19-   A0 C0       LDY   #$C0
0C1B-   C7          ???
0C1C-   CF          ???
0C1D-   D4          ???
0C1E-   CF          ???
0C1F-   A0 C5       LDY   #$C5
0C21-   CE C4 D6    DEC   $D6C4
0C24-   C1 D2       CMP   ($D2,X)
0C26-   D3          ???
0C27-   8D AA 8D    STA   $8DAA
0C2A-   DD D6 C1    CMP   $C1D6,X
0C2D-   D2 B1       CMP   ($B1)
0C2F-   A0 C4       LDY   #$C4
0C31-   D3          ???
0C32-   A0 B2       LDY   #$B2
0C34-   8D DD D6    STA   $D6DD
0C37-   C1 D2       CMP   ($D2,X)
0C39-   B2 A0       LDA   ($A0)
0C3B-   C4 D3       CPY   $D3
0C3D-   A0 B2       LDY   #$B2
0C3F-   8D DD D3    STA   $D3DD
0C42-   D4          ???
0C43-   D2 C9       CMP   ($C9)
0C45-   CE C7 B1    DEC   $B1C7
0C48-   A0 C4       LDY   #$C4
0C4A-   D3          ???
0C4B-   A0 B2       LDY   #$B2
0C4D-   B5 B5       LDA   $B5,X
0C4F-   AC B0 8D    LDY   $8DB0
0C52-   AA          TAX
0C53-   8D C5 CE    STA   $CEC5
0C56-   C4 D6       CPY   $D6
0C58-   C1 D2       CMP   ($D2,X)
0C5A-   D3          ???
0C5B-   8D AA 8D    STA   $8DAA
0C5E-   A0 C0       LDY   #$C0
0C60-   C8          INY
0C61-   CF          ???
0C62-   CD C5 8D    CMP   $8DC5
0C65-   A0 C0       LDY   #$C0
0C67-   C9 CE       CMP   #$CE
0C69-   D6 C5       DEC   $C5,X
0C6B-   D2 D4       CMP   ($D4)
0C6D-   8D A0 C0    STA   $C0A0
0C70-   D0 D2       BNE   $0C44
0C72-   C9 CE       CMP   #$CE
0C74-   D4          ???
0C75-   A0 A2       LDY   #$A2
0C77-   C1 D0       CMP   ($D0,X)
0C79-   D0 CC       BNE   $0C47
0C7B-   C5 C3       CMP   $C3
0C7D-   C8          INY
0C7E-   CF          ???
0C7F-   D0 20       BNE   $0CA1
0C81-   CD C1 C3    CMP   $C3C1
0C84-   D2 CF       CMP   ($CF)
0C86-   20 CC C9    JSR   $C9CC
0C89-   C2          ???
0C8A-   D2 C1       CMP   ($C1)
0C8C-   D2 D9       CMP   ($D9)
0C8E-   A2 AC       LDX   #$AC
0C90-   B8          CLV
0C91-   C4 B8       CPY   $B8
0C93-   C4 8D       CPY   $8D
0C95-   A0 C0       LDY   #$C0
0C97-   CE CF D2    DEC   $D2CF
0C9A-   CD C1 CC    CMP   $CCC1
0C9D-   8D A0 C0    STA   $C0A0
0CA0-   D0 D2       BNE   $0C74
0CA2-   C9 CE       CMP   #$CE
0CA4-   D4          ???
0CA5-   A0 A2       LDY   #$A2
0CA7-   D4          ???
0CA8-   C8          INY
0CA9-   C9 D3       CMP   #$D3
0CAB-   20 C9 D3    JSR   $D3C9
0CAE-   20 C1 20    JSR   $20C1
0CB1-   C4 C5       CPY   $C5
0CB3-   CD CF 20    CMP   $20CF
0CB6-   C6 CF       DEC   $CF
0CB8-   D2 20       CMP   ($20)
0CBA-   D4          ???
0CBB-   C8          INY
0CBC-   C5 A2       CMP   $A2
0CBE-   AC B8 C4    LDY   $C4B8
0CC1-   8D A0 C0    STA   $C0A0
0CC4-   D0 D2       BNE   $0C98
0CC6-   C9 CE       CMP   #$CE
0CC8-   D4          ???
0CC9-   A0 A2       LDY   #$A2
0CCB-   C1 D0       CMP   ($D0,X)
0CCD-   D0 CC       BNE   $0C9B
0CCF-   C5 C3       CMP   $C3
0CD1-   C8          INY
0CD2-   CF          ???
0CD3-   D0 20       BNE   $0CF5
0CD5-   CD C1 C3    CMP   $C3C1
0CD8-   D2 CF       CMP   ($CF)
0CDA-   20 CC C9    JSR   $C9CC
0CDD-   C2          ???
0CDE-   D2 C1       CMP   ($C1)
0CE0-   D2 D9       CMP   ($D9)
0CE2-   AC 20 D7    LDY   $D720
0CE5-   C8          INY
0CE6-   C9 C3       CMP   #$C3
0CE8-   C8          INY
0CE9-   A2 AC       LDX   #$AC
0CEB-   B8          CLV
0CEC-   C4 8D       CPY   $8D
0CEE-   A0 C0       LDY   #$C0
0CF0-   D0 D2       BNE   $0CC4
0CF2-   C9 CE       CMP   #$CE
0CF4-   D4          ???
0CF5-   A0 A2       LDY   #$A2
0CF7-   D3          ???
0CF8-   CF          ???
0CF9-   CD C5 D7    CMP   $D7C5
0CFC-   C8          INY
0CFD-   C1 D4       CMP   ($D4,X)
0CFF-   20 C5 CD    JSR   $CDC5
0D02-   D5 CC       CMP   $CC,X
0D04-   C1 D4       CMP   ($D4,X)
0D06-   C5 D3       CMP   $D3
0D08-   20 D4 C8    JSR   $C8D4
0D0B-   C5 20       CMP   $20
0D0D-   C8          INY
0D0E-   C9 C7       CMP   #$C7
0D10-   C8          INY
0D11-   C5 D2       CMP   $D2
0D13-   AD A2 AC    LDA   $ACA2
0D16-   B8          CLV
0D17-   C4 8D       CPY   $8D
0D19-   A0 C0       LDY   #$C0
0D1B-   D0 D2       BNE   $0CEF
0D1D-   C9 CE       CMP   #$CE
0D1F-   D4          ???
0D20-   A0 A2       LDY   #$A2
0D22-   CC C5 D6    CPY   $D6C5
0D25-   C5 CC       CMP   $CC
0D27-   20 D3 D4    JSR   $D4D3
0D2A-   D2 D5       CMP   ($D5)
0D2C-   C3          ???
0D2D-   D4          ???
0D2E-   D5 D2       CMP   $D2,X
0D30-   C5 20       CMP   $20
0D32-   CF          ???
0D33-   C6 20       DEC   $20
0D35-   C1 D0       CMP   ($D0,X)
0D37-   D0 CC       BNE   $0D05
0D39-   C5 D3       CMP   $D3
0D3B-   CF          ???
0D3C-   C6 D4       DEC   $D4
0D3E-   20 C3 CF    JSR   $CFC3
0D41-   C4 C9       CPY   $C9
0D43-   CE C7 A2    DEC   $A2C7
0D46-   AC B8 C4    LDY   $C4B8
0D49-   8D A0 C0    STA   $C0A0
0D4C-   D0 D2       BNE   $0D20
0D4E-   C9 CE       CMP   #$CE
0D50-   D4          ???
0D51-   A0 A2       LDY   #$A2
0D53-   D4          ???
0D54-   CF          ???
0D55-   20 C5 C1    JSR   $C1C5
0D58-   D3          ???
0D59-   C5 20       CMP   $20
0D5B-   C1 20       CMP   ($20,X)
0D5D-   D4          ???
0D5E-   D2 C1       CMP   ($C1)
0D60-   CE D3 C9    DEC   $C9D3
0D63-   D4          ???
0D64-   C9 CF       CMP   #$CF
0D66-   CE 20 C2    DEC   $C220
0D69-   C5 D4       CMP   $D4
0D6B-   D7          ???
0D6C-   C5 C5       CMP   $C5
0D6E-   CE 20 C8    DEC   $C820
0D71-   C9 C7       CMP   #$C7
0D73-   C8          INY
0D74-   C5 D2       CMP   $D2
0D76-   AD A2 AC    LDA   $ACA2
0D79-   B8          CLV
0D7A-   C4 8D       CPY   $8D
0D7C-   A0 C0       LDY   #$C0
0D7E-   D0 D2       BNE   $0D52
0D80-   C9 CE       CMP   #$CE
0D82-   D4          ???
0D83-   A0 A2       LDY   #$A2
0D85-   CC C5 D6    CPY   $D6C5
0D88-   C5 CC       CMP   $CC
0D8A-   20 CC C1    JSR   $C1CC
0D8D-   CE C7 D5    DEC   $D5C7
0D90-   C1 C7       CMP   ($C7,X)
0D92-   C5 D3       CMP   $D3
0D94-   20 CC C9    JSR   $C9CC
0D97-   CB          ???
0D98-   C5 20       CMP   $20
0D9A-   C1 D0       CMP   ($D0,X)
0D9C-   D0 CC       BNE   $0D6A
0D9E-   C5 D3       CMP   $D3
0DA0-   CF          ???
0DA1-   C6 D4       DEC   $D4
0DA3-   20 C2 C1    JSR   $C1C2
0DA6-   D3          ???
0DA7-   C9 C3       CMP   #$C3
0DA9-   A2 AC       LDX   #$AC
0DAB-   B8          CLV
0DAC-   C4 8D       CPY   $8D
0DAE-   A0 C0       LDY   #$C0
0DB0-   D0 D2       BNE   $0D84
0DB2-   C9 CE       CMP   #$CE
0DB4-   D4          ???
0DB5-   A0 A2       LDY   #$A2
0DB7-   D4          ???
0DB8-   CF          ???
0DB9-   20 B6 B5    JSR   $B5B6
0DBC-   B0 B2       BCS   $0D70
0DBE-   20 C1 D3    JSR   $D3C1
0DC1-   D3          ???
0DC2-   C5 CD       CMP   $CD
0DC4-   C2          ???
0DC5-   CC D9 AE    CPY   $AED9
0DC8-   A2 AC       LDX   #$AC
0DCA-   B8          CLV
0DCB-   C4 B8       CPY   $B8
0DCD-   C4 8D       CPY   $8D
0DCF-   A0 C0       LDY   #$C0
0DD1-   C7          ???
0DD2-   C5 D4       CMP   $D4
0DD4-   8D A0 C0    STA   $C0A0
0DD7-   D0 D2       BNE   $0DAB
0DD9-   C9 CE       CMP   #$CE
0DDB-   D4          ???
0DDC-   A0 A2       LDY   #$A2
0DDE-   CF          ???
0DDF-   C2          ???
0DE0-   D6 C9       DEC   $C9,X
0DE2-   CF          ???
0DE3-   D5 D3       CMP   $D3,X
0DE5-   CC D9 AC    CPY   $ACD9
0DE8-   20 C9 D4    JSR   $D4C9
0DEB-   20 C9 D3    JSR   $D3C9
0DEE-   20 D2 C1    JSR   $C1D2
0DF1-   D4          ???
0DF2-   C8          INY
0DF3-   C5 D2       CMP   $D2
0DF5-   20 C9 CD    JSR   $CDC9
0DF8-   D0 CF       BNE   $0DC9
0DFA-   D3          ???
0DFB-   D3          ???
0DFC-   C9 C2       CMP   #$C2
0DFE-   CC C5 A2    CPY   $A2C5
0E01-   AC B8 C4    LDY   $C4B8
0E04-   8D A0 C0    STA   $C0A0
0E07-   D0 D2       BNE   $0DDB
0E09-   C9 CE       CMP   #$CE
0E0B-   D4          ???
0E0C-   A0 A2       LDY   #$A2
0E0E-   D4          ???
0E0F-   CF          ???
0E10-   20 D3 C9    JSR   $C9D3
0E13-   CD D5 CC    CMP   $CCD5
0E16-   C1 D4       CMP   ($D4,X)
0E18-   C5 20       CMP   $20
0E1A-   C1 D0       CMP   ($D0,X)
0E1C-   D0 CC       BNE   $0DEA
0E1E-   C5 D3       CMP   $D3
0E20-   CF          ???
0E21-   C6 D4       DEC   $D4
0E23-   20 C2 C1    JSR   $C1C2
0E26-   D3          ???
0E27-   C9 C3       CMP   #$C3
0E29-   20 D7 C9    JSR   $C9D7
0E2C-   D4          ???
0E2D-   C8          INY
0E2E-   A2 AC       LDX   #$AC
0E30-   B8          CLV
0E31-   C4 8D       CPY   $8D
0E33-   A0 C0       LDY   #$C0
0E35-   D0 D2       BNE   $0E09
0E37-   C9 CE       CMP   #$CE
0E39-   D4          ???
0E3A-   A0 A2       LDY   #$A2
0E3C-   B1 B0       LDA   ($B0),Y
0E3E-   B0 A5       BCS   $0DE5
0E40-   20 C1 C3    JSR   $C3C1
0E43-   C3          ???
0E44-   D5 D2       CMP   $D2,X
0E46-   C1 C3       CMP   ($C3,X)
0E48-   D9 20 D7    CMP   $D720,Y
0E4B-   C9 D4       CMP   #$D4
0E4D-   C8          INY
0E4E-   CF          ???
0E4F-   D5 D4       CMP   $D4,X
0E51-   20 D3 C9    JSR   $C9D3
0E54-   CD D0 CC    CMP   $CCD0
0E57-   D9 20 D7    CMP   $D720,Y
0E5A-   D2 C9       CMP   ($C9)
0E5C-   D4          ???
0E5D-   C9 CE       CMP   #$CE
0E5F-   C7          ???
0E60-   A2 AC       LDX   #$AC
0E62-   B8          CLV
0E63-   C4 8D       CPY   $8D
0E65-   A0 C0       LDY   #$C0
0E67-   D0 D2       BNE   $0E3B
0E69-   C9 CE       CMP   #$CE
0E6B-   D4          ???
0E6C-   A0 A2       LDY   #$A2
0E6E-   D4          ???
0E6F-   C8          INY
0E70-   C5 20       CMP   $20
0E72-   C9 CE       CMP   #$CE
0E74-   D4          ???
0E75-   C5 D2       CMP   $D2
0E77-   D0 D2       BNE   $0E4B
0E79-   C5 D4       CMP   $D4
0E7B-   C5 D2       CMP   $D2
0E7D-   20 C6 D2    JSR   $D2C6
0E80-   CF          ???
0E81-   CD 20 D4    CMP   $D420
0E84-   C8          INY
0E85-   C5 20       CMP   $20
0E87-   C7          ???
0E88-   D2 CF       CMP   ($CF)
0E8A-   D5 CE       CMP   $CE,X
0E8C-   C4 20       CPY   $20
0E8E-   D5 D0       CMP   $D0,X
0E90-   AC A2 AC    LDY   $ACA2
0E93-   B8          CLV
0E94-   C4 8D       CPY   $8D
0E96-   A0 C0       LDY   #$C0
0E98-   D0 D2       BNE   $0E6C
0E9A-   C9 CE       CMP   #$CE
0E9C-   D4          ???
0E9D-   A0 A2       LDY   #$A2
0E9F-   D7          ???
0EA0-   C8          INY
0EA1-   C9 C3       CMP   #$C3
0EA3-   C8          INY
0EA4-   20 D7 CF    JSR   $CFD7
0EA7-   D5 CC       CMP   $CC,X
0EA9-   C4 20       CPY   $20
0EAB-   C4 C5       CPY   $C5
0EAD-   C6 C5       DEC   $C5
0EAF-   C1 D4       CMP   ($D4,X)
0EB1-   20 D4 C8    JSR   $C8D4
0EB4-   C5 20       CMP   $20
0EB6-   D0 D5       BNE   $0E8D
0EB8-   D2 D0       CMP   ($D0)
0EBA-   CF          ???
0EBB-   D3          ???
0EBC-   C5 20       CMP   $20
0EBE-   C9 CE       CMP   #$CE
0EC0-   20 D4 C8    JSR   $C8D4
0EC3-   C5 A2       CMP   $A2
0EC5-   AC B8 C4    LDY   $C4B8
0EC8-   8D A0 C0    STA   $C0A0
0ECB-   D0 D2       BNE   $0E9F
0ECD-   C9 CE       CMP   #$CE
0ECF-   D4          ???
0ED0-   A0 A2       LDY   #$A2
0ED2-   C6 C9       DEC   $C9
0ED4-   D2 D3       CMP   ($D3)
0ED6-   D4          ???
0ED7-   20 D0 CC    JSR   $CCD0
0EDA-   C1 C3       CMP   ($C3,X)
0EDC-   C5 AE       CMP   $AE
0EDE-   20 D4 C8    JSR   $C8D4
0EE1-   C9 D3       CMP   #$D3
0EE3-   20 CC C9    JSR   $C9CC
0EE6-   C2          ???
0EE7-   D2 C1       CMP   ($C1)
0EE9-   D2 D9       CMP   ($D9)
0EEB-   20 C1 C9    JSR   $C9C1
0EEE-   CD D3 20    CMP   $20D3
0EF1-   D4          ???
0EF2-   CF          ???
0EF3-   20 A2 AC    JSR   $ACA2
0EF6-   B8          CLV
0EF7-   C4 8D       CPY   $8D
0EF9-   A0 C0       LDY   #$C0
0EFB-   D0 D2       BNE   $0ECF
0EFD-   C9 CE       CMP   #$CE
0EFF-   D4          ???
0F00-   A0 A2       LDY   #$A2
0F02-   C8          INY
0F03-   C1 D2       CMP   ($D2,X)
0F05-   CE C5 D3    DEC   $D3C5
0F08-   D3          ???
0F09-   20 C8 C9    JSR   $C9C8
0F0C-   C7          ???
0F0D-   C8          INY
0F0E-   C5 D2       CMP   $D2
0F10-   AD CC C5    LDA   $C5CC
0F13-   D6 C5       DEC   $C5,X
0F15-   CC 20 C6    CPY   $C620
0F18-   D5 CE       CMP   $CE,X
0F1A-   C3          ???
0F1B-   D4          ???
0F1C-   C9 CF       CMP   #$CF
0F1E-   CE C1 CC    DEC   $CCC1
0F21-   C9 D4       CMP   #$D4
0F23-   D9 20 A2    CMP   $A220,Y
0F26-   AC B8 C4    LDY   $C4B8
0F29-   8D A0 C0    STA   $C0A0
0F2C-   D0 D2       BNE   $0F00
0F2E-   C9 CE       CMP   #$CE
0F30-   D4          ???
0F31-   A0 A2       LDY   #$A2
0F33-   D7          ???
0F34-   C8          INY
0F35-   C9 CC       CMP   #$CC
0F37-   C5 20       CMP   $20
0F39-   D3          ???
0F3A-   D4          ???
0F3B-   C9 CC       CMP   #$CC
0F3D-   CC 20 D2    CPY   $D220
0F40-   C5 D1       CMP   $D1
0F42-   D5 C9       CMP   $C9,X
0F44-   D2 C9       CMP   ($C9)
0F46-   CE C7 20    DEC   $20C7
0F49-   D4          ???
0F4A-   C8          INY
0F4B-   C5 20       CMP   $20
0F4D-   D5 D3       CMP   $D3,X
0F4F-   C5 D2       CMP   $D2
0F51-   20 D4 CF    JSR   $CFD4
0F54-   20 CC C5    JSR   $C5CC
0F57-   C1 D2       CMP   ($D2,X)
0F59-   CE A2 AC    DEC   $ACA2
0F5C-   B8          CLV
0F5D-   C4 8D       CPY   $8D
0F5F-   A0 C0       LDY   #$C0
0F61-   D0 D2       BNE   $0F35
0F63-   C9 CE       CMP   #$CE
0F65-   D4          ???
0F66-   A0 A2       LDY   #$A2
0F68-   D4          ???
0F69-   C8          INY
0F6A-   C5 20       CMP   $20
0F6C-   C2          ???
0F6D-   C1 D3       CMP   ($D3,X)
0F6F-   C9 C3       CMP   #$C3
0F71-   D3          ???
0F72-   20 CF C6    JSR   $C6CF
0F75-   20 C1 D3    JSR   $D3C1
0F78-   D3          ???
0F79-   C5 CD       CMP   $CD
0F7B-   C2          ???
0F7C-   CC D9 AE    CPY   $AED9
0F7F-   20 D4 C8    JSR   $C8D4
0F82-   C5 CE       CMP   $CE
0F84-   AC 20 CF    LDY   $CF20
0F87-   CE C3 C5    DEC   $C5C3
0F8A-   A2 AC       LDX   #$AC
0F8C-   B8          CLV
0F8D-   C4 8D       CPY   $8D
0F8F-   A0 C0       LDY   #$C0
0F91-   D0 D2       BNE   $0F65
0F93-   C9 CE       CMP   #$CE
0F95-   D4          ???
0F96-   A0 A2       LDY   #$A2
0F98-   D4          ???
0F99-   C8          INY
0F9A-   C5 20       CMP   $20
0F9C-   D5 D3       CMP   $D3,X
0F9E-   C5 D2       CMP   $D2
0FA0-   20 C9 D3    JSR   $D3C9
0FA3-   20 C3 CF    JSR   $CFC3
0FA6-   CD C6 CF    CMP   $CFC6
0FA9-   D2 D4       CMP   ($D4)
0FAB-   C1 C2       CMP   ($C2,X)
0FAD-   CC C5 20    CPY   $20C5
0FB0-   C5 CE       CMP   $CE
0FB2-   CF          ???
0FB3-   D5 C7       CMP   $C7,X
0FB5-   C8          INY
0FB6-   AC 20 D4    LDY   $D420
0FB9-   C8          INY
0FBA-   C5 D9       CMP   $D9
0FBC-   A2 AC       LDX   #$AC
0FBE-   B8          CLV
0FBF-   C4 8D       CPY   $8D
0FC1-   A0 C0       LDY   #$C0
0FC3-   D0 D2       BNE   $0F97
0FC5-   C9 CE       CMP   #$CE
0FC7-   D4          ???
0FC8-   A0 A2       LDY   #$A2
0FCA-   C1 D2       CMP   ($D2,X)
0FCC-   C5 20       CMP   $20
0FCE-   C6 D2       DEC   $D2
0FD0-   C5 C5       CMP   $C5
0FD2-   20 D4 CF    JSR   $CFD4
0FD5-   20 C5 D8    JSR   $D8C5
0FD8-   D0 CC       BNE   $0FA6
0FDA-   CF          ???
0FDB-   D2 C5       CMP   ($C5)
0FDD-   20 D4 C8    JSR   $C8D4
0FE0-   C5 20       CMP   $20
0FE2-   C9 CE       CMP   #$CE
0FE4-   CE C5 D2    DEC   $D2C5
0FE7-   20 D7 CF    JSR   $CFD7
0FEA-   D2 CB       CMP   ($CB)
0FEC-   C9 CE       CMP   #$CE
0FEE-   C7          ???
0FEF-   D3          ???
0FF0-   A2 AC       LDX   #$AC
0FF2-   B8          CLV
0FF3-   C4 8D       CPY   $8D
0FF5-   A0 C0       LDY   #$C0
0FF7-   D0 D2       BNE   $0FCB
0FF9-   C9 CE       CMP   #$CE
0FFB-   D4          ???
0FFC-   A0 A2       LDY   #$A2
0FFE-   CF          ???
0FFF-   C6 20       DEC   $20
1001-   C8          INY
1002-   CF          ???
1003-   D7          ???
1004-   20 C5 C1    JSR   $C1C5
1007-   C3          ???
1008-   C8          INY
1009-   20 C3 CF    JSR   $CFC3
100C-   CD CD C1    CMP   $C1CD
100F-   CE C4 20    DEC   $20C4
1012-   D7          ???
1013-   CF          ???
1014-   D2 CB       CMP   ($CB)
1016-   D3          ???
1017-   AC 20 D3    LDY   $D320
101A-   CC CF D7    CPY   $D7CF
101D-   CC D9 A2    CPY   $A2D9
1020-   AC B8 C4    LDY   $C4B8
1023-   8D A0 C0    STA   $C0A0
1026-   D0 D2       BNE   $0FFA
1028-   C9 CE       CMP   #$CE
102A-   D4          ???
102B-   A0 A2       LDY   #$A2
102D-   D2 C5       CMP   ($C5)
102F-   D0 CC       BNE   $0FFD
1031-   C1 C3       CMP   ($C3,X)
1033-   C9 CE       CMP   #$CE
1035-   C7          ???
1036-   20 D4 C8    JSR   $C8D4
1039-   C5 20       CMP   $20
103B-   CD C1 C3    CMP   $C3C1
103E-   D2 CF       CMP   ($CF)
1040-   D3          ???
1041-   20 D7 C9    JSR   $C9D7
1044-   D4          ???
1045-   C8          INY
1046-   20 CD CF    JSR   $CFCD
1049-   D2 C5       CMP   ($C5)
104B-   20 A2 AC    JSR   $ACA2
104E-   B8          CLV
104F-   C4 8D       CPY   $8D
1051-   A0 C0       LDY   #$C0
1053-   D0 D2       BNE   $1027
1055-   C9 CE       CMP   #$CE
1057-   D4          ???
1058-   A0 A2       LDY   #$A2
105A-   C5 C6       CMP   $C6
105C-   C6 C9       DEC   $C9
105E-   C3          ???
105F-   C9 C5       CMP   #$C5
1061-   CE D4 20    DEC   $20D4
1064-   CC CF D7    CPY   $D7CF
1067-   20 CC C5    JSR   $C5CC
106A-   D6 C5       DEC   $C5,X
106C-   CC 20 C3    CPY   $C320
106F-   CF          ???
1070-   C4 C5       CPY   $C5
1072-   20 CF C6    JSR   $C6CF
1075-   20 D4 C8    JSR   $C8D4
1078-   C5 C9       CMP   $C9
107A-   D2 20       CMP   ($20)
107C-   CF          ???
107D-   D7          ???
107E-   CE AE A2    DEC   $A2AE
1081-   AC B8 C4    LDY   $C4B8
1084-   8D A0 C0    STA   $C0A0
1087-   C7          ???
1088-   C5 D4       CMP   $D4
108A-   8D A0 DF    STA   $DFA0
108D-   D0 D2       BNE   $1061
108F-   CE A0 A2    DEC   $A2A0
1092-   20 A2 AC    JSR   $ACA2
1095-   B8          CLV
1096-   C4 B8       CPY   $B8
1098-   C4 8D       CPY   $8D
109A-   A0 C0       LDY   #$C0
109C-   C8          INY
109D-   CF          ???
109E-   CD C5 8D    CMP   $8DC5
10A1-   A0 C0       LDY   #$C0
10A3-   D0 D2       BNE   $1077
10A5-   C9 CE       CMP   #$CE
10A7-   D4          ???
10A8-   A0 A2       LDY   #$A2
10AA-   C3          ???
10AB-   D5 D2       CMP   $D2,X
10AD-   D2 C5       CMP   ($C5)
10AF-   CE D4 CC    DEC   $CCD4
10B2-   D9 AC 20    CMP   $20AC,Y
10B5-   D4          ???
10B6-   C8          INY
10B7-   C5 20       CMP   $20
10B9-   C1 D0       CMP   ($D0,X)
10BB-   D0 CC       BNE   $1089
10BD-   C5 C3       CMP   $C3
10BF-   C8          INY
10C0-   CF          ???
10C1-   D0 20       BNE   $10E3
10C3-   CC C9 C2    CPY   $C2C9
10C6-   D2 C1       CMP   ($C1)
10C8-   D2 D9       CMP   ($D9)
10CA-   A2 AC       LDX   #$AC
10CC-   B8          CLV
10CD-   C4 8D       CPY   $8D
10CF-   A0 C0       LDY   #$C0
10D1-   D0 D2       BNE   $10A5
10D3-   C9 CE       CMP   #$CE
10D5-   D4          ???
10D6-   A0 A2       LDY   #$A2
10D8-   CF          ???
10D9-   C6 C6       DEC   $C6
10DB-   C5 D2       CMP   $D2
10DD-   D3          ???
10DE-   20 D4 C8    JSR   $C8D4
10E1-   C5 20       CMP   $20
10E3-   C6 CF       DEC   $CF
10E5-   CC CC CF    CPY   $CFCC
10E8-   D7          ???
10E9-   C9 CE       CMP   #$CE
10EB-   C7          ???
10EC-   20 C3 CF    JSR   $CFC3
10EF-   CD CD C1    CMP   $C1CD
10F2-   CE C4 D3    DEC   $D3C4
10F5-   BA          TSX
10F6-   A2 AC       LDX   #$AC
10F8-   B8          CLV
10F9-   C4 B8       CPY   $B8
10FB-   C4 8D       CPY   $8D
10FD-   A0 C0       LDY   #$C0
10FF-   D0 D2       BNE   $10D3
1101-   C9 CE       CMP   #$CE
1103-   D4          ???
1104-   A0 A2       LDY   #$A2
1106-   C0 C3       CPY   #$C3
1108-   C1 CC       CMP   ($CC,X)
110A-   CC 20 20    CPY   $2020
110D-   20 20 20    JSR   $2020
1110-   C0 C4       CPY   #$C4
1112-   C9 CD       CMP   #$CD
1114-   B1 20       LDA   ($20),Y
1116-   20 20 20    JSR   $2020
1119-   20 C0 C4    JSR   $C4C0
111C-   C9 CD       CMP   #$CD
111E-   B2 A2       LDA   ($A2)
1120-   AC B8 C4    LDY   $C4B8
1123-   8D A0 C0    STA   $C0A0
1126-   D0 D2       BNE   $10FA
1128-   C9 CE       CMP   #$CE
112A-   D4          ???
112B-   A0 A2       LDY   #$A2
112D-   C0 C5       CPY   #$C5
112F-   CE C4 20    DEC   $20C4
1132-   20 20 20    JSR   $2020
1135-   20 20 C0    JSR   $C020    reserved [cassette]
1138-   C5 CE       CMP   $CE
113A-   C4 C9       CPY   $C9
113C-   C6 20       DEC   $20
113E-   20 20 20    JSR   $2020
1141-   C0 C6       CPY   #$C6
1143-   CC C1 D3    CPY   $D3C1
1146-   C8          INY
1147-   A2 AC       LDX   #$AC
1149-   B8          CLV
114A-   C4 8D       CPY   $8D
114C-   A0 C0       LDY   #$C0
114E-   D0 D2       BNE   $1122
1150-   C9 CE       CMP   #$CE
1152-   D4          ???
1153-   A0 A2       LDY   #$A2
1155-   C0 C6       CPY   #$C6
1157-   CF          ???
1158-   D2 20       CMP   ($20)
115A-   20 20 20    JSR   $2020
115D-   20 20 C0    JSR   $C020    reserved [cassette]
1160-   C7          ???
1161-   C5 D4       CMP   $D4
1163-   20 20 20    JSR   $2020
1166-   20 20 20    JSR   $2020
1169-   C0 C7       CPY   #$C7
116B-   CF          ???
116C-   D3          ???
116D-   D5 C2       CMP   $C2,X
116F-   A2 AC       LDX   #$AC
1171-   B8          CLV
1172-   C4 8D       CPY   $8D
1174-   A0 C0       LDY   #$C0
1176-   D0 D2       BNE   $114A
1178-   C9 CE       CMP   #$CE
117A-   D4          ???
117B-   A0 A2       LDY   #$A2
117D-   C0 C7       CPY   #$C7
117F-   CF          ???
1180-   D4          ???
1181-   CF          ???
1182-   20 20 20    JSR   $2020
1185-   20 20 C0    JSR   $C020    reserved [cassette]
1188-   C8          INY
1189-   CF          ???
118A-   CD C5 20    CMP   $20C5
118D-   20 20 20    JSR   $2020
1190-   20 C0 C8    JSR   $C8C0
1193-   D4          ???
1194-   C1 C2       CMP   ($C2,X)
1196-   A2 AC       LDX   #$AC
1198-   B8          CLV
1199-   C4 8D       CPY   $8D
119B-   A0 C0       LDY   #$C0
119D-   D0 D2       BNE   $1171
119F-   C9 CE       CMP   #$CE
11A1-   D4          ???
11A2-   A0 A2       LDY   #$A2
11A4-   C0 C9       CPY   #$C9
11A6-   C6 C7       DEC   $C7
11A8-   CF          ???
11A9-   D4          ???
11AA-   CF          ???
11AB-   20 20 20    JSR   $2020
11AE-   C0 C9       CPY   #$C9
11B0-   C6 D3       DEC   $D3
11B2-   D5 C2       CMP   $C2,X
11B4-   20 20 20    JSR   $2020
11B7-   20 C0 C9    JSR   $C9C0
11BA-   C6 D4       DEC   $D4
11BC-   C8          INY
11BD-   C5 CE       CMP   $CE
11BF-   A2 AC       LDX   #$AC
11C1-   B8          CLV
11C2-   C4 8D       CPY   $8D
11C4-   A0 C0       LDY   #$C0
11C6-   D0 D2       BNE   $119A
11C8-   C9 CE       CMP   #$CE
11CA-   D4          ???
11CB-   A0 A2       LDY   #$A2
11CD-   C0 C9       CPY   #$C9
11CF-   CE D0 D5    DEC   $D5D0
11D2-   D4          ???
11D3-   20 20 20    JSR   $2020
11D6-   20 C0 C9    JSR   $C9C0
11D9-   CE D6 C5    DEC   $C5D6
11DC-   D2 D4       CMP   ($D4)
11DE-   20 20 20    JSR   $2020
11E1-   C0 CE       CPY   #$CE
11E3-   C5 D8       CMP   $D8
11E5-   D4          ???
11E6-   A2 AC       LDX   #$AC
11E8-   B8          CLV
11E9-   C4 8D       CPY   $8D
11EB-   A0 C0       LDY   #$C0
11ED-   D0 D2       BNE   $11C1
11EF-   C9 CE       CMP   #$CE
11F1-   D4          ???
11F2-   A0 A2       LDY   #$A2
11F4-   C0 CE       CPY   #$CE
11F6-   CF          ???
11F7-   D2 CD       CMP   ($CD)
11F9-   C1 CC       CMP   ($CC,X)
11FB-   20 20 20    JSR   $2020
11FE-   C0 D0       CPY   #$D0
1200-   C4 CC       CPY   $CC
1202-   20 20 20    JSR   $2020
1205-   20 20 20    JSR   $2020
1208-   C0 D0       CPY   #$D0
120A-   C5 C5       CMP   $C5
120C-   CB          ???
120D-   A2 AC       LDX   #$AC
120F-   B8          CLV
1210-   C4 8D       CPY   $8D
1212-   A0 C0       LDY   #$C0
1214-   D0 D2       BNE   $11E8
1216-   C9 CE       CMP   #$CE
1218-   D4          ???
1219-   A0 A2       LDY   #$A2
121B-   C0 D0       CPY   #$D0
121D-   CF          ???
121E-   CB          ???
121F-   C5 20       CMP   $20
1221-   20 20 20    JSR   $2020
1224-   20 C0 D0    JSR   $D0C0
1227-   CF          ???
1228-   D3          ???
1229-   20 20 20    JSR   $2020
122C-   20 20 20    JSR   $2020
122F-   C0 D0       CPY   #$D0
1231-   D2 C9       CMP   ($C9)
1233-   CE D4 A2    DEC   $A2D4
1236-   AC B8 C4    LDY   $C4B8
1239-   8D A0 C0    STA   $C0A0
123C-   D0 D2       BNE   $1210
123E-   C9 CE       CMP   #$CE
1240-   D4          ???
1241-   A0 A2       LDY   #$A2
1243-   C0 D0       CPY   #$D0
1245-   CF          ???
1246-   D0 20       BNE   $1268
1248-   20 20 20    JSR   $2020
124B-   20 20 C0    JSR   $C020    reserved [cassette]
124E-   D2 C5       CMP   ($C5)
1250-   D4          ???
1251-   D5 D2       CMP   $D2,X
1253-   CE 20 20    DEC   $2020
1256-   20 C0 CF    JSR   $CFC0
1259-   CE C5 D2    DEC   $D2C5
125C-   D2 A2       CMP   ($A2)
125E-   AC B8 C4    LDY   $C4B8
1261-   8D A0 C0    STA   $C0A0
1264-   D0 D2       BNE   $1238
1266-   C9 CE       CMP   #$CE
1268-   D4          ???
1269-   A0 A2       LDY   #$A2
126B-   C0 D3       CPY   #$D3
126D-   D4          ???
126E-   CF          ???
126F-   D0 20       BNE   $1291
1271-   20 20 20    JSR   $2020
1274-   20 C0 D4    JSR   $D4C0
1277-   C5 D8       CMP   $D8
1279-   D4          ???
127A-   20 20 20    JSR   $2020
127D-   20 20 C0    JSR   $C020    reserved [cassette]
1280-   D6 D4       DEC   $D4,X
1282-   C1 C2       CMP   ($C2,X)
1284-   A2 AC       LDX   #$AC
1286-   B8          CLV
1287-   C4 B8       CPY   $B8
1289-   C4 8D       CPY   $8D
128B-   A0 C0       LDY   #$C0
128D-   C7          ???
128E-   C5 D4       CMP   $D4
1290-   8D A0 C0    STA   $C0A0
1293-   D0 D2       BNE   $1267
1295-   C9 CE       CMP   #$CE
1297-   D4          ???
1298-   A0 A2       LDY   #$A2
129A-   D4          ???
129B-   C8          INY
129C-   C5 20       CMP   $20
129E-   C6 CF       DEC   $CF
12A0-   CC CC CF    CPY   $CFCC
12A3-   D7          ???
12A4-   C9 CE       CMP   #$CE
12A6-   C7          ???
12A7-   20 D7 C9    JSR   $C9D7
12AA-   CC CC 20    CPY   $20CC
12AD-   C2          ???
12AE-   C5 20       CMP   $20
12B0-   C1 C4       CMP   ($C4,X)
12B2-   C4 C5       CPY   $C5
12B4-   C4 20       CPY   $20
12B6-   C9 CE       CMP   #$CE
12B8-   A2 AC       LDX   #$AC
12BA-   B8          CLV
12BB-   C4 8D       CPY   $8D
12BD-   A0 C0       LDY   #$C0
12BF-   D0 D2       BNE   $1293
12C1-   C9 CE       CMP   #$CE
12C3-   D4          ???
12C4-   A0 A2       LDY   #$A2
12C6-   D4          ???
12C7-   C8          INY
12C8-   C5 20       CMP   $20
12CA-   CE C5 C1    DEC   $C1C5
12CD-   D2 20       CMP   ($20)
12CF-   C6 D5       DEC   $D5
12D1-   D4          ???
12D2-   D5 D2       CMP   $D2,X
12D4-   C5 AC       CMP   $AC
12D6-   20 CF CE    JSR   $CECF
12D9-   C3          ???
12DA-   C5 20       CMP   $20
12DC-   CE C5 C3    DEC   $C3C5
12DF-   C5 D3       CMP   $D3
12E1-   D3          ???
12E2-   C1 D2       CMP   ($D2,X)
12E4-   D9 A2 AC    CMP   $ACA2,Y
12E7-   B8          CLV
12E8-   C4 8D       CPY   $8D
12EA-   A0 C0       LDY   #$C0
12EC-   D0 D2       BNE   $12C0
12EE-   C9 CE       CMP   #$CE
12F0-   D4          ???
12F1-   A0 A2       LDY   #$A2
12F3-   D3          ???
12F4-   D5 C2       CMP   $C2,X
12F6-   D2 CF       CMP   ($CF)
12F8-   D5 D4       CMP   $D4,X
12FA-   C9 CE       CMP   #$CE
12FC-   C5 D3       CMP   $D3
12FE-   20 C1 D2    JSR   $D2C1
1301-   C5 20       CMP   $20
1303-   C3          ???
1304-   CF          ???
1305-   CD D0 CC    CMP   $CCD0
1308-   C5 D4       CMP   $D4
130A-   C5 BA       CMP   $BA
130C-   A2 AC       LDX   #$AC
130E-   B8          CLV
130F-   C4 B8       CPY   $B8
1311-   C4 8D       CPY   $8D
1313-   A0 C0       LDY   #$C0
1315-   D0 D2       BNE   $12E9
1317-   C9 CE       CMP   #$CE
1319-   D4          ???
131A-   A0 A2       LDY   #$A2
131C-   C0 C3       CPY   #$C3
131E-   CF          ???
131F-   CC CF D2    CPY   $D2CF
1322-   20 20 20    JSR   $2020
1325-   20 C0 C7    JSR   $C7C0
1328-   D2 20       CMP   ($20)
132A-   20 20 20    JSR   $2020
132D-   20 20 20    JSR   $2020
1330-   C0 C8       CPY   #$C8
1332-   C3          ???
1333-   CF          ???
1334-   CC CF D2    CPY   $D2CF
1337-   A2 AC       LDX   #$AC
1339-   B8          CLV
133A-   C4 8D       CPY   $8D
133C-   A0 C0       LDY   #$C0
133E-   D0 D2       BNE   $1312
1340-   C9 CE       CMP   #$CE
1342-   D4          ???
1343-   A0 A2       LDY   #$A2
1345-   C0 C8       CPY   #$C8
1347-   C7          ???
1348-   D2 20       CMP   ($20)
134A-   20 20 20    JSR   $2020
134D-   20 20 C0    JSR   $C020    reserved [cassette]
1350-   C8          INY
1351-   C7          ???
1352-   D2 B2       CMP   ($B2)
1354-   20 20 20    JSR   $2020
1357-   20 20 C0    JSR   $C020    reserved [cassette]
135A-   C8          INY
135B-   CC C9 CE    CPY   $CEC9
135E-   A2 AC       LDX   #$AC
1360-   B8          CLV
1361-   C4 8D       CPY   $8D
1363-   A0 C0       LDY   #$C0
1365-   D0 D2       BNE   $1339
1367-   C9 CE       CMP   #$CE
1369-   D4          ???
136A-   A0 A2       LDY   #$A2
136C-   C0 C8       CPY   #$C8
136E-   D0 CC       BNE   $133C
1370-   CF          ???
1371-   D4          ???
1372-   20 20 20    JSR   $2020
1375-   20 C0 D0    JSR   $D0C0
1378-   CC CF D4    CPY   $D4CF
137B-   20 20 20    JSR   $2020
137E-   20 20 C0    JSR   $C020    reserved [cassette]
1381-   D6 CC       DEC   $CC,X
1383-   C9 CE       CMP   #$CE
1385-   A2 AC       LDX   #$AC
1387-   B8          CLV
1388-   C4 B8       CPY   $B8
138A-   C4 8D       CPY   $8D
138C-   AA          TAX
138D-   8D AA AA    STA   $AAAA
1390-   20 CD C1    JSR   $C1CD
1393-   D4          ???
1394-   C8          INY
1395-   AC 20 C1    LDY   $C120
1398-   D2 D2       CMP   ($D2)
139A-   C1 D9       CMP   ($D9,X)
139C-   20 C7 C5    JSR   $C5C7
139F-   D4          ???
13A0-   AC 20 C1    LDY   $C120
13A3-   D2 D2       CMP   ($D2)
13A5-   C1 D9       CMP   ($D9,X)
13A7-   20 D0 D5    JSR   $D5D0
13AA-   D4          ???
13AB-   AC 20 C4    LDY   $C420
13AE-   CF          ???
13AF-   D3          ???
13B0-   20 C3 CF    JSR   $CFC3
13B3-   CD CD C1    CMP   $C1CD
13B6-   CE C4 AC    DEC   $ACC4
13B9-   8D AA AA    STA   $AAAA
13BC-   20 C8 C9    JSR   $C9C8
13BF-   D2 C5       CMP   ($C5)
13C1-   D3          ???
13C2-   20 CC C9    JSR   $C9CC
13C5-   CE C5 AC    DEC   $ACC5
13C8-   20 C5 CC    JSR   $CCC5
13CB-   D3          ???
13CC-   C5 AC       CMP   $AC
13CE-   20 D0 D2    JSR   $D2D0
13D1-   C9 CE       CMP   #$CE
13D3-   D4          ???
13D4-   20 CE D5    JSR   $D5CE
13D7-   CD C2 C5    CMP   $C5C2
13DA-   D2 AC       CMP   ($AC)
13DC-   20 CC C5    JSR   $C5CC
13DF-   C6 D4       DEC   $D4
13E1-   A4 AC       LDY   $AC
13E3-   8D AA AA    STA   $AAAA
13E6-   20 D2 C9    JSR   $C9D2
13E9-   C7          ???
13EA-   C8          INY
13EB-   D4          ???
13EC-   A4 AC       LDY   $AC
13EE-   20 CD C9    JSR   $C9CD
13F1-   C4 A4       CPY   $A4
13F3-   AC 20 C3    LDY   $C320
13F6-   C8          INY
13F7-   D2 A4       CMP   ($A4)
13F9-   AC 20 C1    LDY   $C120
13FC-   D3          ???
13FD-   C3          ???
13FE-   AC 20 AE    LDY   $AE20
1401-   AE AE 8D    LDX   $8DAE
1404-   AA          TAX
1405-   8D A0 C0    STA   $C0A0
1408-   C7          ???
1409-   C5 D4       CMP   $D4
140B-   8D A0 C0    STA   $C0A0
140E-   C5 CE       CMP   $CE
1410-   C4 8D       CPY   $8D
1412-   AA          TAX
1413-   8D AA E0    STA   $E0AA
1416-   E0 E0       CPX   #$E0
1418-   E0 E0       CPX   #$E0
141A-   E0 E0       CPX   #$E0
141C-   E0 E0       CPX   #$E0
141E-   E0 E0       CPX   #$E0
1420-   E0 E0       CPX   #$E0
1422-   E0 E0       CPX   #$E0
1424-   E0 E0       CPX   #$E0
1426-   E0 E0       CPX   #$E0
1428-   E0 E0       CPX   #$E0
142A-   E0 E0       CPX   #$E0
142C-   E0 E0       CPX   #$E0
142E-   E0 E0       CPX   #$E0
1430-   E0 E0       CPX   #$E0
1432-   E0 AA       CPX   #$AA
1434-   8D AA 20    STA   $20AA
1437-   20 20 20    JSR   $2020
143A-   20 20 20    JSR   $2020
143D-   20 C2 CF    JSR   $CFC2
1440-   D4          ???
1441-   D4          ???
1442-   CF          ???
1443-   CD 20 C9    CMP   $C920
1446-   CE C3 CC    DEC   $CCC3
1449-   D5 C4       CMP   $C4,X
144B-   C5 D3       CMP   $D3
144D-   20 20 20    JSR   $2020
1450-   20 20 20    JSR   $2020
1453-   20 AA 8D    JSR   $8DAA
1456-   AA          TAX
1457-   AC AC AC    LDY   $ACAC
145A-   AC AC AC    LDY   $ACAC
145D-   AC AC AC    LDY   $ACAC
1460-   AC AC AC    LDY   $ACAC
1463-   AC AC AC    LDY   $ACAC
1466-   AC AC AC    LDY   $ACAC
1469-   AC AC AC    LDY   $ACAC
146C-   AC AC AC    LDY   $ACAC
146F-   AC AC AC    LDY   $ACAC
1472-   AC AC AC    LDY   $ACAC
1475-   AA          TAX
1476-   8D AA 8D    STA   $8DAA
1479-   AA          TAX
147A-   AA          TAX
147B-   20 C2 CF    JSR   $CFC2
147E-   D4          ???
147F-   D4          ???
1480-   CF          ???
1481-   CD 20 C9    CMP   $C920
1484-   CE C3 CC    DEC   $CCC3
1487-   D5 C4       CMP   $C4,X
1489-   C5 D3       CMP   $D3
148B-   8D AA 8D    STA   $8DAA
148E-   A0 CC       LDY   #$CC
1490-   D3          ???
1491-   D4          ???
1492-   A0 CF       LDY   #$CF
1494-   C6 C6       DEC   $C6
1496-   8D A0 D0    STA   $D0A0
1499-   D5 D4       CMP   $D4,X
149B-   A0 CD       LDY   #$CD
149D-   C9 CE       CMP   #$CE
149F-   AE CC C9    LDX   $C9CC
14A2-   C2          ???
14A3-   AE D2 C5    LDX   $C5D2
14A6-   D1 D5       CMP   ($D5),Y
14A8-   C9 D2       CMP   #$D2
14AA-   C5 C4       CMP   $C4
14AC-   8D A0 D0    STA   $D0A0
14AF-   D5 D4       CMP   $D4,X
14B1-   A0 CD       LDY   #$CD
14B3-   C9 CE       CMP   #$CE
14B5-   AE D3 D5    LDX   $D5D3
14B8-   C2          ???
14B9-   AE D8 D0    LDX   $D0D8
14BC-   D2 C9       CMP   ($C9)
14BE-   CE D4 8D    DEC   $8DD4
14C1-   A0 D0       LDY   #$D0
14C3-   D5 D4       CMP   $D4,X
14C5-   A0 CD       LDY   #$CD
14C7-   C9 CE       CMP   #$CE
14C9-   AE D3 D5    LDX   $D5D3
14CC-   C2          ???
14CD-   AE C4 D0    LDX   $D0C4
14D0-   D2 C9       CMP   ($C9)
14D2-   CE D4 8D    DEC   $8DD4
14D5-   AA          TAX
14D6-   8D A0 CC    STA   $CCA0
14D9-   D3          ???
14DA-   D4          ???
14DB-   A0 CF       LDY   #$CF
14DD-   CE 8D 00    DEC   $008D
