0901-   AA          TAX
0902-   8D AA E0    STA   $E0AA
0905-   E0 E0       CPX   #$E0
0907-   E0 E0       CPX   #$E0
0909-   E0 E0       CPX   #$E0
090B-   E0 E0       CPX   #$E0
090D-   E0 E0       CPX   #$E0
090F-   E0 E0       CPX   #$E0
0911-   E0 E0       CPX   #$E0
0913-   E0 E0       CPX   #$E0
0915-   E0 E0       CPX   #$E0
0917-   E0 E0       CPX   #$E0
0919-   E0 E0       CPX   #$E0
091B-   E0 E0       CPX   #$E0
091D-   E0 E0       CPX   #$E0
091F-   E0 E0       CPX   #$E0
0921-   E0 AA       CPX   #$AA
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 AD    JSR   $AD20
092C-   BC 20 C3    LDY   $C320,X
092F-   CF          ???
0930-   CD CD CF    CMP   $CFCD
0933-   CE 20 C4    DEC   $C420
0936-   C5 CD       CMP   $CD
0938-   CF          ???
0939-   20 A9 AD    JSR   $ADA9
093C-   20 20 20    JSR   $2020
093F-   20 20 20    JSR   $2020
0942-   20 AA 8D    JSR   $8DAA
0945-   AA          TAX
0946-   20 20 20    JSR   $2020
0949-   20 20 20    JSR   $2020
094C-   20 20 20    JSR   $2020
094F-   20 20 20    JSR   $2020
0952-   20 20 20    JSR   $2020
0955-   20 20 20    JSR   $2020
0958-   20 20 20    JSR   $2020
095B-   20 20 20    JSR   $2020
095E-   20 20 20    JSR   $2020
0961-   20 20 20    JSR   $2020
0964-   AA          TAX
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 D6 C5    JSR   $C5D6
0971-   D2 D3       CMP   ($D3)
0973-   C9 CF       CMP   #$CF
0975-   CE 20 B0    DEC   $B020
0978-   AE B4 AE    LDX   $AEB4
097B-   B0 20       BCS   $099D
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   20 20 20    JSR   $2020
0992-   20 20 20    JSR   $2020
0995-   20 20 20    JSR   $2020
0998-   20 20 20    JSR   $2020
099B-   20 20 20    JSR   $2020
099E-   20 20 20    JSR   $2020
09A1-   20 20 20    JSR   $2020
09A4-   20 20 AA    JSR   $AA20
09A7-   8D AA 20    STA   $20AA
09AA-   20 20 20    JSR   $2020
09AD-   20 20 20    JSR   $2020
09B0-   20 20 B2    JSR   $B220
09B3-   B8          CLV
09B4-   AD C1 D0    LDA   $D0C1
09B7-   D2 AD       CMP   ($AD)
09B9-   B2 B0       LDA   ($B0)
09BB-   B1 B9       LDA   ($B9),Y
09BD-   20 20 20    JSR   $2020
09C0-   20 20 20    JSR   $2020
09C3-   20 20 20    JSR   $2020
09C6-   20 AA 8D    JSR   $8DAA
09C9-   AA          TAX
09CA-   20 20 20    JSR   $2020
09CD-   20 20 20    JSR   $2020
09D0-   20 20 20    JSR   $2020
09D3-   20 20 20    JSR   $2020
09D6-   20 20 20    JSR   $2020
09D9-   20 20 20    JSR   $2020
09DC-   20 20 20    JSR   $2020
09DF-   20 20 20    JSR   $2020
09E2-   20 20 20    JSR   $2020
09E5-   20 20 20    JSR   $2020
09E8-   AA          TAX
09E9-   8D AA 20    STA   $20AA
09EC-   20 20 20    JSR   $2020
09EF-   20 20 20    JSR   $2020
09F2-   CE C1 D4    DEC   $D4C1
09F5-   C8          INY
09F6-   C1 CE       CMP   ($CE,X)
09F8-   20 C4 AE    JSR   $AEC4
09FB-   20 D2 C9    JSR   $C9D2
09FE-   C7          ???
09FF-   C7          ???
0A00-   D3          ???
0A01-   20 20 20    JSR   $2020
0A04-   20 20 20    JSR   $2020
0A07-   20 20 AA    JSR   $AA20
0A0A-   8D AA 20    STA   $20AA
0A0D-   20 20 CE    JSR   $CE20
0A10-   C1 D4       CMP   ($D4,X)
0A12-   C8          INY
0A13-   C1 CE       CMP   ($CE,X)
0A15-   AE D2 C9    LDX   $C9D2
0A18-   C7          ???
0A19-   C7          ???
0A1A-   D3          ???
0A1B-   C0 CF       CPY   #$CF
0A1D-   D5 D4       CMP   $D4,X
0A1F-   CC CF CF    CPY   $CFCF
0A22-   CB          ???
0A23-   AE C3 CF    LDX   $CFC3
0A26-   CD 20 20    CMP   $2020
0A29-   20 AA 8D    JSR   $8DAA
0A2C-   AA          TAX
0A2D-   AC AC AC    LDY   $ACAC
0A30-   AC AC AC    LDY   $ACAC
0A33-   AC AC AC    LDY   $ACAC
0A36-   AC AC AC    LDY   $ACAC
0A39-   AC AC AC    LDY   $ACAC
0A3C-   AC AC AC    LDY   $ACAC
0A3F-   AC AC AC    LDY   $ACAC
0A42-   AC AC AC    LDY   $ACAC
0A45-   AC AC AC    LDY   $ACAC
0A48-   AC AC AC    LDY   $ACAC
0A4B-   AA          TAX
0A4C-   8D AA 8D    STA   $8DAA
0A4F-   AA          TAX
0A50-   AA          TAX
0A51-   20 C1 D3    JSR   $D3C1
0A54-   D3          ???
0A55-   C5 CD       CMP   $CD
0A57-   C2          ???
0A58-   CC C5 D2    CPY   $D2C5
0A5B-   20 C4 C9    JSR   $C9C4
0A5E-   D2 C5       CMP   ($C5)
0A60-   C3          ???
0A61-   D4          ???
0A62-   C9 D6       CMP   #$D6
0A64-   C5 D3       CMP   $D3
0A66-   8D AA 8D    STA   $8DAA
0A69-   A0 C3       LDY   #$C3
0A6B-   D9 C3 A0    CMP   $A0C3,Y
0A6E-   C1 D6       CMP   ($D6,X)
0A70-   C5 8D       CMP   $8D
0A72-   A0 C5       LDY   #$C5
0A74-   D8          CLD
0A75-   D0 A0       BNE   $0A17
0A77-   CF          ???
0A78-   CE CC D9    DEC   $D9CC
0A7B-   8D A0 D4    STA   $D4A0
0A7E-   D2 A0       CMP   ($A0)
0A80-   CF          ???
0A81-   CE 8D A0    DEC   $A08D
0A84-   C4 D3       CPY   $D3
0A86-   CB          ???
0A87-   A0 D3       LDY   #$D3
0A89-   D4          ???
0A8A-   D2 D5       CMP   ($D5)
0A8C-   C3          ???
0A8D-   D4          ???
0A8E-   D5 D2       CMP   $D2,X
0A90-   C5 D3       CMP   $D3
0A92-   AE C4 C5    LDX   $C5C4
0A95-   CD CF 8D    CMP   $8DCF
0A98-   A0 CF       LDY   #$CF
0A9A-   C2          ???
0A9B-   CA          DEX
0A9C-   A0 A4       LDY   #$A4
0A9E-   C2          ???
0A9F-   C6 C5       DEC   $C5
0AA1-   B0 8D       BCS   $0A30
0AA3-   A0 CF       LDY   #$CF
0AA5-   D2 C7       CMP   ($C7)
0AA7-   A0 A4       LDY   #$A4
0AA9-   B6 B0       LDX   $B0,Y
0AAB-   B0 B0       BCS   $0A5D
0AAD-   8D AA 8D    STA   $8DAA
0AB0-   AA          TAX
0AB1-   E0 E0       CPX   #$E0
0AB3-   E0 E0       CPX   #$E0
0AB5-   E0 E0       CPX   #$E0
0AB7-   E0 E0       CPX   #$E0
0AB9-   E0 E0       CPX   #$E0
0ABB-   E0 E0       CPX   #$E0
0ABD-   E0 E0       CPX   #$E0
0ABF-   E0 E0       CPX   #$E0
0AC1-   E0 E0       CPX   #$E0
0AC3-   E0 E0       CPX   #$E0
0AC5-   E0 E0       CPX   #$E0
0AC7-   E0 E0       CPX   #$E0
0AC9-   E0 E0       CPX   #$E0
0ACB-   E0 E0       CPX   #$E0
0ACD-   E0 E0       CPX   #$E0
0ACF-   AA          TAX
0AD0-   8D AA 20    STA   $20AA
0AD3-   20 D4 CF    JSR   $CFD4
0AD6-   D0 20       BNE   $0AF8
0AD8-   C9 CE       CMP   #$CE
0ADA-   C3          ???
0ADB-   CC D5 C4    CPY   $C4D5
0ADE-   C5 D3       CMP   $D3
0AE0-   20 A8 C8    JSR   $C8A8
0AE3-   CF          ???
0AE4-   CF          ???
0AE5-   CB          ???
0AE6-   D3          ???
0AE7-   AC CD C1    LDY   $C1CD
0AEA-   C3          ???
0AEB-   D2 CF       CMP   ($CF)
0AED-   D3          ???
0AEE-   A9 20       LDA   #$20
0AF0-   AA          TAX
0AF1-   8D AA AC    STA   $ACAA
0AF4-   AC AC AC    LDY   $ACAC
0AF7-   AC AC AC    LDY   $ACAC
0AFA-   AC AC AC    LDY   $ACAC
0AFD-   AC AC AC    LDY   $ACAC
0B00-   AC AC AC    LDY   $ACAC
0B03-   AC AC AC    LDY   $ACAC
0B06-   AC AC AC    LDY   $ACAC
0B09-   AC AC AC    LDY   $ACAC
0B0C-   AC AC AC    LDY   $ACAC
0B0F-   AC AC AA    LDY   $AAAC
0B12-   8D AA 8D    STA   $8DAA
0B15-   A0 D0       LDY   #$D0
0B17-   D5 D4       CMP   $D4,X
0B19-   A0 CD       LDY   #$CD
0B1B-   C9 CE       CMP   #$CE
0B1D-   AE C8 C5    LDX   $C5C8
0B20-   C1 C4       CMP   ($C4,X)
0B22-   AE D2 C5    LDX   $C5D2
0B25-   D1 D5       CMP   ($D5),Y
0B27-   C9 D2       CMP   #$D2
0B29-   C5 C4       CMP   $C4
0B2B-   8D A0 D5    STA   $D5A0
0B2E-   D3          ???
0B2F-   C5 A0       CMP   $A0
0B31-   CD C9 CE    CMP   $CEC9
0B34-   AE CD C1    LDX   $C1CD
0B37-   C3          ???
0B38-   AE D2 C5    LDX   $C5D2
0B3B-   D1 D5       CMP   ($D5),Y
0B3D-   C9 D2       CMP   #$D2
0B3F-   C5 C4       CMP   $C4
0B41-   8D A0 D5    STA   $D5A0
0B44-   D3          ???
0B45-   C5 A0       CMP   $A0
0B47-   CD C1 C3    CMP   $C3C1
0B4A-   AE C9 C6    LDX   $C6C9
0B4D-   D3          ???
0B4E-   D4          ???
0B4F-   D2 D5       CMP   ($D5)
0B51-   C3          ???
0B52-   D4          ???
0B53-   8D A0 D5    STA   $D5A0
0B56-   D3          ???
0B57-   C5 A0       CMP   $A0
0B59-   CD C1 C3    CMP   $C3C1
0B5C-   AE CC CF    LDX   $CFCC
0B5F-   CF          ???
0B60-   D0 D3       BNE   $0B35
0B62-   D4          ???
0B63-   D2 D5       CMP   ($D5)
0B65-   C3          ???
0B66-   D4          ???
0B67-   8D DD C8    STA   $C8DD
0B6A-   CF          ???
0B6B-   CD C5 A0    CMP   $A0C5
0B6E-   C5 D1       CMP   $D1
0B70-   D5 A0       CMP   $A0,X
0B72-   A4 C6       LDY   $C6
0B74-   C3          ???
0B75-   B5 B8       LDA   $B8,X
0B77-   8D AA 8D    STA   $8DAA
0B7A-   AA          TAX
0B7B-   E0 E0       CPX   #$E0
0B7D-   E0 E0       CPX   #$E0
0B7F-   E0 E0       CPX   #$E0
0B81-   E0 E0       CPX   #$E0
0B83-   E0 E0       CPX   #$E0
0B85-   E0 E0       CPX   #$E0
0B87-   E0 E0       CPX   #$E0
0B89-   E0 E0       CPX   #$E0
0B8B-   E0 E0       CPX   #$E0
0B8D-   E0 E0       CPX   #$E0
0B8F-   E0 E0       CPX   #$E0
0B91-   E0 E0       CPX   #$E0
0B93-   E0 E0       CPX   #$E0
0B95-   E0 E0       CPX   #$E0
0B97-   E0 E0       CPX   #$E0
0B99-   AA          TAX
0B9A-   8D AA 20    STA   $20AA
0B9D-   20 20 20    JSR   $2020
0BA0-   20 20 D0    JSR   $D020
0BA3-   D2 CF       CMP   ($CF)
0BA5-   C7          ???
0BA6-   D2 C1       CMP   ($C1)
0BA8-   CD 20 CD    CMP   $CD20
0BAB-   C1 C9       CMP   ($C9,X)
0BAD-   CE 20 C2    DEC   $C220
0BB0-   CF          ???
0BB1-   C4 D9       CPY   $D9
0BB3-   20 20 20    JSR   $2020
0BB6-   20 20 20    JSR   $2020
0BB9-   20 AA 8D    JSR   $8DAA
0BBC-   AA          TAX
0BBD-   AC AC AC    LDY   $ACAC
0BC0-   AC AC AC    LDY   $ACAC
0BC3-   AC AC AC    LDY   $ACAC
0BC6-   AC AC AC    LDY   $ACAC
0BC9-   AC AC AC    LDY   $ACAC
0BCC-   AC AC AC    LDY   $ACAC
0BCF-   AC AC AC    LDY   $ACAC
0BD2-   AC AC AC    LDY   $ACAC
0BD5-   AC AC AC    LDY   $ACAC
0BD8-   AC AC AC    LDY   $ACAC
0BDB-   AA          TAX
0BDC-   8D AA 8D    STA   $8DAA
0BDF-   DD D6 C1    CMP   $C1D6,X
0BE2-   D2 B1       CMP   ($B1)
0BE4-   A0 C5       LDY   #$C5
0BE6-   D1 D5       CMP   ($D5),Y
0BE8-   A0 D6       LDY   #$D6
0BEA-   C1 D2       CMP   ($D2,X)
0BEC-   D4          ???
0BED-   C1 C2       CMP   ($C2,X)
0BEF-   8D DD D6    STA   $D6DD
0BF2-   C1 D2       CMP   ($D2,X)
0BF4-   B2 A0       LDA   ($A0)
0BF6-   C5 D1       CMP   $D1
0BF8-   D5 A0       CMP   $A0,X
0BFA-   D6 C1       DEC   $C1,X
0BFC-   D2 D4       CMP   ($D4)
0BFE-   C1 C2       CMP   ($C2,X)
0C00-   AB          ???
0C01-   B1 8D       LDA   ($8D),Y
0C03-   DD D6 C1    CMP   $C1D6,X
0C06-   D2 B3       CMP   ($B3)
0C08-   A0 C5       LDY   #$C5
0C0A-   D1 D5       CMP   ($D5),Y
0C0C-   A0 D6       LDY   #$D6
0C0E-   C1 D2       CMP   ($D2,X)
0C10-   D4          ???
0C11-   C1 C2       CMP   ($C2,X)
0C13-   AB          ???
0C14-   B2 8D       LDA   ($8D)
0C16-   DD D6 C1    CMP   $C1D6,X
0C19-   D2 B4       CMP   ($B4)
0C1B-   A0 C5       LDY   #$C5
0C1D-   D1 D5       CMP   ($D5),Y
0C1F-   A0 D6       LDY   #$D6
0C21-   C1 D2       CMP   ($D2,X)
0C23-   D4          ???
0C24-   C1 C2       CMP   ($C2,X)
0C26-   AB          ???
0C27-   B3          ???
0C28-   8D DD C3    STA   $C3DD
0C2B-   CF          ???
0C2C-   D5 CE       CMP   $CE,X
0C2E-   D4          ???
0C2F-   C5 D2       CMP   $D2
0C31-   A0 C5       LDY   #$C5
0C33-   D1 D5       CMP   ($D5),Y
0C35-   A0 D6       LDY   #$D6
0C37-   C1 D2       CMP   ($D2,X)
0C39-   D4          ???
0C3A-   C1 C2       CMP   ($C2,X)
0C3C-   AB          ???
0C3D-   B4 8D       LDY   $8D,X
0C3F-   DD C3 CF    CMP   $CFC3,X
0C42-   D5 D4       CMP   $D4,X
0C44-   B1 A0       LDA   ($A0),Y
0C46-   C5 D1       CMP   $D1
0C48-   D5 A0       CMP   $A0,X
0C4A-   A4 C6       LDY   $C6
0C4C-   C4 C6       CPY   $C6
0C4E-   B0 8D       BCS   $0BDD
0C50-   AA          TAX
0C51-   8D A0 CA    STA   $CAA0
0C54-   D3          ???
0C55-   D2 A0       CMP   ($A0)
0C57-   DD C8 CF    CMP   $CFC8,X
0C5A-   CD C5 8D    CMP   $8DC5
0C5D-   AA          TAX
0C5E-   8D A0 CC    STA   $CCA0
0C61-   C4 C1       CPY   $C1
0C63-   A0 A3       LDY   #$A3
0C65-   B1 B0       LDA   ($B0),Y
0C67-   8D A0 D3    STA   $D3A0
0C6A-   D4          ???
0C6B-   C1 A0       CMP   ($A0,X)
0C6D-   DD D6 C1    CMP   $C1D6,X
0C70-   D2 B1       CMP   ($B1)
0C72-   8D A0 D3    STA   $D3A0
0C75-   D4          ???
0C76-   C1 A0       CMP   ($A0,X)
0C78-   DD D6 C1    CMP   $C1D6,X
0C7B-   D2 B3       CMP   ($B3)
0C7D-   8D A0 CC    STA   $CCA0
0C80-   C4 C1       CPY   $C1
0C82-   A0 A3       LDY   #$A3
0C84-   B2 B0       LDA   ($B0)
0C86-   8D A0 D3    STA   $D3A0
0C89-   D4          ???
0C8A-   C1 A0       CMP   ($A0,X)
0C8C-   DD D6 C1    CMP   $C1D6,X
0C8F-   D2 B2       CMP   ($B2)
0C91-   8D A0 D3    STA   $D3A0
0C94-   D4          ???
0C95-   C1 A0       CMP   ($A0,X)
0C97-   DD D6 C1    CMP   $C1D6,X
0C9A-   D2 B4       CMP   ($B4)
0C9C-   8D AA 8D    STA   $8DAA
0C9F-   A0 C9       LDY   #$C9
0CA1-   C6 CA       DEC   $CA
0CA3-   A0 DD       LDY   #$DD
0CA5-   D6 C1       DEC   $C1,X
0CA7-   D2 B1       CMP   ($B1)
0CA9-   BB          ???
0CAA-   C5 BB       CMP   $BB
0CAC-   DD D6 C1    CMP   $C1D6,X
0CAF-   D2 B2       CMP   ($B2)
0CB1-   BB          ???
0CB2-   D6 B1       DEC   $B1,X
0CB4-   C5 B2       CMP   $B2
0CB6-   8D C1 B1    STA   $B1C1
0CB9-   A0 C9       LDY   #$C9
0CBB-   C6 CA       DEC   $CA
0CBD-   A0 DD       LDY   #$DD
0CBF-   D6 C1       DEC   $C1,X
0CC1-   D2 B1       CMP   ($B1)
0CC3-   BB          ???
0CC4-   C5 BB       CMP   $BB
0CC6-   DD D6 C1    CMP   $C1D6,X
0CC9-   D2 B3       CMP   ($B3)
0CCB-   BB          ???
0CCC-   D6 B1       DEC   $B1,X
0CCE-   C5 B3       CMP   $B3
0CD0-   8D C1 B2    STA   $B2C1
0CD3-   A0 C9       LDY   #$C9
0CD5-   C6 CA       DEC   $CA
0CD7-   C5 A0       CMP   $A0
0CD9-   DD D6 C1    CMP   $C1D6,X
0CDC-   D2 B2       CMP   ($B2)
0CDE-   BB          ???
0CDF-   C5 BB       CMP   $BB
0CE1-   DD D6 C1    CMP   $C1D6,X
0CE4-   D2 B3       CMP   ($B3)
0CE6-   BB          ???
0CE7-   D6 B2       DEC   $B2,X
0CE9-   C5 B3       CMP   $B3
0CEB-   BB          ???
0CEC-   D6 B2       DEC   $B2,X
0CEE-   C5 B4       CMP   $B4
0CF0-   8D AA 8D    STA   $8DAA
0CF3-   C1 B3       CMP   ($B3,X)
0CF5-   A0 CC       LDY   #$CC
0CF7-   C4 C1       CPY   $C1
0CF9-   A0 A3       LDY   #$A3
0CFB-   B0 8D       BCS   $0C8A
0CFD-   A0 D3       LDY   #$D3
0CFF-   D4          ???
0D00-   C1 A0       CMP   ($A0,X)
0D02-   DD C3 CF    CMP   $CFC3,X
0D05-   D5 CE       CMP   $CE,X
0D07-   D4          ???
0D08-   C5 D2       CMP   $D2
0D0A-   8D A0 CC    STA   $CCA0
0D0D-   C4 C1       CPY   $C1
0D0F-   A0 A3       LDY   #$A3
0D11-   A2 A5       LDX   #$A5
0D13-   A2 8D       LDX   #$8D
0D15-   A0 CC       LDY   #$CC
0D17-   CF          ???
0D18-   CF          ???
0D19-   D0 A0       BNE   $0CBB
0D1B-   BB          ???
0D1C-   20 C2 C5    JSR   $C5C2
0D1F-   C7          ???
0D20-   C9 CE       CMP   #$CE
0D22-   20 CC CF    JSR   $CFCC
0D25-   CF          ???
0D26-   D0 8D       BNE   $0CB5
0D28-   A0 CC       LDY   #$CC
0D2A-   C4 C1       CPY   $C1
0D2C-   A0 A3       LDY   #$A3
0D2E-   A2 AA       LDX   #$AA
0D30-   A2 8D       LDX   #$8D
0D32-   A0 CA       LDY   #$CA
0D34-   D3          ???
0D35-   D2 A0       CMP   ($A0)
0D37-   DD C3 CF    CMP   $CFC3,X
0D3A-   D5 D4       CMP   $D4,X
0D3C-   B1 8D       LDA   ($8D),Y
0D3E-   A0 C9       LDY   #$C9
0D40-   CE C3 A0    DEC   $A0C3
0D43-   DD C3 CF    CMP   $CFC3,X
0D46-   D5 CE       CMP   $CE,X
0D48-   D4          ???
0D49-   C5 D2       CMP   $D2
0D4B-   8D A0 CC    STA   $CCA0
0D4E-   C4 C1       CPY   $C1
0D50-   A0 A3       LDY   #$A3
0D52-   A2 A5       LDX   #$A5
0D54-   A2 8D       LDX   #$8D
0D56-   A0 D5       LDY   #$D5
0D58-   CE D4 C9    DEC   $C9D4
0D5B-   CC A0 DD    CPY   $DDA0
0D5E-   C3          ???
0D5F-   CF          ???
0D60-   D5 CE       CMP   $CE,X
0D62-   D4          ???
0D63-   C5 D2       CMP   $D2
0D65-   BB          ???
0D66-   C5 BB       CMP   $BB
0D68-   A3          ???
0D69-   B1 B0       LDA   ($B0),Y
0D6B-   8D A0 CA    STA   $CAA0
0D6E-   D3          ???
0D6F-   D2 A0       CMP   ($A0)
0D71-   DD C3 CF    CMP   $CFC3,X
0D74-   D5 D4       CMP   $D4,X
0D76-   B1 8D       LDA   ($8D),Y
0D78-   AA          TAX
0D79-   8D C1 B4    STA   $B4C1
0D7C-   A0 CC       LDY   #$CC
0D7E-   C4 C1       CPY   $C1
0D80-   A0 A3       LDY   #$A3
0D82-   B0 8D       BCS   $0D11
0D84-   A0 D3       LDY   #$D3
0D86-   D4          ???
0D87-   C1 A0       CMP   ($A0,X)
0D89-   DD C3 CF    CMP   $CFC3,X
0D8C-   D5 CE       CMP   $CE,X
0D8E-   D4          ???
0D8F-   C5 D2       CMP   $D2
0D91-   8D A0 CC    STA   $CCA0
0D94-   C4 C1       CPY   $C1
0D96-   A0 A3       LDY   #$A3
0D98-   A2 A5       LDX   #$A5
0D9A-   A2 8D       LDX   #$8D
0D9C-   A0 CC       LDY   #$CC
0D9E-   CF          ???
0D9F-   CF          ???
0DA0-   D0 A0       BNE   $0D42
0DA2-   BB          ???
0DA3-   20 C2 C5    JSR   $C5C2
0DA6-   C7          ???
0DA7-   C9 CE       CMP   #$CE
0DA9-   20 CC CF    JSR   $CFCC
0DAC-   CF          ???
0DAD-   D0 8D       BNE   $0D3C
0DAF-   A0 CC       LDY   #$CC
0DB1-   C4 C1       CPY   $C1
0DB3-   A0 A3       LDY   #$A3
0DB5-   A2 AA       LDX   #$AA
0DB7-   A2 8D       LDX   #$8D
0DB9-   A0 CA       LDY   #$CA
0DBB-   D3          ???
0DBC-   D2 A0       CMP   ($A0)
0DBE-   DD C3 CF    CMP   $CFC3,X
0DC1-   D5 D4       CMP   $D4,X
0DC3-   B1 8D       LDA   ($8D),Y
0DC5-   A0 C9       LDY   #$C9
0DC7-   CE C3 A0    DEC   $A0C3
0DCA-   DD C3 CF    CMP   $CFC3,X
0DCD-   D5 CE       CMP   $CE,X
0DCF-   D4          ???
0DD0-   C5 D2       CMP   $D2
0DD2-   8D A0 CC    STA   $CCA0
0DD5-   C4 C1       CPY   $C1
0DD7-   A0 A3       LDY   #$A3
0DD9-   A2 A5       LDX   #$A5
0DDB-   A2 8D       LDX   #$8D
0DDD-   A0 D7       LDY   #$D7
0DDF-   C8          INY
0DE0-   C9 CC       CMP   #$CC
0DE2-   C5 A0       CMP   $A0
0DE4-   DD C3 CF    CMP   $CFC3,X
0DE7-   D5 CE       CMP   $CE,X
0DE9-   D4          ???
0DEA-   C5 D2       CMP   $D2
0DEC-   BB          ???
0DED-   A8          TAY
0DEE-   BB          ???
0DEF-   A3          ???
0DF0-   B1 B0       LDA   ($B0),Y
0DF2-   8D A0 CA    STA   $CAA0
0DF5-   D3          ???
0DF6-   D2 A0       CMP   ($A0)
0DF8-   DD C3 CF    CMP   $CFC3,X
0DFB-   D5 D4       CMP   $D4,X
0DFD-   B1 8D       LDA   ($8D),Y
0DFF-   AA          TAX
0E00-   8D A0 CC    STA   $CCA0
0E03-   C4 C1       CPY   $C1
0E05-   A0 A3       LDY   #$A3
0E07-   A4 B8       LDY   $B8
0E09-   C4 8D       CPY   $8D
0E0B-   A0 CA       LDY   #$CA
0E0D-   D3          ???
0E0E-   D2 A0       CMP   ($A0)
0E10-   DD C3 CF    CMP   $CFC3,X
0E13-   D5 D4       CMP   $D4,X
0E15-   B1 8D       LDA   ($8D),Y
0E17-   A0 CA       LDY   #$CA
0E19-   D3          ???
0E1A-   D2 A0       CMP   ($A0)
0E1C-   DD C3 CF    CMP   $CFC3,X
0E1F-   D5 D4       CMP   $D4,X
0E21-   B1 8D       LDA   ($8D),Y
0E23-   A0 C6       LDY   #$C6
0E25-   CF          ???
0E26-   D2 A0       CMP   ($A0)
0E28-   A3          ???
0E29-   DD D6 C1    CMP   $C1D6,X
0E2C-   D2 B1       CMP   ($B1)
0E2E-   BB          ???
0E2F-   A3          ???
0E30-   B0 BB       BCS   $0DED
0E32-   A3          ???
0E33-   B1 B0       LDA   ($B0),Y
0E35-   BB          ???
0E36-   A3          ???
0E37-   B2 8D       LDA   ($8D)
0E39-   A0 C4       LDY   #$C4
0E3B-   D5 CD       CMP   $CD,X
0E3D-   D0 A0       BNE   $0DDF
0E3F-   A3          ???
0E40-   DD D6 C1    CMP   $C1D6,X
0E43-   D2 B1       CMP   ($B1)
0E45-   BB          ???
0E46-   A3          ???
0E47-   B2 8D       LDA   ($8D)
0E49-   A0 CE       LDY   #$CE
0E4B-   C5 D8       CMP   $D8
0E4D-   D4          ???
0E4E-   8D AA 8D    STA   $8DAA
0E51-   A0 C9       LDY   #$C9
0E53-   C6 C2       DEC   $C2
0E55-   B0 A0       BCS   $0DF7
0E57-   DD D6 C1    CMP   $C1D6,X
0E5A-   D2 B4       CMP   ($B4)
0E5C-   BB          ???
0E5D-   C5 BB       CMP   $BB
0E5F-   A3          ???
0E60-   B2 B0       LDA   ($B0)
0E62-   8D A0 DF    STA   $DFA0
0E65-   D0 D2       BNE   $0E39
0E67-   CE A0 A2    DEC   $A2A0
0E6A-   D7          ???
0E6B-   C5 CC       CMP   $CC
0E6D-   D0 A2       BNE   $0E11
0E6F-   AC B8 C4    LDY   $C4B8
0E72-   8D A0 C9    STA   $C9A0
0E75-   C6 C2       DEC   $C2
0E77-   B1 A0       LDA   ($A0),Y
0E79-   DD D6 C1    CMP   $C1D6,X
0E7C-   D2 B3       CMP   ($B3)
0E7E-   BB          ???
0E7F-   C5 BB       CMP   $BB
0E81-   A3          ???
0E82-   B0 B9       BCS   $0E3D
0E84-   8D A0 DF    STA   $DFA0
0E87-   D0 D2       BNE   $0E5B
0E89-   CE A0 A2    DEC   $A2A0
0E8C-   D4          ???
0E8D-   C8          INY
0E8E-   C1 D4       CMP   ($D4,X)
0E90-   20 D7 C1    JSR   $C1D7
0E93-   D3          ???
0E94-   20 C6 D5    JSR   $D5C6
0E97-   CE AE A2    DEC   $A2AE
0E9A-   AC B8 C4    LDY   $C4B8
0E9D-   B8          CLV
0E9E-   C4 8D       CPY   $8D
0EA0-   A0 C5       LDY   #$C5
0EA2-   CE C4 C9    DEC   $C9C4
0EA5-   C6 C2       DEC   $C2
0EA7-   B1 8D       LDA   ($8D),Y
0EA9-   A0 DF       LDY   #$DF
0EAB-   D0 D2       BNE   $0E7F
0EAD-   CE A0 A2    DEC   $A2A0
0EB0-   C3          ???
0EB1-   C8          INY
0EB2-   CF          ???
0EB3-   CF          ???
0EB4-   20 C3 C8    JSR   $C8C3
0EB7-   CF          ???
0EB8-   CF          ???
0EB9-   A1 A2       LDA   ($A2,X)
0EBB-   AC B8 C4    LDY   $C4B8
0EBE-   B8          CLV
0EBF-   C4 8D       CPY   $8D
0EC1-   A0 C5       LDY   #$C5
0EC3-   CE C4 C9    DEC   $C9C4
0EC6-   C6 C2       DEC   $C2
0EC8-   B0 8D       BCS   $0E57
0ECA-   A0 DF       LDY   #$DF
0ECC-   D0 D2       BNE   $0EA0
0ECE-   CE A0 A2    DEC   $A2A0
0ED1-   C4 CF       CPY   $CF
0ED3-   CE C5 A1    DEC   $A1C5
0ED6-   A2 AC       LDX   #$AC
0ED8-   B8          CLV
0ED9-   C4 B8       CPY   $B8
0EDB-   C4 8D       CPY   $8D
0EDD-   AA          TAX
0EDE-   8D A0 CA    STA   $CAA0
0EE1-   CD D0 A0    CMP   $A0D0
0EE4-   D2 C5       CMP   ($C5)
0EE6-   C5 CE       CMP   $CE
0EE8-   D4          ???
0EE9-   D2 D9       CMP   ($D9)
0EEB-   8D AA 8D    STA   $8DAA
0EEE-   D6 B1       DEC   $B1,X
0EF0-   C5 B2       CMP   $B2
0EF2-   8D A0 DF    STA   $DFA0
0EF5-   D0 D2       BNE   $0EC9
0EF7-   CE A0 A2    DEC   $A2A0
0EFA-   D6 C1       DEC   $C1,X
0EFC-   D2 B1       CMP   ($B1)
0EFE-   20 BD 20    JSR   $20BD
0F01-   D6 C1       DEC   $C1,X
0F03-   D2 B2       CMP   ($B2)
0F05-   AE A2 8D    LDX   $8DA2
0F08-   A0 CA       LDY   #$CA
0F0A-   CD D0 A0    CMP   $A0D0
0F0D-   C1 B1       CMP   ($B1,X)
0F0F-   8D D6 B1    STA   $B1D6
0F12-   C5 B3       CMP   $B3
0F14-   A0 DF       LDY   #$DF
0F16-   D0 D2       BNE   $0EEA
0F18-   CE A0 A2    DEC   $A2A0
0F1B-   D6 C1       DEC   $C1,X
0F1D-   D2 B1       CMP   ($B1)
0F1F-   20 BD 20    JSR   $20BD
0F22-   D6 C1       DEC   $C1,X
0F24-   D2 B3       CMP   ($B3)
0F26-   A2 AC       LDX   #$AC
0F28-   B8          CLV
0F29-   C4 B8       CPY   $B8
0F2B-   C4 8D       CPY   $8D
0F2D-   A0 CA       LDY   #$CA
0F2F-   CD D0 A0    CMP   $A0D0
0F32-   C1 B2       CMP   ($B2,X)
0F34-   8D D6 B2    STA   $B2D6
0F37-   C5 B3       CMP   $B3
0F39-   8D A0 DF    STA   $DFA0
0F3C-   D0 D2       BNE   $0F10
0F3E-   CE A0 A2    DEC   $A2A0
0F41-   D6 C1       DEC   $C1,X
0F43-   D2 B2       CMP   ($B2)
0F45-   20 BD 20    JSR   $20BD
0F48-   D6 C1       DEC   $C1,X
0F4A-   D2 B3       CMP   ($B3)
0F4C-   AE A2 AC    LDX   $ACA2
0F4F-   B8          CLV
0F50-   C4 B8       CPY   $B8
0F52-   C4 8D       CPY   $8D
0F54-   A0 CA       LDY   #$CA
0F56-   CD D0 A0    CMP   $A0D0
0F59-   C1 B2       CMP   ($B2,X)
0F5B-   8D D6 B2    STA   $B2D6
0F5E-   C5 B4       CMP   $B4
0F60-   8D A0 DF    STA   $DFA0
0F63-   D0 D2       BNE   $0F37
0F65-   CE A0 A2    DEC   $A2A0
0F68-   D6 C1       DEC   $C1,X
0F6A-   D2 B2       CMP   ($B2)
0F6C-   20 BD 20    JSR   $20BD
0F6F-   D6 C1       DEC   $C1,X
0F71-   D2 B4       CMP   ($B4)
0F73-   A2 AC       LDX   #$AC
0F75-   B8          CLV
0F76-   C4 B8       CPY   $B8
0F78-   C4 8D       CPY   $8D
0F7A-   A0 CA       LDY   #$CA
0F7C-   CD D0 A0    CMP   $A0D0
0F7F-   C1 B3       CMP   ($B3,X)
0F81-   8D AA 8D    STA   $8DAA
0F84-   AA          TAX
0F85-   8D AA E0    STA   $E0AA
0F88-   E0 E0       CPX   #$E0
0F8A-   E0 E0       CPX   #$E0
0F8C-   E0 E0       CPX   #$E0
0F8E-   E0 E0       CPX   #$E0
0F90-   E0 E0       CPX   #$E0
0F92-   E0 E0       CPX   #$E0
0F94-   E0 E0       CPX   #$E0
0F96-   E0 E0       CPX   #$E0
0F98-   E0 E0       CPX   #$E0
0F9A-   E0 E0       CPX   #$E0
0F9C-   E0 E0       CPX   #$E0
0F9E-   E0 E0       CPX   #$E0
0FA0-   E0 E0       CPX   #$E0
0FA2-   E0 E0       CPX   #$E0
0FA4-   E0 AA       CPX   #$AA
0FA6-   8D AA 20    STA   $20AA
0FA9-   20 20 20    JSR   $2020
0FAC-   20 20 20    JSR   $2020
0FAF-   20 C2 CF    JSR   $CFC2
0FB2-   D4          ???
0FB3-   D4          ???
0FB4-   CF          ???
0FB5-   CD 20 C9    CMP   $C920
0FB8-   CE C3 CC    DEC   $CCC3
0FBB-   D5 C4       CMP   $C4,X
0FBD-   C5 D3       CMP   $D3
0FBF-   20 20 20    JSR   $2020
0FC2-   20 20 20    JSR   $2020
0FC5-   20 AA 8D    JSR   $8DAA
0FC8-   AA          TAX
0FC9-   AC AC AC    LDY   $ACAC
0FCC-   AC AC AC    LDY   $ACAC
0FCF-   AC AC AC    LDY   $ACAC
0FD2-   AC AC AC    LDY   $ACAC
0FD5-   AC AC AC    LDY   $ACAC
0FD8-   AC AC AC    LDY   $ACAC
0FDB-   AC AC AC    LDY   $ACAC
0FDE-   AC AC AC    LDY   $ACAC
0FE1-   AC AC AC    LDY   $ACAC
0FE4-   AC AC AC    LDY   $ACAC
0FE7-   AA          TAX
0FE8-   8D AA 8D    STA   $8DAA
0FEB-   AA          TAX
0FEC-   AA          TAX
0FED-   20 C2 CF    JSR   $CFC2
0FF0-   D4          ???
0FF1-   D4          ???
0FF2-   CF          ???
0FF3-   CD 20 C9    CMP   $C920
0FF6-   CE C3 CC    DEC   $CCC3
0FF9-   D5 C4       CMP   $C4,X
0FFB-   C5 D3       CMP   $D3
0FFD-   8D AA 8D    STA   $8DAA
1000-   A0 D0       LDY   #$D0
1002-   D5 D4       CMP   $D4,X
1004-   A0 CD       LDY   #$CD
1006-   C9 CE       CMP   #$CE
1008-   AE CC C9    LDX   $C9CC
100B-   C2          ???
100C-   AE D2 C5    LDX   $C5D2
100F-   D1 D5       CMP   ($D5),Y
1011-   C9 D2       CMP   #$D2
1013-   C5 C4       CMP   $C4
1015-   8D 00 00    STA   $0000
