0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C6    LDY   $C620,X
0950-   C9 CC       CMP   #$CC
0952-   C5 C9       CMP   $C9
0954-   CF          ???
0955-   20 20 C4    JSR   $C420
0958-   C5 CD       CMP   $CD
095A-   CF          ???
095B-   20 BE AD    JSR   $ADBE
095E-   20 20 20    JSR   $2020
0961-   20 20 20    JSR   $2020
0964-   AA          TAX
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B2       BCS   $094E
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B2    JSR   $B220
09D4-   B2 AD       LDA   ($AD)
09D6-   C4 C5       CPY   $C5
09D8-   C3          ???
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B8       LDA   ($B8),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 C4    STA   $C4A0
0B02-   D3          ???
0B03-   CB          ???
0B04-   A0 C6       LDY   #$C6
0B06-   C9 CC       CMP   #$CC
0B08-   C5 C9       CMP   $C9
0B0A-   CF          ???
0B0B-   AE C4 C5    LDX   $C5C4
0B0E-   CD CF 8D    CMP   $8DCF
0B11-   AA          TAX
0B12-   8D A0 CF    STA   $CFA0
0B15-   C2          ???
0B16-   CA          DEX
0B17-   A0 A4       LDY   #$A4
0B19-   C2          ???
0B1A-   C6 C5       DEC   $C5
0B1C-   B0 8D       BCS   $0AAB
0B1E-   A0 CF       LDY   #$CF
0B20-   D2 C7       CMP   ($C7)
0B22-   A0 A4       LDY   #$A4
0B24-   B6 B0       LDX   $B0,Y
0B26-   B0 B0       BCS   $0AD8
0B28-   8D AA 8D    STA   $8DAA
0B2B-   AA          TAX
0B2C-   E0 E0       CPX   #$E0
0B2E-   E0 E0       CPX   #$E0
0B30-   E0 E0       CPX   #$E0
0B32-   E0 E0       CPX   #$E0
0B34-   E0 E0       CPX   #$E0
0B36-   E0 E0       CPX   #$E0
0B38-   E0 E0       CPX   #$E0
0B3A-   E0 E0       CPX   #$E0
0B3C-   E0 E0       CPX   #$E0
0B3E-   E0 E0       CPX   #$E0
0B40-   E0 E0       CPX   #$E0
0B42-   E0 E0       CPX   #$E0
0B44-   E0 E0       CPX   #$E0
0B46-   E0 E0       CPX   #$E0
0B48-   E0 E0       CPX   #$E0
0B4A-   AA          TAX
0B4B-   8D AA 20    STA   $20AA
0B4E-   20 D4 CF    JSR   $CFD4
0B51-   D0 20       BNE   $0B73
0B53-   C9 CE       CMP   #$CE
0B55-   C3          ???
0B56-   CC D5 C4    CPY   $C4D5
0B59-   C5 D3       CMP   $D3
0B5B-   20 A8 C8    JSR   $C8A8
0B5E-   CF          ???
0B5F-   CF          ???
0B60-   CB          ???
0B61-   D3          ???
0B62-   AC CD C1    LDY   $C1CD
0B65-   C3          ???
0B66-   D2 CF       CMP   ($CF)
0B68-   D3          ???
0B69-   A9 20       LDA   #$20
0B6B-   AA          TAX
0B6C-   8D AA AC    STA   $ACAA
0B6F-   AC AC AC    LDY   $ACAC
0B72-   AC AC AC    LDY   $ACAC
0B75-   AC AC AC    LDY   $ACAC
0B78-   AC AC AC    LDY   $ACAC
0B7B-   AC AC AC    LDY   $ACAC
0B7E-   AC AC AC    LDY   $ACAC
0B81-   AC AC AC    LDY   $ACAC
0B84-   AC AC AC    LDY   $ACAC
0B87-   AC AC AC    LDY   $ACAC
0B8A-   AC AC AA    LDY   $AAAC
0B8D-   8D AA 8D    STA   $8DAA
0B90-   A0 D5       LDY   #$D5
0B92-   D3          ???
0B93-   C5 A0       CMP   $A0
0B95-   D2 C5       CMP   ($C5)
0B97-   D1 D5       CMP   ($D5),Y
0B99-   C9 D2       CMP   #$D2
0B9B-   C5 C4       CMP   $C4
0B9D-   AE CD C1    LDX   $C1CD
0BA0-   C3          ???
0BA1-   8D A0 D0    STA   $D0A0
0BA4-   D5 D4       CMP   $D4,X
0BA6-   A0 D2       LDY   #$D2
0BA8-   C5 D1       CMP   $D1
0BAA-   D5 C9       CMP   $C9,X
0BAC-   D2 C5       CMP   ($C5)
0BAE-   C4 AE       CPY   $AE
0BB0-   C8          INY
0BB1-   CF          ???
0BB2-   CF          ???
0BB3-   CB          ???
0BB4-   D3          ???
0BB5-   8D AA 8D    STA   $8DAA
0BB8-   A0 D5       LDY   #$D5
0BBA-   D3          ???
0BBB-   C5 A0       CMP   $A0
0BBD-   C6 C9       DEC   $C9
0BBF-   CC C5 C9    CPY   $C9C5
0BC2-   CF          ???
0BC3-   AE CD C1    LDX   $C1CD
0BC6-   C3          ???
0BC7-   8D A0 D0    STA   $D0A0
0BCA-   D5 D4       CMP   $D4,X
0BCC-   A0 C6       LDY   #$C6
0BCE-   C9 CC       CMP   #$CC
0BD0-   C5 C9       CMP   $C9
0BD2-   CF          ???
0BD3-   AE C8 CF    LDX   $CFC8
0BD6-   CF          ???
0BD7-   CB          ???
0BD8-   D3          ???
0BD9-   8D AA 8D    STA   $8DAA
0BDC-   AA          TAX
0BDD-   E0 E0       CPX   #$E0
0BDF-   E0 E0       CPX   #$E0
0BE1-   E0 E0       CPX   #$E0
0BE3-   E0 E0       CPX   #$E0
0BE5-   E0 E0       CPX   #$E0
0BE7-   E0 E0       CPX   #$E0
0BE9-   E0 E0       CPX   #$E0
0BEB-   E0 E0       CPX   #$E0
0BED-   E0 E0       CPX   #$E0
0BEF-   E0 E0       CPX   #$E0
0BF1-   E0 E0       CPX   #$E0
0BF3-   E0 E0       CPX   #$E0
0BF5-   E0 E0       CPX   #$E0
0BF7-   E0 E0       CPX   #$E0
0BF9-   E0 E0       CPX   #$E0
0BFB-   AA          TAX
0BFC-   8D AA 20    STA   $20AA
0BFF-   20 20 20    JSR   $2020
0C02-   20 20 D0    JSR   $D020
0C05-   D2 CF       CMP   ($CF)
0C07-   C7          ???
0C08-   D2 C1       CMP   ($C1)
0C0A-   CD 20 CD    CMP   $CD20
0C0D-   C1 C9       CMP   ($C9,X)
0C0F-   CE 20 C2    DEC   $C220
0C12-   CF          ???
0C13-   C4 D9       CPY   $D9
0C15-   20 20 20    JSR   $2020
0C18-   20 20 20    JSR   $2020
0C1B-   20 AA 8D    JSR   $8DAA
0C1E-   AA          TAX
0C1F-   AC AC AC    LDY   $ACAC
0C22-   AC AC AC    LDY   $ACAC
0C25-   AC AC AC    LDY   $ACAC
0C28-   AC AC AC    LDY   $ACAC
0C2B-   AC AC AC    LDY   $ACAC
0C2E-   AC AC AC    LDY   $ACAC
0C31-   AC AC AC    LDY   $ACAC
0C34-   AC AC AC    LDY   $ACAC
0C37-   AC AC AC    LDY   $ACAC
0C3A-   AC AC AC    LDY   $ACAC
0C3D-   AA          TAX
0C3E-   8D AA 8D    STA   $8DAA
0C41-   AA          TAX
0C42-   AA          TAX
0C43-   AA          TAX
0C44-   AA          TAX
0C45-   AA          TAX
0C46-   AA          TAX
0C47-   AA          TAX
0C48-   AA          TAX
0C49-   AA          TAX
0C4A-   AA          TAX
0C4B-   AA          TAX
0C4C-   AA          TAX
0C4D-   AA          TAX
0C4E-   AA          TAX
0C4F-   AA          TAX
0C50-   AA          TAX
0C51-   AA          TAX
0C52-   AA          TAX
0C53-   AA          TAX
0C54-   AA          TAX
0C55-   AA          TAX
0C56-   AA          TAX
0C57-   AA          TAX
0C58-   AA          TAX
0C59-   AA          TAX
0C5A-   AA          TAX
0C5B-   AA          TAX
0C5C-   AA          TAX
0C5D-   AA          TAX
0C5E-   AA          TAX
0C5F-   AA          TAX
0C60-   AA          TAX
0C61-   8D AA AA    STA   $AAAA
0C64-   AA          TAX
0C65-   AA          TAX
0C66-   AA          TAX
0C67-   AA          TAX
0C68-   AA          TAX
0C69-   AA          TAX
0C6A-   AA          TAX
0C6B-   AA          TAX
0C6C-   AA          TAX
0C6D-   AA          TAX
0C6E-   AA          TAX
0C6F-   AA          TAX
0C70-   AA          TAX
0C71-   AA          TAX
0C72-   AA          TAX
0C73-   AA          TAX
0C74-   AA          TAX
0C75-   AA          TAX
0C76-   AA          TAX
0C77-   AA          TAX
0C78-   AA          TAX
0C79-   AA          TAX
0C7A-   AA          TAX
0C7B-   AA          TAX
0C7C-   AA          TAX
0C7D-   AA          TAX
0C7E-   AA          TAX
0C7F-   AA          TAX
0C80-   AA          TAX
0C81-   AA          TAX
0C82-   8D AA 20    STA   $20AA
0C85-   20 20 20    JSR   $2020
0C88-   20 20 20    JSR   $2020
0C8B-   20 20 20    JSR   $2020
0C8E-   20 20 20    JSR   $2020
0C91-   20 20 20    JSR   $2020
0C94-   20 20 20    JSR   $2020
0C97-   20 20 20    JSR   $2020
0C9A-   20 20 20    JSR   $2020
0C9D-   20 20 20    JSR   $2020
0CA0-   20 20 AA    JSR   $AA20
0CA3-   8D AA 20    STA   $20AA
0CA6-   CE CF D4    DEC   $D4CF
0CA9-   C5 BA       CMP   $BA
0CAB-   20 C6 CF    JSR   $CFC6
0CAE-   D2 20       CMP   ($20)
0CB0-   D4          ???
0CB1-   C8          INY
0CB2-   C9 D3       CMP   #$D3
0CB4-   20 D4 CF    JSR   $CFD4
0CB7-   20 D7 CF    JSR   $CFD7
0CBA-   D2 CB       CMP   ($CB)
0CBC-   20 20 20    JSR   $2020
0CBF-   20 20 20    JSR   $2020
0CC2-   20 AA 8D    JSR   $8DAA
0CC5-   AA          TAX
0CC6-   20 D0 D2    JSR   $D2D0
0CC9-   CF          ???
0CCA-   D0 C5       BNE   $0C91
0CCC-   D2 CC       CMP   ($CC)
0CCE-   D9 AC 20    CMP   $20AC,Y
0CD1-   D4          ???
0CD2-   C8          INY
0CD3-   C5 20       CMP   $20
0CD5-   C4 C5       CPY   $C5
0CD7-   CD CF 20    CMP   $20CF
0CDA-   C8          INY
0CDB-   C1 D3       CMP   ($D3,X)
0CDD-   20 D4 CF    JSR   $CFD4
0CE0-   20 C2 C5    JSR   $C5C2
0CE3-   20 AA 8D    JSR   $8DAA
0CE6-   AA          TAX
0CE7-   20 C2 CC    JSR   $CCC2
0CEA-   CF          ???
0CEB-   C1 C4       CMP   ($C4,X)
0CED-   C5 C4       CMP   $C4
0CEF-   AC 20 D4    LDY   $D420
0CF2-   C8          INY
0CF3-   C5 CE       CMP   $CE
0CF5-   20 C5 D8    JSR   $D8C5
0CF8-   C5 C3       CMP   $C3
0CFA-   D5 D4       CMP   $D4,X
0CFC-   C5 C4       CMP   $C4
0CFE-   20 D6 C9    JSR   $C9D6
0D01-   C1 20       CMP   ($20,X)
0D03-   20 20 AA    JSR   $AA20
0D06-   8D AA 20    STA   $20AA
0D09-   D4          ???
0D0A-   C8          INY
0D0B-   C5 20       CMP   $20
0D0D-   CD CF CE    CMP   $CECF
0D10-   C9 D4       CMP   #$D4
0D12-   CF          ???
0D13-   D2 20       CMP   ($20)
0D15-   A8          TAY
0D16-   B6 B0       LDX   $B0,Y
0D18-   B0 B0       BCS   $0CCA
0D1A-   C7          ???
0D1B-   A9 AE       LDA   #$AE
0D1D-   20 C9 C6    JSR   $C6C9
0D20-   20 D4 C8    JSR   $C8D4
0D23-   C9 D3       CMP   #$D3
0D25-   20 AA 8D    JSR   $8DAA
0D28-   AA          TAX
0D29-   20 C9 D3    JSR   $D3C9
0D2C-   20 CE CF    JSR   $CFCE
0D2F-   D4          ???
0D30-   20 C4 CF    JSR   $CFC4
0D33-   CE C5 AC    DEC   $ACC5
0D36-   20 D9 CF    JSR   $CFD9
0D39-   D5 20       CMP   $20,X
0D3B-   D7          ???
0D3C-   C9 CC       CMP   #$CC
0D3E-   CC 20 C7    CPY   $C720
0D41-   C5 D4       CMP   $D4
0D43-   20 C1 20    JSR   $20C1
0D46-   20 AA 8D    JSR   $8DAA
0D49-   AA          TAX
0D4A-   20 A2 C6    JSR   $C6A2
0D4D-   C9 CC       CMP   #$CC
0D4F-   C5 20       CMP   $20
0D51-   CE CF D4    DEC   $D4CF
0D54-   20 C6 CF    JSR   $CFC6
0D57-   D5 CE       CMP   $CE,X
0D59-   C4 A2       CPY   $A2
0D5B-   20 C5 D2    JSR   $D2C5
0D5E-   D2 CF       CMP   ($CF)
0D60-   D2 20       CMP   ($20)
0D62-   D7          ???
0D63-   C8          INY
0D64-   C5 CE       CMP   $CE
0D66-   20 20 AA    JSR   $AA20
0D69-   8D AA 20    STA   $20AA
0D6C-   C4 CF       CPY   $CF
0D6E-   C9 CE       CMP   #$CE
0D70-   C7          ???
0D71-   20 C6 C9    JSR   $C9C6
0D74-   CC C5 20    CPY   $20C5
0D77-   CF          ???
0D78-   D0 C5       BNE   $0D3F
0D7A-   D2 C1       CMP   ($C1)
0D7C-   D4          ???
0D7D-   C9 CF       CMP   #$CF
0D7F-   CE D3 AE    DEC   $AED3
0D82-   20 20 20    JSR   $2020
0D85-   20 20 20    JSR   $2020
0D88-   20 AA 8D    JSR   $8DAA
0D8B-   AA          TAX
0D8C-   20 20 20    JSR   $2020
0D8F-   20 20 20    JSR   $2020
0D92-   20 20 20    JSR   $2020
0D95-   20 20 20    JSR   $2020
0D98-   20 20 20    JSR   $2020
0D9B-   20 20 20    JSR   $2020
0D9E-   20 20 20    JSR   $2020
0DA1-   20 20 20    JSR   $2020
0DA4-   20 20 20    JSR   $2020
0DA7-   20 20 20    JSR   $2020
0DAA-   AA          TAX
0DAB-   8D AA 20    STA   $20AA
0DAE-   C6 CF       DEC   $CF
0DB0-   D2 20       CMP   ($20)
0DB2-   D9 CF D5    CMP   $D5CF,Y
0DB5-   D2 20       CMP   ($20)
0DB7-   CF          ???
0DB8-   D7          ???
0DB9-   CE 20 D0    DEC   $D020
0DBC-   D2 CF       CMP   ($CF)
0DBE-   CA          DEX
0DBF-   C5 C3       CMP   $C3
0DC1-   D4          ???
0DC2-   D3          ???
0DC3-   AC 20 C1    LDY   $C120
0DC6-   20 D7 C1    JSR   $C1D7
0DC9-   D9 20 AA    CMP   $AA20,Y
0DCC-   8D AA 20    STA   $20AA
0DCF-   D4          ???
0DD0-   CF          ???
0DD1-   20 D7 CF    JSR   $CFD7
0DD4-   D2 CB       CMP   ($CB)
0DD6-   20 C1 D2    JSR   $D2C1
0DD9-   CF          ???
0DDA-   D5 CE       CMP   $CE,X
0DDC-   C4 20       CPY   $20
0DDE-   D4          ???
0DDF-   C8          INY
0DE0-   C9 D3       CMP   #$D3
0DE2-   20 C9 D3    JSR   $D3C9
0DE5-   20 D4 CF    JSR   $CFD4
0DE8-   20 20 20    JSR   $2020
0DEB-   20 AA 8D    JSR   $8DAA
0DEE-   AA          TAX
0DEF-   20 D5 D3    JSR   $D3D5
0DF2-   C5 20       CMP   $20
0DF4-   C1 CE       CMP   ($CE,X)
0DF6-   20 C5 D8    JSR   $D8C5
0DF9-   C5 C3       CMP   $C3
0DFB-   20 C6 C9    JSR   $C9C6
0DFE-   CC C5 20    CPY   $20C5
0E01-   D4          ???
0E02-   CF          ???
0E03-   20 C2 CC    JSR   $CCC2
0E06-   CF          ???
0E07-   C1 C4       CMP   ($C4,X)
0E09-   20 20 20    JSR   $2020
0E0C-   20 AA 8D    JSR   $8DAA
0E0F-   AA          TAX
0E10-   20 C1 CE    JSR   $CEC1
0E13-   C4 20       CPY   $20
0E15-   C5 D8       CMP   $D8
0E17-   C5 C3       CMP   $C3
0E19-   D5 D4       CMP   $D4,X
0E1B-   C5 20       CMP   $20
0E1D-   D4          ???
0E1E-   C8          INY
0E1F-   C5 20       CMP   $20
0E21-   C3          ???
0E22-   CF          ???
0E23-   C4 C5       CPY   $C5
0E25-   AE 20 20    LDX   $2020
0E28-   20 20 20    JSR   $2020
0E2B-   20 20 20    JSR   $2020
0E2E-   AA          TAX
0E2F-   8D AA 20    STA   $20AA
0E32-   20 20 20    JSR   $2020
0E35-   20 20 20    JSR   $2020
0E38-   20 20 20    JSR   $2020
0E3B-   20 20 20    JSR   $2020
0E3E-   20 20 20    JSR   $2020
0E41-   20 20 20    JSR   $2020
0E44-   20 20 20    JSR   $2020
0E47-   20 20 20    JSR   $2020
0E4A-   20 20 20    JSR   $2020
0E4D-   20 20 AA    JSR   $AA20
0E50-   8D AA AA    STA   $AAAA
0E53-   AA          TAX
0E54-   AA          TAX
0E55-   AA          TAX
0E56-   AA          TAX
0E57-   AA          TAX
0E58-   AA          TAX
0E59-   AA          TAX
0E5A-   AA          TAX
0E5B-   AA          TAX
0E5C-   AA          TAX
0E5D-   AA          TAX
0E5E-   AA          TAX
0E5F-   AA          TAX
0E60-   AA          TAX
0E61-   AA          TAX
0E62-   AA          TAX
0E63-   AA          TAX
0E64-   AA          TAX
0E65-   AA          TAX
0E66-   AA          TAX
0E67-   AA          TAX
0E68-   AA          TAX
0E69-   AA          TAX
0E6A-   AA          TAX
0E6B-   AA          TAX
0E6C-   AA          TAX
0E6D-   AA          TAX
0E6E-   AA          TAX
0E6F-   AA          TAX
0E70-   AA          TAX
0E71-   8D AA AA    STA   $AAAA
0E74-   AA          TAX
0E75-   AA          TAX
0E76-   AA          TAX
0E77-   AA          TAX
0E78-   AA          TAX
0E79-   AA          TAX
0E7A-   AA          TAX
0E7B-   AA          TAX
0E7C-   AA          TAX
0E7D-   AA          TAX
0E7E-   AA          TAX
0E7F-   AA          TAX
0E80-   AA          TAX
0E81-   AA          TAX
0E82-   AA          TAX
0E83-   AA          TAX
0E84-   AA          TAX
0E85-   AA          TAX
0E86-   AA          TAX
0E87-   AA          TAX
0E88-   AA          TAX
0E89-   AA          TAX
0E8A-   AA          TAX
0E8B-   AA          TAX
0E8C-   AA          TAX
0E8D-   AA          TAX
0E8E-   AA          TAX
0E8F-   AA          TAX
0E90-   AA          TAX
0E91-   AA          TAX
0E92-   8D AA 8D    STA   $8DAA
0E95-   A0 DF       LDY   #$DF
0E97-   D0 D2       BNE   $0E6B
0E99-   CE D4 A0    DEC   $A0D4
0E9C-   A2 20       LDX   #$20
0E9E-   A2 AC       LDX   #$AC
0EA0-   B8          CLV
0EA1-   C4 B8       CPY   $B8
0EA3-   C4 B8       CPY   $B8
0EA5-   C4 B8       CPY   $B8
0EA7-   C4 B8       CPY   $B8
0EA9-   C4 8D       CPY   $8D
0EAB-   A0 DF       LDY   #$DF
0EAD-   D0 D2       BNE   $0E81
0EAF-   CE D4 A0    DEC   $A0D4
0EB2-   A2 C6       LDX   #$C6
0EB4-   C9 CC       CMP   #$CC
0EB6-   C5 20       CMP   $20
0EB8-   C9 CE       CMP   #$CE
0EBA-   D0 D5       BNE   $0E91
0EBC-   D4          ???
0EBD-   AF          ???
0EBE-   CF          ???
0EBF-   D5 D4       CMP   $D4,X
0EC1-   D0 D5       BNE   $0E98
0EC3-   D4          ???
0EC4-   20 CD C1    JSR   $C1CD
0EC7-   C3          ???
0EC8-   D2 CF       CMP   ($CF)
0ECA-   D3          ???
0ECB-   A2 AC       LDX   #$AC
0ECD-   B8          CLV
0ECE-   C4 8D       CPY   $8D
0ED0-   A0 DF       LDY   #$DF
0ED2-   D0 D2       BNE   $0EA6
0ED4-   CE D4 A0    DEC   $A0D4
0ED7-   A2 AD       LDX   #$AD
0ED9-   AD AD AD    LDA   $ADAD
0EDC-   AD AD AD    LDA   $ADAD
0EDF-   AD AD AD    LDA   $ADAD
0EE2-   AD AD AD    LDA   $ADAD
0EE5-   AD AD AD    LDA   $ADAD
0EE8-   AD AD AD    LDA   $ADAD
0EEB-   AD AD AD    LDA   $ADAD
0EEE-   AD AD A2    LDA   $A2AD
0EF1-   AC B8 C4    LDY   $C4B8
0EF4-   B8          CLV
0EF5-   C4 8D       CPY   $8D
0EF7-   A0 DF       LDY   #$DF
0EF9-   D0 D2       BNE   $0ECD
0EFB-   CE D4 A0    DEC   $A0D4
0EFE-   A2 D4       LDX   #$D4
0F00-   C8          INY
0F01-   C5 20       CMP   $20
0F03-   C2          ???
0F04-   D3          ???
0F05-   C1 D6       CMP   ($D6,X)
0F07-   C5 20       CMP   $20
0F09-   CD C1 C3    CMP   $C3C1
0F0C-   D2 CF       CMP   ($CF)
0F0E-   20 D3 C1    JSR   $C1D3
0F11-   D6 C5       DEC   $C5,X
0F13-   D3          ???
0F14-   20 D4 C8    JSR   $C8D4
0F17-   C5 20       CMP   $20
0F19-   C7          ???
0F1A-   C9 D6       CMP   #$D6
0F1C-   C5 CE       CMP   $CE
0F1E-   A2 AC       LDX   #$AC
0F20-   B8          CLV
0F21-   C4 8D       CPY   $8D
0F23-   A0 DF       LDY   #$DF
0F25-   D0 D2       BNE   $0EF9
0F27-   CE D4 A0    DEC   $A0D4
0F2A-   A2 C1       LDX   #$C1
0F2C-   C4 C4       CPY   $C4
0F2E-   D2 C5       CMP   ($C5)
0F30-   D3          ???
0F31-   D3          ???
0F32-   20 D2 C1    JSR   $C1D2
0F35-   CE C7 C5    DEC   $C5C7
0F38-   20 D5 CE    JSR   $CED5
0F3B-   C4 C5       CPY   $C5
0F3D-   D2 20       CMP   ($20)
0F3F-   D4          ???
0F40-   C8          INY
0F41-   C5 20       CMP   $20
0F43-   D3          ???
0F44-   D0 C5       BNE   $0F0B
0F46-   C3          ???
0F47-   C9 C6       CMP   #$C6
0F49-   C9 C5       CMP   #$C5
0F4B-   C4 A2       CPY   $A2
0F4D-   AC B8 C4    LDY   $C4B8
0F50-   8D A0 DF    STA   $DFA0
0F53-   D0 D2       BNE   $0F27
0F55-   CE D4 A0    DEC   $A0D4
0F58-   A2 C2       LDX   #$C2
0F5A-   C9 CE       CMP   #$CE
0F5C-   C1 D2       CMP   ($D2,X)
0F5E-   D9 20 C6    CMP   $C620,Y
0F61-   C9 CC       CMP   #$CC
0F63-   C5 AE       CMP   $AE
0F65-   20 D4 C8    JSR   $C8D4
0F68-   C5 20       CMP   $20
0F6A-   C1 D2       CMP   ($D2,X)
0F6C-   C7          ???
0F6D-   D5 CD       CMP   $CD,X
0F6F-   C5 CE       CMP   $CE
0F71-   D4          ???
0F72-   20 C9 D3    JSR   $D3C9
0F75-   20 D3 C9    JSR   $C9D3
0F78-   CD D0 CC    CMP   $CCD0
0F7B-   D9 A2 AC    CMP   $ACA2,Y
0F7E-   B8          CLV
0F7F-   C4 8D       CPY   $8D
0F81-   A0 DF       LDY   #$DF
0F83-   D0 D2       BNE   $0F57
0F85-   CE D4 A0    DEC   $A0D4
0F88-   A2 C1       LDX   #$C1
0F8A-   20 D3 D4    JSR   $D4D3
0F8D-   D2 C9       CMP   ($C9)
0F8F-   CE C7 20    DEC   $20C7
0F92-   D4          ???
0F93-   C8          INY
0F94-   C1 D4       CMP   ($D4,X)
0F96-   20 D7 CF    JSR   $CFD7
0F99-   D5 CC       CMP   $CC,X
0F9B-   C4 20       CPY   $20
0F9D-   CD C1 D4    CMP   $D4C1
0FA0-   C3          ???
0FA1-   C8          INY
0FA2-   20 D4 C8    JSR   $C8D4
0FA5-   C5 20       CMP   $20
0FA7-   C1 D2       CMP   ($D2,X)
0FA9-   C7          ???
0FAA-   D5 CD       CMP   $CD,X
0FAC-   C5 CE       CMP   $CE
0FAE-   D4          ???
0FAF-   D3          ???
0FB0-   A2 AC       LDX   #$AC
0FB2-   B8          CLV
0FB3-   C4 8D       CPY   $8D
0FB5-   A0 DF       LDY   #$DF
0FB7-   D0 D2       BNE   $0F8B
0FB9-   CE D4 A0    DEC   $A0D4
0FBC-   A2 CF       LDX   #$CF
0FBE-   C6 20       DEC   $20
0FC0-   C1 20       CMP   ($20,X)
0FC2-   D4          ???
0FC3-   D9 D0 C9    CMP   $C9D0,Y
0FC6-   C3          ???
0FC7-   C1 CC       CMP   ($CC,X)
0FC9-   20 C2 D3    JSR   $D3C2
0FCC-   C1 D6       CMP   ($D6,X)
0FCE-   C5 20       CMP   $20
0FD0-   D3          ???
0FD1-   D4          ???
0FD2-   C1 D4       CMP   ($D4,X)
0FD4-   C5 CD       CMP   $CD
0FD6-   C5 CE       CMP   $CE
0FD8-   D4          ???
0FD9-   20 C9 CE    JSR   $CEC9
0FDC-   20 C4 CF    JSR   $CFC4
0FDF-   D3          ???
0FE0-   AE A2 AC    LDX   $ACA2
0FE3-   B8          CLV
0FE4-   C4 B8       CPY   $B8
0FE6-   C4 8D       CPY   $8D
0FE8-   A0 DF       LDY   #$DF
0FEA-   D0 D2       BNE   $0FBE
0FEC-   CE D4 A0    DEC   $A0D4
0FEF-   A2 C2       LDX   #$C2
0FF1-   D3          ???
0FF2-   C1 D6       CMP   ($D6,X)
0FF4-   C5 20       CMP   $20
0FF6-   A7          ???
0FF7-   D4          ???
0FF8-   C5 D3       CMP   $D3
0FFA-   D4          ???
0FFB-   AC C1 A4    LDY   $A4C1
0FFE-   B8          CLV
0FFF-   B0 B0       BCS   $0FB1
1001-   AC CC A4    LDY   $A4CC
1004-   B1 B0       LDA   ($B0),Y
1006-   B0 A7       BCS   $0FAF
1008-   20 D3 C1    JSR   $C1D3
100B-   D6 C5       DEC   $C5,X
100D-   D3          ???
100E-   20 D4 C8    JSR   $C8D4
1011-   C5 A2       CMP   $A2
1013-   AC B8 C4    LDY   $C4B8
1016-   8D A0 DF    STA   $DFA0
1019-   D0 D2       BNE   $0FED
101B-   CE D4 A0    DEC   $A0D4
101E-   A2 A4       LDX   #$A4
1020-   B1 B0       LDA   ($B0),Y
1022-   B0 20       BCS   $1044
1024-   C2          ???
1025-   D9 D4 C5    CMP   $C5D4,Y
1028-   D3          ???
1029-   20 CC CF    JSR   $CFCC
102C-   C3          ???
102D-   C1 D4       CMP   ($D4,X)
102F-   C5 C4       CMP   $C4
1031-   20 C1 D4    JSR   $D4C1
1034-   20 A4 B8    JSR   $B8A4
1037-   B0 B0       BCS   $0FE9
1039-   20 C9 CE    JSR   $CEC9
103C-   20 D4 C8    JSR   $C8D4
103F-   C5 20       CMP   $20
1041-   C6 C9       DEC   $C9
1043-   CC C5 A2    CPY   $A2C5
1046-   AC B8 C4    LDY   $C4B8
1049-   8D A0 DF    STA   $DFA0
104C-   D0 D2       BNE   $1020
104E-   CE D4 A0    DEC   $A0D4
1051-   A2 D4       LDX   #$D4
1053-   C5 D3       CMP   $D3
1055-   D4          ???
1056-   AE A2 AC    LDX   $ACA2
1059-   B8          CLV
105A-   C4 B8       CPY   $B8
105C-   C4 8D       CPY   $8D
105E-   A0 DF       LDY   #$DF
1060-   D0 D2       BNE   $1034
1062-   CE D4 A0    DEC   $A0D4
1065-   A2 CC       LDX   #$CC
1067-   C5 D4       CMP   $D4
1069-   A7          ???
106A-   D3          ???
106B-   20 D0 D5    JSR   $D5D0
106E-   D4          ???
106F-   20 D3 CF    JSR   $CFD3
1072-   CD C5 D4    CMP   $D4C5
1075-   C8          INY
1076-   C9 CE       CMP   #$CE
1078-   C7          ???
1079-   20 C9 CE    JSR   $CEC9
107C-   D4          ???
107D-   CF          ???
107E-   20 A4 B3    JSR   $B3A4
1081-   B0 B0       BCS   $1033
1083-   20 D4 CF    JSR   $CFD4
1086-   A2 AC       LDX   #$AC
1088-   B8          CLV
1089-   C4 8D       CPY   $8D
108B-   A0 DF       LDY   #$DF
108D-   D0 D2       BNE   $1061
108F-   CE D4 A0    DEC   $A0D4
1092-   A2 D4       LDX   #$D4
1094-   C5 D3       CMP   $D3
1096-   D4          ???
1097-   20 C9 D4    JSR   $D4C9
109A-   20 CF D5    JSR   $D5CF
109D-   D4          ???
109E-   AE A2 AC    LDX   $ACA2
10A1-   B8          CLV
10A2-   C4 B8       CPY   $B8
10A4-   C4 8D       CPY   $8D
10A6-   A0 CC       LDY   #$CC
10A8-   C4 D9       CPY   $D9
10AA-   A0 A3       LDY   #$A3
10AC-   B0 8D       BCS   $103B
10AE-   CC D0 8D    CPY   $8DD0
10B1-   A0 D4       LDY   #$D4
10B3-   D9 C1 8D    CMP   $8DC1,Y
10B6-   A0 D3       LDY   #$D3
10B8-   D4          ???
10B9-   C1 A0       CMP   ($A0,X)
10BB-   A4 B8       LDY   $B8
10BD-   B0 B0       BCS   $106F
10BF-   AC D9 8D    LDY   $8DD9
10C2-   A0 C9       LDY   #$C9
10C4-   CE D9 8D    DEC   $8DD9
10C7-   A0 C3       LDY   #$C3
10C9-   D0 D9       BNE   $10A4
10CB-   A0 A3       LDY   #$A3
10CD-   A4 B1       LDY   $B1
10CF-   B0 B0       BCS   $1081
10D1-   8D A0 C2    STA   $C2A0
10D4-   CE C5 A0    DEC   $A0C5
10D7-   CC D0 8D    CPY   $8DD0
10DA-   A0 DF       LDY   #$DF
10DC-   D7          ???
10DD-   C1 C9       CMP   ($C9,X)
10DF-   D4          ???
10E0-   8D A0 DF    STA   $DFA0
10E3-   C4 D5       CPY   $D5
10E5-   CD D0 A0    CMP   $A0D0
10E8-   A4 B8       LDY   $B8
10EA-   B0 B0       BCS   $109C
10EC-   BB          ???
10ED-   A3          ???
10EE-   A4 B1       LDY   $B1
10F0-   B0 B0       BCS   $10A2
10F2-   8D A0 DF    STA   $DFA0
10F5-   D7          ???
10F6-   C1 C9       CMP   ($C9,X)
10F8-   D4          ???
10F9-   8D A0 DF    STA   $DFA0
10FC-   D0 D2       BNE   $10D0
10FE-   CE D4 20    DEC   $20D4
1101-   A2 C2       LDX   #$C2
1103-   D3          ???
1104-   C1 D6       CMP   ($D6,X)
1106-   C5 20       CMP   $20
1108-   A7          ???
1109-   D4          ???
110A-   C5 D3       CMP   $D3
110C-   D4          ???
110D-   AC C1 A4    LDY   $A4C1
1110-   B8          CLV
1111-   B0 B0       BCS   $10C3
1113-   AC CC A4    LDY   $A4CC
1116-   B1 B0       LDA   ($B0),Y
1118-   B0 A7       BCS   $10C1
111A-   AE AE AE    LDX   $AEAE
111D-   AE A2 8D    LDX   $8DA2
1120-   A0 C2       LDY   #$C2
1122-   D3          ???
1123-   C1 D6       CMP   ($D6,X)
1125-   C5 20       CMP   $20
1127-   A2 D4       LDX   #$D4
1129-   C5 D3       CMP   $D3
112B-   D4          ???
112C-   AC C1 A4    LDY   $A4C1
112F-   B8          CLV
1130-   B0 B0       BCS   $10E2
1132-   AC CC A4    LDY   $A4CC
1135-   B1 B0       LDA   ($B0),Y
1137-   B0 A2       BCS   $10DB
1139-   8D A0 DF    STA   $DFA0
113C-   D0 D2       BNE   $1110
113E-   CE D4 A0    DEC   $A0D4
1141-   A2 C4       LDX   #$C4
1143-   CF          ???
1144-   CE C5 A1    DEC   $A1C5
1147-   A2 AC       LDX   #$AC
1149-   B8          CLV
114A-   C4 B8       CPY   $B8
114C-   C4 8D       CPY   $8D
114E-   A0 DF       LDY   #$DF
1150-   D0 D2       BNE   $1124
1152-   CE D4 A0    DEC   $A0D4
1155-   A2 CE       LDX   #$CE
1157-   CF          ???
1158-   D7          ???
1159-   20 CC C5    JSR   $C5CC
115C-   D4          ???
115D-   A7          ???
115E-   D3          ???
115F-   20 C3 CC    JSR   $CCC3
1162-   C5 C1       CMP   $C1
1164-   D2 20       CMP   ($20)
1166-   A4 B1       LDY   $B1
1168-   B0 B0       BCS   $111A
116A-   20 C2 D9    JSR   $D9C2
116D-   D4          ???
116E-   C5 D3       CMP   $D3
1170-   20 C1 D4    JSR   $D4C1
1173-   A2 AC       LDX   #$AC
1175-   B8          CLV
1176-   C4 8D       CPY   $8D
1178-   A0 DF       LDY   #$DF
117A-   D0 D2       BNE   $114E
117C-   CE D4 A0    DEC   $A0D4
117F-   A2 A4       LDX   #$A4
1181-   B8          CLV
1182-   B0 B0       BCS   $1134
1184-   20 C2 C5    JSR   $C5C2
1187-   C6 CF       DEC   $CF
1189-   D2 C5       CMP   ($C5)
118B-   20 D7 C5    JSR   $C5D7
118E-   20 D2 C5    JSR   $C5D2
1191-   CC CF C1    CPY   $C1CF
1194-   C4 20       CPY   $20
1196-   C9 D4       CMP   #$D4
1198-   20 D7 C9    JSR   $C9D7
119B-   D4          ???
119C-   C8          INY
119D-   20 C2 CC    JSR   $CCC2
11A0-   CF          ???
11A1-   C1 C4       CMP   ($C4,X)
11A3-   AE A2 AC    LDX   $ACA2
11A6-   B8          CLV
11A7-   C4 B8       CPY   $B8
11A9-   C4 8D       CPY   $8D
11AB-   A0 CC       LDY   #$CC
11AD-   C4 D9       CPY   $D9
11AF-   A0 A3       LDY   #$A3
11B1-   B0 8D       BCS   $1140
11B3-   CC D0 B2    CPY   $B2D0
11B6-   8D A0 CC    STA   $CCA0
11B9-   C4 C1       CPY   $C1
11BB-   A0 A3       LDY   #$A3
11BD-   B0 8D       BCS   $114C
11BF-   A0 D3       LDY   #$D3
11C1-   D4          ???
11C2-   C1 A0       CMP   ($A0,X)
11C4-   A4 B8       LDY   $B8
11C6-   B0 B0       BCS   $1178
11C8-   AC D9 8D    LDY   $8DD9
11CB-   A0 C9       LDY   #$C9
11CD-   CE D9 8D    DEC   $8DD9
11D0-   A0 C3       LDY   #$C3
11D2-   D0 D9       BNE   $11AD
11D4-   A0 A3       LDY   #$A3
11D6-   A4 B1       LDY   $B1
11D8-   B0 B0       BCS   $118A
11DA-   8D A0 C2    STA   $C2A0
11DD-   CE C5 A0    DEC   $A0C5
11E0-   CC D0 B2    CPY   $B2D0
11E3-   8D A0 DF    STA   $DFA0
11E6-   C4 D5       CPY   $D5
11E8-   CD D0 A0    CMP   $A0D0
11EB-   A4 B8       LDY   $B8
11ED-   B0 B0       BCS   $119F
11EF-   BB          ???
11F0-   A3          ???
11F1-   A4 B1       LDY   $B1
11F3-   B0 B0       BCS   $11A5
11F5-   8D AA 8D    STA   $8DAA
11F8-   A0 DF       LDY   #$DF
11FA-   D0 D2       BNE   $11CE
11FC-   CE D4 A0    DEC   $A0D4
11FF-   A2 20       LDX   #$20
1201-   A2 AC       LDX   #$AC
1203-   B8          CLV
1204-   C4 B8       CPY   $B8
1206-   C4 8D       CPY   $8D
1208-   A0 DF       LDY   #$DF
120A-   D0 D2       BNE   $11DE
120C-   CE D4 A0    DEC   $A0D4
120F-   A2 CE       LDX   #$CE
1211-   CF          ???
1212-   D7          ???
1213-   20 D7 C5    JSR   $C5D7
1216-   20 C3 C1    JSR   $C1C3
1219-   CE 20 C2    DEC   $C220
121C-   CC CF C1    CPY   $C1CF
121F-   C4 20       CPY   $20
1221-   D4          ???
1222-   C5 D3       CMP   $D3
1224-   D4          ???
1225-   20 D4 CF    JSR   $CFD4
1228-   20 C7 C5    JSR   $C5C7
122B-   D4          ???
122C-   20 A4 B8    JSR   $B8A4
122F-   B0 B0       BCS   $11E1
1231-   A2 AC       LDX   #$AC
1233-   B8          CLV
1234-   C4 8D       CPY   $8D
1236-   A0 DF       LDY   #$DF
1238-   D0 D2       BNE   $120C
123A-   CE D4 A0    DEC   $A0D4
123D-   A2 C2       LDX   #$C2
123F-   C1 C3       CMP   ($C3,X)
1241-   CB          ???
1242-   20 C9 CE    JSR   $CEC9
1245-   D4          ???
1246-   CF          ???
1247-   20 D4 C8    JSR   $C8D4
124A-   C5 20       CMP   $20
124C-   D3          ???
124D-   D4          ???
124E-   C1 D4       CMP   ($D4,X)
1250-   C5 20       CMP   $20
1252-   D7          ???
1253-   C5 20       CMP   $20
1255-   D0 D5       BNE   $122C
1257-   D4          ???
1258-   20 C9 D4    JSR   $D4C9
125B-   AE A2 AC    LDX   $ACA2
125E-   B8          CLV
125F-   C4 B8       CPY   $B8
1261-   C4 8D       CPY   $8D
1263-   A0 DF       LDY   #$DF
1265-   D0 D2       BNE   $1239
1267-   CE D4 A0    DEC   $A0D4
126A-   A2 C2       LDX   #$C2
126C-   CC CF C1    CPY   $C1CF
126F-   C4 20       CPY   $20
1271-   A7          ???
1272-   D4          ???
1273-   C5 D3       CMP   $D3
1275-   D4          ???
1276-   A7          ???
1277-   AE AE AE    LDX   $AEAE
127A-   A2 AC       LDX   #$AC
127C-   B8          CLV
127D-   C4 8D       CPY   $8D
127F-   A0 DF       LDY   #$DF
1281-   D7          ???
1282-   C1 C9       CMP   ($C9,X)
1284-   D4          ???
1285-   8D A0 C2    STA   $C2A0
1288-   CC CF C1    CPY   $C1CF
128B-   C4 A0       CPY   $A0
128D-   A2 D4       LDX   #$D4
128F-   C5 D3       CMP   $D3
1291-   D4          ???
1292-   A2 8D       LDX   #$8D
1294-   A0 DF       LDY   #$DF
1296-   D0 D2       BNE   $126A
1298-   CE D4 A0    DEC   $A0D4
129B-   A2 20       LDX   #$20
129D-   A2 AC       LDX   #$AC
129F-   B8          CLV
12A0-   C4 B8       CPY   $B8
12A2-   C4 8D       CPY   $8D
12A4-   A0 DF       LDY   #$DF
12A6-   D0 D2       BNE   $127A
12A8-   CE D4 A0    DEC   $A0D4
12AB-   A2 C4       LDX   #$C4
12AD-   CF          ???
12AE-   CE C5 A1    DEC   $A1C5
12B1-   A2 AC       LDX   #$AC
12B3-   B8          CLV
12B4-   C4 B8       CPY   $B8
12B6-   C4 8D       CPY   $8D
12B8-   A0 DF       LDY   #$DF
12BA-   C4 D5       CPY   $D5
12BC-   CD D0 A0    CMP   $A0D0
12BF-   A4 B0       LDY   $B0
12C1-   B8          CLV
12C2-   B0 B0       BCS   $1274
12C4-   BB          ???
12C5-   A3          ???
12C6-   A4 B1       LDY   $B1
12C8-   B0 B0       BCS   $127A
12CA-   8D A0 DF    STA   $DFA0
12CD-   D0 D2       BNE   $12A1
12CF-   CE D4 A0    DEC   $A0D4
12D2-   A2 20       LDX   #$20
12D4-   A2 AC       LDX   #$AC
12D6-   B8          CLV
12D7-   C4 B8       CPY   $B8
12D9-   C4 8D       CPY   $8D
12DB-   A0 DF       LDY   #$DF
12DD-   D7          ???
12DE-   C1 C9       CMP   ($C9,X)
12E0-   D4          ???
12E1-   8D AA 8D    STA   $8DAA
12E4-   A0 DF       LDY   #$DF
12E6-   D0 D2       BNE   $12BA
12E8-   CE D4 A0    DEC   $A0D4
12EB-   A2 D4       LDX   #$D4
12ED-   C8          INY
12EE-   C5 20       CMP   $20
12F0-   C3          ???
12F1-   CD C4 20    CMP   $20C4
12F4-   CD C1 C3    CMP   $C3C1
12F7-   D2 CF       CMP   ($CF)
12F9-   20 D3 C9    JSR   $C9D3
12FC-   CD D0 CC    CMP   $CCD0
12FF-   D9 20 C5    CMP   $C520,Y
1302-   D8          CLD
1303-   C5 C3       CMP   $C3
1305-   D5 D4       CMP   $D4,X
1307-   C5 D3       CMP   $D3
1309-   20 C1 A2    JSR   $A2C1
130C-   AC B8 C4    LDY   $C4B8
130F-   8D A0 DF    STA   $DFA0
1312-   D0 D2       BNE   $12E6
1314-   CE D4 A0    DEC   $A0D4
1317-   A2 C4       LDX   #$C4
1319-   CF          ???
131A-   D3          ???
131B-   20 C3 CF    JSR   $CFC3
131E-   CD CD C1    CMP   $C1CD
1321-   CE C4 AC    DEC   $ACC4
1324-   20 C1 CC    JSR   $CCC1
1327-   CF          ???
1328-   CE C7 20    DEC   $20C7
132B-   D7          ???
132C-   C9 D4       CMP   #$D4
132E-   C8          INY
132F-   20 C1 CE    JSR   $CEC1
1332-   D9 20 C1    CMP   $C120,Y
1335-   D2 C7       CMP   ($C7)
1337-   D5 CD       CMP   $CD,X
1339-   C5 CE       CMP   $CE
133B-   D4          ???
133C-   D3          ???
133D-   A2 AC       LDX   #$AC
133F-   B8          CLV
1340-   C4 8D       CPY   $8D
1342-   A0 DF       LDY   #$DF
1344-   D0 D2       BNE   $1318
1346-   CE D4 A0    DEC   $A0D4
1349-   A2 D0       LDX   #$D0
134B-   C1 D3       CMP   ($D3,X)
134D-   D3          ???
134E-   C5 C4       CMP   $C4
1350-   20 D4 CF    JSR   $CFD4
1353-   20 C9 D4    JSR   $D4C9
1356-   AE 20 C3    LDX   $C320
1359-   CD C4 20    CMP   $20C4
135C-   A7          ???
135D-   C3          ???
135E-   C1 D4       CMP   ($D4,X)
1360-   C1 CC       CMP   ($CC,X)
1362-   CF          ???
1363-   C7          ???
1364-   A7          ???
1365-   AC 20 C6    LDY   $C620
1368-   CF          ???
1369-   D2 20       CMP   ($20)
136B-   C9 CE       CMP   #$CE
136D-   D3          ???
136E-   D4          ???
136F-   C1 CE       CMP   ($CE,X)
1371-   C3          ???
1372-   C5 AC       CMP   $AC
1374-   A2 AC       LDX   #$AC
1376-   B8          CLV
1377-   C4 8D       CPY   $8D
1379-   A0 DF       LDY   #$DF
137B-   D0 D2       BNE   $134F
137D-   CE D4 A0    DEC   $A0D4
1380-   A2 D2       LDX   #$D2
1382-   C5 D4       CMP   $D4
1384-   D5 D2       CMP   $D2,X
1386-   CE D3 BA    DEC   $BAD3
1389-   A2 AC       LDX   #$AC
138B-   B8          CLV
138C-   C4 B8       CPY   $B8
138E-   C4 8D       CPY   $8D
1390-   A0 DF       LDY   #$DF
1392-   D7          ???
1393-   C1 C9       CMP   ($C9,X)
1395-   D4          ???
1396-   8D A0 C3    STA   $C3A0
1399-   CD C4 A0    CMP   $A0C4
139C-   A2 C3       LDX   #$C3
139E-   C1 D4       CMP   ($D4,X)
13A0-   C1 CC       CMP   ($CC,X)
13A2-   CF          ???
13A3-   C7          ???
13A4-   A2 8D       LDX   #$8D
13A6-   A0 DF       LDY   #$DF
13A8-   D7          ???
13A9-   C1 C9       CMP   ($C9,X)
13AB-   D4          ???
13AC-   8D AA 8D    STA   $8DAA
13AF-   A0 DF       LDY   #$DF
13B1-   D0 D2       BNE   $1385
13B3-   CE D4 A0    DEC   $A0D4
13B6-   A2 20       LDX   #$20
13B8-   A2 AC       LDX   #$AC
13BA-   B8          CLV
13BB-   C4 B8       CPY   $B8
13BD-   C4 B8       CPY   $B8
13BF-   C4 8D       CPY   $8D
13C1-   A0 DF       LDY   #$DF
13C3-   D0 D2       BNE   $1397
13C5-   CE D4 A0    DEC   $A0D4
13C8-   A2 D4       LDX   #$D4
13CA-   D9 D0 C9    CMP   $C9D0,Y
13CD-   C3          ???
13CE-   C1 CC       CMP   ($CC,X)
13D0-   CC D9 AC    CPY   $ACD9
13D3-   20 D4 C8    JSR   $C8D4
13D6-   C5 20       CMP   $20
13D8-   C3          ???
13D9-   CD C4 20    CMP   $20C4
13DC-   CD C1 C3    CMP   $C3C1
13DF-   D2 CF       CMP   ($CF)
13E1-   20 C9 D3    JSR   $D3C9
13E4-   20 C1 CC    JSR   $CCC1
13E7-   D3          ???
13E8-   CF          ???
13E9-   A2 AC       LDX   #$AC
13EB-   B8          CLV
13EC-   C4 8D       CPY   $8D
13EE-   A0 DF       LDY   #$DF
13F0-   D0 D2       BNE   $13C4
13F2-   CE D4 A0    DEC   $A0D4
13F5-   A2 D5       LDX   #$D5
13F7-   D3          ???
13F8-   C5 C4       CMP   $C4
13FA-   20 C6 CF    JSR   $CFC6
13FD-   D2 20       CMP   ($20)
13FF-   D0 D2       BNE   $13D3
1401-   C5 D0       CMP   $D0
1403-   C1 D2       CMP   ($D2,X)
1405-   C9 CE       CMP   #$CE
1407-   C7          ???
1408-   20 D4 CF    JSR   $CFD4
140B-   20 D2 C5    JSR   $C5D2
140E-   C1 C4       CMP   ($C4,X)
1410-   20 CF D2    JSR   $D2CF
1413-   20 D7 D2    JSR   $D2D7
1416-   C9 D4       CMP   #$D4
1418-   C5 A2       CMP   $A2
141A-   AC B8 C4    LDY   $C4B8
141D-   8D A0 DF    STA   $DFA0
1420-   D0 D2       BNE   $13F4
1422-   CE D4 A0    DEC   $A0D4
1425-   A2 D4       LDX   #$D4
1427-   C5 D8       CMP   $D8
1429-   D4          ???
142A-   20 C6 C9    JSR   $C9C6
142D-   CC C5 D3    CPY   $D3C5
1430-   AE 20 C8    LDX   $C820
1433-   CF          ???
1434-   D7          ???
1435-   C5 D6       CMP   $D6
1437-   C5 D2       CMP   $D2
1439-   AC 20 C2    LDY   $C220
143C-   C5 C6       CMP   $C6
143E-   CF          ???
143F-   D2 C5       CMP   ($C5)
1441-   20 D4 C8    JSR   $C8D4
1444-   C9 D3       CMP   #$D3
1446-   20 C3 C1    JSR   $C1C3
1449-   CE A2 AC    DEC   $ACA2
144C-   B8          CLV
144D-   C4 8D       CPY   $8D
144F-   A0 DF       LDY   #$DF
1451-   D0 D2       BNE   $1425
1453-   CE D4 A0    DEC   $A0D4
1456-   A2 C2       LDX   #$C2
1458-   C5 20       CMP   $20
145A-   C1 C3       CMP   ($C3,X)
145C-   C3          ???
145D-   CF          ???
145E-   CD D0 CC    CMP   $CCD0
1461-   C9 D3       CMP   #$D3
1463-   C8          INY
1464-   C5 C4       CMP   $C4
1466-   AC 20 D4    LDY   $D420
1469-   C8          INY
146A-   C5 20       CMP   $20
146C-   D4          ???
146D-   CD CF C4    CMP   $C4CF
1470-   C5 20       CMP   $20
1472-   CD C1 C3    CMP   $C3C1
1475-   D2 CF       CMP   ($CF)
1477-   A2 AC       LDX   #$AC
1479-   B8          CLV
147A-   C4 8D       CPY   $8D
147C-   A0 DF       LDY   #$DF
147E-   D0 D2       BNE   $1452
1480-   CE D4 A0    DEC   $A0D4
1483-   A2 CD       LDX   #$CD
1485-   D5 D3       CMP   $D3,X
1487-   D4          ???
1488-   20 C2 C5    JSR   $C5C2
148B-   20 D2 D5    JSR   $D5D2
148E-   CE 20 D4    DEC   $D420
1491-   CF          ???
1492-   20 D4 D2    JSR   $D2D4
1495-   C9 C3       CMP   #$C3
1497-   CB          ???
1498-   20 C1 D0    JSR   $D0C1
149B-   D0 CC       BNE   $1469
149D-   C5 D3       CMP   $D3
149F-   CF          ???
14A0-   C6 D4       DEC   $D4
14A2-   20 C9 CE    JSR   $CEC9
14A5-   D4          ???
14A6-   CF          ???
14A7-   A2 AC       LDX   #$AC
14A9-   B8          CLV
14AA-   C4 8D       CPY   $8D
14AC-   A0 DF       LDY   #$DF
14AE-   D0 D2       BNE   $1482
14B0-   CE D4 A0    DEC   $A0D4
14B3-   A2 C2       LDX   #$C2
14B5-   C5 CC       CMP   $CC
14B7-   C9 C5       CMP   #$C5
14B9-   D6 C9       DEC   $C9,X
14BB-   CE C7 20    DEC   $20C7
14BE-   C9 D4       CMP   #$D4
14C0-   20 C9 D3    JSR   $D3C9
14C3-   CE A7 D4    DEC   $D4A7
14C6-   20 C9 CE    JSR   $CEC9
14C9-   20 C9 CD    JSR   $CDC9
14CC-   CD C5 C4    CMP   $C4C5
14CF-   C9 C1       CMP   #$C1
14D1-   D4          ???
14D2-   C5 20       CMP   $20
14D4-   CD CF C4    CMP   $C4CF
14D7-   C5 AE       CMP   $AE
14D9-   A2 AC       LDX   #$AC
14DB-   B8          CLV
14DC-   C4 B8       CPY   $B8
14DE-   C4 8D       CPY   $8D
14E0-   A0 DF       LDY   #$DF
14E2-   D0 D2       BNE   $14B6
14E4-   CE D4 A0    DEC   $A0D4
14E7-   A2 D4       LDX   #$D4
14E9-   CD CF C4    CMP   $C4CF
14EC-   C5 20       CMP   $20
14EE-   C8          INY
14EF-   C1 D3       CMP   ($D3,X)
14F1-   20 CE CF    JSR   $CFCE
14F4-   20 C1 D2    JSR   $D2C1
14F7-   C7          ???
14F8-   D5 CD       CMP   $CD,X
14FA-   C5 CE       CMP   $CE
14FC-   D4          ???
14FD-   D3          ???
14FE-   AE 20 D4    LDX   $D420
1501-   C8          INY
1502-   D5 D3       CMP   $D3,X
1504-   AC 20 D4    LDY   $D420
1507-   C8          INY
1508-   C5 A2       CMP   $A2
150A-   AC B8 C4    LDY   $C4B8
150D-   8D A0 DF    STA   $DFA0
1510-   D0 D2       BNE   $14E4
1512-   CE D4 A0    DEC   $A0D4
1515-   A2 C6       LDX   #$C6
1517-   CF          ???
1518-   CC CC CF    CPY   $CFCC
151B-   D7          ???
151C-   C9 CE       CMP   #$CE
151E-   C7          ???
151F-   20 D0 D2    JSR   $D2D0
1522-   C5 D0       CMP   $D0
1524-   C1 D2       CMP   ($D2,X)
1526-   C5 D3       CMP   $D3
1528-   20 D5 D3    JSR   $D3D5
152B-   20 D4 CF    JSR   $CFD4
152E-   20 CF D0    JSR   $D0CF
1531-   C5 CE       CMP   $CE
1533-   20 C1 20    JSR   $20C1
1536-   D4          ???
1537-   C5 D8       CMP   $D8
1539-   D4          ???
153A-   A2 AC       LDX   #$AC
153C-   B8          CLV
153D-   C4 8D       CPY   $8D
153F-   A0 DF       LDY   #$DF
1541-   D0 D2       BNE   $1515
1543-   CE D4 A0    DEC   $A0D4
1546-   A2 C6       LDX   #$C6
1548-   C9 CC       CMP   #$CC
154A-   C5 20       CMP   $20
154C-   D4          ???
154D-   CF          ???
154E-   20 C2 C5    JSR   $C5C2
1551-   20 D7 D2    JSR   $D2D7
1554-   C9 D4       CMP   #$D4
1556-   D4          ???
1557-   C5 CE       CMP   $CE
1559-   20 D4 CF    JSR   $CFD4
155C-   BA          TSX
155D-   A2 AC       LDX   #$AC
155F-   B8          CLV
1560-   C4 B8       CPY   $B8
1562-   C4 8D       CPY   $8D
1564-   A0 DF       LDY   #$DF
1566-   D0 D2       BNE   $153A
1568-   CE D4 A0    DEC   $A0D4
156B-   A2 D4       LDX   #$D4
156D-   CD C4 CF    CMP   $CFC4
1570-   C5 A2       CMP   $A2
1572-   AC B8 C4    LDY   $C4B8
1575-   8D A0 DF    STA   $DFA0
1578-   D0 D2       BNE   $154C
157A-   CE D4 A0    DEC   $A0D4
157D-   A2 C3       LDX   #$C3
157F-   CD C4 20    CMP   $20C4
1582-   A7          ???
1583-   CF          ???
1584-   D0 C5       BNE   $154B
1586-   CE 20 D4    DEC   $D420
1589-   AE D4 C5    LDX   $C5D4
158C-   D8          CLD
158D-   D4          ???
158E-   C6 C9       DEC   $C9
1590-   CC C5 A7    CPY   $A7C5
1593-   A2 AC       LDX   #$AC
1595-   B8          CLV
1596-   C4 8D       CPY   $8D
1598-   A0 DF       LDY   #$DF
159A-   D0 D2       BNE   $156E
159C-   CE D4 A0    DEC   $A0D4
159F-   A2 C3       LDX   #$C3
15A1-   CD C4 20    CMP   $20C4
15A4-   A7          ???
15A5-   D7          ???
15A6-   D2 C9       CMP   ($C9)
15A8-   D4          ???
15A9-   C5 20       CMP   $20
15AB-   D4          ???
15AC-   AE D4 C5    LDX   $C5D4
15AF-   D8          CLD
15B0-   D4          ???
15B1-   C6 C9       DEC   $C9
15B3-   CC C5 A7    CPY   $A7C5
15B6-   A2 AC       LDX   #$AC
15B8-   B8          CLV
15B9-   C4 B8       CPY   $B8
15BB-   C4 8D       CPY   $8D
15BD-   A0 DF       LDY   #$DF
15BF-   D7          ???
15C0-   C1 C9       CMP   ($C9,X)
15C2-   D4          ???
15C3-   8D AA 8D    STA   $8DAA
15C6-   A0 DF       LDY   #$DF
15C8-   D0 D2       BNE   $159C
15CA-   CE D4 A0    DEC   $A0D4
15CD-   A2 D7       LDX   #$D7
15CF-   C5 20       CMP   $20
15D1-   C3          ???
15D2-   C1 CE       CMP   ($CE,X)
15D4-   20 CE CF    JSR   $CFCE
15D7-   D7          ???
15D8-   20 D0 D2    JSR   $D2D0
15DB-   C9 CE       CMP   #$CE
15DD-   D4          ???
15DE-   20 D4 CF    JSR   $CFD4
15E1-   20 D4 C8    JSR   $C8D4
15E4-   C9 D3       CMP   #$D3
15E6-   20 C6 C9    JSR   $C9C6
15E9-   CC C5 20    CPY   $20C5
15EC-   D7          ???
15ED-   C9 D4       CMP   #$D4
15EF-   C8          INY
15F0-   A2 AC       LDX   #$AC
15F2-   B8          CLV
15F3-   C4 8D       CPY   $8D
15F5-   A0 DF       LDY   #$DF
15F7-   D0 D2       BNE   $15CB
15F9-   CE D4 A0    DEC   $A0D4
15FC-   A2 D4       LDX   #$D4
15FE-   C8          INY
15FF-   C5 20       CMP   $20
1601-   C6 D0       DEC   $D0
1603-   D2 CE       CMP   ($CE)
1605-   20 CD C1    JSR   $C1CD
1608-   C3          ???
1609-   D2 CF       CMP   ($CF)
160B-   AE 20 D4    LDX   $D420
160E-   C8          INY
160F-   C9 D3       CMP   #$D3
1611-   20 CD C1    JSR   $C1CD
1614-   C3          ???
1615-   D2 CF       CMP   ($CF)
1617-   20 C5 C9    JSR   $C9C5
161A-   D4          ???
161B-   C8          INY
161C-   C5 D2       CMP   $D2
161E-   A2 AC       LDX   #$AC
1620-   B8          CLV
1621-   C4 8D       CPY   $8D
1623-   A0 DF       LDY   #$DF
1625-   D0 D2       BNE   $15F9
1627-   CE D4 A0    DEC   $A0D4
162A-   A2 D0       LDX   #$D0
162C-   D2 C9       CMP   ($C9)
162E-   CE D4 D3    DEC   $D3D4
1631-   20 C1 20    JSR   $20C1
1634-   C7          ???
1635-   C9 D6       CMP   #$D6
1637-   C5 CE       CMP   $CE
1639-   20 CC C9    JSR   $C9CC
163C-   CE C5 20    DEC   $20C5
163F-   CF          ???
1640-   C6 20       DEC   $20
1642-   D4          ???
1643-   C5 D8       CMP   $D8
1645-   D4          ???
1646-   20 D4 CF    JSR   $CFD4
1649-   20 D4 C8    JSR   $C8D4
164C-   C5 20       CMP   $20
164E-   C6 C9       DEC   $C9
1650-   CC C5 AC    CPY   $ACC5
1653-   A2 AC       LDX   #$AC
1655-   B8          CLV
1656-   C4 8D       CPY   $8D
1658-   A0 DF       LDY   #$DF
165A-   D0 D2       BNE   $162E
165C-   CE D4 A0    DEC   $A0D4
165F-   A2 C6       LDX   #$C6
1661-   CF          ???
1662-   CC CC CF    CPY   $CFCC
1665-   D7          ???
1666-   C5 C4       CMP   $C4
1668-   20 C2 D9    JSR   $D9C2
166B-   20 C1 20    JSR   $20C1
166E-   D2 C5       CMP   ($C5)
1670-   D4          ???
1671-   D5 D2       CMP   $D2,X
1673-   CE 20 A8    DEC   $A820
1676-   A4 B8       LDY   $B8
1678-   C4 A9       CPY   $A9
167A-   AC 20 CF    LDY   $CF20
167D-   D2 20       CMP   ($20)
167F-   D0 D2       BNE   $1653
1681-   C9 CE       CMP   #$CE
1683-   D4          ???
1684-   D3          ???
1685-   A2 AC       LDX   #$AC
1687-   B8          CLV
1688-   C4 8D       CPY   $8D
168A-   A0 DF       LDY   #$DF
168C-   D0 D2       BNE   $1660
168E-   CE D4 A0    DEC   $A0D4
1691-   A2 D4       LDX   #$D4
1693-   C8          INY
1694-   C5 20       CMP   $20
1696-   C3          ???
1697-   C8          INY
1698-   C1 D2       CMP   ($D2,X)
169A-   C1 C3       CMP   ($C3,X)
169C-   D4          ???
169D-   C5 D2       CMP   $D2
169F-   D3          ???
16A0-   20 C9 CE    JSR   $CEC9
16A3-   20 C1 20    JSR   $20C1
16A6-   D3          ???
16A7-   D4          ???
16A8-   D2 C9       CMP   ($C9)
16AA-   CE C7 20    DEC   $20C7
16AD-   C1 D4       CMP   ($D4,X)
16AF-   20 C1 20    JSR   $20C1
16B2-   C7          ???
16B3-   C9 D6       CMP   #$D6
16B5-   C5 CE       CMP   $CE
16B7-   A2 AC       LDX   #$AC
16B9-   B8          CLV
16BA-   C4 8D       CPY   $8D
16BC-   A0 DF       LDY   #$DF
16BE-   D0 D2       BNE   $1692
16C0-   CE D4 A0    DEC   $A0D4
16C3-   A2 C1       LDX   #$C1
16C5-   C4 C4       CPY   $C4
16C7-   D2 C5       CMP   ($C5)
16C9-   D3          ???
16CA-   D3          ???
16CB-   AE 20 C9    LDX   $C920
16CE-   CE 20 D4    DEC   $D420
16D1-   C8          INY
16D2-   C5 20       CMP   $20
16D4-   CC C1 D4    CPY   $D4C1
16D7-   D4          ???
16D8-   C5 D2       CMP   $D2
16DA-   20 C3 C1    JSR   $C1C3
16DD-   D3          ???
16DE-   C5 AC       CMP   $AC
16E0-   20 D4 C8    JSR   $C8D4
16E3-   C5 20       CMP   $20
16E5-   CC C5 CE    CPY   $CEC5
16E8-   C7          ???
16E9-   D4          ???
16EA-   C8          INY
16EB-   A2 AC       LDX   #$AC
16ED-   B8          CLV
16EE-   C4 8D       CPY   $8D
16F0-   A0 DF       LDY   #$DF
16F2-   D0 D2       BNE   $16C6
16F4-   CE D4 A0    DEC   $A0D4
16F7-   A2 CF       LDX   #$CF
16F9-   C6 20       DEC   $20
16FB-   D4          ???
16FC-   C8          INY
16FD-   C5 20       CMP   $20
16FF-   D3          ???
1700-   D4          ???
1701-   D2 C9       CMP   ($C9)
1703-   CE C7 20    DEC   $20C7
1706-   C9 D3       CMP   #$D3
1708-   20 CE CF    JSR   $CFCE
170B-   D4          ???
170C-   20 D0 D2    JSR   $D2D0
170F-   C5 D3       CMP   $D3
1711-   C5 D2       CMP   $D2
1713-   D6 C5       DEC   $C5,X
1715-   C4 BB       CPY   $BB
1717-   20 CF CE    JSR   $CECF
171A-   CC D9 A2    CPY   $A2D9
171D-   AC B8 C4    LDY   $C4B8
1720-   8D A0 DF    STA   $DFA0
1723-   D0 D2       BNE   $16F7
1725-   CE D4 A0    DEC   $A0D4
1728-   A2 D4       LDX   #$D4
172A-   C8          INY
172B-   C5 20       CMP   $20
172D-   C1 D3       CMP   ($D3,X)
172F-   C3          ???
1730-   C9 C9       CMP   #$C9
1732-   20 C9 D3    JSR   $D3C9
1735-   AE A2 AC    LDX   $ACA2
1738-   B8          CLV
1739-   C4 B8       CPY   $B8
173B-   C4 8D       CPY   $8D
173D-   A0 DF       LDY   #$DF
173F-   D0 D2       BNE   $1713
1741-   CE D4 A0    DEC   $A0D4
1744-   A2 C6       LDX   #$C6
1746-   D0 D2       BNE   $171A
1748-   CE 20 A7    DEC   $A720
174B-   C1 CC       CMP   ($CC,X)
174D-   CC 20 C9    CPY   $C920
1750-   D3          ???
1751-   20 D7 C5    JSR   $C5D7
1754-   CC CC 20    CPY   $20CC
1757-   D4          ???
1758-   C8          INY
1759-   C1 D4       CMP   ($D4,X)
175B-   20 C5 CE    JSR   $CEC5
175E-   C4 D3       CPY   $D3
1760-   20 D7 C5    JSR   $C5D7
1763-   CC CC AE    CPY   $AECC
1766-   A7          ???
1767-   A2 AC       LDX   #$AC
1769-   B8          CLV
176A-   C4 8D       CPY   $8D
176C-   A0 DF       LDY   #$DF
176E-   D0 D2       BNE   $1742
1770-   CE D4 A0    DEC   $A0D4
1773-   A2 C6       LDX   #$C6
1775-   D0 D2       BNE   $1749
1777-   CE 20 D2    DEC   $D220
177A-   C5 D4       CMP   $D4
177C-   CF          ???
177D-   D2 D4       CMP   ($D4)
177F-   A2 AC       LDX   #$AC
1781-   B8          CLV
1782-   C4 B8       CPY   $B8
1784-   C4 8D       CPY   $8D
1786-   A0 D4       LDY   #$D4
1788-   CD CF C4    CMP   $C4CF
178B-   C5 8D       CMP   $8D
178D-   A0 C3       LDY   #$C3
178F-   CD C4 A0    CMP   $A0C4
1792-   A2 CF       LDX   #$CF
1794-   D0 C5       BNE   $175B
1796-   CE 20 D4    DEC   $D420
1799-   AE D4 C5    LDX   $C5D4
179C-   D8          CLD
179D-   D4          ???
179E-   C6 C9       DEC   $C9
17A0-   CC C5 A2    CPY   $A2C5
17A3-   8D A0 C3    STA   $C3A0
17A6-   CD C4 A0    CMP   $A0C4
17A9-   A2 D7       LDX   #$D7
17AB-   D2 C9       CMP   ($C9)
17AD-   D4          ???
17AE-   C5 20       CMP   $20
17B0-   D4          ???
17B1-   AE D4 C5    LDX   $C5D4
17B4-   D8          CLD
17B5-   D4          ???
17B6-   C6 C9       DEC   $C9
17B8-   CC C5 A2    CPY   $A2C5
17BB-   8D A0 C6    STA   $C6A0
17BE-   D0 D2       BNE   $1792
17C0-   CE A0 A2    DEC   $A2A0
17C3-   C1 CC       CMP   ($CC,X)
17C5-   CC 20 C9    CPY   $C920
17C8-   D3          ???
17C9-   20 D7 C5    JSR   $C5D7
17CC-   CC CC 20    CPY   $20CC
17CF-   D4          ???
17D0-   C8          INY
17D1-   C1 D4       CMP   ($D4,X)
17D3-   20 C5 CE    JSR   $CEC5
17D6-   C4 D3       CPY   $D3
17D8-   20 D7 C5    JSR   $C5D7
17DB-   CC CC AE    CPY   $AECC
17DE-   A2 8D       LDX   #$8D
17E0-   A0 C6       LDY   #$C6
17E2-   D0 D2       BNE   $17B6
17E4-   CE A0 D2    DEC   $D2A0
17E7-   C5 D4       CMP   $D4
17E9-   CF          ???
17EA-   D2 D4       CMP   ($D4)
17EC-   8D A0 C3    STA   $C3A0
17EF-   CD C4 A0    CMP   $A0C4
17F2-   A2 C3       LDX   #$C3
17F4-   CC CF D3    CPY   $D3CF
17F7-   C5 20       CMP   $20
17F9-   D4          ???
17FA-   AE D4 C5    LDX   $C5D4
17FD-   D8          CLD
17FE-   D4          ???
17FF-   C6 C9       DEC   $C9
1801-   CC C5 A2    CPY   $A2C5
1804-   8D A0 DF    STA   $DFA0
1807-   D0 D2       BNE   $17DB
1809-   CE D4 A0    DEC   $A0D4
180C-   A2 20       LDX   #$20
180E-   A2 AC       LDX   #$AC
1810-   B8          CLV
1811-   C4 B8       CPY   $B8
1813-   C4 B8       CPY   $B8
1815-   C4 8D       CPY   $8D
1817-   A0 DF       LDY   #$DF
1819-   D0 D2       BNE   $17ED
181B-   CE D4 A0    DEC   $A0D4
181E-   A2 D0       LDX   #$D0
1820-   D5 D4       CMP   $D4,X
1822-   D3          ???
1823-   20 D4 C8    JSR   $C8D4
1826-   C5 20       CMP   $20
1828-   CC C9 D4    CPY   $D4C9
182B-   C5 D2       CMP   $D2
182D-   C1 CC       CMP   ($CC,X)
182F-   20 D0 C8    JSR   $C8D0
1832-   D2 C1       CMP   ($C1)
1834-   D3          ???
1835-   C5 20       CMP   $20
1837-   C1 CE       CMP   ($CE,X)
1839-   C4 20       CPY   $20
183B-   C1 20       CMP   ($20,X)
183D-   D0 C8       BNE   $1807
183F-   D2 C1       CMP   ($C1)
1841-   D3          ???
1842-   C5 A2       CMP   $A2
1844-   AC B8 C4    LDY   $C4B8
1847-   8D A0 DF    STA   $DFA0
184A-   D0 D2       BNE   $181E
184C-   CE D4 A0    DEC   $A0D4
184F-   A2 D3       LDX   #$D3
1851-   D4          ???
1852-   CF          ???
1853-   D2 C5       CMP   ($C5)
1855-   C4 20       CPY   $20
1857-   C9 CE       CMP   #$CE
1859-   20 D4 C8    JSR   $C8D4
185C-   C5 20       CMP   $20
185E-   D2 C5       CMP   ($C5)
1860-   D4          ???
1861-   CF          ???
1862-   D2 D4       CMP   ($D4)
1864-   20 C1 C4    JSR   $C4C1
1867-   C4 D2       CPY   $D2
1869-   C5 D3       CMP   $D3
186B-   D3          ???
186C-   20 C9 CE    JSR   $CEC9
186F-   D4          ???
1870-   CF          ???
1871-   A2 AC       LDX   #$AC
1873-   B8          CLV
1874-   C4 8D       CPY   $8D
1876-   A0 DF       LDY   #$DF
1878-   D0 D2       BNE   $184C
187A-   CE D4 A0    DEC   $A0D4
187D-   A2 D4       LDX   #$D4
187F-   C8          INY
1880-   C5 20       CMP   $20
1882-   C6 C9       DEC   $C9
1884-   CC C5 AE    CPY   $AEC5
1887-   A2 AC       LDX   #$AC
1889-   B8          CLV
188A-   C4 8D       CPY   $8D
188C-   A0 DF       LDY   #$DF
188E-   D7          ???
188F-   C1 C9       CMP   ($C9,X)
1891-   D4          ???
1892-   8D A0 DF    STA   $DFA0
1895-   D0 D2       BNE   $1869
1897-   CE D4 A0    DEC   $A0D4
189A-   A2 20       LDX   #$20
189C-   A2 AC       LDX   #$AC
189E-   B8          CLV
189F-   C4 B8       CPY   $B8
18A1-   C4 B8       CPY   $B8
18A3-   C4 8D       CPY   $8D
18A5-   A0 DF       LDY   #$DF
18A7-   D0 D2       BNE   $187B
18A9-   CE D4 A0    DEC   $A0D4
18AC-   A2 D4       LDX   #$D4
18AE-   C8          INY
18AF-   C5 CE       CMP   $CE
18B1-   AC 20 CC    LDY   $CC20
18B4-   C9 CB       CMP   #$CB
18B6-   C5 20       CMP   $20
18B8-   C1 CC       CMP   ($CC,X)
18BA-   D7          ???
18BB-   C1 D9       CMP   ($D9,X)
18BD-   D3          ???
18BE-   AC 20 D7    LDY   $D720
18C1-   C5 20       CMP   $20
18C3-   CD D5 D3    CMP   $D3D5
18C6-   D4          ???
18C7-   20 C3 CC    JSR   $CCC3
18CA-   CF          ???
18CB-   D3          ???
18CC-   C5 A2       CMP   $A2
18CE-   AC B8 C4    LDY   $C4B8
18D1-   8D A0 DF    STA   $DFA0
18D4-   D0 D2       BNE   $18A8
18D6-   CE D4 A0    DEC   $A0D4
18D9-   A2 D4       LDX   #$D4
18DB-   C8          INY
18DC-   C5 20       CMP   $20
18DE-   C6 C9       DEC   $C9
18E0-   CC C5 20    CPY   $20C5
18E3-   D6 C9       DEC   $C9,X
18E5-   C1 20       CMP   ($20,X)
18E7-   C3          ???
18E8-   CD C4 BA    CMP   $BAC4
18EB-   A2 AC       LDX   #$AC
18ED-   B8          CLV
18EE-   C4 B8       CPY   $B8
18F0-   C4 8D       CPY   $8D
18F2-   A0 DF       LDY   #$DF
18F4-   D0 D2       BNE   $18C8
18F6-   CE D4 A0    DEC   $A0D4
18F9-   A2 C3       LDX   #$C3
18FB-   CD C4 20    CMP   $20C4
18FE-   A7          ???
18FF-   C3          ???
1900-   CC CF D3    CPY   $D3CF
1903-   C5 20       CMP   $20
1905-   D4          ???
1906-   AE D4 C5    LDX   $C5D4
1909-   D8          CLD
190A-   D4          ???
190B-   C6 C9       DEC   $C9
190D-   CC C5 A7    CPY   $A7C5
1910-   A2 AC       LDX   #$AC
1912-   B8          CLV
1913-   C4 B8       CPY   $B8
1915-   C4 B8       CPY   $B8
1917-   C4 8D       CPY   $8D
1919-   A0 DF       LDY   #$DF
191B-   D7          ???
191C-   C1 C9       CMP   ($C9,X)
191E-   D4          ???
191F-   8D A0 DF    STA   $DFA0
1922-   D0 D2       BNE   $18F6
1924-   CE D4 A0    DEC   $A0D4
1927-   A2 C6       LDX   #$C6
1929-   C9 CE       CMP   #$CE
192B-   C1 CC       CMP   ($CC,X)
192D-   CC D9 AC    CPY   $ACD9
1930-   20 D4 CF    JSR   $CFD4
1933-   20 D2 C5    JSR   $C5D2
1936-   C1 C4       CMP   ($C4,X)
1938-   20 D4 C8    JSR   $C8D4
193B-   C9 D3       CMP   #$D3
193D-   20 D4 C5    JSR   $C5D4
1940-   D8          CLD
1941-   D4          ???
1942-   20 C6 C9    JSR   $C9C6
1945-   CC C5 A2    CPY   $A2C5
1948-   AC B8 C4    LDY   $C4B8
194B-   8D A0 DF    STA   $DFA0
194E-   D0 D2       BNE   $1922
1950-   CE D4 A0    DEC   $A0D4
1953-   A2 D7       LDX   #$D7
1955-   C5 20       CMP   $20
1957-   D3          ???
1958-   C9 CD       CMP   #$CD
195A-   D0 CC       BNE   $1928
195C-   D9 20 CE    CMP   $CE20,Y
195F-   C5 C5       CMP   $C5
1961-   C4 20       CPY   $20
1963-   D4          ???
1964-   CF          ???
1965-   20 CF D0    JSR   $D0CF
1968-   C5 CE       CMP   $CE
196A-   20 D4 C8    JSR   $C8D4
196D-   C5 A2       CMP   $A2
196F-   AC B8 C4    LDY   $C4B8
1972-   8D A0 DF    STA   $DFA0
1975-   D0 D2       BNE   $1949
1977-   CE D4 A0    DEC   $A0D4
197A-   A2 C6       LDX   #$C6
197C-   C9 CC       CMP   #$CC
197E-   C5 20       CMP   $20
1980-   C6 CF       DEC   $CF
1982-   D2 20       CMP   ($20)
1984-   D2 C5       CMP   ($C5)
1986-   C1 C4       CMP   ($C4,X)
1988-   C9 CE       CMP   #$CE
198A-   C7          ???
198B-   20 D6 C9    JSR   $C9D6
198E-   C1 20       CMP   ($20,X)
1990-   D4          ???
1991-   C8          INY
1992-   C5 20       CMP   $20
1994-   C3          ???
1995-   CD C4 20    CMP   $20C4
1998-   CD C1 C3    CMP   $C3C1
199B-   D2 CF       CMP   ($CF)
199D-   AC A2 AC    LDY   $ACA2
19A0-   B8          CLV
19A1-   C4 8D       CPY   $8D
19A3-   A0 DF       LDY   #$DF
19A5-   D0 D2       BNE   $1979
19A7-   CE D4 A0    DEC   $A0D4
19AA-   A2 D4       LDX   #$D4
19AC-   C8          INY
19AD-   C5 CE       CMP   $CE
19AF-   20 D5 D3    JSR   $D3D5
19B2-   C5 20       CMP   $20
19B4-   D4          ???
19B5-   C8          INY
19B6-   C5 20       CMP   $20
19B8-   C6 C9       DEC   $C9
19BA-   CE D0 20    DEC   $20D0
19BD-   CD C1 C3    CMP   $C3C1
19C0-   D2 CF       CMP   ($CF)
19C2-   20 D4 CF    JSR   $CFD4
19C5-   20 D2 C5    JSR   $C5D2
19C8-   C1 C4       CMP   ($C4,X)
19CA-   20 C1 20    JSR   $20C1
19CD-   A2 AC       LDX   #$AC
19CF-   B8          CLV
19D0-   C4 8D       CPY   $8D
19D2-   A0 DF       LDY   #$DF
19D4-   D0 D2       BNE   $19A8
19D6-   CE D4 A0    DEC   $A0D4
19D9-   A2 CC       LDX   #$CC
19DB-   C9 CE       CMP   #$CE
19DD-   C5 20       CMP   $20
19DF-   CF          ???
19E0-   C6 20       DEC   $20
19E2-   D4          ???
19E3-   C5 D8       CMP   $D8
19E5-   D4          ???
19E6-   20 C1 CE    JSR   $CEC1
19E9-   C4 20       CPY   $20
19EB-   D3          ???
19EC-   D4          ???
19ED-   CF          ???
19EE-   D2 C5       CMP   ($C5)
19F0-   20 C9 D4    JSR   $D4C9
19F3-   20 C9 CE    JSR   $CEC9
19F6-   A2 AC       LDX   #$AC
19F8-   B8          CLV
19F9-   C4 8D       CPY   $8D
19FB-   A0 DF       LDY   #$DF
19FD-   D0 D2       BNE   $19D1
19FF-   CE D4 A0    DEC   $A0D4
1A02-   A2 CD       LDX   #$CD
1A04-   C5 CD       CMP   $CD
1A06-   CF          ???
1A07-   D2 D9       CMP   ($D9)
1A09-   BA          TSX
1A0A-   A2 AC       LDX   #$AC
1A0C-   B8          CLV
1A0D-   C4 B8       CPY   $B8
1A0F-   C4 8D       CPY   $8D
1A11-   A0 DF       LDY   #$DF
1A13-   D0 D2       BNE   $19E7
1A15-   CE D4 A0    DEC   $A0D4
1A18-   A2 C3       LDX   #$C3
1A1A-   CD C4 20    CMP   $20C4
1A1D-   A7          ???
1A1E-   CF          ???
1A1F-   D0 C5       BNE   $19E6
1A21-   CE 20 D4    DEC   $D420
1A24-   AE D4 C5    LDX   $C5D4
1A27-   D8          CLD
1A28-   D4          ???
1A29-   C6 C9       DEC   $C9
1A2B-   CC C5 A7    CPY   $A7C5
1A2E-   A2 AC       LDX   #$AC
1A30-   B8          CLV
1A31-   C4 8D       CPY   $8D
1A33-   A0 DF       LDY   #$DF
1A35-   D0 D2       BNE   $1A09
1A37-   CE D4 A0    DEC   $A0D4
1A3A-   A2 C3       LDX   #$C3
1A3C-   CD C4 20    CMP   $20C4
1A3F-   A7          ???
1A40-   D2 C5       CMP   ($C5)
1A42-   C1 C4       CMP   ($C4,X)
1A44-   20 D4 AE    JSR   $AED4
1A47-   D4          ???
1A48-   C5 D8       CMP   $D8
1A4A-   D4          ???
1A4B-   C6 C9       DEC   $C9
1A4D-   CC C5 A7    CPY   $A7C5
1A50-   A2 AC       LDX   #$AC
1A52-   B8          CLV
1A53-   C4 8D       CPY   $8D
1A55-   A0 DF       LDY   #$DF
1A57-   D0 D2       BNE   $1A2B
1A59-   CE D4 A0    DEC   $A0D4
1A5C-   A2 C6       LDX   #$C6
1A5E-   C9 CE       CMP   #$CE
1A60-   D0 20       BNE   $1A82
1A62-   D2 C5       CMP   ($C5)
1A64-   D4          ???
1A65-   D5 D2       CMP   $D2,X
1A67-   CE A2 AC    DEC   $ACA2
1A6A-   B8          CLV
1A6B-   C4 8D       CPY   $8D
1A6D-   A0 DF       LDY   #$DF
1A6F-   D0 D2       BNE   $1A43
1A71-   CE D4 A0    DEC   $A0D4
1A74-   A2 C6       LDX   #$C6
1A76-   C9 CE       CMP   #$CE
1A78-   D0 20       BNE   $1A9A
1A7A-   D0 C1       BNE   $1A3D
1A7C-   D2 C1       CMP   ($C1)
1A7E-   CD A2 AC    CMP   $ACA2
1A81-   B8          CLV
1A82-   C4 8D       CPY   $8D
1A84-   A0 DF       LDY   #$DF
1A86-   D0 D2       BNE   $1A5A
1A88-   CE D4 A0    DEC   $A0D4
1A8B-   A2 C3       LDX   #$C3
1A8D-   CD C4 20    CMP   $20C4
1A90-   A7          ???
1A91-   C3          ???
1A92-   CC CF D3    CPY   $D3CF
1A95-   C5 20       CMP   $20
1A97-   D4          ???
1A98-   AE D4 C5    LDX   $C5D4
1A9B-   D8          CLD
1A9C-   D4          ???
1A9D-   C6 C9       DEC   $C9
1A9F-   CC C5 A7    CPY   $A7C5
1AA2-   A2 AC       LDX   #$AC
1AA4-   B8          CLV
1AA5-   C4 B8       CPY   $B8
1AA7-   C4 8D       CPY   $8D
1AA9-   A0 C3       LDY   #$C3
1AAB-   CD C4 A0    CMP   $A0C4
1AAE-   A2 CF       LDX   #$CF
1AB0-   D0 C5       BNE   $1A77
1AB2-   CE 20 D4    DEC   $D420
1AB5-   AE D4 C5    LDX   $C5D4
1AB8-   D8          CLD
1AB9-   D4          ???
1ABA-   C6 C9       DEC   $C9
1ABC-   CC C5 A2    CPY   $A2C5
1ABF-   8D A0 C3    STA   $C3A0
1AC2-   CD C4 A0    CMP   $A0C4
1AC5-   A2 D2       LDX   #$D2
1AC7-   C5 C1       CMP   $C1
1AC9-   C4 20       CPY   $20
1ACB-   D4          ???
1ACC-   AE D4 C5    LDX   $C5D4
1ACF-   D8          CLD
1AD0-   D4          ???
1AD1-   C6 C9       DEC   $C9
1AD3-   CC C5 A2    CPY   $A2C5
1AD6-   8D A0 C6    STA   $C6A0
1AD9-   C9 CE       CMP   #$CE
1ADB-   D0 A0       BNE   $1A7D
1ADD-   D2 C5       CMP   ($C5)
1ADF-   D4          ???
1AE0-   D5 D2       CMP   $D2,X
1AE2-   CE 8D A0    DEC   $A08D
1AE5-   C6 C9       DEC   $C9
1AE7-   CE D0 A0    DEC   $A0D0
1AEA-   D0 C1       BNE   $1AAD
1AEC-   D2 C1       CMP   ($C1)
1AEE-   CD 8D A0    CMP   $A08D
1AF1-   C3          ???
1AF2-   CD C4 A0    CMP   $A0C4
1AF5-   A2 C3       LDX   #$C3
1AF7-   CC CF D3    CPY   $D3CF
1AFA-   C5 20       CMP   $20
1AFC-   D4          ???
1AFD-   AE D4 C5    LDX   $C5D4
1B00-   D8          CLD
1B01-   D4          ???
1B02-   C6 C9       DEC   $C9
1B04-   CC C5 A2    CPY   $A2C5
1B07-   8D A0 DF    STA   $DFA0
1B0A-   D7          ???
1B0B-   C1 C9       CMP   ($C9,X)
1B0D-   D4          ???
1B0E-   8D A0 DF    STA   $DFA0
1B11-   C4 D5       CPY   $D5
1B13-   CD D0 A0    CMP   $A0D0
1B16-   D2 C5       CMP   ($C5)
1B18-   D4          ???
1B19-   D5 D2       CMP   $D2,X
1B1B-   CE BB D2    DEC   $D2BB
1B1E-   C5 D4       CMP   $D4
1B20-   D5 D2       CMP   $D2,X
1B22-   CE 8D A0    DEC   $A08D
1B25-   DF          ???
1B26-   C4 D5       CPY   $D5
1B28-   CD D0 A0    CMP   $A0D0
1B2B-   D0 C1       BNE   $1AEE
1B2D-   D2 C1       CMP   ($C1)
1B2F-   CD BB D0    CMP   $D0BB
1B32-   C1 D2       CMP   ($D2,X)
1B34-   C1 CD       CMP   ($CD,X)
1B36-   8D A0 DF    STA   $DFA0
1B39-   D7          ???
1B3A-   C1 C9       CMP   ($C9,X)
1B3C-   D4          ???
1B3D-   8D AA 8D    STA   $8DAA
1B40-   A0 DF       LDY   #$DF
1B42-   D0 D2       BNE   $1B16
1B44-   CE D4 A0    DEC   $A0D4
1B47-   A2 20       LDX   #$20
1B49-   A2 AC       LDX   #$AC
1B4B-   B8          CLV
1B4C-   C4 B8       CPY   $B8
1B4E-   C4 8D       CPY   $8D
1B50-   A0 DF       LDY   #$DF
1B52-   D0 D2       BNE   $1B26
1B54-   CE D4 A0    DEC   $A0D4
1B57-   A2 D4       LDX   #$D4
1B59-   C8          INY
1B5A-   C5 D3       CMP   $D3
1B5C-   C5 20       CMP   $20
1B5E-   D3          ???
1B5F-   D4          ???
1B60-   D2 C9       CMP   ($C9)
1B62-   CE C7 D3    DEC   $D3C7
1B65-   20 C1 D2    JSR   $D2C1
1B68-   C5 20       CMP   $20
1B6A-   CE CF D7    DEC   $D7CF
1B6D-   20 D3 D4    JSR   $D4D3
1B70-   CF          ???
1B71-   D2 C5       CMP   ($C5)
1B73-   C4 20       CPY   $20
1B75-   C9 CE       CMP   #$CE
1B77-   A2 AC       LDX   #$AC
1B79-   B8          CLV
1B7A-   C4 8D       CPY   $8D
1B7C-   A0 DF       LDY   #$DF
1B7E-   D0 D2       BNE   $1B52
1B80-   CE D4 A0    DEC   $A0D4
1B83-   A2 DB       LDX   #$DB
1B85-   D2 C5       CMP   ($C5)
1B87-   D4          ???
1B88-   D5 D2       CMP   $D2,X
1B8A-   CE DD 20    DEC   $20DD
1B8D-   C1 CE       CMP   ($CE,X)
1B8F-   C4 20       CPY   $20
1B91-   DB          ???
1B92-   D0 C1       BNE   $1B55
1B94-   D2 C1       CMP   ($C1)
1B96-   CD DD AC    CMP   $ACDD
1B99-   20 D2 C5    JSR   $C5D2
1B9C-   D3          ???
1B9D-   D0 C5       BNE   $1B64
1B9F-   C3          ???
1BA0-   D4          ???
1BA1-   C9 D6       CMP   #$D6
1BA3-   C5 CC       CMP   $CC
1BA5-   D9 AC A2    CMP   $A2AC,Y
1BA8-   AC B8 C4    LDY   $C4B8
1BAB-   8D A0 DF    STA   $DFA0
1BAE-   D0 D2       BNE   $1B82
1BB0-   CE D4 A0    DEC   $A0D4
1BB3-   A2 D7       LDX   #$D7
1BB5-   C9 D4       CMP   #$D4
1BB7-   C8          INY
1BB8-   20 C1 20    JSR   $20C1
1BBB-   D0 D2       BNE   $1B8F
1BBD-   C5 C3       CMP   $C3
1BBF-   C5 C4       CMP   $C4
1BC1-   C9 CE       CMP   #$CE
1BC3-   C7          ???
1BC4-   20 CC C5    JSR   $C5CC
1BC7-   CE C7 D4    DEC   $D4C7
1BCA-   C8          INY
1BCB-   20 C2 D9    JSR   $D9C2
1BCE-   D4          ???
1BCF-   C5 AE       CMP   $AE
1BD1-   20 D4 C8    JSR   $C8D4
1BD4-   C5 D3       CMP   $D3
1BD6-   C5 A2       CMP   $A2
1BD8-   AC B8 C4    LDY   $C4B8
1BDB-   8D A0 DF    STA   $DFA0
1BDE-   D0 D2       BNE   $1BB2
1BE0-   CE D4 A0    DEC   $A0D4
1BE3-   A2 C3       LDX   #$C3
1BE5-   C1 CE       CMP   ($CE,X)
1BE7-   20 C2 C5    JSR   $C5C2
1BEA-   20 D0 D2    JSR   $D2D0
1BED-   C9 CE       CMP   #$CE
1BEF-   D4          ???
1BF0-   C5 C4       CMP   $C4
1BF2-   20 D7 C9    JSR   $C9D7
1BF5-   D4          ???
1BF6-   C8          INY
1BF7-   20 D4 C8    JSR   $C8D4
1BFA-   C5 20       CMP   $20
1BFC-   D3          ???
1BFD-   D0 D2       BNE   $1BD1
1BFF-   CE 20 CD    DEC   $CD20
1C02-   C1 C3       CMP   ($C3,X)
1C04-   D2 CF       CMP   ($CF)
1C06-   A2 AC       LDX   #$AC
1C08-   B8          CLV
1C09-   C4 8D       CPY   $8D
1C0B-   A0 DF       LDY   #$DF
1C0D-   D0 D2       BNE   $1BE1
1C0F-   CE D4 A0    DEC   $A0D4
1C12-   A2 C6       LDX   #$C6
1C14-   CF          ???
1C15-   D5 CE       CMP   $CE,X
1C17-   C4 20       CPY   $20
1C19-   C9 CE       CMP   #$CE
1C1B-   20 D4 C8    JSR   $C8D4
1C1E-   C5 20       CMP   $20
1C20-   D3          ???
1C21-   D4          ???
1C22-   D2 C9       CMP   ($C9)
1C24-   CE C7 D3    DEC   $D3C7
1C27-   20 CC C9    JSR   $C9CC
1C2A-   C2          ???
1C2B-   D2 C1       CMP   ($C1)
1C2D-   D2 D9       CMP   ($D9)
1C2F-   AE A2 AC    LDX   $ACA2
1C32-   B8          CLV
1C33-   C4 B8       CPY   $B8
1C35-   C4 B8       CPY   $B8
1C37-   C4 8D       CPY   $8D
1C39-   A0 DF       LDY   #$DF
1C3B-   D7          ???
1C3C-   C1 C9       CMP   ($C9,X)
1C3E-   D4          ???
1C3F-   8D AA 8D    STA   $8DAA
1C42-   AA          TAX
1C43-   AA          TAX
1C44-   AA          TAX
1C45-   AA          TAX
1C46-   AA          TAX
1C47-   AA          TAX
1C48-   AA          TAX
1C49-   AA          TAX
1C4A-   AA          TAX
1C4B-   AA          TAX
1C4C-   AA          TAX
1C4D-   AA          TAX
1C4E-   AA          TAX
1C4F-   AA          TAX
1C50-   AA          TAX
1C51-   AA          TAX
1C52-   AA          TAX
1C53-   AA          TAX
1C54-   AA          TAX
1C55-   AA          TAX
1C56-   AA          TAX
1C57-   AA          TAX
1C58-   AA          TAX
1C59-   AA          TAX
1C5A-   AA          TAX
1C5B-   AA          TAX
1C5C-   AA          TAX
1C5D-   AA          TAX
1C5E-   AA          TAX
1C5F-   AA          TAX
1C60-   AA          TAX
1C61-   AA          TAX
1C62-   8D AA AA    STA   $AAAA
1C65-   AA          TAX
1C66-   AA          TAX
1C67-   AA          TAX
1C68-   AA          TAX
1C69-   AA          TAX
1C6A-   AA          TAX
1C6B-   AA          TAX
1C6C-   AA          TAX
1C6D-   AA          TAX
1C6E-   AA          TAX
1C6F-   AA          TAX
1C70-   AA          TAX
1C71-   AA          TAX
1C72-   AA          TAX
1C73-   AA          TAX
1C74-   AA          TAX
1C75-   AA          TAX
1C76-   AA          TAX
1C77-   AA          TAX
1C78-   AA          TAX
1C79-   AA          TAX
1C7A-   AA          TAX
1C7B-   AA          TAX
1C7C-   AA          TAX
1C7D-   AA          TAX
1C7E-   AA          TAX
1C7F-   AA          TAX
1C80-   AA          TAX
1C81-   AA          TAX
1C82-   AA          TAX
1C83-   8D AA AA    STA   $AAAA
1C86-   AA          TAX
1C87-   AA          TAX
1C88-   AA          TAX
1C89-   AA          TAX
1C8A-   AA          TAX
1C8B-   AA          TAX
1C8C-   AA          TAX
1C8D-   AA          TAX
1C8E-   AA          TAX
1C8F-   AA          TAX
1C90-   AA          TAX
1C91-   AA          TAX
1C92-   AA          TAX
1C93-   AA          TAX
1C94-   AA          TAX
1C95-   AA          TAX
1C96-   AA          TAX
1C97-   AA          TAX
1C98-   AA          TAX
1C99-   AA          TAX
1C9A-   AA          TAX
1C9B-   AA          TAX
1C9C-   AA          TAX
1C9D-   AA          TAX
1C9E-   AA          TAX
1C9F-   AA          TAX
1CA0-   AA          TAX
1CA1-   AA          TAX
1CA2-   AA          TAX
1CA3-   AA          TAX
1CA4-   8D AA 20    STA   $20AA
1CA7-   20 20 20    JSR   $2020
1CAA-   20 20 20    JSR   $2020
1CAD-   20 20 20    JSR   $2020
1CB0-   20 20 20    JSR   $2020
1CB3-   20 20 20    JSR   $2020
1CB6-   20 20 20    JSR   $2020
1CB9-   20 20 20    JSR   $2020
1CBC-   20 20 20    JSR   $2020
1CBF-   20 20 20    JSR   $2020
1CC2-   20 20 AA    JSR   $AA20
1CC5-   8D AA 20    STA   $20AA
1CC8-   20 20 D7    JSR   $D720
1CCB-   20 C1 20    JSR   $20C1
1CCE-   D2 20       CMP   ($20)
1CD0-   CE 20 C9    DEC   $C920
1CD3-   20 CE 20    JSR   $20CE
1CD6-   C7          ???
1CD7-   20 20 20    JSR   $2020
1CDA-   20 20 20    JSR   $2020
1CDD-   20 20 20    JSR   $2020
1CE0-   20 20 20    JSR   $2020
1CE3-   20 20 AA    JSR   $AA20
1CE6-   8D AA 20    STA   $20AA
1CE9-   20 20 20    JSR   $2020
1CEC-   20 20 20    JSR   $2020
1CEF-   20 20 20    JSR   $2020
1CF2-   20 20 20    JSR   $2020
1CF5-   20 20 20    JSR   $2020
1CF8-   20 20 20    JSR   $2020
1CFB-   20 20 20    JSR   $2020
1CFE-   20 20 20    JSR   $2020
1D01-   20 20 20    JSR   $2020
1D04-   20 20 AA    JSR   $AA20
1D07-   8D AA AA    STA   $AAAA
1D0A-   AA          TAX
1D0B-   AA          TAX
1D0C-   AA          TAX
1D0D-   AA          TAX
1D0E-   AA          TAX
1D0F-   AA          TAX
1D10-   AA          TAX
1D11-   AA          TAX
1D12-   AA          TAX
1D13-   AA          TAX
1D14-   AA          TAX
1D15-   AA          TAX
1D16-   AA          TAX
1D17-   AA          TAX
1D18-   AA          TAX
1D19-   AA          TAX
1D1A-   AA          TAX
1D1B-   AA          TAX
1D1C-   AA          TAX
1D1D-   AA          TAX
1D1E-   AA          TAX
1D1F-   AA          TAX
1D20-   AA          TAX
1D21-   AA          TAX
1D22-   AA          TAX
1D23-   AA          TAX
1D24-   AA          TAX
1D25-   AA          TAX
1D26-   AA          TAX
1D27-   AA          TAX
1D28-   8D AA AA    STA   $AAAA
1D2B-   AA          TAX
1D2C-   AA          TAX
1D2D-   AA          TAX
1D2E-   AA          TAX
1D2F-   AA          TAX
1D30-   AA          TAX
1D31-   AA          TAX
1D32-   AA          TAX
1D33-   AA          TAX
1D34-   AA          TAX
1D35-   AA          TAX
1D36-   AA          TAX
1D37-   AA          TAX
1D38-   AA          TAX
1D39-   AA          TAX
1D3A-   AA          TAX
1D3B-   AA          TAX
1D3C-   AA          TAX
1D3D-   AA          TAX
1D3E-   AA          TAX
1D3F-   AA          TAX
1D40-   AA          TAX
1D41-   AA          TAX
1D42-   AA          TAX
1D43-   AA          TAX
1D44-   AA          TAX
1D45-   AA          TAX
1D46-   AA          TAX
1D47-   AA          TAX
1D48-   AA          TAX
1D49-   8D AA AA    STA   $AAAA
1D4C-   AA          TAX
1D4D-   AA          TAX
1D4E-   AA          TAX
1D4F-   AA          TAX
1D50-   AA          TAX
1D51-   AA          TAX
1D52-   AA          TAX
1D53-   AA          TAX
1D54-   AA          TAX
1D55-   AA          TAX
1D56-   AA          TAX
1D57-   AA          TAX
1D58-   AA          TAX
1D59-   AA          TAX
1D5A-   AA          TAX
1D5B-   AA          TAX
1D5C-   AA          TAX
1D5D-   AA          TAX
1D5E-   AA          TAX
1D5F-   AA          TAX
1D60-   AA          TAX
1D61-   AA          TAX
1D62-   AA          TAX
1D63-   AA          TAX
1D64-   AA          TAX
1D65-   AA          TAX
1D66-   AA          TAX
1D67-   AA          TAX
1D68-   AA          TAX
1D69-   AA          TAX
1D6A-   8D AA 8D    STA   $8DAA
1D6D-   A0 DF       LDY   #$DF
1D6F-   D0 D2       BNE   $1D43
1D71-   CE D4 A0    DEC   $A0D4
1D74-   A2 AA       LDX   #$AA
1D76-   AA          TAX
1D77-   AA          TAX
1D78-   AA          TAX
1D79-   AA          TAX
1D7A-   AA          TAX
1D7B-   AA          TAX
1D7C-   AA          TAX
1D7D-   AA          TAX
1D7E-   AA          TAX
1D7F-   AA          TAX
1D80-   AA          TAX
1D81-   AA          TAX
1D82-   AA          TAX
1D83-   AA          TAX
1D84-   AA          TAX
1D85-   AA          TAX
1D86-   AA          TAX
1D87-   AA          TAX
1D88-   AA          TAX
1D89-   AA          TAX
1D8A-   AA          TAX
1D8B-   AA          TAX
1D8C-   AA          TAX
1D8D-   AA          TAX
1D8E-   AA          TAX
1D8F-   AA          TAX
1D90-   AA          TAX
1D91-   AA          TAX
1D92-   AA          TAX
1D93-   AA          TAX
1D94-   AA          TAX
1D95-   A2 AC       LDX   #$AC
1D97-   B8          CLV
1D98-   C4 8D       CPY   $8D
1D9A-   A0 DF       LDY   #$DF
1D9C-   D0 D2       BNE   $1D70
1D9E-   CE D4 A0    DEC   $A0D4
1DA1-   A2 AA       LDX   #$AA
1DA3-   AA          TAX
1DA4-   AA          TAX
1DA5-   AA          TAX
1DA6-   AA          TAX
1DA7-   AA          TAX
1DA8-   AA          TAX
1DA9-   AA          TAX
1DAA-   AA          TAX
1DAB-   AA          TAX
1DAC-   AA          TAX
1DAD-   AA          TAX
1DAE-   AA          TAX
1DAF-   AA          TAX
1DB0-   AA          TAX
1DB1-   AA          TAX
1DB2-   AA          TAX
1DB3-   AA          TAX
1DB4-   AA          TAX
1DB5-   AA          TAX
1DB6-   AA          TAX
1DB7-   AA          TAX
1DB8-   AA          TAX
1DB9-   AA          TAX
1DBA-   AA          TAX
1DBB-   AA          TAX
1DBC-   AA          TAX
1DBD-   AA          TAX
1DBE-   AA          TAX
1DBF-   AA          TAX
1DC0-   AA          TAX
1DC1-   AA          TAX
1DC2-   A2 AC       LDX   #$AC
1DC4-   B8          CLV
1DC5-   C4 B8       CPY   $B8
1DC7-   C4 8D       CPY   $8D
1DC9-   A0 DF       LDY   #$DF
1DCB-   D0 D2       BNE   $1D9F
1DCD-   CE D4 A0    DEC   $A0D4
1DD0-   A2 20       LDX   #$20
1DD2-   20 20 20    JSR   $2020
1DD5-   20 20 D7    JSR   $D720
1DD8-   C1 D2       CMP   ($D2,X)
1DDA-   CE C9 CE    DEC   $CEC9
1DDD-   C7          ???
1DDE-   A1 A1       LDA   ($A1,X)
1DE0-   A1 A2       LDA   ($A2,X)
1DE2-   AC B8 C4    LDY   $C4B8
1DE5-   B8          CLV
1DE6-   C4 8D       CPY   $8D
1DE8-   A0 DF       LDY   #$DF
1DEA-   D0 D2       BNE   $1DBE
1DEC-   CE D4 A0    DEC   $A0D4
1DEF-   A2 AA       LDX   #$AA
1DF1-   AA          TAX
1DF2-   AA          TAX
1DF3-   AA          TAX
1DF4-   AA          TAX
1DF5-   AA          TAX
1DF6-   AA          TAX
1DF7-   AA          TAX
1DF8-   AA          TAX
1DF9-   AA          TAX
1DFA-   AA          TAX
1DFB-   AA          TAX
1DFC-   AA          TAX
1DFD-   AA          TAX
1DFE-   AA          TAX
1DFF-   AA          TAX
1E00-   AA          TAX
1E01-   AA          TAX
1E02-   AA          TAX
1E03-   AA          TAX
1E04-   AA          TAX
1E05-   AA          TAX
1E06-   AA          TAX
1E07-   AA          TAX
1E08-   AA          TAX
1E09-   AA          TAX
1E0A-   AA          TAX
1E0B-   AA          TAX
1E0C-   AA          TAX
1E0D-   AA          TAX
1E0E-   AA          TAX
1E0F-   AA          TAX
1E10-   A2 AC       LDX   #$AC
1E12-   B8          CLV
1E13-   C4 8D       CPY   $8D
1E15-   A0 DF       LDY   #$DF
1E17-   D0 D2       BNE   $1DEB
1E19-   CE D4 A0    DEC   $A0D4
1E1C-   A2 AA       LDX   #$AA
1E1E-   AA          TAX
1E1F-   AA          TAX
1E20-   AA          TAX
1E21-   AA          TAX
1E22-   AA          TAX
1E23-   AA          TAX
1E24-   AA          TAX
1E25-   AA          TAX
1E26-   AA          TAX
1E27-   AA          TAX
1E28-   AA          TAX
1E29-   AA          TAX
1E2A-   AA          TAX
1E2B-   AA          TAX
1E2C-   AA          TAX
1E2D-   AA          TAX
1E2E-   AA          TAX
1E2F-   AA          TAX
1E30-   AA          TAX
1E31-   AA          TAX
1E32-   AA          TAX
1E33-   AA          TAX
1E34-   AA          TAX
1E35-   AA          TAX
1E36-   AA          TAX
1E37-   AA          TAX
1E38-   AA          TAX
1E39-   AA          TAX
1E3A-   AA          TAX
1E3B-   AA          TAX
1E3C-   AA          TAX
1E3D-   A2 AC       LDX   #$AC
1E3F-   B8          CLV
1E40-   C4 B8       CPY   $B8
1E42-   C4 8D       CPY   $8D
1E44-   A0 DF       LDY   #$DF
1E46-   D0 D2       BNE   $1E1A
1E48-   CE D4 A0    DEC   $A0D4
1E4B-   A2 C1       LDX   #$C1
1E4D-   D4          ???
1E4E-   20 D4 C8    JSR   $C8D4
1E51-   C9 D3       CMP   #$D3
1E53-   20 D0 CF    JSR   $CFD0
1E56-   C9 CE       CMP   #$CE
1E58-   D4          ???
1E59-   AC 20 D9    LDY   $D920
1E5C-   CF          ???
1E5D-   D5 20       CMP   $20,X
1E5F-   D7          ???
1E60-   C1 CE       CMP   ($CE,X)
1E62-   D4          ???
1E63-   20 D4 CF    JSR   $CFD4
1E66-   20 C5 CA    JSR   $CAC5
1E69-   C5 C3       CMP   $C3
1E6B-   D4          ???
1E6C-   A2 AC       LDX   #$AC
1E6E-   B8          CLV
1E6F-   C4 8D       CPY   $8D
1E71-   A0 DF       LDY   #$DF
1E73-   D0 D2       BNE   $1E47
1E75-   CE D4 A0    DEC   $A0D4
1E78-   A2 D4       LDX   #$D4
1E7A-   C8          INY
1E7B-   C5 20       CMP   $20
1E7D-   C3          ???
1E7E-   D5 D2       CMP   $D2,X
1E80-   D2 C5       CMP   ($C5)
1E82-   CE D4 20    DEC   $20D4
1E85-   C4 C9       CPY   $C9
1E87-   D3          ???
1E88-   CB          ???
1E89-   AC 20 C1    LDY   $C120
1E8C-   CE C4 20    DEC   $20C4
1E8F-   D0 D5       BNE   $1E66
1E91-   D4          ???
1E92-   20 C9 CE    JSR   $CEC9
1E95-   A2 AC       LDX   #$AC
1E97-   B8          CLV
1E98-   C4 8D       CPY   $8D
1E9A-   A0 DF       LDY   #$DF
1E9C-   D0 D2       BNE   $1E70
1E9E-   CE D4 A0    DEC   $A0D4
1EA1-   A2 C1       LDX   #$C1
1EA3-   20 C4 C9    JSR   $C9C4
1EA6-   D3          ???
1EA7-   CB          ???
1EA8-   20 D4 C8    JSR   $C8D4
1EAB-   C1 D4       CMP   ($D4,X)
1EAD-   20 D9 CF    JSR   $CFD9
1EB0-   D5 20       CMP   $20,X
1EB2-   C4 CF       CPY   $CF
1EB4-   CE A7 D4    DEC   $D4A7
1EB7-   20 CD C9    JSR   $C9CD
1EBA-   CE C4 20    DEC   $20C4
1EBD-   A2 AC       LDX   #$AC
1EBF-   B8          CLV
1EC0-   C4 8D       CPY   $8D
1EC2-   A0 DF       LDY   #$DF
1EC4-   D0 D2       BNE   $1E98
1EC6-   CE D4 A0    DEC   $A0D4
1EC9-   A2 C8       LDX   #$C8
1ECB-   C1 D6       CMP   ($D6,X)
1ECD-   C9 CE       CMP   #$CE
1ECF-   C7          ???
1ED0-   20 D4 CF    JSR   $CFD4
1ED3-   20 D2 C5    JSR   $C5D2
1ED6-   C6 CF       DEC   $CF
1ED8-   D2 CD       CMP   ($CD)
1EDA-   C1 D4       CMP   ($D4,X)
1EDC-   AE 20 A2    LDX   $A220
1EDF-   AC B8 C4    LDY   $C4B8
1EE2-   B8          CLV
1EE3-   C4 8D       CPY   $8D
1EE5-   A0 DF       LDY   #$DF
1EE7-   D0 D2       BNE   $1EBB
1EE9-   CE D4 A0    DEC   $A0D4
1EEC-   A2 D4       LDX   #$D4
1EEE-   C8          INY
1EEF-   C5 20       CMP   $20
1EF1-   D2 C5       CMP   ($C5)
1EF3-   D3          ???
1EF4-   D4          ???
1EF5-   20 CF C6    JSR   $C6CF
1EF8-   20 D4 C8    JSR   $C8D4
1EFB-   C5 20       CMP   $20
1EFD-   D2 CF       CMP   ($CF)
1EFF-   D5 D4       CMP   $D4,X
1F01-   C9 CE       CMP   #$CE
1F03-   C5 D3       CMP   $D3
1F05-   20 C1 D2    JSR   $D2C1
1F08-   C5 A2       CMP   $A2
1F0A-   AC B8 C4    LDY   $C4B8
1F0D-   8D A0 DF    STA   $DFA0
1F10-   D0 D2       BNE   $1EE4
1F12-   CE D4 A0    DEC   $A0D4
1F15-   A2 CC       LDX   #$CC
1F17-   CF          ???
1F18-   D7          ???
1F19-   20 CC C5    JSR   $C5CC
1F1C-   D6 C5       DEC   $C5,X
1F1E-   CC 20 C4    CPY   $C420
1F21-   C9 D3       CMP   #$D3
1F23-   CB          ???
1F24-   20 C1 C3    JSR   $C3C1
1F27-   C3          ???
1F28-   C5 D3       CMP   $D3
1F2A-   D3          ???
1F2B-   20 D0 D2    JSR   $D2D0
1F2E-   CF          ???
1F2F-   C3          ???
1F30-   C5 C4       CMP   $C4
1F32-   D5 D2       CMP   $D2,X
1F34-   C5 D3       CMP   $D3
1F36-   AC A2 AC    LDY   $ACA2
1F39-   B8          CLV
1F3A-   C4 8D       CPY   $8D
1F3C-   A0 DF       LDY   #$DF
1F3E-   D0 D2       BNE   $1F12
1F40-   CE D4 A0    DEC   $A0D4
1F43-   A2 C1       LDX   #$C1
1F45-   CE C4 20    DEC   $20C4
1F48-   C3          ???
1F49-   C1 CE       CMP   ($CE,X)
1F4B-   20 D3 C5    JSR   $C5D3
1F4E-   D2 C9       CMP   ($C9)
1F50-   CF          ???
1F51-   D5 D3       CMP   $D3,X
1F53-   CC D9 20    CPY   $20D9
1F56-   C4 C1       CPY   $C1
1F58-   CD C1 C7    CMP   $C7C1
1F5B-   C5 20       CMP   $20
1F5D-   C1 20       CMP   ($20,X)
1F5F-   C4 C9       CPY   $C9
1F61-   D3          ???
1F62-   CB          ???
1F63-   A1 A2       LDA   ($A2,X)
1F65-   AC B8 C4    LDY   $C4B8
1F68-   B8          CLV
1F69-   C4 8D       CPY   $8D
1F6B-   A0 DF       LDY   #$DF
1F6D-   D0 D2       BNE   $1F41
1F6F-   CE D4 A0    DEC   $A0D4
1F72-   A2 BC       LDX   #$BC
1F74-   BC BC 20    LDY   $20BC,X
1F77-   D0 D2       BNE   $1F4B
1F79-   C5 D3       CMP   $D3
1F7B-   D3          ???
1F7C-   20 C1 20    JSR   $20C1
1F7F-   CB          ???
1F80-   C5 D9       CMP   $D9
1F82-   20 CF CE    JSR   $CECF
1F85-   C3          ???
1F86-   C5 20       CMP   $20
1F88-   D9 CF D5    CMP   $D5CF,Y
1F8B-   A7          ???
1F8C-   D2 C5       CMP   ($C5)
1F8E-   20 D2 C5    JSR   $C5D2
1F91-   C1 C4       CMP   ($C4,X)
1F93-   D9 20 BE    CMP   $BE20,Y
1F96-   BE BE A2    LDX   $A2BE,Y
1F99-   AC B8 C4    LDY   $C4B8
1F9C-   B8          CLV
1F9D-   C4 8D       CPY   $8D
1F9F-   A0 DF       LDY   #$DF
1FA1-   D7          ???
1FA2-   C1 C9       CMP   ($C9,X)
1FA4-   D4          ???
1FA5-   8D AA 8D    STA   $8DAA
1FA8-   A0 DF       LDY   #$DF
1FAA-   D0 D2       BNE   $1F7E
1FAC-   CE D4 A0    DEC   $A0D4
1FAF-   A2 CC       LDX   #$CC
1FB1-   CF          ???
1FB2-   D7          ???
1FB3-   AD CC C5    LDA   $C5CC
1FB6-   D6 C5       DEC   $C5,X
1FB8-   CC 20 C4    CPY   $C420
1FBB-   C9 D3       CMP   #$D3
1FBD-   CB          ???
1FBE-   20 C1 C3    JSR   $C3C1
1FC1-   C3          ???
1FC2-   C5 D3       CMP   $D3
1FC4-   D3          ???
1FC5-   20 C9 D3    JSR   $D3C9
1FC8-   20 C4 CF    JSR   $CFC4
1FCB-   CE C5 20    DEC   $20C5
1FCE-   D6 C9       DEC   $C9,X
1FD0-   C1 A2       CMP   ($A2,X)
1FD2-   AC B8 C4    LDY   $C4B8
1FD5-   8D A0 DF    STA   $DFA0
1FD8-   D0 D2       BNE   $1FAC
1FDA-   CE D4 A0    DEC   $A0D4
1FDD-   A2 D4       LDX   #$D4
1FDF-   C8          INY
1FE0-   C5 20       CMP   $20
1FE2-   D3          ???
1FE3-   D4          ???
1FE4-   C1 CE       CMP   ($CE,X)
1FE6-   C4 C1       CPY   $C1
1FE8-   D2 C4       CMP   ($C4)
1FEA-   20 D2 D7    JSR   $D7D2
1FED-   D4          ???
1FEE-   D3          ???
1FEF-   20 D2 CF    JSR   $CFD2
1FF2-   D5 D4       CMP   $D4,X
1FF4-   C9 CE       CMP   #$CE
1FF6-   C5 AC       CMP   $AC
1FF8-   20 D7 C9    JSR   $C9D7
1FFB-   D4          ???
1FFC-   C8          INY
1FFD-   20 C1 A2    JSR   $A2C1
2000-   AC B8 C4    LDY   $C4B8
2003-   8D A0 DF    STA   $DFA0
2006-   D0 D2       BNE   $1FDA
2008-   CE D4 A0    DEC   $A0D4
200B-   A2 C6       LDX   #$C6
200D-   C5 D7       CMP   $D7
200F-   20 CD C1    JSR   $C1CD
2012-   C3          ???
2013-   D2 CF       CMP   ($CF)
2015-   D3          ???
2016-   20 D4 C8    JSR   $C8D4
2019-   D2 CF       CMP   ($CF)
201B-   D7          ???
201C-   CE 20 C9    DEC   $C920
201F-   CE 20 D4    DEC   $D420
2022-   CF          ???
2023-   20 CD C1    JSR   $C1CD
2026-   CB          ???
2027-   C5 20       CMP   $20
2029-   C9 D4       CMP   #$D4
202B-   20 AA C6    JSR   $C6AA
202E-   C5 C5       CMP   $C5
2030-   CC AA A2    CPY   $A2AA
2033-   AC B8 C4    LDY   $C4B8
2036-   8D A0 DF    STA   $DFA0
2039-   D0 D2       BNE   $200D
203B-   CE D4 A0    DEC   $A0D4
203E-   A2 CD       LDX   #$CD
2040-   CF          ???
2041-   D2 C5       CMP   ($C5)
2043-   20 D3 C5    JSR   $C5D3
2046-   D2 C9       CMP   ($C9)
2048-   C1 CC       CMP   ($CC,X)
204A-   C9 DA       CMP   #$DA
204C-   C5 C4       CMP   $C4
204E-   AE 20 D4    LDX   $D420
2051-   C8          INY
2052-   C5 20       CMP   $20
2054-   C6 CF       DEC   $CF
2056-   CC CC CF    CPY   $CFCC
2059-   D7          ???
205A-   C9 CE       CMP   #$CE
205C-   C7          ???
205D-   20 CD C1    JSR   $C1CD
2060-   C3          ???
2061-   D2 CF       CMP   ($CF)
2063-   D3          ???
2064-   A2 AC       LDX   #$AC
2066-   B8          CLV
2067-   C4 8D       CPY   $8D
2069-   A0 DF       LDY   #$DF
206B-   D0 D2       BNE   $203F
206D-   CE D4 A0    DEC   $A0D4
2070-   A2 C1       LDX   #$C1
2072-   CC D4 C5    CPY   $C5D4
2075-   D2 20       CMP   ($20)
2077-   D4          ???
2078-   C8          INY
2079-   C5 20       CMP   $20
207B-   D2 D7       CMP   ($D7)
207D-   D4          ???
207E-   D3          ???
207F-   20 D2 CF    JSR   $CFD2
2082-   D5 D4       CMP   $D4,X
2084-   C9 CE       CMP   #$CE
2086-   C5 A7       CMP   $A7
2088-   D3          ???
2089-   20 C2 C5    JSR   $C5C2
208C-   C1 C8       CMP   ($C8,X)
208E-   D6 C9       DEC   $C9,X
2090-   CF          ???
2091-   D2 BA       CMP   ($BA)
2093-   A2 AC       LDX   #$AC
2095-   B8          CLV
2096-   C4 B8       CPY   $B8
2098-   C4 8D       CPY   $8D
209A-   A0 DF       LDY   #$DF
209C-   D0 D2       BNE   $2070
209E-   CE D4 A0    DEC   $A0D4
20A1-   A2 D3       LDX   #$D3
20A3-   CC CF D4    CPY   $D4CF
20A6-   20 BA 20    JSR   $20BA
20A9-   D3          ???
20AA-   C5 D4       CMP   $D4
20AC-   D3          ???
20AD-   20 D4 C8    JSR   $C8D4
20B0-   C5 20       CMP   $20
20B2-   D2 D7       CMP   ($D7)
20B4-   D4          ???
20B5-   D3          ???
20B6-   20 D3 CC    JSR   $CCD3
20B9-   CF          ???
20BA-   D4          ???
20BB-   A2 AC       LDX   #$AC
20BD-   B8          CLV
20BE-   C4 8D       CPY   $8D
20C0-   A0 DF       LDY   #$DF
20C2-   D0 D2       BNE   $2096
20C4-   CE D4 A0    DEC   $A0D4
20C7-   A2 C4       LDX   #$C4
20C9-   D2 C9       CMP   ($C9)
20CB-   D6 C5       DEC   $C5,X
20CD-   BA          TSX
20CE-   20 D3 C5    JSR   $C5D3
20D1-   D4          ???
20D2-   D3          ???
20D3-   20 D4 C8    JSR   $C8D4
20D6-   C5 20       CMP   $20
20D8-   D2 D7       CMP   ($D7)
20DA-   D4          ???
20DB-   D3          ???
20DC-   20 C4 D2    JSR   $D2C4
20DF-   C9 D6       CMP   #$D6
20E1-   C5 A2       CMP   $A2
20E3-   AC B8 C4    LDY   $C4B8
20E6-   8D A0 DF    STA   $DFA0
20E9-   D0 D2       BNE   $20BD
20EB-   CE D4 A0    DEC   $A0D4
20EE-   A2 D4       LDX   #$D4
20F0-   D2 C1       CMP   ($C1)
20F2-   C3          ???
20F3-   CB          ???
20F4-   BA          TSX
20F5-   20 D3 C5    JSR   $C5D3
20F8-   D4          ???
20F9-   D3          ???
20FA-   20 D4 C8    JSR   $C8D4
20FD-   C5 20       CMP   $20
20FF-   D4          ???
2100-   D2 C1       CMP   ($C1)
2102-   C3          ???
2103-   CB          ???
2104-   20 D4 CF    JSR   $CFD4
2107-   20 C2 C5    JSR   $C5C2
210A-   20 D7 D2    JSR   $D2D7
210D-   C9 D4       CMP   #$D4
210F-   D4          ???
2110-   C5 CE       CMP   $CE
2112-   AF          ???
2113-   D2 C5       CMP   ($C5)
2115-   C1 C4       CMP   ($C4,X)
2117-   A2 AC       LDX   #$AC
2119-   B8          CLV
211A-   C4 8D       CPY   $8D
211C-   A0 DF       LDY   #$DF
211E-   D0 D2       BNE   $20F2
2120-   CE D4 A0    DEC   $A0D4
2123-   A2 D3       LDX   #$D3
2125-   C5 C3       CMP   $C3
2127-   D4          ???
2128-   20 BA 20    JSR   $20BA
212B-   D3          ???
212C-   C5 D4       CMP   $D4
212E-   D3          ???
212F-   20 D4 C8    JSR   $C8D4
2132-   C5 20       CMP   $20
2134-   D3          ???
2135-   C5 C3       CMP   $C3
2137-   D4          ???
2138-   CF          ???
2139-   D2 20       CMP   ($20)
213B-   D4          ???
213C-   CF          ???
213D-   20 C2 C5    JSR   $C5C2
2140-   20 D2 C5    JSR   $C5D2
2143-   C1 C4       CMP   ($C4,X)
2145-   AF          ???
2146-   D7          ???
2147-   D2 C9       CMP   ($C9)
2149-   D4          ???
214A-   D4          ???
214B-   C5 CE       CMP   $CE
214D-   A2 AC       LDX   #$AC
214F-   B8          CLV
2150-   C4 8D       CPY   $8D
2152-   A0 DF       LDY   #$DF
2154-   D0 D2       BNE   $2128
2156-   CE D4 A0    DEC   $A0D4
2159-   A2 D3       LDX   #$D3
215B-   C5 D4       CMP   $D4
215D-   C4 D2       CPY   $D2
215F-   BA          TSX
2160-   20 D3 C5    JSR   $C5D3
2163-   D4          ???
2164-   20 D2 D7    JSR   $D7D2
2167-   D4          ???
2168-   D3          ???
2169-   20 D4 CF    JSR   $CFD4
216C-   20 D2 C5    JSR   $C5D2
216F-   C1 C4       CMP   ($C4,X)
2171-   20 CD CF    JSR   $CFCD
2174-   C4 C5       CPY   $C5
2176-   A2 AC       LDX   #$AC
2178-   B8          CLV
2179-   C4 8D       CPY   $8D
217B-   A0 DF       LDY   #$DF
217D-   D0 D2       BNE   $2151
217F-   CE D4 A0    DEC   $A0D4
2182-   A2 D3       LDX   #$D3
2184-   C5 D4       CMP   $D4
2186-   C4 D7       CPY   $D7
2188-   BA          TSX
2189-   20 D3 C5    JSR   $C5D3
218C-   D4          ???
218D-   20 D2 D7    JSR   $D7D2
2190-   D4          ???
2191-   D3          ???
2192-   20 D4 CF    JSR   $CFD4
2195-   20 D7 D2    JSR   $D2D7
2198-   C9 D4       CMP   #$D4
219A-   C5 20       CMP   $20
219C-   CD CF C4    CMP   $C4CF
219F-   C5 A2       CMP   $A2
21A1-   AC B8 C4    LDY   $C4B8
21A4-   8D A0 DF    STA   $DFA0
21A7-   D0 D2       BNE   $217B
21A9-   CE D4 A0    DEC   $A0D4
21AC-   A2 C4       LDX   #$C4
21AE-   C2          ???
21AF-   D5 C6       CMP   $C6,X
21B1-   C6 BA       DEC   $BA
21B3-   20 D3 C5    JSR   $C5D3
21B6-   D4          ???
21B7-   20 D4 C8    JSR   $C8D4
21BA-   C5 20       CMP   $20
21BC-   D2 C5       CMP   ($C5)
21BE-   C1 C4       CMP   ($C4,X)
21C0-   AF          ???
21C1-   D7          ???
21C2-   D2 C9       CMP   ($C9)
21C4-   D4          ???
21C5-   C5 20       CMP   $20
21C7-   C2          ???
21C8-   D5 C6       CMP   $C6,X
21CA-   C6 C5       DEC   $C5
21CC-   D2 20       CMP   ($20)
21CE-   C1 C4       CMP   ($C4,X)
21D0-   C4 D2       CPY   $D2
21D2-   C5 D3       CMP   $D3
21D4-   D3          ???
21D5-   A2 AC       LDX   #$AC
21D7-   B8          CLV
21D8-   C4 B8       CPY   $B8
21DA-   C4 8D       CPY   $8D
21DC-   A0 DF       LDY   #$DF
21DE-   D7          ???
21DF-   C1 C9       CMP   ($C9,X)
21E1-   D4          ???
21E2-   8D A0 DF    STA   $DFA0
21E5-   D0 D2       BNE   $21B9
21E7-   CE D4 A0    DEC   $A0D4
21EA-   A2 C5       LDX   #$C5
21EC-   C1 C3       CMP   ($C3,X)
21EE-   C8          INY
21EF-   20 CF C6    JSR   $C6CF
21F2-   20 D4 C8    JSR   $C8D4
21F5-   C5 D3       CMP   $D3
21F7-   C5 20       CMP   $20
21F9-   D3          ???
21FA-   C5 D4       CMP   $D4
21FC-   D4          ???
21FD-   C9 CE       CMP   #$CE
21FF-   C7          ???
2200-   D3          ???
2201-   20 C1 D2    JSR   $D2C1
2204-   C5 20       CMP   $20
2206-   C9 CE       CMP   #$CE
2208-   C8          INY
2209-   C5 D2       CMP   $D2
220B-   C9 D4       CMP   #$D4
220D-   C5 C4       CMP   $C4
220F-   A2 AC       LDX   #$AC
2211-   B8          CLV
2212-   C4 8D       CPY   $8D
2214-   A0 DF       LDY   #$DF
2216-   D0 D2       BNE   $21EA
2218-   CE D4 A0    DEC   $A0D4
221B-   A2 C6       LDX   #$C6
221D-   D2 CF       CMP   ($CF)
221F-   CD 20 D4    CMP   $D420
2222-   C8          INY
2223-   C5 20       CMP   $20
2225-   D0 D2       BNE   $21F9
2227-   C5 D6       CMP   $D6
2229-   C9 CF       CMP   #$CF
222B-   D5 D3       CMP   $D3,X
222D-   20 D3 D4    JSR   $D4D3
2230-   C1 D4       CMP   ($D4,X)
2232-   C5 BB       CMP   $BB
2234-   20 C9 C6    JSR   $C6C9
2237-   20 D9 CF    JSR   $CFD9
223A-   D5 20       CMP   $20,X
223C-   C1 D2       CMP   ($D2,X)
223E-   C5 A2       CMP   $A2
2240-   AC B8 C4    LDY   $C4B8
2243-   8D A0 DF    STA   $DFA0
2246-   D0 D2       BNE   $221A
2248-   CE D4 A0    DEC   $A0D4
224B-   A2 C1       LDX   #$C1
224D-   CC D2 C5    CPY   $C5D2
2250-   C1 C4       CMP   ($C4,X)
2252-   D9 20 D5    CMP   $D520,Y
2255-   D3          ???
2256-   C9 CE       CMP   #$CE
2258-   C7          ???
2259-   20 D3 C5    JSR   $C5D3
225C-   C3          ???
225D-   D4          ???
225E-   CF          ???
225F-   D2 20       CMP   ($20)
2261-   B6 AC       LDX   $AC,Y
2263-   20 C4 D2    JSR   $D2C4
2266-   C9 D6       CMP   #$D6
2268-   C5 20       CMP   $20
226A-   B1 AC       LDA   ($AC),Y
226C-   20 C6 CF    JSR   $CFC6
226F-   D2 A2       CMP   ($A2)
2271-   AC B8 C4    LDY   $C4B8
2274-   8D A0 DF    STA   $DFA0
2277-   D0 D2       BNE   $224B
2279-   CE D4 A0    DEC   $A0D4
227C-   A2 C5       LDX   #$C5
227E-   D8          CLD
227F-   C1 CD       CMP   ($CD,X)
2281-   D0 CC       BNE   $224F
2283-   C5 AC       CMP   $AC
2285-   20 D4 C8    JSR   $C8D4
2288-   C5 CE       CMP   $CE
228A-   20 D9 CF    JSR   $CFD9
228D-   D5 20       CMP   $20,X
228F-   C4 CF       CPY   $CF
2291-   CE A7 D4    DEC   $D4A7
2294-   20 C8 C1    JSR   $C1C8
2297-   D6 C5       DEC   $C5,X
2299-   20 D4 CF    JSR   $CFD4
229C-   20 D3 C5    JSR   $C5D3
229F-   D4          ???
22A0-   20 C9 D4    JSR   $D4C9
22A3-   20 C1 C7    JSR   $C7C1
22A6-   C1 C9       CMP   ($C9,X)
22A8-   CE A2 AC    DEC   $ACA2
22AB-   B8          CLV
22AC-   C4 8D       CPY   $8D
22AE-   A0 DF       LDY   #$DF
22B0-   D0 D2       BNE   $2284
22B2-   CE D4 A0    DEC   $A0D4
22B5-   A2 D5       LDX   #$D5
22B7-   CE CC C5    DEC   $C5CC
22BA-   D3          ???
22BB-   D3          ???
22BC-   20 D9 CF    JSR   $CFD9
22BF-   D5 20       CMP   $20,X
22C1-   D7          ???
22C2-   C1 CE       CMP   ($CE,X)
22C4-   D4          ???
22C5-   20 D4 C8    JSR   $C8D4
22C8-   CF          ???
22C9-   D3          ???
22CA-   C5 20       CMP   $20
22CC-   D3          ???
22CD-   C5 D4       CMP   $D4
22CF-   D4          ???
22D0-   C9 CE       CMP   #$CE
22D2-   C7          ???
22D3-   D3          ???
22D4-   20 C3 C8    JSR   $C8C3
22D7-   C1 CE       CMP   ($CE,X)
22D9-   C7          ???
22DA-   C5 C4       CMP   $C4
22DC-   AE A2 AC    LDX   $ACA2
22DF-   B8          CLV
22E0-   C4 8D       CPY   $8D
22E2-   A0 DF       LDY   #$DF
22E4-   D0 D2       BNE   $22B8
22E6-   CE D4 A0    DEC   $A0D4
22E9-   A2 D4       LDX   #$D4
22EB-   C8          INY
22EC-   C9 D3       CMP   #$D3
22EE-   20 CC C9    JSR   $C9CC
22F1-   C2          ???
22F2-   D2 C1       CMP   ($C1)
22F4-   D2 D9       CMP   ($D9)
22F6-   20 C1 CC    JSR   $CCC1
22F9-   D3          ???
22FA-   CF          ???
22FB-   20 D5 D3    JSR   $D3D5
22FE-   C5 D3       CMP   $D3
2300-   20 D4 C8    JSR   $C8D4
2303-   C5 20       CMP   $20
2305-   D3          ???
2306-   C1 CD       CMP   ($CD,X)
2308-   C5 20       CMP   $20
230A-   C9 CF       CMP   #$CF
230C-   C2          ???
230D-   A2 AC       LDX   #$AC
230F-   B8          CLV
2310-   C4 8D       CPY   $8D
2312-   A0 DF       LDY   #$DF
2314-   D0 D2       BNE   $22E8
2316-   CE D4 A0    DEC   $A0D4
2319-   A2 D4       LDX   #$D4
231B-   C1 C2       CMP   ($C2,X)
231D-   CC C5 20    CPY   $20C5
2320-   C1 D3       CMP   ($D3,X)
2322-   20 D4 C8    JSR   $C8D4
2325-   C5 20       CMP   $20
2327-   CF          ???
2328-   D0 C5       BNE   $22EF
232A-   D2 C1       CMP   ($C1)
232C-   D4          ???
232D-   C9 CE       CMP   #$CE
232F-   C7          ???
2330-   20 D3 D9    JSR   $D9D3
2333-   D3          ???
2334-   D4          ???
2335-   C5 CD       CMP   $CD
2337-   20 A8 C4    JSR   $C4A8
233A-   CF          ???
233B-   D3          ???
233C-   20 CF D2    JSR   $D2CF
233F-   A2 AC       LDX   #$AC
2341-   B8          CLV
2342-   C4 8D       CPY   $8D
2344-   A0 DF       LDY   #$DF
2346-   D0 D2       BNE   $231A
2348-   CE D4 A0    DEC   $A0D4
234B-   A2 D0       LDX   #$D0
234D-   D2 CF       CMP   ($CF)
234F-   C4 CF       CPY   $CF
2351-   D3          ???
2352-   A9 20       LDA   #$20
2354-   D4          ???
2355-   CF          ???
2356-   20 C3 C1    JSR   $C1C3
2359-   D2 D2       CMP   ($D2)
235B-   D9 20 CF    CMP   $CF20,Y
235E-   D6 C5       DEC   $C5,X
2360-   D2 20       CMP   ($20)
2362-   C1 CE       CMP   ($CE,X)
2364-   D9 20 D0    CMP   $D020,Y
2367-   D2 C5       CMP   ($C5)
2369-   D6 C9       DEC   $C9,X
236B-   CF          ???
236C-   D5 D3       CMP   $D3,X
236E-   20 D3 C5    JSR   $C5D3
2371-   D4          ???
2372-   D4          ???
2373-   C9 CE       CMP   #$CE
2375-   C7          ???
2376-   D3          ???
2377-   AE A2 AC    LDX   $ACA2
237A-   B8          CLV
237B-   C4 B8       CPY   $B8
237D-   C4 8D       CPY   $8D
237F-   A0 DF       LDY   #$DF
2381-   D7          ???
2382-   C1 C9       CMP   ($C9,X)
2384-   D4          ???
2385-   8D AA 8D    STA   $8DAA
2388-   A0 DF       LDY   #$DF
238A-   D0 D2       BNE   $235E
238C-   CE D4 A0    DEC   $A0D4
238F-   A2 CF       LDX   #$CF
2391-   CE C3 C5    DEC   $C5C3
2394-   20 D4 C8    JSR   $C8D4
2397-   C5 20       CMP   $20
2399-   D3          ???
239A-   C5 D4       CMP   $D4
239C-   D4          ???
239D-   C9 CE       CMP   #$CE
239F-   C7          ???
23A0-   D3          ???
23A1-   20 C1 D2    JSR   $D2C1
23A4-   C5 20       CMP   $20
23A6-   C1 D3       CMP   ($D3,X)
23A8-   20 C4 C5    JSR   $C5C4
23AB-   D3          ???
23AC-   C9 D2       CMP   #$D2
23AE-   C5 C4       CMP   $C4
23B0-   AC A2 AC    LDY   $ACA2
23B3-   B8          CLV
23B4-   C4 8D       CPY   $8D
23B6-   A0 DF       LDY   #$DF
23B8-   D0 D2       BNE   $238C
23BA-   CE D4 A0    DEC   $A0D4
23BD-   A2 D9       LDX   #$D9
23BF-   CF          ???
23C0-   D5 20       CMP   $20,X
23C2-   D5 D3       CMP   $D3,X
23C4-   C5 20       CMP   $20
23C6-   D4          ???
23C7-   C8          INY
23C8-   C5 20       CMP   $20
23CA-   C4 D2       CPY   $D2
23CC-   D7          ???
23CD-   D4          ???
23CE-   D3          ???
23CF-   20 CD C1    JSR   $C1CD
23D2-   C3          ???
23D3-   D2 CF       CMP   ($CF)
23D5-   20 D4 CF    JSR   $CFD4
23D8-   20 C3 C1    JSR   $C1C3
23DB-   CC CC A2    CPY   $A2CC
23DE-   AC B8 C4    LDY   $C4B8
23E1-   8D A0 DF    STA   $DFA0
23E4-   D0 D2       BNE   $23B8
23E6-   CE D4 A0    DEC   $A0D4
23E9-   A2 D4       LDX   #$D4
23EB-   C8          INY
23EC-   C5 20       CMP   $20
23EE-   D2 D7       CMP   ($D7)
23F0-   D4          ???
23F1-   D3          ???
23F2-   20 D2 CF    JSR   $CFD2
23F5-   D5 D4       CMP   $D4,X
23F7-   C9 CE       CMP   #$CE
23F9-   C5 20       CMP   $20
23FB-   D4          ???
23FC-   CF          ???
23FD-   20 CD C1    JSR   $C1CD
2400-   CB          ???
2401-   C5 20       CMP   $20
2403-   D4          ???
2404-   C8          INY
2405-   C5 20       CMP   $20
2407-   A2 AC       LDX   #$AC
2409-   B8          CLV
240A-   C4 8D       CPY   $8D
240C-   A0 DF       LDY   #$DF
240E-   D0 D2       BNE   $23E2
2410-   CE D4 A0    DEC   $A0D4
2413-   A2 C1       LDX   #$C1
2415-   D0 D0       BNE   $23E7
2417-   D2 CF       CMP   ($CF)
2419-   D0 D2       BNE   $23ED
241B-   C9 C1       CMP   #$C1
241D-   D4          ???
241E-   C5 20       CMP   $20
2420-   D2 C5       CMP   ($C5)
2422-   C1 C4       CMP   ($C4,X)
2424-   20 CF D2    JSR   $D2CF
2427-   20 D7 D2    JSR   $D2D7
242A-   C9 D4       CMP   #$D4
242C-   C5 20       CMP   $20
242E-   C3          ???
242F-   C8          INY
2430-   C1 CE       CMP   ($CE,X)
2432-   C7          ???
2433-   C5 20       CMP   $20
2435-   D4          ???
2436-   CF          ???
2437-   A2 AC       LDX   #$AC
2439-   B8          CLV
243A-   C4 8D       CPY   $8D
243C-   A0 DF       LDY   #$DF
243E-   D0 D2       BNE   $2412
2440-   CE D4 A0    DEC   $A0D4
2443-   A2 D4       LDX   #$D4
2445-   C8          INY
2446-   C5 20       CMP   $20
2448-   C4 C9       CPY   $C9
244A-   D3          ???
244B-   CB          ???
244C-   AE A2 AC    LDX   $ACA2
244F-   B8          CLV
2450-   C4 B8       CPY   $B8
2452-   C4 8D       CPY   $8D
2454-   A0 DF       LDY   #$DF
2456-   D0 D2       BNE   $242A
2458-   CE D4 A0    DEC   $A0D4
245B-   A2 C6       LDX   #$C6
245D-   CF          ???
245E-   D2 20       CMP   ($20)
2460-   D4          ???
2461-   C8          INY
2462-   C5 20       CMP   $20
2464-   D3          ???
2465-   C1 CB       CMP   ($CB,X)
2467-   C5 20       CMP   $20
2469-   CF          ???
246A-   C6 20       DEC   $20
246C-   D0 CC       BNE   $243A
246E-   C1 D9       CMP   ($D9,X)
2470-   C9 CE       CMP   #$CE
2472-   C7          ???
2473-   20 C9 D4    JSR   $D4C9
2476-   20 D3 C1    JSR   $C1D3
2479-   C6 C5       DEC   $C5
247B-   AC A2 AC    LDY   $ACA2
247E-   B8          CLV
247F-   C4 8D       CPY   $8D
2481-   A0 DF       LDY   #$DF
2483-   D0 D2       BNE   $2457
2485-   CE D4 A0    DEC   $A0D4
2488-   A2 D7       LDX   #$D7
248A-   C5 20       CMP   $20
248C-   D7          ???
248D-   CF          ???
248E-   CE A7 D4    DEC   $D4A7
2491-   20 C2 C5    JSR   $C5C2
2494-   20 C4 CF    JSR   $CFC4
2497-   C9 CE       CMP   #$CE
2499-   C7          ???
249A-   20 D4 C8    JSR   $C8D4
249D-   C1 D4       CMP   ($D4,X)
249F-   20 C8 C5    JSR   $C5C8
24A2-   D2 C5       CMP   ($C5)
24A4-   AD AD D9    LDA   $D9AD
24A7-   CF          ???
24A8-   D5 20       CMP   $20,X
24AA-   C3          ???
24AB-   C1 CE       CMP   ($CE,X)
24AD-   A2 AC       LDX   #$AC
24AF-   B8          CLV
24B0-   C4 8D       CPY   $8D
24B2-   A0 DF       LDY   #$DF
24B4-   D0 D2       BNE   $2488
24B6-   CE D4 A0    DEC   $A0D4
24B9-   A2 C5       LDX   #$C5
24BB-   D8          CLD
24BC-   D0 C5       BNE   $2483
24BE-   D2 C9       CMP   ($C9)
24C0-   CD C5 CE    CMP   $CEC5
24C3-   D4          ???
24C4-   20 CF CE    JSR   $CECF
24C7-   20 D9 CF    JSR   $CFD9
24CA-   D5 D2       CMP   $D2,X
24CC-   20 CF D7    JSR   $D7CF
24CF-   CE 20 D7    DEC   $D720
24D2-   C9 D4       CMP   #$D4
24D4-   C8          INY
24D5-   20 D4 C8    JSR   $C8D4
24D8-   C5 D3       CMP   $D3
24DA-   C5 20       CMP   $20
24DC-   C3          ???
24DD-   C1 CC       CMP   ($CC,X)
24DF-   CC D3 BB    CPY   $BBD3
24E2-   A2 AC       LDX   #$AC
24E4-   B8          CLV
24E5-   C4 8D       CPY   $8D
24E7-   A0 DF       LDY   #$DF
24E9-   D0 D2       BNE   $24BD
24EB-   CE D4 A0    DEC   $A0D4
24EE-   A2 D4       LDX   #$D4
24F0-   C8          INY
24F1-   C1 D4       CMP   ($D4,X)
24F3-   20 D7 C1    JSR   $C1D7
24F6-   D9 20 C9    CMP   $C920,Y
24F9-   C6 20       DEC   $20
24FB-   D3          ???
24FC-   CF          ???
24FD-   CD C5 D4    CMP   $D4C5
2500-   C8          INY
2501-   C9 CE       CMP   #$CE
2503-   C7          ???
2504-   20 C2 C1    JSR   $C1C2
2507-   C4 20       CPY   $20
2509-   C8          INY
250A-   C1 D0       CMP   ($D0,X)
250C-   D0 C5       BNE   $24D3
250E-   CE D3 AC    DEC   $ACD3
2511-   A2 AC       LDX   #$AC
2513-   B8          CLV
2514-   C4 8D       CPY   $8D
2516-   A0 DF       LDY   #$DF
2518-   D0 D2       BNE   $24EC
251A-   CE D4 A0    DEC   $A0D4
251D-   A2 C9       LDX   #$C9
251F-   D4          ???
2520-   A7          ???
2521-   D3          ???
2522-   20 CF CE    JSR   $CECF
2525-   20 D9 CF    JSR   $CFD9
2528-   D5 AD       CMP   $AD,X
252A-   AD CE CF    LDA   $CFCE
252D-   D4          ???
252E-   20 CD C5    JSR   $C5CD
2531-   A1 20       LDA   ($20,X)
2533-   BA          TSX
2534-   A9 A2       LDA   #$A2
2536-   AC B8 C4    LDY   $C4B8
2539-   B8          CLV
253A-   C4 B8       CPY   $B8
253C-   C4 8D       CPY   $8D
253E-   A0 DF       LDY   #$DF
2540-   D7          ???
2541-   C1 C9       CMP   ($C9,X)
2543-   D4          ???
2544-   8D AA 8D    STA   $8DAA
2547-   A0 CA       LDY   #$CA
2549-   CD D0 A0    CMP   $A0D0
254C-   D2 C5       CMP   ($C5)
254E-   C5 CE       CMP   $CE
2550-   D4          ???
2551-   D2 D9       CMP   ($D9)
2553-   8D AA 8D    STA   $8DAA
2556-   AA          TAX
2557-   E0 E0       CPX   #$E0
2559-   E0 E0       CPX   #$E0
255B-   E0 E0       CPX   #$E0
255D-   E0 E0       CPX   #$E0
255F-   E0 E0       CPX   #$E0
2561-   E0 E0       CPX   #$E0
2563-   E0 E0       CPX   #$E0
2565-   E0 E0       CPX   #$E0
2567-   E0 E0       CPX   #$E0
2569-   E0 E0       CPX   #$E0
256B-   E0 E0       CPX   #$E0
256D-   E0 E0       CPX   #$E0
256F-   E0 E0       CPX   #$E0
2571-   E0 E0       CPX   #$E0
2573-   E0 E0       CPX   #$E0
2575-   AA          TAX
2576-   8D AA 20    STA   $20AA
2579-   20 20 20    JSR   $2020
257C-   20 20 20    JSR   $2020
257F-   20 C2 CF    JSR   $CFC2
2582-   D4          ???
2583-   D4          ???
2584-   CF          ???
2585-   CD 20 C9    CMP   $C920
2588-   CE C3 CC    DEC   $CCC3
258B-   D5 C4       CMP   $C4,X
258D-   C5 D3       CMP   $D3
258F-   20 20 20    JSR   $2020
2592-   20 20 20    JSR   $2020
2595-   20 AA 8D    JSR   $8DAA
2598-   AA          TAX
2599-   AC AC AC    LDY   $ACAC
259C-   AC AC AC    LDY   $ACAC
259F-   AC AC AC    LDY   $ACAC
25A2-   AC AC AC    LDY   $ACAC
25A5-   AC AC AC    LDY   $ACAC
25A8-   AC AC AC    LDY   $ACAC
25AB-   AC AC AC    LDY   $ACAC
25AE-   AC AC AC    LDY   $ACAC
25B1-   AC AC AC    LDY   $ACAC
25B4-   AC AC AC    LDY   $ACAC
25B7-   AA          TAX
25B8-   8D AA 8D    STA   $8DAA
25BB-   A0 D0       LDY   #$D0
25BD-   D5 D4       CMP   $D4,X
25BF-   A0 C6       LDY   #$C6
25C1-   C9 CC       CMP   #$CC
25C3-   C5 C9       CMP   $C9
25C5-   CF          ???
25C6-   AE CC C9    LDX   $C9CC
25C9-   C2          ???
25CA-   8D A0 D0    STA   $D0A0
25CD-   D5 D4       CMP   $D4,X
25CF-   A0 D2       LDY   #$D2
25D1-   C5 D1       CMP   $D1
25D3-   D5 C9       CMP   $C9,X
25D5-   D2 C5       CMP   ($C5)
25D7-   C4 AE       CPY   $AE
25D9-   CC C9 C2    CPY   $C2C9
25DC-   8D AA 8D    STA   $8DAA
25DF-   D2 C5       CMP   ($C5)
25E1-   D4          ???
25E2-   CF          ???
25E3-   D2 D4       CMP   ($D4)
25E5-   A0 D3       LDY   #$D3
25E7-   D4          ???
25E8-   D2 A0       CMP   ($A0)
25EA-   A2 C9       LDX   #$C9
25EC-   C6 20       DEC   $20
25EE-   D9 CF D5    CMP   $D5CF,Y
25F1-   20 C1 D2    JSR   $D2C1
25F4-   C5 20       CMP   $20
25F6-   D2 C9       CMP   ($C9)
25F8-   C3          ???
25F9-   C8          INY
25FA-   AC 20 C1    LDY   $C120
25FD-   CE D9 C8    DEC   $C8D9
2600-   CF          ???
2601-   D7          ???
2602-   AE AE AE    LDX   $AEAE
2605-   A2 8D       LDX   #$8D
2607-   AA          TAX
2608-   8D 00 00    STA   $0000
