0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C6    LDY   $C620,X
0950-   C9 CC       CMP   #$CC
0952-   C5 C9       CMP   $C9
0954-   CF          ???
0955-   20 20 C4    JSR   $C420
0958-   C5 CD       CMP   $CD
095A-   CF          ???
095B-   20 BE AD    JSR   $ADBE
095E-   20 20 20    JSR   $2020
0961-   20 20 20    JSR   $2020
0964-   AA          TAX
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B0       BCS   $094C
099C-   AE B0 B1    LDX   $B1B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B0    JSR   $B020
09D4-   B3          ???
09D5-   AF          ???
09D6-   B0 B4       BCS   $098C
09D8-   AF          ???
09D9-   B1 B9       LDA   ($B9),Y
09DB-   B8          CLV
09DC-   B0 20       BCS   $09FE
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 C4    STA   $C4A0
0B02-   D3          ???
0B03-   CB          ???
0B04-   A0 C6       LDY   #$C6
0B06-   C9 CC       CMP   #$CC
0B08-   C5 C9       CMP   $C9
0B0A-   CF          ???
0B0B-   AE C4 C5    LDX   $C5C4
0B0E-   CD CF 8D    CMP   $8DCF
0B11-   AA          TAX
0B12-   8D AA E0    STA   $E0AA
0B15-   E0 E0       CPX   #$E0
0B17-   E0 E0       CPX   #$E0
0B19-   E0 E0       CPX   #$E0
0B1B-   E0 E0       CPX   #$E0
0B1D-   E0 E0       CPX   #$E0
0B1F-   E0 E0       CPX   #$E0
0B21-   E0 E0       CPX   #$E0
0B23-   E0 E0       CPX   #$E0
0B25-   E0 E0       CPX   #$E0
0B27-   E0 E0       CPX   #$E0
0B29-   E0 E0       CPX   #$E0
0B2B-   E0 E0       CPX   #$E0
0B2D-   E0 E0       CPX   #$E0
0B2F-   E0 E0       CPX   #$E0
0B31-   E0 AA       CPX   #$AA
0B33-   8D AA 20    STA   $20AA
0B36-   20 D4 CF    JSR   $CFD4
0B39-   D0 20       BNE   $0B5B
0B3B-   C9 CE       CMP   #$CE
0B3D-   C3          ???
0B3E-   CC D5 C4    CPY   $C4D5
0B41-   C5 D3       CMP   $D3
0B43-   20 A8 D0    JSR   $D0A8
0B46-   D5 D4       CMP   $D4,X
0B48-   D3          ???
0B49-   AC 20 CD    LDY   $CD20
0B4C-   C1 C3       CMP   ($C3,X)
0B4E-   D2 CF       CMP   ($CF)
0B50-   D3          ???
0B51-   A9 20       LDA   #$20
0B53-   AA          TAX
0B54-   8D AA AC    STA   $ACAA
0B57-   AC AC AC    LDY   $ACAC
0B5A-   AC AC AC    LDY   $ACAC
0B5D-   AC AC AC    LDY   $ACAC
0B60-   AC AC AC    LDY   $ACAC
0B63-   AC AC AC    LDY   $ACAC
0B66-   AC AC AC    LDY   $ACAC
0B69-   AC AC AC    LDY   $ACAC
0B6C-   AC AC AC    LDY   $ACAC
0B6F-   AC AC AC    LDY   $ACAC
0B72-   AC AC AA    LDY   $AAAC
0B75-   8D AA 8D    STA   $8DAA
0B78-   A0 D0       LDY   #$D0
0B7A-   D5 D4       CMP   $D4,X
0B7C-   A0 C4       LDY   #$C4
0B7E-   C5 C3       CMP   $C3
0B80-   D3          ???
0B81-   8D A0 D5    STA   $D5A0
0B84-   D3          ???
0B85-   C5 20       CMP   $20
0B87-   C6 C9       DEC   $C9
0B89-   CC C5 C9    CPY   $C9C5
0B8C-   CF          ???
0B8D-   AE CD C1    LDX   $C1CD
0B90-   C3          ???
0B91-   8D AA 8D    STA   $8DAA
0B94-   A0 D0       LDY   #$D0
0B96-   D5 D4       CMP   $D4,X
0B98-   A0 C6       LDY   #$C6
0B9A-   C9 CC       CMP   #$CC
0B9C-   C5 C9       CMP   $C9
0B9E-   CF          ???
0B9F-   AE C8 CF    LDX   $CFC8
0BA2-   CF          ???
0BA3-   CB          ???
0BA4-   D3          ???
0BA5-   8D AA 8D    STA   $8DAA
0BA8-   A0 CF       LDY   #$CF
0BAA-   C2          ???
0BAB-   CA          DEX
0BAC-   A0 A4       LDY   #$A4
0BAE-   C2          ???
0BAF-   C6 C5       DEC   $C5
0BB1-   B0 8D       BCS   $0B40
0BB3-   A0 CF       LDY   #$CF
0BB5-   D2 C7       CMP   ($C7)
0BB7-   20 A4 B6    JSR   $B6A4
0BBA-   B0 B0       BCS   $0B6C
0BBC-   B0 8D       BCS   $0B4B
0BBE-   AA          TAX
0BBF-   8D AA E0    STA   $E0AA
0BC2-   E0 E0       CPX   #$E0
0BC4-   E0 E0       CPX   #$E0
0BC6-   E0 E0       CPX   #$E0
0BC8-   E0 E0       CPX   #$E0
0BCA-   E0 E0       CPX   #$E0
0BCC-   E0 E0       CPX   #$E0
0BCE-   E0 E0       CPX   #$E0
0BD0-   E0 E0       CPX   #$E0
0BD2-   E0 E0       CPX   #$E0
0BD4-   E0 E0       CPX   #$E0
0BD6-   E0 E0       CPX   #$E0
0BD8-   E0 E0       CPX   #$E0
0BDA-   E0 E0       CPX   #$E0
0BDC-   E0 E0       CPX   #$E0
0BDE-   E0 AA       CPX   #$AA
0BE0-   8D AA 20    STA   $20AA
0BE3-   20 20 20    JSR   $2020
0BE6-   20 20 D0    JSR   $D020
0BE9-   D2 CF       CMP   ($CF)
0BEB-   C7          ???
0BEC-   D2 C1       CMP   ($C1)
0BEE-   CD 20 CD    CMP   $CD20
0BF1-   C1 C9       CMP   ($C9,X)
0BF3-   CE 20 C2    DEC   $C220
0BF6-   CF          ???
0BF7-   C4 D9       CPY   $D9
0BF9-   20 20 20    JSR   $2020
0BFC-   20 20 20    JSR   $2020
0BFF-   20 AA 8D    JSR   $8DAA
0C02-   AA          TAX
0C03-   AC AC AC    LDY   $ACAC
0C06-   AC AC AC    LDY   $ACAC
0C09-   AC AC AC    LDY   $ACAC
0C0C-   AC AC AC    LDY   $ACAC
0C0F-   AC AC AC    LDY   $ACAC
0C12-   AC AC AC    LDY   $ACAC
0C15-   AC AC AC    LDY   $ACAC
0C18-   AC AC AC    LDY   $ACAC
0C1B-   AC AC AC    LDY   $ACAC
0C1E-   AC AC AC    LDY   $ACAC
0C21-   AA          TAX
0C22-   8D AA 8D    STA   $8DAA
0C25-   AA          TAX
0C26-   8D AA 8D    STA   $8DAA
0C29-   AA          TAX
0C2A-   AA          TAX
0C2B-   20 C2 C9    JSR   $C9C2
0C2E-   C7          ???
0C2F-   20 CC D5    JSR   $D5CC
0C32-   CD D0 D3    CMP   $D3D0
0C35-   20 AD AD    JSR   $ADAD
0C38-   20 C8 C9    JSR   $C9C8
0C3B-   C7          ???
0C3C-   C8          INY
0C3D-   20 CC C5    JSR   $C5CC
0C40-   D6 C5       DEC   $C5,X
0C42-   CC 20 C3    CPY   $C320
0C45-   CF          ???
0C46-   C4 C5       CPY   $C5
0C48-   8D AA 8D    STA   $8DAA
0C4B-   AA          TAX
0C4C-   8D AA 8D    STA   $8DAA
0C4F-   AA          TAX
0C50-   8D AA AA    STA   $AAAA
0C53-   20 D0 D5    JSR   $D5D0
0C56-   D4          ???
0C57-   20 C1 20    JSR   $20C1
0C5A-   C6 C5       DEC   $C5
0C5C-   D7          ???
0C5D-   20 D6 C1    JSR   $C1D6
0C60-   CC D5 C5    CPY   $C5D5
0C63-   D3          ???
0C64-   20 C1 D4    JSR   $D4C1
0C67-   20 A4 B3    JSR   $B3A4
0C6A-   B0 B0       BCS   $0C1C
0C6C-   20 D4 CF    JSR   $CFD4
0C6F-   20 D0 D2    JSR   $D2D0
0C72-   CF          ???
0C73-   D6 C5       DEC   $C5,X
0C75-   8D AA AA    STA   $AAAA
0C78-   20 C2 D3    JSR   $D3C2
0C7B-   C1 D6       CMP   ($D6,X)
0C7D-   C9 CE       CMP   #$CE
0C7F-   C7          ???
0C80-   20 C1 CE    JSR   $CEC1
0C83-   C4 20       CPY   $20
0C85-   C2          ???
0C86-   CC CF C1    CPY   $C1CF
0C89-   C4 C9       CPY   $C9
0C8B-   CE C7 8D    DEC   $8DC7
0C8E-   AA          TAX
0C8F-   8D A0 CC    STA   $CCA0
0C92-   C4 C1       CPY   $C1
0C94-   A0 A3       LDY   #$A3
0C96-   B0 8D       BCS   $0C25
0C98-   A0 D3       LDY   #$D3
0C9A-   D4          ???
0C9B-   C1 A0       CMP   ($A0,X)
0C9D-   A4 B3       LDY   $B3
0C9F-   B0 B0       BCS   $0C51
0CA1-   8D A0 CC    STA   $CCA0
0CA4-   C4 C1       CPY   $C1
0CA6-   A0 A3       LDY   #$A3
0CA8-   B1 8D       LDA   ($8D),Y
0CAA-   A0 D3       LDY   #$D3
0CAC-   D4          ???
0CAD-   C1 A0       CMP   ($A0,X)
0CAF-   A4 B3       LDY   $B3
0CB1-   B0 B1       BCS   $0C64
0CB3-   8D A0 CC    STA   $CCA0
0CB6-   C4 C1       CPY   $C1
0CB8-   A0 A3       LDY   #$A3
0CBA-   B2 8D       LDA   ($8D)
0CBC-   A0 D3       LDY   #$D3
0CBE-   D4          ???
0CBF-   C1 A0       CMP   ($A0,X)
0CC1-   A4 B3       LDY   $B3
0CC3-   B0 B2       BCS   $0C77
0CC5-   8D A0 CC    STA   $CCA0
0CC8-   C4 C1       CPY   $C1
0CCA-   A0 A3       LDY   #$A3
0CCC-   B3          ???
0CCD-   8D A0 D3    STA   $D3A0
0CD0-   D4          ???
0CD1-   C1 A0       CMP   ($A0,X)
0CD3-   A4 B3       LDY   $B3
0CD5-   B0 B3       BCS   $0C8A
0CD7-   8D AA 8D    STA   $8DAA
0CDA-   AA          TAX
0CDB-   8D AA AA    STA   $AAAA
0CDE-   20 C2 D3    JSR   $D3C2
0CE1-   C1 D6       CMP   ($D6,X)
0CE3-   C5 20       CMP   $20
0CE5-   C4 CF       CPY   $CF
0CE7-   C5 D3       CMP   $D3
0CE9-   20 C1 20    JSR   $20C1
0CEC-   C4 CF       CPY   $CF
0CEE-   D3          ???
0CEF-   20 C2 C9    JSR   $C9C2
0CF2-   CE C1 D2    DEC   $D2C1
0CF5-   D9 20 D3    CMP   $D320,Y
0CF8-   C1 D6       CMP   ($D6,X)
0CFA-   C5 20       CMP   $20
0CFC-   D7          ???
0CFD-   C9 D4       CMP   #$D4
0CFF-   C8          INY
0D00-   20 D4 C8    JSR   $C8D4
0D03-   C5 8D       CMP   $8D
0D05-   AA          TAX
0D06-   AA          TAX
0D07-   20 C3 CF    JSR   $CFC3
0D0A-   CD CD C1    CMP   $C1CD
0D0D-   CE C4 20    DEC   $20C4
0D10-   CC C9 CE    CPY   $CEC9
0D13-   C5 20       CMP   $20
0D15-   D0 C1       BNE   $0CD8
0D17-   D2 C1       CMP   ($C1)
0D19-   CD C5 D4    CMP   $D4C5
0D1C-   C5 D2       CMP   $D2
0D1E-   D3          ???
0D1F-   20 D3 D4    JSR   $D4D3
0D22-   CF          ???
0D23-   D2 C5       CMP   ($C5)
0D25-   C4 20       CPY   $20
0D27-   C9 CE       CMP   #$CE
0D29-   20 D4 C8    JSR   $C8D4
0D2C-   C5 8D       CMP   $8D
0D2E-   AA          TAX
0D2F-   AA          TAX
0D30-   20 D3 D4    JSR   $D4D3
0D33-   D2 C9       CMP   ($C9)
0D35-   CE C7 20    DEC   $20C7
0D38-   C3          ???
0D39-   CF          ???
0D3A-   CE D4 C1    DEC   $C1D4
0D3D-   C9 CE       CMP   #$CE
0D3F-   C5 C4       CMP   $C4
0D41-   20 C1 D4    JSR   $D4C1
0D44-   20 D4 C8    JSR   $C8D4
0D47-   C5 20       CMP   $20
0D49-   D3          ???
0D4A-   D0 C5       BNE   $0D11
0D4C-   C3          ???
0D4D-   C9 C6       CMP   #$C6
0D4F-   C9 C5       CMP   #$C5
0D51-   C4 20       CPY   $20
0D53-   C1 C4       CMP   ($C4,X)
0D55-   C4 D2       CPY   $D2
0D57-   C5 D3       CMP   $D3
0D59-   D3          ???
0D5A-   AE 8D AA    LDX   $AA8D
0D5D-   8D AA AA    STA   $AAAA
0D60-   20 C6 CF    JSR   $CFC6
0D63-   D2 20       CMP   ($20)
0D65-   C9 CE       CMP   #$CE
0D67-   D3          ???
0D68-   D4          ???
0D69-   C1 CE       CMP   ($CE,X)
0D6B-   C3          ???
0D6C-   C5 AC       CMP   $AC
0D6E-   20 C9 C6    JSR   $C6C9
0D71-   20 D4 C8    JSR   $C8D4
0D74-   C5 20       CMP   $20
0D76-   D3          ???
0D77-   D4          ???
0D78-   D2 C9       CMP   ($C9)
0D7A-   CE C7 20    DEC   $20C7
0D7D-   C3          ???
0D7E-   CF          ???
0D7F-   CE D4 C1    DEC   $C1D4
0D82-   C9 CE       CMP   #$CE
0D84-   D3          ???
0D85-   BA          TSX
0D86-   8D AA AA    STA   $AAAA
0D89-   20 20 20    JSR   $2020
0D8C-   20 20 20    JSR   $2020
0D8F-   20 D4 C5    JSR   $C5D4
0D92-   D3          ???
0D93-   D4          ???
0D94-   AC C1 A4    LDY   $A4C1
0D97-   B3          ???
0D98-   B0 B0       BCS   $0D4A
0D9A-   AC CC A4    LDY   $A4CC
0D9D-   B1 B0       LDA   ($B0),Y
0D9F-   B0 8D       BCS   $0D2E
0DA1-   AA          TAX
0DA2-   AA          TAX
0DA3-   20 D3 D0    JSR   $D0D3
0DA6-   C3          ???
0DA7-   C9 C6       CMP   #$C6
0DA9-   D9 C9 CE    CMP   $CEC9,Y
0DAC-   C7          ???
0DAD-   20 D4 C8    JSR   $C8D4
0DB0-   C5 20       CMP   $20
0DB2-   CE C1 CD    DEC   $CDC1
0DB5-   C5 20       CMP   $20
0DB7-   CF          ???
0DB8-   C6 20       DEC   $20
0DBA-   D4          ???
0DBB-   C8          INY
0DBC-   C5 20       CMP   $20
0DBE-   C6 C9       DEC   $C9
0DC0-   CC C5 AC    CPY   $ACC5
0DC3-   20 D4 C8    JSR   $C8D4
0DC6-   C5 20       CMP   $20
0DC8-   C1 C4       CMP   ($C4,X)
0DCA-   C4 D2       CPY   $D2
0DCC-   C5 D3       CMP   $D3
0DCE-   D3          ???
0DCF-   8D AA AA    STA   $AAAA
0DD2-   20 CF C6    JSR   $C6CF
0DD5-   C6 20       DEC   $20
0DD7-   D4          ???
0DD8-   C8          INY
0DD9-   C5 20       CMP   $20
0DDB-   CD C5 CD    CMP   $CDC5
0DDE-   CF          ???
0DDF-   D2 D9       CMP   ($D9)
0DE1-   20 D4 CF    JSR   $CFD4
0DE4-   20 D3 D4    JSR   $D4D3
0DE7-   CF          ???
0DE8-   D2 C5       CMP   ($C5)
0DEA-   AC 20 C1    LDY   $C120
0DED-   CE C4 20    DEC   $20C4
0DF0-   D4          ???
0DF1-   C8          INY
0DF2-   C5 20       CMP   $20
0DF4-   CC C5 CE    CPY   $CEC5
0DF7-   C7          ???
0DF8-   D4          ???
0DF9-   C8          INY
0DFA-   8D AA AA    STA   $AAAA
0DFD-   20 D4 CF    JSR   $CFD4
0E00-   20 D3 C1    JSR   $C1D3
0E03-   D6 C5       DEC   $C5,X
0E05-   AC 20 D4    LDY   $D420
0E08-   C8          INY
0E09-   C5 20       CMP   $20
0E0B-   C2          ???
0E0C-   D3          ???
0E0D-   C1 D6       CMP   ($D6,X)
0E0F-   C5 20       CMP   $20
0E11-   D2 CF       CMP   ($CF)
0E13-   D5 D4       CMP   $D4,X
0E15-   C9 CE       CMP   #$CE
0E17-   C5 20       CMP   $20
0E19-   D7          ???
0E1A-   C9 CC       CMP   #$CC
0E1C-   CC 20 C5    CPY   $C520
0E1F-   D8          CLD
0E20-   C5 C3       CMP   $C3
0E22-   D5 D4       CMP   $D4,X
0E24-   C5 8D       CMP   $8D
0E26-   AA          TAX
0E27-   AA          TAX
0E28-   20 D4 C8    JSR   $C8D4
0E2B-   C5 20       CMP   $20
0E2D-   C3          ???
0E2E-   CF          ???
0E2F-   CD CD C1    CMP   $C1CD
0E32-   CE C4 BA    DEC   $BAC4
0E35-   20 C2 D3    JSR   $D3C2
0E38-   C1 D6       CMP   ($D6,X)
0E3A-   C5 20       CMP   $20
0E3C-   D4          ???
0E3D-   C5 D3       CMP   $D3
0E3F-   D4          ???
0E40-   AC C1 A4    LDY   $A4C1
0E43-   B3          ???
0E44-   B0 B0       BCS   $0DF6
0E46-   AC CC A4    LDY   $A4CC
0E49-   B1 B0       LDA   ($B0),Y
0E4B-   B0 8D       BCS   $0DDA
0E4D-   AA          TAX
0E4E-   8D AA AA    STA   $AAAA
0E51-   20 CD C1    JSR   $C1CD
0E54-   C3          ???
0E55-   D2 CF       CMP   ($CF)
0E57-   BA          TSX
0E58-   20 DF C2    JSR   $C2DF
0E5B-   D3          ???
0E5C-   C1 D6       CMP   ($D6,X)
0E5E-   20 D4 C5    JSR   $C5D4
0E61-   D3          ???
0E62-   D4          ???
0E63-   D3          ???
0E64-   D4          ???
0E65-   D2 8D       CMP   ($8D)
0E67-   AA          TAX
0E68-   8D A0 CC    STA   $CCA0
0E6B-   C4 C1       CPY   $C1
0E6D-   A0 A3       LDY   #$A3
0E6F-   BE D4 C5    LDX   $C5D4,Y
0E72-   D3          ???
0E73-   D4          ???
0E74-   D3          ???
0E75-   D4          ???
0E76-   D2 8D       CMP   ($8D)
0E78-   A0 D0       LDY   #$D0
0E7A-   C8          INY
0E7B-   C1 8D       CMP   ($8D,X)
0E7D-   A0 CC       LDY   #$CC
0E7F-   C4 C1       CPY   $C1
0E81-   A0 A3       LDY   #$A3
0E83-   BC D4 C5    LDY   $C5D4,X
0E86-   D3          ???
0E87-   D4          ???
0E88-   D3          ???
0E89-   D4          ???
0E8A-   D2 8D       CMP   ($8D)
0E8C-   A0 D0       LDY   #$D0
0E8E-   C8          INY
0E8F-   C1 8D       CMP   ($8D,X)
0E91-   A0 CA       LDY   #$CA
0E93-   D3          ???
0E94-   D2 A0       CMP   ($A0)
0E96-   C2          ???
0E97-   D3          ???
0E98-   C1 D6       CMP   ($D6,X)
0E9A-   C5 8D       CMP   $8D
0E9C-   AA          TAX
0E9D-   8D AA AA    STA   $AAAA
0EA0-   20 CE CF    JSR   $CFCE
0EA3-   D7          ???
0EA4-   20 C3 CC    JSR   $CCC3
0EA7-   C5 C1       CMP   $C1
0EA9-   D2 20       CMP   ($20)
0EAB-   D4          ???
0EAC-   C8          INY
0EAD-   C5 20       CMP   $20
0EAF-   B1 AC       LDA   ($AC),Y
0EB1-   B2 AC       LDA   ($AC)
0EB3-   B3          ???
0EB4-   20 D3 D4    JSR   $D4D3
0EB7-   CF          ???
0EB8-   D2 C5       CMP   ($C5)
0EBA-   C4 20       CPY   $20
0EBC-   C9 CE       CMP   #$CE
0EBE-   20 A4 B3    JSR   $B3A4
0EC1-   B0 B0       BCS   $0E73
0EC3-   20 D4 CF    JSR   $CFD4
0EC6-   8D AA AA    STA   $AAAA
0EC9-   20 D3 C8    JSR   $C8D3
0ECC-   CF          ???
0ECD-   D7          ???
0ECE-   20 D4 C8    JSR   $C8D4
0ED1-   C1 D4       CMP   ($D4,X)
0ED3-   20 C9 D4    JSR   $D4C9
0ED6-   20 D7 C1    JSR   $C1D7
0ED9-   D3          ???
0EDA-   20 CC CF    JSR   $CFCC
0EDD-   C1 C4       CMP   ($C4,X)
0EDF-   C5 C4       CMP   $C4
0EE1-   20 C1 C7    JSR   $C7C1
0EE4-   C1 C9       CMP   ($C9,X)
0EE6-   CE 8D AA    DEC   $AA8D
0EE9-   8D A0 CC    STA   $CCA0
0EEC-   C4 C1       CPY   $C1
0EEE-   A0 A3       LDY   #$A3
0EF0-   B0 8D       BCS   $0E7F
0EF2-   A0 D3       LDY   #$D3
0EF4-   D4          ???
0EF5-   C1 A0       CMP   ($A0,X)
0EF7-   A4 B3       LDY   $B3
0EF9-   B0 B0       BCS   $0EAB
0EFB-   8D A0 D3    STA   $D3A0
0EFE-   D4          ???
0EFF-   C1 A0       CMP   ($A0,X)
0F01-   A4 B3       LDY   $B3
0F03-   B0 B1       BCS   $0EB6
0F05-   8D A0 D3    STA   $D3A0
0F08-   D4          ???
0F09-   C1 A0       CMP   ($A0,X)
0F0B-   A4 B3       LDY   $B3
0F0D-   B0 B2       BCS   $0EC1
0F0F-   8D A0 D3    STA   $D3A0
0F12-   D4          ???
0F13-   C1 A0       CMP   ($A0,X)
0F15-   A4 B3       LDY   $B3
0F17-   B0 B3       BCS   $0ECC
0F19-   8D AA 8D    STA   $8DAA
0F1C-   AA          TAX
0F1D-   AA          TAX
0F1E-   20 C2 CC    JSR   $CCC2
0F21-   CF          ???
0F22-   C1 C4       CMP   ($C4,X)
0F24-   20 D3 C9    JSR   $C9D3
0F27-   CD D0 CC    CMP   $CCD0
0F2A-   D9 20 C2    CMP   $C220,Y
0F2D-   CC CF C1    CPY   $C1CF
0F30-   C4 D3       CPY   $D3
0F32-   20 D0 D2    JSR   $D2D0
0F35-   C5 D6       CMP   $D6
0F37-   C9 CF       CMP   #$CF
0F39-   D5 D3       CMP   $D3,X
0F3B-   CC D9 20    CPY   $20D9
0F3E-   C2          ???
0F3F-   D3          ???
0F40-   C1 D6       CMP   ($D6,X)
0F42-   C5 C4       CMP   $C4
0F44-   20 C4 C1    JSR   $C1C4
0F47-   D4          ???
0F48-   C1 8D       CMP   ($8D,X)
0F4A-   AA          TAX
0F4B-   AA          TAX
0F4C-   20 C9 CE    JSR   $CEC9
0F4F-   D4          ???
0F50-   CF          ???
0F51-   20 D4 C8    JSR   $C8D4
0F54-   C5 20       CMP   $20
0F56-   D3          ???
0F57-   D0 C5       BNE   $0F1E
0F59-   C3          ???
0F5A-   C9 C6       CMP   #$C6
0F5C-   C9 C5       CMP   #$C5
0F5E-   C4 20       CPY   $20
0F60-   C1 C4       CMP   ($C4,X)
0F62-   C4 D2       CPY   $D2
0F64-   C5 D3       CMP   $D3
0F66-   D3          ???
0F67-   20 C9 CE    JSR   $CEC9
0F6A-   20 D4 C8    JSR   $C8D4
0F6D-   C5 20       CMP   $20
0F6F-   D3          ???
0F70-   D4          ???
0F71-   D2 C9       CMP   ($C9)
0F73-   CE C7 8D    DEC   $8DC7
0F76-   AA          TAX
0F77-   8D AA AA    STA   $AAAA
0F7A-   20 CD C1    JSR   $C1CD
0F7D-   C3          ???
0F7E-   D2 CF       CMP   ($CF)
0F80-   BA          TSX
0F81-   20 DF C2    JSR   $C2DF
0F84-   CC CF C4    CPY   $C4CF
0F87-   20 D4 C5    JSR   $C5D4
0F8A-   D3          ???
0F8B-   D4          ???
0F8C-   CC C4 8D    CPY   $8DC4
0F8F-   AA          TAX
0F90-   8D A0 CC    STA   $CCA0
0F93-   C4 C1       CPY   $C1
0F95-   A0 A3       LDY   #$A3
0F97-   BE D4 C5    LDX   $C5D4,Y
0F9A-   D3          ???
0F9B-   D4          ???
0F9C-   CC C4 8D    CPY   $8DC4
0F9F-   A0 D0       LDY   #$D0
0FA1-   C8          INY
0FA2-   C1 8D       CMP   ($8D,X)
0FA4-   A0 CC       LDY   #$CC
0FA6-   C4 C1       CPY   $C1
0FA8-   A0 A3       LDY   #$A3
0FAA-   BC D4 C5    LDY   $C5D4,X
0FAD-   D3          ???
0FAE-   D4          ???
0FAF-   CC C4 8D    CPY   $8DC4
0FB2-   A0 D0       LDY   #$D0
0FB4-   C8          INY
0FB5-   C1 8D       CMP   ($8D,X)
0FB7-   A0 CA       LDY   #$CA
0FB9-   D3          ???
0FBA-   D2 A0       CMP   ($A0)
0FBC-   C2          ???
0FBD-   CC CF C1    CPY   $C1CF
0FC0-   C4 8D       CPY   $8D
0FC2-   AA          TAX
0FC3-   8D AA 8D    STA   $8DAA
0FC6-   AA          TAX
0FC7-   AA          TAX
0FC8-   20 C3 CD    JSR   $CDC3
0FCB-   C4 20       CPY   $20
0FCD-   D3          ???
0FCE-   C9 CD       CMP   #$CD
0FD0-   D0 CC       BNE   $0F9E
0FD2-   D9 20 D2    CMP   $D220,Y
0FD5-   D5 CE       CMP   $CE,X
0FD7-   D3          ???
0FD8-   20 C1 20    JSR   $20C1
0FDB-   C4 CF       CPY   $CF
0FDD-   D3          ???
0FDE-   20 C3 CF    JSR   $CFC3
0FE1-   CD CD C1    CMP   $C1CD
0FE4-   CE C4 AE    DEC   $AEC4
0FE7-   20 D4 C8    JSR   $C8D4
0FEA-   C9 D3       CMP   #$D3
0FEC-   20 C3 C1    JSR   $C1C3
0FEF-   CE 20 C2    DEC   $C220
0FF2-   C5 20       CMP   $20
0FF4-   D5 D3       CMP   $D3,X
0FF6-   C5 C4       CMP   $C4
0FF8-   8D AA AA    STA   $AAAA
0FFB-   20 D4 CF    JSR   $CFD4
0FFE-   20 D2 C5    JSR   $C5D2
1001-   C1 C4       CMP   ($C4,X)
1003-   20 C1 CE    JSR   $CEC1
1006-   C4 20       CPY   $20
1008-   D7          ???
1009-   D2 C9       CMP   ($C9)
100B-   D4          ???
100C-   C5 20       CMP   $20
100E-   D4          ???
100F-   C5 D8       CMP   $D8
1011-   D4          ???
1012-   20 C6 C9    JSR   $C9C6
1015-   CC C5 D3    CPY   $D3C5
1018-   AC 20 C2    LDY   $C220
101B-   D5 D4       CMP   $D4,X
101D-   20 D4 C8    JSR   $C8D4
1020-   C1 D4       CMP   ($D4,X)
1022-   20 D2 C5    JSR   $C5D2
1025-   D1 D5       CMP   ($D5),Y
1027-   C9 D2       CMP   #$D2
1029-   C5 D3       CMP   $D3
102B-   8D AA AA    STA   $AAAA
102E-   20 C1 CE    JSR   $CEC1
1031-   20 C5 D8    JSR   $D8C5
1034-   D4          ???
1035-   D2 C1       CMP   ($C1)
1037-   20 D3 D4    JSR   $D4D3
103A-   C5 D0       CMP   $D0
103C-   20 A8 D3    JSR   $D3A8
103F-   C5 C5       CMP   $C5
1041-   20 C2 C5    JSR   $C5C2
1044-   CC CF D7    CPY   $D7CF
1047-   A9 AE       LDA   #$AE
1049-   20 CF D4    JSR   $D4CF
104C-   C8          INY
104D-   C5 D2       CMP   $D2
104F-   D7          ???
1050-   C9 D3       CMP   #$D3
1052-   C5 AC       CMP   $AC
1054-   20 C9 D4    JSR   $D4C9
1057-   A7          ???
1058-   D3          ???
1059-   20 CA D5    JSR   $D5CA
105C-   D3          ???
105D-   D4          ???
105E-   8D AA AA    STA   $AAAA
1061-   20 C1 20    JSR   $20C1
1064-   CD C1 D4    CMP   $D4C1
1067-   D4          ???
1068-   C5 D2       CMP   $D2
106A-   20 CF C6    JSR   $C6CF
106D-   20 C3 C1    JSR   $C1C3
1070-   CC CC C9    CPY   $C9CC
1073-   CE C7 20    DEC   $20C7
1076-   D4          ???
1077-   C8          INY
1078-   C5 20       CMP   $20
107A-   D3          ???
107B-   D5 C2       CMP   $C2,X
107D-   D2 CF       CMP   ($CF)
107F-   D5 D4       CMP   $D4,X
1081-   C9 CE       CMP   #$CE
1083-   C5 AC       CMP   $AC
1085-   20 D4 C8    JSR   $C8D4
1088-   C5 CE       CMP   $CE
108A-   20 C8 C1    JSR   $C1C8
108D-   D6 C9       DEC   $C9,X
108F-   CE C7 8D    DEC   $8DC7
1092-   AA          TAX
1093-   AA          TAX
1094-   20 C1 CE    JSR   $CEC1
1097-   20 C1 D3    JSR   $D3C1
109A-   C3          ???
109B-   20 D4 C8    JSR   $C8D4
109E-   C1 D4       CMP   ($D4,X)
10A0-   20 C6 CF    JSR   $CFC6
10A3-   CC CC CF    CPY   $CFCC
10A6-   D7          ???
10A7-   D3          ???
10A8-   20 D7 C9    JSR   $C9D7
10AB-   D4          ???
10AC-   C8          INY
10AD-   20 D4 C8    JSR   $C8D4
10B0-   C5 20       CMP   $20
10B2-   C4 CF       CPY   $CF
10B4-   D3          ???
10B5-   20 C3 CF    JSR   $CFC3
10B8-   CD CD C1    CMP   $C1CD
10BB-   CE C4 AE    DEC   $AEC4
10BE-   8D AA 8D    STA   $8DAA
10C1-   AA          TAX
10C2-   AA          TAX
10C3-   20 CD C1    JSR   $C1CD
10C6-   C3          ???
10C7-   D2 CF       CMP   ($CF)
10C9-   BA          TSX
10CA-   20 DF C3    JSR   $C3DF
10CD-   CD C4 20    CMP   $20C4
10D0-   A2 C3       LDX   #$C3
10D2-   C1 D4       CMP   ($D4,X)
10D4-   C1 CC       CMP   ($CC,X)
10D6-   CF          ???
10D7-   C7          ???
10D8-   A2 8D       LDX   #$8D
10DA-   AA          TAX
10DB-   8D A0 CA    STA   $CAA0
10DE-   D3          ???
10DF-   D2 A0       CMP   ($A0)
10E1-   C3          ???
10E2-   CD C4 8D    CMP   $8DC4
10E5-   A0 C1       LDY   #$C1
10E7-   D3          ???
10E8-   C3          ???
10E9-   A0 A2       LDY   #$A2
10EB-   C3          ???
10EC-   C1 D4       CMP   ($D4,X)
10EE-   C1 CC       CMP   ($CC,X)
10F0-   CF          ???
10F1-   C7          ???
10F2-   A2 8D       LDX   #$8D
10F4-   A0 C8       LDY   #$C8
10F6-   C5 D8       CMP   $D8
10F8-   A0 B8       LDY   #$B8
10FA-   C4 B0       CPY   $B0
10FC-   B0 8D       BCS   $108B
10FE-   AA          TAX
10FF-   8D AA 8D    STA   $8DAA
1102-   AA          TAX
1103-   AA          TAX
1104-   20 D4 CF    JSR   $CFD4
1107-   20 C1 C3    JSR   $C3C1
110A-   C3          ???
110B-   C5 D3       CMP   $D3
110D-   D3          ???
110E-   20 D4 C5    JSR   $C5D4
1111-   D8          CLD
1112-   D4          ???
1113-   20 C6 C9    JSR   $C9C6
1116-   CC C5 D3    CPY   $D3C5
1119-   AC 20 D7    LDY   $D720
111C-   C5 20       CMP   $20
111E-   C8          INY
111F-   C1 D6       CMP   ($D6,X)
1121-   C5 20       CMP   $20
1123-   D4          ???
1124-   CF          ???
1125-   20 C7 CF    JSR   $CFC7
1128-   20 C9 CE    JSR   $CEC9
112B-   D4          ???
112C-   CF          ???
112D-   8D AA AA    STA   $AAAA
1130-   20 C9 CE    JSR   $CEC9
1133-   C4 C9       CPY   $C9
1135-   D2 C5       CMP   ($C5)
1137-   C3          ???
1138-   D4          ???
1139-   20 CD CF    JSR   $CFCD
113C-   C4 C5       CPY   $C5
113E-   20 D4 CF    JSR   $CFD4
1141-   20 C6 CF    JSR   $CFC6
1144-   CF          ???
1145-   CC 20 C4    CPY   $C420
1148-   CF          ???
1149-   D3          ???
114A-   20 C9 CE    JSR   $CEC9
114D-   D4          ???
114E-   CF          ???
114F-   20 D4 C8    JSR   $C8D4
1152-   C9 CE       CMP   #$CE
1154-   CB          ???
1155-   C9 CE       CMP   #$CE
1157-   C7          ???
1158-   20 C1 8D    JSR   $8DC1
115B-   AA          TAX
115C-   AA          TAX
115D-   20 D0 D2    JSR   $D2D0
1160-   CF          ???
1161-   C7          ???
1162-   D2 C1       CMP   ($C1)
1164-   CD 20 C9    CMP   $C920
1167-   D3          ???
1168-   20 D2 D5    JSR   $D5D2
116B-   CE CE C9    DEC   $C9CE
116E-   CE C7 AE    DEC   $AEC7
1171-   20 D4 C8    JSR   $C8D4
1174-   C5 20       CMP   $20
1176-   C3          ???
1177-   C1 D6       CMP   ($D6,X)
1179-   C5 C1       CMP   $C1
117B-   D4          ???
117C-   20 C9 D3    JSR   $D3C9
117F-   20 D4 C8    JSR   $C8D4
1182-   C1 D4       CMP   ($D4,X)
1184-   20 D7 C5    JSR   $C5D7
1187-   8D AA AA    STA   $AAAA
118A-   20 CD D5    JSR   $D5CD
118D-   D3          ???
118E-   D4          ???
118F-   20 CA D5    JSR   $D5CA
1192-   CD D0 20    CMP   $20D0
1195-   D4          ???
1196-   CF          ???
1197-   20 B3 C4    JSR   $C4B3
119A-   B0 20       BCS   $11BC
119C-   A8          TAY
119D-   D2 C5       CMP   ($C5)
119F-   C5 CE       CMP   $CE
11A1-   D4          ???
11A2-   D2 D9       CMP   ($D9)
11A4-   A9 20       LDA   #$20
11A6-   D4          ???
11A7-   CF          ???
11A8-   20 D4 C5    JSR   $C5D4
11AB-   D2 CD       CMP   ($CD)
11AD-   C9 CE       CMP   #$CE
11AF-   D4          ???
11B0-   C5 20       CMP   $20
11B2-   D4          ???
11B3-   C8          INY
11B4-   C5 8D       CMP   $8D
11B6-   AA          TAX
11B7-   AA          TAX
11B8-   20 D0 D2    JSR   $D2D0
11BB-   CF          ???
11BC-   C7          ???
11BD-   D2 C1       CMP   ($C1)
11BF-   CD 20 C9    CMP   $C920
11C2-   CE D3 D4    DEC   $D4D3
11C5-   C5 C1       CMP   $C1
11C7-   C4 20       CPY   $20
11C9-   CF          ???
11CA-   C6 20       DEC   $20
11CC-   D5 D3       CMP   $D3,X
11CE-   C9 CE       CMP   #$CE
11D0-   C7          ???
11D1-   20 D2 D4    JSR   $D4D2
11D4-   D3          ???
11D5-   AE 20 D4    LDX   $D420
11D8-   C8          INY
11D9-   C9 D3       CMP   #$D3
11DB-   20 C9 D3    JSR   $D3C9
11DE-   20 D4 C8    JSR   $C8D4
11E1-   C5 8D       CMP   $8D
11E3-   AA          TAX
11E4-   AA          TAX
11E5-   20 D3 C1    JSR   $C1D3
11E8-   CD C5 20    CMP   $20C5
11EB-   C9 D3       CMP   #$D3
11ED-   D3          ???
11EE-   D5 C5       CMP   $C5,X
11F0-   20 D7 C8    JSR   $C8D7
11F3-   C5 CE       CMP   $CE
11F5-   20 D5 D3    JSR   $D3D5
11F8-   C9 CE       CMP   #$CE
11FA-   C7          ???
11FB-   20 C3 CF    JSR   $CFC3
11FE-   D5 D4       CMP   $D4,X
1200-   AC 20 C8    LDY   $C820
1203-   CF          ???
1204-   D7          ???
1205-   C5 D6       CMP   $D6
1207-   C5 D2       CMP   $D2
1209-   AC 20 D3    LDY   $D320
120C-   CF          ???
120D-   20 C9 D4    JSR   $D4C9
1210-   8D AA AA    STA   $AAAA
1213-   20 C9 D3    JSR   $D3C9
1216-   20 D0 D2    JSR   $D2D0
1219-   C5 D4       CMP   $D4
121B-   D4          ???
121C-   D9 20 D3    CMP   $D320,Y
121F-   D4          ???
1220-   C1 CE       CMP   ($CE,X)
1222-   C4 C1       CPY   $C1
1224-   D2 C4       CMP   ($C4)
1226-   AE 8D AA    LDX   $AA8D
1229-   8D AA AA    STA   $AAAA
122C-   20 CD C1    JSR   $C1CD
122F-   C3          ???
1230-   D2 CF       CMP   ($CF)
1232-   BA          TSX
1233-   20 DF D4    JSR   $D4DF
1236-   CD CF C4    CMP   $C4CF
1239-   8D AA 8D    STA   $8DAA
123C-   A0 CA       LDY   #$CA
123E-   D3          ???
123F-   D2 A0       CMP   ($A0)
1241-   D4          ???
1242-   CD CF C4    CMP   $C4CF
1245-   C5 A0       CMP   $A0
1247-   BB          ???
1248-   20 C5 CE    JSR   $CEC5
124B-   D4          ???
124C-   C5 D2       CMP   $D2
124E-   20 D4 C5    JSR   $C5D4
1251-   D8          CLD
1252-   D4          ???
1253-   20 CF D0    JSR   $D0CF
1256-   C5 D2       CMP   $D2
1258-   C1 D4       CMP   ($D4,X)
125A-   C9 CF       CMP   #$CF
125C-   CE 20 CD    DEC   $CD20
125F-   CF          ???
1260-   C4 C5       CPY   $C5
1262-   8D AA 8D    STA   $8DAA
1265-   AA          TAX
1266-   8D AA AA    STA   $AAAA
1269-   20 CE CF    JSR   $CFCE
126C-   D7          ???
126D-   20 CC C5    JSR   $C5CC
1270-   D4          ???
1271-   A7          ???
1272-   D3          ???
1273-   20 D7 D2    JSR   $D2D7
1276-   C9 D4       CMP   #$D4
1278-   C5 20       CMP   $20
127A-   C1 20       CMP   ($20,X)
127C-   D4          ???
127D-   C5 D8       CMP   $D8
127F-   D4          ???
1280-   20 C6 C9    JSR   $C9C6
1283-   CC C5 20    CPY   $20C5
1286-   D5 D3       CMP   $D3,X
1288-   C9 CE       CMP   #$CE
128A-   C7          ???
128B-   20 C1 20    JSR   $20C1
128E-   CD C9 D8    CMP   $D8C9
1291-   8D AA AA    STA   $AAAA
1294-   20 CF C6    JSR   $C6CF
1297-   20 C3 CD    JSR   $CDC3
129A-   C4 20       CPY   $20
129C-   C1 CE       CMP   ($CE,X)
129E-   C4 20       CPY   $20
12A0-   D4          ???
12A1-   C8          INY
12A2-   C5 20       CMP   $20
12A4-   C6 D0       DEC   $D0
12A6-   D2 C9       CMP   ($C9)
12A8-   CE D4 20    DEC   $20D4
12AB-   C3          ???
12AC-   CF          ???
12AD-   CD CD C1    CMP   $C1CD
12B0-   CE C4 8D    DEC   $8DC4
12B3-   AA          TAX
12B4-   8D AA AA    STA   $AAAA
12B7-   20 CD C1    JSR   $C1CD
12BA-   C3          ???
12BB-   D2 CF       CMP   ($CF)
12BD-   BA          TSX
12BE-   20 DF C6    JSR   $C6DF
12C1-   D0 D2       BNE   $1295
12C3-   CE 20 A2    DEC   $A220
12C6-   D4          ???
12C7-   C8          INY
12C8-   C9 D3       CMP   #$D3
12CA-   20 C9 D3    JSR   $D3C9
12CD-   20 C1 20    JSR   $20C1
12D0-   D4          ???
12D1-   C5 D3       CMP   $D3
12D3-   D4          ???
12D4-   AE A2 8D    LDX   $8DA2
12D7-   AA          TAX
12D8-   8D A0 CA    STA   $CAA0
12DB-   D3          ???
12DC-   D2 A0       CMP   ($A0)
12DE-   C3          ???
12DF-   CD C4 8D    CMP   $8DC4
12E2-   A0 C1       LDY   #$C1
12E4-   D3          ???
12E5-   C3          ???
12E6-   A0 A2       LDY   #$A2
12E8-   CF          ???
12E9-   D0 C5       BNE   $12B0
12EB-   CE 20 D4    DEC   $D420
12EE-   C5 D8       CMP   $D8
12F0-   D4          ???
12F1-   B1 A2       LDA   ($A2),Y
12F3-   8D A0 C8    STA   $C8A0
12F6-   C5 D8       CMP   $D8
12F8-   A0 B8       LDY   #$B8
12FA-   C4 B0       CPY   $B0
12FC-   B0 8D       BCS   $128B
12FE-   A0 CA       LDY   #$CA
1300-   D3          ???
1301-   D2 A0       CMP   ($A0)
1303-   C3          ???
1304-   CD C4 8D    CMP   $8DC4
1307-   A0 C1       LDY   #$C1
1309-   D3          ???
130A-   C3          ???
130B-   A0 A2       LDY   #$A2
130D-   D7          ???
130E-   D2 C9       CMP   ($C9)
1310-   D4          ???
1311-   C5 20       CMP   $20
1313-   D4          ???
1314-   C5 D8       CMP   $D8
1316-   D4          ???
1317-   B1 A2       LDA   ($A2),Y
1319-   8D A0 C8    STA   $C8A0
131C-   C5 D8       CMP   $D8
131E-   A0 B8       LDY   #$B8
1320-   C4 B0       CPY   $B0
1322-   B0 8D       BCS   $12B1
1324-   A0 CA       LDY   #$CA
1326-   D3          ???
1327-   D2 A0       CMP   ($A0)
1329-   C6 D0       DEC   $D0
132B-   D2 C9       CMP   ($C9)
132D-   CE D4 8D    DEC   $8DD4
1330-   A0 C1       LDY   #$C1
1332-   D3          ???
1333-   C3          ???
1334-   A0 A2       LDY   #$A2
1336-   D4          ???
1337-   C8          INY
1338-   C9 D3       CMP   #$D3
133A-   20 C9 D3    JSR   $D3C9
133D-   20 C1 20    JSR   $20C1
1340-   D4          ???
1341-   C5 D3       CMP   $D3
1343-   D4          ???
1344-   AE A2 8D    LDX   $8DA2
1347-   A0 C8       LDY   #$C8
1349-   C5 D8       CMP   $D8
134B-   A0 B8       LDY   #$B8
134D-   C4 B0       CPY   $B0
134F-   B0 8D       BCS   $12DE
1351-   A0 CA       LDY   #$CA
1353-   D3          ???
1354-   D2 A0       CMP   ($A0)
1356-   C3          ???
1357-   CD C4 8D    CMP   $8DC4
135A-   A0 C1       LDY   #$C1
135C-   D3          ???
135D-   C3          ???
135E-   A0 A2       LDY   #$A2
1360-   C3          ???
1361-   CC CF D3    CPY   $D3CF
1364-   C5 20       CMP   $20
1366-   D4          ???
1367-   C5 D8       CMP   $D8
1369-   D4          ???
136A-   B1 A2       LDA   ($A2),Y
136C-   8D A0 C8    STA   $C8A0
136F-   C5 D8       CMP   $D8
1371-   A0 B8       LDY   #$B8
1373-   C4 B0       CPY   $B0
1375-   B0 8D       BCS   $1304
1377-   AA          TAX
1378-   8D AA 8D    STA   $8DAA
137B-   AA          TAX
137C-   AA          TAX
137D-   20 CE CF    JSR   $CFCE
1380-   D7          ???
1381-   20 CC C5    JSR   $C5CC
1384-   D4          ???
1385-   A7          ???
1386-   D3          ???
1387-   20 D2 C5    JSR   $C5D2
138A-   C1 C4       CMP   ($C4,X)
138C-   20 D4 C8    JSR   $C8D4
138F-   C1 D4       CMP   ($D4,X)
1391-   20 C6 C9    JSR   $C9C6
1394-   CC C5 20    CPY   $20C5
1397-   D7          ???
1398-   C9 D4       CMP   #$D4
139A-   C8          INY
139B-   20 C6 C9    JSR   $C9C6
139E-   CE D0 D5    DEC   $D5D0
13A1-   D4          ???
13A2-   AC 20 D7    LDY   $D720
13A5-   C8          INY
13A6-   C9 C3       CMP   #$C3
13A8-   C8          INY
13A9-   8D AA AA    STA   $AAAA
13AC-   20 D3 C9    JSR   $C9D3
13AF-   CD D0 CC    CMP   $CCD0
13B2-   D9 20 D5    CMP   $D520,Y
13B5-   D3          ???
13B6-   C5 D3       CMP   $D3
13B8-   20 D4 C8    JSR   $C8D4
13BB-   C5 20       CMP   $20
13BD-   CD CF CE    CMP   $CECF
13C0-   C9 D4       CMP   #$D4
13C2-   CF          ???
13C3-   D2 20       CMP   ($20)
13C5-   C9 CE       CMP   #$CE
13C7-   D0 D5       BNE   $139E
13C9-   D4          ???
13CA-   20 D2 CF    JSR   $CFD2
13CD-   D5 D4       CMP   $D4,X
13CF-   C9 CE       CMP   #$CE
13D1-   C5 20       CMP   $20
13D3-   C1 CE       CMP   ($CE,X)
13D5-   C4 20       CPY   $20
13D7-   D4          ???
13D8-   C8          INY
13D9-   C5 CE       CMP   $CE
13DB-   8D AA AA    STA   $AAAA
13DE-   20 C3 CF    JSR   $CFC3
13E1-   D0 C9       BNE   $13AC
13E3-   C5 D3       CMP   $D3
13E5-   20 D4 C8    JSR   $C8D4
13E8-   C5 20       CMP   $20
13EA-   C2          ???
13EB-   D5 C6       CMP   $C6,X
13ED-   C6 C5       DEC   $C5
13EF-   D2 20       CMP   ($20)
13F1-   D4          ???
13F2-   CF          ???
13F3-   20 D4 C8    JSR   $C8D4
13F6-   C5 20       CMP   $20
13F8-   D3          ???
13F9-   D0 C5       BNE   $13C0
13FB-   C3          ???
13FC-   C9 C6       CMP   #$C6
13FE-   C9 C5       CMP   #$C5
1400-   C4 20       CPY   $20
1402-   CC CF C3    CPY   $C3CF
1405-   C1 D4       CMP   ($D4,X)
1407-   C9 CF       CMP   #$CF
1409-   CE AE 8D    DEC   $8DAE
140C-   AA          TAX
140D-   AA          TAX
140E-   20 D9 CF    JSR   $CFD9
1411-   D5 20       CMP   $20,X
1413-   C3          ???
1414-   C1 CE       CMP   ($CE,X)
1416-   20 C1 CC    JSR   $CCC1
1419-   D3          ???
141A-   CF          ???
141B-   20 D5 D3    JSR   $D3D5
141E-   C5 20       CMP   $20
1420-   C6 C7       DEC   $C7
1422-   C5 D4       CMP   $D4
1424-   AC 20 D7    LDY   $D720
1427-   C8          INY
1428-   C9 C3       CMP   #$C3
142A-   C8          INY
142B-   20 D3 D4    JSR   $D4D3
142E-   CF          ???
142F-   D2 C5       CMP   ($C5)
1431-   D3          ???
1432-   20 C1 20    JSR   $20C1
1435-   D3          ???
1436-   C9 CE       CMP   #$CE
1438-   C7          ???
1439-   CC C5 8D    CPY   $8DC5
143C-   AA          TAX
143D-   AA          TAX
143E-   20 C3 C8    JSR   $C8C3
1441-   C1 D2       CMP   ($D2,X)
1443-   C1 C3       CMP   ($C3,X)
1445-   D4          ???
1446-   C5 D2       CMP   $D2
1448-   20 C6 D2    JSR   $D2C6
144B-   CF          ???
144C-   CD 20 D4    CMP   $D420
144F-   C8          INY
1450-   C5 20       CMP   $20
1452-   C6 C9       DEC   $C9
1454-   CC C5 20    CPY   $20C5
1457-   C9 CE       CMP   #$CE
1459-   D4          ???
145A-   CF          ???
145B-   20 D4 C8    JSR   $C8D4
145E-   C5 20       CMP   $20
1460-   C1 C3       CMP   ($C3,X)
1462-   C3          ???
1463-   D5 CD       CMP   $CD,X
1465-   D5 CC       CMP   $CC,X
1467-   C1 D4       CMP   ($D4,X)
1469-   CF          ???
146A-   D2 AE       CMP   ($AE)
146C-   8D AA 8D    STA   $8DAA
146F-   AA          TAX
1470-   AA          TAX
1471-   20 CD C1    JSR   $C1CD
1474-   C3          ???
1475-   D2 CF       CMP   ($CF)
1477-   BA          TSX
1478-   20 DF C6    JSR   $C6DF
147B-   C9 CE       CMP   #$CE
147D-   D0 20       BNE   $149F
147F-   A4 B3       LDY   $B3
1481-   B0 B0       BCS   $1433
1483-   8D AA 8D    STA   $8DAA
1486-   A0 CA       LDY   #$CA
1488-   D3          ???
1489-   D2 A0       CMP   ($A0)
148B-   C3          ???
148C-   CD C4 8D    CMP   $8DC4
148F-   A0 C1       LDY   #$C1
1491-   D3          ???
1492-   C3          ???
1493-   A0 A2       LDY   #$A2
1495-   CF          ???
1496-   D0 C5       BNE   $145D
1498-   CE 20 D4    DEC   $D420
149B-   C5 D8       CMP   $D8
149D-   D4          ???
149E-   B1 A2       LDA   ($A2),Y
14A0-   8D A0 C8    STA   $C8A0
14A3-   C5 D8       CMP   $D8
14A5-   A0 B8       LDY   #$B8
14A7-   C4 B0       CPY   $B0
14A9-   B0 8D       BCS   $1438
14AB-   A0 CA       LDY   #$CA
14AD-   D3          ???
14AE-   D2 A0       CMP   ($A0)
14B0-   C3          ???
14B1-   CD C4 8D    CMP   $8DC4
14B4-   A0 C1       LDY   #$C1
14B6-   D3          ???
14B7-   C3          ???
14B8-   A0 A2       LDY   #$A2
14BA-   D2 C5       CMP   ($C5)
14BC-   C1 C4       CMP   ($C4,X)
14BE-   20 D4 C5    JSR   $C5D4
14C1-   D8          CLD
14C2-   D4          ???
14C3-   B1 A2       LDA   ($A2),Y
14C5-   8D A0 C8    STA   $C8A0
14C8-   C5 D8       CMP   $D8
14CA-   A0 B8       LDY   #$B8
14CC-   C4 B0       CPY   $B0
14CE-   B0 8D       BCS   $145D
14D0-   A0 CC       LDY   #$CC
14D2-   C4 C1       CPY   $C1
14D4-   A0 A3       LDY   #$A3
14D6-   BE A4 B3    LDX   $B3A4,Y
14D9-   B0 B0       BCS   $148B
14DB-   A0 BB       LDY   #$BB
14DD-   20 D0 D5    JSR   $D5D0
14E0-   D4          ???
14E1-   20 D2 C5    JSR   $C5D2
14E4-   C1 C4       CMP   ($C4,X)
14E6-   20 D3 D4    JSR   $D4D3
14E9-   D2 C9       CMP   ($C9)
14EB-   CE C7 20    DEC   $20C7
14EE-   C8          INY
14EF-   C5 D2       CMP   $D2
14F1-   C5 8D       CMP   $8D
14F3-   A0 D0       LDY   #$D0
14F5-   C8          INY
14F6-   C1 8D       CMP   ($8D,X)
14F8-   A0 CC       LDY   #$CC
14FA-   C4 C1       CPY   $C1
14FC-   A0 A3       LDY   #$A3
14FE-   BC A4 B3    LDY   $B3A4,X
1501-   B0 B0       BCS   $14B3
1503-   8D A0 D0    STA   $D0A0
1506-   C8          INY
1507-   C1 8D       CMP   ($8D,X)
1509-   A0 CA       LDY   #$CA
150B-   D3          ???
150C-   D2 A0       CMP   ($A0)
150E-   C6 C9       DEC   $C9
1510-   CE D0 D5    DEC   $D5D0
1513-   D4          ???
1514-   8D A0 CA    STA   $CAA0
1517-   D3          ???
1518-   D2 A0       CMP   ($A0)
151A-   C3          ???
151B-   CD C4 8D    CMP   $8DC4
151E-   A0 C1       LDY   #$C1
1520-   D3          ???
1521-   C3          ???
1522-   A0 A2       LDY   #$A2
1524-   C3          ???
1525-   CC CF D3    CPY   $D3CF
1528-   C5 20       CMP   $20
152A-   D4          ???
152B-   C5 D8       CMP   $D8
152D-   D4          ???
152E-   B1 A2       LDA   ($A2),Y
1530-   8D A0 C8    STA   $C8A0
1533-   C5 D8       CMP   $D8
1535-   A0 B8       LDY   #$B8
1537-   C4 B0       CPY   $B0
1539-   B0 8D       BCS   $14C8
153B-   AA          TAX
153C-   8D AA 8D    STA   $8DAA
153F-   AA          TAX
1540-   AA          TAX
1541-   20 C6 D0    JSR   $D0C6
1544-   D3          ???
1545-   D4          ???
1546-   D2 20       CMP   ($20)
1548-   D7          ???
1549-   D2 C9       CMP   ($C9)
154B-   D4          ???
154C-   C5 D3       CMP   $D3
154E-   20 C1 20    JSR   $20C1
1551-   D3          ???
1552-   D4          ???
1553-   D2 C9       CMP   ($C9)
1555-   CE C7 20    DEC   $20C7
1558-   D4          ???
1559-   CF          ???
155A-   20 C1 20    JSR   $20C1
155D-   D4          ???
155E-   C5 D8       CMP   $D8
1560-   D4          ???
1561-   20 C6 C9    JSR   $C9C6
1564-   CC C5 8D    CPY   $8DC5
1567-   AA          TAX
1568-   AA          TAX
1569-   20 D4 C8    JSR   $C8D4
156C-   C1 D4       CMP   ($D4,X)
156E-   20 D2 C5    JSR   $C5D2
1571-   D3          ???
1572-   C9 C4       CMP   #$C4
1574-   C5 D3       CMP   $D3
1576-   20 C9 CE    JSR   $CEC9
1579-   20 C1 20    JSR   $20C1
157C-   D3          ???
157D-   D0 C5       BNE   $1544
157F-   C3          ???
1580-   C9 C6       CMP   #$C6
1582-   C9 C3       CMP   #$C3
1584-   20 C1 C4    JSR   $C4C1
1587-   C4 D2       CPY   $D2
1589-   C5 D3       CMP   $D3
158B-   D3          ???
158C-   AE 8D AA    LDX   $AA8D
158F-   8D AA AA    STA   $AAAA
1592-   20 CD C1    JSR   $C1CD
1595-   C3          ???
1596-   D2 CF       CMP   ($CF)
1598-   BA          TSX
1599-   20 DF C6    JSR   $C6DF
159C-   D0 D2       BNE   $1570
159E-   CE 20 D4    DEC   $D420
15A1-   D3          ???
15A2-   D4          ???
15A3-   D2 8D       CMP   ($8D)
15A5-   AA          TAX
15A6-   8D A0 CA    STA   $CAA0
15A9-   D3          ???
15AA-   D2 A0       CMP   ($A0)
15AC-   C3          ???
15AD-   CD C4 8D    CMP   $8DC4
15B0-   A0 C1       LDY   #$C1
15B2-   D3          ???
15B3-   C3          ???
15B4-   A0 A2       LDY   #$A2
15B6-   CF          ???
15B7-   D0 C5       BNE   $157E
15B9-   CE 20 D4    DEC   $D420
15BC-   AE D4 C5    LDX   $C5D4
15BF-   D3          ???
15C0-   D4          ???
15C1-   A2 8D       LDX   #$8D
15C3-   A0 C8       LDY   #$C8
15C5-   C5 D8       CMP   $D8
15C7-   A0 B8       LDY   #$B8
15C9-   C4 B0       CPY   $B0
15CB-   B0 8D       BCS   $155A
15CD-   A0 CA       LDY   #$CA
15CF-   D3          ???
15D0-   D2 A0       CMP   ($A0)
15D2-   C3          ???
15D3-   CD C4 8D    CMP   $8DC4
15D6-   A0 C1       LDY   #$C1
15D8-   D3          ???
15D9-   C3          ???
15DA-   A0 A2       LDY   #$A2
15DC-   D7          ???
15DD-   D2 C9       CMP   ($C9)
15DF-   D4          ???
15E0-   C5 20       CMP   $20
15E2-   D4          ???
15E3-   AE D4 C5    LDX   $C5D4
15E6-   D3          ???
15E7-   D4          ???
15E8-   A2 8D       LDX   #$8D
15EA-   A0 C8       LDY   #$C8
15EC-   C5 D8       CMP   $D8
15EE-   A0 B8       LDY   #$B8
15F0-   C4 B0       CPY   $B0
15F2-   B0 8D       BCS   $1581
15F4-   A0 CC       LDY   #$CC
15F6-   C4 C1       CPY   $C1
15F8-   A0 A3       LDY   #$A3
15FA-   BE D4 D3    LDX   $D3D4,Y
15FD-   D4          ???
15FE-   D2 8D       CMP   ($8D)
1600-   A0 D0       LDY   #$D0
1602-   C8          INY
1603-   C1 8D       CMP   ($8D,X)
1605-   A0 CC       LDY   #$CC
1607-   C4 C1       CPY   $C1
1609-   A0 A3       LDY   #$A3
160B-   BC D4 D3    LDY   $D3D4,X
160E-   D4          ???
160F-   D2 8D       CMP   ($8D)
1611-   A0 D0       LDY   #$D0
1613-   C8          INY
1614-   C1 8D       CMP   ($8D,X)
1616-   A0 CA       LDY   #$CA
1618-   D3          ???
1619-   D2 A0       CMP   ($A0)
161B-   C6 D0       DEC   $D0
161D-   D3          ???
161E-   D4          ???
161F-   D2 8D       CMP   ($8D)
1621-   A0 CA       LDY   #$CA
1623-   D3          ???
1624-   D2 A0       CMP   ($A0)
1626-   C3          ???
1627-   CD C4 8D    CMP   $8DC4
162A-   A0 C1       LDY   #$C1
162C-   D3          ???
162D-   C3          ???
162E-   A0 A2       LDY   #$A2
1630-   C3          ???
1631-   CC CF D3    CPY   $D3CF
1634-   C5 20       CMP   $20
1636-   D4          ???
1637-   AE D4 C5    LDX   $C5D4
163A-   D3          ???
163B-   D4          ???
163C-   A2 8D       LDX   #$8D
163E-   A0 C8       LDY   #$C8
1640-   C5 D8       CMP   $D8
1642-   A0 B8       LDY   #$B8
1644-   C4 B0       CPY   $B0
1646-   B0 8D       BCS   $15D5
1648-   AA          TAX
1649-   8D AA AA    STA   $AAAA
164C-   20 DF C6    JSR   $C6DF
164F-   C7          ???
1650-   C5 D4       CMP   $D4
1652-   20 D3 C9    JSR   $C9D3
1655-   CD D0 CC    CMP   $CCD0
1658-   D9 20 C7    CMP   $C720,Y
165B-   C5 D4       CMP   $D4
165D-   D3          ???
165E-   20 C1 20    JSR   $20C1
1661-   D3          ???
1662-   C9 CE       CMP   #$CE
1664-   C7          ???
1665-   CC C5 20    CPY   $20C5
1668-   C3          ???
1669-   C8          INY
166A-   C1 D2       CMP   ($D2,X)
166C-   C1 C3       CMP   ($C3,X)
166E-   D4          ???
166F-   C5 D2       CMP   $D2
1671-   20 C6 D2    JSR   $D2C6
1674-   CF          ???
1675-   CD 8D AA    CMP   $AA8D
1678-   AA          TAX
1679-   20 D4 C8    JSR   $C8D4
167C-   C5 20       CMP   $20
167E-   C7          ???
167F-   C9 D6       CMP   #$D6
1681-   C5 CE       CMP   $CE
1683-   20 C6 C9    JSR   $C9C6
1686-   CC C5 20    CPY   $20C5
1689-   C1 CE       CMP   ($CE,X)
168B-   C4 20       CPY   $20
168D-   D3          ???
168E-   D4          ???
168F-   CF          ???
1690-   D2 C5       CMP   ($C5)
1692-   D3          ???
1693-   20 C9 D4    JSR   $D4C9
1696-   20 C9 CE    JSR   $CEC9
1699-   20 D4 C8    JSR   $C8D4
169C-   C5 8D       CMP   $8D
169E-   AA          TAX
169F-   AA          TAX
16A0-   20 C1 C3    JSR   $C3C1
16A3-   C3          ???
16A4-   D5 CD       CMP   $CD,X
16A6-   D5 CC       CMP   $CC,X
16A8-   C1 D4       CMP   ($D4,X)
16AA-   CF          ???
16AB-   D2 AE       CMP   ($AE)
16AD-   8D AA 8D    STA   $8DAA
16B0-   A0 DF       LDY   #$DF
16B2-   C3          ???
16B3-   CD C4 A0    CMP   $A0C4
16B6-   A2 CF       LDX   #$CF
16B8-   D0 C5       BNE   $167F
16BA-   CE 20 D4    DEC   $D420
16BD-   AE D4 C5    LDX   $C5D4
16C0-   D3          ???
16C1-   D4          ???
16C2-   A2 8D       LDX   #$8D
16C4-   A0 DF       LDY   #$DF
16C6-   C3          ???
16C7-   CD C4 A0    CMP   $A0C4
16CA-   A2 D2       LDX   #$D2
16CC-   C5 C1       CMP   $C1
16CE-   C4 20       CPY   $20
16D0-   D4          ???
16D1-   AE D4 C5    LDX   $C5D4
16D4-   D3          ???
16D5-   D4          ???
16D6-   A2 8D       LDX   #$8D
16D8-   A0 DF       LDY   #$DF
16DA-   C6 C7       DEC   $C7
16DC-   C5 D4       CMP   $D4
16DE-   8D A0 DF    STA   $DFA0
16E1-   C3          ???
16E2-   CD C4 A0    CMP   $A0C4
16E5-   A2 C3       LDX   #$C3
16E7-   CC CF D3    CPY   $D3CF
16EA-   C5 20       CMP   $20
16EC-   D4          ???
16ED-   AE D4 C5    LDX   $C5D4
16F0-   D3          ???
16F1-   D4          ???
16F2-   A2 8D       LDX   #$8D
16F4-   AA          TAX
16F5-   8D AA 8D    STA   $8DAA
16F8-   AA          TAX
16F9-   AA          TAX
16FA-   AA          TAX
16FB-   AA          TAX
16FC-   AA          TAX
16FD-   AA          TAX
16FE-   AA          TAX
16FF-   AA          TAX
1700-   AA          TAX
1701-   AA          TAX
1702-   AA          TAX
1703-   AA          TAX
1704-   AA          TAX
1705-   AA          TAX
1706-   AA          TAX
1707-   AA          TAX
1708-   AA          TAX
1709-   AA          TAX
170A-   AA          TAX
170B-   AA          TAX
170C-   AA          TAX
170D-   AA          TAX
170E-   AA          TAX
170F-   AA          TAX
1710-   AA          TAX
1711-   AA          TAX
1712-   AA          TAX
1713-   AA          TAX
1714-   AA          TAX
1715-   AA          TAX
1716-   AA          TAX
1717-   AA          TAX
1718-   8D AA AA    STA   $AAAA
171B-   AA          TAX
171C-   AA          TAX
171D-   AA          TAX
171E-   AA          TAX
171F-   AA          TAX
1720-   AA          TAX
1721-   AA          TAX
1722-   AA          TAX
1723-   AA          TAX
1724-   AA          TAX
1725-   AA          TAX
1726-   AA          TAX
1727-   AA          TAX
1728-   AA          TAX
1729-   AA          TAX
172A-   AA          TAX
172B-   AA          TAX
172C-   AA          TAX
172D-   AA          TAX
172E-   AA          TAX
172F-   AA          TAX
1730-   AA          TAX
1731-   AA          TAX
1732-   AA          TAX
1733-   AA          TAX
1734-   AA          TAX
1735-   AA          TAX
1736-   AA          TAX
1737-   AA          TAX
1738-   AA          TAX
1739-   8D AA AA    STA   $AAAA
173C-   AA          TAX
173D-   AA          TAX
173E-   AA          TAX
173F-   AA          TAX
1740-   AA          TAX
1741-   AA          TAX
1742-   AA          TAX
1743-   AA          TAX
1744-   AA          TAX
1745-   AA          TAX
1746-   AA          TAX
1747-   AA          TAX
1748-   AA          TAX
1749-   AA          TAX
174A-   AA          TAX
174B-   AA          TAX
174C-   AA          TAX
174D-   AA          TAX
174E-   AA          TAX
174F-   AA          TAX
1750-   AA          TAX
1751-   AA          TAX
1752-   AA          TAX
1753-   AA          TAX
1754-   AA          TAX
1755-   AA          TAX
1756-   AA          TAX
1757-   AA          TAX
1758-   AA          TAX
1759-   AA          TAX
175A-   8D AA AA    STA   $AAAA
175D-   AA          TAX
175E-   AA          TAX
175F-   AA          TAX
1760-   AA          TAX
1761-   AA          TAX
1762-   AA          TAX
1763-   AA          TAX
1764-   AA          TAX
1765-   AA          TAX
1766-   AA          TAX
1767-   AA          TAX
1768-   AA          TAX
1769-   AA          TAX
176A-   AA          TAX
176B-   AA          TAX
176C-   AA          TAX
176D-   AA          TAX
176E-   AA          TAX
176F-   AA          TAX
1770-   AA          TAX
1771-   AA          TAX
1772-   AA          TAX
1773-   AA          TAX
1774-   AA          TAX
1775-   AA          TAX
1776-   AA          TAX
1777-   AA          TAX
1778-   AA          TAX
1779-   AA          TAX
177A-   AA          TAX
177B-   8D AA 20    STA   $20AA
177E-   20 20 20    JSR   $2020
1781-   20 20 20    JSR   $2020
1784-   20 20 20    JSR   $2020
1787-   20 20 20    JSR   $2020
178A-   20 20 20    JSR   $2020
178D-   20 20 20    JSR   $2020
1790-   20 20 20    JSR   $2020
1793-   20 20 20    JSR   $2020
1796-   20 20 20    JSR   $2020
1799-   20 20 AA    JSR   $AA20
179C-   8D AA 20    STA   $20AA
179F-   20 20 C4    JSR   $C420
17A2-   20 C1 20    JSR   $20C1
17A5-   CE 20 C7    DEC   $C720
17A8-   20 C5 20    JSR   $20C5
17AB-   D2 20       CMP   ($20)
17AD-   C4 20       CPY   $20
17AF-   C1 20       CMP   ($20,X)
17B1-   CE 20 C7    DEC   $C720
17B4-   20 C5 20    JSR   $20C5
17B7-   D2 20       CMP   ($20)
17B9-   20 20 20    JSR   $2020
17BC-   AA          TAX
17BD-   8D AA 20    STA   $20AA
17C0-   20 20 20    JSR   $2020
17C3-   20 20 20    JSR   $2020
17C6-   20 20 20    JSR   $2020
17C9-   20 20 20    JSR   $2020
17CC-   20 20 20    JSR   $2020
17CF-   20 20 20    JSR   $2020
17D2-   20 20 20    JSR   $2020
17D5-   20 20 20    JSR   $2020
17D8-   20 20 20    JSR   $2020
17DB-   20 20 AA    JSR   $AA20
17DE-   8D AA AA    STA   $AAAA
17E1-   AA          TAX
17E2-   AA          TAX
17E3-   AA          TAX
17E4-   AA          TAX
17E5-   AA          TAX
17E6-   AA          TAX
17E7-   AA          TAX
17E8-   AA          TAX
17E9-   AA          TAX
17EA-   AA          TAX
17EB-   AA          TAX
17EC-   AA          TAX
17ED-   AA          TAX
17EE-   AA          TAX
17EF-   AA          TAX
17F0-   AA          TAX
17F1-   AA          TAX
17F2-   AA          TAX
17F3-   AA          TAX
17F4-   AA          TAX
17F5-   AA          TAX
17F6-   AA          TAX
17F7-   AA          TAX
17F8-   AA          TAX
17F9-   AA          TAX
17FA-   AA          TAX
17FB-   AA          TAX
17FC-   AA          TAX
17FD-   AA          TAX
17FE-   AA          TAX
17FF-   8D AA AA    STA   $AAAA
1802-   AA          TAX
1803-   AA          TAX
1804-   AA          TAX
1805-   AA          TAX
1806-   AA          TAX
1807-   AA          TAX
1808-   AA          TAX
1809-   AA          TAX
180A-   AA          TAX
180B-   AA          TAX
180C-   AA          TAX
180D-   AA          TAX
180E-   AA          TAX
180F-   AA          TAX
1810-   AA          TAX
1811-   AA          TAX
1812-   AA          TAX
1813-   AA          TAX
1814-   AA          TAX
1815-   AA          TAX
1816-   AA          TAX
1817-   AA          TAX
1818-   AA          TAX
1819-   AA          TAX
181A-   AA          TAX
181B-   AA          TAX
181C-   AA          TAX
181D-   AA          TAX
181E-   AA          TAX
181F-   AA          TAX
1820-   8D AA AA    STA   $AAAA
1823-   AA          TAX
1824-   AA          TAX
1825-   AA          TAX
1826-   AA          TAX
1827-   AA          TAX
1828-   AA          TAX
1829-   AA          TAX
182A-   AA          TAX
182B-   AA          TAX
182C-   AA          TAX
182D-   AA          TAX
182E-   AA          TAX
182F-   AA          TAX
1830-   AA          TAX
1831-   AA          TAX
1832-   AA          TAX
1833-   AA          TAX
1834-   AA          TAX
1835-   AA          TAX
1836-   AA          TAX
1837-   AA          TAX
1838-   AA          TAX
1839-   AA          TAX
183A-   AA          TAX
183B-   AA          TAX
183C-   AA          TAX
183D-   AA          TAX
183E-   AA          TAX
183F-   AA          TAX
1840-   AA          TAX
1841-   8D AA AA    STA   $AAAA
1844-   AA          TAX
1845-   AA          TAX
1846-   AA          TAX
1847-   AA          TAX
1848-   AA          TAX
1849-   AA          TAX
184A-   AA          TAX
184B-   AA          TAX
184C-   AA          TAX
184D-   AA          TAX
184E-   AA          TAX
184F-   AA          TAX
1850-   AA          TAX
1851-   AA          TAX
1852-   AA          TAX
1853-   AA          TAX
1854-   AA          TAX
1855-   AA          TAX
1856-   AA          TAX
1857-   AA          TAX
1858-   AA          TAX
1859-   AA          TAX
185A-   AA          TAX
185B-   AA          TAX
185C-   AA          TAX
185D-   AA          TAX
185E-   AA          TAX
185F-   AA          TAX
1860-   AA          TAX
1861-   AA          TAX
1862-   8D AA 8D    STA   $8DAA
1865-   AA          TAX
1866-   AA          TAX
1867-   20 D4 C8    JSR   $C8D4
186A-   C5 20       CMP   $20
186C-   C6 CF       DEC   $CF
186E-   CC CC CF    CPY   $CFCC
1871-   D7          ???
1872-   C9 CE       CMP   #$CE
1874-   C7          ???
1875-   20 C3 CF    JSR   $CFC3
1878-   C4 C5       CPY   $C5
187A-   20 C4 CF    JSR   $CFC4
187D-   C5 D3       CMP   $D3
187F-   20 CC CF    JSR   $CFCC
1882-   D7          ???
1883-   8D AA AA    STA   $AAAA
1886-   20 CC C5    JSR   $C5CC
1889-   D6 C5       DEC   $C5,X
188B-   CC 20 C4    CPY   $C420
188E-   C9 D3       CMP   #$D3
1890-   CB          ???
1891-   20 C1 C3    JSR   $C3C1
1894-   C3          ???
1895-   C5 D3       CMP   $D3
1897-   D3          ???
1898-   AC 20 D7    LDY   $D720
189B-   C8          INY
189C-   C9 C3       CMP   #$C3
189E-   C8          INY
189F-   20 C3 CF    JSR   $CFC3
18A2-   D5 CC       CMP   $CC,X
18A4-   C4 8D       CPY   $8D
18A6-   AA          TAX
18A7-   AA          TAX
18A8-   20 D3 C5    JSR   $C5D3
18AB-   D2 C9       CMP   ($C9)
18AD-   CF          ???
18AE-   D5 D3       CMP   $D3,X
18B0-   CC D9 20    CPY   $20D9
18B3-   C3          ???
18B4-   CF          ???
18B5-   D2 D2       CMP   ($D2)
18B7-   D5 D0       CMP   $D0,X
18B9-   D4          ???
18BA-   20 D9 CF    JSR   $CFD9
18BD-   D5 D2       CMP   $D2,X
18BF-   20 C4 C9    JSR   $C9C4
18C2-   D3          ???
18C3-   CB          ???
18C4-   AE 8D AA    LDX   $AA8D
18C7-   8D AA AA    STA   $AAAA
18CA-   20 CD C1    JSR   $C1CD
18CD-   CB          ???
18CE-   C5 20       CMP   $20
18D0-   D3          ???
18D1-   D5 D2       CMP   $D2,X
18D3-   C5 20       CMP   $20
18D5-   D9 CF D5    CMP   $D5CF,Y
18D8-   20 D5 D3    JSR   $D3D5
18DB-   C5 20       CMP   $20
18DD-   D4          ???
18DE-   C8          INY
18DF-   C5 D3       CMP   $D3
18E1-   C5 20       CMP   $20
18E3-   D2 CF       CMP   ($CF)
18E5-   D5 D4       CMP   $D4,X
18E7-   C9 CE       CMP   #$CE
18E9-   C5 D3       CMP   $D3
18EB-   8D AA AA    STA   $AAAA
18EE-   20 CF CE    JSR   $CECF
18F1-   CC D9 20    CPY   $20D9
18F4-   D7          ???
18F5-   C8          INY
18F6-   C5 CE       CMP   $CE
18F8-   20 D9 CF    JSR   $CFD9
18FB-   D5 20       CMP   $20,X
18FD-   C8          INY
18FE-   C1 D6       CMP   ($D6,X)
1900-   C5 20       CMP   $20
1902-   C2          ???
1903-   C1 C3       CMP   ($C3,X)
1905-   CB          ???
1906-   D5 D0       CMP   $D0,X
1908-   D3          ???
1909-   20 C1 CE    JSR   $CEC1
190C-   C4 8D       CPY   $8D
190E-   AA          TAX
190F-   AA          TAX
1910-   20 CB CE    JSR   $CECB
1913-   CF          ???
1914-   D7          ???
1915-   20 D7 C8    JSR   $C8D7
1918-   C1 D4       CMP   ($D4,X)
191A-   20 D9 CF    JSR   $CFD9
191D-   D5 A7       CMP   $A7,X
191F-   D2 C5       CMP   ($C5)
1921-   20 C4 CF    JSR   $CFC4
1924-   C9 CE       CMP   #$CE
1926-   C7          ???
1927-   A1 8D       LDA   ($8D,X)
1929-   AA          TAX
192A-   8D AA 8D    STA   $8DAA
192D-   AA          TAX
192E-   AA          TAX
192F-   20 DF D3    JSR   $D3DF
1932-   CC CF D4    CPY   $D4CF
1935-   20 D3 C5    JSR   $C5D3
1938-   D4          ???
1939-   D3          ???
193A-   20 D4 C8    JSR   $C8D4
193D-   C5 20       CMP   $20
193F-   D3          ???
1940-   CC CF D4    CPY   $D4CF
1943-   20 C6 CF    JSR   $CFC6
1946-   D2 20       CMP   ($20)
1948-   D2 D7       CMP   ($D7)
194A-   D4          ???
194B-   D3          ???
194C-   8D AA AA    STA   $AAAA
194F-   20 CC CF    JSR   $CFCC
1952-   D7          ???
1953-   AD CC C5    LDA   $C5CC
1956-   D6 C5       DEC   $C5,X
1958-   CC 20 C4    CPY   $C420
195B-   C9 D3       CMP   #$D3
195D-   CB          ???
195E-   20 CF D0    JSR   $D0CF
1961-   C5 D2       CMP   $D2
1963-   C1 D4       CMP   ($D4,X)
1965-   C9 CF       CMP   #$CF
1967-   CE D3 AE    DEC   $AED3
196A-   8D AA AA    STA   $AAAA
196D-   20 D4 C8    JSR   $C8D4
1970-   C5 D2       CMP   $D2
1972-   C5 20       CMP   $20
1974-   C9 D3       CMP   #$D3
1976-   20 CE CF    JSR   $CFCE
1979-   20 C1 C3    JSR   $C3C1
197C-   D4          ???
197D-   D5 C1       CMP   $C1,X
197F-   CC 20 D2    CPY   $D220
1982-   CF          ???
1983-   D5 D4       CMP   $D4,X
1985-   C9 CE       CMP   #$CE
1987-   C5 20       CMP   $20
1989-   C6 CF       DEC   $CF
198B-   D2 8D       CMP   ($8D)
198D-   AA          TAX
198E-   AA          TAX
198F-   20 D4 C8    JSR   $C8D4
1992-   C9 D3       CMP   #$D3
1994-   20 C9 CE    JSR   $CEC9
1997-   20 D4 C8    JSR   $C8D4
199A-   C5 20       CMP   $20
199C-   CC C9 C2    CPY   $C2C9
199F-   D2 C1       CMP   ($C1)
19A1-   D2 D9       CMP   ($D9)
19A3-   BB          ???
19A4-   20 C9 D4    JSR   $D4C9
19A7-   20 CF CE    JSR   $CECF
19AA-   CC D9 20    CPY   $20D9
19AD-   C5 D8       CMP   $D8
19AF-   C9 D3       CMP   #$D3
19B1-   D4          ???
19B2-   D3          ???
19B3-   8D AA AA    STA   $AAAA
19B6-   20 C1 D3    JSR   $D3C1
19B9-   20 C1 20    JSR   $20C1
19BC-   CD C1 C3    CMP   $C3C1
19BF-   D2 CF       CMP   ($CF)
19C1-   AE 8D AA    LDX   $AA8D
19C4-   8D A0 DF    STA   $DFA0
19C7-   D3          ???
19C8-   CC CF D4    CPY   $D4CF
19CB-   A0 A3       LDY   #$A3
19CD-   B6 8D       LDX   $8D,Y
19CF-   AA          TAX
19D0-   8D AA AA    STA   $AAAA
19D3-   20 D4 C8    JSR   $C8D4
19D6-   C5 20       CMP   $20
19D8-   D2 C5       CMP   ($C5)
19DA-   D3          ???
19DB-   D4          ???
19DC-   20 CF C6    JSR   $C6CF
19DF-   20 D4 C8    JSR   $C8D4
19E2-   C5 20       CMP   $20
19E4-   C3          ???
19E5-   CF          ???
19E6-   CD CD C1    CMP   $C1CD
19E9-   CE C4 D3    DEC   $D3C4
19EC-   20 D5 D0    JSR   $D0D5
19EF-   20 D5 CE    JSR   $CED5
19F2-   D4          ???
19F3-   C9 CC       CMP   #$CC
19F5-   8D AA AA    STA   $AAAA
19F8-   20 DF D2    JSR   $D2DF
19FB-   D7          ???
19FC-   D4          ???
19FD-   D3          ???
19FE-   20 C6 CF    JSR   $CFC6
1A01-   CC CC CF    CPY   $CFCC
1A04-   D7          ???
1A05-   20 C1 20    JSR   $20C1
1A08-   D3          ???
1A09-   C9 CD       CMP   #$CD
1A0B-   C9 CC       CMP   #$CC
1A0D-   C1 D2       CMP   ($D2,X)
1A0F-   20 D0 C1    JSR   $C1D0
1A12-   D4          ???
1A13-   D4          ???
1A14-   C5 D2       CMP   $D2
1A16-   CE AC 20    DEC   $20AC
1A19-   C1 CE       CMP   ($CE,X)
1A1B-   C4 20       CPY   $20
1A1D-   C1 CC       CMP   ($CC,X)
1A1F-   CC 8D AA    CPY   $AA8D
1A22-   AA          TAX
1A23-   20 C3 C8    JSR   $C8C3
1A26-   C1 CE       CMP   ($CE,X)
1A28-   C7          ???
1A29-   C5 20       CMP   $20
1A2B-   D4          ???
1A2C-   C8          INY
1A2D-   C5 20       CMP   $20
1A2F-   C9 CF       CMP   #$CF
1A31-   C2          ???
1A32-   20 D4 C1    JSR   $C1D4
1A35-   C2          ???
1A36-   CC C5 AE    CPY   $AEC5
1A39-   8D AA 8D    STA   $8DAA
1A3C-   AA          TAX
1A3D-   8D A0 DF    STA   $DFA0
1A40-   C4 D2       CPY   $D2
1A42-   C9 D6       CMP   #$D6
1A44-   A0 A3       LDY   #$A3
1A46-   B2 A0       LDA   ($A0)
1A48-   BB          ???
1A49-   20 C3 C8    JSR   $C8C3
1A4C-   C1 CE       CMP   ($CE,X)
1A4E-   C7          ???
1A4F-   C5 20       CMP   $20
1A51-   C4 D2       CPY   $D2
1A53-   C9 D6       CMP   #$D6
1A55-   C5 8D       CMP   $8D
1A57-   AA          TAX
1A58-   8D A0 DF    STA   $DFA0
1A5B-   C3          ???
1A5C-   CF          ???
1A5D-   CD CD A0    CMP   $A0CD
1A60-   A3          ???
1A61-   B1 A0       LDA   ($A0),Y
1A63-   BB          ???
1A64-   20 D3 C5    JSR   $C5D3
1A67-   D4          ???
1A68-   20 C6 CF    JSR   $CFC6
1A6B-   D2 20       CMP   ($20)
1A6D-   D2 C5       CMP   ($C5)
1A6F-   C1 C4       CMP   ($C4,X)
1A71-   8D AA 8D    STA   $8DAA
1A74-   A0 DF       LDY   #$DF
1A76-   C4 C2       CPY   $C2
1A78-   D5 C6       CMP   $C6,X
1A7A-   A0 A4       LDY   #$A4
1A7C-   B1 B0       LDA   ($B0),Y
1A7E-   B0 B0       BCS   $1A30
1A80-   A0 BB       LDY   #$BB
1A82-   20 C4 C9    JSR   $C9C4
1A85-   D3          ???
1A86-   CB          ???
1A87-   20 C2 D5    JSR   $D5C2
1A8A-   C6 C6       DEC   $C6
1A8C-   C5 D2       CMP   $D2
1A8E-   20 C1 D2    JSR   $D2C1
1A91-   C5 C1       CMP   $C1
1A93-   8D AA 8D    STA   $8DAA
1A96-   A0 DF       LDY   #$DF
1A98-   D4          ???
1A99-   D2 C1       CMP   ($C1)
1A9B-   CB          ???
1A9C-   A0 A3       LDY   #$A3
1A9E-   B2 A0       LDA   ($A0)
1AA0-   BB          ???
1AA1-   20 D3 C5    JSR   $C5D3
1AA4-   D4          ???
1AA5-   20 D4 D2    JSR   $D2D4
1AA8-   C1 C3       CMP   ($C3,X)
1AAA-   CB          ???
1AAB-   8D A0 DF    STA   $DFA0
1AAE-   D3          ???
1AAF-   C5 C3       CMP   $C3
1AB1-   D4          ???
1AB2-   A0 A3       LDY   #$A3
1AB4-   B2 A0       LDA   ($A0)
1AB6-   BB          ???
1AB7-   20 D3 C5    JSR   $C5D3
1ABA-   D4          ???
1ABB-   20 D3 C5    JSR   $C5D3
1ABE-   C3          ???
1ABF-   D4          ???
1AC0-   CF          ???
1AC1-   D2 8D       CMP   ($8D)
1AC3-   AA          TAX
1AC4-   8D A0 DF    STA   $DFA0
1AC7-   D2 D7       CMP   ($D7)
1AC9-   D4          ???
1ACA-   D3          ???
1ACB-   8D A0 C2    STA   $C2A0
1ACE-   D2 CB       CMP   ($CB)
1AD0-   8D AA 8D    STA   $8DAA
1AD3-   AA          TAX
1AD4-   AA          TAX
1AD5-   20 D4 C8    JSR   $C8D4
1AD8-   C5 20       CMP   $20
1ADA-   D0 D2       BNE   $1AAE
1ADC-   C5 C3       CMP   $C3
1ADE-   C5 C4       CMP   $C4
1AE0-   C9 CE       CMP   #$CE
1AE2-   C7          ???
1AE3-   20 D2 C5    JSR   $C5D2
1AE6-   C1 C4       CMP   ($C4,X)
1AE8-   D3          ???
1AE9-   20 C6 D2    JSR   $D2C6
1AEC-   CF          ???
1AED-   CD 20 D4    CMP   $D420
1AF0-   D2 C1       CMP   ($C1)
1AF2-   C3          ???
1AF3-   CB          ???
1AF4-   20 B2 AC    JSR   $ACB2
1AF7-   20 D3 C5    JSR   $C5D3
1AFA-   C3          ???
1AFB-   D4          ???
1AFC-   CF          ???
1AFD-   D2 20       CMP   ($20)
1AFF-   B2 8D       LDA   ($8D)
1B01-   AA          TAX
1B02-   AA          TAX
1B03-   20 CF C6    JSR   $C6CF
1B06-   20 C4 D2    JSR   $D2C4
1B09-   C9 D6       CMP   #$D6
1B0B-   C5 20       CMP   $20
1B0D-   B2 20       LDA   ($20)
1B0F-   C9 CE       CMP   #$CE
1B11-   20 D3 CC    JSR   $CCD3
1B14-   CF          ???
1B15-   D4          ???
1B16-   20 B6 AC    JSR   $ACB6
1B19-   20 C1 CE    JSR   $CEC1
1B1C-   C4 20       CPY   $20
1B1E-   C3          ???
1B1F-   CF          ???
1B20-   D0 C9       BNE   $1AEB
1B22-   C5 D3       CMP   $D3
1B24-   20 C9 D4    JSR   $D4C9
1B27-   20 D4 CF    JSR   $CFD4
1B2A-   20 A4 B1    JSR   $B1A4
1B2D-   B0 B0       BCS   $1ADF
1B2F-   B0 AE       BCS   $1ADF
1B31-   8D AA 8D    STA   $8DAA
1B34-   AA          TAX
1B35-   AA          TAX
1B36-   20 D4 C8    JSR   $C8D4
1B39-   C5 D2       CMP   $D2
1B3B-   C5 20       CMP   $20
1B3D-   C1 D2       CMP   ($D2,X)
1B3F-   C5 20       CMP   $20
1B41-   D0 CC       BNE   $1B0F
1B43-   C5 CE       CMP   $CE
1B45-   D4          ???
1B46-   D9 20 CF    CMP   $CF20,Y
1B49-   C6 20       DEC   $20
1B4B-   CF          ???
1B4C-   D4          ???
1B4D-   C8          INY
1B4E-   C5 D2       CMP   $D2
1B50-   20 D5 D3    JSR   $D3D5
1B53-   C5 D3       CMP   $D3
1B55-   20 C8 C5    JSR   $C5C8
1B58-   D2 C5       CMP   ($C5)
1B5A-   AC 20 C2    LDY   $C220
1B5D-   D5 D4       CMP   $D4,X
1B5F-   20 C6 CF    JSR   $CFC6
1B62-   D2 8D       CMP   ($8D)
1B64-   AA          TAX
1B65-   AA          TAX
1B66-   20 D4 C8    JSR   $C8D4
1B69-   C5 20       CMP   $20
1B6B-   D3          ???
1B6C-   C1 CB       CMP   ($CB,X)
1B6E-   C5 20       CMP   $20
1B70-   CF          ???
1B71-   C6 20       DEC   $20
1B73-   D3          ???
1B74-   C1 C6       CMP   ($C6,X)
1B76-   C5 D4       CMP   $D4
1B78-   D9 AC 20    CMP   $20AC,Y
1B7B-   D7          ???
1B7C-   C5 20       CMP   $20
1B7E-   D7          ???
1B7F-   CF          ???
1B80-   CE A7 D4    DEC   $D4A7
1B83-   20 C2 C5    JSR   $C5C2
1B86-   20 D3 C8    JSR   $C8D3
1B89-   CF          ???
1B8A-   D7          ???
1B8B-   C9 CE       CMP   #$CE
1B8D-   C7          ???
1B8E-   20 C1 CE    JSR   $CEC1
1B91-   D9 8D AA    CMP   $AA8D,Y
1B94-   AA          TAX
1B95-   20 C4 C9    JSR   $C9C4
1B98-   D3          ???
1B99-   CB          ???
1B9A-   20 D7 D2    JSR   $D2D7
1B9D-   C9 D4       CMP   #$D4
1B9F-   C5 20       CMP   $20
1BA1-   CF          ???
1BA2-   D0 C5       BNE   $1B69
1BA4-   D2 C1       CMP   ($C1)
1BA6-   D4          ???
1BA7-   C9 CF       CMP   #$CF
1BA9-   CE D3 AE    DEC   $AED3
1BAC-   20 C8 CF    JSR   $CFC8
1BAF-   D7          ???
1BB0-   C5 D6       CMP   $D6
1BB2-   C5 D2       CMP   $D2
1BB4-   AC 20 D4    LDY   $D420
1BB7-   C8          INY
1BB8-   C5 D2       CMP   $D2
1BBA-   C5 20       CMP   $20
1BBC-   D7          ???
1BBD-   C9 CC       CMP   #$CC
1BBF-   CC 20 C2    CPY   $C220
1BC2-   C5 20       CMP   $20
1BC4-   C1 8D       CMP   ($8D,X)
1BC6-   AA          TAX
1BC7-   AA          TAX
1BC8-   20 C4 C9    JSR   $C9C4
1BCB-   D3          ???
1BCC-   CB          ???
1BCD-   20 C4 C5    JSR   $C5C4
1BD0-   C4 C9       CPY   $C9
1BD2-   C3          ???
1BD3-   C1 D4       CMP   ($D4,X)
1BD5-   C5 C4       CMP   $C4
1BD7-   20 D4 CF    JSR   $CFD4
1BDA-   20 D4 C8    JSR   $C8D4
1BDD-   C9 D3       CMP   #$D3
1BDF-   20 C9 CE    JSR   $CEC9
1BE2-   20 D4 C8    JSR   $C8D4
1BE5-   C5 20       CMP   $20
1BE7-   C6 D5       DEC   $D5
1BE9-   D4          ???
1BEA-   D5 D2       CMP   $D2,X
1BEC-   C5 AC       CMP   $AC
1BEE-   20 C2 D5    JSR   $D5C2
1BF1-   D4          ???
1BF2-   20 D7 C9    JSR   $C9D7
1BF5-   D4          ???
1BF6-   C8          INY
1BF7-   CF          ???
1BF8-   D5 D4       CMP   $D4,X
1BFA-   8D AA AA    STA   $AAAA
1BFD-   20 D4 C8    JSR   $C8D4
1C00-   C5 20       CMP   $20
1C02-   D3          ???
1C03-   CF          ???
1C04-   D5 D2       CMP   $D2,X
1C06-   C3          ???
1C07-   C5 20       CMP   $20
1C09-   C3          ???
1C0A-   CF          ???
1C0B-   C4 C5       CPY   $C5
1C0D-   20 CF CE    JSR   $CECF
1C10-   20 C9 D4    JSR   $D4C9
1C13-   AE 8D AA    LDX   $AA8D
1C16-   8D AA 8D    STA   $8DAA
1C19-   AA          TAX
1C1A-   8D AA AA    STA   $AAAA
1C1D-   20 CC C9    JSR   $C9CC
1C20-   D4          ???
1C21-   D4          ???
1C22-   CC C5 20    CPY   $20C5
1C25-   CC D5 CD    CPY   $CDD5
1C28-   D0 D3       BNE   $1BFD
1C2A-   20 AD AD    JSR   $ADAD
1C2D-   20 CD C9    JSR   $C9CD
1C30-   C4 AF       CPY   $AF
1C32-   CC CF D7    CPY   $D7CF
1C35-   20 CC C5    JSR   $C5CC
1C38-   D6 C5       DEC   $C5,X
1C3A-   CC 8D AA    CPY   $AA8D
1C3D-   8D AA 8D    STA   $8DAA
1C40-   A0 CA       LDY   #$CA
1C42-   CD D0 A0    CMP   $A0D0
1C45-   D2 C5       CMP   ($C5)
1C47-   C5 CE       CMP   $CE
1C49-   D4          ???
1C4A-   D2 D9       CMP   ($D9)
1C4C-   8D AA 8D    STA   $8DAA
1C4F-   AA          TAX
1C50-   AA          TAX
1C51-   20 C4 C1    JSR   $C1C4
1C54-   D4          ???
1C55-   C1 8D       CMP   ($8D,X)
1C57-   AA          TAX
1C58-   8D D4 C5    STA   $C5D4
1C5B-   D3          ???
1C5C-   D4          ???
1C5D-   D3          ???
1C5E-   D4          ???
1C5F-   D2 A0       CMP   ($A0)
1C61-   D3          ???
1C62-   D4          ???
1C63-   D2 A0       CMP   ($A0)
1C65-   A2 D4       LDX   #$D4
1C67-   C5 D3       CMP   $D3
1C69-   D4          ???
1C6A-   AC C1 A4    LDY   $A4C1
1C6D-   B3          ???
1C6E-   B0 B0       BCS   $1C20
1C70-   AC CC A4    LDY   $A4CC
1C73-   B1 B0       LDA   ($B0),Y
1C75-   B0 A2       BCS   $1C19
1C77-   8D D4 C5    STA   $C5D4
1C7A-   D3          ???
1C7B-   D4          ???
1C7C-   CC C4 A0    CPY   $A0C4
1C7F-   D3          ???
1C80-   D4          ???
1C81-   D2 A0       CMP   ($A0)
1C83-   A2 D4       LDX   #$D4
1C85-   C5 D3       CMP   $D3
1C87-   D4          ???
1C88-   AC C1 A4    LDY   $A4C1
1C8B-   B3          ???
1C8C-   B0 B0       BCS   $1C3E
1C8E-   A2 8D       LDX   #$8D
1C90-   D4          ???
1C91-   D3          ???
1C92-   D4          ???
1C93-   D2 A0       CMP   ($A0)
1C95-   D3          ???
1C96-   D4          ???
1C97-   D2 A0       CMP   ($A0)
1C99-   A2 C3       LDX   #$C3
1C9B-   CF          ???
1C9C-   CD CD D5    CMP   $D5CD
1C9F-   CE C9 D3    DEC   $D3C9
1CA2-   CD 20 D7    CMP   $D720
1CA5-   C9 CC       CMP   #$CC
1CA7-   CC 20 D7    CPY   $D720
1CAA-   C9 CE       CMP   #$CE
1CAC-   A1 A2       LDA   ($A2,X)
1CAE-   8D AA 8D    STA   $8DAA
1CB1-   AA          TAX
1CB2-   8D AA E0    STA   $E0AA
1CB5-   E0 E0       CPX   #$E0
1CB7-   E0 E0       CPX   #$E0
1CB9-   E0 E0       CPX   #$E0
1CBB-   E0 E0       CPX   #$E0
1CBD-   E0 E0       CPX   #$E0
1CBF-   E0 E0       CPX   #$E0
1CC1-   E0 E0       CPX   #$E0
1CC3-   E0 E0       CPX   #$E0
1CC5-   E0 E0       CPX   #$E0
1CC7-   E0 E0       CPX   #$E0
1CC9-   E0 E0       CPX   #$E0
1CCB-   E0 E0       CPX   #$E0
1CCD-   E0 E0       CPX   #$E0
1CCF-   E0 E0       CPX   #$E0
1CD1-   E0 AA       CPX   #$AA
1CD3-   8D AA 20    STA   $20AA
1CD6-   20 20 20    JSR   $2020
1CD9-   20 20 20    JSR   $2020
1CDC-   20 C2 CF    JSR   $CFC2
1CDF-   D4          ???
1CE0-   D4          ???
1CE1-   CF          ???
1CE2-   CD 20 C9    CMP   $C920
1CE5-   CE C3 CC    DEC   $CCC3
1CE8-   D5 C4       CMP   $C4,X
1CEA-   C5 D3       CMP   $D3
1CEC-   20 20 20    JSR   $2020
1CEF-   20 20 20    JSR   $2020
1CF2-   20 AA 8D    JSR   $8DAA
1CF5-   AA          TAX
1CF6-   AC AC AC    LDY   $ACAC
1CF9-   AC AC AC    LDY   $ACAC
1CFC-   AC AC AC    LDY   $ACAC
1CFF-   AC AC AC    LDY   $ACAC
1D02-   AC AC AC    LDY   $ACAC
1D05-   AC AC AC    LDY   $ACAC
1D08-   AC AC AC    LDY   $ACAC
1D0B-   AC AC AC    LDY   $ACAC
1D0E-   AC AC AC    LDY   $ACAC
1D11-   AC AC AC    LDY   $ACAC
1D14-   AA          TAX
1D15-   8D AA 8D    STA   $8DAA
1D18-   AA          TAX
1D19-   8D AA AA    STA   $AAAA
1D1C-   20 C2 CF    JSR   $CFC2
1D1F-   D4          ???
1D20-   D4          ???
1D21-   CF          ???
1D22-   CD 20 C9    CMP   $C920
1D25-   CE C3 CC    DEC   $CCC3
1D28-   D5 C4       CMP   $C4,X
1D2A-   C5 D3       CMP   $D3
1D2C-   8D AA 8D    STA   $8DAA
1D2F-   A0 D0       LDY   #$D0
1D31-   D5 D4       CMP   $D4,X
1D33-   A0 C6       LDY   #$C6
1D35-   C9 CC       CMP   #$CC
1D37-   C5 C9       CMP   $C9
1D39-   CF          ???
1D3A-   AE CC C9    LDX   $C9CC
1D3D-   C2          ???
1D3E-   8D AA 8D    STA   $8DAA
