0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C3    LDY   $C320,X
0950-   CF          ???
0951-   CD CD CF    CMP   $CFCD
0954-   CE 20 C4    DEC   $C420
0957-   C5 CD       CMP   $CD
0959-   CF          ???
095A-   20 A9 AD    JSR   $ADA9
095D-   20 20 20    JSR   $2020
0960-   20 20 20    JSR   $2020
0963-   20 AA 8D    JSR   $8DAA
0966-   AA          TAX
0967-   20 20 20    JSR   $2020
096A-   20 20 20    JSR   $2020
096D-   20 20 20    JSR   $2020
0970-   20 20 20    JSR   $2020
0973-   20 20 20    JSR   $2020
0976-   20 20 20    JSR   $2020
0979-   20 20 20    JSR   $2020
097C-   20 20 20    JSR   $2020
097F-   20 20 20    JSR   $2020
0982-   20 20 20    JSR   $2020
0985-   AA          TAX
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   20 D6 C5    JSR   $C5D6
0992-   D2 D3       CMP   ($D3)
0994-   C9 CF       CMP   #$CF
0996-   CE 20 B0    DEC   $B020
0999-   AE B3 AE    LDX   $AEB3
099C-   B0 20       BCS   $09BE
099E-   20 20 20    JSR   $2020
09A1-   20 20 20    JSR   $2020
09A4-   20 20 AA    JSR   $AA20
09A7-   8D AA 20    STA   $20AA
09AA-   20 20 20    JSR   $2020
09AD-   20 20 20    JSR   $2020
09B0-   20 20 20    JSR   $2020
09B3-   20 20 20    JSR   $2020
09B6-   20 20 20    JSR   $2020
09B9-   20 20 20    JSR   $2020
09BC-   20 20 20    JSR   $2020
09BF-   20 20 20    JSR   $2020
09C2-   20 20 20    JSR   $2020
09C5-   20 20 AA    JSR   $AA20
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B1    JSR   $B120
09D4-   B0 AD       BCS   $0983
09D6-   CA          DEX
09D7-   C1 CE       CMP   ($CE,X)
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B9       LDA   ($B9),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 D4    STA   $D4A0
0B02-   D2 A0       CMP   ($A0)
0B04-   CF          ???
0B05-   CE 8D A0    DEC   $A08D
0B08-   C4 D3       CPY   $D3
0B0A-   CB          ???
0B0B-   A0 C3       LDY   #$C3
0B0D-   CF          ???
0B0E-   CD CD CF    CMP   $CFCD
0B11-   CE AE C4    DEC   $C4AE
0B14-   C5 CD       CMP   $CD
0B16-   CF          ???
0B17-   8D A0 CF    STA   $CFA0
0B1A-   C2          ???
0B1B-   CA          DEX
0B1C-   A0 A4       LDY   #$A4
0B1E-   C2          ???
0B1F-   C6 C5       DEC   $C5
0B21-   B0 8D       BCS   $0AB0
0B23-   A0 CF       LDY   #$CF
0B25-   D2 C7       CMP   ($C7)
0B27-   A0 A4       LDY   #$A4
0B29-   B6 B0       LDX   $B0,Y
0B2B-   B0 B0       BCS   $0ADD
0B2D-   8D AA 8D    STA   $8DAA
0B30-   AA          TAX
0B31-   E0 E0       CPX   #$E0
0B33-   E0 E0       CPX   #$E0
0B35-   E0 E0       CPX   #$E0
0B37-   E0 E0       CPX   #$E0
0B39-   E0 E0       CPX   #$E0
0B3B-   E0 E0       CPX   #$E0
0B3D-   E0 E0       CPX   #$E0
0B3F-   E0 E0       CPX   #$E0
0B41-   E0 E0       CPX   #$E0
0B43-   E0 E0       CPX   #$E0
0B45-   E0 E0       CPX   #$E0
0B47-   E0 E0       CPX   #$E0
0B49-   E0 E0       CPX   #$E0
0B4B-   E0 E0       CPX   #$E0
0B4D-   E0 E0       CPX   #$E0
0B4F-   AA          TAX
0B50-   8D AA 20    STA   $20AA
0B53-   20 D4 CF    JSR   $CFD4
0B56-   D0 20       BNE   $0B78
0B58-   C9 CE       CMP   #$CE
0B5A-   C3          ???
0B5B-   CC D5 C4    CPY   $C4D5
0B5E-   C5 D3       CMP   $D3
0B60-   20 A8 C8    JSR   $C8A8
0B63-   CF          ???
0B64-   CF          ???
0B65-   CB          ???
0B66-   D3          ???
0B67-   AC CD C1    LDY   $C1CD
0B6A-   C3          ???
0B6B-   D2 CF       CMP   ($CF)
0B6D-   D3          ???
0B6E-   A9 20       LDA   #$20
0B70-   AA          TAX
0B71-   8D AA AC    STA   $ACAA
0B74-   AC AC AC    LDY   $ACAC
0B77-   AC AC AC    LDY   $ACAC
0B7A-   AC AC AC    LDY   $ACAC
0B7D-   AC AC AC    LDY   $ACAC
0B80-   AC AC AC    LDY   $ACAC
0B83-   AC AC AC    LDY   $ACAC
0B86-   AC AC AC    LDY   $ACAC
0B89-   AC AC AC    LDY   $ACAC
0B8C-   AC AC AC    LDY   $ACAC
0B8F-   AC AC AA    LDY   $AAAC
0B92-   8D AA 8D    STA   $8DAA
0B95-   A0 D0       LDY   #$D0
0B97-   D5 D4       CMP   $D4,X
0B99-   A0 CD       LDY   #$CD
0B9B-   C9 CE       CMP   #$CE
0B9D-   AE D6 C1    LDX   $C1D6
0BA0-   D2 D3       CMP   ($D3)
0BA2-   AE D2 C5    LDX   $C5D2
0BA5-   D1 D5       CMP   ($D5),Y
0BA7-   C9 D2       CMP   #$D2
0BA9-   C5 C4       CMP   $C4
0BAB-   8D A0 D5    STA   $D5A0
0BAE-   D3          ???
0BAF-   C5 A0       CMP   $A0
0BB1-   CD C9 CE    CMP   $CEC9
0BB4-   AE CD C1    LDX   $C1CD
0BB7-   C3          ???
0BB8-   AE D2 C5    LDX   $C5D2
0BBB-   D1 D5       CMP   ($D5),Y
0BBD-   C9 D2       CMP   #$D2
0BBF-   C5 C4       CMP   $C4
0BC1-   8D A0 D0    STA   $D0A0
0BC4-   D5 D4       CMP   $D4,X
0BC6-   A0 CD       LDY   #$CD
0BC8-   C9 CE       CMP   #$CE
0BCA-   AE C8 CF    LDX   $CFC8
0BCD-   CF          ???
0BCE-   CB          ???
0BCF-   D3          ???
0BD0-   AE D2 C5    LDX   $C5D2
0BD3-   D1 D5       CMP   ($D5),Y
0BD5-   C9 D2       CMP   #$D2
0BD7-   C5 C4       CMP   $C4
0BD9-   8D A0 D5    STA   $D5A0
0BDC-   D3          ???
0BDD-   C5 A0       CMP   $A0
0BDF-   CD C9 CE    CMP   $CEC9
0BE2-   AE CD C1    LDX   $C1CD
0BE5-   C3          ???
0BE6-   AE C3 CF    LDX   $CFC3
0BE9-   CD CD CF    CMP   $CFCD
0BEC-   CE 8D A0    DEC   $A08D
0BEF-   D0 D5       BNE   $0BC6
0BF1-   D4          ???
0BF2-   20 A0 CD    JSR   $CDA0
0BF5-   C9 CE       CMP   #$CE
0BF7-   AE C8 CF    LDX   $CFC8
0BFA-   CF          ???
0BFB-   CB          ???
0BFC-   D3          ???
0BFD-   AE C3 CF    LDX   $CFC3
0C00-   CD CD CF    CMP   $CFCD
0C03-   CE 8D AA    DEC   $AA8D
0C06-   8D AA E0    STA   $E0AA
0C09-   E0 E0       CPX   #$E0
0C0B-   E0 E0       CPX   #$E0
0C0D-   E0 E0       CPX   #$E0
0C0F-   E0 E0       CPX   #$E0
0C11-   E0 E0       CPX   #$E0
0C13-   E0 E0       CPX   #$E0
0C15-   E0 E0       CPX   #$E0
0C17-   E0 E0       CPX   #$E0
0C19-   E0 E0       CPX   #$E0
0C1B-   E0 E0       CPX   #$E0
0C1D-   E0 E0       CPX   #$E0
0C1F-   E0 E0       CPX   #$E0
0C21-   E0 E0       CPX   #$E0
0C23-   E0 E0       CPX   #$E0
0C25-   E0 AA       CPX   #$AA
0C27-   8D AA 20    STA   $20AA
0C2A-   20 20 20    JSR   $2020
0C2D-   20 20 D0    JSR   $D020
0C30-   D2 CF       CMP   ($CF)
0C32-   C7          ???
0C33-   D2 C1       CMP   ($C1)
0C35-   CD 20 CD    CMP   $CD20
0C38-   C1 C9       CMP   ($C9,X)
0C3A-   CE 20 C2    DEC   $C220
0C3D-   CF          ???
0C3E-   C4 D9       CPY   $D9
0C40-   20 20 20    JSR   $2020
0C43-   20 20 20    JSR   $2020
0C46-   20 AA 8D    JSR   $8DAA
0C49-   AA          TAX
0C4A-   AC AC AC    LDY   $ACAC
0C4D-   AC AC AC    LDY   $ACAC
0C50-   AC AC AC    LDY   $ACAC
0C53-   AC AC AC    LDY   $ACAC
0C56-   AC AC AC    LDY   $ACAC
0C59-   AC AC AC    LDY   $ACAC
0C5C-   AC AC AC    LDY   $ACAC
0C5F-   AC AC AC    LDY   $ACAC
0C62-   AC AC AC    LDY   $ACAC
0C65-   AC AC AC    LDY   $ACAC
0C68-   AA          TAX
0C69-   8D AA 8D    STA   $8DAA
0C6C-   AA          TAX
0C6D-   AA          TAX
0C6E-   20 CD C6    JSR   $C6CD
0C71-   C9 CC       CMP   #$CC
0C73-   CC 20 C4    CPY   $C420
0C76-   CF          ???
0C77-   C5 D3       CMP   $D3
0C79-   20 C1 C2    JSR   $C2C1
0C7C-   CF          ???
0C7D-   D5 D4       CMP   $D4,X
0C7F-   20 D7 C8    JSR   $C8D7
0C82-   C1 D4       CMP   ($D4,X)
0C84-   20 C9 D4    JSR   $D4C9
0C87-   D3          ???
0C88-   20 CE C1    JSR   $C1CE
0C8B-   CD C5 8D    CMP   $8DC5
0C8E-   AA          TAX
0C8F-   AA          TAX
0C90-   20 C9 CD    JSR   $CDC9
0C93-   D0 CC       BNE   $0C61
0C95-   C9 C5       CMP   #$C5
0C97-   D3          ???
0C98-   BA          TSX
0C99-   20 C9 D4    JSR   $D4C9
0C9C-   20 C6 C9    JSR   $C9C6
0C9F-   CC CC D3    CPY   $D3CC
0CA2-   20 C1 20    JSR   $20C1
0CA5-   C2          ???
0CA6-   CC CF C3    CPY   $C3CF
0CA9-   CB          ???
0CAA-   20 CF C6    JSR   $C6CF
0CAD-   20 CD C5    JSR   $C5CD
0CB0-   CD CF D2    CMP   $D2CF
0CB3-   D9 8D AA    CMP   $AA8D,Y
0CB6-   AA          TAX
0CB7-   20 D7 C9    JSR   $C9D7
0CBA-   D4          ???
0CBB-   C8          INY
0CBC-   20 C1 20    JSR   $20C1
0CBF-   D0 C1       BNE   $0C82
0CC1-   D2 D4       CMP   ($D4)
0CC3-   C9 C3       CMP   #$C3
0CC5-   D5 CC       CMP   $CC,X
0CC7-   C1 D2       CMP   ($D2,X)
0CC9-   20 C3 C8    JSR   $C8C3
0CCC-   C1 D2       CMP   ($D2,X)
0CCE-   C1 C3       CMP   ($C3,X)
0CD0-   D4          ???
0CD1-   C5 D2       CMP   $D2
0CD3-   AE 8D AA    LDX   $AA8D
0CD6-   8D A0 DF    STA   $DFA0
0CD9-   D0 D2       BNE   $0CAD
0CDB-   CE D4 A0    DEC   $A0D4
0CDE-   A2 20       LDX   #$20
0CE0-   A2 AC       LDX   #$AC
0CE2-   B8          CLV
0CE3-   C4 B8       CPY   $B8
0CE5-   C4 8D       CPY   $8D
0CE7-   A0 CD       LDY   #$CD
0CE9-   C6 C9       DEC   $C9
0CEB-   CC CC A0    CPY   $A0CC
0CEE-   A3          ???
0CEF-   A4 B3       LDY   $B3
0CF1-   B0 B0       BCS   $0CA3
0CF3-   BB          ???
0CF4-   A3          ???
0CF5-   B1 B0       LDA   ($B0),Y
0CF7-   BB          ???
0CF8-   A3          ???
0CF9-   B0 8D       BCS   $0C88
0CFB-   A0 DF       LDY   #$DF
0CFD-   D0 D2       BNE   $0CD1
0CFF-   CE D4 A0    DEC   $A0D4
0D02-   A2 CD       LDX   #$CD
0D04-   C6 C9       DEC   $C9
0D06-   CC CC 20    CPY   $20CC
0D09-   C6 C9       DEC   $C9
0D0B-   CC CC D3    CPY   $D3CC
0D0E-   20 C1 20    JSR   $20C1
0D11-   D0 CF       BNE   $0CE2
0D13-   D2 D4       CMP   ($D4)
0D15-   C9 CF       CMP   #$CF
0D17-   CE 20 CF    DEC   $CF20
0D1A-   C6 20       DEC   $20
0D1C-   CD C5 CD    CMP   $CDC5
0D1F-   CF          ???
0D20-   D2 D9       CMP   ($D9)
0D22-   20 D7 C9    JSR   $C9D7
0D25-   D4          ???
0D26-   C8          INY
0D27-   A2 AC       LDX   #$AC
0D29-   B8          CLV
0D2A-   C4 8D       CPY   $8D
0D2C-   A0 DF       LDY   #$DF
0D2E-   D0 D2       BNE   $0D02
0D30-   CE D4 A0    DEC   $A0D4
0D33-   A2 C1       LDX   #$C1
0D35-   20 D3 D0    JSR   $D0D3
0D38-   C5 C3       CMP   $C3
0D3A-   C9 C6       CMP   #$C6
0D3C-   C9 C5       CMP   #$C5
0D3E-   C4 20       CPY   $20
0D40-   D6 C1       DEC   $C1,X
0D42-   CC D5 C5    CPY   $C5D5
0D45-   AE 20 A2    LDX   $A220
0D48-   AC B8 C4    LDY   $C4B8
0D4B-   B8          CLV
0D4C-   C4 8D       CPY   $8D
0D4E-   A0 C4       LDY   #$C4
0D50-   D5 CD       CMP   $CD,X
0D52-   D0 A0       BNE   $0CF4
0D54-   A3          ???
0D55-   A4 B3       LDY   $B3
0D57-   B0 B0       BCS   $0D09
0D59-   BB          ???
0D5A-   A3          ???
0D5B-   B1 B0       LDA   ($B0),Y
0D5D-   8D A0 DF    STA   $DFA0
0D60-   D7          ???
0D61-   C1 C9       CMP   ($C9,X)
0D63-   D4          ???
0D64-   8D AA 8D    STA   $8DAA
0D67-   AA          TAX
0D68-   AA          TAX
0D69-   20 CD CD    JSR   $CDCD
0D6C-   CF          ???
0D6D-   D6 C5       DEC   $C5,X
0D6F-   20 C1 CC    JSR   $CCC1
0D72-   D3          ???
0D73-   CF          ???
0D74-   20 C4 CF    JSR   $CFC4
0D77-   C5 D3       CMP   $D3
0D79-   20 D7 C8    JSR   $C8D7
0D7C-   C1 D4       CMP   ($D4,X)
0D7E-   20 C9 D4    JSR   $D4C9
0D81-   20 D3 C1    JSR   $C1D3
0D84-   D9 D3 BA    CMP   $BAD3,Y
0D87-   20 C9 D4    JSR   $D4C9
0D8A-   20 CD CF    JSR   $CFCD
0D8D-   D6 C5       DEC   $C5,X
0D8F-   D3          ???
0D90-   8D AA AA    STA   $AAAA
0D93-   20 C1 20    JSR   $20C1
0D96-   C2          ???
0D97-   CC CF C3    CPY   $C3CF
0D9A-   CB          ???
0D9B-   20 CF C6    JSR   $C6CF
0D9E-   20 CD C5    JSR   $C5CD
0DA1-   CD CF D2    CMP   $D2CF
0DA4-   D9 20 C6    CMP   $C620,Y
0DA7-   D2 CF       CMP   ($CF)
0DA9-   CD 20 C1    CMP   $C120
0DAC-   20 D3 CF    JSR   $CFD3
0DAF-   D5 D2       CMP   $D2,X
0DB1-   C3          ???
0DB2-   C5 20       CMP   $20
0DB4-   CC CF C3    CPY   $C3CF
0DB7-   C1 D4       CMP   ($D4,X)
0DB9-   C9 CF       CMP   #$CF
0DBB-   CE 8D AA    DEC   $AA8D
0DBE-   AA          TAX
0DBF-   20 D4 CF    JSR   $CFD4
0DC2-   20 C1 20    JSR   $20C1
0DC5-   C4 C5       CPY   $C5
0DC7-   D3          ???
0DC8-   D4          ???
0DC9-   C9 CE       CMP   #$CE
0DCB-   C1 D4       CMP   ($D4,X)
0DCD-   C9 CF       CMP   #$CF
0DCF-   CE 20 CC    DEC   $CC20
0DD2-   CF          ???
0DD3-   C3          ???
0DD4-   C1 D4       CMP   ($D4,X)
0DD6-   C9 CF       CMP   #$CF
0DD8-   CE AE 20    DEC   $20AE
0DDB-   D7          ???
0DDC-   C5 A7       CMP   $A7
0DDE-   CC CC 20    CPY   $20CC
0DE1-   CE CF D7    DEC   $D7CF
0DE4-   20 CD CF    JSR   $CFCD
0DE7-   D6 C5       DEC   $C5,X
0DE9-   8D AA AA    STA   $AAAA
0DEC-   20 D4 C8    JSR   $C8D4
0DEF-   CF          ???
0DF0-   D3          ???
0DF1-   C5 20       CMP   $20
0DF3-   DA          PHX
0DF4-   C5 D2       CMP   $D2
0DF6-   CF          ???
0DF7-   C5 D3       CMP   $D3
0DF9-   20 D0 CC    JSR   $CCD0
0DFC-   C1 C3       CMP   ($C3,X)
0DFE-   C5 C4       CMP   $C4
0E00-   20 C2 D9    JSR   $D9C2
0E03-   20 CD C5    JSR   $C5CD
0E06-   CD C6 C9    CMP   $C9C6
0E09-   CC CC 20    CPY   $20CC
0E0C-   D4          ???
0E0D-   CF          ???
0E0E-   20 C1 CE    JSR   $CEC1
0E11-   CF          ???
0E12-   D4          ???
0E13-   C8          INY
0E14-   C5 D2       CMP   $D2
0E16-   8D AA AA    STA   $AAAA
0E19-   20 CC CF    JSR   $CFCC
0E1C-   C3          ???
0E1D-   C1 D4       CMP   ($D4,X)
0E1F-   C9 CF       CMP   #$CF
0E21-   CE AE 8D    DEC   $8DAE
0E24-   AA          TAX
0E25-   8D A0 DF    STA   $DFA0
0E28-   D0 D2       BNE   $0DFC
0E2A-   CE D4 A0    DEC   $A0D4
0E2D-   A2 20       LDX   #$20
0E2F-   A2 AC       LDX   #$AC
0E31-   B8          CLV
0E32-   C4 B8       CPY   $B8
0E34-   C4 8D       CPY   $8D
0E36-   A0 DF       LDY   #$DF
0E38-   D0 D2       BNE   $0E0C
0E3A-   CE D4 A0    DEC   $A0D4
0E3D-   A2 CD       LDX   #$CD
0E3F-   CD CF D6    CMP   $D6CF
0E42-   C5 20       CMP   $20
0E44-   C3          ???
0E45-   CF          ???
0E46-   D0 C9       BNE   $0E11
0E48-   C5 D3       CMP   $D3
0E4A-   20 C1 20    JSR   $20C1
0E4D-   D3          ???
0E4E-   D0 C1       BNE   $0E11
0E50-   CE 20 CF    DEC   $CF20
0E53-   C6 20       DEC   $20
0E55-   CD C5 CD    CMP   $CDC5
0E58-   CF          ???
0E59-   D2 D9       CMP   ($D9)
0E5B-   A2 AC       LDX   #$AC
0E5D-   B8          CLV
0E5E-   C4 8D       CPY   $8D
0E60-   A0 DF       LDY   #$DF
0E62-   D0 D2       BNE   $0E36
0E64-   CE D4 A0    DEC   $A0D4
0E67-   A2 C6       LDX   #$C6
0E69-   D2 CF       CMP   ($CF)
0E6B-   CD 20 C1    CMP   $C120
0E6E-   20 D3 CF    JSR   $CFD3
0E71-   D5 D2       CMP   $D2,X
0E73-   C3          ???
0E74-   C5 20       CMP   $20
0E76-   D4          ???
0E77-   CF          ???
0E78-   20 C1 20    JSR   $20C1
0E7B-   C4 C5       CPY   $C5
0E7D-   D3          ???
0E7E-   D4          ???
0E7F-   C9 CE       CMP   #$CE
0E81-   C1 D4       CMP   ($D4,X)
0E83-   C9 CF       CMP   #$CF
0E85-   CE 20 C1    DEC   $C120
0E88-   C4 C4       CPY   $C4
0E8A-   D2 C5       CMP   ($C5)
0E8C-   D3          ???
0E8D-   D3          ???
0E8E-   AE A2 AC    LDX   $ACA2
0E91-   B8          CLV
0E92-   C4 B8       CPY   $B8
0E94-   C4 8D       CPY   $8D
0E96-   A0 DF       LDY   #$DF
0E98-   D0 D2       BNE   $0E6C
0E9A-   CE D4 A0    DEC   $A0D4
0E9D-   A2 D3       LDX   #$D3
0E9F-   CF          ???
0EA0-   20 CD CF    JSR   $CFCD
0EA3-   D6 C9       DEC   $C9,X
0EA5-   CE C7 20    DEC   $20C7
0EA8-   A4 B3       LDY   $B3
0EAA-   B0 B0       BCS   $0E5C
0EAC-   20 D4 CF    JSR   $CFD4
0EAF-   20 A4 B3    JSR   $B3A4
0EB2-   B2 B0       LDA   ($B0)
0EB4-   20 D2 C5    JSR   $C5D2
0EB7-   D3          ???
0EB8-   D5 CC       CMP   $CC,X
0EBA-   D4          ???
0EBB-   D3          ???
0EBC-   20 C9 CE    JSR   $CEC9
0EBF-   BA          TSX
0EC0-   A2 AC       LDX   #$AC
0EC2-   B8          CLV
0EC3-   C4 B8       CPY   $B8
0EC5-   C4 8D       CPY   $8D
0EC7-   A0 CD       LDY   #$CD
0EC9-   CD CF D6    CMP   $D6CF
0ECC-   C5 A0       CMP   $A0
0ECE-   A3          ???
0ECF-   A4 B3       LDY   $B3
0ED1-   B0 B0       BCS   $0E83
0ED3-   BB          ???
0ED4-   A3          ???
0ED5-   A4 B3       LDY   $B3
0ED7-   B2 B0       LDA   ($B0)
0ED9-   BB          ???
0EDA-   A3          ???
0EDB-   B1 B0       LDA   ($B0),Y
0EDD-   8D A0 C4    STA   $C4A0
0EE0-   D5 CD       CMP   $CD,X
0EE2-   D0 A0       BNE   $0E84
0EE4-   A3          ???
0EE5-   A4 B3       LDY   $B3
0EE7-   B2 B0       LDA   ($B0)
0EE9-   BB          ???
0EEA-   A3          ???
0EEB-   B1 B0       LDA   ($B0),Y
0EED-   8D A0 DF    STA   $DFA0
0EF0-   D7          ???
0EF1-   C1 C9       CMP   ($C9,X)
0EF3-   D4          ???
0EF4-   8D AA 8D    STA   $8DAA
0EF7-   AA          TAX
0EF8-   AA          TAX
0EF9-   20 C4 C5    JSR   $C5C4
0EFC-   CC C1 D9    CPY   $D9C1
0EFF-   20 D2 D5    JSR   $D5D2
0F02-   CE D3 20    DEC   $20D3
0F05-   D4          ???
0F06-   C8          INY
0F07-   D2 CF       CMP   ($CF)
0F09-   D5 C7       CMP   $C7,X
0F0B-   C8          INY
0F0C-   20 C3 D9    JSR   $D9C3
0F0F-   C3          ???
0F10-   CC C5 D3    CPY   $D3C5
0F13-   20 CF C6    JSR   $C6CF
0F16-   20 D4 C8    JSR   $C8D4
0F19-   C5 8D       CMP   $8D
0F1B-   AA          TAX
0F1C-   AA          TAX
0F1D-   20 B6 B5    JSR   $B5B6
0F20-   B0 B2       BCS   $0ED4
0F22-   20 D5 CE    JSR   $CED5
0F25-   D4          ???
0F26-   C9 CC       CMP   #$CC
0F28-   20 C1 20    JSR   $20C1
0F2B-   C3          ???
0F2C-   C5 D2       CMP   $D2
0F2E-   D4          ???
0F2F-   C1 C9       CMP   ($C9,X)
0F31-   CE 20 C1    DEC   $C120
0F34-   CD CF D5    CMP   $D5CF
0F37-   CE D4 20    DEC   $20D4
0F3A-   CF          ???
0F3B-   C6 20       DEC   $20
0F3D-   D4          ???
0F3E-   C9 CD       CMP   #$CD
0F40-   C5 8D       CMP   $8D
0F42-   AA          TAX
0F43-   AA          TAX
0F44-   20 C8 C1    JSR   $C1C8
0F47-   D3          ???
0F48-   20 D0 C1    JSR   $C1D0
0F4B-   D3          ???
0F4C-   D3          ???
0F4D-   C5 C4       CMP   $C4
0F4F-   AE 8D AA    LDX   $AA8D
0F52-   8D A0 DF    STA   $DFA0
0F55-   D0 D2       BNE   $0F29
0F57-   CE D4 A0    DEC   $A0D4
0F5A-   A2 20       LDX   #$20
0F5C-   A2 AC       LDX   #$AC
0F5E-   B8          CLV
0F5F-   C4 B8       CPY   $B8
0F61-   C4 8D       CPY   $8D
0F63-   A0 DF       LDY   #$DF
0F65-   D0 D2       BNE   $0F39
0F67-   CE D4 A0    DEC   $A0D4
0F6A-   A2 C4       LDX   #$C4
0F6C-   C5 CC       CMP   $CC
0F6E-   C1 D9       CMP   ($D9,X)
0F70-   20 C4 C5    JSR   $C5C4
0F73-   CC C1 D9    CPY   $D9C1
0F76-   D3          ???
0F77-   20 C1 20    JSR   $20C1
0F7A-   D3          ???
0F7B-   D0 C5       BNE   $0F42
0F7D-   C3          ???
0F7E-   C9 C6       CMP   #$C6
0F80-   C9 C5       CMP   #$C5
0F82-   C4 20       CPY   $20
0F84-   CE D5 CD    DEC   $CDD5
0F87-   C2          ???
0F88-   C5 D2       CMP   $D2
0F8A-   20 CF C6    JSR   $C6CF
0F8D-   A2 AC       LDX   #$AC
0F8F-   B8          CLV
0F90-   C4 8D       CPY   $8D
0F92-   A0 DF       LDY   #$DF
0F94-   D0 D2       BNE   $0F68
0F96-   CE D4 A0    DEC   $A0D4
0F99-   A2 CD       LDX   #$CD
0F9B-   C9 CC       CMP   #$CC
0F9D-   CC C9 D3    CPY   $D3C9
0FA0-   C5 C3       CMP   $C3
0FA2-   CF          ???
0FA3-   CE C4 D3    DEC   $D3C4
0FA6-   AE 20 B2    LDX   $B220
0FA9-   B5 B0       LDA   $B0,X
0FAB-   20 CD C9    JSR   $C9CD
0FAE-   CC CC C9    CPY   $C9CC
0FB1-   D3          ???
0FB2-   C5 C3       CMP   $C3
0FB4-   CF          ???
0FB5-   CE C4 D3    DEC   $D3C4
0FB8-   20 BD 20    JSR   $20BD
0FBB-   B1 AF       LDA   ($AF),Y
0FBD-   B4 20       LDY   $20,X
0FBF-   D3          ???
0FC0-   C5 C3       CMP   $C3
0FC2-   CF          ???
0FC3-   CE C4 AE    DEC   $AEC4
0FC6-   A2 AC       LDX   #$AC
0FC8-   B8          CLV
0FC9-   C4 B8       CPY   $B8
0FCB-   C4 8D       CPY   $8D
0FCD-   AA          TAX
0FCE-   8D A0 C4    STA   $C4A0
0FD1-   C5 CC       CMP   $CC
0FD3-   C1 D9       CMP   ($D9,X)
0FD5-   A0 A3       LDY   #$A3
0FD7-   B2 B5       LDA   ($B5)
0FD9-   B0 A0       BCS   $0F7B
0FDB-   BB          ???
0FDC-   20 20 D4    JSR   $D420
0FDF-   C9 CD       CMP   #$CD
0FE1-   C5 20       CMP   $20
0FE3-   C9 CE       CMP   #$CE
0FE5-   20 CD C9    JSR   $C9CD
0FE8-   CC CC C9    CPY   $C9CC
0FEB-   D3          ???
0FEC-   C5 C3       CMP   $C3
0FEE-   CF          ???
0FEF-   CE C4 D3    DEC   $D3C4
0FF2-   8D BB 20    STA   $20BB
0FF5-   C9 D3       CMP   #$D3
0FF7-   20 D0 C1    JSR   $C1D0
0FFA-   D3          ???
0FFB-   D3          ???
0FFC-   C5 C4       CMP   $C4
0FFE-   20 D6 C9    JSR   $C9D6
1001-   C1 20       CMP   ($20,X)
1003-   D9 8D BB    CMP   $BB8D,Y
1006-   20 B2 B5    JSR   $B5B2
1009-   B0 20       BCS   $102B
100B-   BD 20 B1    LDA   $B120,X
100E-   AF          ???
100F-   B4 20       LDY   $20,X
1011-   D3          ???
1012-   C5 C3       CMP   $C3
1014-   CF          ???
1015-   CE C4 8D    DEC   $8DC4
1018-   A0 C2       LDY   #$C2
101A-   C5 C5       CMP   $C5
101C-   D0 A0       BNE   $0FBE
101E-   B1 8D       LDA   ($8D),Y
1020-   A0 DF       LDY   #$DF
1022-   D0 D2       BNE   $0FF6
1024-   CE D4 A0    DEC   $A0D4
1027-   A2 B1       LDX   #$B1
1029-   AF          ???
102A-   B4 20       LDY   $20,X
102C-   D3          ???
102D-   C5 C3       CMP   $C3
102F-   CF          ???
1030-   CE C4 A2    DEC   $A2C4
1033-   AC B8 C4    LDY   $C4B8
1036-   8D A0 C4    STA   $C4A0
1039-   C5 CC       CMP   $CC
103B-   C1 D9       CMP   ($D9,X)
103D-   A0 A3       LDY   #$A3
103F-   B2 B5       LDA   ($B5)
1041-   B0 8D       BCS   $0FD0
1043-   A0 C2       LDY   #$C2
1045-   C5 C5       CMP   $C5
1047-   D0 A0       BNE   $0FE9
1049-   B2 8D       LDA   ($8D)
104B-   A0 DF       LDY   #$DF
104D-   D0 D2       BNE   $1021
104F-   CE D4 A0    DEC   $A0D4
1052-   A2 B1       LDX   #$B1
1054-   AF          ???
1055-   B4 20       LDY   $20,X
1057-   D3          ???
1058-   C5 C3       CMP   $C3
105A-   CF          ???
105B-   CE C4 A2    DEC   $A2C4
105E-   AC B8 C4    LDY   $C4B8
1061-   8D A0 C4    STA   $C4A0
1064-   C5 CC       CMP   $CC
1066-   C1 D9       CMP   ($D9,X)
1068-   A0 A3       LDY   #$A3
106A-   B2 B5       LDA   ($B5)
106C-   B0 8D       BCS   $0FFB
106E-   A0 C2       LDY   #$C2
1070-   C5 C5       CMP   $C5
1072-   D0 A0       BNE   $1014
1074-   B3          ???
1075-   8D A0 DF    STA   $DFA0
1078-   D0 D2       BNE   $104C
107A-   CE D4 A0    DEC   $A0D4
107D-   A2 B1       LDX   #$B1
107F-   AF          ???
1080-   B4 20       LDY   $20,X
1082-   D3          ???
1083-   C5 C3       CMP   $C3
1085-   CF          ???
1086-   CE C4 A2    DEC   $A2C4
1089-   AC B8 C4    LDY   $C4B8
108C-   8D A0 C4    STA   $C4A0
108F-   C5 CC       CMP   $CC
1091-   C1 D9       CMP   ($D9,X)
1093-   A0 A3       LDY   #$A3
1095-   B2 B5       LDA   ($B5)
1097-   B0 8D       BCS   $1026
1099-   A0 C2       LDY   #$C2
109B-   C5 C5       CMP   $C5
109D-   D0 A0       BNE   $103F
109F-   B4 8D       LDY   $8D,X
10A1-   A0 DF       LDY   #$DF
10A3-   D0 D2       BNE   $1077
10A5-   CE D4 A0    DEC   $A0D4
10A8-   A2 B1       LDX   #$B1
10AA-   AF          ???
10AB-   B4 20       LDY   $20,X
10AD-   D3          ???
10AE-   C5 C3       CMP   $C3
10B0-   CF          ???
10B1-   CE C4 A2    DEC   $A2C4
10B4-   AC B8 C4    LDY   $C4B8
10B7-   8D AA 8D    STA   $8DAA
10BA-   A0 DF       LDY   #$DF
10BC-   D0 D2       BNE   $1090
10BE-   CE D4 A0    DEC   $A0D4
10C1-   A2 20       LDX   #$20
10C3-   A2 AC       LDX   #$AC
10C5-   B8          CLV
10C6-   C4 B8       CPY   $B8
10C8-   C4 8D       CPY   $8D
10CA-   A0 DF       LDY   #$DF
10CC-   D7          ???
10CD-   C1 C9       CMP   ($C9,X)
10CF-   D4          ???
10D0-   8D AA 8D    STA   $8DAA
10D3-   AA          TAX
10D4-   AA          TAX
10D5-   20 DA D3    JSR   $D3DA
10D8-   C1 D6       CMP   ($D6,X)
10DA-   C5 20       CMP   $20
10DC-   C2          ???
10DD-   C1 C3       CMP   ($C3,X)
10DF-   CB          ???
10E0-   D3          ???
10E1-   20 D5 D0    JSR   $D0D5
10E4-   20 D4 C8    JSR   $C8D4
10E7-   C5 20       CMP   $20
10E9-   A2 C6       LDX   #$C6
10EB-   D2 C5       CMP   ($C5)
10ED-   C5 A2       CMP   $A2
10EF-   20 C1 D2    JSR   $D2C1
10F2-   C5 C1       CMP   $C1
10F4-   D3          ???
10F5-   20 CF C6    JSR   $C6CF
10F8-   8D AA AA    STA   $AAAA
10FB-   20 D4 C8    JSR   $C8D4
10FE-   C5 20       CMP   $20
1100-   DA          PHX
1101-   C5 D2       CMP   $D2
1103-   CF          ???
1104-   20 D0 C1    JSR   $C1D0
1107-   C7          ???
1108-   C5 20       CMP   $20
110A-   D4          ???
110B-   CF          ???
110C-   20 C1 CE    JSR   $CEC1
110F-   20 C1 CC    JSR   $CCC1
1112-   D4          ???
1113-   C5 D2       CMP   $D2
1115-   CE C1 D4    DEC   $D4C1
1118-   C5 20       CMP   $20
111A-   CD C5 CD    CMP   $CDC5
111D-   CF          ???
111E-   D2 D9       CMP   ($D9)
1120-   8D AA AA    STA   $AAAA
1123-   20 CC CF    JSR   $CFCC
1126-   C3          ???
1127-   C1 D4       CMP   ($D4,X)
1129-   C9 CF       CMP   #$CF
112B-   CE AE 20    DEC   $20AE
112E-   D4          ???
112F-   C8          INY
1130-   C9 D3       CMP   #$D3
1132-   20 C9 D3    JSR   $D3C9
1135-   20 CD CF    JSR   $CFCD
1138-   D3          ???
1139-   D4          ???
113A-   CC D9 20    CPY   $20D9
113D-   D5 D3       CMP   $D3,X
113F-   C5 C6       CMP   $C6
1141-   D5 CC       CMP   $CC,X
1143-   20 D7 C8    JSR   $C8D7
1146-   C5 CE       CMP   $CE
1148-   8D AA AA    STA   $AAAA
114B-   20 D9 CF    JSR   $CFD9
114E-   D5 20       CMP   $20,X
1150-   CB          ???
1151-   CE CF D7    DEC   $D7CF
1154-   20 C1 20    JSR   $20C1
1157-   D2 CF       CMP   ($CF)
1159-   D5 D4       CMP   $D4,X
115B-   C9 CE       CMP   #$CE
115D-   C5 20       CMP   $20
115F-   D5 D3       CMP   $D3,X
1161-   C5 D3       CMP   $D3
1163-   20 D4 C8    JSR   $C8D4
1166-   C5 20       CMP   $20
1168-   DA          PHX
1169-   C5 D2       CMP   $D2
116B-   CF          ???
116C-   20 D0 C1    JSR   $C1D0
116F-   C7          ???
1170-   C5 AC       CMP   $AC
1172-   8D AA AA    STA   $AAAA
1175-   20 C2 D5    JSR   $D5C2
1178-   D4          ???
1179-   20 D9 CF    JSR   $CFD9
117C-   D5 20       CMP   $20,X
117E-   D7          ???
117F-   C1 CE       CMP   ($CE,X)
1181-   D4          ???
1182-   20 D4 CF    JSR   $CFD4
1185-   20 CB C5    JSR   $C5CB
1188-   C5 D0       CMP   $D0
118A-   20 D4 C8    JSR   $C8D4
118D-   C5 20       CMP   $20
118F-   D6 C1       DEC   $C1,X
1191-   CC D5 C5    CPY   $C5D5
1194-   D3          ???
1195-   20 C3 D5    JSR   $D5C3
1198-   D2 D2       CMP   ($D2)
119A-   C5 CE       CMP   $CE
119C-   D4          ???
119D-   CC D9 8D    CPY   $8DD9
11A0-   AA          TAX
11A1-   AA          TAX
11A2-   20 D3 D4    JSR   $D4D3
11A5-   CF          ???
11A6-   D2 C5       CMP   ($C5)
11A8-   C4 20       CPY   $20
11AA-   D4          ???
11AB-   C8          INY
11AC-   C5 D2       CMP   $D2
11AE-   C5 20       CMP   $20
11B0-   C1 C6       CMP   ($C6,X)
11B2-   D4          ???
11B3-   C5 D2       CMP   $D2
11B5-   20 C3 C1    JSR   $C1C3
11B8-   CC CC C9    CPY   $C9CC
11BB-   CE C7 20    DEC   $20C7
11BE-   D4          ???
11BF-   C8          INY
11C0-   C5 20       CMP   $20
11C2-   D2 CF       CMP   ($CF)
11C4-   D5 D4       CMP   $D4,X
11C6-   C9 CE       CMP   #$CE
11C8-   C5 AE       CMP   $AE
11CA-   8D AA 8D    STA   $8DAA
11CD-   AA          TAX
11CE-   AA          TAX
11CF-   20 CE CF    JSR   $CFCE
11D2-   D4          ???
11D3-   C5 20       CMP   $20
11D5-   D4          ???
11D6-   C8          INY
11D7-   C1 D4       CMP   ($D4,X)
11D9-   20 D3 C9    JSR   $C9D3
11DC-   CE C3 C5    DEC   $C5C3
11DF-   20 D4 C8    JSR   $C8D4
11E2-   C5 20       CMP   $20
11E4-   CC C9 C2    CPY   $C2C9
11E7-   D2 C1       CMP   ($C1)
11E9-   D2 D9       CMP   ($D9)
11EB-   20 CD C1    JSR   $C1CD
11EE-   CB          ???
11EF-   C5 D3       CMP   $D3
11F1-   20 C8 C5    JSR   $C5C8
11F4-   C1 D6       CMP   ($D6,X)
11F6-   D9 20 D5    CMP   $D520,Y
11F9-   D3          ???
11FA-   C5 8D       CMP   $8D
11FC-   AA          TAX
11FD-   AA          TAX
11FE-   20 CF C6    JSR   $C6CF
1201-   20 D4 C8    JSR   $C8D4
1204-   C5 D3       CMP   $D3
1206-   C5 20       CMP   $20
1208-   CD C5 CD    CMP   $CDC5
120B-   CF          ???
120C-   D2 D9       CMP   ($D9)
120E-   20 C1 C4    JSR   $C4C1
1211-   C4 D2       CPY   $D2
1213-   C5 D3       CMP   $D3
1215-   D3          ???
1216-   C5 D3       CMP   $D3
1218-   AC 20 C1    LDY   $C120
121B-   CE D9 20    DEC   $20D9
121E-   D4          ???
121F-   C9 CD       CMP   #$CD
1221-   C5 20       CMP   $20
1223-   D9 CF D5    CMP   $D5CF,Y
1226-   D2 20       CMP   ($20)
1228-   C3          ???
1229-   CF          ???
122A-   C4 C5       CPY   $C5
122C-   8D AA AA    STA   $AAAA
122F-   20 CD C1    JSR   $C1CD
1232-   CB          ???
1233-   C5 D3       CMP   $D3
1235-   20 D5 D3    JSR   $D3D5
1238-   C5 20       CMP   $20
123A-   CF          ???
123B-   C6 20       DEC   $20
123D-   D4          ???
123E-   C8          INY
123F-   C5 20       CMP   $20
1241-   DA          PHX
1242-   C5 D2       CMP   $D2
1244-   CF          ???
1245-   20 D0 C1    JSR   $C1D0
1248-   C7          ???
1249-   C5 AC       CMP   $AC
124B-   20 C9 D4    JSR   $D4C9
124E-   20 C9 D3    JSR   $D3C9
1251-   20 C1 C4    JSR   $C4C1
1254-   D6 C9       DEC   $C9,X
1256-   D3          ???
1257-   C5 C4       CMP   $C4
1259-   20 D4 CF    JSR   $CFD4
125C-   8D AA AA    STA   $AAAA
125F-   20 D3 C1    JSR   $C1D3
1262-   D6 C5       DEC   $C5,X
1264-   20 D4 C8    JSR   $C8D4
1267-   C5 20       CMP   $20
1269-   D3          ???
126A-   D4          ???
126B-   C1 D4       CMP   ($D4,X)
126D-   C5 20       CMP   $20
126F-   C2          ???
1270-   C5 C6       CMP   $C6
1272-   CF          ???
1273-   D2 C5       CMP   ($C5)
1275-   20 C3 C1    JSR   $C1C3
1278-   CC CC C9    CPY   $C9CC
127B-   CE C7 20    DEC   $20C7
127E-   C1 CE       CMP   ($CE,X)
1280-   D9 20 CF    CMP   $CF20,Y
1283-   D4          ???
1284-   C8          INY
1285-   C5 D2       CMP   $D2
1287-   20 D2 CF    JSR   $CFD2
128A-   D5 D4       CMP   $D4,X
128C-   C9 CE       CMP   #$CE
128E-   C5 D3       CMP   $D3
1290-   AE 8D AA    LDX   $AA8D
1293-   8D A0 CC    STA   $CCA0
1296-   C4 C1       CPY   $C1
1298-   A0 A3       LDY   #$A3
129A-   B0 B1       BCS   $124D
129C-   8D A0 D3    STA   $D3A0
129F-   D4          ???
12A0-   C1 A0       CMP   ($A0,X)
12A2-   A4 B0       LDY   $B0
12A4-   B6 8D       LDX   $8D,Y
12A6-   A0 CC       LDY   #$CC
12A8-   C4 C1       CPY   $C1
12AA-   A0 A3       LDY   #$A3
12AC-   B0 B2       BCS   $1260
12AE-   8D A0 D3    STA   $D3A0
12B1-   D4          ???
12B2-   C1 A0       CMP   ($A0,X)
12B4-   A4 B0       LDY   $B0
12B6-   B7          ???
12B7-   8D A0 CC    STA   $CCA0
12BA-   C4 C1       CPY   $C1
12BC-   A0 A3       LDY   #$A3
12BE-   B0 B3       BCS   $1273
12C0-   8D A0 D3    STA   $D3A0
12C3-   D4          ???
12C4-   C1 A0       CMP   ($A0,X)
12C6-   A4 B0       LDY   $B0
12C8-   B8          CLV
12C9-   8D A0 CC    STA   $CCA0
12CC-   C4 C1       CPY   $C1
12CE-   A0 A3       LDY   #$A3
12D0-   B0 B4       BCS   $1286
12D2-   8D A0 D3    STA   $D3A0
12D5-   D4          ???
12D6-   C1 A0       CMP   ($A0,X)
12D8-   A4 B0       LDY   $B0
12DA-   B9 8D A0    LDA   $A08D,Y
12DD-   DA          PHX
12DE-   D3          ???
12DF-   C1 D6       CMP   ($D6,X)
12E1-   C5 A0       CMP   $A0
12E3-   A3          ???
12E4-   A4 B3       LDY   $B3
12E6-   B0 B0       BCS   $1298
12E8-   8D AA 8D    STA   $8DAA
12EB-   A0 DF       LDY   #$DF
12ED-   D0 D2       BNE   $12C1
12EF-   CE D4 A0    DEC   $A0D4
12F2-   A2 20       LDX   #$20
12F4-   A2 AC       LDX   #$AC
12F6-   B8          CLV
12F7-   C4 B8       CPY   $B8
12F9-   C4 8D       CPY   $8D
12FB-   A0 DF       LDY   #$DF
12FD-   D0 D2       BNE   $12D1
12FF-   CE D4 A0    DEC   $A0D4
1302-   A2 DA       LDX   #$DA
1304-   D3          ???
1305-   C1 D6       CMP   ($D6,X)
1307-   C5 20       CMP   $20
1309-   D3          ???
130A-   C1 D6       CMP   ($D6,X)
130C-   C5 D3       CMP   $D3
130E-   20 D4 C8    JSR   $C8D4
1311-   C5 20       CMP   $20
1313-   D3          ???
1314-   D4          ???
1315-   C1 D4       CMP   ($D4,X)
1317-   C5 20       CMP   $20
1319-   CF          ???
131A-   C6 20       DEC   $20
131C-   D4          ???
131D-   C8          INY
131E-   C5 20       CMP   $20
1320-   DA          PHX
1321-   C5 D2       CMP   $D2
1323-   CF          ???
1324-   20 D0 C1    JSR   $C1D0
1327-   C7          ???
1328-   C5 20       CMP   $20
132A-   A2 AC       LDX   #$AC
132C-   B8          CLV
132D-   C4 8D       CPY   $8D
132F-   A0 DF       LDY   #$DF
1331-   D0 D2       BNE   $1305
1333-   CE D4 A0    DEC   $A0D4
1336-   A2 C1       LDX   #$C1
1338-   C4 C4       CPY   $C4
133A-   D2 C5       CMP   ($C5)
133C-   D3          ???
133D-   D3          ???
133E-   C5 D3       CMP   $D3
1340-   20 D4 C8    JSR   $C8D4
1343-   C1 D4       CMP   ($D4,X)
1345-   20 C1 D2    JSR   $D2C1
1348-   C5 20       CMP   $20
134A-   CE CF D4    DEC   $D4CF
134D-   20 D5 D3    JSR   $D3D5
1350-   C5 C4       CMP   $C4
1352-   20 C2 D9    JSR   $D9C2
1355-   20 C4 CF    JSR   $CFC4
1358-   D3          ???
1359-   AC A2 AC    LDY   $ACA2
135C-   B8          CLV
135D-   C4 8D       CPY   $8D
135F-   A0 DF       LDY   #$DF
1361-   D0 D2       BNE   $1335
1363-   CE D4 A0    DEC   $A0D4
1366-   A2 C1       LDX   #$C1
1368-   D0 D0       BNE   $133A
136A-   CC C5 D3    CPY   $D3C5
136D-   CF          ???
136E-   C6 D4       DEC   $D4
1370-   AC D0 D2    LDY   $D2D0
1373-   CF          ???
1374-   C4 CF       CPY   $CF
1376-   D3          ???
1377-   20 CF D2    JSR   $D2CF
137A-   20 C9 CE    JSR   $CEC9
137D-   D4          ???
137E-   C5 C7       CMP   $C7
1380-   C5 D2       CMP   $D2
1382-   20 C2 C1    JSR   $C1C2
1385-   D3          ???
1386-   C9 C3       CMP   #$C3
1388-   AE A2 AC    LDX   $ACA2
138B-   B8          CLV
138C-   C4 B8       CPY   $B8
138E-   C4 8D       CPY   $8D
1390-   A0 DF       LDY   #$DF
1392-   D0 D2       BNE   $1366
1394-   CE D4 A0    DEC   $A0D4
1397-   A2 D3       LDX   #$D3
1399-   CF          ???
139A-   20 D4 C8    JSR   $C8D4
139D-   C5 20       CMP   $20
139F-   C2          ???
13A0-   C1 C3       CMP   ($C3,X)
13A2-   CB          ???
13A3-   C5 C4       CMP   $C4
13A5-   20 D5 D0    JSR   $D0D5
13A8-   20 DA C5    JSR   $C5DA
13AB-   D2 CF       CMP   ($CF)
13AD-   20 D0 C1    JSR   $C1D0
13B0-   C7          ???
13B1-   C5 20       CMP   $20
13B3-   C1 D4       CMP   ($D4,X)
13B5-   20 A4 B3    JSR   $B3A4
13B8-   B0 B0       BCS   $136A
13BA-   20 C9 D3    JSR   $D3C9
13BD-   BA          TSX
13BE-   A2 AC       LDX   #$AC
13C0-   B8          CLV
13C1-   C4 B8       CPY   $B8
13C3-   C4 8D       CPY   $8D
13C5-   A0 C4       LDY   #$C4
13C7-   D5 CD       CMP   $CD,X
13C9-   D0 A0       BNE   $136B
13CB-   A3          ???
13CC-   A4 B3       LDY   $B3
13CE-   B0 B0       BCS   $1380
13D0-   BB          ???
13D1-   A3          ???
13D2-   B1 B8       LDA   ($B8),Y
13D4-   8D A0 DF    STA   $DFA0
13D7-   D0 D2       BNE   $13AB
13D9-   CE D4 A0    DEC   $A0D4
13DC-   A2 20       LDX   #$20
13DE-   A2 AC       LDX   #$AC
13E0-   B8          CLV
13E1-   C4 B8       CPY   $B8
13E3-   C4 8D       CPY   $8D
13E5-   A0 DF       LDY   #$DF
13E7-   D0 D2       BNE   $13BB
13E9-   CE D4 A0    DEC   $A0D4
13EC-   A2 B1       LDX   #$B1
13EE-   B8          CLV
13EF-   20 C2 D9    JSR   $D9C2
13F2-   D4          ???
13F3-   C5 D3       CMP   $D3
13F5-   20 C1 D2    JSR   $D2C1
13F8-   C5 20       CMP   $20
13FA-   D5 D3       CMP   $D3,X
13FC-   C5 C4       CMP   $C4
13FE-   AE A2 AC    LDX   $ACA2
1401-   B8          CLV
1402-   C4 B8       CPY   $B8
1404-   C4 8D       CPY   $8D
1406-   A0 DF       LDY   #$DF
1408-   D7          ???
1409-   C1 C9       CMP   ($C9,X)
140B-   D4          ???
140C-   8D AA 8D    STA   $8DAA
140F-   AA          TAX
1410-   AA          TAX
1411-   20 D9 CF    JSR   $CFD9
1414-   D5 20       CMP   $20,X
1416-   C3          ???
1417-   C1 CE       CMP   ($CE,X)
1419-   20 D2 C5    JSR   $C5D2
141C-   D3          ???
141D-   D4          ???
141E-   CF          ???
141F-   D2 C5       CMP   ($C5)
1421-   20 D4 C8    JSR   $C8D4
1424-   C5 20       CMP   $20
1426-   DA          PHX
1427-   C5 D2       CMP   $D2
1429-   CF          ???
142A-   20 D0 C1    JSR   $C1D0
142D-   C7          ???
142E-   C5 20       CMP   $20
1430-   D4          ???
1431-   CF          ???
1432-   20 C9 D4    JSR   $D4C9
1435-   D3          ???
1436-   8D AA AA    STA   $AAAA
1439-   20 D0 D2    JSR   $D2D0
143C-   C9 CF       CMP   #$CF
143E-   D2 20       CMP   ($20)
1440-   D3          ???
1441-   D4          ???
1442-   C1 D4       CMP   ($D4,X)
1444-   C5 20       CMP   $20
1446-   C2          ???
1447-   D9 20 D4    CMP   $D420,Y
144A-   C8          INY
144B-   C5 CE       CMP   $CE
144D-   20 C3 C1    JSR   $C1C3
1450-   CC CC C9    CPY   $C9CC
1453-   CE C7 20    DEC   $20C7
1456-   DA          PHX
1457-   CC CF C1    CPY   $C1CF
145A-   C4 AE       CPY   $AE
145C-   8D AA 8D    STA   $8DAA
145F-   A0 DA       LDY   #$DA
1461-   CC CF C1    CPY   $C1CF
1464-   C4 A0       CPY   $A0
1466-   A3          ???
1467-   A4 B3       LDY   $B3
1469-   B0 B0       BCS   $141B
146B-   8D AA 8D    STA   $8DAA
146E-   A0 DF       LDY   #$DF
1470-   D0 D2       BNE   $1444
1472-   CE D4 A0    DEC   $A0D4
1475-   A2 20       LDX   #$20
1477-   A2 AC       LDX   #$AC
1479-   B8          CLV
147A-   C4 B8       CPY   $B8
147C-   C4 8D       CPY   $8D
147E-   A0 DF       LDY   #$DF
1480-   D0 D2       BNE   $1454
1482-   CE D4 A0    DEC   $A0D4
1485-   A2 D9       LDX   #$D9
1487-   CF          ???
1488-   D5 20       CMP   $20,X
148A-   C3          ???
148B-   C1 CE       CMP   ($CE,X)
148D-   20 D4 C8    JSR   $C8D4
1490-   C5 CE       CMP   $CE
1492-   20 D2 C5    JSR   $C5D2
1495-   D3          ???
1496-   D4          ???
1497-   CF          ???
1498-   D2 C5       CMP   ($C5)
149A-   20 D4 C8    JSR   $C8D4
149D-   C5 20       CMP   $20
149F-   C6 D2       DEC   $D2
14A1-   C5 C5       CMP   $C5
14A3-   20 DA C5    JSR   $C5DA
14A6-   D2 CF       CMP   ($CF)
14A8-   20 D0 C1    JSR   $C1D0
14AB-   C7          ???
14AC-   C5 A2       CMP   $A2
14AE-   AC B8 C4    LDY   $C4B8
14B1-   8D A0 DF    STA   $DFA0
14B4-   D0 D2       BNE   $1488
14B6-   CE D4 A0    DEC   $A0D4
14B9-   A2 CC       LDX   #$CC
14BB-   CF          ???
14BC-   C3          ???
14BD-   C1 D4       CMP   ($D4,X)
14BF-   C9 CF       CMP   #$CF
14C1-   CE D3 20    DEC   $20D3
14C4-   D7          ???
14C5-   C9 D4       CMP   #$D4
14C7-   C8          INY
14C8-   20 DA CC    JSR   $CCDA
14CB-   CF          ???
14CC-   C1 C4       CMP   ($C4,X)
14CE-   AE 20 D4    LDX   $D420
14D1-   C8          INY
14D2-   C5 D2       CMP   $D2
14D4-   C5 20       CMP   $20
14D6-   C9 D3       CMP   #$D3
14D8-   CE A7 D4    DEC   $D4A7
14DB-   20 C1 CE    JSR   $CEC1
14DE-   D9 A2 AC    CMP   $ACA2,Y
14E1-   B8          CLV
14E2-   C4 8D       CPY   $8D
14E4-   A0 DF       LDY   #$DF
14E6-   D0 D2       BNE   $14BA
14E8-   CE D4 A0    DEC   $A0D4
14EB-   A2 CD       LDX   #$CD
14ED-   C5 C1       CMP   $C1
14EF-   CE C9 CE    DEC   $CEC9
14F2-   C7          ???
14F3-   C6 D5       DEC   $D5
14F5-   CC 20 CF    CPY   $CF20
14F8-   D5 D4       CMP   $D4,X
14FA-   D0 D5       BNE   $14D1
14FC-   D4          ???
14FD-   20 D4 CF    JSR   $CFD4
1500-   20 D0 D5    JSR   $D5D0
1503-   D4          ???
1504-   20 C8 C5    JSR   $C5C8
1507-   D2 C5       CMP   ($C5)
1509-   20 D4 CF    JSR   $CFD4
150C-   20 A2 AC    JSR   $ACA2
150F-   B8          CLV
1510-   C4 8D       CPY   $8D
1512-   A0 DF       LDY   #$DF
1514-   D0 D2       BNE   $14E8
1516-   CE D4 A0    DEC   $A0D4
1519-   A2 C9       LDX   #$C9
151B-   CC CC D5    CPY   $D5CC
151E-   D3          ???
151F-   D4          ???
1520-   D2 C1       CMP   ($C1)
1522-   D4          ???
1523-   C5 20       CMP   $20
1525-   D4          ???
1526-   C8          INY
1527-   C1 D4       CMP   ($D4,X)
1529-   AC 20 D3    LDY   $D320
152C-   CF          ???
152D-   20 D5 D3    JSR   $D3D5
1530-   C5 20       CMP   $20
1532-   D9 CF D5    CMP   $D5CF,Y
1535-   D2 20       CMP   ($20)
1537-   C9 CD       CMP   #$CD
1539-   C1 C7       CMP   ($C7,X)
153B-   C9 CE       CMP   #$CE
153D-   C1 D4       CMP   ($D4,X)
153F-   C9 CF       CMP   #$CF
1541-   CE A1 A2    DEC   $A2A1
1544-   AC B8 C4    LDY   $C4B8
1547-   B8          CLV
1548-   C4 8D       CPY   $8D
154A-   A0 DF       LDY   #$DF
154C-   D7          ???
154D-   C1 C9       CMP   ($C9,X)
154F-   D4          ???
1550-   8D AA 8D    STA   $8DAA
1553-   AA          TAX
1554-   AA          TAX
1555-   20 D4 C8    JSR   $C8D4
1558-   C5 20       CMP   $20
155A-   CD D3 D7    CMP   $D7D3
155D-   C1 D0       CMP   ($D0,X)
155F-   20 CD C1    JSR   $C1CD
1562-   C3          ???
1563-   D2 CF       CMP   ($CF)
1565-   20 D3 D7    JSR   $D7D3
1568-   C1 D0       CMP   ($D0,X)
156A-   D3          ???
156B-   20 D4 C8    JSR   $C8D4
156E-   C5 20       CMP   $20
1570-   CD C5 CD    CMP   $CDC5
1573-   CF          ???
1574-   D2 D9       CMP   ($D9)
1576-   20 C2 CC    JSR   $CCC2
1579-   CF          ???
157A-   C3          ???
157B-   CB          ???
157C-   20 C1 D4    JSR   $D4C1
157F-   20 CF CE    JSR   $CECF
1582-   C5 8D       CMP   $8D
1584-   AA          TAX
1585-   AA          TAX
1586-   20 C1 C4    JSR   $C4C1
1589-   C4 D2       CPY   $D2
158B-   C5 D3       CMP   $D3
158D-   D3          ???
158E-   20 D7 C9    JSR   $C9D7
1591-   D4          ???
1592-   C8          INY
1593-   20 D4 C8    JSR   $C8D4
1596-   C5 20       CMP   $20
1598-   D3          ???
1599-   C1 CD       CMP   ($CD,X)
159B-   C5 20       CMP   $20
159D-   CC C5 CE    CPY   $CEC5
15A0-   C7          ???
15A1-   D4          ???
15A2-   C8          INY
15A3-   20 C1 D4    JSR   $D4C1
15A6-   20 C1 CE    JSR   $CEC1
15A9-   CF          ???
15AA-   D4          ???
15AB-   C8          INY
15AC-   C5 D2       CMP   $D2
15AE-   AE 8D AA    LDX   $AA8D
15B1-   8D A0 DF    STA   $DFA0
15B4-   D0 D2       BNE   $1588
15B6-   CE D4 A0    DEC   $A0D4
15B9-   A2 D4       LDX   #$D4
15BB-   C8          INY
15BC-   C5 20       CMP   $20
15BE-   CD D3 D7    CMP   $D7D3
15C1-   C1 D0       CMP   ($D0,X)
15C3-   20 CD C1    JSR   $C1CD
15C6-   C3          ???
15C7-   D2 CF       CMP   ($CF)
15C9-   20 D3 D7    JSR   $D7D3
15CC-   C1 D0       CMP   ($D0,X)
15CE-   D3          ???
15CF-   20 C1 20    JSR   $20C1
15D2-   CC C5 CE    CPY   $CEC5
15D5-   C7          ???
15D6-   D4          ???
15D7-   C8          INY
15D8-   A2 AC       LDX   #$AC
15DA-   B8          CLV
15DB-   C4 8D       CPY   $8D
15DD-   A0 DF       LDY   #$DF
15DF-   D0 D2       BNE   $15B3
15E1-   CE D4 A0    DEC   $A0D4
15E4-   A2 CF       LDX   #$CF
15E6-   C6 20       DEC   $20
15E8-   CD C5 CD    CMP   $CDC5
15EB-   CF          ???
15EC-   D2 D9       CMP   ($D9)
15EE-   20 C6 D2    JSR   $D2C6
15F1-   CF          ???
15F2-   CD 20 CF    CMP   $CF20
15F5-   CE C5 20    DEC   $20C5
15F8-   CC CF C3    CPY   $C3CF
15FB-   C1 D4       CMP   ($D4,X)
15FD-   C9 CF       CMP   #$CF
15FF-   CE A2 AC    DEC   $ACA2
1602-   B8          CLV
1603-   C4 8D       CPY   $8D
1605-   A0 DF       LDY   #$DF
1607-   D0 D2       BNE   $15DB
1609-   CE D4 A0    DEC   $A0D4
160C-   A2 D4       LDX   #$D4
160E-   CF          ???
160F-   20 C1 CE    JSR   $CEC1
1612-   CF          ???
1613-   D4          ???
1614-   C8          INY
1615-   C5 D2       CMP   $D2
1617-   AE 20 D3    LDX   $D320
161A-   CF          ???
161B-   AC 20 C2    LDY   $C220
161E-   C5 C6       CMP   $C6
1620-   CF          ???
1621-   D2 C5       CMP   ($C5)
1623-   20 D3 D7    JSR   $D7D3
1626-   C1 D0       CMP   ($D0,X)
1628-   BA          TSX
1629-   A2 AC       LDX   #$AC
162B-   B8          CLV
162C-   C4 B8       CPY   $B8
162E-   C4 8D       CPY   $8D
1630-   A0 C4       LDY   #$C4
1632-   D5 CD       CMP   $CD,X
1634-   D0 A0       BNE   $15D6
1636-   A3          ???
1637-   A4 B3       LDY   $B3
1639-   B0 B0       BCS   $15EB
163B-   BB          ???
163C-   A3          ???
163D-   B1 B0       LDA   ($B0),Y
163F-   8D A0 C4    STA   $C4A0
1642-   D5 CD       CMP   $CD,X
1644-   D0 A0       BNE   $15E6
1646-   A3          ???
1647-   A4 B3       LDY   $B3
1649-   B2 B0       LDA   ($B0)
164B-   BB          ???
164C-   A3          ???
164D-   B1 B0       LDA   ($B0),Y
164F-   8D A0 CD    STA   $CDA0
1652-   D3          ???
1653-   D7          ???
1654-   C1 D0       CMP   ($D0,X)
1656-   A0 A3       LDY   #$A3
1658-   A4 B3       LDY   $B3
165A-   B0 B0       BCS   $160C
165C-   BB          ???
165D-   A3          ???
165E-   A4 B3       LDY   $B3
1660-   B2 B0       LDA   ($B0)
1662-   BB          ???
1663-   A3          ???
1664-   B1 B0       LDA   ($B0),Y
1666-   8D A0 DF    STA   $DFA0
1669-   D0 D2       BNE   $163D
166B-   CE D4 A0    DEC   $A0D4
166E-   A2 20       LDX   #$20
1670-   A2 AC       LDX   #$AC
1672-   B8          CLV
1673-   C4 8D       CPY   $8D
1675-   A0 DF       LDY   #$DF
1677-   D0 D2       BNE   $164B
1679-   CE D4 A0    DEC   $A0D4
167C-   A2 C1       LDX   #$C1
167E-   CE C4 20    DEC   $20C4
1681-   C1 C6       CMP   ($C6,X)
1683-   D4          ???
1684-   C5 D2       CMP   $D2
1686-   20 D3 D7    JSR   $D7D3
1689-   C1 D0       CMP   ($D0,X)
168B-   BA          TSX
168C-   20 A2 AC    JSR   $ACA2
168F-   B8          CLV
1690-   C4 B8       CPY   $B8
1692-   C4 8D       CPY   $8D
1694-   A0 C4       LDY   #$C4
1696-   D5 CD       CMP   $CD,X
1698-   D0 A0       BNE   $163A
169A-   A3          ???
169B-   A4 B3       LDY   $B3
169D-   B0 B0       BCS   $164F
169F-   BB          ???
16A0-   A3          ???
16A1-   B1 B0       LDA   ($B0),Y
16A3-   8D A0 C4    STA   $C4A0
16A6-   D5 CD       CMP   $CD,X
16A8-   D0 A0       BNE   $164A
16AA-   A3          ???
16AB-   A4 B3       LDY   $B3
16AD-   B2 B0       LDA   ($B0)
16AF-   BB          ???
16B0-   A3          ???
16B1-   B1 B0       LDA   ($B0),Y
16B3-   8D A0 DF    STA   $DFA0
16B6-   D7          ???
16B7-   C1 C9       CMP   ($C9,X)
16B9-   D4          ???
16BA-   8D AA 8D    STA   $8DAA
16BD-   A0 CA       LDY   #$CA
16BF-   CD D0 A0    CMP   $A0D0
16C2-   D2 C5       CMP   ($C5)
16C4-   C5 CE       CMP   $CE
16C6-   D4          ???
16C7-   D2 D9       CMP   ($D9)
16C9-   8D AA 8D    STA   $8DAA
16CC-   AA          TAX
16CD-   E0 E0       CPX   #$E0
16CF-   E0 E0       CPX   #$E0
16D1-   E0 E0       CPX   #$E0
16D3-   E0 E0       CPX   #$E0
16D5-   E0 E0       CPX   #$E0
16D7-   E0 E0       CPX   #$E0
16D9-   E0 E0       CPX   #$E0
16DB-   E0 E0       CPX   #$E0
16DD-   E0 E0       CPX   #$E0
16DF-   E0 E0       CPX   #$E0
16E1-   E0 E0       CPX   #$E0
16E3-   E0 E0       CPX   #$E0
16E5-   E0 E0       CPX   #$E0
16E7-   E0 E0       CPX   #$E0
16E9-   E0 E0       CPX   #$E0
16EB-   AA          TAX
16EC-   8D AA 20    STA   $20AA
16EF-   20 20 20    JSR   $2020
16F2-   20 20 20    JSR   $2020
16F5-   20 C2 CF    JSR   $CFC2
16F8-   D4          ???
16F9-   D4          ???
16FA-   CF          ???
16FB-   CD 20 C9    CMP   $C920
16FE-   CE C3 CC    DEC   $CCC3
1701-   D5 C4       CMP   $C4,X
1703-   C5 D3       CMP   $D3
1705-   20 20 20    JSR   $2020
1708-   20 20 20    JSR   $2020
170B-   20 AA 8D    JSR   $8DAA
170E-   AA          TAX
170F-   AC AC AC    LDY   $ACAC
1712-   AC AC AC    LDY   $ACAC
1715-   AC AC AC    LDY   $ACAC
1718-   AC AC AC    LDY   $ACAC
171B-   AC AC AC    LDY   $ACAC
171E-   AC AC AC    LDY   $ACAC
1721-   AC AC AC    LDY   $ACAC
1724-   AC AC AC    LDY   $ACAC
1727-   AC AC AC    LDY   $ACAC
172A-   AC AC AC    LDY   $ACAC
172D-   AA          TAX
172E-   8D AA 8D    STA   $8DAA
1731-   AA          TAX
1732-   AA          TAX
1733-   20 C2 CF    JSR   $CFC2
1736-   D4          ???
1737-   D4          ???
1738-   CF          ???
1739-   CD 20 C9    CMP   $C920
173C-   CE C3 CC    DEC   $CCC3
173F-   D5 C4       CMP   $C4,X
1741-   C5 D3       CMP   $D3
1743-   8D AA 8D    STA   $8DAA
1746-   A0 D0       LDY   #$D0
1748-   D5 D4       CMP   $D4,X
174A-   A0 CD       LDY   #$CD
174C-   C9 CE       CMP   #$CE
174E-   AE CC C9    LDX   $C9CC
1751-   C2          ???
1752-   AE D2 C5    LDX   $C5D2
1755-   D1 D5       CMP   ($D5),Y
1757-   C9 D2       CMP   #$D2
1759-   C5 C4       CMP   $C4
175B-   8D AA 8D    STA   $8DAA
175E-   AA          TAX
175F-   AA          TAX
1760-   20 C9 CE    JSR   $CEC9
1763-   C4 C9       CPY   $C9
1765-   D6 C9       DEC   $C9,X
1767-   C4 D5       CPY   $D5
1769-   C1 CC       CMP   ($CC,X)
176B-   20 D3 D5    JSR   $D5D3
176E-   C2          ???
176F-   D2 CF       CMP   ($CF)
1771-   D5 D4       CMP   $D4,X
1773-   C9 CE       CMP   #$CE
1775-   C5 20       CMP   $20
1777-   C9 CE       CMP   #$CE
1779-   C3          ???
177A-   CC D5 C4    CPY   $C4D5
177D-   C5 D3       CMP   $D3
177F-   8D AA 8D    STA   $8DAA
1782-   AA          TAX
1783-   20 20 C3    JSR   $C320
1786-   CF          ???
1787-   CD CD CF    CMP   $CFCD
178A-   CE 20 CC    DEC   $CC20
178D-   C9 C2       CMP   #$C2
178F-   D2 C1       CMP   ($C1)
1791-   D2 D9       CMP   ($D9)
1793-   20 D3 D5    JSR   $D5D3
1796-   C2          ???
1797-   D2 CF       CMP   ($CF)
1799-   D5 D4       CMP   $D4,X
179B-   C9 CE       CMP   #$CE
179D-   C5 D3       CMP   $D3
179F-   8D AA 8D    STA   $8DAA
17A2-   A0 D0       LDY   #$D0
17A4-   D5 D4       CMP   $D4,X
17A6-   A0 CD       LDY   #$CD
17A8-   C9 CE       CMP   #$CE
17AA-   AE D3 D5    LDX   $D5D3
17AD-   C2          ???
17AE-   AE CD C5    LDX   $C5CD
17B1-   CD C6 C9    CMP   $C9C6
17B4-   CC CC 8D    CPY   $8DCC
17B7-   A0 D0       LDY   #$D0
17B9-   D5 D4       CMP   $D4,X
17BB-   A0 CD       LDY   #$CD
17BD-   C9 CE       CMP   #$CE
17BF-   AE D3 D5    LDX   $D5D3
17C2-   C2          ???
17C3-   AE CD C5    LDX   $C5CD
17C6-   CD CD CF    CMP   $CFCD
17C9-   D6 C5       DEC   $C5,X
17CB-   8D A0 D0    STA   $D0A0
17CE-   D5 D4       CMP   $D4,X
17D0-   A0 CD       LDY   #$CD
17D2-   C9 CE       CMP   #$CE
17D4-   AE D3 D5    LDX   $D5D3
17D7-   C2          ???
17D8-   AE C4 C5    LDX   $C5C4
17DB-   CC C1 D9    CPY   $D9C1
17DE-   CD D3 8D    CMP   $8DD3
17E1-   A0 D0       LDY   #$D0
17E3-   D5 D4       CMP   $D4,X
17E5-   A0 CD       LDY   #$CD
17E7-   C9 CE       CMP   #$CE
17E9-   AE D3 D5    LDX   $D5D3
17EC-   C2          ???
17ED-   AE DA CD    LDX   $CDDA
17F0-   D3          ???
17F1-   C1 D6       CMP   ($D6,X)
17F3-   C5 8D       CMP   $8D
17F5-   A0 D0       LDY   #$D0
17F7-   D5 D4       CMP   $D4,X
17F9-   A0 CD       LDY   #$CD
17FB-   C9 CE       CMP   #$CE
17FD-   AE D3 D5    LDX   $D5D3
1800-   C2          ???
1801-   AE DA CD    LDX   $CDDA
1804-   CC CF C1    CPY   $C1CF
1807-   C4 8D       CPY   $8D
1809-   A0 D0       LDY   #$D0
180B-   D5 D4       CMP   $D4,X
180D-   A0 CD       LDY   #$CD
180F-   C9 CE       CMP   #$CE
1811-   AE D3 D5    LDX   $D5D3
1814-   C2          ???
1815-   AE CD C5    LDX   $C5CD
1818-   CD D3 D7    CMP   $D7D3
181B-   C1 D0       CMP   ($D0,X)
181D-   8D 00 00    STA   $0000
