0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C3    LDY   $C320,X
0950-   CF          ???
0951-   CE D6 C5    DEC   $C5D6
0954-   D2 D4       CMP   ($D4)
0956-   20 C4 C5    JSR   $C5C4
0959-   CD CF 20    CMP   $20CF
095C-   BE AD 20    LDX   $20AD,Y
095F-   20 20 20    JSR   $2020
0962-   20 20 AA    JSR   $AA20
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B3       BCS   $094F
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B0    JSR   $B020
09D4-   B6 AD       LDX   $AD,Y
09D6-   C6 C5       DEC   $C5
09D8-   C2          ???
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B9       LDA   ($B9),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 D4       LDY   #$D4
0AF8-   D2 A0       CMP   ($A0)
0AFA-   CF          ???
0AFB-   CE 8D A0    DEC   $A08D
0AFE-   C5 D8       CMP   $D8
0B00-   D0 A0       BNE   $0AA2
0B02-   CF          ???
0B03-   CE CC D9    DEC   $D9CC
0B06-   8D A0 C4    STA   $C4A0
0B09-   D3          ???
0B0A-   CB          ???
0B0B-   A0 C3       LDY   #$C3
0B0D-   CF          ???
0B0E-   CE D6 C5    DEC   $C5D6
0B11-   D2 D4       CMP   ($D4)
0B13-   AE C4 C5    LDX   $C5C4
0B16-   CD CF 8D    CMP   $8DCF
0B19-   A0 CF       LDY   #$CF
0B1B-   C2          ???
0B1C-   CA          DEX
0B1D-   A0 A4       LDY   #$A4
0B1F-   C2          ???
0B20-   C6 C5       DEC   $C5
0B22-   B0 8D       BCS   $0AB1
0B24-   A0 CF       LDY   #$CF
0B26-   D2 C7       CMP   ($C7)
0B28-   A0 A4       LDY   #$A4
0B2A-   B6 B0       LDX   $B0,Y
0B2C-   B0 B0       BCS   $0ADE
0B2E-   8D AA 8D    STA   $8DAA
0B31-   AA          TAX
0B32-   E0 E0       CPX   #$E0
0B34-   E0 E0       CPX   #$E0
0B36-   E0 E0       CPX   #$E0
0B38-   E0 E0       CPX   #$E0
0B3A-   E0 E0       CPX   #$E0
0B3C-   E0 E0       CPX   #$E0
0B3E-   E0 E0       CPX   #$E0
0B40-   E0 E0       CPX   #$E0
0B42-   E0 E0       CPX   #$E0
0B44-   E0 E0       CPX   #$E0
0B46-   E0 E0       CPX   #$E0
0B48-   E0 E0       CPX   #$E0
0B4A-   E0 E0       CPX   #$E0
0B4C-   E0 E0       CPX   #$E0
0B4E-   E0 E0       CPX   #$E0
0B50-   AA          TAX
0B51-   8D AA 20    STA   $20AA
0B54-   20 D4 CF    JSR   $CFD4
0B57-   D0 20       BNE   $0B79
0B59-   C9 CE       CMP   #$CE
0B5B-   C3          ???
0B5C-   CC D5 C4    CPY   $C4D5
0B5F-   C5 D3       CMP   $D3
0B61-   20 A8 D0    JSR   $D0A8
0B64-   D5 D4       CMP   $D4,X
0B66-   D3          ???
0B67-   AC 20 CD    LDY   $CD20
0B6A-   C1 C3       CMP   ($C3,X)
0B6C-   D2 CF       CMP   ($CF)
0B6E-   D3          ???
0B6F-   A9 20       LDA   #$20
0B71-   AA          TAX
0B72-   8D AA AC    STA   $ACAA
0B75-   AC AC AC    LDY   $ACAC
0B78-   AC AC AC    LDY   $ACAC
0B7B-   AC AC AC    LDY   $ACAC
0B7E-   AC AC AC    LDY   $ACAC
0B81-   AC AC AC    LDY   $ACAC
0B84-   AC AC AC    LDY   $ACAC
0B87-   AC AC AC    LDY   $ACAC
0B8A-   AC AC AC    LDY   $ACAC
0B8D-   AC AC AC    LDY   $ACAC
0B90-   AC AC AA    LDY   $AAAC
0B93-   8D AA 8D    STA   $8DAA
0B96-   A0 D0       LDY   #$D0
0B98-   D5 D4       CMP   $D4,X
0B9A-   A0 CD       LDY   #$CD
0B9C-   C9 CE       CMP   #$CE
0B9E-   AE D6 C1    LDX   $C1D6
0BA1-   D2 D3       CMP   ($D3)
0BA3-   AE D2 C5    LDX   $C5D2
0BA6-   D1 D5       CMP   ($D5),Y
0BA8-   C9 D2       CMP   #$D2
0BAA-   C5 C4       CMP   $C4
0BAC-   8D A0 D5    STA   $D5A0
0BAF-   D3          ???
0BB0-   C5 A0       CMP   $A0
0BB2-   CD C9 CE    CMP   $CEC9
0BB5-   AE CD C1    LDX   $C1CD
0BB8-   C3          ???
0BB9-   AE D2 C5    LDX   $C5D2
0BBC-   D1 D5       CMP   ($D5),Y
0BBE-   C9 D2       CMP   #$D2
0BC0-   C5 C4       CMP   $C4
0BC2-   8D A0 D0    STA   $D0A0
0BC5-   D5 D4       CMP   $D4,X
0BC7-   A0 CD       LDY   #$CD
0BC9-   C9 CE       CMP   #$CE
0BCB-   AE C8 CF    LDX   $CFC8
0BCE-   CF          ???
0BCF-   CB          ???
0BD0-   D3          ???
0BD1-   AE D2 C5    LDX   $C5D2
0BD4-   D1 D5       CMP   ($D5),Y
0BD6-   C9 D2       CMP   #$D2
0BD8-   C5 C4       CMP   $C4
0BDA-   8D A0 D5    STA   $D5A0
0BDD-   D3          ???
0BDE-   C5 A0       CMP   $A0
0BE0-   CD C9 CE    CMP   $CEC9
0BE3-   AE CD C1    LDX   $C1CD
0BE6-   C3          ???
0BE7-   AE C3 CF    LDX   $CFC3
0BEA-   CE D6 C5    DEC   $C5D6
0BED-   D2 D4       CMP   ($D4)
0BEF-   8D AA D0    STA   $D0AA
0BF2-   D5 D4       CMP   $D4,X
0BF4-   20 C8 CF    JSR   $CFC8
0BF7-   CF          ???
0BF8-   CB          ???
0BF9-   D3          ???
0BFA-   AE C3 CF    LDX   $CFC3
0BFD-   CE D6 C5    DEC   $C5D6
0C00-   D2 D4       CMP   ($D4)
0C02-   8D AA 8D    STA   $8DAA
0C05-   AA          TAX
0C06-   8D AA E0    STA   $E0AA
0C09-   E0 E0       CPX   #$E0
0C0B-   E0 E0       CPX   #$E0
0C0D-   E0 E0       CPX   #$E0
0C0F-   E0 E0       CPX   #$E0
0C11-   E0 E0       CPX   #$E0
0C13-   E0 E0       CPX   #$E0
0C15-   E0 E0       CPX   #$E0
0C17-   E0 E0       CPX   #$E0
0C19-   E0 E0       CPX   #$E0
0C1B-   E0 E0       CPX   #$E0
0C1D-   E0 E0       CPX   #$E0
0C1F-   E0 E0       CPX   #$E0
0C21-   E0 E0       CPX   #$E0
0C23-   E0 E0       CPX   #$E0
0C25-   E0 AA       CPX   #$AA
0C27-   8D AA 20    STA   $20AA
0C2A-   20 20 20    JSR   $2020
0C2D-   20 20 D0    JSR   $D020
0C30-   D2 CF       CMP   ($CF)
0C32-   C7          ???
0C33-   D2 C1       CMP   ($C1)
0C35-   CD 20 CD    CMP   $CD20
0C38-   C1 C9       CMP   ($C9,X)
0C3A-   CE 20 C2    DEC   $C220
0C3D-   CF          ???
0C3E-   C4 D9       CPY   $D9
0C40-   20 20 20    JSR   $2020
0C43-   20 20 20    JSR   $2020
0C46-   20 AA 8D    JSR   $8DAA
0C49-   AA          TAX
0C4A-   AC AC AC    LDY   $ACAC
0C4D-   AC AC AC    LDY   $ACAC
0C50-   AC AC AC    LDY   $ACAC
0C53-   AC AC AC    LDY   $ACAC
0C56-   AC AC AC    LDY   $ACAC
0C59-   AC AC AC    LDY   $ACAC
0C5C-   AC AC AC    LDY   $ACAC
0C5F-   AC AC AC    LDY   $ACAC
0C62-   AC AC AC    LDY   $ACAC
0C65-   AC AC AC    LDY   $ACAC
0C68-   AA          TAX
0C69-   8D AA 8D    STA   $8DAA
0C6C-   AA          TAX
0C6D-   AA          TAX
0C6E-   20 C9 CE    JSR   $CEC9
0C71-   D4          ???
0C72-   C1 D3       CMP   ($D3,X)
0C74-   C3          ???
0C75-   20 CD C1    JSR   $C1CD
0C78-   C3          ???
0C79-   D2 CF       CMP   ($CF)
0C7B-   8D AA 8D    STA   $8DAA
0C7E-   AA          TAX
0C7F-   AA          TAX
0C80-   20 D5 D3    JSR   $D3D5
0C83-   C1 C7       CMP   ($C7,X)
0C85-   C5 BA       CMP   $BA
0C87-   20 C9 CE    JSR   $CEC9
0C8A-   D4          ???
0C8B-   C1 D3       CMP   ($D3,X)
0C8D-   C3          ???
0C8E-   20 DB CC    JSR   $CCDB
0C91-   C9 D4       CMP   #$D4
0C93-   C5 D2       CMP   $D2
0C95-   C1 CC       CMP   ($CC,X)
0C97-   20 CF D2    JSR   $D2CF
0C9A-   20 C1 C4    JSR   $C4C1
0C9D-   C4 D2       CPY   $D2
0C9F-   C5 D3       CMP   $D3
0CA1-   D3          ???
0CA2-   DD 8D AA    CMP   $AA8D,X
0CA5-   8D A0 DF    STA   $DFA0
0CA8-   D0 D2       BNE   $0C7C
0CAA-   CE D4 A0    DEC   $A0D4
0CAD-   A2 20       LDX   #$20
0CAF-   A2 AC       LDX   #$AC
0CB1-   B8          CLV
0CB2-   C4 B8       CPY   $B8
0CB4-   C4 8D       CPY   $8D
0CB6-   A0 DF       LDY   #$DF
0CB8-   D0 D2       BNE   $0C8C
0CBA-   CE D4 A0    DEC   $A0D4
0CBD-   A2 D4       LDX   #$D4
0CBF-   C8          INY
0CC0-   C5 20       CMP   $20
0CC2-   C9 CE       CMP   #$CE
0CC4-   D4          ???
0CC5-   C1 D3       CMP   ($D3,X)
0CC7-   C3          ???
0CC8-   20 CD C1    JSR   $C1CD
0CCB-   C3          ???
0CCC-   D2 CF       CMP   ($CF)
0CCE-   20 C3 CF    JSR   $CFC3
0CD1-   CE D6 C5    DEC   $C5D6
0CD4-   D2 D4       CMP   ($D4)
0CD6-   D3          ???
0CD7-   A2 AC       LDX   #$AC
0CD9-   B8          CLV
0CDA-   C4 8D       CPY   $8D
0CDC-   A0 DF       LDY   #$DF
0CDE-   D0 D2       BNE   $0CB2
0CE0-   CE D4 A0    DEC   $A0D4
0CE3-   A2 C1       LDX   #$C1
0CE5-   20 C8 C5    JSR   $C5C8
0CE8-   D8          CLD
0CE9-   C1 C4       CMP   ($C4,X)
0CEB-   C5 C3       CMP   $C3
0CED-   C9 CD       CMP   #$CD
0CEF-   C1 CC       CMP   ($CC,X)
0CF1-   20 D7 CF    JSR   $CFD7
0CF4-   D2 C4       CMP   ($C4)
0CF6-   20 A8 B2    JSR   $B2A8
0CF9-   20 C2 D9    JSR   $D9C2
0CFC-   D4          ???
0CFD-   C5 D3       CMP   $D3
0CFF-   A9 A2       LDA   #$A2
0D01-   AC B8 C4    LDY   $C4B8
0D04-   8D A0 DF    STA   $DFA0
0D07-   D0 D2       BNE   $0CDB
0D09-   CE D4 A0    DEC   $A0D4
0D0C-   A2 C9       LDX   #$C9
0D0E-   CE D4 CF    DEC   $CFD4
0D11-   20 D4 C8    JSR   $C8D4
0D14-   C5 20       CMP   $20
0D16-   C3          ???
0D17-   CF          ???
0D18-   D2 D2       CMP   ($D2)
0D1A-   C5 D3       CMP   $D3
0D1C-   D0 CF       BNE   $0CED
0D1E-   CE C4 C9    DEC   $C9C4
0D21-   CE C7 20    DEC   $20C7
0D24-   D3          ???
0D25-   C9 C7       CMP   #$C7
0D27-   CE C5 C4    DEC   $C4C5
0D2A-   A2 AC       LDX   #$AC
0D2C-   B8          CLV
0D2D-   C4 8D       CPY   $8D
0D2F-   A0 DF       LDY   #$DF
0D31-   D0 D2       BNE   $0D05
0D33-   CE D4 A0    DEC   $A0D4
0D36-   A2 CF       LDX   #$CF
0D38-   D2 20       CMP   ($20)
0D3A-   D5 CE       CMP   $CE,X
0D3C-   D3          ???
0D3D-   C9 C7       CMP   #$C7
0D3F-   CE C5 C4    DEC   $C4C5
0D42-   20 C4 C5    JSR   $C5C4
0D45-   C3          ???
0D46-   C9 CD       CMP   #$CD
0D48-   C1 CC       CMP   ($CC,X)
0D4A-   20 D3 D4    JSR   $D4D3
0D4D-   D2 C9       CMP   ($C9)
0D4F-   CE C7 AE    DEC   $AEC7
0D52-   A2 AC       LDX   #$AC
0D54-   B8          CLV
0D55-   C4 B8       CPY   $B8
0D57-   C4 8D       CPY   $8D
0D59-   A0 DF       LDY   #$DF
0D5B-   D0 D2       BNE   $0D2F
0D5D-   CE D4 A0    DEC   $A0D4
0D60-   A2 D4       LDX   #$D4
0D62-   C8          INY
0D63-   D5 D3       CMP   $D3,X
0D65-   AC 20 C9    LDY   $C920
0D68-   CE D4 C1    DEC   $C1D4
0D6B-   D3          ???
0D6C-   C3          ???
0D6D-   20 A3 A4    JSR   $A4A3
0D70-   C6 C6       DEC   $C6
0D72-   20 D2 C5    JSR   $C5D2
0D75-   D4          ???
0D76-   D5 D2       CMP   $D2,X
0D78-   CE D3 BA    DEC   $BAD3
0D7B-   A2 AC       LDX   #$AC
0D7D-   B8          CLV
0D7E-   C4 B8       CPY   $B8
0D80-   C4 8D       CPY   $8D
0D82-   A0 C9       LDY   #$C9
0D84-   CE D4 C1    DEC   $C1D4
0D87-   D3          ???
0D88-   C3          ???
0D89-   A0 A3       LDY   #$A3
0D8B-   A4 C6       LDY   $C6
0D8D-   C6 8D       DEC   $8D
0D8F-   A0 C4       LDY   #$C4
0D91-   D5 CD       CMP   $CD,X
0D93-   D0 A0       BNE   $0D35
0D95-   A3          ???
0D96-   D2 C5       CMP   ($C5)
0D98-   D4          ???
0D99-   D5 D2       CMP   $D2,X
0D9B-   CE BB A3    DEC   $A3BB
0D9E-   B4 8D       LDY   $8D,X
0DA0-   A0 DF       LDY   #$DF
0DA2-   D7          ???
0DA3-   C1 C9       CMP   ($C9,X)
0DA5-   D4          ???
0DA6-   8D AA 8D    STA   $8DAA
0DA9-   AA          TAX
0DAA-   AA          TAX
0DAB-   20 C1 D3    JSR   $D3C1
0DAE-   C3          ???
0DAF-   C9 CE       CMP   #$CE
0DB1-   D4          ???
0DB2-   20 CD C1    JSR   $C1CD
0DB5-   C3          ???
0DB6-   D2 CF       CMP   ($CF)
0DB8-   8D AA 8D    STA   $8DAA
0DBB-   AA          TAX
0DBC-   AA          TAX
0DBD-   20 D5 D3    JSR   $D3D5
0DC0-   C1 C7       CMP   ($C7,X)
0DC2-   C5 BA       CMP   $BA
0DC4-   20 C1 D3    JSR   $D3C1
0DC7-   C3          ???
0DC8-   C9 CE       CMP   #$CE
0DCA-   D4          ???
0DCB-   20 DB D3    JSR   $D3DB
0DCE-   D4          ???
0DCF-   D2 C9       CMP   ($C9)
0DD1-   CE C7 20    DEC   $20C7
0DD4-   CF          ???
0DD5-   D2 20       CMP   ($20)
0DD7-   D3          ???
0DD8-   D4          ???
0DD9-   D2 C9       CMP   ($C9)
0DDB-   CE C7 20    DEC   $20C7
0DDE-   C1 C4       CMP   ($C4,X)
0DE0-   C4 D2       CPY   $D2
0DE2-   C5 D3       CMP   $D3
0DE4-   D3          ???
0DE5-   DD 8D AA    CMP   $AA8D,X
0DE8-   8D A0 DF    STA   $DFA0
0DEB-   D0 D2       BNE   $0DBF
0DED-   CE D4 A0    DEC   $A0D4
0DF0-   A2 20       LDX   #$20
0DF2-   A2 AC       LDX   #$AC
0DF4-   B8          CLV
0DF5-   C4 B8       CPY   $B8
0DF7-   C4 8D       CPY   $8D
0DF9-   A0 DF       LDY   #$DF
0DFB-   D0 D2       BNE   $0DCF
0DFD-   CE D4 A0    DEC   $A0D4
0E00-   A2 C1       LDX   #$C1
0E02-   D3          ???
0E03-   C3          ???
0E04-   C9 CE       CMP   #$CE
0E06-   D4          ???
0E07-   20 C4 CF    JSR   $CFC4
0E0A-   C5 D3       CMP   $D3
0E0C-   20 D4 C8    JSR   $C8D4
0E0F-   C5 20       CMP   $20
0E11-   CF          ???
0E12-   D0 D0       BNE   $0DE4
0E14-   CF          ???
0E15-   D3          ???
0E16-   C9 D4       CMP   #$D4
0E18-   C5 20       CMP   $20
0E1A-   CF          ???
0E1B-   C6 20       DEC   $20
0E1D-   A2 AC       LDX   #$AC
0E1F-   B8          CLV
0E20-   C4 8D       CPY   $8D
0E22-   A0 DF       LDY   #$DF
0E24-   D0 D2       BNE   $0DF8
0E26-   CE D4 A0    DEC   $A0D4
0E29-   A2 C9       LDX   #$C9
0E2B-   CE D4 C1    DEC   $C1D4
0E2E-   D3          ???
0E2F-   C3          ???
0E30-   BB          ???
0E31-   20 C9 D4    JSR   $D4C9
0E34-   20 D4 D5    JSR   $D5D4
0E37-   D2 CE       CMP   ($CE)
0E39-   D3          ???
0E3A-   20 C1 20    JSR   $20C1
0E3D-   D3          ???
0E3E-   D4          ???
0E3F-   D2 C9       CMP   ($C9)
0E41-   CE C7 20    DEC   $20C7
0E44-   CF          ???
0E45-   C6 A2       DEC   $A2
0E47-   AC B8 C4    LDY   $C4B8
0E4A-   8D A0 DF    STA   $DFA0
0E4D-   D0 D2       BNE   $0E21
0E4F-   CE D4 A0    DEC   $A0D4
0E52-   A2 C4       LDX   #$C4
0E54-   C5 C3       CMP   $C3
0E56-   C9 CD       CMP   #$CD
0E58-   C1 CC       CMP   ($CC,X)
0E5A-   20 C9 CE    JSR   $CEC9
0E5D-   D4          ???
0E5E-   C5 C7       CMP   $C7
0E60-   C5 D2       CMP   $D2
0E62-   D3          ???
0E63-   20 C9 CE    JSR   $CEC9
0E66-   D4          ???
0E67-   CF          ???
0E68-   20 C9 D4    JSR   $D4C9
0E6B-   D3          ???
0E6C-   20 A2 AC    JSR   $ACA2
0E6F-   B8          CLV
0E70-   C4 8D       CPY   $8D
0E72-   A0 DF       LDY   #$DF
0E74-   D0 D2       BNE   $0E48
0E76-   CE D4 A0    DEC   $A0D4
0E79-   A2 C3       LDX   #$C3
0E7B-   CF          ???
0E7C-   D2 D2       CMP   ($D2)
0E7E-   C5 D3       CMP   $D3
0E80-   D0 CF       BNE   $0E51
0E82-   CE C4 C9    DEC   $C9C4
0E85-   CE C7 20    DEC   $20C7
0E88-   D4          ???
0E89-   D7          ???
0E8A-   CF          ???
0E8B-   AD C2 D9    LDA   $D9C2
0E8E-   D4          ???
0E8F-   C5 20       CMP   $20
0E91-   D6 C1       DEC   $C1,X
0E93-   CC D5 C5    CPY   $C5D5
0E96-   AE A2 AC    LDX   $ACA2
0E99-   B8          CLV
0E9A-   C4 B8       CPY   $B8
0E9C-   C4 8D       CPY   $8D
0E9E-   A0 DF       LDY   #$DF
0EA0-   D0 D2       BNE   $0E74
0EA2-   CE D4 A0    DEC   $A0D4
0EA5-   A2 D3       LDX   #$D3
0EA7-   CF          ???
0EA8-   AC 20 C1    LDY   $C120
0EAB-   D3          ???
0EAC-   C3          ???
0EAD-   C9 CE       CMP   #$CE
0EAF-   D4          ???
0EB0-   20 A7 B2    JSR   $B2A7
0EB3-   B5 B5       LDA   $B5,X
0EB5-   A7          ???
0EB6-   20 D2 C5    JSR   $C5D2
0EB9-   D4          ???
0EBA-   D5 D2       CMP   $D2,X
0EBC-   CE D3 BA    DEC   $BAD3
0EBF-   A2 AC       LDX   #$AC
0EC1-   B8          CLV
0EC2-   C4 B8       CPY   $B8
0EC4-   C4 8D       CPY   $8D
0EC6-   A0 C1       LDY   #$C1
0EC8-   D3          ???
0EC9-   C3          ???
0ECA-   C9 CE       CMP   #$CE
0ECC-   D4          ???
0ECD-   A0 A2       LDY   #$A2
0ECF-   B2 B5       LDA   ($B5)
0ED1-   B5 A2       LDA   $A2,X
0ED3-   8D A0 C4    STA   $C4A0
0ED6-   D5 CD       CMP   $CD,X
0ED8-   D0 A0       BNE   $0E7A
0EDA-   A3          ???
0EDB-   D2 C5       CMP   ($C5)
0EDD-   D4          ???
0EDE-   D5 D2       CMP   $D2,X
0EE0-   CE BB D2    DEC   $D2BB
0EE3-   C5 D4       CMP   $D4
0EE5-   CC C5 CE    CPY   $CEC5
0EE8-   8D A0 DF    STA   $DFA0
0EEB-   D7          ???
0EEC-   C1 C9       CMP   ($C9,X)
0EEE-   D4          ???
0EEF-   8D AA 8D    STA   $8DAA
0EF2-   AA          TAX
0EF3-   AA          TAX
0EF4-   20 C8 C5    JSR   $C5C8
0EF7-   D8          CLD
0EF8-   C1 D3       CMP   ($D3,X)
0EFA-   C3          ???
0EFB-   20 CD C1    JSR   $C1CD
0EFE-   C3          ???
0EFF-   D2 CF       CMP   ($CF)
0F01-   8D AA 8D    STA   $8DAA
0F04-   AA          TAX
0F05-   AA          TAX
0F06-   20 D5 D3    JSR   $D3D5
0F09-   C1 C7       CMP   ($C7,X)
0F0B-   C5 BA       CMP   $BA
0F0D-   20 C8 C5    JSR   $C5C8
0F10-   D8          CLD
0F11-   C1 D3       CMP   ($D3,X)
0F13-   C3          ???
0F14-   20 DB CC    JSR   $CCDB
0F17-   C9 D4       CMP   #$D4
0F19-   C5 D2       CMP   $D2
0F1B-   C1 CC       CMP   ($CC,X)
0F1D-   20 CE D5    JSR   $D5CE
0F20-   CD C2 C5    CMP   $C5C2
0F23-   D2 20       CMP   ($20)
0F25-   CF          ???
0F26-   D2 20       CMP   ($20)
0F28-   C1 C4       CMP   ($C4,X)
0F2A-   C4 D2       CPY   $D2
0F2C-   C5 D3       CMP   $D3
0F2E-   D3          ???
0F2F-   20 CF C6    JSR   $C6CF
0F32-   20 C2 D9    JSR   $D9C2
0F35-   D4          ???
0F36-   C5 DD       CMP   $DD
0F38-   8D AA 8D    STA   $8DAA
0F3B-   A0 DF       LDY   #$DF
0F3D-   D0 D2       BNE   $0F11
0F3F-   CE D4 A0    DEC   $A0D4
0F42-   A2 20       LDX   #$20
0F44-   A2 AC       LDX   #$AC
0F46-   B8          CLV
0F47-   C4 B8       CPY   $B8
0F49-   C4 8D       CPY   $8D
0F4B-   A0 DF       LDY   #$DF
0F4D-   D0 D2       BNE   $0F21
0F4F-   CE D4 A0    DEC   $A0D4
0F52-   A2 D4       LDX   #$D4
0F54-   C8          INY
0F55-   C5 20       CMP   $20
0F57-   C8          INY
0F58-   C5 D8       CMP   $D8
0F5A-   C1 D3       CMP   ($D3,X)
0F5C-   C3          ???
0F5D-   20 CD C1    JSR   $C1CD
0F60-   C3          ???
0F61-   D2 CF       CMP   ($CF)
0F63-   20 C3 CF    JSR   $CFC3
0F66-   CE D6 C5    DEC   $C5D6
0F69-   D2 D4       CMP   ($D4)
0F6B-   D3          ???
0F6C-   20 C1 20    JSR   $20C1
0F6F-   C2          ???
0F70-   D9 D4 C5    CMP   $C5D4,Y
0F73-   A2 AC       LDX   #$AC
0F75-   B8          CLV
0F76-   C4 8D       CPY   $8D
0F78-   A0 DF       LDY   #$DF
0F7A-   D0 D2       BNE   $0F4E
0F7C-   CE D4 A0    DEC   $A0D4
0F7F-   A2 C9       LDX   #$C9
0F81-   CE 20 CD    DEC   $CD20
0F84-   C5 CD       CMP   $CD
0F86-   CF          ???
0F87-   D2 D9       CMP   ($D9)
0F89-   20 D4 CF    JSR   $CFD4
0F8C-   20 C9 D4    JSR   $D4C9
0F8F-   D3          ???
0F90-   20 C3 CF    JSR   $CFC3
0F93-   D2 D2       CMP   ($D2)
0F95-   C5 D3       CMP   $D3
0F97-   D0 CF       BNE   $0F68
0F99-   CE C4 C9    DEC   $C9C4
0F9C-   CE C7 A2    DEC   $A2C7
0F9F-   AC B8 C4    LDY   $C4B8
0FA2-   8D A0 DF    STA   $DFA0
0FA5-   D0 D2       BNE   $0F79
0FA7-   CE D4 A0    DEC   $A0D4
0FAA-   A2 C8       LDX   #$C8
0FAC-   C5 D8       CMP   $D8
0FAE-   20 D6 C1    JSR   $C1D6
0FB1-   CC D5 C5    CPY   $C5D5
0FB4-   20 C1 D3    JSR   $D3C1
0FB7-   20 C1 20    JSR   $20C1
0FBA-   D3          ???
0FBB-   D4          ???
0FBC-   D2 C9       CMP   ($C9)
0FBE-   CE C7 AE    DEC   $AEC7
0FC1-   A2 AC       LDX   #$AC
0FC3-   B8          CLV
0FC4-   C4 B8       CPY   $B8
0FC6-   C4 8D       CPY   $8D
0FC8-   A0 DF       LDY   #$DF
0FCA-   D0 D2       BNE   $0F9E
0FCC-   CE D4 A0    DEC   $A0D4
0FCF-   A2 D4       LDX   #$D4
0FD1-   C8          INY
0FD2-   C5 D2       CMP   $D2
0FD4-   C5 C6       CMP   $C6
0FD6-   CF          ???
0FD7-   D2 C5       CMP   ($C5)
0FD9-   AC 20 C8    LDY   $C820
0FDC-   C5 D8       CMP   $D8
0FDE-   C1 D3       CMP   ($D3,X)
0FE0-   C3          ???
0FE1-   20 A3 A4    JSR   $A4A3
0FE4-   C6 C6       DEC   $C6
0FE6-   20 D2 C5    JSR   $C5D2
0FE9-   D4          ???
0FEA-   D5 D2       CMP   $D2,X
0FEC-   CE D3 BA    DEC   $BAD3
0FEF-   20 A2 AC    JSR   $ACA2
0FF2-   B8          CLV
0FF3-   C4 B8       CPY   $B8
0FF5-   C4 8D       CPY   $8D
0FF7-   A0 C8       LDY   #$C8
0FF9-   C5 D8       CMP   $D8
0FFB-   C1 D3       CMP   ($D3,X)
0FFD-   C3          ???
0FFE-   A0 A3       LDY   #$A3
1000-   A4 C6       LDY   $C6
1002-   C6 8D       DEC   $8D
1004-   A0 C4       LDY   #$C4
1006-   D5 CD       CMP   $CD,X
1008-   D0 A0       BNE   $0FAA
100A-   A3          ???
100B-   D2 C5       CMP   ($C5)
100D-   D4          ???
100E-   D5 D2       CMP   $D2,X
1010-   CE BB D2    DEC   $D2BB
1013-   C5 D4       CMP   $D4
1015-   CC C5 CE    CPY   $CEC5
1018-   8D A0 DF    STA   $DFA0
101B-   D7          ???
101C-   C1 C9       CMP   ($C9,X)
101E-   D4          ???
101F-   8D AA 8D    STA   $8DAA
1022-   AA          TAX
1023-   AA          TAX
1024-   20 C1 D3    JSR   $D3C1
1027-   C3          ???
1028-   C8          INY
1029-   C5 D8       CMP   $D8
102B-   20 CD C1    JSR   $C1CD
102E-   C3          ???
102F-   D2 CF       CMP   ($CF)
1031-   8D AA 8D    STA   $8DAA
1034-   AA          TAX
1035-   AA          TAX
1036-   20 D5 D3    JSR   $D3D5
1039-   C1 C7       CMP   ($C7,X)
103B-   C5 BA       CMP   $BA
103D-   20 C1 D3    JSR   $D3C1
1040-   C3          ???
1041-   C8          INY
1042-   C5 D8       CMP   $D8
1044-   20 DB D3    JSR   $D3DB
1047-   D4          ???
1048-   D2 C9       CMP   ($C9)
104A-   CE C7 20    DEC   $20C7
104D-   CF          ???
104E-   D2 20       CMP   ($20)
1050-   C1 C4       CMP   ($C4,X)
1052-   C4 D2       CPY   $D2
1054-   C5 D3       CMP   $D3
1056-   D3          ???
1057-   DD 8D AA    CMP   $AA8D,X
105A-   8D A0 DF    STA   $DFA0
105D-   D0 D2       BNE   $1031
105F-   CE D4 A0    DEC   $A0D4
1062-   A2 20       LDX   #$20
1064-   A2 AC       LDX   #$AC
1066-   B8          CLV
1067-   C4 B8       CPY   $B8
1069-   C4 8D       CPY   $8D
106B-   A0 DF       LDY   #$DF
106D-   D0 D2       BNE   $1041
106F-   CE D4 A0    DEC   $A0D4
1072-   A2 D4       LDX   #$D4
1074-   C8          INY
1075-   C5 20       CMP   $20
1077-   C1 D3       CMP   ($D3,X)
1079-   C3          ???
107A-   C8          INY
107B-   C5 D8       CMP   $D8
107D-   20 CD C1    JSR   $C1CD
1080-   C3          ???
1081-   D2 CF       CMP   ($CF)
1083-   20 C4 CF    JSR   $CFC4
1086-   C5 D3       CMP   $D3
1088-   20 D4 C8    JSR   $C8D4
108B-   C5 A2       CMP   $A2
108D-   AC B8 C4    LDY   $C4B8
1090-   8D A0 DF    STA   $DFA0
1093-   D0 D2       BNE   $1067
1095-   CE D4 A0    DEC   $A0D4
1098-   A2 CF       LDX   #$CF
109A-   D0 D0       BNE   $106C
109C-   CF          ???
109D-   D3          ???
109E-   C9 D4       CMP   #$D4
10A0-   C5 20       CMP   $20
10A2-   CF          ???
10A3-   C6 20       DEC   $20
10A5-   C8          INY
10A6-   C5 D8       CMP   $D8
10A8-   C1 D3       CMP   ($D3,X)
10AA-   C3          ???
10AB-   BA          TSX
10AC-   20 C9 D4    JSR   $D4C9
10AF-   20 D4 D5    JSR   $D5D4
10B2-   D2 CE       CMP   ($CE)
10B4-   D3          ???
10B5-   20 C1 A2    JSR   $A2C1
10B8-   AC B8 C4    LDY   $C4B8
10BB-   8D A0 DF    STA   $DFA0
10BE-   D0 D2       BNE   $1092
10C0-   CE D4 A0    DEC   $A0D4
10C3-   A2 C8       LDX   #$C8
10C5-   C5 D8       CMP   $D8
10C7-   C1 C4       CMP   ($C4,X)
10C9-   C5 C3       CMP   $C3
10CB-   C9 CD       CMP   #$CD
10CD-   C1 CC       CMP   ($CC,X)
10CF-   20 D3 D4    JSR   $D4D3
10D2-   D2 C9       CMP   ($C9)
10D4-   CE C7 20    DEC   $20C7
10D7-   C9 CE       CMP   #$CE
10D9-   D4          ???
10DA-   CF          ???
10DB-   20 C9 D4    JSR   $D4C9
10DE-   D3          ???
10DF-   20 A2 AC    JSR   $ACA2
10E2-   B8          CLV
10E3-   C4 8D       CPY   $8D
10E5-   A0 DF       LDY   #$DF
10E7-   D0 D2       BNE   $10BB
10E9-   CE D4 A0    DEC   $A0D4
10EC-   A2 D6       LDX   #$D6
10EE-   C1 CC       CMP   ($CC,X)
10F0-   D5 C5       CMP   $C5,X
10F2-   20 C5 D1    JSR   $D1C5
10F5-   D5 C9       CMP   $C9,X
10F7-   D6 C1       DEC   $C1,X
10F9-   CC C5 CE    CPY   $CEC5
10FC-   D4          ???
10FD-   AE 20 20    LDX   $2020
1100-   20 20 A2    JSR   $A220
1103-   AC B8 C4    LDY   $C4B8
1106-   B8          CLV
1107-   C4 8D       CPY   $8D
1109-   A0 DF       LDY   #$DF
110B-   D0 D2       BNE   $10DF
110D-   CE D4 A0    DEC   $A0D4
1110-   A2 D3       LDX   #$D3
1112-   CF          ???
1113-   AC 20 C1    LDY   $C120
1116-   D3          ???
1117-   C3          ???
1118-   C8          INY
1119-   C5 D8       CMP   $D8
111B-   20 A7 C5    JSR   $C5A7
111E-   C5 A7       CMP   $A7
1120-   20 D2 C5    JSR   $C5D2
1123-   D4          ???
1124-   D5 D2       CMP   $D2,X
1126-   CE D3 BA    DEC   $BAD3
1129-   A2 AC       LDX   #$AC
112B-   B8          CLV
112C-   C4 B8       CPY   $B8
112E-   C4 8D       CPY   $8D
1130-   A0 C1       LDY   #$C1
1132-   D3          ???
1133-   C3          ???
1134-   C8          INY
1135-   C5 D8       CMP   $D8
1137-   A0 A2       LDY   #$A2
1139-   C5 C5       CMP   $C5
113B-   A2 8D       LDX   #$8D
113D-   A0 C4       LDY   #$C4
113F-   D5 CD       CMP   $CD,X
1141-   D0 A0       BNE   $10E3
1143-   A3          ???
1144-   D2 C5       CMP   ($C5)
1146-   D4          ???
1147-   D5 D2       CMP   $D2,X
1149-   CE BB D2    DEC   $D2BB
114C-   C5 D4       CMP   $D4
114E-   CC C5 CE    CPY   $CEC5
1151-   8D A0 DF    STA   $DFA0
1154-   D7          ???
1155-   C1 C9       CMP   ($C9,X)
1157-   D4          ???
1158-   8D AA 8D    STA   $8DAA
115B-   AA          TAX
115C-   AA          TAX
115D-   20 C2 C9    JSR   $C9C2
1160-   CE C1 D3    DEC   $D3C1
1163-   C3          ???
1164-   20 CD C1    JSR   $C1CD
1167-   C3          ???
1168-   D2 CF       CMP   ($CF)
116A-   8D AA 8D    STA   $8DAA
116D-   AA          TAX
116E-   AA          TAX
116F-   20 D5 D3    JSR   $D3D5
1172-   C1 C7       CMP   ($C7,X)
1174-   C5 BA       CMP   $BA
1176-   20 C2 C9    JSR   $C9C2
1179-   CE C1 D3    DEC   $D3C1
117C-   C3          ???
117D-   20 DB CC    JSR   $CCDB
1180-   C9 D4       CMP   #$D4
1182-   C5 D2       CMP   $D2
1184-   C1 CC       CMP   ($CC,X)
1186-   20 CF D2    JSR   $D2CF
1189-   20 C1 C4    JSR   $C4C1
118C-   C4 D2       CPY   $D2
118E-   C5 D3       CMP   $D3
1190-   D3          ???
1191-   DD 8D AA    CMP   $AA8D,X
1194-   8D A0 DF    STA   $DFA0
1197-   D0 D2       BNE   $116B
1199-   CE D4 A0    DEC   $A0D4
119C-   A2 20       LDX   #$20
119E-   A2 AC       LDX   #$AC
11A0-   B8          CLV
11A1-   C4 B8       CPY   $B8
11A3-   C4 8D       CPY   $8D
11A5-   A0 DF       LDY   #$DF
11A7-   D0 D2       BNE   $117B
11A9-   CE D4 A0    DEC   $A0D4
11AC-   A2 C2       LDX   #$C2
11AE-   C9 CE       CMP   #$CE
11B0-   C1 D3       CMP   ($D3,X)
11B2-   C3          ???
11B3-   20 D4 C1    JSR   $C1D4
11B6-   CB          ???
11B7-   C5 D3       CMP   $D3
11B9-   20 C1 20    JSR   $20C1
11BC-   D6 C1       DEC   $C1,X
11BE-   CC D5 C5    CPY   $C5D5
11C1-   20 C1 CE    JSR   $CEC1
11C4-   C4 20       CPY   $20
11C6-   D4          ???
11C7-   C8          INY
11C8-   C5 CE       CMP   $CE
11CA-   A2 AC       LDX   #$AC
11CC-   B8          CLV
11CD-   C4 8D       CPY   $8D
11CF-   A0 DF       LDY   #$DF
11D1-   D0 D2       BNE   $11A5
11D3-   CE D4 A0    DEC   $A0D4
11D6-   A2 D2       LDX   #$D2
11D8-   C5 D4       CMP   $D4
11DA-   D5 D2       CMP   $D2,X
11DC-   CE D3 20    DEC   $20D3
11DF-   C1 20       CMP   ($20,X)
11E1-   C2          ???
11E2-   C9 CE       CMP   #$CE
11E4-   C1 D2       CMP   ($D2,X)
11E6-   D9 20 D3    CMP   $D320,Y
11E9-   D4          ???
11EA-   D2 C9       CMP   ($C9)
11EC-   CE C7 20    DEC   $20C7
11EF-   CF          ???
11F0-   C6 20       DEC   $20
11F2-   D4          ???
11F3-   C8          INY
11F4-   C5 A2       CMP   $A2
11F6-   AC B8 C4    LDY   $C4B8
11F9-   8D A0 DF    STA   $DFA0
11FC-   D0 D2       BNE   $11D0
11FE-   CE D4 A0    DEC   $A0D4
1201-   A2 C2       LDX   #$C2
1203-   D9 D4 C5    CMP   $C5D4,Y
1206-   AE A2 AC    LDX   $ACA2
1209-   B8          CLV
120A-   C4 B8       CPY   $B8
120C-   C4 8D       CPY   $8D
120E-   A0 DF       LDY   #$DF
1210-   D0 D2       BNE   $11E4
1212-   CE D4 A0    DEC   $A0D4
1215-   A2 D4       LDX   #$D4
1217-   C8          INY
1218-   D5 D3       CMP   $D3,X
121A-   20 C2 C9    JSR   $C9C2
121D-   CE C1 D3    DEC   $D3C1
1220-   C3          ???
1221-   20 A3 A4    JSR   $A4A3
1224-   B0 C6       BCS   $11EC
1226-   20 D2 C5    JSR   $C5D2
1229-   D4          ???
122A-   D5 D2       CMP   $D2,X
122C-   CE D3 BA    DEC   $BAD3
122F-   A2 AC       LDX   #$AC
1231-   B8          CLV
1232-   C4 B8       CPY   $B8
1234-   C4 8D       CPY   $8D
1236-   A0 C2       LDY   #$C2
1238-   C9 CE       CMP   #$CE
123A-   C1 D3       CMP   ($D3,X)
123C-   C3          ???
123D-   A0 A3       LDY   #$A3
123F-   A4 B0       LDY   $B0
1241-   C6 8D       DEC   $8D
1243-   A0 C4       LDY   #$C4
1245-   D5 CD       CMP   $CD,X
1247-   D0 A0       BNE   $11E9
1249-   A3          ???
124A-   D2 C5       CMP   ($C5)
124C-   D4          ???
124D-   D5 D2       CMP   $D2,X
124F-   CE BB A3    DEC   $A3BB
1252-   B8          CLV
1253-   8D A0 DF    STA   $DFA0
1256-   D7          ???
1257-   C1 C9       CMP   ($C9,X)
1259-   D4          ???
125A-   8D AA 8D    STA   $8DAA
125D-   AA          TAX
125E-   AA          TAX
125F-   20 C1 D3    JSR   $D3C1
1262-   C3          ???
1263-   C2          ???
1264-   C9 CE       CMP   #$CE
1266-   20 CD C1    JSR   $C1CD
1269-   C3          ???
126A-   D2 CF       CMP   ($CF)
126C-   8D AA 8D    STA   $8DAA
126F-   AA          TAX
1270-   AA          TAX
1271-   20 D5 D3    JSR   $D3D5
1274-   C1 C7       CMP   ($C7,X)
1276-   C5 BA       CMP   $BA
1278-   20 C1 D3    JSR   $D3C1
127B-   C3          ???
127C-   C2          ???
127D-   C9 CE       CMP   #$CE
127F-   20 DB C2    JSR   $C2DB
1282-   C9 CE       CMP   #$CE
1284-   C1 D2       CMP   ($D2,X)
1286-   D9 20 D3    CMP   $D320,Y
1289-   D4          ???
128A-   D2 C9       CMP   ($C9)
128C-   CE C7 20    DEC   $20C7
128F-   CF          ???
1290-   D2 20       CMP   ($20)
1292-   C1 C4       CMP   ($C4,X)
1294-   C4 D2       CPY   $D2
1296-   C5 D3       CMP   $D3
1298-   D3          ???
1299-   DD 8D AA    CMP   $AA8D,X
129C-   8D A0 DF    STA   $DFA0
129F-   D0 D2       BNE   $1273
12A1-   CE D4 A0    DEC   $A0D4
12A4-   A2 C1       LDX   #$C1
12A6-   CE C4 20    DEC   $20C4
12A9-   C1 D3       CMP   ($D3,X)
12AB-   C3          ???
12AC-   C2          ???
12AD-   C9 CE       CMP   #$CE
12AF-   20 C4 CF    JSR   $CFC4
12B2-   C5 D3       CMP   $D3
12B4-   20 D4 C8    JSR   $C8D4
12B7-   C5 20       CMP   $20
12B9-   CF          ???
12BA-   D0 D0       BNE   $128C
12BC-   CF          ???
12BD-   D3          ???
12BE-   C9 D4       CMP   #$D4
12C0-   C5 BA       CMP   $BA
12C2-   A2 AC       LDX   #$AC
12C4-   B8          CLV
12C5-   C4 8D       CPY   $8D
12C7-   A0 DF       LDY   #$DF
12C9-   D0 D2       BNE   $129D
12CB-   CE D4 A0    DEC   $A0D4
12CE-   A2 C9       LDX   #$C9
12D0-   D4          ???
12D1-   20 D4 C1    JSR   $C1D4
12D4-   CB          ???
12D5-   C5 D3       CMP   $D3
12D7-   20 C1 20    JSR   $20C1
12DA-   C2          ???
12DB-   C9 CE       CMP   #$CE
12DD-   C1 D2       CMP   ($D2,X)
12DF-   D9 20 D3    CMP   $D320,Y
12E2-   D4          ???
12E3-   D2 C9       CMP   ($C9)
12E5-   CE C7 20    DEC   $20C7
12E8-   A8          TAY
12E9-   B8          CLV
12EA-   20 C4 C9    JSR   $C9C4
12ED-   C7          ???
12EE-   C9 D4       CMP   #$D4
12F0-   D3          ???
12F1-   A9 A2       LDA   #$A2
12F3-   AC B8 C4    LDY   $C4B8
12F6-   8D A0 DF    STA   $DFA0
12F9-   D0 D2       BNE   $12CD
12FB-   CE D4 A0    DEC   $A0D4
12FE-   A2 C1       LDX   #$C1
1300-   CE C4 20    DEC   $20C4
1303-   D2 C5       CMP   ($C5)
1305-   D4          ???
1306-   D5 D2       CMP   $D2,X
1308-   CE D3 20    DEC   $20D3
130B-   C9 D4       CMP   #$D4
130D-   D3          ???
130E-   20 C3 CF    JSR   $CFC3
1311-   D2 D2       CMP   ($D2)
1313-   C5 D3       CMP   $D3
1315-   D0 CF       BNE   $12E6
1317-   CE C4 C9    DEC   $C9C4
131A-   CE C7 20    DEC   $20C7
131D-   D6 C1       DEC   $C1,X
131F-   CC D5 C5    CPY   $C5D5
1322-   AE A2 AC    LDX   $ACA2
1325-   B8          CLV
1326-   C4 B8       CPY   $B8
1328-   C4 8D       CPY   $8D
132A-   A0 DF       LDY   #$DF
132C-   D0 D2       BNE   $1300
132E-   CE D4 A0    DEC   $A0D4
1331-   A2 D4       LDX   #$D4
1333-   C8          INY
1334-   D5 D3       CMP   $D3,X
1336-   AC 20 C1    LDY   $C120
1339-   D3          ???
133A-   C3          ???
133B-   C2          ???
133C-   C9 CE       CMP   #$CE
133E-   20 A7 B0    JSR   $B0A7
1341-   B0 B0       BCS   $12F3
1343-   B0 B1       BCS   $12F6
1345-   B1 B1       LDA   ($B1),Y
1347-   B1 A7       LDA   ($A7),Y
1349-   20 D2 C5    JSR   $C5D2
134C-   D4          ???
134D-   D5 D2       CMP   $D2,X
134F-   CE D3 BA    DEC   $BAD3
1352-   A2 AC       LDX   #$AC
1354-   B8          CLV
1355-   C4 B8       CPY   $B8
1357-   C4 8D       CPY   $8D
1359-   A0 C1       LDY   #$C1
135B-   D3          ???
135C-   C3          ???
135D-   C2          ???
135E-   C9 CE       CMP   #$CE
1360-   A0 A2       LDY   #$A2
1362-   B0 B0       BCS   $1314
1364-   B0 B0       BCS   $1316
1366-   B1 B1       LDA   ($B1),Y
1368-   B1 B1       LDA   ($B1),Y
136A-   A2 8D       LDX   #$8D
136C-   A0 C4       LDY   #$C4
136E-   D5 CD       CMP   $CD,X
1370-   D0 A0       BNE   $1312
1372-   A3          ???
1373-   D2 C5       CMP   ($C5)
1375-   D4          ???
1376-   D5 D2       CMP   $D2,X
1378-   CE BB A3    DEC   $A3BB
137B-   B1 8D       LDA   ($8D),Y
137D-   A0 DF       LDY   #$DF
137F-   D7          ???
1380-   C1 C9       CMP   ($C9,X)
1382-   D4          ???
1383-   8D AA 8D    STA   $8DAA
1386-   A0 DF       LDY   #$DF
1388-   D0 D2       BNE   $135C
138A-   CE D4 A0    DEC   $A0D4
138D-   A2 20       LDX   #$20
138F-   A2 AC       LDX   #$AC
1391-   B8          CLV
1392-   C4 B8       CPY   $B8
1394-   C4 B8       CPY   $B8
1396-   C4 8D       CPY   $8D
1398-   A0 DF       LDY   #$DF
139A-   D0 D2       BNE   $136E
139C-   CE D4 A0    DEC   $A0D4
139F-   A2 C6       LDX   #$C6
13A1-   C9 CE       CMP   #$CE
13A3-   AE A2 AC    LDX   $ACA2
13A6-   B8          CLV
13A7-   C4 B8       CPY   $B8
13A9-   C4 B8       CPY   $B8
13AB-   C4 8D       CPY   $8D
13AD-   AA          TAX
13AE-   8D AA 8D    STA   $8DAA
13B1-   AA          TAX
13B2-   8D A0 CA    STA   $CAA0
13B5-   CD D0 A0    CMP   $A0D0
13B8-   D2 C5       CMP   ($C5)
13BA-   C5 CE       CMP   $CE
13BC-   D4          ???
13BD-   D2 D9       CMP   ($D9)
13BF-   8D AA 8D    STA   $8DAA
13C2-   AA          TAX
13C3-   E0 E0       CPX   #$E0
13C5-   E0 E0       CPX   #$E0
13C7-   E0 E0       CPX   #$E0
13C9-   E0 E0       CPX   #$E0
13CB-   E0 E0       CPX   #$E0
13CD-   E0 E0       CPX   #$E0
13CF-   E0 E0       CPX   #$E0
13D1-   E0 E0       CPX   #$E0
13D3-   E0 E0       CPX   #$E0
13D5-   E0 E0       CPX   #$E0
13D7-   E0 E0       CPX   #$E0
13D9-   E0 E0       CPX   #$E0
13DB-   E0 E0       CPX   #$E0
13DD-   E0 E0       CPX   #$E0
13DF-   E0 E0       CPX   #$E0
13E1-   AA          TAX
13E2-   8D AA 20    STA   $20AA
13E5-   20 20 20    JSR   $2020
13E8-   20 20 20    JSR   $2020
13EB-   20 C2 CF    JSR   $CFC2
13EE-   D4          ???
13EF-   D4          ???
13F0-   CF          ???
13F1-   CD 20 C9    CMP   $C920
13F4-   CE C3 CC    DEC   $CCC3
13F7-   D5 C4       CMP   $C4,X
13F9-   C5 D3       CMP   $D3
13FB-   20 20 20    JSR   $2020
13FE-   20 20 20    JSR   $2020
1401-   20 AA 8D    JSR   $8DAA
1404-   AA          TAX
1405-   AC AC AC    LDY   $ACAC
1408-   AC AC AC    LDY   $ACAC
140B-   AC AC AC    LDY   $ACAC
140E-   AC AC AC    LDY   $ACAC
1411-   AC AC AC    LDY   $ACAC
1414-   AC AC AC    LDY   $ACAC
1417-   AC AC AC    LDY   $ACAC
141A-   AC AC AC    LDY   $ACAC
141D-   AC AC AC    LDY   $ACAC
1420-   AC AC AC    LDY   $ACAC
1423-   AA          TAX
1424-   8D AA 8D    STA   $8DAA
1427-   AA          TAX
1428-   AA          TAX
1429-   20 C2 CF    JSR   $CFC2
142C-   D4          ???
142D-   D4          ???
142E-   CF          ???
142F-   CD 20 C9    CMP   $C920
1432-   CE C3 CC    DEC   $CCC3
1435-   D5 C4       CMP   $C4,X
1437-   C5 D3       CMP   $D3
1439-   8D AA 8D    STA   $8DAA
143C-   A0 D0       LDY   #$D0
143E-   D5 D4       CMP   $D4,X
1440-   A0 CD       LDY   #$CD
1442-   C9 CE       CMP   #$CE
1444-   AE CC C9    LDX   $C9CC
1447-   C2          ???
1448-   AE D2 C5    LDX   $C5D2
144B-   D1 D5       CMP   ($D5),Y
144D-   C9 D2       CMP   #$D2
144F-   C5 C4       CMP   $C4
1451-   8D AA 8D    STA   $8DAA
1454-   AA          TAX
1455-   AA          TAX
1456-   20 C9 CE    JSR   $CEC9
1459-   C4 C9       CPY   $C9
145B-   D6 C9       DEC   $C9,X
145D-   C4 D5       CPY   $D5
145F-   C1 CC       CMP   ($CC,X)
1461-   20 D3 D5    JSR   $D5D3
1464-   C2          ???
1465-   D2 CF       CMP   ($CF)
1467-   D5 D4       CMP   $D4,X
1469-   C9 CE       CMP   #$CE
146B-   C5 20       CMP   $20
146D-   C9 CE       CMP   #$CE
146F-   C3          ???
1470-   CC D5 C4    CPY   $C4D5
1473-   C5 D3       CMP   $D3
1475-   8D AA 8D    STA   $8DAA
1478-   AA          TAX
1479-   AA          TAX
147A-   20 D3 D4    JSR   $D4D3
147D-   D2 C9       CMP   ($C9)
147F-   CE C7 20    DEC   $20C7
1482-   D3          ???
1483-   D5 C2       CMP   $C2,X
1485-   D2 CF       CMP   ($CF)
1487-   D5 D4       CMP   $D4,X
1489-   C9 CE       CMP   #$CE
148B-   C5 D3       CMP   $D3
148D-   8D AA 8D    STA   $8DAA
1490-   A0 D0       LDY   #$D0
1492-   D5 D4       CMP   $D4,X
1494-   A0 CD       LDY   #$CD
1496-   C9 CE       CMP   #$CE
1498-   AE D3 D5    LDX   $D5D3
149B-   C2          ???
149C-   AE C8 C5    LDX   $C5C8
149F-   D8          CLD
14A0-   B2 C9       LDA   ($C9)
14A2-   CE D4 C1    DEC   $C1D4
14A5-   D3          ???
14A6-   C3          ???
14A7-   8D A0 D0    STA   $D0A0
14AA-   D5 D4       CMP   $D4,X
14AC-   A0 CD       LDY   #$CD
14AE-   C9 CE       CMP   #$CE
14B0-   AE D3 D5    LDX   $D5D3
14B3-   C2          ???
14B4-   AE C9 CE    LDX   $CEC9
14B7-   D4          ???
14B8-   C1 D3       CMP   ($D3,X)
14BA-   C3          ???
14BB-   B2 C8       LDA   ($C8)
14BD-   C5 D8       CMP   $D8
14BF-   8D A0 D0    STA   $D0A0
14C2-   D5 D4       CMP   $D4,X
14C4-   A0 CD       LDY   #$CD
14C6-   C9 CE       CMP   #$CE
14C8-   AE D3 D5    LDX   $D5D3
14CB-   C2          ???
14CC-   AE C8 C5    LDX   $C5C8
14CF-   D8          CLD
14D0-   B2 C2       LDA   ($C2)
14D2-   C9 CE       CMP   #$CE
14D4-   C1 D3       CMP   ($D3,X)
14D6-   C3          ???
14D7-   8D A0 D0    STA   $D0A0
14DA-   D5 D4       CMP   $D4,X
14DC-   A0 CD       LDY   #$CD
14DE-   C9 CE       CMP   #$CE
14E0-   AE D3 D5    LDX   $D5D3
14E3-   C2          ???
14E4-   AE C2 C9    LDX   $C9C2
14E7-   CE C1 D3    DEC   $D3C1
14EA-   C3          ???
14EB-   B2 C8       LDA   ($C8)
14ED-   C5 D8       CMP   $D8
14EF-   8D A0 D0    STA   $D0A0
14F2-   D5 D4       CMP   $D4,X
14F4-   A0 CD       LDY   #$CD
14F6-   C9 CE       CMP   #$CE
14F8-   AE D3 D5    LDX   $D5D3
14FB-   C2          ???
14FC-   AE C8 C5    LDX   $C5C8
14FF-   D8          CLD
1500-   B2 C8       LDA   ($C8)
1502-   C5 D8       CMP   $D8
1504-   C1 D3       CMP   ($D3,X)
1506-   C3          ???
1507-   8D A0 D0    STA   $D0A0
150A-   D5 D4       CMP   $D4,X
150C-   A0 CD       LDY   #$CD
150E-   C9 CE       CMP   #$CE
1510-   AE D3 D5    LDX   $D5D3
1513-   C2          ???
1514-   AE C8 C5    LDX   $C5C8
1517-   D8          CLD
1518-   C1 D3       CMP   ($D3,X)
151A-   C3          ???
151B-   B2 C8       LDA   ($C8)
151D-   C5 D8       CMP   $D8
151F-   8D AA 8D    STA   $8DAA
