0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C3    LDY   $C320,X
0950-   CF          ???
0951-   CD CD CF    CMP   $CFCD
0954-   CE 20 C4    DEC   $C420
0957-   C5 CD       CMP   $CD
0959-   CF          ???
095A-   20 A9 AD    JSR   $ADA9
095D-   20 20 20    JSR   $2020
0960-   20 20 20    JSR   $2020
0963-   20 AA 8D    JSR   $8DAA
0966-   AA          TAX
0967-   20 20 20    JSR   $2020
096A-   20 20 20    JSR   $2020
096D-   20 20 20    JSR   $2020
0970-   20 20 20    JSR   $2020
0973-   20 20 20    JSR   $2020
0976-   20 20 20    JSR   $2020
0979-   20 20 20    JSR   $2020
097C-   20 20 20    JSR   $2020
097F-   20 20 20    JSR   $2020
0982-   20 20 20    JSR   $2020
0985-   AA          TAX
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   20 D6 C5    JSR   $C5D6
0992-   D2 D3       CMP   ($D3)
0994-   C9 CF       CMP   #$CF
0996-   CE 20 B0    DEC   $B020
0999-   AE B3 AE    LDX   $AEB3
099C-   B0 20       BCS   $09BE
099E-   20 20 20    JSR   $2020
09A1-   20 20 20    JSR   $2020
09A4-   20 20 AA    JSR   $AA20
09A7-   8D AA 20    STA   $20AA
09AA-   20 20 20    JSR   $2020
09AD-   20 20 20    JSR   $2020
09B0-   20 20 20    JSR   $2020
09B3-   20 20 20    JSR   $2020
09B6-   20 20 20    JSR   $2020
09B9-   20 20 20    JSR   $2020
09BC-   20 20 20    JSR   $2020
09BF-   20 20 20    JSR   $2020
09C2-   20 20 20    JSR   $2020
09C5-   20 20 AA    JSR   $AA20
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B1    JSR   $B120
09D4-   B0 AD       BCS   $0983
09D6-   CA          DEX
09D7-   C1 CE       CMP   ($CE,X)
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B9       LDA   ($B9),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 C4    STA   $C4A0
0B02-   D3          ???
0B03-   CB          ???
0B04-   A0 C3       LDY   #$C3
0B06-   CF          ???
0B07-   CD CD CF    CMP   $CFCD
0B0A-   CE AE C4    DEC   $C4AE
0B0D-   C5 CD       CMP   $CD
0B0F-   CF          ???
0B10-   8D A0 CF    STA   $CFA0
0B13-   C2          ???
0B14-   CA          DEX
0B15-   A0 A4       LDY   #$A4
0B17-   C2          ???
0B18-   C6 C5       DEC   $C5
0B1A-   B0 8D       BCS   $0AA9
0B1C-   A0 CF       LDY   #$CF
0B1E-   D2 C7       CMP   ($C7)
0B20-   A0 A4       LDY   #$A4
0B22-   B6 B0       LDX   $B0,Y
0B24-   B0 B0       BCS   $0AD6
0B26-   8D AA 8D    STA   $8DAA
0B29-   AA          TAX
0B2A-   E0 E0       CPX   #$E0
0B2C-   E0 E0       CPX   #$E0
0B2E-   E0 E0       CPX   #$E0
0B30-   E0 E0       CPX   #$E0
0B32-   E0 E0       CPX   #$E0
0B34-   E0 E0       CPX   #$E0
0B36-   E0 E0       CPX   #$E0
0B38-   E0 E0       CPX   #$E0
0B3A-   E0 E0       CPX   #$E0
0B3C-   E0 E0       CPX   #$E0
0B3E-   E0 E0       CPX   #$E0
0B40-   E0 E0       CPX   #$E0
0B42-   E0 E0       CPX   #$E0
0B44-   E0 E0       CPX   #$E0
0B46-   E0 E0       CPX   #$E0
0B48-   AA          TAX
0B49-   8D AA 20    STA   $20AA
0B4C-   20 D4 CF    JSR   $CFD4
0B4F-   D0 20       BNE   $0B71
0B51-   C9 CE       CMP   #$CE
0B53-   C3          ???
0B54-   CC D5 C4    CPY   $C4D5
0B57-   C5 D3       CMP   $D3
0B59-   20 A8 C8    JSR   $C8A8
0B5C-   CF          ???
0B5D-   CF          ???
0B5E-   CB          ???
0B5F-   D3          ???
0B60-   AC CD C1    LDY   $C1CD
0B63-   C3          ???
0B64-   D2 CF       CMP   ($CF)
0B66-   D3          ???
0B67-   A9 20       LDA   #$20
0B69-   AA          TAX
0B6A-   8D AA AC    STA   $ACAA
0B6D-   AC AC AC    LDY   $ACAC
0B70-   AC AC AC    LDY   $ACAC
0B73-   AC AC AC    LDY   $ACAC
0B76-   AC AC AC    LDY   $ACAC
0B79-   AC AC AC    LDY   $ACAC
0B7C-   AC AC AC    LDY   $ACAC
0B7F-   AC AC AC    LDY   $ACAC
0B82-   AC AC AC    LDY   $ACAC
0B85-   AC AC AC    LDY   $ACAC
0B88-   AC AC AA    LDY   $AAAC
0B8B-   8D AA 8D    STA   $8DAA
0B8E-   A0 D5       LDY   #$D5
0B90-   D3          ???
0B91-   C5 A0       CMP   $A0
0B93-   D2 C5       CMP   ($C5)
0B95-   D1 D5       CMP   ($D5),Y
0B97-   C9 D2       CMP   #$D2
0B99-   C5 C4       CMP   $C4
0B9B-   AE CD C1    LDX   $C1CD
0B9E-   C3          ???
0B9F-   AE CD C9    LDX   $C9CD
0BA2-   CE 8D A0    DEC   $A08D
0BA5-   D0 D5       BNE   $0B7C
0BA7-   D4          ???
0BA8-   A0 D2       LDY   #$D2
0BAA-   C5 D1       CMP   $D1
0BAC-   D5 C9       CMP   $C9,X
0BAE-   D2 C5       CMP   ($C5)
0BB0-   C4 AE       CPY   $AE
0BB2-   C8          INY
0BB3-   CF          ???
0BB4-   CF          ???
0BB5-   CB          ???
0BB6-   D3          ???
0BB7-   AE CD C9    LDX   $C9CD
0BBA-   CE 8D A0    DEC   $A08D
0BBD-   D5 D3       CMP   $D3,X
0BBF-   C5 A0       CMP   $A0
0BC1-   C3          ???
0BC2-   CF          ???
0BC3-   CD CD CF    CMP   $CFCD
0BC6-   CE AE CD    DEC   $CDAE
0BC9-   C1 C3       CMP   ($C3,X)
0BCB-   AE CD C9    LDX   $C9CD
0BCE-   CE 8D A0    DEC   $A08D
0BD1-   D0 D5       BNE   $0BA8
0BD3-   D4          ???
0BD4-   20 A0 C3    JSR   $C3A0
0BD7-   CF          ???
0BD8-   CD CD CF    CMP   $CFCD
0BDB-   CE AE C8    DEC   $C8AE
0BDE-   CF          ???
0BDF-   CF          ???
0BE0-   CB          ???
0BE1-   D3          ???
0BE2-   AE CD C9    LDX   $C9CD
0BE5-   CE 8D AA    DEC   $AA8D
0BE8-   8D AA E0    STA   $E0AA
0BEB-   E0 E0       CPX   #$E0
0BED-   E0 E0       CPX   #$E0
0BEF-   E0 E0       CPX   #$E0
0BF1-   E0 E0       CPX   #$E0
0BF3-   E0 E0       CPX   #$E0
0BF5-   E0 E0       CPX   #$E0
0BF7-   E0 E0       CPX   #$E0
0BF9-   E0 E0       CPX   #$E0
0BFB-   E0 E0       CPX   #$E0
0BFD-   E0 E0       CPX   #$E0
0BFF-   E0 E0       CPX   #$E0
0C01-   E0 E0       CPX   #$E0
0C03-   E0 E0       CPX   #$E0
0C05-   E0 E0       CPX   #$E0
0C07-   E0 AA       CPX   #$AA
0C09-   8D AA 20    STA   $20AA
0C0C-   20 20 20    JSR   $2020
0C0F-   20 20 D0    JSR   $D020
0C12-   D2 CF       CMP   ($CF)
0C14-   C7          ???
0C15-   D2 C1       CMP   ($C1)
0C17-   CD 20 CD    CMP   $CD20
0C1A-   C1 C9       CMP   ($C9,X)
0C1C-   CE 20 C2    DEC   $C220
0C1F-   CF          ???
0C20-   C4 D9       CPY   $D9
0C22-   20 20 20    JSR   $2020
0C25-   20 20 20    JSR   $2020
0C28-   20 AA 8D    JSR   $8DAA
0C2B-   AA          TAX
0C2C-   AC AC AC    LDY   $ACAC
0C2F-   AC AC AC    LDY   $ACAC
0C32-   AC AC AC    LDY   $ACAC
0C35-   AC AC AC    LDY   $ACAC
0C38-   AC AC AC    LDY   $ACAC
0C3B-   AC AC AC    LDY   $ACAC
0C3E-   AC AC AC    LDY   $ACAC
0C41-   AC AC AC    LDY   $ACAC
0C44-   AC AC AC    LDY   $ACAC
0C47-   AC AC AC    LDY   $ACAC
0C4A-   AA          TAX
0C4B-   8D AA 8D    STA   $8DAA
0C4E-   AA          TAX
0C4F-   AA          TAX
0C50-   20 CD C6    JSR   $C6CD
0C53-   C9 CC       CMP   #$CC
0C55-   CC 20 C4    CPY   $C420
0C58-   CF          ???
0C59-   C5 D3       CMP   $D3
0C5B-   20 C1 C2    JSR   $C2C1
0C5E-   CF          ???
0C5F-   D5 D4       CMP   $D4,X
0C61-   20 D7 C8    JSR   $C8D7
0C64-   C1 D4       CMP   ($D4,X)
0C66-   20 C9 D4    JSR   $D4C9
0C69-   D3          ???
0C6A-   20 CE C1    JSR   $C1CE
0C6D-   CD C5 8D    CMP   $8DC5
0C70-   AA          TAX
0C71-   AA          TAX
0C72-   20 C9 CD    JSR   $CDC9
0C75-   D0 CC       BNE   $0C43
0C77-   C9 C5       CMP   #$C5
0C79-   D3          ???
0C7A-   BA          TSX
0C7B-   20 C9 D4    JSR   $D4C9
0C7E-   20 C6 C9    JSR   $C9C6
0C81-   CC CC D3    CPY   $D3CC
0C84-   20 C1 20    JSR   $20C1
0C87-   C2          ???
0C88-   CC CF C3    CPY   $C3CF
0C8B-   CB          ???
0C8C-   20 CF C6    JSR   $C6CF
0C8F-   20 CD C5    JSR   $C5CD
0C92-   CD CF D2    CMP   $D2CF
0C95-   D9 8D AA    CMP   $AA8D,Y
0C98-   AA          TAX
0C99-   20 D7 C9    JSR   $C9D7
0C9C-   D4          ???
0C9D-   C8          INY
0C9E-   20 C1 20    JSR   $20C1
0CA1-   D0 C1       BNE   $0C64
0CA3-   D2 D4       CMP   ($D4)
0CA5-   C9 C3       CMP   #$C3
0CA7-   D5 CC       CMP   $CC,X
0CA9-   C1 D2       CMP   ($D2,X)
0CAB-   20 C3 C8    JSR   $C8C3
0CAE-   C1 D2       CMP   ($D2,X)
0CB0-   C1 C3       CMP   ($C3,X)
0CB2-   D4          ???
0CB3-   C5 D2       CMP   $D2
0CB5-   AE 8D AA    LDX   $AA8D
0CB8-   8D A0 CD    STA   $CDA0
0CBB-   C6 C9       DEC   $C9
0CBD-   CC CC A0    CPY   $A0CC
0CC0-   A3          ???
0CC1-   A4 B3       LDY   $B3
0CC3-   B0 B0       BCS   $0C75
0CC5-   BB          ???
0CC6-   A3          ???
0CC7-   B1 B0       LDA   ($B0),Y
0CC9-   BB          ???
0CCA-   A3          ???
0CCB-   B0 8D       BCS   $0C5A
0CCD-   A0 DF       LDY   #$DF
0CCF-   D0 D2       BNE   $0CA3
0CD1-   CE D4 A0    DEC   $A0D4
0CD4-   A2 CD       LDX   #$CD
0CD6-   C6 C9       DEC   $C9
0CD8-   CC CC 20    CPY   $20CC
0CDB-   C6 C9       DEC   $C9
0CDD-   CC CC D3    CPY   $D3CC
0CE0-   20 C1 20    JSR   $20C1
0CE3-   D0 CF       BNE   $0CB4
0CE5-   D2 D4       CMP   ($D4)
0CE7-   C9 CF       CMP   #$CF
0CE9-   CE 20 CF    DEC   $CF20
0CEC-   C6 20       DEC   $20
0CEE-   CD C5 CD    CMP   $CDC5
0CF1-   CF          ???
0CF2-   D2 D9       CMP   ($D9)
0CF4-   20 D7 C9    JSR   $C9D7
0CF7-   D4          ???
0CF8-   C8          INY
0CF9-   A2 AC       LDX   #$AC
0CFB-   B8          CLV
0CFC-   C4 8D       CPY   $8D
0CFE-   A0 DF       LDY   #$DF
0D00-   D0 D2       BNE   $0CD4
0D02-   CE D4 A0    DEC   $A0D4
0D05-   A2 C1       LDX   #$C1
0D07-   20 D3 D0    JSR   $D0D3
0D0A-   C5 C3       CMP   $C3
0D0C-   C9 C6       CMP   #$C6
0D0E-   C9 C5       CMP   #$C5
0D10-   C4 20       CPY   $20
0D12-   D6 C1       DEC   $C1,X
0D14-   CC D5 C5    CPY   $C5D5
0D17-   AE 20 A2    LDX   $A220
0D1A-   AC B8 C4    LDY   $C4B8
0D1D-   B8          CLV
0D1E-   C4 8D       CPY   $8D
0D20-   A0 DF       LDY   #$DF
0D22-   C4 D5       CPY   $D5
0D24-   CD D0 A0    CMP   $A0D0
0D27-   A4 B3       LDY   $B3
0D29-   B0 B0       BCS   $0CDB
0D2B-   BB          ???
0D2C-   A3          ???
0D2D-   B1 B0       LDA   ($B0),Y
0D2F-   8D A0 DF    STA   $DFA0
0D32-   D7          ???
0D33-   C1 C9       CMP   ($C9,X)
0D35-   D4          ???
0D36-   8D AA 8D    STA   $8DAA
0D39-   AA          TAX
0D3A-   AA          TAX
0D3B-   20 CD CD    JSR   $CDCD
0D3E-   CF          ???
0D3F-   D6 C5       DEC   $C5,X
0D41-   20 C1 CC    JSR   $CCC1
0D44-   D3          ???
0D45-   CF          ???
0D46-   20 C4 CF    JSR   $CFC4
0D49-   C5 D3       CMP   $D3
0D4B-   20 D7 C8    JSR   $C8D7
0D4E-   C1 D4       CMP   ($D4,X)
0D50-   20 C9 D4    JSR   $D4C9
0D53-   20 D3 C1    JSR   $C1D3
0D56-   D9 D3 BA    CMP   $BAD3,Y
0D59-   20 C9 D4    JSR   $D4C9
0D5C-   20 CD CF    JSR   $CFCD
0D5F-   D6 C5       DEC   $C5,X
0D61-   D3          ???
0D62-   8D AA AA    STA   $AAAA
0D65-   20 C1 20    JSR   $20C1
0D68-   C2          ???
0D69-   CC CF C3    CPY   $C3CF
0D6C-   CB          ???
0D6D-   20 CF C6    JSR   $C6CF
0D70-   20 CD C5    JSR   $C5CD
0D73-   CD CF D2    CMP   $D2CF
0D76-   D9 20 C6    CMP   $C620,Y
0D79-   D2 CF       CMP   ($CF)
0D7B-   CD 20 C1    CMP   $C120
0D7E-   20 D3 CF    JSR   $CFD3
0D81-   D5 D2       CMP   $D2,X
0D83-   C3          ???
0D84-   C5 20       CMP   $20
0D86-   CC CF C3    CPY   $C3CF
0D89-   C1 D4       CMP   ($D4,X)
0D8B-   C9 CF       CMP   #$CF
0D8D-   CE 8D AA    DEC   $AA8D
0D90-   AA          TAX
0D91-   20 D4 CF    JSR   $CFD4
0D94-   20 C1 20    JSR   $20C1
0D97-   C4 C5       CPY   $C5
0D99-   D3          ???
0D9A-   D4          ???
0D9B-   C9 CE       CMP   #$CE
0D9D-   C1 D4       CMP   ($D4,X)
0D9F-   C9 CF       CMP   #$CF
0DA1-   CE 20 CC    DEC   $CC20
0DA4-   CF          ???
0DA5-   C3          ???
0DA6-   C1 D4       CMP   ($D4,X)
0DA8-   C9 CF       CMP   #$CF
0DAA-   CE AE 20    DEC   $20AE
0DAD-   D7          ???
0DAE-   C5 A7       CMP   $A7
0DB0-   CC CC 20    CPY   $20CC
0DB3-   CE CF D7    DEC   $D7CF
0DB6-   20 CD CF    JSR   $CFCD
0DB9-   D6 C5       DEC   $C5,X
0DBB-   8D AA AA    STA   $AAAA
0DBE-   20 D4 C8    JSR   $C8D4
0DC1-   CF          ???
0DC2-   D3          ???
0DC3-   C5 20       CMP   $20
0DC5-   DA          PHX
0DC6-   C5 D2       CMP   $D2
0DC8-   CF          ???
0DC9-   C5 D3       CMP   $D3
0DCB-   20 D0 CC    JSR   $CCD0
0DCE-   C1 C3       CMP   ($C3,X)
0DD0-   C5 C4       CMP   $C4
0DD2-   20 C2 D9    JSR   $D9C2
0DD5-   20 CD C5    JSR   $C5CD
0DD8-   CD C6 C9    CMP   $C9C6
0DDB-   CC CC 20    CPY   $20CC
0DDE-   D4          ???
0DDF-   CF          ???
0DE0-   20 C1 CE    JSR   $CEC1
0DE3-   CF          ???
0DE4-   D4          ???
0DE5-   C8          INY
0DE6-   C5 D2       CMP   $D2
0DE8-   8D AA AA    STA   $AAAA
0DEB-   20 CC CF    JSR   $CFCC
0DEE-   C3          ???
0DEF-   C1 D4       CMP   ($D4,X)
0DF1-   C9 CF       CMP   #$CF
0DF3-   CE AE 8D    DEC   $8DAE
0DF6-   AA          TAX
0DF7-   8D A0 DF    STA   $DFA0
0DFA-   D0 D2       BNE   $0DCE
0DFC-   CE D4 A0    DEC   $A0D4
0DFF-   A2 20       LDX   #$20
0E01-   A2 AC       LDX   #$AC
0E03-   B8          CLV
0E04-   C4 B8       CPY   $B8
0E06-   C4 8D       CPY   $8D
0E08-   A0 DF       LDY   #$DF
0E0A-   D0 D2       BNE   $0DDE
0E0C-   CE D4 A0    DEC   $A0D4
0E0F-   A2 CD       LDX   #$CD
0E11-   CD CF D6    CMP   $D6CF
0E14-   C5 20       CMP   $20
0E16-   C3          ???
0E17-   CF          ???
0E18-   D0 C9       BNE   $0DE3
0E1A-   C5 D3       CMP   $D3
0E1C-   20 C1 20    JSR   $20C1
0E1F-   D3          ???
0E20-   D0 C1       BNE   $0DE3
0E22-   CE 20 CF    DEC   $CF20
0E25-   C6 20       DEC   $20
0E27-   CD C5 CD    CMP   $CDC5
0E2A-   CF          ???
0E2B-   D2 D9       CMP   ($D9)
0E2D-   A2 AC       LDX   #$AC
0E2F-   B8          CLV
0E30-   C4 8D       CPY   $8D
0E32-   A0 DF       LDY   #$DF
0E34-   D0 D2       BNE   $0E08
0E36-   CE D4 A0    DEC   $A0D4
0E39-   A2 C6       LDX   #$C6
0E3B-   D2 CF       CMP   ($CF)
0E3D-   CD 20 C1    CMP   $C120
0E40-   20 D3 CF    JSR   $CFD3
0E43-   D5 D2       CMP   $D2,X
0E45-   C3          ???
0E46-   C5 20       CMP   $20
0E48-   D4          ???
0E49-   CF          ???
0E4A-   20 C1 20    JSR   $20C1
0E4D-   C4 C5       CPY   $C5
0E4F-   D3          ???
0E50-   D4          ???
0E51-   C9 CE       CMP   #$CE
0E53-   C1 D4       CMP   ($D4,X)
0E55-   C9 CF       CMP   #$CF
0E57-   CE 20 C1    DEC   $C120
0E5A-   C4 C4       CPY   $C4
0E5C-   D2 C5       CMP   ($C5)
0E5E-   D3          ???
0E5F-   D3          ???
0E60-   AE A2 AC    LDX   $ACA2
0E63-   B8          CLV
0E64-   C4 B8       CPY   $B8
0E66-   C4 8D       CPY   $8D
0E68-   A0 DF       LDY   #$DF
0E6A-   D0 D2       BNE   $0E3E
0E6C-   CE D4 A0    DEC   $A0D4
0E6F-   A2 D3       LDX   #$D3
0E71-   CF          ???
0E72-   20 CD CF    JSR   $CFCD
0E75-   D6 C9       DEC   $C9,X
0E77-   CE C7 20    DEC   $20C7
0E7A-   A4 B3       LDY   $B3
0E7C-   B0 B0       BCS   $0E2E
0E7E-   20 D4 CF    JSR   $CFD4
0E81-   20 A4 B3    JSR   $B3A4
0E84-   B2 B0       LDA   ($B0)
0E86-   20 D2 C5    JSR   $C5D2
0E89-   D3          ???
0E8A-   D5 CC       CMP   $CC,X
0E8C-   D4          ???
0E8D-   D3          ???
0E8E-   20 C9 CE    JSR   $CEC9
0E91-   BA          TSX
0E92-   A2 AC       LDX   #$AC
0E94-   B8          CLV
0E95-   C4 B8       CPY   $B8
0E97-   C4 8D       CPY   $8D
0E99-   A0 CD       LDY   #$CD
0E9B-   CD CF D6    CMP   $D6CF
0E9E-   C5 A0       CMP   $A0
0EA0-   A4 B3       LDY   $B3
0EA2-   B0 B0       BCS   $0E54
0EA4-   BB          ???
0EA5-   A4 B3       LDY   $B3
0EA7-   B2 B0       LDA   ($B0)
0EA9-   BB          ???
0EAA-   A3          ???
0EAB-   B1 B0       LDA   ($B0),Y
0EAD-   8D A0 DF    STA   $DFA0
0EB0-   C4 D5       CPY   $D5
0EB2-   CD D0 A0    CMP   $A0D0
0EB5-   A4 B3       LDY   $B3
0EB7-   B2 B0       LDA   ($B0)
0EB9-   BB          ???
0EBA-   A3          ???
0EBB-   B1 B0       LDA   ($B0),Y
0EBD-   8D A0 DF    STA   $DFA0
0EC0-   D7          ???
0EC1-   C1 C9       CMP   ($C9,X)
0EC3-   D4          ???
0EC4-   8D AA 8D    STA   $8DAA
0EC7-   AA          TAX
0EC8-   AA          TAX
0EC9-   20 C4 C5    JSR   $C5C4
0ECC-   CC C1 D9    CPY   $D9C1
0ECF-   20 D2 D5    JSR   $D5D2
0ED2-   CE D3 20    DEC   $20D3
0ED5-   D4          ???
0ED6-   C8          INY
0ED7-   D2 CF       CMP   ($CF)
0ED9-   D5 C7       CMP   $C7,X
0EDB-   C8          INY
0EDC-   20 C3 D9    JSR   $D9C3
0EDF-   C3          ???
0EE0-   CC C5 D3    CPY   $D3C5
0EE3-   20 CF C6    JSR   $C6CF
0EE6-   20 D4 C8    JSR   $C8D4
0EE9-   C5 8D       CMP   $8D
0EEB-   AA          TAX
0EEC-   AA          TAX
0EED-   20 B6 B5    JSR   $B5B6
0EF0-   B0 B2       BCS   $0EA4
0EF2-   20 D5 CE    JSR   $CED5
0EF5-   D4          ???
0EF6-   C9 CC       CMP   #$CC
0EF8-   20 C1 20    JSR   $20C1
0EFB-   C3          ???
0EFC-   C5 D2       CMP   $D2
0EFE-   D4          ???
0EFF-   C1 C9       CMP   ($C9,X)
0F01-   CE 20 C1    DEC   $C120
0F04-   CD CF D5    CMP   $D5CF
0F07-   CE D4 20    DEC   $20D4
0F0A-   CF          ???
0F0B-   C6 20       DEC   $20
0F0D-   D4          ???
0F0E-   C9 CD       CMP   #$CD
0F10-   C5 8D       CMP   $8D
0F12-   AA          TAX
0F13-   AA          TAX
0F14-   20 C8 C1    JSR   $C1C8
0F17-   D3          ???
0F18-   20 D0 C1    JSR   $C1D0
0F1B-   D3          ???
0F1C-   D3          ???
0F1D-   C5 C4       CMP   $C4
0F1F-   AE 8D AA    LDX   $AA8D
0F22-   8D A0 DF    STA   $DFA0
0F25-   D0 D2       BNE   $0EF9
0F27-   CE D4 A0    DEC   $A0D4
0F2A-   A2 20       LDX   #$20
0F2C-   A2 AC       LDX   #$AC
0F2E-   B8          CLV
0F2F-   C4 B8       CPY   $B8
0F31-   C4 8D       CPY   $8D
0F33-   A0 DF       LDY   #$DF
0F35-   D0 D2       BNE   $0F09
0F37-   CE D4 A0    DEC   $A0D4
0F3A-   A2 C4       LDX   #$C4
0F3C-   C5 CC       CMP   $CC
0F3E-   C1 D9       CMP   ($D9,X)
0F40-   20 C4 C5    JSR   $C5C4
0F43-   CC C1 D9    CPY   $D9C1
0F46-   D3          ???
0F47-   20 C1 20    JSR   $20C1
0F4A-   D3          ???
0F4B-   D0 C5       BNE   $0F12
0F4D-   C3          ???
0F4E-   C9 C6       CMP   #$C6
0F50-   C9 C5       CMP   #$C5
0F52-   C4 20       CPY   $20
0F54-   CE D5 CD    DEC   $CDD5
0F57-   C2          ???
0F58-   C5 D2       CMP   $D2
0F5A-   20 CF C6    JSR   $C6CF
0F5D-   A2 AC       LDX   #$AC
0F5F-   B8          CLV
0F60-   C4 8D       CPY   $8D
0F62-   A0 DF       LDY   #$DF
0F64-   D0 D2       BNE   $0F38
0F66-   CE D4 A0    DEC   $A0D4
0F69-   A2 CD       LDX   #$CD
0F6B-   C9 CC       CMP   #$CC
0F6D-   CC C9 D3    CPY   $D3C9
0F70-   C5 C3       CMP   $C3
0F72-   CF          ???
0F73-   CE C4 D3    DEC   $D3C4
0F76-   AE 20 B2    LDX   $B220
0F79-   B5 B0       LDA   $B0,X
0F7B-   20 CD C9    JSR   $C9CD
0F7E-   CC CC C9    CPY   $C9CC
0F81-   D3          ???
0F82-   C5 C3       CMP   $C3
0F84-   CF          ???
0F85-   CE C4 D3    DEC   $D3C4
0F88-   20 BD 20    JSR   $20BD
0F8B-   B1 AF       LDA   ($AF),Y
0F8D-   B4 20       LDY   $20,X
0F8F-   D3          ???
0F90-   C5 C3       CMP   $C3
0F92-   CF          ???
0F93-   CE C4 AE    DEC   $AEC4
0F96-   A2 AC       LDX   #$AC
0F98-   B8          CLV
0F99-   C4 B8       CPY   $B8
0F9B-   C4 8D       CPY   $8D
0F9D-   AA          TAX
0F9E-   8D A0 C4    STA   $C4A0
0FA1-   C5 CC       CMP   $CC
0FA3-   C1 D9       CMP   ($D9,X)
0FA5-   A0 A3       LDY   #$A3
0FA7-   B2 B5       LDA   ($B5)
0FA9-   B0 A0       BCS   $0F4B
0FAB-   BB          ???
0FAC-   20 20 D4    JSR   $D420
0FAF-   C9 CD       CMP   #$CD
0FB1-   C5 20       CMP   $20
0FB3-   C9 CE       CMP   #$CE
0FB5-   20 CD C9    JSR   $C9CD
0FB8-   CC CC C9    CPY   $C9CC
0FBB-   D3          ???
0FBC-   C5 C3       CMP   $C3
0FBE-   CF          ???
0FBF-   CE C4 D3    DEC   $D3C4
0FC2-   8D BB 20    STA   $20BB
0FC5-   C9 D3       CMP   #$D3
0FC7-   20 D0 C1    JSR   $C1D0
0FCA-   D3          ???
0FCB-   D3          ???
0FCC-   C5 C4       CMP   $C4
0FCE-   20 D6 C9    JSR   $C9D6
0FD1-   C1 20       CMP   ($20,X)
0FD3-   D9 8D BB    CMP   $BB8D,Y
0FD6-   20 B2 B5    JSR   $B5B2
0FD9-   B0 20       BCS   $0FFB
0FDB-   BD 20 B1    LDA   $B120,X
0FDE-   AF          ???
0FDF-   B4 20       LDY   $20,X
0FE1-   D3          ???
0FE2-   C5 C3       CMP   $C3
0FE4-   CF          ???
0FE5-   CE C4 8D    DEC   $8DC4
0FE8-   A0 C2       LDY   #$C2
0FEA-   C5 C5       CMP   $C5
0FEC-   D0 A0       BNE   $0F8E
0FEE-   B1 8D       LDA   ($8D),Y
0FF0-   A0 DF       LDY   #$DF
0FF2-   D0 D2       BNE   $0FC6
0FF4-   CE D4 A0    DEC   $A0D4
0FF7-   A2 B1       LDX   #$B1
0FF9-   AF          ???
0FFA-   B4 20       LDY   $20,X
0FFC-   D3          ???
0FFD-   C5 C3       CMP   $C3
0FFF-   CF          ???
1000-   CE C4 A2    DEC   $A2C4
1003-   AC B8 C4    LDY   $C4B8
1006-   8D A0 C4    STA   $C4A0
1009-   C5 CC       CMP   $CC
100B-   C1 D9       CMP   ($D9,X)
100D-   A0 A3       LDY   #$A3
100F-   B2 B5       LDA   ($B5)
1011-   B0 8D       BCS   $0FA0
1013-   A0 C2       LDY   #$C2
1015-   C5 C5       CMP   $C5
1017-   D0 A0       BNE   $0FB9
1019-   B2 8D       LDA   ($8D)
101B-   A0 DF       LDY   #$DF
101D-   D0 D2       BNE   $0FF1
101F-   CE D4 A0    DEC   $A0D4
1022-   A2 B1       LDX   #$B1
1024-   AF          ???
1025-   B4 20       LDY   $20,X
1027-   D3          ???
1028-   C5 C3       CMP   $C3
102A-   CF          ???
102B-   CE C4 A2    DEC   $A2C4
102E-   AC B8 C4    LDY   $C4B8
1031-   8D A0 C4    STA   $C4A0
1034-   C5 CC       CMP   $CC
1036-   C1 D9       CMP   ($D9,X)
1038-   A0 A3       LDY   #$A3
103A-   B2 B5       LDA   ($B5)
103C-   B0 8D       BCS   $0FCB
103E-   A0 C2       LDY   #$C2
1040-   C5 C5       CMP   $C5
1042-   D0 A0       BNE   $0FE4
1044-   B3          ???
1045-   8D A0 DF    STA   $DFA0
1048-   D0 D2       BNE   $101C
104A-   CE D4 A0    DEC   $A0D4
104D-   A2 B1       LDX   #$B1
104F-   AF          ???
1050-   B4 20       LDY   $20,X
1052-   D3          ???
1053-   C5 C3       CMP   $C3
1055-   CF          ???
1056-   CE C4 A2    DEC   $A2C4
1059-   AC B8 C4    LDY   $C4B8
105C-   8D A0 C4    STA   $C4A0
105F-   C5 CC       CMP   $CC
1061-   C1 D9       CMP   ($D9,X)
1063-   A0 A3       LDY   #$A3
1065-   B2 B5       LDA   ($B5)
1067-   B0 8D       BCS   $0FF6
1069-   A0 C2       LDY   #$C2
106B-   C5 C5       CMP   $C5
106D-   D0 A0       BNE   $100F
106F-   B4 8D       LDY   $8D,X
1071-   A0 DF       LDY   #$DF
1073-   D0 D2       BNE   $1047
1075-   CE D4 A0    DEC   $A0D4
1078-   A2 B1       LDX   #$B1
107A-   AF          ???
107B-   B4 20       LDY   $20,X
107D-   D3          ???
107E-   C5 C3       CMP   $C3
1080-   CF          ???
1081-   CE C4 A2    DEC   $A2C4
1084-   AC B8 C4    LDY   $C4B8
1087-   8D AA 8D    STA   $8DAA
108A-   A0 DF       LDY   #$DF
108C-   D0 D2       BNE   $1060
108E-   CE D4 A0    DEC   $A0D4
1091-   A2 20       LDX   #$20
1093-   A2 AC       LDX   #$AC
1095-   B8          CLV
1096-   C4 B8       CPY   $B8
1098-   C4 8D       CPY   $8D
109A-   A0 DF       LDY   #$DF
109C-   D7          ???
109D-   C1 C9       CMP   ($C9,X)
109F-   D4          ???
10A0-   8D AA 8D    STA   $8DAA
10A3-   AA          TAX
10A4-   AA          TAX
10A5-   20 DA D3    JSR   $D3DA
10A8-   C1 D6       CMP   ($D6,X)
10AA-   C5 20       CMP   $20
10AC-   C2          ???
10AD-   C1 C3       CMP   ($C3,X)
10AF-   CB          ???
10B0-   D3          ???
10B1-   20 D5 D0    JSR   $D0D5
10B4-   20 D4 C8    JSR   $C8D4
10B7-   C5 20       CMP   $20
10B9-   A2 C6       LDX   #$C6
10BB-   D2 C5       CMP   ($C5)
10BD-   C5 A2       CMP   $A2
10BF-   20 C1 D2    JSR   $D2C1
10C2-   C5 C1       CMP   $C1
10C4-   D3          ???
10C5-   20 CF C6    JSR   $C6CF
10C8-   8D AA AA    STA   $AAAA
10CB-   20 D4 C8    JSR   $C8D4
10CE-   C5 20       CMP   $20
10D0-   DA          PHX
10D1-   C5 D2       CMP   $D2
10D3-   CF          ???
10D4-   20 D0 C1    JSR   $C1D0
10D7-   C7          ???
10D8-   C5 20       CMP   $20
10DA-   D4          ???
10DB-   CF          ???
10DC-   20 C1 CE    JSR   $CEC1
10DF-   20 C1 CC    JSR   $CCC1
10E2-   D4          ???
10E3-   C5 D2       CMP   $D2
10E5-   CE C1 D4    DEC   $D4C1
10E8-   C5 20       CMP   $20
10EA-   CD C5 CD    CMP   $CDC5
10ED-   CF          ???
10EE-   D2 D9       CMP   ($D9)
10F0-   8D AA AA    STA   $AAAA
10F3-   20 CC CF    JSR   $CFCC
10F6-   C3          ???
10F7-   C1 D4       CMP   ($D4,X)
10F9-   C9 CF       CMP   #$CF
10FB-   CE AE 20    DEC   $20AE
10FE-   D4          ???
10FF-   C8          INY
1100-   C9 D3       CMP   #$D3
1102-   20 C9 D3    JSR   $D3C9
1105-   20 CD CF    JSR   $CFCD
1108-   D3          ???
1109-   D4          ???
110A-   CC D9 20    CPY   $20D9
110D-   D5 D3       CMP   $D3,X
110F-   C5 C6       CMP   $C6
1111-   D5 CC       CMP   $CC,X
1113-   20 D7 C8    JSR   $C8D7
1116-   C5 CE       CMP   $CE
1118-   8D AA AA    STA   $AAAA
111B-   20 D9 CF    JSR   $CFD9
111E-   D5 20       CMP   $20,X
1120-   CB          ???
1121-   CE CF D7    DEC   $D7CF
1124-   20 C1 20    JSR   $20C1
1127-   D2 CF       CMP   ($CF)
1129-   D5 D4       CMP   $D4,X
112B-   C9 CE       CMP   #$CE
112D-   C5 20       CMP   $20
112F-   D5 D3       CMP   $D3,X
1131-   C5 D3       CMP   $D3
1133-   20 D4 C8    JSR   $C8D4
1136-   C5 20       CMP   $20
1138-   DA          PHX
1139-   C5 D2       CMP   $D2
113B-   CF          ???
113C-   20 D0 C1    JSR   $C1D0
113F-   C7          ???
1140-   C5 AC       CMP   $AC
1142-   8D AA AA    STA   $AAAA
1145-   20 C2 D5    JSR   $D5C2
1148-   D4          ???
1149-   20 D9 CF    JSR   $CFD9
114C-   D5 20       CMP   $20,X
114E-   D7          ???
114F-   C1 CE       CMP   ($CE,X)
1151-   D4          ???
1152-   20 D4 CF    JSR   $CFD4
1155-   20 CB C5    JSR   $C5CB
1158-   C5 D0       CMP   $D0
115A-   20 D4 C8    JSR   $C8D4
115D-   C5 20       CMP   $20
115F-   D6 C1       DEC   $C1,X
1161-   CC D5 C5    CPY   $C5D5
1164-   D3          ???
1165-   20 C3 D5    JSR   $D5C3
1168-   D2 D2       CMP   ($D2)
116A-   C5 CE       CMP   $CE
116C-   D4          ???
116D-   CC D9 8D    CPY   $8DD9
1170-   AA          TAX
1171-   AA          TAX
1172-   20 D3 D4    JSR   $D4D3
1175-   CF          ???
1176-   D2 C5       CMP   ($C5)
1178-   C4 20       CPY   $20
117A-   D4          ???
117B-   C8          INY
117C-   C5 D2       CMP   $D2
117E-   C5 20       CMP   $20
1180-   C1 C6       CMP   ($C6,X)
1182-   D4          ???
1183-   C5 D2       CMP   $D2
1185-   20 C3 C1    JSR   $C1C3
1188-   CC CC C9    CPY   $C9CC
118B-   CE C7 20    DEC   $20C7
118E-   D4          ???
118F-   C8          INY
1190-   C5 20       CMP   $20
1192-   D2 CF       CMP   ($CF)
1194-   D5 D4       CMP   $D4,X
1196-   C9 CE       CMP   #$CE
1198-   C5 AE       CMP   $AE
119A-   8D AA 8D    STA   $8DAA
119D-   AA          TAX
119E-   AA          TAX
119F-   20 CE CF    JSR   $CFCE
11A2-   D4          ???
11A3-   C5 20       CMP   $20
11A5-   D4          ???
11A6-   C8          INY
11A7-   C1 D4       CMP   ($D4,X)
11A9-   20 D3 C9    JSR   $C9D3
11AC-   CE C3 C5    DEC   $C5C3
11AF-   20 D4 C8    JSR   $C8D4
11B2-   C5 20       CMP   $20
11B4-   CC C9 C2    CPY   $C2C9
11B7-   D2 C1       CMP   ($C1)
11B9-   D2 D9       CMP   ($D9)
11BB-   20 CD C1    JSR   $C1CD
11BE-   CB          ???
11BF-   C5 D3       CMP   $D3
11C1-   20 C8 C5    JSR   $C5C8
11C4-   C1 D6       CMP   ($D6,X)
11C6-   D9 20 D5    CMP   $D520,Y
11C9-   D3          ???
11CA-   C5 8D       CMP   $8D
11CC-   AA          TAX
11CD-   AA          TAX
11CE-   20 CF C6    JSR   $C6CF
11D1-   20 D4 C8    JSR   $C8D4
11D4-   C5 D3       CMP   $D3
11D6-   C5 20       CMP   $20
11D8-   CD C5 CD    CMP   $CDC5
11DB-   CF          ???
11DC-   D2 D9       CMP   ($D9)
11DE-   20 C1 C4    JSR   $C4C1
11E1-   C4 D2       CPY   $D2
11E3-   C5 D3       CMP   $D3
11E5-   D3          ???
11E6-   C5 D3       CMP   $D3
11E8-   AC 20 C1    LDY   $C120
11EB-   CE D9 20    DEC   $20D9
11EE-   D4          ???
11EF-   C9 CD       CMP   #$CD
11F1-   C5 20       CMP   $20
11F3-   D9 CF D5    CMP   $D5CF,Y
11F6-   D2 20       CMP   ($20)
11F8-   C3          ???
11F9-   CF          ???
11FA-   C4 C5       CPY   $C5
11FC-   8D AA AA    STA   $AAAA
11FF-   20 CD C1    JSR   $C1CD
1202-   CB          ???
1203-   C5 D3       CMP   $D3
1205-   20 D5 D3    JSR   $D3D5
1208-   C5 20       CMP   $20
120A-   CF          ???
120B-   C6 20       DEC   $20
120D-   D4          ???
120E-   C8          INY
120F-   C5 20       CMP   $20
1211-   DA          PHX
1212-   C5 D2       CMP   $D2
1214-   CF          ???
1215-   20 D0 C1    JSR   $C1D0
1218-   C7          ???
1219-   C5 AC       CMP   $AC
121B-   20 C9 D4    JSR   $D4C9
121E-   20 C9 D3    JSR   $D3C9
1221-   20 C1 C4    JSR   $C4C1
1224-   D6 C9       DEC   $C9,X
1226-   D3          ???
1227-   C5 C4       CMP   $C4
1229-   20 D4 CF    JSR   $CFD4
122C-   8D AA AA    STA   $AAAA
122F-   20 D3 C1    JSR   $C1D3
1232-   D6 C5       DEC   $C5,X
1234-   20 D4 C8    JSR   $C8D4
1237-   C5 20       CMP   $20
1239-   D3          ???
123A-   D4          ???
123B-   C1 D4       CMP   ($D4,X)
123D-   C5 20       CMP   $20
123F-   C2          ???
1240-   C5 C6       CMP   $C6
1242-   CF          ???
1243-   D2 C5       CMP   ($C5)
1245-   20 C3 C1    JSR   $C1C3
1248-   CC CC C9    CPY   $C9CC
124B-   CE C7 20    DEC   $20C7
124E-   C1 CE       CMP   ($CE,X)
1250-   D9 20 CF    CMP   $CF20,Y
1253-   D4          ???
1254-   C8          INY
1255-   C5 D2       CMP   $D2
1257-   20 D2 CF    JSR   $CFD2
125A-   D5 D4       CMP   $D4,X
125C-   C9 CE       CMP   #$CE
125E-   C5 D3       CMP   $D3
1260-   AE 8D AA    LDX   $AA8D
1263-   8D A0 CC    STA   $CCA0
1266-   C4 C1       CPY   $C1
1268-   A0 A3       LDY   #$A3
126A-   B0 B1       BCS   $121D
126C-   8D A0 D3    STA   $D3A0
126F-   D4          ???
1270-   C1 A0       CMP   ($A0,X)
1272-   A4 B0       LDY   $B0
1274-   B6 8D       LDX   $8D,Y
1276-   A0 CC       LDY   #$CC
1278-   C4 C1       CPY   $C1
127A-   A0 A3       LDY   #$A3
127C-   B0 B2       BCS   $1230
127E-   8D A0 D3    STA   $D3A0
1281-   D4          ???
1282-   C1 A0       CMP   ($A0,X)
1284-   A4 B0       LDY   $B0
1286-   B7          ???
1287-   8D A0 CC    STA   $CCA0
128A-   C4 C1       CPY   $C1
128C-   A0 A3       LDY   #$A3
128E-   B0 B3       BCS   $1243
1290-   8D A0 D3    STA   $D3A0
1293-   D4          ???
1294-   C1 A0       CMP   ($A0,X)
1296-   A4 B0       LDY   $B0
1298-   B8          CLV
1299-   8D A0 CC    STA   $CCA0
129C-   C4 C1       CPY   $C1
129E-   A0 A3       LDY   #$A3
12A0-   B0 B4       BCS   $1256
12A2-   8D A0 D3    STA   $D3A0
12A5-   D4          ???
12A6-   C1 A0       CMP   ($A0,X)
12A8-   A4 B0       LDY   $B0
12AA-   B9 8D A0    LDA   $A08D,Y
12AD-   DA          PHX
12AE-   D3          ???
12AF-   C1 D6       CMP   ($D6,X)
12B1-   C5 A0       CMP   $A0
12B3-   A4 B3       LDY   $B3
12B5-   B0 B0       BCS   $1267
12B7-   8D AA 8D    STA   $8DAA
12BA-   A0 DF       LDY   #$DF
12BC-   D0 D2       BNE   $1290
12BE-   CE D4 A0    DEC   $A0D4
12C1-   A2 20       LDX   #$20
12C3-   A2 AC       LDX   #$AC
12C5-   B8          CLV
12C6-   C4 B8       CPY   $B8
12C8-   C4 8D       CPY   $8D
12CA-   A0 DF       LDY   #$DF
12CC-   D0 D2       BNE   $12A0
12CE-   CE D4 A0    DEC   $A0D4
12D1-   A2 DA       LDX   #$DA
12D3-   D3          ???
12D4-   C1 D6       CMP   ($D6,X)
12D6-   C5 20       CMP   $20
12D8-   D3          ???
12D9-   C1 D6       CMP   ($D6,X)
12DB-   C5 D3       CMP   $D3
12DD-   20 D4 C8    JSR   $C8D4
12E0-   C5 20       CMP   $20
12E2-   D3          ???
12E3-   D4          ???
12E4-   C1 D4       CMP   ($D4,X)
12E6-   C5 20       CMP   $20
12E8-   CF          ???
12E9-   C6 20       DEC   $20
12EB-   D4          ???
12EC-   C8          INY
12ED-   C5 20       CMP   $20
12EF-   DA          PHX
12F0-   C5 D2       CMP   $D2
12F2-   CF          ???
12F3-   20 D0 C1    JSR   $C1D0
12F6-   C7          ???
12F7-   C5 20       CMP   $20
12F9-   A2 AC       LDX   #$AC
12FB-   B8          CLV
12FC-   C4 8D       CPY   $8D
12FE-   A0 DF       LDY   #$DF
1300-   D0 D2       BNE   $12D4
1302-   CE D4 A0    DEC   $A0D4
1305-   A2 C1       LDX   #$C1
1307-   C4 C4       CPY   $C4
1309-   D2 C5       CMP   ($C5)
130B-   D3          ???
130C-   D3          ???
130D-   C5 D3       CMP   $D3
130F-   20 D4 C8    JSR   $C8D4
1312-   C1 D4       CMP   ($D4,X)
1314-   20 C1 D2    JSR   $D2C1
1317-   C5 20       CMP   $20
1319-   CE CF D4    DEC   $D4CF
131C-   20 D5 D3    JSR   $D3D5
131F-   C5 C4       CMP   $C4
1321-   20 C2 D9    JSR   $D9C2
1324-   20 C4 CF    JSR   $CFC4
1327-   D3          ???
1328-   AC A2 AC    LDY   $ACA2
132B-   B8          CLV
132C-   C4 8D       CPY   $8D
132E-   A0 DF       LDY   #$DF
1330-   D0 D2       BNE   $1304
1332-   CE D4 A0    DEC   $A0D4
1335-   A2 C1       LDX   #$C1
1337-   D0 D0       BNE   $1309
1339-   CC C5 D3    CPY   $D3C5
133C-   CF          ???
133D-   C6 D4       DEC   $D4
133F-   AC D0 D2    LDY   $D2D0
1342-   CF          ???
1343-   C4 CF       CPY   $CF
1345-   D3          ???
1346-   20 CF D2    JSR   $D2CF
1349-   20 C9 CE    JSR   $CEC9
134C-   D4          ???
134D-   C5 C7       CMP   $C7
134F-   C5 D2       CMP   $D2
1351-   20 C2 C1    JSR   $C1C2
1354-   D3          ???
1355-   C9 C3       CMP   #$C3
1357-   AE A2 AC    LDX   $ACA2
135A-   B8          CLV
135B-   C4 B8       CPY   $B8
135D-   C4 8D       CPY   $8D
135F-   A0 DF       LDY   #$DF
1361-   D0 D2       BNE   $1335
1363-   CE D4 A0    DEC   $A0D4
1366-   A2 D3       LDX   #$D3
1368-   CF          ???
1369-   20 D4 C8    JSR   $C8D4
136C-   C5 20       CMP   $20
136E-   C2          ???
136F-   C1 C3       CMP   ($C3,X)
1371-   CB          ???
1372-   C5 C4       CMP   $C4
1374-   20 D5 D0    JSR   $D0D5
1377-   20 DA C5    JSR   $C5DA
137A-   D2 CF       CMP   ($CF)
137C-   20 D0 C1    JSR   $C1D0
137F-   C7          ???
1380-   C5 20       CMP   $20
1382-   C1 D4       CMP   ($D4,X)
1384-   20 A4 B3    JSR   $B3A4
1387-   B0 B0       BCS   $1339
1389-   20 C9 D3    JSR   $D3C9
138C-   BA          TSX
138D-   A2 AC       LDX   #$AC
138F-   B8          CLV
1390-   C4 B8       CPY   $B8
1392-   C4 8D       CPY   $8D
1394-   A0 DF       LDY   #$DF
1396-   C4 D5       CPY   $D5
1398-   CD D0 A0    CMP   $A0D0
139B-   A4 B3       LDY   $B3
139D-   B0 B0       BCS   $134F
139F-   BB          ???
13A0-   A3          ???
13A1-   B1 B8       LDA   ($B8),Y
13A3-   8D A0 DF    STA   $DFA0
13A6-   D0 D2       BNE   $137A
13A8-   CE D4 A0    DEC   $A0D4
13AB-   A2 20       LDX   #$20
13AD-   A2 AC       LDX   #$AC
13AF-   B8          CLV
13B0-   C4 B8       CPY   $B8
13B2-   C4 8D       CPY   $8D
13B4-   A0 DF       LDY   #$DF
13B6-   D0 D2       BNE   $138A
13B8-   CE D4 A0    DEC   $A0D4
13BB-   A2 B1       LDX   #$B1
13BD-   B8          CLV
13BE-   20 C2 D9    JSR   $D9C2
13C1-   D4          ???
13C2-   C5 D3       CMP   $D3
13C4-   20 C1 D2    JSR   $D2C1
13C7-   C5 20       CMP   $20
13C9-   D5 D3       CMP   $D3,X
13CB-   C5 C4       CMP   $C4
13CD-   AE A2 AC    LDX   $ACA2
13D0-   B8          CLV
13D1-   C4 B8       CPY   $B8
13D3-   C4 8D       CPY   $8D
13D5-   A0 DF       LDY   #$DF
13D7-   D7          ???
13D8-   C1 C9       CMP   ($C9,X)
13DA-   D4          ???
13DB-   8D AA 8D    STA   $8DAA
13DE-   AA          TAX
13DF-   AA          TAX
13E0-   20 D9 CF    JSR   $CFD9
13E3-   D5 20       CMP   $20,X
13E5-   C3          ???
13E6-   C1 CE       CMP   ($CE,X)
13E8-   20 D2 C5    JSR   $C5D2
13EB-   D3          ???
13EC-   D4          ???
13ED-   CF          ???
13EE-   D2 C5       CMP   ($C5)
13F0-   20 D4 C8    JSR   $C8D4
13F3-   C5 20       CMP   $20
13F5-   DA          PHX
13F6-   C5 D2       CMP   $D2
13F8-   CF          ???
13F9-   20 D0 C1    JSR   $C1D0
13FC-   C7          ???
13FD-   C5 20       CMP   $20
13FF-   D4          ???
1400-   CF          ???
1401-   20 C9 D4    JSR   $D4C9
1404-   D3          ???
1405-   8D AA AA    STA   $AAAA
1408-   20 D0 D2    JSR   $D2D0
140B-   C9 CF       CMP   #$CF
140D-   D2 20       CMP   ($20)
140F-   D3          ???
1410-   D4          ???
1411-   C1 D4       CMP   ($D4,X)
1413-   C5 20       CMP   $20
1415-   C2          ???
1416-   D9 20 D4    CMP   $D420,Y
1419-   C8          INY
141A-   C5 CE       CMP   $CE
141C-   20 C3 C1    JSR   $C1C3
141F-   CC CC C9    CPY   $C9CC
1422-   CE C7 20    DEC   $20C7
1425-   DA          PHX
1426-   CC CF C1    CPY   $C1CF
1429-   C4 AE       CPY   $AE
142B-   8D AA 8D    STA   $8DAA
142E-   A0 DA       LDY   #$DA
1430-   CC CF C1    CPY   $C1CF
1433-   C4 A0       CPY   $A0
1435-   A4 B3       LDY   $B3
1437-   B0 B0       BCS   $13E9
1439-   8D AA 8D    STA   $8DAA
143C-   A0 DF       LDY   #$DF
143E-   D0 D2       BNE   $1412
1440-   CE D4 A0    DEC   $A0D4
1443-   A2 20       LDX   #$20
1445-   A2 AC       LDX   #$AC
1447-   B8          CLV
1448-   C4 B8       CPY   $B8
144A-   C4 8D       CPY   $8D
144C-   A0 DF       LDY   #$DF
144E-   D0 D2       BNE   $1422
1450-   CE D4 A0    DEC   $A0D4
1453-   A2 D9       LDX   #$D9
1455-   CF          ???
1456-   D5 20       CMP   $20,X
1458-   C3          ???
1459-   C1 CE       CMP   ($CE,X)
145B-   20 D4 C8    JSR   $C8D4
145E-   C5 CE       CMP   $CE
1460-   20 D2 C5    JSR   $C5D2
1463-   D3          ???
1464-   D4          ???
1465-   CF          ???
1466-   D2 C5       CMP   ($C5)
1468-   20 D4 C8    JSR   $C8D4
146B-   C5 20       CMP   $20
146D-   C6 D2       DEC   $D2
146F-   C5 C5       CMP   $C5
1471-   20 DA C5    JSR   $C5DA
1474-   D2 CF       CMP   ($CF)
1476-   20 D0 C1    JSR   $C1D0
1479-   C7          ???
147A-   C5 A2       CMP   $A2
147C-   AC B8 C4    LDY   $C4B8
147F-   8D A0 DF    STA   $DFA0
1482-   D0 D2       BNE   $1456
1484-   CE D4 A0    DEC   $A0D4
1487-   A2 CC       LDX   #$CC
1489-   CF          ???
148A-   C3          ???
148B-   C1 D4       CMP   ($D4,X)
148D-   C9 CF       CMP   #$CF
148F-   CE D3 20    DEC   $20D3
1492-   D7          ???
1493-   C9 D4       CMP   #$D4
1495-   C8          INY
1496-   20 DA CC    JSR   $CCDA
1499-   CF          ???
149A-   C1 C4       CMP   ($C4,X)
149C-   AE 20 D4    LDX   $D420
149F-   C8          INY
14A0-   C5 D2       CMP   $D2
14A2-   C5 20       CMP   $20
14A4-   C9 D3       CMP   #$D3
14A6-   CE A7 D4    DEC   $D4A7
14A9-   20 C1 CE    JSR   $CEC1
14AC-   D9 A2 AC    CMP   $ACA2,Y
14AF-   B8          CLV
14B0-   C4 8D       CPY   $8D
14B2-   A0 DF       LDY   #$DF
14B4-   D0 D2       BNE   $1488
14B6-   CE D4 A0    DEC   $A0D4
14B9-   A2 CD       LDX   #$CD
14BB-   C5 C1       CMP   $C1
14BD-   CE C9 CE    DEC   $CEC9
14C0-   C7          ???
14C1-   C6 D5       DEC   $D5
14C3-   CC 20 CF    CPY   $CF20
14C6-   D5 D4       CMP   $D4,X
14C8-   D0 D5       BNE   $149F
14CA-   D4          ???
14CB-   20 D4 CF    JSR   $CFD4
14CE-   20 D0 D5    JSR   $D5D0
14D1-   D4          ???
14D2-   20 C8 C5    JSR   $C5C8
14D5-   D2 C5       CMP   ($C5)
14D7-   20 D4 CF    JSR   $CFD4
14DA-   20 A2 AC    JSR   $ACA2
14DD-   B8          CLV
14DE-   C4 8D       CPY   $8D
14E0-   A0 DF       LDY   #$DF
14E2-   D0 D2       BNE   $14B6
14E4-   CE D4 A0    DEC   $A0D4
14E7-   A2 C9       LDX   #$C9
14E9-   CC CC D5    CPY   $D5CC
14EC-   D3          ???
14ED-   D4          ???
14EE-   D2 C1       CMP   ($C1)
14F0-   D4          ???
14F1-   C5 20       CMP   $20
14F3-   D4          ???
14F4-   C8          INY
14F5-   C1 D4       CMP   ($D4,X)
14F7-   AC 20 D3    LDY   $D320
14FA-   CF          ???
14FB-   20 D5 D3    JSR   $D3D5
14FE-   C5 20       CMP   $20
1500-   D9 CF D5    CMP   $D5CF,Y
1503-   D2 20       CMP   ($20)
1505-   C9 CD       CMP   #$CD
1507-   C1 C7       CMP   ($C7,X)
1509-   C9 CE       CMP   #$CE
150B-   C1 D4       CMP   ($D4,X)
150D-   C9 CF       CMP   #$CF
150F-   CE A1 A2    DEC   $A2A1
1512-   AC B8 C4    LDY   $C4B8
1515-   B8          CLV
1516-   C4 8D       CPY   $8D
1518-   A0 DF       LDY   #$DF
151A-   D7          ???
151B-   C1 C9       CMP   ($C9,X)
151D-   D4          ???
151E-   8D AA 8D    STA   $8DAA
1521-   AA          TAX
1522-   AA          TAX
1523-   20 D4 C8    JSR   $C8D4
1526-   C5 20       CMP   $20
1528-   CD D3 D7    CMP   $D7D3
152B-   C1 D0       CMP   ($D0,X)
152D-   20 CD C1    JSR   $C1CD
1530-   C3          ???
1531-   D2 CF       CMP   ($CF)
1533-   20 D3 D7    JSR   $D7D3
1536-   C1 D0       CMP   ($D0,X)
1538-   D3          ???
1539-   20 D4 C8    JSR   $C8D4
153C-   C5 20       CMP   $20
153E-   CD C5 CD    CMP   $CDC5
1541-   CF          ???
1542-   D2 D9       CMP   ($D9)
1544-   20 C2 CC    JSR   $CCC2
1547-   CF          ???
1548-   C3          ???
1549-   CB          ???
154A-   20 C1 D4    JSR   $D4C1
154D-   20 CF CE    JSR   $CECF
1550-   C5 8D       CMP   $8D
1552-   AA          TAX
1553-   AA          TAX
1554-   20 C1 C4    JSR   $C4C1
1557-   C4 D2       CPY   $D2
1559-   C5 D3       CMP   $D3
155B-   D3          ???
155C-   20 D7 C9    JSR   $C9D7
155F-   D4          ???
1560-   C8          INY
1561-   20 D4 C8    JSR   $C8D4
1564-   C5 20       CMP   $20
1566-   D3          ???
1567-   C1 CD       CMP   ($CD,X)
1569-   C5 20       CMP   $20
156B-   CC C5 CE    CPY   $CEC5
156E-   C7          ???
156F-   D4          ???
1570-   C8          INY
1571-   20 C1 D4    JSR   $D4C1
1574-   20 C1 CE    JSR   $CEC1
1577-   CF          ???
1578-   D4          ???
1579-   C8          INY
157A-   C5 D2       CMP   $D2
157C-   AE 8D AA    LDX   $AA8D
157F-   8D A0 DF    STA   $DFA0
1582-   D0 D2       BNE   $1556
1584-   CE D4 A0    DEC   $A0D4
1587-   A2 D4       LDX   #$D4
1589-   C8          INY
158A-   C5 20       CMP   $20
158C-   CD D3 D7    CMP   $D7D3
158F-   C1 D0       CMP   ($D0,X)
1591-   20 CD C1    JSR   $C1CD
1594-   C3          ???
1595-   D2 CF       CMP   ($CF)
1597-   20 D3 D7    JSR   $D7D3
159A-   C1 D0       CMP   ($D0,X)
159C-   D3          ???
159D-   20 C1 20    JSR   $20C1
15A0-   CC C5 CE    CPY   $CEC5
15A3-   C7          ???
15A4-   D4          ???
15A5-   C8          INY
15A6-   A2 AC       LDX   #$AC
15A8-   B8          CLV
15A9-   C4 8D       CPY   $8D
15AB-   A0 DF       LDY   #$DF
15AD-   D0 D2       BNE   $1581
15AF-   CE D4 A0    DEC   $A0D4
15B2-   A2 CF       LDX   #$CF
15B4-   C6 20       DEC   $20
15B6-   CD C5 CD    CMP   $CDC5
15B9-   CF          ???
15BA-   D2 D9       CMP   ($D9)
15BC-   20 C6 D2    JSR   $D2C6
15BF-   CF          ???
15C0-   CD 20 CF    CMP   $CF20
15C3-   CE C5 20    DEC   $20C5
15C6-   CC CF C3    CPY   $C3CF
15C9-   C1 D4       CMP   ($D4,X)
15CB-   C9 CF       CMP   #$CF
15CD-   CE A2 AC    DEC   $ACA2
15D0-   B8          CLV
15D1-   C4 8D       CPY   $8D
15D3-   A0 DF       LDY   #$DF
15D5-   D0 D2       BNE   $15A9
15D7-   CE D4 A0    DEC   $A0D4
15DA-   A2 D4       LDX   #$D4
15DC-   CF          ???
15DD-   20 C1 CE    JSR   $CEC1
15E0-   CF          ???
15E1-   D4          ???
15E2-   C8          INY
15E3-   C5 D2       CMP   $D2
15E5-   AE 20 D3    LDX   $D320
15E8-   CF          ???
15E9-   AC 20 C2    LDY   $C220
15EC-   C5 C6       CMP   $C6
15EE-   CF          ???
15EF-   D2 C5       CMP   ($C5)
15F1-   20 D3 D7    JSR   $D7D3
15F4-   C1 D0       CMP   ($D0,X)
15F6-   BA          TSX
15F7-   A2 AC       LDX   #$AC
15F9-   B8          CLV
15FA-   C4 B8       CPY   $B8
15FC-   C4 8D       CPY   $8D
15FE-   A0 DF       LDY   #$DF
1600-   C4 D5       CPY   $D5
1602-   CD D0 A0    CMP   $A0D0
1605-   A4 B3       LDY   $B3
1607-   B0 B0       BCS   $15B9
1609-   BB          ???
160A-   A3          ???
160B-   B1 B0       LDA   ($B0),Y
160D-   8D A0 DF    STA   $DFA0
1610-   C4 D5       CPY   $D5
1612-   CD D0 A0    CMP   $A0D0
1615-   A4 B3       LDY   $B3
1617-   B2 B0       LDA   ($B0)
1619-   BB          ???
161A-   A3          ???
161B-   B1 B0       LDA   ($B0),Y
161D-   8D A0 CD    STA   $CDA0
1620-   D3          ???
1621-   D7          ???
1622-   C1 D0       CMP   ($D0,X)
1624-   A0 A4       LDY   #$A4
1626-   B3          ???
1627-   B0 B0       BCS   $15D9
1629-   BB          ???
162A-   A4 B3       LDY   $B3
162C-   B2 B0       LDA   ($B0)
162E-   BB          ???
162F-   A3          ???
1630-   B1 B0       LDA   ($B0),Y
1632-   8D A0 DF    STA   $DFA0
1635-   D0 D2       BNE   $1609
1637-   CE D4 A0    DEC   $A0D4
163A-   A2 20       LDX   #$20
163C-   A2 AC       LDX   #$AC
163E-   B8          CLV
163F-   C4 8D       CPY   $8D
1641-   A0 DF       LDY   #$DF
1643-   D0 D2       BNE   $1617
1645-   CE D4 A0    DEC   $A0D4
1648-   A2 C1       LDX   #$C1
164A-   CE C4 20    DEC   $20C4
164D-   C1 C6       CMP   ($C6,X)
164F-   D4          ???
1650-   C5 D2       CMP   $D2
1652-   20 D3 D7    JSR   $D7D3
1655-   C1 D0       CMP   ($D0,X)
1657-   BA          TSX
1658-   20 A2 AC    JSR   $ACA2
165B-   B8          CLV
165C-   C4 B8       CPY   $B8
165E-   C4 8D       CPY   $8D
1660-   A0 DF       LDY   #$DF
1662-   C4 D5       CPY   $D5
1664-   CD D0 A0    CMP   $A0D0
1667-   A4 B3       LDY   $B3
1669-   B0 B0       BCS   $161B
166B-   BB          ???
166C-   A3          ???
166D-   B1 B0       LDA   ($B0),Y
166F-   8D A0 DF    STA   $DFA0
1672-   C4 D5       CPY   $D5
1674-   CD D0 A0    CMP   $A0D0
1677-   A4 B3       LDY   $B3
1679-   B2 B0       LDA   ($B0)
167B-   BB          ???
167C-   A3          ???
167D-   B1 B0       LDA   ($B0),Y
167F-   8D A0 DF    STA   $DFA0
1682-   D7          ???
1683-   C1 C9       CMP   ($C9,X)
1685-   D4          ???
1686-   8D AA 8D    STA   $8DAA
1689-   AA          TAX
168A-   AA          TAX
168B-   20 D4 C8    JSR   $C8D4
168E-   C5 20       CMP   $20
1690-   C6 CF       DEC   $CF
1692-   CC CC CF    CPY   $CFCC
1695-   D7          ???
1696-   C9 CE       CMP   #$CE
1698-   C7          ???
1699-   20 C9 CC    JSR   $CCC9
169C-   CC D5 D3    CPY   $D3D5
169F-   D4          ???
16A0-   D2 C1       CMP   ($C1)
16A2-   D4          ???
16A3-   C5 D3       CMP   $D3
16A5-   20 D4 C8    JSR   $C8D4
16A8-   C5 20       CMP   $20
16AA-   DF          ???
16AB-   D2 C4       CMP   ($C4)
16AD-   D5 CD       CMP   $CD,X
16AF-   D0 20       BNE   $16D1
16B1-   CD C1 C3    CMP   $C3C1
16B4-   D2 CF       CMP   ($CF)
16B6-   20 C9 CE    JSR   $CEC9
16B9-   8D AA AA    STA   $AAAA
16BC-   20 D4 C8    JSR   $C8D4
16BF-   C5 20       CMP   $20
16C1-   D2 C5       CMP   ($C5)
16C3-   D1 D5       CMP   ($D5),Y
16C5-   C9 D2       CMP   #$D2
16C7-   C5 C4       CMP   $C4
16C9-   20 CC C9    JSR   $C9CC
16CC-   C2          ???
16CD-   D2 C1       CMP   ($C1)
16CF-   D2 D9       CMP   ($D9)
16D1-   AE 8D AA    LDX   $AA8D
16D4-   8D A0 CC    STA   $CCA0
16D7-   C4 C1       CPY   $C1
16D9-   A0 A3       LDY   #$A3
16DB-   A4 B1       LDY   $B1
16DD-   B1 8D       LDA   ($8D),Y
16DF-   A0 CC       LDY   #$CC
16E1-   C4 D8       CPY   $D8
16E3-   A0 A3       LDY   #$A3
16E5-   A4 B1       LDY   $B1
16E7-   B2 8D       LDA   ($8D)
16E9-   A0 CC       LDY   #$CC
16EB-   C4 D9       CPY   $D9
16ED-   A0 A3       LDY   #$A3
16EF-   A4 B1       LDY   $B1
16F1-   B3          ???
16F2-   8D A0 C3    STA   $C3A0
16F5-   CC C3 8D    CPY   $8DC3
16F8-   A0 DF       LDY   #$DF
16FA-   D2 C4       CMP   ($C4)
16FC-   D5 CD       CMP   $CD,X
16FE-   D0 8D       BNE   $168D
1700-   AA          TAX
1701-   8D A0 CA    STA   $CAA0
1704-   CD D0 A0    CMP   $A0D0
1707-   D2 C5       CMP   ($C5)
1709-   C5 CE       CMP   $CE
170B-   D4          ???
170C-   D2 D9       CMP   ($D9)
170E-   8D AA 8D    STA   $8DAA
1711-   AA          TAX
1712-   E0 E0       CPX   #$E0
1714-   E0 E0       CPX   #$E0
1716-   E0 E0       CPX   #$E0
1718-   E0 E0       CPX   #$E0
171A-   E0 E0       CPX   #$E0
171C-   E0 E0       CPX   #$E0
171E-   E0 E0       CPX   #$E0
1720-   E0 E0       CPX   #$E0
1722-   E0 E0       CPX   #$E0
1724-   E0 E0       CPX   #$E0
1726-   E0 E0       CPX   #$E0
1728-   E0 E0       CPX   #$E0
172A-   E0 E0       CPX   #$E0
172C-   E0 E0       CPX   #$E0
172E-   E0 E0       CPX   #$E0
1730-   AA          TAX
1731-   8D AA 20    STA   $20AA
1734-   20 20 20    JSR   $2020
1737-   20 20 20    JSR   $2020
173A-   20 C2 CF    JSR   $CFC2
173D-   D4          ???
173E-   D4          ???
173F-   CF          ???
1740-   CD 20 C9    CMP   $C920
1743-   CE C3 CC    DEC   $CCC3
1746-   D5 C4       CMP   $C4,X
1748-   C5 D3       CMP   $D3
174A-   20 20 20    JSR   $2020
174D-   20 20 20    JSR   $2020
1750-   20 AA 8D    JSR   $8DAA
1753-   AA          TAX
1754-   AC AC AC    LDY   $ACAC
1757-   AC AC AC    LDY   $ACAC
175A-   AC AC AC    LDY   $ACAC
175D-   AC AC AC    LDY   $ACAC
1760-   AC AC AC    LDY   $ACAC
1763-   AC AC AC    LDY   $ACAC
1766-   AC AC AC    LDY   $ACAC
1769-   AC AC AC    LDY   $ACAC
176C-   AC AC AC    LDY   $ACAC
176F-   AC AC AC    LDY   $ACAC
1772-   AA          TAX
1773-   8D AA 8D    STA   $8DAA
1776-   AA          TAX
1777-   AA          TAX
1778-   20 C2 CF    JSR   $CFC2
177B-   D4          ???
177C-   D4          ???
177D-   CF          ???
177E-   CD 20 C9    CMP   $C920
1781-   CE C3 CC    DEC   $CCC3
1784-   D5 C4       CMP   $C4,X
1786-   C5 D3       CMP   $D3
1788-   8D AA 8D    STA   $8DAA
178B-   A0 D0       LDY   #$D0
178D-   D5 D4       CMP   $D4,X
178F-   A0 C3       LDY   #$C3
1791-   CF          ???
1792-   CD CD CF    CMP   $CFCD
1795-   CE AE CC    DEC   $CCAE
1798-   C9 C2       CMP   #$C2
179A-   AE CD C9    LDX   $C9CD
179D-   CE 8D A0    DEC   $A08D
17A0-   D0 D5       BNE   $1777
17A2-   D4          ???
17A3-   A0 D2       LDY   #$D2
17A5-   C5 D1       CMP   $D1
17A7-   D5 C9       CMP   $C9,X
17A9-   D2 C5       CMP   ($C5)
17AB-   C4 AE       CPY   $AE
17AD-   CC C9 C2    CPY   $C2C9
17B0-   AE CD C9    LDX   $C9CD
17B3-   CE 8D AA    DEC   $AA8D
17B6-   8D 00 00    STA   $0000
