0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C3    LDY   $C320,X
0950-   CF          ???
0951-   CD CD CF    CMP   $CFCD
0954-   CE 20 C4    DEC   $C420
0957-   C5 CD       CMP   $CD
0959-   CF          ???
095A-   20 A9 AD    JSR   $ADA9
095D-   20 20 20    JSR   $2020
0960-   20 20 20    JSR   $2020
0963-   20 AA 8D    JSR   $8DAA
0966-   AA          TAX
0967-   20 20 20    JSR   $2020
096A-   20 20 20    JSR   $2020
096D-   20 20 20    JSR   $2020
0970-   20 20 20    JSR   $2020
0973-   20 20 20    JSR   $2020
0976-   20 20 20    JSR   $2020
0979-   20 20 20    JSR   $2020
097C-   20 20 20    JSR   $2020
097F-   20 20 20    JSR   $2020
0982-   20 20 20    JSR   $2020
0985-   AA          TAX
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B2       BCS   $094E
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B1    JSR   $B120
09D4-   B2 AD       LDA   ($AD)
09D6-   C4 C5       CPY   $C5
09D8-   C3          ???
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B8       LDA   ($B8),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 C4    STA   $C4A0
0B02-   D3          ???
0B03-   CB          ???
0B04-   A0 C3       LDY   #$C3
0B06-   CF          ???
0B07-   CD CD CF    CMP   $CFCD
0B0A-   CE AE C4    DEC   $C4AE
0B0D-   C5 CD       CMP   $CD
0B0F-   CF          ???
0B10-   8D A0 CF    STA   $CFA0
0B13-   C2          ???
0B14-   CA          DEX
0B15-   A0 A4       LDY   #$A4
0B17-   C2          ???
0B18-   C6 C5       DEC   $C5
0B1A-   B0 8D       BCS   $0AA9
0B1C-   A0 CF       LDY   #$CF
0B1E-   D2 C7       CMP   ($C7)
0B20-   A0 A4       LDY   #$A4
0B22-   B6 B0       LDX   $B0,Y
0B24-   B0 B0       BCS   $0AD6
0B26-   8D AA 8D    STA   $8DAA
0B29-   AA          TAX
0B2A-   E0 E0       CPX   #$E0
0B2C-   E0 E0       CPX   #$E0
0B2E-   E0 E0       CPX   #$E0
0B30-   E0 E0       CPX   #$E0
0B32-   E0 E0       CPX   #$E0
0B34-   E0 E0       CPX   #$E0
0B36-   E0 E0       CPX   #$E0
0B38-   E0 E0       CPX   #$E0
0B3A-   E0 E0       CPX   #$E0
0B3C-   E0 E0       CPX   #$E0
0B3E-   E0 E0       CPX   #$E0
0B40-   E0 E0       CPX   #$E0
0B42-   E0 E0       CPX   #$E0
0B44-   E0 E0       CPX   #$E0
0B46-   E0 E0       CPX   #$E0
0B48-   AA          TAX
0B49-   8D AA 20    STA   $20AA
0B4C-   20 D4 CF    JSR   $CFD4
0B4F-   D0 20       BNE   $0B71
0B51-   C9 CE       CMP   #$CE
0B53-   C3          ???
0B54-   CC D5 C4    CPY   $C4D5
0B57-   C5 D3       CMP   $D3
0B59-   20 A8 C8    JSR   $C8A8
0B5C-   CF          ???
0B5D-   CF          ???
0B5E-   CB          ???
0B5F-   D3          ???
0B60-   AC CD C1    LDY   $C1CD
0B63-   C3          ???
0B64-   D2 CF       CMP   ($CF)
0B66-   D3          ???
0B67-   A9 20       LDA   #$20
0B69-   AA          TAX
0B6A-   8D AA AC    STA   $ACAA
0B6D-   AC AC AC    LDY   $ACAC
0B70-   AC AC AC    LDY   $ACAC
0B73-   AC AC AC    LDY   $ACAC
0B76-   AC AC AC    LDY   $ACAC
0B79-   AC AC AC    LDY   $ACAC
0B7C-   AC AC AC    LDY   $ACAC
0B7F-   AC AC AC    LDY   $ACAC
0B82-   AC AC AC    LDY   $ACAC
0B85-   AC AC AC    LDY   $ACAC
0B88-   AC AC AA    LDY   $AAAC
0B8B-   8D AA 8D    STA   $8DAA
0B8E-   A0 D5       LDY   #$D5
0B90-   D3          ???
0B91-   C5 A0       CMP   $A0
0B93-   D2 C5       CMP   ($C5)
0B95-   D1 D5       CMP   ($D5),Y
0B97-   C9 D2       CMP   #$D2
0B99-   C5 C4       CMP   $C4
0B9B-   AE CD C1    LDX   $C1CD
0B9E-   C3          ???
0B9F-   8D A0 D0    STA   $D0A0
0BA2-   D5 D4       CMP   $D4,X
0BA4-   A0 D2       LDY   #$D2
0BA6-   C5 D1       CMP   $D1
0BA8-   D5 C9       CMP   $C9,X
0BAA-   D2 C5       CMP   ($C5)
0BAC-   C4 AE       CPY   $AE
0BAE-   C8          INY
0BAF-   CF          ???
0BB0-   CF          ???
0BB1-   CB          ???
0BB2-   D3          ???
0BB3-   8D A0 D5    STA   $D5A0
0BB6-   D3          ???
0BB7-   C5 A0       CMP   $A0
0BB9-   C3          ???
0BBA-   CF          ???
0BBB-   CD CD CF    CMP   $CFCD
0BBE-   CE AE CD    DEC   $CDAE
0BC1-   C1 C3       CMP   ($C3,X)
0BC3-   8D A0 D0    STA   $D0A0
0BC6-   D5 D4       CMP   $D4,X
0BC8-   20 A0 C3    JSR   $C3A0
0BCB-   CF          ???
0BCC-   CD CD CF    CMP   $CFCD
0BCF-   CE AE C8    DEC   $C8AE
0BD2-   CF          ???
0BD3-   CF          ???
0BD4-   CB          ???
0BD5-   D3          ???
0BD6-   8D AA 8D    STA   $8DAA
0BD9-   AA          TAX
0BDA-   E0 E0       CPX   #$E0
0BDC-   E0 E0       CPX   #$E0
0BDE-   E0 E0       CPX   #$E0
0BE0-   E0 E0       CPX   #$E0
0BE2-   E0 E0       CPX   #$E0
0BE4-   E0 E0       CPX   #$E0
0BE6-   E0 E0       CPX   #$E0
0BE8-   E0 E0       CPX   #$E0
0BEA-   E0 E0       CPX   #$E0
0BEC-   E0 E0       CPX   #$E0
0BEE-   E0 E0       CPX   #$E0
0BF0-   E0 E0       CPX   #$E0
0BF2-   E0 E0       CPX   #$E0
0BF4-   E0 E0       CPX   #$E0
0BF6-   E0 E0       CPX   #$E0
0BF8-   AA          TAX
0BF9-   8D AA 20    STA   $20AA
0BFC-   20 20 20    JSR   $2020
0BFF-   20 20 D0    JSR   $D020
0C02-   D2 CF       CMP   ($CF)
0C04-   C7          ???
0C05-   D2 C1       CMP   ($C1)
0C07-   CD 20 CD    CMP   $CD20
0C0A-   C1 C9       CMP   ($C9,X)
0C0C-   CE 20 C2    DEC   $C220
0C0F-   CF          ???
0C10-   C4 D9       CPY   $D9
0C12-   20 20 20    JSR   $2020
0C15-   20 20 20    JSR   $2020
0C18-   20 AA 8D    JSR   $8DAA
0C1B-   AA          TAX
0C1C-   AC AC AC    LDY   $ACAC
0C1F-   AC AC AC    LDY   $ACAC
0C22-   AC AC AC    LDY   $ACAC
0C25-   AC AC AC    LDY   $ACAC
0C28-   AC AC AC    LDY   $ACAC
0C2B-   AC AC AC    LDY   $ACAC
0C2E-   AC AC AC    LDY   $ACAC
0C31-   AC AC AC    LDY   $ACAC
0C34-   AC AC AC    LDY   $ACAC
0C37-   AC AC AC    LDY   $ACAC
0C3A-   AA          TAX
0C3B-   8D AA 8D    STA   $8DAA
0C3E-   AA          TAX
0C3F-   AA          TAX
0C40-   20 CD C5    JSR   $C5CD
0C43-   CD C6 C9    CMP   $C9C6
0C46-   CC CC 20    CPY   $20CC
0C49-   C4 CF       CPY   $CF
0C4B-   C5 D3       CMP   $D3
0C4D-   20 C1 C2    JSR   $C2C1
0C50-   CF          ???
0C51-   D5 D4       CMP   $D4,X
0C53-   20 D7 C8    JSR   $C8D7
0C56-   C1 D4       CMP   ($D4,X)
0C58-   20 C9 D4    JSR   $D4C9
0C5B-   D3          ???
0C5C-   20 CE C1    JSR   $C1CE
0C5F-   CD C5 8D    CMP   $8DC5
0C62-   AA          TAX
0C63-   AA          TAX
0C64-   20 C9 CD    JSR   $CDC9
0C67-   D0 CC       BNE   $0C35
0C69-   C9 C5       CMP   #$C5
0C6B-   D3          ???
0C6C-   BA          TSX
0C6D-   20 C9 D4    JSR   $D4C9
0C70-   20 C6 C9    JSR   $C9C6
0C73-   CC CC D3    CPY   $D3CC
0C76-   20 C1 20    JSR   $20C1
0C79-   C2          ???
0C7A-   CC CF C3    CPY   $C3CF
0C7D-   CB          ???
0C7E-   20 CF C6    JSR   $C6CF
0C81-   20 CD C5    JSR   $C5CD
0C84-   CD CF D2    CMP   $D2CF
0C87-   D9 8D AA    CMP   $AA8D,Y
0C8A-   AA          TAX
0C8B-   20 D7 C9    JSR   $C9D7
0C8E-   D4          ???
0C8F-   C8          INY
0C90-   20 C1 20    JSR   $20C1
0C93-   D0 C1       BNE   $0C56
0C95-   D2 D4       CMP   ($D4)
0C97-   C9 C3       CMP   #$C3
0C99-   D5 CC       CMP   $CC,X
0C9B-   C1 D2       CMP   ($D2,X)
0C9D-   20 C3 C8    JSR   $C8C3
0CA0-   C1 D2       CMP   ($D2,X)
0CA2-   C1 C3       CMP   ($C3,X)
0CA4-   D4          ???
0CA5-   C5 D2       CMP   $D2
0CA7-   AE 8D AA    LDX   $AA8D
0CAA-   8D AA AA    STA   $AAAA
0CAD-   20 CD C1    JSR   $C1CD
0CB0-   C3          ???
0CB1-   D2 CF       CMP   ($CF)
0CB3-   BA          TSX
0CB4-   20 CD C6    JSR   $C6CD
0CB7-   C9 CC       CMP   #$CC
0CB9-   CC 20 C1    CPY   $C120
0CBC-   C4 C4       CPY   $C4
0CBE-   D2 C5       CMP   ($C5)
0CC0-   D3          ???
0CC1-   D3          ???
0CC2-   DF          ???
0CC3-   D3          ???
0CC4-   D4          ???
0CC5-   C1 D2       CMP   ($D2,X)
0CC7-   D4          ???
0CC8-   BB          ???
0CC9-   C2          ???
0CCA-   D9 D4 C5    CMP   $C5D4,Y
0CCD-   DF          ???
0CCE-   CC C5 CE    CPY   $CEC5
0CD1-   C7          ???
0CD2-   D4          ???
0CD3-   C8          INY
0CD4-   BB          ???
0CD5-   C6 C9       DEC   $C9
0CD7-   CC CC DF    CPY   $DFCC
0CDA-   D6 C1       DEC   $C1,X
0CDC-   CC D5 C5    CPY   $C5D5
0CDF-   8D AA 8D    STA   $8DAA
0CE2-   A0 CC       LDY   #$CC
0CE4-   C4 C1       CPY   $C1
0CE6-   A0 A3       LDY   #$A3
0CE8-   BE A4 B3    LDX   $B3A4,Y
0CEB-   B0 B0       BCS   $0C9D
0CED-   A0 BB       LDY   #$BB
0CEF-   20 C1 D2    JSR   $D2C1
0CF2-   C5 C1       CMP   $C1
0CF4-   20 D4 CF    JSR   $CFD4
0CF7-   20 C6 C9    JSR   $C9C6
0CFA-   CC CC BB    CPY   $BBCC
0CFD-   20 C8 C9    JSR   $C9C8
0D00-   C7          ???
0D01-   C8          INY
0D02-   8D A0 D0    STA   $D0A0
0D05-   C8          INY
0D06-   C1 8D       CMP   ($8D,X)
0D08-   A0 CC       LDY   #$CC
0D0A-   C4 C1       CPY   $C1
0D0C-   A0 A3       LDY   #$A3
0D0E-   BC A4 B3    LDY   $B3A4,X
0D11-   B0 B0       BCS   $0CC3
0D13-   A0 BB       LDY   #$BB
0D15-   20 CC CF    JSR   $CFCC
0D18-   D7          ???
0D19-   8D A0 D0    STA   $D0A0
0D1C-   C8          INY
0D1D-   C1 8D       CMP   ($8D,X)
0D1F-   A0 CC       LDY   #$CC
0D21-   C4 C1       CPY   $C1
0D23-   A0 A3       LDY   #$A3
0D25-   BE B1 B0    LDX   $B0B1,Y
0D28-   8D A0 D0    STA   $D0A0
0D2B-   C8          INY
0D2C-   C1 8D       CMP   ($8D,X)
0D2E-   A0 CC       LDY   #$CC
0D30-   C4 C1       CPY   $C1
0D32-   A0 A3       LDY   #$A3
0D34-   BC B1 B0    LDY   $B0B1,X
0D37-   8D A0 D0    STA   $D0A0
0D3A-   C8          INY
0D3B-   C1 8D       CMP   ($8D,X)
0D3D-   A0 CC       LDY   #$CC
0D3F-   C4 C1       CPY   $C1
0D41-   A0 A3       LDY   #$A3
0D43-   B0 A0       BCS   $0CE5
0D45-   BB          ???
0D46-   20 C6 C9    JSR   $C9C6
0D49-   CC CC 20    CPY   $20CC
0D4C-   C3          ???
0D4D-   C8          INY
0D4E-   C1 D2       CMP   ($D2,X)
0D50-   C1 C3       CMP   ($C3,X)
0D52-   D4          ???
0D53-   C5 D2       CMP   $D2
0D55-   8D A0 D0    STA   $D0A0
0D58-   C8          INY
0D59-   C1 8D       CMP   ($8D,X)
0D5B-   A0 CA       LDY   #$CA
0D5D-   D3          ???
0D5E-   D2 A0       CMP   ($A0)
0D60-   CD C5 CD    CMP   $CDC5
0D63-   C6 C9       DEC   $C9
0D65-   CC CC 8D    CPY   $8DCC
0D68-   AA          TAX
0D69-   8D A0 DF    STA   $DFA0
0D6C-   D0 D2       BNE   $0D40
0D6E-   CE D4 A0    DEC   $A0D4
0D71-   A2 CD       LDX   #$CD
0D73-   C5 CD       CMP   $CD
0D75-   C6 C9       DEC   $C9
0D77-   CC CC 20    CPY   $20CC
0D7A-   C6 C9       DEC   $C9
0D7C-   CC CC D3    CPY   $D3CC
0D7F-   20 C1 20    JSR   $20C1
0D82-   D0 CF       BNE   $0D53
0D84-   D2 D4       CMP   ($D4)
0D86-   C9 CF       CMP   #$CF
0D88-   CE 20 CF    DEC   $CF20
0D8B-   C6 20       DEC   $20
0D8D-   CD C5 CD    CMP   $CDC5
0D90-   CF          ???
0D91-   D2 D9       CMP   ($D9)
0D93-   20 D7 C9    JSR   $C9D7
0D96-   D4          ???
0D97-   C8          INY
0D98-   A2 AC       LDX   #$AC
0D9A-   B8          CLV
0D9B-   C4 8D       CPY   $8D
0D9D-   A0 DF       LDY   #$DF
0D9F-   D0 D2       BNE   $0D73
0DA1-   CE D4 A0    DEC   $A0D4
0DA4-   A2 C1       LDX   #$C1
0DA6-   20 D3 D0    JSR   $D0D3
0DA9-   C5 C3       CMP   $C3
0DAB-   C9 C6       CMP   #$C6
0DAD-   C9 C5       CMP   #$C5
0DAF-   C4 20       CPY   $20
0DB1-   D6 C1       DEC   $C1,X
0DB3-   CC D5 C5    CPY   $C5D5
0DB6-   AE 20 A2    LDX   $A220
0DB9-   AC B8 C4    LDY   $C4B8
0DBC-   B8          CLV
0DBD-   C4 8D       CPY   $8D
0DBF-   A0 DF       LDY   #$DF
0DC1-   C4 D5       CPY   $D5
0DC3-   CD D0 A0    CMP   $A0D0
0DC6-   A4 B3       LDY   $B3
0DC8-   B0 B0       BCS   $0D7A
0DCA-   BB          ???
0DCB-   A3          ???
0DCC-   B1 B0       LDA   ($B0),Y
0DCE-   8D A0 DF    STA   $DFA0
0DD1-   D7          ???
0DD2-   C1 C9       CMP   ($C9,X)
0DD4-   D4          ???
0DD5-   8D AA 8D    STA   $8DAA
0DD8-   AA          TAX
0DD9-   AA          TAX
0DDA-   20 CD C5    JSR   $C5CD
0DDD-   CD CD CF    CMP   $CFCD
0DE0-   D6 C5       DEC   $C5,X
0DE2-   20 C1 CC    JSR   $CCC1
0DE5-   D3          ???
0DE6-   CF          ???
0DE7-   20 C4 CF    JSR   $CFC4
0DEA-   C5 D3       CMP   $D3
0DEC-   20 D7 C8    JSR   $C8D7
0DEF-   C1 D4       CMP   ($D4,X)
0DF1-   20 C9 D4    JSR   $D4C9
0DF4-   20 D3 C1    JSR   $C1D3
0DF7-   D9 D3 BA    CMP   $BAD3,Y
0DFA-   20 C9 D4    JSR   $D4C9
0DFD-   20 CD CF    JSR   $CFCD
0E00-   D6 C5       DEC   $C5,X
0E02-   D3          ???
0E03-   8D AA AA    STA   $AAAA
0E06-   20 C1 20    JSR   $20C1
0E09-   C2          ???
0E0A-   CC CF C3    CPY   $C3CF
0E0D-   CB          ???
0E0E-   20 CF C6    JSR   $C6CF
0E11-   20 CD C5    JSR   $C5CD
0E14-   CD CF D2    CMP   $D2CF
0E17-   D9 20 C6    CMP   $C620,Y
0E1A-   D2 CF       CMP   ($CF)
0E1C-   CD 20 C1    CMP   $C120
0E1F-   20 D3 CF    JSR   $CFD3
0E22-   D5 D2       CMP   $D2,X
0E24-   C3          ???
0E25-   C5 20       CMP   $20
0E27-   CC CF C3    CPY   $C3CF
0E2A-   C1 D4       CMP   ($D4,X)
0E2C-   C9 CF       CMP   #$CF
0E2E-   CE 8D AA    DEC   $AA8D
0E31-   AA          TAX
0E32-   20 D4 CF    JSR   $CFD4
0E35-   20 C1 20    JSR   $20C1
0E38-   C4 C5       CPY   $C5
0E3A-   D3          ???
0E3B-   D4          ???
0E3C-   C9 CE       CMP   #$CE
0E3E-   C1 D4       CMP   ($D4,X)
0E40-   C9 CF       CMP   #$CF
0E42-   CE 20 CC    DEC   $CC20
0E45-   CF          ???
0E46-   C3          ???
0E47-   C1 D4       CMP   ($D4,X)
0E49-   C9 CF       CMP   #$CF
0E4B-   CE AE 20    DEC   $20AE
0E4E-   D7          ???
0E4F-   C5 A7       CMP   $A7
0E51-   CC CC 20    CPY   $20CC
0E54-   CE CF D7    DEC   $D7CF
0E57-   20 CD CF    JSR   $CFCD
0E5A-   D6 C5       DEC   $C5,X
0E5C-   8D AA AA    STA   $AAAA
0E5F-   20 D4 C8    JSR   $C8D4
0E62-   CF          ???
0E63-   D3          ???
0E64-   C5 20       CMP   $20
0E66-   DA          PHX
0E67-   C5 D2       CMP   $D2
0E69-   CF          ???
0E6A-   C5 D3       CMP   $D3
0E6C-   20 D0 CC    JSR   $CCD0
0E6F-   C1 C3       CMP   ($C3,X)
0E71-   C5 C4       CMP   $C4
0E73-   20 C2 D9    JSR   $D9C2
0E76-   20 CD C5    JSR   $C5CD
0E79-   CD C6 C9    CMP   $C9C6
0E7C-   CC CC 20    CPY   $20CC
0E7F-   D4          ???
0E80-   CF          ???
0E81-   20 C1 CE    JSR   $CEC1
0E84-   CF          ???
0E85-   D4          ???
0E86-   C8          INY
0E87-   C5 D2       CMP   $D2
0E89-   8D AA AA    STA   $AAAA
0E8C-   20 CC CF    JSR   $CFCC
0E8F-   C3          ???
0E90-   C1 D4       CMP   ($D4,X)
0E92-   C9 CF       CMP   #$CF
0E94-   CE AE 8D    DEC   $8DAE
0E97-   AA          TAX
0E98-   8D AA AA    STA   $AAAA
0E9B-   20 CD C1    JSR   $C1CD
0E9E-   C3          ???
0E9F-   D2 CF       CMP   ($CF)
0EA1-   BA          TSX
0EA2-   20 CD CD    JSR   $CDCD
0EA5-   CF          ???
0EA6-   D6 C5       DEC   $C5,X
0EA8-   20 D3 D2    JSR   $D2D3
0EAB-   C3          ???
0EAC-   DF          ???
0EAD-   C1 C4       CMP   ($C4,X)
0EAF-   C4 D2       CPY   $D2
0EB1-   BB          ???
0EB2-   C4 C5       CPY   $C5
0EB4-   D3          ???
0EB5-   D4          ???
0EB6-   DF          ???
0EB7-   C1 C4       CMP   ($C4,X)
0EB9-   C4 D2       CPY   $D2
0EBB-   BB          ???
0EBC-   C2          ???
0EBD-   D9 D4 C5    CMP   $C5D4,Y
0EC0-   DF          ???
0EC1-   CC C5 CE    CPY   $CEC5
0EC4-   C7          ???
0EC5-   D4          ???
0EC6-   C8          INY
0EC7-   8D AA 8D    STA   $8DAA
0ECA-   A0 CC       LDY   #$CC
0ECC-   C4 C1       CPY   $C1
0ECE-   A0 A3       LDY   #$A3
0ED0-   BE A4 B3    LDX   $B3A4,Y
0ED3-   B0 B0       BCS   $0E85
0ED5-   A0 BB       LDY   #$BB
0ED7-   20 D3 D2    JSR   $D2D3
0EDA-   C3          ???
0EDB-   20 C8 C9    JSR   $C9C8
0EDE-   C7          ???
0EDF-   C8          INY
0EE0-   8D A0 D0    STA   $D0A0
0EE3-   C8          INY
0EE4-   C1 8D       CMP   ($8D,X)
0EE6-   A0 CC       LDY   #$CC
0EE8-   C4 C1       CPY   $C1
0EEA-   A0 A3       LDY   #$A3
0EEC-   BC A4 B3    LDY   $B3A4,X
0EEF-   B0 B0       BCS   $0EA1
0EF1-   A0 BB       LDY   #$BB
0EF3-   20 D3 D2    JSR   $D2D3
0EF6-   C3          ???
0EF7-   20 CC CF    JSR   $CFCC
0EFA-   D7          ???
0EFB-   8D A0 D0    STA   $D0A0
0EFE-   C8          INY
0EFF-   C1 8D       CMP   ($8D,X)
0F01-   A0 CC       LDY   #$CC
0F03-   C4 C1       CPY   $C1
0F05-   A0 A3       LDY   #$A3
0F07-   BE A4 B3    LDX   $B3A4,Y
0F0A-   B2 B0       LDA   ($B0)
0F0C-   A0 BB       LDY   #$BB
0F0E-   20 C4 C5    JSR   $C5C4
0F11-   D3          ???
0F12-   D4          ???
0F13-   20 C8 C9    JSR   $C9C8
0F16-   C7          ???
0F17-   C8          INY
0F18-   8D A0 D0    STA   $D0A0
0F1B-   C8          INY
0F1C-   C1 8D       CMP   ($8D,X)
0F1E-   A0 CC       LDY   #$CC
0F20-   C4 C1       CPY   $C1
0F22-   A0 A3       LDY   #$A3
0F24-   BC A4 B3    LDY   $B3A4,X
0F27-   B2 B0       LDA   ($B0)
0F29-   A0 BB       LDY   #$BB
0F2B-   20 C4 C5    JSR   $C5C4
0F2E-   D3          ???
0F2F-   D4          ???
0F30-   20 CC CF    JSR   $CFCC
0F33-   D7          ???
0F34-   8D A0 D0    STA   $D0A0
0F37-   C8          INY
0F38-   C1 8D       CMP   ($8D,X)
0F3A-   A0 CC       LDY   #$CC
0F3C-   C4 C1       CPY   $C1
0F3E-   A0 A3       LDY   #$A3
0F40-   BE B1 B0    LDX   $B0B1,Y
0F43-   A0 BB       LDY   #$BB
0F45-   20 A3 20    JSR   $20A3
0F48-   CF          ???
0F49-   C6 20       DEC   $20
0F4B-   C2          ???
0F4C-   D9 D4 C5    CMP   $C5D4,Y
0F4F-   D3          ???
0F50-   20 D4 CF    JSR   $CFD4
0F53-   20 CD CF    JSR   $CFCD
0F56-   D6 C5       DEC   $C5,X
0F58-   8D A0 D0    STA   $D0A0
0F5B-   C8          INY
0F5C-   C1 8D       CMP   ($8D,X)
0F5E-   A0 CC       LDY   #$CC
0F60-   C4 C1       CPY   $C1
0F62-   A0 A3       LDY   #$A3
0F64-   BC B1 B0    LDY   $B0B1,X
0F67-   A0 BB       LDY   #$BB
0F69-   20 CC CF    JSR   $CFCC
0F6C-   D7          ???
0F6D-   20 C2 D9    JSR   $D9C2
0F70-   D4          ???
0F71-   C5 8D       CMP   $8D
0F73-   A0 D0       LDY   #$D0
0F75-   C8          INY
0F76-   C1 8D       CMP   ($8D,X)
0F78-   A0 CA       LDY   #$CA
0F7A-   D3          ???
0F7B-   D2 A0       CMP   ($A0)
0F7D-   CD C5 CD    CMP   $CDC5
0F80-   CD CF D6    CMP   $D6CF
0F83-   C5 8D       CMP   $8D
0F85-   AA          TAX
0F86-   8D A0 DF    STA   $DFA0
0F89-   D0 D2       BNE   $0F5D
0F8B-   CE D4 A0    DEC   $A0D4
0F8E-   A2 20       LDX   #$20
0F90-   A2 AC       LDX   #$AC
0F92-   B8          CLV
0F93-   C4 B8       CPY   $B8
0F95-   C4 8D       CPY   $8D
0F97-   A0 DF       LDY   #$DF
0F99-   D0 D2       BNE   $0F6D
0F9B-   CE D4 A0    DEC   $A0D4
0F9E-   A2 CD       LDX   #$CD
0FA0-   C5 CD       CMP   $CD
0FA2-   CD CF D6    CMP   $D6CF
0FA5-   C5 20       CMP   $20
0FA7-   CD CF D6    CMP   $D6CF
0FAA-   C5 D3       CMP   $D3
0FAC-   20 C3 CF    JSR   $CFC3
0FAF-   D0 C9       BNE   $0F7A
0FB1-   C5 D3       CMP   $D3
0FB3-   20 C1 20    JSR   $20C1
0FB6-   D3          ???
0FB7-   D0 C1       BNE   $0F7A
0FB9-   CE 20 CF    DEC   $CF20
0FBC-   C6 20       DEC   $20
0FBE-   CD C5 CD    CMP   $CDC5
0FC1-   CF          ???
0FC2-   D2 D9       CMP   ($D9)
0FC4-   A2 AC       LDX   #$AC
0FC6-   B8          CLV
0FC7-   C4 8D       CPY   $8D
0FC9-   A0 DF       LDY   #$DF
0FCB-   D0 D2       BNE   $0F9F
0FCD-   CE D4 A0    DEC   $A0D4
0FD0-   A2 C6       LDX   #$C6
0FD2-   D2 CF       CMP   ($CF)
0FD4-   CD 20 C1    CMP   $C120
0FD7-   20 D3 CF    JSR   $CFD3
0FDA-   D5 D2       CMP   $D2,X
0FDC-   C3          ???
0FDD-   C5 20       CMP   $20
0FDF-   D4          ???
0FE0-   CF          ???
0FE1-   20 C1 20    JSR   $20C1
0FE4-   C4 C5       CPY   $C5
0FE6-   D3          ???
0FE7-   D4          ???
0FE8-   C9 CE       CMP   #$CE
0FEA-   C1 D4       CMP   ($D4,X)
0FEC-   C9 CF       CMP   #$CF
0FEE-   CE 20 C1    DEC   $C120
0FF1-   C4 C4       CPY   $C4
0FF3-   D2 C5       CMP   ($C5)
0FF5-   D3          ???
0FF6-   D3          ???
0FF7-   AE A2 AC    LDX   $ACA2
0FFA-   B8          CLV
0FFB-   C4 B8       CPY   $B8
0FFD-   C4 8D       CPY   $8D
0FFF-   A0 DF       LDY   #$DF
1001-   D0 D2       BNE   $0FD5
1003-   CE D4 A0    DEC   $A0D4
1006-   A2 D3       LDX   #$D3
1008-   CF          ???
1009-   20 CD CF    JSR   $CFCD
100C-   D6 C9       DEC   $C9,X
100E-   CE C7 20    DEC   $20C7
1011-   A4 B3       LDY   $B3
1013-   B0 B0       BCS   $0FC5
1015-   20 D4 CF    JSR   $CFD4
1018-   20 A4 B3    JSR   $B3A4
101B-   B2 B0       LDA   ($B0)
101D-   20 D2 C5    JSR   $C5D2
1020-   D3          ???
1021-   D5 CC       CMP   $CC,X
1023-   D4          ???
1024-   D3          ???
1025-   20 C9 CE    JSR   $CEC9
1028-   BA          TSX
1029-   A2 AC       LDX   #$AC
102B-   B8          CLV
102C-   C4 B8       CPY   $B8
102E-   C4 8D       CPY   $8D
1030-   A0 DF       LDY   #$DF
1032-   C4 D5       CPY   $D5
1034-   CD D0 A0    CMP   $A0D0
1037-   A4 B3       LDY   $B3
1039-   B2 B0       LDA   ($B0)
103B-   BB          ???
103C-   A3          ???
103D-   B1 B0       LDA   ($B0),Y
103F-   8D A0 DF    STA   $DFA0
1042-   D7          ???
1043-   C1 C9       CMP   ($C9,X)
1045-   D4          ???
1046-   8D AA 8D    STA   $8DAA
1049-   AA          TAX
104A-   AA          TAX
104B-   20 C4 C5    JSR   $C5C4
104E-   CC C1 D9    CPY   $D9C1
1051-   CD D3 20    CMP   $20D3
1054-   D2 D5       CMP   ($D5)
1056-   CE D3 20    DEC   $20D3
1059-   D4          ???
105A-   C8          INY
105B-   D2 CF       CMP   ($CF)
105D-   D5 C7       CMP   $C7,X
105F-   C8          INY
1060-   20 C3 D9    JSR   $D9C3
1063-   C3          ???
1064-   CC C5 D3    CPY   $D3C5
1067-   20 CF C6    JSR   $C6CF
106A-   20 D4 C8    JSR   $C8D4
106D-   C5 8D       CMP   $8D
106F-   AA          TAX
1070-   AA          TAX
1071-   20 B6 B5    JSR   $B5B6
1074-   B0 B2       BCS   $1028
1076-   20 D5 CE    JSR   $CED5
1079-   D4          ???
107A-   C9 CC       CMP   #$CC
107C-   20 C1 20    JSR   $20C1
107F-   C3          ???
1080-   C5 D2       CMP   $D2
1082-   D4          ???
1083-   C1 C9       CMP   ($C9,X)
1085-   CE 20 C1    DEC   $C120
1088-   CD CF D5    CMP   $D5CF
108B-   CE D4 20    DEC   $20D4
108E-   CF          ???
108F-   C6 20       DEC   $20
1091-   D4          ???
1092-   C9 CD       CMP   #$CD
1094-   C5 8D       CMP   $8D
1096-   AA          TAX
1097-   AA          TAX
1098-   20 C8 C1    JSR   $C1C8
109B-   D3          ???
109C-   20 D0 C1    JSR   $C1D0
109F-   D3          ???
10A0-   D3          ???
10A1-   C5 C4       CMP   $C4
10A3-   AE 8D AA    LDX   $AA8D
10A6-   8D AA AA    STA   $AAAA
10A9-   20 CD C1    JSR   $C1CD
10AC-   C3          ???
10AD-   D2 CF       CMP   ($CF)
10AF-   BA          TSX
10B0-   20 C4 C5    JSR   $C5C4
10B3-   CC C1 D9    CPY   $D9C1
10B6-   20 A3 B2    JSR   $B2A3
10B9-   B5 B0       LDA   $B0,X
10BB-   8D AA 8D    STA   $8DAA
10BE-   A0 DF       LDY   #$DF
10C0-   D0 D2       BNE   $1094
10C2-   CE D4 A0    DEC   $A0D4
10C5-   A2 20       LDX   #$20
10C7-   A2 AC       LDX   #$AC
10C9-   B8          CLV
10CA-   C4 B8       CPY   $B8
10CC-   C4 8D       CPY   $8D
10CE-   A0 DF       LDY   #$DF
10D0-   D0 D2       BNE   $10A4
10D2-   CE D4 A0    DEC   $A0D4
10D5-   A2 C4       LDX   #$C4
10D7-   C5 CC       CMP   $CC
10D9-   C1 D9       CMP   ($D9,X)
10DB-   CD D3 20    CMP   $20D3
10DE-   C4 C5       CPY   $C5
10E0-   CC C1 D9    CPY   $D9C1
10E3-   D3          ???
10E4-   20 C1 20    JSR   $20C1
10E7-   D3          ???
10E8-   D0 C5       BNE   $10AF
10EA-   C3          ???
10EB-   C9 C6       CMP   #$C6
10ED-   C9 C5       CMP   #$C5
10EF-   C4 20       CPY   $20
10F1-   CE D5 CD    DEC   $CDD5
10F4-   C2          ???
10F5-   C5 D2       CMP   $D2
10F7-   20 CF C6    JSR   $C6CF
10FA-   A2 AC       LDX   #$AC
10FC-   B8          CLV
10FD-   C4 8D       CPY   $8D
10FF-   A0 DF       LDY   #$DF
1101-   D0 D2       BNE   $10D5
1103-   CE D4 A0    DEC   $A0D4
1106-   A2 CD       LDX   #$CD
1108-   C9 CC       CMP   #$CC
110A-   CC C9 D3    CPY   $D3C9
110D-   C5 C3       CMP   $C3
110F-   CF          ???
1110-   CE C4 D3    DEC   $D3C4
1113-   AE 20 B2    LDX   $B220
1116-   B5 B0       LDA   $B0,X
1118-   20 CD C9    JSR   $C9CD
111B-   CC CC C9    CPY   $C9CC
111E-   D3          ???
111F-   C5 C3       CMP   $C3
1121-   CF          ???
1122-   CE C4 D3    DEC   $D3C4
1125-   20 BD 20    JSR   $20BD
1128-   B1 AF       LDA   ($AF),Y
112A-   B4 20       LDY   $20,X
112C-   D3          ???
112D-   C5 C3       CMP   $C3
112F-   CF          ???
1130-   CE C4 AE    DEC   $AEC4
1133-   A2 AC       LDX   #$AC
1135-   B8          CLV
1136-   C4 B8       CPY   $B8
1138-   C4 8D       CPY   $8D
113A-   AA          TAX
113B-   8D A0 CC    STA   $CCA0
113E-   C4 D9       CPY   $D9
1140-   A0 A3       LDY   #$A3
1142-   B2 B5       LDA   ($B5)
1144-   B0 A0       BCS   $10E6
1146-   BB          ???
1147-   20 D4 C9    JSR   $C9D4
114A-   CD C5 20    CMP   $20C5
114D-   C9 CE       CMP   #$CE
114F-   20 CD C9    JSR   $C9CD
1152-   CC CC C9    CPY   $C9CC
1155-   D3          ???
1156-   C5 C3       CMP   $C3
1158-   CF          ???
1159-   CE C4 D3    DEC   $D3C4
115C-   8D BB 20    STA   $20BB
115F-   C9 D3       CMP   #$D3
1161-   20 D0 C1    JSR   $C1D0
1164-   D3          ???
1165-   D3          ???
1166-   C5 C4       CMP   $C4
1168-   20 D6 C9    JSR   $C9D6
116B-   C1 20       CMP   ($20,X)
116D-   D9 8D BB    CMP   $BB8D,Y
1170-   20 B2 B5    JSR   $B5B2
1173-   B0 20       BCS   $1195
1175-   BD 20 B1    LDA   $B120,X
1178-   AF          ???
1179-   B4 20       LDY   $20,X
117B-   D3          ???
117C-   C5 C3       CMP   $C3
117E-   CF          ???
117F-   CE C4 8D    DEC   $8DC4
1182-   A0 CA       LDY   #$CA
1184-   D3          ???
1185-   D2 A0       CMP   ($A0)
1187-   C4 C5       CPY   $C5
1189-   CC C1 D9    CPY   $D9C1
118C-   CD D3 8D    CMP   $8DD3
118F-   A0 C2       LDY   #$C2
1191-   C5 C5       CMP   $C5
1193-   D0 A0       BNE   $1135
1195-   B1 8D       LDA   ($8D),Y
1197-   A0 DF       LDY   #$DF
1199-   D0 D2       BNE   $116D
119B-   CE D4 A0    DEC   $A0D4
119E-   A2 B1       LDX   #$B1
11A0-   AF          ???
11A1-   B4 20       LDY   $20,X
11A3-   D3          ???
11A4-   C5 C3       CMP   $C3
11A6-   CF          ???
11A7-   CE C4 A2    DEC   $A2C4
11AA-   AC B8 C4    LDY   $C4B8
11AD-   8D A0 CC    STA   $CCA0
11B0-   C4 D9       CPY   $D9
11B2-   A0 A3       LDY   #$A3
11B4-   B2 B5       LDA   ($B5)
11B6-   B0 8D       BCS   $1145
11B8-   A0 CA       LDY   #$CA
11BA-   D3          ???
11BB-   D2 A0       CMP   ($A0)
11BD-   C4 C5       CPY   $C5
11BF-   CC C1 D9    CPY   $D9C1
11C2-   CD D3 8D    CMP   $8DD3
11C5-   A0 C2       LDY   #$C2
11C7-   C5 C5       CMP   $C5
11C9-   D0 A0       BNE   $116B
11CB-   B2 8D       LDA   ($8D)
11CD-   A0 DF       LDY   #$DF
11CF-   D0 D2       BNE   $11A3
11D1-   CE D4 A0    DEC   $A0D4
11D4-   A2 B1       LDX   #$B1
11D6-   AF          ???
11D7-   B4 20       LDY   $20,X
11D9-   D3          ???
11DA-   C5 C3       CMP   $C3
11DC-   CF          ???
11DD-   CE C4 A2    DEC   $A2C4
11E0-   AC B8 C4    LDY   $C4B8
11E3-   8D A0 CC    STA   $CCA0
11E6-   C4 D9       CPY   $D9
11E8-   A0 A3       LDY   #$A3
11EA-   B2 B5       LDA   ($B5)
11EC-   B0 8D       BCS   $117B
11EE-   A0 CA       LDY   #$CA
11F0-   D3          ???
11F1-   D2 A0       CMP   ($A0)
11F3-   C4 C5       CPY   $C5
11F5-   CC C1 D9    CPY   $D9C1
11F8-   CD D3 8D    CMP   $8DD3
11FB-   A0 C2       LDY   #$C2
11FD-   C5 C5       CMP   $C5
11FF-   D0 A0       BNE   $11A1
1201-   B3          ???
1202-   8D A0 DF    STA   $DFA0
1205-   D0 D2       BNE   $11D9
1207-   CE D4 A0    DEC   $A0D4
120A-   A2 B1       LDX   #$B1
120C-   AF          ???
120D-   B4 20       LDY   $20,X
120F-   D3          ???
1210-   C5 C3       CMP   $C3
1212-   CF          ???
1213-   CE C4 A2    DEC   $A2C4
1216-   AC B8 C4    LDY   $C4B8
1219-   8D A0 CC    STA   $CCA0
121C-   C4 D9       CPY   $D9
121E-   A0 A3       LDY   #$A3
1220-   B2 B5       LDA   ($B5)
1222-   B0 8D       BCS   $11B1
1224-   A0 CA       LDY   #$CA
1226-   D3          ???
1227-   D2 A0       CMP   ($A0)
1229-   C4 C5       CPY   $C5
122B-   CC C1 D9    CPY   $D9C1
122E-   CD D3 A0    CMP   $A0D3
1231-   BB          ???
1232-   20 BD 20    JSR   $20BD
1235-   B1 20       LDA   ($20),Y
1237-   D3          ???
1238-   C5 C3       CMP   $C3
123A-   CF          ???
123B-   CE C4 20    DEC   $20C4
123E-   C4 C5       CPY   $C5
1240-   CC C1 D9    CPY   $D9C1
1243-   8D A0 C2    STA   $C2A0
1246-   C5 C5       CMP   $C5
1248-   D0 A0       BNE   $11EA
124A-   B4 8D       LDY   $8D,X
124C-   A0 DF       LDY   #$DF
124E-   D0 D2       BNE   $1222
1250-   CE D4 A0    DEC   $A0D4
1253-   A2 B1       LDX   #$B1
1255-   AF          ???
1256-   B4 20       LDY   $20,X
1258-   D3          ???
1259-   C5 C3       CMP   $C3
125B-   CF          ???
125C-   CE C4 A2    DEC   $A2C4
125F-   AC B8 C4    LDY   $C4B8
1262-   8D AA 8D    STA   $8DAA
1265-   A0 DF       LDY   #$DF
1267-   D0 D2       BNE   $123B
1269-   CE D4 A0    DEC   $A0D4
126C-   A2 20       LDX   #$20
126E-   A2 AC       LDX   #$AC
1270-   B8          CLV
1271-   C4 B8       CPY   $B8
1273-   C4 8D       CPY   $8D
1275-   A0 DF       LDY   #$DF
1277-   D7          ???
1278-   C1 C9       CMP   ($C9,X)
127A-   D4          ???
127B-   8D AA 8D    STA   $8DAA
127E-   AA          TAX
127F-   AA          TAX
1280-   20 DA CD    JSR   $CDDA
1283-   D3          ???
1284-   C1 D6       CMP   ($D6,X)
1286-   C5 20       CMP   $20
1288-   C2          ???
1289-   C1 C3       CMP   ($C3,X)
128B-   CB          ???
128C-   D3          ???
128D-   20 D5 D0    JSR   $D0D5
1290-   20 D4 C8    JSR   $C8D4
1293-   C5 20       CMP   $20
1295-   A2 C6       LDX   #$C6
1297-   D2 C5       CMP   ($C5)
1299-   C5 A2       CMP   $A2
129B-   20 C1 D2    JSR   $D2C1
129E-   C5 C1       CMP   $C1
12A0-   D3          ???
12A1-   20 CF C6    JSR   $C6CF
12A4-   8D AA AA    STA   $AAAA
12A7-   20 D4 C8    JSR   $C8D4
12AA-   C5 20       CMP   $20
12AC-   DA          PHX
12AD-   C5 D2       CMP   $D2
12AF-   CF          ???
12B0-   20 D0 C1    JSR   $C1D0
12B3-   C7          ???
12B4-   C5 20       CMP   $20
12B6-   D4          ???
12B7-   CF          ???
12B8-   20 C1 CE    JSR   $CEC1
12BB-   20 C1 CC    JSR   $CCC1
12BE-   D4          ???
12BF-   C5 D2       CMP   $D2
12C1-   CE C1 D4    DEC   $D4C1
12C4-   C5 20       CMP   $20
12C6-   CD C5 CD    CMP   $CDC5
12C9-   CF          ???
12CA-   D2 D9       CMP   ($D9)
12CC-   8D AA AA    STA   $AAAA
12CF-   20 CC CF    JSR   $CFCC
12D2-   C3          ???
12D3-   C1 D4       CMP   ($D4,X)
12D5-   C9 CF       CMP   #$CF
12D7-   CE AE 20    DEC   $20AE
12DA-   D4          ???
12DB-   C8          INY
12DC-   C9 D3       CMP   #$D3
12DE-   20 C9 D3    JSR   $D3C9
12E1-   20 CD CF    JSR   $CFCD
12E4-   D3          ???
12E5-   D4          ???
12E6-   CC D9 20    CPY   $20D9
12E9-   D5 D3       CMP   $D3,X
12EB-   C5 C6       CMP   $C6
12ED-   D5 CC       CMP   $CC,X
12EF-   20 D7 C8    JSR   $C8D7
12F2-   C5 CE       CMP   $CE
12F4-   8D AA AA    STA   $AAAA
12F7-   20 D9 CF    JSR   $CFD9
12FA-   D5 20       CMP   $20,X
12FC-   CB          ???
12FD-   CE CF D7    DEC   $D7CF
1300-   20 C1 20    JSR   $20C1
1303-   D2 CF       CMP   ($CF)
1305-   D5 D4       CMP   $D4,X
1307-   C9 CE       CMP   #$CE
1309-   C5 20       CMP   $20
130B-   D5 D3       CMP   $D3,X
130D-   C5 D3       CMP   $D3
130F-   20 D4 C8    JSR   $C8D4
1312-   C5 20       CMP   $20
1314-   DA          PHX
1315-   C5 D2       CMP   $D2
1317-   CF          ???
1318-   20 D0 C1    JSR   $C1D0
131B-   C7          ???
131C-   C5 AC       CMP   $AC
131E-   8D AA AA    STA   $AAAA
1321-   20 C2 D5    JSR   $D5C2
1324-   D4          ???
1325-   20 D9 CF    JSR   $CFD9
1328-   D5 20       CMP   $20,X
132A-   D7          ???
132B-   C1 CE       CMP   ($CE,X)
132D-   D4          ???
132E-   20 D4 CF    JSR   $CFD4
1331-   20 CB C5    JSR   $C5CB
1334-   C5 D0       CMP   $D0
1336-   20 D4 C8    JSR   $C8D4
1339-   C5 20       CMP   $20
133B-   D6 C1       DEC   $C1,X
133D-   CC D5 C5    CPY   $C5D5
1340-   D3          ???
1341-   20 C3 D5    JSR   $D5C3
1344-   D2 D2       CMP   ($D2)
1346-   C5 CE       CMP   $CE
1348-   D4          ???
1349-   CC D9 8D    CPY   $8DD9
134C-   AA          TAX
134D-   AA          TAX
134E-   20 D3 D4    JSR   $D4D3
1351-   CF          ???
1352-   D2 C5       CMP   ($C5)
1354-   C4 20       CPY   $20
1356-   D4          ???
1357-   C8          INY
1358-   C5 D2       CMP   $D2
135A-   C5 20       CMP   $20
135C-   C1 C6       CMP   ($C6,X)
135E-   D4          ???
135F-   C5 D2       CMP   $D2
1361-   20 C3 C1    JSR   $C1C3
1364-   CC CC C9    CPY   $C9CC
1367-   CE C7 20    DEC   $20C7
136A-   D4          ???
136B-   C8          INY
136C-   C5 20       CMP   $20
136E-   D2 CF       CMP   ($CF)
1370-   D5 D4       CMP   $D4,X
1372-   C9 CE       CMP   #$CE
1374-   C5 AE       CMP   $AE
1376-   8D AA 8D    STA   $8DAA
1379-   AA          TAX
137A-   AA          TAX
137B-   20 CE CF    JSR   $CFCE
137E-   D4          ???
137F-   C5 20       CMP   $20
1381-   D4          ???
1382-   C8          INY
1383-   C1 D4       CMP   ($D4,X)
1385-   20 D3 C9    JSR   $C9D3
1388-   CE C3 C5    DEC   $C5C3
138B-   20 D4 C8    JSR   $C8D4
138E-   C5 20       CMP   $20
1390-   CC C9 C2    CPY   $C2C9
1393-   D2 C1       CMP   ($C1)
1395-   D2 D9       CMP   ($D9)
1397-   20 CD C1    JSR   $C1CD
139A-   CB          ???
139B-   C5 D3       CMP   $D3
139D-   20 C8 C5    JSR   $C5C8
13A0-   C1 D6       CMP   ($D6,X)
13A2-   D9 20 D5    CMP   $D520,Y
13A5-   D3          ???
13A6-   C5 8D       CMP   $8D
13A8-   AA          TAX
13A9-   AA          TAX
13AA-   20 CF C6    JSR   $C6CF
13AD-   20 D4 C8    JSR   $C8D4
13B0-   C5 D3       CMP   $D3
13B2-   C5 20       CMP   $20
13B4-   CD C5 CD    CMP   $CDC5
13B7-   CF          ???
13B8-   D2 D9       CMP   ($D9)
13BA-   20 C1 C4    JSR   $C4C1
13BD-   C4 D2       CPY   $D2
13BF-   C5 D3       CMP   $D3
13C1-   D3          ???
13C2-   C5 D3       CMP   $D3
13C4-   AC 20 C1    LDY   $C120
13C7-   CE D9 20    DEC   $20D9
13CA-   D4          ???
13CB-   C9 CD       CMP   #$CD
13CD-   C5 20       CMP   $20
13CF-   D9 CF D5    CMP   $D5CF,Y
13D2-   D2 20       CMP   ($20)
13D4-   C3          ???
13D5-   CF          ???
13D6-   C4 C5       CPY   $C5
13D8-   8D AA AA    STA   $AAAA
13DB-   20 CD C1    JSR   $C1CD
13DE-   CB          ???
13DF-   C5 D3       CMP   $D3
13E1-   20 D5 D3    JSR   $D3D5
13E4-   C5 20       CMP   $20
13E6-   CF          ???
13E7-   C6 20       DEC   $20
13E9-   D4          ???
13EA-   C8          INY
13EB-   C5 20       CMP   $20
13ED-   DA          PHX
13EE-   C5 D2       CMP   $D2
13F0-   CF          ???
13F1-   20 D0 C1    JSR   $C1D0
13F4-   C7          ???
13F5-   C5 AC       CMP   $AC
13F7-   20 C9 D4    JSR   $D4C9
13FA-   20 C9 D3    JSR   $D3C9
13FD-   20 C1 C4    JSR   $C4C1
1400-   D6 C9       DEC   $C9,X
1402-   D3          ???
1403-   C5 C4       CMP   $C4
1405-   20 D4 CF    JSR   $CFD4
1408-   8D AA AA    STA   $AAAA
140B-   20 D3 C1    JSR   $C1D3
140E-   D6 C5       DEC   $C5,X
1410-   20 D4 C8    JSR   $C8D4
1413-   C5 20       CMP   $20
1415-   D3          ???
1416-   D4          ???
1417-   C1 D4       CMP   ($D4,X)
1419-   C5 20       CMP   $20
141B-   C2          ???
141C-   C5 C6       CMP   $C6
141E-   CF          ???
141F-   D2 C5       CMP   ($C5)
1421-   20 C3 C1    JSR   $C1C3
1424-   CC CC C9    CPY   $C9CC
1427-   CE C7 20    DEC   $20C7
142A-   C1 CE       CMP   ($CE,X)
142C-   D9 20 CF    CMP   $CF20,Y
142F-   D4          ???
1430-   C8          INY
1431-   C5 D2       CMP   $D2
1433-   20 D2 CF    JSR   $CFD2
1436-   D5 D4       CMP   $D4,X
1438-   C9 CE       CMP   #$CE
143A-   C5 D3       CMP   $D3
143C-   AE 8D AA    LDX   $AA8D
143F-   8D AA AA    STA   $AAAA
1442-   20 CD C1    JSR   $C1CD
1445-   C3          ???
1446-   D2 CF       CMP   ($CF)
1448-   BA          TSX
1449-   20 DA D3    JSR   $D3DA
144C-   C1 D6       CMP   ($D6,X)
144E-   C5 20       CMP   $20
1450-   20 C2 C1    JSR   $C1C2
1453-   C3          ???
1454-   CB          ???
1455-   D5 D0       CMP   $D0,X
1457-   DF          ???
1458-   C1 C4       CMP   ($C4,X)
145A-   C4 D2       CPY   $D2
145C-   8D AA 8D    STA   $8DAA
145F-   A0 CC       LDY   #$CC
1461-   C4 C1       CPY   $C1
1463-   A0 A3       LDY   #$A3
1465-   B0 B1       BCS   $1418
1467-   8D A0 D3    STA   $D3A0
146A-   D4          ???
146B-   C1 A0       CMP   ($A0,X)
146D-   A4 B0       LDY   $B0
146F-   B6 8D       LDX   $8D,Y
1471-   A0 CC       LDY   #$CC
1473-   C4 C1       CPY   $C1
1475-   A0 A3       LDY   #$A3
1477-   B0 B2       BCS   $142B
1479-   8D A0 D3    STA   $D3A0
147C-   D4          ???
147D-   C1 A0       CMP   ($A0,X)
147F-   A4 B0       LDY   $B0
1481-   B7          ???
1482-   8D A0 CC    STA   $CCA0
1485-   C4 C1       CPY   $C1
1487-   A0 A3       LDY   #$A3
1489-   B0 B3       BCS   $143E
148B-   8D A0 D3    STA   $D3A0
148E-   D4          ???
148F-   C1 A0       CMP   ($A0,X)
1491-   A4 B0       LDY   $B0
1493-   B8          CLV
1494-   8D A0 CC    STA   $CCA0
1497-   C4 C1       CPY   $C1
1499-   A0 A3       LDY   #$A3
149B-   B0 B4       BCS   $1451
149D-   8D A0 D3    STA   $D3A0
14A0-   D4          ???
14A1-   C1 A0       CMP   ($A0,X)
14A3-   A4 B0       LDY   $B0
14A5-   B9 8D A0    LDA   $A08D,Y
14A8-   CC C4 C1    CPY   $C1C4
14AB-   A0 A3       LDY   #$A3
14AD-   BE A4 B3    LDX   $B3A4,Y
14B0-   B0 B0       BCS   $1462
14B2-   8D A0 D0    STA   $D0A0
14B5-   C8          INY
14B6-   C1 8D       CMP   ($8D,X)
14B8-   A0 CC       LDY   #$CC
14BA-   C4 C1       CPY   $C1
14BC-   A0 A3       LDY   #$A3
14BE-   BC A4 B3    LDY   $B3A4,X
14C1-   B0 B0       BCS   $1473
14C3-   A0 BB       LDY   #$BB
14C5-   20 CC CF    JSR   $CFCC
14C8-   D7          ???
14C9-   20 C4 C5    JSR   $C5C4
14CC-   D3          ???
14CD-   D4          ???
14CE-   8D A0 D0    STA   $D0A0
14D1-   C8          INY
14D2-   C1 8D       CMP   ($8D,X)
14D4-   A0 CA       LDY   #$CA
14D6-   D3          ???
14D7-   D2 A0       CMP   ($A0)
14D9-   DA          PHX
14DA-   CD D3 C1    CMP   $C1D3
14DD-   D6 C5       DEC   $C5,X
14DF-   8D AA 8D    STA   $8DAA
14E2-   A0 DF       LDY   #$DF
14E4-   D0 D2       BNE   $14B8
14E6-   CE D4 A0    DEC   $A0D4
14E9-   A2 20       LDX   #$20
14EB-   A2 AC       LDX   #$AC
14ED-   B8          CLV
14EE-   C4 B8       CPY   $B8
14F0-   C4 8D       CPY   $8D
14F2-   A0 DF       LDY   #$DF
14F4-   D0 D2       BNE   $14C8
14F6-   CE D4 A0    DEC   $A0D4
14F9-   A2 DA       LDX   #$DA
14FB-   CD D3 C1    CMP   $C1D3
14FE-   D6 C5       DEC   $C5,X
1500-   20 D3 C1    JSR   $C1D3
1503-   D6 C5       DEC   $C5,X
1505-   D3          ???
1506-   20 D4 C8    JSR   $C8D4
1509-   C5 20       CMP   $20
150B-   D3          ???
150C-   D4          ???
150D-   C1 D4       CMP   ($D4,X)
150F-   C5 20       CMP   $20
1511-   CF          ???
1512-   C6 20       DEC   $20
1514-   D4          ???
1515-   C8          INY
1516-   C5 20       CMP   $20
1518-   DA          PHX
1519-   C5 D2       CMP   $D2
151B-   CF          ???
151C-   20 D0 C1    JSR   $C1D0
151F-   C7          ???
1520-   C5 20       CMP   $20
1522-   A2 AC       LDX   #$AC
1524-   B8          CLV
1525-   C4 8D       CPY   $8D
1527-   A0 DF       LDY   #$DF
1529-   D0 D2       BNE   $14FD
152B-   CE D4 A0    DEC   $A0D4
152E-   A2 C1       LDX   #$C1
1530-   C4 C4       CPY   $C4
1532-   D2 C5       CMP   ($C5)
1534-   D3          ???
1535-   D3          ???
1536-   C5 D3       CMP   $D3
1538-   20 D4 C8    JSR   $C8D4
153B-   C1 D4       CMP   ($D4,X)
153D-   20 C1 D2    JSR   $D2C1
1540-   C5 20       CMP   $20
1542-   CE CF D4    DEC   $D4CF
1545-   20 D5 D3    JSR   $D3D5
1548-   C5 C4       CMP   $C4
154A-   20 C2 D9    JSR   $D9C2
154D-   20 C4 CF    JSR   $CFC4
1550-   D3          ???
1551-   AC A2 AC    LDY   $ACA2
1554-   B8          CLV
1555-   C4 8D       CPY   $8D
1557-   A0 DF       LDY   #$DF
1559-   D0 D2       BNE   $152D
155B-   CE D4 A0    DEC   $A0D4
155E-   A2 C1       LDX   #$C1
1560-   D0 D0       BNE   $1532
1562-   CC C5 D3    CPY   $D3C5
1565-   CF          ???
1566-   C6 D4       DEC   $D4
1568-   AC D0 D2    LDY   $D2D0
156B-   CF          ???
156C-   C4 CF       CPY   $CF
156E-   D3          ???
156F-   20 CF D2    JSR   $D2CF
1572-   20 C9 CE    JSR   $CEC9
1575-   D4          ???
1576-   C5 C7       CMP   $C7
1578-   C5 D2       CMP   $D2
157A-   20 C2 C1    JSR   $C1C2
157D-   D3          ???
157E-   C9 C3       CMP   #$C3
1580-   AE A2 AC    LDX   $ACA2
1583-   B8          CLV
1584-   C4 B8       CPY   $B8
1586-   C4 8D       CPY   $8D
1588-   A0 DF       LDY   #$DF
158A-   D0 D2       BNE   $155E
158C-   CE D4 A0    DEC   $A0D4
158F-   A2 D3       LDX   #$D3
1591-   CF          ???
1592-   20 D4 C8    JSR   $C8D4
1595-   C5 20       CMP   $20
1597-   C2          ???
1598-   C1 C3       CMP   ($C3,X)
159A-   CB          ???
159B-   C5 C4       CMP   $C4
159D-   20 D5 D0    JSR   $D0D5
15A0-   20 DA C5    JSR   $C5DA
15A3-   D2 CF       CMP   ($CF)
15A5-   20 D0 C1    JSR   $C1D0
15A8-   C7          ???
15A9-   C5 20       CMP   $20
15AB-   C1 D4       CMP   ($D4,X)
15AD-   20 A4 B3    JSR   $B3A4
15B0-   B0 B0       BCS   $1562
15B2-   20 C9 D3    JSR   $D3C9
15B5-   BA          TSX
15B6-   A2 AC       LDX   #$AC
15B8-   B8          CLV
15B9-   C4 B8       CPY   $B8
15BB-   C4 8D       CPY   $8D
15BD-   A0 DF       LDY   #$DF
15BF-   C4 D5       CPY   $D5
15C1-   CD D0 A0    CMP   $A0D0
15C4-   A4 B3       LDY   $B3
15C6-   B0 B0       BCS   $1578
15C8-   BB          ???
15C9-   A3          ???
15CA-   B1 B8       LDA   ($B8),Y
15CC-   8D A0 DF    STA   $DFA0
15CF-   D0 D2       BNE   $15A3
15D1-   CE D4 A0    DEC   $A0D4
15D4-   A2 20       LDX   #$20
15D6-   A2 AC       LDX   #$AC
15D8-   B8          CLV
15D9-   C4 B8       CPY   $B8
15DB-   C4 8D       CPY   $8D
15DD-   A0 DF       LDY   #$DF
15DF-   D0 D2       BNE   $15B3
15E1-   CE D4 A0    DEC   $A0D4
15E4-   A2 B1       LDX   #$B1
15E6-   B8          CLV
15E7-   20 C2 D9    JSR   $D9C2
15EA-   D4          ???
15EB-   C5 D3       CMP   $D3
15ED-   20 C1 D2    JSR   $D2C1
15F0-   C5 20       CMP   $20
15F2-   D5 D3       CMP   $D3,X
15F4-   C5 C4       CMP   $C4
15F6-   AE A2 AC    LDX   $ACA2
15F9-   B8          CLV
15FA-   C4 B8       CPY   $B8
15FC-   C4 8D       CPY   $8D
15FE-   A0 DF       LDY   #$DF
1600-   D7          ???
1601-   C1 C9       CMP   ($C9,X)
1603-   D4          ???
1604-   8D AA 8D    STA   $8DAA
1607-   AA          TAX
1608-   AA          TAX
1609-   20 D9 CF    JSR   $CFD9
160C-   D5 20       CMP   $20,X
160E-   C3          ???
160F-   C1 CE       CMP   ($CE,X)
1611-   20 D2 C5    JSR   $C5D2
1614-   D3          ???
1615-   D4          ???
1616-   CF          ???
1617-   D2 C5       CMP   ($C5)
1619-   20 D4 C8    JSR   $C8D4
161C-   C5 20       CMP   $20
161E-   DA          PHX
161F-   C5 D2       CMP   $D2
1621-   CF          ???
1622-   20 D0 C1    JSR   $C1D0
1625-   C7          ???
1626-   C5 20       CMP   $20
1628-   D4          ???
1629-   CF          ???
162A-   20 C9 D4    JSR   $D4C9
162D-   D3          ???
162E-   8D AA AA    STA   $AAAA
1631-   20 D0 D2    JSR   $D2D0
1634-   C9 CF       CMP   #$CF
1636-   D2 20       CMP   ($20)
1638-   D3          ???
1639-   D4          ???
163A-   C1 D4       CMP   ($D4,X)
163C-   C5 20       CMP   $20
163E-   C2          ???
163F-   D9 20 D4    CMP   $D420,Y
1642-   C8          INY
1643-   C5 CE       CMP   $CE
1645-   20 C3 C1    JSR   $C1C3
1648-   CC CC C9    CPY   $C9CC
164B-   CE C7 20    DEC   $20C7
164E-   DA          PHX
164F-   CD CC CF    CMP   $CFCC
1652-   C1 C4       CMP   ($C4,X)
1654-   AE 8D AA    LDX   $AA8D
1657-   8D AA AA    STA   $AAAA
165A-   20 CD C1    JSR   $C1CD
165D-   C3          ???
165E-   D2 CF       CMP   ($CF)
1660-   BA          TSX
1661-   20 DA CC    JSR   $CCDA
1664-   CF          ???
1665-   C1 C4       CMP   ($C4,X)
1667-   20 C2 C1    JSR   $C1C2
166A-   C3          ???
166B-   CB          ???
166C-   D5 D0       CMP   $D0,X
166E-   DF          ???
166F-   C1 C4       CMP   ($C4,X)
1671-   C4 D2       CPY   $D2
1673-   C5 D3       CMP   $D3
1675-   D3          ???
1676-   8D AA 8D    STA   $8DAA
1679-   A0 CC       LDY   #$CC
167B-   C4 C1       CPY   $C1
167D-   A0 A3       LDY   #$A3
167F-   BE A4 B3    LDX   $B3A4,Y
1682-   B0 B0       BCS   $1634
1684-   A0 BB       LDY   #$BB
1686-   20 C8 C9    JSR   $C9C8
1689-   C7          ???
168A-   C8          INY
168B-   BB          ???
168C-   20 D3 CF    JSR   $CFD3
168F-   D5 D2       CMP   $D2,X
1691-   C3          ???
1692-   C5 8D       CMP   $8D
1694-   A0 D0       LDY   #$D0
1696-   C8          INY
1697-   C1 8D       CMP   ($8D,X)
1699-   A0 CC       LDY   #$CC
169B-   C4 C1       CPY   $C1
169D-   A0 A3       LDY   #$A3
169F-   BC A4 B3    LDY   $B3A4,X
16A2-   B0 B0       BCS   $1654
16A4-   A0 BB       LDY   #$BB
16A6-   20 CC CF    JSR   $CFCC
16A9-   D7          ???
16AA-   8D A0 D0    STA   $D0A0
16AD-   C8          INY
16AE-   C1 8D       CMP   ($8D,X)
16B0-   A0 CA       LDY   #$CA
16B2-   D3          ???
16B3-   D2 20       CMP   ($20)
16B5-   DA          PHX
16B6-   CD CC CF    CMP   $CFCC
16B9-   C1 C4       CMP   ($C4,X)
16BB-   8D AA 8D    STA   $8DAA
16BE-   A0 DF       LDY   #$DF
16C0-   D0 D2       BNE   $1694
16C2-   CE D4 A0    DEC   $A0D4
16C5-   A2 20       LDX   #$20
16C7-   A2 AC       LDX   #$AC
16C9-   B8          CLV
16CA-   C4 B8       CPY   $B8
16CC-   C4 8D       CPY   $8D
16CE-   A0 DF       LDY   #$DF
16D0-   D0 D2       BNE   $16A4
16D2-   CE D4 A0    DEC   $A0D4
16D5-   A2 D9       LDX   #$D9
16D7-   CF          ???
16D8-   D5 20       CMP   $20,X
16DA-   C3          ???
16DB-   C1 CE       CMP   ($CE,X)
16DD-   20 D4 C8    JSR   $C8D4
16E0-   C5 CE       CMP   $CE
16E2-   20 D2 C5    JSR   $C5D2
16E5-   D3          ???
16E6-   D4          ???
16E7-   CF          ???
16E8-   D2 C5       CMP   ($C5)
16EA-   20 D4 C8    JSR   $C8D4
16ED-   C5 20       CMP   $20
16EF-   C6 D2       DEC   $D2
16F1-   C5 C5       CMP   $C5
16F3-   20 DA C5    JSR   $C5DA
16F6-   D2 CF       CMP   ($CF)
16F8-   20 D0 C1    JSR   $C1D0
16FB-   C7          ???
16FC-   C5 A2       CMP   $A2
16FE-   AC B8 C4    LDY   $C4B8
1701-   8D A0 DF    STA   $DFA0
1704-   D0 D2       BNE   $16D8
1706-   CE D4 A0    DEC   $A0D4
1709-   A2 CC       LDX   #$CC
170B-   CF          ???
170C-   C3          ???
170D-   C1 D4       CMP   ($D4,X)
170F-   C9 CF       CMP   #$CF
1711-   CE D3 20    DEC   $20D3
1714-   D7          ???
1715-   C9 D4       CMP   #$D4
1717-   C8          INY
1718-   20 DA CD    JSR   $CDDA
171B-   CC CF C1    CPY   $C1CF
171E-   C4 AE       CPY   $AE
1720-   20 D4 C8    JSR   $C8D4
1723-   C5 D2       CMP   $D2
1725-   C5 20       CMP   $20
1727-   C9 D3       CMP   #$D3
1729-   CE A7 D4    DEC   $D4A7
172C-   20 C1 CE    JSR   $CEC1
172F-   D9 A2 AC    CMP   $ACA2,Y
1732-   B8          CLV
1733-   C4 8D       CPY   $8D
1735-   A0 DF       LDY   #$DF
1737-   D0 D2       BNE   $170B
1739-   CE D4 A0    DEC   $A0D4
173C-   A2 CD       LDX   #$CD
173E-   C5 C1       CMP   $C1
1740-   CE C9 CE    DEC   $CEC9
1743-   C7          ???
1744-   C6 D5       DEC   $D5
1746-   CC 20 CF    CPY   $CF20
1749-   D5 D4       CMP   $D4,X
174B-   D0 D5       BNE   $1722
174D-   D4          ???
174E-   20 D4 CF    JSR   $CFD4
1751-   20 D0 D5    JSR   $D5D0
1754-   D4          ???
1755-   20 C8 C5    JSR   $C5C8
1758-   D2 C5       CMP   ($C5)
175A-   20 D4 CF    JSR   $CFD4
175D-   20 A2 AC    JSR   $ACA2
1760-   B8          CLV
1761-   C4 8D       CPY   $8D
1763-   A0 DF       LDY   #$DF
1765-   D0 D2       BNE   $1739
1767-   CE D4 A0    DEC   $A0D4
176A-   A2 C9       LDX   #$C9
176C-   CC CC D5    CPY   $D5CC
176F-   D3          ???
1770-   D4          ???
1771-   D2 C1       CMP   ($C1)
1773-   D4          ???
1774-   C5 20       CMP   $20
1776-   D4          ???
1777-   C8          INY
1778-   C1 D4       CMP   ($D4,X)
177A-   AC 20 D3    LDY   $D320
177D-   CF          ???
177E-   20 D5 D3    JSR   $D3D5
1781-   C5 20       CMP   $20
1783-   D9 CF D5    CMP   $D5CF,Y
1786-   D2 20       CMP   ($20)
1788-   C9 CD       CMP   #$CD
178A-   C1 C7       CMP   ($C7,X)
178C-   C9 CE       CMP   #$CE
178E-   C1 D4       CMP   ($D4,X)
1790-   C9 CF       CMP   #$CF
1792-   CE A1 A2    DEC   $A2A1
1795-   AC B8 C4    LDY   $C4B8
1798-   B8          CLV
1799-   C4 8D       CPY   $8D
179B-   A0 DF       LDY   #$DF
179D-   D7          ???
179E-   C1 C9       CMP   ($C9,X)
17A0-   D4          ???
17A1-   8D AA 8D    STA   $8DAA
17A4-   A0 CA       LDY   #$CA
17A6-   CD D0 A0    CMP   $A0D0
17A9-   D2 C5       CMP   ($C5)
17AB-   C5 CE       CMP   $CE
17AD-   D4          ???
17AE-   D2 D9       CMP   ($D9)
17B0-   8D AA 8D    STA   $8DAA
17B3-   AA          TAX
17B4-   E0 E0       CPX   #$E0
17B6-   E0 E0       CPX   #$E0
17B8-   E0 E0       CPX   #$E0
17BA-   E0 E0       CPX   #$E0
17BC-   E0 E0       CPX   #$E0
17BE-   E0 E0       CPX   #$E0
17C0-   E0 E0       CPX   #$E0
17C2-   E0 E0       CPX   #$E0
17C4-   E0 E0       CPX   #$E0
17C6-   E0 E0       CPX   #$E0
17C8-   E0 E0       CPX   #$E0
17CA-   E0 E0       CPX   #$E0
17CC-   E0 E0       CPX   #$E0
17CE-   E0 E0       CPX   #$E0
17D0-   E0 E0       CPX   #$E0
17D2-   AA          TAX
17D3-   8D AA 20    STA   $20AA
17D6-   20 20 20    JSR   $2020
17D9-   20 20 20    JSR   $2020
17DC-   20 C2 CF    JSR   $CFC2
17DF-   D4          ???
17E0-   D4          ???
17E1-   CF          ???
17E2-   CD 20 C9    CMP   $C920
17E5-   CE C3 CC    DEC   $CCC3
17E8-   D5 C4       CMP   $C4,X
17EA-   C5 D3       CMP   $D3
17EC-   20 20 20    JSR   $2020
17EF-   20 20 20    JSR   $2020
17F2-   20 AA 8D    JSR   $8DAA
17F5-   AA          TAX
17F6-   AC AC AC    LDY   $ACAC
17F9-   AC AC AC    LDY   $ACAC
17FC-   AC AC AC    LDY   $ACAC
17FF-   AC AC AC    LDY   $ACAC
1802-   AC AC AC    LDY   $ACAC
1805-   AC AC AC    LDY   $ACAC
1808-   AC AC AC    LDY   $ACAC
180B-   AC AC AC    LDY   $ACAC
180E-   AC AC AC    LDY   $ACAC
1811-   AC AC AC    LDY   $ACAC
1814-   AA          TAX
1815-   8D AA 8D    STA   $8DAA
1818-   AA          TAX
1819-   AA          TAX
181A-   20 C2 CF    JSR   $CFC2
181D-   D4          ???
181E-   D4          ???
181F-   CF          ???
1820-   CD 20 C9    CMP   $C920
1823-   CE C3 CC    DEC   $CCC3
1826-   D5 C4       CMP   $C4,X
1828-   C5 D3       CMP   $D3
182A-   8D AA 8D    STA   $8DAA
182D-   A0 D0       LDY   #$D0
182F-   D5 D4       CMP   $D4,X
1831-   A0 C3       LDY   #$C3
1833-   CF          ???
1834-   CD CD CF    CMP   $CFCD
1837-   CE AE CC    DEC   $CCAE
183A-   C9 C2       CMP   #$C2
183C-   8D A0 D0    STA   $D0A0
183F-   D5 D4       CMP   $D4,X
1841-   A0 D2       LDY   #$D2
1843-   C5 D1       CMP   $D1
1845-   D5 C9       CMP   $C9,X
1847-   D2 C5       CMP   ($C5)
1849-   C4 AE       CPY   $AE
184B-   CC C9 C2    CPY   $C2C9
184E-   8D AA 8D    STA   $8DAA
