0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 C3    LDY   $C320,X
0950-   CF          ???
0951-   CD CD CF    CMP   $CFCD
0954-   CE 20 C4    DEC   $C420
0957-   C5 CD       CMP   $CD
0959-   CF          ???
095A-   20 A9 AD    JSR   $ADA9
095D-   20 20 20    JSR   $2020
0960-   20 20 20    JSR   $2020
0963-   20 AA 8D    JSR   $8DAA
0966-   AA          TAX
0967-   20 20 20    JSR   $2020
096A-   20 20 20    JSR   $2020
096D-   20 20 20    JSR   $2020
0970-   20 20 20    JSR   $2020
0973-   20 20 20    JSR   $2020
0976-   20 20 20    JSR   $2020
0979-   20 20 20    JSR   $2020
097C-   20 20 20    JSR   $2020
097F-   20 20 20    JSR   $2020
0982-   20 20 20    JSR   $2020
0985-   AA          TAX
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B2       BCS   $094E
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B1    JSR   $B120
09D4-   B2 AD       LDA   ($AD)
09D6-   C4 C5       CPY   $C5
09D8-   C3          ???
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B8       LDA   ($B8),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 C4    STA   $C4A0
0B02-   D3          ???
0B03-   CB          ???
0B04-   A0 C3       LDY   #$C3
0B06-   CF          ???
0B07-   CD CD CF    CMP   $CFCD
0B0A-   CE AE C4    DEC   $C4AE
0B0D-   C5 CD       CMP   $CD
0B0F-   CF          ???
0B10-   8D A0 CF    STA   $CFA0
0B13-   C2          ???
0B14-   CA          DEX
0B15-   A0 A4       LDY   #$A4
0B17-   C2          ???
0B18-   C6 C5       DEC   $C5
0B1A-   B0 8D       BCS   $0AA9
0B1C-   A0 CF       LDY   #$CF
0B1E-   D2 C7       CMP   ($C7)
0B20-   A0 A4       LDY   #$A4
0B22-   B6 B0       LDX   $B0,Y
0B24-   B0 B0       BCS   $0AD6
0B26-   8D AA 8D    STA   $8DAA
0B29-   AA          TAX
0B2A-   E0 E0       CPX   #$E0
0B2C-   E0 E0       CPX   #$E0
0B2E-   E0 E0       CPX   #$E0
0B30-   E0 E0       CPX   #$E0
0B32-   E0 E0       CPX   #$E0
0B34-   E0 E0       CPX   #$E0
0B36-   E0 E0       CPX   #$E0
0B38-   E0 E0       CPX   #$E0
0B3A-   E0 E0       CPX   #$E0
0B3C-   E0 E0       CPX   #$E0
0B3E-   E0 E0       CPX   #$E0
0B40-   E0 E0       CPX   #$E0
0B42-   E0 E0       CPX   #$E0
0B44-   E0 E0       CPX   #$E0
0B46-   E0 E0       CPX   #$E0
0B48-   AA          TAX
0B49-   8D AA 20    STA   $20AA
0B4C-   20 D4 CF    JSR   $CFD4
0B4F-   D0 20       BNE   $0B71
0B51-   C9 CE       CMP   #$CE
0B53-   C3          ???
0B54-   CC D5 C4    CPY   $C4D5
0B57-   C5 D3       CMP   $D3
0B59-   20 A8 C8    JSR   $C8A8
0B5C-   CF          ???
0B5D-   CF          ???
0B5E-   CB          ???
0B5F-   D3          ???
0B60-   AC CD C1    LDY   $C1CD
0B63-   C3          ???
0B64-   D2 CF       CMP   ($CF)
0B66-   D3          ???
0B67-   A9 20       LDA   #$20
0B69-   AA          TAX
0B6A-   8D AA AC    STA   $ACAA
0B6D-   AC AC AC    LDY   $ACAC
0B70-   AC AC AC    LDY   $ACAC
0B73-   AC AC AC    LDY   $ACAC
0B76-   AC AC AC    LDY   $ACAC
0B79-   AC AC AC    LDY   $ACAC
0B7C-   AC AC AC    LDY   $ACAC
0B7F-   AC AC AC    LDY   $ACAC
0B82-   AC AC AC    LDY   $ACAC
0B85-   AC AC AC    LDY   $ACAC
0B88-   AC AC AA    LDY   $AAAC
0B8B-   8D AA 8D    STA   $8DAA
0B8E-   A0 D5       LDY   #$D5
0B90-   D3          ???
0B91-   C5 A0       CMP   $A0
0B93-   D2 C5       CMP   ($C5)
0B95-   D1 D5       CMP   ($D5),Y
0B97-   C9 D2       CMP   #$D2
0B99-   C5 C4       CMP   $C4
0B9B-   AE CD C1    LDX   $C1CD
0B9E-   C3          ???
0B9F-   AE CD C9    LDX   $C9CD
0BA2-   CE 8D A0    DEC   $A08D
0BA5-   D0 D5       BNE   $0B7C
0BA7-   D4          ???
0BA8-   A0 D2       LDY   #$D2
0BAA-   C5 D1       CMP   $D1
0BAC-   D5 C9       CMP   $C9,X
0BAE-   D2 C5       CMP   ($C5)
0BB0-   C4 AE       CPY   $AE
0BB2-   C8          INY
0BB3-   CF          ???
0BB4-   CF          ???
0BB5-   CB          ???
0BB6-   D3          ???
0BB7-   AE CD C9    LDX   $C9CD
0BBA-   CE 8D A0    DEC   $A08D
0BBD-   D5 D3       CMP   $D3,X
0BBF-   C5 A0       CMP   $A0
0BC1-   C3          ???
0BC2-   CF          ???
0BC3-   CD CD CF    CMP   $CFCD
0BC6-   CE AE CD    DEC   $CDAE
0BC9-   C1 C3       CMP   ($C3,X)
0BCB-   8D A0 D0    STA   $D0A0
0BCE-   D5 D4       CMP   $D4,X
0BD0-   20 A0 C3    JSR   $C3A0
0BD3-   CF          ???
0BD4-   CD CD CF    CMP   $CFCD
0BD7-   CE AE C8    DEC   $C8AE
0BDA-   CF          ???
0BDB-   CF          ???
0BDC-   CB          ???
0BDD-   D3          ???
0BDE-   8D AA 8D    STA   $8DAA
0BE1-   AA          TAX
0BE2-   E0 E0       CPX   #$E0
0BE4-   E0 E0       CPX   #$E0
0BE6-   E0 E0       CPX   #$E0
0BE8-   E0 E0       CPX   #$E0
0BEA-   E0 E0       CPX   #$E0
0BEC-   E0 E0       CPX   #$E0
0BEE-   E0 E0       CPX   #$E0
0BF0-   E0 E0       CPX   #$E0
0BF2-   E0 E0       CPX   #$E0
0BF4-   E0 E0       CPX   #$E0
0BF6-   E0 E0       CPX   #$E0
0BF8-   E0 E0       CPX   #$E0
0BFA-   E0 E0       CPX   #$E0
0BFC-   E0 E0       CPX   #$E0
0BFE-   E0 E0       CPX   #$E0
0C00-   AA          TAX
0C01-   8D AA 20    STA   $20AA
0C04-   20 20 20    JSR   $2020
0C07-   20 20 D0    JSR   $D020
0C0A-   D2 CF       CMP   ($CF)
0C0C-   C7          ???
0C0D-   D2 C1       CMP   ($C1)
0C0F-   CD 20 CD    CMP   $CD20
0C12-   C1 C9       CMP   ($C9,X)
0C14-   CE 20 C2    DEC   $C220
0C17-   CF          ???
0C18-   C4 D9       CPY   $D9
0C1A-   20 20 20    JSR   $2020
0C1D-   20 20 20    JSR   $2020
0C20-   20 AA 8D    JSR   $8DAA
0C23-   AA          TAX
0C24-   AC AC AC    LDY   $ACAC
0C27-   AC AC AC    LDY   $ACAC
0C2A-   AC AC AC    LDY   $ACAC
0C2D-   AC AC AC    LDY   $ACAC
0C30-   AC AC AC    LDY   $ACAC
0C33-   AC AC AC    LDY   $ACAC
0C36-   AC AC AC    LDY   $ACAC
0C39-   AC AC AC    LDY   $ACAC
0C3C-   AC AC AC    LDY   $ACAC
0C3F-   AC AC AC    LDY   $ACAC
0C42-   AA          TAX
0C43-   8D AA 8D    STA   $8DAA
0C46-   AA          TAX
0C47-   AA          TAX
0C48-   20 CD C5    JSR   $C5CD
0C4B-   CD C6 C9    CMP   $C9C6
0C4E-   CC CC 20    CPY   $20CC
0C51-   C4 CF       CPY   $CF
0C53-   C5 D3       CMP   $D3
0C55-   20 C1 C2    JSR   $C2C1
0C58-   CF          ???
0C59-   D5 D4       CMP   $D4,X
0C5B-   20 D7 C8    JSR   $C8D7
0C5E-   C1 D4       CMP   ($D4,X)
0C60-   20 C9 D4    JSR   $D4C9
0C63-   D3          ???
0C64-   20 CE C1    JSR   $C1CE
0C67-   CD C5 8D    CMP   $8DC5
0C6A-   AA          TAX
0C6B-   AA          TAX
0C6C-   20 C9 CD    JSR   $CDC9
0C6F-   D0 CC       BNE   $0C3D
0C71-   C9 C5       CMP   #$C5
0C73-   D3          ???
0C74-   BA          TSX
0C75-   20 C9 D4    JSR   $D4C9
0C78-   20 C6 C9    JSR   $C9C6
0C7B-   CC CC D3    CPY   $D3CC
0C7E-   20 C1 20    JSR   $20C1
0C81-   C2          ???
0C82-   CC CF C3    CPY   $C3CF
0C85-   CB          ???
0C86-   20 CF C6    JSR   $C6CF
0C89-   20 CD C5    JSR   $C5CD
0C8C-   CD CF D2    CMP   $D2CF
0C8F-   D9 8D AA    CMP   $AA8D,Y
0C92-   AA          TAX
0C93-   20 D7 C9    JSR   $C9D7
0C96-   D4          ???
0C97-   C8          INY
0C98-   20 C1 20    JSR   $20C1
0C9B-   D0 C1       BNE   $0C5E
0C9D-   D2 D4       CMP   ($D4)
0C9F-   C9 C3       CMP   #$C3
0CA1-   D5 CC       CMP   $CC,X
0CA3-   C1 D2       CMP   ($D2,X)
0CA5-   20 C3 C8    JSR   $C8C3
0CA8-   C1 D2       CMP   ($D2,X)
0CAA-   C1 C3       CMP   ($C3,X)
0CAC-   D4          ???
0CAD-   C5 D2       CMP   $D2
0CAF-   AE 8D AA    LDX   $AA8D
0CB2-   8D AA AA    STA   $AAAA
0CB5-   20 CD C1    JSR   $C1CD
0CB8-   C3          ???
0CB9-   D2 CF       CMP   ($CF)
0CBB-   BA          TSX
0CBC-   20 CD C6    JSR   $C6CD
0CBF-   C9 CC       CMP   #$CC
0CC1-   CC 20 C1    CPY   $C120
0CC4-   C4 C4       CPY   $C4
0CC6-   D2 C5       CMP   ($C5)
0CC8-   D3          ???
0CC9-   D3          ???
0CCA-   DF          ???
0CCB-   D3          ???
0CCC-   D4          ???
0CCD-   C1 D2       CMP   ($D2,X)
0CCF-   D4          ???
0CD0-   BB          ???
0CD1-   C2          ???
0CD2-   D9 D4 C5    CMP   $C5D4,Y
0CD5-   DF          ???
0CD6-   CC C5 CE    CPY   $CEC5
0CD9-   C7          ???
0CDA-   D4          ???
0CDB-   C8          INY
0CDC-   BB          ???
0CDD-   C6 C9       DEC   $C9
0CDF-   CC CC DF    CPY   $DFCC
0CE2-   D6 C1       DEC   $C1,X
0CE4-   CC D5 C5    CPY   $C5D5
0CE7-   8D AA 8D    STA   $8DAA
0CEA-   A0 CC       LDY   #$CC
0CEC-   C4 C1       CPY   $C1
0CEE-   A0 A3       LDY   #$A3
0CF0-   BE A4 B3    LDX   $B3A4,Y
0CF3-   B0 B0       BCS   $0CA5
0CF5-   A0 BB       LDY   #$BB
0CF7-   20 C1 D2    JSR   $D2C1
0CFA-   C5 C1       CMP   $C1
0CFC-   20 D4 CF    JSR   $CFD4
0CFF-   20 C6 C9    JSR   $C9C6
0D02-   CC CC BB    CPY   $BBCC
0D05-   20 C8 C9    JSR   $C9C8
0D08-   C7          ???
0D09-   C8          INY
0D0A-   8D A0 D0    STA   $D0A0
0D0D-   C8          INY
0D0E-   C1 8D       CMP   ($8D,X)
0D10-   A0 CC       LDY   #$CC
0D12-   C4 C1       CPY   $C1
0D14-   A0 A3       LDY   #$A3
0D16-   BC A4 B3    LDY   $B3A4,X
0D19-   B0 B0       BCS   $0CCB
0D1B-   A0 BB       LDY   #$BB
0D1D-   20 CC CF    JSR   $CFCC
0D20-   D7          ???
0D21-   8D A0 D0    STA   $D0A0
0D24-   C8          INY
0D25-   C1 8D       CMP   ($8D,X)
0D27-   A0 CC       LDY   #$CC
0D29-   C4 C1       CPY   $C1
0D2B-   A0 A3       LDY   #$A3
0D2D-   BE B1 B0    LDX   $B0B1,Y
0D30-   8D A0 D0    STA   $D0A0
0D33-   C8          INY
0D34-   C1 8D       CMP   ($8D,X)
0D36-   A0 CC       LDY   #$CC
0D38-   C4 C1       CPY   $C1
0D3A-   A0 A3       LDY   #$A3
0D3C-   BC B1 B0    LDY   $B0B1,X
0D3F-   8D A0 D0    STA   $D0A0
0D42-   C8          INY
0D43-   C1 8D       CMP   ($8D,X)
0D45-   A0 CC       LDY   #$CC
0D47-   C4 C1       CPY   $C1
0D49-   A0 A3       LDY   #$A3
0D4B-   B0 A0       BCS   $0CED
0D4D-   BB          ???
0D4E-   20 C6 C9    JSR   $C9C6
0D51-   CC CC 20    CPY   $20CC
0D54-   C3          ???
0D55-   C8          INY
0D56-   C1 D2       CMP   ($D2,X)
0D58-   C1 C3       CMP   ($C3,X)
0D5A-   D4          ???
0D5B-   C5 D2       CMP   $D2
0D5D-   8D A0 D0    STA   $D0A0
0D60-   C8          INY
0D61-   C1 8D       CMP   ($8D,X)
0D63-   A0 CA       LDY   #$CA
0D65-   D3          ???
0D66-   D2 A0       CMP   ($A0)
0D68-   CD C5 CD    CMP   $CDC5
0D6B-   C6 C9       DEC   $C9
0D6D-   CC CC 8D    CPY   $8DCC
0D70-   AA          TAX
0D71-   8D A0 DF    STA   $DFA0
0D74-   D0 D2       BNE   $0D48
0D76-   CE D4 A0    DEC   $A0D4
0D79-   A2 CD       LDX   #$CD
0D7B-   C5 CD       CMP   $CD
0D7D-   C6 C9       DEC   $C9
0D7F-   CC CC 20    CPY   $20CC
0D82-   C6 C9       DEC   $C9
0D84-   CC CC D3    CPY   $D3CC
0D87-   20 C1 20    JSR   $20C1
0D8A-   D0 CF       BNE   $0D5B
0D8C-   D2 D4       CMP   ($D4)
0D8E-   C9 CF       CMP   #$CF
0D90-   CE 20 CF    DEC   $CF20
0D93-   C6 20       DEC   $20
0D95-   CD C5 CD    CMP   $CDC5
0D98-   CF          ???
0D99-   D2 D9       CMP   ($D9)
0D9B-   20 D7 C9    JSR   $C9D7
0D9E-   D4          ???
0D9F-   C8          INY
0DA0-   A2 AC       LDX   #$AC
0DA2-   B8          CLV
0DA3-   C4 8D       CPY   $8D
0DA5-   A0 DF       LDY   #$DF
0DA7-   D0 D2       BNE   $0D7B
0DA9-   CE D4 A0    DEC   $A0D4
0DAC-   A2 C1       LDX   #$C1
0DAE-   20 D3 D0    JSR   $D0D3
0DB1-   C5 C3       CMP   $C3
0DB3-   C9 C6       CMP   #$C6
0DB5-   C9 C5       CMP   #$C5
0DB7-   C4 20       CPY   $20
0DB9-   D6 C1       DEC   $C1,X
0DBB-   CC D5 C5    CPY   $C5D5
0DBE-   AE 20 A2    LDX   $A220
0DC1-   AC B8 C4    LDY   $C4B8
0DC4-   B8          CLV
0DC5-   C4 8D       CPY   $8D
0DC7-   A0 DF       LDY   #$DF
0DC9-   C4 D5       CPY   $D5
0DCB-   CD D0 A0    CMP   $A0D0
0DCE-   A4 B3       LDY   $B3
0DD0-   B0 B0       BCS   $0D82
0DD2-   BB          ???
0DD3-   A3          ???
0DD4-   B1 B0       LDA   ($B0),Y
0DD6-   8D A0 DF    STA   $DFA0
0DD9-   D7          ???
0DDA-   C1 C9       CMP   ($C9,X)
0DDC-   D4          ???
0DDD-   8D AA 8D    STA   $8DAA
0DE0-   AA          TAX
0DE1-   AA          TAX
0DE2-   20 CD C5    JSR   $C5CD
0DE5-   CD CD CF    CMP   $CFCD
0DE8-   D6 C5       DEC   $C5,X
0DEA-   20 C1 CC    JSR   $CCC1
0DED-   D3          ???
0DEE-   CF          ???
0DEF-   20 C4 CF    JSR   $CFC4
0DF2-   C5 D3       CMP   $D3
0DF4-   20 D7 C8    JSR   $C8D7
0DF7-   C1 D4       CMP   ($D4,X)
0DF9-   20 C9 D4    JSR   $D4C9
0DFC-   20 D3 C1    JSR   $C1D3
0DFF-   D9 D3 BA    CMP   $BAD3,Y
0E02-   20 C9 D4    JSR   $D4C9
0E05-   20 CD CF    JSR   $CFCD
0E08-   D6 C5       DEC   $C5,X
0E0A-   D3          ???
0E0B-   8D AA AA    STA   $AAAA
0E0E-   20 C1 20    JSR   $20C1
0E11-   C2          ???
0E12-   CC CF C3    CPY   $C3CF
0E15-   CB          ???
0E16-   20 CF C6    JSR   $C6CF
0E19-   20 CD C5    JSR   $C5CD
0E1C-   CD CF D2    CMP   $D2CF
0E1F-   D9 20 C6    CMP   $C620,Y
0E22-   D2 CF       CMP   ($CF)
0E24-   CD 20 C1    CMP   $C120
0E27-   20 D3 CF    JSR   $CFD3
0E2A-   D5 D2       CMP   $D2,X
0E2C-   C3          ???
0E2D-   C5 20       CMP   $20
0E2F-   CC CF C3    CPY   $C3CF
0E32-   C1 D4       CMP   ($D4,X)
0E34-   C9 CF       CMP   #$CF
0E36-   CE 8D AA    DEC   $AA8D
0E39-   AA          TAX
0E3A-   20 D4 CF    JSR   $CFD4
0E3D-   20 C1 20    JSR   $20C1
0E40-   C4 C5       CPY   $C5
0E42-   D3          ???
0E43-   D4          ???
0E44-   C9 CE       CMP   #$CE
0E46-   C1 D4       CMP   ($D4,X)
0E48-   C9 CF       CMP   #$CF
0E4A-   CE 20 CC    DEC   $CC20
0E4D-   CF          ???
0E4E-   C3          ???
0E4F-   C1 D4       CMP   ($D4,X)
0E51-   C9 CF       CMP   #$CF
0E53-   CE AE 20    DEC   $20AE
0E56-   D7          ???
0E57-   C5 A7       CMP   $A7
0E59-   CC CC 20    CPY   $20CC
0E5C-   CE CF D7    DEC   $D7CF
0E5F-   20 CD CF    JSR   $CFCD
0E62-   D6 C5       DEC   $C5,X
0E64-   8D AA AA    STA   $AAAA
0E67-   20 D4 C8    JSR   $C8D4
0E6A-   CF          ???
0E6B-   D3          ???
0E6C-   C5 20       CMP   $20
0E6E-   DA          PHX
0E6F-   C5 D2       CMP   $D2
0E71-   CF          ???
0E72-   C5 D3       CMP   $D3
0E74-   20 D0 CC    JSR   $CCD0
0E77-   C1 C3       CMP   ($C3,X)
0E79-   C5 C4       CMP   $C4
0E7B-   20 C2 D9    JSR   $D9C2
0E7E-   20 CD C5    JSR   $C5CD
0E81-   CD C6 C9    CMP   $C9C6
0E84-   CC CC 20    CPY   $20CC
0E87-   D4          ???
0E88-   CF          ???
0E89-   20 C1 CE    JSR   $CEC1
0E8C-   CF          ???
0E8D-   D4          ???
0E8E-   C8          INY
0E8F-   C5 D2       CMP   $D2
0E91-   8D AA AA    STA   $AAAA
0E94-   20 CC CF    JSR   $CFCC
0E97-   C3          ???
0E98-   C1 D4       CMP   ($D4,X)
0E9A-   C9 CF       CMP   #$CF
0E9C-   CE AE 8D    DEC   $8DAE
0E9F-   AA          TAX
0EA0-   8D AA AA    STA   $AAAA
0EA3-   20 CD C1    JSR   $C1CD
0EA6-   C3          ???
0EA7-   D2 CF       CMP   ($CF)
0EA9-   BA          TSX
0EAA-   20 CD CD    JSR   $CDCD
0EAD-   CF          ???
0EAE-   D6 C5       DEC   $C5,X
0EB0-   20 D3 D2    JSR   $D2D3
0EB3-   C3          ???
0EB4-   DF          ???
0EB5-   C1 C4       CMP   ($C4,X)
0EB7-   C4 D2       CPY   $D2
0EB9-   BB          ???
0EBA-   C4 C5       CPY   $C5
0EBC-   D3          ???
0EBD-   D4          ???
0EBE-   DF          ???
0EBF-   C1 C4       CMP   ($C4,X)
0EC1-   C4 D2       CPY   $D2
0EC3-   BB          ???
0EC4-   C2          ???
0EC5-   D9 D4 C5    CMP   $C5D4,Y
0EC8-   DF          ???
0EC9-   CC C5 CE    CPY   $CEC5
0ECC-   C7          ???
0ECD-   D4          ???
0ECE-   C8          INY
0ECF-   8D AA 8D    STA   $8DAA
0ED2-   A0 CC       LDY   #$CC
0ED4-   C4 C1       CPY   $C1
0ED6-   A0 A3       LDY   #$A3
0ED8-   BE A4 B3    LDX   $B3A4,Y
0EDB-   B0 B0       BCS   $0E8D
0EDD-   A0 BB       LDY   #$BB
0EDF-   20 D3 D2    JSR   $D2D3
0EE2-   C3          ???
0EE3-   20 C8 C9    JSR   $C9C8
0EE6-   C7          ???
0EE7-   C8          INY
0EE8-   8D A0 D0    STA   $D0A0
0EEB-   C8          INY
0EEC-   C1 8D       CMP   ($8D,X)
0EEE-   A0 CC       LDY   #$CC
0EF0-   C4 C1       CPY   $C1
0EF2-   A0 A3       LDY   #$A3
0EF4-   BC A4 B3    LDY   $B3A4,X
0EF7-   B0 B0       BCS   $0EA9
0EF9-   A0 BB       LDY   #$BB
0EFB-   20 D3 D2    JSR   $D2D3
0EFE-   C3          ???
0EFF-   20 CC CF    JSR   $CFCC
0F02-   D7          ???
0F03-   8D A0 D0    STA   $D0A0
0F06-   C8          INY
0F07-   C1 8D       CMP   ($8D,X)
0F09-   A0 CC       LDY   #$CC
0F0B-   C4 C1       CPY   $C1
0F0D-   A0 A3       LDY   #$A3
0F0F-   BE A4 B3    LDX   $B3A4,Y
0F12-   B2 B0       LDA   ($B0)
0F14-   A0 BB       LDY   #$BB
0F16-   20 C4 C5    JSR   $C5C4
0F19-   D3          ???
0F1A-   D4          ???
0F1B-   20 C8 C9    JSR   $C9C8
0F1E-   C7          ???
0F1F-   C8          INY
0F20-   8D A0 D0    STA   $D0A0
0F23-   C8          INY
0F24-   C1 8D       CMP   ($8D,X)
0F26-   A0 CC       LDY   #$CC
0F28-   C4 C1       CPY   $C1
0F2A-   A0 A3       LDY   #$A3
0F2C-   BC A4 B3    LDY   $B3A4,X
0F2F-   B2 B0       LDA   ($B0)
0F31-   A0 BB       LDY   #$BB
0F33-   20 C4 C5    JSR   $C5C4
0F36-   D3          ???
0F37-   D4          ???
0F38-   20 CC CF    JSR   $CFCC
0F3B-   D7          ???
0F3C-   8D A0 D0    STA   $D0A0
0F3F-   C8          INY
0F40-   C1 8D       CMP   ($8D,X)
0F42-   A0 CC       LDY   #$CC
0F44-   C4 C1       CPY   $C1
0F46-   A0 A3       LDY   #$A3
0F48-   BE B1 B0    LDX   $B0B1,Y
0F4B-   A0 BB       LDY   #$BB
0F4D-   20 A3 20    JSR   $20A3
0F50-   CF          ???
0F51-   C6 20       DEC   $20
0F53-   C2          ???
0F54-   D9 D4 C5    CMP   $C5D4,Y
0F57-   D3          ???
0F58-   20 D4 CF    JSR   $CFD4
0F5B-   20 CD CF    JSR   $CFCD
0F5E-   D6 C5       DEC   $C5,X
0F60-   8D A0 D0    STA   $D0A0
0F63-   C8          INY
0F64-   C1 8D       CMP   ($8D,X)
0F66-   A0 CC       LDY   #$CC
0F68-   C4 C1       CPY   $C1
0F6A-   A0 A3       LDY   #$A3
0F6C-   BC B1 B0    LDY   $B0B1,X
0F6F-   A0 BB       LDY   #$BB
0F71-   20 CC CF    JSR   $CFCC
0F74-   D7          ???
0F75-   20 C2 D9    JSR   $D9C2
0F78-   D4          ???
0F79-   C5 8D       CMP   $8D
0F7B-   A0 D0       LDY   #$D0
0F7D-   C8          INY
0F7E-   C1 8D       CMP   ($8D,X)
0F80-   A0 CA       LDY   #$CA
0F82-   D3          ???
0F83-   D2 A0       CMP   ($A0)
0F85-   CD C5 CD    CMP   $CDC5
0F88-   CD CF D6    CMP   $D6CF
0F8B-   C5 8D       CMP   $8D
0F8D-   AA          TAX
0F8E-   8D A0 DF    STA   $DFA0
0F91-   D0 D2       BNE   $0F65
0F93-   CE D4 A0    DEC   $A0D4
0F96-   A2 20       LDX   #$20
0F98-   A2 AC       LDX   #$AC
0F9A-   B8          CLV
0F9B-   C4 B8       CPY   $B8
0F9D-   C4 8D       CPY   $8D
0F9F-   A0 DF       LDY   #$DF
0FA1-   D0 D2       BNE   $0F75
0FA3-   CE D4 A0    DEC   $A0D4
0FA6-   A2 CD       LDX   #$CD
0FA8-   C5 CD       CMP   $CD
0FAA-   CD CF D6    CMP   $D6CF
0FAD-   C5 20       CMP   $20
0FAF-   CD CF D6    CMP   $D6CF
0FB2-   C5 D3       CMP   $D3
0FB4-   20 C3 CF    JSR   $CFC3
0FB7-   D0 C9       BNE   $0F82
0FB9-   C5 D3       CMP   $D3
0FBB-   20 C1 20    JSR   $20C1
0FBE-   D3          ???
0FBF-   D0 C1       BNE   $0F82
0FC1-   CE 20 CF    DEC   $CF20
0FC4-   C6 20       DEC   $20
0FC6-   CD C5 CD    CMP   $CDC5
0FC9-   CF          ???
0FCA-   D2 D9       CMP   ($D9)
0FCC-   A2 AC       LDX   #$AC
0FCE-   B8          CLV
0FCF-   C4 8D       CPY   $8D
0FD1-   A0 DF       LDY   #$DF
0FD3-   D0 D2       BNE   $0FA7
0FD5-   CE D4 A0    DEC   $A0D4
0FD8-   A2 C6       LDX   #$C6
0FDA-   D2 CF       CMP   ($CF)
0FDC-   CD 20 C1    CMP   $C120
0FDF-   20 D3 CF    JSR   $CFD3
0FE2-   D5 D2       CMP   $D2,X
0FE4-   C3          ???
0FE5-   C5 20       CMP   $20
0FE7-   D4          ???
0FE8-   CF          ???
0FE9-   20 C1 20    JSR   $20C1
0FEC-   C4 C5       CPY   $C5
0FEE-   D3          ???
0FEF-   D4          ???
0FF0-   C9 CE       CMP   #$CE
0FF2-   C1 D4       CMP   ($D4,X)
0FF4-   C9 CF       CMP   #$CF
0FF6-   CE 20 C1    DEC   $C120
0FF9-   C4 C4       CPY   $C4
0FFB-   D2 C5       CMP   ($C5)
0FFD-   D3          ???
0FFE-   D3          ???
0FFF-   AE A2 AC    LDX   $ACA2
1002-   B8          CLV
1003-   C4 B8       CPY   $B8
1005-   C4 8D       CPY   $8D
1007-   A0 DF       LDY   #$DF
1009-   D0 D2       BNE   $0FDD
100B-   CE D4 A0    DEC   $A0D4
100E-   A2 D3       LDX   #$D3
1010-   CF          ???
1011-   20 CD CF    JSR   $CFCD
1014-   D6 C9       DEC   $C9,X
1016-   CE C7 20    DEC   $20C7
1019-   A4 B3       LDY   $B3
101B-   B0 B0       BCS   $0FCD
101D-   20 D4 CF    JSR   $CFD4
1020-   20 A4 B3    JSR   $B3A4
1023-   B2 B0       LDA   ($B0)
1025-   20 D2 C5    JSR   $C5D2
1028-   D3          ???
1029-   D5 CC       CMP   $CC,X
102B-   D4          ???
102C-   D3          ???
102D-   20 C9 CE    JSR   $CEC9
1030-   BA          TSX
1031-   A2 AC       LDX   #$AC
1033-   B8          CLV
1034-   C4 B8       CPY   $B8
1036-   C4 8D       CPY   $8D
1038-   A0 DF       LDY   #$DF
103A-   C4 D5       CPY   $D5
103C-   CD D0 A0    CMP   $A0D0
103F-   A4 B3       LDY   $B3
1041-   B2 B0       LDA   ($B0)
1043-   BB          ???
1044-   A3          ???
1045-   B1 B0       LDA   ($B0),Y
1047-   8D A0 DF    STA   $DFA0
104A-   D7          ???
104B-   C1 C9       CMP   ($C9,X)
104D-   D4          ???
104E-   8D AA 8D    STA   $8DAA
1051-   AA          TAX
1052-   AA          TAX
1053-   20 C4 C5    JSR   $C5C4
1056-   CC C1 D9    CPY   $D9C1
1059-   CD D3 20    CMP   $20D3
105C-   D2 D5       CMP   ($D5)
105E-   CE D3 20    DEC   $20D3
1061-   D4          ???
1062-   C8          INY
1063-   D2 CF       CMP   ($CF)
1065-   D5 C7       CMP   $C7,X
1067-   C8          INY
1068-   20 C3 D9    JSR   $D9C3
106B-   C3          ???
106C-   CC C5 D3    CPY   $D3C5
106F-   20 CF C6    JSR   $C6CF
1072-   20 D4 C8    JSR   $C8D4
1075-   C5 8D       CMP   $8D
1077-   AA          TAX
1078-   AA          TAX
1079-   20 B6 B5    JSR   $B5B6
107C-   B0 B2       BCS   $1030
107E-   20 D5 CE    JSR   $CED5
1081-   D4          ???
1082-   C9 CC       CMP   #$CC
1084-   20 C1 20    JSR   $20C1
1087-   C3          ???
1088-   C5 D2       CMP   $D2
108A-   D4          ???
108B-   C1 C9       CMP   ($C9,X)
108D-   CE 20 C1    DEC   $C120
1090-   CD CF D5    CMP   $D5CF
1093-   CE D4 20    DEC   $20D4
1096-   CF          ???
1097-   C6 20       DEC   $20
1099-   D4          ???
109A-   C9 CD       CMP   #$CD
109C-   C5 8D       CMP   $8D
109E-   AA          TAX
109F-   AA          TAX
10A0-   20 C8 C1    JSR   $C1C8
10A3-   D3          ???
10A4-   20 D0 C1    JSR   $C1D0
10A7-   D3          ???
10A8-   D3          ???
10A9-   C5 C4       CMP   $C4
10AB-   AE 8D AA    LDX   $AA8D
10AE-   8D AA AA    STA   $AAAA
10B1-   20 CD C1    JSR   $C1CD
10B4-   C3          ???
10B5-   D2 CF       CMP   ($CF)
10B7-   BA          TSX
10B8-   20 C4 C5    JSR   $C5C4
10BB-   CC C1 D9    CPY   $D9C1
10BE-   20 A3 B2    JSR   $B2A3
10C1-   B5 B0       LDA   $B0,X
10C3-   8D AA 8D    STA   $8DAA
10C6-   A0 DF       LDY   #$DF
10C8-   D0 D2       BNE   $109C
10CA-   CE D4 A0    DEC   $A0D4
10CD-   A2 20       LDX   #$20
10CF-   A2 AC       LDX   #$AC
10D1-   B8          CLV
10D2-   C4 B8       CPY   $B8
10D4-   C4 8D       CPY   $8D
10D6-   A0 DF       LDY   #$DF
10D8-   D0 D2       BNE   $10AC
10DA-   CE D4 A0    DEC   $A0D4
10DD-   A2 C4       LDX   #$C4
10DF-   C5 CC       CMP   $CC
10E1-   C1 D9       CMP   ($D9,X)
10E3-   CD D3 20    CMP   $20D3
10E6-   C4 C5       CPY   $C5
10E8-   CC C1 D9    CPY   $D9C1
10EB-   D3          ???
10EC-   20 C1 20    JSR   $20C1
10EF-   D3          ???
10F0-   D0 C5       BNE   $10B7
10F2-   C3          ???
10F3-   C9 C6       CMP   #$C6
10F5-   C9 C5       CMP   #$C5
10F7-   C4 20       CPY   $20
10F9-   CE D5 CD    DEC   $CDD5
10FC-   C2          ???
10FD-   C5 D2       CMP   $D2
10FF-   20 CF C6    JSR   $C6CF
1102-   A2 AC       LDX   #$AC
1104-   B8          CLV
1105-   C4 8D       CPY   $8D
1107-   A0 DF       LDY   #$DF
1109-   D0 D2       BNE   $10DD
110B-   CE D4 A0    DEC   $A0D4
110E-   A2 CD       LDX   #$CD
1110-   C9 CC       CMP   #$CC
1112-   CC C9 D3    CPY   $D3C9
1115-   C5 C3       CMP   $C3
1117-   CF          ???
1118-   CE C4 D3    DEC   $D3C4
111B-   AE 20 B2    LDX   $B220
111E-   B5 B0       LDA   $B0,X
1120-   20 CD C9    JSR   $C9CD
1123-   CC CC C9    CPY   $C9CC
1126-   D3          ???
1127-   C5 C3       CMP   $C3
1129-   CF          ???
112A-   CE C4 D3    DEC   $D3C4
112D-   20 BD 20    JSR   $20BD
1130-   B1 AF       LDA   ($AF),Y
1132-   B4 20       LDY   $20,X
1134-   D3          ???
1135-   C5 C3       CMP   $C3
1137-   CF          ???
1138-   CE C4 AE    DEC   $AEC4
113B-   A2 AC       LDX   #$AC
113D-   B8          CLV
113E-   C4 B8       CPY   $B8
1140-   C4 8D       CPY   $8D
1142-   AA          TAX
1143-   8D A0 CC    STA   $CCA0
1146-   C4 D9       CPY   $D9
1148-   A0 A3       LDY   #$A3
114A-   B2 B5       LDA   ($B5)
114C-   B0 A0       BCS   $10EE
114E-   BB          ???
114F-   20 D4 C9    JSR   $C9D4
1152-   CD C5 20    CMP   $20C5
1155-   C9 CE       CMP   #$CE
1157-   20 CD C9    JSR   $C9CD
115A-   CC CC C9    CPY   $C9CC
115D-   D3          ???
115E-   C5 C3       CMP   $C3
1160-   CF          ???
1161-   CE C4 D3    DEC   $D3C4
1164-   8D BB 20    STA   $20BB
1167-   C9 D3       CMP   #$D3
1169-   20 D0 C1    JSR   $C1D0
116C-   D3          ???
116D-   D3          ???
116E-   C5 C4       CMP   $C4
1170-   20 D6 C9    JSR   $C9D6
1173-   C1 20       CMP   ($20,X)
1175-   D9 8D BB    CMP   $BB8D,Y
1178-   20 B2 B5    JSR   $B5B2
117B-   B0 20       BCS   $119D
117D-   BD 20 B1    LDA   $B120,X
1180-   AF          ???
1181-   B4 20       LDY   $20,X
1183-   D3          ???
1184-   C5 C3       CMP   $C3
1186-   CF          ???
1187-   CE C4 8D    DEC   $8DC4
118A-   A0 CA       LDY   #$CA
118C-   D3          ???
118D-   D2 A0       CMP   ($A0)
118F-   C4 C5       CPY   $C5
1191-   CC C1 D9    CPY   $D9C1
1194-   CD D3 8D    CMP   $8DD3
1197-   A0 C2       LDY   #$C2
1199-   C5 C5       CMP   $C5
119B-   D0 A0       BNE   $113D
119D-   B1 8D       LDA   ($8D),Y
119F-   A0 DF       LDY   #$DF
11A1-   D0 D2       BNE   $1175
11A3-   CE D4 A0    DEC   $A0D4
11A6-   A2 B1       LDX   #$B1
11A8-   AF          ???
11A9-   B4 20       LDY   $20,X
11AB-   D3          ???
11AC-   C5 C3       CMP   $C3
11AE-   CF          ???
11AF-   CE C4 A2    DEC   $A2C4
11B2-   AC B8 C4    LDY   $C4B8
11B5-   8D A0 CC    STA   $CCA0
11B8-   C4 D9       CPY   $D9
11BA-   A0 A3       LDY   #$A3
11BC-   B2 B5       LDA   ($B5)
11BE-   B0 8D       BCS   $114D
11C0-   A0 CA       LDY   #$CA
11C2-   D3          ???
11C3-   D2 A0       CMP   ($A0)
11C5-   C4 C5       CPY   $C5
11C7-   CC C1 D9    CPY   $D9C1
11CA-   CD D3 8D    CMP   $8DD3
11CD-   A0 C2       LDY   #$C2
11CF-   C5 C5       CMP   $C5
11D1-   D0 A0       BNE   $1173
11D3-   B2 8D       LDA   ($8D)
11D5-   A0 DF       LDY   #$DF
11D7-   D0 D2       BNE   $11AB
11D9-   CE D4 A0    DEC   $A0D4
11DC-   A2 B1       LDX   #$B1
11DE-   AF          ???
11DF-   B4 20       LDY   $20,X
11E1-   D3          ???
11E2-   C5 C3       CMP   $C3
11E4-   CF          ???
11E5-   CE C4 A2    DEC   $A2C4
11E8-   AC B8 C4    LDY   $C4B8
11EB-   8D A0 CC    STA   $CCA0
11EE-   C4 D9       CPY   $D9
11F0-   A0 A3       LDY   #$A3
11F2-   B2 B5       LDA   ($B5)
11F4-   B0 8D       BCS   $1183
11F6-   A0 CA       LDY   #$CA
11F8-   D3          ???
11F9-   D2 A0       CMP   ($A0)
11FB-   C4 C5       CPY   $C5
11FD-   CC C1 D9    CPY   $D9C1
1200-   CD D3 8D    CMP   $8DD3
1203-   A0 C2       LDY   #$C2
1205-   C5 C5       CMP   $C5
1207-   D0 A0       BNE   $11A9
1209-   B3          ???
120A-   8D A0 DF    STA   $DFA0
120D-   D0 D2       BNE   $11E1
120F-   CE D4 A0    DEC   $A0D4
1212-   A2 B1       LDX   #$B1
1214-   AF          ???
1215-   B4 20       LDY   $20,X
1217-   D3          ???
1218-   C5 C3       CMP   $C3
121A-   CF          ???
121B-   CE C4 A2    DEC   $A2C4
121E-   AC B8 C4    LDY   $C4B8
1221-   8D A0 CC    STA   $CCA0
1224-   C4 D9       CPY   $D9
1226-   A0 A3       LDY   #$A3
1228-   B2 B5       LDA   ($B5)
122A-   B0 8D       BCS   $11B9
122C-   A0 CA       LDY   #$CA
122E-   D3          ???
122F-   D2 A0       CMP   ($A0)
1231-   C4 C5       CPY   $C5
1233-   CC C1 D9    CPY   $D9C1
1236-   CD D3 A0    CMP   $A0D3
1239-   BB          ???
123A-   20 BD 20    JSR   $20BD
123D-   B1 20       LDA   ($20),Y
123F-   D3          ???
1240-   C5 C3       CMP   $C3
1242-   CF          ???
1243-   CE C4 20    DEC   $20C4
1246-   C4 C5       CPY   $C5
1248-   CC C1 D9    CPY   $D9C1
124B-   8D A0 C2    STA   $C2A0
124E-   C5 C5       CMP   $C5
1250-   D0 A0       BNE   $11F2
1252-   B4 8D       LDY   $8D,X
1254-   A0 DF       LDY   #$DF
1256-   D0 D2       BNE   $122A
1258-   CE D4 A0    DEC   $A0D4
125B-   A2 B1       LDX   #$B1
125D-   AF          ???
125E-   B4 20       LDY   $20,X
1260-   D3          ???
1261-   C5 C3       CMP   $C3
1263-   CF          ???
1264-   CE C4 A2    DEC   $A2C4
1267-   AC B8 C4    LDY   $C4B8
126A-   8D AA 8D    STA   $8DAA
126D-   A0 DF       LDY   #$DF
126F-   D0 D2       BNE   $1243
1271-   CE D4 A0    DEC   $A0D4
1274-   A2 20       LDX   #$20
1276-   A2 AC       LDX   #$AC
1278-   B8          CLV
1279-   C4 B8       CPY   $B8
127B-   C4 8D       CPY   $8D
127D-   A0 DF       LDY   #$DF
127F-   D7          ???
1280-   C1 C9       CMP   ($C9,X)
1282-   D4          ???
1283-   8D AA 8D    STA   $8DAA
1286-   AA          TAX
1287-   AA          TAX
1288-   20 DA CD    JSR   $CDDA
128B-   D3          ???
128C-   C1 D6       CMP   ($D6,X)
128E-   C5 20       CMP   $20
1290-   C2          ???
1291-   C1 C3       CMP   ($C3,X)
1293-   CB          ???
1294-   D3          ???
1295-   20 D5 D0    JSR   $D0D5
1298-   20 D4 C8    JSR   $C8D4
129B-   C5 20       CMP   $20
129D-   A2 C6       LDX   #$C6
129F-   D2 C5       CMP   ($C5)
12A1-   C5 A2       CMP   $A2
12A3-   20 C1 D2    JSR   $D2C1
12A6-   C5 C1       CMP   $C1
12A8-   D3          ???
12A9-   20 CF C6    JSR   $C6CF
12AC-   8D AA AA    STA   $AAAA
12AF-   20 D4 C8    JSR   $C8D4
12B2-   C5 20       CMP   $20
12B4-   DA          PHX
12B5-   C5 D2       CMP   $D2
12B7-   CF          ???
12B8-   20 D0 C1    JSR   $C1D0
12BB-   C7          ???
12BC-   C5 20       CMP   $20
12BE-   D4          ???
12BF-   CF          ???
12C0-   20 C1 CE    JSR   $CEC1
12C3-   20 C1 CC    JSR   $CCC1
12C6-   D4          ???
12C7-   C5 D2       CMP   $D2
12C9-   CE C1 D4    DEC   $D4C1
12CC-   C5 20       CMP   $20
12CE-   CD C5 CD    CMP   $CDC5
12D1-   CF          ???
12D2-   D2 D9       CMP   ($D9)
12D4-   8D AA AA    STA   $AAAA
12D7-   20 CC CF    JSR   $CFCC
12DA-   C3          ???
12DB-   C1 D4       CMP   ($D4,X)
12DD-   C9 CF       CMP   #$CF
12DF-   CE AE 20    DEC   $20AE
12E2-   D4          ???
12E3-   C8          INY
12E4-   C9 D3       CMP   #$D3
12E6-   20 C9 D3    JSR   $D3C9
12E9-   20 CD CF    JSR   $CFCD
12EC-   D3          ???
12ED-   D4          ???
12EE-   CC D9 20    CPY   $20D9
12F1-   D5 D3       CMP   $D3,X
12F3-   C5 C6       CMP   $C6
12F5-   D5 CC       CMP   $CC,X
12F7-   20 D7 C8    JSR   $C8D7
12FA-   C5 CE       CMP   $CE
12FC-   8D AA AA    STA   $AAAA
12FF-   20 D9 CF    JSR   $CFD9
1302-   D5 20       CMP   $20,X
1304-   CB          ???
1305-   CE CF D7    DEC   $D7CF
1308-   20 C1 20    JSR   $20C1
130B-   D2 CF       CMP   ($CF)
130D-   D5 D4       CMP   $D4,X
130F-   C9 CE       CMP   #$CE
1311-   C5 20       CMP   $20
1313-   D5 D3       CMP   $D3,X
1315-   C5 D3       CMP   $D3
1317-   20 D4 C8    JSR   $C8D4
131A-   C5 20       CMP   $20
131C-   DA          PHX
131D-   C5 D2       CMP   $D2
131F-   CF          ???
1320-   20 D0 C1    JSR   $C1D0
1323-   C7          ???
1324-   C5 AC       CMP   $AC
1326-   8D AA AA    STA   $AAAA
1329-   20 C2 D5    JSR   $D5C2
132C-   D4          ???
132D-   20 D9 CF    JSR   $CFD9
1330-   D5 20       CMP   $20,X
1332-   D7          ???
1333-   C1 CE       CMP   ($CE,X)
1335-   D4          ???
1336-   20 D4 CF    JSR   $CFD4
1339-   20 CB C5    JSR   $C5CB
133C-   C5 D0       CMP   $D0
133E-   20 D4 C8    JSR   $C8D4
1341-   C5 20       CMP   $20
1343-   D6 C1       DEC   $C1,X
1345-   CC D5 C5    CPY   $C5D5
1348-   D3          ???
1349-   20 C3 D5    JSR   $D5C3
134C-   D2 D2       CMP   ($D2)
134E-   C5 CE       CMP   $CE
1350-   D4          ???
1351-   CC D9 8D    CPY   $8DD9
1354-   AA          TAX
1355-   AA          TAX
1356-   20 D3 D4    JSR   $D4D3
1359-   CF          ???
135A-   D2 C5       CMP   ($C5)
135C-   C4 20       CPY   $20
135E-   D4          ???
135F-   C8          INY
1360-   C5 D2       CMP   $D2
1362-   C5 20       CMP   $20
1364-   C1 C6       CMP   ($C6,X)
1366-   D4          ???
1367-   C5 D2       CMP   $D2
1369-   20 C3 C1    JSR   $C1C3
136C-   CC CC C9    CPY   $C9CC
136F-   CE C7 20    DEC   $20C7
1372-   D4          ???
1373-   C8          INY
1374-   C5 20       CMP   $20
1376-   D2 CF       CMP   ($CF)
1378-   D5 D4       CMP   $D4,X
137A-   C9 CE       CMP   #$CE
137C-   C5 AE       CMP   $AE
137E-   8D AA 8D    STA   $8DAA
1381-   AA          TAX
1382-   AA          TAX
1383-   20 CE CF    JSR   $CFCE
1386-   D4          ???
1387-   C5 20       CMP   $20
1389-   D4          ???
138A-   C8          INY
138B-   C1 D4       CMP   ($D4,X)
138D-   20 D3 C9    JSR   $C9D3
1390-   CE C3 C5    DEC   $C5C3
1393-   20 D4 C8    JSR   $C8D4
1396-   C5 20       CMP   $20
1398-   CC C9 C2    CPY   $C2C9
139B-   D2 C1       CMP   ($C1)
139D-   D2 D9       CMP   ($D9)
139F-   20 CD C1    JSR   $C1CD
13A2-   CB          ???
13A3-   C5 D3       CMP   $D3
13A5-   20 C8 C5    JSR   $C5C8
13A8-   C1 D6       CMP   ($D6,X)
13AA-   D9 20 D5    CMP   $D520,Y
13AD-   D3          ???
13AE-   C5 8D       CMP   $8D
13B0-   AA          TAX
13B1-   AA          TAX
13B2-   20 CF C6    JSR   $C6CF
13B5-   20 D4 C8    JSR   $C8D4
13B8-   C5 D3       CMP   $D3
13BA-   C5 20       CMP   $20
13BC-   CD C5 CD    CMP   $CDC5
13BF-   CF          ???
13C0-   D2 D9       CMP   ($D9)
13C2-   20 C1 C4    JSR   $C4C1
13C5-   C4 D2       CPY   $D2
13C7-   C5 D3       CMP   $D3
13C9-   D3          ???
13CA-   C5 D3       CMP   $D3
13CC-   AC 20 C1    LDY   $C120
13CF-   CE D9 20    DEC   $20D9
13D2-   D4          ???
13D3-   C9 CD       CMP   #$CD
13D5-   C5 20       CMP   $20
13D7-   D9 CF D5    CMP   $D5CF,Y
13DA-   D2 20       CMP   ($20)
13DC-   C3          ???
13DD-   CF          ???
13DE-   C4 C5       CPY   $C5
13E0-   8D AA AA    STA   $AAAA
13E3-   20 CD C1    JSR   $C1CD
13E6-   CB          ???
13E7-   C5 D3       CMP   $D3
13E9-   20 D5 D3    JSR   $D3D5
13EC-   C5 20       CMP   $20
13EE-   CF          ???
13EF-   C6 20       DEC   $20
13F1-   D4          ???
13F2-   C8          INY
13F3-   C5 20       CMP   $20
13F5-   DA          PHX
13F6-   C5 D2       CMP   $D2
13F8-   CF          ???
13F9-   20 D0 C1    JSR   $C1D0
13FC-   C7          ???
13FD-   C5 AC       CMP   $AC
13FF-   20 C9 D4    JSR   $D4C9
1402-   20 C9 D3    JSR   $D3C9
1405-   20 C1 C4    JSR   $C4C1
1408-   D6 C9       DEC   $C9,X
140A-   D3          ???
140B-   C5 C4       CMP   $C4
140D-   20 D4 CF    JSR   $CFD4
1410-   8D AA AA    STA   $AAAA
1413-   20 D3 C1    JSR   $C1D3
1416-   D6 C5       DEC   $C5,X
1418-   20 D4 C8    JSR   $C8D4
141B-   C5 20       CMP   $20
141D-   D3          ???
141E-   D4          ???
141F-   C1 D4       CMP   ($D4,X)
1421-   C5 20       CMP   $20
1423-   C2          ???
1424-   C5 C6       CMP   $C6
1426-   CF          ???
1427-   D2 C5       CMP   ($C5)
1429-   20 C3 C1    JSR   $C1C3
142C-   CC CC C9    CPY   $C9CC
142F-   CE C7 20    DEC   $20C7
1432-   C1 CE       CMP   ($CE,X)
1434-   D9 20 CF    CMP   $CF20,Y
1437-   D4          ???
1438-   C8          INY
1439-   C5 D2       CMP   $D2
143B-   20 D2 CF    JSR   $CFD2
143E-   D5 D4       CMP   $D4,X
1440-   C9 CE       CMP   #$CE
1442-   C5 D3       CMP   $D3
1444-   AE 8D AA    LDX   $AA8D
1447-   8D AA AA    STA   $AAAA
144A-   20 CD C1    JSR   $C1CD
144D-   C3          ???
144E-   D2 CF       CMP   ($CF)
1450-   BA          TSX
1451-   20 DA D3    JSR   $D3DA
1454-   C1 D6       CMP   ($D6,X)
1456-   C5 20       CMP   $20
1458-   20 C2 C1    JSR   $C1C2
145B-   C3          ???
145C-   CB          ???
145D-   D5 D0       CMP   $D0,X
145F-   DF          ???
1460-   C1 C4       CMP   ($C4,X)
1462-   C4 D2       CPY   $D2
1464-   8D AA 8D    STA   $8DAA
1467-   A0 CC       LDY   #$CC
1469-   C4 C1       CPY   $C1
146B-   A0 A3       LDY   #$A3
146D-   B0 B1       BCS   $1420
146F-   8D A0 D3    STA   $D3A0
1472-   D4          ???
1473-   C1 A0       CMP   ($A0,X)
1475-   A4 B0       LDY   $B0
1477-   B6 8D       LDX   $8D,Y
1479-   A0 CC       LDY   #$CC
147B-   C4 C1       CPY   $C1
147D-   A0 A3       LDY   #$A3
147F-   B0 B2       BCS   $1433
1481-   8D A0 D3    STA   $D3A0
1484-   D4          ???
1485-   C1 A0       CMP   ($A0,X)
1487-   A4 B0       LDY   $B0
1489-   B7          ???
148A-   8D A0 CC    STA   $CCA0
148D-   C4 C1       CPY   $C1
148F-   A0 A3       LDY   #$A3
1491-   B0 B3       BCS   $1446
1493-   8D A0 D3    STA   $D3A0
1496-   D4          ???
1497-   C1 A0       CMP   ($A0,X)
1499-   A4 B0       LDY   $B0
149B-   B8          CLV
149C-   8D A0 CC    STA   $CCA0
149F-   C4 C1       CPY   $C1
14A1-   A0 A3       LDY   #$A3
14A3-   B0 B4       BCS   $1459
14A5-   8D A0 D3    STA   $D3A0
14A8-   D4          ???
14A9-   C1 A0       CMP   ($A0,X)
14AB-   A4 B0       LDY   $B0
14AD-   B9 8D A0    LDA   $A08D,Y
14B0-   CC C4 C1    CPY   $C1C4
14B3-   A0 A3       LDY   #$A3
14B5-   BE A4 B3    LDX   $B3A4,Y
14B8-   B0 B0       BCS   $146A
14BA-   8D A0 D0    STA   $D0A0
14BD-   C8          INY
14BE-   C1 8D       CMP   ($8D,X)
14C0-   A0 CC       LDY   #$CC
14C2-   C4 C1       CPY   $C1
14C4-   A0 A3       LDY   #$A3
14C6-   BC A4 B3    LDY   $B3A4,X
14C9-   B0 B0       BCS   $147B
14CB-   A0 BB       LDY   #$BB
14CD-   20 CC CF    JSR   $CFCC
14D0-   D7          ???
14D1-   20 C4 C5    JSR   $C5C4
14D4-   D3          ???
14D5-   D4          ???
14D6-   8D A0 D0    STA   $D0A0
14D9-   C8          INY
14DA-   C1 8D       CMP   ($8D,X)
14DC-   A0 CA       LDY   #$CA
14DE-   D3          ???
14DF-   D2 A0       CMP   ($A0)
14E1-   DA          PHX
14E2-   CD D3 C1    CMP   $C1D3
14E5-   D6 C5       DEC   $C5,X
14E7-   8D AA 8D    STA   $8DAA
14EA-   A0 DF       LDY   #$DF
14EC-   D0 D2       BNE   $14C0
14EE-   CE D4 A0    DEC   $A0D4
14F1-   A2 20       LDX   #$20
14F3-   A2 AC       LDX   #$AC
14F5-   B8          CLV
14F6-   C4 B8       CPY   $B8
14F8-   C4 8D       CPY   $8D
14FA-   A0 DF       LDY   #$DF
14FC-   D0 D2       BNE   $14D0
14FE-   CE D4 A0    DEC   $A0D4
1501-   A2 DA       LDX   #$DA
1503-   CD D3 C1    CMP   $C1D3
1506-   D6 C5       DEC   $C5,X
1508-   20 D3 C1    JSR   $C1D3
150B-   D6 C5       DEC   $C5,X
150D-   D3          ???
150E-   20 D4 C8    JSR   $C8D4
1511-   C5 20       CMP   $20
1513-   D3          ???
1514-   D4          ???
1515-   C1 D4       CMP   ($D4,X)
1517-   C5 20       CMP   $20
1519-   CF          ???
151A-   C6 20       DEC   $20
151C-   D4          ???
151D-   C8          INY
151E-   C5 20       CMP   $20
1520-   DA          PHX
1521-   C5 D2       CMP   $D2
1523-   CF          ???
1524-   20 D0 C1    JSR   $C1D0
1527-   C7          ???
1528-   C5 20       CMP   $20
152A-   A2 AC       LDX   #$AC
152C-   B8          CLV
152D-   C4 8D       CPY   $8D
152F-   A0 DF       LDY   #$DF
1531-   D0 D2       BNE   $1505
1533-   CE D4 A0    DEC   $A0D4
1536-   A2 C1       LDX   #$C1
1538-   C4 C4       CPY   $C4
153A-   D2 C5       CMP   ($C5)
153C-   D3          ???
153D-   D3          ???
153E-   C5 D3       CMP   $D3
1540-   20 D4 C8    JSR   $C8D4
1543-   C1 D4       CMP   ($D4,X)
1545-   20 C1 D2    JSR   $D2C1
1548-   C5 20       CMP   $20
154A-   CE CF D4    DEC   $D4CF
154D-   20 D5 D3    JSR   $D3D5
1550-   C5 C4       CMP   $C4
1552-   20 C2 D9    JSR   $D9C2
1555-   20 C4 CF    JSR   $CFC4
1558-   D3          ???
1559-   AC A2 AC    LDY   $ACA2
155C-   B8          CLV
155D-   C4 8D       CPY   $8D
155F-   A0 DF       LDY   #$DF
1561-   D0 D2       BNE   $1535
1563-   CE D4 A0    DEC   $A0D4
1566-   A2 C1       LDX   #$C1
1568-   D0 D0       BNE   $153A
156A-   CC C5 D3    CPY   $D3C5
156D-   CF          ???
156E-   C6 D4       DEC   $D4
1570-   AC D0 D2    LDY   $D2D0
1573-   CF          ???
1574-   C4 CF       CPY   $CF
1576-   D3          ???
1577-   20 CF D2    JSR   $D2CF
157A-   20 C9 CE    JSR   $CEC9
157D-   D4          ???
157E-   C5 C7       CMP   $C7
1580-   C5 D2       CMP   $D2
1582-   20 C2 C1    JSR   $C1C2
1585-   D3          ???
1586-   C9 C3       CMP   #$C3
1588-   AE A2 AC    LDX   $ACA2
158B-   B8          CLV
158C-   C4 B8       CPY   $B8
158E-   C4 8D       CPY   $8D
1590-   A0 DF       LDY   #$DF
1592-   D0 D2       BNE   $1566
1594-   CE D4 A0    DEC   $A0D4
1597-   A2 D3       LDX   #$D3
1599-   CF          ???
159A-   20 D4 C8    JSR   $C8D4
159D-   C5 20       CMP   $20
159F-   C2          ???
15A0-   C1 C3       CMP   ($C3,X)
15A2-   CB          ???
15A3-   C5 C4       CMP   $C4
15A5-   20 D5 D0    JSR   $D0D5
15A8-   20 DA C5    JSR   $C5DA
15AB-   D2 CF       CMP   ($CF)
15AD-   20 D0 C1    JSR   $C1D0
15B0-   C7          ???
15B1-   C5 20       CMP   $20
15B3-   C1 D4       CMP   ($D4,X)
15B5-   20 A4 B3    JSR   $B3A4
15B8-   B0 B0       BCS   $156A
15BA-   20 C9 D3    JSR   $D3C9
15BD-   BA          TSX
15BE-   A2 AC       LDX   #$AC
15C0-   B8          CLV
15C1-   C4 B8       CPY   $B8
15C3-   C4 8D       CPY   $8D
15C5-   A0 DF       LDY   #$DF
15C7-   C4 D5       CPY   $D5
15C9-   CD D0 A0    CMP   $A0D0
15CC-   A4 B3       LDY   $B3
15CE-   B0 B0       BCS   $1580
15D0-   BB          ???
15D1-   A3          ???
15D2-   B1 B8       LDA   ($B8),Y
15D4-   8D A0 DF    STA   $DFA0
15D7-   D0 D2       BNE   $15AB
15D9-   CE D4 A0    DEC   $A0D4
15DC-   A2 20       LDX   #$20
15DE-   A2 AC       LDX   #$AC
15E0-   B8          CLV
15E1-   C4 B8       CPY   $B8
15E3-   C4 8D       CPY   $8D
15E5-   A0 DF       LDY   #$DF
15E7-   D0 D2       BNE   $15BB
15E9-   CE D4 A0    DEC   $A0D4
15EC-   A2 B1       LDX   #$B1
15EE-   B8          CLV
15EF-   20 C2 D9    JSR   $D9C2
15F2-   D4          ???
15F3-   C5 D3       CMP   $D3
15F5-   20 C1 D2    JSR   $D2C1
15F8-   C5 20       CMP   $20
15FA-   D5 D3       CMP   $D3,X
15FC-   C5 C4       CMP   $C4
15FE-   AE A2 AC    LDX   $ACA2
1601-   B8          CLV
1602-   C4 B8       CPY   $B8
1604-   C4 8D       CPY   $8D
1606-   A0 DF       LDY   #$DF
1608-   D7          ???
1609-   C1 C9       CMP   ($C9,X)
160B-   D4          ???
160C-   8D AA 8D    STA   $8DAA
160F-   AA          TAX
1610-   AA          TAX
1611-   20 D9 CF    JSR   $CFD9
1614-   D5 20       CMP   $20,X
1616-   C3          ???
1617-   C1 CE       CMP   ($CE,X)
1619-   20 D2 C5    JSR   $C5D2
161C-   D3          ???
161D-   D4          ???
161E-   CF          ???
161F-   D2 C5       CMP   ($C5)
1621-   20 D4 C8    JSR   $C8D4
1624-   C5 20       CMP   $20
1626-   DA          PHX
1627-   C5 D2       CMP   $D2
1629-   CF          ???
162A-   20 D0 C1    JSR   $C1D0
162D-   C7          ???
162E-   C5 20       CMP   $20
1630-   D4          ???
1631-   CF          ???
1632-   20 C9 D4    JSR   $D4C9
1635-   D3          ???
1636-   8D AA AA    STA   $AAAA
1639-   20 D0 D2    JSR   $D2D0
163C-   C9 CF       CMP   #$CF
163E-   D2 20       CMP   ($20)
1640-   D3          ???
1641-   D4          ???
1642-   C1 D4       CMP   ($D4,X)
1644-   C5 20       CMP   $20
1646-   C2          ???
1647-   D9 20 D4    CMP   $D420,Y
164A-   C8          INY
164B-   C5 CE       CMP   $CE
164D-   20 C3 C1    JSR   $C1C3
1650-   CC CC C9    CPY   $C9CC
1653-   CE C7 20    DEC   $20C7
1656-   DA          PHX
1657-   CD CC CF    CMP   $CFCC
165A-   C1 C4       CMP   ($C4,X)
165C-   AE 8D AA    LDX   $AA8D
165F-   8D AA AA    STA   $AAAA
1662-   20 CD C1    JSR   $C1CD
1665-   C3          ???
1666-   D2 CF       CMP   ($CF)
1668-   BA          TSX
1669-   20 DA CC    JSR   $CCDA
166C-   CF          ???
166D-   C1 C4       CMP   ($C4,X)
166F-   20 C2 C1    JSR   $C1C2
1672-   C3          ???
1673-   CB          ???
1674-   D5 D0       CMP   $D0,X
1676-   DF          ???
1677-   C1 C4       CMP   ($C4,X)
1679-   C4 D2       CPY   $D2
167B-   C5 D3       CMP   $D3
167D-   D3          ???
167E-   8D AA 8D    STA   $8DAA
1681-   A0 CC       LDY   #$CC
1683-   C4 C1       CPY   $C1
1685-   A0 A3       LDY   #$A3
1687-   BE A4 B3    LDX   $B3A4,Y
168A-   B0 B0       BCS   $163C
168C-   A0 BB       LDY   #$BB
168E-   20 C8 C9    JSR   $C9C8
1691-   C7          ???
1692-   C8          INY
1693-   BB          ???
1694-   20 D3 CF    JSR   $CFD3
1697-   D5 D2       CMP   $D2,X
1699-   C3          ???
169A-   C5 8D       CMP   $8D
169C-   A0 D0       LDY   #$D0
169E-   C8          INY
169F-   C1 8D       CMP   ($8D,X)
16A1-   A0 CC       LDY   #$CC
16A3-   C4 C1       CPY   $C1
16A5-   A0 A3       LDY   #$A3
16A7-   BC A4 B3    LDY   $B3A4,X
16AA-   B0 B0       BCS   $165C
16AC-   A0 BB       LDY   #$BB
16AE-   20 CC CF    JSR   $CFCC
16B1-   D7          ???
16B2-   8D A0 D0    STA   $D0A0
16B5-   C8          INY
16B6-   C1 8D       CMP   ($8D,X)
16B8-   A0 CA       LDY   #$CA
16BA-   D3          ???
16BB-   D2 20       CMP   ($20)
16BD-   DA          PHX
16BE-   CD CC CF    CMP   $CFCC
16C1-   C1 C4       CMP   ($C4,X)
16C3-   8D AA 8D    STA   $8DAA
16C6-   A0 DF       LDY   #$DF
16C8-   D0 D2       BNE   $169C
16CA-   CE D4 A0    DEC   $A0D4
16CD-   A2 20       LDX   #$20
16CF-   A2 AC       LDX   #$AC
16D1-   B8          CLV
16D2-   C4 B8       CPY   $B8
16D4-   C4 8D       CPY   $8D
16D6-   A0 DF       LDY   #$DF
16D8-   D0 D2       BNE   $16AC
16DA-   CE D4 A0    DEC   $A0D4
16DD-   A2 D9       LDX   #$D9
16DF-   CF          ???
16E0-   D5 20       CMP   $20,X
16E2-   C3          ???
16E3-   C1 CE       CMP   ($CE,X)
16E5-   20 D4 C8    JSR   $C8D4
16E8-   C5 CE       CMP   $CE
16EA-   20 D2 C5    JSR   $C5D2
16ED-   D3          ???
16EE-   D4          ???
16EF-   CF          ???
16F0-   D2 C5       CMP   ($C5)
16F2-   20 D4 C8    JSR   $C8D4
16F5-   C5 20       CMP   $20
16F7-   C6 D2       DEC   $D2
16F9-   C5 C5       CMP   $C5
16FB-   20 DA C5    JSR   $C5DA
16FE-   D2 CF       CMP   ($CF)
1700-   20 D0 C1    JSR   $C1D0
1703-   C7          ???
1704-   C5 A2       CMP   $A2
1706-   AC B8 C4    LDY   $C4B8
1709-   8D A0 DF    STA   $DFA0
170C-   D0 D2       BNE   $16E0
170E-   CE D4 A0    DEC   $A0D4
1711-   A2 CC       LDX   #$CC
1713-   CF          ???
1714-   C3          ???
1715-   C1 D4       CMP   ($D4,X)
1717-   C9 CF       CMP   #$CF
1719-   CE D3 20    DEC   $20D3
171C-   D7          ???
171D-   C9 D4       CMP   #$D4
171F-   C8          INY
1720-   20 DA CD    JSR   $CDDA
1723-   CC CF C1    CPY   $C1CF
1726-   C4 AE       CPY   $AE
1728-   20 D4 C8    JSR   $C8D4
172B-   C5 D2       CMP   $D2
172D-   C5 20       CMP   $20
172F-   C9 D3       CMP   #$D3
1731-   CE A7 D4    DEC   $D4A7
1734-   20 C1 CE    JSR   $CEC1
1737-   D9 A2 AC    CMP   $ACA2,Y
173A-   B8          CLV
173B-   C4 8D       CPY   $8D
173D-   A0 DF       LDY   #$DF
173F-   D0 D2       BNE   $1713
1741-   CE D4 A0    DEC   $A0D4
1744-   A2 CD       LDX   #$CD
1746-   C5 C1       CMP   $C1
1748-   CE C9 CE    DEC   $CEC9
174B-   C7          ???
174C-   C6 D5       DEC   $D5
174E-   CC 20 CF    CPY   $CF20
1751-   D5 D4       CMP   $D4,X
1753-   D0 D5       BNE   $172A
1755-   D4          ???
1756-   20 D4 CF    JSR   $CFD4
1759-   20 D0 D5    JSR   $D5D0
175C-   D4          ???
175D-   20 C8 C5    JSR   $C5C8
1760-   D2 C5       CMP   ($C5)
1762-   20 D4 CF    JSR   $CFD4
1765-   20 A2 AC    JSR   $ACA2
1768-   B8          CLV
1769-   C4 8D       CPY   $8D
176B-   A0 DF       LDY   #$DF
176D-   D0 D2       BNE   $1741
176F-   CE D4 A0    DEC   $A0D4
1772-   A2 C9       LDX   #$C9
1774-   CC CC D5    CPY   $D5CC
1777-   D3          ???
1778-   D4          ???
1779-   D2 C1       CMP   ($C1)
177B-   D4          ???
177C-   C5 20       CMP   $20
177E-   D4          ???
177F-   C8          INY
1780-   C1 D4       CMP   ($D4,X)
1782-   AC 20 D3    LDY   $D320
1785-   CF          ???
1786-   20 D5 D3    JSR   $D3D5
1789-   C5 20       CMP   $20
178B-   D9 CF D5    CMP   $D5CF,Y
178E-   D2 20       CMP   ($20)
1790-   C9 CD       CMP   #$CD
1792-   C1 C7       CMP   ($C7,X)
1794-   C9 CE       CMP   #$CE
1796-   C1 D4       CMP   ($D4,X)
1798-   C9 CF       CMP   #$CF
179A-   CE A1 A2    DEC   $A2A1
179D-   AC B8 C4    LDY   $C4B8
17A0-   B8          CLV
17A1-   C4 8D       CPY   $8D
17A3-   A0 DF       LDY   #$DF
17A5-   D7          ???
17A6-   C1 C9       CMP   ($C9,X)
17A8-   D4          ???
17A9-   8D AA 8D    STA   $8DAA
17AC-   AA          TAX
17AD-   AA          TAX
17AE-   20 D4 C8    JSR   $C8D4
17B1-   C5 20       CMP   $20
17B3-   DF          ???
17B4-   CD D3 D7    CMP   $D7D3
17B7-   C1 D0       CMP   ($D0,X)
17B9-   20 CD C1    JSR   $C1CD
17BC-   C3          ???
17BD-   D2 CF       CMP   ($CF)
17BF-   20 D3 D7    JSR   $D7D3
17C2-   C1 D0       CMP   ($D0,X)
17C4-   D3          ???
17C5-   20 D4 C8    JSR   $C8D4
17C8-   C5 20       CMP   $20
17CA-   CD C5 CD    CMP   $CDC5
17CD-   CF          ???
17CE-   D2 D9       CMP   ($D9)
17D0-   20 C2 CC    JSR   $CCC2
17D3-   CF          ???
17D4-   C3          ???
17D5-   CB          ???
17D6-   20 C1 D4    JSR   $D4C1
17D9-   20 CF CE    JSR   $CECF
17DC-   C5 8D       CMP   $8D
17DE-   AA          TAX
17DF-   AA          TAX
17E0-   20 C1 C4    JSR   $C4C1
17E3-   C4 D2       CPY   $D2
17E5-   C5 D3       CMP   $D3
17E7-   D3          ???
17E8-   20 D7 C9    JSR   $C9D7
17EB-   D4          ???
17EC-   C8          INY
17ED-   20 D4 C8    JSR   $C8D4
17F0-   C5 20       CMP   $20
17F2-   D3          ???
17F3-   C1 CD       CMP   ($CD,X)
17F5-   C5 20       CMP   $20
17F7-   CC C5 CE    CPY   $CEC5
17FA-   C7          ???
17FB-   D4          ???
17FC-   C8          INY
17FD-   20 C1 D4    JSR   $D4C1
1800-   20 C1 CE    JSR   $CEC1
1803-   CF          ???
1804-   D4          ???
1805-   C8          INY
1806-   C5 D2       CMP   $D2
1808-   AE 8D AA    LDX   $AA8D
180B-   8D A0 DF    STA   $DFA0
180E-   D0 D2       BNE   $17E2
1810-   CE D4 A0    DEC   $A0D4
1813-   A2 D4       LDX   #$D4
1815-   C8          INY
1816-   C5 20       CMP   $20
1818-   CD D3 D7    CMP   $D7D3
181B-   C1 D0       CMP   ($D0,X)
181D-   20 CD C1    JSR   $C1CD
1820-   C3          ???
1821-   D2 CF       CMP   ($CF)
1823-   20 D3 D7    JSR   $D7D3
1826-   C1 D0       CMP   ($D0,X)
1828-   D3          ???
1829-   20 C1 20    JSR   $20C1
182C-   CC C5 CE    CPY   $CEC5
182F-   C7          ???
1830-   D4          ???
1831-   C8          INY
1832-   A2 AC       LDX   #$AC
1834-   B8          CLV
1835-   C4 8D       CPY   $8D
1837-   A0 DF       LDY   #$DF
1839-   D0 D2       BNE   $180D
183B-   CE D4 A0    DEC   $A0D4
183E-   A2 CF       LDX   #$CF
1840-   C6 20       DEC   $20
1842-   CD C5 CD    CMP   $CDC5
1845-   CF          ???
1846-   D2 D9       CMP   ($D9)
1848-   20 C6 D2    JSR   $D2C6
184B-   CF          ???
184C-   CD 20 CF    CMP   $CF20
184F-   CE C5 20    DEC   $20C5
1852-   CC CF C3    CPY   $C3CF
1855-   C1 D4       CMP   ($D4,X)
1857-   C9 CF       CMP   #$CF
1859-   CE A2 AC    DEC   $ACA2
185C-   B8          CLV
185D-   C4 8D       CPY   $8D
185F-   A0 DF       LDY   #$DF
1861-   D0 D2       BNE   $1835
1863-   CE D4 A0    DEC   $A0D4
1866-   A2 D4       LDX   #$D4
1868-   CF          ???
1869-   20 C1 CE    JSR   $CEC1
186C-   CF          ???
186D-   D4          ???
186E-   C8          INY
186F-   C5 D2       CMP   $D2
1871-   AE 20 D3    LDX   $D320
1874-   CF          ???
1875-   AC 20 C2    LDY   $C220
1878-   C5 C6       CMP   $C6
187A-   CF          ???
187B-   D2 C5       CMP   ($C5)
187D-   20 D3 D7    JSR   $D7D3
1880-   C1 D0       CMP   ($D0,X)
1882-   BA          TSX
1883-   A2 AC       LDX   #$AC
1885-   B8          CLV
1886-   C4 B8       CPY   $B8
1888-   C4 8D       CPY   $8D
188A-   A0 DF       LDY   #$DF
188C-   C4 D5       CPY   $D5
188E-   CD D0 A0    CMP   $A0D0
1891-   A4 B3       LDY   $B3
1893-   B0 B0       BCS   $1845
1895-   BB          ???
1896-   A3          ???
1897-   B1 B0       LDA   ($B0),Y
1899-   8D A0 DF    STA   $DFA0
189C-   C4 D5       CPY   $D5
189E-   CD D0 A0    CMP   $A0D0
18A1-   A4 B3       LDY   $B3
18A3-   B2 B0       LDA   ($B0)
18A5-   BB          ???
18A6-   A3          ???
18A7-   B1 B0       LDA   ($B0),Y
18A9-   8D A0 CD    STA   $CDA0
18AC-   D3          ???
18AD-   D7          ???
18AE-   C1 D0       CMP   ($D0,X)
18B0-   A0 A4       LDY   #$A4
18B2-   B3          ???
18B3-   B0 B0       BCS   $1865
18B5-   BB          ???
18B6-   A4 B3       LDY   $B3
18B8-   B2 B0       LDA   ($B0)
18BA-   BB          ???
18BB-   A3          ???
18BC-   B1 B0       LDA   ($B0),Y
18BE-   8D A0 DF    STA   $DFA0
18C1-   D0 D2       BNE   $1895
18C3-   CE D4 A0    DEC   $A0D4
18C6-   A2 20       LDX   #$20
18C8-   A2 AC       LDX   #$AC
18CA-   B8          CLV
18CB-   C4 8D       CPY   $8D
18CD-   A0 DF       LDY   #$DF
18CF-   D0 D2       BNE   $18A3
18D1-   CE D4 A0    DEC   $A0D4
18D4-   A2 C1       LDX   #$C1
18D6-   CE C4 20    DEC   $20C4
18D9-   C1 C6       CMP   ($C6,X)
18DB-   D4          ???
18DC-   C5 D2       CMP   $D2
18DE-   20 D3 D7    JSR   $D7D3
18E1-   C1 D0       CMP   ($D0,X)
18E3-   BA          TSX
18E4-   20 A2 AC    JSR   $ACA2
18E7-   B8          CLV
18E8-   C4 B8       CPY   $B8
18EA-   C4 8D       CPY   $8D
18EC-   A0 DF       LDY   #$DF
18EE-   C4 D5       CPY   $D5
18F0-   CD D0 A0    CMP   $A0D0
18F3-   A4 B3       LDY   $B3
18F5-   B0 B0       BCS   $18A7
18F7-   BB          ???
18F8-   A3          ???
18F9-   B1 B0       LDA   ($B0),Y
18FB-   8D A0 DF    STA   $DFA0
18FE-   C4 D5       CPY   $D5
1900-   CD D0 A0    CMP   $A0D0
1903-   A4 B3       LDY   $B3
1905-   B2 B0       LDA   ($B0)
1907-   BB          ???
1908-   A3          ???
1909-   B1 B0       LDA   ($B0),Y
190B-   8D AA 8D    STA   $8DAA
190E-   AA          TAX
190F-   AA          TAX
1910-   20 D4 C8    JSR   $C8D4
1913-   C5 20       CMP   $20
1915-   C6 CF       DEC   $CF
1917-   CC CC CF    CPY   $CFCC
191A-   D7          ???
191B-   C9 CE       CMP   #$CE
191D-   C7          ???
191E-   20 C9 CC    JSR   $CCC9
1921-   CC D5 D3    CPY   $D3D5
1924-   D4          ???
1925-   D2 C1       CMP   ($C1)
1927-   D4          ???
1928-   C5 D3       CMP   $D3
192A-   20 D4 C8    JSR   $C8D4
192D-   C5 20       CMP   $20
192F-   DF          ???
1930-   D2 C4       CMP   ($C4)
1932-   D5 CD       CMP   $CD,X
1934-   D0 20       BNE   $1956
1936-   CD C1 C3    CMP   $C3C1
1939-   D2 CF       CMP   ($CF)
193B-   20 C9 CE    JSR   $CEC9
193E-   8D AA AA    STA   $AAAA
1941-   20 D4 C8    JSR   $C8D4
1944-   C5 20       CMP   $20
1946-   D2 C5       CMP   ($C5)
1948-   D1 D5       CMP   ($D5),Y
194A-   C9 D2       CMP   #$D2
194C-   C5 C4       CMP   $C4
194E-   20 CC C9    JSR   $C9CC
1951-   C2          ???
1952-   D2 C1       CMP   ($C1)
1954-   D2 D9       CMP   ($D9)
1956-   AE 8D AA    LDX   $AA8D
1959-   8D A0 CC    STA   $CCA0
195C-   C4 C1       CPY   $C1
195E-   A0 A3       LDY   #$A3
1960-   A4 B1       LDY   $B1
1962-   B1 8D       LDA   ($8D),Y
1964-   A0 CC       LDY   #$CC
1966-   C4 D8       CPY   $D8
1968-   A0 A3       LDY   #$A3
196A-   A4 B1       LDY   $B1
196C-   B2 8D       LDA   ($8D)
196E-   A0 CC       LDY   #$CC
1970-   C4 D9       CPY   $D9
1972-   A0 A3       LDY   #$A3
1974-   A4 B1       LDY   $B1
1976-   B3          ???
1977-   8D A0 C3    STA   $C3A0
197A-   CC C3 8D    CPY   $8DC3
197D-   A0 DF       LDY   #$DF
197F-   D2 C4       CMP   ($C4)
1981-   D5 CD       CMP   $CD,X
1983-   D0 8D       BNE   $1912
1985-   AA          TAX
1986-   8D A0 CA    STA   $CAA0
1989-   CD D0 A0    CMP   $A0D0
198C-   D2 C5       CMP   ($C5)
198E-   C5 CE       CMP   $CE
1990-   D4          ???
1991-   D2 D9       CMP   ($D9)
1993-   8D AA 8D    STA   $8DAA
1996-   AA          TAX
1997-   E0 E0       CPX   #$E0
1999-   E0 E0       CPX   #$E0
199B-   E0 E0       CPX   #$E0
199D-   E0 E0       CPX   #$E0
199F-   E0 E0       CPX   #$E0
19A1-   E0 E0       CPX   #$E0
19A3-   E0 E0       CPX   #$E0
19A5-   E0 E0       CPX   #$E0
19A7-   E0 E0       CPX   #$E0
19A9-   E0 E0       CPX   #$E0
19AB-   E0 E0       CPX   #$E0
19AD-   E0 E0       CPX   #$E0
19AF-   E0 E0       CPX   #$E0
19B1-   E0 E0       CPX   #$E0
19B3-   E0 E0       CPX   #$E0
19B5-   AA          TAX
19B6-   8D AA 20    STA   $20AA
19B9-   20 20 20    JSR   $2020
19BC-   20 20 20    JSR   $2020
19BF-   20 C2 CF    JSR   $CFC2
19C2-   D4          ???
19C3-   D4          ???
19C4-   CF          ???
19C5-   CD 20 C9    CMP   $C920
19C8-   CE C3 CC    DEC   $CCC3
19CB-   D5 C4       CMP   $C4,X
19CD-   C5 D3       CMP   $D3
19CF-   20 20 20    JSR   $2020
19D2-   20 20 20    JSR   $2020
19D5-   20 AA 8D    JSR   $8DAA
19D8-   AA          TAX
19D9-   AC AC AC    LDY   $ACAC
19DC-   AC AC AC    LDY   $ACAC
19DF-   AC AC AC    LDY   $ACAC
19E2-   AC AC AC    LDY   $ACAC
19E5-   AC AC AC    LDY   $ACAC
19E8-   AC AC AC    LDY   $ACAC
19EB-   AC AC AC    LDY   $ACAC
19EE-   AC AC AC    LDY   $ACAC
19F1-   AC AC AC    LDY   $ACAC
19F4-   AC AC AC    LDY   $ACAC
19F7-   AA          TAX
19F8-   8D AA 8D    STA   $8DAA
19FB-   AA          TAX
19FC-   AA          TAX
19FD-   20 C2 CF    JSR   $CFC2
1A00-   D4          ???
1A01-   D4          ???
1A02-   CF          ???
1A03-   CD 20 C9    CMP   $C920
1A06-   CE C3 CC    DEC   $CCC3
1A09-   D5 C4       CMP   $C4,X
1A0B-   C5 D3       CMP   $D3
1A0D-   8D AA 8D    STA   $8DAA
1A10-   A0 D0       LDY   #$D0
1A12-   D5 D4       CMP   $D4,X
1A14-   A0 C3       LDY   #$C3
1A16-   CF          ???
1A17-   CD CD CF    CMP   $CFCD
1A1A-   CE AE CC    DEC   $CCAE
1A1D-   C9 C2       CMP   #$C2
1A1F-   8D A0 D0    STA   $D0A0
1A22-   D5 D4       CMP   $D4,X
1A24-   A0 D2       LDY   #$D2
1A26-   C5 D1       CMP   $D1
1A28-   D5 C9       CMP   $C9,X
1A2A-   D2 C5       CMP   ($C5)
1A2C-   C4 AE       CPY   $AE
1A2E-   CC C9 C2    CPY   $C2C9
1A31-   AE CD C9    LDX   $C9CD
1A34-   CE 8D AA    DEC   $AA8D
1A37-   8D 00 00    STA   $0000
