0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 D3    LDY   $D320,X
0950-   D4          ???
0951-   D2 C9       CMP   ($C9)
0953-   CE C7 D3    DEC   $D3C7
0956-   20 C4 C5    JSR   $C5C4
0959-   CD CF 20    CMP   $20CF
095C-   BE AD 20    LDX   $20AD,Y
095F-   20 20 20    JSR   $2020
0962-   20 20 AA    JSR   $AA20
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B2       BCS   $094E
099C-   AE B0 B0    LDX   $B0B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B2    JSR   $B220
09D4-   B1 AD       LDA   ($AD),Y
09D6-   C4 C5       CPY   $C5
09D8-   C3          ???
09D9-   AD B2 B0    LDA   $B0B2
09DC-   B1 B8       LDA   ($B8),Y
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 C4    STA   $C4A0
0B02-   D3          ???
0B03-   CB          ???
0B04-   A0 D3       LDY   #$D3
0B06-   D4          ???
0B07-   D2 C9       CMP   ($C9)
0B09-   CE C7 D3    DEC   $D3C7
0B0C-   AE C4 C5    LDX   $C5C4
0B0F-   CD CF 8D    CMP   $8DCF
0B12-   AA          TAX
0B13-   8D A0 CF    STA   $CFA0
0B16-   C2          ???
0B17-   CA          DEX
0B18-   A0 A4       LDY   #$A4
0B1A-   C2          ???
0B1B-   C6 C5       DEC   $C5
0B1D-   B0 8D       BCS   $0AAC
0B1F-   A0 CF       LDY   #$CF
0B21-   D2 C7       CMP   ($C7)
0B23-   A0 A4       LDY   #$A4
0B25-   B6 B0       LDX   $B0,Y
0B27-   B0 B0       BCS   $0AD9
0B29-   8D AA 8D    STA   $8DAA
0B2C-   AA          TAX
0B2D-   E0 E0       CPX   #$E0
0B2F-   E0 E0       CPX   #$E0
0B31-   E0 E0       CPX   #$E0
0B33-   E0 E0       CPX   #$E0
0B35-   E0 E0       CPX   #$E0
0B37-   E0 E0       CPX   #$E0
0B39-   E0 E0       CPX   #$E0
0B3B-   E0 E0       CPX   #$E0
0B3D-   E0 E0       CPX   #$E0
0B3F-   E0 E0       CPX   #$E0
0B41-   E0 E0       CPX   #$E0
0B43-   E0 E0       CPX   #$E0
0B45-   E0 E0       CPX   #$E0
0B47-   E0 E0       CPX   #$E0
0B49-   E0 E0       CPX   #$E0
0B4B-   AA          TAX
0B4C-   8D AA 20    STA   $20AA
0B4F-   20 D4 CF    JSR   $CFD4
0B52-   D0 20       BNE   $0B74
0B54-   C9 CE       CMP   #$CE
0B56-   C3          ???
0B57-   CC D5 C4    CPY   $C4D5
0B5A-   C5 D3       CMP   $D3
0B5C-   20 A8 D0    JSR   $D0A8
0B5F-   D5 D4       CMP   $D4,X
0B61-   D3          ???
0B62-   AC 20 CD    LDY   $CD20
0B65-   C1 C3       CMP   ($C3,X)
0B67-   D2 CF       CMP   ($CF)
0B69-   D3          ???
0B6A-   A9 20       LDA   #$20
0B6C-   AA          TAX
0B6D-   8D AA AC    STA   $ACAA
0B70-   AC AC AC    LDY   $ACAC
0B73-   AC AC AC    LDY   $ACAC
0B76-   AC AC AC    LDY   $ACAC
0B79-   AC AC AC    LDY   $ACAC
0B7C-   AC AC AC    LDY   $ACAC
0B7F-   AC AC AC    LDY   $ACAC
0B82-   AC AC AC    LDY   $ACAC
0B85-   AC AC AC    LDY   $ACAC
0B88-   AC AC AC    LDY   $ACAC
0B8B-   AC AC AA    LDY   $AAAC
0B8E-   8D AA 8D    STA   $8DAA
0B91-   A0 D5       LDY   #$D5
0B93-   D3          ???
0B94-   C5 A0       CMP   $A0
0B96-   D2 C5       CMP   ($C5)
0B98-   D1 D5       CMP   ($D5),Y
0B9A-   C9 D2       CMP   #$D2
0B9C-   C5 C4       CMP   $C4
0B9E-   AE CD C1    LDX   $C1CD
0BA1-   C3          ???
0BA2-   8D A0 D0    STA   $D0A0
0BA5-   D5 D4       CMP   $D4,X
0BA7-   A0 D2       LDY   #$D2
0BA9-   C5 D1       CMP   $D1
0BAB-   D5 C9       CMP   $C9,X
0BAD-   D2 C5       CMP   ($C5)
0BAF-   C4 AE       CPY   $AE
0BB1-   C8          INY
0BB2-   CF          ???
0BB3-   CF          ???
0BB4-   CB          ???
0BB5-   D3          ???
0BB6-   8D AA 8D    STA   $8DAA
0BB9-   A0 D5       LDY   #$D5
0BBB-   D3          ???
0BBC-   C5 A0       CMP   $A0
0BBE-   D3          ???
0BBF-   D4          ???
0BC0-   D2 C9       CMP   ($C9)
0BC2-   CE C7 D3    DEC   $D3C7
0BC5-   AE CD C1    LDX   $C1CD
0BC8-   C3          ???
0BC9-   8D A0 D0    STA   $D0A0
0BCC-   D5 D4       CMP   $D4,X
0BCE-   A0 D3       LDY   #$D3
0BD0-   D4          ???
0BD1-   D2 C9       CMP   ($C9)
0BD3-   CE C7 D3    DEC   $D3C7
0BD6-   AE C8 CF    LDX   $CFC8
0BD9-   CF          ???
0BDA-   CB          ???
0BDB-   D3          ???
0BDC-   8D AA 8D    STA   $8DAA
0BDF-   AA          TAX
0BE0-   8D AA E0    STA   $E0AA
0BE3-   E0 E0       CPX   #$E0
0BE5-   E0 E0       CPX   #$E0
0BE7-   E0 E0       CPX   #$E0
0BE9-   E0 E0       CPX   #$E0
0BEB-   E0 E0       CPX   #$E0
0BED-   E0 E0       CPX   #$E0
0BEF-   E0 E0       CPX   #$E0
0BF1-   E0 E0       CPX   #$E0
0BF3-   E0 E0       CPX   #$E0
0BF5-   E0 E0       CPX   #$E0
0BF7-   E0 E0       CPX   #$E0
0BF9-   E0 E0       CPX   #$E0
0BFB-   E0 E0       CPX   #$E0
0BFD-   E0 E0       CPX   #$E0
0BFF-   E0 AA       CPX   #$AA
0C01-   8D AA 20    STA   $20AA
0C04-   20 20 20    JSR   $2020
0C07-   20 20 D0    JSR   $D020
0C0A-   D2 CF       CMP   ($CF)
0C0C-   C7          ???
0C0D-   D2 C1       CMP   ($C1)
0C0F-   CD 20 CD    CMP   $CD20
0C12-   C1 C9       CMP   ($C9,X)
0C14-   CE 20 C2    DEC   $C220
0C17-   CF          ???
0C18-   C4 D9       CPY   $D9
0C1A-   20 20 20    JSR   $2020
0C1D-   20 20 20    JSR   $2020
0C20-   20 AA 8D    JSR   $8DAA
0C23-   AA          TAX
0C24-   AC AC AC    LDY   $ACAC
0C27-   AC AC AC    LDY   $ACAC
0C2A-   AC AC AC    LDY   $ACAC
0C2D-   AC AC AC    LDY   $ACAC
0C30-   AC AC AC    LDY   $ACAC
0C33-   AC AC AC    LDY   $ACAC
0C36-   AC AC AC    LDY   $ACAC
0C39-   AC AC AC    LDY   $ACAC
0C3C-   AC AC AC    LDY   $ACAC
0C3F-   AC AC AC    LDY   $ACAC
0C42-   AA          TAX
0C43-   8D AA 8D    STA   $8DAA
0C46-   A0 DF       LDY   #$DF
0C48-   D0 D2       BNE   $0C1C
0C4A-   CE D4 A0    DEC   $A0D4
0C4D-   A2 20       LDX   #$20
0C4F-   A2 AC       LDX   #$AC
0C51-   B8          CLV
0C52-   C4 B8       CPY   $B8
0C54-   C4 B8       CPY   $B8
0C56-   C4 B8       CPY   $B8
0C58-   C4 8D       CPY   $8D
0C5A-   A0 DF       LDY   #$DF
0C5C-   D0 D2       BNE   $0C30
0C5E-   CE D4 A0    DEC   $A0D4
0C61-   A2 D3       LDX   #$D3
0C63-   D4          ???
0C64-   D2 C9       CMP   ($C9)
0C66-   CE C7 D3    DEC   $D3C7
0C69-   20 CC C9    JSR   $C9CC
0C6C-   C2          ???
0C6D-   D2 C1       CMP   ($C1)
0C6F-   D2 D9       CMP   ($D9)
0C71-   20 C4 C5    JSR   $C5C4
0C74-   CD CF A2    CMP   $A2CF
0C77-   AC B8 C4    LDY   $C4B8
0C7A-   8D A0 DF    STA   $DFA0
0C7D-   D0 D2       BNE   $0C51
0C7F-   CE D4 A0    DEC   $A0D4
0C82-   A2 AD       LDX   #$AD
0C84-   AD AD AD    LDA   $ADAD
0C87-   AD AD AD    LDA   $ADAD
0C8A-   AD AD AD    LDA   $ADAD
0C8D-   AD AD AD    LDA   $ADAD
0C90-   AD AD AD    LDA   $ADAD
0C93-   AD AD AD    LDA   $ADAD
0C96-   AD A2 AC    LDA   $ACA2
0C99-   B8          CLV
0C9A-   C4 8D       CPY   $8D
0C9C-   A0 DF       LDY   #$DF
0C9E-   D0 D2       BNE   $0C72
0CA0-   CE D4 A0    DEC   $A0D4
0CA3-   A2 20       LDX   #$20
0CA5-   A2 AC       LDX   #$AC
0CA7-   B8          CLV
0CA8-   C4 8D       CPY   $8D
0CAA-   A0 DF       LDY   #$DF
0CAC-   D0 D2       BNE   $0C80
0CAE-   CE D4 A0    DEC   $A0D4
0CB1-   A2 D4       LDX   #$D4
0CB3-   C8          INY
0CB4-   C5 20       CMP   $20
0CB6-   D3          ???
0CB7-   C3          ???
0CB8-   CD D0 20    CMP   $20D0
0CBB-   CD C1 C3    CMP   $C3C1
0CBE-   D2 CF       CMP   ($CF)
0CC0-   20 C3 CF    JSR   $CFC3
0CC3-   CD D0 C1    CMP   $C1D0
0CC6-   D2 C5       CMP   ($C5)
0CC8-   D3          ???
0CC9-   20 D4 D7    JSR   $D7D4
0CCC-   CF          ???
0CCD-   20 A2 AC    JSR   $ACA2
0CD0-   B8          CLV
0CD1-   C4 8D       CPY   $8D
0CD3-   A0 DF       LDY   #$DF
0CD5-   D0 D2       BNE   $0CA9
0CD7-   CE D4 A0    DEC   $A0D4
0CDA-   A2 D3       LDX   #$D3
0CDC-   D4          ???
0CDD-   D2 C9       CMP   ($C9)
0CDF-   CE C7 D3    DEC   $D3C7
0CE2-   20 C1 CE    JSR   $CEC1
0CE5-   C4 20       CPY   $20
0CE7-   D3          ???
0CE8-   C5 D4       CMP   $D4
0CEA-   D3          ???
0CEB-   20 D4 C8    JSR   $C8D4
0CEE-   C5 20       CMP   $20
0CF0-   C6 CC       DEC   $CC
0CF2-   C1 C7       CMP   ($C7,X)
0CF4-   D3          ???
0CF5-   A2 AC       LDX   #$AC
0CF7-   B8          CLV
0CF8-   C4 8D       CPY   $8D
0CFA-   A0 DF       LDY   #$DF
0CFC-   D0 D2       BNE   $0CD0
0CFE-   CE D4 A0    DEC   $A0D4
0D01-   A2 C1       LDX   #$C1
0D03-   C3          ???
0D04-   C3          ???
0D05-   CF          ???
0D06-   D2 C4       CMP   ($C4)
0D08-   C9 CE       CMP   #$CE
0D0A-   C7          ???
0D0B-   CC D9 AE    CPY   $AED9
0D0E-   20 C9 C6    JSR   $C6C9
0D11-   20 D4 C8    JSR   $C8D4
0D14-   C5 20       CMP   $20
0D16-   D4          ???
0D17-   D7          ???
0D18-   CF          ???
0D19-   20 C1 D2    JSR   $D2C1
0D1C-   C5 20       CMP   $20
0D1E-   C5 D1       CMP   $D1
0D20-   D5 C1       CMP   $C1,X
0D22-   CC AC A2    CPY   $A2AC
0D25-   AC B8 C4    LDY   $C4B8
0D28-   8D A0 DF    STA   $DFA0
0D2B-   D0 D2       BNE   $0CFF
0D2D-   CE D4 A0    DEC   $A0D4
0D30-   A2 D4       LDX   #$D4
0D32-   C8          INY
0D33-   C5 CE       CMP   $CE
0D35-   20 AE DA    JSR   $DAAE
0D38-   20 C9 D3    JSR   $D3C9
0D3B-   20 D3 C5    JSR   $C5D3
0D3E-   D4          ???
0D3F-   20 D4 CF    JSR   $CFD4
0D42-   20 DA C5    JSR   $C5DA
0D45-   D2 CF       CMP   ($CF)
0D47-   BB          ???
0D48-   20 C9 C6    JSR   $C6C9
0D4B-   20 CE CF    JSR   $CFCE
0D4E-   D4          ???
0D4F-   AC 20 B1    LDY   $B120
0D52-   AE A2 AC    LDX   $ACA2
0D55-   B8          CLV
0D56-   C4 B8       CPY   $B8
0D58-   C4 8D       CPY   $8D
0D5A-   A0 DF       LDY   #$DF
0D5C-   D0 D2       BNE   $0D30
0D5E-   CE D4 A0    DEC   $A0D4
0D61-   A2 C9       LDX   #$C9
0D63-   C6 20       DEC   $20
0D65-   D3          ???
0D66-   D4          ???
0D67-   D2 C9       CMP   ($C9)
0D69-   CE C7 B1    DEC   $B1C7
0D6C-   20 CC C5    JSR   $C5CC
0D6F-   CE C7 D4    DEC   $D4C7
0D72-   C8          INY
0D73-   20 BE 20    JSR   $20BE
0D76-   D3          ???
0D77-   D4          ???
0D78-   D2 C9       CMP   ($C9)
0D7A-   CE C7 B2    DEC   $B2C7
0D7D-   20 CC C5    JSR   $C5CC
0D80-   CE C7 D4    DEC   $D4C7
0D83-   C8          INY
0D84-   AC A2 AC    LDY   $ACA2
0D87-   B8          CLV
0D88-   C4 8D       CPY   $8D
0D8A-   A0 DF       LDY   #$DF
0D8C-   D0 D2       BNE   $0D60
0D8E-   CE D4 A0    DEC   $A0D4
0D91-   A2 AE       LDX   #$AE
0D93-   C3          ???
0D94-   A8          TAY
0D95-   C1 D2       CMP   ($D2,X)
0D97-   D2 D9       CMP   ($D9)
0D99-   A9 20       LDA   #$20
0D9B-   BD 20 B0    LDA   $B020,X
0D9E-   BB          ???
0D9F-   20 C5 CC    JSR   $CCC5
0DA2-   D3          ???
0DA3-   C5 AC       CMP   $AC
0DA5-   20 AE C3    JSR   $C3AE
0DA8-   20 BD 20    JSR   $20BD
0DAB-   B1 AE       LDA   ($AE),Y
0DAD-   A2 AC       LDX   #$AC
0DAF-   B8          CLV
0DB0-   C4 B8       CPY   $B8
0DB2-   C4 8D       CPY   $8D
0DB4-   A0 DF       LDY   #$DF
0DB6-   D0 D2       BNE   $0D8A
0DB8-   CE D4 A0    DEC   $A0D4
0DBB-   A2 D3       LDX   #$D3
0DBD-   CF          ???
0DBE-   AC 20 D7    LDY   $D720
0DC1-   C5 20       CMP   $20
0DC3-   C3          ???
0DC4-   C1 CE       CMP   ($CE,X)
0DC6-   20 C3 CF    JSR   $CFC3
0DC9-   CD D0 C1    CMP   $C1D0
0DCC-   D2 C5       CMP   ($C5)
0DCE-   20 D4 C8    JSR   $C8D4
0DD1-   C5 20       CMP   $20
0DD3-   CC C9 D4    CPY   $D4C9
0DD6-   C5 D2       CMP   $D2
0DD8-   C1 CC       CMP   ($CC,X)
0DDA-   20 A7 C1    JSR   $C1A7
0DDD-   A7          ???
0DDE-   A2 AC       LDX   #$AC
0DE0-   B8          CLV
0DE1-   C4 8D       CPY   $8D
0DE3-   A0 DF       LDY   #$DF
0DE5-   D0 D2       BNE   $0DB9
0DE7-   CE D4 A0    DEC   $A0D4
0DEA-   A2 D4       LDX   #$D4
0DEC-   CF          ???
0DED-   20 D4 C8    JSR   $C8D4
0DF0-   C5 20       CMP   $20
0DF2-   D6 C1       DEC   $C1,X
0DF4-   CC D5 C5    CPY   $C5D5
0DF7-   20 D3 D4    JSR   $D4D3
0DFA-   CF          ???
0DFB-   D2 C5       CMP   ($C5)
0DFD-   C4 20       CPY   $20
0DFF-   C9 CE       CMP   #$CE
0E01-   20 C1 D3    JSR   $D3C1
0E04-   D4          ???
0E05-   D2 AC       CMP   ($AC)
0E07-   20 D7 C8    JSR   $C8D7
0E0A-   C9 C3       CMP   #$C3
0E0C-   C8          INY
0E0D-   A2 AC       LDX   #$AC
0E0F-   B8          CLV
0E10-   C4 8D       CPY   $8D
0E12-   A0 DF       LDY   #$DF
0E14-   D0 D2       BNE   $0DE8
0E16-   CE D4 A0    DEC   $A0D4
0E19-   A2 C8       LDX   #$C8
0E1B-   CF          ???
0E1C-   CC C4 D3    CPY   $D3C4
0E1F-   20 D4 C8    JSR   $C8D4
0E22-   C5 20       CMP   $20
0E24-   D3          ???
0E25-   C1 CD       CMP   ($CD,X)
0E27-   C5 20       CMP   $20
0E29-   D3          ???
0E2A-   D4          ???
0E2B-   D2 C9       CMP   ($C9)
0E2D-   CE C7 AC    DEC   $ACC7
0E30-   20 D4 C8    JSR   $C8D4
0E33-   C5 CE       CMP   $CE
0E35-   20 D5 D3    JSR   $D3D5
0E38-   C5 20       CMP   $20
0E3A-   C2          ???
0E3B-   CE C5 20    DEC   $20C5
0E3E-   D4          ???
0E3F-   CF          ???
0E40-   A2 AC       LDX   #$AC
0E42-   B8          CLV
0E43-   C4 8D       CPY   $8D
0E45-   A0 DF       LDY   #$DF
0E47-   D0 D2       BNE   $0E1B
0E49-   CE D4 A0    DEC   $A0D4
0E4C-   A2 D4       LDX   #$D4
0E4E-   C5 D3       CMP   $D3
0E50-   D4          ???
0E51-   20 C9 C6    JSR   $C6C9
0E54-   20 D4 C8    JSR   $C8D4
0E57-   C5 D9       CMP   $D9
0E59-   20 C1 D2    JSR   $D2C1
0E5C-   C5 20       CMP   $20
0E5E-   C5 D1       CMP   $D1
0E60-   D5 C1       CMP   $C1,X
0E62-   CC AE A2    CPY   $A2AE
0E65-   AC B8 C4    LDY   $C4B8
0E68-   B8          CLV
0E69-   C4 8D       CPY   $8D
0E6B-   A0 D3       LDY   #$D3
0E6D-   C3          ???
0E6E-   CD D0 A0    CMP   $A0D0
0E71-   A2 C1       LDX   #$C1
0E73-   A2 BB       LDX   #$BB
0E75-   C1 D3       CMP   ($D3,X)
0E77-   D4          ???
0E78-   D2 8D       CMP   ($8D)
0E7A-   A0 C2       LDY   #$C2
0E7C-   CE C5 A0    DEC   $A0C5
0E7F-   D0 C5       BNE   $0E46
0E81-   A0 BB       LDY   #$BB
0E83-   20 C9 D3    JSR   $D3C9
0E86-   20 DA C5    JSR   $C5DA
0E89-   D2 CF       CMP   ($CF)
0E8B-   20 C6 CC    JSR   $CCC6
0E8E-   C1 C7       CMP   ($C7,X)
0E90-   20 B1 BF    JSR   $BFB1
0E93-   20 C2 D2    JSR   $D2C2
0E96-   C1 CE       CMP   ($CE,X)
0E98-   C3          ???
0E99-   C8          INY
0E9A-   20 C9 C6    JSR   $C6C9
0E9D-   20 D3 CF    JSR   $CFD3
0EA0-   8D A0 CA    STA   $CAA0
0EA3-   CD D0 A0    CMP   $A0D0
0EA6-   C3          ???
0EA7-   CF          ???
0EA8-   CE D4 8D    DEC   $8DD4
0EAB-   D0 C5       BNE   $0E72
0EAD-   8D A0 DF    STA   $DFA0
0EB0-   D0 D2       BNE   $0E84
0EB2-   CE D4 A0    DEC   $A0D4
0EB5-   A2 D4       LDX   #$D4
0EB7-   C8          INY
0EB8-   C5 20       CMP   $20
0EBA-   CC C9 D4    CPY   $D4C9
0EBD-   C5 D2       CMP   $D2
0EBF-   C1 CC       CMP   ($CC,X)
0EC1-   20 C1 20    JSR   $20C1
0EC4-   C1 CE       CMP   ($CE,X)
0EC6-   C4 20       CPY   $20
0EC8-   D4          ???
0EC9-   C8          INY
0ECA-   C5 20       CMP   $20
0ECC-   C1 20       CMP   ($20,X)
0ECE-   D3          ???
0ECF-   D4          ???
0ED0-   D2 C9       CMP   ($C9)
0ED2-   CE C7 20    DEC   $20C7
0ED5-   C1 D2       CMP   ($D2,X)
0ED7-   C5 A2       CMP   $A2
0ED9-   AC B8 C4    LDY   $C4B8
0EDC-   8D A0 DF    STA   $DFA0
0EDF-   D0 D2       BNE   $0EB3
0EE1-   CE D4 A0    DEC   $A0D4
0EE4-   A2 C5       LDX   #$C5
0EE6-   D1 D5       CMP   ($D5),Y
0EE8-   C1 CC       CMP   ($CC,X)
0EEA-   AE A2 AC    LDX   $ACA2
0EED-   B8          CLV
0EEE-   C4 B8       CPY   $B8
0EF0-   C4 B8       CPY   $B8
0EF2-   C4 8D       CPY   $8D
0EF4-   C3          ???
0EF5-   CF          ???
0EF6-   CE D4 8D    DEC   $8DD4
0EF9-   A0 DF       LDY   #$DF
0EFB-   D7          ???
0EFC-   C1 C9       CMP   ($C9,X)
0EFE-   D4          ???
0EFF-   8D A0 DF    STA   $DFA0
0F02-   D0 D2       BNE   $0ED6
0F04-   CE D4 A0    DEC   $A0D4
0F07-   A2 CE       LDX   #$CE
0F09-   CF          ???
0F0A-   D4          ???
0F0B-   C5 20       CMP   $20
0F0D-   D4          ???
0F0E-   C8          INY
0F0F-   C1 D4       CMP   ($D4,X)
0F11-   20 CF CE    JSR   $CECF
0F14-   CC D9 20    CPY   $20D9
0F17-   C1 20       CMP   ($20,X)
0F19-   D3          ???
0F1A-   C9 CE       CMP   #$CE
0F1C-   C7          ???
0F1D-   CC C5 20    CPY   $20C5
0F20-   D0 C1       BNE   $0EE3
0F22-   D2 C1       CMP   ($C1)
0F24-   CD C5 D4    CMP   $D4C5
0F27-   C5 D2       CMP   $D2
0F29-   A2 AC       LDX   #$AC
0F2B-   B8          CLV
0F2C-   C4 8D       CPY   $8D
0F2E-   A0 DF       LDY   #$DF
0F30-   D0 D2       BNE   $0F04
0F32-   CE D4 A0    DEC   $A0D4
0F35-   A2 CD       LDX   #$CD
0F37-   C1 D9       CMP   ($D9,X)
0F39-   20 C2 C5    JSR   $C5C2
0F3C-   20 C1 20    JSR   $20C1
0F3F-   CC C9 D4    CPY   $D4C9
0F42-   C5 D2       CMP   $D2
0F44-   C1 CC       CMP   ($CC,X)
0F46-   20 D3 D4    JSR   $D4D3
0F49-   D2 C9       CMP   ($C9)
0F4B-   CE C7 20    DEC   $20C7
0F4E-   C9 CE       CMP   #$CE
0F50-   20 D3 C3    JSR   $C3D3
0F53-   CD D0 BB    CMP   $BBD0
0F56-   A2 AC       LDX   #$AC
0F58-   B8          CLV
0F59-   C4 8D       CPY   $8D
0F5B-   A0 DF       LDY   #$DF
0F5D-   D0 D2       BNE   $0F31
0F5F-   CE D4 A0    DEC   $A0D4
0F62-   A2 D4       LDX   #$D4
0F64-   C8          INY
0F65-   C9 D3       CMP   #$D3
0F67-   20 D3 C1    JSR   $C1D3
0F6A-   CD C5 20    CMP   $20C5
0F6D-   D2 D5       CMP   ($D5)
0F6F-   CC C5 20    CPY   $20C5
0F72-   C1 D0       CMP   ($D0,X)
0F74-   D0 CC       BNE   $0F42
0F76-   C9 C5       CMP   #$C5
0F78-   D3          ???
0F79-   20 D4 CF    JSR   $CFD4
0F7C-   20 C1 CC    JSR   $CCC1
0F7F-   CC 20 CD    CPY   $CD20
0F82-   C1 C3       CMP   ($C3,X)
0F84-   D2 CF       CMP   ($CF)
0F86-   D3          ???
0F87-   A2 AC       LDX   #$AC
0F89-   B8          CLV
0F8A-   C4 8D       CPY   $8D
0F8C-   A0 DF       LDY   #$DF
0F8E-   D0 D2       BNE   $0F62
0F90-   CE D4 A0    DEC   $A0D4
0F93-   A2 D4       LDX   #$D4
0F95-   C8          INY
0F96-   C1 D4       CMP   ($D4,X)
0F98-   20 C1 C3    JSR   $C3C1
0F9B-   C3          ???
0F9C-   C5 D0       CMP   $D0
0F9E-   D4          ???
0F9F-   20 D3 D4    JSR   $D4D3
0FA2-   D2 C9       CMP   ($C9)
0FA4-   CE C7 D3    DEC   $D3C7
0FA7-   20 C1 D3    JSR   $D3C1
0FAA-   20 D0 C1    JSR   $C1D0
0FAD-   D2 C1       CMP   ($C1)
0FAF-   CD C5 D4    CMP   $D4C5
0FB2-   C5 D2       CMP   $D2
0FB4-   D3          ???
0FB5-   AE A2 AC    LDX   $ACA2
0FB8-   B8          CLV
0FB9-   C4 B8       CPY   $B8
0FBB-   C4 8D       CPY   $8D
0FBD-   A0 DF       LDY   #$DF
0FBF-   D0 D2       BNE   $0F93
0FC1-   CE D4 A0    DEC   $A0D4
0FC4-   A2 D9       LDX   #$D9
0FC6-   CF          ???
0FC7-   D5 20       CMP   $20,X
0FC9-   C3          ???
0FCA-   C1 CE       CMP   ($CE,X)
0FCC-   20 C1 CC    JSR   $CCC1
0FCF-   D3          ???
0FD0-   CF          ???
0FD1-   20 D5 D3    JSR   $D3D5
0FD4-   C5 20       CMP   $20
0FD6-   D3          ???
0FD7-   C3          ???
0FD8-   CD D0 20    CMP   $20D0
0FDB-   D4          ???
0FDC-   CF          ???
0FDD-   20 C3 CF    JSR   $CFC3
0FE0-   CD D0 C1    CMP   $C1D0
0FE3-   D2 C5       CMP   ($C5)
0FE5-   A2 AC       LDX   #$AC
0FE7-   B8          CLV
0FE8-   C4 8D       CPY   $8D
0FEA-   A0 DF       LDY   #$DF
0FEC-   D0 D2       BNE   $0FC0
0FEE-   CE D4 A0    DEC   $A0D4
0FF1-   A2 D4       LDX   #$D4
0FF3-   C8          INY
0FF4-   C5 20       CMP   $20
0FF6-   CC C5 CE    CPY   $CEC5
0FF9-   C7          ???
0FFA-   D4          ???
0FFB-   C8          INY
0FFC-   D3          ???
0FFD-   20 CF C6    JSR   $C6CF
1000-   20 D4 D7    JSR   $D7D4
1003-   CF          ???
1004-   20 C4 C9    JSR   $C9C4
1007-   C6 C6       DEC   $C6
1009-   C5 D2       CMP   $D2
100B-   C5 CE       CMP   $CE
100D-   D4          ???
100E-   20 D3 D4    JSR   $D4D3
1011-   D2 C9       CMP   ($C9)
1013-   CE C7 D3    DEC   $D3C7
1016-   AE A2 AC    LDX   $ACA2
1019-   B8          CLV
101A-   C4 B8       CPY   $B8
101C-   C4 8D       CPY   $8D
101E-   A0 DF       LDY   #$DF
1020-   D0 D2       BNE   $0FF4
1022-   CE D4 A0    DEC   $A0D4
1025-   A2 D4       LDX   #$D4
1027-   C8          INY
1028-   C5 20       CMP   $20
102A-   C3          ???
102B-   C1 D2       CMP   ($D2,X)
102D-   D2 D9       CMP   ($D9)
102F-   20 C6 CC    JSR   $CCC6
1032-   C1 C7       CMP   ($C7,X)
1034-   20 C9 D3    JSR   $D3C9
1037-   20 D3 C5    JSR   $C5D3
103A-   D4          ???
103B-   20 D4 CF    JSR   $CFD4
103E-   20 B0 20    JSR   $20B0
1041-   C9 C6       CMP   #$C6
1043-   20 D4 C8    JSR   $C8D4
1046-   C5 A2       CMP   $A2
1048-   AC B8 C4    LDY   $C4B8
104B-   8D A0 DF    STA   $DFA0
104E-   D0 D2       BNE   $1022
1050-   CE D4 A0    DEC   $A0D4
1053-   A2 C6       LDX   #$C6
1055-   C9 D2       CMP   #$D2
1057-   D3          ???
1058-   D4          ???
1059-   20 D3 D4    JSR   $D4D3
105C-   D2 C9       CMP   ($C9)
105E-   CE C7 20    DEC   $20C7
1061-   C8          INY
1062-   C1 D3       CMP   ($D3,X)
1064-   20 C1 20    JSR   $20C1
1067-   CC C5 CE    CPY   $CEC5
106A-   C7          ???
106B-   D4          ???
106C-   C8          INY
106D-   20 BE 20    JSR   $20BE
1070-   D4          ???
1071-   C8          INY
1072-   C1 CE       CMP   ($CE,X)
1074-   20 D4 C8    JSR   $C8D4
1077-   C5 20       CMP   $20
1079-   A2 AC       LDX   #$AC
107B-   B8          CLV
107C-   C4 8D       CPY   $8D
107E-   A0 DF       LDY   #$DF
1080-   D0 D2       BNE   $1054
1082-   CE D4 A0    DEC   $A0D4
1085-   A2 D3       LDX   #$D3
1087-   C5 C3       CMP   $C3
1089-   CF          ???
108A-   CE C4 20    DEC   $20C4
108D-   D3          ???
108E-   D4          ???
108F-   D2 C9       CMP   ($C9)
1091-   CE C7 A7    DEC   $A7C7
1094-   D3          ???
1095-   20 CC C5    JSR   $C5CC
1098-   CE C7 D4    DEC   $D4C7
109B-   C8          INY
109C-   AE 20 D4    LDX   $D420
109F-   C8          INY
10A0-   C9 D3       CMP   #$D3
10A2-   20 C3 C1    JSR   $C1C3
10A5-   CE 20 D4    DEC   $D420
10A8-   C8          INY
10A9-   C5 CE       CMP   $CE
10AB-   A2 AC       LDX   #$AC
10AD-   B8          CLV
10AE-   C4 8D       CPY   $8D
10B0-   A0 DF       LDY   #$DF
10B2-   D0 D2       BNE   $1086
10B4-   CE D4 A0    DEC   $A0D4
10B7-   A2 C2       LDX   #$C2
10B9-   C5 20       CMP   $20
10BB-   D4          ???
10BC-   C5 D3       CMP   $D3
10BE-   D4          ???
10BF-   C5 C4       CMP   $C4
10C1-   20 D7 C9    JSR   $C9D7
10C4-   D4          ???
10C5-   C8          INY
10C6-   20 C2 C3    JSR   $C3C2
10C9-   D3          ???
10CA-   AE A2 AC    LDX   $ACA2
10CD-   B8          CLV
10CE-   C4 B8       CPY   $B8
10D0-   C4 8D       CPY   $8D
10D2-   A0 DF       LDY   #$DF
10D4-   D0 D2       BNE   $10A8
10D6-   CE D4 A0    DEC   $A0D4
10D9-   A2 D3       LDX   #$D3
10DB-   CF          ???
10DC-   20 C9 C6    JSR   $C6C9
10DF-   20 D7 C5    JSR   $C5D7
10E2-   20 C3 CF    JSR   $CFC3
10E5-   CD D0 C1    CMP   $C1D0
10E8-   D2 C5       CMP   ($C5)
10EA-   20 D4 C8    JSR   $C8D4
10ED-   C5 20       CMP   $20
10EF-   CC C9 D4    CPY   $D4C9
10F2-   C5 D2       CMP   $D2
10F4-   C1 CC       CMP   ($CC,X)
10F6-   20 A7 C1    JSR   $C1A7
10F9-   C1 A7       CMP   ($A7,X)
10FB-   20 A2 AC    JSR   $ACA2
10FE-   B8          CLV
10FF-   C4 8D       CPY   $8D
1101-   A0 DF       LDY   #$DF
1103-   D0 D2       BNE   $10D7
1105-   CE D4 A0    DEC   $A0D4
1108-   A2 D4       LDX   #$D4
110A-   CF          ???
110B-   20 D4 C8    JSR   $C8D4
110E-   C5 20       CMP   $20
1110-   D3          ???
1111-   C1 CD       CMP   ($CD,X)
1113-   C5 20       CMP   $20
1115-   C1 D3       CMP   ($D3,X)
1117-   D4          ???
1118-   D2 AC       CMP   ($AC)
111A-   20 D7 C5    JSR   $C5D7
111D-   20 D7 C9    JSR   $C9D7
1120-   CC CC 20    CPY   $20CC
1123-   C6 C9       DEC   $C9
1125-   CE C4 20    DEC   $20C4
1128-   D4          ???
1129-   C8          INY
112A-   C1 D4       CMP   ($D4,X)
112C-   A2 AC       LDX   #$AC
112E-   B8          CLV
112F-   C4 8D       CPY   $8D
1131-   A0 DF       LDY   #$DF
1133-   D0 D2       BNE   $1107
1135-   CE D4 A0    DEC   $A0D4
1138-   A2 D4       LDX   #$D4
113A-   C8          INY
113B-   C5 20       CMP   $20
113D-   CC C9 D4    CPY   $D4C9
1140-   C5 D2       CMP   $D2
1142-   C1 CC       CMP   ($CC,X)
1144-   20 C8 C1    JSR   $C1C8
1147-   D3          ???
1148-   20 C1 20    JSR   $20C1
114B-   C7          ???
114C-   D2 C5       CMP   ($C5)
114E-   C1 D4       CMP   ($D4,X)
1150-   C5 D2       CMP   $D2
1152-   20 CC C5    JSR   $C5CC
1155-   CE C7 D4    DEC   $D4C7
1158-   C8          INY
1159-   AE A2 AC    LDX   $ACA2
115C-   B8          CLV
115D-   C4 B8       CPY   $B8
115F-   C4 8D       CPY   $8D
1161-   AA          TAX
1162-   8D A0 D3    STA   $D3A0
1165-   C3          ???
1166-   CD D0 A0    CMP   $A0D0
1169-   A2 C1       LDX   #$C1
116B-   C1 A2       CMP   ($A2,X)
116D-   BB          ???
116E-   C1 D3       CMP   ($D3,X)
1170-   D4          ???
1171-   D2 8D       CMP   ($8D)
1173-   A0 C2       LDY   #$C2
1175-   C3          ???
1176-   D3          ???
1177-   A0 CC       LDY   #$CC
1179-   C5 8D       CMP   $8D
117B-   A0 CA       LDY   #$CA
117D-   CD D0 A0    CMP   $A0D0
1180-   C3          ???
1181-   CF          ???
1182-   CE D4 B2    DEC   $B2D4
1185-   8D CC C5    STA   $C5CC
1188-   8D A0 DF    STA   $DFA0
118B-   D0 D2       BNE   $115F
118D-   CE D4 A0    DEC   $A0D4
1190-   A2 D4       LDX   #$D4
1192-   C8          INY
1193-   C5 20       CMP   $20
1195-   CC C9 D4    CPY   $D4C9
1198-   C5 D2       CMP   $D2
119A-   C1 CC       CMP   ($CC,X)
119C-   20 A7 C1    JSR   $C1A7
119F-   C1 A7       CMP   ($A7,X)
11A1-   20 C9 D3    JSR   $D3C9
11A4-   20 C7 D2    JSR   $D2C7
11A7-   C5 C1       CMP   $C1
11A9-   D4          ???
11AA-   C5 D2       CMP   $D2
11AC-   20 D4 C8    JSR   $C8D4
11AF-   C1 CE       CMP   ($CE,X)
11B1-   20 A2 AC    JSR   $ACA2
11B4-   B8          CLV
11B5-   C4 8D       CPY   $8D
11B7-   A0 DF       LDY   #$DF
11B9-   D0 D2       BNE   $118D
11BB-   CE D4 A0    DEC   $A0D4
11BE-   A2 C1       LDX   #$C1
11C0-   D3          ???
11C1-   D4          ???
11C2-   D2 AC       CMP   ($AC)
11C4-   20 D7 C8    JSR   $C8D7
11C7-   C9 C3       CMP   #$C3
11C9-   C8          INY
11CA-   20 C8 CF    JSR   $CFC8
11CD-   CC C4 D3    CPY   $D3C4
11D0-   20 A7 C1    JSR   $C1A7
11D3-   A7          ???
11D4-   AE A2 AC    LDX   $ACA2
11D7-   B8          CLV
11D8-   C4 B8       CPY   $B8
11DA-   C4 B8       CPY   $B8
11DC-   C4 8D       CPY   $8D
11DE-   C3          ???
11DF-   CF          ???
11E0-   CE D4 B2    DEC   $B2D4
11E3-   8D A0 DF    STA   $DFA0
11E6-   D7          ???
11E7-   C1 C9       CMP   ($C9,X)
11E9-   D4          ???
11EA-   8D AA 8D    STA   $8DAA
11ED-   A0 DF       LDY   #$DF
11EF-   D0 D2       BNE   $11C3
11F1-   CE D4 A0    DEC   $A0D4
11F4-   A2 20       LDX   #$20
11F6-   A2 AC       LDX   #$AC
11F8-   B8          CLV
11F9-   C4 B8       CPY   $B8
11FB-   C4 B8       CPY   $B8
11FD-   C4 B8       CPY   $B8
11FF-   C4 8D       CPY   $8D
1201-   A0 DF       LDY   #$DF
1203-   D0 D2       BNE   $11D7
1205-   CE D4 A0    DEC   $A0D4
1208-   A2 D4       LDX   #$D4
120A-   C8          INY
120B-   C5 20       CMP   $20
120D-   D3          ???
120E-   C3          ???
120F-   C1 D4       CMP   ($D4,X)
1211-   20 CD C1    JSR   $C1CD
1214-   C3          ???
1215-   D2 CF       CMP   ($CF)
1217-   20 C3 CF    JSR   $CFC3
121A-   CE C3 C1    DEC   $C1C3
121D-   D4          ???
121E-   C5 CE       CMP   $CE
1220-   C1 D4       CMP   ($D4,X)
1222-   C5 D3       CMP   $D3
1224-   A2 AC       LDX   #$AC
1226-   B8          CLV
1227-   C4 8D       CPY   $8D
1229-   A0 DF       LDY   #$DF
122B-   D0 D2       BNE   $11FF
122D-   CE D4 A0    DEC   $A0D4
1230-   A2 C1       LDX   #$C1
1232-   20 D3 C5    JSR   $C5D3
1235-   C3          ???
1236-   CF          ???
1237-   CE C4 20    DEC   $20C4
123A-   C7          ???
123B-   C9 D6       CMP   #$D6
123D-   C5 CE       CMP   $CE
123F-   20 D3 D4    JSR   $D4D3
1242-   D2 C9       CMP   ($C9)
1244-   CE C7 20    DEC   $20C7
1247-   D4          ???
1248-   CF          ???
1249-   20 C1 20    JSR   $20C1
124C-   A2 AC       LDX   #$AC
124E-   B8          CLV
124F-   C4 8D       CPY   $8D
1251-   A0 DF       LDY   #$DF
1253-   D0 D2       BNE   $1227
1255-   CE D4 A0    DEC   $A0D4
1258-   A2 C6       LDX   #$C6
125A-   C9 D2       CMP   #$D2
125C-   D3          ???
125D-   D4          ???
125E-   20 C7 C9    JSR   $C9C7
1261-   D6 C5       DEC   $C5,X
1263-   CE 20 D3    DEC   $D320
1266-   D4          ???
1267-   D2 C9       CMP   ($C9)
1269-   CE C7 AE    DEC   $AEC7
126C-   20 C5 C9    JSR   $C9C5
126F-   D4          ???
1270-   C8          INY
1271-   C5 D2       CMP   $D2
1273-   20 D0 C1    JSR   $C1D0
1276-   D2 C1       CMP   ($C1)
1278-   CD C5 D4    CMP   $D4C5
127B-   C5 D2       CMP   $D2
127D-   A2 AC       LDX   #$AC
127F-   B8          CLV
1280-   C4 8D       CPY   $8D
1282-   A0 DF       LDY   #$DF
1284-   D0 D2       BNE   $1258
1286-   CE D4 A0    DEC   $A0D4
1289-   A2 CD       LDX   #$CD
128B-   C1 D9       CMP   ($D9,X)
128D-   20 C2 C5    JSR   $C5C2
1290-   20 C1 20    JSR   $20C1
1293-   CC C9 D4    CPY   $D4C9
1296-   C5 D2       CMP   $D2
1298-   C1 CC       CMP   ($CC,X)
129A-   20 D3 D4    JSR   $D4D3
129D-   D2 C9       CMP   ($C9)
129F-   CE C7 AC    DEC   $ACC7
12A2-   20 C2 D5    JSR   $D5C2
12A5-   D4          ???
12A6-   20 CE C5    JSR   $C5CE
12A9-   D6 C5       DEC   $C5,X
12AB-   D2 20       CMP   ($20)
12AD-   C2          ???
12AE-   CF          ???
12AF-   D4          ???
12B0-   C8          INY
12B1-   AE A2 AC    LDX   $ACA2
12B4-   B8          CLV
12B5-   C4 B8       CPY   $B8
12B7-   C4 8D       CPY   $8D
12B9-   A0 DF       LDY   #$DF
12BB-   D0 D2       BNE   $128F
12BD-   CE D4 A0    DEC   $A0D4
12C0-   A2 D3       LDX   #$D3
12C2-   C3          ???
12C3-   C1 D4       CMP   ($D4,X)
12C5-   20 A7 D7    JSR   $D7A7
12C8-   D4          ???
12C9-   C6 20       DEC   $20
12CB-   C9 D3       CMP   #$D3
12CD-   20 A7 BB    JSR   $BBA7
12D0-   C1 D3       CMP   ($D3,X)
12D2-   D4          ???
12D3-   D2 BB       CMP   ($BB)
12D5-   A3          ???
12D6-   B5 B0       LDA   $B0,X
12D8-   20 D2 C5    JSR   $C5D2
12DB-   D4          ???
12DC-   D5 D2       CMP   $D2,X
12DE-   CE D3 BA    DEC   $BAD3
12E1-   20 A2 AC    JSR   $ACA2
12E4-   B8          CLV
12E5-   C4 B8       CPY   $B8
12E7-   C4 8D       CPY   $8D
12E9-   A0 D3       LDY   #$D3
12EB-   C3          ???
12EC-   C1 D4       CMP   ($D4,X)
12EE-   A0 A2       LDY   #$A2
12F0-   D7          ???
12F1-   D4          ???
12F2-   C6 20       DEC   $20
12F4-   C9 D3       CMP   #$D3
12F6-   20 A2 BB    JSR   $BBA2
12F9-   C1 D3       CMP   ($D3,X)
12FB-   D4          ???
12FC-   D2 BB       CMP   ($BB)
12FE-   A3          ???
12FF-   B5 B0       LDA   $B0,X
1301-   8D A0 D3    STA   $D3A0
1304-   D0 D2       BNE   $12D8
1306-   CE A0 D2    DEC   $D2A0
1309-   C5 D4       CMP   $D4
130B-   D5 D2       CMP   $D2,X
130D-   CE 8D A0    DEC   $A08D
1310-   DF          ???
1311-   D0 D2       BNE   $12E5
1313-   CE D4 A0    DEC   $A0D4
1316-   A2 20       LDX   #$20
1318-   A2 AC       LDX   #$AC
131A-   B8          CLV
131B-   C4 B8       CPY   $B8
131D-   C4 B8       CPY   $B8
131F-   C4 8D       CPY   $8D
1321-   A0 DF       LDY   #$DF
1323-   D7          ???
1324-   C1 C9       CMP   ($C9,X)
1326-   D4          ???
1327-   8D AA 8D    STA   $8DAA
132A-   A0 DF       LDY   #$DF
132C-   D0 D2       BNE   $1300
132E-   CE D4 A0    DEC   $A0D4
1331-   A2 D4       LDX   #$D4
1333-   CF          ???
1334-   20 D3 C8    JSR   $C8D3
1337-   CF          ???
1338-   D7          ???
1339-   20 D4 C8    JSR   $C8D4
133C-   C5 20       CMP   $20
133E-   D2 C5       CMP   ($C5)
1340-   D3          ???
1341-   D5 CC       CMP   $CC,X
1343-   D4          ???
1344-   20 CF C6    JSR   $C6CF
1347-   20 D3 C3    JSR   $C3D3
134A-   C1 D4       CMP   ($D4,X)
134C-   AC A2 AC    LDY   $ACA2
134F-   B8          CLV
1350-   C4 8D       CPY   $8D
1352-   A0 DF       LDY   #$DF
1354-   D0 D2       BNE   $1328
1356-   CE D4 A0    DEC   $A0D4
1359-   A2 D7       LDX   #$D7
135B-   C5 20       CMP   $20
135D-   D5 D3       CMP   $D3,X
135F-   C5 C4       CMP   $C4
1361-   20 D4 C8    JSR   $C8D4
1364-   C5 20       CMP   $20
1366-   D3          ???
1367-   D0 D2       BNE   $133B
1369-   CE 20 CD    DEC   $CD20
136C-   C1 C3       CMP   ($C3,X)
136E-   D2 CF       CMP   ($CF)
1370-   AC 20 D7    LDY   $D720
1373-   C8          INY
1374-   C9 C3       CMP   #$C3
1376-   C8          INY
1377-   A2 AC       LDX   #$AC
1379-   B8          CLV
137A-   C4 8D       CPY   $8D
137C-   A0 DF       LDY   #$DF
137E-   D0 D2       BNE   $1352
1380-   CE D4 A0    DEC   $A0D4
1383-   A2 D3       LDX   #$D3
1385-   C9 CD       CMP   #$CD
1387-   D0 CC       BNE   $1355
1389-   D9 20 D0    CMP   $D020,Y
138C-   D2 C9       CMP   ($C9)
138E-   CE D4 D3    DEC   $D3D4
1391-   20 C1 20    JSR   $20C1
1394-   D3          ???
1395-   D4          ???
1396-   D2 C9       CMP   ($C9)
1398-   CE C7 AE    DEC   $AEC7
139B-   20 D4 C8    JSR   $C8D4
139E-   C9 D3       CMP   #$D3
13A0-   A2 AC       LDX   #$AC
13A2-   B8          CLV
13A3-   C4 8D       CPY   $8D
13A5-   A0 DF       LDY   #$DF
13A7-   D0 D2       BNE   $137B
13A9-   CE D4 A0    DEC   $A0D4
13AC-   A2 D7       LDX   #$D7
13AE-   CF          ???
13AF-   D2 CB       CMP   ($CB)
13B1-   D3          ???
13B2-   20 C4 C9    JSR   $C9C4
13B5-   C6 C6       DEC   $C6
13B7-   C5 D2       CMP   $D2
13B9-   C5 CE       CMP   $CE
13BB-   D4          ???
13BC-   CC D9 20    CPY   $20D9
13BF-   D4          ???
13C0-   C8          INY
13C1-   C1 CE       CMP   ($CE,X)
13C3-   20 D4 C8    JSR   $C8D4
13C6-   C5 20       CMP   $20
13C8-   D0 D2       BNE   $139C
13CA-   C9 CE       CMP   #$CE
13CC-   D4          ???
13CD-   A2 AC       LDX   #$AC
13CF-   B8          CLV
13D0-   C4 8D       CPY   $8D
13D2-   A0 DF       LDY   #$DF
13D4-   D0 D2       BNE   $13A8
13D6-   CE D4 A0    DEC   $A0D4
13D9-   A2 D2       LDX   #$D2
13DB-   CF          ???
13DC-   D5 D4       CMP   $D4,X
13DE-   C9 CE       CMP   #$CE
13E0-   C5 D3       CMP   $D3
13E2-   20 C9 CE    JSR   $CEC9
13E5-   20 D3 D4    JSR   $D4D3
13E8-   C4 C9       CPY   $C9
13EA-   CF          ???
13EB-   20 CF D2    JSR   $D2CF
13EE-   20 D4 C8    JSR   $C8D4
13F1-   C5 20       CMP   $20
13F3-   DF          ???
13F4-   D0 D2       BNE   $13C8
13F6-   CE D4 A2    DEC   $A2D4
13F9-   AC B8 C4    LDY   $C4B8
13FC-   8D A0 DF    STA   $DFA0
13FF-   D0 D2       BNE   $13D3
1401-   CE D4 A0    DEC   $A0D4
1404-   A2 D2       LDX   #$D2
1406-   CF          ???
1407-   D5 D4       CMP   $D4,X
1409-   C9 CE       CMP   #$CE
140B-   C5 AC       CMP   $AC
140D-   20 C1 D3    JSR   $D3C1
1410-   20 C9 D4    JSR   $D4C9
1413-   20 C3 C1    JSR   $C1C3
1416-   CE 20 CF    DEC   $CF20
1419-   CE CC D9    DEC   $D9CC
141C-   20 C8 C1    JSR   $C1C8
141F-   CE C4 CC    DEC   $CCC4
1422-   C5 A2       CMP   $A2
1424-   AC B8 C4    LDY   $C4B8
1427-   8D A0 DF    STA   $DFA0
142A-   D0 D2       BNE   $13FE
142C-   CE D4 A0    DEC   $A0D4
142F-   A2 C1       LDX   #$C1
1431-   20 D3 D4    JSR   $D4D3
1434-   D2 C9       CMP   ($C9)
1436-   CE C7 20    DEC   $20C7
1439-   C1 C4       CMP   ($C4,X)
143B-   C4 D2       CPY   $D2
143D-   C5 D3       CMP   $D3
143F-   D3          ???
1440-   AE A2 AC    LDX   $ACA2
1443-   B8          CLV
1444-   C4 B8       CPY   $B8
1446-   C4 8D       CPY   $8D
1448-   A0 DF       LDY   #$DF
144A-   D0 D2       BNE   $141E
144C-   CE D4 A0    DEC   $A0D4
144F-   A2 D3       LDX   #$D3
1451-   D0 D2       BNE   $1425
1453-   CE 20 C2    DEC   $C220
1456-   D3          ???
1457-   D4          ???
1458-   D2 20       CMP   ($20)
145A-   D2 C5       CMP   ($C5)
145C-   D4          ???
145D-   D5 D2       CMP   $D2,X
145F-   CE D3 BA    DEC   $BAD3
1462-   20 A2 8D    JSR   $8DA2
1465-   A0 D3       LDY   #$D3
1467-   D0 D2       BNE   $143B
1469-   CE A0 C2    DEC   $C2A0
146C-   D3          ???
146D-   D4          ???
146E-   D2 8D       CMP   ($8D)
1470-   A0 DF       LDY   #$DF
1472-   D0 D2       BNE   $1446
1474-   CE D4 A0    DEC   $A0D4
1477-   A2 20       LDX   #$20
1479-   A2 AC       LDX   #$AC
147B-   B8          CLV
147C-   C4 B8       CPY   $B8
147E-   C4 B8       CPY   $B8
1480-   C4 8D       CPY   $8D
1482-   A0 DF       LDY   #$DF
1484-   D7          ???
1485-   C1 C9       CMP   ($C9,X)
1487-   D4          ???
1488-   8D A0 DF    STA   $DFA0
148B-   D0 D2       BNE   $145F
148D-   CE D4 A0    DEC   $A0D4
1490-   A2 20       LDX   #$20
1492-   A2 AC       LDX   #$AC
1494-   B8          CLV
1495-   C4 B8       CPY   $B8
1497-   C4 B8       CPY   $B8
1499-   C4 8D       CPY   $8D
149B-   A0 DF       LDY   #$DF
149D-   D0 D2       BNE   $1471
149F-   CE D4 A0    DEC   $A0D4
14A2-   A2 D4       LDX   #$D4
14A4-   CF          ???
14A5-   D3          ???
14A6-   D4          ???
14A7-   D2 20       CMP   ($20)
14A9-   C3          ???
14AA-   CF          ???
14AB-   CE D6 C5    DEC   $C5D6
14AE-   D2 D4       CMP   ($D4)
14B0-   D3          ???
14B1-   20 C1 20    JSR   $20C1
14B4-   B1 B6       LDA   ($B6),Y
14B6-   AD C2 C9    LDA   $C9C2
14B9-   D4          ???
14BA-   20 C9 CE    JSR   $CEC9
14BD-   D4          ???
14BE-   C5 C7       CMP   $C7
14C0-   C5 D2       CMP   $D2
14C2-   20 C9 CE    JSR   $CEC9
14C5-   D4          ???
14C6-   CF          ???
14C7-   A2 AC       LDX   #$AC
14C9-   B8          CLV
14CA-   C4 8D       CPY   $8D
14CC-   A0 DF       LDY   #$DF
14CE-   D0 D2       BNE   $14A2
14D0-   CE D4 A0    DEC   $A0D4
14D3-   A2 C9       LDX   #$C9
14D5-   D4          ???
14D6-   D3          ???
14D7-   20 D3 D4    JSR   $D4D3
14DA-   D2 C9       CMP   ($C9)
14DC-   CE C7 20    DEC   $20C7
14DF-   C5 D1       CMP   $D1
14E1-   D5 C9       CMP   $C9,X
14E3-   D6 C1       DEC   $C1,X
14E5-   CC C5 CE    CPY   $CEC5
14E8-   D4          ???
14E9-   AE 20 D4    LDX   $D420
14EC-   C8          INY
14ED-   C9 D3       CMP   #$D3
14EF-   20 C3 C1    JSR   $C1C3
14F2-   CE A2 AC    DEC   $ACA2
14F5-   B8          CLV
14F6-   C4 8D       CPY   $8D
14F8-   A0 DF       LDY   #$DF
14FA-   D0 D2       BNE   $14CE
14FC-   CE D4 A0    DEC   $A0D4
14FF-   A2 C5       LDX   #$C5
1501-   C9 D4       CMP   #$D4
1503-   C8          INY
1504-   C5 D2       CMP   $D2
1506-   20 C2 C5    JSR   $C5C2
1509-   20 C1 20    JSR   $20C1
150C-   CC C9 D4    CPY   $D4C9
150F-   C5 D2       CMP   $D2
1511-   C1 CC       CMP   ($CC,X)
1513-   20 CF D2    JSR   $D2CF
1516-   20 C1 CE    JSR   $CEC1
1519-   20 C1 C4    JSR   $C4C1
151C-   C4 D2       CPY   $D2
151E-   C5 D3       CMP   $D3
1520-   D3          ???
1521-   AE A2 8D    LDX   $8DA2
1524-   A0 DF       LDY   #$DF
1526-   D0 D2       BNE   $14FA
1528-   CE D4 A0    DEC   $A0D4
152B-   A2 20       LDX   #$20
152D-   A2 AC       LDX   #$AC
152F-   B8          CLV
1530-   C4 B8       CPY   $B8
1532-   C4 8D       CPY   $8D
1534-   A0 DF       LDY   #$DF
1536-   D0 D2       BNE   $150A
1538-   CE D4 A0    DEC   $A0D4
153B-   A2 D4       LDX   #$D4
153D-   CF          ???
153E-   D3          ???
153F-   D4          ???
1540-   D2 20       CMP   ($20)
1542-   A3          ???
1543-   B5 B0       LDA   $B0,X
1545-   B0 B0       BCS   $14F7
1547-   20 D2 C5    JSR   $C5D2
154A-   D4          ???
154B-   D5 D2       CMP   $D2,X
154D-   CE D3 BA    DEC   $BAD3
1550-   20 A2 8D    JSR   $8DA2
1553-   A0 D4       LDY   #$D4
1555-   CF          ???
1556-   D3          ???
1557-   D4          ???
1558-   D2 A0       CMP   ($A0)
155A-   A3          ???
155B-   B5 B0       LDA   $B0,X
155D-   B0 B0       BCS   $150F
155F-   8D A0 D3    STA   $D3A0
1562-   D0 D2       BNE   $1536
1564-   CE A0 D2    DEC   $D2A0
1567-   C5 D4       CMP   $D4
1569-   D5 D2       CMP   $D2,X
156B-   CE 8D A0    DEC   $A08D
156E-   DF          ???
156F-   D0 D2       BNE   $1543
1571-   CE D4 A0    DEC   $A0D4
1574-   A2 20       LDX   #$20
1576-   A2 AC       LDX   #$AC
1578-   B8          CLV
1579-   C4 B8       CPY   $B8
157B-   C4 8D       CPY   $8D
157D-   A0 DF       LDY   #$DF
157F-   D0 D2       BNE   $1553
1581-   CE D4 A0    DEC   $A0D4
1584-   A2 D4       LDX   #$D4
1586-   CF          ???
1587-   D3          ???
1588-   D4          ???
1589-   D2 20       CMP   ($20)
158B-   A4 B3       LDY   $B3
158D-   B0 B0       BCS   $153F
158F-   20 D2 C5    JSR   $C5D2
1592-   D4          ???
1593-   D5 D2       CMP   $D2,X
1595-   CE D3 20    DEC   $20D3
1598-   A2 8D       LDX   #$8D
159A-   A0 CC       LDY   #$CC
159C-   C4 C1       CPY   $C1
159E-   A0 A3       LDY   #$A3
15A0-   A4 C6       LDY   $C6
15A2-   C6 8D       DEC   $8D
15A4-   A0 D3       LDY   #$D3
15A6-   D4          ???
15A7-   C1 A0       CMP   ($A0,X)
15A9-   A4 B3       LDY   $B3
15AB-   B0 B0       BCS   $155D
15AD-   8D A0 D3    STA   $D3A0
15B0-   D4          ???
15B1-   C1 A0       CMP   ($A0,X)
15B3-   A4 B3       LDY   $B3
15B5-   B0 B1       BCS   $1568
15B7-   8D A0 D4    STA   $D4A0
15BA-   CF          ???
15BB-   D3          ???
15BC-   D4          ???
15BD-   D2 A0       CMP   ($A0)
15BF-   A4 B3       LDY   $B3
15C1-   B0 B0       BCS   $1573
15C3-   8D A0 D3    STA   $D3A0
15C6-   D0 D2       BNE   $159A
15C8-   CE A0 D2    DEC   $D2A0
15CB-   C5 D4       CMP   $D4
15CD-   D5 D2       CMP   $D2,X
15CF-   CE 8D A0    DEC   $A08D
15D2-   DF          ???
15D3-   D0 D2       BNE   $15A7
15D5-   CE D4 A0    DEC   $A0D4
15D8-   A2 20       LDX   #$20
15DA-   A2 AC       LDX   #$AC
15DC-   B8          CLV
15DD-   C4 B8       CPY   $B8
15DF-   C4 8D       CPY   $8D
15E1-   A0 DF       LDY   #$DF
15E3-   D0 D2       BNE   $15B7
15E5-   CE D4 A0    DEC   $A0D4
15E8-   A2 CE       LDX   #$CE
15EA-   CF          ???
15EB-   D4          ???
15EC-   C5 20       CMP   $20
15EE-   D4          ???
15EF-   C8          INY
15F0-   C1 D4       CMP   ($D4,X)
15F2-   20 A4 C6    JSR   $C6A4
15F5-   C6 C6       DEC   $C6
15F7-   C6 20       DEC   $20
15F9-   D2 C5       CMP   ($C5)
15FB-   D4          ???
15FC-   D5 D2       CMP   $D2,X
15FE-   CE D3 20    DEC   $20D3
1601-   AD B1 20    LDA   $20B1
1604-   C2          ???
1605-   C5 C3       CMP   $C3
1607-   C1 D5       CMP   ($D5,X)
1609-   D3          ???
160A-   C5 A2       CMP   $A2
160C-   AC B8 C4    LDY   $C4B8
160F-   8D A0 DF    STA   $DFA0
1612-   D0 D2       BNE   $15E6
1614-   CE D4 A0    DEC   $A0D4
1617-   A2 D4       LDX   #$D4
1619-   C8          INY
161A-   C5 20       CMP   $20
161C-   D4          ???
161D-   CF          ???
161E-   D3          ???
161F-   D4          ???
1620-   D2 20       CMP   ($20)
1622-   D2 CF       CMP   ($CF)
1624-   D5 D4       CMP   $D4,X
1626-   C9 CE       CMP   #$CE
1628-   C5 20       CMP   $20
162A-   C1 D3       CMP   ($D3,X)
162C-   D3          ???
162D-   D5 CD       CMP   $CD,X
162F-   C5 D3       CMP   $D3
1631-   20 C1 20    JSR   $20C1
1634-   A2 AC       LDX   #$AC
1636-   B8          CLV
1637-   C4 8D       CPY   $8D
1639-   A0 DF       LDY   #$DF
163B-   D0 D2       BNE   $160F
163D-   CE D4 A0    DEC   $A0D4
1640-   A2 D3       LDX   #$D3
1642-   C9 C7       CMP   #$C7
1644-   CE C5 C4    DEC   $C4C5
1647-   20 D6 C1    JSR   $C1D6
164A-   CC D5 C5    CPY   $C5D5
164D-   AE 20 A2    LDX   $A220
1650-   8D A0 DF    STA   $DFA0
1653-   D0 D2       BNE   $1627
1655-   CE D4 A0    DEC   $A0D4
1658-   A2 20       LDX   #$20
165A-   A2 AC       LDX   #$AC
165C-   B8          CLV
165D-   C4 B8       CPY   $B8
165F-   C4 B8       CPY   $B8
1661-   C4 8D       CPY   $8D
1663-   A0 DF       LDY   #$DF
1665-   D7          ???
1666-   C1 C9       CMP   ($C9,X)
1668-   D4          ???
1669-   8D AA 8D    STA   $8DAA
166C-   A0 DF       LDY   #$DF
166E-   D0 D2       BNE   $1642
1670-   CE D4 A0    DEC   $A0D4
1673-   A2 20       LDX   #$20
1675-   A2 AC       LDX   #$AC
1677-   B8          CLV
1678-   C4 B8       CPY   $B8
167A-   C4 B8       CPY   $B8
167C-   C4 8D       CPY   $8D
167E-   A0 DF       LDY   #$DF
1680-   D0 D2       BNE   $1654
1682-   CE D4 A0    DEC   $A0D4
1685-   A2 C1       LDX   #$C1
1687-   CE C4 20    DEC   $20C4
168A-   D4          ???
168B-   C8          INY
168C-   C5 20       CMP   $20
168E-   D4          ???
168F-   CF          ???
1690-   CE D5 CD    DEC   $CDD5
1693-   20 CD C1    JSR   $C1CD
1696-   C3          ???
1697-   D2 CF       CMP   ($CF)
1699-   20 C4 CF    JSR   $CFC4
169C-   C5 D3       CMP   $D3
169E-   20 D4 C8    JSR   $C8D4
16A1-   C5 A2       CMP   $A2
16A3-   AC B8 C4    LDY   $C4B8
16A6-   8D A0 DF    STA   $DFA0
16A9-   D0 D2       BNE   $167D
16AB-   CE D4 A0    DEC   $A0D4
16AE-   A2 CF       LDX   #$CF
16B0-   D0 D0       BNE   $1682
16B2-   CF          ???
16B3-   D3          ???
16B4-   C9 D4       CMP   #$D4
16B6-   C5 BA       CMP   $BA
16B8-   20 C9 D4    JSR   $D4C9
16BB-   20 D2 C5    JSR   $C5D2
16BE-   D4          ???
16BF-   D5 D2       CMP   $D2,X
16C1-   CE D3 20    DEC   $20D3
16C4-   C1 20       CMP   ($20,X)
16C6-   B1 B6       LDA   ($B6),Y
16C8-   AD C2 C9    LDA   $C9C2
16CB-   D4          ???
16CC-   20 A2 AC    JSR   $ACA2
16CF-   B8          CLV
16D0-   C4 8D       CPY   $8D
16D2-   A0 DF       LDY   #$DF
16D4-   D0 D2       BNE   $16A8
16D6-   CE D4 A0    DEC   $A0D4
16D9-   A2 C9       LDX   #$C9
16DB-   CE D4 C5    DEC   $C5D4
16DE-   C7          ???
16DF-   C5 D2       CMP   $D2
16E1-   20 D6 C1    JSR   $C1D6
16E4-   CC D5 C5    CPY   $C5D5
16E7-   20 C3 CF    JSR   $CFC3
16EA-   CE C5 D2    DEC   $D2C5
16ED-   D4          ???
16EE-   C5 C4       CMP   $C4
16F0-   20 C6 D2    JSR   $D2C6
16F3-   CF          ???
16F4-   CD 20 C9    CMP   $C920
16F7-   D4          ???
16F8-   D3          ???
16F9-   A2 AC       LDX   #$AC
16FB-   B8          CLV
16FC-   C4 8D       CPY   $8D
16FE-   A0 DF       LDY   #$DF
1700-   D0 D2       BNE   $16D4
1702-   CE D4 A0    DEC   $A0D4
1705-   A2 D3       LDX   #$D3
1707-   D4          ???
1708-   D2 C9       CMP   ($C9)
170A-   CE C7 20    DEC   $20C7
170D-   C5 D1       CMP   $D1
170F-   D5 C9       CMP   $C9,X
1711-   D6 C1       DEC   $C1,X
1713-   CC C5 CE    CPY   $CEC5
1716-   D4          ???
1717-   AE 20 D4    LDX   $D420
171A-   C8          INY
171B-   D5 D3       CMP   $D3,X
171D-   BA          TSX
171E-   A2 AC       LDX   #$AC
1720-   B8          CLV
1721-   C4 B8       CPY   $B8
1723-   C4 8D       CPY   $8D
1725-   A0 DF       LDY   #$DF
1727-   D0 D2       BNE   $16FB
1729-   CE D4 A0    DEC   $A0D4
172C-   A2 D4       LDX   #$D4
172E-   CF          ???
172F-   CE D5 CD    DEC   $CDD5
1732-   20 A7 B2    JSR   $B2A7
1735-   B5 B5       LDA   $B5,X
1737-   A7          ???
1738-   20 D2 C5    JSR   $C5D2
173B-   D4          ???
173C-   D5 D2       CMP   $D2,X
173E-   CE D3 BA    DEC   $BAD3
1741-   A2 AC       LDX   #$AC
1743-   B8          CLV
1744-   C4 8D       CPY   $8D
1746-   A0 D4       LDY   #$D4
1748-   CF          ???
1749-   CE D5 CD    DEC   $CDD5
174C-   A0 A2       LDY   #$A2
174E-   B2 B5       LDA   ($B5)
1750-   B5 A2       LDA   $A2,X
1752-   8D A0 DF    STA   $DFA0
1755-   C4 D5       CPY   $D5
1757-   CD D0 A0    CMP   $A0D0
175A-   D2 C5       CMP   ($C5)
175C-   D4          ???
175D-   D5 D2       CMP   $D2,X
175F-   CE BB D2    DEC   $D2BB
1762-   C5 D4       CMP   $D4
1764-   CC C5 CE    CPY   $CEC5
1767-   8D A0 DF    STA   $DFA0
176A-   D0 D2       BNE   $173E
176C-   CE D4 A0    DEC   $A0D4
176F-   A2 20       LDX   #$20
1771-   A2 AC       LDX   #$AC
1773-   B8          CLV
1774-   C4 B8       CPY   $B8
1776-   C4 B8       CPY   $B8
1778-   C4 8D       CPY   $8D
177A-   A0 DF       LDY   #$DF
177C-   D7          ???
177D-   C1 C9       CMP   ($C9,X)
177F-   D4          ???
1780-   8D AA 8D    STA   $8DAA
1783-   A0 DF       LDY   #$DF
1785-   D0 D2       BNE   $1759
1787-   CE D4 A0    DEC   $A0D4
178A-   A2 20       LDX   #$20
178C-   A2 AC       LDX   #$AC
178E-   B8          CLV
178F-   C4 B8       CPY   $B8
1791-   C4 B8       CPY   $B8
1793-   C4 B8       CPY   $B8
1795-   C4 8D       CPY   $8D
1797-   A0 DF       LDY   #$DF
1799-   D0 D2       BNE   $176D
179B-   CE D4 A0    DEC   $A0D4
179E-   A2 D3       LDX   #$D3
17A0-   D5 C2       CMP   $C2,X
17A2-   D3          ???
17A3-   D4          ???
17A4-   D2 C9       CMP   ($C9)
17A6-   CE C7 20    DEC   $20C7
17A9-   D2 CF       CMP   ($CF)
17AB-   D5 D4       CMP   $D4,X
17AD-   C9 CE       CMP   #$CE
17AF-   C5 D3       CMP   $D3
17B1-   AF          ???
17B2-   CD C1 C3    CMP   $C3C1
17B5-   D2 CF       CMP   ($CF)
17B7-   D3          ???
17B8-   A2 AC       LDX   #$AC
17BA-   B8          CLV
17BB-   C4 8D       CPY   $8D
17BD-   A0 DF       LDY   #$DF
17BF-   D0 D2       BNE   $1793
17C1-   CE D4 A0    DEC   $A0D4
17C4-   A2 AD       LDX   #$AD
17C6-   AD AD AD    LDA   $ADAD
17C9-   AD AD AD    LDA   $ADAD
17CC-   AD AD AD    LDA   $ADAD
17CF-   AD AD AD    LDA   $ADAD
17D2-   AD AD AD    LDA   $ADAD
17D5-   AD AD AD    LDA   $ADAD
17D8-   AD AD AD    LDA   $ADAD
17DB-   AD AD AD    LDA   $ADAD
17DE-   A2 AC       LDX   #$AC
17E0-   B8          CLV
17E1-   C4 B8       CPY   $B8
17E3-   C4 8D       CPY   $8D
17E5-   A0 DF       LDY   #$DF
17E7-   D0 D2       BNE   $17BB
17E9-   CE D4 A0    DEC   $A0D4
17EC-   A2 D3       LDX   #$D3
17EE-   D0 CF       BNE   $17BF
17F0-   D3          ???
17F1-   20 C6 C9    JSR   $C9C6
17F4-   CE C4 D3    DEC   $D3C4
17F7-   20 D4 C8    JSR   $C8D4
17FA-   C5 20       CMP   $20
17FC-   D0 CF       BNE   $17CD
17FE-   D3          ???
17FF-   C9 D4       CMP   #$D4
1801-   C9 CF       CMP   #$CF
1803-   CE 20 CF    DEC   $CF20
1806-   C6 A2       DEC   $A2
1808-   AC B8 C4    LDY   $C4B8
180B-   8D A0 DF    STA   $DFA0
180E-   D0 D2       BNE   $17E2
1810-   CE D4 A0    DEC   $A0D4
1813-   A2 C1       LDX   #$C1
1815-   20 D3 D5    JSR   $D5D3
1818-   C2          ???
1819-   D3          ???
181A-   D4          ???
181B-   D2 C9       CMP   ($C9)
181D-   CE C7 20    DEC   $20C7
1820-   D7          ???
1821-   C9 D4       CMP   #$D4
1823-   C8          INY
1824-   C9 CE       CMP   #$CE
1826-   20 C1 CE    JSR   $CEC1
1829-   CF          ???
182A-   D4          ???
182B-   C8          INY
182C-   C5 D2       CMP   $D2
182E-   A2 AC       LDX   #$AC
1830-   B8          CLV
1831-   C4 8D       CPY   $8D
1833-   A0 DF       LDY   #$DF
1835-   D0 D2       BNE   $1809
1837-   CE D4 A0    DEC   $A0D4
183A-   A2 D3       LDX   #$D3
183C-   D4          ???
183D-   D2 C9       CMP   ($C9)
183F-   CE C7 AE    DEC   $AEC7
1842-   A2 AC       LDX   #$AC
1844-   B8          CLV
1845-   C4 B8       CPY   $B8
1847-   C4 8D       CPY   $8D
1849-   A0 DF       LDY   #$DF
184B-   D0 D2       BNE   $181F
184D-   CE D4 A0    DEC   $A0D4
1850-   A2 D3       LDX   #$D3
1852-   D0 CF       BNE   $1823
1854-   D3          ???
1855-   20 A7 D4    JSR   $D4A7
1858-   C8          INY
1859-   C9 D3       CMP   #$D3
185B-   20 C9 D3    JSR   $D3C9
185E-   20 C1 20    JSR   $20C1
1861-   D3          ???
1862-   D4          ???
1863-   D2 C9       CMP   ($C9)
1865-   CE C7 A7    DEC   $A7C7
1868-   BB          ???
1869-   C1 D3       CMP   ($D3,X)
186B-   D4          ???
186C-   D2 20       CMP   ($20)
186E-   D2 C5       CMP   ($C5)
1870-   D4          ???
1871-   D5 D2       CMP   $D2,X
1873-   CE D3 BA    DEC   $BAD3
1876-   20 A2 8D    JSR   $8DA2
1879-   A0 D3       LDY   #$D3
187B-   D0 CF       BNE   $184C
187D-   D3          ???
187E-   A0 A2       LDY   #$A2
1880-   D4          ???
1881-   C8          INY
1882-   C9 D3       CMP   #$D3
1884-   20 C9 D3    JSR   $D3C9
1887-   20 C1 20    JSR   $20C1
188A-   D3          ???
188B-   D4          ???
188C-   D2 C9       CMP   ($C9)
188E-   CE C7 A2    DEC   $A2C7
1891-   BB          ???
1892-   C1 D3       CMP   ($D3,X)
1894-   D4          ???
1895-   D2 8D       CMP   ($8D)
1897-   A0 D3       LDY   #$D3
1899-   D4          ???
189A-   C1 A0       CMP   ($A0,X)
189C-   A4 B3       LDY   $B3
189E-   B0 B0       BCS   $1850
18A0-   8D A0 CC    STA   $CCA0
18A3-   C4 C1       CPY   $C1
18A5-   A0 A3       LDY   #$A3
18A7-   B0 8D       BCS   $1836
18A9-   A0 D3       LDY   #$D3
18AB-   D4          ???
18AC-   C1 A0       CMP   ($A0,X)
18AE-   A4 B3       LDY   $B3
18B0-   B0 B1       BCS   $1863
18B2-   A0 BB       LDY   #$BB
18B4-   20 C3 CC    JSR   $CCC3
18B7-   C5 C1       CMP   $C1
18B9-   D2 20       CMP   ($20)
18BB-   C8          INY
18BC-   C9 20       CMP   #$20
18BE-   C2          ???
18BF-   D9 D4 C5    CMP   $C5D4,Y
18C2-   8D A0 D4    STA   $D4A0
18C5-   CF          ???
18C6-   D3          ???
18C7-   D4          ???
18C8-   D2 A0       CMP   ($A0)
18CA-   A4 B3       LDY   $B3
18CC-   B0 B0       BCS   $187E
18CE-   8D A0 D3    STA   $D3A0
18D1-   D0 D2       BNE   $18A5
18D3-   CE A0 D2    DEC   $D2A0
18D6-   C5 D4       CMP   $D4
18D8-   D5 D2       CMP   $D2,X
18DA-   CE 8D A0    DEC   $A08D
18DD-   DF          ???
18DE-   D0 D2       BNE   $18B2
18E0-   CE D4 A0    DEC   $A0D4
18E3-   A2 20       LDX   #$20
18E5-   A2 AC       LDX   #$AC
18E7-   B8          CLV
18E8-   C4 B8       CPY   $B8
18EA-   C4 B8       CPY   $B8
18EC-   C4 8D       CPY   $8D
18EE-   AA          TAX
18EF-   8D A0 DF    STA   $DFA0
18F2-   D0 D2       BNE   $18C6
18F4-   CE D4 A0    DEC   $A0D4
18F7-   A2 20       LDX   #$20
18F9-   A2 AC       LDX   #$AC
18FB-   B8          CLV
18FC-   C4 B8       CPY   $B8
18FE-   C4 B8       CPY   $B8
1900-   C4 8D       CPY   $8D
1902-   A0 DF       LDY   #$DF
1904-   D0 D2       BNE   $18D8
1906-   CE D4 A0    DEC   $A0D4
1909-   A2 D4       LDX   #$D4
190B-   C8          INY
190C-   C5 20       CMP   $20
190E-   D3          ???
190F-   C3          ???
1910-   D0 D9       BNE   $18EB
1912-   20 CD C1    JSR   $C1CD
1915-   C3          ???
1916-   D2 CF       CMP   ($CF)
1918-   20 C3 CF    JSR   $CFC3
191B-   D0 C9       BNE   $18E6
191D-   C5 D3       CMP   $D3
191F-   20 C1 20    JSR   $20C1
1922-   A2 AC       LDX   #$AC
1924-   B8          CLV
1925-   C4 8D       CPY   $8D
1927-   A0 DF       LDY   #$DF
1929-   D0 D2       BNE   $18FD
192B-   CE D4 A0    DEC   $A0D4
192E-   A2 D3       LDX   #$D3
1930-   D5 C2       CMP   $C2,X
1932-   D3          ???
1933-   D4          ???
1934-   D2 C9       CMP   ($C9)
1936-   CE C7 20    DEC   $20C7
1939-   C6 D2       DEC   $D2
193B-   CF          ???
193C-   CD 20 C1    CMP   $C120
193F-   CE CF D4    DEC   $D4CF
1942-   C8          INY
1943-   C5 D2       CMP   $D2
1945-   20 D3 D4    JSR   $D4D3
1948-   D2 C9       CMP   ($C9)
194A-   CE C7 A2    DEC   $A2C7
194D-   AC B8 C4    LDY   $C4B8
1950-   8D A0 DF    STA   $DFA0
1953-   D0 D2       BNE   $1927
1955-   CE D4 A0    DEC   $A0D4
1958-   A2 C1       LDX   #$C1
195A-   D4          ???
195B-   20 D4 C8    JSR   $C8D4
195E-   C5 20       CMP   $20
1960-   D3          ???
1961-   D0 C5       BNE   $1928
1963-   C3          ???
1964-   C9 C6       CMP   #$C6
1966-   C9 C5       CMP   #$C5
1968-   C4 20       CPY   $20
196A-   C9 CE       CMP   #$CE
196C-   C4 C5       CPY   $C5
196E-   D8          CLD
196F-   AC 20 C8    LDY   $C820
1972-   CF          ???
1973-   CC C4 C9    CPY   $C9C4
1976-   CE C7 A2    DEC   $A2C7
1979-   AC B8 C4    LDY   $C4B8
197C-   8D A0 DF    STA   $DFA0
197F-   D0 D2       BNE   $1953
1981-   CE D4 A0    DEC   $A0D4
1984-   A2 D4       LDX   #$D4
1986-   C8          INY
1987-   C5 20       CMP   $20
1989-   D3          ???
198A-   D5 C2       CMP   $C2,X
198C-   D3          ???
198D-   D4          ???
198E-   D2 C9       CMP   ($C9)
1990-   CE C7 20    DEC   $20C7
1993-   C9 CE       CMP   #$CE
1995-   20 DB D2    JSR   $D2DB
1998-   C5 D4       CMP   $D4
199A-   D5 D2       CMP   $D2,X
199C-   CE DD AE    DEC   $AEDD
199F-   A2 AC       LDX   #$AC
19A1-   B8          CLV
19A2-   C4 B8       CPY   $B8
19A4-   C4 8D       CPY   $8D
19A6-   A0 DF       LDY   #$DF
19A8-   D0 D2       BNE   $197C
19AA-   CE D4 A0    DEC   $A0D4
19AD-   A2 D3       LDX   #$D3
19AF-   C3          ???
19B0-   D0 D9       BNE   $198B
19B2-   20 A7 C1    JSR   $C1A7
19B5-   C2          ???
19B6-   C3          ???
19B7-   C4 C5       CPY   $C5
19B9-   C6 C7       DEC   $C7
19BB-   C8          INY
19BC-   C9 CA       CMP   #$CA
19BE-   CB          ???
19BF-   A7          ???
19C0-   BB          ???
19C1-   A3          ???
19C2-   B2 BB       LDA   ($BB)
19C4-   A3          ???
19C5-   B4 BB       LDY   $BB,X
19C7-   A3          ???
19C8-   B5 B0       LDA   $B0,X
19CA-   20 D2 C5    JSR   $C5D2
19CD-   D4          ???
19CE-   D5 D2       CMP   $D2,X
19D0-   CE D3 BA    DEC   $BAD3
19D3-   20 A2 8D    JSR   $8DA2
19D6-   A0 D3       LDY   #$D3
19D8-   C3          ???
19D9-   D0 D9       BNE   $19B4
19DB-   A0 A2       LDY   #$A2
19DD-   C1 C2       CMP   ($C2,X)
19DF-   C3          ???
19E0-   C4 C5       CPY   $C5
19E2-   C6 C7       DEC   $C7
19E4-   C8          INY
19E5-   C9 CA       CMP   #$CA
19E7-   CB          ???
19E8-   A2 BB       LDX   #$BB
19EA-   A3          ???
19EB-   B2 BB       LDA   ($BB)
19ED-   A3          ???
19EE-   B4 BB       LDY   $BB,X
19F0-   A3          ???
19F1-   A4 C6       LDY   $C6
19F3-   C6 8D       DEC   $8D
19F5-   A0 D3       LDY   #$D3
19F7-   D0 D2       BNE   $19CB
19F9-   CE A0 D2    DEC   $D2A0
19FC-   C5 D4       CMP   $D4
19FE-   D5 D2       CMP   $D2,X
1A00-   CE 8D A0    DEC   $A08D
1A03-   DF          ???
1A04-   D0 D2       BNE   $19D8
1A06-   CE D4 A0    DEC   $A0D4
1A09-   A2 20       LDX   #$20
1A0B-   A2 AC       LDX   #$AC
1A0D-   B8          CLV
1A0E-   C4 B8       CPY   $B8
1A10-   C4 B8       CPY   $B8
1A12-   C4 8D       CPY   $8D
1A14-   A0 DF       LDY   #$DF
1A16-   D7          ???
1A17-   C1 C9       CMP   ($C9,X)
1A19-   D4          ???
1A1A-   8D AA 8D    STA   $8DAA
1A1D-   A0 DF       LDY   #$DF
1A1F-   D0 D2       BNE   $19F3
1A21-   CE D4 A0    DEC   $A0D4
1A24-   A2 20       LDX   #$20
1A26-   A2 AC       LDX   #$AC
1A28-   B8          CLV
1A29-   C4 B8       CPY   $B8
1A2B-   C4 B8       CPY   $B8
1A2D-   C4 B8       CPY   $B8
1A2F-   C4 B8       CPY   $B8
1A31-   C4 8D       CPY   $8D
1A33-   A0 DF       LDY   #$DF
1A35-   D0 D2       BNE   $1A09
1A37-   CE D4 A0    DEC   $A0D4
1A3A-   A2 D4       LDX   #$D4
1A3C-   C8          INY
1A3D-   C5 20       CMP   $20
1A3F-   D3          ???
1A40-   C4 C5       CPY   $C5
1A42-   CC 20 CD    CPY   $CD20
1A45-   C1 C3       CMP   ($C3,X)
1A47-   D2 CF       CMP   ($CF)
1A49-   20 C4 C5    JSR   $C5C4
1A4C-   CC C5 D4    CPY   $D4C5
1A4F-   C5 D3       CMP   $D3
1A51-   20 C1 20    JSR   $20C1
1A54-   D3          ???
1A55-   D5 C2       CMP   $C2,X
1A57-   D3          ???
1A58-   D4          ???
1A59-   D2 C9       CMP   ($C9)
1A5B-   CE C7 A2    DEC   $A2C7
1A5E-   AC B8 C4    LDY   $C4B8
1A61-   8D A0 DF    STA   $DFA0
1A64-   D0 D2       BNE   $1A38
1A66-   CE D4 A0    DEC   $A0D4
1A69-   A2 C6       LDX   #$C6
1A6B-   D2 CF       CMP   ($CF)
1A6D-   CD 20 D4    CMP   $D420
1A70-   C8          INY
1A71-   C5 20       CMP   $20
1A73-   C7          ???
1A74-   C9 D6       CMP   #$D6
1A76-   C5 CE       CMP   $CE
1A78-   20 D3 CF    JSR   $CFD3
1A7B-   D5 D2       CMP   $D2,X
1A7D-   C3          ???
1A7E-   C5 20       CMP   $20
1A80-   D3          ???
1A81-   D4          ???
1A82-   D2 C9       CMP   ($C9)
1A84-   CE C7 AE    DEC   $AEC7
1A87-   20 CE CF    JSR   $CFCE
1A8A-   D4          ???
1A8B-   C5 20       CMP   $20
1A8D-   A2 AC       LDX   #$AC
1A8F-   B8          CLV
1A90-   C4 8D       CPY   $8D
1A92-   A0 DF       LDY   #$DF
1A94-   D0 D2       BNE   $1A68
1A96-   CE D4 A0    DEC   $A0D4
1A99-   A2 D4       LDX   #$D4
1A9B-   C8          INY
1A9C-   C1 D4       CMP   ($D4,X)
1A9E-   20 D4 C8    JSR   $C8D4
1AA1-   C5 20       CMP   $20
1AA3-   D3          ???
1AA4-   CF          ???
1AA5-   D5 D2       CMP   $D2,X
1AA7-   C3          ???
1AA8-   C5 20       CMP   $20
1AAA-   D3          ???
1AAB-   D4          ???
1AAC-   D2 C9       CMP   ($C9)
1AAE-   CE C7 20    DEC   $20C7
1AB1-   CD D5 D3    CMP   $D3D5
1AB4-   D4          ???
1AB5-   20 CE CF    JSR   $CFCE
1AB8-   D4          ???
1AB9-   A2 AC       LDX   #$AC
1ABB-   B8          CLV
1ABC-   C4 8D       CPY   $8D
1ABE-   A0 DF       LDY   #$DF
1AC0-   D0 D2       BNE   $1A94
1AC2-   CE D4 A0    DEC   $A0D4
1AC5-   A2 C2       LDX   #$C2
1AC7-   C5 20       CMP   $20
1AC9-   C1 20       CMP   ($20,X)
1ACB-   CC C9 D4    CPY   $D4C9
1ACE-   C5 D2       CMP   $D2
1AD0-   C1 CC       CMP   ($CC,X)
1AD2-   20 C2 C5    JSR   $C5C2
1AD5-   C3          ???
1AD6-   C1 D5       CMP   ($D5,X)
1AD8-   D3          ???
1AD9-   C5 20       CMP   $20
1ADB-   D4          ???
1ADC-   C8          INY
1ADD-   C9 D3       CMP   #$D3
1ADF-   20 D2 CF    JSR   $CFD2
1AE2-   D5 D4       CMP   $D4,X
1AE4-   C9 CE       CMP   #$CE
1AE6-   C5 A2       CMP   $A2
1AE8-   AC B8 C4    LDY   $C4B8
1AEB-   8D A0 DF    STA   $DFA0
1AEE-   D0 D2       BNE   $1AC2
1AF0-   CE D4 A0    DEC   $A0D4
1AF3-   A2 C1       LDX   #$C1
1AF5-   CC D4 C5    CPY   $C5D4
1AF8-   D2 D3       CMP   ($D3)
1AFA-   20 D4 C8    JSR   $C8D4
1AFD-   C5 20       CMP   $20
1AFF-   D3          ???
1B00-   D4          ???
1B01-   D2 C9       CMP   ($C9)
1B03-   CE C7 20    DEC   $20C7
1B06-   D0 C1       BNE   $1AC9
1B08-   D3          ???
1B09-   D3          ???
1B0A-   C5 C4       CMP   $C4
1B0C-   20 D4 CF    JSR   $CFD4
1B0F-   20 C9 D4    JSR   $D4C9
1B12-   AE A2 AC    LDX   $ACA2
1B15-   B8          CLV
1B16-   C4 B8       CPY   $B8
1B18-   C4 8D       CPY   $8D
1B1A-   A0 DF       LDY   #$DF
1B1C-   D0 D2       BNE   $1AF0
1B1E-   CE D4 A0    DEC   $A0D4
1B21-   A2 C9       LDX   #$C9
1B23-   C6 20       DEC   $20
1B25-   CC D3 D4    CPY   $D4D3
1B28-   D2 20       CMP   ($20)
1B2A-   C8          INY
1B2B-   CF          ???
1B2C-   CC C4 D3    CPY   $D3C4
1B2F-   20 A7 D4    JSR   $D4A7
1B32-   C8          INY
1B33-   C9 D3       CMP   #$D3
1B35-   20 C9 D3    JSR   $D3C9
1B38-   20 C1 20    JSR   $20C1
1B3B-   D3          ???
1B3C-   D4          ???
1B3D-   D2 C9       CMP   ($C9)
1B3F-   CE C7 AE    DEC   $AEC7
1B42-   A7          ???
1B43-   A2 AC       LDX   #$AC
1B45-   B8          CLV
1B46-   C4 8D       CPY   $8D
1B48-   A0 DF       LDY   #$DF
1B4A-   D0 D2       BNE   $1B1E
1B4C-   CE D4 A0    DEC   $A0D4
1B4F-   A2 D4       LDX   #$D4
1B51-   C8          INY
1B52-   C5 CE       CMP   $CE
1B54-   20 D3 C4    JSR   $C4D3
1B57-   C5 CC       CMP   $CC
1B59-   20 CC D3    JSR   $D3CC
1B5C-   D4          ???
1B5D-   D2 BB       CMP   ($BB)
1B5F-   A3          ???
1B60-   B1 BB       LDA   ($BB),Y
1B62-   A3          ???
1B63-   B7          ???
1B64-   20 D2 C5    JSR   $C5D2
1B67-   D4          ???
1B68-   D5 D2       CMP   $D2,X
1B6A-   CE D3 BA    DEC   $BAD3
1B6D-   20 A2 AC    JSR   $ACA2
1B70-   B8          CLV
1B71-   C4 B8       CPY   $B8
1B73-   C4 8D       CPY   $8D
1B75-   A0 D3       LDY   #$D3
1B77-   C4 C5       CPY   $C5
1B79-   CC A0 CC    CPY   $CCA0
1B7C-   D3          ???
1B7D-   D4          ???
1B7E-   D2 BB       CMP   ($BB)
1B80-   A3          ???
1B81-   B1 BB       LDA   ($BB),Y
1B83-   A3          ???
1B84-   B7          ???
1B85-   8D A0 D3    STA   $D3A0
1B88-   D0 D2       BNE   $1B5C
1B8A-   CE A0 CC    DEC   $CCA0
1B8D-   D3          ???
1B8E-   D4          ???
1B8F-   D2 8D       CMP   ($8D)
1B91-   A0 DF       LDY   #$DF
1B93-   D0 D2       BNE   $1B67
1B95-   CE D4 A0    DEC   $A0D4
1B98-   A2 20       LDX   #$20
1B9A-   A2 AC       LDX   #$AC
1B9C-   B8          CLV
1B9D-   C4 B8       CPY   $B8
1B9F-   C4 B8       CPY   $B8
1BA1-   C4 B8       CPY   $B8
1BA3-   C4 8D       CPY   $8D
1BA5-   A0 DF       LDY   #$DF
1BA7-   D7          ???
1BA8-   C1 C9       CMP   ($C9,X)
1BAA-   D4          ???
1BAB-   8D AA 8D    STA   $8DAA
1BAE-   A0 DF       LDY   #$DF
1BB0-   D0 D2       BNE   $1B84
1BB2-   CE D4 A0    DEC   $A0D4
1BB5-   A2 D4       LDX   #$D4
1BB7-   C8          INY
1BB8-   C5 20       CMP   $20
1BBA-   D3          ???
1BBB-   C9 CE       CMP   #$CE
1BBD-   D3          ???
1BBE-   20 CD C1    JSR   $C1CD
1BC1-   C3          ???
1BC2-   D2 CF       CMP   ($CF)
1BC4-   20 C4 CF    JSR   $CFC4
1BC7-   C5 D3       CMP   $D3
1BC9-   20 D4 C8    JSR   $C8D4
1BCC-   C5 20       CMP   $20
1BCE-   A2 AC       LDX   #$AC
1BD0-   B8          CLV
1BD1-   C4 8D       CPY   $8D
1BD3-   A0 DF       LDY   #$DF
1BD5-   D0 D2       BNE   $1BA9
1BD7-   CE D4 A0    DEC   $A0D4
1BDA-   A2 CF       LDX   #$CF
1BDC-   D0 D0       BNE   $1BAE
1BDE-   CF          ???
1BDF-   D3          ???
1BE0-   C9 D4       CMP   #$D4
1BE2-   C5 20       CMP   $20
1BE4-   CF          ???
1BE5-   C6 20       DEC   $20
1BE7-   D3          ???
1BE8-   C4 C5       CPY   $C5
1BEA-   CC BA 20    CPY   $20BA
1BED-   C9 D4       CMP   #$D4
1BEF-   20 C9 CE    JSR   $CEC9
1BF2-   D3          ???
1BF3-   C5 D2       CMP   $D2
1BF5-   D4          ???
1BF6-   D3          ???
1BF7-   A2 AC       LDX   #$AC
1BF9-   B8          CLV
1BFA-   C4 8D       CPY   $8D
1BFC-   A0 DF       LDY   #$DF
1BFE-   D0 D2       BNE   $1BD2
1C00-   CE D4 A0    DEC   $A0D4
1C03-   A2 C1       LDX   #$C1
1C05-   20 D3 D5    JSR   $D5D3
1C08-   C2          ???
1C09-   D3          ???
1C0A-   D4          ???
1C0B-   D2 C9       CMP   ($C9)
1C0D-   CE C7 20    DEC   $20C7
1C10-   C9 CE       CMP   #$CE
1C12-   D4          ???
1C13-   CF          ???
1C14-   20 C1 20    JSR   $20C1
1C17-   D0 C1       BNE   $1BDA
1C19-   D2 C5       CMP   ($C5)
1C1B-   CE D4 20    DEC   $20D4
1C1E-   D3          ???
1C1F-   D4          ???
1C20-   D2 C9       CMP   ($C9)
1C22-   CE C7 A2    DEC   $A2C7
1C25-   AC B8 C4    LDY   $C4B8
1C28-   8D A0 DF    STA   $DFA0
1C2B-   D0 D2       BNE   $1BFF
1C2D-   CE D4 A0    DEC   $A0D4
1C30-   A2 C1       LDX   #$C1
1C32-   D4          ???
1C33-   20 D4 C8    JSR   $C8D4
1C36-   C5 20       CMP   $20
1C38-   C7          ???
1C39-   C9 D6       CMP   #$D6
1C3B-   C5 CE       CMP   $CE
1C3D-   20 C9 CE    JSR   $CEC9
1C40-   C4 C5       CPY   $C5
1C42-   D8          CLD
1C43-   AE 20 CE    LDX   $CE20
1C46-   CF          ???
1C47-   D4          ???
1C48-   C5 20       CMP   $20
1C4A-   D4          ???
1C4B-   C8          INY
1C4C-   C1 D4       CMP   ($D4,X)
1C4E-   A2 AC       LDX   #$AC
1C50-   B8          CLV
1C51-   C4 8D       CPY   $8D
1C53-   A0 DF       LDY   #$DF
1C55-   D0 D2       BNE   $1C29
1C57-   CE D4 A0    DEC   $A0D4
1C5A-   A2 D7       LDX   #$D7
1C5C-   C8          INY
1C5D-   C9 CC       CMP   #$CC
1C5F-   C5 20       CMP   $20
1C61-   D4          ???
1C62-   C8          INY
1C63-   C5 20       CMP   $20
1C65-   D0 C1       BNE   $1C28
1C67-   D2 C5       CMP   ($C5)
1C69-   CE D4 20    DEC   $20D4
1C6C-   D3          ???
1C6D-   D4          ???
1C6E-   D2 C9       CMP   ($C9)
1C70-   CE C7 20    DEC   $20C7
1C73-   C3          ???
1C74-   C1 CE       CMP   ($CE,X)
1C76-   CE CF D4    DEC   $D4CF
1C79-   20 C2 C5    JSR   $C5C2
1C7C-   20 A2 AC    JSR   $ACA2
1C7F-   B8          CLV
1C80-   C4 8D       CPY   $8D
1C82-   A0 DF       LDY   #$DF
1C84-   D0 D2       BNE   $1C58
1C86-   CE D4 A0    DEC   $A0D4
1C89-   A2 C1       LDX   #$C1
1C8B-   20 CC C9    JSR   $C9CC
1C8E-   D4          ???
1C8F-   C5 D2       CMP   $D2
1C91-   C1 CC       CMP   ($CC,X)
1C93-   AC 20 D4    LDY   $D420
1C96-   C8          INY
1C97-   C5 20       CMP   $20
1C99-   D3          ???
1C9A-   D5 C2       CMP   $C2,X
1C9C-   D3          ???
1C9D-   D4          ???
1C9E-   D2 C9       CMP   ($C9)
1CA0-   CE C7 20    DEC   $20C7
1CA3-   C9 D4       CMP   #$D4
1CA5-   D3          ???
1CA6-   C5 CC       CMP   $CC
1CA8-   C6 20       DEC   $20
1CAA-   C3          ???
1CAB-   C1 CE       CMP   ($CE,X)
1CAD-   20 C2 C5    JSR   $C5C2
1CB0-   AE A2 AC    LDX   $ACA2
1CB3-   B8          CLV
1CB4-   C4 B8       CPY   $B8
1CB6-   C4 8D       CPY   $8D
1CB8-   A0 DF       LDY   #$DF
1CBA-   D0 D2       BNE   $1C8E
1CBC-   CE D4 A0    DEC   $A0D4
1CBF-   A2 D4       LDX   #$D4
1CC1-   C8          INY
1CC2-   D5 D3       CMP   $D3,X
1CC4-   20 D3 C9    JSR   $C9D3
1CC7-   CE D3 20    DEC   $20D3
1CCA-   CC D3 D4    CPY   $D4D3
1CCD-   D2 BB       CMP   ($BB)
1CCF-   A3          ???
1CD0-   B1 BB       LDA   ($BB),Y
1CD2-   A3          ???
1CD3-   B5 B0       LDA   $B0,X
1CD5-   BB          ???
1CD6-   A7          ???
1CD7-   D4          ???
1CD8-   C8          INY
1CD9-   C9 D3       CMP   #$D3
1CDB-   20 C9 D3    JSR   $D3C9
1CDE-   20 CE CF    JSR   $CFCE
1CE1-   D4          ???
1CE2-   A7          ???
1CE3-   A2 AC       LDX   #$AC
1CE5-   B8          CLV
1CE6-   C4 8D       CPY   $8D
1CE8-   A0 DF       LDY   #$DF
1CEA-   D0 D2       BNE   $1CBE
1CEC-   CE D4 A0    DEC   $A0D4
1CEF-   A2 D2       LDX   #$D2
1CF1-   C5 D4       CMP   $D4
1CF3-   D5 D2       CMP   $D2,X
1CF5-   CE D3 BA    DEC   $BAD3
1CF8-   20 A2 AC    JSR   $ACA2
1CFB-   B8          CLV
1CFC-   C4 8D       CPY   $8D
1CFE-   A0 D3       LDY   #$D3
1D00-   C9 CE       CMP   #$CE
1D02-   D3          ???
1D03-   A0 CC       LDY   #$CC
1D05-   D3          ???
1D06-   D4          ???
1D07-   D2 BB       CMP   ($BB)
1D09-   A3          ???
1D0A-   B1 BB       LDA   ($BB),Y
1D0C-   A3          ???
1D0D-   B5 B0       LDA   $B0,X
1D0F-   BB          ???
1D10-   A2 D4       LDX   #$D4
1D12-   C8          INY
1D13-   C9 D3       CMP   #$D3
1D15-   A0 C9       LDY   #$C9
1D17-   D3          ???
1D18-   A0 CE       LDY   #$CE
1D1A-   CF          ???
1D1B-   D4          ???
1D1C-   A2 8D       LDX   #$8D
1D1E-   A0 D3       LDY   #$D3
1D20-   D0 D2       BNE   $1CF4
1D22-   CE A0 CC    DEC   $CCA0
1D25-   D3          ???
1D26-   D4          ???
1D27-   D2 8D       CMP   ($8D)
1D29-   A0 DF       LDY   #$DF
1D2B-   D0 D2       BNE   $1CFF
1D2D-   CE D4 A0    DEC   $A0D4
1D30-   A2 20       LDX   #$20
1D32-   A2 AC       LDX   #$AC
1D34-   B8          CLV
1D35-   C4 B8       CPY   $B8
1D37-   C4 B8       CPY   $B8
1D39-   C4 B8       CPY   $B8
1D3B-   C4 8D       CPY   $8D
1D3D-   A0 DF       LDY   #$DF
1D3F-   D7          ???
1D40-   C1 C9       CMP   ($C9,X)
1D42-   D4          ???
1D43-   8D 8D AA    STA   $AA8D
1D46-   8D A0 CA    STA   $CAA0
1D49-   CD D0 A0    CMP   $A0D0
1D4C-   D2 C5       CMP   ($C5)
1D4E-   C5 CE       CMP   $CE
1D50-   D4          ???
1D51-   D2 D9       CMP   ($D9)
1D53-   8D AA 8D    STA   $8DAA
1D56-   AA          TAX
1D57-   E0 E0       CPX   #$E0
1D59-   E0 E0       CPX   #$E0
1D5B-   E0 E0       CPX   #$E0
1D5D-   E0 E0       CPX   #$E0
1D5F-   E0 E0       CPX   #$E0
1D61-   E0 E0       CPX   #$E0
1D63-   E0 E0       CPX   #$E0
1D65-   E0 E0       CPX   #$E0
1D67-   E0 E0       CPX   #$E0
1D69-   E0 E0       CPX   #$E0
1D6B-   E0 E0       CPX   #$E0
1D6D-   E0 E0       CPX   #$E0
1D6F-   E0 E0       CPX   #$E0
1D71-   E0 E0       CPX   #$E0
1D73-   E0 E0       CPX   #$E0
1D75-   AA          TAX
1D76-   8D AA 20    STA   $20AA
1D79-   20 20 20    JSR   $2020
1D7C-   20 20 20    JSR   $2020
1D7F-   20 C2 CF    JSR   $CFC2
1D82-   D4          ???
1D83-   D4          ???
1D84-   CF          ???
1D85-   CD 20 C9    CMP   $C920
1D88-   CE C3 CC    DEC   $CCC3
1D8B-   D5 C4       CMP   $C4,X
1D8D-   C5 D3       CMP   $D3
1D8F-   20 20 20    JSR   $2020
1D92-   20 20 20    JSR   $2020
1D95-   20 AA 8D    JSR   $8DAA
1D98-   AA          TAX
1D99-   AC AC AC    LDY   $ACAC
1D9C-   AC AC AC    LDY   $ACAC
1D9F-   AC AC AC    LDY   $ACAC
1DA2-   AC AC AC    LDY   $ACAC
1DA5-   AC AC AC    LDY   $ACAC
1DA8-   AC AC AC    LDY   $ACAC
1DAB-   AC AC AC    LDY   $ACAC
1DAE-   AC AC AC    LDY   $ACAC
1DB1-   AC AC AC    LDY   $ACAC
1DB4-   AC AC AC    LDY   $ACAC
1DB7-   AA          TAX
1DB8-   8D AA 8D    STA   $8DAA
1DBB-   AA          TAX
1DBC-   AA          TAX
1DBD-   20 C2 CF    JSR   $CFC2
1DC0-   D4          ???
1DC1-   D4          ???
1DC2-   CF          ???
1DC3-   CD 20 C9    CMP   $C920
1DC6-   CE C3 CC    DEC   $CCC3
1DC9-   D5 C4       CMP   $C4,X
1DCB-   C5 D3       CMP   $D3
1DCD-   8D AA 8D    STA   $8DAA
1DD0-   A0 D0       LDY   #$D0
1DD2-   D5 D4       CMP   $D4,X
1DD4-   A0 D3       LDY   #$D3
1DD6-   D4          ???
1DD7-   D2 C9       CMP   ($C9)
1DD9-   CE C7 D3    DEC   $D3C7
1DDC-   AE CC C9    LDX   $C9CC
1DDF-   C2          ???
1DE0-   8D A0 D0    STA   $D0A0
1DE3-   D5 D4       CMP   $D4,X
1DE5-   A0 D3       LDY   #$D3
1DE7-   D5 C2       CMP   $C2,X
1DE9-   D3          ???
1DEA-   D4          ???
1DEB-   D2 C9       CMP   ($C9)
1DED-   CE C7 D3    DEC   $D3C7
1DF0-   AE CC C9    LDX   $C9CC
1DF3-   C2          ???
1DF4-   8D A0 D0    STA   $D0A0
1DF7-   D5 D4       CMP   $D4,X
1DF9-   A0 D2       LDY   #$D2
1DFB-   C5 D1       CMP   $D1
1DFD-   D5 C9       CMP   $C9,X
1DFF-   D2 C5       CMP   ($C5)
1E01-   C4 AE       CPY   $AE
1E03-   CC C9 C2    CPY   $C2C9
1E06-   8D AA 8D    STA   $8DAA
1E09-   C1 D3       CMP   ($D3,X)
1E0B-   D4          ???
1E0C-   D2 A0       CMP   ($A0)
1E0E-   D3          ???
1E0F-   D4          ???
1E10-   D2 A0       CMP   ($A0)
1E12-   A2 C1       LDX   #$C1
1E14-   A2 8D       LDX   #$8D
1E16-   C2          ???
1E17-   D3          ???
1E18-   D4          ???
1E19-   D2 A0       CMP   ($A0)
1E1B-   D3          ???
1E1C-   D4          ???
1E1D-   D2 A0       CMP   ($A0)
1E1F-   A2 C2       LDX   #$C2
1E21-   A2 8D       LDX   #$8D
1E23-   CC D3 D4    CPY   $D4D3
1E26-   D2 A0       CMP   ($A0)
1E28-   D3          ???
1E29-   D4          ???
1E2A-   D2 A0       CMP   ($A0)
1E2C-   A2 D4       LDX   #$D4
1E2E-   C8          INY
1E2F-   C9 D3       CMP   #$D3
1E31-   20 C9 D3    JSR   $D3C9
1E34-   20 C1 20    JSR   $20C1
1E37-   D3          ???
1E38-   D4          ???
1E39-   D2 C9       CMP   ($C9)
1E3B-   CE C7 AE    DEC   $AEC7
1E3E-   A2 8D       LDX   #$8D
