0901-   AA          TAX
0902-   8D AA AA    STA   $AAAA
0905-   AA          TAX
0906-   AA          TAX
0907-   AA          TAX
0908-   AA          TAX
0909-   AA          TAX
090A-   AA          TAX
090B-   AA          TAX
090C-   AA          TAX
090D-   AA          TAX
090E-   AA          TAX
090F-   AA          TAX
0910-   AA          TAX
0911-   AA          TAX
0912-   AA          TAX
0913-   AA          TAX
0914-   AA          TAX
0915-   AA          TAX
0916-   AA          TAX
0917-   AA          TAX
0918-   AA          TAX
0919-   AA          TAX
091A-   AA          TAX
091B-   AA          TAX
091C-   AA          TAX
091D-   AA          TAX
091E-   AA          TAX
091F-   AA          TAX
0920-   AA          TAX
0921-   AA          TAX
0922-   AA          TAX
0923-   8D AA 20    STA   $20AA
0926-   20 20 20    JSR   $2020
0929-   20 20 20    JSR   $2020
092C-   20 20 20    JSR   $2020
092F-   20 20 20    JSR   $2020
0932-   20 20 20    JSR   $2020
0935-   20 20 20    JSR   $2020
0938-   20 20 20    JSR   $2020
093B-   20 20 20    JSR   $2020
093E-   20 20 20    JSR   $2020
0941-   20 20 AA    JSR   $AA20
0944-   8D AA 20    STA   $20AA
0947-   20 20 20    JSR   $2020
094A-   20 20 AD    JSR   $AD20
094D-   BC 20 D3    LDY   $D320,X
0950-   D4          ???
0951-   D2 C9       CMP   ($C9)
0953-   CE C7 D3    DEC   $D3C7
0956-   20 C4 C5    JSR   $C5C4
0959-   CD CF 20    CMP   $20CF
095C-   BE AD 20    LDX   $20AD,Y
095F-   20 20 20    JSR   $2020
0962-   20 20 AA    JSR   $AA20
0965-   8D AA 20    STA   $20AA
0968-   20 20 20    JSR   $2020
096B-   20 20 20    JSR   $2020
096E-   20 20 20    JSR   $2020
0971-   20 20 20    JSR   $2020
0974-   20 20 20    JSR   $2020
0977-   20 20 20    JSR   $2020
097A-   20 20 20    JSR   $2020
097D-   20 20 20    JSR   $2020
0980-   20 20 20    JSR   $2020
0983-   20 20 AA    JSR   $AA20
0986-   8D AA 20    STA   $20AA
0989-   20 20 20    JSR   $2020
098C-   20 20 20    JSR   $2020
098F-   D6 C5       DEC   $C5,X
0991-   D2 D3       CMP   ($D3)
0993-   C9 CF       CMP   #$CF
0995-   CE 20 B0    DEC   $B020
0998-   B0 AE       BCS   $0948
099A-   B0 B0       BCS   $094C
099C-   AE B0 B1    LDX   $B1B0
099F-   20 20 20    JSR   $2020
09A2-   20 20 20    JSR   $2020
09A5-   20 AA 8D    JSR   $8DAA
09A8-   AA          TAX
09A9-   20 20 20    JSR   $2020
09AC-   20 20 20    JSR   $2020
09AF-   20 20 20    JSR   $2020
09B2-   20 20 20    JSR   $2020
09B5-   20 20 20    JSR   $2020
09B8-   20 20 20    JSR   $2020
09BB-   20 20 20    JSR   $2020
09BE-   20 20 20    JSR   $2020
09C1-   20 20 20    JSR   $2020
09C4-   20 20 20    JSR   $2020
09C7-   AA          TAX
09C8-   8D AA 20    STA   $20AA
09CB-   20 20 20    JSR   $2020
09CE-   20 20 20    JSR   $2020
09D1-   20 20 B0    JSR   $B020
09D4-   B3          ???
09D5-   AF          ???
09D6-   B0 B4       BCS   $098C
09D8-   AF          ???
09D9-   B1 B9       LDA   ($B9),Y
09DB-   B8          CLV
09DC-   B0 20       BCS   $09FE
09DE-   20 20 20    JSR   $2020
09E1-   20 20 20    JSR   $2020
09E4-   20 20 20    JSR   $2020
09E7-   20 AA 8D    JSR   $8DAA
09EA-   AA          TAX
09EB-   20 20 20    JSR   $2020
09EE-   20 20 20    JSR   $2020
09F1-   20 20 20    JSR   $2020
09F4-   20 20 20    JSR   $2020
09F7-   20 20 20    JSR   $2020
09FA-   20 20 20    JSR   $2020
09FD-   20 20 20    JSR   $2020
0A00-   20 20 20    JSR   $2020
0A03-   20 20 20    JSR   $2020
0A06-   20 20 20    JSR   $2020
0A09-   AA          TAX
0A0A-   8D AA AA    STA   $AAAA
0A0D-   AA          TAX
0A0E-   AA          TAX
0A0F-   AA          TAX
0A10-   AA          TAX
0A11-   AA          TAX
0A12-   AA          TAX
0A13-   AA          TAX
0A14-   AA          TAX
0A15-   AA          TAX
0A16-   AA          TAX
0A17-   AA          TAX
0A18-   AA          TAX
0A19-   AA          TAX
0A1A-   AA          TAX
0A1B-   AA          TAX
0A1C-   AA          TAX
0A1D-   AA          TAX
0A1E-   AA          TAX
0A1F-   AA          TAX
0A20-   AA          TAX
0A21-   AA          TAX
0A22-   AA          TAX
0A23-   AA          TAX
0A24-   AA          TAX
0A25-   AA          TAX
0A26-   AA          TAX
0A27-   AA          TAX
0A28-   AA          TAX
0A29-   AA          TAX
0A2A-   AA          TAX
0A2B-   8D AA 20    STA   $20AA
0A2E-   20 20 20    JSR   $2020
0A31-   20 20 20    JSR   $2020
0A34-   20 20 20    JSR   $2020
0A37-   20 20 20    JSR   $2020
0A3A-   20 20 20    JSR   $2020
0A3D-   20 20 20    JSR   $2020
0A40-   20 20 20    JSR   $2020
0A43-   20 20 20    JSR   $2020
0A46-   20 20 20    JSR   $2020
0A49-   20 20 AA    JSR   $AA20
0A4C-   8D AA 20    STA   $20AA
0A4F-   20 20 20    JSR   $2020
0A52-   20 20 20    JSR   $2020
0A55-   CE C1 D4    DEC   $D4C1
0A58-   C8          INY
0A59-   C1 CE       CMP   ($CE,X)
0A5B-   20 C4 AE    JSR   $AEC4
0A5E-   20 D2 C9    JSR   $C9D2
0A61-   C7          ???
0A62-   C7          ???
0A63-   D3          ???
0A64-   20 20 20    JSR   $2020
0A67-   20 20 20    JSR   $2020
0A6A-   20 20 AA    JSR   $AA20
0A6D-   8D AA 20    STA   $20AA
0A70-   20 20 CE    JSR   $CE20
0A73-   C1 D4       CMP   ($D4,X)
0A75-   C8          INY
0A76-   C1 CE       CMP   ($CE,X)
0A78-   AE D2 C9    LDX   $C9D2
0A7B-   C7          ???
0A7C-   C7          ???
0A7D-   D3          ???
0A7E-   C0 CF       CPY   #$CF
0A80-   D5 D4       CMP   $D4,X
0A82-   CC CF CF    CPY   $CFCF
0A85-   CB          ???
0A86-   AE C3 CF    LDX   $CFC3
0A89-   CD 20 20    CMP   $2020
0A8C-   20 AA 8D    JSR   $8DAA
0A8F-   AA          TAX
0A90-   20 20 20    JSR   $2020
0A93-   20 20 20    JSR   $2020
0A96-   20 20 20    JSR   $2020
0A99-   20 20 20    JSR   $2020
0A9C-   20 20 20    JSR   $2020
0A9F-   20 20 20    JSR   $2020
0AA2-   20 20 20    JSR   $2020
0AA5-   20 20 20    JSR   $2020
0AA8-   20 20 20    JSR   $2020
0AAB-   20 20 20    JSR   $2020
0AAE-   AA          TAX
0AAF-   8D AA AA    STA   $AAAA
0AB2-   AA          TAX
0AB3-   AA          TAX
0AB4-   AA          TAX
0AB5-   AA          TAX
0AB6-   AA          TAX
0AB7-   AA          TAX
0AB8-   AA          TAX
0AB9-   AA          TAX
0ABA-   AA          TAX
0ABB-   AA          TAX
0ABC-   AA          TAX
0ABD-   AA          TAX
0ABE-   AA          TAX
0ABF-   AA          TAX
0AC0-   AA          TAX
0AC1-   AA          TAX
0AC2-   AA          TAX
0AC3-   AA          TAX
0AC4-   AA          TAX
0AC5-   AA          TAX
0AC6-   AA          TAX
0AC7-   AA          TAX
0AC8-   AA          TAX
0AC9-   AA          TAX
0ACA-   AA          TAX
0ACB-   AA          TAX
0ACC-   AA          TAX
0ACD-   AA          TAX
0ACE-   AA          TAX
0ACF-   AA          TAX
0AD0-   8D AA 8D    STA   $8DAA
0AD3-   AA          TAX
0AD4-   AA          TAX
0AD5-   20 C1 D3    JSR   $D3C1
0AD8-   D3          ???
0AD9-   C5 CD       CMP   $CD
0ADB-   C2          ???
0ADC-   CC C5 D2    CPY   $D2C5
0ADF-   20 C4 C9    JSR   $C9C4
0AE2-   D2 C5       CMP   ($C5)
0AE4-   C3          ???
0AE5-   D4          ???
0AE6-   C9 D6       CMP   #$D6
0AE8-   C5 D3       CMP   $D3
0AEA-   8D AA 8D    STA   $8DAA
0AED-   A0 C3       LDY   #$C3
0AEF-   D9 C3 A0    CMP   $A0C3,Y
0AF2-   C1 D6       CMP   ($D6,X)
0AF4-   C5 8D       CMP   $8D
0AF6-   A0 C5       LDY   #$C5
0AF8-   D8          CLD
0AF9-   D0 A0       BNE   $0A9B
0AFB-   CF          ???
0AFC-   CE CC D9    DEC   $D9CC
0AFF-   8D A0 C4    STA   $C4A0
0B02-   D3          ???
0B03-   CB          ???
0B04-   A0 D3       LDY   #$D3
0B06-   D4          ???
0B07-   D2 C9       CMP   ($C9)
0B09-   CE C7 D3    DEC   $D3C7
0B0C-   AE C4 C5    LDX   $C5C4
0B0F-   CD CF 8D    CMP   $8DCF
0B12-   AA          TAX
0B13-   8D AA E0    STA   $E0AA
0B16-   E0 E0       CPX   #$E0
0B18-   E0 E0       CPX   #$E0
0B1A-   E0 E0       CPX   #$E0
0B1C-   E0 E0       CPX   #$E0
0B1E-   E0 E0       CPX   #$E0
0B20-   E0 E0       CPX   #$E0
0B22-   E0 E0       CPX   #$E0
0B24-   E0 E0       CPX   #$E0
0B26-   E0 E0       CPX   #$E0
0B28-   E0 E0       CPX   #$E0
0B2A-   E0 E0       CPX   #$E0
0B2C-   E0 E0       CPX   #$E0
0B2E-   E0 E0       CPX   #$E0
0B30-   E0 E0       CPX   #$E0
0B32-   E0 AA       CPX   #$AA
0B34-   8D AA 20    STA   $20AA
0B37-   20 D4 CF    JSR   $CFD4
0B3A-   D0 20       BNE   $0B5C
0B3C-   C9 CE       CMP   #$CE
0B3E-   C3          ???
0B3F-   CC D5 C4    CPY   $C4D5
0B42-   C5 D3       CMP   $D3
0B44-   20 A8 D0    JSR   $D0A8
0B47-   D5 D4       CMP   $D4,X
0B49-   D3          ???
0B4A-   AC 20 CD    LDY   $CD20
0B4D-   C1 C3       CMP   ($C3,X)
0B4F-   D2 CF       CMP   ($CF)
0B51-   D3          ???
0B52-   A9 20       LDA   #$20
0B54-   AA          TAX
0B55-   8D AA AC    STA   $ACAA
0B58-   AC AC AC    LDY   $ACAC
0B5B-   AC AC AC    LDY   $ACAC
0B5E-   AC AC AC    LDY   $ACAC
0B61-   AC AC AC    LDY   $ACAC
0B64-   AC AC AC    LDY   $ACAC
0B67-   AC AC AC    LDY   $ACAC
0B6A-   AC AC AC    LDY   $ACAC
0B6D-   AC AC AC    LDY   $ACAC
0B70-   AC AC AC    LDY   $ACAC
0B73-   AC AC AA    LDY   $AAAC
0B76-   8D AA 8D    STA   $8DAA
0B79-   A0 D0       LDY   #$D0
0B7B-   D5 D4       CMP   $D4,X
0B7D-   A0 C4       LDY   #$C4
0B7F-   C5 C3       CMP   $C3
0B81-   D3          ???
0B82-   8D A0 D5    STA   $D5A0
0B85-   D3          ???
0B86-   C5 20       CMP   $20
0B88-   D3          ???
0B89-   D4          ???
0B8A-   D2 C9       CMP   ($C9)
0B8C-   CE C7 D3    DEC   $D3C7
0B8F-   AE CD C1    LDX   $C1CD
0B92-   C3          ???
0B93-   8D AA 8D    STA   $8DAA
0B96-   A0 D0       LDY   #$D0
0B98-   D5 D4       CMP   $D4,X
0B9A-   A0 D3       LDY   #$D3
0B9C-   D4          ???
0B9D-   D2 C9       CMP   ($C9)
0B9F-   CE C7 D3    DEC   $D3C7
0BA2-   AE C8 CF    LDX   $CFC8
0BA5-   CF          ???
0BA6-   CB          ???
0BA7-   D3          ???
0BA8-   8D AA 8D    STA   $8DAA
0BAB-   A0 CF       LDY   #$CF
0BAD-   C2          ???
0BAE-   CA          DEX
0BAF-   A0 A4       LDY   #$A4
0BB1-   C2          ???
0BB2-   C6 C5       DEC   $C5
0BB4-   B0 8D       BCS   $0B43
0BB6-   A0 CF       LDY   #$CF
0BB8-   D2 C7       CMP   ($C7)
0BBA-   20 A4 B6    JSR   $B6A4
0BBD-   B0 B0       BCS   $0B6F
0BBF-   B0 8D       BCS   $0B4E
0BC1-   AA          TAX
0BC2-   8D AA E0    STA   $E0AA
0BC5-   E0 E0       CPX   #$E0
0BC7-   E0 E0       CPX   #$E0
0BC9-   E0 E0       CPX   #$E0
0BCB-   E0 E0       CPX   #$E0
0BCD-   E0 E0       CPX   #$E0
0BCF-   E0 E0       CPX   #$E0
0BD1-   E0 E0       CPX   #$E0
0BD3-   E0 E0       CPX   #$E0
0BD5-   E0 E0       CPX   #$E0
0BD7-   E0 E0       CPX   #$E0
0BD9-   E0 E0       CPX   #$E0
0BDB-   E0 E0       CPX   #$E0
0BDD-   E0 E0       CPX   #$E0
0BDF-   E0 E0       CPX   #$E0
0BE1-   E0 AA       CPX   #$AA
0BE3-   8D AA 20    STA   $20AA
0BE6-   20 20 20    JSR   $2020
0BE9-   20 20 D0    JSR   $D020
0BEC-   D2 CF       CMP   ($CF)
0BEE-   C7          ???
0BEF-   D2 C1       CMP   ($C1)
0BF1-   CD 20 CD    CMP   $CD20
0BF4-   C1 C9       CMP   ($C9,X)
0BF6-   CE 20 C2    DEC   $C220
0BF9-   CF          ???
0BFA-   C4 D9       CPY   $D9
0BFC-   20 20 20    JSR   $2020
0BFF-   20 20 20    JSR   $2020
0C02-   20 AA 8D    JSR   $8DAA
0C05-   AA          TAX
0C06-   AC AC AC    LDY   $ACAC
0C09-   AC AC AC    LDY   $ACAC
0C0C-   AC AC AC    LDY   $ACAC
0C0F-   AC AC AC    LDY   $ACAC
0C12-   AC AC AC    LDY   $ACAC
0C15-   AC AC AC    LDY   $ACAC
0C18-   AC AC AC    LDY   $ACAC
0C1B-   AC AC AC    LDY   $ACAC
0C1E-   AC AC AC    LDY   $ACAC
0C21-   AC AC AC    LDY   $ACAC
0C24-   AA          TAX
0C25-   8D AA 8D    STA   $8DAA
0C28-   AA          TAX
0C29-   8D AA 8D    STA   $8DAA
0C2C-   AA          TAX
0C2D-   AA          TAX
0C2E-   20 C2 C9    JSR   $C9C2
0C31-   C7          ???
0C32-   20 CC D5    JSR   $D5CC
0C35-   CD D0 D3    CMP   $D3D0
0C38-   20 AD AD    JSR   $ADAD
0C3B-   20 C8 C9    JSR   $C9C8
0C3E-   C7          ???
0C3F-   C8          INY
0C40-   20 CC C5    JSR   $C5CC
0C43-   D6 C5       DEC   $C5,X
0C45-   CC 20 C3    CPY   $C320
0C48-   CF          ???
0C49-   C4 C5       CPY   $C5
0C4B-   8D AA 8D    STA   $8DAA
0C4E-   AA          TAX
0C4F-   8D AA AA    STA   $AAAA
0C52-   20 D3 D4    JSR   $D4D3
0C55-   D2 C3       CMP   ($C3)
0C57-   CD D0 20    CMP   $20D0
0C5A-   C3          ???
0C5B-   CF          ???
0C5C-   CD D0 C1    CMP   $C1D0
0C5F-   D2 C5       CMP   ($C5)
0C61-   D3          ???
0C62-   20 D4 D7    JSR   $D7D4
0C65-   CF          ???
0C66-   20 D3 D4    JSR   $D4D3
0C69-   D2 C9       CMP   ($C9)
0C6B-   CE C7 D3    DEC   $D3C7
0C6E-   AC 20 D4    LDY   $D420
0C71-   C8          INY
0C72-   C5 CE       CMP   $CE
0C74-   8D AA AA    STA   $AAAA
0C77-   20 D3 C5    JSR   $C5D3
0C7A-   D4          ???
0C7B-   D3          ???
0C7C-   20 D4 C8    JSR   $C8D4
0C7F-   C5 20       CMP   $20
0C81-   D3          ???
0C82-   D4          ???
0C83-   C1 D4       CMP   ($D4,X)
0C85-   D5 D3       CMP   $D3,X
0C87-   20 D2 C5    JSR   $C5D2
0C8A-   C7          ???
0C8B-   C9 D3       CMP   #$D3
0C8D-   D4          ???
0C8E-   C5 D2       CMP   $D2
0C90-   20 C1 D3    JSR   $D3C1
0C93-   20 C6 CF    JSR   $CFC6
0C96-   CC CC CF    CPY   $CFCC
0C99-   D7          ???
0C9A-   D3          ???
0C9B-   BA          TSX
0C9C-   8D AA 8D    STA   $8DAA
0C9F-   AA          TAX
0CA0-   AA          TAX
0CA1-   20 DA BD    JSR   $BDDA
0CA4-   B1 20       LDA   ($20),Y
0CA6-   C9 C6       CMP   #$C6
0CA8-   20 D3 D4    JSR   $D4D3
0CAB-   D2 C9       CMP   ($C9)
0CAD-   CE C7 D3    DEC   $D3C7
0CB0-   20 C1 D2    JSR   $D2C1
0CB3-   C5 20       CMP   $20
0CB5-   C9 C4       CMP   #$C4
0CB7-   C5 CE       CMP   $CE
0CB9-   D4          ???
0CBA-   C9 C3       CMP   #$C3
0CBC-   C1 CC       CMP   ($CC,X)
0CBE-   8D AA AA    STA   $AAAA
0CC1-   20 DA BD    JSR   $BDDA
0CC4-   B0 20       BCS   $0CE6
0CC6-   C9 C6       CMP   #$C6
0CC8-   20 D3 D4    JSR   $D4D3
0CCB-   D2 C9       CMP   ($C9)
0CCD-   CE C7 D3    DEC   $D3C7
0CD0-   20 CE CF    JSR   $CFCE
0CD3-   D4          ???
0CD4-   20 C9 C4    JSR   $C4C9
0CD7-   C5 CE       CMP   $CE
0CD9-   D4          ???
0CDA-   C9 C3       CMP   #$C3
0CDC-   C1 CC       CMP   ($CC,X)
0CDE-   8D AA AA    STA   $AAAA
0CE1-   20 C3 BD    JSR   $BDC3
0CE4-   B1 20       LDA   ($20),Y
0CE6-   C9 C6       CMP   #$C6
0CE8-   20 D3 D4    JSR   $D4D3
0CEB-   D2 C9       CMP   ($C9)
0CED-   CE C7 B2    DEC   $B2C7
0CF0-   20 CC C5    JSR   $C5CC
0CF3-   CE C7 D4    DEC   $D4C7
0CF6-   C8          INY
0CF7-   20 C9 D3    JSR   $D3C9
0CFA-   20 BE 8D    JSR   $8DBE
0CFD-   AA          TAX
0CFE-   AA          TAX
0CFF-   20 C3 BD    JSR   $BDC3
0D02-   B0 20       BCS   $0D24
0D04-   C9 C6       CMP   #$C6
0D06-   20 D3 D4    JSR   $D4D3
0D09-   D2 C9       CMP   ($C9)
0D0B-   CE C7 B1    DEC   $B1C7
0D0E-   20 CC C5    JSR   $C5CC
0D11-   CE C7 D4    DEC   $D4C7
0D14-   C8          INY
0D15-   20 C9 D3    JSR   $D3C9
0D18-   20 BE 8D    JSR   $8DBE
0D1B-   AA          TAX
0D1C-   8D AA AA    STA   $AAAA
0D1F-   20 CD C1    JSR   $C1CD
0D22-   C3          ???
0D23-   D2 CF       CMP   ($CF)
0D25-   BA          TSX
0D26-   8D AA 8D    STA   $8DAA
0D29-   A0 CA       LDY   #$CA
0D2B-   CD D0 A0    CMP   $A0D0
0D2E-   C3          ???
0D2F-   CF          ???
0D30-   CE D4 8D    DEC   $8DD4
0D33-   D3          ???
0D34-   D4          ???
0D35-   D2 B1       CMP   ($B1)
0D37-   A0 D3       LDY   #$D3
0D39-   D4          ???
0D3A-   D2 A0       CMP   ($A0)
0D3C-   A2 D4       LDX   #$D4
0D3E-   C8          INY
0D3F-   C9 DA       CMP   #$DA
0D41-   20 C9 D3    JSR   $D3C9
0D44-   20 D3 D4    JSR   $D4D3
0D47-   D2 C9       CMP   ($C9)
0D49-   CE C7 B1    DEC   $B1C7
0D4C-   A2 8D       LDX   #$8D
0D4E-   D3          ???
0D4F-   D4          ???
0D50-   D2 B2       CMP   ($B2)
0D52-   A0 D3       LDY   #$D3
0D54-   D4          ???
0D55-   D2 A0       CMP   ($A0)
0D57-   A2 D4       LDX   #$D4
0D59-   C8          INY
0D5A-   C9 D3       CMP   #$D3
0D5C-   20 C9 D3    JSR   $D3C9
0D5F-   20 D3 D4    JSR   $D4D3
0D62-   D2 C9       CMP   ($C9)
0D64-   CE C7 20    DEC   $20C7
0D67-   B2 A2       LDA   ($A2)
0D69-   8D C3 CF    STA   $CFC3
0D6C-   CE D4 8D    DEC   $8DD4
0D6F-   A0 CC       LDY   #$CC
0D71-   C4 C1       CPY   $C1
0D73-   A0 A3       LDY   #$A3
0D75-   BE D3 D4    LDX   $D4D3,Y
0D78-   D2 B1       CMP   ($B1)
0D7A-   8D A0 D0    STA   $D0A0
0D7D-   C8          INY
0D7E-   C1 8D       CMP   ($8D,X)
0D80-   A0 CC       LDY   #$CC
0D82-   C4 C1       CPY   $C1
0D84-   A0 A3       LDY   #$A3
0D86-   BC D3 D4    LDY   $D4D3,X
0D89-   D2 B1       CMP   ($B1)
0D8B-   8D A0 D0    STA   $D0A0
0D8E-   C8          INY
0D8F-   C1 8D       CMP   ($8D,X)
0D91-   A0 CC       LDY   #$CC
0D93-   C4 C1       CPY   $C1
0D95-   A0 A3       LDY   #$A3
0D97-   BE D3 D4    LDX   $D4D3,Y
0D9A-   D2 B2       CMP   ($B2)
0D9C-   8D A0 D0    STA   $D0A0
0D9F-   C8          INY
0DA0-   C1 8D       CMP   ($8D,X)
0DA2-   A0 CC       LDY   #$CC
0DA4-   C4 C1       CPY   $C1
0DA6-   A0 A3       LDY   #$A3
0DA8-   BC D3 D4    LDY   $D4D3,X
0DAB-   D2 B2       CMP   ($B2)
0DAD-   8D A0 D0    STA   $D0A0
0DB0-   C8          INY
0DB1-   C1 8D       CMP   ($8D,X)
0DB3-   A0 CA       LDY   #$CA
0DB5-   D3          ???
0DB6-   D2 A0       CMP   ($A0)
0DB8-   D3          ???
0DB9-   D4          ???
0DBA-   D2 C3       CMP   ($C3)
0DBC-   CD D0 8D    CMP   $8DD0
0DBF-   AA          TAX
0DC0-   20 C2 D2    JSR   $D2C2
0DC3-   CB          ???
0DC4-   20 BB 20    JSR   $20BB
0DC7-   D0 20       BNE   $0DE9
0DC9-   BD 20 B3    LDA   $B320,X
0DCC-   B1 20       LDA   ($20),Y
0DCE-   BD 20 B0    LDA   $B020,X
0DD1-   B0 B1       BCS   $0D84
0DD3-   B1 B0       LDA   ($B0),Y
0DD5-   B0 B0       BCS   $0D87
0DD7-   B1 BB       LDA   ($BB),Y
0DD9-   20 DA BD    JSR   $BDDA
0DDC-   B0 AC       BCS   $0D8A
0DDE-   C3          ???
0DDF-   BD B1 8D    LDA   $8DB1,X
0DE2-   AA          TAX
0DE3-   8D AA 8D    STA   $8DAA
0DE6-   AA          TAX
0DE7-   AA          TAX
0DE8-   20 D3 D4    JSR   $D4D3
0DEB-   D2 C3       CMP   ($C3)
0DED-   C1 D4       CMP   ($D4,X)
0DEF-   20 C3 CF    JSR   $CFC3
0DF2-   CE C3 C1    DEC   $C1C3
0DF5-   D4          ???
0DF6-   C5 CE       CMP   $CE
0DF8-   C1 D4       CMP   ($D4,X)
0DFA-   C5 D3       CMP   $D3
0DFC-   20 D4 D7    JSR   $D7D4
0DFF-   CF          ???
0E00-   20 D3 D4    JSR   $D4D3
0E03-   D2 C9       CMP   ($C9)
0E05-   CE C7 D3    DEC   $D3C7
0E08-   20 C1 CE    JSR   $CEC1
0E0B-   C4 20       CPY   $20
0E0D-   D2 C5       CMP   ($C5)
0E0F-   D4          ???
0E10-   D5 D2       CMP   $D2,X
0E12-   CE D3 8D    DEC   $8DD3
0E15-   AA          TAX
0E16-   AA          TAX
0E17-   20 D4 C8    JSR   $C8D4
0E1A-   C5 20       CMP   $20
0E1C-   C3          ???
0E1D-   CF          ???
0E1E-   CE C3 C1    DEC   $C1C3
0E21-   D4          ???
0E22-   C5 CE       CMP   $CE
0E24-   C1 D4       CMP   ($D4,X)
0E26-   C5 C4       CMP   $C4
0E28-   20 D3 D4    JSR   $D4D3
0E2B-   D2 C9       CMP   ($C9)
0E2D-   CE C7 20    DEC   $20C7
0E30-   D7          ???
0E31-   C8          INY
0E32-   C5 D2       CMP   $D2
0E34-   C5 20       CMP   $20
0E36-   D4          ???
0E37-   C8          INY
0E38-   C5 20       CMP   $20
0E3A-   C6 C9       DEC   $C9
0E3C-   D2 D3       CMP   ($D3)
0E3E-   D4          ???
0E3F-   8D AA AA    STA   $AAAA
0E42-   20 D3 D4    JSR   $D4D3
0E45-   D2 C9       CMP   ($C9)
0E47-   CE C7 20    DEC   $20C7
0E4A-   D7          ???
0E4B-   C1 D3       CMP   ($D3,X)
0E4D-   20 D3 D4    JSR   $D4D3
0E50-   CF          ???
0E51-   D2 C5       CMP   ($C5)
0E53-   C4 AE       CPY   $AE
0E55-   8D AA 8D    STA   $8DAA
0E58-   AA          TAX
0E59-   AA          TAX
0E5A-   20 CD C1    JSR   $C1CD
0E5D-   C3          ???
0E5E-   D2 CF       CMP   ($CF)
0E60-   BA          TSX
0E61-   8D AA 8D    STA   $8DAA
0E64-   A0 CA       LDY   #$CA
0E66-   CD D0 A0    CMP   $A0D0
0E69-   C3          ???
0E6A-   C1 D4       CMP   ($D4,X)
0E6C-   C3          ???
0E6D-   CF          ???
0E6E-   CE 8D C3    DEC   $C38D
0E71-   C1 D4       CMP   ($D4,X)
0E73-   D3          ???
0E74-   D4          ???
0E75-   D2 A0       CMP   ($A0)
0E77-   D3          ???
0E78-   D4          ???
0E79-   D2 A0       CMP   ($A0)
0E7B-   A2 C1       LDX   #$C1
0E7D-   C2          ???
0E7E-   C3          ???
0E7F-   A2 8D       LDX   #$8D
0E81-   C2          ???
0E82-   CC C1 CE    CPY   $CEC1
0E85-   CB          ???
0E86-   A0 D3       LDY   #$D3
0E88-   D4          ???
0E89-   D2 A0       CMP   ($A0)
0E8B-   A2 20       LDX   #$20
0E8D-   20 20 A2    JSR   $A220
0E90-   8D C3 C1    STA   $C1C3
0E93-   D4          ???
0E94-   D3          ???
0E95-   D4          ???
0E96-   D2 B2       CMP   ($B2)
0E98-   A0 D3       LDY   #$D3
0E9A-   D4          ???
0E9B-   D2 A0       CMP   ($A0)
0E9D-   A2 C4       LDX   #$C4
0E9F-   C5 C6       CMP   $C6
0EA1-   A2 8D       LDX   #$8D
0EA3-   AA          TAX
0EA4-   8D C3 C1    STA   $C1C3
0EA7-   D4          ???
0EA8-   C3          ???
0EA9-   CF          ???
0EAA-   CE 8D A0    DEC   $A08D
0EAD-   CC C4 C1    CPY   $C1C4
0EB0-   A0 A3       LDY   #$A3
0EB2-   BE C3 C1    LDX   $C1C3,Y
0EB5-   D4          ???
0EB6-   D3          ???
0EB7-   D4          ???
0EB8-   D2 8D       CMP   ($8D)
0EBA-   A0 D0       LDY   #$D0
0EBC-   C8          INY
0EBD-   C1 8D       CMP   ($8D,X)
0EBF-   A0 CC       LDY   #$CC
0EC1-   C4 C1       CPY   $C1
0EC3-   A0 A3       LDY   #$A3
0EC5-   BC C3 C1    LDY   $C1C3,X
0EC8-   D4          ???
0EC9-   D3          ???
0ECA-   D4          ???
0ECB-   D2 8D       CMP   ($8D)
0ECD-   A0 D0       LDY   #$D0
0ECF-   C8          INY
0ED0-   C1 8D       CMP   ($8D,X)
0ED2-   A0 CC       LDY   #$CC
0ED4-   C4 C1       CPY   $C1
0ED6-   A0 A3       LDY   #$A3
0ED8-   BE C3 C1    LDX   $C1C3,Y
0EDB-   D4          ???
0EDC-   D3          ???
0EDD-   D4          ???
0EDE-   D2 B2       CMP   ($B2)
0EE0-   8D A0 D0    STA   $D0A0
0EE3-   C8          INY
0EE4-   C1 8D       CMP   ($8D,X)
0EE6-   A0 CC       LDY   #$CC
0EE8-   C4 C1       CPY   $C1
0EEA-   A0 A3       LDY   #$A3
0EEC-   BC C3 C1    LDY   $C1C3,X
0EEF-   D4          ???
0EF0-   D3          ???
0EF1-   D4          ???
0EF2-   D2 B2       CMP   ($B2)
0EF4-   8D A0 D0    STA   $D0A0
0EF7-   C8          INY
0EF8-   C1 8D       CMP   ($8D,X)
0EFA-   A0 CC       LDY   #$CC
0EFC-   C4 C1       CPY   $C1
0EFE-   A0 A3       LDY   #$A3
0F00-   B7          ???
0F01-   A0 BB       LDY   #$BB
0F03-   20 CD C1    JSR   $C1CD
0F06-   D8          CLD
0F07-   20 D3 C9    JSR   $C9D3
0F0A-   DA          PHX
0F0B-   C5 20       CMP   $20
0F0D-   CF          ???
0F0E-   C6 20       DEC   $20
0F10-   C3          ???
0F11-   C1 D4       CMP   ($D4,X)
0F13-   8D A0 D0    STA   $D0A0
0F16-   C8          INY
0F17-   C1 8D       CMP   ($8D,X)
0F19-   A0 CA       LDY   #$CA
0F1B-   D3          ???
0F1C-   D2 A0       CMP   ($A0)
0F1E-   D3          ???
0F1F-   D4          ???
0F20-   D2 C3       CMP   ($C3)
0F22-   C1 D4       CMP   ($D4,X)
0F24-   8D A0 CC    STA   $CCA0
0F27-   C4 D8       CPY   $D8
0F29-   A0 A3       LDY   #$A3
0F2B-   BE C3 C1    LDX   $C1C3,Y
0F2E-   D4          ???
0F2F-   D3          ???
0F30-   D4          ???
0F31-   D2 8D       CMP   ($8D)
0F33-   A0 CC       LDY   #$CC
0F35-   C4 D9       CPY   $D9
0F37-   A0 A3       LDY   #$A3
0F39-   BC C3 C1    LDY   $C1C3,X
0F3C-   D4          ???
0F3D-   D3          ???
0F3E-   D4          ???
0F3F-   D2 8D       CMP   ($8D)
0F41-   AA          TAX
0F42-   20 C2 D2    JSR   $D2C2
0F45-   CB          ???
0F46-   20 BB 20    JSR   $20BB
0F49-   D8          CLD
0F4A-   AC D9 20    LDY   $20D9
0F4D-   C8          INY
0F4E-   CF          ???
0F4F-   CC C4 D3    CPY   $D3C4
0F52-   20 CC CF    JSR   $CFCC
0F55-   D7          ???
0F56-   20 C1 CE    JSR   $CEC1
0F59-   C4 20       CPY   $20
0F5B-   C8          INY
0F5C-   C9 C7       CMP   #$C7
0F5E-   C8          INY
0F5F-   20 C2 D9    JSR   $D9C2
0F62-   D4          ???
0F63-   C5 D3       CMP   $D3
0F65-   20 CF C6    JSR   $C6CF
0F68-   8D AA 20    STA   $20AA
0F6B-   D4          ???
0F6C-   C8          INY
0F6D-   C5 20       CMP   $20
0F6F-   C1 C4       CMP   ($C4,X)
0F71-   C4 D2       CPY   $D2
0F73-   C5 D3       CMP   $D3
0F75-   D3          ???
0F76-   20 D4 CF    JSR   $CFD4
0F79-   20 D4 C8    JSR   $C8D4
0F7C-   C5 20       CMP   $20
0F7E-   C3          ???
0F7F-   CF          ???
0F80-   CE C3 C1    DEC   $C1C3
0F83-   D4          ???
0F84-   C5 CE       CMP   $CE
0F86-   C1 D4       CMP   ($D4,X)
0F88-   C5 C4       CMP   $C4
0F8A-   20 D3 D4    JSR   $D4D3
0F8D-   D2 C9       CMP   ($C9)
0F8F-   CE C7 AE    DEC   $AEC7
0F92-   8D AA 20    STA   $20AA
0F95-   C9 C6       CMP   #$C6
0F97-   20 D9 CF    JSR   $CFD9
0F9A-   D5 20       CMP   $20,X
0F9C-   CC C9 D3    CPY   $D3C9
0F9F-   D4          ???
0FA0-   20 D4 C8    JSR   $C8D4
0FA3-   C1 D4       CMP   ($D4,X)
0FA5-   20 C1 C4    JSR   $C4C1
0FA8-   C4 D2       CPY   $D2
0FAA-   C5 D3       CMP   $D3
0FAC-   D3          ???
0FAD-   AC 20 D9    LDY   $D920
0FB0-   CF          ???
0FB1-   D5 20       CMP   $20,X
0FB3-   D3          ???
0FB4-   C8          INY
0FB5-   CF          ???
0FB6-   D5 CC       CMP   $CC,X
0FB8-   C4 20       CPY   $20
0FBA-   D3          ???
0FBB-   C5 C5       CMP   $C5
0FBD-   8D AA 20    STA   $20AA
0FC0-   D4          ???
0FC1-   C8          INY
0FC2-   C1 D4       CMP   ($D4,X)
0FC4-   20 D4 C8    JSR   $C8D4
0FC7-   C5 20       CMP   $20
0FC9-   C6 C9       DEC   $C9
0FCB-   D2 D3       CMP   ($D3)
0FCD-   D4          ???
0FCE-   20 CC CF    JSR   $CFCC
0FD1-   C3          ???
0FD2-   C1 D4       CMP   ($D4,X)
0FD4-   C9 CF       CMP   #$CF
0FD6-   CE 20 C8    DEC   $C820
0FD9-   CF          ???
0FDA-   CC C4 D3    CPY   $D3C4
0FDD-   20 D4 C8    JSR   $C8D4
0FE0-   C5 20       CMP   $20
0FE2-   CC C5 CE    CPY   $CEC5
0FE5-   C7          ???
0FE6-   D4          ???
0FE7-   C8          INY
0FE8-   8D AA 20    STA   $20AA
0FEB-   CF          ???
0FEC-   C6 20       DEC   $20
0FEE-   D4          ???
0FEF-   C8          INY
0FF0-   C5 20       CMP   $20
0FF2-   CE C5 D7    DEC   $D7C5
0FF5-   20 D3 D4    JSR   $D4D3
0FF8-   D2 C9       CMP   ($C9)
0FFA-   CE C7 20    DEC   $20C7
0FFD-   A8          TAY
0FFE-   B0 B6       BCS   $0FB6
1000-   A9 AC       LDA   #$AC
1002-   20 C6 CF    JSR   $CFC6
1005-   CC CC CF    CPY   $CFCC
1008-   D7          ???
1009-   C5 C4       CMP   $C4
100B-   20 C2 D9    JSR   $D9C2
100E-   20 D4 C8    JSR   $C8D4
1011-   C5 8D       CMP   $8D
1013-   AA          TAX
1014-   20 C8 C5    JSR   $C5C8
1017-   D8          CLD
1018-   C1 C4       CMP   ($C4,X)
101A-   C5 C3       CMP   $C3
101C-   C9 CD       CMP   #$CD
101E-   C1 CC       CMP   ($CC,X)
1020-   20 C3 CF    JSR   $CFC3
1023-   C4 C5       CPY   $C5
1025-   D3          ???
1026-   20 C6 CF    JSR   $CFC6
1029-   D2 20       CMP   ($20)
102B-   D4          ???
102C-   C8          INY
102D-   C5 20       CMP   $20
102F-   C3          ???
1030-   C8          INY
1031-   C1 D2       CMP   ($D2,X)
1033-   C1 C3       CMP   ($C3,X)
1035-   D4          ???
1036-   C5 D2       CMP   $D2
1038-   D3          ???
1039-   8D AA 20    STA   $20AA
103C-   C1 C2       CMP   ($C2,X)
103E-   C3          ???
103F-   C4 C5       CPY   $C5
1041-   C6 BA       DEC   $BA
1043-   20 C3 B1    JSR   $B1C3
1046-   20 C3 B2    JSR   $B2C3
1049-   20 C3 B3    JSR   $B3C3
104C-   20 C3 B4    JSR   $B4C3
104F-   20 C3 B5    JSR   $B5C3
1052-   20 C3 B6    JSR   $B6C3
1055-   8D AA 8D    STA   $8DAA
1058-   AA          TAX
1059-   8D AA 8D    STA   $8DAA
105C-   AA          TAX
105D-   AA          TAX
105E-   20 D0 D2    JSR   $D2D0
1061-   CE D3 D4    DEC   $D4D3
1064-   D2 20       CMP   ($20)
1066-   D0 D2       BNE   $103A
1068-   C9 CE       CMP   #$CE
106A-   D4          ???
106B-   D3          ???
106C-   20 D4 C8    JSR   $C8D4
106F-   C5 20       CMP   $20
1071-   D3          ???
1072-   D4          ???
1073-   D2 C9       CMP   ($C9)
1075-   CE C7 20    DEC   $20C7
1078-   C1 D4       CMP   ($D4,X)
107A-   20 D4 C8    JSR   $C8D4
107D-   C5 20       CMP   $20
107F-   D3          ???
1080-   D0 C5       BNE   $1047
1082-   C3          ???
1083-   C9 C6       CMP   #$C6
1085-   C9 C5       CMP   #$C5
1087-   C4 8D       CPY   $8D
1089-   AA          TAX
108A-   AA          TAX
108B-   20 CD C5    JSR   $C5CD
108E-   CD CF D2    CMP   $D2CF
1091-   D9 20 C1    CMP   $C120,Y
1094-   C4 C4       CPY   $C4
1096-   D2 C5       CMP   ($C5)
1098-   D3          ???
1099-   D3          ???
109A-   20 D4 CF    JSR   $CFD4
109D-   20 C3 CF    JSR   $CFC3
10A0-   D5 D4       CMP   $D4,X
10A2-   B1 AE       LDA   ($AE),Y
10A4-   8D AA 8D    STA   $8DAA
10A7-   AA          TAX
10A8-   AA          TAX
10A9-   20 CD C1    JSR   $C1CD
10AC-   C3          ???
10AD-   D2 CF       CMP   ($CF)
10AF-   BA          TSX
10B0-   8D AA 8D    STA   $8DAA
10B3-   A0 CC       LDY   #$CC
10B5-   C4 C1       CPY   $C1
10B7-   A0 A3       LDY   #$A3
10B9-   BE C3 C1    LDX   $C1C3,Y
10BC-   D4          ???
10BD-   D3          ???
10BE-   D4          ???
10BF-   D2 A0       CMP   ($A0)
10C1-   BB          ???
10C2-   20 C6 D2    JSR   $D2C6
10C5-   CF          ???
10C6-   CD 20 D0    CMP   $D020
10C9-   D2 C5       CMP   ($C5)
10CB-   D6 C9       DEC   $C9,X
10CD-   CF          ???
10CE-   D5 D3       CMP   $D3,X
10D0-   20 C5 D8    JSR   $D8C5
10D3-   C1 CD       CMP   ($CD,X)
10D5-   D0 CC       BNE   $10A3
10D7-   C5 8D       CMP   $8D
10D9-   A0 D0       LDY   #$D0
10DB-   C8          INY
10DC-   C1 8D       CMP   ($8D,X)
10DE-   A0 CC       LDY   #$CC
10E0-   C4 C1       CPY   $C1
10E2-   A0 A3       LDY   #$A3
10E4-   BC C3 C1    LDY   $C1C3,X
10E7-   D4          ???
10E8-   D3          ???
10E9-   D4          ???
10EA-   D2 8D       CMP   ($8D)
10EC-   A0 D0       LDY   #$D0
10EE-   C8          INY
10EF-   C1 8D       CMP   ($8D,X)
10F1-   A0 CA       LDY   #$CA
10F3-   D3          ???
10F4-   D2 A0       CMP   ($A0)
10F6-   D0 D2       BNE   $10CA
10F8-   CE D3 D4    DEC   $D4D3
10FB-   D2 8D       CMP   ($8D)
10FD-   AA          TAX
10FE-   20 C2 D2    JSR   $D2C2
1101-   CB          ???
1102-   20 BB 20    JSR   $20BB
1105-   D9 CF D5    CMP   $D5CF,Y
1108-   20 D3 C8    JSR   $C8D3
110B-   CF          ???
110C-   D5 CC       CMP   $CC,X
110E-   C4 20       CPY   $20
1110-   D3          ???
1111-   C5 C5       CMP   $C5
1113-   8D AA 20    STA   $20AA
1116-   A2 C1       LDX   #$C1
1118-   C2          ???
1119-   C3          ???
111A-   C4 C5       CPY   $C5
111C-   C6 A2       DEC   $A2
111E-   20 C1 D0    JSR   $D0C1
1121-   D0 C5       BNE   $10E8
1123-   CE C4 C5    DEC   $C5C4
1126-   C4 20       CPY   $20
1128-   D4          ???
1129-   CF          ???
112A-   20 D4 C8    JSR   $C8D4
112D-   C5 20       CMP   $20
112F-   CC C9 CE    CPY   $CEC9
1132-   C5 20       CMP   $20
1134-   D7          ???
1135-   C8          INY
1136-   C5 D2       CMP   $D2
1138-   C5 20       CMP   $20
113A-   D9 CF D5    CMP   $D5CF,Y
113D-   8D AA 20    STA   $20AA
1140-   D4          ???
1141-   D9 D0 C5    CMP   $C5D0,Y
1144-   C4 20       CPY   $20
1146-   A2 C2       LDX   #$C2
1148-   D2 D5       CMP   ($D5)
114A-   CE 20 D3    DEC   $D320
114D-   D4          ???
114E-   D2 C9       CMP   ($C9)
1150-   CE C7 D3    DEC   $D3C7
1153-   AE C4 C5    LDX   $C5C4
1156-   CD CF AE    CMP   $AECF
1159-   A2 20       LDX   #$20
115B-   D5 D3       CMP   $D3,X
115D-   C5 20       CMP   $20
115F-   D2 CF       CMP   ($CF)
1161-   D5 D4       CMP   $D4,X
1163-   C9 CE       CMP   #$CE
1165-   C5 D3       CMP   $D3
1167-   20 C6 D2    JSR   $D2C6
116A-   CF          ???
116B-   CD 8D AA    CMP   $AA8D
116E-   20 D3 D4    JSR   $D4D3
1171-   C4 C9       CPY   $C9
1173-   CF          ???
1174-   20 C6 CF    JSR   $CFC6
1177-   D2 20       CMP   ($20)
1179-   D0 CC       BNE   $1147
117B-   C1 C3       CMP   ($C3,X)
117D-   C5 CD       CMP   $CD
117F-   C5 CE       CMP   $CE
1181-   D4          ???
1182-   20 CF C6    JSR   $C6CF
1185-   20 D4 C8    JSR   $C8D4
1188-   C5 20       CMP   $20
118A-   D4          ???
118B-   C5 D8       CMP   $D8
118D-   D4          ???
118E-   AE 8D AA    LDX   $AA8D
1191-   8D AA 8D    STA   $8DAA
1194-   AA          TAX
1195-   8D AA 8D    STA   $8DAA
1198-   A0 CA       LDY   #$CA
119A-   CD D0 A0    CMP   $A0D0
119D-   CE D5 CD    DEC   $CDD5
11A0-   D3          ???
11A1-   D4          ???
11A2-   D2 D8       CMP   ($D8)
11A4-   8D CE D5    STA   $D5CE
11A7-   CD D3 D4    CMP   $D4D3
11AA-   D2 A0       CMP   ($A0)
11AC-   C8          INY
11AD-   C5 D8       CMP   $D8
11AF-   A0 B2       LDY   #$B2
11B1-   C2          ???
11B2-   B6 B7       LDX   $B7,Y
11B4-   A0 BB       LDY   #$BB
11B6-   B1 B1       LDA   ($B1),Y
11B8-   B1 B1       LDA   ($B1),Y
11BA-   B1 8D       LDA   ($8D),Y
11BC-   CE D5 CD    DEC   $CDD5
11BF-   D3          ???
11C0-   D4          ???
11C1-   D2 D8       CMP   ($D8)
11C3-   8D AA 8D    STA   $8DAA
11C6-   A0 CC       LDY   #$CC
11C8-   C4 C1       CPY   $C1
11CA-   A0 A3       LDY   #$A3
11CC-   BE A4 B3    LDX   $B3A4,Y
11CF-   B0 B0       BCS   $1181
11D1-   A0 BB       LDY   #$BB
11D3-   20 C4 C5    JSR   $C5C4
11D6-   D3          ???
11D7-   D4          ???
11D8-   C9 CE       CMP   #$CE
11DA-   C1 D4       CMP   ($D4,X)
11DC-   C9 CF       CMP   #$CF
11DE-   CE 8D A0    DEC   $A08D
11E1-   D0 C8       BNE   $11AB
11E3-   C1 8D       CMP   ($8D,X)
11E5-   A0 CC       LDY   #$CC
11E7-   C4 C1       CPY   $C1
11E9-   A0 A3       LDY   #$A3
11EB-   BC A4 B3    LDY   $B3A4,X
11EE-   B0 B0       BCS   $11A0
11F0-   8D A0 D0    STA   $D0A0
11F3-   C8          INY
11F4-   C1 8D       CMP   ($8D,X)
11F6-   A0 CC       LDY   #$CC
11F8-   C4 C1       CPY   $C1
11FA-   A0 A3       LDY   #$A3
11FC-   BE B1 B1    LDX   $B1B1,Y
11FF-   B1 B1       LDA   ($B1),Y
1201-   B1 A0       LDA   ($A0),Y
1203-   BB          ???
1204-   20 D6 C1    JSR   $C1D6
1207-   CC D5 C5    CPY   $C5D5
120A-   20 D4 CF    JSR   $CFD4
120D-   20 C3 CF    JSR   $CFC3
1210-   CE D6 C5    DEC   $C5D6
1213-   D2 D4       CMP   ($D4)
1215-   8D A0 D0    STA   $D0A0
1218-   C8          INY
1219-   C1 8D       CMP   ($8D,X)
121B-   A0 CC       LDY   #$CC
121D-   C4 C1       CPY   $C1
121F-   A0 A3       LDY   #$A3
1221-   BC B1 B1    LDY   $B1B1,X
1224-   B1 B1       LDA   ($B1),Y
1226-   B1 8D       LDA   ($8D),Y
1228-   A0 D0       LDY   #$D0
122A-   C8          INY
122B-   C1 8D       CMP   ($8D,X)
122D-   A0 CA       LDY   #$CA
122F-   D3          ???
1230-   D2 A0       CMP   ($A0)
1232-   CE D5 CD    DEC   $CDD5
1235-   B2 D3       LDA   ($D3)
1237-   D4          ???
1238-   D2 8D       CMP   ($8D)
123A-   AA          TAX
123B-   C2          ???
123C-   D2 CB       CMP   ($CB)
123E-   8D AA 8D    STA   $8DAA
1241-   AA          TAX
1242-   20 A4 B3    JSR   $B3A4
1245-   B0 B0       BCS   $11F7
1247-   20 D3 C8    JSR   $C8D3
124A-   CF          ???
124B-   D5 CC       CMP   $CC,X
124D-   C4 20       CPY   $20
124F-   CE CF D7    DEC   $D7CF
1252-   20 C8 CF    JSR   $CFC8
1255-   CC C4 20    CPY   $20C4
1258-   B0 B5       BCS   $120F
125A-   AC C2 B1    LDY   $B1C2
125D-   AC C2 B1    LDY   $B1C2
1260-   AC C2 B1    LDY   $B1C2
1263-   AC C2 B1    LDY   $B1C2
1266-   AC C2 B1    LDY   $B1C2
1269-   8D AA 8D    STA   $8DAA
126C-   AA          TAX
126D-   8D AA 8D    STA   $8DAA
1270-   AA          TAX
1271-   AA          TAX
1272-   20 D3 D4    JSR   $D4D3
1275-   D2 B2       CMP   ($B2)
1277-   CE D5 CD    DEC   $CDD5
127A-   20 C4 CF    JSR   $CFC4
127D-   C5 D3       CMP   $D3
127F-   20 D4 C8    JSR   $C8D4
1282-   C5 20       CMP   $20
1284-   CF          ???
1285-   D0 D0       BNE   $1257
1287-   CF          ???
1288-   D3          ???
1289-   C9 D4       CMP   #$D4
128B-   C5 20       CMP   $20
128D-   CF          ???
128E-   C6 20       DEC   $20
1290-   CE D5 CD    DEC   $CDD5
1293-   B2 D3       LDA   ($D3)
1295-   D4          ???
1296-   D2 BA       CMP   ($BA)
1298-   20 C9 D4    JSR   $D4C9
129B-   8D AA AA    STA   $AAAA
129E-   20 D2 C5    JSR   $C5D2
12A1-   D4          ???
12A2-   D5 D2       CMP   $D2,X
12A4-   CE D3 20    DEC   $20D3
12A7-   D4          ???
12A8-   C8          INY
12A9-   C5 20       CMP   $20
12AB-   CE D5 CD    DEC   $CDD5
12AE-   C2          ???
12AF-   C5 D2       CMP   $D2
12B1-   20 C5 D1    JSR   $D1C5
12B4-   D5 C9       CMP   $C9,X
12B6-   D6 C1       DEC   $C1,X
12B8-   CC C5 CE    CPY   $CEC5
12BB-   D4          ???
12BC-   20 CF C6    JSR   $C6CF
12BF-   20 C1 20    JSR   $20C1
12C2-   D3          ???
12C3-   D4          ???
12C4-   D2 C9       CMP   ($C9)
12C6-   CE C7 8D    DEC   $8DC7
12C9-   AA          TAX
12CA-   AA          TAX
12CB-   20 C1 CE    JSR   $CEC1
12CE-   C4 20       CPY   $20
12D0-   C8          INY
12D1-   CF          ???
12D2-   CC C4 D3    CPY   $D3C4
12D5-   20 D4 C8    JSR   $C8D4
12D8-   C5 CD       CMP   $CD
12DA-   20 C9 CE    JSR   $CEC9
12DD-   20 D8 20    JSR   $20D8
12E0-   A8          TAY
12E1-   C8          INY
12E2-   C9 C7       CMP   #$C7
12E4-   C8          INY
12E5-   A9 20       LDA   #$20
12E7-   C1 CE       CMP   ($CE,X)
12E9-   C4 20       CPY   $20
12EB-   D9 20 A8    CMP   $A820,Y
12EE-   CC CF D7    CPY   $D7CF
12F1-   A9 8D       LDA   #$8D
12F3-   AA          TAX
12F4-   8D A0 CC    STA   $CCA0
12F7-   C4 C1       CPY   $C1
12F9-   A0 A3       LDY   #$A3
12FB-   BE A4 B3    LDX   $B3A4,Y
12FE-   B0 B0       BCS   $12B0
1300-   A0 BB       LDY   #$BB
1302-   20 D3 D4    JSR   $D4D3
1305-   D2 C9       CMP   ($C9)
1307-   CE C7 20    DEC   $20C7
130A-   C6 D2       DEC   $D2
130C-   CF          ???
130D-   CD 20 D0    CMP   $D020
1310-   D2 C5       CMP   ($C5)
1312-   D6 C9       DEC   $C9,X
1314-   CF          ???
1315-   D5 D3       CMP   $D3,X
1317-   8D A0 D0    STA   $D0A0
131A-   C8          INY
131B-   C1 8D       CMP   ($8D,X)
131D-   A0 CC       LDY   #$CC
131F-   C4 C1       CPY   $C1
1321-   A0 A3       LDY   #$A3
1323-   BC A4 B3    LDY   $B3A4,X
1326-   B0 B0       BCS   $12D8
1328-   8D A0 D0    STA   $D0A0
132B-   C8          INY
132C-   C1 8D       CMP   ($8D,X)
132E-   A0 CA       LDY   #$CA
1330-   D3          ???
1331-   D2 A0       CMP   ($A0)
1333-   D3          ???
1334-   D4          ???
1335-   D2 B2       CMP   ($B2)
1337-   CE D5 CD    DEC   $CDD5
133A-   8D AA C2    STA   $C2AA
133D-   D2 CB       CMP   ($CB)
133F-   20 BB 20    JSR   $20BB
1342-   D8          CLD
1343-   AC D9 20    LDY   $20D9
1346-   C8          INY
1347-   CF          ???
1348-   CC C4 D3    CPY   $D3C4
134B-   20 B2 C2    JSR   $C2B2
134E-   B6 B7       LDX   $B7,Y
1350-   AC 20 A3    LDY   $A320
1353-   B1 B1       LDA   ($B1),Y
1355-   B1 B1       LDA   ($B1),Y
1357-   B1 8D       LDA   ($8D),Y
1359-   AA          TAX
135A-   8D AA 8D    STA   $8DAA
135D-   AA          TAX
135E-   AA          TAX
135F-   20 D3 D5    JSR   $D5D3
1362-   C2          ???
1363-   D0 CF       BNE   $1334
1365-   D3          ???
1366-   20 D2 C5    JSR   $C5D2
1369-   D4          ???
136A-   D5 D2       CMP   $D2,X
136C-   CE D3 20    DEC   $20D3
136F-   D4          ???
1370-   C8          INY
1371-   C5 20       CMP   $20
1373-   D0 CF       BNE   $1344
1375-   D3          ???
1376-   C9 D4       CMP   #$D4
1378-   C9 CF       CMP   #$CF
137A-   CE 20 CF    DEC   $CF20
137D-   C6 20       DEC   $20
137F-   C1 20       CMP   ($20,X)
1381-   D3          ???
1382-   D5 C2       CMP   $C2,X
1384-   D3          ???
1385-   D4          ???
1386-   D2 C9       CMP   ($C9)
1388-   CE C7 8D    DEC   $8DC7
138B-   AA          TAX
138C-   AA          TAX
138D-   20 D7 C9    JSR   $C9D7
1390-   D4          ???
1391-   C8          INY
1392-   C9 CE       CMP   #$CE
1394-   20 C1 20    JSR   $20C1
1397-   D0 C1       BNE   $135A
1399-   D2 C5       CMP   ($C5)
139B-   CE D4 20    DEC   $20D4
139E-   D3          ???
139F-   D4          ???
13A0-   D2 C9       CMP   ($C9)
13A2-   CE C7 AE    DEC   $AEC7
13A5-   8D AA 8D    STA   $8DAA
13A8-   A0 CC       LDY   #$CC
13AA-   C4 C1       CPY   $C1
13AC-   A0 A3       LDY   #$A3
13AE-   BE D3 D4    LDX   $D4D3,Y
13B1-   D2 A0       CMP   ($A0)
13B3-   BB          ???
13B4-   20 D3 D4    JSR   $D4D3
13B7-   D2 C9       CMP   ($C9)
13B9-   CE C7 20    DEC   $20C7
13BC-   C1 C4       CMP   ($C4,X)
13BE-   C4 D2       CPY   $D2
13C0-   C5 D3       CMP   $D3
13C2-   D3          ???
13C3-   8D A0 D0    STA   $D0A0
13C6-   C8          INY
13C7-   C1 8D       CMP   ($8D,X)
13C9-   A0 CC       LDY   #$CC
13CB-   C4 C1       CPY   $C1
13CD-   A0 A3       LDY   #$A3
13CF-   BC D3 D4    LDY   $D4D3,X
13D2-   D2 8D       CMP   ($8D)
13D4-   A0 D0       LDY   #$D0
13D6-   C8          INY
13D7-   C1 8D       CMP   ($8D,X)
13D9-   A0 CC       LDY   #$CC
13DB-   C4 C1       CPY   $C1
13DD-   A0 A3       LDY   #$A3
13DF-   BE D3 D5    LDX   $D5D3,Y
13E2-   C2          ???
13E3-   A0 BB       LDY   #$BB
13E5-   20 D3 D5    JSR   $D5D3
13E8-   C2          ???
13E9-   D3          ???
13EA-   D4          ???
13EB-   D2 C9       CMP   ($C9)
13ED-   CE C7 20    DEC   $20C7
13F0-   C1 C4       CMP   ($C4,X)
13F2-   C4 D2       CPY   $D2
13F4-   C5 D3       CMP   $D3
13F6-   D3          ???
13F7-   8D A0 D0    STA   $D0A0
13FA-   C8          INY
13FB-   C1 8D       CMP   ($8D,X)
13FD-   A0 CC       LDY   #$CC
13FF-   C4 C1       CPY   $C1
1401-   A0 A3       LDY   #$A3
1403-   BC D3 D5    LDY   $D5D3,X
1406-   C2          ???
1407-   8D A0 D0    STA   $D0A0
140A-   C8          INY
140B-   C1 8D       CMP   ($8D,X)
140D-   A0 CA       LDY   #$CA
140F-   D3          ???
1410-   D2 A0       CMP   ($A0)
1412-   D3          ???
1413-   D5 C2       CMP   $C2,X
1415-   D0 CF       BNE   $13E6
1417-   D3          ???
1418-   8D A0 CA    STA   $CAA0
141B-   CD D0 A0    CMP   $A0D0
141E-   D3          ???
141F-   D5 C2       CMP   $C2,X
1421-   D0 CF       BNE   $13F2
1423-   D3          ???
1424-   D8          CLD
1425-   8D D3 D4    STA   $D4D3
1428-   D2 A0       CMP   ($A0)
142A-   D3          ???
142B-   D4          ???
142C-   D2 A0       CMP   ($A0)
142E-   A2 D4       LDX   #$D4
1430-   C8          INY
1431-   C9 D3       CMP   #$D3
1433-   20 C9 D3    JSR   $D3C9
1436-   20 C1 20    JSR   $20C1
1439-   D4          ???
143A-   C5 D3       CMP   $D3
143C-   D4          ???
143D-   A2 8D       LDX   #$8D
143F-   D3          ???
1440-   D5 C2       CMP   $C2,X
1442-   A0 D3       LDY   #$D3
1444-   D4          ???
1445-   D2 A0       CMP   ($A0)
1447-   A2 C9       LDX   #$C9
1449-   D3          ???
144A-   20 C1 20    JSR   $20C1
144D-   D4          ???
144E-   C5 D3       CMP   $D3
1450-   D4          ???
1451-   A2 8D       LDX   #$8D
1453-   D3          ???
1454-   D5 C2       CMP   $C2,X
1456-   D0 CF       BNE   $1427
1458-   D3          ???
1459-   D8          CLD
145A-   8D AA C2    STA   $C2AA
145D-   D2 CB       CMP   ($CB)
145F-   20 BB 20    JSR   $20BB
1462-   C1 20       CMP   ($20,X)
1464-   BD 20 B0    LDA   $B020,X
1467-   B6 8D       LDX   $8D,Y
1469-   AA          TAX
146A-   8D AA 8D    STA   $8DAA
146D-   AA          TAX
146E-   AA          TAX
146F-   20 D3 D5    JSR   $D5D3
1472-   C2          ???
1473-   C3          ???
1474-   CF          ???
1475-   D0 D9       BNE   $1450
1477-   20 C3 CF    JSR   $CFC3
147A-   D0 C9       BNE   $1445
147C-   C5 D3       CMP   $D3
147E-   20 C1 20    JSR   $20C1
1481-   D3          ???
1482-   D5 C2       CMP   $C2,X
1484-   D3          ???
1485-   D4          ???
1486-   D2 C9       CMP   ($C9)
1488-   CE C7 20    DEC   $20C7
148B-   C1 D4       CMP   ($D4,X)
148D-   20 D4 C8    JSR   $C8D4
1490-   C5 20       CMP   $20
1492-   D3          ???
1493-   D0 C5       BNE   $145A
1495-   C3          ???
1496-   C9 C6       CMP   #$C6
1498-   C9 C5       CMP   #$C5
149A-   C4 8D       CPY   $8D
149C-   AA          TAX
149D-   AA          TAX
149E-   20 D0 CF    JSR   $CFD0
14A1-   D3          ???
14A2-   C9 D4       CMP   #$D4
14A4-   C9 CF       CMP   #$CF
14A6-   CE 20 D4    DEC   $D420
14A9-   CF          ???
14AA-   20 C1 20    JSR   $20C1
14AD-   D0 C1       BNE   $1470
14AF-   D2 D4       CMP   ($D4)
14B1-   C9 C3       CMP   #$C3
14B3-   D5 CC       CMP   $CC,X
14B5-   C1 D2       CMP   ($D2,X)
14B7-   20 CD C5    JSR   $C5CD
14BA-   CD CF D2    CMP   $D2CF
14BD-   D9 20 C1    CMP   $C120,Y
14C0-   C4 C4       CPY   $C4
14C2-   D2 C5       CMP   ($C5)
14C4-   D3          ???
14C5-   D3          ???
14C6-   8D AA 8D    STA   $8DAA
14C9-   A0 CC       LDY   #$CC
14CB-   C4 C1       CPY   $C1
14CD-   A0 A3       LDY   #$A3
14CF-   BE D3 D4    LDX   $D4D3,Y
14D2-   D2 B1       CMP   ($B1)
14D4-   B1 A0       LDA   ($A0),Y
14D6-   BB          ???
14D7-   20 D3 CF    JSR   $CFD3
14DA-   D5 D2       CMP   $D2,X
14DC-   C3          ???
14DD-   C5 20       CMP   $20
14DF-   D3          ???
14E0-   D4          ???
14E1-   D2 C9       CMP   ($C9)
14E3-   CE C7 8D    DEC   $8DC7
14E6-   A0 D0       LDY   #$D0
14E8-   C8          INY
14E9-   C1 8D       CMP   ($8D,X)
14EB-   A0 CC       LDY   #$CC
14ED-   C4 C1       CPY   $C1
14EF-   A0 A3       LDY   #$A3
14F1-   BC D3 D4    LDY   $D4D3,X
14F4-   D2 B1       CMP   ($B1)
14F6-   B1 8D       LDA   ($8D),Y
14F8-   A0 D0       LDY   #$D0
14FA-   C8          INY
14FB-   C1 8D       CMP   ($8D,X)
14FD-   A0 CC       LDY   #$CC
14FF-   C4 C1       CPY   $C1
1501-   A0 A3       LDY   #$A3
1503-   B5 A0       LDA   $A0,X
1505-   BB          ???
1506-   20 C9 CE    JSR   $CEC9
1509-   C4 C5       CPY   $C5
150B-   D8          CLD
150C-   20 D4 CF    JSR   $CFD4
150F-   20 D3 D4    JSR   $D4D3
1512-   C1 D2       CMP   ($D2,X)
1514-   D4          ???
1515-   20 C3 CF    JSR   $CFC3
1518-   D0 D9       BNE   $14F3
151A-   8D A0 D0    STA   $D0A0
151D-   C8          INY
151E-   C1 8D       CMP   ($8D,X)
1520-   A0 CC       LDY   #$CC
1522-   C4 C1       CPY   $C1
1524-   A0 A3       LDY   #$A3
1526-   B5 A0       LDA   $A0,X
1528-   BB          ???
1529-   20 CC C5    JSR   $C5CC
152C-   CE C7 D4    DEC   $D4C7
152F-   C8          INY
1530-   20 D4 CF    JSR   $CFD4
1533-   20 C3 CF    JSR   $CFC3
1536-   D0 D9       BNE   $1511
1538-   8D A0 D0    STA   $D0A0
153B-   C8          INY
153C-   C1 8D       CMP   ($8D,X)
153E-   A0 CC       LDY   #$CC
1540-   C4 C1       CPY   $C1
1542-   A0 A3       LDY   #$A3
1544-   BE D3 D4    LDX   $D4D3,Y
1547-   D2 B2       CMP   ($B2)
1549-   B1 8D       LDA   ($8D),Y
154B-   A0 D0       LDY   #$D0
154D-   C8          INY
154E-   C1 8D       CMP   ($8D,X)
1550-   A0 CC       LDY   #$CC
1552-   C4 C1       CPY   $C1
1554-   A0 A3       LDY   #$A3
1556-   BC D3 D4    LDY   $D4D3,X
1559-   D2 B2       CMP   ($B2)
155B-   B1 8D       LDA   ($8D),Y
155D-   A0 D0       LDY   #$D0
155F-   C8          INY
1560-   C1 8D       CMP   ($8D,X)
1562-   A0 CC       LDY   #$CC
1564-   C4 C1       CPY   $C1
1566-   A0 A3       LDY   #$A3
1568-   B1 B5       LDA   ($B5),Y
156A-   A0 BB       LDY   #$BB
156C-   20 CD C1    JSR   $C1CD
156F-   D8          CLD
1570-   20 CC C5    JSR   $C5CC
1573-   CE C7 D4    DEC   $D4C7
1576-   C8          INY
1577-   20 CF C6    JSR   $C6CF
157A-   20 D3 D4    JSR   $D4D3
157D-   D2 C9       CMP   ($C9)
157F-   CE C7 20    DEC   $20C7
1582-   B2 8D       LDA   ($8D)
1584-   A0 D0       LDY   #$D0
1586-   C8          INY
1587-   C1 8D       CMP   ($8D,X)
1589-   A0 CA       LDY   #$CA
158B-   D3          ???
158C-   D2 A0       CMP   ($A0)
158E-   D3          ???
158F-   D5 C2       CMP   $C2,X
1591-   C3          ???
1592-   CF          ???
1593-   D0 D9       BNE   $156E
1595-   8D A0 CA    STA   $CAA0
1598-   CD D0 A0    CMP   $A0D0
159B-   D3          ???
159C-   D4          ???
159D-   D2 C3       CMP   ($C3)
159F-   CF          ???
15A0-   D0 D9       BNE   $157B
15A2-   D8          CLD
15A3-   8D D3 D4    STA   $D4D3
15A6-   D2 B1       CMP   ($B1)
15A8-   B1 A0       LDA   ($A0),Y
15AA-   D3          ???
15AB-   D4          ???
15AC-   D2 A0       CMP   ($A0)
15AE-   A2 B0       LDX   #$B0
15B0-   B1 B2       LDA   ($B2),Y
15B2-   B3          ???
15B3-   B4 B5       LDY   $B5,X
15B5-   B6 B7       LDX   $B7,Y
15B7-   B8          CLV
15B8-   B9 B0 B1    LDA   $B1B0,Y
15BB-   B2 B3       LDA   ($B3)
15BD-   B4 B5       LDY   $B5,X
15BF-   A2 8D       LDX   #$8D
15C1-   D3          ???
15C2-   D4          ???
15C3-   D2 B2       CMP   ($B2)
15C5-   B1 A0       LDA   ($A0),Y
15C7-   D3          ???
15C8-   D4          ???
15C9-   D2 A0       CMP   ($A0)
15CB-   A2 B0       LDX   #$B0
15CD-   B0 B0       BCS   $157F
15CF-   B0 B0       BCS   $1581
15D1-   B0 B0       BCS   $1583
15D3-   B0 B0       BCS   $1585
15D5-   B0 B0       BCS   $1587
15D7-   B0 B0       BCS   $1589
15D9-   B0 B0       BCS   $158B
15DB-   B0 B0       BCS   $158D
15DD-   B0 A2       BCS   $1581
15DF-   8D D3 D4    STA   $D4D3
15E2-   D2 C3       CMP   ($C3)
15E4-   CF          ???
15E5-   D0 D9       BNE   $15C0
15E7-   D8          CLD
15E8-   8D A0 CC    STA   $CCA0
15EB-   C4 D8       CPY   $D8
15ED-   A0 A3       LDY   #$A3
15EF-   BE D3 D4    LDX   $D4D3,Y
15F2-   D2 B2       CMP   ($B2)
15F4-   B1 8D       LDA   ($8D),Y
15F6-   A0 CC       LDY   #$CC
15F8-   C4 D9       CPY   $D9
15FA-   A0 A3       LDY   #$A3
15FC-   BC D3 D4    LDY   $D4D3,X
15FF-   D2 B2       CMP   ($B2)
1601-   B1 A0       LDA   ($A0),Y
1603-   BB          ???
1604-   20 C1 C4    JSR   $C4C1
1607-   C4 D2       CPY   $D2
1609-   C5 D3       CMP   $D3
160B-   D3          ???
160C-   20 CF C6    JSR   $C6CF
160F-   20 D3 D4    JSR   $D4D3
1612-   D2 B2       CMP   ($B2)
1614-   8D AA C2    STA   $C2AA
1617-   D2 CB       CMP   ($CB)
1619-   20 BB 20    JSR   $20BB
161C-   CC CF C3    CPY   $C3CF
161F-   C1 D4       CMP   ($D4,X)
1621-   C9 CF       CMP   #$CF
1623-   CE 20 C6    DEC   $C620
1626-   CF          ???
1627-   D2 20       CMP   ($20)
1629-   D3          ???
162A-   D4          ???
162B-   D2 B2       CMP   ($B2)
162D-   B1 20       LDA   ($20),Y
162F-   D3          ???
1630-   C8          INY
1631-   CF          ???
1632-   D5 CC       CMP   $CC,X
1634-   C4 20       CPY   $20
1636-   CE CF D7    DEC   $D7CF
1639-   20 D3 D4    JSR   $D4D3
163C-   C1 D2       CMP   ($D2,X)
163E-   D4          ???
163F-   20 D7 C9    JSR   $C9D7
1642-   D4          ???
1643-   C8          INY
1644-   8D AA 20    STA   $20AA
1647-   B4 AC       LDY   $AC,X
1649-   B5 AC       LDA   $AC,X
164B-   B6 AC       LDX   $AC,Y
164D-   B7          ???
164E-   AC B8 8D    LDY   $8DB8
1651-   AA          TAX
1652-   8D AA 8D    STA   $8DAA
1655-   AA          TAX
1656-   AA          TAX
1657-   20 D3 D5    JSR   $D5D3
165A-   C2          ???
165B-   C4 C5       CPY   $C5
165D-   CC 20 C4    CPY   $C420
1660-   C5 CC       CMP   $CC
1662-   C5 D4       CMP   $D4
1664-   C5 D3       CMP   $D3
1666-   20 C1 20    JSR   $20C1
1669-   D3          ???
166A-   D5 C2       CMP   $C2,X
166C-   D3          ???
166D-   D4          ???
166E-   D2 C9       CMP   ($C9)
1670-   CE C7 20    DEC   $20C7
1673-   C6 D2       DEC   $D2
1675-   CF          ???
1676-   CD 20 C1    CMP   $C120
1679-   20 C7 C9    JSR   $C9C7
167C-   D6 C5       DEC   $C5,X
167E-   CE 20 D3    DEC   $D320
1681-   D4          ???
1682-   D2 C9       CMP   ($C9)
1684-   CE C7 8D    DEC   $8DC7
1687-   AA          TAX
1688-   AA          TAX
1689-   20 C1 CE    JSR   $CEC1
168C-   C4 20       CPY   $20
168E-   C3          ???
168F-   C8          INY
1690-   C1 CE       CMP   ($CE,X)
1692-   C7          ???
1693-   C5 D3       CMP   $D3
1695-   20 D4 C8    JSR   $C8D4
1698-   C5 20       CMP   $20
169A-   D3          ???
169B-   D4          ???
169C-   D2 C9       CMP   ($C9)
169E-   CE C7 20    DEC   $20C7
16A1-   D3          ???
16A2-   C9 DA       CMP   #$DA
16A4-   C5 20       CMP   $20
16A6-   C1 C3       CMP   ($C3,X)
16A8-   C3          ???
16A9-   CF          ???
16AA-   D2 C4       CMP   ($C4)
16AC-   C9 CE       CMP   #$CE
16AE-   C7          ???
16AF-   CC D9 AE    CPY   $AED9
16B2-   8D AA AA    STA   $AAAA
16B5-   20 CD C9    JSR   $C9CD
16B8-   CE 20 D0    DEC   $D020
16BB-   CF          ???
16BC-   D3          ???
16BD-   C9 D4       CMP   #$D4
16BF-   C9 CF       CMP   #$CF
16C1-   CE 20 C9    DEC   $C920
16C4-   D3          ???
16C5-   20 B1 AC    JSR   $ACB1
16C8-   20 CE CF    JSR   $CFCE
16CB-   D4          ???
16CC-   20 B0 8D    JSR   $8DB0
16CF-   AA          TAX
16D0-   8D A0 CC    STA   $CCA0
16D3-   C4 C1       CPY   $C1
16D5-   A0 A3       LDY   #$A3
16D7-   BE D3 D4    LDX   $D4D3,Y
16DA-   D2 B1       CMP   ($B1)
16DC-   B1 A0       LDA   ($A0),Y
16DE-   BB          ???
16DF-   20 D3 D4    JSR   $D4D3
16E2-   D2 C9       CMP   ($C9)
16E4-   CE C7 20    DEC   $20C7
16E7-   CC CF C3    CPY   $C3CF
16EA-   C1 D4       CMP   ($D4,X)
16EC-   C9 CF       CMP   #$CF
16EE-   CE 8D A0    DEC   $A08D
16F1-   D0 C8       BNE   $16BB
16F3-   C1 8D       CMP   ($8D,X)
16F5-   A0 CC       LDY   #$CC
16F7-   C4 C1       CPY   $C1
16F9-   A0 A3       LDY   #$A3
16FB-   BC D3 D4    LDY   $D4D3,X
16FE-   D2 B1       CMP   ($B1)
1700-   B1 8D       LDA   ($8D),Y
1702-   A0 D0       LDY   #$D0
1704-   C8          INY
1705-   C1 8D       CMP   ($8D,X)
1707-   A0 CC       LDY   #$CC
1709-   C4 C1       CPY   $C1
170B-   A0 A3       LDY   #$A3
170D-   B1 A0       LDA   ($A0),Y
170F-   BB          ???
1710-   20 D3 D4    JSR   $D4D3
1713-   C1 D2       CMP   ($D2,X)
1715-   D4          ???
1716-   C9 CE       CMP   #$CE
1718-   C7          ???
1719-   20 C9 CE    JSR   $CEC9
171C-   C4 C5       CPY   $C5
171E-   D8          CLD
171F-   20 C6 CF    JSR   $CFC6
1722-   D2 20       CMP   ($20)
1724-   C4 C5       CPY   $C5
1726-   CC C5 D4    CPY   $D4C5
1729-   C5 8D       CMP   $8D
172B-   A0 D0       LDY   #$D0
172D-   C8          INY
172E-   C1 8D       CMP   ($8D,X)
1730-   A0 CC       LDY   #$CC
1732-   C4 C1       CPY   $C1
1734-   A0 A3       LDY   #$A3
1736-   B5 A0       LDA   $A0,X
1738-   BB          ???
1739-   20 CC C5    JSR   $C5CC
173C-   CE C7 D4    DEC   $D4C7
173F-   C8          INY
1740-   20 D4 CF    JSR   $CFD4
1743-   20 C4 C5    JSR   $C5C4
1746-   CC C5 D4    CPY   $D4C5
1749-   C5 8D       CMP   $8D
174B-   A0 D0       LDY   #$D0
174D-   C8          INY
174E-   C1 8D       CMP   ($8D,X)
1750-   A0 CA       LDY   #$CA
1752-   D3          ???
1753-   D2 A0       CMP   ($A0)
1755-   D3          ???
1756-   D5 C2       CMP   $C2,X
1758-   C4 C5       CPY   $C5
175A-   CC 8D A0    CPY   $A08D
175D-   CC C4 D8    CPY   $D8C4
1760-   A0 A3       LDY   #$A3
1762-   BE D3 D4    LDX   $D4D3,Y
1765-   D2 B1       CMP   ($B1)
1767-   B1 8D       LDA   ($8D),Y
1769-   A0 CC       LDY   #$CC
176B-   C4 D9       CPY   $D9
176D-   A0 A3       LDY   #$A3
176F-   BC D3 D4    LDY   $D4D3,X
1772-   D2 B1       CMP   ($B1)
1774-   B1 8D       LDA   ($8D),Y
1776-   AA          TAX
1777-   C2          ???
1778-   D2 CB       CMP   ($CB)
177A-   20 BB 20    JSR   $20BB
177D-   C6 C9       DEC   $C9
177F-   D2 D3       CMP   ($D3)
1781-   D4          ???
1782-   20 B5 20    JSR   $20B5
1785-   C4 C9       CPY   $C9
1787-   C7          ???
1788-   C9 D4       CMP   #$D4
178A-   D3          ???
178B-   20 C1 D2    JSR   $D2C1
178E-   C5 20       CMP   $20
1790-   C4 C5       CPY   $C5
1792-   CC C5 D4    CPY   $D4C5
1795-   C5 C4       CMP   $C4
1797-   AC 20 D2    LDY   $D220
179A-   C5 CD       CMP   $CD
179C-   C1 C9       CMP   ($C9,X)
179E-   CE C9 CE    DEC   $CEC9
17A1-   C7          ???
17A2-   20 D3 D4    JSR   $D4D3
17A5-   D2 C9       CMP   ($C9)
17A7-   CE C7 8D    DEC   $8DC7
17AA-   AA          TAX
17AB-   20 D3 D4    JSR   $D4D3
17AE-   CF          ???
17AF-   D2 C5       CMP   ($C5)
17B1-   C4 20       CPY   $20
17B3-   C1 CE       CMP   ($CE,X)
17B5-   C5 D7       CMP   $D7
17B7-   8D AA 8D    STA   $8DAA
17BA-   AA          TAX
17BB-   8D AA AA    STA   $AAAA
17BE-   20 D3 D5    JSR   $D5D3
17C1-   C2          ???
17C2-   C9 CE       CMP   #$CE
17C4-   D3          ???
17C5-   20 C9 CE    JSR   $CEC9
17C8-   D3          ???
17C9-   C5 D2       CMP   $D2
17CB-   D4          ???
17CC-   D3          ???
17CD-   20 C1 20    JSR   $20C1
17D0-   D3          ???
17D1-   CF          ???
17D2-   D5 D2       CMP   $D2,X
17D4-   C3          ???
17D5-   C5 20       CMP   $20
17D7-   D3          ???
17D8-   D4          ???
17D9-   D2 C9       CMP   ($C9)
17DB-   CE C7 8D    DEC   $8DC7
17DE-   AA          TAX
17DF-   AA          TAX
17E0-   20 C9 CE    JSR   $CEC9
17E3-   D4          ???
17E4-   CF          ???
17E5-   20 C1 CE    JSR   $CEC1
17E8-   CF          ???
17E9-   D4          ???
17EA-   C8          INY
17EB-   C5 D2       CMP   $D2
17ED-   20 C4 C5    JSR   $C5C4
17F0-   D3          ???
17F1-   D4          ???
17F2-   C9 CE       CMP   #$CE
17F4-   C1 D4       CMP   ($D4,X)
17F6-   C9 CF       CMP   #$CF
17F8-   CE 20 D3    DEC   $D320
17FB-   D4          ???
17FC-   D2 C9       CMP   ($C9)
17FE-   CE C7 AC    DEC   $ACC7
1801-   20 CD CF    JSR   $CFCD
1804-   D6 C9       DEC   $C9,X
1806-   CE C7 20    DEC   $20C7
1809-   D4          ???
180A-   C8          INY
180B-   C5 8D       CMP   $8D
180D-   AA          TAX
180E-   AA          TAX
180F-   20 C3 CF    JSR   $CFC3
1812-   CE D4 C5    DEC   $C5D4
1815-   CE D4 D3    DEC   $D3D4
1818-   20 C1 CE    JSR   $CEC1
181B-   C4 20       CPY   $20
181D-   C1 C4       CMP   ($C4,X)
181F-   CA          DEX
1820-   D5 D3       CMP   $D3,X
1822-   D4          ???
1823-   C9 CE       CMP   #$CE
1825-   C7          ???
1826-   20 CC C5    JSR   $C5CC
1829-   CE C7 D4    DEC   $D4C7
182C-   C8          INY
182D-   20 C1 D3    JSR   $D3C1
1830-   20 CE C5    JSR   $C5CE
1833-   C3          ???
1834-   C5 D3       CMP   $D3
1836-   D3          ???
1837-   C1 D2       CMP   ($D2,X)
1839-   D9 AE 8D    CMP   $8DAE,Y
183C-   AA          TAX
183D-   8D A0 CC    STA   $CCA0
1840-   C4 C1       CPY   $C1
1842-   A0 A3       LDY   #$A3
1844-   BE C9 CE    LDX   $CEC9,Y
1847-   D3          ???
1848-   B1 A0       LDA   ($A0),Y
184A-   BB          ???
184B-   20 C4 C5    JSR   $C5C4
184E-   D3          ???
184F-   D4          ???
1850-   C9 CE       CMP   #$CE
1852-   C1 D4       CMP   ($D4,X)
1854-   C9 CF       CMP   #$CF
1856-   CE 8D A0    DEC   $A08D
1859-   D0 C8       BNE   $1823
185B-   C1 8D       CMP   ($8D,X)
185D-   A0 CC       LDY   #$CC
185F-   C4 C1       CPY   $C1
1861-   A0 A3       LDY   #$A3
1863-   BC C9 CE    LDY   $CEC9,X
1866-   D3          ???
1867-   B1 8D       LDA   ($8D),Y
1869-   A0 D0       LDY   #$D0
186B-   C8          INY
186C-   C1 8D       CMP   ($8D,X)
186E-   A0 CC       LDY   #$CC
1870-   C4 C1       CPY   $C1
1872-   A0 A3       LDY   #$A3
1874-   B3          ???
1875-   A0 BB       LDY   #$BB
1877-   20 C9 CE    JSR   $CEC9
187A-   C4 C5       CPY   $C5
187C-   D8          CLD
187D-   8D A0 D0    STA   $D0A0
1880-   C8          INY
1881-   C1 8D       CMP   ($8D,X)
1883-   A0 CC       LDY   #$CC
1885-   C4 C1       CPY   $C1
1887-   A0 A3       LDY   #$A3
1889-   B2 B0       LDA   ($B0)
188B-   B0 A0       BCS   $182D
188D-   BB          ???
188E-   20 CD C1    JSR   $C1CD
1891-   D8          CLD
1892-   CC C5 CE    CPY   $CEC5
1895-   20 CF C6    JSR   $C6CF
1898-   20 CE C5    JSR   $C5CE
189B-   D7          ???
189C-   20 D3 D4    JSR   $D4D3
189F-   D2 C9       CMP   ($C9)
18A1-   CE C7 8D    DEC   $8DC7
18A4-   A0 D0       LDY   #$D0
18A6-   C8          INY
18A7-   C1 8D       CMP   ($8D,X)
18A9-   A0 CC       LDY   #$CC
18AB-   C4 C1       CPY   $C1
18AD-   A0 A3       LDY   #$A3
18AF-   BE C9 CE    LDX   $CEC9,Y
18B2-   D3          ???
18B3-   B2 A0       LDA   ($A0)
18B5-   BB          ???
18B6-   20 D3 CF    JSR   $CFD3
18B9-   D5 D2       CMP   $D2,X
18BB-   C3          ???
18BC-   C5 20       CMP   $20
18BE-   D3          ???
18BF-   D5 C2       CMP   $C2,X
18C1-   D3          ???
18C2-   D4          ???
18C3-   D2 C9       CMP   ($C9)
18C5-   CE C7 8D    DEC   $8DC7
18C8-   A0 D0       LDY   #$D0
18CA-   C8          INY
18CB-   C1 8D       CMP   ($8D,X)
18CD-   A0 CC       LDY   #$CC
18CF-   C4 C1       CPY   $C1
18D1-   A0 A3       LDY   #$A3
18D3-   BC C9 CE    LDY   $CEC9,X
18D6-   D3          ???
18D7-   B2 8D       LDA   ($8D)
18D9-   A0 D0       LDY   #$D0
18DB-   C8          INY
18DC-   C1 8D       CMP   ($8D,X)
18DE-   A0 CA       LDY   #$CA
18E0-   D3          ???
18E1-   D2 A0       CMP   ($A0)
18E3-   D3          ???
18E4-   D5 C2       CMP   $C2,X
18E6-   C9 CE       CMP   #$CE
18E8-   D3          ???
18E9-   8D A0 CC    STA   $CCA0
18EC-   C4 D9       CPY   $D9
18EE-   A0 A3       LDY   #$A3
18F0-   BC C9 CE    LDY   $CEC9,X
18F3-   D3          ???
18F4-   B1 8D       LDA   ($8D),Y
18F6-   A0 CC       LDY   #$CC
18F8-   C4 D8       CPY   $D8
18FA-   A0 A3       LDY   #$A3
18FC-   BE C9 CE    LDX   $CEC9,Y
18FF-   D3          ???
1900-   B1 8D       LDA   ($8D),Y
1902-   AA          TAX
1903-   C2          ???
1904-   D2 CB       CMP   ($CB)
1906-   20 BB 20    JSR   $20BB
1909-   CD C5 CD    CMP   $CDC5
190C-   CC CF C3    CPY   $C3CF
190F-   20 C9 CE    JSR   $CEC9
1912-   20 D8 D9    JSR   $D9D8
1915-   20 CE CF    JSR   $CFCE
1918-   D7          ???
1919-   20 C8 C1    JSR   $C1C8
191C-   D3          ???
191D-   20 C9 CE    JSR   $CEC9
1920-   D3          ???
1921-   B2 20       LDA   ($20)
1923-   C9 CE       CMP   #$CE
1925-   D3          ???
1926-   C5 D2       CMP   $D2
1928-   D4          ???
1929-   C5 C4       CMP   $C4
192B-   20 C9 CE    JSR   $CEC9
192E-   D4          ???
192F-   CF          ???
1930-   20 C9 CE    JSR   $CEC9
1933-   D3          ???
1934-   B1 8D       LDA   ($8D),Y
1936-   AA          TAX
1937-   20 C1 D4    JSR   $D4C1
193A-   20 CC CF    JSR   $CFCC
193D-   C3          ???
193E-   C1 D4       CMP   ($D4,X)
1940-   C9 CF       CMP   #$CF
1942-   CE 20 B3    DEC   $B320
1945-   8D AA 8D    STA   $8DAA
1948-   AA          TAX
1949-   AA          TAX
194A-   20 C4 C1    JSR   $C1C4
194D-   D4          ???
194E-   C1 8D       CMP   ($8D,X)
1950-   AA          TAX
1951-   8D C9 CE    STA   $CEC9
1954-   D3          ???
1955-   B1 A0       LDA   ($A0),Y
1957-   D3          ???
1958-   D4          ???
1959-   D2 A0       CMP   ($A0)
195B-   A2 D8       LDX   #$D8
195D-   D8          CLD
195E-   D8          CLD
195F-   D8          CLD
1960-   D8          CLD
1961-   D8          CLD
1962-   D8          CLD
1963-   D8          CLD
1964-   D8          CLD
1965-   A2 8D       LDX   #$8D
1967-   DA          PHX
1968-   DA          PHX
1969-   DA          PHX
196A-   A0 D3       LDY   #$D3
196C-   D4          ???
196D-   D2 A0       CMP   ($A0)
196F-   A2 B9       LDX   #$B9
1971-   B9 B9 B9    LDA   $B9B9,Y
1974-   B9 B9 B9    LDA   $B9B9,Y
1977-   B9 B9 A2    LDA   $A2B9,Y
197A-   8D C9 CE    STA   $CEC9
197D-   D3          ???
197E-   B2 A0       LDA   ($A0)
1980-   D3          ???
1981-   D4          ???
1982-   D2 A0       CMP   ($A0)
1984-   A2 B1       LDX   #$B1
1986-   B1 B1       LDA   ($B1),Y
1988-   B1 B1       LDA   ($B1),Y
198A-   B1 B1       LDA   ($B1),Y
198C-   B1 B1       LDA   ($B1),Y
198E-   A2 8D       LDX   #$8D
1990-   AA          TAX
1991-   8D AA 8D    STA   $8DAA
1994-   AA          TAX
1995-   8D AA 8D    STA   $8DAA
1998-   AA          TAX
1999-   AA          TAX
199A-   20 CC C9    JSR   $C9CC
199D-   D4          ???
199E-   D4          ???
199F-   CC C5 20    CPY   $20C5
19A2-   CC D5 CD    CPY   $CDD5
19A5-   D0 D3       BNE   $197A
19A7-   20 AD AD    JSR   $ADAD
19AA-   20 CD C9    JSR   $C9CD
19AD-   C4 AF       CPY   $AF
19AF-   CC CF D7    CPY   $D7CF
19B2-   20 CC C5    JSR   $C5CC
19B5-   D6 C5       DEC   $C5,X
19B7-   CC 8D AA    CPY   $AA8D
19BA-   8D AA 8D    STA   $8DAA
19BD-   A0 CA       LDY   #$CA
19BF-   CD D0 A0    CMP   $A0D0
19C2-   D2 C5       CMP   ($C5)
19C4-   C5 CE       CMP   $CE
19C6-   D4          ???
19C7-   D2 D9       CMP   ($D9)
19C9-   8D AA 8D    STA   $8DAA
19CC-   AA          TAX
19CD-   E0 E0       CPX   #$E0
19CF-   E0 E0       CPX   #$E0
19D1-   E0 E0       CPX   #$E0
19D3-   E0 E0       CPX   #$E0
19D5-   E0 E0       CPX   #$E0
19D7-   E0 E0       CPX   #$E0
19D9-   E0 E0       CPX   #$E0
19DB-   E0 E0       CPX   #$E0
19DD-   E0 E0       CPX   #$E0
19DF-   E0 E0       CPX   #$E0
19E1-   E0 E0       CPX   #$E0
19E3-   E0 E0       CPX   #$E0
19E5-   E0 E0       CPX   #$E0
19E7-   E0 E0       CPX   #$E0
19E9-   E0 E0       CPX   #$E0
19EB-   AA          TAX
19EC-   8D AA 20    STA   $20AA
19EF-   20 20 20    JSR   $2020
19F2-   20 20 20    JSR   $2020
19F5-   20 C2 CF    JSR   $CFC2
19F8-   D4          ???
19F9-   D4          ???
19FA-   CF          ???
19FB-   CD 20 C9    CMP   $C920
19FE-   CE C3 CC    DEC   $CCC3
1A01-   D5 C4       CMP   $C4,X
1A03-   C5 D3       CMP   $D3
1A05-   20 20 20    JSR   $2020
1A08-   20 20 20    JSR   $2020
1A0B-   20 AA 8D    JSR   $8DAA
1A0E-   AA          TAX
1A0F-   AC AC AC    LDY   $ACAC
1A12-   AC AC AC    LDY   $ACAC
1A15-   AC AC AC    LDY   $ACAC
1A18-   AC AC AC    LDY   $ACAC
1A1B-   AC AC AC    LDY   $ACAC
1A1E-   AC AC AC    LDY   $ACAC
1A21-   AC AC AC    LDY   $ACAC
1A24-   AC AC AC    LDY   $ACAC
1A27-   AC AC AC    LDY   $ACAC
1A2A-   AC AC AC    LDY   $ACAC
1A2D-   AA          TAX
1A2E-   8D AA 8D    STA   $8DAA
1A31-   AA          TAX
1A32-   8D AA AA    STA   $AAAA
1A35-   20 C2 CF    JSR   $CFC2
1A38-   D4          ???
1A39-   D4          ???
1A3A-   CF          ???
1A3B-   CD 20 C9    CMP   $C920
1A3E-   CE C3 CC    DEC   $CCC3
1A41-   D5 C4       CMP   $C4,X
1A43-   C5 D3       CMP   $D3
1A45-   8D AA 8D    STA   $8DAA
1A48-   A0 D0       LDY   #$D0
1A4A-   D5 D4       CMP   $D4,X
1A4C-   A0 D3       LDY   #$D3
1A4E-   D4          ???
1A4F-   D2 C9       CMP   ($C9)
1A51-   CE C7 D3    DEC   $D3C7
1A54-   AE CC C9    LDX   $C9CC
1A57-   C2          ???
1A58-   8D A0 D0    STA   $D0A0
1A5B-   D5 D4       CMP   $D4,X
1A5D-   A0 D3       LDY   #$D3
1A5F-   D5 C2       CMP   $C2,X
1A61-   D3          ???
1A62-   D4          ???
1A63-   D2 C9       CMP   ($C9)
1A65-   CE C7 D3    DEC   $D3C7
1A68-   AE CC C9    LDX   $C9CC
1A6B-   C2          ???
1A6C-   8D AA 8D    STA   $8DAA
